### ISSUE TITLE
Add latest Windows SDK

### ISSUE THREAD

**Issue by MehdiChinoune** [actions/runner-images#10012]
### Tool name

Windows SDK

### Tool license

Commercial

### Add or update?

- [ ] Add
- [X] Update

### Desired version

10.0.26100 

### Approximate size

3GB

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by MehdiChinoune** [comment]
https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.10.2
```
Add an optional installer component for the recently released Windows SDK version 10.0.26100.
```

**Comment by jxy-s** [comment]
Our build CI for our kernel driver is failing. Please also ensure the last WDK is also installed alongside the latest SDK. Thanks!

https://github.com/winsiderss/systeminformer/issues/2109

**Comment by jxy-s** [comment]
Why was this closed?

**Comment by Omar27HILMY** [comment]
من أجل مستقبل أفضل للعالم
