### ISSUE TITLE
Experiencing build crashes after upgrade to msvc toolset 14.40

### ISSUE THREAD

**Issue by jonaski** [actions/runner-images#10019]
### Description

Recently, toolset 14.3 is gone, and I've now set toolset 14.40, but I'm encountering several crashes, icu4c and boost builds crash.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I can't find "Set up job" anywhere.

### Is it regression?

It did not happen with toolset 14.3

### Expected behavior

Runs without crashes.

### Actual behavior

When building icu4c in Release, the ``genrb`` command crashes:

```
 NMAKE : fatal error U1077: '"D:\a\icu-msvc-test-build\icu-msvc-test-build\build\icu\source\extra\uconv\..\..\..\bin64\genrb" -s resources -d resources root.txt' : return code '0xc0000005' [D:\a\icu-msvc-test-build\icu-msvc-test-build\build\icu\source\extra\uconv\uconv.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'makedata.mak' exited with code 2. [D:\a\icu-msvc-test-build\icu-msvc-test-build\build\icu\source\extra\uconv\uconv.vcxproj]
```

See https://github.com/jonaski/icu-msvc-test-build/actions/runs/9430271887/job/25977616191

With boost, the ``b2`` command crashes in both release and debug:

```
Run b2.exe -a -q -j 4 -d1 --ignore-site-config --stagedir="stage" --layout="tagged" --without-mpi --without-python --prefix="c:/strawberry_msvc_x86_64_release" --exec-prefix="c:/strawberry_msvc_x86_64_release\bin" --libdir="c:/strawberry_msvc_x86_64_release\lib" --includedir="c:/strawberry_msvc_x86_64_release\include" toolset=msvc architecture=x86 link=shared runtime-link=shared threadapi=win32 threading=multi variant=release install
  
Error: Process completed with exit code -1073741819.
```

See https://github.com/jonaski/boost-msvc-test-build/actions/runs/9430284329/job/25977641576

These issues only happens in GitHub actions, on a Windows PC with update-to-date Visual Studio 2022 it does not occur.

### Repro steps

https://github.com/jonaski/icu-msvc-test-build/blob/master/.github/workflows/icu4c.yaml

**Comment by jonaski** [comment]
If protobuf is compiled in release, `protoc.exe` also crashes.

**Comment by shamil-mubarakshin** [comment]
Hey @jonaski,
Windows 2022 `20240603.1` release contained a number of issues. With https://github.com/actions/runner-images/pull/10014 and https://github.com/actions/runner-images/pull/10010 fixes both boosted and unboosted workflows completed successfully during my test runs.

We will start Image rollout this week

**Comment by jonaski** [comment]
Works now, thanks for the fast fix.
