### ISSUE TITLE
Add GCC 14 to macOS

### ISSUE THREAD

**Issue by McFlyboy** [actions/runner-images#10026]
### Tool name

GCC 14

### Tool license

Same as previous versions

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

GNU Compiler Collection

### URL for tool's homepage

https://gcc.gnu.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @McFlyboy!
Work in progress here: https://github.com/actions/runner-images/pull/10043. Should be done in the next couple of weeks.

**Comment by McFlyboy** [comment]
Nice, looking forward to it 🙂

**Comment by erik-bershel** [comment]
Hey @McFlyboy!
Sorry for such a delay. Changes merged. Should be rolled out next week.

**Comment by McFlyboy** [comment]
Sounds good! 🙂

**Comment by sarathrajsrinivasan** [comment]
Hey @McFlyboy,

The new image was deployed last week with GCC 14. 
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!
