### ISSUE TITLE
gfortran alias not available only on ubuntu 24.04

### ISSUE THREAD

**Issue by jmarrec** [actions/runner-images#10025]
### Description

Ubuntu 20.04 and 22.04 have `gfortran` available as an alias right off the bat. 24.04 does not not.

See this test workflow https://github.com/jmarrec/test-Github-Actions/actions/runs/9446090781/job/26015013360#step:2:26

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240604.1.0

### Is it regression?

Not really, but it's only present in 24.04

### Expected behavior

I would expect it to work like on Ubuntu 20.04, 22.04, `gfortran` alias is defined

### Actual behavior

`gfortran` alias is not available, only the `gfortran-12`  `gfortran-13`  `gfortran-14`

### Repro steps

See this test workflow that demonstrate the issue: https://github.com/jmarrec/test-Github-Actions/actions/runs/9446090781/job/26015013360#step:2:26

**Comment by vidyasagarnimmagaddi** [comment]
Hi @jmarrec  , gofortan has been installed as a part of depedency, we will test and run the same, install . Thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @jmarrec  , kindly fork the latest code from "main" and ry to reproduce the same.Thanks

**Comment by jmarrec** [comment]
Maybe it's not released yet, but it didn't work: https://github.com/jmarrec/test-Github-Actions/actions/runs/9446090781/job/26015013360

**Comment by vidyasagarnimmagaddi** [comment]
Hi @jmarrec  , Version-less Gfortran has been added for Ubuntu-24 ,and deployed.Kindly fork the latest code from "main" and ry to reproduce the same.Thanks

**Comment by jmarrec** [comment]
Confirmed: https://github.com/jmarrec/test-Github-Actions/actions/runs/9446090781/job/26484228106#step:2:24

**Comment by jmarrec** [comment]
Thank you.
