### ISSUE TITLE
Setuptools not working with latest ubuntu 22.04 image

### ISSUE THREAD

**Issue by quevon24** [actions/runner-images#10021]
### Description

Since May 29, a workflow to run tests has been failing due to not being able to find setuptools.

```
Traceback (most recent call last):
  File "/home/runner/work/juriscraper/juriscraper/setup.py", line 5, in <module>
    from setuptools import find_packages, setup
ModuleNotFoundError: No module named 'setuptools'
```

The setup.py used has not been modified other than to increase the version of the library and the last changes made to the workflow are from january of this year. That's why I consider that the problem is related to the latest version of the image.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20240603.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240603.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240603.1

and 

Image: ubuntu-22.04
Version: 20240526.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240526.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240526.1

### Is it regression?

version: 20240516.1.0 link: https://github.com/freelawproject/juriscraper/actions/runs/9229675213/job/25396345581

### Expected behavior

Be able to run tests (even if they fail)

### Actual behavior

When you get to the step of running the tests you get the error:

```
Traceback (most recent call last):
  File "/home/runner/work/juriscraper/juriscraper/setup.py", line 5, in <module>
    from setuptools import find_packages, setup
ModuleNotFoundError: No module named 'setuptools'
```

Previous step to set up python 3.12 was successful using setup-python@v5 action

I became aware of the problem on May 29.

The last workflow to run correctly was on May 24 with ubuntu 22.04 image version 20240516.1.0

### Repro steps

https://github.com/freelawproject/juriscraper/blob/main/.github/workflows/tests.yml
https://github.com/freelawproject/juriscraper/blob/main/setup.py

**Comment by hemanthmanga** [comment]
Hi @quevon24 We are looking into the issue, we will get back to you after investigating this issue, Thanks.

**Comment by quevon24** [comment]
I had to force the installation of setuptools directly in the step to install the dependencies to get it to work

```
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
```

**Comment by RaviAkshintala** [comment]
@quevon24 We are closing this issue for now, If you have any issues please to reach us.
