### ISSUE TITLE
MSVC: header format errors when using catch2 since toolset updates

### ISSUE THREAD

**Issue by gracicot** [actions/runner-images#10032]
### Description

Previously working jobs now fails. Error C2440 now happens in `<format>` at line 500. It seems to originate from a msvc template class named `std::_Fmt_codec<char,_Statically_Utf8>`

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

This task build correctly until I re-ran it after the update: https://github.com/gracicot/kangaru/actions/runs/9360750011/job/26031854394

All new tasks fails with the same error

### Is it regression?

20240514.3.0

### Expected behavior

The C++ header `<format>` should not contain errors when using supported catch2 from vcpkg.

### Actual behavior

```
Error: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\format(500): error C2440: 'initializing': cannot convert from 'const char16_t (*)[20]' to 'const char16_t (&)[20]'
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\format(500): note: Reason: cannot convert from 'const char16_t (*)[20]' to 'const char16_t [20]'
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\format(500): note: There are no conversions to array types, although there are conversions to references or pointers to arrays
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\format(500): note: the template instantiation context (the oldest one first) is
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\format(552): note: while compiling class template partial specialization 'std::_Fmt_codec<char,_Statically_Utf8>'
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\format(602): note: see reference to function template instantiation 'int std::_Unicode_width_estimate<& std::_Width_estimate_low_intervals>(const char32_t) noexcept' being compiled
```

No error seems to happen in my code, or originate from it according to the compiler.

### Repro steps

1. Create a C++ project using vcpkg as package manager and install catch2 in manifest mode
2. Create a simple test file:
```
#include <catch2/catch_test_macros.hpp>
TEST_CASE("Just a test", "[tag]") {}
```
3. Attempt compiling
4. Observe compilation error

**Comment by hemanthmanga** [comment]
@gracicot We are looking into the issue, we will get back to you after investigating this issue, Thanks.

**Comment by hemanthmanga** [comment]
@gracicot 
                   The image deployment has completed, could you please try to rerun the workflow.

`Image: windows-2022
  Version: 20240610.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240610.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F202406[10](https://github.com/hemanthmanga/kangaru/actions/runs/9514507006/job/26226851495#step:1:11).1`

If you have any issues, please reach out to us.

**Comment by Costallat** [comment]
I Have the same problem, if I don't force it to use MSVC 14.29 it uses an older version and the compiler complains that we need a newer one, so I forced it to use the 14.29.x, but it throws the same error from this ticket.

Tried to run today: https://github.com/mehah/otclient/actions/runs/9523710124/job/26314061584

**Comment by hemanthmanga** [comment]
@gracicot 
 
> In my `dev-5.x.y` branch where I use a modern setup, the problem is still happening. Here's a workflow run I tried today, with the 20240610.1.0 image: https://github.com/gracicot/kangaru/actions/runs/9360750011/job/26315233901#step:6:435

--- As of now 20240610.1.0 is the latest image version and we have ran the dev-5.x.y with workflow it got succeeded.

<img width="797" alt="image" src="https://github.com/actions/runner-images/assets/166606741/1f675133-72b0-421d-bf77-0129ac38c24f">

If you have any issues, Please reach to us, Thanks.

**Comment by gracicot** [comment]
@hemanthmanga I'm not sure how to say this. Your screenshot clearly shows my workflow in my master branch. You can see clearly that this workflow doesn't run visual studio 2022.

The windows 2019 and 2017 don't have that issue, since it's a problem with very recent MSVC version. Those images don't support C++20, and the problem only manifest in the format header, which is C++20 and up only.

My workflow still fails, I just re-ran it with the version you specified.

![Screenshot_20240620-082847](https://github.com/actions/runner-images/assets/2906673/16f7e265-a2df-43aa-9a4a-347527b81b1c)

As you can see, the name of the tasks are different from what you ran.

Here's a link to the still failing workflow. https://github.com/gracicot/kangaru/actions/runs/9360750011/job/26465999363#step:6:510

Would creating a minimal repo with only one branch and only one task help identifying the issue?

**Comment by Costallat** [comment]
Can someone reopen this ticket? It was not closed it was just tested on the wrong branch.

Tks

**Comment by hemanthmanga** [comment]
@Costallat,
we have changed as mentioned in the below and got passed with your branch dev-5.x.y, Please try with change.
```name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          useVcpkgToolchainFile: true
          vcpkgGitCommitId: '01f602195983451bc83e72f4214af2cbc495aa94'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
```

**Comment by Costallat** [comment]
Hi @hemanthmanga ,

Thanks for the information. I tested here and it worked. In fact we had to just update the vcpkgGitCommitId.

Thanks for the help!

**Comment by gracicot** [comment]
@hemanthmanga thank you! That was very informative. It fixed my pipeline too.
