### ISSUE TITLE
Cannot install package manager using corepack on node 16

### ISSUE THREAD

**Issue by SunsetTechuila** [actions/runner-images#10036]
### Description

No matter what node version you have chosen, the latest corepack will be used. The problem is that the latest corepack tries to use node's built-in fetch, which is not available in node 16

This is a [quite common](https://github.com/search?q=%22globalThis.fetch+is+not+a+function%22&type=pullrequests) problem

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-24.04 20240604.1.0

[failed workflow run](https://github.com/import-js/eslint-import-resolver-typescript/actions/runs/9327252035/job/25676880068)

### Is it regression?

ubuntu-22.04 20240324.2.0 was working fine - https://github.com/import-js/eslint-import-resolver-typescript/actions/runs/8502297529/job/23286295001

### Expected behavior

I expect the chosen package manager to be installed

### Actual behavior

```
Error: Error when performing the request to https://registry.npmjs.org/yarn/latest; 
  [cause]: TypeError: globalThis.fetch is not a function
      at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22756:33)
```

### Repro steps

1. Set the `packageManager` filed in the `package.json` file
2. Create a workflow containing these steps:

```yml
- uses: actions/checkout@v4
- run: corepack enable
- uses: actions/setup-node@v4
  with:
    node-version: 16
```
3. Run workflow

Or:

1. Fork [this repo](https://github.com/SunsetTechuila/setup-node16-issue)
2. Run the `Showcase` workflow

**Comment by kishorekumar-anchala** [comment]
Hi @SunsetTechuila , We're working on your issue , will provide the solution as soon as possible . Thank you for your support !

**Comment by kishorekumar-anchala** [comment]
Hi @SunsetTechuila ,

 i have seen your package.json file , there is some syntax issue . i made some significant changes in package.json file as below 

{
  "name": "core-pack",
  "version": "1.0.0",
  "packageManager": "corepack",
  "devDependencies": {
    "pnpm": "~8.14.2"
  }
}

as per your package.json file ,  you're using **pnpm** as dependency so we need to install that dependency . kindly look into below workflow as per your repro steps i build and got succeeded.

`      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install node-fetch for Corepack
        run: pnpm install node-fetch || npm install node-fetch

      - name: Setup globalThis.fetch for Corepack
        run: echo "globalThis.fetch = require('node-fetch');" >> $GITHUB_ENV

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}` 

Try to re-produce with above workaround , if any issue feel free to revert us .

**Comment by kishorekumar-anchala** [comment]
Hi @SunsetTechuila ,

  Hope you have tried above work around , please share your comments on your issue ?

**Comment by SunsetTechuila** [comment]
hello

> there is some syntax issue

no, my package.json is completely fine
the `name` and `version` fields are only necessary when publishing a package
about the `packageManager` field - https://nodejs.org/api/packages.html#packagemanager

> "packageManager": "corepack",

this is not a valid value, please check [this](https://nodejs.org/api/corepack.html#supported-package-managers) link and above

> you're using pnpm as dependency so we need to install that dependency

> run: npm install -g pnpm

you don't have to manually install package managers, that's the whole point of Corepack
see https://yarnpkg.com/getting-started/install for example

also there are better workarounds for this:

 - for yarn - https://github.com/import-js/eslint-import-resolver-typescript/pull/290/commits/88253951ca5932423ff0d2a51cdd90ae56b731e1
 
 - for pnpm - https://github.com/pnpm/action-setup


and in the end, all of this are only **workarounds**, which weren't necessary a few months ago

**Comment by kishorekumar-anchala** [comment]
Hi @SunsetTechuila ,

  Thank You for your quick reply on it , in my observation you're getting compatibility issue as node 16 will not support the latest corepack manager version, so i tried to install it manually .

  I hope your issue got resolved with above workarounds in your case, Please confirm from your end to proceed further step.

**Comment by SunsetTechuila** [comment]
> in my observation you're getting compatibility issue as node 16 will not support the latest corepack manager version

Yes, that's what I said in the description

> so i tried to install it manually .

So you should have seen that this can't be reproduced on the local machine because Node ships with the compatible version of Corepack. Download prebuilt binaries of `v16.20.2` from the [Node site](https://nodejs.org/en/download/prebuilt-binaries/current), unpack the downloaded archive, open the `lib/node_modules/corepack/dist/corepack.js` file and search for `var version = `. You will see that it is `0.17.0`, which is not the latest build

**Comment by SunsetTechuila** [comment]
@kishorekumar-anchala hello

can i ask you why have you closed the issue?

**Comment by SunsetTechuila** [comment]
As I said:

> This issue can't be reproduced on local machine because Node ships with the compatible version of Corepack

I expect the same from runners

**Comment by SunsetTechuila** [comment]
@mikhailkoliada hello, could you please take a look at this issue and reopen it?

sorry for tagging you, but this seems to be the only way to get this issue properly investigated and resolved

**Comment by SunsetTechuila** [comment]
update:

> no, my package.json is completely fine

no, it wasn't. didn't notice the leading `@` in the `packageManager` field, sorry

> the latest corepack will be used

this happens because I run `corepack enable` before setting up Node
