### ISSUE TITLE
Facing below error while creating VM from the image created 

### ISSUE THREAD

**Issue by sagarshitole01** [actions/runner-images#10054]
### Description

Facing below error while creating VM from the image created

"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."

I am using below script for creating image
Import-Module $(System.DefaultWorkingDirectory)/_actions_runner-images/helpers/GenerateResourcesAndImage.ps1
GenerateResourcesAndImage -SubscriptionId $(SubscriptionId) -ResourceGroupName "$(ResourceGroupName)" -ImageGenerationRepositoryRoot "$(System.DefaultWorkingDirectory)/_actions_runner-images" -ImageType $(ImageType) -AzureLocation "$(AzureLocation)" -AzureClientId $(AzureClientId) -AzureClientSecret $(AzureClientSecret) -AzureTenantId $(AzureTenantId) -Force

and below script to add image version under image definition
az sig image-version create --resource-group $(DestinationResourceGroupName) --gallery-name $(GalleryName) --gallery-image-definition $(GalleryImageDefinitionName) --gallery-image-version $(GalleryImageVersionName) --managed-image $(ManagedImage) --target-regions $(GalleryImageDefinitionLocation)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

[RELEASE_ARTIFACTS__ACTIONS_RUNNER-IMAGES_SOURCEVERSION] --> [25c57a1bbfaa5fbffc2e221b4015754e3815f7c5]

### Is it regression?

NA

### Expected behavior

VM is created without any errors attached

### Actual behavior

Facing error when trying to create VM in azure portal using the image generated "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."

### Repro steps

Step1:
Import-Module $(System.DefaultWorkingDirectory)/_actions_runner-images/helpers/GenerateResourcesAndImage.ps1
GenerateResourcesAndImage -SubscriptionId $(SubscriptionId) -ResourceGroupName "$(ResourceGroupName)" -ImageGenerationRepositoryRoot "$(System.DefaultWorkingDirectory)/_actions_runner-images" -ImageType $(ImageType) -AzureLocation "$(AzureLocation)" -AzureClientId $(AzureClientId) -AzureClientSecret $(AzureClientSecret) -AzureTenantId $(AzureTenantId) -Force

Step2:
az sig image-version create --resource-group $(DestinationResourceGroupName) --gallery-name $(GalleryName) --gallery-image-definition $(GalleryImageDefinitionName) --gallery-image-version $(GalleryImageVersionName) --managed-image $(ManagedImage) --target-regions $(GalleryImageDefinitionLocation)

Step3:
In azure portal I am trying to create a VM from the image generated in our compute image gallery

**Comment by hemanthmanga** [comment]
Hi @sagarshitole01,
  Could you please share the error logs to investigate further, it would be great if you could provide us.

**Comment by sagarshitole01** [comment]
{
  "code": "DeploymentFailed",
  "target": "/",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "target": "/",
      "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    }
  ]
}

**Comment by hemanthmanga** [comment]
@sagarshitole01 Please share packer file and complete log file to understand your issue.

**Comment by sagarshitole01** [comment]
[ReleaseLogs_1151 (1).zip](https://github.com/user-attachments/files/15838595/ReleaseLogs_1151.1.zip)

above are the image creation logs
and for VM creation I am not using any pipeline, I am creating it directly from portal manually, so no any log file is generating and I am not referring to any packer file

**Comment by hemanthmanga** [comment]
@sagarshitole01

https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#generated-machine-deployment

Kindly follow the instructions as mentioned above link.

**Comment by hemanthmanga** [comment]
@sagarshitole01 could you please provide your comments.

**Comment by hemanthmanga** [comment]
Hi @sagarshitole01 we try to follow-up for your response, hopefully issue got resolved with above [instructions](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#generated-machine-deployment). We are closing the issue as of now, Thanks.
