### ISSUE TITLE
Add Colima on macOS 13/14

### ISSUE THREAD

**Issue by devhaozi** [actions/runner-images#10079]
### Tool name

Colima

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Colima was previously available on macOS 11/12, but it’s not known why it’s missing from macOS 13 onwards.
Previous PR: https://github.com/actions/runner-images/pull/6285

### URL for tool's homepage

https://github.com/abiosoft/colima

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Previous PR: https://github.com/actions/runner-images/pull/6285

**Comment by erik-bershel** [comment]
Hi @devhaozi!
Thank you for the interest for our project. We are really appreciate it. Unfortunately, due to a number of reasons, we do not plan to return containerisation tools to macOS images for now. The decision may be changed later. In this case, we will try to release an announcement.
