### ISSUE TITLE
20240603.1.1 contains a buggy VS version

### ISSUE THREAD

**Issue by alexander-vitchevsky** [actions/runner-images#10074]
### Description

windows-2022 image version 20240603.1.1 contains an update of Visual Studio Enterprise 2022 into version 17.10.34928.147. This version has a bug described and discussed here:
https://developercommunity.visualstudio.com/t/Cannot-build-any-project-after-update-to/10664111

Bug was fixed by the next VS service release 17.10.2 (17.10.35004.147).

Is it possible to expedite update of the pipeline to have a fixed VS version?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

There is no public example, this is internal MS team build.

### Is it regression?

20240514.3.1

### Expected behavior

Visual Studio Enterprise 2022 version 17.10.35004.147 (17.10.2) should be installed.

### Actual behavior

Visual Studio Enterprise 2022 version 17.10.34928.147 is installed (17.10.0 or 17.10.1 - not sure).

### Repro steps

Try to build a C# project which uses .net sdk version 7.0.404.
Build solution will crash crash with errors similar to the following:

> Unhandled Exception: System.MissingMethodException: Method not found: ‘System.Collections.Generic.IEnumerator1<Microsoft.CodeAnalysis.NodeStateEntry1<System.ValueTuple2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable1.GetEnumerator()’. axshare_mvc.Core, Axure.Atlassian.Connect, Axure.Cloud.Mailer.Templates, Axure.Mailer.Templates C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets

**Comment by vidyasagarnimmagaddi** [comment]
Hi @alexander-vitchevsky , Visual Studio version is updated regularly to ensure the runners have the latest features, performance improvements, and security patches.Kindly wait for next vm roll out.Thanks

**Comment by vidyasagarnimmagaddi** [comment]
HI @alexander-vitchevsky  , the required Visual Studio version :17.10.35013.160 has been rolled out. Thanks.

**Comment by alexander-vitchevsky** [comment]
@vidyasagarnimmagaddi , thank you!
