### ISSUE TITLE
Ubuntu: speed up updating packages

### ISSUE THREAD

**Issue by chipitsine** [actions/runner-images#10089]
### Description

microsoft package adds feeds for three architectures

```
deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main
```

which adds some overhead for "apt-get update"

<img width="560" alt="image" src="https://github.com/actions/runner-images/assets/2217296/ddd7fa23-fe88-419b-bbe7-108bab5a172e">

for every single run it's about 0 or 1 seconds.

but I guess that Github can benefit from it at a scale.

the following patch should limit feed to current arch only

```diff
diff --git a/images/ubuntu/scripts/build/install-ms-repos.sh b/images/ubuntu/scripts/build/install-ms-repos.sh
index b4a56e8b..5b8280be 100644
--- a/images/ubuntu/scripts/build/install-ms-repos.sh
+++ b/images/ubuntu/scripts/build/install-ms-repos.sh
@@ -10,6 +10,12 @@ os_label=$(lsb_release -rs)
 wget https://packages.microsoft.com/config/ubuntu/$os_label/packages-microsoft-prod.deb
 dpkg -i packages-microsoft-prod.deb

+#
+# limit packages feed to current arch, speed up "apt-get update"
+#
+arch=$(dpkg --print-architecture)
+echo "APT::Architecture=${arch};" > /etc/apt/apt.conf.d/99arch
+
 # update
 apt-get install apt-transport-https ca-certificates curl software-properties-common
 apt-get update
```

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

any Ubuntu

### Is it regression?

nope

### Expected behavior

use only required feed

### Actual behavior

all feed ised

### Repro steps

run "apt-get update" from pipeline

**Comment by RaviAkshintala** [comment]
@chipitsine Thank you for bringing this issue to us. We are looking into this issue, we will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
Hi @chipitsine Thanks for your suggestion. Currently, we cannot perform architectural changes as it impacts other customers.Thanks closing this issue.
