### ISSUE TITLE
Github actions: macOS not running on Github hosted runner

### ISSUE THREAD

**Issue by m-chirodea** [actions/runner-images#10099]
### Description

Hello!

Since 11:00 AM (GMT+3) We are experiencing issues with any macOS image when running on github hosted runners. The action hangs on Waiting for a runner to pick up this job...

Switching to ubuntu works instantly so it seems that only macOS runners are affected.

i'll leave an example workflow that we use for macOS.

`name: Deploy
on:
    push: 
        branches:
            - staging
    workflow_dispatch:
        
jobs:
  upload_to_appcenter:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPSTORE_BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.APPSTORE_BUILD_CERTIFICATE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPSTORE_BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPSTORE_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-latest

### Is it regression?

no

### Expected behavior

The workflow run to start

### Actual behavior

The workflow run hangs on Waiting for a runner to pick up this job...

### Repro steps

1. Take the example provided
2. Create a workflow with it
3. Run the workflow
4. The workflow is stuck on  Waiting for a runner to pick up this job...

**Comment by erik-bershel** [comment]
Hey @m-chirodea!

Tried this:
```yml
name: Casual test
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-12, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Print
      run: |
        echo "!"
```

All green:
<img width="318" alt="Screenshot 2024-06-20 at 11 36 33" src="https://github.com/actions/runner-images/assets/110455084/759abfb1-56d8-45e7-a831-06ddfa673406">

Are you sure it is service related?

**Comment by erik-bershel** [comment]
@m-chirodea please, provide links for the runs in hanging state.

**Comment by m-chirodea** [comment]
Hi! Thank you for answering. Unfortunately I don't think I can share the links for the hanging run state, I can however provide an image.

![image](https://github.com/actions/runner-images/assets/115530882/874fcaa0-c5f9-4075-a138-9b75537f3af9)

And to answer the first question. I'll try with the example that you provided and see if I get any success

**Comment by m-chirodea** [comment]
As a small update.

Seems to be doing the same.

![image](https://github.com/actions/runner-images/assets/115530882/18abf1ff-1dcc-4b73-b9cd-a2c23461d599)

**Comment by erik-bershel** [comment]
@m-chirodea please contact [GitHub Support](https://support.github.com/contact/bug-report). It's not related to the images itself. I'll keep this issue for some time in case it's a massive outage.

**Comment by m-chirodea** [comment]
Update. last night the pipeline magically worked again. Not sure what the cause was, but no changes to the pipeline were done.

**Comment by Andrey1994** [comment]
We see the same, no jobs started. It was macos 11 which is removed now, I am switching to 12 in this PR https://github.com/brainflow-dev/brainflow/pull/732 and none of the macos jobs are picked by runners

**Comment by robertsLando** [comment]
Happening the same for me here: https://github.com/yao-pkg/pkg-fetch/actions/runs/10611372113/job/29410753919

**Comment by erik-bershel** [comment]
Hey @robertsLando!

There is no YAML label like `macos-13.0`, please update your workflow.

**Comment by robertsLando** [comment]
@erik-bershel Oh you are right! I was using `macos-11.0` before and I saw this behaviour so I found out it was removed and I bumped to 13 without checking the correct tag, thanks! 🙏🏼
