### ISSUE TITLE
Missing deprecation date for macos-11

### ISSUE THREAD

**Issue by h-vetinari** [actions/runner-images#10097]
### Breaking changes

When will macos-11 be removed?

### Target date

???

### The motivation for the changes

The image deprecation policy in the README says:
https://github.com/actions/runner-images/blob/cb3fcb62b9ccef6bfcf0ffd613e0baad92e5a9e8/README.md?plain=1#L137-L144

macos-11 got deprecated rather unceremoniously in https://github.com/actions/runner-images/commit/5418817c5fd272379f7d5a56c2e63a3d7f1a49d8 a couple month ago, yet I cannot find any deprecation issue or announcement for it (in contrast to [10.15](https://github.com/actions/runner-images/issues/5583) for example). The one [comment](https://github.com/actions/runner-images/issues/7900#issuecomment-1637980378) I found is from almost a year ago:

> > When will macOS 11 be deprecated?
> 
> @vpolikarpov-akvelon: According to [the policy](https://github.com/actions/runner-images/tree/main#image-deprecation-policy) image deprecation process will start when new version (it's 13 currently) is out of beta. I can't provide any exact dates though. Deprecation will be announced in advance.

### Possible impact

Know when macos-11 will be removed

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Upgrade

**Comment by erik-bershel** [comment]
Hey @h-vetinari!

All the available information was published here: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal
It will take about one more week to deprecate macOS-11 image completely.

**Comment by h-vetinari** [comment]
Thank you! I had opened the issue because the README had said:
> During this time there will be an Announcement pinned in the repo to remind users of the deprecation. 

In any case, that provides the requested information for me! Unless you think this issue could help other people looking for the same information, feel free to close it. :)

**Comment by The-Compiler** [comment]
What's the state of this? The [communicated removal date](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal) of June 28th has passed, but currently builds seem to [be stuck in queued state](https://github.com/qutebrowser/qutebrowser/actions/runs/9751234664) for hours (so I'm assuming the GitHub macOS 11 workers are shut down).

**Comment by Alexey-Ayupov** [comment]
Hi @h-vetinari, the macOS-11 image was deprecated. The issue will be closed.
