### ISSUE TITLE
Build is failing on windows-latest. Current image version: '20240610.1.0'

### ISSUE THREAD

**Issue by parupallihemanth** [actions/runner-images#10090]
### Description

Build is successful on windows-latest. Current image version: '20240514.3.0'

Below is the error. I'm using Azure artifacts to store VCPKG's and suddenly bootstrapping vcpkg is failing and I see only difference is the current image version: '20240610.1.0'. Please give me suggestions. Thanks!

![Screenshot_18-6-2024_15427_dev azure com](https://github.com/actions/runner-images/assets/39115525/5b00764f-a7df-425e-b377-8cb041c13c62)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image : windows-latest and version:20240610.1.0'

### Is it regression?

 windows-latest. Current image version: '20240514.3.0'

### Expected behavior

Bootsrtaping VCPKG should be successful
- task: CmdLine@2
      displayName: 'Bootstrap vcpkg'
      inputs:
        script: |
          vcpkg integrate install
          vcpkg install --triplet x86-windows

### Actual behavior

Throwing this error
![Screenshot_18-6-2024_15427_dev azure com](https://github.com/actions/runner-images/assets/39115525/ffddbbfa-6de5-449d-a127-48366f283ccb)

### Repro steps

n/a

**Comment by hemanthmanga** [comment]
@parupallihemanth Please provide us with repro steps for further investigation. It would be help us to investigate further.

**Comment by hemanthmanga** [comment]
@parupallihemanth Please provide your repro steps for us further investigation.

**Comment by hemanthmanga** [comment]
Hi @parupallihemanth we are closing this issue as of now due to insufficient of information, Thanks.

**Comment by parupallihemanth** [comment]
Hello @hemanthmanga, thank you. Downgraded the vcpkg version to 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e on the windows-latest image. Solved the issue.
