### ISSUE TITLE
DacFx/SqlPackage 162.3.563 known issue, patching with hotfix release

### ISSUE THREAD

**Issue by dzsquared** [actions/runner-images#10102]
### Description

We have a regression in DacFx/SqlPackage 162.3.563 (from an inadvertent change to our API surface area).  This version was picked up into Linux/Windows images created between June 6th and June 24th and impacts users doing SQL database deployments with SqlPackage and a deployment contributor.

For users with deployment contributors, the most direct workaround is to manually install the [previous version (162.2.111)](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver16#1622111-sqlpackage) of SqlPackage

A patch release of DacFx/SqlPackage is planned for Monday June 24th and will be included automatically in the next images generated.

https://github.com/microsoft/DacFx/issues/461

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Ubuntu and Windows images betwen June 6th and June 24th

### Is it regression?

yes

### Expected behavior

SqlPackage publish operations should be able to pick up deployment contributors to alter the deployment steps

### Actual behavior

SqlPackage publish operations throw an error if they are given a deployment contributor that the method signatures do not match

### Repro steps

1. Build a deployment contributor with Microsoft.SqlServer.DacFx versions 162.0 - 162.2
2. Use the deployment contributor with SqlPackage 162.3.563 publish action

**Comment by ijunaidm** [comment]
@dzsquared - Thank you for bringing this issue to us, we are investigating on this issue and we will update you on this issue after our findings.

**Comment by dzsquared** [comment]
hi @ijunaidm  - no investigation necessary - we know the issue on the DacFx side and are working on the hotifx. I was filing the issue placeholder here in case users come across it and land here.

**Comment by dzsquared** [comment]
The fix has been released in SqlPackage/DacFx 162.3.566 - which will be picked up automatically by the next deployments

https://learn.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver16#1623566-sqlpackage

**Comment by dzsquared** [comment]
With the 20240624 releases, the DacFx hotfix was picked up.  Those releases are now fully deployed!
https://github.com/actions/runner-images/releases/tag/win22%2F20240624.1
