### ISSUE TITLE
Biztalk Download URI returns 403

### ISSUE THREAD

**Issue by J-M-Reed** [actions/runner-images#10103]
### Description

When running the packer to create a Windows 2019 image the URL in https://github.com/actions/runner-images/blob/main/images/windows/scripts/build/Install-BizTalkBuildComponent.ps1 is set to https://aka.ms/BuildComponentSetup.EN which resolves to https://biztalkvault.blob.core.windows.net/devops-test/BuildComponentSetup.EN.zip 

This URL returns 403

![Screenshot 2024-06-21 085047](https://github.com/actions/runner-images/assets/128470211/8c2ed6f5-9e7e-4d3a-89b5-40a3cc261c52)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Latest code in Main

### Is it regression?

Yes

### Expected behavior

Biztalk install should be downloaded

### Actual behavior

The download fails

### Repro steps

Rin a build of the Windows 2019 image

**Comment by kishorekumar-anchala** [comment]
HI @J-M-Reed ,

   We are working on the issue , we have raise a request with official team for this issue . we will in post the latest update ASAP.

**Comment by kishorekumar-anchala** [comment]
HI @J-M-Reed ,

  Please try now , the [URL](https://aka.ms/BuildComponentSetup.EN) is working now , Please re run the pipeline.

**Comment by kishorekumar-anchala** [comment]
HI @J-M-Reed , The URL is up and working , Please re run the pipeline .

**Comment by J-M-Reed** [comment]
Thanks, this is confirmed to work
