### ISSUE TITLE
macOS-14 images missing iOS 18 Simulator

### ISSUE THREAD

**Issue by chadseippel** [actions/runner-images#10114]
### Description

While running Xcode builds against the macOS-14 pipelines, xcodebuild fails because it cannot find a scheme for iphoneos18.0. It looks like even though Xcode16.0 is installed, it's missing the iOS 18 Simulator. 

If I run this command before running xcodebuild, it succeeds - "sudo xcodebuild -downloadPlatform iOS". But it adds around ~10 minutes to the build time. Can the macOS14 images have the iOS 18 simulator pre-installed?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-14
Version: 20240616.1

### Is it regression?

No

### Expected behavior

iOS 18 Simulator does not need to be manually installed

### Actual behavior

iOS 18 Simulator is missing and xcodebuild fails in Xcode16.0

### Repro steps

Use macOS14 image with Xcode16 installed, run xcodebuild against iphoneos scheme

**Comment by erik-bershel** [comment]
Hey @chadseippel!

That's true. We didn't installed `Xcode 16.0 Beta 1` runtimes for `macOS-14` images, only for `macOS-14-arm64`. We are working on it right now. Will provide the additional information later. Sorry for inconsistency. 😞

**Comment by sarathrajsrinivasan** [comment]
Hi @chadseippel,

Thanks for the patience :) We have installed `Xcode 16.1 Beta` with runtimes and we are able to see `iphonesimulator18.0` and `iphoneos18.0` in the image. Please validate the same.

We are also working on including `Xcode 16.0 Beta 6`in our image and will post an update here once done.

**Comment by sarathrajsrinivasan** [comment]
Hi @chadseippel ,

We have installed the runtimes for all the Xcode versions. Please check.

**Comment by ZeeWanderer** [comment]
I am now encountering the same error for Xcode 16.4 on `macos-14` runner

**Comment by erik-bershel** [comment]
Hey @ZeeWanderer!
Should be fixed with the next image rollout (around two weeks to be deployed). Please open an additional issue if not. :bow:

**Comment by Voxar** [comment]
@erik-bershel Great to hear! 

Do we currently have any way of selecting the latest supported xcode and sdk version combo when asking for macos-latest?

I found that I could use https://github.com/maxim-lobanov/setup-xcode to pick the latest xcode version but that is unfortunately  what led me to this issue.

**Comment by erik-bershel** [comment]
Hey @Voxar!

> Do we currently have any way of selecting the latest supported xcode and sdk version combo when asking for macos-latest?

Nope. The image is a single entity, its state is described in the corresponding `readme`, and if you need to change something in it, you will have to do it yourself or using some tool. To install the required platform tools for your chosen Xcode, you can use the command below:
`xcodebuild -downloadPlatform <iOS|watchOS|tvOS|visionOS>  [-exportPath <destinationpath> -buildVersion <version>]`

The missing `iOS 18.2` is still waiting for a new image to be rolled out. You can use `macOS-15` where the required component is present. Or install it manually with the command I sent, but this will take more valuable time.

**Comment by riderx** [comment]
@erik-bershel I have this issue again, since few days:
https://github.com/Cap-go/capacitor-camera-preview/actions/runs/17079337709/job/48428908994
Unable to find a destination matching the provided destination specifier:
		{ generic:1, platform:iOS }
I tried with mac15 build as well and both fail

**Comment by riderx** [comment]
ok found https://github.com/actions/runner-images/issues/12758
