### ISSUE TITLE
[macOS] Default Xcode on macOS 14 Sonoma will be set to Xcode 15.4 on July, 22

### ISSUE THREAD

**Issue by erik-bershel** [actions/runner-images#10121]
### Breaking changes

Default Xcode will be changed to 15.4 on macOS 14 Sonoma

### Target date

The propagation will start on July, 22 and take 2-3 days

### The motivation for the changes

New minor Xcode releases for this version are no longer expected; the most popular among users is the latest available version of the IDE. We would like to provide images with the latest stable updates as default ones and removed old patch version as per our [guidelines](https://github.com/actions/runner-images#software-and-image-support).

### Possible impact

If you use the default Xcode version and your project is not compatible with Xcode 15.4 your build can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Please consider switching Xcode in runtime to the version that you need to build an app.
The following snippet can be used to switch Xcode:

```
sudo xcode-select -s "/Applications/Xcode_15.0.1.app"
```

The list of all available Xcode versions can be found in the [image documentation](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode)

**Comment by sarathrajsrinivasan** [comment]
Image rollout completed. 15.4 is now the default Xcode on macOS 14.
