### ISSUE TITLE
Remove [Windows Driver Kit]

### ISSUE THREAD

**Issue by middlemose** [actions/runner-images#10128]
### Tool name

Windows Driver Kit

### Tool license

Proprietary

### Add or update?

- [ ] Add
- [ ] Update

### Desired version

NA

### Brief description of tool

@neoadonis @prashantchahar @jakobl-msft

The recommended approach to utilizing the Windows Driver Kit (WDK) for building Windows drivers is now via [NuGet](https://www.nuget.org/packages/Microsoft.Windows.WDK.x64). The driver samples repo integrates the latest version of SDK and WDK directly in the CI pipeline instead of leveraging the preinstalled kits in the Windows runner image. 

It is our intention to move away from updating and maintaining the version of the Windows Driver Kit Visual Studio Extension (WDK vsix) and WDK itself in the runner images. As we move to releasing the WDK on a different cadence it is ideal that NuGet be the standard moving forward.

Please help us by removing the WDK and the WDK vsix installation as a build step and test when composing a new spin of Windows runner image.

Thank you kindly!

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by hemanthmanga** [comment]
Hi @middlemose the requirement to remove WDK versions is not possible as it can effects other customers, Thank you.

**Comment by middlemose** [comment]
Adding a few folks: 
@JakobL-MSFT
@NeoAdonais
@prashantchahar

**Comment by middlemose** [comment]
@hemanthmanga Thank you for your reply and concern about how it may or may not affect customers. That being said, our long-term goal is for projects to ingest the WDK through NuGet. To prevent version conflict and the maintenance of updating the WDK versions in the runner image we would like it removed. Is there a process we can go through to escalate this and come to an agreement on a possible long-term removal process?

**Comment by middlemose** [comment]
@hemanthmanga Following up here to see if there is more progress we can make on a long-term removal process?
