### ISSUE TITLE
Bring back R to Ubuntu 24.04

### ISSUE THREAD

**Issue by krlmlr** [actions/runner-images#10130]
### Tool name

R

### Tool license

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Approximate size

50 MB

### Brief description of tool

R was preinstalled by default but removed in Ubuntu 24.04 according to https://github.com/actions/runner-images/issues/9848#issue-2295881948 (reason: "Removed from the Ubuntu 24.04 image due to maintenance reasons."). Are there plans to bring it back?

There are well-maintained actions to install it, but installation takes substantial time, and this makes it difficult to use R as a tool to, e.g., define a build matrix.

### URL for tool's homepage

https://www.r-project.org/

### Provide a basic test case to validate the tool's functionality.

```bash
R --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by RaviAkshintala** [comment]
Hi @krlmlr Unfortunately, at the moment we are trying to make the images as light as possible and trying to avoid installing programs and packages that can be easily and quickly added at runtime. Thank you. Closing this issue.
