### ISSUE TITLE
Building Ubuntu 20.04 image fails on 'CLI.Tools.Tests.ps1' at 'Describing OC CLI'

### ISSUE THREAD

**Issue by robertreemsrivm** [actions/runner-images#10148]
### Description

Starting from 26-Jun-2024 our daily pipeline fails consistently to build the Ubuntu 20.04 image. We are building the image with the unmodified packer template. Is there anything I should do to fix this issue on our side?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

yes but the latest build is not applicable here

### Expected behavior

To pass the tests defined in 'CLI.Tools.Tests.ps1'

### Actual behavior

The build of the image fails with the following error:

```bash
azure-arm.build_image: Running tests from '/imagegeneration/tests/CLI.Tools.Tests.ps1'
azure-arm.build_image: Describing OC CLI
azure-arm.build_image:   [-] OC CLI 176ms (140ms|36ms)
azure-arm.build_image:    Command 'oc version' has finished with exit code
azure-arm.build_image:        oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by oc) oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by oc) oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by oc)
azure-arm.build_image:    at "oc version" | Should -ReturnZeroExitCode, /imagegeneration/tests/CLI.Tools.Tests.ps1:47
azure-arm.build_image:    at <ScriptBlock>, /imagegeneration/tests/CLI.Tools.Tests.ps1:47
azure-arm.build_image: Tests completed in 869ms
azure-arm.build_image: Tests Passed: 0, Failed: 1, Skipped: 0, Inconclusive: 0, NotRun: 9
``` 

### Repro steps

simply start the packer build using packer.

**Comment by kishorekumar-anchala** [comment]
Hi @robertreemsrivm ,

  We're working on it , we will let you know once we done with investigation .
  
  Thankyou !

**Comment by kishorekumar-anchala** [comment]
HI @robertreemsrivm ,

  We've fixed the issue , Could you please fork the latest code frim main branch and retry .

Thank you !

**Comment by robertreemsrivm** [comment]
Hi, our last build of the main branch worked. Thanks for your quick support!.
