### ISSUE TITLE
Add Parallels to macos-14

### ISSUE THREAD

**Issue by zadesai** [actions/runner-images#10143]
### Tool name

Parallels + Parallels SDK

### Tool license

Paid.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest Parallels - currently 19.4.0-54962 and Parallels SDK - currently 19.4.0-54962

### Brief description of tool

Add Parallels and enable its Kernel extension. This request is the same as https://github.com/actions/runner-images/issues/6105 for macos-12. This request is to add Parallels, enable the Kernel extension, Reboot and then remove Parallels.

Product URLS:
https://download.parallels.com/desktop/v19/19.4.0-54962/ParallelsDesktop-19.4.0-54962.dmg
https://download.parallels.com/desktop/v19/19.4.0-54962/ParallelsVirtualizationSDK-19.4.0-54962-mac.dmg

### URL for tool's homepage

https://www.parallels.com/

### Provide a basic test case to validate the tool's functionality.
dbName="/var/db/SystemPolicyConfiguration/KextPolicy"
dbQuery="SELECT * FROM kext_policy WHERE bundle_id LIKE 'com.parallels.kext.hypervisor';"
kext=$(sudo sqlite3 $dbName "$dbQuery")

if [[ -z $kext ]]; then
    echo "Parallels hypervisor not found"
else
    echo $kext
fi

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install --cask parallels
brew install --cask parallels-virtualization-sdk

(A reboot is needed afterwards)
```

### Tool installation time in runtime

around 1 minute

### Are you willing to submit a PR?

Yes

**Comment by sarathrajsrinivasan** [comment]
Hi @zadesai 

We are looking into it. Will keep you posted.

**Comment by prasanjitsahoo** [comment]
Hi @zadesai 

The current labels 'macos-latest' and 'macos-14' are Arm64 based machines and are built using a virtualization platform.
Due to the limitation of Apple's Virtualization Framework, Nested-virtualization is not supported in arm64 macOS runners.

The macos14 intel based machines are large runners (macos-latest-large or macos-14-large). 
Larger runners are only available for organizations and enterprises using the GitHub Team or GitHub Enterprise Cloud plans.

Could you please confirm the runner you are using? If it is arm64 runners we will not be able to add parallels as mentioned above.

Please find the limitations for the runners here : 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#limitations-for-arm64-macos-runners

**Comment by zadesai** [comment]
Hi @prasanjitsahoo,

Currently we use the macos12 runner. We do not need Arm64 based machines and would like to use the macos14 intel-based machine.

Thanks!

**Comment by dedavis6797** [comment]
Hey @prasanjitsahoo,

I wanted to follow up on whether this work item has an ETA for completion. For context, the Parallels VMs we produce get tens of thousands of downloads per month but are now currently blocked. We'd greatly appreciate any assistance in getting this issue resolved.

If I understand correctly, similar to #6105, we'd just need the same solution on MacOS 14 as what was done for MacOS 12.

Please let us know if there's any more information we can provide to help progress this topic.

**Comment by sarathrajsrinivasan** [comment]
Hi @dedavis6797 ,

We are working on it. Will keep you posted once our testing looks good.

**Comment by dedavis6797** [comment]
Thanks for the update @sarathrajsrinivasan, happy to see you have a draft PR started. 🙂

Do you have an estimate for how long the testing period typically takes?

**Comment by sarathrajsrinivasan** [comment]
Hi @zadesai @dedavis6797,

Thanks for the patience :) We are planning to roll out the changes to macOS-13 Intel machines first. Once the VM rollout is done and our initial validations are good I will update you on the same by next week and post which we will push the changes for macOS-14 Intel machines as well.

**Comment by sarathrajsrinivasan** [comment]
Hi @zadesai @dedavis6797 ,

The VM rollouts for macOS-14 Intel machines are done as well. Please validate the same for both macOS-13 Intel and macOS-14 Intel machines. 

```
    steps: 
    - name: Install Parallels
      shell: bash
      run: |
        brew install --cask parallels
        brew install --cask parallels-virtualization-sdk

    - name: Validate Kernel extension
      run: |
        MAX_RETRIES=2
        RETRY_COUNT=0
        until [ $RETRY_COUNT -ge $MAX_RETRIES ]
        do
          sudo kextload /Applications/Parallels\ Desktop.app/Contents/Library/Extensions/10.9/prl_hypervisor.kext && break
          RETRY_COUNT=$((RETRY_COUNT+1))
          echo "Waiting before retrying..."
          sleep 5
        done
```

**Comment by safmswork** [comment]
Hi @sarathrajsrinivasan , I've taken over the work that @zadesai was doing here.  I've switched our Azure Pipeline to use macos 14 but am getting an error that seems to indicate that the parallels kernel extension was not added to macos14. The error we see is:
==> parallels-iso.windows: Error starting VM: prlctl error: Failed to start the VM: To start "WinDev02", allow the Parallels Hypervisor System Extension and restart your Mac. Open the macOS System Preferences > Security & Privacy > General and click Allow. Or if you don’t want to change the macOS preferences, there’s another way – switch the hypervisor type to Apple in the virtual machine configuration. For more details, please see here (https://www.parallels.com/products/desktop/supportinfo/pdfm20_en_US_56521).

Can you please take a look?  This is the specific job where it failed if you are interested:
https://microsoft.visualstudio.com/Dart/_build/results?buildId=106674012&view=logs&j=c4dcfa9f-a076-539f-d132-893ba4adf683&t=2d0ae907-e25e-556e-8b57-ed90dcf28585

Thanks!
