### ISSUE TITLE
Github workflow fails for unknown reason

### ISSUE THREAD

**Issue by ggkiokas** [actions/runner-images#10140]
### Description

I created a dummy example of the [failed](https://github.com/Seafair/poseidon/actions/runs/9713801033/job/26811513218#step:36:1680) workflow

Probably it is related with [this](https://github.com/actions/runner-images/issues/6680) .
I added a new FE repo which needs yarn install && yarn start. This probably leads to lack of CPU  resources. Can you please check if this is the case. If indeed this is the problem, can you please let me know about the additional cost of the upgrade ?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/Seafair/poseidon/actions/runs/9713801033/job/26811513218#step:36:1680

### Is it regression?

yes

### Expected behavior

it should complete without issues

### Actual behavior

I got an error 
Error: The operation was canceled.
I also got in the past error:
error code 143

### Repro steps

Run the workflow of provided link

**Comment by vidyasagarnimmagaddi** [comment]
HI @ggkiokas  , could you please provide the link to the failed build for ubuntu-24 for further analysis.

**Comment by ggkiokas** [comment]
Here is the link:
https://github.com/Seafair/poseidon/actions/runs/9713801033/job/26811513218#step:36:1680

**Comment by vidyasagarnimmagaddi** [comment]
Hi @ggkiokas , coould you please confirm issue with ubuntu-22 or ubuntu-24, for the above provided link it is for ubuntu-22 .Further we cannot access the link to see the error, kindly provide the image name and post all the screenshots  , if available. thanks

**Comment by ggkiokas** [comment]
I am sorry for the confusion.
All the jobs of my workflow are:
- runs-on: ubuntu-latest
 
The ubuntu version as you can see in the screenshot is: 
- 22.04.4
![Screenshot from 2024-07-01 11-19-59](https://github.com/actions/runner-images/assets/115367874/aa8914b4-dcf5-4a17-bc21-f285ef6159e7)


Please lmk if you need more info

**Comment by vidyasagarnimmagaddi** [comment]
Hello @ggkiokas  ,We have checked the logs and found out that your run https://github.com/Seafair/poseidon/actions/runs/9713801033/job/26811513218 exhaust all available CPU and disk thruput resources on the runner.

In this case you have a several options:

1)Adjust your workflow to minimize CPU and disk write operation load
2)Switch to the [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners)
3)Set up your own [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners)

Hope , your issue will be resolved, Closing this issue. Thanks

**Comment by ggkiokas** [comment]
@vidyasagarnimmagaddi  Thanks for your response! Should I contact customer service for reviewing my options about large runners? I am not sure what is the current state of my runners and where I should aim to.

**Comment by ggkiokas** [comment]
Any news on that @vidyasagarnimmagaddi  ?
