### ISSUE TITLE
Add SQL Server to the windows-latest image

### ISSUE THREAD

**Issue by laumacirule** [actions/runner-images#10165]
### Tool name

SQL Server

### Tool license

MIT License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

I don't find SQL server as one of the Databases in the windows-latest description: https://github.com/actions/runner-images/blob/win22/20240421.1/images/windows/Windows2022-Readme.md#databases
Windows with SQL server is a popular combination; thus, we need to install the SQL server for almost all test runs on Windows.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
- name: Setup SQL Server
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine
          sa-password: **********
```

### Tool installation time in runtime

3m

**Comment by hemanthmanga** [comment]
@laumacirule Thank you for bringing this request/ issue, We will investigate and provide update.

**Comment by hemanthmanga** [comment]
Hi @laumacirule Unfortunately, at the moment we are trying to make the images as light as possible and trying to avoid installing programs and packages that can be easily and quickly added at runtime. Thank you, We are closing this issue.

**Comment by laumacirule** [comment]
Hi @hemanthmanga!
Thanks for the update! Though it is not what I was looking forward to :) 
I do disagree with the 'quickly added at runtime' - installing SQL Server takes 3-4min (as noted above), and that is not quick :(
