### ISSUE TITLE
Native x64 image fails on windows2022

### ISSUE THREAD

**Issue by AHuusom** [actions/runner-images#10168]
### Description

After having run for 4½ hours the packer build is failing on the step.

windows.azure-arm.windowsbuildserver: NGen: update x64 native images...
==> windows.azure-arm.windowsbuildserver: Update of x64 native images failed with exit code -1
==> windows.azure-arm.windowsbuildserver: At C:\Windows\Temp\script-66853b67-84a8-c439-98f8-c0d61450ffe0.ps1:15 char:5
==> windows.azure-arm.windowsbuildserver: +     throw "Update of x64 native images failed with 
exit code $LASTEXI ...
==> windows.azure-arm.windowsbuildserver: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> windows.azure-arm.windowsbuildserver:     + CategoryInfo          : OperationStopped: (Update of x64 n...th exit code -1:String) [], RuntimeException
==> windows.azure-arm.windowsbuildserver:     + FullyQualifiedErrorId : Update of x64 native images failed with exit code -1
==> windows.azure-arm.windowsbuildserver:

What is this step for, and why does it fail?

Can I remove it?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Both:
Image Version: 20240624.1.0
Image Version: 20240630.1.1

### Is it regression?

Don't know

### Expected behavior

That it completes, just as it does on windows2019

### Actual behavior

It fails, with a very none descriptive error.

### Repro steps

Just run it.

**Comment by RaviAkshintala** [comment]
@AHuusom Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
@AHuusom For this ,we're unable to produce your issue from our side , we hope you're trying with the latest code and expecting no changes made from your end . Could you please retry by forking latest code from main branch ?
Thank you !

**Comment by RaviAkshintala** [comment]
@AHuusom We have attempted to follow up regarding your response. We hope the issue has been resolved. We are now closing the issue. Thank you.
