### ISSUE TITLE
Update Ruby

### ISSUE THREAD

**Issue by rosslyn-beckynorville** [actions/runner-images#10164]
### Tool name

Ruby

### Tool license

Open source

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.2 (or 3.3)

### Brief description of tool

A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.

Note: there are problems with the version of Ruby on these images (3.1.6 and 3.0.7) due to Rexml and Stringscanner. New version of Rexml requires newer version of Ruby, https://bugs.ruby-lang.org/issues/20516

### URL for tool's homepage

https://www.ruby-lang.org/en/

### Provide a basic test case to validate the tool's functionality.

```bash
1. Open command prompt
2. Enter ruby -v
3. Press the Return key

Expected Result
The output should be: ruby 3.2.x
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

10 minutes

**Comment by vidyasagarnimmagaddi** [comment]
Hi @rosslyn-beckynorville  ,We will be  investigating on this issue and provide our possible outcome. thanks

**Comment by djaus2** [comment]
My desktop version of Ruby is V 3.2.2! V3.3.0 is available for Windows.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @djaus2  , the new image version has been rolled out, and version of 3.2 has been added. thanks.

**Comment by djaus2** [comment]
Great! I had noticed that yesterday.

David Jones (MVP)
________________________________
