### ISSUE TITLE
Update/Add alpine:3.19

### ISSUE THREAD

**Issue by Kielek** [actions/runner-images#10176]
### Tool name

alpine:3.19

### Tool license

https://pkgs.alpinelinux.org/packages

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.19

### URL for tool's homepage

https://alpinelinux.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, it will be automatically downloaded by the docker.
```

**Comment by Kielek** [comment]
Previous PR for 3.18.
I do not found information where to add it to beta version of 24.04. If not possible yet, it can be skipped.

**Comment by kishorekumar-anchala** [comment]
Hi @Kielek , the new version will be rolled out with the new deployment. Thankyou !

**Comment by RaviAkshintala** [comment]
@Kielek We have added 3.19 alpine version and it is available in main branch. Kindly fork the main branch and proceed.
We are closing this issue, Thank you.
