### ISSUE TITLE
SuperTuxKart fails to bundle libcurl.4.dylib despite the file being present since 20240701.9

### ISSUE THREAD

**Issue by tobbi** [actions/runner-images#10184]
### Description

I was notified that SuperTuxKart's dylibbundler signing stage fails since the latest image release of the MacOS image.

Here's the step:
```
      - name: Run dylibbundler and sign STK
        if: ${{ env.release_tag != '' }}
        env:
          developer_id: "Developer ID Application: ${{ secrets.MAC_DEVELOPER_NAME }} (${{ secrets.MAC_DEVELOPER_TEAM }})"
        run: |
          wget https://github.com/supertuxkart/dependencies/releases/download/preview/dependencies-macosx.tar.xz
          tar xf dependencies-macosx.tar.xz
          HOMEBREW_NO_AUTO_UPDATE=1 brew install dylibbundler
          lipo -create ./macosx-x86_64/supertuxkart.app/Contents/MacOS/supertuxkart ./macosx-arm64/supertuxkart.app/Contents/MacOS/supertuxkart -output ./macosx-arm64/supertuxkart.app/Contents/MacOS/supertuxkart
          chmod 755 ./macosx-arm64/supertuxkart.app/Contents/MacOS/supertuxkart
          dylibbundler -od -b -x ./macosx-arm64/supertuxkart.app/Contents/MacOS/supertuxkart -d ./macosx-arm64/supertuxkart.app/Contents/libs/ -p @executable_path/../libs/ -s ./dependencies-macosx/lib -ns
          # We use SDL_Vulkan_LoadLibrary for 10.9 compatibility, so otool -L supertuxkart has no libMoltenVK.dylib
          cp ./dependencies-macosx/lib/libMoltenVK.dylib ./macosx-arm64/supertuxkart.app/Contents/libs/
          cd ./macosx-arm64/supertuxkart.app/Contents/Resources/data
          wget https://github.com/supertuxkart/stk-assets-mobile/releases/download/git/stk-assets-full.zip
          unzip stk-assets-full.zip
          rm stk-assets-full.zip
          cd ../../../../..
          mv ./macosx-arm64/supertuxkart.app SuperTuxKart.app
          codesign --force --sign "$developer_id" SuperTuxKart.app/Contents/libs/*.dylib
          codesign --force --options=runtime --deep --sign "$developer_id" SuperTuxKart.app
```

The error is this one:
```
==> Pouring dylibbundler--1.0.5.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/dylibbundler/1.0.5: 6 files, 224.4KB

/!\ WARNING : Cannot resolve path 'libcurl.4.dylib'

/!\ WARNING : Library libcurl.4.dylib has an incomplete name (location unknown)
./dependencies-macosx/lib/libcurl.4.dylib was found. /!\ DYLIBBUNDLER MAY NOT CORRECTLY HANDLE THIS DEPENDENCY: Manually check the executable with 'otool -L'

* Collecting dependencies..............................FOUND libcurl.4.dylib in ./dependencies-macosx/lib/
/!\ WARNING : Cannot resolve path 'libcurl.4.dylib'

/!\ WARNING : can't collect rpaths for nonexistent file 'libcurl.4.dylib'
error: /Applications/Xcode_15.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: libcurl.4.dylib (No such file or directory)
Cannot find file libcurl.4.dylib to read its dependencies
........................
```

You can find a link to the workflow yml file here:
https://github.com/supertuxkart/stk-code/blob/master/.github/workflows/apple.yml

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20240701.9
https://github.com/supertuxkart/stk-code/actions/runs/9824097461/job/27122765552

### Is it regression?

20240625.2 https://github.com/supertuxkart/stk-code/actions/runs/9783915380/job/27013614216 

### Expected behavior

dylibbundler finds dependencies and properly bundles them with the executable

### Actual behavior

Despite dylibbundler finding the relevant file, it still doesn't bundle them.

I assume that this has something to do with the XCode version update to 1.5.0 as per https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240701.9

### Repro steps

Run the linked .yml workflow file and get to the packaging step.

**Comment by sarathrajsrinivasan** [comment]
Hi @tobbi,

We are looking into it. Will keep you posted.

**Comment by sarathrajsrinivasan** [comment]
Hi @tobbi ,

Based on our investigation, we could see: 

`1. Failed run on Image "20240701.9" is looking for libcurl.4.dylib in the same folder as executable and workflow fails during dylibbundler.`

`2. Successful run on Image "20240625.2" is looking for libcurl.4.dylib in @rpath/libcurl.4.8.0.dylib - A relative path, slightly different dylib and successful dylibbundler execution.`

At this point suspicion is that something has changed during the build jobs. It could either be the code or the tools in the image (maybe gcc?). You can try to add the below code before dylibbundler. This essentially modifies the rpath of libcurl.4.dylib to a relative path.
  
```
install_name_tool -change libcurl.4.dylib @rpath/libcurl.4.dylib ./macosx-arm64/supertuxkart.app/Contents/MacOS/supertuxkart
```

After adding the above workaround, we could see the bundling step passes successfully. We hope this resolves your issue. Thanks!

**Comment by tobbi** [comment]
Thank you very much! That fixed it.
