### ISSUE TITLE
Add Openshift CLI to MacOS images

### ISSUE THREAD

**Issue by Victoremepunto** [actions/runner-images#10186]
### Tool name

Openshift CLI (oc)

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

120Mb

### Brief description of tool

This is the [Openshift CLI](https://github.com/openshift/oc) tool, for interacting with Openshift clusters. 

### URL for tool's homepage

https://github.com/openshift/oc

### Provide a basic test case to validate the tool's functionality.

```bash
Describe "OC CLI" {
    It "OC CLI" {
        "oc version" | Should -ReturnZeroExitCode
    }
}
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
#!/bin/bash -e -o pipefail
################################################################################
##  File:  install-oc-cli.sh
##  Desc:  Install the OC CLI
################################################################################

# Source the helpers for use with the script

source ~/utils/utils.sh

echo "Installing Openshift CLI tools..."
brew_smart_install "openshift-cli"

invoke_tests "OC.Tests" "OC CLI"
```

### Tool installation time in runtime

under 2 minutes

### Are you willing to submit a PR?

I did, #10185 - it's in DRAFT because you currently don't accept PRs for MacOS images

**Comment by sarathrajsrinivasan** [comment]
Hi @Victoremepunto,

Unfortunately, at the moment we are trying to make the images as light as possible and trying to avoid installing programs and packages that can be easily and quickly added at runtime. Thank you, We are closing this issue.
