### ISSUE TITLE
macos-11 failures

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [actions/runner-images#10183]
### Description

Since a few days, all the macos-11 builds of my libproc-rs project have been failing (cancelled).

Is macos-11 still supported?
Any reason why they would be respectively cancelled?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/andrewdavidmackenzie/libproc-rs/actions/runs/9797846202

### Is it regression?

Yes, https://github.com/andrewdavidmackenzie/libproc-rs/actions/runs/9716309941

### Expected behavior

Build completes

### Actual behavior

Build cancelled

### Repro steps

Trigger a build using macos-11

**Comment by Skgland** [comment]
based on https://github.com/actions/runner-images/issues/9255 macos-11 was to be removed last quarter

**Comment by andrewdavidmackenzie** [comment]
So, should I understand it *has* been removed?

Was there an announcement?

**Comment by susmitamane** [comment]
@andrewdavidmackenzie mac-os 11 has been removed, you can check below documents for reference or an announcement:
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal.

closing this issue as mac-os 11 is deprecated, Please let us know if you face any further issues. Thanks.
