### ISSUE TITLE
Different Terraform versions on agents

### ISSUE THREAD

**Issue by williamwd** [actions/runner-images#10209]
### Description

I have a simple terraform azure pipeline that runs plan and apply in separate stages. The first stage generates a plan and saves it as an artifact for use whenever the following apply is approved. 
Running the apply **randomly** gives me this error:
```
╷
│ Error: Failed to read plan from plan file
│ 
│ Cannot read the plan from the given plan file: plan file was created by
│ Terraform 1.9.1, but this is 1.9.0; plan files cannot be transferred
│ between different Terraform versions.
╵
```
Both `plan` and `apply` use what it seems to be the same pool:
```
pool:
  vmImage: 'ubuntu-latest'
```
### Workaround
Currently, I have been able to work around that by setting a specific version of the image, rather than `latest`. This might be linked to 24.04, as using `ubuntu-22.04` works just fine.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

##[debug]agent.version=3.241.0
Image: ubuntu-latest

### Is it regression?

No

### Expected behavior

Have the same version of a tool in two runners that run within minutes apart.

### Actual behavior

Two runners have different `terraform` versions.

### Repro steps

Run the pipeline with multiple stages. Randomly, the second stage will have different versions of the same tool.

**Comment by RaviAkshintala** [comment]
@williamwd Could you please add the below snippet at first stage and try to reproduce the issue.
```
- task: UseTerraform@0
      inputs:
        command: 'version'
        terraformVersion: '1.9.0'

**Comment by williamwd** [comment]
> @williamwd Could you please add the below snippet at first stage and try to reproduce the issue.
> 
> ```
> - task: UseTerraform@0
>       inputs:
>         command: 'version'
>         terraformVersion: '1.9.0'
> ```

Fixing the version is a great idea, worked for all jobs using `latest` agent. 
Unfortunately, our directory does not have that specific extension, but I have used another that _should_ have the same effect.
```
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.9.0'
```

Is it a real bug/issue that some agents get spawned with different versions of the same tool? Nevertheless, my issue is now solved.

**Comment by RaviAkshintala** [comment]
@williamwd Thanks for confirming, We are closing this issue.
