### ISSUE TITLE
Ubuntu20.04: Getting Error for Nodejs

### ISSUE THREAD

**Issue by aqua-coding** [actions/runner-images#10206]
### Description

When I build images using packer, I am repeatedly getting the error for nodejs:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version 2.0.0 and above

### Is it regression?

no

### Expected behavior

the images should be generated without npm or jq error

### Actual behavior

It is showing me repeatedly the following error:
![image](https://github.com/actions/runner-images/assets/105941230/89fef887-0e1e-405e-8522-4b73aa95abc4)

and in the debugging step for home/packer I am getting the following output:

line 1: cd: /home/packer: No such file or directory

### Repro steps

release ubuntu20/20240603

**Comment by kishorekumar-anchala** [comment]
HI @aqua-coding ,

Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
@aqua-coding Can you please share your log file for further investigation.

**Comment by aqua-coding** [comment]
Sorry, because of company policy regarding sensitive data I am not allowed to share log file. Does it work, if you tell me what part of deployment log you require and I can share that part after making sure that there is no sensitive data in there? :)

**Comment by RaviAkshintala** [comment]
@aqua-coding Please share the deployment log related to npm error.

**Comment by aqua-coding** [comment]
Here is the log for npm error:

`
==> azure-arm.build_image: Provisioning with shell script: /home/vsts/work/1/s/packer/azure_devops_agent_basic/sources/scripts/build/install-sqlpackage.sh
==> azure-arm.build_image: Downloading package from https://aka.ms/sqlpackage-linux to /tmp/sqlpackage-linux...
==> azure-arm.build_image: Package downloaded in 1 seconds
    azure-arm.build_image: Pester v5.6.1
    azure-arm.build_image:
    azure-arm.build_image: Starting discovery in 1 files.
    azure-arm.build_image: Discovery found 77 tests in 1.07s.
    azure-arm.build_image: Filter 'FullName' set to ('SqlPackage').
    azure-arm.build_image: Filters selected 1 tests to run.
    azure-arm.build_image: Running tests.
    azure-arm.build_image:
    azure-arm.build_image: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_image: Describing SqlPackage
    azure-arm.build_image:   [+] sqlpackage 341ms (294ms|47ms)
    azure-arm.build_image: Tests completed in 1.82s
    azure-arm.build_image: Tests Passed: 1, Failed: 0, Skipped: 0, Inconclusive: 0, NotRun: 76
==> azure-arm.build_image: Provisioning with shell script: /home/vsts/work/1/s/packer/azure_devops_agent_basic/sources/scripts/build/install-nodejs.sh
    azure-arm.build_image:   installing : node-v18.20.3
    azure-arm.build_image:        mkdir : /usr/local/n/versions/node/18.20.3
    azure-arm.build_image:        fetch : https://nodejs.org/dist/v18.20.3/node-v18.20.3-linux-x64.tar.xz
    azure-arm.build_image:      copying : node/18.20.3
    azure-arm.build_image:    installed : v18.20.3 (with npm 10.7.0)
==> azure-arm.build_image: jq: error (at /imagegeneration/installers/toolset.json:251): Cannot iterate over null (null)
==> azure-arm.build_image: npm error code ENOENT
==> azure-arm.build_image: npm error syscall open
==> azure-arm.build_image: npm error path /home/packer/package.json
==> azure-arm.build_image: npm error errno -2
==> azure-arm.build_image: npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/packer/package.json'
==> azure-arm.build_image: npm error enoent This is related to npm not being able to find a file.
==> azure-arm.build_image: npm error enoent
==> azure-arm.build_image:
==> azure-arm.build_image: npm error A complete log of this run can be found in: /root/.npm/_logs/2024-debug-0.log
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_image: 
==> azure-arm.build_image: Deleting Virtual Machine deployment and its attatched resources...`

**Comment by aqua-coding** [comment]
this is my install-nodejs.sh script where nodejs is installed:

![image](https://github.com/actions/runner-images/assets/105941230/b0147c53-0b31-49bb-a024-1bd42b61bbb1)

This is my Node.Test.ps1 script:
`Describe "Node.js" {
    $binaries = @("node")
    $module_commands = if ((Get-ToolsetContent).node_modules) {
        (Get-ToolsetContent).node_modules | ForEach-Object { $_.command }
    }
    else {
        @()
    }
    $testCases = $binaries + $module_commands | ForEach-Object { @{NodeCommand = $_ } }

    It "<NodeCommand>" -TestCases $testCases {
        "$NodeCommand --version" | Should -ReturnZeroExitCode
    }

    It "Node.js version should correspond to the version in the toolset" {
        node --version | Should -BeLike "v$((Get-ToolsetContent).node.default).*"
    }
}`

My toolset.json script code block where modules are defined:
![image](https://github.com/actions/runner-images/assets/105941230/40169db0-bc01-4338-8178-c12b0344b90a)

and this is Toolset.Tests.ps1 script for tests:
`Describe "Toolset" {
    $tools = (Get-ToolsetContent).toolcache

    $toolsExecutables = @{
        Python = @{
            tools   = @("python", "bin/pip")
            command = "--version"
        }
        node   = @{
            tools   = @("bin/node", "bin/npm")
            command = "--version"
        }
        PyPy   = @{
            tools   = @("bin/python", "bin/pip")
            command = "--version"
        }
        go     = @{
            tools   = @("bin/go")
            command = "version"
        }
        Ruby   = @{
            tools   = @("bin/ruby")
            command = "--version"
        }
        CodeQL = @{
            tools   = @("codeql/codeql")
            command = "version"
        }
    }

    foreach ($tool in $tools) {
        $toolName = $tool.Name
        Context "$toolName" {
            $toolExecs = $toolsExecutables[$toolName]

            foreach ($version in $tool.versions) {
                # Add wildcard if missing
                if ($version.Split(".").Length -lt 3) {
                    $version += ".*"
                }

                $expectedVersionPath = Join-Path $env:AGENT_TOOLSDIRECTORY $toolName $version

                It "$version version folder exists" -TestCases @{ ExpectedVersionPath = $expectedVersionPath } {
                    $ExpectedVersionPath | Should -Exist
                }

                $foundVersion = Get-Item $expectedVersionPath `
                | Sort-Object -Property { [SemVer]$_.name } -Descending `
                | Select-Object -First 1
                $foundVersionPath = Join-Path $foundVersion $tool.arch

                if ($toolExecs) {
                    foreach ($executable in $toolExecs["tools"]) {
                        $executablePath = Join-Path $foundVersionPath $executable

                        It "Validate $executable" -TestCases @{ExecutablePath = $executablePath } {
                            $ExecutablePath | Should -Exist
                        }
                    }
                }
            }
        }
    }
}`

**Comment by RaviAkshintala** [comment]
@aqua-coding Could you please try with the latest version `20240708.1`.

**Comment by RaviAkshintala** [comment]
@aqua-coding Could you please try with the below steps.
```
Ensure dependencies described correctly on package.json
 npm init
 npm install and hit Enter.

Check issue still exists. and If issue not resolved, continue these methods.
type npm cache clean and hit Enter
type sudo npm install -g npm and hit Enter.
Retry npm install and hit Enter.

**Comment by aqua-coding** [comment]
Sorry. Please forgive me for asking this question. I am not able to find the package.json file and in the github repository I dont find it either. Could you please explain what am I missing here?

**Comment by aqua-coding** [comment]
so i have added `npm init` command to the install-nodejs.sh file and this is the output I am getting and the Node.Tests.ps1 tests are still failing:
![image](https://github.com/user-attachments/assets/23bf7958-28a2-45a0-9393-31a402889449)
![image](https://github.com/user-attachments/assets/952db80f-443a-4e0d-ab87-eee4cdc37360)

**Comment by RaviAkshintala** [comment]
@aqua-coding Could you please try with the below workaround, hope it will work.
````
Describe "Node.js" {
    $binaries = @("node")
    $module_commands = if ((Get-ToolsetContent).node_modules) {
        (Get-ToolsetContent).node_modules | ForEach-Object { $_.command }
    }
    else {
        @()
    }
    $testCases = $binaries + $module_commands | ForEach-Object { @{NodeCommand = $_} }

    It "<NodeCommand>" -TestCases $testCases {
        Write-Output "Running: $NodeCommand --version"
        "$NodeCommand --version" | Should -ReturnZeroExitCode
    }

    It "Node.js version should correspond to the version in the toolset" {
        $expectedVersion = "v$((Get-ToolsetContent).node.default).*"
        Write-Output "Expected Version: $expectedVersion"
        node --version | Should -BeLike $expectedVersion
    }
}

**Comment by aqua-coding** [comment]
with your work around the install-nodejs.sh file is running but I am still getting the jq error, which however is not stoping/breaking the pipeline:

![image](https://github.com/user-attachments/assets/d7e27527-0786-4552-bf40-46bad5ba3d34)

Also, unrelated to the npm error, I am getting this weird permission denied error which is very inconsistent to the files that it denotes to. Sometimes I get permission denied error for cleanup.sh, sometimes for install-sqlpackage.sh, sometime for install-postgresql.sh and sometimes for other files. Doy ou have any fix for this?:

![image](https://github.com/user-attachments/assets/e0af8d6f-f4bf-4172-a9e7-289ad150f9b1)
![image](https://github.com/user-attachments/assets/d752e633-85f6-4df0-be9c-686d3a9e2066)

**Comment by RaviAkshintala** [comment]
@aqua-coding Can you please share the cleanup.sh, install-sqlpackage.sh and install-postgresql.sh.

**Comment by aqua-coding** [comment]
This error is not consistent or specific just to these files and in the past I got the same 'Permission denied' error for other scripts as well.
Here are the scripts:

cleanups.sh:
`#!/bin/bash -e
################################################################################
##  File:  cleanup.sh
##  Desc:  Perform cleanup
################################################################################

# before cleanup
before=$(df / -Pm | awk 'NR==2{print $4}')

# clears out the local repository of retrieved package files
# It removes everything but the lock file from /var/cache/apt/archives/ and /var/cache/apt/archives/partial
apt-get clean
rm -rf /tmp/*
rm -rf /root/.cache

# journalctl
if command -v journalctl; then
    journalctl --rotate
    journalctl --vacuum-time=1s
fi

# delete all .gz and rotated file
find /var/log -type f -regex ".*\.gz$" -delete
find /var/log -type f -regex ".*\.[0-9]$" -delete

# wipe log files
find /var/log/ -type f -exec cp /dev/null {} \;

# delete symlink for tests running
rm -f /usr/local/bin/invoke_tests

# remove apt mock
prefix=/usr/local/bin
for tool in apt apt-get apt-key; do
    sudo rm -f $prefix/$tool
done

# after cleanup
after=$(df / -Pm | awk 'NR==2{print $4}')

# display size
echo "Before: $before MB"
echo "After : $after MB"
echo "Delta : $(($after - $before)) MB"
`

install-postgres.sh:
`#!/bin/bash -e
################################################################################
##  File:  install-postgresql.sh
##  Desc:  Install PostgreSQL
################################################################################

# Source the helpers
source $HELPER_SCRIPTS/os.sh
source $HELPER_SCRIPTS/install.sh

REPO_URL="https://apt.postgresql.org/pub/repos/apt/"

# Preparing repo for PostgreSQL
wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor >/usr/share/keyrings/postgresql.gpg
echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] $REPO_URL $(lsb_release -cs)-pgdg main" >/etc/apt/sources.list.d/pgdg.list

# Fetch PostgreSQL version to install from the toolset
toolset_version=$(get_toolset_value '.postgresql.version')

# Install PostgreSQL
echo "Install PostgreSQL"
apt update
apt-get install postgresql-$toolset_version

echo "Install libpq-dev"
apt-get install libpq-dev

# Disable postgresql.service
systemctl is-active --quiet postgresql.service && systemctl stop postgresql.service
systemctl disable postgresql.service

rm /etc/apt/sources.list.d/pgdg.list
rm /usr/share/keyrings/postgresql.gpg

echo "postgresql $REPO_URL" >>$HELPER_SCRIPTS/apt-sources.txt

invoke_tests "Databases" "PostgreSQL"
`

install-sqlpackage.sh:
`#!/bin/bash -e
################################################################################
##  File:  install-sqlpackage.sh
##  Desc:  Install SqlPackage CLI to DacFx (https://docs.microsoft.com/sql/tools/sqlpackage/sqlpackage-download#get-sqlpackage-net-core-for-linux)
################################################################################

# Source the helpers for use with the script
source $HELPER_SCRIPTS/install.sh
source $HELPER_SCRIPTS/os.sh

# Install libssl1.1 dependency
if is_ubuntu22; then
    focal_list=/etc/apt/sources.list.d/focal-security.list
    echo "deb http://archive.ubuntu.com/ubuntu/ focal-security main" | tee "${focal_list}"
    apt-get update --quiet

    apt-get install --no-install-recommends libssl1.1

    rm "${focal_list}"
    apt-get update --quiet
fi

# Install SqlPackage
archive_path=$(download_with_retry "https://aka.ms/sqlpackage-linux")
unzip -qq "$archive_path" -d /usr/local/sqlpackage
chmod +x /usr/local/sqlpackage/sqlpackage
ln -sf /usr/local/sqlpackage/sqlpackage /usr/local/bin

invoke_tests "Tools" "SqlPackage"
`

**Comment by RaviAkshintala** [comment]
@aqua-coding The permission denied error might be occurring because some of the commands in the script require superuser (root) privileges. You can try modifying the script to use sudo for commands that need permissions. Node js issue is resolved, We are closing this issue. Thank you.
