### ISSUE TITLE
MS Cert thumbprint is not matching the actaul file downloaded for Visual Studio 2022

### ISSUE THREAD

**Issue by 1edevops** [actions/runner-images#10204]
### Description

The packer build fails as the downloaded installer for the Visual Studio signing certificate is not match the current download file

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

The signing cert Thumbprint of MS was wrong on the actual downloaded installer

### Is it regression?

No

### Expected behavior

Install Visual Studio 2022 using Packer should be working

### Actual behavior

The packer build fails complaining that the downloaded installer not matching the Microsoft certificate thumprintthumbprint

### Repro steps

on file images/windows/toolsets/toolset-2022.json change thumbprint to something and the build will fail

**Comment by hemanthmanga** [comment]
@1edevops Thank you for bringing this issue to us, we are investigating on this issue and will update you on this issue after our findings.

**Comment by hemanthmanga** [comment]
Hi @1edevops it will taken care by  https://github.com/actions/runner-images/issues/10201,
closing this issue, Thank you.
