### ISSUE TITLE
Update/Add Microsoft.NETCore.App v6.0.32

### ISSUE THREAD

**Issue by acheungedc** [actions/runner-images#10218]
### Tool name

Microsoft.NETCore.App 

### Tool license

same as other versions of Microsoft.NETCore.App

### Add or update?

- [X] Add
- [ ] Update

### Desired version

6.0.32

### Brief description of tool

This is the latest version for .NET 6. We need this version as an interim solution before we upgrade to .NET 8 in the next 2 months. The current version we are using (6.0.26) is causing some vulnerability issues identified by a code scanning tool.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by hemanthmanga** [comment]
@acheungedc Thank you for bringing this issue to us, we are investigating on this issue and will update you on this issue after our findings.

**Comment by kishorekumar-anchala** [comment]
Hi @acheungedc ,

Microsoft.NETCore.App v6.0.32 is available now with the latest release (20240714.1) . Thank you !.

**Comment by acheungedc** [comment]
Thank you for your quick action on this ticket.
