### ISSUE TITLE
Update/Add flux

### ISSUE THREAD

**Issue by schdief** [actions/runner-images#10223]
### Tool name

flux

### Tool license

Apache-2.0 license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest supported version from AKS (https://learn.microsoft.com/de-de/azure/azure-arc/kubernetes/extensions-release#flux-gitops)

### Approximate size

19mb

### Brief description of tool

Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration (like Git repositories and OCI artifacts), and automating updates to configuration when there is new code to deploy.

Flux is supported as an AKS extension and needed to configure it and reconcile at will.

### URL for tool's homepage

https://github.com/fluxcd/flux2

### Provide a basic test case to validate the tool's functionality.

```bash
flux version --client
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
RUN curl -s -L -0 https://github.com/fluxcd/flux2/releases/download/v$FLUX_CD_VERSION/flux_${FLUX_CD_VERSION}_linux_amd64.tar.gz -o flux.tar.gz && tar xf flux.tar.gz -C /bin && rm flux.tar.gz
RUN flux completion bash > /etc/bash_completion.d/flux
```

### Tool installation time in runtime

2s

### Are you willing to submit a PR?

sure

**Comment by RaviAkshintala** [comment]
@schdief Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
@schdief It was decided not to add this tool to the Ubuntu images due to maintenance concerns and relatively short installation time. Please continue installing it in runtime. We are closing this issue. Thanks.
