### ISSUE TITLE
Podman 3.4.4 no longer compatible with Docker 26.1.3

### ISSUE THREAD

**Issue by strangiato** [actions/runner-images#10225]
### Description

It appears that Docker has updated the minimum API version that is required for clients connecting to the docker-daemon and attempting to use Podman to connect to the Docker Daemon fails with the following error message:

```
podman pull docker-daemon:hello-world:latest
  Error: initializing source docker-daemon:hello-world:latest: loading image from docker engine: Error response from daemon: {"message":"client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}
  ```
  
The older 3.4.4 Podman version is no longer compatible with the Docker version shipped in `ubuntu-24.04` runner image.

Podman should be updated to a newer version.

Additional discussion fo the issue can be found here:

https://github.com/containers/podman/issues/21419

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240708.1.0

Example failed action: https://github.com/strangiato/mlflow-server/actions/runs/9914484994/job/27393652593

### Is it regression?

20240514.2.0

### Expected behavior

Podman should be able to interact with the docker daemon and successfully pull an image from the local docker instance into the podman instance.

### Actual behavior

Podman fails with the following error:

```
{"message":"client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}
```

### Repro steps

Here is an example action to reproduce the issue:

```
name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test docker-daemon
        run: |
          echo "Docker Version"
          docker version
          docker pull alpine:latest
          echo
          echo "Podman Version"
          podman version
          podman pull docker-daemon:alpine:latest
```

**Comment by hemanthmanga** [comment]
@strangiato Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @strangiato- The current updated version for Podman is 4.9.3 in Ubuntu-24 image, Are you still facing an error by running the below command
`podman pull docker-daemon:hello-world:latest`

**Comment by hemanthmanga** [comment]
Hi @strangiato, As we haven’t received a response, we’ll assume your issue has been resolved and will proceed with closing this issue. Thank you!
