### ISSUE TITLE
Update/Add Microsoft.NETCore.App v8.0.7

### ISSUE THREAD

**Issue by JSdeJong** [actions/runner-images#10222]
### Tool name

Microsoft.NETCore.App

### Tool license

same as other versions of Microsoft.NETCore.App

### Add or update?

- [ ] Add
- [X] Update

### Desired version

8.0.7

### Brief description of tool

Security vulnerabilities in current version

### URL for tool's homepage

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by Prabhatkumar59** [comment]
@JSdeJong-- Thank you for bringing this issue to us. We are working on it and will update you:)

**Comment by Prabhatkumar59** [comment]
Hi @JSdeJong - We are pleased to announce that the new version of Microsoft.NETCore.App has been successfully updated. This update includes several enhancements and bug fixes to improve performance and stability. Thank you for your attention and cooperation. We are closing this.
Let me know if you need any further assistance!
