### ISSUE TITLE
I need additional storage space, the current storage space is a bit small.

### ISSUE THREAD

**Issue by siaimes** [actions/runner-images#10237]
### Description

https://github.com/siaimes/pytorch/actions

I installed some additional components based on the official pytorch image for my own use. There was no problem with pytorch 2.0 and before. Recently, I wanted to upgrade to 2.3.1 and found that the action failed to run. The error message was "no space left on device" when pulling the image.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/siaimes/pytorch/actions

### Is it regression?

No

### Expected behavior

Create and publish a Docker image #70: Commit [fca23d7](https://github.com/siaimes/pytorch/commit/fca23d71e42584e2a733485afbf6bb905262994f) pushed by [siaimes](https://github.com/siaimes)

### Actual behavior

buildx failed with: ERROR: failed to solve: failed to register layer: write /opt/conda/lib/libnppial.so.11.8.0.86: no space left on device

### Repro steps

https://github.com/siaimes/pytorch

**Comment by Prabhatkumar59** [comment]
Hi @siaimes-- Thank you for bringing this issue to us. We are looking into this issue and will update you shortly on this after investigating.

**Comment by siaimes** [comment]
@Prabhatkumar59 Thank you for your advice, the problem has been solved.

```
      - name: Clean runner
        run: |
          docker builder prune -f
          docker system prune -a -f
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
```
