### ISSUE TITLE
Biztalk download URI returns 403 on Windows 2019

### ISSUE THREAD

**Issue by mysteq** [actions/runner-images#10231]
### Description

Same issue as the recent #10103. Could you raise a request with the official team supporting that again?

When running the packer to create a Windows 2019 image the URL in https://github.com/actions/runner-images/blob/main/images/windows/scripts/build/Install-BizTalkBuildComponent.ps1 is set to https://aka.ms/BuildComponentSetup.EN which resolves to https://biztalkvault.blob.core.windows.net/devops-test/BuildComponentSetup.EN.zip

This URL returns 403

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest

### Is it regression?

yes

### Expected behavior

Build downloads file

### Actual behavior

Build fails to download

### Repro steps

Run a Windows 2019 build

**Comment by vidyasagarnimmagaddi** [comment]
Hi @mysteq , We have informed the official team and awaiting reply .Thanks

**Comment by vidyasagarnimmagaddi** [comment]
HI @mysteq  , the issue has been resolved, kindly try to build windows 2019 .
