### ISSUE TITLE
Update/Add Xcode 16 to Beta 4 (16A5211f)

### ISSUE THREAD

**Issue by liamnichols** [actions/runner-images#10242]
### Tool name

Xcode 16

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16A5211f (Beta 4)

### Brief description of tool

Xcode 16 Beta 4 (16A5211f) was launched on July 23rd, please consider updating the macOS 14 runner image from Beta 2

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Sure, but i'm not sure what I would need to do! Where does the sha256 come from?

**Comment by sureshe456** [comment]
We are looking into the issue.Will keep you posted.

**Comment by liamnichols** [comment]
I just updated the ticket for beta 4 (released just a few hours ago).

Just saw the linked PR for beta 3 though. Thanks! Sorry about the timing 😬

**Comment by sarathrajsrinivasan** [comment]
Image rollout completed. Xcode 16 Beta 4 added to macOS14.
