### ISSUE TITLE
.NET patches missing in the image

### ISSUE THREAD

**Issue by angaaruriakhil** [actions/runner-images#10307]
Hi, 

Thanks for the work on these images. We use the code in this repository monthly to build images for use with VMSS. I'd like to get some clarity on the .NET patches installed on the Windows images. 

From the readme, it says, for .NET Core: _“2 latest LTS versions and 1 latest version. For each feature version only latest patch is installed”._

Our Qualys scans are flagging up that the following patches are missing:

- Microsoft .NET Core Security Update for January 2024
- Microsoft .NET Security Update for September 2022
- Microsoft .NET Core and ASP.NET Core Security Update for November 2023
- Microsoft .NET Core and ASP.NET Core Security Update for February 2024
- Microsoft .NET Security Update for July 2023
- Microsoft .NET Security Update for June 2023
- Microsoft .NET Security Update for April 2023
- Microsoft .NET Security Update for February 2023
- Microsoft .NET Security Update for December 2022
- Microsoft .NET (NuGet Client) Security Update for October 2022
- Microsoft .NET Framework Update for April 2024
- Microsoft .NET Security Update for April 2024
- Microsoft .NET Security Update for March 2024
- Microsoft .NET Security Update for October 2023
- Microsoft .NET Security Update for September 2023
- Microsoft .NET Security Update for August 2023
- Microsoft .NET Security Update for January 2023
- Microsoft .NET Security Update for August 2022
- Microsoft .NET Security Update for June 2022

From the code, it appears that the latest patches should be getting installed which should cover these, particularly this should be covered in the Install-WindowsUpdate.ps1 script. 

Are there any plans to include these patches that are missing in the image? Thanks.

_Originally posted by @angaaruriakhil in https://github.com/actions/runner-images/discussions/10087_

**Comment by kishorekumar-anchala** [comment]
Thank you for bringing this issue to us. We are looking into this issue and will update you shortly on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
Hi @angaaruriakhil ,

  Could you please try to build now and share us the comment.
  latest version : 20240721.1.0

**Comment by angaaruriakhil** [comment]
> Thank you for addressing this.
> 
> We need to do a rebuild, we don't use the MS-hosted agents but build our own VMSS with this repo. 
> 
> We are also currently internally transitioning our vulnerability process. We can't run a scan at the moment unfortunately but should be able to in the coming weeks. 
> 
> Could you kindly summarise the changes that have been made? I can't see anything in the commits. But I may be missing something..

Thanks!

**Comment by kishorekumar-anchala** [comment]
> We need to do a rebuild, we don't use the MS-hosted agents but build our own VMSS with this repo.
>  sorry , i didn't observe this .  it is working with hosted agents.

**Comment by kishorekumar-anchala** [comment]
Hi @angaaruriakhil ,

this is issue not related to hosted agents as mentioned , we are closing the issue and we will provide further investigation update on discussion forum .
    
    https://github.com/actions/runner-images/discussions/10087
