### ISSUE TITLE
Cache eviction feature for actions/setup-node

### ISSUE THREAD

**Issue by karlhorky** [actions/runner-images#10311]
To be clear, this is not a tool request - it's a feature request for `runner-images`, requested by @aparnajyothi-y of the `actions/setup-node` team

### Tool name

actions/setup-node

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

--

### Brief description of tool

Cache eviction feature for @aparnajyothi-y and the rest of the `actions/setup-node` team, as requested here:

- https://github.com/actions/setup-node/issues/940#issuecomment-2238987460

This will enable purging of old cached LTS versions to avoid the problem that `node-version: 'lts/*'` installs an outdated version, as described in the issue:

- https://github.com/actions/setup-node/issues/940

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by hemanthmanga** [comment]
Hi @karlhorky As the runner images team, we believe cache eviction should be handled through tasks, not the runner itself. 
Please look into the [comment](https://github.com/actions/setup-node/issues/940#issuecomment-2239209457)

**Comment by karlhorky** [comment]
Ok, that's unfortunate for users.

This common `lts/*` config for `actions/setup-node` is broken (does not retrieve latest LTS version, even days after release), and if `actions/runner-images` won't build anything to fix it, it will stay broken:

```yaml
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
```

Source: https://github.com/actions/setup-node/issues/940#issuecomment-2029638604

**Comment by karlhorky** [comment]
Opened a new followup issue, since users will not find this configuration footgun, and it will lead to their CI failing and potentially being insecure:

- #1207
