### ISSUE TITLE
Update Android LTS NDK to 27

### ISSUE THREAD

**Issue by finagolfin** [actions/runner-images#10314]
### Tool name

Android NDK

### Tool license

Custom

### Add or update?

- [ ] Add
- [X] Update

### Desired version

27

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Prabhatkumar59** [comment]
Hi @finagolfin--Thank you for bringing this issue to us. We are looking into this issue and will update you shortly on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
Hi @finagolfin ,

 We added new NDK Version , kindly try with it latest version . Thank you !

**Comment by finagolfin** [comment]
I'm now using this, works well. 😃

**Comment by kishorekumar-anchala** [comment]
Thanks for the confirmation @finagolfin

**Comment by wang-bin** [comment]
macos is missing
