### ISSUE TITLE
Update Microsoft Hosted Agent is not taking stable version of chromedriver which is 126.0.6478.182 instead its taking 126.0.6478.126 which is causing session problems while executing selenium cases

### ISSUE THREAD

**Issue by HrishikeshRangdale-gep** [actions/runner-images#10320]
### Tool name

ChromeDriver

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

126.0.6478.182

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by RaviAkshintala** [comment]
@HrishikeshRangdale-gep Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
@HrishikeshRangdale-gep Chrome Driver 126.0.6478.182 is available now with the latest release (20240721.1) . Thank you !.
