### ISSUE TITLE
Azure DevOps Self-hosted VMSS not working using correct Version of Microsoft.Azure.DevOps.Pipelines.Agent extension with Ubuntu 24.04

### ISSUE THREAD

**Issue by markDmullins** [actions/runner-images#10335]
### Description

When deploying the Ubuntu 24.04 image within an Azure virtual machine scale set for a VMSS pool of Azure DevOps, the [Microsoft.Azure.DevOps.Pipelines.Agent](https://github.com/microsoft/vsts-azurevm-extension) extension is added, using version 1.2.3 instead of the current latest version 1.2.5.2

1.2.3 of the script has a known issue with Ubuntu24.04 [10122 -( Microsoft.Azure.DevOps.Pipelines.Agent)](https://github.com/actions/runner-images/issues/10122) 

![image](https://github.com/user-attachments/assets/f4a1c56d-18f0-43a7-b240-6159d2c3e534)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

no

### Expected behavior

Create an azure Virtual Machine Scale set Agent Pool in Azure DevOps and it uses a version of the [Microsoft.Azure.DevOps.Pipelines.Agent](https://github.com/microsoft/vsts-azurevm-extension) extension that is compatible with Ubuntu 24.04 (>1.25.2)

### Actual behavior

Azure Virtual Machine Scale set is being configured with version 1.23 of [Microsoft.Azure.DevOps.Pipelines.Agent](https://github.com/microsoft/vsts-azurevm-extension)

### Repro steps

Create a self-hosted Azure DevOps pool, of type Azure virtual machine scale set, connected to your VMSS.

**Comment by Prabhatkumar59** [comment]
Hi @markDmullins - Thank you for bringing this issue to us. We are looking into this issue and will update you shortly on this issue after investigating.
