### ISSUE TITLE
Permission Denied error for build shell scripts

### ISSUE THREAD

**Issue by aqua-coding** [actions/runner-images#10333]
### Description

I am getting this weird permission denied error which is very inconsistent to the files that it denotes to. Sometimes I get permission denied error for cleanup.sh, sometimes for install-sqlpackage.sh, sometime for install-postgresql.sh and sometimes for other files.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version 2.2.4

### Is it regression?

No

### Expected behavior

the images should be generated without permission denied error

### Actual behavior

I am using `sudo packer build` cmd to execute with retryCountOnTaskFailure: 3 and sometimes in different files are getting the same permission denied error which is breaking the pipeline

the errors:
![image](https://github.com/user-attachments/assets/1f8d27f6-a159-42c0-949b-de1728fc8c14)
![image](https://github.com/user-attachments/assets/bea11026-93c2-4365-961e-798fe9a08c94)
![image](https://github.com/user-attachments/assets/6d0102ea-a94e-40ae-8583-1595e2ad4c10)

and this error is weird because in one deployment it will show permission denied for install-erlang.sh and in next pipeline run the script install-erlang.sh will run without any problem but then I will get the same error with install-javatools.sh or some other script.

### Repro steps

release ubuntu20/20240708.1.

**Comment by RaviAkshintala** [comment]
@aqua-coding Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
@aqua-coding Could you please try with the latest version `20240721.1 `

**Comment by aqua-coding** [comment]
I updated to the latest version `20240721.1` and set the retryCountOnTaskFailure: 3 but still got permission denied error, this time with install-java-tools.sh
![image](https://github.com/user-attachments/assets/5558b1b2-ad8b-4626-a072-148b28048ec4)

Also, in one of the retry, i got the following error with the script Generate-SoftwareReport.ps1, do you have any fix for this?:
![image](https://github.com/user-attachments/assets/3cc07172-d33b-4706-8e35-4694596dea8b)

**Comment by aqua-coding** [comment]
hello, just asking for an update, were you able to find a fix for the permission denied error?

**Comment by RaviAkshintala** [comment]
@aqua-coding The permission denied error might be occurring because some of the commands in the script require superuser (root) privileges. You can try modifying the script to use sudo for commands that need permissions. We tried checking the same, we haven't faced any permission errors and kindly check the latest rolled out image.

**Comment by RaviAkshintala** [comment]
Hi @aqua-coding We have been following up with the issue, as there is no response from you We are closing this issue.Thank you.
