### ISSUE TITLE
TestScript passed on Server, failing on GitHub

### ISSUE THREAD

**Issue by bandavv** [actions/runner-images#10347]
### Description

Hello, 
I'm executing ALM test scripts using Github actions, it is failing. When I run same test script on the remote server, the script executed successfully. I'm run script using self hosted runner using Github actions. Below is the error. I reinstalled ALM on server and run the script from github getting same error.

Check that your ALM client is installed properly\n Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)) \n   at Mercury.TD.Client.Ota.QC9.ITestSetFolder.FindTestSets(String Pattern, Boolean MatchCase, String Filter)
   at HpToolsLauncher.AlmTestSetsRunner.GetAllTestSetsFromDirTree(ITestSetFolder tsFolder)

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

no

### Is it regression?

no

### Expected behavior

not applicable

### Actual behavior

not applicable

### Repro steps

step1 : NA
Step 2 : NA

**Comment by bandavv** [comment]
Hello Hemanth, Any update on issue

**Comment by hemanthmanga** [comment]
Hi @bandavv 
GitHub Actions runners, which are used to run workflows and CI/CD pipelines, do not come with built-in support for ALM clients. If you need to use an ALM client, you'll need to add steps to your GitHub Actions workflow to download, install, and configure the client. This means you'll set up the ALM client as part of your workflow configuration, allowing you to integrate its functionality into your CI/CD processes.
Hence we are closing the issue, Thank you.

**Comment by bandavv** [comment]
In the last two years it was working with selfhosted runner from past three months it was not working. I installed ALM client on server. Idk why it's not to working now.
