### ISSUE TITLE
[All OSes] Android NDK versions <=25 will be removed from images on August 19

### ISSUE THREAD

**Issue by vidyasagarnimmagaddi** [actions/runner-images#10342]
### Breaking changes

Toolcache Android NDK versions <=25 will be removed from images on August 19

### Target date

Image deployment is starting on July 29 and will take 3-4 days.

### The motivation for the changes

All versions <= 25 were EOLed more than a 10 months [ago](https://github.com/android/ndk/wiki/Unsupported-Downloads). We would like to remove long-term unsupported versions.

### Possible impact

If your workflows / pipeline depend on Android NDK versions <=25 , they might become broken

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Nothing is required.

**Comment by kishorekumar-anchala** [comment]
New version available with [PR](https://github.com/actions/runner-images/pull/10343)

**Comment by vidyasagarnimmagaddi** [comment]
Hi , The changes has been made under  [PR](https://github.com/actions/runner-images/pull/10343) , the default ndk version would be "27" , thanks , closing the announcement.

**Comment by mcneilrp1** [comment]
s8

**Comment by kishorekumar-anchala** [comment]
The changes have been made under this [PR](https://github.com/actions/runner-images/pull/10343)
