### ISSUE TITLE
Update Mingw64 in windows-2019 image

### ISSUE THREAD

**Issue by tobil4sk** [actions/runner-images#10352]
### Tool name

MinGW64

### Tool license

GNU

### Add or update?

- [ ] Add
- [X] Update

### Desired version

8.5.0

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes: #10353

**Comment by tobil4sk** [comment]
Currently, the install scripts are using a very old build of mingw from sourceforge with gcc 8.1.0 but v6 of the mingw runtime (from 2018). There is a build here with gcc 8.5.0: https://github.com/niXman/mingw-builds-binaries/releases/tag/8.5.0-rt_v10-rev0. This version is much more up to date with features in windows headers that have been added since 2018.

**Comment by ijunaidm** [comment]
@tobil4sk - Thank you for bringing this issue to us. We are investigating on this issue , and will get back to you after our findings.

**Comment by ijunaidm** [comment]
@tobil4sk - We don't want to switch to new installation method because we have concerns about supply chain when we use unofficial build of mingw. 

And we prefer to keep using official build distributed via sourceforge even if it is outdated.

Thank you, I am closing the issue.

**Comment by tobil4sk** [comment]
> We don't want to switch to new installation method because we have concerns about supply chain when we use unofficial build of mingw.

This is the same source that is already being used by the windows-2022 image:
https://github.com/actions/runner-images/blob/59a0b3727b675f4d29713127bca7726492d7a085/images/windows/scripts/build/Install-Mingw64.ps1#L53-L56
