### ISSUE TITLE
Visual Studio thumbprint changed

### ISSUE THREAD

**Issue by achechen** [actions/runner-images#10350]
### Description

Windows 2022 image, Install-VisualStudio.ps1 script is failing due to signature thumbprint change:
```
==> azure-arm.build_image: Provisioning with powershell script: xxxxxxxxxxxxxxx\Install-VisualStudio.ps1
    azure-arm.build_image: Downloading Bootstrapper ...
    azure-arm.build_image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.build_image: Package downloaded in 0.45 seconds
    azure-arm.build_image: Signature thumbprint do not match expected.
    azure-arm.build_image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.build_image: +         throw "Signature thumbprint do not match expected."
    azure-arm.build_image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.build_image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.build_image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
    azure-arm.build_image:
==> azure-arm.build_image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0 3010]

```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest version main branch

### Is it regression?

no

### Expected behavior

thumbprint should be updated

### Actual behavior

script fails

### Repro steps

run the pipeline

**Comment by kishorekumar-anchala** [comment]
Hi @achechen ,

  We're looking into the issue we, will update you once the investigation complete .

**Comment by kishorekumar-anchala** [comment]
Hi @achechen ,

  We updated the new thumbprint and it is available with the main. Kindly fork the latest code and retry.
