### ISSUE TITLE
`libtiff` in Ubuntu 22.04 is unusable because of a missing dependency

### ISSUE THREAD

**Issue by mmomtchev** [actions/runner-images#10378]
### Description

`libtiff` in Ubuntu 22.04 is unusable because of a missing dependency.

Ubuntu 22.04 itself has a missing dependency between these packages - `libtiff` requires `webp`.

This confuses `configure` scripts.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.317.0

### Is it regression?

Probably not

### Expected behavior

`libtiff` has all of its dependencies

### Actual behavior

`libtiff` is missing `libwebp`

### Repro steps

Compile the following program:

```cpp
#include <tiff.h>
#include <tiffio.h>

int main() {
  thandle_t image;
  TIFFClientOpen("", "rb", image, nullptr, nullptr, nullptr, nullptr, nullptr,
                 nullptr, nullptr);
  return 0;
}
```

with

```
g++ -o test-tiff test-tiff.cc `pkg-config --static --libs libtiff-4`
```

Also

```
ldd /lib/x86_64-linux-gnu/libtiff.so.5
```

**Comment by mmomtchev** [comment]
https://github.com/mmomtchev/ImageMagick/actions/runs/10195141340/job/28203226137

**Comment by hemanthmanga** [comment]
@mmomtchev Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
@mmomtchev Could you please try the below 

```name: Compile and Check TIFF Program

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Create test-tiff.cc file
        run: |
          echo '#include <tiff.h>
          #include <tiffio.h>
          int main() {
            thandle_t image;
            TIFFClientOpen("", "rb", image, nullptr, nullptr, nullptr, nullptr, nullptr,
                           nullptr, nullptr);
            return 0;
          }' > test-tiff.cc
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtiff-dev libwebp-dev pkg-config
      - name: Compile the program
        run: |
          g++ -o test-tiff test-tiff.cc `pkg-config --static --libs libtiff-4`
      - name: Check dependencies of libtiff
        run: |
          ldd /lib/x86_64-linux-gnu/libtiff.so.5```

**Comment by mmomtchev** [comment]
Yes, installing the missing dependency will obviously fix it

**Comment by hemanthmanga** [comment]
@mmomtchev Hopefully your issue is resolved, Closing this issue Thanks.
