### ISSUE TITLE
Audio driver troubles on latest macos runners.

### ISSUE THREAD

**Issue by piiertho** [actions/runner-images#10373]
### Description

Recently I update a project MacOs runners (it was running on MacOs 11 before).  
I now encounter troubles with audio drivers: https://github.com/utopia-rise/fmod-gdextension/actions/runs/10158162846/job/28089640224?pr=232

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/utopia-rise/fmod-gdextension/actions/runs/10158162846/job/28089640224?pr=232

### Is it regression?

macos-11

### Expected behavior

FMOD should initialize well.

### Actual behavior

FMOD does not initialize well failing with:
```
ERROR: A call to a standard soundcard driver failed, which could possibly mean a bug in the driver or resources were missing or exhausted.void
```

### Repro steps

Run godot-fmod action linked.

**Comment by susmitamane** [comment]
Hi @piiertho We are looking into the issue.Will keep you posted.

**Comment by sarathrajsrinivasan** [comment]
Hi @piiertho,

We are aware of the FMOD issue in arm64 machines. We are working on it and do not have a set timeline yet.
Closing this issue since the resolution/update will be tracked in #10219 . Please let us know incase of any questions.
