### ISSUE TITLE
Add v15.6.0 nodejs version to node-versions

### ISSUE THREAD

**Issue by hobbsh** [actions/runner-images#10377]
### Tool name

nodejs

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

15.6.0

### Brief description of tool

I would like to request that `v15.6.0` is added to `node-versions` (it says to open an issue here).

We often get this error when `setup-node` runs and subsequently fails:
```
Attempting to download 15.6.0...
Not found in manifest. Falling back to download directly from Node
Acquiring 15.6.0 - x64 from https://nodejs.org/dist/v15.6.0/node-v15.6.0-linux-x64.tar.gz
aborted
Waiting 12 seconds before trying again
aborted
Waiting 12 seconds before trying again
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
It should be added to https://github.com/actions/node-versions
```

### Are you willing to submit a PR?

Yes

**Comment by RaviAkshintala** [comment]
@hobbsh Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
Hi @hobbsh The required version 15.6.0 nodejs has EOL on  01 Jun 2021, at present the current default version of ubuntu 22 is 18 and default version of ubuntu 24 is 20. Hence the downgrade of version is not possible which will effect other customers.

**Comment by hobbsh** [comment]
@RaviAkshintala Thanks for your quick reply! What you explained is understandable, except why are major versions `6`, `8`, `10`, `12, `13` and `14` all supported in [node-versions](https://github.com/actions/node-versions/blob/main/versions-manifest.json)?
