### ISSUE TITLE
Firefox WebDriver not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by torokati44** [actions/runner-images#10374]
### Description

When running browser tests in Firefox, I'm getting this error:
`[1-0] 2024-07-31T09:44:30.951Z WARN webdriver: Request failed with status 500 due to Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: ubuntu-24.04
  Version: 20240721.1.0

https://github.com/ruffle-rs/ruffle/actions/runs/10177828674/job/28150157900?pr=16352#step:11:90

### Is it regression?

yes, it works on Ubuntu 22.04

### Expected behavior

The tests pass.

### Actual behavior

The tests don't pass.

### Repro steps

Trigger a CI run of https://github.com/ruffle-rs/ruffle/pull/16352.

**Comment by danielhjacobs** [comment]
Ubuntu 24.04 is missing Firefox, Geckodriver, Edge, and Edgedriver: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#browsers-and-drivers. Ubuntu 22.04 has those: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#browsers-and-drivers.

**Comment by torokati44** [comment]
I see. Well then, that's the bug.

**Comment by danielhjacobs** [comment]
This is in the Ubuntu 22.04 image template:

https://github.com/actions/runner-images/blob/da684ca6d2b6de512a4dec746c7c134d2b010626/images/ubuntu/templates/ubuntu-22.04.pkr.hcl#L292-L295

Both the Firefox and Edge installation lines are missing from the Ubuntu 24.04 image template:

https://github.com/actions/runner-images/blob/da684ca6d2b6de512a4dec746c7c134d2b010626/images/ubuntu/templates/ubuntu-24.04.pkr.hcl#L290-L291

**Comment by torokati44** [comment]
Frankly, I don't give much of a heck about Edge, but Firefox must not be allowed to be left out, once this image is GA.

**Comment by ijunaidm** [comment]
@torokati44 - Thank you for bringing this issue to us, we are looking into this issue and get back to you after our findings.

**Comment by janbrasna** [comment]
For now this is expected as the preinstalled software list mentions the browsers' removal, however according to:

> "… there will definitely be changes until GA including the software list installation (for instance we are to add firefox & edge, but a bit later), but we do not guarantee we are to address all the requests…"
> — posted by `@mikhailkoliada` in https://github.com/actions/runner-images/issues/9848#issuecomment-2112088377

they plan to bring these back before it goes out of beta, so we'll see.

**Comment by ijunaidm** [comment]
@torokati44 - We have added firefox to Ubuntu24.04 image. Thank you for opening the ticket issue.

**Comment by torokati44** [comment]
Indeed, this is now fixed in https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240915.1 via https://github.com/actions/runner-images/pull/10589 (also related: https://github.com/actions/runner-images/pull/10597).
The image is now well under deployment: https://github.com/actions/runner-images/pull/10626
Thank you!
