### ISSUE TITLE
Ubuntu 22.04 version 20240730.2.0 missing command docker-compose

### ISSUE THREAD

**Issue by DRsabadash** [actions/runner-images#10384]
### Description

After the recent version bump from v. 20240721.1.0 to v.20240730.2.0 our github actions are all failing due to docker-compose not being available.

no difference in action file between these two deployments, verified it's not a source code issue:
![image](https://github.com/user-attachments/assets/267d7185-c6cb-46db-93bf-f75e062ade70)
![image](https://github.com/user-attachments/assets/7078445b-5aee-4630-bfc1-6efefc46d91f)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [x] Ubuntu 20.04
- [X] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240730.2.0

### Is it regression?

no

### Expected behavior

docker-compose should be an available command

### Actual behavior

build fails due to 'Command not found'

### Repro steps

- initiate a github action using ubuntu-22.04
- attempt to run the command docker-compose (any flags)

**Comment by DRsabadash** [comment]
upon further inspection it is affecting all three images: 20.04, 22.04 and 24.04

**Comment by SargisPlusPlus** [comment]
I think they announced about it here: https://github.com/actions/runner-images/issues/9692

**Comment by DRsabadash** [comment]
> I think they announced about it here: #9692 You can replace `docker-compose` with `docker compose` and it all should work.

resolved the issue. will close this bug.

it would be nice to get breaking changes announced in a better way.

**Comment by angle319** [comment]
I have to complain here. Our pipeline was locked to a default version, but in July, continuous changes to Docker Compose commands caused release errors. We are enterprise users who follow the documentation to write our pipelines, yet we still have to help Microsoft find errors?
