### ISSUE TITLE
AWS Cli is broken for ECS tasks 

### ISSUE THREAD

**Issue by papunsenapati07** [actions/runner-images#10387]
### Description

Using ubuntu-latest image gives An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Role is not valid exceptions when registering task definitions - This might because upgrading aws cli to 2.7.19.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

both in latest and ubuntu-20.04 images

### Expected behavior

An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Role is not valid

### Actual behavior

Task should register

### Repro steps

Create a ECS task definition - and try registering it with ECS.
aws ecs register-task-definition --region $AWS_REGION --cli-input-json "file://${GITHUB_WORKSPACE}/ecs-task-def.json

**Comment by Prabhatkumar59** [comment]
Hi @papunsenapati07 Thank you for bringing this issue to our attention. We will update you on this issue after investigating.

**Comment by papunsenapati07** [comment]
@Prabhatkumar59 thanks for picking this one - it seems to be an issue with AWS ECS itself we got a confirmation from service team, cli is working fine.
