### ISSUE TITLE
ulimit in self-hosted runner's shell mismatch the ulimit set in machine

### ISSUE THREAD

**Issue by igorluppi** [actions/runner-images#10402]
### Description

When ulimit -a is performed in regular machine' shell we got:

`
POSIX message queues         (bytes, -q) 4194304
`

But Github runners are limiting it to another value. If we run the same command in runner shell:

`POSIX message queues         (bytes, -q) 819200`

The runner is installed in the same machine, although it cannot use the same resource as set.

In our `/etc/security/limits.conf` we have:

```
* hard msgqueue 4194304
<$USER> hard msgqueue 4194304
root hard msgqueue 4194304
* soft msgqueue 4194304
<$USER> soft msgqueue 4194304
root soft msgqueue 4194304
```

How can Github self-hosted runner access the same amount of memory?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.317.0'

### Is it regression?

no

### Expected behavior

When we run `ulimit -a` we should see `POSIX message queues         (bytes, -q) 4194304`

### Actual behavior

When we run `ulimit -a` we see `POSIX message queues         (bytes, -q) 819200`

### Repro steps

Just run `ulimit -a` in Github runner shell, if you have changed the default value for the desired ulimit.

**Comment by ijunaidm** [comment]
@igorluppi - Thank you for bringing this issue to us , we will investigate and update you after our findings on this issue.

**Comment by kishorekumar-anchala** [comment]
HI @igorluppi ,

Since this issue is related to a self-hosted runner, which we don't own, hence closing the issue. 

Please create an issue in the [actions/runner](https://github.com/actions/runner) repository as it is the correct place for agent issues.

Thank you !

**Comment by igorluppi** [comment]
Thanks @kishorekumar-anchala ,
Unfortunately I havent received any feedback from that repository.
