### ISSUE TITLE
Azure CLI updated, signature mismatch

### ISSUE THREAD

**Issue by GitYukari** [actions/runner-images#10403]
### Description

Build fails when installing Azure CLI. Updated last night, 8/6.

Is there a reason that you do not use chocolatey to install? The helper script for Azure CLI seems unnecessary, especially because you are using chocolatey for all other packages. It is extra effort and doesn't make sense to manually update the signature each time a new version of Azure CLI is released, especially since the URL is not locked to a single version.

If not chocolatey, you should either disable the signature check (not needed) or link to the actual MSI of the release, rather than the aka.ms link. Otherwise, this will break every time. The most recent msi is https://azcliprod.blob.core.windows.net/msi/azure-cli-2.63.0.msi

### Platforms affected

- [x] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

all windows versions

### Is it regression?

No

### Expected behavior

Azure CLI should install

### Actual behavior

```
azure-arm.image: Install the latest Azure CLI release
azure-arm.image: Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\im2e0z2k.msi...
==> azure-arm.image: Signature thumbprint do not match expected.
```

### Repro steps

1. Checkout any release for Windows
2. Run Packer build

**Comment by hemanthmanga** [comment]
@GitYukari  Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
@GitYukari The signature has been updated, Kindly fork your main, Thanks.

**Comment by jricond** [comment]
@hemanthmanga just a note. There is no working building from your tags currently.
