### ISSUE TITLE
Unable to start `Windows Search` service on `windows-latest`

### ISSUE THREAD

**Issue by ho-229** [actions/runner-images#10419]
### Description

My program will interact with Windows Search so I start it manually by:

```pwsh
Start-Service -Name "wsearch"
```

but got

```txt
Start-Service: D:\a\_temp\9011a052-896d-4888-a407-c516033e7747.ps1:2
Line |
   2 |  Start-Service -Name "wsearch"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Service 'Windows Search (wsearch)' cannot be started due to the following error: Cannot start service 'wsearch'
     | on computer '.'.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240807.2.0
Job link: https://github.com/ho-229/cloud-filter-rs/actions/runs/10337038485/job/28613453322

### Is it regression?

No

### Expected behavior

`Start-Service -Name "wsearch"` succeeds and `Windows Search` is running.

### Actual behavior

`Start-Service -Name "wsearch"` failed.

### Repro steps

Run `Start-Service -Name "wsearch"` on pwsh.

**Comment by hemanthmanga** [comment]
@ho-229 Thank you for bringing this issue to us. We will look into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
The windows-latest runner in GitHub Actions may have certain services disabled or restricted for security reasons, including the Windows Search service. To work around this, you can try one of the following solutions:
1. Use a Self-Hosted Runner
A self-hosted runner gives you full control over the environment, including the ability to start services like wsearch. You can configure a self-hosted Windows runner and then use it for your workflow.
2. Check if the Service is Disabled
Before starting the service, you can check if the service is disabled and change its startup type to Manual or Automatic before attempting to start it. 

**Here's how you can do it:**
```
jobs:
  start-search:
    runs-on: windows-latest
    steps:
      - name: Check Windows Search Service Status
        run: |
          $service = Get-Service -Name 'wsearch'
          if ($service.Status -eq 'Stopped') {
            Set-Service -Name 'wsearch' -StartupType Manual
            Start-Service -Name 'wsearch'
          }
      - name: Confirm Windows Search Service is Running
        run: |
          Get-Service -Name 'wsearch' | Select-Object Status
 ```
 If these workarounds don't meet the needs, moving to a self-hosted runner would be the most robust solution.

**Comment by ho-229** [comment]
Thanks for your effort.
