### ISSUE TITLE
Azure policy creation failure in windows-latest

### ISSUE THREAD

**Issue by kevinzhg** [actions/runner-images#10428]
### Description

Azure policy creation failure in windows-latest

Current image version: '20240807.2.0'
AZ version is 12.1.0

##[error][InvalidRequestContent] : The request content was invalid and could not be deserialized: 'Error converting value "@{type=String; metadata=}" to type 'Microsoft.WindowsAzure.Governance.PolicyService.Models.Policy.PolicyParameterDefinition'. Path 'properties.parameters.effect', line 18, position 43.'. the block below is the one I am using.

    "parameters": {
      "effect": {
        "type": "String",
        "defaultValue": "Append",
        "allowedValues": [
          "Append",
          "Disabled"
        ],
        "metadata": {
          "displayName": "Effect",
          "description": "Enable or disable the execution of the policy"
        }
      }
    }

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current image version: '20240807.2.0'
AZ version is 12.1.0

### Is it regression?

no

### Expected behavior

No error.

### Actual behavior

##[error][InvalidRequestContent] : The request content was invalid and could not be deserialized: 'Error converting value "@{type=String; metadata=}" to type 'Microsoft.WindowsAzure.Governance.PolicyService.Models.Policy.PolicyParameterDefinition'. Path 'properties.parameters.effect', line 18, position 43.'.

### Repro steps

1. Using windows-latest version in Azure DevOps.
2. Creating the azure policy according to https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_definitions/policy_definition_es_Append-KV-SoftDelete.json
3. you will see the error.

**Comment by kishorekumar-anchala** [comment]
Hi @kevinzhg ,

It seems below repo is the appropriate to raise issue about your bug. Please check the below repo . thank you !

https://github.com/Azure/ALZ-Bicep/issues

**Comment by kevinzhg** [comment]
> Hi @kevinzhg ,
> 
> It seems below repo is the appropriate to raise issue about your bug. Please check the below repo . thank you !
> 
> https://github.com/Azure/ALZ-Bicep/issues

As a temporary solution, we switched the agent version to windows-2019, and it worked well until midnight. We noticed the change in the image from (Current image version: '20240730.1.0') to (Current image version: '20240811.1.0'). Could you direct me to where I can find the release notes for the '20240811.1.0' version? if there have been any changes introduced in this image related to the deserialization in 'Microsoft.WindowsAzure.Governance.PolicyService.Models.Policy.PolicyParameterDefinition'. thanks in advance.

**Comment by kishorekumar-anchala** [comment]
Hi @kevinzhg 

please find below urls.

[win-19 ](https://github.com/actions/runner-images/pull/10427/files) and [win-22](https://github.com/actions/runner-images/pull/10425/files)

**Comment by kishorekumar-anchala** [comment]
HI @kevinzhg , 

  do we have any update?

**Comment by kishorekumar-anchala** [comment]
Hi @kevinzhg , 

 We hope you're issue got resolved , could you please share your comments ?

**Comment by kishorekumar-anchala** [comment]
Hi @kevinzhg , we hope the issue got resolved , we are closing the issue.

**Comment by almirayasmin** [comment]
Is there any resolution to this issue? I face the same problem

**Comment by smerkx** [comment]
There is a temporary solution to use a '-BackwardCompatible' flag (https://github.com/Azure/azure-powershell/blob/main/documentation/migration-guides/Az.12.0.0-migration-guide.md#azresources).

But basically it is a breaking change in Az 12.0 and you will need to adapt your scripts to handle to changes.
