### ISSUE TITLE
[Request] Toolset Ubuntu 22.04 - set go version 1.22.* as default

### ISSUE THREAD

**Issue by habandy** [actions/runner-images#10436]
### Tool name

go

### Tool license

https://github.com/golang/go/blob/master/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.22.*

### Brief description of tool

Go is an open source programming language that makes it easy to build simple, reliable, and efficient software

### URL for tool's homepage

https://go.dev/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
already present, but default version is set to 1.21.

Version 1.20 was set to default before 1.21. 
see here: https://github.com/actions/runner-images/commit/e844facbb931ee1a122ef569d76b68edfaf1d8f0

Version 1.21 was set to default end of february. 
see here: https://github.com/actions/runner-images/commit/2730b04222bce454147a124e5d50efaa89ab8c1d

Version 1.22 was set to default on Ubuntu 24.04 only in may.
see here: https://github.com/actions/runner-images/commit/7781af869bec02d4d491cba6d01de412e96d865d

Is there a reason why this has not adapted to Ubuntu 22.04 image toolset?
```

**Comment by RaviAkshintala** [comment]
@habandy Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
@habandy The current latest version of Go is 1.23, So we will update the default Go version to 1.23. I hope it will work for you as well.

**Comment by habandy** [comment]
> @habandy The current latest version of Go is 1.23, So we will update the default Go version to 1.23. I hope it will work for you as well.

Sure, thank you! 😃

**Comment by habandy** [comment]
#10587 has been closed without merge and #10500 does not contain a updated toolset.json
How is the actual state about this request?

**Comment by habandy** [comment]
i saw #10580 has been merged. 
however the PR only changed the toolset for Ubuntu 24.04 not for 22.04

**Comment by habandy** [comment]
@RaviAkshintala @ijunaidm @vidyasagarnimmagaddi
Sorry for the ping, just want to make you aware of my comment and the fact that Ubuntu 22.04 still has 1.21.* as default.

**Comment by RaviAkshintala** [comment]
Hi @habandy 

> > @habandy The current latest version of Go is 1.23, So we will update the default Go version to 1.23. I hope it will work for you as well.
> 
> Sure, thank you! 😃

Hi @habandy We have added Go version 1.23 set as default and it is available in main branch. Kindly fork the main branch and proceed.
We are closing this issue, Thank you.
