### ISSUE TITLE
Packer Build Ubuntu 24.04 on main branch is now failing on "Describing Nginx"

### ISSUE THREAD

**Issue by simonlock** [actions/runner-images#10433]
### Description

Hi

Using the packer template https://github.com/actions/runner-images/tree/main/images/ubuntu/templates/ubuntu-24.04.pkr.hcl builds now fail to  complete due to failing tests for Nginx. The relevant log file snippet is povided below.

This  template previously worked a few days ago.

Describing Nginx
  [+] Nginx CLI 11ms (11ms|1ms)
  [+] Nginx Service 115ms (115ms|0ms)
Tests completed in 22.17s
Tests Passed: 399, Failed: 1, Skipped: 40, Inconclusive: 0, NotRun: 0

Containers            : {[+] /imagegeneration/tests/ActionArchiveCache.Tests.ps
                        1, [+] /imagegeneration/tests/Android.Tests.ps1, [+] /i
                        magegeneration/tests/Apt.Tests.ps1, [+] /imagegeneratio
                        n/tests/Browsers.Tests.ps1…}
Result                : Failed
FailedCount           : 1
FailedBlocksCount     : 0
FailedContainersCount : 0
PassedCount           : 399
SkippedCount          : 40
InconclusiveCount     : 0
NotRunCount           : 0
TotalCount            : 440
Duration              : 00:00:22.1670616
Executed              : True
ExecutedAt            : 08/12/2024 18:42:30
Version               : 5.6.1
PSVersion             : 7.4.2
PSBoundParameters     : {[Configuration, PesterConfiguration]}
Plugins               : 
PluginConfiguration   : 
PluginData            : 
Configuration         : PesterConfiguration
DiscoveryDuration     : 00:00:01.1643021
UserDuration          : 00:00:19.2243355
FrameworkDuration     : 00:00:01.7784240
Failed                : {[-] Image has enough free space}
FailedBlocks          : {}
FailedContainers      : {}
Passed                : {[+] /opt/actionarchivecache not empty, [+] /opt/action
                        archivecache/actions_cache/0865c47f36e68161719c5b124609
                        996bb5c40129.tar.gz, [+] /opt/actionarchivecache/action
                        s_cache/0c45773b623bea8c8e75f6c82b208c3cf94ea4f9.tar.gz
                        , [+] /opt/actionarchivecache/actions_cache/136d96b4aee
                        02b1f0de3ba493b1d47135042d9c0.tar.gz…}
Skipped               : {[!] Firefox, [!] Geckodriver, [!] Edge, [!] Edge Drive
                        r…}
Inconclusive          : {}
NotRun                : {}
Tests                 : {[+] /opt/actionarchivecache not empty, [+] /opt/action
                        archivecache/actions_cache/0865c47f36e68161719c5b124609
                        996bb5c40129.tar.gz, [+] /opt/actionarchivecache/action
                        s_cache/0c45773b623bea8c8e75f6c82b208c3cf94ea4f9.tar.gz
                        , [+] /opt/actionarchivecache/actions_cache/136d96b4aee
                        02b1f0de3ba493b1d47135042d9c0.tar.gz…}
CodeCoverage          : 

Exception: Test run has failed
Provisioning step had errors: Running the cleanup provisioner, if present...

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest
Current agent version: '3.243.0'
Agent name: 'Hosted Agent'

### Is it regression?

yes

### Expected behavior

The nginx test should pass and the image should be built

### Actual behavior

Fails toward the end of the build. The relevant logs have been provided above.

### Repro steps

packer build

**Comment by kishorekumar-anchala** [comment]
Hi @simonlock , Thank you for bringing this issue to us. We will look into this issue and will update you on this issue after investigating

**Comment by kishorekumar-anchala** [comment]
Hi @simonlock ,

   Could you please fork the latest code from main branch and try to run the image gen pipeline. we are not reproducing this issue. Thank you !

**Comment by simonlock** [comment]
Hi @kishorekumar-anchala,

Thank you for your response. I'm currently using only your template, provisioners and scripts, this is because I'm publishing the built images to an Azure Compute Gallery, I'm not using your pipeline.

I’ve identified the cause of the build failure. It appears that the Packer temporary VM requires a minimum of 64GB of os disk space for the build to complete successfully. Setting it to 60GB leads to a failure, as mentioned earlier, but interestingly, there’s no error related to insufficient disk space in that case. However, when set to less than 60GB, the build fails, and the logs correctly indicate insufficient disk space.

It seems that setting os_disk_size_gb = 64 is the sweet spot.

Kind Regards

Simon

**Comment by kishorekumar-anchala** [comment]
Thanks for your response @simonlock .
