### ISSUE TITLE
Encounter error "AADSTS5000611: Symmetric Key Derivation Function version 'KDFV1' is invalid"

### ISSUE THREAD

**Issue by tongyuze** [actions/runner-images#10438]
### Description

Hi there, recently we found an issue in our pipeline. This issue is Windows-only. While we are running our test, we saw this error:
Message: AADSTS5000611: Symmetric Key Derivation Function version 'KDFV1' is invalid. Update the device for the latest updates.

And I found this: https://techcommunity.microsoft.com/t5/microsoft-entra-blog/what-s-new-in-microsoft-entra-june-2024/ba-p/3796387#:~:text=sign%2Dins%20workbook-,Change%20announcements,devices%20have%20Security%20Patches%20after%20July%202021%20no%20action%20is%20required.,-If%20your%20Windows

Do you know if the VM image "windows server 2019" is patched?

This issue happens sporadically.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: windows-2019
Version: 20240730.1.0

Image: windows-2019
Version: 20240811.1.0

https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1344843&view=logs&j=eb47cf0f-d985-55a1-6f14-8e290b77d0a1&t=c5c9351d-1e6e-4cd0-a382-f00d0e38cb8e

### Is it regression?

No

### Expected behavior

The test should succeed.

### Actual behavior

The test failed with AADSTS5000611: Symmetric Key Derivation Function version 'KDFV1' is invalid. Update the device for the latest updates.

### Repro steps

N/A

**Comment by kishorekumar-anchala** [comment]
Hi @tongyuze , looking into your issue , we will investigate and inform you !.

**Comment by kishorekumar-anchala** [comment]
@tongyuze , The new version will available by EOW. thank you ! .

**Comment by tongyuze** [comment]
Thank you for the quick response @kishorekumar-anchala ! Will check after that.

**Comment by kishorekumar-anchala** [comment]
Hi @tongyuze , Could you please try now .

**Comment by tongyuze** [comment]
@kishorekumar-anchala Since this doesn't always repro in our pipeline, I would like to look at it for the next two days. So far, I haven't seen any failure.

**Comment by kishorekumar-anchala** [comment]
Hi @tongyuze , I believe we're not reproducing the issue again, hence we're closing the issue. Thank you !
