### ISSUE TITLE
Failed to Fetch https://azure.archive.ubuntu.com Not Found

### ISSUE THREAD

**Issue by FunLow** [actions/runner-images#10446]
### Description

We are facing currently issues with installing curl package from the azure.archive.ubuntu.com repository resulting in a fail for all of our build jobs. The package itself can be found but it seems that the installation files are missing.

```
$ sudo apt-get install curl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcurl4
The following packages will be upgraded:
  curl libcurl4
2 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
Need to get 484 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Ign:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.17
Ign:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.17
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.17
  404  Not Found [IP: 20.54.144.51 80]
Err:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.17
  404  Not Found [IP: 20.54.144.51 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.81.0-1ubuntu1.17_amd64.deb  404  Not Found [IP: 20.54.144.51 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.81.0-1ubuntu1.17_amd64.deb  404  Not Found [IP: 20.54.144.51 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240811.1.0

### Is it regression?

no

### Expected behavior

Install the packages using the azure.archive.ubuntu repository

### Actual behavior

Packages can be found but the installation package doesn't seem to be available.

### Repro steps

Use `sudo apt-get install curl`
or `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

**Comment by ijunaidm** [comment]
@FunLow -  Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by jackmtpt** [comment]
This is also happening for `libkrb5-3` and its dependencies on `jammy`

**Comment by jonasby** [comment]
Ditto for our self-hosted build agents installing packages, e.g. libpython3.10

working yesterday:

```
2024-08-14T11:31:42.2010323Z Get:56 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-*** amd64 3.10.12-1~22.04.5 [4762 kB]
...
2024-08-14T11:31:44.5494110Z Preparing to unpack .../00-libpython3.10_3.10.12-1~22.04.5_amd64.deb ...
2024-08-14T11:31:44.6206333Z Unpacking libpython3.10:amd64 (3.10.12-1~22.04.5) over (3.10.12-1~22.04.3) ...
```

failing today

```
2024-08-15T13:32:57.3480473Z Get:56 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-*** amd64 3.10.12-1~22.04.5 [4762 kB]
...
2024-08-15T13:32:57.5939383Z Err:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10 amd64 3.10.12-1~22.04.5
2024-08-15T13:32:57.5940224Z   404  Not Found [IP: 51.104.174.161 80]
```

**Comment by jonasby** [comment]
The source is working again today. Hurrah!

**Comment by kierzo89** [comment]
404's still , seems the repo is broken at http://azure.archive.ubuntu.com/ubuntu 

seems a loop when trying to navigate into the ubuntu folder as per:

![image](https://github.com/user-attachments/assets/ba720fb2-b461-464d-bba0-f47c77593bef)

**Comment by FunLow** [comment]
Can confirm that the issue has also been fixed for us.

@hemanthmanga 
I tried Solution 1 and that one didn't worked for us. 
Solution 2 may have been possible but didn't tried that.
Solution 3 would have been quite hard as the identification would require that we test each package and also have to evaluate if the relevant packages are compatible. Most of the packages installed were coming from some other packages requiring these as dependencies.

As we are using an automated setup for dependencies installed on short living Agents manual installation wasn't an option.

Still thank you for your suggestions.

**Comment by hemanthmanga** [comment]
Hi @FunLow,

Thank you for your update and detailed feedback.

I understand that Solution 1, which involved using --fix-missing, didn’t resolve the issue, and Solution 2, switching mirrors, was considered but not applied. Given your automated setup and the short-lived nature of your agents, it’s clear that manual installations were not feasible.

As an alternative solution, you might consider using a different package manager like snap to install curl. This can serve as a temporary workaround:

**Install curl via snap:**

`sudo snap install curl`

This approach can bypass issues with the package repository and may offer a quick fix.

If you encounter any further issues or have additional questions, please don’t hesitate to reach out.

**Comment by kierzo89** [comment]
@FunLow this is not a solution, the solution is to fix the mirror, not paste some chatgpt response.

**Comment by hemanthmanga** [comment]
Hi @FunLow, Since we haven't heard back, we'll assume your issue is resolved and will close this issue for now. Feel free to reach out us for any other queries. Thanks.

**Comment by Wemmy0** [comment]
This isn't fixed and unsurprisingly the chatGPT bot @hemanthmanga isn't too much help
