### ISSUE TITLE
New-AzPolicySetDefinition not working in Latest Microsoft Hosted Devops Agent 

### ISSUE THREAD

**Issue by harish-chandrasekaran-premaraj** [actions/runner-images#10441]
### Description

Input:

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

Current image version: '20240811.1.0 - error Message 
New-AzPolicySetDefinition_CreateExpanded1: /usr/share/az_12.1.0/Az.Resources/7.2.0/Policy.Autorest/custom/New-AzPolicySetDefinition.ps1:249

 $scriptCmd = {& $wrappedCmd @calledParameters}

Old working  image version: '20240804.1.0 - Working

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '3.243.0'
Operating System
Ubuntu
22.04.4
LTS
Runner Image
Image: ubuntu-22.04
Version: 20240811.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240811.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240811.1
Runner Image Provisioner
2.0.374.1

### Is it regression?

https://dev.azure.com/RIT-CCOE/Azure/_build/results?buildId=58883&view=logs&j=b85e8826-7a77-58a1-7cbd-4ef4adad4f19&t=b194b80b-9cd7-478a-aca1-1a74d937ebb4

### Expected behavior

New-AzPolicySetDefinition was working with the old image version: '20240804.1.0'

### Actual behavior

New-AzPolicySetDefinition_CreateExpanded1: /usr/share/az_12.1.0/Az.Resources/7.2.0/Policy.Autorest/custom/New-AzPolicySetDefinition.ps1:249

 $scriptCmd = {& $wrappedCmd @calledParameters}

More information - https://github.com/Azure/azure-powershell/blob/6d49acd0933c1dbc9202de0bbbc8566a49f6e7df/src/Resources/Policy.Autorest/custom/New-AzPolicySetDefinition.ps1#L168

### Repro steps

New-AzPolicySetDefinition commands is not working with vmImage: 'ubuntu-latest' version 20240804.1.0

**Comment by Prabhatkumar59** [comment]
Hi @harish-chandrasekaran-premaraj - Thank you for bringing this issue to our attention. We will look into this issue and will confirm and update you after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @harish-chandrasekaran-premaraj - As new image version has been rolled out. So, please try using latest image version.
I hope your issue will be resolved now and we are closing this issue.
