### ISSUE TITLE
WDK installation fails during windows2022 image build

### ISSUE THREAD

**Issue by greha** [actions/runner-images#10444]
### Description

Windows2022 image build fails with the following error:

```
azure-arm.image: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/templates/../scripts/build/Install-WDK.ps1
    azure-arm.image: Downloading package from https://go.microsoft.com/fwlink/?linkid=2249371 to C:\Users\packer\AppData\Local\Temp\dtsaizmu.exe...
    azure-arm.image: Package downloaded in 0.53 seconds
    azure-arm.image: Signature for C:\Users\packer\AppData\Local\Temp\dtsaizmu.exe is valid
    azure-arm.image: Starting Install ...
    azure-arm.image: Installation successful in 74.66 seconds
    azure-arm.image: Installing VSIX from C:\Program Files (x86)\Windows Kits\10\Vsix\VS2022\10.0.22621.0\WDK.vsix...
    azure-arm.image: VSIX installation failed with exit code -2146233079.
    azure-arm.image: Waiting 10 seconds before retrying. Retries left: 19
    azure-arm.image: VSIX installation failed with exit code -2146233079.
    azure-arm.image: Waiting 10 seconds before retrying. Retries left: 18
    azure-arm.image: VSIX installation failed with exit code -2146233079.
    azure-arm.image: Waiting 10 seconds before retrying. Retries left: 17
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Fails for released, pre-release and main

### Is it regression?

yes

### Expected behavior

WDK installation passes.

### Actual behavior

```
azure-arm.image: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/templates/../scripts/build/Install-WDK.ps1
    azure-arm.image: Downloading package from https://go.microsoft.com/fwlink/?linkid=2249371 to C:\Users\packer\AppData\Local\Temp\dtsaizmu.exe...
    azure-arm.image: Package downloaded in 0.53 seconds
    azure-arm.image: Signature for C:\Users\packer\AppData\Local\Temp\dtsaizmu.exe is valid
    azure-arm.image: Starting Install ...
    azure-arm.image: Installation successful in 74.66 seconds
    azure-arm.image: Installing VSIX from C:\Program Files (x86)\Windows Kits\10\Vsix\VS2022\10.0.22621.0\WDK.vsix...
    azure-arm.image: VSIX installation failed with exit code -2146233079.
    azure-arm.image: Waiting 10 seconds before retrying. Retries left: 19
    azure-arm.image: VSIX installation failed with exit code -2146233079.
    azure-arm.image: Waiting 10 seconds before retrying. Retries left: 18
    azure-arm.image: VSIX installation failed with exit code -2146233079.
    azure-arm.image: Waiting 10 seconds before retrying. Retries left: 17

```

### Repro steps

Clone repo and build the windows2022 image. 
It failed for released, pre-release and main

**Comment by tdysko-cf** [comment]
we've go the same issue, we're using the latest windows build

**Comment by angaaruriakhil** [comment]
Also facing the same issue.

**Comment by ijunaidm** [comment]
@greha -  Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by pbk8s** [comment]
Facing the same issue. This is what I found in the debug logs - 
```8/14/2024 5:58:00 PM - Installation of Component.Microsoft.Windows.DriverKit failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.
8/14/2024 5:58:00 PM - Install Error : System.InvalidOperationException: Installation of Component.Microsoft.Windows.DriverKit failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.

**Comment by jsloan117** [comment]
same here as well, like the rest.

**Comment by ayanavolu** [comment]
also facing the same issue 

    **amazon-ebs.Windows2022-Base: Downloading package from https://go.microsoft.com/fwlink/?linkid=2249371 to C:\Users\ADMINI~1\AppData\Local\Temp\o2y1020r.exe...
    amazon-ebs.Windows2022-Base: Package downloaded in 0.83 seconds
    amazon-ebs.Windows2022-Base: Signature for C:\Users\ADMINI~1\AppData\Local\Temp\o2y1020r.exe is valid
    amazon-ebs.Windows2022-Base: Starting Install ...**
##[debug]Agent environment resources - Disk: C:\ Available 328649.00 MB out of 511997.00 MB, Memory: Used 7580.00 MB out of 16195.00 MB, CPU: Usage 0.51%
##[debug]Agent environment resources - Disk: C:\ Available 328649.00 MB out of 511997.00 MB, Memory: Used 7571.00 MB out of 16195.00 MB, CPU: Usage 0.51%
##[debug]Agent environment resources - Disk: C:\ Available 328650.00 MB out of 511997.00 MB, Memory: Used 7625.00 MB out of 16195.00 MB, CPU: Usage 0.51%
    **amazon-ebs.Windows2022-Base: Installation successful in 103.56 seconds
    amazon-ebs.Windows2022-Base: Installing VSIX from C:\Program Files (x86)\Windows** Kits\10\Vsix\VS2022\10.0.22621.0\WDK.vsix...
##[debug]Agent environment resources - Disk: C:\ Available 328638.00 MB out of 511997.00 MB, Memory: Used 7585.00 MB out of 16195.00 MB, CPU: Usage 0.50%
##[debug]Agent environment resources - Disk: C:\ Available 328640.00 MB out of 511997.00 MB, Memory: Used 7635.00 MB out of 16195.00 MB, CPU: Usage 0.50%
    **amazon-ebs.Windows2022-Base: VSIX installation failed with exit code -2146233079.**

**Comment by luissoal** [comment]
I got the same issue

**Comment by BernieWSA** [comment]
Facing this as well

**Comment by juanfer007** [comment]
Hi. 
I got the same issue.
No new releases since 20240811. 
All the others like Windows2019, Ubuntu20 and Ubuntu22 have a new one 20240818.

Thanks for your help.

**Comment by RaviAkshintala** [comment]
@greha We are working on resolving the issue, we will keep you updated once the issue is fixed.

**Comment by ChemometecJMJ** [comment]
I got the same issue

**Comment by LokeshNagireddy** [comment]
Hi Team,

I too got the same issue while building the Windows 2022 image. May we know the approximate date of fix or the progress of fix?

**Comment by greha** [comment]
@kishorekumar-anchala 
Thank you, worked :)

**Comment by veronicagt094** [comment]
I am having an error with VSIX at this point, any solution, already make this change: https://github.com/actions/runner-images/pull/10475/commits/2605eb1faf9e1ea782d5dd263809e45911404d01

    azure-arm.image: Downloading package from https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2022extension/1.0.0.22/1668223914320/Votive2022.vsix to C:\Users\packer\AppData\Local\Temp\Votive2022.vsix...
    azure-arm.image: Package downloaded in 0.52 seconds
    azure-arm.image: Installing VSIX from C:\Users\packer\AppData\Local\Temp\Votive2022.vsix...
    azure-arm.image: VSIX installation failed with exit code 1014.
