### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by AHuusom** [actions/runner-images#10445]
### Tool name

Packer

### Tool license

?

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

Please add packer to ubuntu2404 as it is missing.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ijunaidm** [comment]
@AHuusom -  Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by ijunaidm** [comment]
@AHuusom - Sure, We will be adding the packer tool to Ubuntu24.04 image in the next week and it will be implemented by next week. 
I will keep you updated once the tool gets added, and also when it will be available on ubuntu24.04 image to be used.

**Comment by ijunaidm** [comment]
@AHuusom - Packer tool should get deployed with the next week's Ubuntu24.04 image deployment version .

**Comment by ijunaidm** [comment]
Hi @AHuusom - Packer tool should be available on ubuntu24.04 image to be used . Thank you for opening a ticket issue on adding  packer tool to ubuntu24.04 image.

**Comment by ijunaidm** [comment]
@AHuusom - Thank you, I am closing the ticket issue.
