### ISSUE TITLE
Docker-compose not actually installed

### ISSUE THREAD

**Issue by shawaj** [actions/runner-images#10451]
### Description

This image says it has docker compose installed. https://github.com/actions/runner-images/blob/ubuntu22/20240811.1/images/ubuntu/Ubuntu2204-Readme.md

However it actually doesn't, as when I try to run `docker-compose config -q` it gives me an error...

```
/bin/sh: 1: docker-compose: not found
```

If I run `sudo apt-get install docker-compose` at the beginning of the action then the action completes fine but if not then it fails. 

This is a regression because it used to work fine until last couple of weeks.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240811.1.0

### Is it regression?

Yes

### Expected behavior

Docker compose should work

### Actual behavior

Docker compose not found 

### Repro steps

Described above

**Comment by vidyasagarnimmagaddi** [comment]
Hi @shawaj  , We will be analysing the issue and revert with our analysis.thanks

**Comment by ijunaidm** [comment]
@shawaj - As of now Docker-compose v1 version is completely deprecated from all the images, you have to use docker-compose v2 version .

**Comment by shawaj** [comment]
> @shawaj - As of now Docker-compose v1 version is completely deprecated from all the images, you have to use docker-compose v2 version .

This is an absurd change. Remove it from new images sure but existing ones shouldn't have regressions like this.

As an alternative, I don't see any reason why docker-compose command can't be linked to the new command docker compose.

You are just breaking people's actions for no good reason.

**Comment by shawaj** [comment]
> I agree with @shawaj. This really affected many teams that were not using the new docker API. It broke without much warning and suddenly. This is generally what engineering teams try to avoid.

💯

This was not communicated in any effective way to people that use this daily

**Comment by quesurifn** [comment]
@shawaj Are you guys experiencing the added pleasure of debugging docker compose DNS issues? All of our docker compose network settings suddenly broke. We fixed with static IP and this morning PRs were put up and the runner failed again with the static IP fix.

**Comment by shawaj** [comment]
> @shawaj Are you guys experiencing the added pleasure of debugging docker compose DNS issues? All of our docker compose network settings suddenly broke. We fixed with static IP two weeks ago and this morning PRs were put up and the runner failed again with the static IP fix.

Not something we use TBH. But I feel for you because that sounds like a massive pain! 

I get that stuff has to be updated but it should be properly communicated. The first time you hear about it shouldn't be when your actions fail. Doesn't matter if it's a free service or not... 

Cloudflare is the best I've experienced in this kind of thing... Very good communication and updates

**Comment by ijunaidm** [comment]
@shawaj -  Please refer to the below announcement open ticket issue created for the Docker-compose v1 deprecation . 
https://github.com/actions/runner-images/issues/9692

**Comment by shawaj** [comment]
> @shawaj - Please refer to the below announcement open ticket issue created for the Docker-compose v1 deprecation . #9692

Totally useless. But nice try

**Comment by ijunaidm** [comment]
Sure  @quesurifn. 

Thank you @shawaj @quesurifn . I am closing this ticket issue.

**Comment by shawaj** [comment]
> Sure @quesurifn.
> 
> Thank you @shawaj @quesurifn . I am closing this ticket issue.

So you are not going to fix this regression? Is that correct?

**Comment by ijunaidm** [comment]
@shawaj - I completely understand the pain for breaking changes. But we did announced in this ticket https://github.com/actions/runner-images/issues/9692

Please try replacing docker-compose with docker compose to fix your issue.

**Comment by ijunaidm** [comment]
@shawaj - Did replacing docker-compose with docker composr worked for you ?

**Comment by ijunaidm** [comment]
@shawaj - Thank you , I am closing this ticket issue. Hopefully your issue is resolved , feel free to open a new ticket if you face any issues related to the runner images.

**Comment by danieljamesscott** [comment]
Did docker-compose get added back in? We worked around the removal by modifying our workflows to install docker-compose, but the [recent docker upgrade](https://github.com/actions/runner-images/issues/13474) seems to be causing issues with our workaround.

**Comment by erik-bershel** [comment]
Hey @danieljamesscott!

Nope.

**Comment by danieljamesscott** [comment]
But [this](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) says it is included in the image?

**Comment by erik-bershel** [comment]
It's `Docker Compose v2 2.38.2` Not `docker-compose` v1.
