### ISSUE TITLE
Microsoft.Azure.DevOps.Pipelines.Agent v1.23 VM Extension does not start in Ubuntu 24.04 image

### ISSUE THREAD

**Issue by bvaughan527** [actions/runner-images#10450]
### Description

The Microsoft.Azure.DevOps.Pipelines.Agent v1.23 VM Extension does not start when a VMSS instance is provisioned from the Ubuntu 24.04 image. The VMSS will show the provisioning status of the VM extension as failed with the error that the agent failed to start and had a terminal exception non-zero exit code.

I also noticed that the ubuntu 24.04 packer file does not have a configuration, similar to the below that is in the Ubuntu 22.04 packer file and appears to be used for Azure DevOps agent configuration.

```
provisioner "file" {
    destination = "/tmp/"
    source      = "${path.root}/../assets/ubuntu2204.conf"
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline          = ["mkdir -p /etc/vsts", "cp /tmp/ubuntu2204.conf /etc/vsts/machine_instance.conf"]
  }
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: 20240811.1.1

### Is it regression?

No

### Expected behavior

The Microsoft.Azure.DevOps.Pipelines.Agent VM Extension should provision and start successfully when provisioning a VM instance with the Ubuntu 24.04 image.

### Actual behavior

The Microsoft.Azure.DevOps.Pipelines.Agent VM Extension does not start when a VMSS instance is provisioned from the Ubuntu 24.04 image. The VMSS will show the provisioning status of the VM extension as failed with the error that the agent failed to start and had a terminal exception non-zero exit code.

### Repro steps

Repro Steps:
1. Build an ubuntu 24.04 build agent image following the instructions at: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md
2. Once the image is built and saved to a Shared Image Gallery, review the status of an Azure DevOps managed VMSS using the above image as an image reference and that the provisioning status of the Microsoft.Azure.DevOps.Pipelines.Agent VM Extension which should show as failed.

**Comment by RaviAkshintala** [comment]
@bvaughan527  Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
Hi @bvaughan527 This issue should be fixed on ADO side, Please refer the below link and we are closing this issue. Thanks.
https://github.com/microsoft/vsts-azurevm-extension/pull/235/files
