### ISSUE TITLE
Add Visual Studio Community IDE

### ISSUE THREAD

**Issue by KishanVaishnani** [actions/runner-images#10468]
### Tool name

Visual Studio Community IDE

### Tool license

open-source

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2022

### Brief description of tool

Visual Studio Community IDE is missing

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by vidyasagarnimmagaddi** [comment]
Hi @KishanVaishnani 
Thank you for bringing this issue to our attention. We will look into this and will update you after investigating:)

**Comment by kishorekumar-anchala** [comment]
HI @KishanVaishnani , 

  May we know the use-case for your request ?

**Comment by KishanVaishnani** [comment]
Hi @kishorekumar-anchala 

I wanted to use the devenv command for the Visual Studio installer project pipeline in Azure. Currently, I am using the Enterprise version and it's asking for a license key so, I noticed that in the windows-2022 image, the community IDE is missing.

Unfortunately, I can't provide the pipeline code but some sample lines of code are listed below

`
trigger:
  branches:
    include:
    - 'release'
  tags:
    include:
    - '*'
pool:
  vmImage: 'windows-2022'
variables:
 devCmd: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com' <-------------

- task: BatchScript@1
  displayName: Enable .vdproj Builds
  inputs:
    filename: '"$(disableToolPath)\DisableOutOfProcBuild.exe"'
    workingFolder: '"$(disableToolPath)"'

- script: '"$(devCmd)" $(System.DefaultWorkingDirectory)\SampleProject.sln /Build "Release" /Project $(System.DefaultWorkingDirectory)\SampleProject\Setup.vdproj'
  displayName: Build Installer
`

**Comment by kishorekumar-anchala** [comment]
@KishanVaishnani , Thanks for your response , we will update you when investigation done.

**Comment by kishorekumar-anchala** [comment]
Hi @KishanVaishnani ,

Installing community and enterprise editions side by side is tricky and can easily cause compatibility problems. Hence we're closing the request. Thank you !
