### ISSUE TITLE
Update/Add [tool name] Need  Chrome 127.0.6533.120 and chrome driver 127.0.6533.119

### ISSUE THREAD

**Issue by HrishikeshRangdale-gep** [actions/runner-images#10469]
### Tool name

Chrome 127.0.6533.120 and chrome driver 127.0.6533.119

### Tool license

Chrome 127.0.6533.120 and chrome driver 127.0.6533.119

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Chrome 127.0.6533.120 and chrome driver 127.0.6533.119

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by HrishikeshRangdale-gep** [comment]
These are latest versions and stable so pls add as our selenium UI automation is failing in 99 version

**Comment by Prabhatkumar59** [comment]
Hi @HrishikeshRangdale-gep - Thank you for bringing this issue to our attention. We will look into this and will update you after investigating:)

**Comment by tabish99999** [comment]
Haishz

**Comment by vidyasagarnimmagaddi** [comment]
Hi @HrishikeshRangdale-gep  , specific version of chrome driver cannot be updated to image, the latest version will be rolled out in this week deployment.thanks

**Comment by Prabhatkumar59** [comment]
Hi @HrishikeshRangdale-gep - Specific mentioned version of chrome driver cannot be updated to image. However, the latest version has been rolled out with Google Chrome 128.0.6613.85
Chrome Driver 128.0.6613.84. Please try using this.
We are closing this issue, thanks.
