### ISSUE TITLE
Request to add Xcode 16.0 beta back

### ISSUE THREAD

**Issue by isnine** [actions/runner-images#10464]
### Tool name

Xcode 16.0 beta

### Tool license

/

### Add or update?

- [X] Add
- [] Update

### Desired version

16.0 beta 5

### Approximate size

/

### Brief description of tool

It looks like we want to use xcode 16.1 beta to replace Xcode 16.0 beta. https://github.com/actions/runner-images/pull/10460 
#10439 

But they're completely different versions. For example, on the day iOS 18 is officially released in September, Apple will first release the official version of Xcode 16.0. However, at that time, Xcode 16.1 will still be in beta. Developers will need to use Xcode 16.0 to compile and upload their apps to the App Store and cannot use the 16.1 beta to do the same thing.

There will also be very many differences between them, so I'm requesting to add Xcode 16.0 back in.

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by isnine** [comment]
I drafted a PR #10465 for this issue. Let me know if anyone have different thoughts.

**Comment by prasanjitsahoo** [comment]
HI @isnine,
We are looking into it. Will keep you posted with the updates.

**Comment by isnine** [comment]
Thanks @prasanjitsahoo !
