### ISSUE TITLE
Strawberry perl installation includes pkg-config which interferes with other stuff

### ISSUE THREAD

**Issue by phadej** [actions/runner-images#10482]
### Description

The `/c/Strawberry/perl/bin` is apparently in PATH, and that path contains `pkg-config`; so every tool which relies on existence of `pkg-config` picks that.

What makes it worse, apparently, that pkg-config database contains PostgreSQL client library, `libpq`; which is quite old (11.3), so new stuff just doesnt' work.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Runner Image
  Image: windows-2022
  Version: 20240[8](https://github.com/haskellari/postgresql-libpq/actions/runs/10539408119/job/29202958333#step:1:9)11.1.0
  ```

### Is it regression?

Maybe

### Expected behavior

I would expect no `pkg-config` in PATH; it's not a thing on Windows. Or if there were one, than the one by *the* MSYS installation.

### Actual behavior

There is an arbitrary `pkg-config` in PATH.

### Repro steps

```yaml
  steps:
      - name: which pkg-config
        run: which pkg-config
 ```
 
 prints `/c/Strawberry/perl/bin/pkg-config`

**Comment by vidyasagarnimmagaddi** [comment]
Hi @phadej  , Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
HI @phadej , 

  i am unable to produce the issue, could you please retry and confirm?
