### ISSUE TITLE
Xcode 16.0 Beta Not Available

### ISSUE THREAD

**Issue by jjessel** [actions/runner-images#10497]
### Description

Xcode 16.0 beta has been removed from the runner. Xcode 16.1 beta has been added but that only helps if you're targeting iOS 18.1. Can Xcode 16.0 beta be added back?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.319.1'

### Is it regression?

Yes

### Expected behavior

Xcode 16.0 beta to be present

### Actual behavior

Xcode 16.0 beta has been removed and 16.1 added.

### Repro steps

Try to run using Xcode 16.0 beta

**Comment by sarathrajsrinivasan** [comment]
Hi @jjessel,

We are already working on adding Xcode 16.0 Beta 6 to the images. Will post an update here once the VM rollouts are done.

**Comment by bgoncal** [comment]
@sarathrajsrinivasan Based on the PR merged above can I assume this should be working now? My step below (and the other tentatives below) is failing my workflow:

```
steps:
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16_beta_6.app/Contents/Developer
```

```
steps:
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
```
```
steps:
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.0.app/Contents/Developer
```

**Comment by sarathrajsrinivasan** [comment]
Hi @bgoncal ,

The VM rollouts are in progress for Xcode 16 Beta 6. Will update here once done.

**Comment by sarathrajsrinivasan** [comment]
Hi @bgoncal ,

The VM rollouts are done now and Xcode 16.0 Beta 6 is available in the image. Please validate.
