### ISSUE TITLE
macOS keychain reports that there are no certificates

### ISSUE THREAD

**Issue by saagarjha** [actions/runner-images#10498]
### Description

One of my CI jobs has been failing recently and it seems like at some point in the last few months (when this job last ran) the keychain stopped returning results. I'm not entirely sure what is going on here, maybe the keychain is locked? So this is mostly just asking if you happen to have touched something that might be related.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20240818.4
Failing run: https://github.com/saagarjha/Ensemble/actions/runs/10550954430

### Is it regression?

https://github.com/saagarjha/Ensemble/actions/runs/9286017853

### Expected behavior

I would expect the keychain to contain things in it

### Actual behavior

The keychain comes back empty

### Repro steps

1. I ran a build

**Comment by susmitamane** [comment]
Hi @saagarjha 

We are looking into it. Will keep you posted.

**Comment by saagarjha** [comment]
Ok, so this turned out to be my fault. The certificate I was trying to add was expired (at least, I think it was expired). I created a new one and it seems to show up the keychain correctly. Sorry for the confusion!
