### ISSUE TITLE
Win2022 Install VSExtensions Error: Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by xianlin** [actions/runner-images#10501]
### Description

The Windows 2022 build script `Install-VSExtensions.ps1`  run into error as the title showed.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20240811.1.0

### Is it regression?

N.A.

### Expected behavior

Install successfully

### Actual behavior

```
==> azure-arm.image: Provisioning with powershell script: /agent/_work/1/s/images/windows/templates/../scripts/build/Install-VSExtensions.ps1
    azure-arm.image: There is an error encountered:
    azure-arm.image:  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 19
    azure-arm.image: There is an error encountered:
    azure-arm.image:  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 18
    azure-arm.image: There is an error encountered:
    azure-arm.image:  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
...
...
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 3
    azure-arm.image: There is an error encountered:
    azure-arm.image:  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 2
    azure-arm.image: There is an error encountered:
    azure-arm.image:  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 1
    azure-arm.image: There is an error encountered:
    azure-arm.image:  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
```

### Repro steps

N.A.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin  , Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin  , kindly wait for the new version of windows-22 being rolled out , and try the same.thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin  , the latest windows-22 version (20240825.1) has been rolled, kindly synch your main , and try the same.If failed, share the repo steps and  error logs.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin  , Have you tried the `Windows 2022 build script Install-VSExtensions.ps1`  with the latest version , kindly revert.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin , Have you tried the Windows 2022 build script Install-VSExtensions.ps1 with the latest version , kindly revert.Thanks

**Comment by xianlin** [comment]
Hi @vidyasagarnimmagaddi, I tried to use the latest "main" but still get the same result. I need to check my network firewall on this.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @cupacheeno , the new image has been rolled out (20240912.1.1) .The issue is fixed now. kindly synch your main .Thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin  , The issue is fixed now. kindly synch your main .Thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @xianlin , the issue is fixed  now. And the new image 20240915.1 is rolled out. Kindly synch your main . Closing the issue. Thanks.
