### ISSUE TITLE
Preinstall dotnet workloads

### ISSUE THREAD

**Issue by rick-micpoint** [actions/runner-images#10512]
### Tool name

dotnet workload

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

The one that matches the installed dotnet sdk

### Brief description of tool

If you want to target specific platforms (or frameworks i.e. MAUI) in .NET, you often need to install additional workloads using the [dotnet workload](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload) tool. This can be quite time consuming though, so it would be great if each platform could have their workloads pre-installed.

More details about workloads can also be found [here](https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workloads.md)

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

The base `dotnet` sdk is already installed, and the workloads can be installed by using either [dotnet workload install](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install) or [dotnet workload restore](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-restore)

### Tool installation time in runtime

Depending on the workload 2 to 10 minutes. The MAUI workload is probably the worst.

**Comment by vidyasagarnimmagaddi** [comment]
hi @rick-micpoint , Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by rick-micpoint** [comment]
Thanks. I only marked the Windows images because that's where I currently need the workloads, but it obviously could be useful for the other platforms as well.

**Comment by vidyasagarnimmagaddi** [comment]
Hi, @rick-micpoint . We will track this requirement of pre-install workloads by the number of requests received . 
we will validate all requests to incorporate them in future releases.thanks .

**Comment by zoooN** [comment]
Up!
What’s the status of this request? I also recently realized that installing workloads is quite time consuming. It would be really helpful if you could include them in the Windows and macOS images.
