### ISSUE TITLE
CRITITAL BUG -- Missing display sclaing options on a 2560*1440 monitor

### ISSUE THREAD

**Issue by Mintactus** [actions/runner-images#10514]
### Description

===CRITICAL BUG IMPACTING USER EXPERIENCE A LOT====

Hi, I'm using ubuntu 24.04.1 latest version up to this date.
I have a 2560 * 1440 native resolution monitors
BENQ GW2765
ASUS PB278(Q)

I'm trying set the scaling at 150% using fractionnal scalling but the result doesn't make any sens when both screens are connected.  Part of the contextual menu ( right click ) disapear, like splitted in half, etc.)

I will not garanti that it work every single time, I don't trust the scaling option, but it seems that with my unique BENQ pluged-in, it works, the attached report is made with this unique screen connected.
[system.md](https://github.com/user-attachments/files/16825568/system.md)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

No imsge provided

### Is it regression?

No, but I don't know about previous ubuntu

### Expected behavior

A decent looking desktop

### Actual behavior

A not decent looking desktop, eveything is either tiny or way too big or completly broken

### Repro steps

Get two 2560*1440 monitors and try to scale at 125 or 150%

**Comment by RaviAkshintala** [comment]
Hi @Mintactus Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
Hi @Mintactus Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @Mintactus - The issue you are facing with fractional scaling on dual 2560x1440 monitors in Ubuntu 24.04.1 is basically related to how GNOME handles fractional scaling, which can sometimes lead to visual glitches, particularly when using multiple monitors with different scaling settings.

**For you, i am providing the below resolution for this:-**

A. By Enabling Experimental Fractional Scaling-
Here, You can enable a more stable version of fractional scaling via the **gsettings** command.

**Firstly**, Open a terminal and run below:
`gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
`
**After that**, Restart your GNOME session by logging out and logging back in, or restart your computer.

B. For more fine-grained control, you can also manually set the scaling using the **xrandr** tool

C. You can also set the scaling factor manually for each monitor. For **150% scaling:**

`xrandr --output HDMI-1 --scale 1.5x1.5 --output DP-1 --scale 1.5x1.5
Here, you can Adjust the output names and scaling factors as necessary.

D. Another method is to create a custom resolution that simulates 150% scaling by using below:

`xrandr --output HDMI-1 --mode 2560x1440 --scale 1.5x1.5 --output DP-1 --mode 2560x1440 --scale 1.5x1.5
`
E. Further customization might be necessary using **dconf** or **gsettings** to tweak the way GNOME handles multiple monitors and scaling.

F. If **GNOME’s** scaling continues to cause issues, consider using a different desktop environment that might handle high-resolution monitors better, such as KDE Plasma, which has more advanced and stable scaling options.

By using these ways, hopefully you will be able to achieve a **decent looking desktop** with their dual 2560x1440 monitors. 
If any further query, please feel free to ask us.

**Comment by Mintactus** [comment]
Thank you it's really appreciated,

Do you have any recommendation of distribution or UI, like you mentioned,
KDE Plasma, which I find a bit overwhelming, that suppots hight resolutions
?
I liked Ubuntu, but not being able to scale with today's screens is indeed
a massive problem in 2024, does Ubuntu is thinking about going away from
GNOME or working on changing the engine internally who is in charge of it ?


Have a great day

**Comment by Prabhatkumar59** [comment]
Hi @Mintactus- Thanks for your response.

As Ubuntu with GNOME is still highly capable and remains a strong choice for high-resolution displays like 2560x1440. Ubuntu's **GNOME** environment, especially when configured with fractional scaling and the latest updates, provides a consistent and polished experience. By enabling experimental fractional scaling, updating graphics drivers can provide visually appealing desktop.

So, you can try using above mentioned steps from A to E and by using above experimental fractional scaling, fine-tuning with **xrandr**, you might be able to achieve the outcomes.
Feel free to reach out to us in case.

**Comment by Mintactus** [comment]
Thank you
I will do as suggested

Will this "experimental" fractional scaling be the default one in the near
future ?

**Comment by Prabhatkumar59** [comment]
Hi @Mintactus - Thanks for your response.

"The 'experimental' fractional scaling feature in GNOME is actively being developed and improved. However, I can't confirm an exact timeline for it becoming the default.

**Comment by Prabhatkumar59** [comment]
Hi @Mintactus - Hopefully your issue might have resolved now and will close this issue for now. Feel free to reach out us for any other queries. Thanks.
