### ISSUE TITLE
Keep Ubuntu 24.04 Dock on top of other windows

### ISSUE THREAD

**Issue by Mintactus** [actions/runner-images#10518]
### Tool name

Overlapping Dock

### Tool license

Included in Ubuntu 24.04.1 license

### Add or update?

- [ ] Add
- [ ] Update

### Desired version

Doesn't apply

### Brief description of tool

Add an option in the Ubuntu Desktop -> Dock section to make the Dock overlap the other windows. Instead of hiding it, hiding it is ennoying when you have you go back and forward between applications, and not hiding it takes a shit load of space in your screen of the apps, you already have a second bar on top who already take space on the screen. Since your systry options, bluetooth, wifi etc,  are not part of the dock that cause a situation where a lot of space on the screen is taken for no reasons. 

Another option could be to add the systry to the dock.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

### Tool installation time in runtime

Part of native installation

### Are you willing to submit a PR?

What's a PR...using contraction is no pro, expression yourself

**Comment by RaviAkshintala** [comment]
Hi @Mintactus Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @Mintactus- This seems to be an issue with the ubuntu desktop not the runner images issue. Hence closing the issue.Thanks!
