### ISSUE TITLE
something wrong on latest(20240827.1) mac os image for code signing

### ISSUE THREAD

**Issue by muukii** [actions/runner-images#10519]
### Description

https://github.com/actions/runner-images/compare/macos-14-arm64/20240818.4...macos-14/20240827.1

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/compare/macos-14-arm64/20240818.4...macos-14/20240827.1

### Is it regression?

no

### Expected behavior

exporting ipa works

### Actual behavior

code sign fails

### Repro steps

- Uses fastlane
- run gym for archiving and exporting IPA

**Comment by susmitamane** [comment]
Hi @muukii 

We are looking into it. Will keep you posted.

**Comment by muukii** [comment]
@susmitamane 
thank you.
after I looked the error log what I have, it seems disk space issue is happening.
I've found this error - no space left on device

as it's only 14GB storage, how we build iOS Applications might affect this case. but it was good until now.

**Comment by muukii** [comment]
@susmitamane 
It works for me after deleted all of xcode which is not necessary. so it was just disk space was not enough.
I think I can close this ticket. but this decreasing disk space after updated image might affect other consumers.
