### ISSUE TITLE
Checksum verification fails for cosmosdb-emulator installation

### ISSUE THREAD

**Issue by vd84** [actions/runner-images#10524]
### Description

When running agent install for windows2022

I think we need to update the checksum to "DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41"

In the file [Install-AzureCosmosDbEmulator.ps1](https://github.com/actions/runner-images/blob/12335f2cc4243907c2238dbb6577892b3073a141/images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1#L7)

==> azure-arm.image: Checksum verification failed: expected D21A0476B7F3439319BE6A1060935E7C865FEFA87C47943C9A6D595137703F49, got
==> azure-arm.image: DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
==> azure-arm.image: +         throw "Checksum verification failed: expected $expectedHash,  ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Checksum verifi...C9A6020220BEE41:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Checksum verification failed: expected D21A0476B7F3439319BE6A1060935E7C865FEFA87C47943C9
==> azure-arm.image:    A6D595137703F49, got DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41
==> azure-arm.image:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows2022

### Is it regression?

no

### Expected behavior

Install cosmosdb emulator

### Actual behavior

==> azure-arm.image: Checksum verification failed: expected D21A0476B7F3439319BE6A1060935E7C865FEFA87C47943C9A6D595137703F49, got
==> azure-arm.image: DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
==> azure-arm.image: +         throw "Checksum verification failed: expected $expectedHash,  ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Checksum verifi...C9A6020220BEE41:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Checksum verification failed: expected D21A0476B7F3439319BE6A1060935E7C865FEFA87C47943C9
==> azure-arm.image:    A6D595137703F49, got DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41
==> azure-arm.image:

### Repro steps

Run install vm image on windows 2022

**Comment by impsoftjoel** [comment]
Can also vouch for this we are getting the same errors for window-2022:
![image](https://github.com/user-attachments/assets/9c35f420-3622-4dbe-b265-3e65c2027445)

==> azure-arm.image: Provisioning with powershell script: C:/a/1/s/runner-images/images/windows/templates/../scripts/build/Install-AzureCosmosDbEmulator.ps1
    azure-arm.image: Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\r05cffti.msi...
    azure-arm.image: Package downloaded in 1.3 seconds
==> azure-arm.image: Checksum verification failed: expected D21A0476B7F3439319BE6A1060935E7C865FEFA87C47943C9A6D595137703F49, got
==> azure-arm.image: DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
==> azure-arm.image: +         throw "Checksum verification failed: expected $expectedHash,  ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Checksum verifi...C9A6020220BEE41:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Checksum verification failed: expected D21A0476B7F3439319BE6A1060935E7C865FEFA87C47943C9
==> azure-arm.image:    A6D595137703F49, got DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...

**Comment by kishorekumar-anchala** [comment]
HI @vd84 ,

  Thanks for raising the issue, we're working on the issue.

**Comment by RaviAkshintala** [comment]
@vd84  cosmosdb-emulator signature has been updated, Could you please retry by forking latest code from main branch.
Closing this issue,Thank you.
