### ISSUE TITLE
[Macos-12] Python version 3.7 will be removed from the macos-12 image on September 16,2024

### ISSUE THREAD

**Issue by susmitamane** [actions/runner-images#10529]
### Breaking changes

Pre-cached python 3.7 will be removed from the macos-12.

### Target date

September 16,2024

### The motivation for the changes

According to our software and image guidelines tools and versions will typically be removed 6 months after they are deprecated or have reached end-of-life. Python 3.7 series which has now reached end-of-life more than a year ago thus we have to remove it.

### Possible impact

- GitHub actions — runs can take a bit more time as https://github.com/actions/setup-python will have to download and install 3.7 version instead of using the pre-cached one
- AzureDevOps — builds using python 3.7 will be broken

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

AzureDevOps — consider switching your projects to more recent python versions.

**Comment by sarathrajsrinivasan** [comment]
We are planning on not proceeding with this. Hence closing the announcement.
