### ISSUE TITLE
[Macos] go version 1.20.0 will be removed on September 16,2024.

### ISSUE THREAD

**Issue by susmitamane** [actions/runner-images#10531]
### Breaking changes

Two changes:

- Removing go 1.20.0 from all macos images.

### Target date

September 16, 2024

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of go are supported i.e., Go 1.21.0,1.22.0,1.23.0

### Possible impact

If your builds depend on go 1.20.0 they can be broken

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

- https://github.com/actions/setup-go action for GH actions
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by sarathrajsrinivasan** [comment]
Closing as we are not going forward with this change for now. Will re-open with the updated date.
