### ISSUE TITLE
Wrong Signature Thumbprint - Install Azure CLI - Windows Server 2019 Runner Image

### ISSUE THREAD

**Issue by korbin-ashby** [actions/runner-images#10547]
### Description

Install Azure CLi has the wrong signature thumbprint on the test.

==> azure-arm.image: Provisioning with powershell script: D:/a/azure-sig/azure-sig/images/windows/templates/../scripts/build/Install-AzureCli.ps1
    azure-arm.image: Install the latest Azure CLI release
    azure-arm.image: Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\wk3hy2hl.msi...
    azure-arm.image: Package downloaded in 1.11 seconds
==> azure-arm.image: Signature thumbprint do not match expected.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Latest commit: Date: Tue Sep 3 18:45:06 2024 +0200; Commit: ab150879795b7e9b05c4dd1321a385800fc1965f - [macOS] Introduce macOS-15 code (#10535); Author: Erik Bershel <110455084+erik-bershel@users.noreply.github.com>

### Is it regression?

No

### Expected behavior

Successful Build

### Actual behavior

Failing Build

### Repro steps

Run GenerateResourcesAndImage.ps1 using the Windows 2019 packer template file

**Comment by RaviAkshintala** [comment]
@korbin-ashby Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
Hi @korbin-ashby Azure CLI signature has been updated, Could you please retry by forking latest code from main branch. Closing this issue,Thank you.
