### ISSUE TITLE
Signature thumbprint do not match expected for latest Azure CLI release

### ISSUE THREAD

**Issue by tgw-lgu** [actions/runner-images#10540]
### Description

> azure-arm.image: Provisioning with powershell script: C:/a/1/s/images/windows/templates/../scripts/build/Install-AzureCli.ps1
    azure-arm.image: Install the latest Azure CLI release
    azure-arm.image: Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\jau5wotj.msi...
    azure-arm.image: Package downloaded in 9.8 seconds
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:978 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

release_branch : "releases/win22/20240902"

### Is it regression?

no

### Expected behavior

Green build

### Actual behavior

Failing build

### Repro steps

Start build with sources of branch 'releases/win22/20240902'

**Comment by RaviAkshintala** [comment]
@tgw-lgu Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by tgw-lgu** [comment]
Thank you for your response. I just found the thumbprint and updated it in my sources. It's a bit of a hassle that so many builds fail because the image thumbprint doesn't match the expected one on different installers—this often happens with the Visual Studio installers. However, now that I’ve learned where to find the image thumbprint, I can handle it myself!

**Comment by vidyasagarnimmagaddi** [comment]
Thank you @tgw-lgu for ltting us know , We will be closing this issue .
