### ISSUE TITLE
Update/Add timmrt

### ISSUE THREAD

**Issue by RRocaP** [actions/runner-images#10558]
### Tool name

linux runner

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

linux vm runner

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
anaconda, Rstudioserver, python3 latest, rclone and anything else needed for data science and generative ai models
```

**Comment by hemanthmanga** [comment]
Hi @RRocaP Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @RRocaP Could you please provide more information on this tool

**Comment by hemanthmanga** [comment]
Hi @RRocaP ,
We haven’t heard from you in two weeks and hope your issue has been resolved. If you need further assistance, please reach out to us. We will close the issue for now. Thank you.
