### ISSUE TITLE
why is new image consisting latest chrome and chrome driver is not taken by azure pipleines

### ISSUE THREAD

**Issue by HrishikeshRangdale-gep** [actions/runner-images#10550]
### Description

Our azure pipelines are taking below images which doesn't contains latest chrome and chrome driver please fix

https://github.com/actions/runner-images/releases/tag/win22%2F20240811.1

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/win22%2F20240811.1

### Is it regression?

NO

### Expected behavior

Need latest browsers and drivers

### Actual behavior

Taking 127 version

### Repro steps

https://github.com/actions/runner-images/releases/tag/win22%2F20240811.1

**Comment by RaviAkshintala** [comment]
@HrishikeshRangdale-gep Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
HI @HrishikeshRangdale-gep ,

   The mentioned version by you was old one , Could you please check latest version(20240825.1) as it has latest chrome and drivers versions.

**Comment by HrishikeshRangdale-gep** [comment]
but why our pipelines are taking old versions?

**Comment by kishorekumar-anchala** [comment]
May be the location constraints(I suspect), I request could you please try with latest  code and run the pipeline. if not works lets wait for the new rollout , i will confirm it done. thank you !

**Comment by kishorekumar-anchala** [comment]
Hi @HrishikeshRangdale-gep ,

  we hope you tried above workaround, if not kindly try now. thank you !

**Comment by HrishikeshRangdale-gep** [comment]
still not working what we have to change ? images are taken automaticlally right when azure MS hosted pipleines run
<img width="881" alt="image" src="https://github.com/user-attachments/assets/f6c4493d-bd3a-4246-90d9-12dbc32d0a6e">

**Comment by HrishikeshRangdale-gep** [comment]
<img width="756" alt="image" src="https://github.com/user-attachments/assets/f7aca200-e47b-4067-a829-ed53624e30c8">

**Comment by kishorekumar-anchala** [comment]
Sorry , there is a misunderstanding . I thought it is win-19 . I will confirm new version version available.

**Comment by kishorekumar-anchala** [comment]
@HrishikeshRangdale-gep , New version has been rollout, kindly verify now. we are getting latets version . please find below screenshot.

<img width="685" alt="Screenshot 2024-09-05 at 2 20 26 PM" src="https://github.com/user-attachments/assets/1ac963b5-b808-4f93-a070-cacc850ba64e">

**Comment by oggy22** [comment]
We are facing the same issue when running our pipeline with `windows-2022`. It is using `20220811.1` instead of the latest even though there are two more versions after `20220811.1`. I'd be good to know when we can expect the newer versions? Thank you!

**Comment by kishorekumar-anchala** [comment]
Hi @oggy22 ,

   we're investigating into this , we will update you once it fix. thank you !

**Comment by kishorekumar-anchala** [comment]
Hi @HrishikeshRangdale-gep ,

   Could you please try now , i am getting latest version i.e. 20240912.1 . thank you !

**Comment by kishorekumar-anchala** [comment]
Hi @HrishikeshRangdale-gep ,

  Could you please provide your confirmation. Thank you !

**Comment by HrishikeshRangdale-gep** [comment]
working now what was RCA

**Comment by kishorekumar-anchala** [comment]
Hi @HrishikeshRangdale-gep , The issue fixed with new image version , we just re-deploy the image . 

Thank you for your confirmation, we 're closing the issue as completed.
