### ISSUE TITLE
iOS simulator in MacOS crashed (simmetalhost and mobilecal crashes)

### ISSUE THREAD

**Issue by ashok672** [actions/runner-images#10592]
### Description

I saw an instance where the iOS simulator was not responding at all and timed out after the 1 hr timeout defined by our pipeline. I have attached the crash dumps. 
[SimMetalHost-2024-09-10-220840.txt](https://github.com/user-attachments/files/16955930/SimMetalHost-2024-09-10-220840.txt)
[MobileCal-2024-09-10-221726.txt](https://github.com/user-attachments/files/16955931/MobileCal-2024-09-10-221726.txt)
 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-14
Version: 20240908.1
Included Software: https://github.com/actions/runner-images/blob/macos-14/20240908.1/images/macos/macos-14-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-14%2F20240908.1

### Is it regression?

Not sure

### Expected behavior

Simulator doesn't crash.

### Actual behavior

Simulator is not responsive

### Repro steps

Not sure if there is a definitive repro steps. I have seen this once and I just wanted to report the issue with crash dumps to see if it will give your team an idea what the issue might be.

**Comment by sureshe456** [comment]
Hi @ashok672 We will take a look in to this issue and keep you posted updates.

**Comment by sureshe456** [comment]
Hi @ashok672 - 1. Could you please share the workflow pipeline to reproduce the issue you are facing from our end or the URL to the failed run?

2. Are you facing this issue multiple times and with multiple runs, or is it a one-time issue? If it is a one-time issue, we can close it and reopen it in case you see multiple failure instances.
