### ISSUE TITLE
Signature for Visual Studio is incorrect

### ISSUE THREAD

**Issue by korbin-ashby** [actions/runner-images#10591]
### Description

Signature for Visual Studio is incorrect

==> azure-arm.image: Provisioning with powershell script: D:/a/azure-sig/azure-sig/images/windows/templates/../scripts/build/Install-VisualStudio.ps1
    azure-arm.image: Downloading Bootstrapper ...
    azure-arm.image: Downloading package from https://aka.ms/vs/16/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.image: Package downloaded in 3.62 seconds
    azure-arm.image: Signature thumbprint do not match expected.
    azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.image: +         throw "Signature thumbprint do not match expected."
    azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Latest commit: Date: Tue Sep 10 21:23:10 2024 +0530; Commit: c7adf5d533a9ee2cbe4ec1e954b5b73abff6e9a3 - add swift version to ubuntu 24 (#10578); Author: kishorekumar-anchala <168699259+kishorekumar-anchala@users.noreply.github.com>.

### Is it regression?

Yes

### Expected behavior

Build to Succeed

### Actual behavior

Build Fails

### Repro steps

Run GenerateResourcesAndImage.ps1 with the Windows2019 image version

**Comment by kishorekumar-anchala** [comment]
@korbin-ashby . Thank you for bringing the issue with us , we are looking into it and will back Asap.

**Comment by kishorekumar-anchala** [comment]
HI @korbin-ashby , Issue got fixed . i request you fork the latest code and try to build. thank you !
