### ISSUE TITLE
Runner images readme files should properly list all available Languages and Runtimes & Package Managers

### ISSUE THREAD

**Issue by kilasuit** [actions/runner-images#10590]
### Description

In each of these readme files, I'd expect to see dotnet, Go, PHP, PowerShell, Rust & other missing languages and runtimes listed in Languages and Runtimes section, even if it then points me to read further down in the readme what those have available to them

Also I noted that as all have PowerShell on these images PowerShellGet should also be listed as a Package Manager, as too should it's replacement PSResourceGet which is included with PowerShell 7.x

Happy to submit a PR for this btw

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### Repro steps

n/a

**Comment by hemanthmanga** [comment]
Hi @kilasuit Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by sureshe456** [comment]
Hello @kilasuit We will take a look in to this issue and keep you posted updates.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kilasuit  , Kindly provide the exact requirement, as in specific we do have all   Available languages and tools for the specific image are mentioned in the  Readme files .

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kilasuit , Available languages and tools for the specific image are mentioned in the Readme files , as there is no response from you , we are closing this issue. Thanks.

**Comment by kilasuit** [comment]
Please reopen
I'll submit a pr for this later
