### ISSUE TITLE
[Ubuntu 20 and 22] Go version 1.20.0 will be removed on October 14,2024.

### ISSUE THREAD

**Issue by RaviAkshintala** [actions/runner-images#10607]
### Breaking changes

Removing Go 1.20.0 from Ubuntu 20 and 22 images.

### Target date

October 14,2024.

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of go are supported i.e., Go 1.21.0,1.22.0,1.23.0

### Possible impact

If your builds depend on Go 1.20.0 they can be broken

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

https://github.com/actions/setup-go action for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by tikto29** [comment]
Ok
