### ISSUE TITLE
Macos 14 docs out of date

### ISSUE THREAD

**Issue by dingwilson** [actions/runner-images#10610]
### Description

`/Applications/Xcode_16_beta_6.app` no longer exists for macos-14 runtime (https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md)

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240911.3

### Is it regression?

yes, 20240903.5

### Expected behavior

error: missing DEVELOPER_DIR path: /Applications/Xcode_16_beta_6.app/Contents/Developer

### Actual behavior

DEVELOPER_DIR path should exist - /Applications/Xcode_16_beta_6.app/Contents/Developer

### Repro steps

create github action and ENV var DEVELOPER_DIR="/Applications/Xcode_16_beta_6.app/Contents/Developer"

**Comment by sarathrajsrinivasan** [comment]
Hi @dingwilson ,

We have replaced Xcode 16.0 Beta 6 with Xcode 16 Release candidate (RC) for macOS14-arm64.

This is the updated path now: `/Applications/Xcode_16_Release_Candidate.app`

**Comment by dingwilson** [comment]
Hi @sarathrajsrinivasan - I tried that and go this:

> error: missing DEVELOPER_DIR path: /Applications/Xcode_16_Release_Candidate.app/Contents/Developer

**Comment by dingwilson** [comment]
Also this issue is still relevant right? The docs remain out of date as far as I can tell.

**Comment by sarathrajsrinivasan** [comment]
Our deployment for macOS14-arm64 is still in progress. The document will be updated only when the deployment for all the region complete.

**Comment by erik-bershel** [comment]
This is not an issue, the documentation that placed in the repository reflects only the current state of the images without taking into account the update process - it is not possible to reflect in human-readable format. When updating an image, we specify its status [here](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) and open a pull request with incoming changes [here](https://github.com/actions/runner-images/pull/10603), also we have `pre-release` mechanism for the images in updating state that could be tracked [here](https://github.com/actions/runner-images/releases). You can see the list of packages that were installed on the runner in the `Runner Image` section of the `Set up job` step. For example:

<img width="1064" alt="Screenshot 2024-09-14 at 00 43 21" src="https://github.com/user-attachments/assets/8de2b5cd-a596-4c30-a0ad-c547ee42d30c">

Unfortunately, we cannot simultaneously provide two versions of the package for one `major.minor` Xcode release. To ensure more convenient work, we provide a symlink mechanism. You can access `Xcode-16.0-whatever-there-was-version` using the symlink `/Applications/Xcode_16.0.app`

**Comment by dingwilson** [comment]
I see - didn't know about the symlink! Will give that a try thanks!

**Comment by erik-bershel** [comment]
>didn't know about the symlink

And this is the issue, but we are working on it here: https://github.com/actions/runner-images/pull/10568
