### ISSUE TITLE
[Macos 13 and 14] Android NDK versions <=25 will be removed from images on October 07,2024

### ISSUE THREAD

**Issue by susmitamane** [actions/runner-images#10614]
### Breaking changes

Toolcache Android NDK versions <=25 will be removed from Macos 13 and 14 images on October 07,2024.

### Target date

October 07,2024

### The motivation for the changes

All versions <= 25 were EOLed more than a 10 months [ago](https://github.com/android/ndk/wiki/Unsupported-Downloads). We would like to remove long-term unsupported versions.

### Possible impact

If your workflows / pipeline depend on Android NDK versions <=25 , they might become broken

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Nothing is required.

**Comment by sarathrajsrinivasan** [comment]
Android NDK versions <=25 is removed from all macOS13 and macOS14 images.
