### ISSUE TITLE
Add macOS 15 Sequoia runner image

### ISSUE THREAD

**Issue by 4brunu** [actions/runner-images#10632]
### Tool name

macOS 15 Sequoia

### Tool license

https://www.apple.com/au/legal/sla/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

15.0 (24A335)

### Brief description of tool

Latest major macOS version released by Apple.

### URL for tool's homepage

https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

### Tool installation time in runtime

N/A

### Are you willing to submit a PR?

No

**Comment by erik-bershel** [comment]
Hey @4brunu!

Work is in progress. We'll keep you updated regarding the `feature request`.

**Comment by erik-bershel** [comment]
Hey @4brunu! 👋 

macOS-15 beta is here. 🎉 
- https://github.com/actions/runner-images/issues/10686

**Comment by 4brunu** [comment]
That was quick, thanks.
Hope that it's available in azure devops soon.

**Comment by erik-bershel** [comment]
Hey @ashokm and @4brunu!
I am not aware of any plans to add macOS-15 support to Azure DevOps at the moment. This may change closer to GA or the `latest` migration. We'll definitely announce such changes of course.

**Comment by marcberman14** [comment]
What's the alternative for an Azure Devops enterprise user to build against the latest MacOS apart from paying for another service?

**Comment by memogarrido** [comment]
Also I would say the FAQ on the REAME is wrong 

["The availability of images for GitHub Actions and Azure DevOps is the same. However, deprecation policies may differ. See documentation for more details:"](https://github.com/actions/runner-images/blob/7bf4ada29d08793066edab9bd6a16dc3c5ffff27/README.md?plain=1#L175) 


That does not seem to be true, and is misleading.
