### ISSUE TITLE
gpg: Can't check signature: No public key

### ISSUE THREAD

**Issue by Howun** [actions/runner-images#10637]
### Description

Error when downloading package from swift:

==> azure-arm.build_vhd: gpg: signature made Mon Sep 16 21:18:59 2024 UTC
==> azure-arm.build_vhd: gpg:                     using RSA key EF80A866B47A981F
==> azure-arm.build_vhd: gpg: Can't check signature: No public key

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A private build

### Is it regression?

Yes, last worked 16th September 2024

### Expected behavior

All tests passed successfully and build successfully for Ubuntu 20.04 using the build code in this repo.

### Actual behavior

Our pipeline that builds the Ubuntu 20.04 image using the runner images code is failing when downloading package from swift

### Repro steps

Run packer build using the latest code in this repo for Ubuntu 20.04

**Comment by pretkowski** [comment]
I am having the same issue

**Comment by kishorekumar-anchala** [comment]
HI @Howun ,

 the issue got fixed under this [PR](https://github.com/actions/runner-images/pull/10634).
