### ISSUE TITLE
Consider switching from miniconda to miniforge

### ISSUE THREAD

**Issue by jfrost-mo** [actions/runner-images#10643]
### Tool name

miniconda

### Tool license

https://legal.anaconda.com/policies/en/

### Add or update?

- [ ] Add
- [X] Update

### Desired version

miniforge

### Approximate size

same

### Brief description of tool

The licensing situation around miniconda seems increasingly unclear. Consider switching to miniforge which doesn't include any components that require agreeing to the Anaconda Licence.

### URL for tool's homepage

https://github.com/conda-forge/miniforge

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
yes
```

**Comment by kishorekumar-anchala** [comment]
Hi @jfrost-mo ,

Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by jfrost-mo** [comment]
This article describes the general issue: https://www.theregister.com/2024/08/08/anaconda_puts_the_squeeze_on

This blog post describes it in more technical and actionable terms: https://prefix.dev/blog/towards_a_vendor_lock_in_free_conda_experience

**Comment by lakshminarayana02** [comment]
Hi @jfrost-mo 

We are examining why the licence for miniconda is not explicitly stated, however it is most likely inherited from conda (BSD 3-Clause) and packages from conda-forge (various open-source licences). We will comment on it soon. 

and  to integrate the miniforge utility in Ubuntu 24.04 and Windows Server 2022.  We will review and follow the approval  process to include, or if approval is denied, we will offer a workaround solution  and respond promptly.   Kindly be patient with us.

**Comment by jfrost-mo** [comment]
From my understanding distributing conda itself is fine, but using it to download any packages from the `defaults` channels requires a licence from Anaconda, Inc for many organisations.

Miniconda defaults to using the `defaults` channels, while miniforge does not include them, and just has conda-forge, which is openly usable.

**Comment by lakshminarayana02** [comment]
Hi @jfrost-mo 
During our initial investigation by our team , we understood that miniconda is a lightweight tool, and Anaconda  maintains the "defaults" channel to ensure that packages are compatible and routinely updated, and  we have been investigating and comparing with MiniForge to take a call with the GitHub approval team. 

Please bear with us till we provide additional updates.

**Comment by lakshminarayana02** [comment]
Hi 

We appreciate that you highlighted the limits of miniconda, but we included  miniconda in Ubuntu 20 to 22 and continued in the the latest Ubuntu release. 

We are now closing this ticket, and we assure you that we have taken note of and discussed it; if more users want the same, we will initiate the process to add your recommendation. 

Please continue as is, alternatively you can add the selected miniforge version in the runtime for your builds.

Thank you.

**Comment by jfrost-mo** [comment]
I see that conda is now implicitly accepting the ToS for the Anaconda Inc. channels, which I suspect is happening to a lot of organisations without their knowledge.

Job log:
```
Run # Check cache hasn't pulled a partial key match.
  # Check cache hasn't pulled a partial key match.
  test ! -e "${HOME}/conda-env"
  conda create --prefix="${HOME}/conda-env" --file=requirements/locks/py313-lock-linux-64.txt
  shell: /usr/bin/bash -e {0}
CI detected...
Terms of Service implicitly accepted for https://repo.anaconda.com/pkgs/main
Terms of Service implicitly accepted for https://repo.anaconda.com/pkgs/r
2 channel Terms of Service accepted

Downloading and Extracting Packages: ...working...
```
