### ISSUE TITLE
Flaky network / nuget downloads

### ISSUE THREAD

**Issue by thomhurst** [actions/runner-images#10654]
### Description

I've seen this for a couple of months now. Fairly often NuGet will error my pipelines with failures to download a package. Happens way too frequently nowadays so I assume something is wrong somewhere?

```
/Users/runner/.dotnet/sdk/8.0.401/NuGet.targets(174,5): error : The feed 'nuget.org [https://api.nuget.org/v3/index.json]' lists package 'Polly.8.4.1' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/Users/runner/work/ModularPipelines/ModularPipelines/ModularPipelines.Analyzers.sln]
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/thomhurst/ModularPipelines/actions/runs/10948383717/job/30399283041

### Is it regression?

Yes?

### Expected behavior

Download succeeds

### Actual behavior

Download fails

### Repro steps

`dotnet restore`

**Comment by kishorekumar-anchala** [comment]
Hi @thomhurst ,

Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by JonathanLydall** [comment]
It being particularly problematic for the last couple of weeks might be related to https://github.com/NuGet/Home/issues/13729.

**Comment by RaviAkshintala** [comment]
@thomhurst  Could you please provide the platform on which you are facing an issue?

**Comment by paulb777** [comment]
We've been seeing similar issues on macOS the last few days that Swift Package Manager tests that use binary dependencies are almost always failing with ` downloadError("The network connection was lost.")`. Examples at  https://github.com/firebase/firebase-ios-sdk/actions/runs/10957246834/job/30424994614#step:5:102 and https://github.com/firebase/firebase-ios-sdk/issues/13681#issuecomment-2363878938

**Comment by paulb777** [comment]
Using the `cache` action is looking like a promising resolution to the binary Swift Package Manager network failures we were seeing.  https://github.com/firebase/data-connect-ios-sdk/pull/16

**Comment by thomhurst** [comment]
Sounds like they're workarounds that can help, but ultimately there's an issue that needs fixing

**Comment by RaviAkshintala** [comment]
Hi @thomhurst Could you please try with the below workaround.
https://github.com/RaviAkshintala/TUnit/actions/runs/10994988176/workflow#L30
