### ISSUE TITLE
macos-14 deploys "RELEASE_ARM64_VMAPPLE arm64" 

### ISSUE THREAD

**Issue by panchaBhuta** [actions/runner-images#10657]
### Description

macos-14 deploys "RELEASE_ARM64_VMAPPLE arm64" ; expected is "RELEASE_X86_64 x86_64".
ARM64 has lower floating point precision compared to X86, and tests fail due to this.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.319.1'
Operating System
&ensp;&ensp;&ensp;macOS
&ensp;&ensp;&ensp;14.6.1
&ensp;&ensp;&ensp;23G93
Runner Image
&ensp;&ensp;&ensp;Image: macos-14-arm64
&ensp;&ensp;&ensp;Version: 20240915.3
&ensp;&ensp;&ensp;Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240915.3/images/macos/macos-14-arm64-Readme.md
&ensp;&ensp;&ensp;Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240915.3
Runner Image Provisioner
&ensp;&ensp;&ensp;2.0.384.1+6d6c56aa16f1b9c7dd7935df5d63980397e44def](https://github.com/panchaBhuta/converter/actions/runs/10882030283/job/30192192682)

### Is it regression?

no

### Expected behavior

macos-13 (success) :: expect similar OS for macOS-14 image
https://github.com/panchaBhuta/converter/actions/runs/10882030283/job/30192194614
![Screenshot from 2024-09-16 16-16-12](https://github.com/user-attachments/assets/43257d56-91f6-4616-9686-1729579fa86e)

### Actual behavior

macos-14 (fails)
https://github.com/panchaBhuta/converter/actions/runs/10882030283/job/30192192682
In the logs , on 3rd step "Get Version" ; command "uname -a" revels that its ARM64.
Check screen shot below for reference.
![Screenshot from 2024-09-16 16-09-26](https://github.com/user-attachments/assets/71e337c3-ce74-441e-beb7-83fb52eaafef)

### Repro steps

https://github.com/panchaBhuta/converter/actions/runs/10882030283/job/30192192682
re-run the job "Build (macos-14, default)"

**Comment by erik-bershel** [comment]
Hey @panchaBhuta!

It's expected behaviour. Please follow the doc: https://github.com/actions/runner-images?tab=readme-ov-file#available-images

`macos-13` is `Intel`-based, when `macos-14` is `arm64`-based. Other architectures available via `macos-13-xlarge` and `macos-14-large`, respectively.
