### ISSUE TITLE
hostname could have more than 64 characters

### ISSUE THREAD

**Issue by kezhuw** [actions/runner-images#10650]
### Description

`hostname` gives `fv-az1272-448.grsihaubamwerhiryzjrxtypna.phxx.internal.cloudapp.net` which is longer than 64 characters. Some tools, say OpenSSL, refuses these hostnames.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/kezhuw/zookeeper/actions/runs/10831378697/job/30053388552

The first job step runs `hostname -f`.

### Is it regression?

Not sure.

### Expected behavior

> Hostnames must be less than 63 characters in length per [Section 2.3.4 of the Domain Names Specification RFC](https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.4).

https://docs.github.com/en/enterprise-server@3.10/admin/configuring-settings/configuring-network-settings/configuring-the-hostname-for-your-instance

### Actual behavior

`hostname` gives `fv-az1272-448.grsihaubamwerhiryzjrxtypna.phxx.internal.cloudapp.net` which is longer than 64 characters.

### Repro steps

Adds a job step to output `hostname`.

**Comment by kishorekumar-anchala** [comment]
Hi @kezhuw ,

Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kezhuw  ,  We have anlayzed the issue by forking your repo. The build appears to be successful. hence closing the issue. Thanks
