### ISSUE TITLE
Issues with yarn workspaces builds on Ubuntu 22.04.5

### ISSUE THREAD

**Issue by joshcasey-aderant** [actions/runner-images#10655]
### Description

After latest build of images, when building in a focused workspace using yarn workspaces focus --production and tsc build our builds fail due to building test files that are not included in our production build. 

There has been no code changes, only noticeable change is the runners version change from 22.04.4 to 22.04.5

On the same commit, builds pass when operating system is Ubuntu 22.04.4, however now **fail**, on Ubuntu 22.04.5

Have attempted all the new Ubuntu images and the problem persists.

Any ideas?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
  Version: 20240915.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240[9](https://github.com/aderant/cloud-ar/actions/runs/10948609866/job/30400008973#step:1:10)15.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240915.1

### Is it regression?

Yes

### Expected behavior

Builds do not build test files after the dev dependencies are removed.

### Actual behavior

Builds are building code paths that should not be being built after a workspace focus on yarn

### Repro steps

Using yarn workspaces focus --production and tsc build, build project.

**Comment by aderant-smcd** [comment]
Looks like this is caused by a newer TSC version being stricter about some dependency issues, will update with full cause later - if anyone else is getting issues with yarn workspaces on the latest ubuntu runners try making your builds use tsc 5.1.3.

**Comment by joshcasey-aderant** [comment]
As above ^, we had to downgrade our TS Version on the runner as we had some compilation issues due to the newer version of TSC and this also exposed some dependency issues which required resolution.
