### ISSUE TITLE
Powershell module Az missing on Windows Server 2022

### ISSUE THREAD

**Issue by obuolinis** [actions/runner-images#10664]
### Description

Readme claims that Az module is preinstalled on Windows Server 2022 runner but it's actually missing
https://github.com/actions/runner-images/blob/win22/20240915.1/images/windows/Windows2022-Readme.md#powershell-modules

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20240915.1.0

### Is it regression?

Not sure

### Expected behavior

`Get-Module -Name Az.* -ListAvailable` should return the whole list of Az.* modules.

### Actual behavior

`Get-Module -Name Az.* -ListAvailable` returns nothing.

### Repro steps

1. Execute `Get-Module -Name Az.* -ListAvailable` using pwsh shell on a windows-latest runner.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @obuolinis  , Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @obuolinis, All Azure-specific modules are installed in the `C:\Modules` directory. However, since this path is not part of the default PSModulePath, the modules will not be available for standard `Get-* `commands, and you will need to operate on them manually, Thanks.
