### ISSUE TITLE
Homebrew packer package will vanish Sep 27th

### ISSUE THREAD

**Issue by gjasny** [actions/runner-images#10682]
### Description

Hello,

while building the Anka macOS VM images I noticed the following output:
```
    veertu-<sensitive>-vm-clone.template: Installing packer...
    veertu-<sensitive>-vm-clone.template: Downloading packer...
==> veertu-<sensitive>-vm-clone.template: Warning: packer has been deprecated! It will be disabled on 2024-09-27.
```

This is in line with the deprecation notice on the homebrew site: https://formulae.brew.sh/formula/packer. Oneway to replace it would be using `hashicorp/tap/packer` instead.

Thanks,
Gregor

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

HEAD

### Is it regression?

no

### Expected behavior

Packer installs w/o warning.

### Actual behavior

A warning is emitted.

### Repro steps

Build the Anka macOS images.

**Comment by sureshe456** [comment]
Hi @gjasny We will look in to this issue and keep you updated.

**Comment by sureshe456** [comment]
Hi @gjasny, Now Packer package is fetching and installing from hashicorp/tap/packer for all macOS images. Since there is no action item pending from our end, Hence we are closing the issue.
