### ISSUE TITLE
Update Fastlane to min 2.223.1

### ISSUE THREAD

**Issue by Baza207** [actions/runner-images#10694]
### Description

Fastlane started having a problem with the `upload_to_testflight` task as discussed in this Issue https://github.com/fastlane/fastlane/issues/22248.

This issue seems to have been fixed now, but we need to have the Fastlane tool to fix issues with uploading builds in pipelines.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

The issue is with the Fastlane tool before version 2.223.1.

### Is it regression?

No

### Expected behavior

Fastlane should allow us to upload to TestFlight.

### Actual behavior

Uploads fail waiting for processing.

### Repro steps

Upload a IPA with Fastlane prior to 2.223.1 using the `upload_to_testflight` as discussed here: https://github.com/fastlane/fastlane/issues/22248..

**Comment by dannycohn** [comment]
Yes please

**Comment by maroy1986** [comment]
> Hey there!
> 
> We install `fastlane` as a gem, so all the images built after Sep 27 will contain required version. Please wait for the image rollout.

Is there any ETA for the image to be available? I see it is marked as "Deploying" on the readme of the repository but it seems nowhere to be found yet.

This is causing our steps that use fastlane to fail. Hopefully the build still gets uploaded to TestFlight, no issues for Android, but we end up with an error in our pipeline.

Yes I could add a step in my job to update Fastlane myself but this feels counterproductive knowing an official image is on the way with it.

Thanks for everything anyway :)

**Comment by erik-bershel** [comment]
Hey @maroy1986!

> Is there any ETA for the image to be available? I see it is marked as "Deploying" on the readme for the MacOS-14 image but it seems nowhere to be found yet.

We expect the new images to be deployed in about 48 hours for `macos-13`, `macos-13-arm64` and `macos-14` (!not a YAML labels!), but no promises here - deployment process might take longer as usual. 😞  Also I should note that `macOS-14-arm64` image updating process is not yet started. We are working on providing updates ASAP. 🧑‍🏭

**Comment by erik-bershel** [comment]
👋 @maroy1986 and @Baza207 
macOS-15 images with the updated Fastlane gem are rolled out.

**Comment by maroy1986** [comment]
> 👋 @maroy1986 and @Baza207 
> macOS-15 images with the updated Fastlane gem are rolled out.

Yes I saw that, my pipelines started picking it up this morning!

Thanks for everything!

**Comment by vaishalipawar1490** [comment]
Hi @Baza207, Since there are no further action items pending from our side, we will proceed with closing this issue.
Please feel free to reach out if you have any further questions.
