### ISSUE TITLE
SSL Error: Unable to Connect to HTTPS URL for PyPy-3.10-nightly version on Windows

### ISSUE THREAD

**Issue by aparnajyothi-y** [actions/runner-images#10705]
### Description

Facing SSL Error: Unable to Connect to HTTPS URL for PyPy-3.10-nightly version on Windows -2022 and please find the [failure links](https://github.com/actions/setup-python/actions/runs/11098960252/job/30832442213) for reference.
Reference of closed [Pypi issue](https://github.com/pypi/warehouse/issues/16802)
```
jobs:
setup-pypy:
name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
fail-fast: false
matrix:
os: [windows-latest]
pypy:
- 'pypy-3.10-nightly'

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: setup-python ${{ matrix.pypy }}
    id: setup-python
    uses: ./
    with:
      python-version: ${{ matrix.pypy }}
```
```
Error we are getting is mentioned below
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
The process 'D:\a_temp\5871[35](https://github.com/actions/setup-python/actions/runs/10957214111/job/30424936558?pr=947#step:3:36)78-6f7f-47f8-a4ec-62dcdc704c0d\pypy-c-jit-185389-9ca9d9be1715-win64\python.exe' failed with exit code 1
Error: The process 'D:\a_temp\58713578-6f7f-47f8-a4ec-62dcdc704c0d\pypy-c-jit-185389-9ca9d9be1715-win64\python.exe' failed with exit code 1
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20240922.1.0

### Is it regression?

No

### Expected behavior

The workflow should run successfully like this [run](https://github.com/actions/setup-python/actions/runs/10915113556/job/30294322618) on windows

### Actual behavior

[Failure run](https://github.com/actions/setup-python/actions/runs/11098960252/job/30832442213)

### Repro steps

```
jobs:
setup-pypy:
name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
fail-fast: false
matrix:
os: [windows-latest]
pypy:
- 'pypy-3.10-nightly'

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: setup-python ${{ matrix.pypy }}
    id: setup-python
    uses: ./
    with:
      python-version: ${{ matrix.pypy }}
```

**Comment by vidyasagarnimmagaddi** [comment]
Hi @aparnajyothi-y , Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating

**Comment by aparnajyothi-y** [comment]
Hello @kishorekumar-anchala, This issue can be fixed from pypy as per this [issue](https://github.com/pypy/pypy/issues/5074) comments. I guess we can close this issue as the issue is from pypy. Thank you.
