### ISSUE TITLE
Was meson recently removed from the macos-12 image?

### ISSUE THREAD

**Issue by cpackham** [actions/runner-images#10700]
### Description

I've had a couple of build jobs fail because the meson build tool is missing on macos-12. e.g

https://github.com/crosstool-ng/crosstool-ng/actions/runs/11095948105/job/30825350756

The same build was fine in an earlier run

https://github.com/crosstool-ng/crosstool-ng/actions/runs/10914579710/job/30293040931

I notice we're not explicitly asking for meson but this seems to be a recent problem (or Hyrum's law in action).

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240916.115

https://github.com/crosstool-ng/crosstool-ng/actions/runs/11095948105/job/30825350756

### Is it regression?

20240908.1

https://github.com/crosstool-ng/crosstool-ng/actions/runs/10914579710/job/30293040931

### Expected behavior

meson should be available

### Actual behavior

meson is not available

### Repro steps

build picolibc

**Comment by cpackham** [comment]
I've made a change to explicitly install meson and ninja https://github.com/crosstool-ng/crosstool-ng/pull/2209 so I think we're OK. I suspect we were getting them via some other dependency which has now changed.

**Comment by erik-bershel** [comment]
Hey @cpackham! 👋 

Yeah, meson was one of the external dependencies in your workflow - we just never installed it.
