### ISSUE TITLE
MacOS 15 For Azure Devops

### ISSUE THREAD

**Issue by marcberman14** [actions/runner-images#10718]
### Tool name

MacOS-15

### Tool license

https://www.apple.com/au/legal/sla/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

15.0 (24A335)

### Brief description of tool

Latest major macOS version released by Apple.

### URL for tool's homepage

https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No, it's an agent.
```

Please could MacOS 15 be added to Azure Devops. This is a major concern for many mobile app developers who are dependent on the latest Mac tools being available in Devops.

We are in an enterprise situation and migrating to Github Actions or any other tool is no small task. 

If we are indeed required to migrate from Azure Devops builds to Github Actions then please provide a guide on the process

**Comment by erik-bershel** [comment]
Hey @marcberman14! 
In general it's a duplicate for https://github.com/actions/runner-images/issues/10632, but we'll keep it on the board to use as a place to notify interested parties. I'll provide all the info as soon as it become available.

**Comment by marcberman14** [comment]
What's the alternative for an Azure Devops enterprise user to build against the latest MacOS apart from paying for another service?

**Comment by erik-bershel** [comment]
Hey @marcberman14!
> What's the alternative for an Azure Devops enterprise user to build against the latest MacOS apart from paying for another service?

We are working on providing macOS-15 based hosted runners for ADO. It might take some time. Unfortunately I am not able to provide exact ETA now.

**Comment by erik-bershel** [comment]
Hey @albertoAround!
Our target is to provide it before the deprecation of Xcode 16 on macOS-14 end of this month. Will work on providing it sooner, but as I said - no promises.

**Comment by erik-bershel** [comment]
`macOS-15` is now available using `Azure DevOps` 🚀 
More info: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

**Comment by badredaha** [comment]
Hi,

I use AzureDevops Agent Specification. Who I can specify the Agent Specification with macos arm ? I can't foud it!
