### ISSUE TITLE
Update/Add buildah

### ISSUE THREAD

**Issue by ramonsmits** [actions/runner-images#10716]
### Tool name

buildah

### Tool license

Apache License 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.37.0

### Brief description of tool

Current version is pretty old and missing many bugfixes/features

/usr/bin/buildah version
  Version:         1.23.1
  Go Version:      go1.17
  Image Spec:      1.0.1
  Runtime Spec:    1.0.2-dev
  CNI Spec:        0.4.0
  libcni Version:  
  image Version:   5.[16](https://github.com/Particular/ServiceControl.Connector.MassTransit/actions/runs/11125540505/job/30913441631?pr=33#step:4:17).0
  Git Commit:      
  Built:           Thu Jan  1 00:00:00 [19](https://github.com/Particular/ServiceControl.Connector.MassTransit/actions/runs/11125540505/job/30913441631?pr=33#step:4:20)70
  OS/Arch:         linux/amd64
  BuildPlatform:   linux/amd64

### URL for tool's homepage

https://buildah.io/

### Provide a basic test case to validate the tool's functionality.

```bash
buildah version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

I would but I don't know how to provide a tool update PR

**Comment by vidyasagarnimmagaddi** [comment]
Hi @ramonsmits , Thanks for providing the issue .We will update once validated . thanks

**Comment by ramonsmits** [comment]
@vidyasagarnimmagaddi FYI:

When I do:

```
sudo apt-get update
sudo apt-get -y install buildah
```

It outputs:

```
buildah is already the newest version (1.23.1+ds1-2).
```

Which is strange.. I think it misses a repository?

**Comment by ramonsmits** [comment]
According to docs it should be part of Ubuntu

> The buildah package is available in the official repositories for Ubuntu 20.10 and newer.

Source: https://github.com/containers/buildah/blob/main/install.md#ubuntu

**Comment by lakshminarayana02** [comment]
Hi

We understand that 1.37.0 is the most recent version of Buildah, and the image presently has Buildah 1.33.7. We will continue to update the system with the most recent stable versions, so please bear with us till next week. We will keep you updated. 

ref link : https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

**Comment by lakshminarayana02** [comment]
Dear @ramonsmits 
The exact cause is still being looked into,  please bear with us.

**Comment by lakshminarayana02** [comment]
Dear @ramonsmits 

Thanks for your diligence, we understand that you required the latest version of Buildah tool,

 this version is   pinned for update and Ubuntu has 24.04 has Buildah 1.33.7 version, this version is pinned, and Ubuntu 24.04 has Buildah 1.33.7 version, we recommend to use this, and to inform you that there are many reasons that few selected tools may not be updated regularly, such as dependency conflicts, regularity, performance related, etc.

The workaround is to use the latest version in your runtime, and we will continue to monitor and update the latest version in the following days.
