### ISSUE TITLE
Update the version of Chrome shipped with the ubuntu-latest image

### ISSUE THREAD

**Issue by kenzieschmoll** [actions/runner-images#10726]
### Description

The ubuntu-latest image is currently shipped with Chrome 129.0.6668.58. This version is behind the current Chrome stable: https://googlechromelabs.github.io/chrome-for-testing/#stable. There is a bug in this Chrome version that has since been fixed, but this bug still exists for all github actions jobs running with the ubuntu-latest image due to the outdated chrome version.

Example where my team has a benchmark test that fails due to this bug in Chrome: https://github.com/flutter/devtools/actions/runs/11152974278/job/30999677139?pr=8320

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/flutter/devtools/actions/runs/11152974278/job/30999677139?pr=8320

### Is it regression?

Chrome regression.

### Expected behavior

Chrome is always on the latest stable.

### Actual behavior

The Chrome version is behind the latest stable.

### Repro steps

N/A. The bug on Chrome has already been fixed. The Chrome version on the ubuntu image (likely all platforms) just needs to be updated.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kenzieschmoll , Thanks for providing the issue .We will update once validated . thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kenzieschmoll  , the latest Chrome version on the ubuntu image , will be fixed  out in the  next image rolllout. Thanks

**Comment by kenzieschmoll** [comment]
Hi @vidyasagarnimmagaddi. Thanks for the quick fix. When can we expect the next rollout?

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kenzieschmoll  , We plan for rollout in next week with latest version .  Thanks.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @kenzieschmoll  , We started  rolling out  ubuntu images , with chrome version version as `129.0.6668.89` . thanks

**Comment by kenzieschmoll** [comment]
Thanks for the quick fix!

**Comment by vidyasagarnimmagaddi** [comment]
Hi , The Ubuntu 24 version `20241006.1` has been rolled out , We are closing this issue . thanks.
