### ISSUE TITLE
Windows 2022 image not updating .NET 8 sdk and doesn't include all feature bands

### ISSUE THREAD

**Issue by Styxxy** [actions/runner-images#10728]
### Description

Compared to the `windows-2019` image, the `windows-2022` image doesn't update .NET 8 SDK version nor does it include any of the feature bands (1xx, 2xx, 3xx). This causes the `UseDotNet` task to always have to download and install the correct .NET SDK (managed through global.json).

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240929.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20240929.1/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240929.1

### Is it regression?

No

### Expected behavior

Have the latest (at image build time) .NET 8 SDK installed as well as the latest patch of each feature band within .NET 8; which is the case in image `windows-2019`.

When running on `vmImage: windows-2019`, output of command `dotnet --list-sdks`:
```cmd
> dotnet --list-sdks

6.0.133 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
6.0.425 [C:\Program Files\dotnet\sdk]
7.0.120 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.317 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.108 [C:\Program Files\dotnet\sdk]
8.0.206 [C:\Program Files\dotnet\sdk]
8.0.304 [C:\Program Files\dotnet\sdk]
8.0.401 [C:\Program Files\dotnet\sdk]
```

### Actual behavior

All features bands of .NET 6 and .NET 7 are available, with .NET 8 only the default version `8.0.400` (which comes from the Visual Studio 2022 installer) is installed (and not patched!).

```cmd
> dotnet --list-sdks

6.0.133 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
6.0.425 [C:\Program Files\dotnet\sdk]
7.0.120 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.317 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.400 [C:\Program Files\dotnet\sdk]
```

### Repro steps

When running on `vmImage: windows-2019`, output of command `dotnet --list-sdks`:
```cmd
> dotnet --list-sdks

6.0.133 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
6.0.425 [C:\Program Files\dotnet\sdk]
7.0.120 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.317 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.108 [C:\Program Files\dotnet\sdk]
8.0.206 [C:\Program Files\dotnet\sdk]
8.0.304 [C:\Program Files\dotnet\sdk]
8.0.401 [C:\Program Files\dotnet\sdk]
```

When running on `vmImage: windows-2022`, output of command `dotnet --list-sdks`:
```cmd
> dotnet --list-sdks

6.0.133 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
6.0.425 [C:\Program Files\dotnet\sdk]
7.0.120 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.317 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.400 [C:\Program Files\dotnet\sdk]
```

**Comment by Styxxy** [comment]
It seems like version "8.0" should be added here to make it work:
https://github.com/actions/runner-images/blob/7bf4ada29d08793066edab9bd6a16dc3c5ffff27/images/windows/toolsets/toolset-2022.json#L315-L324

If comparing to the image toolset definition of `windows-2019` it is included there:
https://github.com/actions/runner-images/blob/7bf4ada29d08793066edab9bd6a16dc3c5ffff27/images/windows/toolsets/toolset-2019.json#L408-L418

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Styxxy , Thanks for providing the issue .We will update once validated . thanks

**Comment by lakshminarayana02** [comment]
Hi 
we are working on it and will keep you posted with the latest updates.

**Comment by MarkusRodler** [comment]
I think I have the same problem with ubuntu-latest:
![Bildschirmfoto_11-10-2024_123632_github com](https://github.com/user-attachments/assets/bbf45a44-e792-42ba-8766-4e1fa6712069)

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Styxxy  ,.Net 8 SDK  is rolled out in the new image '20241113.3.0` .thanks
