### ISSUE TITLE
PowerShell modules Az* missing on ubuntu-latest

### ISSUE THREAD

**Issue by dronkoff** [actions/runner-images#10733]
### Description

When running a PowerShell step, there are no Az* modules visible to PWSH.

The reason is that Az* modules are installed to `/usr/share/az_12.1.0` (see [Install-PowerShellAzModules.ps1](https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1) ) and this path is **not** in the `PSModulePath `environment variable (`/home/runner/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules`) . 
Modules present on runner file system, but pwsh can't see them.

Workaround: 
Add this line at the beginning of a PowerShell run step.
```
$env:PSModulePath += ":/usr/share/az_12.1.0"
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.319.1'
Operating System
  Ubuntu
  [2](...)2.04.5
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20240922.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240922.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240922.1

### Is it regression?

don't know

### Expected behavior

A list of modules including Az* modules.

### Actual behavior

No Az* modules visible to PowerShell.

### Repro steps

Running this code 
```
    - name: PWSH as a shell
      run: |
        Get-Module -ListAvailable  | FT Name, Version
      shell: pwsh
```
produces the following list of modules.
There should be a list of Az modules as well, but there are non.
```
Name                                            Version
----                                            -------
MarkdownPS                                      1.10
Microsoft.Graph                                 2.23.0
Microsoft.Graph.Applications                    2.23.0
Microsoft.Graph.Authentication                  2.23.0
Microsoft.Graph.BackupRestore                   2.23.0
Microsoft.Graph.Bookings                        2.23.0
Microsoft.Graph.Calendar                        2.23.0
Microsoft.Graph.ChangeNotifications             2.23.0
Microsoft.Graph.CloudCommunications             2.23.0
Microsoft.Graph.Compliance                      2.23.0
Microsoft.Graph.CrossDeviceExperiences          2.23.0
Microsoft.Graph.DeviceManagement                2.23.0
Microsoft.Graph.DeviceManagement.Actions        2.23.0
Microsoft.Graph.DeviceManagement.Administration 2.23.0
Microsoft.Graph.DeviceManagement.Enrollment     2.23.0
Microsoft.Graph.DeviceManagement.Functions      2.23.0
Microsoft.Graph.Devices.CloudPrint              2.23.0
Microsoft.Graph.Devices.CorporateManagement     2.23.0
Microsoft.Graph.Devices.ServiceAnnouncement     2.23.0
Microsoft.Graph.DirectoryObjects                2.23.0
Microsoft.Graph.Education                       2.23.0
Microsoft.Graph.Files                           2.23.0
Microsoft.Graph.Groups                          2.23.0
Microsoft.Graph.Identity.DirectoryManagement    2.23.0
Microsoft.Graph.Identity.Governance             2.23.0
Microsoft.Graph.Identity.Partner                2.23.0
Microsoft.Graph.Identity.SignIns                2.23.0
Microsoft.Graph.Mail                            2.23.0
Microsoft.Graph.Notes                           2.23.0
Microsoft.Graph.People                          2.23.0
Microsoft.Graph.PersonalContacts                2.23.0
Microsoft.Graph.Planner                         2.23.0
Microsoft.Graph.Reports                         2.23.0
Microsoft.Graph.SchemaExtensions                2.23.0
Microsoft.Graph.Search                          2.23.0
Microsoft.Graph.Security                        2.23.0
Microsoft.Graph.Sites                           2.23.0
Microsoft.Graph.Teams                           2.23.0
Microsoft.Graph.Users                           2.23.0
Microsoft.Graph.Users.Actions                   2.23.0
Microsoft.Graph.Users.Functions                 2.23.0
Pester                                          5.6.1
PSScriptAnalyzer                                1.22.0
Microsoft.PowerShell.Archive                    1.2.5
Microsoft.PowerShell.Host                       7.0.0.0
Microsoft.PowerShell.Management                 7.0.0.0
Microsoft.PowerShell.PSResourceGet              1.0.4.1
Microsoft.PowerShell.Security                   7.0.0.0
Microsoft.PowerShell.Utility                    7.0.0.0
PackageManagement                               1.4.8.1
PowerShellGet                                   2.2.5
PSReadLine                                      2.3.5
ThreadJob                                       2.0.3
```

**Comment by hemanthmanga** [comment]
Hi @dronkoff, Thank you for bringing this issue, we will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @dronkoff, Due to some maintenance concerns we are not making any changes for now, we are closing this issue,Thanks.

**Comment by dronkoff** [comment]
I didn't get it. Is it fixed or will be fixed?

**Comment by joshfrias** [comment]
You've got to be kidding me here. This breaks everyone using the running images with the modules and isn't going to be fixed?

**Comment by dronkoff** [comment]
Well, you can use `azure/powershell@v2` which fixes this bug for you, but I don't see reasons not to do `$env:PSModulePath += ":/usr/share/az_12.1.0"` out of the box.

**Comment by joshfrias** [comment]
Because the version keeps updating and then I'm put up with the maintenance burden of adding extra steps to discover modules.

**Comment by kohtala** [comment]
You can just add

    $env:PSModulePath = $env:PSModulePath + ":/usr/share"

But I too don't understand the _some maintenance concerns_ explanation to closing this. azure/login also uses this kind of trick. For Windows it'd be `;C:\\Modules`.

**Comment by andrej98** [comment]
Even if I add this to my task:
```
$env:PSModulePath = $env:PSModulePath + ":/usr/share"
```
It does not solve the problem, because in the next tasks in the same job, the `$env:PSModulePath` variable is not updated. 
I hoped I can modify the path in just one task and the other tasks are going to have it available. 

If I have other tasks that are not directly script/powershell, but instead some other program execution that internally calls PowerShell Az modules, it does not fix this problem.

Why not just include it in the `PSModulePath` by default, as in the windows images?
