### ISSUE TITLE
20240929.1.0 Windows runner image breaks Python virtualenv

### ISSUE THREAD

**Issue by MarkCallow** [actions/runner-images#10749]
### Description

After the update of the Windows runner image to 20240929.1.0 my builds break with

```
ERROR Failed to create venv. Maybe try installing virtualenv.
```

The only change since the last successful build is the runner image update.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image version: 20240929.1.0

Failed build: https://github.com/KhronosGroup/KTX-Software/actions/runs/11174988721/job/31065570054

### Is it regression?

Yes. Latest working image is 20240915.1.0. Latest successful build is https://github.com/KhronosGroup/KTX-Software/actions/runs/11028019847/job/30627418606

### Expected behavior

I expected my Python builds to still work.

### Actual behavior

The python builds fail with an error that look like `virtualenv` was removed from the image. However the change logs for 20240929.1.0 show no changes to any Python components.

### Repro steps

The easiest way to repro is just to run a build of https://github.com/KhronosGroup/KTX-Software/actions/runs/11174988721/job/31065570054.

More detailed steps.
1. Set up a Python project with a `requirements.txt` listing required python packages. I'm using CMake to my Python stuff as part of a larger project but this probably isn't a necessary condition.
2. As part of the build process for the project do:
    ```
    python3 -m pip install --no-warn-script-location -r ${SOURCE_DIR}/requirements.txt
    ````
4. Set up CI with a step that installs Python:
    ```
    name: Set up Python 3.11
      if: matrix.options.py == 'ON' && matrix.check_mkvk != 'ONLY'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
    ```
5.  Add a build step that does:
    ```
    run: |
      cmake . -B build
      cmake --build build
    ```

**Comment by MarkCallow** [comment]
I am relatively new to Python and did not write the Python parts of our project. Therefore I am not sure what determines that `virtualenv` should be used when using a Windows runner image. Consequently I am not sure if the error is
* because something has changed to trigger use of virtualenv and it never existed and doesn't exist in the image
* or because virtualenv was removed from the latest image.

I am surprised, judging from the lack of an existing bug report, that nobody else seems to have encountered this problem.

I have tried to install virtualenv using `pipx install virtualenv` in a step after the step that installs Python. The installation appears to be successful but I still get the same error.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @MarkCallow , thank you for bringing this issue. We will update you once validated. Thanks .

**Comment by MarkCallow** [comment]
I used `pip` instead of `pipx` to install virtualenv: `pip install virtualenv`. It works. So it looks like virtualenv was removed from the image and the removal escaped the generator of the change list.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @MarkCallow , is the issue resolved ..?

**Comment by MarkCallow** [comment]
> is the issue resolved

Only in that I've got my build working again. The runner image is broken. A previously supported featured was removed. Given the lack of info in the change list it does not look intentional. If I'm the only one complaining you may not care but I think virtualenv is widely used by Python projects hence my surprise at the lack of other bug reports.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @MarkCallow , thanks for the confirmation , we try to gather the necessary requests from customer , based on the number of requests will consider including in images.
As in  moment we are trying to make the images as light as possible .thanks .closing this issue.

**Comment by MarkCallow** [comment]
> Hi @MarkCallow , thanks for the confirmation , we try to gather the necessary requests from customer , based on the number of requests will consider including in images.

I think you have that backwards. As virtualenv was included in the images previously but has now been removed there will not previously have been any requests to add it.

>  As in moment we are trying to make the images as light as possible .thanks .closing this issue.

At most this is going to save some kbytes on your image storage and shave a few milliseconds off booting a virtual machine.

There is nothing in my python project that explicitly requests use of a virtualenv. It is the python `build module` that is requesting it for both of the following commands executed while building my target:

```
${PYTHON_EXECUTABLE} -m build --sdist --outdir ${DIST_DIR}

${PYTHON_EXECUTABLE} -m build --wheel --outdir ${DIST_DIR}
```

I suspect both sdist and wheel are widely used in Python projects and therefore need to be built and will thus now encounter the absence of virtualenv.

Please reopen this issue.

**Comment by MarkCallow** [comment]
I used `pip` instead of `pipx` to install virtualenv: `pip install virtualenv`. It works. So it looks like virtualenv was removed from the image and the removal escaped the generator of the change list.
