### ISSUE TITLE
Cache@2 frequently failed with Access denied Linux RHEL image

### ISSUE THREAD

**Issue by xinyuxu1026** [actions/runner-images#10747]
### Description

Cache@2 failed with Access denied every couple days.
Example runs:
[Restore compiled Python3.7 failed](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1369774&view=logs&j=2d0d219d-b8ac-5de9-8c39-2faacaf89005&t=31cedac6-5db0-57dc-e8e7-99755dc0e644)
[Restore compiled Python3.9 failed](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1371645&view=logs&j=39a2a1c6-51e7-579d-c072-d6effd7c89ca&t=7ab91629-9cfe-5483-0147-62930813c719)
```
Task         : Cache
Description  : Cache files between runs
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - "Python"   [string]
 - "3.9.20"   [string]
 - "rhel_8_2" [string]
Resolved to: "Python"|"3.9.20"|"rhel_8_2"
Using default max parallelism.
Using default max parallelism.
Max dedup parallelism: 192
DomainId: 0
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 1cc047fe-8cc7-4c4c-9ca3-915a25557f44
Hashtype: Dedup64K
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `"Python"|"3.9.20"|"rhel_8_2"`
There is a cache hit: `"Python"|"3.9.20"|"rhel_8_2"`
Used scope: 1497;a7934fdd-dcde-4492-a406-7fad6ac00e17;refs/pull/4405/merge;AzureAD/microsoft-authentication-library-for-cpp
Missed on the following scopes: 1497;a7934fdd-dcde-4492-a406-7fad6ac00e17;refs/heads/tongyuze/add-usgov-check;AzureAD/microsoft-authentication-library-for-cpp, 1497;a7934fdd-dcde-4492-a406-7fad6ac00e17;refs/heads/develop;AzureAD/microsoft-authentication-library-for-cpp, 1497;a7934fdd-dcde-4492-a406-7fad6ac00e17;refs/heads/develop;AzureAD/microsoft-authentication-library-for-cpp
Entry found at fingerprint: `"Python"|"3.9.20"|"rhel_8_2"`
ApplicationInsightsTelemetrySender correlated 3 events with X-TFS-Session 1cc047fe-8cc7-4c4c-9ca3-915a25557f44
##[error]Access to the path '/mnt/vss/_work/_tool/Python/3.9.20' is denied.
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: 8.10.2024070513

### Is it regression?

Not sure

### Expected behavior

It should not fail with access denied.

### Actual behavior

Cache@2 failed with Access denied every couple days.

##[error]Access to the path '/mnt/vss/_work/_tool/Python/3.9.20' is denied.

### Repro steps

1. create the Cache@2 job
2. wait for a few days and it failed with access denied.

**Comment by Prabhatkumar59** [comment]
Hi @xinyuxu1026 - Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
Hi @xinyuxu1026 ,

   The issue which you're facing is not belongs to images, i suspect the issue with configuration variables. kindy refer below official link for more information. Thank you ! 
   
  [ Link1 ](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget)
  
 [ LInk2](https://stackoverflow.com/questions/78342976/cache2-azure-devops-pipeline-task-fails)
