### ISSUE TITLE
Crashes on iOS simulator on MacOS images (AccessibilityControlExtension)

### ISSUE THREAD

**Issue by githubursul** [actions/runner-images#10746]
### Description

Periodic crashes of processes on iOS Simulator, leading to UX tests failures, Processes crashing:
- Prosesses in WebProcess pool (GPUProcess)
- AccessibilityControlExtension - may of may not be related

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1367703&view=logs&s=2b1cf740-7e83-5b38-9f56-89c750cf5d77&j=17b33f93-55d8-50b9-7cc6-cef868e6389b

Image version: 20240923.101

### Is it regression?

Not sure

### Expected behavior

Processes in WebProcess pool should not crash. 

### Actual behavior

Periodic crashes of processes on iOS Simulator, leading to UX tests failures, Processes crashing:
- Prosesses in WebProcess pool (GPUProcess)
- AccessibilityControlExtension - may of may not be related
[crash_dumps_and_logs.zip](https://github.com/user-attachments/files/17282213/crash_dumps_and_logs.zip)

### Repro steps

Run UI XCTest tests on iOS Simulator that involve WKWebView, for example - AAD or MSA sign-in. Periodically you will see failures due to GPUProcess process becoming unresponsive (likely a crash).

**Comment by sarathrajsrinivasan** [comment]
Hi @githubursul , 

We are looking into it. Will keep you posted.

**Comment by susmitamane** [comment]
Hi @githubursul New images have deployed this week 🎉

Could you please check and confirm if the issue still persist. If yes then could you please help us by providing more information to reproduce this issue?

Thank you.

**Comment by susmitamane** [comment]
Hi @githubursul Closing this issue for now, as no response on asked details for 3+ weeks.

Please open new issue if you are still facing similar issue with your workflows.

Thank you.
