### ISSUE TITLE
Visual Studio Signature thumbprint do not match expected

### ISSUE THREAD

**Issue by MathijsHofkens** [actions/runner-images#10753]
### Description

azure-arm.build_gallery_image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.build_gallery_image: Package downloaded in 0.3 seconds
    azure-arm.build_gallery_image: Signature thumbprint do not match expected.
    azure-arm.build_gallery_image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.build_gallery_image: +         throw "Signature thumbprint do not match expected."
    azure-arm.build_gallery_image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.build_gallery_image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.build_gallery_image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows2022

### Is it regression?

no

### Expected behavior

Download visual studio enterprise bootstrapper

### Actual behavior

azure-arm.build_gallery_image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.build_gallery_image: Package downloaded in 0.3 seconds
    azure-arm.build_gallery_image: Signature thumbprint do not match expected.
    azure-arm.build_gallery_image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.build_gallery_image: +         throw "Signature thumbprint do not match expected."
    azure-arm.build_gallery_image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.build_gallery_image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.build_gallery_image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

### Repro steps

Run the create VM pipeline for windows2022

**Comment by vidyasagarnimmagaddi** [comment]
Hi @MathijsHofkens  , Thanks for bringing the issue. We will update once issue is fixed. thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @MathijsHofkens , the signature has been updated. Kindly retry by forking latest code from main branch.
Closing this issue,Thank you.

**Comment by MathijsHofkens** [comment]
Hi @vidyasagarnimmagaddi, visual studio is installing right now but VSIX does not seem to install properly. Created #10755
