### ISSUE TITLE
Add Pack CLI from Buildpacks.io

### ISSUE THREAD

**Issue by AHuusom** [actions/runner-images#10752]
### Tool name

Pack CLI

### Tool license

I don't know. None I guess.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

Pack CLI is a command-line tool from Buildpacks.io, part of the Cloud Native Buildpacks project under the CNCF. It automates the process of building container images directly from application source code without the need for a Dockerfile. Pack CLI leverages buildpacks to detect the appropriate runtime, install dependencies, and create production-ready containers, streamlining the developer experience. It's ideal for building, testing, and managing containerized applications across cloud platforms.

### URL for tool's homepage

https://buildpacks.io/

### Provide a basic test case to validate the tool's functionality.

```bash
I don't have one. My company asked for it to be installed.
I personally don't know how to use it, I just manage the buildservers.
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Ubuntu:
pack can be installed using the official PPA by running the following commands:

sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
sudo apt-get update
sudo apt-get install pack-cli

Windows:
To install pack on Windows, we recommend using Chocolatey:

choco install pack --version=0.35.1

MacOS:
pack can be installed via Homebrew:

brew install buildpacks/tap/pack
```

### Tool installation time in runtime

Don't know

### Are you willing to submit a PR?

If I knew how I would.

**Comment by vaishalipawar1490** [comment]
Hi @AHuusom, Please note that for macOS, we are currently focusing on keeping the images as lightweight as possible by avoiding the pre-installation of programs and packages that can be easily and quickly added at runtime. We acknowledge your cooperation. 

Please try using the following command:
brew install buildpacks/tap/pack 
pack --version

Thank you.

**Comment by lakshminarayana02** [comment]
Hi @AHuusom 

We understand  that Buildpacks  will improve the developer experience and portability, but these kinds of tools may be installed during  runtime. Kindly adhere to the same.

We will definitely look into if more people want this tool be included in the OS image.
