### ISSUE TITLE
Network issues with macOS 14 20241007.259

### ISSUE THREAD

**Issue by yambaypaulcandido** [actions/runner-images#10760]
### Description

Not sure if this is an issue with the image (20241007.259) or a general github/internet connectivity issue but trying to download additional software using curl is failing. The connection keeps getting reset with the following error:
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
I tried forcing it to http 1.1 but that also failed with a different error
curl: (18) transfer closed with 837732267 bytes remaining to read
This is downloading from a url on the microsoft.com domain and works when I run the curl command locally. There has been no recent changes to the build script and the most recent build that succeeded was around 24hrs ago which ran on image verion 20240922.1

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-14-arm64
Version: 20241007.259

### Is it regression?

20240922.1

### Expected behavior

That the file will download without error or interruption.

### Actual behavior

File download interrupted by what seems to be network issues.

### Repro steps

Download a large file using curl

**Comment by sureshe456** [comment]
@yambaypaulcandido, We will look into the issue and keep you updated.

**Comment by yambaypaulcandido** [comment]
> @yambaypaulcandido, We will look into the issue and keep you updated.

@sureshe456 It seems the issue might have been cleared up and been a general connectivity issue. Our latest build just completed and downloaded all files successfully.

**Comment by yambaypaulcandido** [comment]
@sureshe456 Actually this is still happening, just happened on our latest build. Have you had any chance to investigate if this is an issue with the image?

**Comment by yambaypaulcandido** [comment]
Just another update, this is unfortnunatly still happening

**Comment by aartis17** [comment]
We are still analysing the issue. Will keep you posted.

**Comment by aartis17** [comment]
Hi @yambaypaulcandido, Can you please share the size of file which you are trying to consumed, I tried with 5 GB size file and its downloading successfully, we are seeing no issue with this file.

**Comment by HinTak** [comment]
I am seeing a regression of 14.7 vs 14.6.1, of looking for a matching python package via pip, using the macos-latest label, within the last month. Could this be related?

**Comment by HinTak** [comment]
Pip of course tries to download.

**Comment by yambaypaulcandido** [comment]
> Hi @yambaypaulcandido, Can you please share the size of file which you are trying to consume, I tried downloading 5 GB size file multiple times and its downloading successfully, we are seeing no issue with this file.

I believe this has been resolved, our github builds are building more reliably now and have stopped running into this connectivity issues. This must have been some other issue (potentially route issue between github and microsoft) and just coincidently happened at the same time as the mac-os image was updated.
