### ISSUE TITLE
sbt is missing in the latest ubuntu runner release

### ISSUE THREAD

**Issue by sebastianfeduniak** [actions/runner-images#10767]
### Description

My pipelines depend on `sbt` installed on the runner.
It was included in the previous versions of ubuntu runner.
It's available in the previous version: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L66
But not available in the latest version: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L58

In effect, my builds started failing.

I didn't find announcement regarding it. Is it a bug or you won't provide sbt for now on?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

It's available in the previous version: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L66
But not available in the latest version: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L58

### Is it regression?

ubuntu-22.04

### Expected behavior

sbt is available

### Actual behavior

sbt is not available

### Repro steps

1. Run anything using `sbt` in the latest ubuntu runner version.
2. It fails because of missing `sbt` binary.

**Comment by Prabhatkumar59** [comment]
Hi @sebastianfeduniak - Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
HI @sebastianfeduniak ,

   Previously `ubuntu-latest` tag with ubuntu-22.04 image and now` -latest` tag with ubuntu-24.04 . 
   
   I request that please use ubuntu-22.04 version and run the pipeline ; it would work . 
   
   Thank you !

**Comment by Prabhatkumar59** [comment]
Hi @sebastianfeduniak - Thank you for your input. As @kishorekumar-anchala mentioned to use **ubuntu-22.04 version**  to ensure the pipeline runs successfully. While I understand your preference for using the latest versions, this approach can help mitigate the issue.
Please proceed with @kishorekumar-anchala  suggestion. Thanks!

**Comment by soroshansari** [comment]
I have a similar issue with `gcloud` and fixed it by adding this additional step to set up Cloud SDK first.

```
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
```

**Comment by kevin-lee** [comment]
`macos-latest` has the same issue.
https://github.com/kevin-lee/jdk-sym-link/actions/runs/11304980267/job/31443978394
![Screenshot 2024-10-12 at 9 44 37 pm](https://github.com/user-attachments/assets/af44fee7-8150-46b7-9baa-e41b42c92256)

I think any version higher than macOS 12 has this problem.
* [macos-12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#project-management) has `sbt`.
* [macos-13](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#project-management) doesn't have it.
* [macos-13-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md#project-management) doesn't have it.
* [macos-14](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#project-management) doesn't have it.
* [macos-14-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#project-management) doesn't have it.
* [macos-15](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#project-management) doesn't have it.
* [macos-15-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md#project-management) doesn't have it.

**Comment by armanbilge** [comment]
fyi
- https://github.com/actions/runner-images/issues/9837#issuecomment-2107335260

**Comment by kevin-lee** [comment]
> fyi
> 
> * [Add `sbt` to macOS 13 and macOS 14 #9837 (comment)](https://github.com/actions/runner-images/issues/9837#issuecomment-2107335260)

@armanbilge Thank you so much. Also by following the link from that issue, I found that there is `sbt/setup-sbt`.
https://github.com/actions/setup-java/issues/627#issuecomment-2184234779

**Comment by vidyasagarnimmagaddi** [comment]
Hi All, This issue will be taken care under [10788](https://github.com/actions/runner-images/issues/10788) .
