### ISSUE TITLE
Latest 24.04 image update breaking CDKTF Deployment

### ISSUE THREAD

**Issue by newknowledg** [actions/runner-images#10764]
### Description

After the image update on 10 10 2024 at roughly 2:00 pm EDT the CDKTF-CLI application stopped working.
I was able to run the command successfully up until this time and I am able to use the 22.04 image currently without issue.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://github.com/user-attachments/assets/3db0b341-b13b-4607-b236-fabc249354ff)
https://github.com/newknowledg/CDKTF_AWS/actions/runs/11279609832/job/31370731482

### Is it regression?

22.04

### Expected behavior

CDKTF-CLI tool should run without errors and successfully deploy the resources generated from the scripts.

### Actual behavior

Error
 `[2024-10-10T18:11:18.694] [INFO] default - Unable to determine Terraform version: Error: Terraform CLI not present - Please install a current version https://learn.hashicorp.com/terraform/getting-started/install.html
`

### Repro steps

Run

jobs:
  tf_deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: install dependencies
        run: |
          npm install --force
          npm install -g cdktf-cli@latest --force
      - name: CDKTF Synth
        run: |
          cdktf --app "npx ts-node main.ts" synth

**Comment by mikehardy** [comment]
Terraform was documented as removed in the step between ubuntu 22 and 24
you'll need to install it now rather than relying on it being in the system image

action to install it --> https://github.com/marketplace/actions/hashicorp-setup-terraform

**Comment by newknowledg** [comment]
> Terraform was documented as removed in the step between ubuntu 22 and 24 you'll need to install it now rather than relying on it being in the system image
> 
> action to install it --> https://github.com/marketplace/actions/hashicorp-setup-terraform

This resolved my issue. Thank you

**Comment by newknowledg** [comment]
This issue is resolved

**Comment by sungmincs** [comment]
While adding `setup-terraform` fixed the issue this looks like a breaking change, and could've been communicated better.
It wasn't mentioned in any of these announcements here on this page, and I had to go through the actual changelog to find what's wrong with the build. 

It says it's removed for /maintenance reasons. Does that mean it is removed forever from the version? or it's a temporary removal?
