### ISSUE TITLE
macos-14/macos-15 runners have the same hw.uuid

### ISSUE THREAD

**Issue by StephenHodgson** [actions/runner-images#10773]
### Description

The macos-14/macos-15 runner instances have the same hw.uuid which is preventing licensed software from properly activating during our builds.

Regression from macos-13 runners.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.320.0'
Operating System
  macOS
  15.0
  24A335
Runner Image
  Image: macos-15-arm64
  Version: 20241007.159
  Included Software: https://github.com/actions/runner-images/blob/macos-15-arm64/20241007.159/images/macos/macos-15-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-15-arm64%2F20241007.159

### Is it regression?

yes from macos-13

### Expected behavior

machine hw.uuids should be unique for each ephemeral runner.

### Actual behavior

machine hw.uuids are the same for each respective runner os, which causes our licensed software to reject activations and has to be ran one at a time across all our repos.

### Repro steps

not easily reproducible, since timing is a factor when activating the software licenses.

**Comment by prasanjitsahoo** [comment]
Hi @StephenHodgson We'll investigate the issue and keep you posted with any updates

**Comment by aartis17** [comment]
Hi @StephenHodgson,
Thank you for your patience. I apologise for the delay in addressing your issue. 
The arm64 macOS runners do not have a static UUID/UDID assigned to them because Apple does not support this feature. 
This is the limitations of arm64 macOS runners.
but for generating the UUID dynamically during build, you can use system_profiler command in workflow file.
Please let me know if there's any further questions.

**Comment by StephenHodgson** [comment]
What is `system_profiler` and how would I use it?

**Comment by StephenHodgson** [comment]
> The arm64 macOS runners do not have a static UUID/UDID assigned to them because Apple does not support this feature.

Actually the problem is the ***opposite*** of this. 

The hw/uuids are always the same which is what is causing the problems.

**Comment by lakshminarayana02** [comment]
HI
we understand that each runner need a unique hw.uuid. This would allow the licenced software to recognise them as autonomous system  and allow activation on several runners at the same time, checking  whether Apple allows for a unique identity for arm64 runners in future releases,  We ensure that it will be included if Apple allows this feature. 

However, this feature is no longer available, thus we're closing this issue.

**Comment by lakshminarayana02** [comment]
..

**Comment by lakshminarayana02** [comment]
However, this feature is no longer available, thus we're closing this issue.

**Comment by lakshminarayana02** [comment]
However, this feature is no longer available, thus we're closing this issue.

**Comment by StephenHodgson** [comment]
Not really a feature, but a requirement.

Closing doesn't make it magically better.
