### ISSUE TITLE
Update/Add imagemagick

### ISSUE THREAD

**Issue by zoezhangmattr** [actions/runner-images#10772]
### Tool name

imagemagick

### Tool license

https://github.com/ImageMagick/ImageMagick/blob/main/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

80mb

### Brief description of tool

the tool is installed in ubuntu 2204, but not in ubuntu2404, when we start to use 2404 from 2204 this is missing
is it possible to add it to 2404 as well please

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by RaviAkshintala** [comment]
Hi @zoezhangmattr Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by lakshminarayana02** [comment]
Hi @zoezhangmattr 
Thank you for contacting us. We have not included imagemagick and a few other tools to maintain the lightweight Ubuntu 24.04 image to optimise performance,  however, we kindly request that you include them in your runtime environment as needed.

**Comment by tvdeyen** [comment]
Shouldnt it be have closed as "wont fix"?
