### ISSUE TITLE
heroku: command not found error on ubuntu/latest

### ISSUE THREAD

**Issue by stephenhmarsh** [actions/runner-images#10786]
### Description

previously this step was working fine, suddenly started throwing an error today:

<img width="1058" alt="Screenshot 2024-10-15 at 12 06 05 PM" src="https://github.com/user-attachments/assets/1962affb-085e-46db-95d3-aafd6ddb7cf7">

there were no announcments in https://github.com/actions/runner-images/blob/ubuntu24/20241006.1/images/ubuntu/Ubuntu2404-Readme.md but it no longer lists Heroku as installed software?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.320.0'
Operating System
  Ubuntu
  24.04.1
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20241006.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20241006.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20241006.1
Runner Image Provisioner
  2.0.384.1
  ```

### Is it regression?

yes / ubuntu-22.04 / 20241006.1.0 / https://github.com/metmuseum/met-js/actions/runs/11294535025

### Expected behavior

heroku should be an available command

### Actual behavior

heroku command not found

### Repro steps

try to use a command like `heroku login` - it is available in 22.04 but not 24.04

**Comment by vidyasagarnimmagaddi** [comment]
Hi @stephenhmarsh , 
Earlier `Ubuntu-latest` tag is with ubuntu-22.04 image and now `-latest` tag with ubuntu-24.04 .
Due to maintenance concerns  Heroku is not part of `Ubuntu-24`.
Kindly install the same at runtime.
Thank you !

**Comment by lethib** [comment]
Faced the same issue for my deployments !
Solved by adding the following step **before** using the Heroku CLI 👇

```yml
- name: Install Heroku CLI
   run: |
     curl https://cli-assets.heroku.com/install.sh | sh
```
Source: https://devcenter.heroku.com/articles/heroku-cli#standalone-installation-with-a-tarball

**Comment by stephenhmarsh** [comment]
thanks @lethib for the solve

**Comment by vidyasagarnimmagaddi** [comment]
Hi @stephenhmarsh , kindly install the same at runtime. thanks closing this issue.

**Comment by DevboiDesigns** [comment]
works!
