### ISSUE TITLE
ubuntu-latest bump from 22 to 24 fails to include sbt, nvm, and probably more

### ISSUE THREAD

**Issue by ljharb** [actions/runner-images#10788]
### Description

See https://twitter.com/ljharb/status/1846298893447004498

Namely, with no announcement, the Ubuntu version seems to have been bumped from 22 to 24, and the current images fail to ship nvm, as well as sbt, and presumably a lot more.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/tc39/ecma262/actions/runs/11268873692 works

https://github.com/tc39/ecma262/actions/runs/11354432242 does not

### Is it regression?

yes

### Expected behavior

I expect nvm and sbt to be available by default on the ubuntu image, always.

### Actual behavior

They aren't there.

### Repro steps

See https://github.com/tc39/ecma262/actions/runs/11354432242

**Comment by ljharb** [comment]
While I eventually discovered https://github.com/actions/runner-images/issues/10636, given that github has advised everyone to use "latest" for years, it's just not acceptable to ever ship breaking changes that aren't absolutely necessary.

**Comment by RaviAkshintala** [comment]
Hi @ljharb Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by voxpelli** [comment]
[The announcement](https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/) of the `ubuntu-24.04` runner image beta linked to a list of the included software rather than the diff that's included in the #10636 issue. Neither is it in the [general availability announcement](https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/) (which is the same which announced the `ubuntu-latest` move)

I think that's one of the issues here – I follow the announcements on the blog, but the initial beta announcement simply said:

> Some users may notice differences in workflows as the Ubuntu 22.04 image has different tools and tool versions, see the [full list](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) of changed software.

And the `full list` is the actual full list, not the diff that #10636 has.

**Comment by tsawada** [comment]
@kishorekumar-anchala 
Thank you for working on this issue. I understand the need to carefully decide what should be included, but I'd really appreciate if you consider keeping sbt in the image.

`sbt` is [a lightweight shellscript](https://github.com/sbt/sbt/blob/52cf06d80ec42df22ea8575afa896ce5d67c79fe/sbt).  It is less than 30KB with no new dependencies required on the image (just curl). It reads the version from build files  and downloads the necessary binary, thus the script is independent from the binary version, and the script itself rarely needs updates.

Currently, [14k+ workflows](https://github.com/search?type=code&q=path%3A.github%2Fworkflows+sbt+language%3AYAML+ubuntu-latest+sbt) rely on sbt in ubuntu-latest. Rolling out 22.04 as is will break all these builds, potentially causing hundreds of users to spend significant amount of time in total, for troubleshooting, fixing, reviewing, and merging changes to address the incompatibility.

I believe including this small script in the bin directory and preserving the current behavior will improve the overall developer experience, more than the amount of cost and effort required.

Thank you for considering this request!

**Comment by hughsimpson** [comment]
For those who're missing `sbt` support, adding a cheeky `- uses: sbt/setup-sbt@v1` step should be enough to work with 24.x. I don't see it ever being added back to the base since it's been dropped from mac images too.
