### ISSUE TITLE
Terraform is not found in ubuntu-latest

### ISSUE THREAD

**Issue by ANavakahtsky** [actions/runner-images#10796]
### Description

Terraform scripts do not work when 'runs-on' still references `ubuntu-latest` in github actions, but in fact uses 24.04.1 version instead 22.04.5.

I get `terraform: command not found Error: Process completed with exit code 127` error when try to run `terraform init`.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Operating System: Ubuntu 24.04.1 LTS
Runner Image: ubuntu-24.04 (20241006.1.0) 

### Is it regression?

Yes. Ubuntu 22.04.5 LTS, Runner Image ubuntu-22.04 (20241006.1.0)

### Expected behavior

Terraform is installed and is a part of an Ubuntu 24.04 image.

### Actual behavior

Terraform not fount in Ubuntu 24.04 runner image.

### Repro steps

Try run 'terraform init' within ubuntu-latest github action.

**Comment by ANavakahtsky** [comment]
`runs-on: ubuntu-22.04` fixes this issue, but does not seem to be aligned with recommended strategy to use `ubuntu@latest`.

**Comment by hemanthmanga** [comment]
Hi @ANavakahtsky Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by cahitihac** [comment]
Terraform is not included in the list of installed softwares here: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

But it's available here: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

Looks like for some reasons they decided to exclude it.

**Comment by nmodi1** [comment]
It has been a few months and new versions of Terraform have been released in the mean-time. Could you please investigate if it can be re-added to the runners now? Or could you let us know what security concerns you have that caused it to be removed from the runners?
