### ISSUE TITLE
Android SDK Build Tools doesn't exists on macOS runners on default

### ISSUE THREAD

**Issue by mcagabe19** [actions/runner-images#10814]
### Description

title and I use `ANDROID_HOME` env btw

(sorry if something is wrong, I'm first time making issue to here)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [x] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20241014.193
Link to build: https://github.com/MobilePorting/FPS-Plus-Mobile/actions/runs/11408800443/job/31747750013

### Is it regression?

uhhh no ig?

### Expected behavior

To Build

### Actual behavior

build-tools is missing or misplaced, idk really

### Repro steps

1. Set sdk path to lime
2. Run a build
3. Getting build-tools missing

**Comment by mcagabe19** [comment]
after some digging and using `find` on `$ANDROID_HOME`, I can confirm it's really not there

**Comment by sarathrajsrinivasan** [comment]
Hi @mcagabe19 ,

We are looking into it. Will keep you posted.

**Comment by sarathrajsrinivasan** [comment]
Hi @mcagabe19 ,

We are able to see the Android SDK Build tools in all macOS12, macOS13 and macOS14 images. 

We are investigating for macOS15. In the meantime please check your workflow with either macOS13 or macOS14.
```
    steps: 
    - name: Check Android SDK Build tools
      run: |
        echo "ANDROID_HOME is set to: $ANDROID_HOME"
        echo "Contents of Users/runner/Library/Android/sdk/build-tools/"
        ls -ltr /Users/runner/Library/Android/sdk/build-tools/
```

**Comment by mcagabe19** [comment]
on a test workflow, indeed macOS 12, 13 and 14 does have
https://github.com/mcagabe19/v/actions/runs/11476806865

**Comment by qwertylolman** [comment]
finally, I found this ticket xD

any workarounds? it's critical for us, and PR is still not approved

**Comment by mcagabe19** [comment]
> finally, I found this ticket xD
> 
> any workarounds? it's critical for us, and PR is still not approved

https://github.com/MobilePorting/FNF-PsychEngine-Mobile/blob/9ef0af771c89102fcbbdb0b27b8ee3115136bb93/.github/workflows/build.yml#L43-L51

**Comment by sven-s** [comment]
The build-tools are not on [macos-15](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md). I need it for my maui project, since i got this error:

/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.143/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): error XA5205: Cannot find `aapt`. Please install the Android SDK Build-Tools package with the `/Users/runner/Library/Android/sdk/tools/android` program. [/Users/runner/work/1/s/cpm-app/cpm-app.csproj::TargetFramework=net8.0-android]

Please make the buidl-tools available. Thanks!

**Comment by visualspark** [comment]
> The build-tools are not on [macos-15](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md). I need it for my maui project, since i got this error:
> 
> /Users/runner/hostedtoolcache/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.143/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): error XA5205: Cannot find `aapt`. Please install the Android SDK Build-Tools package with the `/Users/runner/Library/Android/sdk/tools/android` program. [/Users/runner/work/1/s/cpm-app/cpm-app.csproj::TargetFramework=net8.0-android]
> 
> Please make the buidl-tools available. Thanks!

Same with me, since upgrading to macos-15 to compile my maui ios project with xcode 16, my android tasks are failing. 

```
All projects are up-to-date for restore.
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.145/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): error XA5205: Cannot find `aapt`. Please install the Android SDK Build-Tools package with the `/Users/runner/Library/Android/sdk/tools/android` program. [/Users/runner/work/1/s/App/App.csproj::TargetFramework=net8.0-android]

```

**Comment by mcagabe19** [comment]
> > finally, I found this ticket xD
> > any workarounds? it's critical for us, and PR is still not approved
> 
> https://github.com/MobilePorting/FNF-PsychEngine-Mobile/blob/6d805893ffdb391be5dbaa1f3dae717463d258a4/.github/workflows/build.yml#L43-L51

I guess this workaround still gonna apply for a while

**Comment by mcagabe19** [comment]
whenever this pull request is merged, it'll be fixed I think
https://github.com/actions/runner-images/pull/10912

**Comment by spelletier** [comment]
I managed to get my Azure Devon pipelines to complete by adding a script task after the MAUI install. Replace $(AndroidProjectPath) with your own path to the Android project.

```
    - script: |
          dotnet workload install maui
      displayName: 'Install MAUI workload'

    - script: |
          yes | /Users/runner/Library/Android/sdk/tools/bin/sdkmanager --licenses
          dotnet build -t:InstallAndroidDependencies -f net8.0-android "-p:AndroidSdkDirectory=/Users/runner/Library/Android/sdk"
      workingDirectory: $(AndroidProjectPath)
      displayName: 'Install Android sdk dependencies'

```

**Comment by TomSoPolaris** [comment]
I was able to work around this but had to add these 3 tasks after the step to install the MAUI workloads. We're building our .NET MAUI app with Android 14 as the target version (API level 34).

```
# Workaround for Android build tools not being available on macos-15 agents: https://github.com/actions/runner-images/issues/10814
- task: Bash@3
  displayName: 'Workaround build-tools issue'
  inputs:
    targetType: 'inline'
    script: |
      curl https://dl.google.com/android/repository/build-tools_r35_macosx.zip > $ANDROID_HOME/build-tools_r35_macosx.zip
      cd $ANDROID_HOME
      mkdir build-tools
      unzip build-tools_r35_macosx.zip
      mv android-15 build-tools/35.0.0

# Workaround. Need to install sdkmanager first. sdkmanager is required for installing the Android SDK platform
- task: Bash@3
  displayName: 'Install Android SDK Command-line Tools'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Android SDK Command-line Tools..."
      mkdir -p $ANDROID_HOME/cmdline-tools
      curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-7583922_latest.zip
      unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
      mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
      yes | sdkmanager --licenses
      yes | sdkmanager "platforms;android-34"


# Workaround for macos-15 error: Could not find android.jar for API level 34. This means the Android SDK platform for API level 34 is not installed
- task: Bash@3
  displayName: 'Install Android SDK for API level 34'
  inputs:
    targetType: 'inline'
    script: |
      echo "Setting up Android SDK environment variables..."
      export ANDROID_HOME=$HOME/Library/Android/sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

      echo "Installing Android SDK components..."
      yes | sdkmanager "platforms;android-34"
```

**Comment by mcagabe19** [comment]
now `build-tools` does exists but there's nothing on it

**Comment by erik-bershel** [comment]
Heads up! 👋

New runners deployed. 🥳

**Comment by AndreyPhilippov** [comment]
Hey guys! Still have this problem with the lates macos-15 image. My app targets API 34. Build script shows next error `Android SDK platform for API level 34 is not installed; it was expected to be in Users/runner/Library/Android/sdk/platforms/android-34/android.jar`

But the image has
```
drwxr-xr-x  15 runner  staff  480 Dec  2 12:14 android-35-ext14
drwxr-xr-x  15 runner  staff  480 Dec  2 12:14 android-35
drwxr-xr-x  15 runner  staff  480 Dec  2 12:14 android-34-ext8
drwxr-xr-x  15 runner  staff  480 Dec  2 12:15 android-34-ext12
drwxr-xr-x  15 runner  staff  480 Dec  2 12:15 android-34-ext11
drwxr-xr-x  15 runner  staff  480 Dec  2 12:15 android-34-ext10
drwxr-xr-x  15 runner  staff  480 Dec  2 12:15 android-33-ext5
drwxr-xr-x  15 runner  staff  480 Dec  2 12:15 android-33-ext4
```
So android-34 folder doesn't exist. Instead there are only extended android 34 SDKs. Why clean android-34 is not installed but android-35 is? How to solve this?

**Comment by amit-thapa** [comment]
> Hey @AndreyPhilippov, @sven-s and @amit-thapa! 👋
> 
> Here was the workaround for Android SDK with API level 34 (grateful for @TomSoPolaris input 🙇 ) : [#10814 (comment)](https://github.com/actions/runner-images/issues/10814#issuecomment-2479882185) Quote:
> 
> ```yaml
> # Workaround for macos-15 error: Could not find android.jar for API level 34. This means the Android SDK platform for API level 34 is not installed
> - task: Bash@3
>   displayName: 'Install Android SDK for API level 34'
>   inputs:
>     targetType: 'inline'
>     script: |
>       echo "Setting up Android SDK environment variables..."
>       export ANDROID_HOME=$HOME/Library/Android/sdk
>       export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
> 
>       echo "Installing Android SDK components..."
>       yes | sdkmanager "platforms;android-34"
> ```
> 
> The same script might be applied for GitHub Actions.
> 
> Comment with the reasons description: [#10703 (comment)](https://github.com/actions/runner-images/issues/10703#issuecomment-2518003915)
> 
> To the main point. Due to the popularity of this SDK version, I am thinking of adding it to the `macOS-15` build. 🤔 Deployment will probably take place next week (I can't promise at the moment 😞). Until then, please use workaround. 🙇

@erik-bershel thank you for this, I will try it. But yes, I think Android SDK with API level 34 should be available for this runner out of the box. Android 15 - API Level 35 is only available on Google Pixel devices, other manufacturers only have the beta version some are even rolling out the beta just this week like Samsung. So, majority of the Play store apps will be targeting API Level 34 for quite some time. Please make this available if possible, thanks

**Comment by catishu** [comment]
@erik-bershel Do you know if we have include Android SDK 34 in macOS-15 image yet?  I have tried to put your workaround in the yml file but it is still not working.
It shows error parsing the XML

<img width="719" alt="Image" src="https://github.com/user-attachments/assets/554c43f5-b977-49f5-bf93-b946ad09dab0" />
And at the end of our build, it shows the following

`* What went wrong:
A problem occurred evaluating script.
> No installed build tools found. Please install the Android build tools version 34.0.0.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./`

**Comment by erik-bershel** [comment]
Hey @catishu!

You can check there: https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#android

Android SDK Build-tools | 35.0.0 35.0.1
-- | --
Android SDK Platforms | android-35-ext14 (rev 1)android-35 (rev 2)android-34-ext8 (rev 1)android-34-ext12 (rev 1)android-34-ext11 (rev 1)android-34-ext10 (rev 1)android-34 (rev 3)android-33-ext5 (rev 1)android-33-ext4 (rev 1)

As I can see your build relies on Android SDK build tools v34 which is not installed in the image itself. It's separate component not directly bounded to SDK itself.

**Comment by catishu** [comment]
@erik-bershel Yes I got that now.  Thanks
