### ISSUE TITLE
[macOS] Python 3.9 and 3.10 will be removed from macOS13 arm64 and  macOS14 arm64 on November 25.

### ISSUE THREAD

**Issue by susmitamane** [actions/runner-images#10812]
### Breaking changes

- Python < 3.11 will be removed from macOS-13 arm64 and macOS-14 arm64.

### Target date

Image deployment will start on November 25, 2024 and will take 2-3 days.

### The motivation for the changes

We use [python-versions](https://github.com/actions/python-versions) as a source for Python binaries. As per the [repo policy](https://github.com/actions/python-versions?tab=readme-ov-file#building-installation-packages) , we are removing Python < 3.11 from arm64 runners.

### Possible impact

- If your workflows are using Python < 3.11 builds will fail.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Please consider using Python version >=3.11 in your workflows.

**Comment by willemjanvankranenburg** [comment]
Did this change get rolled out 10 days earlier for some reason?

![image](https://github.com/user-attachments/assets/59dd718d-67fa-4581-90d3-3117c43e9555)

![image](https://github.com/user-attachments/assets/fa4527be-477b-4f9f-8d28-3150e544f68d)

**Comment by hugovk** [comment]
Does this only affect the versions in the images? Can we still install Python < 3.11 using actions/setup-python? 

> As per the [repo policy](https://github.com/actions/python-versions?tab=readme-ov-file#building-installation-packages) , we are removing Python < 3.11 from arm64 runners.

Please could you point out which bit of the policy applies? The linked anchor says you build < 3.11 and use the official installer for >= 3.11.

The next section is the [support policy](https://github.com/actions/python-versions?tab=readme-ov-file#support-policy), which says non-EOL versions are supported (which are 3.9+).

Thank you!

**Comment by altendky** [comment]
> Did this change get rolled out 10 days earlier for some reason?

I went ahead and reproduced this based on intermittently hitting it myself.  30x runs each for each of Intel/ARM and Python 3.9/3.10/3.11/3.12 https://github.com/Chia-Network/chia-blockchain/actions/runs/11745259139/job/32723484446?pr=18844  But, I'm not really sure the right place to report it.

**Comment by mikeharder** [comment]
> Did this change get rolled out 10 days earlier for some reason?
> 
> ![image](https://private-user-images.githubusercontent.com/31033654/384256223-59dd718d-67fa-4581-90d3-3117c43e9555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwOTExODksIm5iZiI6MTczMTA5MDg4OSwicGF0aCI6Ii8zMTAzMzY1NC8zODQyNTYyMjMtNTlkZDcxOGQtNjdmYS00NTgxLTkwZDMtMzExN2M0M2U5NTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE4MzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5Mzg3OTI5NTllYjc2NTdiYTAzY2RiMDM4NDJlNDg0NDY2ODMwZjYxNTUxOTliYTNhZjJiZTA1MTI2NDZlZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hoqM3j9fYB9NeAIMUzzeZZdPUFAUksQ3_pHs4YabJZA)
> 
> ![image](https://private-user-images.githubusercontent.com/31033654/384256417-fa4527be-477b-4f9f-8d28-3150e544f68d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwOTExODksIm5iZiI6MTczMTA5MDg4OSwicGF0aCI6Ii8zMTAzMzY1NC8zODQyNTY0MTctZmE0NTI3YmUtNDc3Yi00ZjlmLThkMjgtMzE1MGU1NDRmNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE4MzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzExN2M4OWNiZWZjMWJmYWE0ZGZhODU1MTVkMTljMDUxYTc5ZGVlYjYwMTE0N2QzZjFiYWMwZjA2ZTFkY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CHSR_v3z9pUAJMVp_368mp9uNXPC3unpmCWp9isGg-o)

The error message is an SSL failure.  Could it be related to https://github.com/actions/runner-images/issues/10817?

**Comment by susmitamane** [comment]
Heads up! 👋

New runners deployed.
