### ISSUE TITLE
Windows Server 2019 runner image Docker Engine version updating to v27

### ISSUE THREAD

**Issue by jersonACN** [actions/runner-images#10823]
### Description

When will the docker engine API be updated to v27 for Windows Server 2019 (windows-2019)? We are using a vendor tool (Aqua Security) for docker image scanning and it has compatibility issue with the Docker Engine API version.

2024-10-21 03:37:35.136	ERROR	Failed scanning image <IMAGE NAME>: failed pulling image: Failed connecting to remote docker engine: Error response from daemon: client version 1.46 is too new. Maximum supported API version is 1.45

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: windows-2019
Version: 20241018.1.0
Included Software: https://github.com/actions/runner-images/blob/win19/20241018.1/images/windows/Windows2019-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win19%2F20241018.1
Runner Image Provisioner
Current image version: '20241018.1.0'
Agent running as: 'VssAdministrator'

### Is it regression?

No

### Expected behavior

If the Docker Engine API version of the windows-2019 runner image and Aqua Security scanner tool.

### Actual behavior

The issue is caused by a lower version of Docker Engine API compared to the vendor scanning tool.

2024-10-21 03:37:35.136	ERROR	Failed scanning image <IMAGE NAME>: failed pulling image: Failed connecting to remote docker engine: Error response from daemon: client version 1.46 is too new. Maximum supported API version is 1.45

### Repro steps

1. Use windows-2019 as the MS hosted build agent.
2. Build, scan a Windows image.

**Comment by hemanthmanga** [comment]
Hi @jersonACN, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by jersonACN** [comment]
Hello @vidyasagarnimmagaddi. Will there be plans to use Docker v27 in windows-2019 build agent?

**Comment by vidyasagarnimmagaddi** [comment]
Hi @jersonACN  , We do have plan for changing Docker v27, will raise an announcement , and so that customers will be able to know the changes. thanks.

**Comment by vidyasagarnimmagaddi** [comment]
> Hello @vidyasagarnimmagaddi. Following up with you about this. Thank you!

HI ,We have made an announcement for Updating the Docker Engine version to 27.* . [Announcement](https://github.com/actions/runner-images/issues/11104) .
The status can be tracked under the same. Can this issue be closed ?

**Comment by jersonACN** [comment]
Yes we can close this ticket now. Thank you for the assistance!

**Comment by vidyasagarnimmagaddi** [comment]
Hi @jersonACN , Thanks for confirming. Closing this issue.
