### ISSUE TITLE
Ubuntu-latest is failing to deploy SWAs properly

### ISSUE THREAD

**Issue by Skintkingle** [actions/runner-images#10828]
### Description

Since Friday we've had strange issue in our SWA in Azure. It's randomly providing 404s for files that were properly deploying on Friday 18th Oct 2024.

If we try and redeploy the same commit that we deployed successfully on that date, then the build appears to be successful, but browsing to our SWA seems to cause random files to not be deployed, resulting in 404s and page load issues. We are deploying a Blazor app using the AzureStaticWebApp@0 task. at version 0.247.1. This version is UNCHANGED and so is not the tasks fault.

For example after 1 deploy, and a full cacheless refresh, we get a 404 on blazor.boot.json,
After another deploy we get a 404 on our scoped css file.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Issue with 20241015.1.0
Worked last friday with 20241006.1.0

### Is it regression?

Yes

### Expected behavior

Deployments to be full and correct.

### Actual behavior

randomly missing files

### Repro steps

deploy using AzureStaticWebApp@0 to a SWA site in Azure.
Attempt to browse to the site after deployment
From dev tools, notice random 404s on files

**Comment by kishorekumar-anchala** [comment]
Hi @Skintkingle ,

  This issue not related to runner images repo, i request you to kindly raise a new issue with static web app repo . 
  
  I have seen already an issue has been raised , please look into the below link.
  
  https://github.com/Azure/static-web-apps/issues/1560

**Comment by Skintkingle** [comment]
Thanks for the quick response. This might be related although we aren't using Functions, just pure SWA file hosting. I'll raise an issue there, thank you.

**Comment by kishorekumar-anchala** [comment]
We're closing the issue as it it not belongs to runner images. thank you !.
