### ISSUE TITLE
[windows-2019] Microsoft Edge WebDriver Signature thumbprint do not match

### ISSUE THREAD

**Issue by koaminakligo-eaton** [actions/runner-images#10822]
### Description

Hi,
I am generating images windows-2019 in azure, and the build failed three times for Microsoft Edge WebDriver, version 130.0.2849.46, Signature thumbprint does not match. 

Provisioning with powershell script: D:/a/1/s/images/windows/templates/../scripts/build/Install-EdgeDriver.ps1
    azure-arm.image: Get the Microsoft Edge WebDriver version...
    azure-arm.image:
    azure-arm.image:
    azure-arm.image:     Directory: C:\SeleniumWebDrivers
    azure-arm.image:
    azure-arm.image:
    azure-arm.image: Mode                LastWriteTime         Length Name
    azure-arm.image: ----                -------------         ------ ----
    azure-arm.image: d-----       10/20/2024   5:49 AM                EdgeDriver
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/LATEST_RELEASE_130_WINDOWS to C:\SeleniumWebDrivers\EdgeDriver\versioninfo.txt...
    azure-arm.image: Package downloaded in 0.07 seconds
    azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.46/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.09 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

Two days ago, the version 129.0.2792.89 works for me.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

This is for an organization.

### Is it regression?

I can't provide the link.

### Expected behavior

No issue

### Actual behavior

Failed

### Repro steps

Build an windows-2019 image to verify it.

**Comment by RaviAkshintala** [comment]
Hi @koaminakligo-eaton Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by RaviAkshintala** [comment]
@vd84 Microsoft Edge WebDriver Signature thumbprint  has been updated, Could you please retry by forking latest code from main branch.
Closing this issue,Thank you.

**Comment by koaminakligo-eaton** [comment]
> @vd84 Microsoft Edge WebDriver Signature thumbprint has been updated, Could you please retry by forking latest code from main branch. Closing this issue,Thank you.

Thank you, the issue is fixed.
