### ISSUE TITLE
Invalid Signature Microsoft Edge Webdriver

### ISSUE THREAD

**Issue by stoopman** [actions/runner-images#10840]
### Description

Image build on windows 2022 on tag **win22/20241015.1** fails due to **Signature thumbprint do not match expected.** error

```
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/LATEST_RELEASE_130_WINDOWS to C:\SeleniumWebDrivers\EdgeDriver\versioninfo.txt...
    azure-arm.image: Package downloaded in 0.13 seconds
    azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.46/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.22 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Tag: win22/20241015.1

### Is it regression?

n/a

### Expected behavior

successful build

### Actual behavior

Error with **Signature thumbprint do not match expected**

### Repro steps

Clone repo with Tag: win22/20241015.1 and build the image for win 2022

**Comment by RaviAkshintala** [comment]
Hi @stoopman  Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by RaviAkshintala** [comment]
Hi @stoopman The Microsoft Edge Webdriver signature thumbprint is already up to date, and the Windows 2022 build was successful. The thumbprint we are using is `0BD8C56733FDCC06F8CB919FF5A200E39B1ACF71`. Kindly check this and synch your main. We are closing this issue now, Thanks!

**Comment by veronicagt094** [comment]
Hi @RaviAkshintala could you tell me the commit to solve this error please?

**Comment by GitHubAre** [comment]
Still not solved, we are getting this error as of today, using latest from main

**Comment by veronicagt094** [comment]
Thanks for the response @GitHubAre , I am waiting for the solution since this is why my pipeline fails

**Comment by stoopman** [comment]
@RaviAkshintala this is still not resolved, I ran a build on the **main** branch yesterday and got the following error

```
    azure-arm.image: Get the Microsoft Edge WebDriver version...
    azure-arm.image:
    azure-arm.image:
    azure-arm.image:     Directory: C:\SeleniumWebDrivers
    azure-arm.image:
    azure-arm.image:
    azure-arm.image: Mode                 LastWriteTime         Length Name
    azure-arm.image: ----                 -------------         ------ ----
    azure-arm.image: d-----         11/4/2024   1:48 AM                EdgeDriver
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/LATEST_RELEASE_130_WINDOWS to C:\SeleniumWebDrivers\EdgeDriver\versioninfo.txt...
    azure-arm.image: Package downloaded in 0.11 seconds
    azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.68/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.05 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
```

**Comment by iphydro** [comment]
The main branch was fixed for a while, but this [commit](https://github.com/actions/runner-images/commit/2d275789110208cd547c539918d824b58e6612d5) broke it again. Instead of updating the ubuntu edgedriver signature it reverted the windows server edgedriver signature.
