### ISSUE TITLE
Update Git (for Windows) to v2.47.0.windows.2

### ISSUE THREAD

**Issue by vorporeal** [actions/runner-images#10843]
### Tool name

Git

### Tool license

GPL v2

### Add or update?

- [ ] Add
- [X] Update

### Desired version

v2.47.0.windows.2

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by vorporeal** [comment]
Git v2.47.0.windows.1 has a bug that causes problems fetching repositories via SSH: https://github.com/git-for-windows/git/issues/5199

v2.47.0.windows.1 was rolled out in the 20241015.1.0 Windows Server image release.

v2.47.0.windows.2 was released today with a fix for the issue, and should be included in the Windows Server runner images ASAP to mitigate user impact (it broke one of our workflows, which could no longer reliably fetch a private GitHub repository over SSH).

**Comment by hemanthmanga** [comment]
Hi @vorporeal, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by UrsDeSwardt** [comment]
Any progress on this? 🙂

**Comment by pulkitsharma07** [comment]
Issue got resolved after updating git to version 47.0.2. 

Add this step in the workflow (taken from https://github.com/CeruleanSonar/SonarView/pull/10) before invoking any `git` command:

```
    - name: Bump git-for-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.47.0.windows.2/Git-2.47.0.2-64-bit.exe" -OutFile "${{runner.temp}}/git-for-windows.exe"
        Start-Process -Filepath "${{runner.temp}}/git-for-windows.exe" -ArgumentList  @("/VERYSILENT","/NORESTART","/NOCANCEL","/SP-","/CLOSEAPPLICATIONS","/RESTARTAPPLICATIONS","/o:PathOption=CmdTools","/o:BashTerminalOption=ConHost","/o:EnableSymlinks=Enabled","/COMPONENTS=gitlfs") -NoNewWindow -Wait
```

**Comment by vaibhavagrawal2912** [comment]
This has become a blocker for us. Can this be prioritised and deployed sooner?

**Comment by rotu** [comment]
FWIW, I think neither the above workaround *nor* faster turnaround on issues like this really address the problem.

It would be nice to be able to rollback the runner to a working image[^1] and/or to have Windows container support[^2].

[^1]: https://github.com/actions/runner-images/discussions/7521

[^2]: https://github.com/actions/runner/issues/904

**Comment by lakshminarayana02** [comment]
Hi
We are looking into this problem and will make sure that the latest Git version will be included on subsequent  image releases. We appreciate your patience with us.

**Comment by berleant** [comment]
My org is also affected by this issue, and the workaround posted above does not work (times out). Do you have a timeline for getting this fixed?

**Comment by hlevring** [comment]
Yeah, we are also one of the unlucky once. We have been scratching our heads for a couple of days spending a ton of man hours before we finally contacted github support who pointed to this thread

**Comment by flavienbwk** [comment]
> Yeah, we are also one of the unlucky once. We have been scratching our heads for a couple of days spending a ton of man hours before we finally contacted github support who pointed to this thread

Same, 20h lost for that. GitHub not checking its runners to work correctly with git is unbelievable.

**Comment by lakshminarayana02** [comment]
Hi
We are working on this update should be added to the future  runner images as soon as possible.

**Comment by berleant** [comment]
> Hi We are working on this update should be added to the future runner images as soon as possible.

Can you give an estimated date for the fix?

**Comment by lakshminarayana02** [comment]
Hi @berleant 
We understand  that the most recent fix version has been released and is available, but in order to include it in our images, we must complete a strict process that includes numerous tests.   Please be patient with us. and, certainly, we are working on it.

**Comment by rotu** [comment]
> We understand that the most recent fix version has been released and is available, but in order to include it in our images, we must complete a strict process that includes numerous tests. Please be patient with us. and, certainly, we are working on it.

@lakshminarayana02, Hopefully a slightly better process than the one that deployed v2.47.0.windows.1 into these images.

Any reason the image wasn't just rolled back to 20241006.1.0, which was *before* the breaking change? This seems like one of the main reasons `actions/runner-images` is under source control in the first place!

**Comment by lakshminarayana02** [comment]
Hi

We have been working on it and have done the testing, but for some reason, the version has been brought back to the previous version from the authorised source repository, from which we used to regularly download the latest version for our images. 

Reference links are included.
https://github.com/git-for-windows/git/tree/v2.47.1.windows.1
https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1

Once the new version is out,  will update our images and we appreciate your patience and suggestions.

**Comment by lakshminarayana02** [comment]
Hi @ajungg 
yes, we are confirming you that v2.47.1.windows.1 . it will be available in next week release.
