### ISSUE TITLE
Latest macOS 13 (20241023) Image Update breaks the build

### ISSUE THREAD

**Issue by mattleibow** [actions/runner-images#10857]
### Description

I have a pipeline that got a new image for one of the jobs and that job failed: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=10444412&view=logs&j=aaf09777-7812-5d11-5912-09caf96718ec&t=9b5ed072-9ad2-5137-089a-b45b38c6f2ac

The previous image is good: 20241008.186
The new image fails: 20241023.237

Seems the `pipes` module in python is missing:

```
Traceback (most recent call last):
  File "/Users/runner/work/1/s/externals/depot_tools/ninja.py", line 14, in <module>
    import gclient_paths
  File "/Users/runner/work/1/s/externals/depot_tools/gclient_paths.py", line 13, in <module>
    import gclient_utils
  File "/Users/runner/work/1/s/externals/depot_tools/gclient_utils.py", line 19, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Operating System
macOS
13.7
22H123

Runner Image
Image: macos-13
Version: 20241023.237
Included Software: https://github.com/actions/runner-images/blob/macos-13/20241023.237/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20241023.237

Runner Image Provisioner
2.0.384.1+6d6c56aa16f1b9c7dd7935df5d63980397e44def
Current image version: '20241023.237'

### Is it regression?

macos-13/20241008.186

### Expected behavior

No build error

### Actual behavior

Missing module

### Repro steps

Run the build

**Comment by vaishalipawar1490** [comment]
Hi @mattleibow, we're checking into this and will keep you posted.

**Comment by vaishalipawar1490** [comment]
Hi @mattleibow, 
Could you please confirm if you're still facing the issue or if it has been resolved ? Because we noticed that the "**Run the bootstrapper for external-android**" stage passed successfully on 3rd attempt in your pipeline without any failure.

**Comment by mattleibow** [comment]
Hmm, it seems to have decided to pick up the old image again: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=10444412&view=logs&j=93cde958-e777-5e84-d665-4f513a789d08&t=5ae81d6a-07d1-44cc-a481-df1f413732ed

Not sure if that is good or bad, or maybe devops decided it had enough red and just picked an older image.

**Comment by erik-bershel** [comment]
Hey @mattleibow!

Which Python version do you use? `Pipes` is deprecated a long time ago in order to force users to switch to `subprocess`: https://peps.python.org/pep-0594/#pipes
I suspect that using the pre-cached Python@3.11 package should fix the problem: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines

**Comment by vaishalipawar1490** [comment]
Hi @mattleibow, Since there are no further action items pending from our side, we will proceed with closing this issue.
Please feel free to reach out if you have any further questions.
