### ISSUE TITLE
ADO agents fail to start when using vmscaleset image Ubuntu 24.04

### ISSUE THREAD

**Issue by tumm0283** [actions/runner-images#10855]
### Description

I have created a new vmscaleset using the latest Ubuntu 24.04 image.
when trying to point ADO pipeline to this new image (Ubuntu 24.04) ,i see the VM gets created but in ado agents won't show up even though everything has been permissioned.

we have same instance setup using Ubuntu 22.04 and everything works (Agents) no issues.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent version 1.25.2.0
OS version Ubuntu 24.04

### Is it regression?

Yes, 22.04 is fine

### Expected behavior

I expect the agents to scale up when using the image based on Ubuntu 24.04.
As it works for Ubuntu 22.04 image

### Actual behavior

found similar github post https://github.com/microsoft/azure-pipelines-agent/issues/5012#issuecomment-2421014643
is there any issues with ado pipeline agent ?

### Repro steps

1.Run GenerateResoureandImage
2.Run Packer
3.Update RG to the new image created
4. Create a new agent pool in ADO based on the subscription and VMSS pool
5. Run the pipeline to new pool

**Comment by hemanthmanga** [comment]
Hi @tumm0283,  Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by kishorekumar-anchala** [comment]
HI @tumm0283 , 

   it seems the issue with agent , i request you to kindly raise an issue with the below repo .

**Comment by kishorekumar-anchala** [comment]
Hi @tumm0283 , 

    we're closing this issue as it is not belongs to runner images , Thank you ! .
