### ISSUE TITLE
Windows cant clone private repos

### ISSUE THREAD

**Issue by calebstott** [actions/runner-images#10858]
### Description

Action fails when cloning private repos through PlatformIO. Due to this we cannot create production builds

Believe #10843 would fix the issue

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2019 20241021.1.0
windows-2022 20241015.1.0
(Repos are private)

### Is it regression?

Yes (no log available for previous builds)

### Expected behavior

Private repos to be cloned with provided keys

### Actual behavior

Action fails whenever PlatformIO tries to clone private library dependencies (seems platformio defaults to using SSH)

### Repro steps

1. Set up deploy keys using [webfactory/ssh-agent](https://github.com/webfactory/ssh-agent)
2. Try to build a [PlatformIO ](https://docs.platformio.org/en/latest/projectconf/sections/env/options/library/lib_deps.html) project that has a library dependency found in a private repo

**Comment by hemanthmanga** [comment]
Hi @calebstott,  Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @calebstott , Kindly provide the error screenshots or any sample workflow , this will help in resolve the issue. thanks

**Comment by calebstott** [comment]
This is all I can provide sorry. The runner hangs on line 53 for a few minutes, before failing to clone the private repo
![image](https://github.com/user-attachments/assets/8a572f91-f56d-462f-850b-bee4b23dc1ba)

**Comment by vidyasagarnimmagaddi** [comment]
Hi @calebstott  , As the source: https://github.com/git-for-windows/git/releases , the latest version will be [2.47.1.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1) .  it will be included in our next image rollout.thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @calebstott , As the source: https://github.com/git-for-windows/git/releases , the latest version will be [2.47.1.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1) . it will be included in our next image rollout.thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @calebstott  ,
The issue will be resolved once the next image rollout happens. And git version of [2.47.1.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1) will be included. thanks closing this issue.
