### ISSUE TITLE
Not seeing macOS 15 Arm64 as a Pipeline Agent Specification option in ADO

### ISSUE THREAD

**Issue by bobnoble2** [actions/runner-images#10852]
### Description

When viewing the Agent Specification list of options, I do not see macOS-15-arm64. See attached image. Is there something I need to do to see macOS-15-arm64 as an option?
<img width="439" alt="Screenshot 2024-10-23 at 9 16 57 AM" src="https://github.com/user-attachments/assets/b06cde94-14ff-46b0-a597-8d9e45f7fddb">

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We are currently using macOS-14 but want to use macOS-15-arm64

### Is it regression?

No - I have never seen the macOS-15-arm64 option.

### Expected behavior

I expect to see macOS-15-arm64 as an Agent Specification option.

### Actual behavior

No macOS-15-arm64 Agent Specification option is listed.

### Repro steps

1. Create a new or open an existing ADO pipeline
2. Set Agent Pool to Azure Pipelines
3. Drop down the list of available Agent Specification

Note that macOS-15-arm64 is not included in the list.

**Comment by sean-mcmanus** [comment]
I'm seeing the same issue -- I can get macOS-15 and macOS-14-arm64, but not macOS-15-arm64.

**Comment by erik-bershel** [comment]
Hey @bobnoble2 and @sean-mcmanus!
`macOS-15-arm64` is not yet available in `Azure DevOps` and there is no plans right now to add it there. We will announce these changes [here](https://github.com/actions/runner-images/issues/8971) if the decision is changed.
