### ISSUE TITLE
macOS 15 runner image is missing Mono

### ISSUE THREAD

**Issue by richardfric** [actions/runner-images#10859]
### Description

In compare to MacOS 14 there is no Mono tool installed, which causes the nuget pack command to fail:

> 2024-10-24T11:02:31.8893810Z Attempting to pack file: /Users/runner/work/1/s/my.nuspec
2024-10-24T11:02:31.8950130Z ##[error]Error: Unable to locate executable file: 'mono'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
2024-10-24T11:02:31.8970120Z ##[error]An error occurred while trying to pack the files.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-15
Version: 20241014.202

### Is it regression?

yes, macOS-14

### Expected behavior

nuget pack command should work as expected

### Actual behavior

nuget pack fails and no nuget package is created

### Repro steps

nuget pack <any>.nuspec

**Comment by sureshe456** [comment]
Hi @richardfric , We will take a look into this issue and keep you updated.

**Comment by aartis17** [comment]
Hi @richardfric ,

Changes were announced here: https://github.com/actions/runner-images/issues/10686

Please see below points for NuGet :

- The Mono project is in limbo: https://www.mono-project.com/download/stable/
- There have been no updates for a long time: https://github.com/mono/mono/tags
- No one has tested compatibility with macOS-15 (NuGet team plans)
- The NuGet project will be forking from Mono in the near future (NuGet team plans)

As a runtime workaround, please use brew: https://formulae.brew.sh/formula/nuget#default

**Comment by richardfric** [comment]
Using homebrew to install nuget works but it's sad there is no usable nuget tool available out of the box. It can be considered as user comfort degradation.

**Comment by MarkCallow** [comment]
The `nuget` Brew package has mono as a dependency. Is it possible to use the .NET package for macOS that Microsoft makes available? Does that include `nuget`?

Some of my jobs still run on earlier runners that include mono which causes `brew install nuget` to fail. I have not yet found a clean way to make my workflow run on macOS 15 and on earlier runners, hence my question about .NET.

**Comment by erik-bershel** [comment]
Hey @MarkCallow!

Try using that at the first:

```bash
nuget help || brew install nuget -q
```

If Nuget is installed, nothing will happen, if not installed, it will be installed with all dependencies. 🤷

**Comment by MarkCallow** [comment]
@erik-bershel thanks for the tip. Works like a charm. Misled by the vcpkg documentation for using a nuget cache, I didn't realize nuget was installed in the pre-macOS-15 runners so thought I was coping with a situation where the nuget package's dependency (mono) was either present or not. Following their instructions I was having vcpkg fetch nuget and calling mono to run the downloaded file.
