### ISSUE TITLE
MacOS 14: operation not permitted, scandir

### ISSUE THREAD

**Issue by JP250552** [actions/runner-images#10869]
### Description

We're receiving build failures on the latest image that were previously working

![image](https://github.com/user-attachments/assets/cd88e18a-7d76-447f-98f1-64d4101f93be)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`20241022.361`

Build Link (private): https://github.com/LodoSoftware/core-mobile/actions/runs/11558810034/job/32172126210

### Is it regression?

Yes, `20241014.301`

Build Link (private): https://github.com/LodoSoftware/core-mobile/actions/runs/11520178922/job/32070967435

### Expected behavior

Builds should pass, should not receive "operation not permitted" error

### Actual behavior

Receiving these 2 errors:

```
Error: EPERM: operation not permitted, scandir 'hermes-engine'
```

```
error: Sandbox: mkdir(17884) deny(1) file-write-create /Users/runner/Library/Developer/Xcode/DerivedData/Mobile-atvoxbwxkqxckqdorphlbugfhxgw/Build/Intermediates.noindex/ArchiveIntermediates/Mobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/React-rncore.build/DerivedSources/generated (in target 'React-rncore' from project 'Pods')
```

### Repro steps

Running a React Native iOS build using Fastlane

**Comment by spriggyjeff** [comment]
We are seeing the same error you described, with the same broken and working runner image versions:

Previous working build was:
Image: macos-14-arm64
  Version: 20241014.301

First broken build was on:
Image: macos-14-arm64
  Version: 20241022.361

**Comment by sureshe456** [comment]
Hi @JP250552 We are looking into the issue. Will keep you posted with updates.Thanks.

**Comment by mlopez34** [comment]
Getting similar error: 

last working run used:
Runner Image
  Image: macos-14-arm64
  Version: 20241014.301
  
  reran the same job with no code changes today and it used the following:
  
 Runner Image
  Image: macos-14-arm64
  Version: 20241022.361
  
<img width="1069" alt="Screenshot 2024-10-29 at 1 53 31 AM" src="https://github.com/user-attachments/assets/e6477108-6703-4ce4-805b-f2455fac42fa">

**Comment by aste-mikkok** [comment]
Was also getting the `operation not permitted, scandir` error with latest runners, upgrading cocoapods to version 1.16 seems to have resolved the problem for us.

**Comment by Aminager** [comment]
> Was also getting the `operation not permitted, scandir` error with latest runners, upgrading cocoapods to version 1.16 seems to have resolved the problem for us.

This solved the problem!!!

**Comment by unpunnyfuns** [comment]
I have the same issue on macOS-15. Will attempt installing cocoapods 1.16.

**Comment by novalagung** [comment]
Saw the issue yesterday. Solved it by upgrading the cocoapods to `v1.16` and use `macos-15`

**Comment by susmitamane** [comment]
Hi @JP250552 ,  New images have deployed this week 🎉

As per analysis and user responses cocoapods v1.16 update may fix this issue, The latest images have cocoapods to v1.16. Could you please check and confirm if the issue still persist. 

Thank you.

**Comment by JP250552** [comment]
Thank you for the reply @susmitamane! 
1.16 does in fact fix the issue. 

Its slightly concerning that we don't fully understand the root cause. 
If we weren't able to switch cocoapods versions, then we would be unable to create mobile builds. 

I will go ahead and close this issue though since we are up and running again.
