### ISSUE TITLE
Invalid Signature for Microsoft Edge Webdriver

### ISSUE THREAD

**Issue by GitHubAre** [actions/runner-images#10868]
### Description

Signature check fails for MSFT Edge Webdriver

Output from PowerShell build image script:

```
azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.56/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.14 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.image: 
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Latest from this git repo - a1633b01936bfd1fcd4ec9a88d087b0e07e907aa

### Is it regression?

n/a

### Expected behavior

Signature veirified correctly

### Actual behavior

Signature does not match.

### Repro steps

Executing pwsh script

`. 'C:\a\1\s\runner-images\images.CI\linux-and-win\build-image.ps1' -ImageName windows-2022-552827 ` -ClientId *** ` -ClientSecret *** ` -TemplatePath C:\a\1\s\runner-images\images\windows\templates\windows-2022.pkr.hcl ` -ImageResourceGroupName *** ` -SubscriptionId *** ` -TenantId *** ` -Location *** ` -TempResourceGroupName packer-temp-windows-2022-552827`

**Comment by vidyasagarnimmagaddi** [comment]
Hi @GitHubAre  , Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by The-Moonster** [comment]
Just wanted to mention that I'm getting the same error too.  Trying to create a Server2022 image on Friday and again today.

`azure-arm.image: Download Microsoft Edge WebDriver...
azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.56/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
azure-arm.image: Package downloaded in 0.13 seconds
azure-arm.image: Expand Microsoft Edge WebDriver archive...
azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
azure-arm.image: Signature thumbprint do not match expected.
azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
azure-arm.image: +         throw "Signature thumbprint do not match expected."
azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
azure-arm.image:
azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
azure-arm.image: Step "StepProvision" failed
azure-arm.image: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?`

**Comment by james-woodbridge** [comment]
I am getting the same issue, and it seems this issue is happening semi-regularly for different tools used by these images. Is it not possible to target known versions rather than latest and guarantee that the signatures will match?

**Comment by vidyasagarnimmagaddi** [comment]
Hi @GitHubAre  , The signature issue has been fixed, could you please try to synch your main and re-run the build and confirm us. thanks

**Comment by GitHubAre** [comment]
@RaviAkshintala Thank you very much for so quick fix!
Will test it today and let you know

**Comment by beryl-factset** [comment]
I've got the same error, that change seemed to fix it for one build a couple of days ago, but now I'm seeing it again.

**Comment by GitHubAre** [comment]
I can confirm that it was resolved, image was built successfully.
Thank you once more for very quick help on this!

**Comment by The-Moonster** [comment]
> I can confirm that it was resolved, image was built successfully. Thank you once more for very quick help on this!

Same here.  Was able to build an image, use it in a Scale set, and deploy a new DevOps agent pool.
