### ISSUE TITLE
[ macOS ] Node.js version 16 will be removed from macOS13 and macOS13 arm64 images on November, 25.

### ISSUE THREAD

**Issue by susmitamane** [actions/runner-images#10873]
### Breaking changes

Node.js version 16 will be removed from macOS13 and macOS13 arm64 images.

### Target date

Rollout of the change will start on November, 25 and will take 3-4 days.

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of go are supported i.e., Node.js 18, 20, 22.

### Possible impact

If your builds depend on Node.js 16 they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Nothing is required, if you are using the [Node Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) task (for Azure DevOps) and the [setup-node](https://github.com/actions/setup-node) action (for GitHub Actions) both will still download a version you specify if it is available in the [versions-manifest.json](https://github.com/actions/node-versions/blob/main/versions-manifest.json) file.

**Comment by erik-bershel** [comment]
Heads up! 👋

New runners deployed. 🥳
