### ISSUE TITLE
Android Emulator Not Found and Timing Out in Azure Pipelines Windows 2019 Image

### ISSUE THREAD

**Issue by rashmi-athavale** [actions/runner-images#10870]
### Description

We are encountering an urgent issue in our OneBranch pipelines, where our Android tests are not running due to the emulator not starting as expected. This problem arose unexpectedly in May, with no recent changes on our end. The Android tests work fine locally, and we are using a PowerShell script to install the Android emulator on the Azure Pipelines Windows 2019 image. We would greatly appreciate any assistance in investigating and resolving this issue.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://dev.azure.com/msazure/One/_build/results?buildId=106510471&view=cloudtest.1ESTest-tab.build&ctSession=c830b720-1a60-4e51-8fa0-7f628b7ae271&ctEnv=Prod&ctNode=780e0c1c-c4af-558b-9a90-390c10757c21_c2b85da6-2d68-59c6-b5bd-8a2194ea45c8&ctTab=Logs&ctView=Attachment&ctAttachment=TestResults/exeTestConsoleLogs/RunAndroidTests_10.out

Azure Pipelines Windows 2019 image

### Is it regression?

Yes

### Expected behavior

The Android emulator should be detected and initialized successfully, allowing our tests to proceed as expected.

### Actual behavior

The emulator fails to initialize and times out, which prevents our Android tests from running.

### Repro steps

In the linked build, you can review the RunAndroidTests_10.out log, where the emulator startup attempt fails and times out.

**Comment by kishorekumar-anchala** [comment]
Hi @rashmi-athavale 

   Thanks for bringing to us , we will look into this and update. Thank you !

**Comment by vidyasagarnimmagaddi** [comment]
Hi, @rashmi-athavale , We cant access the build link provided, kindly share the error logs, repro steps  with us for issue resolution, thanks.

**Comment by rashmi-athavale** [comment]
Hi @vidyasagarnimmagaddi @kishorekumar-anchala,

I've attached the logs below. In RunAndroidTests_10.out, you can see the Android emulator failing to start and timing out. Since you don’t have access to our code and repository, providing detailed repro steps may be challenging. However, as mentioned in the issue, we’re using a PowerShell script to install the Android emulator on the Azure Pipelines Windows 2019 image.

[GeneralAttachment.zip](https://github.com/user-attachments/files/17562463/GeneralAttachment.zip)

**Comment by rashmi-athavale** [comment]
@vidyasagarnimmagaddi @kishorekumar-anchala Please let me know if there is an update on the above. Thanks!

**Comment by DergachevE** [comment]
Hi @rashmi-athavale,

Can you please provide a link to the actual pipeline job that executes the tests?
Is this the correct one?
https://dev.azure.com/msazure/One/_build/results?buildId=106510471&view=logs&j=78e6ba89-5628-5d19-e7a6-16014c840c74

How do you run these tests? Is it CloudTest?

**Comment by rashmi-athavale** [comment]
@DergachevE Yes, that link is correct. We're using CloudTest to run our tests, but we're encountering a timeout issue when locating the Android emulator, which is preventing the tests from running.

**Comment by DergachevE** [comment]
@rashmi-athavale As I can see, these tests are running on CloudTest environment and not on AzDO pool/agent.
You need to escalate this issue to the corresponding CloudTest team

**Comment by vidyasagarnimmagaddi** [comment]
Hi @rashmi-athavale ,
we are closing this issue as this issue is related to CloudTest team. Thanks.
