### ISSUE TITLE
Update/Add Cocoapods

### ISSUE THREAD

**Issue by cyrilcolinet** [actions/runner-images#10874]
### Tool name

Cocoapods

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.16.0

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sureshe456** [comment]
Hi @cyrilcolinet We will look into this issue.Will keep you posted with updates.

**Comment by sarathrajsrinivasan** [comment]
Hi @cyrilcolinet ,

We will begin our weekly deployment for macOS on Monday, and the current CocoaPods version 1.16.1 will be available within 3-4 days after that. Will post an update here once the VM rollout is complete.

**Comment by cyrilcolinet** [comment]
Hi team, any update on this? Or any ETA for rollout?

Thanks

**Comment by sureshe456** [comment]
Hi @cyrilcolinet , There is a deployment issues and we are working on it. Will update here once VM rollout is complete.

**Comment by cyrilcolinet** [comment]
Hi @sureshe456 thanks for update.
Good luck!
