### ISSUE TITLE
Invalid Signature for Microsoft Edge Webdriver

### ISSUE THREAD

**Issue by denyos** [actions/runner-images#10886]
### Description

Signature check fails for Microsoft Edge Webdriver

```
  azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.68/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.22 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:

```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Latest main, commit a29761eb602738fa26f650a9859eff599ed64f85 

Download main branch from https://github.com/actions/runner-images.git
Cloning into '.'...
Latest commit:
Date: Fri Nov 1 11:16:08 2024 +0100; Commit: a29761eb602738fa26f650a9859eff599ed64f85 - [ubuntu-24] Add nvm and gcloud cli (#10881); Author: Shamil Mubarakshin <127750046+shamil-mubarakshin@users.noreply.github.com>
image_os: windows2022

### Is it regression?

n/a

### Expected behavior

Signature veirified correctly

### Actual behavior

Signature does not match.

### Repro steps

Executing powershell script /images.CI/linux-and-win/build-image.ps1

. 'C:\a\1\s\runner-images\images.CI\linux-and-win\build-image.ps1' -ImageName windows-2022-552827  -ClientId *** -ClientSecret *** -TemplatePath C:\a\1\s\runner-images\images\windows\templates\windows-2022.pkr.hcl -ImageResourceGroupName *** -SubscriptionId *** -TenantId *** -Location ***  -TempResourceGroupName packer-temp-windows-2022-552827

**Comment by Denyos** [comment]
It seems that Microsoft is doing something strange with the release of the new edge driver.
https://msedgedriver.azureedge.net/LATEST_RELEASE_130_WINDOWS is currently returning 130.0.2849.56, while earlier today it returned 130.0.2849.68 as can be seen in my error log above.

https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver shows 130.0.2849.68 as latest.

**Comment by peterjlay** [comment]
Same issue here.

    azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/130.0.2849.68/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.75 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.image: 
==> azure-arm.image: Deleting Virtual Machine deployment and its attatched resources...

**Comment by kishorekumar-anchala** [comment]
Working on this issue, we will update shortly

**Comment by kishorekumar-anchala** [comment]
Hi @denyos , now the latest code has new signature , request you to try with the latest code.

**Comment by denyos** [comment]
I've started our pipelines. Thanks for letting me know.
