### ISSUE TITLE
Approve and add new nodejs version

### ISSUE THREAD

**Issue by zdm** [actions/runner-images#10882]
### Description

Could you please merge this PR https://github.com/actions/node-versions/pull/191
It adds new nodejs releases.
Thousands of projects depends on this data.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

-

### Expected behavior

-

### Actual behavior

-

### Repro steps

-

**Comment by vidyasagarnimmagaddi** [comment]
Hi @zdm , We cannot approve/merge PR for other repositories. As the PR is  already raised in `node-versions` , You could request the same team. Thanks ,closing the issue.

**Comment by zdm** [comment]
But readme in that project says that I should create issues here.
