### ISSUE TITLE
feature request: set Azure Tags on Packer VM

### ISSUE THREAD

**Issue by baidarka** [actions/runner-images#10883]
### Description

Feature request: extra parameter on 'build-image.ps1' script so that Azure tags can be passed along to the temporary Packer VM resource.

Although the Packer templates support the parameter 'azure_tags', the build script 'build-image.ps1' does not support that parameter. It is not possible to set Azure tags on the Packer VM when using 'build-image.ps1' or the Azure pipelines in this repo.
(this is an issue, not a bug; apologies, i could not find a matching issue format)

Implemented in PR #10884

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I need to set Azure tags on the temporary Packer VM that build the image. 

### Is it regression?

No

### Expected behavior

Have a parameter on the build-image.ps1 script to pass on Azure tags to the Packer template file. 

### Actual behavior

No such parameter.

### Repro steps

No such parameter.

**Comment by kishorekumar-anchala** [comment]
Hi @baidarka ,

  We're looking into your issue , thank you !

**Comment by baidarka** [comment]
PR #10884

**Comment by pkoelemij** [comment]
This would be a nice addition!

**Comment by lakshminarayana02** [comment]
Hi 
we are validating it.

**Comment by lakshminarayana02** [comment]
Hi 
Packer templates can contain the parameter 'azure_tags to include with many', however the challenge here is how to go about including temporary resource tags without a business case for implementing this and obtaining approval from GitHub.

We request that you give further information or justification to consider it.

**Comment by baidarka** [comment]
Would it be helpful if I provide additional information? If yes, what would you be looking for? Looking forward to your insights!

**Comment by lakshminarayana02** [comment]
Hi @baidarka 
We are trying to say that it is at the OS image creation level changes needed and azure policy definitions may need to be amended, additionally worried that it could  affect the security posture of the VM.  


Please share your thoughts.

**Comment by baidarka** [comment]
> Hi @baidarka We are trying to say that it is at the OS image creation level changes needed and azure policy definitions may need to be amended, additionally worried that it could affect the security posture of the VM.
> 
> Please share your thoughts.

Dear @lakshminarayana02,

The requested feature (and PR) are not aimed at OS image creation nor at azure policy definitions, nor security posture.
The request is merely to _optionally_ expose an _existing_ packer template parameter in the build script.

Existing parameter: [`variable "azure_tags"`](https://github.com/actions/runner-images/blob/a63a87f6a09e9eba15845cd397812010f130675e/images/windows/templates/windows-2022.pkr.hcl#L24) in windows-2022.pkr.hcl

This template parameter is not used or exposed in [build-image.ps1](https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/build-image.ps1).
The PR [#10884](https://github.com/actions/runner-images/pull/10884) exposes this parameter in the build-image.ps1 script and propagates its value to the template parameter.

This does not affect the image to be build. It affects the temporary Packer VM used to build the image.
Hope this helps & kinds regards!

**Comment by lakshminarayana02** [comment]
Hi @baidarka 
Thank you for sharing these details,  we will consult with stakeholders with these details and keep you updated.

**Comment by lakshminarayana02** [comment]
Hi @baidarka 

After considerable internal discussion, we would like to notify you that Github hosted runners rarely need tags because our VMs are ephemeral. Furthermore, with such a broad set of users, selecting and maintaining tags is simply daunting.
As you use self-hosted runners, please feel free to build the image and add the tags parameter to your runner images as suggested in this.  Hence, we are unable to proceed.

**Comment by baidarka** [comment]
I'm sorry to hear this issue is closed.
The approach you suggest is exactly what my associated PR implements for the buildscript.

Passing in optional Tags is supported in the existing 'generate' script, but not in the 'build' script (hence not in the pipeline).
The optional tags are not a parameter in the 'build' script, only in the 'generate' script.

I feel we do have a misunderstanding in this regard.
I am not suggesting that anyone should maintain such Tags. I am suggesting to optionally allow users (such as ourselves) to pass in an Azure Tags hashtable in the 'build' script.

Nevertheless thank you for your efforts.

**Comment by pkoelemij** [comment]
C

**Comment by baidarka** [comment]
Although my PR #10884 is rejected, the good new is that PR #11367 implements the requested feature.
Thanks @Alexey-Ayupov
