### ISSUE TITLE
Add instructions to build without PS & Azure CLI

### ISSUE THREAD

**Issue by GamePlayer-8** [actions/runner-images#10895]
### Tool name

Ubuntu

### Tool license

-

### Add or update?

- [ ] Add
- [X] Update

### Desired version

-

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

-

### Are you willing to submit a PR?

Not really

**Comment by kishorekumar-anchala** [comment]
Hi @GamePlayer-8 - we'll look into this request and update ASAP. Thank you !

**Comment by lakshminarayana02** [comment]
Hi 

We understand that these tools are vital for automating the build process and interacting with Azure resources.it  relies extensively on Azure-specific capabilities and services and many services may be  typically controlled via PowerShell and the Azure CLI. Without these tools, it would be difficult.
