### ISSUE TITLE
unexpected disconnect while reading sideband packet

### ISSUE THREAD

**Issue by yuzurihaaa** [actions/runner-images#10892]
### Description

My application used to work fine compiling the app on windows.  However, recently, there are a number of failures happened when fetching dependency. This issue only happened on windows, but not on macos or ubuntu.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

  Image: windows-2022
  Version: 20241021.1.0

### Is it regression?

Yes -   last working, Image: windows-2022   Version: 20241006.1.0

### Expected behavior

App should be able to fetch dependencies and build application.

### Actual behavior

Currently when I am trying to fetch app dependency, I get error

```
Git error. Command: `git clone --mirror git@github.com:google/flutter-desktop-embedding.git C:\Users\runneradmin\AppData\Local\Pub\Cache\_temp\dir5a5d1c1b`
[ 4m 51.436s] Resolving dependencies...
stdout: 
stderr: Cloning into bare repository 'C:\Users\runneradmin\AppData\Local\Pub\Cache\_temp\dir5a5d1c1b'...
Read from remote host github.com: Connection reset by peer
client_loop: send disconnect: Connection reset by peer
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
exit code: 128
```

only on Windows. MacOS and Ubuntu works fine.

### Repro steps

-

**Comment by jvanhuis-zebra** [comment]
I am also experiencing the same failure.  MacOS and Ubuntu builds passing, Windows build fails with same failure message.

**Comment by raphaelmenges** [comment]
I am facing the same issue. I do not have that issue when using a self-hosted Windows runner.

**Comment by jvanhuis-zebra** [comment]
Found a workaround here: https://github.com/git-for-windows/git/issues/5199

`- name: Install git for windows
   if: runner.os == 'Windows'
   shell: pwsh
   run: |
     Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.47.0.windows.2/Git-2.47.0.2-64-bit.exe" -OutFile "${{runner.temp}}/git-for-windows.exe"
     Start-Process -Filepath "${{runner.temp}}/git-for-windows.exe" -ArgumentList  @("/VERYSILENT","/NORESTART","/NOCANCEL","/SP-","/CLOSEAPPLICATIONS","/RESTARTAPPLICATIONS","/o:PathOption=CmdTools","/o:BashTerminalOption=ConHost","/o:EnableSymlinks=Enabled","/COMPONENTS=gitlfs") -NoNewWindow -Wait`

**Comment by kishorekumar-anchala** [comment]
Hi @yuzurihaaa , 

  Are this issue still persist ? I request you kindly try with the latest rollout version . Hope it will fix the issue . 

Kindly confirm if the issue resolved or further assistance needed. 

Looking forward for your confirmation.

**Comment by jan-reznik-mo** [comment]
I believe the issue still persist as the Windows images do not include the updated git client yet - `v2.47.0.windows.2`

**Comment by yuzurihaaa** [comment]
Hi @kishorekumar-anchala I just retrigger the pipeline and seems like still getting the error.

Here are the details in Set Up Job

```
Current runner version: '2.321.0'

Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter

Runner Image
Image: windows-2022
Version: 20241125.1.0 
```

```
Read from remote host github.com: Connection reset by peer
client_loop: send disconnect: Connection reset by peer
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

**Comment by kishorekumar-anchala** [comment]
@yuzurihaaa ,

   This v2.47.1.windows.1 version nit available with this roll out. it will be available with the next roll out . i will confirm you once it done.
   
   meanwhile , i request you to proceed with temporary workaround 
   
```
 - name: Install git for windows
   if: runner.os == 'Windows'
   shell: pwsh
   run: |
     Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.47.1.windows.1/Git-2.47.1-64-bit.exe" -OutFile "${{runner.temp}}/git-for-windows.exe"
     Start-Process -Filepath "${{runner.temp}}/git-for-windows.exe" -ArgumentList  @("/VERYSILENT","/NORESTART","/NOCANCEL","/SP-","/CLOSEAPPLICATIONS","/RESTARTAPPLICATIONS","/o:PathOption=CmdTools","/o:BashTerminalOption=ConHost","/o:EnableSymlinks=Enabled","/COMPONENTS=gitlfs") -NoNewWindow -Wait
```

**Comment by kishorekumar-anchala** [comment]
HI @yuzurihaaa @jvanhuis-zebra ,
    new rollout has been completed , i request you kindly validate the issue and confirm . 
    
  ```
 Image: windows-2022
  Version: 20241201.2.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20241201.2/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20241201.2
```
new version has been updated . 

<img width="869" alt="Screenshot 2024-12-05 at 3 44 41 PM" src="https://github.com/user-attachments/assets/d457b89f-16ac-4d45-9f3d-2499afcc83d5">

**Comment by jan-reznik-mo** [comment]
> HI @yuzurihaaa @jvanhuis-zebra , new rollout has been completed , i request you kindly validate the issue and confirm .
> 
> ```
> Image: windows-2022
> Version: 20241201.2.0
> Included Software: https://github.com/actions/runner-images/blob/win22/20241201.2/images/windows/Windows2022-Readme.md
> Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20241201.2
> ```
> 
> new version has been updated .
> <img alt="Screenshot 2024-12-05 at 3 44 41 PM" width="869" src="https://private-user-images.githubusercontent.com/168699259/392765917-d457b89f-16ac-4d45-9f3d-2499afcc83d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDc1NTUsIm5iZiI6MTczMzUwNzI1NSwicGF0aCI6Ii8xNjg2OTkyNTkvMzkyNzY1OTE3LWQ0NTdiODlmLTE2YWMtNGQ0NS05ZjNkLTI0OTlhZmNjODNkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNzQ3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmJlOGZlMzY1OTJkNTk4MzdjZWIzYTNjN2ZkMWI0MTAwNWIwMjliYjlmOTIxOTRjODkyMGRlY2U5MzNiMTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iTq0LAQHhR3d6InyqvUeu29Pz8DBnXkws1JS8NK9cCw">

I have updated our workflow and removed the workaround mentioned above and all is working as expected. Thank you.

**Comment by kishorekumar-anchala** [comment]
Thank you for your confirmation, we are closing this issue as resolved.

Thank you for support !
