### ISSUE TITLE
Update/Add NodeJS version 23

### ISSUE THREAD

**Issue by kyle-leonhard** [actions/runner-images#10907]
### Tool name

NodeJS

### Tool license

unknown

### Add or update?

- [ ] Add
- [X] Update

### Desired version

23

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by kishorekumar-anchala** [comment]
Hi @kyle-leonhard , We're looking into the issue, we'll share update ASAP . thank you !

**Comment by lakshminarayana02** [comment]
Hi
we are working on it.

**Comment by lakshminarayana02** [comment]
Hi @kyle-leonhard 

Thank you for your patience,  We received the update, will be included in the upcoming image OS releases

**Comment by lakshminarayana02** [comment]
Hi
We maintain Node.js LTS versions  such as 18, 20, and 22. Currently, Node.js has released the current public version 23, however the LTS version has yet to be announced .  We maintain the most latest approved versions up to date.
