### ISSUE TITLE
[macOS 15] Add Xcode 16.1 final version (replace the RC)

### ISSUE THREAD

**Issue by salvatoreboemia** [actions/runner-images#10910]
### Description

Hi

<img width="882" alt="Screenshot 2024-11-06 at 12 04 54" src="https://github.com/user-attachments/assets/be8eff84-b336-4392-ad82-598435bd8c1d">

do you have an ETA for replacing RC with the final version?

Thanks

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

xcode 16.1

### Is it regression?

no

### Expected behavior

16.1 instead RC

### Actual behavior

RC instead final one

### Repro steps

read documentation

**Comment by susmitamane** [comment]
Hi @salvatoreboemia We will look into the issue and keep you posted with updates.

**Comment by erik-bershel** [comment]
Hey @salvatoreboemia! 👋 

It will be available with the next image release. Applied changes:
- https://github.com/actions/runner-images/pull/10880
- https://github.com/actions/runner-images/pull/10906

We are working on providing it ASAP, but unfortunately it cannot take less than three business days after `pre-release` anyway. 😞

**Comment by erik-bershel** [comment]
Changes to track (`macos-15`, Intel-based images both regular and larger): https://github.com/actions/runner-images/pull/10912

**Comment by salvatoreboemia** [comment]
> Hey @salvatoreboemia! 👋
> 
> It will be available with the next image release. Applied changes:
> 
>     * [[macOS] Add Xcode 16.1 and 16.2 Beta 1 to macOS15 #10880](https://github.com/actions/runner-images/pull/10880)
> 
>     * [[macOS]Add Xcode 16.2_beta_2 to macOS 15 #10906](https://github.com/actions/runner-images/pull/10906)
> 
> 
> We are working on providing it ASAP, but unfortunately it cannot take less than three business days after `pre-release` anyway. 😞

super, so basically this week will be available the new Xcode 16.1 for all macOS 15 image. 

Thanks

**Comment by vaishalipawar1490** [comment]
Hi @salvatoreboemia 
Xcode 16.1 is now available on macOS 15 and macOS 15 ARM. Please check.
Closing this issue. Feel free to reach out if you have any further queries.
