### ISSUE TITLE
Update Android SDK's cmake

### ISSUE THREAD

**Issue by yujincheng08** [actions/runner-images#10933]
### Tool name

Android SDK's cmake

### Tool license

BSD 3-clause License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.31.0

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

#10932

**Comment by kishorekumar-anchala** [comment]
Hi @yujincheng08 - Looking into this issue, we will update on this ASAP.

**Comment by prasanjitsahoo** [comment]
Hi @yujincheng08 , We have been working diligently on only MAC OS images, and if you want to include the CMAKE tool for Windows, please open a new issue with the selection of specific OS, and a separate team will work on it.

**Comment by prasanjitsahoo** [comment]
@yujincheng08 As discussed with the Windows and Ubuntu teams, CMake 3.31.0 is already updated in the images, so no separate ticket is needed. Thanks.

**Comment by yujincheng08** [comment]
@prasanjitsahoo I mean **Andoird's** cmake. And it's still an old version:

https://github.com/actions/runner-images/blob/d22a5ec4c17b7417e8014e6911344df7ca68b86e/images/ubuntu/toolsets/toolset-2004.json#L90-L92
