### ISSUE TITLE
cmake install failing after action update

### ISSUE THREAD

**Issue by bhourahine** [actions/runner-images#10941]
### Description

An action is now failing possibly after the runner-images update yesterday, manifesting within the last 4 hours (re-running pipeline that worked fails with no changes). Action was working for cmake  3.30.5, it's installed using pip3, which now looks like:

Run pip3 install cmake
Collecting cmake
  Downloading cmake-3.31.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)

But is now giving the error:

Run cmake -B _build -G Ninja -DCMAKE_INSTALL_PREFIX=${PWD}/_install -DCMAKE_BUILD_TYPE=Debug ${CMAKE_OPTIONS} -DWITH_MPI=${WITH_MPI}
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/opt/hostedtoolcache/Python/3.12.7/x64/share/cmake-3.31
CMake Error: Error executing cmake::LoadCache(). Aborting.

Error: Process completed with exit code 1.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Attempt 2 fails :
https://github.com/dftbplus/dftbplus/actions/runs/11758461511

### Is it regression?

Yes, Attempt 1 for action from ~4 hours ago succeeds: https://github.com/dftbplus/dftbplus/actions/runs/11758461511/attempts/1

### Expected behavior

Paths for cmake OK, and action proceeds to next stage of building project.

### Actual behavior

Error from cmake about probably not installing correctly:

Run cmake -B _build -G Ninja -DCMAKE_INSTALL_PREFIX=${PWD}/_install -DCMAKE_BUILD_TYPE=Debug ${CMAKE_OPTIONS} -DWITH_MPI=${WITH_MPI}
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/opt/hostedtoolcache/Python/3.12.7/x64/share/cmake-3.31
CMake Error: Error executing cmake::LoadCache(). Aborting.

Error: Process completed with exit code 1.

### Repro steps

1. Install cmake via pip3
2. call cmake in pipeline

**Comment by vidyasagarnimmagaddi** [comment]
Hi @bhourahine  , Thanks for confirming. Closing this issue.
