### ISSUE TITLE
Add just

### ISSUE THREAD

**Issue by BuriKizilkaya** [actions/runner-images#10958]
### Tool name

Just

### Tool license

CC0 1.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

3 MB

### Brief description of tool

Just is an tool to automate different command line task with custom tasks.

### URL for tool's homepage

https://github.com/casey/just

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
windows: choco install just
linux: apt install just or over the script
```

### Are you willing to submit a PR?

Maybe

**Comment by vidyasagarnimmagaddi** [comment]
Hi @BuriKizilkaya  , Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by BuriKizilkaya** [comment]
I can also help, but I don't know how to add ah new tool. I don't understand your architecture. Have you some guides  or docs?

**Comment by aartis17** [comment]
Hi @BuriKizilkaya , We will look into the issue and keep you posted with updates.

**Comment by sureshe456** [comment]
Hi @BuriKizilkaya, We don't want to add any tools currently to the macOS images due to the issues with the disk space available and maintains.
