### ISSUE TITLE
Update Ubuntu 24 toolset

### ISSUE THREAD

**Issue by DergachevE** [actions/runner-images#10965]
### Tool name

ruby

### Tool license

n/a

### Add or update?

- [ ] Add
- [x] Update

### Desired version

3.2

### Brief description of tool

AzDO tasks need the Ruby tool version 3.2 to be added in toolset:
https://github.com/actions/runner-images/blob/918263378c472623f0e156cd610c5f2c22b00312/images/ubuntu/toolsets/toolset-2404.json#L52

### Provide a basic test case to validate the tool's functionality.

```bash

```

### Platforms where you need the tool

- [x] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash

```

### Tool installation time in runtime

Already persists in the image

**Comment by vidyasagarnimmagaddi** [comment]
Hi @DergachevE 

We will revert with after analyzing the issue. Thanks

**Comment by vidyasagarnimmagaddi** [comment]
HI @DergachevE 
The Ruby version 3.2.* has been added in toolset-24.04 , and new image with the changes  has been deployed  
![image](https://github.com/user-attachments/assets/0bfa9d0f-c7ff-47c9-83c0-efab097bafc7)
