### ISSUE TITLE
Issue with brew package pkgconf

### ISSUE THREAD

**Issue by smorimoto** [actions/runner-images#10984]
### Description

It could be that the macOS runners now have the `pkg-config` brew package already installed, which conflicts with the `pkgconf` package.

But it's already deprecated: https://github.com/Homebrew/homebrew-core/pull/194885

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20241022.361

### Is it regression?

No

### Expected behavior

It should be installed successfully.

### Actual behavior

It fails:

```
- ==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/manifests/2.3.0
- ==> Fetching pkgconf
- ==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/blobs/sha256:4d7c580[39](https://github.com/ocaml/setup-ocaml/actions/runs/11884964161/job/33113941200#step:4:40)43bf2dcc8cb9ff8c838ea4283eeab24f49982df044cbc3031856fd8
- ::error::Cannot install pkgconf because conflicting formulae are installed.%0A  pkg-config: because both install `pkg.m4` file%0A%0APlease `brew unlink pkg-config` before continuing.%0A%0AUnlinking removes a formula's symlinks from /opt/homebrew. You can%0Alink the formula again after the install finishes. You can `--force` this%0Ainstall, but the build may fail or cause obscure side effects in the%0Aresulting software.%0A
[ERROR] These packages are still missing: pkgconf
```

Ref: https://github.com/ocaml/setup-ocaml/actions/runs/11884964161/job/33113941200

### Repro steps

Run `brew install pkgconf` on `macos-latest`

**Comment by smorimoto** [comment]
This should probably happen on all macOS runners and break existing workflows.

**Comment by prasanjitsahoo** [comment]
Hi @smorimoto  We will look into the issue and keep you posted with updates.

**Comment by smorimoto** [comment]
@prasanjitsahoo Thanks a lot!

**Comment by erik-bershel** [comment]
For those who fall into this (cost ~2 minutes):

```yaml
      - name: Runtime workaround for brew pkg-config -> pkgconf
        run: |
          brew update
          brew upgrade
          brew install pkgconf
```

As a temporary measure, we will switch to a hardcoded version of the original `pkg-config` that expected to be friendly with `brew` [here](https://github.com/actions/runner-images/pull/10971). We would be glad to hear your opinion on the consequences of replacing it with an updated `pkgconf` from `brew`.

**Comment by akoeplinger** [comment]
@erik-bershel I think that pinning the old pkg-config 0.29 version means installing pkgconf will fail since it's trying to install into the same file paths. pkgconf is already an alias in Homebrew so you can probably just install that.

**Comment by erik-bershel** [comment]
Hey @akoeplinger!
Thank you for your feedback. :heart: We'll migrate to the new `Homebrew` package next week than. 🤔

**Comment by erik-bershel** [comment]
Heads up! 👋 

New runners deployed. 🥳  Due to the way the deployment works, you may encounter an outdated image for the next few hours, the next image is not affected by the issue.

**Comment by smorimoto** [comment]
Nice!
