### ISSUE TITLE
Getting ICU error when trying to build with globalization

### ISSUE THREAD

**Issue by DevOpsAzurance** [actions/runner-images#10989]
### Description

Ubuntu image is not built with required ICU packages needed for dotnet build:

Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

Setting environment variable to:

$export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

is not viable as dev requires globalization.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '3.236.0'
Current image version: '1.0.3'

This image is using the March Build of the Ubuntu OS.

### Is it regression?

NA

### Expected behavior

It should be able to build with Globalization using ICU on Ubuntu

### Actual behavior

Fails due to missing packages

### Repro steps

1. Run build

**Comment by Prabhatkumar59** [comment]
Hi @DevOpsAzurance - Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by fedordikarev** [comment]
hi! just sharing that we today started to get builds failing due to missing `icu` in macos images

could that be related to original issue and any of recent changes in images?

**Comment by Prabhatkumar59** [comment]
Hi @DevOpsAzurance - After my observation from your issue description, you can try to follow below workflow to resolve the ICU issue on Ubuntu runners for .NET builds which will install the required ICU packages before the build.:-
```
steps:
  - name: Install ICU packages
    run: sudo apt-get update && sudo apt-get install -y libicu-dev
```
This might ensures that the .NET build can proceed with full globalization support.

**Comment by Prabhatkumar59** [comment]
Hi @DevOpsAzurance - Since we haven't heard back, we'll assume your issue is resolved and will close this issue for now. Please feel free to reach out to us for any other queries. Thanks.

**Comment by jon-a-nygaard** [comment]
Thanks for the workaround @Prabhatkumar59 🙂 

I see that the same issue is also present in the ubuntu-24.04 runner image, so I was therefore wondering if we can expect later runner images to include the ICU packages as in 20.04, or should we rely on installing the ICU packages from now on?

**Comment by DevOpsAzurance** [comment]
> Hi @DevOpsAzurance - Since we haven't heard back, we'll assume your issue is resolved and will close this issue for now. Please feel free to reach out to us for any other queries. Thanks.

Can you reopen this issue?

We run our image rebuilds bi-monthly and this was not retested since then.  We are using Azure DevOps so this was added if running DotNetCore builds in a linux OS:

```
  - task: bash@3
    displayName: 'Install ICU Globalization on Linux'
    condition: eq(variables['Agent.OS'], 'Linux')
    inputs:
      targetType: 'inline'
      script: 'sudo apt-get update && sudo apt-get install -y libicu-dev'
```

which returns this:

```
Starting: Install ICU Globalization on Linux
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.246.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
sudo apt-get update && sudo apt-get install -y libicu-dev
========================== Starting Command Output ===========================
/usr/bin/bash /agent/_work/_temp/08239187-3f97-449d-b051-d7db41128859.sh
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu noble-security InRelease
Hit:6 https://packages.microsoft.com/repos/azure-cli noble InRelease
Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libicu-dev is already the newest version (74.2-1ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.

Finishing: Install ICU Globalization on Linux
```

but results in this during the build:

```
  Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
     at System.Environment.FailFast(System.String)
     at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
     at System.Globalization.GlobalizationMode..cctor()
     at System.Globalization.CultureData.CreateCultureWithInvariantData()
     at System.Globalization.CultureData.get_Invariant()
     at System.Globalization.CultureInfo..cctor()
     at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
     at System.Resources.ResourceManager.CommonAssemblyInit()
     at System.Resources.ResourceManager..ctor(System.Type)
     at System.SR.get_ResourceManager()
     at System.SR.GetResourceString(System.String, System.String)
     at System.SR.get_XmlConvert_BadUri()
     at System.Xml.XmlReaderSettings.CreateReader(System.String, System.Xml.XmlParserContext)
     at System.Xml.XmlReader.Create(System.String, System.Xml.XmlReaderSettings, System.Xml.XmlParserContext)
     at System.Xml.XmlReader.Create(System.String, System.Xml.XmlReaderSettings)
     at System.Xml.Linq.XDocument.Load(System.String, System.Xml.Linq.LoadOptions)
     at System.Xml.Linq.XDocument.Load(System.String)
     at Vsxmd.Program.Main(System.String[])
  Aborted (core dumped)
##[error]/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build/Vsxmd.targets(17,5): Error MSB3073: The command ""/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build//../tools/linux-x64/Vsxmd" "" "" "True"" exited with code 134.
/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build/Vsxmd.targets(17,5): error MSB3073: The command ""/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build//../tools/linux-x64/Vsxmd" "" "" "True"" exited with code 134. [/agent/_work/5/s/SourceCodeRepo/src/Services/FNOL_PolicyInfo.Domain/FNOL_PolicyInfo.Domain.csproj]

Build FAILED.
```

This is the latest Ubuntu build, which is strange as the install ICU step says it is already at the latest and marking it as manually installed. Seems like something is there, but then fails anyways.

**Comment by DevOpsAzurance** [comment]
> Thanks for the workaround @Prabhatkumar59 🙂
> 
> I see that the same issue is also present in the ubuntu-24.04 runner image, so I was therefore wondering if we can expect later runner images to include the ICU packages as in 20.04, or should we rely on installing the ICU packages from now on?

I am ok with running that install step, but so far not working for me.

**Comment by PanPanZou** [comment]
> > Thanks for the workaround @Prabhatkumar59 🙂
> > I see that the same issue is also present in the ubuntu-24.04 runner image, so I was therefore wondering if we can expect later runner images to include the ICU packages as in 20.04, or should we rely on installing the ICU packages from now on?
> 
> I am ok with running that install step, but so far not working for me.

Hi, may I ask if your issue has been resolved? I am encountering the exact same problem.

**Comment by PanPanZou** [comment]
> > Thanks for the workaround @Prabhatkumar59 🙂
> > I see that the same issue is also present in the ubuntu-24.04 runner image, so I was therefore wondering if we can expect later runner images to include the ICU packages as in 20.04, or should we rely on installing the ICU packages from now on?
> 
> I am ok with running that install step, but so far not working for me.

Hi, I am encountering the exact same problem, and I solve it by change:
    runs-on: ubuntu-latest
to:
    runs-on: ubuntu-20.04

**Comment by jsm174** [comment]
We just had same issue, as `ubuntu-latest` in one fork selected `ubuntu-24.04` vs another fork selected `ubuntu-22.04`

I tried an update step as well

```yml
      - if: (matrix.os == 'ubuntu-latest')
        name: Add icu support (ubuntu runner)
        run: |
          sudo apt-get install libicu-dev
```

```
Reading package lists...
Building dependency tree...
Reading state information...
libicu-dev is already the newest version (74.2-1ubuntu3.1).
libicu-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
```

**Comment by jamesbailey-sh** [comment]
> We just had same issue, as `ubuntu-latest` in one fork selected `ubuntu-24.04` vs another fork selected `ubuntu-22.04`
> 
> I tried an update step as well
> 
> ```yaml
>       - if: (matrix.os == 'ubuntu-latest')
>         name: Add icu support (ubuntu runner)
>         run: |
>           sudo apt-get install libicu-dev
> ```
> 
> ```
> Reading package lists...
> Building dependency tree...
> Reading state information...
> libicu-dev is already the newest version (74.2-1ubuntu3.1).
> libicu-dev set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
> ```
> 
> Temporarily forcing `ubuntu-22.04` until this gets resolved.

@jsm174 - This worked for me, thanks for your help

**Comment by DevOpsAzurance** [comment]
> > We just had same issue, as `ubuntu-latest` in one fork selected `ubuntu-24.04` vs another fork selected `ubuntu-22.04`
> > I tried an update step as well
> >       - if: (matrix.os == 'ubuntu-latest')
> >         name: Add icu support (ubuntu runner)
> >         run: |
> >           sudo apt-get install libicu-dev
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Reading package lists...
> > Building dependency tree...
> > Reading state information...
> > libicu-dev is already the newest version (74.2-1ubuntu3.1).
> > libicu-dev set to manually installed.
> > 0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Temporarily forcing `ubuntu-22.04` until this gets resolved.
> 
> [@jsm174](https://github.com/jsm174) - This worked for me, thanks for your help

Still having an issue. My Pipeline YAML is running this:

```
    - task: bash@3
      displayName: 'Install ICU Globalization on Linux'
      condition: eq(variables['Agent.OS'], 'Linux')
      inputs:
        targetType: 'inline'
        script: >
          echo "##vso[task.setvariable variable=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT;]0"

          sudo apt-get update

          sudo apt-get -U install -y libicu-dev
```

Dev teams can set whether invariant is set to 0 or 1.  If '0' and running on linux machine, it needs to install libicu-dev. The output of said steps is:

```
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash /agent/_work/_temp/0d5f30fd-8992-4d16-9031-22d0699ca3ef.sh
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu noble InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Hit:6 https://packages.microsoft.com/repos/azure-cli noble InRelease
Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [775 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 Components [151 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [974 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu noble-updates/universe amd64 Components [309 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Components [212 B]
Get:13 http://azure.archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Components [940 B]
Get:14 http://azure.archive.ubuntu.com/ubuntu noble-backports/main amd64 Components [208 B]
Get:15 http://azure.archive.ubuntu.com/ubuntu noble-backports/universe amd64 Components [11.7 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu noble-backports/restricted amd64 Components [216 B]
Get:17 http://azure.archive.ubuntu.com/ubuntu noble-backports/multiverse amd64 Components [212 B]
Get:18 http://azure.archive.ubuntu.com/ubuntu noble-security/main amd64 Components [7240 B]
Get:19 http://azure.archive.ubuntu.com/ubuntu noble-security/universe amd64 Components [52.0 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu noble-security/restricted amd64 Components [212 B]
Get:21 http://azure.archive.ubuntu.com/ubuntu noble-security/multiverse amd64 Components [212 B]
Fetched 2661 kB in 2s (1439 kB/s)
Reading package lists...
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:6 https://packages.microsoft.com/repos/azure-cli noble InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu noble-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libicu-dev is already the newest version (74.2-1ubuntu3.1).
libicu-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.

Finishing: Install ICU Globalization on Linux
```

but then still fails with:

```
/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/Exceptions/MyClasses.cs(35,13): warning SYSLIB0051: 'Exception.Exception(SerializationInfo, StreamingContext)' is obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.' (https://aka.ms/dotnet-warnings/SYSLIB0051) [/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/MyProject.csproj]
  MyProject -> /agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/bin/release/net8.0/MyProject.dll
  Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
     at System.Environment.FailFast(System.String)
     at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
     at System.Globalization.GlobalizationMode..cctor()
     at System.Globalization.CultureData.CreateCultureWithInvariantData()
     at System.Globalization.CultureData.get_Invariant()
     at System.Globalization.CultureInfo..cctor()
     at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
     at System.Resources.ResourceManager.CommonAssemblyInit()
     at System.Resources.ResourceManager..ctor(System.Type)
     at System.SR.get_ResourceManager()
     at System.SR.GetResourceString(System.String, System.String)
     at System.SR.get_XmlConvert_BadUri()
     at System.Xml.XmlReaderSettings.CreateReader(System.String, System.Xml.XmlParserContext)
     at System.Xml.XmlReader.Create(System.String, System.Xml.XmlReaderSettings, System.Xml.XmlParserContext)
     at System.Xml.XmlReader.Create(System.String, System.Xml.XmlReaderSettings)
     at System.Xml.Linq.XDocument.Load(System.String, System.Xml.Linq.LoadOptions)
     at System.Xml.Linq.XDocument.Load(System.String)
     at Vsxmd.Program.Main(System.String[])
  Aborted (core dumped)
##[error]/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build/Vsxmd.targets(17,5): Error MSB3073: The command ""/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build//../tools/linux-x64/Vsxmd" "" "" "True"" exited with code 134.
/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build/Vsxmd.targets(17,5): error MSB3073: The command ""/home/AzDevOps/.nuget/packages/vsxmd/1.4.5/build//../tools/linux-x64/Vsxmd" "" "" "True"" exited with code 134. [/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/MyProject.csproj]

Build FAILED.

/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/Entities/ReinsuranceResult.cs(46,53): warning CS8618: Non-nullable property 'Claim' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/MyProject.csproj]
/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/Exceptions/MyClasses.cs(35,13): warning SYSLIB0051: 'Exception.Exception(SerializationInfo, StreamingContext)' is obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.' (https://aka.ms/dotnet-warnings/SYSLIB0051) [/agent/_work/4/s/SourceCodeRepo/src/Services/MyProject/MyProject.csproj]
```
