### ISSUE TITLE
Update/Add MicrosoftPowerBIMgmt

### ISSUE THREAD

**Issue by hmayer1980** [actions/runner-images#11008]
### Tool name

MicrosoftPowerBIMgmt

### Tool license

https://github.com/microsoft/powerbi-powershell/blob/master/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.2.1111

### Brief description of tool

Powershell Modules to interact with Microsoft PowerBI
See https://learn.microsoft.com/en-us/powershell/power-bi/overview?view=powerbi-ps

### URL for tool's homepage

https://github.com/microsoft/powerbi-powershell

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Install-Module -Name MicrosoftPowerBIMgmt
```

### Tool installation time in runtime

2s

**Comment by Prabhatkumar59** [comment]
Hi @hmayer1980 - Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by lakshminarayana02** [comment]
Hi 
We have evaluated the feasibility of including Microsoft Power BI Management nevertheless, we perfer maintaining lightweight OS images for users, considering its inclusion of BI  in the operating system images unfeasible due to the larger size of the installation.

**Comment by lakshminarayana02** [comment]
Hi 
We have evaluated the feasibility of including Microsoft Power BI Management nevertheless, we prefer maintaining lightweight OS images for users, considering its inclusion of BI  in the operating system images unfeasible due to the larger size of the installation.
