### ISSUE TITLE
AzureCosmosDbEmulator Checksum verification failed for windows 2022 

### ISSUE THREAD

**Issue by antika080** [actions/runner-images#11002]
### Description

AzureCosmosDbEmulator Checksum verification failed for windows 2022 

Error:
Provisioning with powershell script: /agent/_work/17/s/runner-images/images/windows/templates/../scripts/build/Install-AzureCosmosDbEmulator.ps1
Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\xelknulf.msi...
Package downloaded in 6.99 seconds
Checksum verification failed: expected DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FDC9A6020220BEE41, got
1EF64CF9CD13C611AAC394113A703AF6F525C7C39BFB6B4C3F884D57F6F1D1CF
At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
+         throw "Checksum verification failed: expected $expectedHash,  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Checksum verifi...F884D57F6F1D1CF:String) [], RuntimeException
 + FullyQualifiedErrorId : Checksum verification failed: expected DB9D5E496C5FDAE17C12C03385D2BAC973DA61C280023D9FD
C9A6020220BEE41, got 1EF64CF9CD13C611AAC394113A703AF6F525C7C39BFB6B4C3F884D57F6F1D1CF

Provisioning step had errors: Running the cleanup provisioner, if present...

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

NA

### Is it regression?

No

### Expected behavior

Install-AzureCosmosDbEmulator.ps1 should be run without error

### Actual behavior

Install-AzureCosmosDbEmulator.ps1 is failing with error

### Repro steps

run Install-AzureCosmosDbEmulator.ps1 script

**Comment by Prabhatkumar59** [comment]
Hi @antika080 - Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by kishorekumar-anchala** [comment]
fix under #11004
