### ISSUE TITLE
Signature thumbprint do not match expected - AzureCLI Win22/Win19

### ISSUE THREAD

**Issue by hmayer1980** [actions/runner-images#11005]
### Description

I did try multiple Version to build over the day. This is for Tag "win22/20241113.3" (the last one documented at https://github.com/actions/runner-images/tree/win22/20241113.3)
I also tried the prev Release releases/win22/20241021 - which ends in a different Thumbprint to not match (Visual Studio Enterprise)
I just want one version that works for a standalone VM 
I also treid "win19/20241113.3" for Win 2019 but same error.
https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md 
It may be also benefitial to add to clone a dedicated release or tag for the build process before doing it.

==> azure-arm.image: Provisioning with powershell script: C:/runner-images/runner-images/images/windows/templates/../scripts/build/Install-AzureCli.ps1
    azure-arm.image: Install the latest Azure CLI release
    azure-arm.image: Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\yov5dhw2.msi...
    azure-arm.image: Package downloaded in 8 seconds
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.image: Step "StepProvision" failed

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

win19/20241113.3
win22/20241113.3

### Is it regression?

Not for me - first time tried that

### Expected behavior

a Standalone VM is created witht he Version of Windows and all software

### Actual behavior

Build failed

### Repro steps

Follow the Steps of Manual Image creation under
https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#manual-image-generation
but before runnning "GenerateResourcesAndImage" use git checkout "tagName /Branchname"

**Comment by kishorekumar-anchala** [comment]
working on it .

**Comment by hmayer1980** [comment]
I did try your Repo with the fix - "git checkout kishorekumar-anchala:fix-win"
For Windows2022 I end up in this error then...

Not sure there are some commits from some other branches missing or this is also new - when running 20241113.3 I did get over the Visual Studio installation.

Treat this just as a comment, because I do not really know where the final merge comes together yet.

```
==> azure-arm.image: Provisioning with powershell script: C:/Repos/runner-images-kishore/images/windows/templates/../scripts/build/Install-VisualStudio.ps1
    azure-arm.image: Downloading Bootstrapper ...
    azure-arm.image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.image: Package downloaded in 0.82 seconds
    azure-arm.image: Signature thumbprint do not match expected.
    azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.image: +         throw "Signature thumbprint do not match expected."
    azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
    azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0 3010]
==> azure-arm.image: Step "StepProvision" failed
```
