### ISSUE TITLE
Regression in `macos-15-arm64/20241118.362`: `xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.`

### ISSUE THREAD

**Issue by AkihiroSuda** [actions/runner-images#11021]
### Description

`xcrun --show-sdk-version` began to fail in  [`macos-15-arm64/20241118.362`](https://github.com/actions/runner-images/releases/tag/macos-15-arm64%2F20241118.362): 
https://github.com/lima-vm/lima/actions/runs/11926090231/job/33239305288
```
2024-11-20 03:19:58.872 xcodebuild[3694:23068] Writing error result bundle to /var/folders/lk/k1lvvf3j5wv0tknvl_jqs0hw0000gn/T/ResultBundle_2024-20-11_03-19-0058.xcresult
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

No error in 20241022.250.
https://github.com/lima-vm/lima/actions/runs/11924369458/job/33234574412

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/macos-15-arm64%2F20241118.362

https://github.com/lima-vm/lima/actions/runs/11926090231/job/33239305288

### Is it regression?

Yes

### Expected behavior

`xcrun --show-sdk-version` should successfully print the SDK version

### Actual behavior

`xcrun --show-sdk-version` fails as above.

### Repro steps

`xcrun --show-sdk-version`

**Comment by aartis17** [comment]
HI @AkihiroSuda, We will look into the issue and keep you posted with updates.

**Comment by aartis17** [comment]
Hi @AkihiroSuda, The error is coming because of Xcode CLT was updated from 16.0 to 16.1.

To find the macOS 15 arm64 SDKs, we need to select the xcode version as 16.1. Please find the code below.
Our readme file is in accordance with the below:

```
  - name: Get SDKs
      run: |
           sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
           xcodebuild -showsdks
           
  - name: SDK
      run : xcrun --show-sdk-version
           
```
Output: 
      
<img width="1204" alt="Screenshot 2024-11-22 at 2 40 51 PM" src="https://github.com/user-attachments/assets/6b04a6ba-a168-4de9-9a91-cb7b2f68d8c3">



<img width="1119" alt="Screenshot 2024-11-22 at 2 34 09 PM" src="https://github.com/user-attachments/assets/19b91b58-f232-434c-a0f6-e5de6ec6c8a9">

Hope this resolves issue ! Please free to reach out if any further questions.

**Comment by AkihiroSuda** [comment]
Thanks, is there any intentional reason that 16.1 isn't selected by default?

**Comment by erik-bershel** [comment]
> Thanks, is there any intentional reason that 16.1 isn't selected by default?

Yes, we leave it to the users. Switching the default version on our side does not make much sense - each user is free to choose the version of `Xcode` they need. We usually do this either upon request (usually due to some very global issues in a specific release) or after the release of new minor versions is completed (for example, for version `15.4`).

**Comment by nirs** [comment]
> Hi @AkihiroSuda, The error is coming because of Xcode CLT was updated from 16.0 to 16.1.
> 
> To find the macOS 15 arm64 SDKs, we need to select the xcode version as 16.1. Please find the code below. Our readme file is in accordance with the below:
> 
> ```
>   - name: Get SDKs
>       run: |
>            sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
>            xcodebuild -showsdks
>            
>   - name: SDK
>       run : xcrun --show-sdk-version
>            
> ```

So we need to select the xcode version before we run xcrun?

This is reasonable workaround, but feels wrong. The xcodebuild and xcrun commands should work regardless of the currently selected xcode version.

**Comment by aartis17** [comment]
@nirs, xcodebuild will run using the default Xcode version for the specific image. For example, for macOS 14, the default version is 15.4, and for macOS 15, it is 16.0. If you wish to set 16.1 as the default, we can usually accommodate this upon request.

**Comment by aartis17** [comment]
@AkihiroSuda We are closing this request due to no response from your side. If you still need assistance, please feel free to reopen the issue. :) 
Thank you.

**Comment by devinbinnie** [comment]
This has now switched to Xcode 16.2, causing our workflow to break again. I was able to switch to 16.2, but is there a path we can use that's fixed so that I don't need to go in and update this everytime a new Xcode version is released?

**Comment by erik-bershel** [comment]
Hey @devinbinnie!

Issue with Xcode 16.2 will be investigated here: https://github.com/actions/runner-images/issues/11348
