### ISSUE TITLE
windows 2022 image: AzureCosmosDbEmulator Checksum verification failed

### ISSUE THREAD

**Issue by isandulache** [actions/runner-images#11022]
### Description

**_AzureCosmosDbEmulator Checksum verification failed when building windows 2022 image_**

**Build error log :**

```

Provisioning with powershell script: /home/vsts/work/1/s/Packer/runner-images/images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\g5ja4od5.msi...
Package downloaded in 591.82 seconds
Checksum verification failed: expected 1EF64CF9CD13C611AAC394113A703AF6F525C7C39BFB6B4C3F884D57F6F1D1CF, got
5E4F4086F02B7FB12334D4E6494DCD2081F284B76B264E035376A9334E106B6B
At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
+         throw "Checksum verification failed: expected $expectedHash,  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Checksum verifi...376A9334E106B6B:String) [], RuntimeException
    + FullyQualifiedErrorId : Checksum verification failed: expected 1EF64CF9CD13C611AAC394113A703AF6F525C7C39BFB6B4C3
   F884D57F6F1D1CF, got 5E4F4086F02B7FB12334D4E6494DCD2081F284B76B264E035376A9334E106B6B

Provisioning step had errors: Running the cleanup provisioner, if present...

```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

Install-AzureCosmosDbEmulator.ps1 should be run without error

### Actual behavior

Install-AzureCosmosDbEmulator.ps1 is failing with error

### Repro steps

run Install-AzureCosmosDbEmulator.ps1 script

**Comment by kishorekumar-anchala** [comment]
We will update you shortly. thanks you !
