### ISSUE TITLE
Arm64 based Mac machine is not picked

### ISSUE THREAD

**Issue by sravanmetro** [actions/runner-images#11034]
### Description

I want to use arm64 (M series) Mac for the pipeline. when I use the labels `macos-latest` or `macos-14` the system is picking up a machine with Intel processor. 

Also, the following labels are not working when I trigger from Azure pipeline.
`macos-latest-xlarge` or `macos-14-xlarge`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: macos-14
Version: 20241118.366
Included Software: [https://github.com/actions/runner-images/blob/macos-14/20241118.366/images/macos/macos-14-Readme.md](https://github.com/actions/runner-images/blob/macos-14/20241118.366/images/macos/macos-14-Readme.md)
Image Release: [https://github.com/actions/runner-images/releases/tag/macos-14%2F20241118.366](https://github.com/actions/runner-images/releases/tag/macos-14%2F20241118.366)

### Is it regression?

Yes

### Expected behavior

right machine to be picked up according to the image label given. 

### Actual behavior

when I mention arm64 based image label, system is picking non-arm64 based machine.

### Repro steps

In the `azure-pipelines.yml`, mention 
`vmImage: macos-14`

trigger the build 
just observe the machine type under "Initialize job" -> "Runner Image" -> "Included software".

**Comment by aartis17** [comment]
Hi @sravanmetro,  We will look into the issue and keep you posted with updates.

**Comment by erik-bershel** [comment]
Hey @sravanmetro!
Please, see there: [Microsoft Hosted agents documentation and YAML labels scheme](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software)

Also this issue is a duplicate to https://github.com/actions/runner-images/issues/8971, so I am going to close it now. 😞 Feel free to open new issues in case of other problems with the runner images.
