### ISSUE TITLE
Update/Add .NET workload 'wasm-tools'

### ISSUE THREAD

**Issue by mip1983** [actions/runner-images#11049]
### Tool name

.NET workload wasm-tools

### Tool license

Microsoft owned .NET

### Add or update?

- [X] Add
- [ ] Update

### Desired version

9.0.0 or latest

### Brief description of tool

Can I request that both the 'windows-latest' and 'ubuntu-latest' have the .NET workload 'wasm-tools' (used by Blazor Web) installed by default?

I would say for both these images, it would be good if they had the latest .NET sdk (9.0.0 at time of writing) and any .NET workloads (wasm-tools, maui) installed by default so I don't need to run a dotnet workload restore step in my pipeline.

I imagine quite a lot of people are using .NET and Blazor, given they're you're main SDK and web UI framework, it would be good if they get first class support in any pipelines.

### URL for tool's homepage

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-restore

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, but it adds and extra 2-5 minutes to each build step

You can use:

- task: DotNetCoreCLI@2
  displayName: 'dotnet workload restore'
  inputs:
      command: 'custom'
      custom: 'workload'
      arguments: 'restore
```

### Tool installation time in runtime

2-5 minutes

### Are you willing to submit a PR?

Wouldn't know how

**Comment by RaviAkshintala** [comment]
Hi @mip1983 Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by lakshminarayana02** [comment]
Hi @mip1983 

Wasm.tools 9.0.24.52809 is already available for Windows 2022, and it may not be possible to add these packages in Ubuntu OS owing to the lightweight image,  it is always advised that you use it in runtime for Linux.

**Comment by mip1983** [comment]
> Hi @mip1983
> 
> Wasm.tools 9.0.24.52809 is already available for Windows 2022, and it may not be possible to add these packages in Ubuntu OS owing to the lightweight image, it is always advised that you use it in runtime for Linux.

Hi there,

I've just tried a build on a 'windows-latest' agent without the dotnet workload restore step, and it doesn't seem like wasm-tools are installed, I get the following error:

>ERROR: 
error NETSDK1147: **To build this project, the following workloads must be installed: wasm-tools** 
error NETSDK1147: **To install these workloads, run the following command: dotnet workload restore** 


Given the .NET Aspire documentation and azd tool are generating pipelines with 'ubuntu-latest' as the default, I'd suggest it would make sense if this image did have .NET and the latest workload tools. Otherwise people using the docs verbatim will end up with pipelines that spend a lot of time/CPU cycles/C02 wasted doing this repeated work of installing .NET and workloads.
