### ISSUE TITLE
Windows2022 - DacFx signature thumbprint

### ISSUE THREAD

**Issue by BlakeWills** [actions/runner-images#11053]
### Description

I've been trying to get a build of the Windows 2022 image for the last several weeks, each time they fail with invalid signature thumbprint on various packages. This time it seems to fail on DacFx:

```
Provisioning with powershell script: D:/a/1/s/virtual-environments/images/windows/templates/../scripts/build/Install-DACFx.ps1
    azure-arm.image: Downloading package from https://aka.ms/dacfx-msi to C:\Users\packer\AppData\Local\Temp\hs4egueb.msi...
    azure-arm.image: Package downloaded in 0.77 seconds
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
```

As a side note, are the Windows image builds usually this flaky? I've tried 6 runs since the 12th November and none have succeeded - whereas the Linux builds are usually fine. Is there something we can do in the provisioners to retry the download should it fail? There's been a few instances where just re-running the build seemingly fixes it, but that's not great when you're two hours in.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

N/A

### Expected behavior

DacFx is expected to install correctly.

### Actual behavior

DacFx provisioner throws a signature thumbprint validation error.

### Repro steps

Follow the manual image generation instructions:
https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#manual-image-generation

**Comment by RaviAkshintala** [comment]
Hi @BlakeWills DAcFx signature has been [updated](https://github.com/actions/runner-images/pull/11030), Could you please retry by forking latest code from main branch.
Closing this issue,Thank you.
