### ISSUE TITLE
ubuntu-24.04 claims ruby versions, but none are installed

### ISSUE THREAD

**Issue by martinemde** [actions/runner-images#11051]
### Description

The [Readme](https://github.com/actions/runner-images/blob/ubuntu24/20241117.1/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L28) for ubuntu-24.04 says that Ruby 3.2.3 is available on the image. This must be the installed system ruby because no others are listed as available.

If you look [here](https://github.com/actions/runner-images/blob/55793912317c82b0d448a99290dc7224f972d217/images/ubuntu/toolsets/toolset-2404.json#L52), you can see that there are no versions of ruby.

You can also see this in my azure pipelines output on ubuntu-24.04:

```
Starting: UseRubyVersion
==============================================================================
Task         : Use Ruby version
Description  : Use the specified version of Ruby from the tool cache, optionally adding it to the PATH
Version      : 0.248.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-ruby-version
==============================================================================
##[error]Version spec 3.2 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /opt/hostedtoolcache

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Ruby at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Ruby versions at https://go.microsoft.com/fwlink/?linkid=2005989.
Finishing: UseRubyVersion
```

Given that [2 different minor versions](https://github.com/actions/runner-images/blob/55793912317c82b0d448a99290dc7224f972d217/images/ubuntu/toolsets/toolset-2204.json#L53-L59) are available on ubuntu-22.04, it seems like a strange oversight to exclude any selectable versions of ruby from the toolset.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20241117.1.0

### Is it regression?

ubuntu-22.04

### Expected behavior

Expected ruby 3.2 and ruby 3.3 to be selectable with UseRubyVersion.

### Actual behavior

No rubies are selectable with UseRubyVersion.

### Repro steps

Create a pipeline with UseRubyVersion in azure-pipeline.yml on an ubuntu-24.04 image on a microsoft hosted agent.

```yaml
          - task: UseRubyVersion@0
            inputs:
              versionSpec: "3.2.3"
              addToPath: true
```

**Comment by RaviAkshintala** [comment]
Hi @martinemde Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by RaviAkshintala** [comment]
Hi @martinemde The [Ruby](https://github.com/actions/runner-images/blob/20d0451bdd96d99951cbaff4be26f9e56ddbcbae/images/ubuntu/toolsets/toolset-2404.json#L49) version 3.2.* has been added in toolset-24.04 , and new image with the changes has been deployed. Could you please retry by forking latest code from main branch. We are closing this issue, thanks.

**Comment by martinemde** [comment]
Thanks for the quick fix.
