### ISSUE TITLE
[ubuntu 24.04] install-powershell.sh script fails with 404

### ISSUE THREAD

**Issue by habandy** [actions/runner-images#11055]
### Description

Hi there, 

Currently the script [images/ubuntu/scripts/build/install-powershell.sh](https://github.com/actions/runner-images/blob/20d0451bdd96d99951cbaff4be26f9e56ddbcbae/images/ubuntu/scripts/build/install-powershell.sh#L15C93-L15C125) fails because of http return 404 - file not found. 

It tries to download `https://mirrors.edge.kernel.org/ubuntu/pool/main/i/icu/libicu72_72.1-3ubuntu2_amd64.deb`

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

_

### Is it regression?

no

### Expected behavior

Working url

### Actual behavior

failing with http 404

### Repro steps

Start the build workflow

**Comment by vidyasagarnimmagaddi** [comment]
Hi @habandy , Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by habandy** [comment]
Updated the issue. This only affects ubuntu 24.04 as it seems, because of the if condition in the script. older versions like 20.04 and 22.04 should not be affected.

**Comment by RaviAkshintala** [comment]
Hi @habandy This [PR](https://github.com/actions/runner-images/pull/11062) will fix your issue and it has been merged. Could you please retry by forking the latest code from the main branch. We are closing this issue, thanks.
