### ISSUE TITLE
linux image build fails due to kotlin tests

### ISSUE THREAD

**Issue by H777K** [actions/runner-images#11058]
### Description

Currently the ubuntu image builds are failing, because in the latest kotlin release the `kotlin-dce-js.bat` has been removed, but it´s still covered by the pester test.

There is already an PR which fixes this for windows images (#11056). 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

\-

### Is it regression?

no

### Expected behavior

The kotlin pester tests should not throw an error.

### Actual behavior

The kotlin pester test is failing because `kotlin-dce-js.bat` has been removed, but it´s still covered by the test.

### Repro steps

Build a linux image.

**Comment by RaviAkshintala** [comment]
Hi @H777K Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by PrashantRaj18198** [comment]
This is happening for macos images as well. Mac builds are failing with similar error.
```
[-] kotlin-dce-js is available 38ms (38ms|1ms)
Command 'kotlin-dce-js -version' has finished with exit code
/bin/bash: kotlin-dce-js: command not found
at "$toolName -version" | Should -ReturnZeroExitCode, /Users/<sensitive>/image-generation/tests/BasicTools.Tests.ps1:166
```

**Comment by H777K** [comment]
@PrashantRaj18198 Yes, this is happening for windows, linux and macos images. I´ve already raised a PR which fixes this for the ubuntu images, the same has to be done for macos here:

https://github.com/actions/runner-images/blob/9b0a6c08c91f2bb7dacb0fd69771f18c06aa43ea/images/macos/scripts/tests/BasicTools.Tests.ps1#L162-L163

**Comment by RaviAkshintala** [comment]
Hi @H777K This [PR](https://github.com/actions/runner-images/pull/11062) has been merged. Could you please retry by forking the latest code from the main branch.We are closing this issue, thanks.
