### ISSUE TITLE
windows 2022 image: AzureCosmosDbEmulator Checksum verification failed

### ISSUE THREAD

**Issue by antika080** [actions/runner-images#11061]
### Description

Provisioning with powershell script: /agent/_work/27/s/runner-images/images/windows/templates/../scripts/build/Install-AzureCosmosDbEmulator.ps1
Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\xe0ii32y.msi...
Package downloaded in 90.94 seconds
Checksum verification failed: expected 1EF64CF9CD13C611AAC394113A703AF6F525C7C39BFB6B4C3F884D57F6F1D1CF, got
E43CB2D88D5A3E3029C885B217EDDD0290AB9D40B616EB83EBCACCAC7A3CE30A
At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
+         throw "Checksum verification failed: expected $expectedHash,  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Checksum verifi...BCACCAC7A3CE30A:String) [], RuntimeException
+ FullyQualifiedErrorId : Checksum verification failed: expected 1EF64CF9CD13C611AAC394113A703AF6F525C7C39BFB6B4C3
F884D57F6F1D1CF, got E43CB2D88D5A3E3029C885B217EDDD0290AB9D40B616EB83EBCACCAC7A3CE30A

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

Install-AzureCosmosDbEmulator.ps1 should be run without error

### Actual behavior

Install-AzureCosmosDbEmulator.ps1 is failing with error

### Repro steps

run Install-AzureCosmosDbEmulator.ps1 script

**Comment by RaviAkshintala** [comment]
Hi @antika080 Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by antika080** [comment]
@RaviAkshintala @hemanthmanga how much time it will take to resolve this issue?

**Comment by hemanthmanga** [comment]
Hi @antika080, 
AzureCosmosDbEmulator Checksum is already upto date, kindly sync the main branch. We are closing this issue. Thank you.
