### ISSUE TITLE
Update/Add XCode

### ISSUE THREAD

**Issue by jjohnnyl** [actions/runner-images#11060]
### Tool name

Xcode 16.1

### Tool license

XCode 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16.1

### Brief description of tool

Requesting XCode 16.1 on macOS-15 image

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by vaishalipawar1490** [comment]
Hi @jjohnnyl,
We are looking into it. Will keep you posted.

**Comment by vaishalipawar1490** [comment]
Hi @jjohnnyl 
Xcode 16.1 has already been added to both the macOS 15 and macOS 15 ARM64 runner images.
You can find the relevant details in the following README files:

[macOS - 15 README ](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md)
[macOS - 15 ARM 64 README ](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md)

These documents list all the tools available on the respective runner images, including Xcode 16.1.
Feel free to reach out if you need any further assistance. Thanks!

**Comment by erik-bershel** [comment]
To use Xcode 16.1 you need to select it from installed (for example):
```bash
        echo "Setting Xcode version..."
        sudo xcode-select -s /Applications/Xcode_16.1.app
```

**Comment by jjohnnyl** [comment]
Hi, thanks for the updated.

Can newer versions of xcode be defaulted when maui ios workloads require the newer versions of xcode?

**Comment by erik-bershel** [comment]
> Can newer versions of xcode be defaulted when maui ios workloads require the newer versions of xcode?

I think we'll return to this somewhere around January, yeah.
