### ISSUE TITLE
Fail to install XCTestHTMLReport in macOS-14-arm64 image

### ISSUE THREAD

**Issue by KangxuanYe** [actions/runner-images#11079]
### Description

Our team is running our iOS E2E testing on `macOS-14-arm64` image. Here are some information from our CI pipeline regarding of VM image.

```
Starting: Initialize job
Agent name: 'Azure Pipelines 34'
Agent machine name: 'Mac-1733167460320'
Current agent version: '4.248.0'
Operating System
macOS
14.7.1
23H222
Runner Image
Image: macos-14-arm64
Version: 20241202.580
Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20241202.580/images/macos/macos-14-arm64-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20241202.580
Runner Image Provisioner
2.0.385.1+6d6c56aa16f1b9c7dd7935df5d63980397e44def
Current image version: '20241202.580'
Agent running as: 'runner'
```

There is one step which requests to install XCTestHtmlReport to parse test result. You can check the link here: https://github.com/OfficeDev/microsoft-teams-library-js/blob/7e9582d8336daa9e63a9da95959ef8e3581063a9/tools/yaml-templates/ios-test.yml#L15-L22

```
  - task: Bash@3
    displayName: 'Install XCTestHtmlReport for publishing result'
    inputs:
      targetType: inline
      script: |
        brew install xctesthtmlreport
      workingDirectory: '$(Agent.BuildDirectory)/iOSHost'
      condition: always()
```

Sometimes, it will run into the failure as below. Could you please help investigate it and tell us how to make it more stable?

```
Generating script.
Script contents:
brew install xctesthtmlreport
========================== Starting Command Output ===========================
/bin/bash /Users/runner/work/_temp/1b7514fe-ba5a-41d8-8a01-9cc2ca868aa9.sh
dyld[4604]: terminating because inserted dylib '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' could not be loaded: tried: '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (no such file), '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e'))
dyld[4604]: tried: '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (no such file), '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e'))
/Users/runner/work/_temp/1b7514fe-ba5a-41d8-8a01-9cc2ca868aa9.sh: line 1:  4604 Abort trap: 6           brew install xctesthtmlreport
```

Please let me know If you have any questions.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: macos-14-arm64
Version: 20241202.580

We cannot share build link for some purposes.

### Is it regression?

No

### Expected behavior

This task should be completed successfully and no intermittent failure

### Actual behavior

We will have intermittent failure on this task

### Repro steps

No way to repro. It fails sometimes. We cannot tell when it will fail.

**Comment by susmitamane** [comment]
Hi @KangxuanYe 

We will look into the issue and keep you posted with updates.

Thank You.

**Comment by angelapwen** [comment]
Hi @KangxuanYe — thank you for the note. We have a related fix in the CodeQL v2.19.4 build tracer that has just been released. Could you try the workflow again (including using the newest version of CodeQL) and let us know if the error persists? Thank you!

**Comment by KangxuanYe** [comment]
Hi @angelapwen @susmitamane , thank you for being activated on helping investigating and fixing this issue. This is an intermittent issue in our side so I cannot reproduce/retry it. However, we will keep monitoring on this and if there are still some exceptions happening, we will report to you.

**Comment by angelapwen** [comment]
Thank you! If the error continues to be CodeQL-related, feel free to post in https://github.com/github/codeql for a slightly faster turnaround time 😸 the CodeQL team doesn't directly monitor this repository!

**Comment by angelapwen** [comment]
Ah, my colleagues just reminded me that since you're reporting the issue from Microsoft, we have a separate support escalation for CodeQL for MSFT: http://aka.ms/codeql that you should reach out to next time 😄

**Comment by KangxuanYe** [comment]
@angelapwen, thanks a lot. I have a question not related to this issue. Do you happen to know which team is working for `publishArtifact` task in pipeline?

**Comment by angelapwen** [comment]
I think that is probably one of the teams working on the Microsoft side and not the GitHub side 🤔 at GitHub we generally don't own any of the MSFT pipelines!

**Comment by KangxuanYe** [comment]
Okay. Thank you! That's helpful and at least narrow down my searching scope.

**Comment by KangxuanYe** [comment]
@angelapwen , sorry I need to reopen this issue because we encountered the same thing again

```
Agent name: 'Azure Pipelines 180'
Agent machine name: 'Mac-1733521058405'
Current agent version: '4.248.0'
Operating System
Runner Image
Image: macos-14-arm64
Version: 20241206.593
Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20241206.593/images/macos/macos-14-arm64-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20241206.593
Runner Image Provisioner
2.0.385.1+6d6c56aa16f1b9c7dd7935df5d63980397e44def
Current image version: '20241206.593'
Agent running as: 'runner'
```

```
dyld[5597]: terminating because inserted dylib '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' could not be loaded: tried: '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (no such file), '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e'))
dyld[5597]: tried: '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (no such file), '/Users/runner/work/_temp/codeql3000/distribution/codeql/tools/osx64/libtrace.dylib' (fat file, but missing compatible architecture (have 'x86_64,arm64', need 'arm64e'))
/Users/runner/work/_temp/9cf1a082-9e62-4e9e-b571-2167da04e358.sh: line 1:  5597 Abort trap: 6           brew install xctesthtmlreport
```

I tried to use your link dropped me to file a bug ticket for codeQL team but it is hard for me to find the right entrance to do so. That is why I came back and asked for your help. Do you know why we are still getting the same error? Is this because the fix has not been deployed?

Thank you so much for helping

**Comment by angelapwen** [comment]
Hi @KangxuanYe, apologies! Could you use http://aka.ms/codeqlsupport instead? Apparently the link changed 😓 

The original fix was definitely released 😢 so there may need to be an additional fix for your use case. If you could raise the issue with that link ^ you should get the appropriate support for CodeQL for MSFT! Thanks!!

**Comment by KangxuanYe** [comment]
Sure @angelapwen, thank you for redirecting to the right place.
