### ISSUE TITLE
Getting error New-Item : The path is not of a legal form for Windows builds

### ISSUE THREAD

**Issue by angaaruriakhil** [actions/runner-images#11077]
### Description

As part of commit https://github.com/actions/runner-images/commit/5a263020f559343719f2dbacfd1065e94a691c11 , the code was changed so that a new temp directory is now being used under D:\\temp for both Windows 2022 and Windows 2019 builds. 

Now, when running a build, it fails to create the temp folder under the D:\\ filesystem, with a "The path is not of a legal form" error. 

Our build continues and then fails later on when there is no directory to refer to. 

 _azure-arm.build_vhd: New-Item : The path is not of a legal form.
    azure-arm.build_vhd:     Directory: C:\
    azure-arm.build_vhd:
    azure-arm.build_vhd:
    azure-arm.build_vhd: Mode                 LastWriteTime         Length Name
    azure-arm.build_vhd: ----                 -------------         ------ ----
    azure-arm.build_vhd: d-----         12/2/2024   4:56 PM                image
    azure-arm.build_vhd: D:\temp
    azure-arm.build_vhd: C:\image
==> azure-arm.build_vhd: At C:\Windows\Temp\script-674de6be-9e8b-7fe2-a892-4428e383d125.ps1:6 char:1
==> azure-arm.build_vhd: + New-Item -Path $temp_dir -ItemType Directory -Force
==> azure-arm.build_vhd: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.build_vhd:     + CategoryInfo          : InvalidArgument: (D:\:String) [New-Item], ArgumentException
==> azure-arm.build_vhd:     + FullyQualifiedErrorId : CreateDirectoryArgumentError,Microsoft.PowerShell.Commands.NewItemCommand
==> azure-arm.build_vhd:_

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Self hosted VMSS

### Is it regression?

Yes

### Expected behavior

New-Item should provision the temp directory as needed

### Actual behavior

Receiving this error: 

```
 azure-arm.build_vhd: New-Item : The path is not of a legal form.
    azure-arm.build_vhd:     Directory: C:\
    azure-arm.build_vhd:
    azure-arm.build_vhd:
    azure-arm.build_vhd: Mode                 LastWriteTime         Length Name
    azure-arm.build_vhd: ----                 -------------         ------ ----
    azure-arm.build_vhd: d-----         12/2/2024   4:56 PM                image
    azure-arm.build_vhd: D:\temp
    azure-arm.build_vhd: C:\image
==> azure-arm.build_vhd: At C:\Windows\Temp\script-674de6be-9e8b-7fe2-a892-4428e383d125.ps1:6 char:1
==> azure-arm.build_vhd: + New-Item -Path $temp_dir -ItemType Directory -Force
==> azure-arm.build_vhd: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.build_vhd:     + CategoryInfo          : InvalidArgument: (D:\:String) [New-Item], ArgumentException
==> azure-arm.build_vhd:     + FullyQualifiedErrorId : CreateDirectoryArgumentError,Microsoft.PowerShell.Commands.NewItemCommand
==> azure-arm.build_vhd:
```

### Repro steps

Clone down runner-images repo and perform an image build of either Windows 2019 or Windows 2022 with Packer

**Comment by jshield** [comment]
I'm also getting a number of errors related to the haphazard merge of the new temp_dir changes, using a vm sku that has a scratch disk appears to now be mandatory.

particularly the VS Log Collect tool appears to write the logs to $TEMP, but the scripts expect it in $TEMP_DIR, and thus breaks the build because the expected path isn't being passed to the collect tool.

**Comment by hemanthmanga** [comment]
Hi @angaaruriakhil, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by vidyasagarnimmagaddi** [comment]
Hi @angaaruriakhil ,
Our builds are successful , we are not facing issue. Kindly synch your main, try to build. If error, revert with the logs /runs . thanks

**Comment by angaaruriakhil** [comment]
Hi, we do a fresh clone of the repo every time we do a build. I'm still seeing the same issue, I've now reverted to using the old temp directory as a workaround which gets it past the initial error. 

```
variable "temp_dir" {
  type    = string
  default = "C:\\Users\\packer\\AppData\\Local\\Temp"
}
```

As a result of this change, is a particular vm_size, or particular scratch disk now required? Because the advice currently is that it can be customized. https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md. I would like some more clarity on the practices we should be following as consumers of this repo, as this change has come in out of nowhere and broken our builds.

**Comment by Alexey-Ayupov** [comment]
Hello @angaaruriakhil, the directory for temporary files has been moved to drive `D:` due to the new cleanup process.

You are getting an error because the VM size you selected ([Standard_D8s_v4](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dv4-series?tabs=sizestoragelocal)) does not have a local (temporary) disk. However [Fsv2 sizes series](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/compute-optimized/fsv2-series?tabs=sizestoragelocal#host-specifications) do have such drive.

To workaround this issue, you can either update VM size `variable "vm_size"` or update the variable for temporary files `variable "temp_dir"`, which you essentially already did.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @angaaruriakhil  , Hope your issue resolves. We are closing this issue . thanks.
