### ISSUE TITLE
`gsutil` appears to be broken with Ubuntu 24.04 on v1.0.5 (seen on arm64)

### ISSUE THREAD

**Issue by phlax** [actions/runner-images#11089]
### Description

We have some ci that uses gsutil

Since today our large arm runners have started failing  (arm64/ubuntu 24.04)

```console
Run gsutil --version
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
	1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
	2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.
```

gsutil always had the python requirement in its setup.py but for some reason it was ignored - we install it a few ways and it ~works

the difference between today and yesterday appears to be that the vms were updated to v1.0.5 and now it reliably fails 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```console
VM Image
  OS: Linux (arm64)
  Source: Marketplace
  Publisher: arm
  Offer: github_arm_linux_runner_2404
  Plan: github_arm_linux_runner_plan_2404
  Version: 1.0.5
```

https://github.com/envoyproxy/envoy/actions/runs/12134322882/job/33831342212#step:1:4

### Is it regression?

yes

### Expected behavior

to be able to use the installed `gsutil`

### Actual behavior

error when tryng to use `gsutil` related to the system version of python

### Repro steps

- create a (large) arm64 runner
- run: `gsutil --version`

**Comment by hemanthmanga** [comment]
Hi @phlax,  Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by phlax** [comment]
fwiw we have other ci that is using v1.0.7 - everything appears to work as expected in that case

**Comment by RaviAkshintala** [comment]
Hi @phlax After merging the mentioned PR, it appears that your build is successful. gsutil can be installed via pip on Python versions 3.12.1 and above. We are closing this issue. Thank you.
