### ISSUE TITLE
Android emulator removed in the latest Ubuntu 22.04 image (20241201.1)

### ISSUE THREAD

**Issue by skyline75489** [actions/runner-images#11092]
### Description

Android emulator can no longer be found with the latest Ubuntu 22.04 image (20241201.1)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/microsoft/onnxruntime-genai/actions/runs/12151684632/job/33886721985

### Is it regression?

20241124.1.0

### Expected behavior

Android emulator can be found and used.

The job worked with 20241124.1.0. See: https://github.com/microsoft/onnxruntime-genai/actions/runs/12134105425/job/33830765031

### Actual behavior

Android emulator can't be found.

### Repro steps

Nothing really changes from our side. After the latest image release, our Python testing code throws exception:

```text
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/android/sdk/emulator'
```

**Comment by baijumeswani** [comment]
@hemanthmanga any update on this?

**Comment by skyline75489** [comment]
Switching to Ubuntu 24.04 doesn't help, either. See https://github.com/microsoft/onnxruntime-genai/actions/runs/12368157404/job/34517650932?pr=1155

@hemanthmanga  Is it safe to say Android emulator will not be available in the future? If so, we'll need to migrate our tests somewhere else.

**Comment by skyline75489** [comment]
We've switched to our own self-hosted pool and added additional steps to install android emulator. I'll close this for now.

**Comment by hemanthmanga** [comment]
> Switching to Ubuntu 24.04 doesn't help, either. See https://github.com/microsoft/onnxruntime-genai/actions/runs/12368157404/job/34517650932?pr=1155
> 
> @hemanthmanga Is it safe to say Android emulator will not be available in the future? If so, we'll need to migrate our tests somewhere else.

At the moment, we do not have any information. If there is any, it will be announced, Thanks.
