### ISSUE TITLE
Broken docker capabilities

### ISSUE THREAD

**Issue by henkhofs** [actions/runner-images#11099]
### Description

Until yesterday we were able to run docker compose with a service with the following capabilities on the github runners just fine, but since today the jobs started failing with errors about insufficient permissions to open the TUN/TAP 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

was working in 20241124.1.0 got broken in 20241201.1.0

### Is it regression?

20241124.1.0

### Expected behavior

the capabilities are added to the docker container

### Actual behavior

getting permission denied errors inside the container, which leads me to believe the capabilities do no get applied properly to the container

### Repro steps

docker compose file with a service with the following config:
```
    cap_add:
      - NET_ADMIN
      - NET_RAW
 ```

**Comment by hemanthmanga** [comment]
Hi @henkhofs Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by mgsnuno** [comment]
same issue: `options: --cap-add=NET_ADMIN` stopped working in github actions

**Comment by henkhofs** [comment]
any update on this? it's blocking us from getting new code to production....

**Comment by mgsnuno** [comment]
same here

**Comment by Prabhatkumar59** [comment]
Hi @henkhofs - Thanks for your input. We are look into this issue and will update you shortly.

**Comment by mgsnuno** [comment]
@Prabhatkumar59 unfortunately `options: --cap-add=NET_ADMIN` still not working with https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241211.1

**Comment by henkhofs** [comment]
Yes, still broken

**Comment by Prabhatkumar59** [comment]
Hey @henkhofs - Thanks for your input. Could you please share the build link where it says **options: --cap-add=NET_ADMIN** is broken. In meantime, we will check more into this closely and will update you. Thanks!

**Comment by henkhofs** [comment]
it's in private repos, so you wont be able to see any output there

**Comment by henkhofs** [comment]
Seems I was able to resolve this by adding: 
```
devices:
  - /dev/net/tun
 ```
to my compose file, must be something in docker that changed, but works again now.
