### ISSUE TITLE
Windows Server 2022 agent cannot build C ARM projects anymore: missing kernel32.lib

### ISSUE THREAD

**Issue by vbaderks** [actions/runner-images#11094]
### Description

I have an C++ open source project that is cross-platform. I noticed that suddenly the arm build started to fail with the following error:

```
-- The C compiler identification is MSVC 19.42.34435.0
-- The CXX compiler identification is MSVC 19.42.34435.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/arm/cl.exe
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/arm/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/arm/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'D:/a/1/b/build/CMakeFiles/CMakeScratch/TryCompile-wdner9'
    
    Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_f8e41
    [1/2] C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Ob0 /Od -MDd -Zi /showIncludes /FoCMakeFiles\cmTC_f8e41.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_f8e41.dir\ /FS -c D:\a\1\b\build\CMakeFiles\CMakeScratch\TryCompile-wdner9\testCCompiler.c
    [2/2] C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --msvc-ver=1942 --intdir=CMakeFiles\cmTC_f8e41.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm\link.exe /nologo CMakeFiles\cmTC_f8e41.dir\testCCompiler.c.obj  /out:cmTC_f8e41.exe /implib:cmTC_f8e41.lib /pdb:cmTC_f8e41.pdb /version:0.0 /machine:ARM  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib && cd ."
    FAILED: cmTC_f8e41.exe 
    C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --msvc-ver=1942 --intdir=CMakeFiles\cmTC_f8e41.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm\link.exe /nologo CMakeFiles\cmTC_f8e41.dir\testCCompiler.c.obj  /out:cmTC_f8e41.exe /implib:cmTC_f8e41.lib /pdb:cmTC_f8e41.pdb /version:0.0 /machine:ARM  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm\link.exe /nologo CMakeFiles\cmTC_f8e41.dir\testCCompiler.c.obj /out:cmTC_f8e41.exe /implib:cmTC_f8e41.lib /pdb:cmTC_f8e41.pdb /version:0.0 /machine:ARM /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_f8e41.dir/intermediate.manifest CMakeFiles\cmTC_f8e41.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

    ninja: build stopped: subcommand failed.
```

The full logs can be found at:
https://dev.azure.com/team-charls/charls/_build/results?buildId=2083&view=logs&jobId=ec0dcfab-c10e-56a1-e68f-f5d8d94dae3f&j=ec0dcfab-c10e-56a1-e68f-f5d8d94dae3f&t=2a383810-ca08-5e2a-499d-ec462f92ef28

The ARM-64 build is working ok.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

2.0.385.1
Current image version: '20241201.2.0'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.246.1)
Downloading task: BatchScript (1.226.0)
Downloading task: CMake (1.246.1)

The full logs can be found at:
https://dev.azure.com/team-charls/charls/_build/results?buildId=2083&view=logs&jobId=ec0dcfab-c10e-56a1-e68f-f5d8d94dae3f&j=ec0dcfab-c10e-56a1-e68f-f5d8d94dae3f&t=2a383810-ca08-5e2a-499d-ec462f92ef28

### Is it regression?

https://dev.azure.com/team-charls/charls/_build/results?buildId=2075&view=logs&j=ec0dcfab-c10e-56a1-e68f-f5d8d94dae3f

### Expected behavior

CMake would be able to compile and link a C app for the arm architecture

### Actual behavior

CMake fails to link the app 

### Repro steps

Start a build pipeline 
Note: I have removed the currently failing CI step from the lastest .yml file

**Comment by hemanthmanga** [comment]
Hi @vbaderks, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by zufuliu** [comment]
Duplicate of issue #10981.

**Comment by vbaderks** [comment]
@zufuliu: thanks for the feedback. This issue is indeed a duplicate of #10981
