### ISSUE TITLE
Conflicting MinGW-w64 installations on windows-2019 runner

### ISSUE THREAD

**Issue by Flamefire** [actions/runner-images#11102]
### Description

We use the MinGW-w64 installation on the windows-2019 runners as part of our tests. This setup uses a matrix to run variations using the ubuntu and windows runners (and other dimensions not relevant here). To make this easier we use `bash` as the shell via `jobs.<name>.defaults.run.shell` such that the same code works across the 2 OS types.

The C++ compiler is automatically found by CMake at `/c/mingw64/bin/c++` and compilation works well. However recently the tests started to fail coinciding with using the C++11 threading features such as `thread_local`

Investigation showed that `/mingw64/bin` comes first in $PATH before  `/c/mingw64/bin` which causes a mismatch between the libraries linked by the compiler and those found at application startup leading to instant termination with exit code `0xc0000139 (STATUS_ENTRYPOINT_NOT_FOUND)`

This PATH mismatch is caused by using `bash` as the shell which forces prepending a path to $PATH which can not be avoided or overwritten using `$GITHUB_PATH`. I'm not sure, where those 2 MinGW actually come from as "MinGW" isn't [documented](https://github.com/actions/runner-images/blob/d7901f6e9320897e1be976b76981177b33949626/images/windows/Windows2019-Readme.md) although [installed.](https://github.com/actions/runner-images/blob/d7901f6e9320897e1be976b76981177b33949626/images/windows/scripts/build/Install-Mingw64.ps1) and available by default

As a workaround switching to `pwsh` as the shell for this step and limited to Windows resolves that.

However I'm wondering if the availability of the 2 conflicting versions of MinGW is intentional and if the situation can be improved by using a bash from the installed MinGW or changing the order in $PATH such that using the bash doesn't shadow the MinGW paths although I expect similar issues with running bash now.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image
  Image: windows-2019
  Version: 20241125.1.0

windows-2022 has same issue as the same mingw installation script is used

### Is it regression?

No

### Expected behavior

Using MinGW and bash shell works together

### Actual behavior

Crash on compiled application startup

### Repro steps

1. Add a step using `bash` as the shell on `windows-2019` runner
2. Compile C++ code containing `thread_local` variables using `c++` as the compiler
3. Run the resulting executable

**Comment by hemanthmanga** [comment]
Hi @Flamefire, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Flamefire 
Kindly provide an update whether the suggested workaround worked or not. thanks

**Comment by Flamefire** [comment]
@vidyasagarnimmagaddi Yes this workaround does work for me.

To be generic as that step is executed on all platforms I used:
` [[ "${{runner.os}}" != 'Windows' ]] || export PATH="/c/mingw64/bin:$PATH"`

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Flamefire 
Thanks for confirming. We are closing this issue.

**Comment by johan-boule** [comment]
A workaround is enough to close issues at Microsoft?
