### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by ETEnterprises1** [actions/runner-images#11113]
### Tool name

Add User

### Tool license

Apache Maven v.2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

.dev

### Brief description of tool

this tool is so that when new users get on my page they will be able to add an account via developer mode 

### URL for tool's homepage

BMOFinancialGroup.com/tools

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
yes
```

### Are you willing to submit a PR?

yes

**Comment by ETEnterprises1** [comment]
# Description
New tool, Bug fixing, or Improvement?
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.
**For new tools, please provide total size and installation time.**



#### Related issue:

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

**Comment by hemanthmanga** [comment]
Hi @ETEnterprises1 , Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.
