### ISSUE TITLE
Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by ChrisGibson1982** [actions/runner-images#11117]
### Description

The image creation process fails with the  error "Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string."  I am pulling the latest version of the runner-images repo as part of my process

`==> azure-arm.image: Provisioning with powershell script: C:/Agent7/_work/3/s/runner-images/images/windows/templates/../scripts/build/Install-Chocolatey.ps1
    azure-arm.image: Set TLS1.2
    azure-arm.image: Install chocolatey
==> azure-arm.image: Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
    azure-arm.image: Downloading package from https://chocolatey.org/install.ps1 to ...
    azure-arm.image: WARNING: Package download failed in 0.02 seconds
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:177 char:33
    azure-arm.image: WARNING: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
==> azure-arm.image: +         $Path = Join-Path -Path "${env:TEMP_DIR}" -ChildPath $fileNam ...
    azure-arm.image: WARNING: Waiting 30 seconds before retrying (retries left: 20)...
==> azure-arm.image: +                                 ~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
==> azure-arm.image:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
==> azure-arm.image:    PathCommand
==> azure-arm.image:`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

This issue is happening when trying to build the image on  a vanilla windows vm with the prereqs.

### Is it regression?

no

### Expected behavior

The script should download chocolatey so that the process can continue

### Actual behavior

The build fails with the above error

### Repro steps

Run the GenerateResourcesAndImage with the below params

`GenerateResourcesAndImage -SubscriptionId $(CreateSubscriptionId) `
-ImageGenerationRepositoryRoot "$(Build.SourcesDirectory)/runner-images" `
-ResourceGroupName "$(createResourceGroup)" `
-AzureLocation "$(azureLocation)" `
-ImageType "$(imageType)" `
-AzureClientId "$(CreateAzureClientId)" `
-AzureClientSecret "$(CreateAzureClientSecret)" `
-AzureTenantId "$(AzureTenantId)" `
-ManagedImageName "Runner-Image-$imageType-$(Get-Date -Format 'ddMMyyyy')" `
-force `
-tags @{ 'ImageType' = $imageType; 'BuildNumber' = "$(Build.BuildNumber)" } #`
-RestrictToAgentIpAddress
-OnError "cleanup"
`

**Comment by hemanthmanga** [comment]
Hi @ChrisGibson1982, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by ChrisGibson1982** [comment]
The code that the error is relating to is in the file: 'images\windows\scripts\helpers\InstallHelpers.ps1'.  Its part of hte Invoke-DownloadWithRetry function.

**Comment by ChrisGibson1982** [comment]
This can be closed. I had modified the 2022 hcl file and this was causing the issue. I'm guessing this, as when I stopped messing with it (adding extra scripts to run), it worked.

**Comment by ChrisGibson1982** [comment]
Thanks for looking at this
