### ISSUE TITLE
Int

### ISSUE THREAD

**Issue by Intrust111** [actions/runner-images#11124]
### Breaking changes

https://github.com/actions/runner-images/blob/c2c0261ea4bb291fdd9669eb1660504b27748b17/SECURITY.md

### Target date

https://github.com/actions/runner-images/blob/c2c0261ea4bb291fdd9669eb1660504b27748b17/SECURITY.md

### The motivation for the changes

Int

### Possible impact

Int

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

https://github.com/actions/runner-images/blob/c2c0261ea4bb291fdd9669eb1660504b27748b17/SECURITY.md

**Comment by lakshminarayana02** [comment]
Hi
please provide more information about this request.
