### ISSUE TITLE
[Windows Server 2022] Bindgen failing test cases

### ISSUE THREAD

**Issue by Reterino** [actions/runner-images#11130]
### Description

This is part of the build process for Windows Server 2022 image, using the provided Packer template.

The test for Bindgen fails (within Rust.Tests.ps1). Bindgen is installed without issue but the command `bindgen.exe` returns an exit code of 2 as it expects specific arguments to be passed:

[-] bindgen.exe is installed to the 'C:\Users\Default\.cargo\bin\bindgen.exe' folder 204ms (201ms|3ms)
    azure-arm.image:    Command 'bindgen.exe --version' has finished with exit code 2 and output:
    azure-arm.image:        error: the following required arguments were not provided:
    azure-arm.image:          <HEADER>
    azure-arm.image:
    azure-arm.image:        Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...
    azure-arm.image:
    azure-arm.image:        For more information, try '--help'.
    azure-arm.image:    at "$ToolName --version" | Should -ReturnZeroExitCode, C:\image\tests\Rust.Tests.ps1:40
    azure-arm.image:    at <ScriptBlock>, C:\image\tests\Rust.Tests.ps1:40

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Windows Server 2022

### Is it regression?

No issues earlier last week

### Expected behavior

The test should check for bindgen.exe being installed and pass successfully

### Actual behavior

The test checks for bindgen.exe by calling it and fails due to it expecting additional parameters.

### Repro steps

1. Build Windows Server 2022 image
2. Wait until Rust set-up section
3. Rust and components install without issue
4. Rust tests fail due to Bindgen.exe

**Comment by kishorekumar-anchala** [comment]
Hi @Reterino ,

Thanks for reporting to us , we will look into your issue and updtate ASAP.

**Comment by BlakeWills** [comment]
This is also failing for the Ubuntu 20.04 and Ubuntu 22.04 images:

```
    azure-arm.build_image: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_image: Describing Rust
    azure-arm.build_image:   [+] Rustup is installed 157ms (120ms|37ms)
    azure-arm.build_image:   [+] Rustc is installed 60ms (58ms|2ms)
    azure-arm.build_image:   [+] Rustdoc is installed 60ms (58ms|2ms)
    azure-arm.build_image:   [+] Rustfmt is installed 55ms (54ms|2ms)
    azure-arm.build_image:   [+] cargo 52ms (50ms|3ms)
    azure-arm.build_image:  Context Cargo dependencies
    azure-arm.build_image:    [-] bindgen 41ms (33ms|8ms)
    azure-arm.build_image:     Command 'bindgen --version' has finished with exit code
    azure-arm.build_image:         error: the following required arguments were not provided:   <HEADER>  Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...  For more information, try '--help'.
    azure-arm.build_image:     at "bindgen --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Tools.Tests.ps1:47
    azure-arm.build_image:     at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:47
    azure-arm.build_image:    [+] cbindgen 15ms (13ms|2ms)
    azure-arm.build_image:    [+] cargo-clippy 56ms (55ms|2ms)
    azure-arm.build_image:    [+] Cargo audit 57ms (55ms|2ms)
    azure-arm.build_image:    [+] Cargo outdated 62ms (60ms|2ms)
    azure-arm.build_image: Tests completed in 1.99s
    azure-arm.build_image: Tests Passed: 9, Failed: 1, Skipped: 0, Inconclusive: 0, NotRun: 85

```

**Comment by mmcdermo2** [comment]
We see this failure on **both** Windows 2019 and Windows 2022

**Comment by kishorekumar-anchala** [comment]
HI @mmcdermo2 @BlakeWills ,

 Due to new version of bindgen , they got failed . i request you try to pin the old version and try as temporary workaround . ( If possible ) .
 
` cargo install bindgen-cli --version 0.70.1`

for  both windows and ubuntu .

**Comment by mmcdermo2** [comment]
@kishorekumar-anchala thanks for the response, I can give it a try.  I'm not very familiar with cargo however, below is the current command in the repo (for installing on Windows)
`cargo install bindgen-cli cbindgen cargo-audit cargo-outdated`
should this become:
`cargo install bindgen-cli cbindgen cargo-audit cargo-outdated --version 0.70.1`
or should it become:
```
cargo install bindgen-cli --version 0.70.1
cargo install cbindgen cargo-audit cargo-outdated
```
Thanks in advance !

**Comment by kishorekumar-anchala** [comment]
it should be like below . as it impacting only for bindgen-cli .

```
cargo install bindgen-cli --version 0.70.1
cargo install cbindgen cargo-audit cargo-outdated
```

**Comment by Reterino** [comment]
> it should be like below . as it impacting only for bindgen-cli .
> 
> ```
> cargo install bindgen-cli --version 0.70.1
> cargo install cbindgen cargo-audit cargo-outdated
> ```

Modifying the Install-Rust.ps1 file to be like the above works fine and passes tests.

**Comment by kishorekumar-anchala** [comment]
Now issue got fixed , please try with your original code . 

thanks for your confirmation.

cc @BlakeWills @Reterino @mmcdermo2
