### ISSUE TITLE
Add mise package manager

### ISSUE THREAD

**Issue by nekrich** [actions/runner-images#11143]
### Tool name

mise

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

It's a tool version manager.
It's like the Homebrew but with a tool version control.

### URL for tool's homepage

https://mise.jdx.dev/

### Provide a basic test case to validate the tool's functionality.

```bash
1. Create a .mise.toml
    
    [tools]
    tuist = "4.34.3"
    ```
2. Run `mise install`
3. `tuist version` command must return `4.34.3`.
```


### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
1. curl https://mise.run | sh
2. Prepend `PATH` variable with shims location (~/.local/share/mise/shims on macOS).
```

### Tool installation time in runtime

5-20s locally

### Are you willing to submit a PR?

I'll consider it as an option if it will be approved.

**Comment by sureshe456** [comment]
Hi @nekrich We will look into the issue and keep you posted on updates. Thanks.

**Comment by sureshe456** [comment]
Hi @nekrich,  I would like to inform you that we are unable to add these tools in the macOS images due to the need to maintain lightweight   operating system images and limited space.

We request that you use the runtime for your build.

**Comment by nekrich** [comment]
Thanks.
