### ISSUE TITLE
Invalid Signature for Microsoft Edge Webdriver - Re-introduced

### ISSUE THREAD

**Issue by eohlde** [actions/runner-images#11186]
### Description

Bug #10840 seems to have been reintroduced. 
I'm trying to provision a window-2022 image from this repo to use as self-hosted build agents.
I'm currently getting failing builds from the main branch of this (https://github.com/actions/runner-images.git) repository.

Here is the error I'm seeing:
```
azure-arm.image: Provisioning with powershell script: /home/runner/work/rvp-build_agents/rvp-build_agents/runner-images/images/windows/templates/../scripts/build/Install-EdgeDriver.ps1
    azure-arm.image: Get the Microsoft Edge WebDriver version...
    azure-arm.image:
    azure-arm.image:
    azure-arm.image:     Directory: C:\SeleniumWebDrivers
    azure-arm.image:
    azure-arm.image:
    azure-arm.image: Mode                 LastWriteTime         Length Name
    azure-arm.image: ----                 -------------         ------ ----
    azure-arm.image: d-----        12/14/2024  12:00 AM                EdgeDriver
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/LATEST_RELEASE_131_WINDOWS to C:\SeleniumWebDrivers\EdgeDriver\versioninfo.txt...
    azure-arm.image: Package downloaded in 0.05 seconds
    azure-arm.image: Download Microsoft Edge WebDriver...
    azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/131.0.2903.99/edgedriver_win64.zip to D:\temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.08 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'D:\temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:997 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.image: Step "StepProvision" failed
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
```

And here is the commit that I'm building off of:
```
Latest commit: Date: Fri Dec 13 20:19:19 2024 +0100; Commit: 7cd7c6a18af1ee77e597d6c3895d61f42a223e37 - Add Microsoft.Net.Component.4.7.2.SDK to Windows toolset 2022 (#11118); Author: Joost Voskuil <joost@foxhole.nl>.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I'm using this build agent in github to execute my build:
```
Current runner version: '2.321.0'
Operating System
Runner Image
  Image: ubuntu-24.04
  Version: 20241208.1.0
  ```

### Is it regression?

Possibly. Others are commenting in $10840 that they are seeing the issue again

### Expected behavior

The build for Windows 2022 should successfully complete and the image should provision

### Actual behavior

The build for windows-2022 is failing after ~ 3 hrs with the error listed above

### Repro steps

1. git clone https://github.com/actions/runner-images.git runner-images

2. Set-Location runner-images

3. Import-Module .\helpers\GenerateResourcesAndImage.ps1

4. GenerateResourcesAndimage -SubscriptionId ${{ vars.ARM_SUBSCRIPTION_ID }} `
                                      -ResourceGroupName ${{ vars.RUNNER_IMAGE_RG }} `
                                      -ManagedImageName ${{ vars.MANAGED_IMAGE_NAME }} `
                                      -AzureLocation "${{ vars.AZURE_REGION }}" `
                                      -ImageType "${{ vars.IMAGE }}" `
                                      -AzureClientId ${{ vars.ARM_CLIENT_ID }} `
                                      -AzureClientSecret ${{ secrets.ARM_CLIENT_SECRET }} `
                                      -AzureTenantId ${{ vars.ARM_TENANT_ID }} `
                                      -Tags @{"ExcludeMdeAutoProvisioning"="True"} `
                                      -RestrictToAgentIpAddress

**Comment by vidyasagarnimmagaddi** [comment]
Hi @eohlde , the signature  is fixed under https://github.com/actions/runner-images/pull/11192 . Kindly try to build  image. thanks

**Comment by eohlde** [comment]
Running a build with this now. Thank you for the quick turn around!

**Comment by vidyasagarnimmagaddi** [comment]
Hi @eohlde ,
Thanks for the update, closing this issue.
