### ISSUE TITLE
xfgbfvb

### ISSUE THREAD

**Issue by abishakla** [actions/runner-images#11190]
### Description

cvdcv

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

sdsc

### Is it regression?

dfvfdv

### Expected behavior

cvbcvb

### Actual behavior

defrgt

### Repro steps

fbfbvc

**Comment by vidyasagarnimmagaddi** [comment]
,
