### ISSUE TITLE
"Signature status is not valid. Status: Unknown" when dowloading Postgres

### ISSUE THREAD

**Issue by ChrisGibson1982** [actions/runner-images#11204]
### Description

When my image creation gets to the downloading Postgres, i get the below error.  I am use the current mian branch

`==> azure-arm.image: Provisioning with powershell script: C:/Agent7/_work/3/s/runner-images/images/windows/templates/../scripts/build/Install-PostgreSQL.ps1
    azure-arm.image: Downloading package from https://get.enterprisedb.com/postgresql/postgresql-14.12-1-windows-x64.exe to D:\temp\postgresql-14.12-1-windows-x64.exe...
    azure-arm.image: Package downloaded in 13.97 seconds
==> azure-arm.image: Signature status is not valid. Status: UnknownError
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:983 char:9
==> azure-arm.image: +         throw "Signature status is not valid. Status: $($signature.St ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature statu...s: UnknownError:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature status is not valid. Status: UnknownError
==> azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.image: Step "StepProvision" failed`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest code from main branch

### Is it regression?

no

### Expected behavior

to successfully download and install Postgres

### Actual behavior

Fails to install/download Postgres

### Repro steps

run the GenerateResourcesAndImage powershell function to build a new image

**Comment by vidyasagarnimmagaddi** [comment]
Hi @ChrisGibson1982 ,Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
hi @ChrisGibson1982 ,
We are able to build the image and facing no issue in installing postgresql , could you please try to build the image again and share the logs if error. Thanks

**Comment by ChrisGibson1982** [comment]
[buildAgentLog_Postgres.txt](https://github.com/user-attachments/files/18162767/buildAgentLog_Postgres.txt)
I've kicked off another build, but i ran two yesterday and got the same issue.  I have also managed to download the file on another windows VM on the same subnet.  Attached is the Azure DevOps log which shows the issue.  Once the build finishes i will update this issue, its going to take 3-4 hours

**Comment by ChrisGibson1982** [comment]
Our network team have checked the inbound/outbound traffic for the temp packer vm and they can't see any connections that where blocked, apart from http to a hashicorp url that then succeeed on 443

**Comment by vidyasagarnimmagaddi** [comment]
Hi all, Please be informed.
The directory for temporary files has been moved to drive D: due to the new cleanup process.
The VM size ([Standard_D8s_v4](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dv4-series?tabs=sizestoragelocal)) does not have a local (temporary) disk. However [Fsv2 sizes series](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/compute-optimized/fsv2-series?tabs=sizestoragelocal#host-specifications) do have such drive.

To workaround this issue, you can either update VM size variable "vm_size" or update the variable for temporary files variable "temp_dir". Thanks

**Comment by ChrisGibson1982** [comment]
Hi, the temporary vm is s Standard F8s V2, which does have a temp drive.  I also ran ps command via the portal and i can see the D drive. so should this be ok?

**Comment by vidyasagarnimmagaddi** [comment]
> Hi, the temporary vm is s Standard F8s V2, which does have a temp drive. I also ran ps command via the portal and i can see the D drive. so should this be ok?

Yes , please try it, and revert the status of it , thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @ChrisGibson1982 , Any update on this . Could you please provide .. thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @ChrisGibson1982 ,  We are not facing any issues in our builds, .Hoper your issue resolves. Closing this issue. thanks
