### ISSUE TITLE
Subversion missing in ubuntu-latest (24.04)

### ISSUE THREAD

**Issue by p3lim** [actions/runner-images#11219]
### Description

Subversion was provided in earlier versions of the ubuntu image, but is missing from 24.04.

Please provide it again, or perhaps `git-svn` as an alternative with a warning to users, as this is a breaking (and unannounced) change.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest / ubuntu-24.04

### Is it regression?

ubuntu-22.04

### Expected behavior

`svn` command to exist

### Actual behavior

`svn: command not found`

### Repro steps

1. Use `svn` in a workflow or in an action
2. Switch from ubuntu-22.04 image to ubuntu-24.04 image
3. Receive errors

**Comment by vidyasagarnimmagaddi** [comment]
Hi @p3lim , SVN has been Removed from the Ubuntu 24.04 image due to maintenance reasons.
The same. has been mentioned in [reference#1](https://github.com/actions/runner-images/issues/10636). and 
[reference#2](https://github.com/actions/runner-images/issues/9848).

Further the same can be installed. thanks

**Comment by p3lim** [comment]
That's alright. Just curious, what was the maintenance reason? Considering it's a single package in the Ubuntu repos.

**Comment by nextgenthemes** [comment]
Haha, "Maintenance reason" is total bullshit, it's maintained by Canonical/the author(s) that still maintains the package in the Ubuntu sources. It's still in the Ubuntu universe sources as it always was, for all the latest Ubuntu releases, it's just a matter of installing it. GitHub does not have to "maintain" shit. It's 5mb of space they have unlimited of.

Of course, GitHub is heavily biased against every other version management that is not called git.

Download-Size: 920 kB
Installed-Size: 4.998 kB

(on Plucky)
