### ISSUE TITLE
Windows agent image build failure

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#11236]
### Description

**Error for window agent image build failure**
   azure-arm.image: Downloading package from https://msedgedriver.azureedge.net/131.0.2903.112/edgedriver_win64.zip to D:\temp\edgedriver_win64.zip...
    azure-arm.image: Package downloaded in 0.08 seconds
    azure-arm.image: Expand Microsoft Edge WebDriver archive...
    azure-arm.image: Expand archive 'D:\temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:997 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Image 20241215.1.0

### Is it regression?

N/A

### Expected behavior

Image build completes successfully

### Actual behavior

error pasted in description.

### Repro steps

NA

**Comment by hemanthmanga** [comment]
Hi @jaswant-dnv , Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @jaswant-dnv,  EdgeDriver signature has been updated, Could you please retry by forking latest code from main branch.
Closing this issue,Thank you.
