### ISSUE TITLE
Update MSVC version to 14.43 or later

### ISSUE THREAD

**Issue by KeithRare** [actions/runner-images#11239]
### Tool name

MSVC

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

At least 14.43

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022
- [X] Windows Server 2025

**Comment by RaviAkshintala** [comment]
Hi @KeithRare Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by MehdiChinoune** [comment]
@KeithRare MSVC 14.43 is part of VS 2022 17.13 which still not released yet. GitHub Actions doesn't provide VS preview, you should until 17.13 is released.

**Comment by subir0071** [comment]
Closing this issue as of now.
