### ISSUE TITLE
link.exe fails with no error message

### ISSUE THREAD

**Issue by rayzchen** [actions/runner-images#5566]
### Description

Happens randomly for only some versions of Python, all on `windows-latest`.

https://github.com/pyunity/pyunity/runs/6478387670?check_suite_focus=true
https://github.com/pyunity/pyunity/runs/6478387830?check_suite_focus=true
https://github.com/pyunity/pyunity/runs/6478270707?check_suite_focus=true

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
  Version: 20220511.2
  Included Software: https://github.com/actions/virtual-environments/blob/win22/20220511.2/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220511.2

### Expected behavior

No error

### Actual behavior

https://github.com/pyunity/pyunity/runs/6478333635?check_suite_focus=true

### Repro steps

Clone https://github.com/pyunity/pyunity
Run `python setup.py build_ext`

**Comment by mikhailkoliada** [comment]
Hi @rayzchen!

We will take a look.

**Comment by rayzchen** [comment]
https://github.com/pyunity/pyunity/runs/6478489421?check_suite_focus=true Same commit as the failing build, yet it still worked perfectly.

**Comment by rayzchen** [comment]
> Hi @rayzchen!
> 
> We will take a look.

@mikhailkoliada Has there been any progress?

**Comment by rayzchen** [comment]
Another failing build: https://github.com/pyunity/pyunity/runs/6535898575?check_suite_focus=true
And its successful rerun: https://github.com/pyunity/pyunity/runs/6535927114?check_suite_focus=true

**Comment by rayzchen** [comment]
Any progress?

**Comment by miketimofeev** [comment]
@rayzchen I'm afraid we didn't have a chance to take a look yet

**Comment by vsafonkin** [comment]
Hi @rayzchen, is this issue still actual for you?

**Comment by rayzchen** [comment]
Is there any reason why this happens?

**Comment by vsafonkin** [comment]
Sorry @rayzchen, I can't find any reasons from our side.

**Comment by rayzchen** [comment]
After disabling parallel compilation, the error seems to have disappeared, however parallel compilation works on Linux Github Actions, MacOS Github Actions, my Windows home computer and a Windows VPS that I tested on. This is enabled with `python setup.py build_ext -j <cpu>`. Would there be any reason why parallel compilation would crash?

**Comment by mikhailkoliada** [comment]
@rayzchen hey! Is it still a problem?

**Comment by rayzchen** [comment]
I've taken a rest of 6 months from programming, but I think I may be coming back to my project soon. Funnily enough, the Windows builds of 6 months ago seemed to be successful, but I'll let you know how it goes once I return to programming.

Here's a list of the most recent builds:
https://github.com/pyunity/pyunity/actions/workflows/windows.yml

**Comment by rayzchen** [comment]
Oops, my bad. The logs have expired since 6 months ago and my previous comment also stated that I had disabled parallel compilation, which seemed to have been the cause.

**Comment by mikhailkoliada** [comment]
@rayzchen Just going to close the ticket for now then to indicate nothing happens here for long (as the problem seems to be rather specific), feel free to reopen  if you hit something similar in the future :)
