### ISSUE TITLE
Have a problem on Azure pipelines with Xcode 13.4 on macOS 12

### ISSUE THREAD

**Issue by kvyatkovskys** [actions/runner-images#5584]
### Description

Pipeline freezes when resolving swift packages

![Screen Shot 2022-05-20 at 5 03 24 PM](https://user-images.githubusercontent.com/8233076/169545317-8ec88568-4c06-496a-b464-59f9100e7b94.png)
![Screen Shot 2022-05-20 at 5 09 51 PM](https://user-images.githubusercontent.com/8233076/169546008-df3fd30e-5715-4bad-a21d-2f7a680370f4.png)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: macOS 12
Version: 20220520.1

### Is it regression?

no

### Expected behavior

Pipeline should works correctly 

### Actual behavior

Pipeline freezes.
Xcode 13.4 works fine on my MacBook. 

### Repro steps

- select a iOS project with swift packages
- run pipeline
- select macOS 12
- select Xcode 13.4

**Comment by miketimofeev** [comment]
Hi @kvyatkovskys!
Could you prepare a workflow that can be used to reproduce the issue?

**Comment by miketimofeev** [comment]
@kvyatkovskys yes as we need to reproduce the issue to debug it further.

**Comment by kvyatkovskys** [comment]
env:
- macOS 12
- iOS project with swift packages
- fastlane (2.206.0) gym (to build project)

pipeline with settings below
<img width="600" alt="Screen Shot 2022-05-20 at 9 40 46 PM" src="https://user-images.githubusercontent.com/8233076/169592148-d8f1bacd-e516-4067-b2c1-fe6b30ff5001.png">

task *Prepare environment*:
- sudo xcode-select -switch /Applications/Xcode_13.4.app
- xcode-select --print-path
- gem install bundler:1.16.1
- bundle update --all

task *Fastlane run dev*:
- bundle exec fastlane build

steps:
- run pipeline
- select branch
- run

**Comment by kvyatkovskys** [comment]
any updates? 🙂

**Comment by kvyatkovskys** [comment]
@miketimofeev any updates?🙂

**Comment by miketimofeev** [comment]
@panticmilos did you have a chance to take a look?

**Comment by kvyatkovskys** [comment]
> Hi @kvyatkovskys,
> 
> 
> 
> Thank you for your patience, just to let you know I started investigating this issue in-depth today, so I will get back to you with some useful info as soon as possible.
> 
> 
> 
> Cheers

Thanks 🙂

**Comment by panticmilos** [comment]
hi @kvyatkovskys,

Just to check, is using this version, Xcode 13.2.1, a workaround you can use until we resolve this issue?

**Comment by kvyatkovskys** [comment]
Yes we can and we use Xcode 13.2.1. And we also plan to update  Xcode

**Comment by kvyatkovskys** [comment]
Hi @panticmilos, any updates?

**Comment by kvyatkovskys** [comment]
still have problems

<img width="915" alt="Screen Shot 2022-06-28 at 10 24 01 PM" src="https://user-images.githubusercontent.com/8233076/176269301-292c4036-c79e-4353-b87d-294725d8c055.png">
<img width="1077" alt="Screen Shot 2022-06-28 at 10 31 11 PM" src="https://user-images.githubusercontent.com/8233076/176269318-f9ec9196-fe80-45c5-9bdf-f007ba0c9246.png">

**Comment by panticmilos** [comment]
Hi @kvyatkovskys,

Is there any way you can provide me with a mock of the repository?

**Comment by kvyatkovskys** [comment]
> @kvyatkovskys nice! Hope this will work for the others too.
> 
> @pavshr, is removing the Twilio package applicable to your case as well?

Yeah 😀 but we use the Twilio package in our project. Still investigating the issue

**Comment by michaelmoneypenny** [comment]
> > @kvyatkovskys nice! Hope this will work for the others too.
> > @pavshr, is removing the Twilio package applicable to your case as well?
> 
> Yeah 😀 but we use the Twilio package in our project. Still investigating the issue

I had an issue with twilio and bitcode, apparently disabling bitcode fixes the issue (bitcode is apparently deprecated)

**Comment by pavshr** [comment]
@panticmilos No, we are not using Twilio, and bitcode is also disabled for our app.

**Comment by kvyatkovskys** [comment]
I fixed the issue🙂. I added the twilio package as a binary xcframework to the project.

`package.swift` example

```
let package = Package(
    name: "VideoVisit",
    platforms: [.iOS(.v14), .macOS(.v10_15)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "VideoVisit",
            targets: ["VideoVisit", "TwilioVideo"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/SnapKit/SnapKit", .upToNextMajor(from: "5.0.0")),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .binaryTarget(
            name: "TwilioVideo",
            path: "TwilioVideo.xcframework"
        ),
        .target(
            name: "VideoVisit",
            dependencies: [
                "SnapKit",
                .target(name: "TwilioVideo"),
            ],
            path: "Sources",
            exclude: ["../VV-Example"],
            resources: [
                .process("../Sources/Media.xcassets")
            ]),
        .testTarget(
            name: "VideoVisitTests",
            dependencies: ["VideoVisit"]),
    ]
)
```

**Comment by kvyatkovskys** [comment]
I think, problem was due to a large file download. The twilio package is 60 mb in size. 

cc @miketimofeev @panticmilos 

```
import PackageDescription

let package = Package(
    name: "TwilioVideo",
    platforms: [
        .iOS("12.2")
    ],
    products: [
        .library(
            name: "TwilioVideo",
            targets: ["TwilioVideo"]),
    ],
    targets: [
        .binaryTarget(
            name: "TwilioVideo",
            url: "https://github.com/twilio/twilio-video-ios/releases/download/5.1.1/TwilioVideo.xcframework.zip",
            checksum: "125e944221600cbe98436d1cbc7bd8817c2795e6a9f36e3a63c01f0016f67d78"
        )
    ]
)
```

**Comment by jmprice18** [comment]
We've hit this issue on our side and we can reproduce it easily on MacOS 12 and Xcode 13.4+.  We believe that Xcode is trying to access the keychain interactively while cloning at least 10 repositories from Github with a PAT.  But if you only use public repositories, you won't run into this.  We've tried using the PAT in git credential helper or via URL re-write and both produce the same error depending on the number of repositories xcodebuild is trying to resolve. The issue does not happen on XCode 13.2.1, even on the MacOS 12 agent.

Reproduce:
1. Use MacOS 12 and Xcode 13.4+.  

2. Add a URL rewrite to gitconfig:
`git config --global url.https://username:pat@github.com.insteadOf https://github.com`

3. Run the pipeline and this will hang when cloning one of the repositories during xcodebuild.

Locally, we've tried to reproduce this error, and we can occasionally get a keychain prompt from XCode.  See screenshot below on local dev machine.

![E0A74EAB-8523-4AEA-BEFF-0886CB493D5E](https://user-images.githubusercontent.com/6707368/187681507-6f69ca4e-7487-4845-8382-f281aa728cee.png)

@miketimofeev, any thoughts on how to resolve this?

**Comment by miketimofeev** [comment]
@jmprice18 we will take a look at what can be done from our side but at first glance, it looks like Xcode security limitations.

**Comment by panticmilos** [comment]
Hi @jmprice18, we were discussing how we could potentially overcome this issue, and for self-hosted runner, we could maybe run `git config credential.helper cache` after auth to avoid keychain prompts. In this case, we could avoid it. Of course, there is still a question to be resolved how we can avoid it for hosted runners.

**Comment by panticmilos** [comment]
Hi everyone. Since this looks like the security limitation of the Xcode and given the recent inactivity on the issue I am going to close it for now. 

Feel free to continue the conversation here or reopen the issue.
Cheers
