### ISSUE TITLE
[Windows] [Windows Server 2022] [WDK] error MSB8020: The build tools for WindowsKernelModeDriver10.0 cannot be found.

### ISSUE THREAD

**Issue by MiroKaku** [actions/runner-images#5897]
### Description

Date:   Wed Jul 13 10:49:09 2022 +0800

https://github.com/MiroKaku/ucxxrt/runs/7313600205?check_suite_focus=true#step:4:27

> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(440,5): error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\ucxxrt\ucxxrt\msvc\ucxxrt.vcxproj]

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2022

```yaml
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022
```

### Is it regression?

No

### Expected behavior

build success.

### Actual behavior

error MSB8020: The build tools for WindowsKernelModeDriver10.0 cannot be found.

### Repro steps

https://github.com/MiroKaku/ucxxrt/blob/master/.github/workflows/build.bat
```bat
@echo off
setlocal enabledelayedexpansion

pushd "%~dp0"

set msbuild="%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"

for /f "usebackq tokens=*" %%i in (`vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe`) do (
  set msbuild="%%i"
)

if exist bin rd /s /q bin
if exist lib rd /s /q lib
if exist ucxxrt rd /s /q ucxxrt

%msbuild% -p:Configuration=Debug   -p:Platform=x86 ..\..\ucxxrt.sln -t:ucxxrt
%msbuild% -p:Configuration=Release -p:Platform=x86 ..\..\ucxxrt.sln -t:ucxxrt

%msbuild% -p:Configuration=Debug   -p:Platform=x64 ..\..\ucxxrt.sln -t:ucxxrt
%msbuild% -p:Configuration=Release -p:Platform=x64 ..\..\ucxxrt.sln -t:ucxxrt

%msbuild% -p:Configuration=Debug   -p:Platform=ARM ..\..\ucxxrt.sln -t:ucxxrt
%msbuild% -p:Configuration=Release -p:Platform=ARM ..\..\ucxxrt.sln -t:ucxxrt

%msbuild% -p:Configuration=Debug   -p:Platform=ARM64 ..\..\ucxxrt.sln -t:ucxxrt
%msbuild% -p:Configuration=Release -p:Platform=ARM64 ..\..\ucxxrt.sln -t:ucxxrt

:exit
popd
@echo on
```

**Comment by MiroKaku** [comment]
thanks, it worked

**Comment by ms-gavinkinsey** [comment]
The posted workaround works but adds a significant amount of time to our builds.

I believe the underlying issue may now be resolved in a newer version of the WDK.

From https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
"""
If you installed the original Windows 11, version 22H2 WDK between May and August 2022 (version 10.0.22621.1), you may see the following error message when you start Visual Studio with the WDK.

The service ‘Microsoft.VisualStudio.Shell.Interop.SVsUIShell’ must be installed for this feature to work. Ensure that this service is available.
You can either safely dismiss this message, or you can uninstall the WDK and then reinstall the WDK (updated August 19, 2022 to version 10.0.22621.382) using the WDK download link below.
"""

Could you try preinstalling the VSIX extension with WDK 10.0.22621.382 so this workaround is no longer required please?

**Comment by al-cheb** [comment]
@ms-gavinkinsey, I will check it.

**Comment by al-cheb** [comment]
The new image with WDK.vsix has been deployed.
