### ISSUE TITLE
[Floating Issue] dotnet build runs too long

### ISSUE THREAD

**Issue by flopik3-5** [actions/runner-images#5916]
### Description

dotnet build operation runs too long (floating problem), agent fails with one of the next errors:

`We stopped hearing from agent Azure Pipelines 2. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610`

`Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\VssAdministrator\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.`

`Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 3221225725`

The same code can be build in range 8-30 minutes. The issue occurs since middle of June. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220710.1

### Is it regression?

20220607.3

### Expected behavior

dotnet build runs stable

### Actual behavior

dotnet build runs non stable

### Repro steps

dotnet build -c Release

main .csproj file
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>...</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <!-- This group contains project properties for RazorLight on .NET Core -->
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  ...

</Project>
```

**Comment by igorboskovic3** [comment]
Hi @flopik3-5, thank you for reporting this one. We will take a look.

**Comment by TiffD72** [comment]
> ### Description
> dotnet build operation runs too long (floating problem), agent fails with one of the next errors:
> 
> `We stopped hearing from agent Azure Pipelines 2. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610`
> 
> `Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\VssAdministrator\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.`
> 
> `Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 3221225725`
> 
> The same code can be build in range 8-30 minutes. The issue occurs since middle of June.
> 
> ### Platforms affected
> * [x]  Azure DevOps
> * [ ]  GitHub Actions
> 
> ### Virtual environments affected
> * [ ]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [ ]  Ubuntu 22.04
> * [ ]  macOS 10.15
> * [ ]  macOS 11
> * [ ]  macOS 12
> * [ ]  Windows Server 2019
> * [x]  Windows Server 2022
> 
> ### Image version and build link
> 20220710.1
> 
> ### Is it regression?
> 20220607.3
> 
> ### Expected behavior
> dotnet build runs stable
> 
> ### Actual behavior
> dotnet build runs non stable
> 
> ### Repro steps
> dotnet build -c Release
> 
> main .csproj file
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <RootNamespace>...</RootNamespace>
>   </PropertyGroup>
> 
>   <PropertyGroup>
>     
>     <PreserveCompilationReferences>true</PreserveCompilationReferences>
>     <PreserveCompilationContext>true</PreserveCompilationContext>
>   </PropertyGroup>
> 
>   ...
> 
> </Project>
> ```<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>...</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  ...

</Project>

**Comment by TiffD72** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>...</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  ...

</Project>
```<Project Sdk="Microsoft.NET.Sdk.Web">

**Comment by TiffD72** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>...</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  ...

</Project>

**Comment by dmitry-shibanov** [comment]
Hello @flopik3-5. Thank you for your report. Could you please provide a public repository to reproduce the issue.

**Comment by dmitry-shibanov** [comment]
Hello @flopik3-5, just a gentle ping

**Comment by flopik3-5** [comment]
Hello @dmitry-shibanov, unfortunately no.

**Comment by vsafonkin** [comment]
@flopik3-5, we cannot do something without repro. I'm going to close this issue, feel free to reopen it if you can provide it.
