### ISSUE TITLE
Update cmake of Android SDK to 3.22.1

### ISSUE THREAD

**Issue by yujincheng08** [actions/runner-images#5952]
### Tool name

cmake

### Tool license

OSI-approved BSD 3-clause

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.22.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by ddobranic** [comment]
@yujincheng08 thank you for submitting this issue. we will update cmake of Android SDK to 3.22.1 next week with update of Android NDK.

**Comment by al-cheb** [comment]
All images have been updated.
