### ISSUE TITLE
iOS build in Azure pipeline is failing at archive task after changing the macOS agent to macoOS-12

### ISSUE THREAD

**Issue by Rajeswari06** [actions/runner-images#5966]
### Description

iOS build in Azure pipeline is failing at archive task after changing the macOS agent to macoOS-12 and Xcode version to /Applications/Xcode_13.4.1.app with below steps

SetMode u+w,go-w,a+rX /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app (in target 'iOSBuild' from project 'iOSBuild')
   cd /Users/runner/work/1/s/iOSBuild
  /bin/chmod -RH u+w,go-w,a+rX /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app
CodeSign /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app (in target 'iOSBuild' from project 'iOSBuild')
 cd /Users/runner/work/1/s/iOSBuild
 export CODESIGN_ALLOCATE\=/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
     
     Signing Identity:     "iPhone Distribution:"
  Provisioning Profile: “202022_app3_iOSBuild"
                       
     
    /usr/bin/codesign --force --sign 7123453540F2A16334D761F20F176665AB3D89DD --entitlements /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/IntermediateBuildFilesPath/iOSBuild.build/Fit-iphoneos/iOSBuild.build/iOSBuild.app.xcent --generate-entitlement-der /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app

 RegisterExecutionPolicyException /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app (in target 'iOSBuild' from project 'iOSBuild')
   cd /Users/runner/work/1/s/iOSBuild
    builtin-RegisterExecutionPolicyException /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app

 Validate /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app (in target 'iOSBuild' from project 'iOSBuild')
  cd /Users/runner/work/1/s/iOSBuild
    builtin-validationUtility /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app

Touch /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app (in target 'iOSBuild' from project 'iOSBuild')
   cd /Users/runner/work/1/s/iOSBuild
  /usr/bin/touch -c /Users/runner/Library/Developer/Xcode/DerivedData/iOSBuild-ehqfaveavmyhzlfqcwjddekgmauk/Build/Intermediates.noindex/ArchiveIntermediates/iOSBuild/InstallationBuildProductsLocation/Applications/iOSBuild.app

 ** ARCHIVE FAILED **

 ##[error]Error: The process '/usr/bin/xcodebuild' failed with exit code 65

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-12

### Is it regression?

no

### Expected behavior

Archive should be succesful

### Actual behavior

Archive failed

### Repro steps

use maOS-12
use Xcode-13.4.1

**Comment by al-cheb** [comment]
Hey @Rajeswari06.
Please include ta repo with minimum steps needed to reproduce the issue.

**Comment by Rajeswari06** [comment]
Hi @al-cheb ,

Please use below steps to reproduce the issue,

An iOS project with objective-c code
Enable Push notifications
Use entitlements file
Run the build in pipeline

Below is the yml configuration used  for Azure devops pipeline build. Pipeline is failing at step 'Xcode archive' with above mentioned error. 

- job: Build
  condition: and(succeededOrFailed(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.Reason'], 'Manual')))
  pool:
    vmImage: 'macOS-12'

- task: Xcode@5
    displayName: 'Xcode archive'
    inputs:
      actions: archive

      configuration: '$(Configuration)'

      xcWorkspacePath: '$(xcWorkspacePath)'

      scheme: '$(scheme)'

      xcodeDeveloperDir: '$(xcodePath)'

      xcodeVersion: '$(xcode)'

      packageApp: true

      useXcpretty: false

      archivePath: appPad

      exportPath: '$(Configuration)-appPad'

      signingOption: default

      workingDirectory: appPad

      args: '-UseModernBuildSystem=NO -verbose '

**Comment by dsame** [comment]
@Rajeswari06 
The problem is not reproducible 

https://dev.azure.com/v-sdolin-demo/virtual-environments-issues-5966/_build/results?buildId=1&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=133f3517-8e0b-58ce-ce4b-35396d6eb7ef

I created the public repo 
https://dev.azure.com/v-sdolin-demo/virtual-environments-issues-5966

Please feel free to fork the git repo 
https://dev.azure.com/v-sdolin-demo/_git/virtual-environments-issues-5966

and modifiy it and the corresponding build pipeline in order to make the problem to appear.  

Also i can add you to the project, so you can modify the source code and the pipeline i've already created. Please give me your AzDev account name if you prefer this approach.

**Comment by al-cheb** [comment]
@Rajeswari06,  I am planning to close the thread , if you have any concerns feel free to open it.
