### ISSUE TITLE
'virtual-environments' repository name will be changed to 'runner-images' on August, 8th

### ISSUE THREAD

**Issue by ddobranic** [actions/runner-images#5967]
### Breaking changes

Current name of 'virtual-environments' repository will be changed to 'runner-images'

### Target date

The repository will be re-named starting on August 8th but will take 2 weeks for changes to fully propagate out

### The motivation for the changes

The term "virtual-environments" no longer accurately represents what GitHub is trying to achieve with this repository

### Possible impact

There should be no impact. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:
`$ git remote set-url origin new_url`

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

N/A

**Comment by SHADYKIMBUM** [comment]
Hi
