### ISSUE TITLE
Update Docker Compose v2 to v2.9.0

### ISSUE THREAD

**Issue by elb3k** [actions/runner-images#5980]
### Tool name

Docker Compose v2

### Tool license

Apache 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.9.0

### Brief description of tool

Docker Compose is a tool for running multi-container applications on Docker defined using the [Compose file format](https://compose-spec.io/). A Compose file is used to define how the one or more containers that make up your application are configured.

### URL for tool's homepage

https://github.com/docker/compose

### Provide a basic test case to validate the tool's functionality.

```bash
Docker Compose v2.9.0 adds support for build time environment-based secrets.

Building docker with build time environment-based secrets. Example `docker-compose.yml`:
https://github.com/docker/compose/blob/v2/pkg/e2e/fixtures/build-test/secrets/compose.yml
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
@elb3k, there is no updated version of docker-compose v2 in https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/moby-compose/ repository

**Comment by elb3k** [comment]
> @elb3k, there is no updated version of docker-compose v2 in https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/moby-compose/ repository

Probably it will be pushed soon. You can see the release in compose github page: https://github.com/docker/compose/releases/tag/v2.7.0

**Comment by al-cheb** [comment]
> > @elb3k, there is no updated version of docker-compose v2 in https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/moby-compose/ repository
> 
> Probably it will be pushed soon. You can see the release in compose github page: https://github.com/docker/compose/releases/tag/v2.7.0

We use moby project to install docker and  moby-compose(docker-compose-linux-x86_64).

If you need the latest version of docker-compose you can install it in runtime:
```
 - run: |
          wget "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
          chmod +x docker-compose-linux-x86_64
          ./docker-compose-linux-x86_64 version
```

**Comment by elb3k** [comment]
@al-cheb Thanks! will try that.

**Comment by elb3k** [comment]
@al-cheb I tried installing newest `docker-compose`, and it is good for now. (kind of bandaid solution for the time being)
Do you know how often `moby-compose` gets updated to reflect `docker-compose v2` releases?

**Comment by al-cheb** [comment]
@cpuguy83, Could you please answer to a question?

**Comment by cpuguy83** [comment]
Apologies for the delay.
Some of our release automation broken due to some internal issues.
I've pushed compose v2.9.0.

**Comment by elb3k** [comment]
@al-cheb since compose v2.9.0 is pushed, can we reopen the ticket, I changed the version from 2.7.0 to 2.9.0.

**Comment by al-cheb** [comment]
@elb3k, The new Ubuntu Server 20.04 image with Docker Compose v2 2.9.0+azure-1 on board has been deployed.
