### ISSUE TITLE
Ubuntu 22.04 is generally available starting from August, 8

### ISSUE THREAD

**Issue by miketimofeev** [actions/runner-images#5998]
### Breaking changes

Ubuntu 22.04 is generally available starting from August, 8. Use it by putting `runs-on: ubuntu-22.04` in your workflow file.

### Target date

August, 8

### The motivation for the changes

Most of the software issues with the new image were resolved.

### Possible impact

n\a

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

n\a

**Comment by MarkusTeufelberger** [comment]
Will `ubuntu-latest` also point to `ubuntu-22.04` starting today?

**Comment by mikhailkoliada** [comment]
@MarkusTeufelberger No, migration to the latest tag is a separate process out of this specific announcement.

**Comment by tedmiston** [comment]
Was ubuntu-latest recently changed to point to 22.04?

My otherwise unchanged code that runs a SHA pinned Docker image has inexplicably started failing on the GHA Ubuntu runner beginning yesterday ~14 hours ago and the timing seems curious.

https://github.com/tedmiston/qcbrunch/actions/workflows/ci.yml?query=branch%3Amaster

I also noticed other users reporting Docker issues in https://github.com/actions/runner-images/issues/5490.

I have opened a GitHub support ticket here.

https://support.github.com/ticket/personal/0/1741196

**Comment by al-cheb** [comment]
@tedmiston , please read the https://github.com/actions/runner-images/issues/5998#issuecomment-1208105796

> My otherwise unchanged code that runs a SHA pinned Docker image building nightly has inexplicably started failing on the GHA Ubuntu runner beginning yesterday ~14 hours ago and the timing seems curious.
> 
> https://github.com/tedmiston/qcbrunch/actions/workflows/ci.yml?query=branch%3Amaster

As I can see the failed build was run on Ubuntu Server 20.04. How can it be related to Ubuntu Server 22.04?

![image](https://user-images.githubusercontent.com/47745270/184368249-3d69fee4-505b-411e-abe9-e75bbd60506f.png)

**Comment by al-cheb** [comment]
> @al-cheb Thank you for highlighting that. I did not realize this was exposed to the end user!
> 
> I will continue debugging other causes.

If you need any help please create a new issue with minimal repro steps.

**Comment by sivasamsivasam** [comment]
> @MarkusTeufelberger No, migration to the latest tag is a separate process out of this specific announcement.

Any ETA to change the default tag to 22.04?

**Comment by miketimofeev** [comment]
@sivasamsivasam we are going to announce it soon and migrate the tag till the end of this year.
