### ISSUE TITLE
The Ubuntu 18.04 Actions runner image will begin deprecation on 2022/08/08 and will be fully unsupported by 2023/04/03

### ISSUE THREAD

**Issue by miketimofeev** [actions/runner-images#6002]
### Breaking changes

We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/03

To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:

**GitHub Actions\Azure DevOps::**

- October 3, 12:00 UTC – October 3, 14:00 UTC
- October 18, 14:00 UTC – October 18, 16:00 UTC
- November 15, 18:00 UTC – November 15, 20:00 UTC
- November 30, 20:00 UTC – November 30, 22:00 UTC
- December 15, 20:00 UTC – December 16 00:00 UTC
- January 5, 10.00 UTC – January 5, 14.00 UTC
- January 13, 12.00 UTC – January 13, 16.00 UTC
- January 18, 14.00 UTC – January 18, 18.00 UTC
- January 24, 16.00 UTC – January 24, 20.00 UTC
- February 7, 16.00 UTC – February 7, 22.00 UTC
- February 21, 10.00 UTC – February 21, 22.00 UTC
- March 6, 00.00 UTC – March 7, 00.00 UTC
- March 13, 00.00 UTC – March 14, 00.00 UTC
- March 21, 00.00 UTC – March 22, 00.00 UTC
- March 28, 00.00 UTC – March 29, 00.00 UTC

### Target date

April 1st, 2023

### The motivation for the changes

We maintain the latest two stable versions of any given OS version. Ubuntu 22.04 is going GA on 8/8/22 thus we start deprecating the oldest image.

### Possible impact

Workflows using the `ubuntu-18.04` image label should be updated to `ubuntu-latest`, `ubuntu-20.04`, or `ubuntu-22.04`

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

N\A

**Comment by willaaam** [comment]
Don't get me wrong, I fully understand that you're deprecating 18.04 - but incorporating brownout periods to raise awareness?

If my team needs to get a build out for a critical bugfix on the 22nd of August... I'm just going to have to wait for 4 hours? If my understanding of that is true, I find that very odd behavior in an enterprise environment. Some businesses actually have SLA's with their clients. Would kindly request the team to find another way to "raise awareness".

You're giving us two weeks to migrate away before brownouts start. Migrating is an action that requires testing and validation.

**Comment by fbrosseau** [comment]
Does this impact hosted agents only, or does this also mean the agent tooling/infra (for self hosted pools, but also for 1ES pools for internal folks) will become EOL for ubuntu18? We still need to keep shipping ubuntu18 versions of our product for years.

**Comment by panekj** [comment]
@fbrosseau it's hosted agent only

**Comment by smistad** [comment]
I am sad to see this removal of ubuntu-18.04 and hope you will reconsider.
I use github to build C++ software on ubuntu-18.04, essentially making it possible to run it on 18.04 and newer releases.
Due to the lack of backward compatability when compiling with the C++ libraries on linux (GLIBC), binaries compiled on 20.04 will not work on 18.04.

**Comment by mikhailkoliada** [comment]
> I am sad to see this removal of ubuntu-18.04 and hope you will reconsider. I use github to build C++ software on ubuntu-18.04, essentially making it possible to run it on 18.04 and newer releases. Due to the lack of backward compatability when compiling with the C++ libraries on linux (GLIBC), binaries compiled on 20.04 will not work on 18.04.

@smistad as per the policy we only support the two latest LTS

**Comment by panekj** [comment]
> I use github to build C++ software on ubuntu-18.04, essentially making it possible to run it on 18.04 and newer releases.
> Due to the lack of backward compatability when compiling with the C++ libraries on linux (GLIBC), binaries compiled on 20.04 will not work on 18.04.

You can use `container:` option to build with `ubuntu:18.04` image or statically link binaries.

**Comment by smistad** [comment]
> > I use github to build C++ software on ubuntu-18.04, essentially making it possible to run it on 18.04 and newer releases.
> > Due to the lack of backward compatability when compiling with the C++ libraries on linux (GLIBC), binaries compiled on 20.04 will not work on 18.04.
> 
> You can use `container:` option to build with `ubuntu:18.04` image or statically link binaries.

Thanks for the tip @panekj

**Comment by ojwb** [comment]
> Deprecation will begin on 8/8/2022 and the image will be fully unsupported by 12/1/2022

Should be 12/1/2023 or is it a US format date?

**Comment by aaronfranke** [comment]
> @smistad as per the policy we only support the two latest LTS

@mikhailkoliada Is there any way we can convince GitHub to change this to the latest three LTS releases? We actually switched from 20.04 to 18.04 a few months ago because we found it worked better for our use cases.

**Comment by deathaxe** [comment]
What about projects which still need python 3.3 support for a reasonable time?

see: https://github.com/wbond/package_control/runs/7884696802?check_suite_focus=true

You must not simply break existing workflows!!!!

**Comment by scottshambaugh** [comment]
Ubuntu 18.04 does not reach the end of its standard support phase until [April 2023](https://wiki.ubuntu.com/Releases). If the policy here is to support the last two LTS releases, I would suggest it be amended to align dropping support when Ubuntu does.

**Comment by probonopd** [comment]
Ubuntu 18.04 does not reach the end of its standard support phase until [April 2023](https://wiki.ubuntu.com/Releases). The AppImage project is relying on it to be available on GitHub Actions for the whole timeframe doring which it is supported.

**Comment by danfairs** [comment]
So yeah, we've just found out that 18.04 is deprecated. Considering I just upgraded to Enterprise at the cost of the order of thousands of dollars a month, I'm not massively pleased to see you just breaking our whole company's jobs for four hours. 

Couldn't this be done in a different way? A banner on jobs that use the image? An email to org admins? It's pretty bad behaviour.

**Comment by panekj** [comment]
> A banner on jobs that use the image?

![image](https://user-images.githubusercontent.com/50457605/185933938-a414ff30-9134-4ff0-81da-1ec2154db8a3.png)

**Comment by danfairs** [comment]
> > A banner on jobs that use the image?
> 
> ![image](https://user-images.githubusercontent.com/50457605/185933938-a414ff30-9134-4ff0-81da-1ec2154db8a3.png)

What can I say? A whole company of 20 people didn't notice it.

**Comment by panekj** [comment]
There is also https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22

**Comment by danfairs** [comment]
> There is also https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22

I'm sure there is. But we *pay* for this. You (as in GH, not you personally) need to be proactive about reaching out to customers when you're planning to break something. The rest of Microsoft is pretty good at this.

**Comment by m0ar** [comment]
This brownout scheme is the worst way to "raise awareness for deprecation" and has put a dark tint over our otherwise happy relationship with GitHub. Who figured that this would be a good solution? We sure disagree.

**Comment by covidium** [comment]
Why not send some emails? It's easier than screwing peoples builds :)

**Comment by amacgregorhumi** [comment]
@miketimofeev Brownout is pretty extreme, you are getting in the way of people shipping and being able to work. And stopping for service we are paying for. 

This is huge loss of trust, and pushing us to consider alternatives.

**Comment by Steve-Glass** [comment]
👋  Thank you all for expressing your concerns with the deprecation schedule and  feedback on preferred availability. We will revise the deprecation schedule and are will immediately stop the brownouts.

**Comment by j4mb0ti** [comment]
We are working on a complex migration with a pretty tight deadline (tomorrow). We have noticed the deprecation and planned for it accordingly. Running into a random brownout is the worst thing any tool could do to us at the moment. 
Yes, we are aware of the deprecation. Yes, we have planned to make the necessary changes when we are able to. You are just adding insult to an injury - not raising awareness. Much disappointment. I thought microsoft would have learned from its passed mistakes - but apparently we are still in the Windows SE area. That's the kind of awareness you are raising. And now I am pretty sure I'll keep my other projects over at GitLab.

**Comment by mullermp** [comment]
This is impacting AWS SDK For Ruby CI - I agree with others that this is a poor way to raise awareness, as this is the first time I've heard of this campaign. We can make steps to migrate.

**Comment by rtek** [comment]
Please come up with a more reasonable way to handle deprecation of the runners. 

Consider how AWS handles lambda runtime deprecations as an example. They distribute emails when old runtimes are being used. You have access to all the workflows so you know whos using them.

**Comment by ijansch** [comment]
With a three week notice period, introducing these brownouts is like pulling the deprecation date forward. Because you can’t rely on a production system that breaks deployments every week for 6 hours. Not being able to perform an action during this time is Ill-advised and a serious risk for anyone relying on GitHub actions for production deployments. 

It’s like putting a house on fire to raise awareness that playing with matches is dangerous. 

See https://www.linkedin.com/posts/jansch_github-cicd-activity-6967561507354120192-084T?utm_source=share&utm_medium=member_ios for how this lead to a serious production incident at one of our customers when we needed to roll back a release because of a bug. 

At least make this a setting so we can only do this 
‘Forced awareness’ on test/acceptance builds. A feature like this on production is just killing reliability or GitHub actions for serious production work.

**Comment by mattlewis92** [comment]
We got hit by this brownout yesterday but nothing told us our jobs were getting cancelled because of the brownout, I found this issue purely by chance. If you're going to do something like this you really need to give an obvious error message and explain why jobs are being cancelled, just seeing the job being cancelled made me think there was an outage. Even our github account manager wasn't aware of this brownout that was happening.

![CleanShot 2022-08-22 at 16 05 23](https://user-images.githubusercontent.com/6425649/186146535-600f7725-7a78-458e-850f-5a81e2559a27.png)

**Comment by fcjz** [comment]
Also, last night, I also experienced this brownout , but there is no explanation, I feel a little baffling.

Too sloppy.

**Comment by martingalvan-nordic** [comment]
> Don't get me wrong, I fully understand that you're deprecating 18.04 - but incorporating brownout periods to raise awareness?
> 
> If my team needs to get a build out for a critical bugfix on the 22nd of August... I'm just going to have to wait for 4 hours? If my understanding of that is true, I find that very odd behavior in an enterprise environment. Some businesses actually have SLAs with their clients. Would kindly request the team to find another way to "raise awareness". I came here because of the red banner when using the image, that worked fine as well and is a lot less invasive.
> 
> You're giving us two weeks to migrate away before brownouts start. Migrating is an action that requires testing and validation.

We had the exact same problem when windows-2017 was deprecated, and it was extremely painful to have this transition forced unto us.

IMHO this one is particularly bad since there are legitimate reasons to build on older versions of Ubuntu; namely, so that the linker won't pull in symbols from newer versions of glibc which the customer's systems don't have.

**Comment by miketimofeev** [comment]
The deprecation date has shifted to March 1st, 2023 to give more time to adapt the workflows to Ubuntu20 or Ubuntu22.
The brownout schedule is also adjusted and now has shortened periods.

**Comment by dbussink** [comment]
> The deprecation date has shifted to March 1st, 2023 to give more time to adapt the workflows to Ubuntu20 or Ubuntu22.
> The brownout schedule is also adjusted and now has shortened periods.

@miketimofeev Is there also a plan to make it much more obvious in the UI that the brownout is happening? The lack of any information in the view linked from pull requests made the user experience significantly worse here.

**Comment by miketimofeev** [comment]
> > The deprecation date has shifted to March 1st, 2023 to give more time to adapt the workflows to Ubuntu20 or Ubuntu22.
> > The brownout schedule is also adjusted and now has shortened periods.
> 
> @miketimofeev Is there also a plan to make it much more obvious in the UI that the brownout is happening? The lack of any information in the view linked from pull requests made the user experience significantly worse here.

it's on our radar but I'm afraid we can't guarantee that better UI notifications will be implemented during this deprecation.

**Comment by miketimofeev** [comment]
We have decided to prolong the deprecation until the official end of life — April 2023. Brownouts schedule has been adjusted  as well to reflect the prolonged deprecation

**Comment by JimmyBanks** [comment]
> We have decided to prolong the deprecation until the official end of life — April 2023. Brownouts schedule has been adjusted as well to reflect the prolonged deprecation

Our project is using 'ubuntu-latest', but the pipelines continually default to 18.04 giving us this alert/error notice.

**Comment by miketimofeev** [comment]
@JimmyBanks could you share a few links to your pipelines with these warning and the screenshot of the Initialize job step with the runner image?

**Comment by JimmyBanks** [comment]
> @JimmyBanks could you share a few links to your pipelines with these warning and the screenshot of the Initialize job step with the runner image?

Turns out this was a mistake on our end and the pipeline was set to 18.04, not latest. We mixed up two different projects settings, and assumed both were updated at the same time to latest.

Sorry for wasting your time

**Comment by rene-hermenau** [comment]
> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. 

This will explain why our jobs suddenly fail without doing any modifications. 
We are paying you a lot of money for CI minutes, so you should inform your customers properly in advance, keep the deprecated services running until expiration date instead of making your clients tests fail and rising their costs for extra CI minutes and development time.

**Comment by santoshx** [comment]
What is the name of new pool to replace with pool "Azure Pipelines"?

**Comment by jkoooo4456** [comment]
Tlustoch

**Comment by sean-mcmanus** [comment]
Our data shows Ubuntu 18 usage is still close to Ubuntu 22 usage. Can you delay the deprecation/removal until more users have migrated off Ubuntu 18? The support for only 2 OS versions seems arbitrary and not driven by usage data?

**Comment by miketimofeev** [comment]
@sean-mcmanus we will support Ubuntu 18 until it reaches end of life in April 2023

**Comment by dsuch** [comment]
Hello @miketimofeev - can you please clarify whether 4/1/2023 means the 4th of January or the 1st of April in 2023? Thank you.

**Comment by awaters-pa** [comment]
This is happening today and today is not on your list....any advice?  We are very aware of the deprecation and don't need our productivity on the needed changes to be blacked by an artificial hindrance.

**Comment by patrickcavli** [comment]
This incident occurred while running CI pipeline of our platform. At least they could have mentioned this before the scheduled brownout.

**Comment by HSPDev** [comment]
Yeah wtf, this was not scheduled and on a friday... I was about to go home with a nice bugfixed shipped out....

**Comment by GeoFro** [comment]
October 14th is not on your brownout list.

**Comment by gibz104** [comment]
🤡

**Comment by OlegKarasik** [comment]
The best moment here is that jobs are get canceled and ... no notifications are send by email. We have just lost a few hours before realised that our build is not running and not propagating to environments. Thanks you very much, you increased my awareness of other platforms.

**Comment by ollielowson-wcbs** [comment]
> October 14th is not on your brownout list.

@github / @miketimofeev - any comment (other than just adding it after the fact and hoping none of your paying customers would notice)? This does not reflect well on you: the questionable decision to use brownouts is one thing, but then attempting to cover up a miscommunication by editing the communication after the fact makes you look unprofessional. Another reason to move to @gitlab!

**Comment by ollielowson-wcbs** [comment]
### For posterity, @miketimofeev / @github.
Before:
https://web.archive.org/web/20221012145059/https://github.com/actions/runner-images/issues/6002
![image](https://user-images.githubusercontent.com/95355555/195879442-a9c5847c-ed86-4c91-89e1-e2d3443d50ab.png)

After:
![image](https://user-images.githubusercontent.com/95355555/195879485-594942a1-ef35-4ca6-a2cf-e6db817a85d0.png)

**Comment by awaters-pa** [comment]
And the blog still isn't updated... :roll_eyes: 
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by miketimofeev** [comment]
@ollielowson-wcbs sorry, I'm not part of the team anymore and am not aware of the changes to the schedule.
Please ping @ddobranic for clarification

**Comment by ddobranic** [comment]
@awaters-pa sorry, my bad. reverted to original dates.

**Comment by awaters-pa** [comment]
> @awaters-pa sorry, my bad. reverted to original dates.

So when should we expect this unexpected brownout to end? @ddobranic

**Comment by redaER7** [comment]
brownouts are starting...
of course, with no notifications or alert...

**Comment by pierskarsenbarg** [comment]
Information on brownouts here: https://github.com/actions/runner-images/issues/6002

**Comment by awaters-pa** [comment]
> Information on brownouts here: #6002

Why link back to this issue?  The dates are wrong.  They were changed and then changed back.

**Comment by pierskarsenbarg** [comment]
Because when I first saw the link to this issue it said that the brownouts were due today 🤷

**Comment by mihaylovg** [comment]
@ddobranic Only registered to let you know what happened today was not professional at all.
My client was not able to deploy changes to production so they are not happy too.

**Comment by manxorist** [comment]
Please use a non-broken date format in the issue title: https://en.wikipedia.org/wiki/ISO_8601

**Comment by aibaars** [comment]
Out of curiosity is `4/1/2023` an English or an American date?

**Comment by aalbacetef** [comment]
> Don't get me wrong, I fully understand that you're deprecating 18.04 - but incorporating brownout periods to raise awareness?
> 
> If my team needs to get a build out for a critical bugfix on the 22nd of August... I'm just going to have to wait for 4 hours? If my understanding of that is true, I find that very odd behavior in an enterprise environment. Some businesses actually have SLAs with their clients. Would kindly request the team to find another way to "raise awareness". I came here because of the red banner when using the image, that worked fine as well and is a lot less invasive.
> 
> You're giving us two weeks to migrate away before brownouts start. Migrating is an action that requires testing and validation.


Literally just ran into this. CI started failing due to the brownout while working a on a bugfix

**Comment by dalboris** [comment]
Pretty please, GitHub, would it be possible to stop with this "brownout periods" insanity? Some people are trying to work.

In order to raise awareness, I would recommend sending emails. As is, Ubuntu 18.04 is still supported and breaking builds is poor practice. At the very least add a button "Yes, I'm aware of the deprecation, please always run my Ubuntu 18.04 builds anyway from now on".

Note that the reason we're still using Ubuntu 18.04 is *not* that our organization is slow to migrate to newer versions. The reason is that we need to generate AppImages, and these AppImages must be generated on Ubuntu 18.04 until at least April 2023, and ideally even after that. Our build scripts work perfectly fine on`ubuntu-latest`, but we *have to* build them on Ubuntu 18.04, otherwise the built binaries would link to versions of libc which are too new.

**Comment by niagol** [comment]
Can you at least adhere to your own timelines?

**Comment by rossvz** [comment]
> Can you at least adhere to your own timelines?
Agreed.
At the time of this comment, the original post states `November 15, 18:00 UTC – November 15, 20:00 UTC` but this brownout seemed to start at `20:00 UTC`

**Comment by dalboris** [comment]
It's 21:02 UTC, builds are still failing. Oh, and they did fail already soon after 18:00 UTC. The only reasonable course of action for GitHub is to cancel all brownouts periods until an opt-out mechanism is implemented, this is simply not acceptable.

**Comment by sjaeckel** [comment]
IMO your decision logic on the helpfulness of these brownout tests is flawed.

The assumption that this leads to fewer projects breaking sometime in the future when a specific runner is deprecated won't work, as this brownout mechanism is only triggered for "very active" projects. If a project is e.g. feature complete and has not many rebuilds, chances are high that this will not help at all and builds will only break sometime in the future after the runner was deprecated.

Instead you're hurting all projects that maybe have a good reason to still build against "soon to be deprecated runners" as already indicated by many users.

> [...] Ubuntu 18.04 is still supported and breaking builds is poor practice. At the very least add a button "Yes, I'm aware of the deprecation, please always run my Ubuntu 18.04 builds anyway from now on".

^ this

> The only reasonable course of action for GitHub is to cancel all brownouts periods until an opt-out mechanism is implemented, this is simply not acceptable.

^ and this

**Comment by hosseinmirzae** [comment]
> ### Breaking changes
> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01
> 
> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
> 
> **GitHub Actions\Azure DevOps::**
> 
> * October 3, 12:00 UTC – October 3, 14:00 UTC
> * October 18, 14:00 UTC – October 18, 16:00 UTC
> * November 15, 18:00 UTC – November 15, 20:00 UTC
> * November 30, 20:00 UTC – November 30, 22:00 UTC
> * December 15, 20:00 UTC - December 16 00:00 UTC
> * January 5, 10.00 UTC - January 5, 14.00 UTC
> * January 13, 12.00 UTC - January 13, 16.00 UTC
> * January 18, 14.00 UTC - January 18, 18.00 UTC
> * January 24, 16.00 UTC - January 24, 20.00 UTC
> * February 1, 18.00 UTC - February 1, 22.00 UTC
> * February 7, 16.00 UTC - February 7, 22.00 UTC
> * February 13, 14.00 UTC - February 13, 22.00 UTC
> * February 21, 10.00 UTC - February 21, 22.00 UTC
> * February 28, 10.00 UTC - February 28, 22.00 UTC
> * March 6, 00.00 UTC - March 7, 00.00 UTC
> * March 13, 00.00 UTC - March 14, 00.00 UTC
> * March 21, 00.00 UTC - March 22, 00.00 UTC
> 
> ### Target date
> April 1st, 2023
> 
> ### The motivation for the changes
> We maintain the latest two stable versions of any given OS version. Ubuntu 22.04 is going GA on 8/8/22 thus we start deprecating the oldest image.
> 
> ### Possible impact
> Workflows using the `ubuntu-18.04` image label should be updated to `ubuntu-latest`, `ubuntu-20.04`, or `ubuntu-22.04`
> 
> ### Platforms affected
> * [x]  Azure DevOps
> * [x]  GitHub Actions
> 
> ### Virtual environments affected
> * [x]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [ ]  Ubuntu 22.04
> * [ ]  macOS 10.15
> * [ ]  macOS 11
> * [ ]  macOS 12
> * [ ]  Windows Server 2019
> * [ ]  Windows Server 2022
> 
> ### Mitigation ways
> N\A

gh pr checkout 81

**Comment by Adisa101** [comment]
Resolve the master payment and explore it

**Comment by sgorugantu** [comment]
Even though we are using "windows-latest" as our Vm Image, we are still getting error as "This is a scheduled Ubuntu-18.04 brownout" and this is impacting our pipelines.

**Comment by kyrofa** [comment]
Interesting strategy to make sure folks were notified! May I suggest, however, a less hair-pulling message on this page? I re-triggered several times and checked the github status before I finally visited the summary page, which actually contained a very helpful message.

![Screenshot from 2023-02-07 08-46-57](https://user-images.githubusercontent.com/946674/217309442-feb24b10-22f4-45cf-872c-44f9dcdbb855.png)

**Comment by phlax** [comment]
as if to emphasize what an incredibly bad idea this is without any kind of opt out you have done this in the middle of an openssl patch release when projects need to run CI to publish their projects

**Comment by aligajani** [comment]
I do not think it is a good idea to prevent Github actions from running due to a brownout. You could notify us in a different way, or warn us using some alerts, but preventing a critical push due to this issue isn't a pleasing Developer Experience.

**Comment by joshforbes** [comment]
I do not think a "brownout" is a good strategy for this. Quite frustrating to be honest. We don't want to move off of 18.04, our plan is to move to a container before the deadline. However, it would have been nice to continue operations uninterrupted until the date.

**Comment by AleksandarTokarev** [comment]
I agree with the comments above - brownouts are not the best way to do things - it would be better to have notifications or emails sent with warnings instead.

**Comment by work-direxfranko** [comment]
> ### Breaking changes
> 
> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01
> 
> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
> 
> **GitHub Actions\Azure DevOps::**
> 
> - October 3, 12:00 UTC – October 3, 14:00 UTC
> - October 18, 14:00 UTC – October 18, 16:00 UTC
> - November 15, 18:00 UTC – November 15, 20:00 UTC
> - November 30, 20:00 UTC – November 30, 22:00 UTC
> - December 15, 20:00 UTC – December 16 00:00 UTC
> - January 5, 10.00 UTC – January 5, 14.00 UTC
> - January 13, 12.00 UTC – January 13, 16.00 UTC
> - January 18, 14.00 UTC – January 18, 18.00 UTC
> - January 24, 16.00 UTC – January 24, 20.00 UTC
> - February 7, 16.00 UTC – February 7, 22.00 UTC
> - February 21, 10.00 UTC – February 21, 22.00 UTC
> - March 6, 00.00 UTC – March 7, 00.00 UTC
> - March 13, 00.00 UTC – March 14, 00.00 UTC
> - March 21, 00.00 UTC – March 22, 00.00 UTC
> - March 28, 00.00 UTC – March 29, 00.00 UTC
> 
> ### Target date
> 
> April 1st, 2023
> 
> ### The motivation for the changes
> 
> We maintain the latest two stable versions of any given OS version. Ubuntu 22.04 is going GA on 8/8/22 thus we start deprecating the oldest image.
> 
> ### Possible impact
> 
> Workflows using the `ubuntu-18.04` image label should be updated to `ubuntu-latest`, `ubuntu-20.04`, or `ubuntu-22.04`
> 
> ### Platforms affected
> 
> - [X] Azure DevOps
> - [X] GitHub Actions
> 
> ### Virtual environments affected
> 
> - [X] Ubuntu 18.04
> - [ ] Ubuntu 20.04
> - [ ] Ubuntu 22.04
> - [ ] macOS 10.15
> - [ ] macOS 11
> - [ ] macOS 12
> - [ ] Windows Server 2019
> - [ ] Windows Server 2022
> 
> ### Mitigation ways
> 
> N\A

**Comment by probonopd** [comment]
> the image will be fully unsupported by 2023/04/0

Will it become un_supported_ or un_available_? I hope the former, since I'd like to continue building for it.

**Comment by CALIFAS95** [comment]
> ### Breaking changes
> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01
> 
> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
> 
> **GitHub Actions\Azure DevOps::**
> 
> * October 3, 12:00 UTC – October 3, 14:00 UTC
> * October 18, 14:00 UTC – October 18, 16:00 UTC
> * November 15, 18:00 UTC – November 15, 20:00 UTC
> * November 30, 20:00 UTC – November 30, 22:00 UTC
> * December 15, 20:00 UTC – December 16 00:00 UTC
> * January 5, 10.00 UTC – January 5, 14.00 UTC
> * January 13, 12.00 UTC – January 13, 16.00 UTC
> * January 18, 14.00 UTC – January 18, 18.00 UTC
> * January 24, 16.00 UTC – January 24, 20.00 UTC
> * February 7, 16.00 UTC – February 7, 22.00 UTC
> * February 21, 10.00 UTC – February 21, 22.00 UTC
> * March 6, 00.00 UTC – March 7, 00.00 UTC
> * March 13, 00.00 UTC – March 14, 00.00 UTC
> * March 21, 00.00 UTC – March 22, 00.00 UTC
> * March 28, 00.00 UTC – March 29, 00.00 UTC
> 
> ### Target date
> April 1st, 2023
> 
> ### The motivation for the changes
> We maintain the latest two stable versions of any given OS version. Ubuntu 22.04 is going GA on 8/8/22 thus we start deprecating the oldest image.
> 
> ### Possible impact
> Workflows using the `ubuntu-18.04` image label should be updated to `ubuntu-latest`, `ubuntu-20.04`, or `ubuntu-22.04`
> 
> ### Platforms affected
> * [x]  Azure DevOps
> * [x]  GitHub Actions
> 
> ### Virtual environments affected
> * [x]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [ ]  Ubuntu 22.04
> * [ ]  macOS 10.15
> * [ ]  macOS 11
> * [ ]  macOS 12
> * [ ]  Windows Server 2019
> * [ ]  Windows Server 2022
> 
> ### Mitigation ways
> N\A

**Comment by dirkf** [comment]
How do we run tests against old versions of packages not offered in later Ubuntu images?

**Comment by kyrofa** [comment]
Consider using docker, @dirkf.

**Comment by GKOLKO** [comment]
Hello, I am facing issue with the new versions of Ubunto (20, 22 and latest)
I have this error each time: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.0:resources (default-resources) on project ebx-technip-module: filtering /home/vsts/work/1/s/mdm-technip/ebx-technip-module/src/main/resources/resources.lnk to /home/vsts/work/1/s/mdm-technip/ebx-technip-module/src/main/webapp/WEB-INF/classes/resources.lnk failed with MalformedInputException: Input length = 1 -> [Help 1]
How can I solve this issue?

**Comment by MikeMcC399** [comment]
@GKOLKO 
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.0:resources
> How can I solve this issue?

This does not sound like an error with the GitHub runner. I suggest you search instead on https://stackoverflow.com/.

**Comment by nahimmedvent** [comment]
Ubuntu 20.04 and 22.04 don't work at all for me, I keep getting the error /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/site/wwwroot/.python_packages/lib/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so)	
Because these versions run on 2.29 glibc

**Comment by mikhailkoliada** [comment]
@nahimmedvent software on Ubuntu 20.04 and 22.04 is compiled with newer version of libc, which makes the software compiled with older version of libs simply incompatible. There is no straightforward way tp solve this problem as it is a bit non-trivial. The easiest solution would be to switch to ubuntu:18.04 in docker.

**Comment by lakshyagithub** [comment]
This will happen on April fools 🤣

**Comment by mikhailkoliada** [comment]
Ubuntu-18.04 is deprecated and disabled for all the customers

**Comment by Abduljakulsalsal** [comment]
> 

✌️

**Comment by eyalroz** [comment]
Well, you could at least provide a proper notice about Ubuntu 18.04 runners no longer being available, instead of having actions fail mysteriously...
