### ISSUE TITLE
Ubuntu 20.04.4 Environment Locks Up While Cloning a Repo (Github-hosted runner)

### ISSUE THREAD

**Issue by bhjelstrom** [actions/runner-images#6022]
### Description

I have an action that sometimes completes in three hours, but often locks-up at the exact same spot while cloning a repository. When this lock-up occurs, it resolves itself consistently after 3 hours and 50 minutes. This lock-up causes my action to fail as it pushes the total action time beyond 6 hours. Git is used to clone the repo via a script in another repo. Hundreds of other repositories are cloned before and after this particular repository is cloned. The same mirror is used for other repositories.

I can't replicate this on my local machine and I never observed this when I was using self-hosted runners. I've upgraded the github-hosted runner to the newly released Ubuntu 22.0.4 environment for now to see if anything changes. Perhaps this has something to do with the network stack, cloud provider, or some other VM resource limitation.

I can't identify exactly what is locking up at this time (git, the virtual environment, etc). 

EDIT: The first run with 22.04 did not lock up. The clone step in question took only 13 seconds.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220729.1

### Is it regression?

No

### Expected behavior

No lock-up occurs

### Actual behavior

3.8 hour lockup sometimes occurs while cloning a repository

### Repro steps

1. Run action
2. Sometimes the action takes 3.8 hours to clone a particular repository, and sometimes it does not.

**Comment by mikhailkoliada** [comment]
@bhjelstrom hello!

Could you please provide real examples of the problem so we take a look.

**Comment by bhjelstrom** [comment]
I now have 4 basically identical workflows (Ubuntu 22.0.4) running on every commit. Each workflow will sometimes pause for the aforementioned 3.8 hours while downloading ncurses. Through hundreds of self-hosted and local builds I have never seen this. Note the time difference:

```
2022-08-04T20:52:30.0232682Z >>> Downloading ncurses  6.1 
2022-08-05T00:43:04.0877252Z >>> Extracting ncurses 6.1
```

Sometimes when I try to access the logs of workflows that are stuck on this step, this is all I see:
```
2022-08-08T18:29:41.5275692Z Requested labels: ubuntu-22.04
2022-08-08T18:29:41.5275736Z Job defined at: <redacted>
2022-08-08T18:29:41.5275754Z Waiting for a runner to pick up this job...
2022-08-08T18:29:42.9712121Z Job is waiting for a hosted runner to come online.
2022-08-08T18:29:46.2681587Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
```

Is there another log file I can extract from the github-hosted runners? Not sure what else to provide.

**Comment by miketimofeev** [comment]
@bhjelstrom do you have any updates? And maybe you have a repo that we can clone and experiment with?

**Comment by bhjelstrom** [comment]
I believe this has been fixed by reducing in the number of make jobs from 4 (via nproc) to 2. The build completes an entire hour earlier as well. This implies that the old builds were locking up more than once.

Most likely cause: My build required too much memory for the 7GB runner and sometimes spilled over into swap. I should have seen this coming, but resource warnings for action runners might generally add value. 

Also, I would definitely pay for bigger/faster runners to help keep our workflows in github.

**Comment by miketimofeev** [comment]
@bhjelstrom thanks for the update!
More powerful runners are on our radar but I can't provide ETA when they will be available.
I'm going to close the issue please let me know if you have any concerns.
Thank you!

**Comment by miketimofeev** [comment]
@bhjelstrom beta is announced by the way https://github.blog/2022-09-01-github-actions-introducing-the-new-larger-github-hosted-runners-beta/

**Comment by bhjelstrom** [comment]
@miketimofeev Great timing! I signed up for the beta. Thanks.
