### ISSUE TITLE
[All OSs] Go version 1.16 will be removed on August, 15th

### ISSUE THREAD

**Issue by ddobranic** [actions/runner-images#6024]
### Breaking changes

Go version 1.16 will be removed from all operating systems.

### Target date

August 15, 2022.

### The motivation for the changes

According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md)
we support [3 latest minor versions of Go],
(https://endoflife.date/go) which are 1.17, 1.18 & 1.19 at the moment.

### Possible impact

If your project depends on a pre-installed Go version 1.16 it can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

To install any versions in runtime use:

https://github.com/actions/setup-go action for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by mikhailkoliada** [comment]
Will be removed next week.
