### ISSUE TITLE
CI seemed to run on an unmerged branch

### ISSUE THREAD

**Issue by danielhjacobs** [actions/runner-images#6034]
### Description

https://github.com/ruffle-rs/ruffle/runs/7731010612?check_suite_focus=true ran with this image: https://github.com/actions/runner-images/blob/ubuntu20/20220807.1/images/linux/Ubuntu2004-Readme.md#browsers-and-drivers, but that image is created by commit https://github.com/actions/runner-images/commit/3c5935f2a2208ebca95da6a10be038acd9f153be, which is part of PR https://github.com/actions/runner-images/pull/6031, which is un-merged.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220807.1

As I said, an unmerged branch; see build (failed because of Chromedriver mismatch with Chrome version): https://github.com/ruffle-rs/ruffle/runs/7731010612?check_suite_focus=true

### Is it regression?

Unknown

### Expected behavior

CI should always run on https://github.com/actions/runner-images/commits/main

### Actual behavior

CI ran on an unmerged branch.

### Repro steps

Unknown: It seemed to be a fluke, as other CI runs both before and after ran on main.

**Comment by danielhjacobs** [comment]
Possibly because https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20220807.1 is available on https://github.com/actions/runner-images/releases, despite it's status as an unmerged PR.

**Comment by danielhjacobs** [comment]
Image used is entirely inconsistent:

https://github.com/ruffle-rs/ruffle/actions/runs/2820646866:
- Test Node.js 16 / Rust stable / ubuntu-latest
    - Version: 20220807.1
- Test Node.js 18 / Rust stable / ubuntu-latest
    - Version: 20220729.1

https://github.com/ruffle-rs/ruffle/actions/runs/2820648391:
- Test Node.js 16 / Rust stable / ubuntu-latest
    - Version: 20220729.1
- Test Node.js 18 / Rust stable / ubuntu-latest
    - Version: 20220807.1

**Comment by panekj** [comment]
That PR is only for documentation to be merged, image version is already being deployed and status can be seen in [README.md](https://github.com/actions/runner-images/blob/main/README.md)

**Comment by danielhjacobs** [comment]
Ok. Why is the used image inconsistent though?

**Comment by panekj** [comment]
Because it's being rolled out to all hosted runners so some of them will run different version until all are updated, unless you mean something else?
