### ISSUE TITLE
MFCS140u.lib missing for arm/arm64

### ISSUE THREAD

**Issue by yassermkhan** [actions/runner-images#6055]
### Description

Mfcs140u.dll is missing in the arm and arm64 vs2022 installs inside the windows2022. Other flavors are fine.

![image](https://user-images.githubusercontent.com/86027491/184050211-ac5fce04-16bc-4b87-96ed-73c6cf2271f3.png)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20220808.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20220808.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220808.1

### Is it regression?

no

### Expected behavior

All flavors should have this DLL.

### Actual behavior

ARM and ARM64 msbuilds are failing with this missing DLL.

### Repro steps

Compile something with mfcs140u.dll required.

**Comment by al-cheb** [comment]
Hello @yassermkhan.
I didn't found any mention about this `mfcs140u.dll` lib. Which VS component contains this lib?

**Comment by swenkeratmicrosoft** [comment]
In my local install, I see the following, so I assume it's the ATL MFC Spectre-mitigated components for ARM and ARM64.

c:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\atlmfc\lib\spectre\arm\mfcs140u.lib
c:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\atlmfc\lib\spectre\arm64\mfcs140u.lib
c:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\atlmfc\lib\spectre\x64\mfcs140u.lib
c:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\atlmfc\lib\spectre\x86\mfcs140u.lib

**Comment by al-cheb** [comment]
@swenkeratmicrosoft, those libraries are already preinstalled:

![image](https://user-images.githubusercontent.com/47745270/184191709-22f4f755-bff6-40bb-b9cf-2d4de7a7806f.png)

**Comment by swenkeratmicrosoft** [comment]
@al-cheb

From your above output, versions 14.16 and 14.32 have arm but 14.29 does not.  I suspect that's our issue.

**Comment by yassermkhan** [comment]
I can confirm that the 2022 image has the same libs (missing 14.29 on arm/arm64)

**Comment by al-cheb** [comment]
In scope of this https://github.com/actions/runner-images/pull/6064 PR I added new VS components.

**Comment by al-cheb** [comment]
The new Windows Server 2022 image has been deployed.

![image](https://user-images.githubusercontent.com/47745270/184888603-289191fd-1582-4720-b606-c1bf4b4e4124.png)

**Comment by swenkeratmicrosoft** [comment]
@al-cheb - I confirmed that the new libs are available and that this fixed our build break.  Thanks!
