### ISSUE TITLE
Update Chrome Driver

### ISSUE THREAD

**Issue by PraveenHudgi1** [actions/runner-images#6061]
### Tool name

ChromeDriver

### Tool license

No License 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

104.0.5112.79

### Brief description of tool

Current driver version having issue to run selenium scripts , hence needed updated version of chrome driver for windows

### URL for tool's homepage

https://chromedriver.storage.googleapis.com/index.html?path=104.0.5112.79/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

**Comment by igorboskovic3** [comment]
Hi @PraveenHudgi1, thank you for you request, we already updated Chrome driver to desired version, so it will be updated as soon as we finish with this week deployments.

**Comment by PraveenHudgi1** [comment]
Thank You for the update @igorboskovic3 .

When we can expect ? Any tentative date ? 
Because of current version of chrome driver 103,We are not able to run automation script on azure pipeline.

**Comment by al-cheb** [comment]
@PraveenHudgi1, The new Windows Server 2019 image has been deployed - https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md

- Google Chrome 104.0.5112.81
- Chrome Driver 104.0.5112.79
