### ISSUE TITLE
Windows2019 requires ARM64EC workload

### ISSUE THREAD

**Issue by DavidXanatos** [actions/runner-images#6069]
### Tool name

ARM64EC workload for VS

### Tool license

same as teh rest of VS

### Add or update?

- [X] Add
- [ ] Update

### Desired version

newest

### Brief description of tool

Allows to build ARM64EC binaries using VS 2019

Using VS 2022 is not an option as VS 2022 can no longer compile windows 7 compatible drivers.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```cmd
cmd.exe /c start /wait " " "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --add Microsoft.VisualStudio.Component.VC.Tools.ARM64EC --norestart --installWhileDownloading --quiet
```

### Tool installation time in runtime

It takes 10 minutes :(

**Comment by DavidXanatos** [comment]
When #6075 be online? currently it still fails

**Comment by al-cheb** [comment]
> When #6075 be online? currently it still fails

The new image rollout will be started on Monday and it will take 2-3 days.

**Comment by al-cheb** [comment]
The new Windows Server 2019 image has been deployed.

**Comment by DavidXanatos** [comment]
seams to be working thank you very much
