### ISSUE TITLE
Add Netwide Assembler (NASM)

### ISSUE THREAD

**Issue by TES286** [actions/runner-images#6070]
### Tool name

Netwide Assembler (NASM)

### Tool license

Simplified (2-clause) BSD license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

Less than 2M

### Brief description of tool

An asssembler for the x86 CPU architecture portable to nearly every modern platform, and with code generation for many platforms old and new.

### URL for tool's homepage

https://www.nasm.us/

### Provide a basic test case to validate the tool's functionality.

```bash
nasm --version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
It could build from source code or download from its website
Please visit https://github.com/netwide-assembler/nasm/blob/master/INSTALL or https://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D
```

### Tool installation time in runtime

Unknown

### Are you willing to submit a PR?

Sorry, I may not have time.

**Comment by al-cheb** [comment]
Hey @TES286.
There is a community task [setup-nasm](https://github.com/marketplace/actions/set-up-nasm) to install it in runtime. Please consider using it.
Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns
