### ISSUE TITLE
No way to update session environment in Windows runners

### ISSUE THREAD

**Issue by MarkCallow** [actions/runner-images#6071]
### Description

After a step runs a software installer that adds environment variables or updates the Path environment in the Windows registry there is no way to update the session environment so it has the updated environment. I have been trying Chocolatey's `refreshenv`. Even subsequent steps do not see the new environment. Do they not use new shells?

I consider this to be a bug because (a) figuring out the environment updates made by each used installer is unmaintainable and (b) other CI systems' Windows runners support it.

I asked about this in https://github.com/actions/runner-images/discussions/6065. The suggested answer was to use GITHUB_ENV. I refer to my point (a) above. I think GITHUB_ENV supports a different use case.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/KhronosGroup/KTX-Software/runs/7825296047?check_suite_focus=true#step:8:94

### Is it regression?

Don't know. I only just started  using Actions.

### Expected behavior

I want calling `refreshenv` to update the environment of the current session (shell) and any newly started shells in the same or subsequent steps to pick up the new environment from the Windows registry.

### Actual behavior

`refreshenv` apparently runs. It prints out the message

```
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
```

nevertheless the newly added variable(s) are not visible in the shell. The variables are also not visible in a subsequent step even with `refreshenv` there also.

AFAIK the default shell is Powershell so I don't understand why the message above mentions `cmd.exe`. According to the [Chocolatey doc](https://docs.chocolatey.org/en-us/create/functions/update-sessionenvironment) `refreshenv` in Powershell is an alias for `Update-SessionEnvironment` but if I try to explicitly call `Update-SessionEnvironment` I get an error that a cmdlet with that name can't be found.

### Repro steps

Create and run Action with steps like these:

```
- name Install env var
   run: |
     reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v VULKAN_SDK /t REG_SZ /d foo\bar
     refreshenv
     echo "VULKAN_SDK is $env:VULKAN_SDK"
     reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v VULKAN_SDK

 - name: Build
   run: |
     reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v VULKAN_SDK
     refreshenv
     echo "VULKAN_SDK is $env:VULKAN_SDK"
     refreshenv && echo "VULKAN_SDK is $env:VULKAN_SDK"
```

The reg queries will show the variable is in the registry yet `$env:VULKAN_SDK is empty.

Note that I may have the syntax for `reg add` wrong. I haven't tried that  as the installer I run in the first step sets the variable.

**Comment by al-cheb** [comment]
Hey @MarkCallow.
This issue is not related to images itself, for general questions about using the runner images please open requests in the [GitHub Actions Runner](https://github.com/actions/runner) or  [GitHub Actions Community Forum](https://github.community/c/github-actions/41).
