### ISSUE TITLE
Add Tailscale

### ISSUE THREAD

**Issue by johannesdrescher** [actions/runner-images#6072]
### Tool name

Tailscale

### Tool license

BSD-3-Clause license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.28.0

### Brief description of tool

CLI for WireGuard VPN Provider

### URL for tool's homepage

https://tailscale.com/

### Provide a basic test case to validate the tool's functionality.

```bash
tailscale --version && tailscaled --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
# I use
RUN brew up && brew install tailscale
# However the Tailscale docs suggest using apt-get for Ubuntu 20.04 (see https://tailscale.com/kb/1039/install-ubuntu-2004/)
```

### Tool installation time in runtime

Approximately 5s

### Are you willing to submit a PR?

Yes, but this would be my first one

**Comment by al-cheb** [comment]
Hey @johannesdrescher.

Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns

**Comment by johannesdrescher** [comment]
Hi @al-cheb, thank you for your response. I undertand your position. The thing is, this tool is so widely used and gaining popularity. I use it in almost all of my workflows and I'm sure many others do too. It takes about 5-8 seconds to install (granted, not much, but on every workflow run...). Caching it doesn't speed things up because that takes a moment too. Considering that many users will have the exact same problem, maybe the trouble of maintaining it would really be worth it. I wouldn't at all mind taking over the responsibility of keeping it up to date.
