### ISSUE TITLE
Xamarin workload is missing or not installed in windows-2022 20220814.1

### ISSUE THREAD

**Issue by jeromelaban** [actions/runner-images#6082]
### Description

Building a xamarin.ios library using windows-2022 20220814.1 results in failures such [as this one](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=51963&view=logs&j=2f2835f1-b487-5d0f-02dc-03106f033ea9&t=d5a0b1a3-e1dc-521c-db15-8d5dd936a2aa&l=8100):

```
C:\Users\VssAdministrator\.nuget\packages\msbuild.sdk.extras\3.0.23\Build\LanguageTargets\CheckMissing.targets(44,5): error : The specified language targets for xamarinios10 is missing. Ensure correct tooling is installed for 'xamarinios'. Missing: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets' [D:\a\1\s\src\library\Uno.Material\Uno.Material.csproj]
```

Curiously, the image is [supposed to have it installed](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#workloads-components-and-extensions) with `Component.Xamarin`, but in general installing VS 17.3 on a desktop does not install it by default. It could be related.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220814.1

### Is it regression?

yes, it worked with the previous agents builds

### Expected behavior

Builds are completing properly

### Actual behavior

```
C:\Users\VssAdministrator\.nuget\packages\msbuild.sdk.extras\3.0.23\Build\LanguageTargets\CheckMissing.targets(44,5): error : The specified language targets for xamarinios10 is missing. Ensure correct tooling is installed for 'xamarinios'. Missing: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets' [D:\a\1\s\src\library\Uno.Material\Uno.Material.csproj]
```

### Repro steps

Build any Xamarin library.

**Comment by al-cheb** [comment]
Hey @jeromelaban.
We have been starting a new image rollout and this component is not pre-installed by default - https://github.com/actions/runner-images/pull/6078. I will add it back.

**Comment by al-cheb** [comment]
As a temporary workaround, this component can be installed in runtime:

```
- run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToAdd = @(
            "Component.Xamarin"
          )
          [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0)
          {
              Write-Host "components have been successfully added"
          }
          else
          {
              Write-Host "components were not installed"
              exit 1
          }
```

**Comment by jeromelaban** [comment]
Thanks for the workaround, I'll keep it handy in case this happens in the future :) Also as an FYI, a rollback has been made and builds are running on `20220808.1`.

**Comment by jeromelaban** [comment]
Update again, it looks like the rollback was rollbacked and I'm back on `20220814.1`.

**Comment by WilliamWatterson86** [comment]
Having the same issue here.  Do we think this one will be fixed soon?  Workaround seems to work ok for me at the minute

**Comment by jeromelaban** [comment]
Also, as a note, testing is difficult because agents are balanced between `20220814.1` and `20220808.1`, making builds pass or fail randomly.

**Comment by WilliamWatterson86** [comment]
Actually the workaround didnt work for me, it got passed the nuget restore step (which was the one failing previously), but this time it fails with an AOT error.  Build works fine when it uses agent with version 20220808.1.  Is there any way to force my pipeline to use this agent version?

**Comment by al-cheb** [comment]
We have been starting a new image rollout - https://github.com/actions/runner-images/pull/6102. I hope this helps.

**Comment by drmikesell** [comment]
@al-cheb Thanks for addressing this quickly, it's very much appreciated.

**Comment by andersonvieiragomeslopes** [comment]
@al-cheb I'm having a problem too, but only on (Xamarin) android, an error appears apparently from iOS, but it's in the android build, can you tell me if they are different problems or is there?

"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/msbuild.exe" /version /nologo
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 6.3.0.131 / 6.3.0+f43de507d39cf094a546a949f9b32bb5eefcc4ad.f43de507d39cf094a546a949f9b32bb5eefcc4ad
SYSTEMVSSCONNECTION exists true
C:\hostedtoolcache\windows\NuGet\6.3.0\x64\nuget.exe sources Add -NonInteractive -Name 68a4eaa2-2807-473f-a961-d0ffbbce79b8 -Source https://ApplicationName****.pkgs.visualstudio.com/473f0114-c846 -4f11-aeac-9d670193f72e/_packaging/68a4eaa2-2807-473f-a961-d0ffbbce79b8/nuget/v3/index.json -ConfigFile D:\a\1\Nuget\tempNuGet_4498.config
Package source with Name: 68a4eaa2-2807-473f-a961-d0ffbbce79b8 added successfully.
C:\hostedtoolcache\windows\NuGet\6.3.0\x64\nuget.exe sources Add -NonInteractive -Name NuGetOrg -Source https://api.nuget.org/v3/index.json -ConfigFile D:\a\1 \Nuget\tempNuGet_4498.config
Package source with Name: NuGetOrg added successfully.
C:\hostedtoolcache\windows\NuGet\6.3.0\x64\nuget.exe restore D:\a\1\s\ApplicationName****.sln -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\Nuget \tempNuGet_4498.config
NuGet Version: 6.3.0.131
D:\a\1\s\iOS\iOS.csproj(490,11): error MSB4226: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS .CSharp.targets" was not found. Also, tried to find "Xamarin\iOS\Xamarin.iOS.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.

MSBuild auto-detection: using msbuild version '17.3.0.37102' from 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\ozbge4vp.hmz.nugetinputs.targets" /t: GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\v5cj4iot.zd5.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p :DisableCheckingDuplicateNuGetItems="True" /p:RestoreTaskAssemblyFile="C:\hostedtoolcache\windows\NuGet\6.3.0\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\a\1\s\\" /p :RestoreConfigFile="D:\a\1\Nuget\tempNuGet_4498.config" /p:SolutionDir="D:\a\1\s\\" /p:SolutionName="ApplicationName****"
NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by al-cheb** [comment]
@jeromelaban, The new image with `Component.Xamarin` has been deployed.
