### ISSUE TITLE
Visual Studio 2022 17.3

### ISSUE THREAD

**Issue by arvindshmicrosoft** [actions/runner-images#6086]
### Tool name

Visual Studio 2022

### Tool license

https://visualstudio.microsoft.com/license-terms/vs2022-ga-proenterprise/

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.3 - https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-3-is-now-available/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
@arvindshmicrosoft , the new Windows Server 2022 image with Visual Studio Enterprise 2022 | 17.3.32804.467 on board has been deployed - https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by arvindshmicrosoft** [comment]
Thank you for the extremely quick turnaround @al-cheb !
