### ISSUE TITLE
Add miniflare

### ISSUE THREAD

**Issue by tgeoghegan** [actions/runner-images#6087]
### Tool name

miniflare

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

"Miniflare is a simulator for developing and testing [Cloudflare Workers](https://workers.cloudflare.com/)."

This is useful for developers who are deploying to Cloudflare Workers.

### URL for tool's homepage

https://github.com/cloudflare/miniflare

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
The following step in a GitHub Action reliably installs Miniflare:

    - name: Install Miniflare
      # Miniflare is used in support of Daphne integration tests.
      run: npm install --location=global miniflare
```

### Tool installation time in runtime

3s, in [this particular run](https://github.com/divviup/janus/runs/7848552842?check_suite_focus=true) of a test action I have that installs `miniflare`.

**Comment by al-cheb** [comment]
Hey @tgeoghegan.

Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns
