### ISSUE TITLE
Update/Add AWS CDK CLI

### ISSUE THREAD

**Issue by Simonl9l** [actions/runner-images#6088]
### Tool name

AWS CDK CLI

### Tool license

Apache-2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

53 MB

### Brief description of tool

The [AWS Cloud Development Kit](https://github.com/aws/aws-cdk) (AWS CDK) is an open-source software development framework to define cloud infrastructure in code and provision it through AWS CloudFormation.

It offers a high-level object-oriented abstraction to define AWS resources imperatively using the power of modern programming languages. Using the CDK’s library of infrastructure constructs, you can easily encapsulate AWS best practices in your infrastructure definition and share it without worrying about boilerplate logic.

### URL for tool's homepage

https://www.npmjs.com/package/aws-cdk

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
npm install -g aws-cdk
```

### Tool installation time in runtime

less than 10 seconds.

### Are you willing to submit a PR?

If required but no idea how.

**Comment by al-cheb** [comment]
Hey @Simonl9l.

Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns

**Comment by Simonl9l** [comment]
How is this different than including the base AWS Cli in the image ? its also pretty small...

CDK is becoming the standard for IaC deployment. even Hashi Corp Terraform is now adopting it.

As per other issue requests, the eligibility rules for inclusion seem very nebulous. 

I guess in AWS were asking...
