### ISSUE TITLE
Update/Add dotnet Amazon.Lambda.Tools

### ISSUE THREAD

**Issue by Simonl9l** [actions/runner-images#6090]
### Tool name

Amazon.Lambda.Tools

### Tool license

Apache v2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

A dotnet tool - only needed for images that have dotnet installed

Amazon.Lambda.Tools adds commands to the dotnet cli to build/deploy/invoke AWS Lambda functions

### URL for tool's homepage

https://www.nuget.org/packages/Amazon.Lambda.Tools

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
dotnet tool install -g Amazon.Lambda.Tools
```

### Tool installation time in runtime

less than 10 seconds

**Comment by al-cheb** [comment]
Hey @Simonl9l.

Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns

**Comment by Simonl9l** [comment]
@al-cheb it would be good if more concise documentation contained a "real" understanding what requirements define eligibility.

It is very had to distinguish this `Amazon.Lambda.Tools` request say from say the  `dotnet workflow`https://github.com/actions/runner-images/issues/5720 request where it seem the latter will be supported.

there seem to be a ton of subjectivity here!
