### ISSUE TITLE
Maven build issues on Ubuntu 20.04 (20220814.1)

### ISSUE THREAD

**Issue by s4got10dev** [actions/runner-images#6104]
### Description

Since release of [20220814.1](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220814.1) our maven builds are taking too much time to finish or often fails with `Java Heap Space` issues when we run tests with Surefire plugin that starts fork process.

We use ***Java 17*** installed by [**actions/setup-java**](https://github.com/actions/setup-java) and ***MySQL 5.7*** installed by [**mirromutth/mysql-action@v1.1** ](https://github.com/mirromutth/mysql-action)

Configuring java parameters doesn't give needed effect and affects our day to day work.

In same time if we switch our actions to use `ubuntu-22.04` our pipelines working well just like with `ubuntu-20.04:20220807.1`.

Could you, please, check whether you found something already related to this image release.

Alternatively can you, please, advice how we can rollback and use `ubuntu-20.04:20220807.1` on our GitHub Actions? 

Thanks
Serhii

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[ubuntu-20.04 20220814.1](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220814.1)

### Is it regression?

yes

### Expected behavior

Build runs without issues just like on [20220807.1](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220807.1)

### Actual behavior

Maven builds ends up with 
![image](https://user-images.githubusercontent.com/22197145/185157323-844d3f02-22bc-4ce2-bf43-2427ea450325.png)

### Repro steps

It would be time consuming for me to create similar use case with a lot of tests that utilise MySQL, so I expect only answers about possibility to switch back to `ubuntu-20.04:20220807.1` until new release will be done

**Comment by al-cheb** [comment]
Hello @s4got10dev.
Currently, it's not possible to pick up image version.

**Comment by s4got10dev** [comment]
Thanks @al-cheb for quick answer. 

As I understand we can expect next `ubuntu-20.04` release next week?
Is there any roadmap on planned image updated?

**Comment by al-cheb** [comment]
> As I understand we can expect next `ubuntu-20.04` release next week? Is there any roadmap on planned image updated?
Usually, we deploy a new image once per week.

**Comment by miketimofeev** [comment]
@s4got10dev could you check the new image? Does the issue persist?

**Comment by s4got10dev** [comment]
> @s4got10dev could you check the new image? Does the issue persist?

@miketimofeev unfortunately we still facing issues, so we will still use `ubuntu-22.04`

**Comment by miketimofeev** [comment]
@s4got10dev Sorry to hear that. Could you provide a reproducible example so we can experiment and debug the issue further?

**Comment by s4got10dev** [comment]
@miketimofeev as I mentioned in `Repro steps` already It would be quite time consuming to create similar project with a lot of tests that utilise MySQL

**Comment by miketimofeev** [comment]
@s4got10dev I understand, but I'm afraid we can't do much without repro steps as we couldn't find any suspicious changes between working and problematic images.

**Comment by s4got10dev** [comment]
@miketimofeev sure I understand, that's why I just thought that it's possible to fallback to some specific version from the past.
I assume changes are somewhere in low level components that made MySQL or JVM work so slow, so I will close this issue, as it not worth spending too much time on it.
