### ISSUE TITLE
Add Parallels to MacOS image

### ISSUE THREAD

**Issue by dmachaj** [actions/runner-images#6105]
### Tool name

Parallels + Parallels SDK

### Tool license

Paid.  We can supply our own paid license when our builds begin

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest Parallels (currently 18.0.0-53049) 
latest ParallelsVirtualizationSDK (currently 17.1.4-51567)

### Approximate size

43 + 324 = 367MB (.dmg files)

### Brief description of tool

[https://download.parallels.com/desktop/v18/18.0.0-53049/ParallelsDesktop-18.0.0-53049.dmg](https://download.parallels.com/desktop/v18/18.0.0-53049/ParallelsDesktop-18.0.0-53049.dmg)
[https://download.parallels.com/desktop/v17/17.1.4-51567/ParallelsVirtualizationSDK-17.1.4-51567-mac.dmg](https://download.parallels.com/desktop/v17/17.1.4-51567/ParallelsVirtualizationSDK-17.1.4-51567-mac.dmg)

Parallels is a virtualization framework for MacOS.  We produce some VM images using Packer and Parallels is one of the flavors.  On MacOS 10.15 we can install Parallels in our setup script and it works fine.  On MacOS 11 and newer the kernel extension requires a reboot so it cannot be installed during the build.  We need it baked into the agent image with the kernel extension already loaded.

We can happily supply our own license at runtime using `prlsrvctl install-license --key $PARALLELS_LICENSE_KEY`.  We just need the kernel extension loaded ahead of time.

### URL for tool's homepage

https://www.parallels.com/

### Provide a basic test case to validate the tool's functionality.

```bash
prlctl --version
open -a 'Parallels Desktop'
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install --cask parallels
brew install --cask parallels-virtualization-sdk

(A reboot is needed afterwards)
```

### Tool installation time in runtime

30 seconds maybe

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
Hello @dmachaj.
We have decided not to add Parallels software on macos images due to license policy and maintenance complexity. If we see  a lot of requests from customers to add it we will reopen the thread.

**Comment by dmachaj** [comment]
@al-cheb I have been communicating with Parallels support.  One option is simply to get the kernel extension approved without otherwise installing Parallels.  That would avoid the license policy concern.

The approach would be:
1) Install Parallels
2) Approve the Parallels Kernel Extension
3) Reboot
4) Uninstall Parallels

The only remainder in the image would be the kernel record that the Parallels extension is approved.  Workloads that require Parallels can then install _the same version_ of Parallels and the kernel extension will already be approved with no reboot required.  That would unblock us.

**Comment by chrnguyen-msft** [comment]
@al-cheb For context: The Parallels VMs that we produce get nearly a million downloads per year.  
This is a high priority item for us and we would greatly appreciate any assistance that we can get to close on this.

**Comment by al-cheb** [comment]
@dmachaj, Do you have a code snippet that we can use to validate a pipeline except the installation step?

**Comment by dmachaj** [comment]
Could you please elaborate on the question?  I don't think I fully understand.  Are you looking for a pipeline that would test if Parallels is registered properly?  Or one that would use it?  If the latter please send me an email and I can point you to our MacOS build pipeline that uses Parallels.

**Comment by al-cheb** [comment]
@dmachaj,  Are you looking for a pipeline that would test if Parallels is registered properly? - Yep, I am looking for the steps how we can validate it.

**Comment by al-cheb** [comment]
@dmachaj, the new macos-12 image has been deployed.

![image](https://user-images.githubusercontent.com/47745270/193815831-6e7b1bd0-11e2-4348-b916-6a57f1fda4c1.png)
