### ISSUE TITLE
Il mismatch between 'P1' version '20220421' and 'P2' version '20211117'

### ISSUE THREAD

**Issue by matthiakl** [actions/runner-images#6107]
### Description

Since the 20220814.1 Windows runner update MSVC fails linking MSIL module with LTCG. First I thought, the problem was that the vcpkg bincache was built with an older version, but now vcpkg got an update and the problem persists.
This looks similar to #6091

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20220816.1
https://github.com/widelands/widelands/runs/7888821429?check_suite_focus=true

### Is it regression?

20220808.1: https://github.com/widelands/widelands/runs/7846519644?check_suite_focus=true

### Expected behavior

Linking should succeed.

### Actual behavior

```
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
glbinding.lib(functions_d.cpp.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
Stop.
fatal error C1900: Il mismatch between 'P1' version '20220421' and 'P2' version '20211117'
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\nmake.exe"' : return code '0x2'
LINK : fatal error LNK1257: code generation failed
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

### Repro steps

This seems to only affect release builds. Debug builds link successfully: https://github.com/widelands/widelands/runs/7888821298?check_suite_focus=true

**Comment by al-cheb** [comment]
@matthiakl, Could you please test a workaround - https://github.com/actions/runner-images/issues/6091#issuecomment-1219346037 ?

**Comment by matthiakl** [comment]
Thanks @al-cheb, with the workaround it links successfully again.
(https://github.com/matthiakl/widelands/runs/7898693155?check_suite_focus=true)

**Comment by al-cheb** [comment]
Thank you . Close to track https://github.com/actions/runner-images/issues/6091
