### ISSUE TITLE
Add AzureSignTool

### ISSUE THREAD

**Issue by sudara** [actions/runner-images#6113]
### Tool name

AzureSignTool

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.0

### Brief description of tool

Julian Dunn asked me to put in this request.

Currently, one cannot build a signed (deployable) Windows application out of the box with GitHub Actions.  Translated: Windows apps/installers built on GitHub Actions will popup a Malware warning on Windows unless they are signed with an Extended Validation (EV) certificate.

Outside of a physical dongle, one of the only options is to store an EV certificate is on Azure's Key Vault (which stores the certs on an a Hardware Security Module (HSM)).

[AzureSignTool](https://github.com/vcsjones/AzureSignTool) is specified as the tool to use for [Microsoft's official documentation for code signing in GitHub Actions](https://docs.microsoft.com/en-us/windows/msix/desktop/cicd-keyvault#using-azure-signtool-with-github-actions)

However, this tool is not installed by default on GitHub Actions and adds ~30 seconds of time to install every build.

Read more about [EV cert signing on GitHub Actions](https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/).

### URL for tool's homepage

https://github.com/vcsjones/AzureSignTool

### Provide a basic test case to validate the tool's functionality.

```bash
I'd probably recommend just running `AzureSignTool --help` and verifying output. Anything beyond that and I'd need to send a bill somewhere :)
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
dotnet tool install --global AzureSignTool
```

### Tool installation time in runtime

20-45 seconds

**Comment by al-cheb** [comment]
Hey @sudara.

Considering the fact that tool is pretty small and can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns
