### ISSUE TITLE
CI fails for precompiled headers in cmake

### ISSUE THREAD

**Issue by yperess** [actions/runner-images#6114]
### Description

If you add a project that uses:

```
target_precompiled_headers(...)
```

The build will fail with a MinGW error saying there's an invalid memory address access.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/meekrosoft/fff/runs/7927126835?check_suite_focus=true

### Is it regression?

I don't think so

### Expected behavior

This build should pass

### Actual behavior

Compilation of the precompiled header fails

### Repro steps

1. Create a new project that has a precompiled header
2. Add a source that assumes the header is included
3. Add the executable
4. Run this in the windows-latest CI

This can be seen in https://github.com/meekrosoft/fff/pull/113 where I had to add a special handler for `if(WIN32)` in the `test/CMakeLists.txt` file

**Comment by al-cheb** [comment]
Close as external - https://github.com/brechtsanders/winlibs_mingw/issues/97
