### ISSUE TITLE
/home/runner/work/_temp/4dbf8165-adae-46e1-b205-67956c159651.sh: line 1: sudo: command not found

### ISSUE THREAD

**Issue by Nefcanto** [actions/runner-images#6115]
### Description

I use `sudo` on `ubuntu-latest` to create top-level directories in my actions.

It was working fine for this public repository: https://github.com/SultanimMubin/Path

But now it fails with this message:

```
Run sudo mkdir /HolismHolding
  sudo mkdir /HolismHolding
  sudo chmod 777 /HolismHolding
  shell: /usr/bin/bash -e {0}
  env:
    PATH: ${PATH}:/HolismHolding/Commands
/home/runner/work/_temp/4dbf8165-adae-46e1-b[2](https://github.com/SultanimMubin/Path/runs/7930175034?check_suite_focus=true#step:2:2)0[5](https://github.com/SultanimMubin/Path/runs/7930175034?check_suite_focus=true#step:2:5)-[6](https://github.com/SultanimMubin/Path/runs/7930175034?check_suite_focus=true#step:2:6)[7](https://github.com/SultanimMubin/Path/runs/7930175034?check_suite_focus=true#step:2:8)956c159651.sh: line 1: sudo: command not found
Error: Process completed with exit code 127.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Environment: ubuntu-20.04
  Version: 20220[8](https://github.com/SultanimMubin/Path/runs/7930175034?check_suite_focus=true#step:1:9)14.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20220814.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220814.1
```

### Is it regression?

I don't know

### Expected behavior

sudo should work.

### Actual behavior

sudo: command not found

### Repro steps

1- Create a GitHub Action
2- Add a step to create a top-level directory with sudo: `sudo mkdir /SomeDir`

Or

1- See this workflow run => https://github.com/SultanimMubin/Path/runs/7930175034?check_suite_focus=true

**Comment by al-cheb** [comment]
Hey @Nefcanto.

The PATH doesn't expand and contains:
`${PATH}:/HolismHolding/Commands`

If you would like to add something to the PATH you should use - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path 
```

- run: |
          echo "/HolismHolding/Commands" >> $GITHUB_PATH
```

![image](https://user-images.githubusercontent.com/47745270/185746549-cfcb8a36-f365-43d4-b8a0-d0fd6587bec3.png)

**Comment by Nefcanto** [comment]
@al-cheb thank you so much. But that error was **WAY** unrelated to the real problem. How could I solve it? It's solved now.

**Comment by Lurtroxx** [comment]
So what was the solution @Nefcanto

**Comment by Nefcanto** [comment]
```
      - name: Add commands directory to PATH
        run: |
          echo "/HolismHolding/Commands" >> $GITHUB_PATH
```

@Lurtroxx this worked for me.
