### ISSUE TITLE
NUnit tests fail on windows-2019 after image version update to 20220814.1

### ISSUE THREAD

**Issue by vladbresan** [actions/runner-images#6123]
### Description

We are having some trouble with some unit tests failing after the windows-2019 image has been upgraded to 20220814.1 

We ran our pipeline without any issues on 20220801.1 on the same commit hash which is currently failing.

We have also tried to use the windows-2022 vmImage to run our build stage but to no avail. Is there anyone else experiencing this issue? 

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220814.1

### Is it regression?

20220801.1

### Expected behavior

Test to be successful after the image version has been bumped to 20220814.1

### Actual behavior

Some tests are failing due to unknow reasons at the moment.

### Repro steps

This issue is happening on a single project at the moment, not sure why this could happen.
We are using a template, so the steps taken by the build stage are the same across all our projects within azure devops

**Comment by vladbresan** [comment]
@mikhailkoliada unfortunately, this can be only reproduced on our project and I can't share details publicly. 

For reference, the unit tests are running successfully on developers' machines. Tested on latest version VS2019 and VS2022

**Comment by vladbresan** [comment]
So i created a VM and added that to a custom Agent Pool. Logged in through RDP and noticed the following when running our tests:
- CPU reaching 100% and throttling, thus making our tests unstable
- Windows Defender Advanced Threat Protection Service Executable (mssense.exe from my understanding) cruising at at 60-70% CPU usage

Do you have any suggestions regarding this issue besides trying to make our tests more efficient?

**Comment by erik-bershel** [comment]
@vladbresan please update status of issue. Do you have the same troubles on the latest release?

**Comment by vladbresan** [comment]
@erik-bershel we would have to revert to the problematic commit and test it out again. Since the test were failing, we ended up disabling them.
I will try to run a pipeline today and update you

**Comment by mikhailkoliada** [comment]
We are going to close the issue now, feel free to reach us if you have questions left.
