### ISSUE TITLE
.Net Framework 4.8.1 Build Fails

### ISSUE THREAD

**Issue by simonbaralos-codiance** [actions/runner-images#6124]
### Description

Visual Studio build task fails for .Net Framework target 4.8.1

I've set the image to Windows-latest and VS 2022 as the version.

##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1220,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.8.1 were not found. To resolve this

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20220816.1

### Is it regression?

No

### Expected behavior

Build Framework 4.8.1 projects.

### Actual behavior

Fails

### Repro steps

1. Create new .Net Framework Project
2. Configure Devops VS Build Step
3. Set Image: windows-latest
4. VisualStudioVersion="17.0"
5. Build fails with missing SDK

**Comment by al-cheb** [comment]
Hey @simonbaralos-codiance.
We will take a look at it.

**Comment by simonbaralos-codiance** [comment]
Great, thank you 🙂

**Comment by al-cheb** [comment]
@simonbaralos-codiance, we are planning to finish new image deployment by next Wed-Thu.

**Comment by al-cheb** [comment]
The new Windows2022 image with .Net 4.8.1 has been deployed.
