### ISSUE TITLE
`macos-11` and `macos-12` have unreliable build errors between re-runs of jobs

### ISSUE THREAD

**Issue by spencerdrak** [actions/runner-images#6129]
### Description

We are running a build which during setup runs `opam switch create 4.14.0`. This works fine on `macos-10.15` but doesn't work reliably on `macos-11` or `macos-12`. Sometimes it passes, sometimes it fails - when it fails, the error is as such:

```
# sh: /Users/runner/.opam/4.14.0/bin/ocamlc: cannot execute binary file
# Exception: Failure "Bad return from 'ocamlc -where'".
```

We understand you won't be able to assist with the specifics of that command or the specifics of our workflow - but the issue is that this sometimes passes and sometimes fails. Using the `Re-run Failed Jobs` or `Re-run All Jobs` button in the UI causes seemingly random failures or passes. Alternative, using the `Re-run All Jobs` button on a successful run will sometimes result in a failure. There seems to no difference between the logs (even with verbose logging enabled in our `opam` tooling and debug logging enabled on the GHA side) - we've diffed the logs side by side.

Is there any variability in the instance types that jobs can get assigned to? Is there any further debugging info that can be obtained from GHA runners? AFAIK there is no supported way to get something like ssh access to a runner to play around and see what's going wrong. We've dodged the issue for the time being by reverting back to `macos-10.15`, but I understand we don't have much time left on that image.

Thanks for your consideration!

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We've encountered the same issue in `macos-11`: 

```
Environment: macos-11
Version: 20220815.1
```
and on `macos-12`:

```
Environment: macos-12
Version: 20220815.1
```

### Is it regression?

yes - last worked on `macos-10.15`

### Expected behavior

The build either passes reliably, or fails reliably, with logging to support forming a hypothesis as to why it failed.

### Actual behavior

An error is sometimes thrown from this command, even after successive re-runs with no changes to workflow definition. These seem to fail or pass at random.

### Repro steps

Run the following steps in a `macos-11` or `macos-12` runner env. These steps are what we're running

```
brew update
brew install opam pkg-config coreutils pcre
opam init --no-setup --bare
opam switch create 4.14.0 -vvvvvvvvvv
```

We've found that the error noted above occurs about 50% of the time.

**Comment by mikhailkoliada** [comment]
@spencerdrak hello! Thanks, we'll take a look.

**Comment by mikhailkoliada** [comment]
@spencerdrak closing as external, I can reproduce this problem on my own macOS laptop and a clean macOS virtual machine too, please report to formulae maintainers directly. Feel free to reach us out if you think you have questions left.
