### ISSUE TITLE
Update/Add npm to >= 8.16.0

### ISSUE THREAD

**Issue by lopopolo** [actions/runner-images#6136]
### Tool name

npm

### Tool license

The Artistic License 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

8.16.0

### Brief description of tool

npm is the package manager for the node.js ecosystem.

There is a bug in npm 8.15.0 that prevents installation and execution of packages from non-npm registries when using `npx`:

- https://github.com/npm/cli/issues/5132

### URL for tool's homepage

https://docs.npmjs.com/cli/v8

### Provide a basic test case to validate the tool's functionality.

```bash
$ npx github:artichoke/clang-format --help
Usage: clang-format [options] [directory]

Node.js runner for LLVM clang-format

clang-format is a tool to format C code.

If no arguments are given, the runner formats the current directory recursively.
Any clang-format configuration present on the filesystem will be honored.

--check mode is suitable for CI. --check does not attempt to format and instead
exits with a non-zero status code if the source code on disk does not match the
enforced style.

Options:
  -V, --version  output the version number
  --check        Run in 'check' mode. Exit with a non-zero status code if any
                 formatting errors are found.
  -h, --help     display help for command
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
yes
```

### Are you willing to submit a PR?

no

**Comment by mikhailkoliada** [comment]
@lopopolo Hello!

We do not pre-install npm versions other than a version currently available with nodejs by default, you can use `actions/setup-node` to manage the node installation yourself (I see you already did :) )
