### ISSUE TITLE
Add Windows SDK 10.0.22621 to the 2019 image

### ISSUE THREAD

**Issue by mikeb-ah** [actions/runner-images#6137]
### Tool name

Windows SDK 10.0.22621

### Tool license

See SDK

### Add or update?

- [X] Add
- [ ] Update

### Desired version

10.0.22621

### Brief description of tool

Windows 11 SDK, latest version.

### URL for tool's homepage

https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

No - I've tried installing with Nuget and using the same packer-based approach as was taken for windows-2022, but with nuget it does not show as available in subsequent commands, and when running packer the test for the SDK fails.

**Comment by mikeb-ah** [comment]
I should note that the windows 2022 environment has other incompatibilities with the build I'm attempting to automate, so that's not an option in my case.

**Comment by al-cheb** [comment]
Hey @mikeb-ah.

https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
Starting with the Windows 11, version 22H2 release of the WDK and EWDK, the kits support:
- **Visual Studio 2022 exclusively**
- Building and testing kernel-mode drivers for x64 and Arm64
- Building and testing drivers for Windows 10, Windows Server 2016 and later client and server versions
- Side by side (SxS) support with previous WDK/EWDK

**Comment by mikeb-ah** [comment]
That is true for the Windows Driver Kit (WDK), but not for the Windows SDK, see here:
https://developercommunity.visualstudio.com/t/64-bit-EXEs-built-with-VS2019-crash-unde/1248753#TPIN-N10088359

**Comment by erik-bershel** [comment]
@mikeb-ah 
May I ask you to check the set of options for the requested SDK? Will the list of options specified in the pull request be sufficient for your application?
Mentioned PR is [here](https://github.com/actions/runner-images/pull/6148/files#diff-0bc9c7c16dcb9715baaa2770d73a8ca4958d598ceb8bdd405ad622262891f98a). String 49
Or you can provide an example of application.

**Comment by mikeb-ah** [comment]
> @mikeb-ah May I ask you to check the set of options for the requested SDK? Will the list of options specified in the pull request be sufficient for your application? Mentioned PR is [here](https://github.com/actions/runner-images/pull/6148/files#diff-0bc9c7c16dcb9715baaa2770d73a8ca4958d598ceb8bdd405ad622262891f98aR49). String 49 Or you can provide an example of application.

That looks good, thanks very much!
