### ISSUE TITLE
Update Android NDK to r25b LTS

### ISSUE THREAD

**Issue by Javernaut** [actions/runner-images#6141]
### Tool name

Android NDK

### Tool license

Same as before

### Add or update?

- [ ] Add
- [X] Update

### Desired version

25.1.8937393

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Will be deployed next week.

**Comment by mikhailkoliada** [comment]
Deployed
