### ISSUE TITLE
Playwright tests are not running in the latest image version(20220821.1) of "windows-latest" Microsoft hosted agent

### ISSUE THREAD

**Issue by dharanidhar-m** [actions/runner-images#6144]
### Description

Playwright tests stopped working in the latest image version of windows microsoft hosted agent. Can you please check and fix the issue.

MS Hosted Agent: "windows-latest"
Current image version: '20220821.1'

It used to work with earlier version.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

![image](https://user-images.githubusercontent.com/82205190/186739424-729303ba-6818-4b65-bda2-5f6bf5a3e1d1.png)

### Is it regression?

Yes

### Expected behavior

Playwright tests should work

### Actual behavior

Its unable to detect playwright tests

### Repro steps

Run playwright tests within Microsoft hosted agents

**Comment by mikhailkoliada** [comment]
@dharanidhar-m hello!

Could you please provide us with a pipeline with possible reprosteps?

**Comment by dharanidhar-m** [comment]
Hi @mikhailkoliada  When we try to run playwright test cases its throwing no tests found error, 
![image](https://user-images.githubusercontent.com/82205190/186877125-3bf367f8-f613-4558-beec-98b4338388fb.png)

**Comment by dharanidhar-m** [comment]
We are blocked here, Can you please provide the solution if any

**Comment by al-cheb** [comment]
@dharanidhar-m, I can't reproduce the issue from my side using repo - https://github.com/fearlessly-dev/30daysofSWA-testing:

```
steps:
- powershell: 'npx playwright test'
  displayName: 'Run Playwright tests'
```

![image](https://user-images.githubusercontent.com/47745270/187188150-a3adcc0f-03e3-44e5-a0b4-173e4ad02d65.png)

**Comment by al-cheb** [comment]
@dharanidhar-m, Any updates?

**Comment by al-cheb** [comment]
I am going to close the thread. Feel free to open it if you have any concerns.
