### ISSUE TITLE
macOS 12 Slow

### ISSUE THREAD

**Issue by kevinzakka** [actions/runner-images#6147]
### Description

I've noticed that macOS 12 unit tests end up taking 2 to 3x longer than their Ubuntu / Windows counterpart, for example see [here](https://github.com/deepmind/mujoco/runs/8031509285?check_suite_focus=true). Wondering if this is a common issue and how it can be addressed!

Cheers

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/deepmind/mujoco/runs/8031510179?check_suite_focus=true

### Is it regression?

No

### Expected behavior

Roughly same speed as ubuntu / windows images.

### Actual behavior

2 to 3x slower.

### Repro steps

See above.

**Comment by mikhailkoliada** [comment]
@kevinzakka Hello!

This is the hardware limitation, we are working on improving it but have no any ETA at the moment.
