### ISSUE TITLE
libgd-dev cannot be installed

### ISSUE THREAD

**Issue by shlomif** [actions/runner-images#6153]
This is happening again as of yesterday, with the GHA config not having changed at all (https://github.com/PDLPorters/pdl/runs/7473608493?check_suite_focus=true):

```
  The following packages have unmet dependencies:
   libgd-dev : Depends: libgd3 (= 2.2.5-5.2ubuntu2.1) but 2.3.3-5+ubuntu20.04.1+deb.sury.org+1 is to be installed
  E: Unable to correct problems, you have held broken packages.
```

_Originally posted by @mohawk2 in https://github.com/actions/runner-images/issues/2139#issuecomment-1192919820_

**Comment by shlomif** [comment]
see https://github.com/shlomif/shlomi-fish-homepage/runs/8050079666?check_suite_focus=true too

**Comment by al-cheb** [comment]
Hey @shlomif. 
You should remove the nginx first as a dependency of ligdb3:

`-   run: sudo apt-get remove nginx libgd3`
