### ISSUE TITLE
`Segmentation fault` on Windows i686

### ISSUE THREAD

**Issue by liby** [actions/runner-images#6154]
### Description

Starting with `runner version: '2.295.0'` and repeatedly encountering `Segmentation fault`.

> D:\a\_temp\655f499a-168c-4478-b6d4-249d28b527fd.sh: line 2:  1158 [Segmentation fault](https://github.com/liby/hexo-util-rs/runs/8051629074?check_suite_focus=true#:~:text=line%202%3A%20%201158-,Segmentation%20fault,-yarn%20test)      yarn test
> Error: Process completed with exit code 139.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Current runner version: '2.296.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20[3](https://github.com/liby/hexo-util-rs/runs/8051629074?check_suite_focus=true#step:1:3)[4](https://github.com/liby/hexo-util-rs/runs/8051629074?check_suite_focus=true#step:1:4)8
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20220[8](https://github.com/liby/hexo-util-rs/runs/8051629074?check_suite_focus=true#step:1:9)21.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20220821.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20220821.1
Runner Image Provisioner
  1.0.0.0-main-202208[12](https://github.com/liby/hexo-util-rs/runs/8051629074?check_suite_focus=true#step:1:14)-3
```

### Is it regression?

https://github.com/liby/hexo-util-rs/runs/8004703485?check_suite_focus=true

### Expected behavior

Process is completed normally

### Actual behavior

Failed due to segmentation fault

### Repro steps

https://github.com/liby/hexo-util-rs/runs/8051629074?check_suite_focus=true

**Comment by al-cheb** [comment]
@liby, hey. Could you please try running a build without cache packages?

**Comment by igorboskovic3** [comment]
Hi @liby , thank you for reporting this one, we will take a look.

**Comment by liby** [comment]
> @liby, hey. Could you please try running a build without cache packages?

[Same error](https://github.com/liby/hexo-util-rs/runs/8067918444?check_suite_focus=true)

**Comment by al-cheb** [comment]
@liby, I tried the last successful `3265db583bfe729b977fba8ba5add25e2884c2e2` commit and it is working:

![image](https://user-images.githubusercontent.com/47745270/187182991-bdeb5627-3cc3-4cf4-b60d-e14c44e86e6b.png)

**Comment by liby** [comment]
> it is working

It should be caused by the [`workerThreads` option](https://github.com/actions/runner-images/issues/6154#:~:text=3265db583bfe729b977fba8ba5add25e2884c2e2%20commit%20and-,it%20is%20working,-%3A), but it is not clear why.

**Comment by al-cheb** [comment]
Because it worked before updating I am planning to close as external issue.

**Comment by liby** [comment]
> Because it worked before updating I am planning to close as external issue.

Can't agree, because with the `workerThreads` option enabled, only `Windows Server 2022` is wrong, so we still need to look at why.
