### ISSUE TITLE
Update Microsoft Graph module to 1.11.1

### ISSUE THREAD

**Issue by nes-nagashin** [actions/runner-images#6155]
### Tool name

Microsoft.Graph

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.11.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by miketimofeev** [comment]
Hi @nes-nagashin!
The new version will be deployed this week. We will let you know once the deployment is finished.

**Comment by al-cheb** [comment]
The new Ubuntu images with Microsoft.Graph | 1.11.1 have been deployed.
