### ISSUE TITLE
Add xcparse to macOS toolset

### ISSUE THREAD

**Issue by petermolnar-dev** [actions/runner-images#6161]
### Tool name

xcparse

### Tool license

MIT License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.3.0

### Brief description of tool

Xcparse is a tool to extract the Xcode generated Unit test coverage and screenshots during the Xcode test run. It enables to pass the code coverage easier to other static code analysers such as Sonarqube.  

### URL for tool's homepage

https://github.com/ChargePoint/xcparse

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
@petermolnar-dev Hello, we will decide on adding the tool to the images and get back to you.

**Comment by ddobranic** [comment]
Hello @petermolnar-dev, thank you for your proposal for adding `xcparse` to macOS toolset. 
Our general advice is implementing installation logic on task side even if if tool is pre-installed on Hosted images.
Tool is easy and quick to install in runtime, so we recommend that approach in this case.
