### ISSUE TITLE
An error occurred while provisioning resources (Error Type: Failure).

### ISSUE THREAD

**Issue by joaopereiradti** [actions/runner-images#6164]
### Description

I am getting this error when I run my pipe in macos-12

##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
Pool: [Azure Pipelines](https://dev.azure.com/dti-bbi/3b1bf90f-799d-44dd-b332-2dc53c828079/_settings/agentqueues?poolId=&queueId=9)
Image: macos-12

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

yes

### Expected behavior

run my job

### Actual behavior

error when initialize the job

### Repro steps

Run my pipeline
Error is triggered

**Comment by igorboskovic3** [comment]
Hi @joaopereiradti we will take a look. Can you provide repro steps? Thank you

**Comment by joaopereiradti** [comment]
> Hi @joaopereiradti we will take a look. Can you provide repro steps? Thank you

This occurs at job startup. On Friday morning it was working normally...

<img width="985" alt="Captura de Tela 2022-08-29 às 12 33 59" src="https://user-images.githubusercontent.com/43824992/187238735-e14e7bbd-7f9a-463c-bbbb-89992a9b1138.png">

**Comment by joaopereiradti** [comment]
@igorboskovic3 

Adding more infos:

`
ContinueOnError: False
TimeoutInMinutes: 60
CancelTimeoutInMinutes: 5
Expand:
  MaxConcurrency: 0
  ########## System Pipeline Decorator(s) ##########

  Begin evaluating template 'system-pre-steps.yml'
Evaluating: eq('true', variables['system.debugContext'])
Expanded: eq('true', Null)
Result: False
Evaluating: resources['repositories']['self']
Expanded: Object
Result: True
Evaluating: not(containsValue(job['steps']['*']['task']['id'], '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Expanded: not(containsValue(Object, '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Result: True
Evaluating: resources['repositories']['self']['checkoutOptions']
Result: Object
Finished evaluating template 'system-pre-steps.yml'
********************************************************************************
Template and static variable resolution complete. Final runtime YAML document:
steps:
- task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
  inputs:
    repository: self


  MaxConcurrency: 0`

**Comment by igorboskovic3** [comment]
@joaopereiradti Hi, can you provide us with successful and unsuccessful build links?

**Comment by joaopereiradti** [comment]
Hello @igorboskovic3, 
unfortunately this project is not public :/
Is there anything I can help you with?

**Comment by al-cheb** [comment]
@joaopereiradti, please send me links to the failed build al-cheb at github.com.

**Comment by al-cheb** [comment]
@joaopereiradti, any updates?

**Comment by al-cheb** [comment]
I am planning to close the thread. Feel free to open it if you have any concerns.

**Comment by joaopereiradti** [comment]
Hello! 
Sorry for the delay, but this is not working yet...
I create one ticket here: https://developercommunity.visualstudio.com/t/An-error-occurred-while-provisioning-res/10133669
