### ISSUE TITLE
Update/Add git-crypt

### ISSUE THREAD

**Issue by theodrim** [actions/runner-images#6171]
### Tool name

git-crypt

### Tool license

GNU General Public License v3.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.7.0

### Approximate size

206016 bytes

### Transparent file encryption in git.

git-crypt enables transparent encryption and decryption of files in a git repository. Files which you choose to protect are encrypted when committed, and decrypted when checked out. git-crypt lets you freely share a repository containing a mix of public and private content. git-crypt gracefully degrades, so developers without the secret key can still clone and commit to a repository with encrypted files. This lets you store your secret material (such as keys or passwords) in the same repository as your code, without requiring you to lock down your entire repository.

### URL for tool's homepage

https://github.com/AGWA/git-crypt

### Provide a basic test case to validate the tool's functionality.

```bash
$ cd `mktemp -d`
$ git init
$ echo "This is some text" > file.txt
$ git add file.txt
$ git commit -m "Initial commit"
$ git-crypt init
$ git-crypt export-key /tmp/test-key
$ echo "*secret.yml filter=git-crypt diff=git-crypt" > .gitattributes
$ git add .gitattributes
$ git commit -m "Tell git-crypt to encrypt *secret.yml"
$ echo -e "---\nsecret:password" > very-secret.yml
$ git add very-secret.yml
$ git commit -m "Commit secret"
$ file very-secret.yml
very-secret.yml: ASCII text
$ git-crypt lock
$ file very-secret.yml
very-secret.yml: data
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt-get -qq update; apt-get -y install git-crypt

Please do note that this will install version 0.6.0, which is still totally acceptable - but not the latest stable.
```

### Tool installation time in runtime

from 9 to 50 seconds (depending on the runner I guess)

### Are you willing to submit a PR?

Sure

**Comment by mikhailkoliada** [comment]
@theodrim Hello!

We will decide on adding the tool to the images and get back to you.

**Comment by ddobranic** [comment]
Hello @theodrim, thank you for your proposal. Tool is small and easy to install in runtime. We recommend that approach.
