### ISSUE TITLE
Xcode 12.5.1 is not available in macos-11 image

### ISSUE THREAD

**Issue by polqf** [actions/runner-images#6172]
### Description

Up until some time from now, `macos-11` was having Xcode 12.5.1 installed. This is also stated in the [Xcode section](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#xcode) in the README.

But some days ago we started seeing this error message:
`Cannot find an installed Xcode satisfying '~> 12.5.1'`

After adding some logs, I can see that there are only 2 Xcode available, out of the 6 that are listed in the README
```
Run mdfind "kMDItemCFBundleIdentifier = 'com.apple.dt.Xcode'"
/Applications/Xcode_13.2.1.app
/Applications/Xcode_13.0.app
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.296.0

### Is it regression?

Yes

### Expected behavior

All the Xcode versions listed in the README should be available in the image

### Actual behavior

Only Xcode 13.2.1 and 13.0 are available

### Repro steps

Just try to use 12.5.1 in macos-11

**Comment by al-cheb** [comment]
@polqf, hey.

It's work as expected. To set up Xcode version I use the [ctions/setup-xcode-version](https://github.com/marketplace/actions/setup-xcode-version) task:

![image](https://user-images.githubusercontent.com/47745270/187679599-8eb7f8f0-796f-4f04-8587-5f777d97235c.png)

**Comment by al-cheb** [comment]
close as external https://github.com/xcpretty/xcode-install/issues/204
