### ISSUE TITLE
Support Windows ARM64 build images

### ISSUE THREAD

**Issue by dennisameling** [actions/runner-images#6175]
### Tool name

ARM64 Windows

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Windows 11 ARM64

### Brief description of tool

Same as https://github.com/actions/runner-images/issues/5631, but this request is for Windows ARM64 rather than Linux ARM64.

Now that [Azure ARM64 VMs](https://azure.microsoft.com/en-us/blog/azure-virtual-machines-with-ampere-altra-arm-based-processors-generally-available/) are generally available for both Linux and Windows, please add Hosted Runners for Windows ARM64.

### URL for tool's homepage

https://azure.microsoft.com/en-us/blog/azure-virtual-machines-with-ampere-altra-arm-based-processors-generally-available/

### Provide a basic test case to validate the tool's functionality.

Visual Studio 2022 [will have a native ARM64 version](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-3-is-now-available/) starting with version 17.4:

> We are also releasing the first preview of our next release, Visual Studio 2022 17.4 Preview 1. Version 17.4 will be the first version of Visual Studio generally available as a native Arm64 application.

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes, if you can make the VMs available, I'm happy to help with the images

**Comment by igorboskovic3** [comment]
Hi @dennisameling we will take a look and get back to you.

**Comment by illfygli** [comment]
I would find this useful too.
I would like to make Windows-on-ARM builds of [Joplin](https://github.com/laurent22/joplin) available.

**Comment by ddobranic** [comment]
We plan to add this feature in the future but it has not been prioritized.

**Comment by dennisameling** [comment]
For anyone interested: [here's a repo with an Azure Resource Manager template](https://github.com/dennisameling/azure-arm64-templates). It includes a post-deployment script that installs Git for Windows and the GitHub Actions runner, so you can set up your own GitHub Actions runners for this platform until they add official support.
