### ISSUE TITLE
PostgreSQL regression on MacOS

### ISSUE THREAD

**Issue by VadVergasov** [actions/runner-images#6176]
### Description

Something is wrong with the PostgreSQL location and CMake couldn't find it currently. I've tried to ensure, that PostgreSQL has been installed with a brew. The issue seems to be similar to https://github.com/actions/runner-images/issues/6173 but creating symlink links have no effect for me.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/Plnguins/CRM/actions/runs/2970770855

### Is it regression?

https://github.com/Plnguins/CRM/actions/runs/2957187399

### Expected behavior

CMake successfully configures.

### Actual behavior

CMake couldn't find PostgreSQL locationthe 

### Repro steps

Use CMake file with PostgreSQL dependency

**Comment by al-cheb** [comment]
Hello @VadVergasov. 
Could you please try using PostgreSQL_LIBRARY option `-DPostgreSQL_LIBRARY="$(pg_config --libdir)"` ?

**Comment by VadVergasov** [comment]
[Now](https://github.com/Plnguins/CRM/runs/8161152427?check_suite_focus=true) build fails because libpq include can't be found.

**Comment by al-cheb** [comment]
@VadVergasov, check this:
`-DPostgreSQL_INCLUDE_DIR="$(pg_config --includedir)" -DPostgreSQL_LIBRARY="$(pg_config --libdir)"`

**Comment by VadVergasov** [comment]
[Already](https://github.com/Plnguins/CRM/runs/8161228374?check_suite_focus=true) checked this and also can't be build successfully.

**Comment by al-cheb** [comment]
@VadVergasov, try libpq:
`-DPostgreSQL_INCLUDE_DIR="/usr/local/opt/libpq/include" -DPostgreSQL_LIBRARY="/usr/local/opt/libpq/lib/libpq.dylib"`

**Comment by VadVergasov** [comment]
@al-cheb also nothing changed. Same error as in the latest run

**Comment by al-cheb** [comment]
@VadVergasov, add this step before configure cmake step:
```
     - name: Create symlinks
       run: |
          sudo ln -s $(pg_config --libdir)/* /usr/local/lib/ || true
          sudo ln -s $(pg_config --includedir)/* /usr/local/include/ 
```

![image](https://user-images.githubusercontent.com/47745270/188284369-be1b6917-b348-4e31-b510-99e5ea7a654c.png)

**Comment by VadVergasov** [comment]
@al-cheb thanks, that solved the issue
