### ISSUE TITLE
whoami and others coreutils commands are failing

### ISSUE THREAD

**Issue by sylvestre** [actions/runner-images#6177]
### Description

Currently, if you run one of the GNU/Coreutils relative to user/group on one of the Ubuntu VM in github action, it will fail with:
```
/usr/bin/whoami: cannot find name for user ID 1001
```

The /etc/passwd & /etc/group seem to be incorrect:

```
# group
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
systemd-journal:x:101:
systemd-timesync:x:102:
systemd-network:x:103:
systemd-resolve:x:104:
systemd-bus-proxy:x:105:
```

```
# passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-timesync:x:100:102:systemd Time Synchronization,,,:/run/systemd:/bin/false
systemd-network:x:101:103:systemd Network Management,,,:/run/systemd/netif:/bin/false
systemd-resolve:x:102:104:systemd Resolver,,,:/run/systemd/resolve:/bin/false
systemd-bus-proxy:x:103:105:systemd Bus Proxy,,,:/run/systemd:/bin/false
_apt:x:104:65534::/nonexistent:/bin/false
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://pipelines.actions.githubusercontent.com/serviceHosts/91055393-6e6f-4662-ba97-3acee74a8c7c/_apis/pipelines/1/runs/16798/signedlogcontent/154?urlExpires=2022-09-03T21%3A19%3A51.2309771Z&urlSigningMethod=HMACV1&urlSignature=6WXNn796LL%2FnQo6%2BmqEI%2FKF5YJG%2F6RD6dbiPqirE894%3D

### Is it regression?

Yes

### Expected behavior

```
$ /usr/bin/whoami  
<user_name>
```

### Actual behavior

```
$ /usr/bin/whoami  
/usr/bin/whoami: cannot find name for user ID 1001
```

### Repro steps

run /usr/bin/whoami in an ubuntu VM in github action

**Comment by al-cheb** [comment]
Hey @sylvestre.
I can't reproduce the issue from my side.

```
- run: |
        id -a
        /usr/bin/whoami
```

![image](https://user-images.githubusercontent.com/47745270/188316163-a09f0385-4e75-420f-9835-2025186b0e48.png)

**Comment by sylvestre** [comment]
maybe it is a problem between the chair and the keyboard ;) I will try to create a small test case.

The passwd & group files look unusual here https://github.com/uutils/coreutils/issues/3890#issuecomment-1236187636
uid=1001 & gid=121 but no references in /etc/passwd or /etc/group

**Comment by al-cheb** [comment]
Could you please attach a link to the failed build?
```
     - run: |
        getent passwd 1001
        getent group 121
     - run: |
        mkdir -p /tmp/.tmpOpamJH/dir
        mkdir -p /tmp/.tmpOpamJH/dir/subdir
        touch /tmp/.tmpOpamJH/dir/subdir/file
        cd /tmp/.tmpOpamJH
        sudo chgrp -R 121 dir
        ls -la dir
```

![image](https://user-images.githubusercontent.com/47745270/188322742-e8475819-bb60-4ba8-8c32-74207fdf99d9.png)

**Comment by sylvestre** [comment]
Sure, here it is:
https://github.com/sylvestre/coreutils/runs/8171972246?check_suite_focus=true
https://pipelines.actions.githubusercontent.com/serviceHosts/91f3338c-0673-45e0-bd1a-bef98f89b878/_apis/pipelines/1/runs/1741/signedlogcontent/165?urlExpires=2022-09-04T16%3A18%3A35.9690849Z&urlSigningMethod=HMACV1&urlSignature=lgqDvZrYfpj5%2F4%2F1u9TtvX8Bo%2BhBpCaHjmUnixDAJEM%3D

**Comment by al-cheb** [comment]
As I can see you are running tests in docker containers( https://github.com/cross-rs/cross - One of these container engines is required. If both are installed, cross will default to docker.). It explains why passwd & group files are different :
![image](https://user-images.githubusercontent.com/47745270/188331731-0096b735-36e7-492c-b5a4-505bf63186ee.png)

For e.g.:
```
$ docker run -it --rm --user 1000:1000 ubuntu bash
groups: cannot find name for group ID 1000
I have no name!@3ffe1704fc34:/$ whoami
whoami: cannot find name for user ID 1000
```

I'm not familiar with your build system, but as a workaround you can mount /etc/passwd&/etc/group:

```
env:
  DOCKER_OPTS: '--volume /etc/passwd:/etc/passwd --volume /etc/group:/etc/group'
```

![image](https://user-images.githubusercontent.com/47745270/188331918-474ac437-e7e0-4b48-bfd4-1b7021ae7cbe.png)

**Comment by sylvestre** [comment]
@al-cheb many thanks, it fixes the issue:
https://github.com/uutils/coreutils/pull/3902
I am curious why it regressed ?!

**Comment by sylvestre** [comment]
sorry for the noise
