### ISSUE TITLE
Update skopeo

### ISSUE THREAD

**Issue by emo-slido** [actions/runner-images#6180]
### Tool name

skopeo

### Tool license

Apache License Version 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

v1.9.2 (latest) or at least v1.5.1 or greater

### URL for tool's homepage

https://github.com/containers/skopeo

### Provide a basic test case to validate the tool's functionality.

```bash
skopeo inspect --no-tags docker://docker.io/busybox:latest
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
I suppose as it is an upgrade to an existing tool.
```

### Are you willing to submit a PR?

Yes, if you're so kind to point me to the build instructions

**Comment by miketimofeev** [comment]
@emo-slido I'm afraid we don't control the upstream repo updates. The new version of skopeo will be delivered right after those repos (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable for Ubuntu 18&20 and the official Ubuntu repo for Ubuntu22) are updated.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by al-cheb** [comment]
As a workaround you can install skopeo in runtime:


```
- run: |
          sudo apt purge buildah golang-github-containers-common podman skopeo
          sudo apt autoremove --purge
- run: |
          REPO_URL="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable"
          source /etc/os-release
          sudo sh -c "echo 'deb ${REPO_URL}/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
          sudo wget -qnv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
          sudo apt-key add Release.key
          sudo apt-get update
- run: |
          sudo apt-get install skopeo
```

![image](https://user-images.githubusercontent.com/47745270/188400564-a98702a7-3264-46a2-bb43-aea630e0d0fe.png)
