### ISSUE TITLE
[Windows] Docker EE will be replaced with Docker CE / Moby on September, 19

### ISSUE THREAD

**Issue by miketimofeev** [actions/runner-images#6181]
### Breaking changes

Docker EE will be replaced with Docker CE / Moby

### Target date

September, 19. The propagation will take 2-3 days.

### The motivation for the changes

Support for DockerMsftProvider ends at the end of September and will be fully transferred to Mirantis. The alternative is Docker CE / Moby

### Possible impact

If your builds depend on Docker EE-specific functionality they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

n\a

**Comment by mmckechney** [comment]
This seems to have caused an unexpected breaking change. When running an Azure DevOps Windows Container build, it fails at the login for Azure Container Registry with DOCKER_COMMAND_ERROR suggesting that the Docker engine is not running on the worker. I wouldn't have expected this to happen with this update. Can this be investigated please?
![B3503dff338d54526b966bfd84babd71d637994564999694089_azdo_docker_login_issue](https://user-images.githubusercontent.com/7117089/191874792-062c46c3-0d01-4343-a7b6-1612dfcad9b8.png)

**Comment by pfrcks** [comment]
@miketimofeev  I am seeing the same issue as @mmckechney

**Comment by yew** [comment]
@mmckechney, @pfrcks, add this line before `az acr login` could workaround the issue.
`New-Item -ItemType SymbolicLink -Path "C:\Windows\SysWOW64\docker.exe" -Target "C:\Windows\System32\docker.exe"`

**Comment by miketimofeev** [comment]
The changes are now deployed.
@pfrcks @mmckechney @yew sorry for the inconvenience, this will be fixed next week, related pr is https://github.com/actions/runner-images/pull/6287

**Comment by mmckechney** [comment]
@miketimofeev  - can you confirm that this change has been propagated to all Windows runners in all regions?

**Comment by miketimofeev** [comment]
@mmckechney should be. If you see any issues please let us know
