### ISSUE TITLE
[Ubuntu] g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)

### ISSUE THREAD

**Issue by mai-nakagawa** [actions/runner-images#6185]
### Description

The latest `ubuntu-latest` or `ubuntu-20.04` version `2.296.0` and `2.296.1` fails to run `poetry install` (`poetry` is a Python's package manager) with the following error log:
https://github.com/mai-nakagawa/test-runner-images/runs/8200561159?check_suite_focus=true
> g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)

The workaround is to add `sudo apt install gnome-keyring` beforehand:
https://github.com/mai-nakagawa/test-runner-images/runs/8200631090?check_suite_focus=true

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/mai-nakagawa/test-runner-images/runs/8200561159?check_suite_focus=true

### Is it regression?

Yes, the issue didn't persist w/ `2.295.0`

### Expected behavior

poetry install succeeds

### Actual behavior

poetry install fails with:
```
g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
```

### Repro steps

1. Fork https://github.com/mai-nakagawa/test-runner-images
2. Remove [this line](https://github.com/mai-nakagawa/test-runner-images/blob/main/.github/workflows/poetry_install.yaml#L8)
3. Run the CI and you'll see the error
4. Restore the line you removed in the 2nd step
5. Run the CI and you won't see the error

**Comment by al-cheb** [comment]
Hey @mai-nakagawa.
We will take a look at it.

**Comment by al-cheb** [comment]
@mai-nakagawa, I have found out a couple of relative issues: https://github.com/python-poetry/poetry/issues/2692 https://github.com/python-poetry/poetry/issues/6277 https://github.com/pypa/pip/issues/6773

```
env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
```

![image](https://user-images.githubusercontent.com/47745270/188571802-497fe93d-b332-4d93-92be-1cb32a0cbfac.png)

**Comment by al-cheb** [comment]
I am planning to close as external. Feel free to open it if you have any concerns.

**Comment by mai-nakagawa** [comment]
Thanks @al-cheb for your quick investigation. Understood the root cause and the solution!

**Comment by Ramon5** [comment]
> @mai-nakagawa, I have found out a couple of relative issues: [python-poetry/poetry#2692](https://github.com/python-poetry/poetry/issues/2692) [python-poetry/poetry#6277](https://github.com/python-poetry/poetry/issues/6277) [pypa/pip#6773](https://github.com/pypa/pip/issues/6773)
> 
> ```
> env:
>   PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
> ```
> 
> ![image](https://user-images.githubusercontent.com/47745270/188571802-497fe93d-b332-4d93-92be-1cb32a0cbfac.png)

thks man, works for me!
