### ISSUE TITLE
Add xcbeautify to macOS image

### ISSUE THREAD

**Issue by knox** [actions/runner-images#6198]
### Tool name

xcbeautify

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.13.0 / latest

### Brief description of tool

It's recommended to use [xcbeautify](https://github.com/tuist/xcbeautify) for xcodebuild output formatting. This has several advantages e.g. it supports Xcode's new build system and it's faster and more. Refer to [fastlane docs](https://docs.fastlane.tools/best-practices/xcodebuild-formatters/) for more details.

### URL for tool's homepage

https://github.com/tuist/xcbeautify

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
$ brew install xcbeautify
```

### Tool installation time in runtime

few seconds

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/runner-images/issues/1665
