### ISSUE TITLE
cl.exe path is not enviornment variables on Windows

### ISSUE THREAD

**Issue by Journeyman-dev** [actions/runner-images#6205]
### Description

The path to cl.exe is not in the enviornment variables on Windows. This makes it hard to use cl.exe to build C++ binaries. It used to be possible to set the enviornment variable yourself, but the features to do so have been depreciated:

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

NA

### Is it regression?

no

### Expected behavior

cl.exe is in the PATH environment variable.

### Actual behavior

cl.exe is not in the PATH enviornment variable.

### Repro steps

This is one way to find errors caused by this:
(in Windows runners only)
1. Set CC and CXX env variables to cl
2. Install ninja with `choco install` bash command
3. Build a binary using `cmake -S . -B ./build/ -G Ninja`
4. The build fails saying cl.exe cannot be found.

**Comment by al-cheb** [comment]
Hey @Journeyman-dev.
We don't have plans to cl.exe to the PATH. If you need to create an env variable use notation - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

`echo "{environment_variable_name}={value}" >> $GITHUB_ENV`

**Comment by Journeyman-dev** [comment]
> Hey @Journeyman-dev. We don't have any plans to add cl.exe to the PATH. If you need to create an env variable use notation - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
> 
> `echo "{environment_variable_name}={value}" >> $GITHUB_ENV`

I think you meant

`echo "{path}" >> $GITHUB_PATH`
