### ISSUE TITLE
Update/Add ImageMagick

### ISSUE THREAD

**Issue by Kicer86** [actions/runner-images#6207]
### Tool name

ImageMagick

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

7.1.0

### Approximate size

131MB

### Brief description of tool

CLI tool for image maniplation/conversion etc.

### URL for tool's homepage

https://imagemagick.org/script/index.php

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by TAxCOmax** [comment]
I can fix it smoothly

**Comment by ddobranic** [comment]
hi, @Kicer86! we will add ImageMagic to Windows images. new images will be released next week. thank you!

**Comment by erik-bershel** [comment]
@Kicer86 Windows images have been successfully generated! You can use the new tool. Feel free to contact us if something goes wrong, or if you have new suggestions or questions.
