### ISSUE TITLE
Unable to build in Azure Devops pipeline using agent specification windows-2019, before the code was building fine using agent VS2017-win2016

### ISSUE THREAD

**Issue by ShipraRay150** [actions/runner-images#6208]
### Description

Unable to build in Azure Devops pipeline using agent specification windows-2019, before the code was building fine using agent VS2017-win2016(which is decommissioned now)

My VS .net solution is building fine using VS2019 in my local machine but it fails in Azure Devops pipeline using windows-2019 agent.
In my local i had to add one environment variable :
MSBuild with below path
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin

The solution in pipeline was building fine when agent specification used wasVS2017-win2016(which is decommissioned now).

Please help on this.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

As this is Company's build i cant share in public.

### Is it regression?

yes local development 

### Expected behavior

The Azure devops pipeline build should be successful using agent-specification windows-2019

### Actual behavior

Unable to build in Azure Devops pipeline using agent specification windows-2019, before the code was building fine using agent VS2017-win2016

### Repro steps

Unable to build in Azure Devops pipeline using agent specification windows-2019, before the code was building fine using agent VS2017-win2016(which is decommissioned now)

My VS .net solution is building fine using VS2019 in my local machine but it fails in Azure Devops pipeline using windows-2019 agent.
In my local i had to add one environment variable :
MSBuild with below path
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin

The solution in pipeline was building fine when agent specification used wasVS2017-win2016(which is decommissioned now).

Please help on this.

**Comment by al-cheb** [comment]
Hey @ShipraRay150.
Please add minimal repro steps with repo how to reproduce the issue.

**Comment by ShipraRay150** [comment]
Sorry i cannot share the repo as it is a organizations so cant share in public.
Issue:
In Azure devops pipeline my .Net framework 4.6 toolversion = 14 was building fine when agent specification used VS2017-win 2016(which is deprecated now). My organization solution is using Fake library to build the solution

But when agent specification used windows-2019 , build is failing at soln.fsx(Fake build script).
(After analyzing the fake build script found 'Fake.DotNet.MSBuild.run' not able to pick the 2019 msbuild) which was completely working fine when agent specification used VS2017-win 2016.
Please help!

**Comment by ShipraRay150** [comment]
I am not able to check the vs2017-win2016(i donot see the link is visible to check software in msdn as this is deprecated) software links to validate which software is missing that needs to be installed in windows 2019

**Comment by miketimofeev** [comment]
@ShipraRay150 the latest windows-2016 readme is available by this link, you can compare the difference https://github.com/actions/runner-images/blob/493f3c3ee19fc6f2f5456b1f8563f77f0096c3e1/images/win/Windows2016-Readme.md

**Comment by ShipraRay150** [comment]
In my local i am able to build the solution but in Azure Devops Pipeline it is failing.

In my local i have VS2019, but in environment variable i have added:
MSBuild:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin

**Comment by ShipraRay150** [comment]
Please help on this!

**Comment by ShipraRay150** [comment]
@miketimofeev @al-cheb Any suggestions on this issue?

**Comment by al-cheb** [comment]
> @miketimofeev @al-cheb Any suggestions on this issue?

We can't investigate without repro steps.

**Comment by ShipraRay150** [comment]
Reproducing steps:

1.In Azure devops pipeline my .Net framework 4.6 toolversion = 14 was building fine when agent specification used VS2017-win 2016(which is deprecated now). My organization solution is using Fake library to build the solution

2.But when agent specification used windows-2019 , build is failing at soln.fsx(Fake build script).
(After analyzing the fake build script found 'Fake.DotNet.MSBuild.run' not able to pick the 2019 msbuild) which was completely working fine when agent specification used VS2017-win 2016.

**Comment by ShipraRay150** [comment]
@al-cheb @miketimofeev

Please help on this.

**Comment by al-cheb** [comment]
@ShipraRay150, try to add a step:

![image](https://user-images.githubusercontent.com/47745270/190348815-2bcc3414-d5f8-4370-8453-54654d0a1828.png)


```
steps:
- task: BatchScript@1
  displayName: 'Run script C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
    arguments: x64
    modifyEnvironment: true
```

**Comment by ShipraRay150** [comment]
@al-cheb 
I have one task to execute the Fake build script.

Do i need to add this Batch script before the Fake build script task ?

**Comment by al-cheb** [comment]
@ShipraRay150, before the Fake build task.

**Comment by ShipraRay150** [comment]
@al-cheb

Tried but this didnot worked.

MSBuild Path taken: c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe

**Comment by al-cheb** [comment]
@ShipraRay150, please attach build logs.

**Comment by ShipraRay150** [comment]
@al-cheb

I need to modify the fakebuild.fsx script to get the msbuildpath to C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin

Can you please help on this ?
What script modification i need to do?
I tried below but didnot worked:

let toolsVersion = "16.0"
let msBuildPath ="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"

let setParams defaults =
        { defaults with
            Verbosity = Some(Quiet)
            ToolsVersion = Some(toolsVersion)
            ToolPath = msBuildPath
            Targets = ["Build"]
            Properties =
                [
                    "Optimize", "True"
                    "DebugSymbols", "True"
                    "Configuration", buildMode
                ]
         }

**Comment by al-cheb** [comment]
ToolPath should be an exe file, like:
let msBuildPath ="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin\MSBuild.exe"

**Comment by ShipraRay150** [comment]
@al-cheb 
Below is the azure build logs:

2022-09-15T08:57:40.1450368Z ##[command]D:\a\1\s\FAKE\tools\fake.exe "D:\a\1\s\my.fsx" buildcode -fa my.fsx 2021.9.1555277.1 --removeLegacyFakeWarning
2022-09-15T08:57:53.2902202Z targets...
2022-09-15T08:57:53.4913155Z run buildcode
2022-09-15T08:57:53.4913961Z Building project with version: 2021.9.1555277.1
2022-09-15T08:57:53.5010082Z Shortened DependencyGraph for Target BuildCode:
2022-09-15T08:57:53.5010841Z <== BuildCode
2022-09-15T08:57:53.5011120Z 
2022-09-15T08:57:53.5463684Z The running order is:
2022-09-15T08:57:53.5464385Z Group - 1
2022-09-15T08:57:53.5464894Z   - BuildCode
2022-09-15T08:57:53.5898143Z Starting target 'BuildCode'
2022-09-15T08:57:53.5919240Z Clean...
2022-09-15T08:57:53.6794089Z Starting task 'MSBuild': D:\a\1\s\source\Common\Common.sln
2022-09-15T08:57:53.7679920Z Building project: D:\a\1\s\source\Common\Common.sln
2022-09-15T08:57:53.7681208Z   c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  D:\a\1\s\source\Common\Common.sln "/t:Clean,Build" "/m" "/nodeReuse:False" "/p:RestorePackages=False" "/p:OutputPath=D:\a\1\s\build\\" "/p:Configuration=Debug" "/p:PlatformTarget=AnyCpu" "/p:Verbosity=Diagnostic"
2022-09-15T08:57:53.8588303Z c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  D:\a\1\s\source\Common\Common.sln "/t:Clean,Build" "/m" "/nodeReuse:False" "/p:RestorePackages=False" "/p:OutputPath=D:\a\1\s\build\\" "/p:Configuration=Debug" "/p:PlatformTarget=AnyCpu" "/p:Verbosity=Diagnostic"
2022-09-15T08:57:54.4908302Z Microsoft (R) Build Engine version 4.8.3761.0
2022-09-15T08:57:54.4909089Z [Microsoft .NET Framework, version 4.0.30319.42000]
2022-09-15T08:57:54.4909531Z Copyright (C) Microsoft Corporation. All rights reserved.
2022-09-15T08:57:54.4909691Z 
2022-09-15T08:57:55.1676734Z Build started 9/15/2022 8:57:55 AM.

**Comment by ShipraRay150** [comment]
> ToolPath should be an exe file, like: let msBuildPath ="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"

tried with this also not worked, for some reason fake build is still taking MSbuild path as: c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe

**Comment by ShipraRay150** [comment]
@al-cheb 

Is it possible to add an MSBuild environment variable for this agent windows-2019 in microsoft servers
path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin ?

**Comment by ShipraRay150** [comment]
> You can add a step to set this variable:
> 
> ```
> - pwsh: 'Write-Host "##vso[task.setvariable variable=MSBuild]C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"'
>   displayName: 'Set env var'
> ```

How to add this ?

**Comment by al-cheb** [comment]
> > You can add a step to set this variable:
> > ```
> > - pwsh: 'Write-Host "##vso[task.setvariable variable=MSBuild]C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"'
> >   displayName: 'Set env var'
> > ```
> 
> How to add this ?

Click Add a task -> Choose PowerShell:
![image](https://user-images.githubusercontent.com/47745270/190400354-85e038d1-f892-4a6e-b9ad-d406f36e58b2.png)

**Comment by ShipraRay150** [comment]
@al-cheb 

My classic build pipeline is working fine but when i ran release pipeline ahent windows-2019 i get this build error:
error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]]

Can you please help on this??

**Comment by al-cheb** [comment]
@ShipraRay150, please share the AssemblyVersion.cs content.

**Comment by ShipraRay150** [comment]
@al-cheb Before the last successful ran with the release pipeline when agent selected was VS2017-win16

I get this error with agent windows-2019

**Comment by al-cheb** [comment]
@ShipraRay150, do you have SolutionInfo.cs file?

**Comment by ShipraRay150** [comment]
> @ShipraRay150, do you have a SolutionInfo.cs file?

@al-cheb  No we dont have

**Comment by ShipraRay150** [comment]
@al-cheb Any suggestions on this please?

**Comment by al-cheb** [comment]
@ShipraRay150, please attach logs of the failed build.
![image](https://user-images.githubusercontent.com/47745270/191189962-45d1d2ad-0d37-4655-a5ff-d9e8ef3aeef0.png)

**Comment by ShipraRay150** [comment]
> @ShipraRay150, please attach logs of the failed build. ![image](https://user-images.githubusercontent.com/47745270/191189962-45d1d2ad-0d37-4655-a5ff-d9e8ef3aeef0.png)

@al-cheb 
[TestLogs.txt](https://github.com/actions/runner-images/files/9605035/TestLogs.txt)

**Comment by ShipraRay150** [comment]
@al-cheb 
Logs:

2022-09-19T17:22:03.9592497Z        "D:\a\1\s\source\TEST.build.Common\TEST.build.Common.sln" (Clean;Build target) (1) ->
2022-09-19T17:22:03.9602035Z        "D:\a\1\s\source\TEST.build.Common\TEST.build.Constants\TEST.build.Constants.csproj" (default target) (14:2) ->
2022-09-19T17:22:03.9603547Z          D:\a\1\s\source\components\Solution\AssemblyVersion.cs(5,28): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [D:\a\1\s\source\TEST.build.Common\TEST.build.Constants\TEST.build.Constants.csproj]
2022-09-19T17:22:03.9604801Z 
2022-09-19T17:22:03.9605560Z     2 Warning(s)
2022-09-19T17:22:03.9606027Z     2 Error(s)
2022-09-19T17:22:03.9606165Z 
2022-09-19T17:22:03.9606567Z Time Elapsed 00:00:05.02
2022-09-19T17:22:04.2307568Z Finished (Failed) 'MSBuild' in 00:00:05.6992077
2022-09-19T17:22:04.2311331Z Finished (Failed) 'Release' in 00:00:05.8188469

**Comment by al-cheb** [comment]
@ShipraRay150, Please show TEST.build.Constants.csproj content.

**Comment by ShipraRay150** [comment]
@al-cheb 
[logs.txt](https://github.com/actions/runner-images/files/9605212/logs.txt)

**Comment by al-cheb** [comment]
@ShipraRay150, from previous log you passed `2021.9.1646096.1` version. Could you replace the Build part to less than 65535 ( `2021.9.164.1`)  ?

**Comment by ShipraRay150** [comment]
> @ShipraRay150, from previous log you passed `2021.9.1646096.1` version. Could you replace the Build part to less than 65535 ( `2021.9.164.1`) ?

@al-cheb Where i need to make this change?

**Comment by ShipraRay150** [comment]
> @ShipraRay150, from previous log you passed `2021.9.1646096.1` version. Could you replace the Build part to less than 65535 ( `2021.9.164.1`) ?

sure will do and check

**Comment by ShipraRay150** [comment]
> > @ShipraRay150, from previous log you passed `2021.9.1646096.1` version. Could you replace the Build part to less than 65535 ( `2021.9.164.1`) ?
> 
> sure will do and check

This worked Thankyou..!! (y)

**Comment by ShipraRay150** [comment]
@al-cheb, Hi need one help is there any azure devops pipeline task to copy remote server files to local machine? Please help!

**Comment by al-cheb** [comment]
> @al-cheb, Hi need one help is there any azure devops pipeline task to copy remote server files to local machine? Please help!

You can publish an artifact and download it manually to the local machine.  How to publish artifacts - https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=classic#publish-artifacts

**Comment by al-cheb** [comment]
> > > @al-cheb, Hi need one help is there any azure devops pipeline task to copy remote server files to local machine? Please help!
> > 
> > 
> > You can publish an artifact and download it manually to the local machine. How to publish artifacts - https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=classic#publish-artifacts
> 
> @al-cheb my requirement like - i want to fetch some certificates from server to my local machine.how can i do that?

Please read message above how to publish artifacts.
