### ISSUE TITLE
Add sccache

### ISSUE THREAD

**Issue by leighmcculloch** [actions/runner-images#6209]
### Tool name

sccache

### Tool license

Apache License 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v0.3.0

### Approximate size

12MB

### Brief description of tool

[sccache](https://github.com/mozilla/sccache) is a [ccache](https://ccache.dev/)-like compiler caching tool. It is used as a compiler wrapper and avoids compilation when possible, storing cached results either on [local disk](https://github.com/actions/runner-images/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=tool-request.yml&title=Update%2FAdd+%5Btool+name%5D#local) or in one of [several cloud storage backends](https://github.com/actions/runner-images/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=tool-request.yml&title=Update%2FAdd+%5Btool+name%5D#storage-options).

sccache is a popular tool for caching. Given its use for caching in Rust projects it is helpful to have it preinstalled so that a GitHub Actions run can utilize the cache for all Rust components and to remove the need to install any dependencies from scratch.

### URL for tool's homepage

https://github.com/mozilla/sccache

### Provide a basic test case to validate the tool's functionality.

```bash
sccache rustc <(echo 'pub fn main() {}') -o main && ./main
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
cargo install --locked sccache
```

### Tool installation time in runtime

28 seconds

### Are you willing to submit a PR?

Yes!

**Comment by leighmcculloch** [comment]
I have submitted a PR adding sccache: https://github.com/stellar/actions/pull/22.

**Comment by al-cheb** [comment]
Close as https://github.com/actions/runner-images/pull/1600

**Comment by leighmcculloch** [comment]
@al-cheb I note that the reasons for not including sccache was the 9 minute build time and the fact it is installed from source. In my tests install including compile takes 28 seconds, not 9 minutes. Would it be accepted if I change the PR to install the prereleased binary? This would also make it much faster.

**Comment by quyykk** [comment]
This would be really useful, especially since the latest version of sccache now supports using the GitHub Actions cache out of the box.
