### ISSUE TITLE
Ubuntu2204 - Unzip, zip not found

### ISSUE THREAD

**Issue by rdvansloten** [actions/runner-images#6212]
### Description

Several tasks require unzip, but it is not included. I see it present in the toolset-2204.json file, but it is not actually installed. If I look in the hcl file, it seems the toolset installer is called after all the installer packages. I am using the version of this repo that was recent on 9 Sept, main branch commit 148eaf9c80af082b519d24f82f7c965cb5a320e9.

Passing in:
```
apt install curl zip unzip tar bzip2
```

Before all the installer shell scripts start fixes the problem. Some individual installers such as yq are still broken because of other issues, however.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I can't find such a version or link. This is my "Initialize job" tab:

Starting: Initialize job
Agent name: 'myvm'
Agent machine name: 'myvm'
Current agent version: '2.204.0'
Agent running as: 'myuser'
Prepare build directory.
Set build variables.
Download all required tasks.
Checking job knob settings.
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

No

### Expected behavior

Tools to install successfully.

### Actual behavior

Packages want unzip installed.

### Repro steps

- Clone the repository
- Run the Ubuntu2204 pipeline
- Wait for it to fail on:
```
azure-arm.build_vhd: Downloading 'https://www-eu.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip' to '/tmp/maven.zip'...
==> azure-arm.build_vhd: /tmp/script_8492.sh: line 143: unzip: command not found
    azure-arm.build_vhd: Download completed
```

```
    azure-arm.build_vhd: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_vhd: Describing Packer
    azure-arm.build_vhd:   [+] packer 941ms (912ms|29ms)
    azure-arm.build_vhd: Tests completed in 1.7s
    azure-arm.build_vhd: Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 94
==> azure-arm.build_vhd: Provisioning with shell script: /home/azureadm/agent/_work/6/s/images/linux/scripts/installers/vcpkg.sh
    azure-arm.build_vhd: VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg
==> azure-arm.build_vhd: Cloning into '/usr/local/share/vcpkg'...
    azure-arm.build_vhd: Could not find zip. Please install it (and other dependencies) with:
    azure-arm.build_vhd: On Debian and Ubuntu derivatives:
    azure-arm.build_vhd:   sudo apt-get install curl zip unzip tar
```

**Comment by al-cheb** [comment]
Hey @rdvansloten. 

I can't reproduce the issue.

![image](https://user-images.githubusercontent.com/47745270/189482625-213869dc-ec4e-4fb1-8a6a-26525a842633.png)

**Comment by rdvansloten** [comment]
Hi @al-cheb you seem to be testing through GitHub Actions judging by the screenshot? I am using Azure DevOps.

**Comment by al-cheb** [comment]
> Hi @al-cheb you seem to be testing through GitHub Actions judging by the screenshot? I am using Azure DevOps.

We deploy the same image in Azure DevOps&GitHub.

**Comment by rdvansloten** [comment]
So you're saying there's a 0% chance that arguments or settings passed from the included Azure Pipelines file can not be the reason for any potential failure?

**Comment by al-cheb** [comment]
> So you're saying there's a 0% chance that arguments or settings passed from the included Azure Pipelines file can not be the reason for any potential failure?

Please attach repro steps how to reproduce the issue in Azure DevOps.

**Comment by rdvansloten** [comment]
> > So you're saying there's a 0% chance that arguments or settings passed from the included Azure Pipelines file can not be the reason for any potential failure?
> 
> Please attach repro steps how to reproduce the issue in Azure DevOps.

I have, it's in the initial post. I simply cloned the repo to my private organization, and ran the included `images.CI/linux-and-win/azure-pipelines/ubuntu2204.yml pipeline.`

The executing Ubuntu 2204 agent has zip, Packer and pwsh installed, as they are required to run the pipeline steps.

**Comment by al-cheb** [comment]
> > > So you're saying there's a 0% chance that arguments or settings passed from the included Azure Pipelines file can not be the reason for any potential failure?
> > 
> > 
> > Please attach repro steps how to reproduce the issue in Azure DevOps.
> 
> I have, it's in the initial post. I simply cloned the repo to my private organization, and ran the included `images.CI/linux-and-win/azure-pipelines/ubuntu2204.yml` pipeline.
> 
> The executing Ubuntu 2204 agent has zip, Packer and pwsh installed, as they are required to run the pipeline steps.

The nightly build is green with zip&unzip - https://github.visualstudio.com/runner-images/_build/results?buildId=128726&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=72559e73-928c-58e0-b67e-e22d7a78faae

```
| unzip                | 6.0-26ubuntu3                  |
| zip                    | 3.0-12build2                      |
```
