### ISSUE TITLE
Quick fix: wrong comment / file name for mongodb.sh

### ISSUE THREAD

**Issue by HoLengZai** [actions/runner-images#6213]
### Description

The comment indicates "homebrew.sh" instead of "mongodb.sh"

Line 3, 
https://github.com/actions/runner-images/blob/812929556709b48410ec6ac2d3533762c35488a2/images/linux/scripts/installers/mongodb.sh#L2-L5

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

-

### Expected behavior

```bash
 ################################################################################ 
 ##  File:  mongodb.sh 
 ##  Desc:  Installs Mongo DB 
 ################################################################################ 
```

### Actual behavior

https://github.com/actions/runner-images/blob/812929556709b48410ec6ac2d3533762c35488a2/images/linux/scripts/installers/mongodb.sh#L2-L5

### Repro steps

https://github.com/actions/runner-images/blob/812929556709b48410ec6ac2d3533762c35488a2/images/linux/scripts/installers/mongodb.sh#L2-L5

**Comment by al-cheb** [comment]
Hey @HoLengZai.
Thank you. It will be fixed in https://github.com/actions/runner-images/pull/6215.
