### ISSUE TITLE
Add colima

### ISSUE THREAD

**Issue by mvgijssel** [actions/runner-images#6216]
### Tool name

Colima

### Tool license

MIT license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

0.4.4

### Approximate size

17mb

### Brief description of tool

Colima - container runtimes on macOS (and Linux) with minimal setup. Means you can run `docker` without having to install Docker for macOS and run into licensing issues (https://github.com/actions/runner-images/issues/2150). 

### URL for tool's homepage

https://github.com/abiosoft/colima

### Provide a basic test case to validate the tool's functionality.

```bash
❯ colima version
colima version 0.4.4
git commit: 8bb1101a861a8b6d2ef6e16aca97a835f65c4f8f
```
```


### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install docker colima
```

### Tool installation time in runtime

1 minute

### Are you willing to submit a PR?

Sure!

**Comment by mikhailkoliada** [comment]
@mvgijssel we will decide on adding it and get back to you.

**Comment by ddobranic** [comment]
hi @mvgijssel! thank you for your proposal. we will add colima to our macOS images.

**Comment by mvgijssel** [comment]
That’s awesome! Let me know if you need any help!

**Comment by ddobranic** [comment]
hello @mvgijssel! colima has been added to macOS images.

**Comment by Jasperav** [comment]
@mvgijssel @ddobranic does any of you know why this is removed from macos 13?

**Comment by mvgijssel** [comment]
No idea!

**Comment by ejsmith** [comment]
Yeah, wondering the same thing. Why was it removed?

**Comment by asottile-sentry** [comment]
it's also missing on the new macos-14 image as well

**Comment by AkihiroSuda** [comment]
- https://github.com/cncf/toc/issues/1348#issuecomment-2578607870

We, the maintainers of [Lima](https://lima-vm.io) (the tool under the hood of Colima), are trying to promote Lima from Cloud Native Computing Foundation (CNCF) Sandbox to Incubating.

We need several project adopters to be interviewed by the Technical Oversight Committee of CNCF.
Would it be possible to get an interviewee from GitHub/Microsoft to attest the usage of Lima/Colima on GitHub Actions? 🙏
