### ISSUE TITLE
Add Xcode 14 beta (not RC)

### ISSUE THREAD

**Issue by roballie** [actions/runner-images#6221]
### Tool name

Xcode 14 beta

### Tool license

none

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest beta (not RC)

### Approximate size

12.6GB

### Brief description of tool

It is the latest beta of Xcode.  The Xcode 14 release candidate doesn't include the macOS 13 SDK, but the latest beta version does.

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

**Comment by miketimofeev** [comment]
@roballie Hi!
We have already done this in the scope of https://github.com/actions/runner-images/pull/6204
The new image will be deployed in the next two days.

**Comment by miketimofeev** [comment]
@roballie @Brett-Best the new image with both Xcodes has been deployed.
I'm going to close the issue.
Thank you!
