### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by slajar** [actions/runner-images#6224]
### Tool name

XCode 14

### Tool license

free

### Add or update?

- [ ] Add
- [X] Update

### Desired version

latest

### Approximate size

unknown

### Brief description of tool

Apples software developement tool, that is needed for appstore submissions.
This shall be the default XCode from now on.

### URL for tool's homepage

https://developer.apple.com/download/all/?q=Xcode

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

### Tool installation time in runtime

-

### Are you willing to submit a PR?

-

**Comment by miketimofeev** [comment]
@slajar we already have Xcode 14 on the image. We will make it the default one in two weeks.
