### ISSUE TITLE
Error with StartProcess and az command

### ISSUE THREAD

**Issue by damienmartel2** [actions/runner-images#6239]
### Description

In a powershell task i am using the code : 

```
    if ($ok) {
        $arg = "artifacts universal publish --organization `"$OrganizationUrl`" --project `"$Project`" --scope project --feed `"$Feed`" --name `"$Name`" --version `"$Version`" --description `"$Description`" --path `"$ArtifactPath`" "
        $process = Start-Process -NoNewWindow -FilePath "az" -ArgumentList $arg -Wait -PassThru 
        if ($process.ExitCode -ne 0) {
            $ok = $false   
            $errorMessage = "Error $($process.ExitCode) occurred executing az `"$ArtifactPath`""
            Trace-Report -Message $errorMessage -Color Red
            Throw $errorMessage 
        }
    }
```

Without changes the pipeline now fails with this error 
```
Start-Process : This command cannot be run due to the error: %1 is not a valid Win32 application.
At C:\Program Files\WindowsPowerShell\Modules\MSBuildTools\0.1.3\MSBuildTools.psm1:527 char:20
+ ...  $process = Start-Process -NoNewWindow -FilePath "az" -ArgumentList $ ...
```
It seems to have an issue with the command az...

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220911.1

### Is it regression?

yes it worked with 20220905.1

### Expected behavior

The command is ok or an error  message or an alternative

### Actual behavior

The command fails

### Repro steps

- Create a pipeline executed on the runner image version 20220911.1

- create a powershell task inline with comand : 
$arg = "account list"
$process = Start-Process -NoNewWindow -FilePath "az" -ArgumentList $arg -Wait -PassThru 

you will have the error

**Comment by al-cheb** [comment]
Hey @damienmartel2.

az is a powershell script now:

![image](https://user-images.githubusercontent.com/47745270/190165342-148c390b-375f-4f69-84f1-fe672f87847e.png)


az account list - should work

**Comment by damienmartel2** [comment]
Ok the problem is Azure Cli has been updated and so now there is an az.ps1 so i need to make "az.cmd" in order to continue to call the good program...

**Comment by damienmartel2** [comment]
sorry @al-cheb i didn't show your answer. It's exactly that ;) thanks
