### ISSUE TITLE
Driver build broken because SDK 10.1.22621.1 is installed but not the matching WDK

### ISSUE THREAD

**Issue by indygit** [actions/runner-images#6244]
### Description

My driver project depends on headers such as d3d10umddi.h that are installed into C:\Program Files (x86)\Windows Kits\10\Include\[SDK version]\um by WDK, SDK version on "Windows Server 2019 image" is now 10.1.22621.1, but WDK is only 10.1.22000.1, so the build couldn't find the headers such as d3d10umddi.h

Would you be able to install 10.1.22621.1 into "Windows Server 2019 image" ?

My build has been working with "Windows Server 2019 image" up to version 20220828.1, but it is broken with the newer version.

I attached 2 zip files of logs, 1 from 20220828.1, 1 from the 20220905.1

Cheers, Indy

[logs_57203.zip](https://github.com/actions/runner-images/files/9570570/logs_57203.zip)
[logs_57489.zip](https://github.com/actions/runner-images/files/9570571/logs_57489.zip)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220905.1

### Is it regression?

Yes. 20220828.1

### Expected behavior

WDK and SDK of the same version should be installed together.

### Actual behavior

In newer image WDK was not updated.

### Repro steps

My project https://windowspartners.visualstudio.com/imx8m-graphics is not public, my pipeline can no longer build the driver.

**Comment by mikhailkoliada** [comment]
@indygit thanks, we will take a look.

**Comment by erik-bershel** [comment]
@indygit 
Unfortunately, the required WDK is not compatible with the specified base image. For a successful build, I can recommend choosing Win2022 or specifying another version of the SDK (Win11SDK.22000) for which there is a compatible WDK (10.1.22000.1) for your particular project. 
Please, feel free to contact us if we can help in any other way.

**Comment by erik-bershel** [comment]
@indygit 
Hello!
Were you able to verify the build of the project with the specified SDK? Maybe there are some other problems or questions for us?

**Comment by al-cheb** [comment]
I am planning to close the thread. If you have any concerns feel free to open it.

**Comment by indygit** [comment]
Thanks Erik-bershel and Al-cheb.

Yes, specifying 10.1.22000.1 for WindowsTargetPlatformVersion fixed the issue.

Best regards, Indy
