### ISSUE TITLE
Update/Add Xcode 14.1 betas

### ISSUE THREAD

**Issue by fernandotcl** [actions/runner-images#6248]
### Tool name

Xcode

### Tool license

Freeware

### Add or update?

- [X] Add
- [ ] Update

### Desired version

14.1 beta 1

### Brief description of tool

Xcode 14.1 betas contain the macOS 13 (Ventura) SDK. Right now, the only way to do macOS CI on Azure Pipelines would be to revert to the 14.0 betas, which itself has other issues.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
@fernandotcl Hi!

Thanks, we will take care of it.

**Comment by mikhailkoliada** [comment]
Added. Will be deployed next week.

**Comment by miketimofeev** [comment]
@roballie @Brett-Best FYI: we have replaced Xcode 14.0 beta with Xcode 14.1 beta as it supports macOS Ventura SDK. Please let us know if you have any concerns.

**Comment by miketimofeev** [comment]
The image is deployed. I'm going to close the issue.
Thank you!

**Comment by miketimofeev** [comment]
This is now finally deployed.
Closing the issue.
