### ISSUE TITLE
Setting environment variables does not work on windows images

### ISSUE THREAD

**Issue by justusranvier** [actions/runner-images#6254]
### Description

The [instructions](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable) for setting environment variables does not work on windows runners but does work on macos runners.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/justusranvier/action-test/actions/runs/3070035363/jobs/4959344528

### Is it regression?

no

### Expected behavior

VCPKG_INSTALLED_DIR is set to expected value.

macos-11 works: https://github.com/justusranvier/action-test/actions/runs/3070035363/jobs/4959344438

![image](https://user-images.githubusercontent.com/1255702/190711415-7d86e4c3-c3bb-4fb0-b839-b821f48081ff.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/1255702/190711478-6c89d20a-e068-400c-9062-9bb1abfcf819.png)

### Repro steps

https://github.com/justusranvier/action-test/blob/master/.github/workflows/example.yml

**Comment by al-cheb** [comment]
Hello @justusranvier.
In PowerShell to get access to a variable you should use `$env:<variable-name>` syntax. It works in macOS because the default shell is bash where syntax is $VARIABLE-NAME.

```
- name: Set packages directory
  run: echo "VCPKG_INSTALLED_DIR=${{ github.workspace }}/deps/vcpkg_installed/${{ matrix.platform }}" >> $env:GITHUB_ENV
- name: Show packages directory
  run: echo '${{ env.VCPKG_INSTALLED_DIR }}'
```

**Comment by justusranvier** [comment]
That control for switching between Bash and PowerShell only existing at the top of a rather long page makes it very easy to miss. It would be a lot more helpful if every script snippet had that control on it.
