### ISSUE TITLE
Installing HAXM fails on windows-latest runner

### ISSUE THREAD

**Issue by mpconte** [actions/runner-images#6256]
### Description

When attempting to install the HAXM in order to utilize hardware acceleration as required for running Android x86_64 emulators, the install fails

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

 Version: 20220911.1

### Is it regression?

No

### Expected behavior

Installing Intel haxm succeeds

### Actual behavior

The following message is displayed

```
Intel HAXM installation failed!
For more details, please check the installation log: C:\Users\RUNNER~1\AppData\Local\Temp\haxm_install-202209[16](https://github.com/SensoftInc/kotlin_demo/actions/runs/3070730312/jobs/4960753853#step:7:17)_2106.log
```

### Repro steps

As part of the workflow:
```
    - name: Create Android emulator
      run: |
        Invoke-WebRequest "https://github.com/intel/haxm/releases/download/v7.7.1/haxm-windows_v7_7_1.zip" -OutFile ".\haxm-windows_v7_7_1.zip"
        Expand-Archive ".\haxm-windows_v7_7_1.zip" "." -Force
        .\silent_install.bat
        sdkmanager --install "system-images;android-31;google_apis;x86_64"
        echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
```

**Comment by al-cheb** [comment]
Close as https://github.com/actions/runner-images/issues/4023#issuecomment-913576338
