### ISSUE TITLE
The following build commands failed: PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/myproject-hfznzxvrsqgfuzajavqfcfjkopph/Build/Intermediates.noindex/myproject.build/Dev-iphoneos/myproject-IOS.build/Script-00DD1BFF1BD5951E006B06BC.sh

### ISSUE THREAD

**Issue by TonyFTannous** [actions/runner-images#6260]
### Description

Hello, i need help

in my mac using xcode 13.4.1, everything go well, but when publishing using azure/pipeline, the build failed
after the azure update (Updating readme file for macOS-11 version 20220906.1)
but before the update of azure everything go well and no build failed

The following build commands failed:
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/myproject-hfznzxvrsqgfuzajavqfcfjkopph/Build/Intermediates.noindex/myproject.build/Dev-iphoneos/myproject-IOS.build/Script-00DD1BFF1BD5951E006B06BC.sh

**
in my xcode -> build phases -> bundle react native code and images:

export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
**

please any help

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://accuv.visualstudio.com/AccuV/_build/results?buildId=53462&view=results

### Is it regression?

https://accuv.visualstudio.com/AccuV/_build/results?buildId=52824&view=results

### Expected behavior

i expected to build successfuly

### Actual behavior

failed build

### Repro steps

Hello, i need help

in my mac using xcode 13.4.1, everything go well, but when publishing using azure/pipeline, the build failed
after the azure update (Updating readme file for macOS-11 version 20220906.1)
but before the update of azure everything go well and no build failed

The following build commands failed:
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/myproject-hfznzxvrsqgfuzajavqfcfjkopph/Build/Intermediates.noindex/myproject.build/Dev-iphoneos/myproject-IOS.build/Script-00DD1BFF1BD5951E006B06BC.sh

please any help

**Comment by al-cheb** [comment]
Hey, @TonyFTannous.
There is no Xcode 13.4.1 available on macOS 11, it's available only on macOS-12. We don't have access to your repo. Could you please attach logs from  successfuly and failed builds?

**Comment by TonyFTannous** [comment]
Hey al-cheb, thanks for your answere
Xcode 13.4.1, macOS 12.4 is my Mac and using it everything go well.
but when using virtual machine Azure DevOps (macOS-11 version 20220906.1) thru pipeline yaml, the build failed, although before this update all go well on azure devops
[logs.pdf](https://github.com/actions/runner-images/files/9606157/logs.pdf)

**Comment by al-cheb** [comment]
> Hey, @al-cheb thanks for your answere
> 
> Xcode 13.4.1, macOS 12.4 is my Mac and using it everything go well. but when using virtual machine Azure DevOps (macOS-11 version 20220906.1) thru pipeline yaml, the build failed, although before this update all go well on azure devops [logs.pdf](https://github.com/actions/runner-images/files/9606157/logs.pdf)

Could you please attach a zip archive?
![image](https://user-images.githubusercontent.com/47745270/191189962-45d1d2ad-0d37-4655-a5ff-d9e8ef3aeef0.png)

**Comment by TonyFTannous** [comment]
my mac is macos-12 and my xcode is 13.4.1, in these i have not any issues i can build my app
but in azure devops i use macos-11
[logs_53925.zip](https://github.com/actions/runner-images/files/9606505/logs_53925.zip)

**Comment by TonyFTannous** [comment]
Hey. any update
failed to generate the bundle
the script located in bundle react-native code and images failed to generate the bundle
**export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh**

please help
thanks in advanced

**Comment by b7rnee** [comment]
> Hey. any update failed to generate the bundle the script located in bundle react-native code and images failed to generate the bundle **export NODE_BINARY=node ../node_modules/react-native/scripts/react-native-xcode.sh**
> 
> please help thanks in advanced

any update? same issue in here.

**Comment by julestruong** [comment]
I have the same issue , but only on github actions.

In Xcode, i managed to solved this issue because i can see the problem looking at the log.
In github actions, i can't even know what is wrong with the script.

Is there any way to see the logs ?

**Comment by immi-sipgate** [comment]
@julestruong we have the same problem using github actions. Could you figure something out?

**Comment by mikhailkoliada** [comment]
Going to close the issue as no more reports are revealed over time, please let us know if you still have concerns.
