### ISSUE TITLE
Windows Server 2022 Image Build IMAGE_STATE_UNDEPLOYABLE

### ISSUE THREAD

**Issue by swapnil-kambli** [actions/runner-images#6270]
### Description

vhd: Machine successfully restarted, moving on
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\AzDevOps\AppData\Local\Temp\1\powershell-provisioner539113561
    vhd: IMAGE_STATE_COMPLETE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current agent version: '2.210.1'
Current image version: 'dev'

### Is it regression?

NA

### Expected behavior

Image Deployment state to be "COMPLETE"

### Actual behavior

    vhd: Finalize-VM.ps1 - completed
==> vhd: Restarting Machine
==> vhd: Waiting for machine to restart...
==> vhd: A system shutdown is in progress.(1115)
    vhd: pkrvmiddabx0tx7 restarted.
==> vhd: Machine successfully restarted, moving on
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\AzDevOps\AppData\Local\Temp\1\powershell-provisioner539113561
    vhd: IMAGE_STATE_COMPLETE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE

### Repro steps

Image Build using the image windows2022
https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/image-generation.yml

**Comment by al-cheb** [comment]
Close as https://github.com/actions/runner-images/discussions/6251
