### ISSUE TITLE
Can't select Xcode 14.0 for build process. Instead 14.0.1 is automatically chosen

### ISSUE THREAD

**Issue by Devepre** [actions/runner-images#6273]
### Description

While trying to create a build using **latest public** release at this point of time (Xcode **14.0** 14A309), system can't switch to this version and switches to the **14.0.1** (14A400) instead.
As result, system can't upload created archive because of this problem:
`Could not find transporter at /Applications/Xcode_14.0.1.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.`

Of course it can't, because there is **no public 14.0.1** release yet. Instead it's **RC 1**.

From the logs:
```
Switching Xcode to version '14.0'...
Xcode is set to 14.0.1 (14A400)
```

And here is part of yaml file:
```
jobs:
  deploy:
    runs-on: macos-12
    uses: maxim-lobanov/setup-xcode@v1
        with:
          # should be explicit, and usually the latest available
          xcode-version: '14.0'
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
  Version: 20220917.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20220917.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20220917.1

### Is it regression?

No

### Expected behavior

Archive should be created within selected **14.0** version as per configuration

### Actual behavior

Archive is created within wrong **14.0.1** version

### Repro steps

1. Configure script to use Xcode 14.0
2. Run job
3. Observe logs for error

It will be not an issue after 26 of September (if Apple will release public 14.0.1 version and image will be updated). But up until that point, it's not possible to create build and release it to TestFlight with latest iOS 16 SDK.

**Comment by al-cheb** [comment]
Hey @Devepre.
You could use x.x.x notation to select Xcode version:

```
- uses: maxim-lobanov/setup-xcode@v1
  with:
      xcode-version: '14.0.0'
```

![image](https://user-images.githubusercontent.com/47745270/191282669-34709f97-057a-4996-a128-d41be636ad26.png)
