### ISSUE TITLE
gfortran in Ubuntu images broken because of added `-gdwarf-5` flag

### ISSUE THREAD

**Issue by rgommers** [actions/runner-images#6274]
### Description

Today all Ubuntu jobs in the SciPy CI on Azure DevOps started breaking because `gfortran` is no longer able to compile anything. The way this shows up is:
```
as: unrecognized option '--gdwarf-5'
/home/linuxbrew/.linuxbrew/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC
```
We are not installing Linuxbrew explicitly, nor are adding a `-gdwarf-5` flag. This is likely to be a mixup in GCC specs caused by gh-6258.

See https://github.com/scipy/scipy/issues/17058 for more details on the SciPy build failures in CI.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I'll note that the Ubuntu 22.04 image should also be affected, however we don't have any CI jobs using that image so I can't be sure that it is affected.

Images affected:
```
Image: ubuntu-20.04
Version: 20220919.1
```

```
Image: ubuntu-18.04
Version: 20220919.2
```

### Is it regression?

Yes. The problem started about 6 hours ago. The previous image was `20220905.1`, that worked fine.

### Expected behavior

`gfortran` should not be passed a flag `-gdwarf-5`, and compiling Fortran code with `gfortran` should work.

### Actual behavior

See issue description.

### Repro steps

Here is a CI job that fails: https://github.com/scipy/scipy/blob/main/azure-pipelines.yml#L58.

Compiling any Fortran code with `gfortran -g` should reproduce the issue.

**Comment by al-cheb** [comment]
Hey @rgommers.
We will take a look at it.

**Comment by dawidd6** [comment]
Ubuntu 22.04 should not be affected as Homebrew does not need to install newer gcc there.

**Comment by mikhailkoliada** [comment]
gfortran symlink removed, changes will be released this week.

**Comment by rgommers** [comment]
Thanks @mikhailkoliada! It looks like in the meantime the default image got reverted to an older build, so our CI is working again.

**Comment by mikhailkoliada** [comment]
homebrew has been removed from $PATH so it will not affect you anymore (though we still remove gfortran symlink too, so if you add homebrew back to PATH it should work too).
