### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by Piedone** [actions/runner-images#6275]
### Tool name

curl

### Tool license

https://curl.se/docs/copyright.html

### Add or update?

- [ ] Add
- [X] Update

### Desired version

ideally latest, otherwise >=7.76.0

### Approximate size

3 MB

### URL for tool's homepage

https://curl.se/

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by Piedone** [comment]
There was not field for the rationale, but here's why I'm asking for an update: curl 7.76.0 brought `--fail-with-body` that'll both fail the command (status code != 0) and output the response if the HTTP request fails, see [this SO answer](https://superuser.com/a/1626376/47254). Under prior versions you can either fail the command or output the response, but not both (unless you hack around).

**Comment by al-cheb** [comment]
Hey @Piedone.
Curl version is already updated > 7.76 on Windows Server 2022/Ubuntu Server 22.04.

Windows Server 2022:
![image](https://user-images.githubusercontent.com/47745270/191316322-510f875e-cc37-4ab9-864b-1db7335a91c6.png)

Ubuntu Server 22.04:
![image](https://user-images.githubusercontent.com/47745270/191316468-f3141a23-40a2-4ff8-9c94-dc4804a6e358.png)

**Comment by Piedone** [comment]
Hmm, `--fail-with-body` is not working for some reason though with `curl: option --fail-with-body: is unknown`. Let me check.

**Comment by Piedone** [comment]
Ah well, `ubuntu-latest` is not 22.x but 20.x, I see. Thanks for the quick reply.
