### ISSUE TITLE
[Ubuntu] homebrew will be removed from PATH variable

### ISSUE THREAD

**Issue by ddobranic** [actions/runner-images#6283]
### Breaking changes

homebrew will be removed from $PATH on Ubuntu images.

### Target date

Image deployment will start September 22nd, and will be finished on Monday, September 27th.

### The motivation for the changes

Starting with homebrew 3.6.0, gcc and its toolchain (binutils and glibc) became mandatory dependencies for any installed package. We are going to remove homebrew from the $PATH variable so it does not conflict with the canonical-provided software and toolchain.

See more:
- [linuxbrew overrides some basic toolchain commands #110877 ](https://github.com/Homebrew/homebrew-core/issues/110877)
- [homebrew executables are superseded by system ones #1136](https://github.com/actions/runner-images/blob/f7664a3f4a59ececba6e50a45e8a347b2dafe4b8/images/linux/scripts/installers/homebrew.sh#L5)
- [Latest update to Ubuntu 20.04 image breaks gcc compiler #6280](https://github.com/actions/runner-images/issues/6280)
- [gfortran in Ubuntu images broken because of added -gdwarf-5 flag #6274](https://github.com/actions/runner-images/issues/6274)

### Possible impact

If your project depends on homebrew your build will be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation Path

Please use `Homebrew/actions/setup-homebrew` [action](https://github.com/Homebrew/actions/tree/master/setup-homebrew) to make brew available during running session.

**Comment by rfay** [comment]
Enormous breakage, enormous number of repositories.

**Comment by selfsk** [comment]
Strange approach... lets brake image that used probably by 95% of github actions. Where there an announcement made about these changes? If not - it makes github images completely unreliable.

**Comment by akhil-cervello** [comment]
Could've been handled with prior announcement! Reactive approach.

**Comment by antonmos** [comment]
This change breaks the commitment made in https://github.com/actions/runner-images/tree/releases/ubuntu20/20220922#default-version-update-policy
Moreover, this suggestion just does not work `echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH`
`eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` does work, but for the life of me, i cannot get `tfenv` to run after `brew install tfenv` succeeds.

The biggest problem is that there is no way for me to change `runs-on` to just use the previous version of the runner!

**Comment by antonmos** [comment]
> 1. This change breaks the commitment made in https://github.com/actions/runner-images/tree/main#default-version-update-policy that promises to announce breaking change 1 month in advance.
> 2. This suggestion just does not work `echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH`
>    `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` does work, but for the life of me, i cannot get `tfenv` to run after `brew install tfenv` succeeds.
> 3. The biggest problem is that there is no way for me to change `runs-on` to just use the previous version of the runner!

After multiple hours, I found a workaround that works, run the following commands in a **single action step**:
* `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"`
* `brew install tfenv`
* `tfenv install terraform`

Hope this is helps someone.

**Comment by raviqqe** [comment]
Is it possible for GitHub to provide an official GitHub Action that enables Homebrew in Ubuntu images (e.g. `actions/homebrew`?)

Copying the `eval` line in every workflow in every repository is not robust against future changes to Homebrew's implementation details. For example, IIRC, Homebrew introduced the global `/home/linuxbrew` directory just a few years ago.

**Comment by Milne4t1qbit** [comment]
I use Astronomer Cloud for Apache Airflow.  The YAML file they provide to their clients uses brew to install their CLI, which then manages the push from GitHub to their repo.  This is detail that I thought had been abstracted away from my workflow.

The GitHub admins could have easily mapped the brew command onto something that provided useful useful information. Also, what was the rationale for removing brew from the path in older ubuntu images that were deprecated?  We all understand that things change, and that "latest" may break.  But to break things that were working and eliminate the possibility of rolling back?  That was not very customer-friendly.

**Comment by nigulable** [comment]
> echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH



> > 1. This change breaks the commitment made in https://github.com/actions/runner-images/tree/main#default-version-update-policy that promises to announce breaking change 1 month in advance.
> > 2. This suggestion just does not work `echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH`
> >    `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` does work, but for the life of me, i cannot get `tfenv` to run after `brew install tfenv` succeeds.
> > 3. The biggest problem is that there is no way for me to change `runs-on` to just use the previous version of the runner!
> 
> After multiple hours, I found a workaround that works, run the following commands in a **single action step**:
> 
> * `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"`
> * `brew install tfenv`
> * `tfenv install terraform`
> 
> Hope this is helps someone.

Im using tgenv  and that wont find terragrunt commands anymore. Anyone knows how to fix this?

**Comment by mrvindu** [comment]
```
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install tfsec

/home/linuxbrew/.linuxbrew/bin/tfsec
``` 
works with above path on different steps

**Comment by mikhailkoliada** [comment]
Hello! We see that lots of customers are corcerned about this specific change,
so we deem necessery to give more context on what has happened.

Starting from version 6.0, homebrew has a dependency on gcc@11 and this dependency is installed automatically together with brew.
Installing these dependencies cause overriding the Ubuntu tools installed from apt and some preinstalled Ubuntu tools.


By default, the Homebrew package manager installs itself to have the highest priority in the system
(i.e. it comes first in the `$PATH` variable). Previosuly we had already tried to move brew to
the end of `$PATH`, but had no [luck](https://github.com/actions/runner-images/pull/789).
Currently, as homebrew is the first choice, it will automatically override some very basic
linux commands, utilities, and libraries such as:

* `locale`
* `ldd`
* `ar`
* `ranlib`

and some others.
Given the nature and importance of the entire linux toolchain ecosystem we decided to drop homebrew from `$PATH` 
for all the Ubuntu versions (including Ubuntu 22.04, due to consistency), 
following the principle of least surprise and to make the environemnts as predictable
as possible.

While we were working with the homebrew project on figuring out ways of fixing some issues we still consider
that not having homebrew in the `$PATH` variable is the safest way to prevent more issues in the future.

We would also like to give more context on the mitigation ways presented in the original announcement, literally:


the `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` will only affect your current workflow's step
as this command is only affecting the currently running session and does not affect any further steps.

Adding homebrew to the [$GITHUB_PATH](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path) variable considered as more robust solution as it makes `brew` available in the scope of the currently running job.

**Comment by alexkfreed** [comment]
> i tried to use `echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH` but it just didnt work. 

For me it worked when I setup the command as its own step. Subsequent steps were then able to find brew.

**Comment by hfhbd** [comment]
Could you please use the blog for such a big breaking change? With the new UI, it shows some blog posts in the upper right corner and media uses announcements of the company blog too, but not a random issue in some repo.

**Comment by David-Trustana** [comment]
I never saw an announcement regarding this change, and filed a support ticket regarding 'brew: command not found'. You responded that you were receiving a large number of support requests and a response (which I never got) would take a while. No wonder. Perhaps better notification would have reduced the number of support requests?

**Comment by mxcl** [comment]
Just saying that @teaxyz would never choose an action that would compel the maintainers of a CI system used by millions to withdraw use of our tooling.

**Comment by ljharb** [comment]
Why not just stick to homebrew 5.0 and avoid breaking everyone??

**Comment by spencerbart** [comment]
I didn't know this happened until a critical piece of our infrastructure stopped working in CI/CD.

**Comment by mikhailkoliada** [comment]
Removed a month ago

**Comment by ingeridhellen** [comment]
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md still says ubuntu-22 includes homebrew.

**Comment by jeremyharisch** [comment]
Using suggested mitigation does not work and fails with 
```
| [command]/usr/bin/bash /run/act/actions/Homebrew-actions-setup-homebrew@master/setup-homebrew/main.sh true false
| Could not find 'brew' command in PATH or standard locations.
```

**Comment by jozefizso** [comment]
The amount of breaking changes in GHA runner images is staggering. For the last 30 days we see randomly failing workflows because GitHub released incompatible images without any communication.
