### ISSUE TITLE
Error running the windows2022 image scripts

### ISSUE THREAD

**Issue by McAdamz** [actions/runner-images#6286]
### Description

Trying to run the latest windows2022 image, but receiving this error:

` vhd: Install docker-wincred
==> vhd: Start-DownloadWithRetry : Cannot bind argument to parameter 'Url' because it is an empty string.
==> vhd: At C:\Windows\Temp\script-632ccdd5-4fa3-a4ae-f996-6902a8f192d7.ps1:25 char:51
==> vhd: + ... ckerCredArchive = Start-DownloadWithRetry -Url $dockerCredDownloadUrl
==> vhd: +                                                    ~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidData: (:) [Start-DownloadWithRetry], ParentContainsErrorRecordException
==> vhd:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Start-DownloadWithRetry`

The "images/win/scripts/Installers/Install-Docker.ps1" is incorrect:

![image](https://user-images.githubusercontent.com/87050311/191863444-d0adb4df-1bfc-4724-95cb-52d110bdedb3.png)

The url "https://api.github.com/repos/docker/docker-credential-helpers/releases/latest" does not contain a *wincred*.zip file anymore:

$dockerCredLatestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/docker/docker-credential-helpers/releases/latest"
$dockerCredLatestRelease.assets.browser_download_url
https://github.com/docker/docker-credential-helpers/releases/download/v0.7.0/docker-credential-wincred-v0.7.0.windows-amd64.exe

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

-

### Is it regression?

yes

### Expected behavior

The image is failing running the build-image.ps1

**Comment by SagiKovaliov** [comment]
Getting the same on win2019 image. On any release tag. Seems like it's not connected to the code

**Comment by al-cheb** [comment]
Hey @McAdamz.
It will be fixed in scope of this https://github.com/actions/runner-images/pull/6287 PR.
