### ISSUE TITLE
[Windows] Add SQL Server Reporting Services PowerShell utilities

### ISSUE THREAD

**Issue by pauloafp** [actions/runner-images#6296]
### Tool name

Windows Server 2022 image

### Tool license

MIT license

### Add or update?

- [ ] Add
- [X] Update

### Desired version

windows-latest

### Brief description of tool

Powershell module ReportingServicesTools for Msft SQL Server Reporting Services and PowerBI

### URL for tool's homepage

https://github.com/microsoft/ReportingServicesTools

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by igorboskovic3** [comment]
Hi @pauloafp we will take a look and get back to you. Thank you

**Comment by pauloafp** [comment]
Hi,

We're not using GitHub Actions. Instead we're using Azure DevOps. Currently is taking almost 2 minutes to install this module on a windows agent, what is more than half of the time it takes to execute the pipeline.

Melhores Cumprimentos,
Best Regards,

Paulo Palma

**Comment by erik-bershel** [comment]
@pauloafp 
I apologise for the misunderstanding on my part. I checked the information and ran a couple of tests. Yes, indeed, in the case of ADO for runtime install, the “idle” time increases by about two minutes. But unfortunately our maintenance policy in this case forces me to leave the installation decision the same. I offer my deepest apologies for wasting your time. Please, feel free to open new issues if you have any other questions or suggestions.
