### ISSUE TITLE
Java has incorrect version names

### ISSUE THREAD

**Issue by XZTDean** [actions/runner-images#6302]
### Description

For Ubuntu images, in the [readme file](https://github.com/actions/runner-images/blob/releases/ubuntu20/20220922/images/linux/Ubuntu2004-Readme.md#java), the version of java 11 is 11.0.16+1 and java 17 is 17.0.4+1. But the correct tag for those two versions is [11.0.16.1+1](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.16.1+1) and [17.0.4.1+1](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.4.1%2B1).

And for [Windows](https://github.com/actions/runner-images/blob/releases/win22/20220919/images/win/Windows2022-Readme.md#java) and [macOS](https://github.com/actions/runner-images/blob/releases/macOS-11/20220918/images/macos/macos-11-Readme.md#java) images, the versions name are 11.0.16+101 and 17.0.4+101. 

When executing `java --version`, it will also display the correct version tags 11.0.16.1+1 and 17.0.4.1+1. ([demo](https://github.com/XZTDean/action-java-demo/actions/runs/3120785600))

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Ubuntu: https://github.com/actions/runner-images/blob/ubuntu20/20220905.1/images/linux/Ubuntu2004-Readme.md
Windows: https://github.com/actions/runner-images/blob/win22/20220919.1/images/win/Windows2022-Readme.md
macOS: https://github.com/actions/runner-images/blob/macOS-11/20220918.1/images/macos/macos-11-Readme.md

### Is it regression?

No

### Expected behavior

Version is 11.0.16.1+1 and 17.0.4.1+1

### Actual behavior

* Version is 11.0.16+1 and 17.0.4+1 on Ubuntu
* Version is 11.0.16+101 and 17.0.4+101 on Windows and macOS

### Repro steps

1. Find version name in the readme file
2. Execute `java --version` in runner

**Comment by mikhailkoliada** [comment]
@XZTDean Hi!

Well, they are not really wrong, on macOS and Windows we are parsing semver, as it is easier to track changes down, for linux we are using `-fullversion` and upstream is using `-version`. So the best course of action here is to switch linux to dosplay semver, too for consistency.

**Comment by mikhailkoliada** [comment]
Hmm, there is no reliable way compare these versions at all as distributions are too different and API do not provide all the specs, close for now as it is technically not a bug, but might be we will come up with some better solution later :/
