### ISSUE TITLE
Incorrect Packer version

### ISSUE THREAD

**Issue by dipesharora** [actions/runner-images#6303]
### Description

Version of packer in the Readme is mentioned as 1.8.3, but during runtime, packer version output shows its 1.5.4

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
Version: 20220905.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20220905.1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220905.1

### Is it regression?

No

### Expected behavior

Build should succeed with Packer version 1.8.3

### Actual behavior

Error during running packer commands
Failed to parse template: Error parsing JSON: invalid character '#' looking for beginning of value
At line 1, column 1 (offset 1):
    1: #
      ^

### Repro steps

Run packer commands with hashicorp/packer-github-actions@v0.2.0 and HCL format of template. Build will fail with Packer version 1.5.4

**Comment by dipesharora** [comment]
Ubuntu 22.04 runner also has same issue
Image: ubuntu-22.04
Version: 20220919.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20220919.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20220919.1

**Comment by mikhailkoliada** [comment]
@dipesharora Hello!

I see this action does not rely on a packer version in the image, it simply runs [docker](https://github.com/hashicorp/packer-github-actions/commits/master/Dockerfile) container with a specific version of packer. Even master version of the action still has 1.8.2 while in the image it is 1.8.3

**Comment by dipesharora** [comment]
Hi, yes that's correct. I did more investigation and found the same that the action has a pinned version of Packer at 1.5.4.
