### ISSUE TITLE
Add qemu-user-static

### ISSUE THREAD

**Issue by Kojoley** [actions/runner-images#6304]
### Tool name

qemu-user-static

### Tool license

GPLv2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

no particular version

### Approximate size

13MB

### Brief description of tool

A generic and open source machine emulator and virtualizer.

### Provide a basic test case to validate the tool's functionality.

```bash
To run arm/ppc/mips Docker containers by simply adding `container: 'multiarch/debian-debootstrap:arm64-bullseye'`.
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

https://github.com/actions/runner-images/pull/119

**Comment by al-cheb** [comment]
Hello, @Kojoley.
Considering the installation time, we wouldn't like to bake this tool into the image for now.

**Comment by adilhusain-s** [comment]
@al-cheb 
can we have custom property or something to install the desired package  in runner image before launching?



jobs:
  myjob:
    runs-on: ubuntu-latest 
    packageToinstall: qemu, docker ....


this way, we don't have to install have to bake the packages in to runner images.
if you agree, I can work on this.
hoping for your response....
