### ISSUE TITLE
Build Pipeline downloading multiple version of snowflake and gets failed

### ISSUE THREAD

**Issue by omptech** [actions/runner-images#6312]
### Description

Suddenly Build Pipeline downloading multiple version of snowflake from function app requirement.txt and gets failed, when specifying like (snowflake-connector-python) but when specifying with version like (snowflake-connector-python==2.7.9) So it works.

Dont know why it suddenly happened

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

NA

### Is it regression?

NA

### Expected behavior

It should install one version

### Actual behavior

Install multiple version

### Repro steps

NA

**Comment by al-cheb** [comment]
Hey @omptech.
Please provide  minimal steps how to reproduce the issue.

**Comment by omptech** [comment]
HI @al-cheb 

To reproduce the issue please follow below steps:

1. Download the requirement.txt file which I have already attached.
[requirement.txt](https://github.com/actions/runner-images/files/9657507/requirement.txt)

2.Run the below command, But before that change the requirement.txt path according to path where you put it.
install --target="./.python_packages/lib/site-packages" -r ./PythonFunction\WebForm\requirements.txt

if you do not see any multiple version installation so change the python version to 3.9 after that see that there will be multiple version downloaded for snowflake-connector-python.

**Comment by al-cheb** [comment]
@omptech , I can reproduce the issue on a clean ubuntu vm with python 3.9 and pip > 20.3 and it's by design - https://pip.pypa.io/en/stable/topics/dependency-resolution/#backtracking

> This can look like pip downloading multiple versions of the same package, since pip explicitly presents each download to the user. The backtracking of choices made during is not unexpected behaviour or a bug. It is part of how dependency resolution for Python packages works

Workarounds:
1. [Reduce the number of versions pip is trying to use](https://pip.pypa.io/en/stable/topics/dependency-resolution/#reduce-the-number-of-versions-pip-is-trying-to-use)
`snowflake-connector-python >= 2.8.0`
3. Install snowflake-connector-python package first:
```
- run: pip3 install snowflake_connector_python
- run: pip3 install -r requirements.txt
```


Close as external.

**Comment by omptech** [comment]
Hi @al-cheb 
The actual problem is not with downloading multiple version. But it gets failed during downloading multiple version in Ubuntu 20.04 So I want to know why it gets failed?

**Comment by al-cheb** [comment]
> Hi @al-cheb The actual problem is not with downloading multiple version. But it gets failed during downloading multiple version in azure devops (agent: Ubuntu 20.04) So I want to know why it gets failed?

There is no issue with downloading, the issue is with resolving dependecies.

**Comment by omptech** [comment]
@al-cheb Yes, but in my case Before the requirement.txt which I attached was working fine but right now it started getting failed. How can I track why it is not working now ?
I have resolved issue already by specifying latest version. Right now I just want to find the root cause

**Comment by al-cheb** [comment]
> @al-cheb Yes, but in my case Before the requirement.txt which I attached was working fine but right now it started getting failed. How can I track why it is not working now ? I have resolved issue already by specifying latest version. Right now I just want to find the root cause

You can ask this question in [https://github.community/c/github-actions/41](https://github.community/c/github-actions/41).

**Comment by al-cheb** [comment]
> > @al-cheb Yes, but in my case Before the requirement.txt which I attached was working fine but right now it started getting failed. How can I track why it is not working now ? I have resolved issue already by specifying latest version. Right now I just want to find the root cause
> 
> You can ask this question in [GitHub Actions Community Forum](https://github.community/c/github-actions/41).
