### ISSUE TITLE
Add alpine:3.16

### ISSUE THREAD

**Issue by Kielek** [actions/runner-images#6315]
### Tool name

alpine:3.16

### Tool license

https://pkgs.alpinelinux.org/packages

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.16

### Brief description of tool

Add alpine:3.16 to cached images both for ubuntu 20.04 and 22.04.
For now, there are only older versions.

### URL for tool's homepage

https://alpinelinux.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes (if needed)

**Comment by ddobranic** [comment]
hello @Kielek, we will add new version of alpine. thank you!

**Comment by erik-bershel** [comment]
@Kielek 
Hello! Cached images with Alpine 3.16 for Ubuntu 20.04 and 22.04 will be deployed next week.

**Comment by mikhailkoliada** [comment]
Deployed now.
