### ISSUE TITLE
Upgrade JSON image definitions to HCL2

### ISSUE THREAD

**Issue by BenedekFarkas** [actions/runner-images#6318]
### Description

It's not actually a bug report, more like a feature request, but this template has the least irrelevant fields.

All the Packer image definitions (except Ubuntu 22.04) are using the old, JSON format, but HCL2 is now the recommended syntax according to the [documentation](https://developer.hashicorp.com/packer/guides/hcl):

> Note: Packer version 1.5.0 introduced support for HCL2 templates as a beta feature. As of version 1.7.0, HCL2 support is no longer in beta and is the preferred way to write Packer configuration(s).

Upgrading existing image definitions can achieved with a single command, for example:
`packer hcl2_upgrade windows2022.json`

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
close as https://github.com/actions/runner-images/discussions/5988

**Comment by BenedekFarkas** [comment]
Ah, I haven't found that discussion, because I searched for `hcl2`, not `hcl`, my bad.

So according to the answer, you'd consider upgrading given there's an accompanying PR. Is that still the case? If yes, please reopen the issue and I'll create a PR with the templates converted.
