### ISSUE TITLE
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.

### ISSUE THREAD

**Issue by since81** [actions/runner-images#6333]
### Description

About two weeks ago my pipelines were working, yesterday I tried to run but got error for first pwsh task in container:

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "[http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/fd8ff246ac5cd257090fd89d1c0e2ba694ee3b594be50704744fdb93928b5911/json"](http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/fd8ff246ac5cd257090fd89d1c0e2ba694ee3b594be50704744fdb93928b5911/json%22): open //./pipe/docker_engine: The system cannot find the file specified.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220925.1

### Is it regression?

20220905.1

### Expected behavior

pwsh task executed

### Actual behavior

```
  - pwsh: |
      $tag = '1.0.0'
      Write-Host "Create a build TAG '$tag'"
      Write-Host "##vso[build.addbuildtag]$tag"
    displayName: Set build tag

```

```
Starting: Print environment versions
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "[http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/fd8ff246ac5cd257090fd89d1c0e2ba694ee3b594be50704744fdb93928b5911/json"](http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/fd8ff246ac5cd257090fd89d1c0e2ba694ee3b594be50704744fdb93928b5911/json%22): open //./pipe/docker_engine: The system cannot find the file specified.
##[error]Exit code 1 returned from process: file name 'C:\Windows\system32\docker.EXE', arguments 'exec -i   fd8ff246ac5cd257090fd89d1c0e2ba694ee3b594be50704744fdb93928b5911 C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.
Finishing: Print environment versions
```

### Repro steps

run pipeline:

```
pool:
  vmImage: "windows-2019"
container: "some_windows_container"


steps:
  - pwsh: |
      $tag = '1.0.0'
      Write-Host "Create a build TAG '$tag'"
      Write-Host "##vso[build.addbuildtag]$tag"
    displayName: Set build tag
```

**Comment by al-cheb** [comment]
Hey @since81. 
We will take a look at it.

**Comment by al-cheb** [comment]
@since81, What image do you use for container?

```
pool:
  vmImage: 'windows-2019'

container: mcr.microsoft.com/windows/servercore:ltsc2019

steps:
- powershell: $PSVersionTable
```
![image](https://user-images.githubusercontent.com/47745270/193262431-84ae9469-4524-42ee-8836-248fbd983cce.png)
![image](https://user-images.githubusercontent.com/47745270/193262384-ab5f9cbd-12c0-4b03-af80-a1b7afb688f7.png)

**Comment by since81** [comment]
It is build  on top of
mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
plus visual studio 2017
plus java 11
plus specific software addon to visual studio 2017

**Comment by al-cheb** [comment]
> It is build on top of mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 plus visual studio 2017 plus pwsh 7.2.6 plus java 11 plus specific software addon to visual studio 2017

Could you share it?

**Comment by since81** [comment]
Container is successfully initialized for me also, two first steps of checkout is working, but first pwsh failed.

![image](https://user-images.githubusercontent.com/15886102/193266929-a60b00e3-3015-4c93-a2cd-8032fbd674fa.png)

**Comment by al-cheb** [comment]
> It is in a private repo, I do not know how to copy/past it.
> 
> Can you try with? mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

Works fine:

![image](https://user-images.githubusercontent.com/47745270/193269507-409da000-2639-464f-a1cb-c8b7b873028d.png)
![image](https://user-images.githubusercontent.com/47745270/193269591-36ec8a86-e9f4-40af-b43d-612517de8f31.png)

**Comment by since81** [comment]
I tried, image by image.
this working: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
next layer also working: vs2017 + pwsh

but last is not, 
will try to get a clue what is a difference.

**Comment by since81** [comment]
I do not know what, but something changed in windows-2019 image.
I cannot run any image tags which was working before.

Also, I cannot build new image, which I can build on September 19.

**Comment by al-cheb** [comment]
The latest huge change was - https://github.com/actions/runner-images/issues/6181

**Comment by al-cheb** [comment]
@since81, any updates?

**Comment by since81** [comment]
Hi @al-cheb ,

I am trying to reproduce error with same binaries of docker which ms are using in azure pipelines.
And it is working locally.

I will upload today images and will provide access for you to tests, if you do not mind.

My assumption: can it be because of a big image of windows containers:
REPOSITORY                                   TAG                              IMAGE ID       CREATED          SIZE
_development.azurecr.io/visualstudio            15                               26419d1ea151   24 hours ago     12.2GB
_development.azurecr.io/buildimage            1.2.3                            30022df1b543   2 weeks ago      16GB
mcr.microsoft.com/dotnet/framework/runtime   4.8-windowsservercore-ltsc2019   4e1a409f4ff5   3 weeks ago      8.16GB

16GB, but we have only 16GB of free space on ms hosted agents?

**Comment by since81** [comment]
Hi @al-cheb,

can you please try with this image, it was working before?
c07970development.azurecr.io/edbt:7.0.7

**Comment by al-cheb** [comment]
@since81, I was able to reproduce the issue locally. Looks like the current docker version contains a bug that was fixed in the latest version, I have prepared a PR  -  https://github.com/actions/runner-images/pull/6360. This fix we are planning to deploy next week.

**Comment by since81** [comment]
Hi @al-cheb,

thank you for your help and effort.

do you still have plan release new images this week?

**Comment by al-cheb** [comment]
@since81, The Win19 deployment is on track - https://github.com/actions/runner-images/pull/6406. I hope we will finish the deployment by Tuesday.

**Comment by since81** [comment]
Hi @al-cheb, with new vetsion of image everything working fine.
Thank you!

**Comment by magnus-book-sb** [comment]
Hi 
I am new to docker and just tried to follow the tutorial from docker.com and got the exact same issue, when running
` docker build -t getting-started .`
as described here https://docs.docker.com/get-started/02_our_app/

Error is
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=getting-started&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.

How should I solve this?

**Comment by al-cheb** [comment]
> getting-started

Please attach Dockerfile.

**Comment by magnus-book-sb** [comment]
This is the dockerfile that was instructed to be created in the tutorial. I had to rename it to .txt since github does not allow plain dockerfile to be attached.

[Dockerfile.txt](https://github.com/actions/runner-images/files/9918798/Dockerfile.txt)

**Comment by al-cheb** [comment]
> This is the dockerfile that was instructed to be created in the tutorial. I had to rename it to .txt since github does not allow plain dockerfile to be attached.
> 
> [Dockerfile.txt](https://github.com/actions/runner-images/files/9918798/Dockerfile.txt)

Currently, it's not possible to run linux containers on Windows hosted agents.

**Comment by al-cheb** [comment]
> So what am I doing wrong? How can I run the tutorial?

You should use Ubuntu hosted agents to run linux containers.

**Comment by magnus-book-sb** [comment]
> You should use Ubuntu hosted agents to run linux containers.
Sorry I am new to this and I am not following, do you mean I cannot use windows at all to run docker containers? The following command 
`docker version`
also gives me the same error, is that expected?

**Comment by al-cheb** [comment]
> > You should use Ubuntu hosted agents to run linux containers.
> 
> Sorry I am new to this and I am not following, do you mean I cannot use windows at all to run docker containers? The following command `docker version` also gives me the same error, is that expected?

Please share a link of the failed build.

**Comment by johnmccrae** [comment]
Hi, I just installed the docker client via chocolatey on Windows 11 and got the same error. I'm just starting the troubleshooting so I'm not sure if I'm late to a solved problem or not
