### ISSUE TITLE
.NET Core SDK 6.0.401 is not being installed on windows 2019

### ISSUE THREAD

**Issue by AHuusom** [actions/runner-images#6334]
### Description

For some reason .NET Core SDK 6.0.401 is noget being installed on the windows 2019 repository.

All the other repositories has it.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest windows 2019

### Is it regression?

latest windows 2019

### Expected behavior

it getting installed

### Actual behavior

not getting installed

### Repro steps

Just check the repository under .net core sdk.

**Comment by al-cheb** [comment]
Hey @AHuusom.
Please take a look at the comment - https://github.com/actions/runner-images/issues/4424#issuecomment-1012911541

Our recommendation is always to use tasks to install .Net in runtime:
1. [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) - Azure DevOps
2. [setup-dotnet](https://github.com/actions/setup-dotnet) - GitHub

**Comment by mattjohnsonpint** [comment]
@al-cheb - that doesn't align at all with what was done for the Ubuntu, Mac, and `windows-2022` images - all of which have .NET 6.0.401 now.  It's only `windows-2019` that doesn't.  Why should it be any different?

Also, the [Support Policy](https://github.com/actions/runner-images#software-and-image-support) says explicitly that .NET Core will have the installation strategy of:

> "2 latest LTS versions and 1 latest version. For each feature version only latest patch is installed"

The `windows-2019` image is getting .NET 5 installed, which is out of support.  .NET 6 and 3.1 are the two LTS versions.
