### ISSUE TITLE
[!] Cannot find an installed Xcode satisfying '13.0' using MacOS 11.7

### ISSUE THREAD

**Issue by bouthainaghachem** [actions/runner-images#6335]
### Description

Hello, 

I'm facing issues with new image version runner updated two days ago under MacOS 11.7 (ref: https://github.com/actions/runner-images/blame/main/images/macos/macos-11-Readme.md)

It's mentionned under the documentation that MacOS 11 still supporting XCode 13.0 version. am I wrong ?
I'm setting under my fastlane file the xcversion(version: "13.0")

but I'm getting the following error : [!] Cannot find an installed Xcode satisfying '13.0'

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

System Version: macOS 11.7 (20G817)
Kernel Version: Darwin 20.6.0
Image Version: 20220925.1

### Is it regression?

Version: 20220918.1

### Expected behavior

As in the documentation, the expected behavior : it should work with XCode 13 as it's set under the available xcode versions, below link for reference :
https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md

### Actual behavior

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | xcversion                  | 0           |
+------+----------------------------+-------------+

[16:24:26]: fastlane finished with errors

[!] Cannot find an installed Xcode satisfying '13.0'
##[error]Bash exited with code '1'.
Finishing: Build app

### Repro steps

None

**Comment by al-cheb** [comment]
Hey @bouthainaghachem.
close as external https://github.com/xcpretty/xcode-install/issues/204
