### ISSUE TITLE
Update Docker Compose v2 to 2.11.2+

### ISSUE THREAD

**Issue by strophy** [actions/runner-images#6337]
### Description

Docker Compose v2 2.11.0 and 2.11.1 contains a bug that prevents built images from being tagged properly. The bug is fixed in 2.11.2

Discussion: https://github.com/docker/compose/issues/9856
Resolution: https://github.com/docker/compose/pull/9862

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220922.2
https://github.com/dashevo/platform/actions/runs/3163104789/jobs/5150340466

### Is it regression?

Yes, but no link because I only encountered the bug while reverting some code

### Expected behavior

Compose should tag images

### Actual behavior

Compose does not tag imgaes

### Repro steps

Try to build an image from a compose file and see if it is properly tagged with `docker image ls`

**Comment by mikhailkoliada** [comment]
will be deployed this week

**Comment by al-cheb** [comment]
The new images with Docker Compose v2 2.11.2 on board have been deployed.
