### ISSUE TITLE
Update Microsoft.Graph module to 1.12.2

### ISSUE THREAD

**Issue by nes-nagashin** [actions/runner-images#6338]
### Tool name

Microsoft.Graph

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.12.2

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Will be deployed this week

**Comment by al-cheb** [comment]
The new images with Microsoft.Graph 1.12.2 have been deployed.
