### ISSUE TITLE
vcpkg install fails when tries to restore cached ports on OSX

### ISSUE THREAD

**Issue by AenBleidd** [actions/runner-images#6344]
### Description

From time to time when I run `vcpkg install` and restore cached binaries, build just fails with the next error:
```
No such file or directory
```
I have to rerun the same build, and after several retries it succeeds.
It's not some particular vcpkg port that is failiing, but different one.
I assume this happens because it tries to restore a lot of small ports with big amount of files.

Ref: https://github.com/BOINC/boinc-apps/actions/runs/3166911630/jobs/5159703089

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-11
Version: 20220925.1

### Is it regression?

No

### Expected behavior

Build succeeds from the first try

### Actual behavior

It takes several retries to get successful builf

### Repro steps

You need to have a cmake project that uses vcpkg to handle dependencies, and you need to include boost and cache dependencies somewhere outside of runner (in my case this is AWS S3), see the reference above.

**Comment by mikhailkoliada** [comment]
@AenBleidd Could you please provide the most minimalistic workflow to reproduce the issue? Your referenced run shows that you need to define a CXX compiler, but it is a bit counter-intuitive.

**Comment by AenBleidd** [comment]
I can try to create a new project and recreate all this, but currently you can see that this happens when doing 'vcpkg install' when boost libraries are cached and are in restore phase.

**Comment by dmitry-shibanov** [comment]
Hello @AenBleidd. Did you reproduce the issue on the minimum project ?

**Comment by AenBleidd** [comment]
@dmitry-shibanov, had no time to do that yet. I'm still experiencing this issue regularly on the repo I linked above. Hopefully will have time to make a minimal project to reproduce this issue later this week.

**Comment by AenBleidd** [comment]
I made a simple repo to reproduce this issue.
Here's the faulty run: https://github.com/AenBleidd/osx_vcpkg_github_actions_test/actions/runs/3281214507/jobs/5403428505
It's not reproducible always, sometime you need to rerun it several times.
Important steps:
- you need to setup AWS to store vcpkg binary cache
- you need to have cache present on AWS, because it doesn't happen when cache is not present on AWS

**Comment by AenBleidd** [comment]
@mikhailkoliada, @dmitry-shibanov please check my last comment

**Comment by AenBleidd** [comment]
@mikhailkoliada, @dmitry-shibanov, @vsafonkin,
Any updates on this? Do you need smth additional to reproduce this that I could help you with?

**Comment by BillyONeal** [comment]
Unfortunately, if it's AWS specific, that was added by a contributor and we don't have a great way to test/verify it. However, if it's OS specific and other caching mechanisms work, it sounds more like a network problem than a vcpkg problem?

**Comment by AenBleidd** [comment]
It's an OS specific issue, you can check the log here: https://github.com/AenBleidd/osx_vcpkg_github_actions_test/actions/runs/3281214507/jobs/5403428505.
Not sure if this issue could be detected and handled from the vcpkg itself.
At least, maybe you could give some insights to the team how to continue with this issue?
Also, I can imagine this issue could also be reproduced even with the local cache, you just need to catch necessary conditions.

**Comment by BillyONeal** [comment]
>It's an OS specific issue

I'm saying OS may be a proxy for network, since OS selection also means datacenter selection in a CI system like Actions. If, for example, we asked curl to download a zip out of a cache, and it downloads a 0 byte file or something bogus like a redirect page instead of an actual zip file, that may cause something like this. We don't have the ability to hash check cache hits.

>At least, maybe you could give some insights to the team how to continue with this issue?

We would need more context as to what happened, unfortunately. The logs don't tell us what happened. Running with `--debug` may help run down the cause?

>Also, I can imagine this issue could also be reproduced even with the local cache, you just need to catch necessary conditions.

It isn't something we have seen so we would need someone who is involved with the system where it's failing to figure out what happened.

**Comment by AenBleidd** [comment]
This is not a network issue but mostly looks like a filesysten issue:
```
Installing 7/81 boost-static-assert:x64-osx...
No such file or directory
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:868 (message):
-- Running vcpkg install - failed
  vcpkg install failed.  See logs for more information:
-- Configuring incomplete, errors occurred!
  /Users/runner/work/osx_vcpkg_github_actions_test/osx_vcpkg_github_actions_test/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)
```

**Comment by BillyONeal** [comment]
>This is not a network issue but mostly looks like a filesysten issue:

If the cache entry we download is bogus that would manifest as a downstream filesystem issue, and there's a 'No such file or directory' message before we get to CMake being confused.

**Comment by AenBleidd** [comment]
Ok, is there a way to run vcpkg with `--debug` option from the cmake call?

**Comment by BillyONeal** [comment]
To clarify, the way this works is, for everything that is a cache hit, when you see:

```
Restored 81 package(s) from AWS in 3.587 min. Use --debug to see more details.
```

that means we downloaded those zips from AWS and extracted them to `<the packages directory>/<port name>_<triplet>`, then later on for anything that was a cache hit we assume the packages directory result is identical to what building would have done. So if the extracted contents aren't right or were interfered with by A/V tools or similar I'm not sure what would happen...

**Comment by BillyONeal** [comment]
> Ok, is there a way to run vcpkg with `--debug` option from the cmake call?

Hmmmmm... I think `VCPKG_INSTALL_OPTIONS` will do it? Our docs need to be better :(

https://github.com/microsoft/vcpkg/blob/6e4fbee0d1e6daffaab50f4c055cd3ccfd3d929a/scripts/buildsystems/vcpkg.cmake#L515

**Comment by BillyONeal** [comment]
>[DEBUG] Failed to open: /Users/runner/work/osx_vcpkg_github_actions_test/osx_vcpkg_github_actions_test/vcpkg/packages/boost-config_x64-osx/CONTROL
No such file or directory

That means the cache entry is toast for some reason?

**Comment by Talalgmel** [comment]
Installing 5/81 boost-config:x64-osx...
[DEBUG] Failed to open: /Users/runner/work/osx_vcpkg_github_actions_test/osx_vcpkg_github_actions_test/vcpkg/packages/boost-config_x64-osx/CONTROL
No such file or directory
[DEBUG] /Users/runner/work/1/s/src/vcpkg/install.cpp(330): 
[DEBUG] Time in subprocesses: 317016929 us
[DEBUG] Time in parsing JSON: 3229 us
[DEBUG] Time in JSON reader: 2183 us
[DEBUG] Time in filesystem: 36561 us
[DEBUG] Time in loading ports: 9556 us
[DEBUG] Exiting after 5.116 min (306911645 us)
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:868 (message):
-- Running vcpkg install - failed
  vcpkg install failed.  See logs for more information:
-- Configuring incomplete, errors occurred!
  /Users/runner/work/osx_vcpkg_github_actions_test/osx_vcpkg_github_actions_test/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)

**Comment by AenBleidd** [comment]
> >[DEBUG] Failed to open: /Users/runner/work/osx_vcpkg_github_actions_test/osx_vcpkg_github_actions_test/vcpkg/packages/boost-config_x64-osx/CONTROL
> 
> No such file or directory
> 
> 
> 
> That means the cache entry is toast for some reason?

Looks like. But how to debug and fix that? There is no error in archive on AWS because on retry it succeeds. There is no error on download (at least not reported). There is no error on zip unpacking (also not reported).

Any idea what else to try here?
Just to note: I've never seen this on any other OS. So for me this looks like an OSX-specific issue.

**Comment by BillyONeal** [comment]
> Looks like. But how to debug and fix that? There is no error in archive on AWS because on retry it succeeds. There is no error on download (at least not reported). There is no error on zip unpacking (also not reported).

Unfortunately, I do not have great ideas on figuring out what happened.

> There is no error on download (at least not reported).

That's why my initial guess was network stuff, e.g. some form of reverse proxy in front of the mac machines that's not returning the correct content. We're only going to report an error if the download actually fails, not if the content is nonsense.

> There is no error on zip unpacking (also not reported).

We shell out to "unzip" for that :/

> Just to note: I've never seen this on any other OS. So for me this looks like an OSX-specific issue.

It sounds like OSX *and* Actions specific though, unless anyone can get it repro'd locally.

Unfortunately I don't have any experience with AWS behavior to help much. If this were a local machine I'd be rerunning with `--debug`, figuring out which cache entry was toast, and inspecting that.

**Comment by AenBleidd** [comment]
Ok, I'll try to catch this error again on CI and upload to AWS the complete state of vcpkg folder to make further investigation

**Comment by AenBleidd** [comment]
Ok, I catched this error and uploaded a full vcpkg folder.
From which I can see, that this time `boost-chrono` failed, and its folder in `packages` completely empty.
Unfortunately, downloaded zip file was removed after extraction, (and both download from AWS and extraction from archive return 0 error code).
@BillyONeal, any way to keep zip file?

**Comment by BillyONeal** [comment]
There does not appear to be a way to keep the zip file.

@ras0219-msft suggests that this may be https://github.com/microsoft/vcpkg-tool/pull/695 ?

Are you comfortable trying to build Thomas1669's branch from source or do we need to try an official release to see if it works

Ah, I stand corrected, we shell out to *awscli* for this, not curl like the other backends.

**Comment by AenBleidd** [comment]
I can try to build from this branch, no problem. Also, I can try to dig aake a customization to keep downloaded zip archive. After that we could think about further experiments.

**Comment by Thomas1664** [comment]
I finally fixed the issue in https://github.com/microsoft/vcpkg-tool/pull/695 . In the meantime, you can work around this issue by setting the environment variable `VCPKG_MAX_CONCURRENCY` to `1`. This will prevent multi-threading.

**Comment by AenBleidd** [comment]
@Thomas1664, setting max concurrency doesn't really fix the issue for me: https://github.com/AenBleidd/osx_vcpkg_github_actions_test/actions/runs/3582623975/jobs/6027367014

**Comment by Thomas1664** [comment]
Your CI failure is unrelated to `popen`:

```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:869 (message):
-- Running vcpkg install - failed
  vcpkg install failed.  See logs for more information:
-- Configuring incomplete, errors occurred!
  /Users/runner/work/osx_vcpkg_github_actions_test/osx_vcpkg_github_actions_test/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

**Comment by dsame** [comment]
Hello @AenBleidd, 

That we see here is definitely CMake starts working before the S3 download has completed - this is why it fails to restore the packages randomly.

The root cause might be a combination of some osx aws client  bugs with the low performance of OSX VMs with the virtualization implementations. As a first guess it might be known problem with the OSX spare files.

But the main problem is AWS S3 protocol does not seem to be mentioned as supported by vcpkg at all: https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md

If the suggestion is correct the workarounds might be

1. do not use AWS S3
2. Download cache zip in its own step and use [files source ](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#valid-source-strings-source) as a cache
3. Not sure if it possible but i'd try to switch from zip to tar (pay attention OSX has 2 tar implementation: GNU and native. In case if native tar keeps failing and GNU tar does not - we definitely face spare files problem)
3. Run restore package in the loop until it succeeded

Does it sound reasonable?

**Comment by AenBleidd** [comment]
> But the main problem is AWS S3 protocol does not seem to be mentioned as supported by vcpkg at all

This is not a problem. Yes, it's experimental, that's true, but it works fine for quite a long time on all OSs witout any issues.

> do not use AWS S3

Not an option, because there is not other 'cheap' option to do vcpkg binary cache/restore in the same effective way

> Download cache zip in its own step and use [files source ](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#valid-source-strings-source)as a cache

Not an option as well. When vcpkg does the build, it asks AWS S3 for the files that it will really use, not the entire bunch of file that are stored on AWS S3. So download everything is much  longer and more expensive (cause you pay for incoming/outcoming traffic).

> Not sure if it possible but i'd try to switch from zip to tar

vcpkg in this case use only zip for this purpose. Switch to tar will require change in vcpkg codebase.

> Run restore package in the loop until it succeeded

This requires change on vcpkg side, and it's not an easy change because you never knows what is the real reason of the failure and do you still need to retry or it's worthless.

> Does it sound reasonable?

Not sure. But since a while I don't see this issue happening anymore. 
So either last fix from @Thomas1664 helps or it was really an infrastructure issue on GitHub Actions that is now resolved but everything looks stable again, that is why I'm closing this ticket for now.

Merry Christmas and a Happy New Year.
