### ISSUE TITLE
Update github cli to 2.16.1

### ISSUE THREAD

**Issue by markododa** [actions/runner-images#6345]
### Tool name

gh

### Tool license

Its your own product

### Add or update?

- [ ] Add
- [X] Update

2.16.0 has a bug breaks calling workflows https://github.com/cli/cli/issues/6328

### Desired version

2.16.1

### Brief description of tool

This is not an add request but 2.16.1 solves an issue with running workflows https://github.com/cli/cli/issues/6328

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Will be deployed this week

**Comment by al-cheb** [comment]
The new images with gh 2.16.1 on board have been deployed.
