### ISSUE TITLE
Long path fails on larger Windows runner, works on standard one

### ISSUE THREAD

**Issue by Piedone** [actions/runner-images#6348]
### Description

I experienced this while trying out the larger runners. However, I don't know if this is due to the larger runners doing something different behind the scenes, or due to the only apparent difference I can observe, the difference in the runner image version. Also, if this is rather something for the `actions/checkout` team then let me know.

- Git checkout of [this repo](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions), with [this workflow](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/d27e9a805fe6a3dd270a0d03b9cd3fc65fce88f4/.github/workflows/build-and-test.yml) works under a standard GitHub-hosted runner, see run [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177282486/jobs/5177539731). Note that the image version is 20220925.1.
- Git checkout of the same repo, with [this workflow](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/29cdb88425b1dbf6fa8260b1d3f14e5699a01bc8/.github/workflows/build-and-test.yml) fails with the below error, see run [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177185558/jobs/5177441264). Note that the image version is 20221002.2.

```
  Error: error: unable to create file Lombiq.Hosting.Azure.ApplicationInsights.Tests.UI/Extensions/OrchardCoreUITestExecutorConfigurationExtensions.cs: Filename too long
  Error: fatal: Unable to checkout 'ba3827afb5fc22610f68875f0b0001c3190fa866' in submodule path 'src/Modules/Lombiq.Hosting.Azure.ApplicationInsights'
```

I wouldn't expect such a difference between the standard and larger runners, or between the two image version.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image version: 20221002.2
Run: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177185558/jobs/5177441264

### Is it regression?

20220925.1

### Expected behavior

The new image works like the older one, and checkout of the repository works.

### Actual behavior

See above.

### Repro steps

See above.

**Comment by al-cheb** [comment]
Hey @Piedone.
Could you try using `git config --system core.longpaths true` command before the checkout step? I see that the paths are slightly different between agents: `hosted(D:/a)` vs `larger-runner(C:/actions-runner/work)`.

**Comment by Piedone** [comment]
Thank you for your quick reply.

Indeed, in the meantime, the working directory is also different, and Git `longpaths` fixes this, see [this run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177521321/jobs/5178056936) (which fails for some other reason).

However, shouldn't the large runner use the same (or at least a similarly short) checkout directory?

**Comment by al-cheb** [comment]
@maxim-lobanov, do you have any thoughts?

**Comment by maxim-lobanov** [comment]
For Linux, Larger Runners have the same layout as Standard Runners
For Windows, layout is a bit different, we use C drive and `C:/actions-runner/work` directory instead `D:/a`

@al-cheb do you think we can apply `git longpaths` configuration on image level by default? AFAIK, we [already have](https://github.com/actions/runner-images/blob/1def28243de16d4b555a9475f871bac5aad465fa/images/win/scripts/Installers/Initialize-VM.ps1#L70) long paths enabled on Windows level.

**Comment by al-cheb** [comment]
> @al-cheb do you think we can apply `git longpaths` configuration on image level by default? AFAIK, we [already have](https://github.com/actions/runner-images/blob/1def28243de16d4b555a9475f871bac5aad465fa/images/win/scripts/Installers/Initialize-VM.ps1#L70) long paths enabled on Windows level.

We shouldn't to apply this fix - https://github.com/actions/runner-images/pull/4915#discussion_r788654504

**Comment by maxim-lobanov** [comment]
@Piedone, I am looking at changing working directory for agent to be `C:\a`. It can take a couple of days to test it and make sure that there is no regression. I will post update at the begin of next week.

**Comment by Piedone** [comment]
Great, thank you.

**Comment by maxim-lobanov** [comment]
@Piedone , changes are fully deployed. Agent working directory should be `C:\a`.

One note, there may be idle VMs waiting to pick up jobs which don't have fix applied yet. So you may need to trigger 1-2 extra jobs to make sure that all workflows are run on VMs with fix.

Will keep the issue opened until confirmation that issue is resolved.

**Comment by Piedone** [comment]
Thank you for fixing this on short notice, it works!

**Comment by maxim-lobanov** [comment]
Nice. Thank you for reporting these two issues and providing simple repro steps.
Larger Runners use a bit different infrastructure from Standard Runners so it is expected that some VM configuration can be different. We are working to make it as consistent with standard runners as possible to ensure smoothly migration from Standard Runners to Larger Runners. Please report any issues.

**Comment by Piedone** [comment]
Great, thank you.

**Comment by Piedone** [comment]
BTW this also fixed another issue later in our build (when running UI tests) that I suspected was due to long paths too. So great!
