### ISSUE TITLE
SQL Server installation (startup?) mostly fails on larger Ubuntu runners

### ISSUE THREAD

**Issue by Piedone** [actions/runner-images#6349]
### Description

Installing and starting up SQL Server on the larger runners fails under Ubuntu. The exact same code works (has been working for the past half year) on standard runners.

Code in question, executed with `pwsh`:

```pwsh
docker pull mcr.microsoft.com/mssql/server &&
docker run --name sql2019 `
    --env 'ACCEPT_EULA=Y' `
    --env 'SA_PASSWORD=Password1!' `
    --publish 1433:1433 `
    --detach 'mcr.microsoft.com/mssql/server:2019-latest' &&
docker exec --user 0 sql2019 bash -c 'mkdir /data; chmod 777 /data -R; chown mssql:root /data'

sqlcmd -b -U sa -P 'Password1!' -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
```

While all the Docker commands seemingly execute properly, the `sqlcmd` call will keep failing, showing that SQL Server didn't properly start.

Interestingly, while the code works all the time with standard runners, with larger runners it only fails almost all but not all the time. I've seen successful runs with the same code [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177521321/jobs/5178056644#step:8:62) and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177521321/jobs/5178486635#step:2:46).

I don't know where to start getting a grip on this, so any suggestions or hints would be appreciated.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- Image version: 20221002.2
- Failed build: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177521321/jobs/5178764578
- Successful build (well, it's a failed one but the "Set up SQL Server" step which runs the above code is successful): https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177717433/jobs/5178866743

### Is it regression?

Perhaps yes, with image 20220925.1 it works, or it's something else the larger runners do differently.

### Expected behavior

The new image works like the older one, and SQL Server starts up.

### Actual behavior

See above.

### Repro steps

See the code above. It's part of the larger workflow -> reusable workflow -> composite action -> script implementation.

- [This is the workflow that doesn't work.](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/cbf5f10543101b8db7c7562d6e5610ebcff9c086/.github/workflows/build-and-test.yml)
- [This is the workflow that works.](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/85210dd2ff43630181752dccd1b5c99aaf2c3147/.github/workflows/build-and-test.yml)

The reusable workflow and else were used on [this commit](https://github.com/Lombiq/GitHub-Actions/tree/8cbc8b5d8653c43602a20f5c0472d730ec633ab8).

**Comment by mikhailkoliada** [comment]
@Piedone Hello! We will take  look

CC: @maxim-lobanov @AlenaSviridenko

**Comment by al-cheb** [comment]
@Piedone, Could you please attach docker logs for a failed build?
`docker logs sql2019`

**Comment by al-cheb** [comment]
LR and hosted agents have slightly different hostname configuration:

```
$ echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1) $(hostname -f) $(hostname -s)"
10.0.0.4 runner runner
$ host $(hostname)
runner.osahkor0zetehoprefcc04jpba.bx.internal.cloudapp.net has address 10.0.0.5
```

Workarounds for LR:
1. Use -S param 
`sqlcmd -b -S '127.0.0.1,1433' -U sa -P 'Password1!' -Q "SELECT @@SERVERNAME as ServerName"`
3. Update hosts file
`- run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1) $(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts`

**Comment by maxim-lobanov** [comment]
@al-cheb , thank you for deep investigation!
I will check if we can apply this fix for all Larger Runners by default.

**Comment by Piedone** [comment]
Thank you for the detailed answer. It would be great if LR could do the same as standard ones.

**Comment by maxim-lobanov** [comment]
Hello @Piedone ,
The fix for this issue was deployed so your use-case should start working without workarounds.

One note, there may be idle VMs waiting to pick up jobs which don't have fix applied yet. So you may need to trigger 1-2 extra jobs to make sure that all workflows are run on VMs with fix.

Will keep the issue opened until confirmation that issue is resolved.

**Comment by Piedone** [comment]
Great, thank you!

I tested it and SQL Server properly starts up now, with the same code that works on standard runners: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3177521321/jobs/5236914471#step:2:47

**Comment by maxim-lobanov** [comment]
Nice,
I closing this issue. Let me know if you have any concerns or objections.

**Comment by Piedone** [comment]
Thank you for fixing this so quickly!
