### ISSUE TITLE
Request: Support Windows Server vNext/Preview

### ISSUE THREAD

**Issue by nibanks** [actions/runner-images#6355]
### Tool name

Windows Server

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

vNext

### Brief description of tool

The latest preview version of Windows Server.

There are more and more examples of Windows components (such as [MsQuic](https://github.com/microsoft/msquic) and [XDP-for-Windows](https://github.com/microsoft/xdp-for-windows)) that are moving out of the OS repo and to GitHub or Azure DevOps. There are tons of upsides to this move, but one significant downside is the loss of test coverage for the latest versions of Windows. This gap can be closed with manual machine pools, but require significant resources for each individual repo to manage (not to mention all the duplication). 

The ask is for the runners to support the vNext/Preview builds that are occasionally released. Even quarterly updates to the latest preview build would likely be enough.

Since this is prerelease OS, we don't expect any significant support beyond exposing the (opt-in) option leverage these builds. It is not ever expected these would be default for `latest` or anything. Additionally, the machine pool size could be fairly small, compared to the other images. We just coverage for these builds.

### URL for tool's homepage

https://techcommunity.microsoft.com/t5/windows-server-insiders/announcing-windows-server-preview-build-25206/m-p/3634220

### Provide a basic test case to validate the tool's functionality.

```bash
N/A
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

### Tool installation time in runtime

N/A

**Comment by mikhailkoliada** [comment]
Currently we are providing pretty standard image offers from azure marketplace as declared in our packer specs, we have never provided preview.

**Comment by nibanks** [comment]
> Currently we are providing pretty standard image offers from azure marketplace as declared in our packer specs, we have never provided preview.

Understood. Yes, this is an ask for something new. But we are asking you folks because otherwise the Windows teams would have to build something entirely separate that's nearly identical to what you already have, just with a different base image.

**Comment by Steve-Glass** [comment]
👋 @nibanks I'm the GitHub PM in this space and we've had a similar requests in the past for `preview` builds. I'll bring this topic to our internal sync next Thursday and will provide an update by 10/20.

**Comment by nibanks** [comment]
Thanks a lot @Steve-Glass. Feel free to reach out internally to me if you need more details. We're driving a pretty big initiative internally that would really benefit from this.

**Comment by mikhailkoliada** [comment]
Looks like discussion is not getting further, @nibanks feel free to reach me, @Steve-Glass, @lkfortuna and @samvantran in teams if the need is still here, we can discuss it.

**Comment by nibanks** [comment]
@mikhailkoliada we still would like to have this as an option. We have gotten around this for our repo by using the internal 1ES Hosted Pools, but it has the following downsides:

1. External folks who fork our repo cannot run the automation in their fork.
2. It's complicated to set up and has some overhead.
3. We have to maintain a subscription and pay for the machines.

@Steve-Glass any chance of getting this opened up and prioritized to have a standard solution? IMHO, having the vNext build of Windows improves quality overall for both Windows and the individual products because it encourages upfront testing.
