### ISSUE TITLE
Github actions failing on checkout

### ISSUE THREAD

**Issue by cipriancaba** [actions/runner-images#6361]
### Description

Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_a9201551-77fe-434b-9a17-dae240c2a706/f9e42ebf-abcc-4cef-ae30-9ce9195a0051.tar.gz. return code: 2.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

##[debug]Starting: Set up job
Current runner version: '2.297.0'
Operating System
  Ubuntu
  20.0
  LTS

### Is it regression?

no

### Expected behavior

just be able to run the pipeline

### Actual behavior

pipeline failing

### Repro steps

just started failing

**Comment by JasonGross** [comment]
Seems to be happening on all actions using checkout, e.g., https://github.com/mit-plv/rewriter/actions/runs/3196480702/jobs/5218469686

**Comment by JasonGross** [comment]
See also https://github.com/actions/checkout/issues/948

**Comment by chrisponton** [comment]
Happening to me also :(

**Comment by mklarsen** [comment]
Plz. check this https://www.githubstatus.com/.

**Comment by cipriancaba** [comment]
Anyone following this, just upgrade the checkout actions to 3.1.0

`actions/checkout@v3.1.0`

**Comment by mikhailkoliada** [comment]
Closed as external as we can't do anything on our side :(
