### ISSUE TITLE
Add Hatch

### ISSUE THREAD

**Issue by ofek** [actions/runner-images#6370]
### Tool name

Hatch

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.6.0

### Brief description of tool

Hatch is a modern, extensible, and standards-compliant Python project manager. I am a maintainer of this tool.

Its first stable release was [announced](https://discuss.python.org/t/15359) on Python's dev forum in April and the project was swiftly [adopted](https://mail.python.org/archives/list/pypa-committers@python.org/thread/J2BL5XTTOCXUCELUE7L5P5HHJ7NXZGZ5/) by Python's official packaging team in the following weeks.

By having Hatch preinstalled, Python projects would save ~10-40 seconds ([example](https://github.com/mkdocs/mkdocs/actions/runs/3209885915)) of setup time depending on the OS image. Additionally, since there is functionality for the entire life cycle of a project (building -> environment management for testing -> versioning -> publishing), projects could [opt-in](https://hatch.pypa.io/1.6/meta/faq/#interoperability) to a unified workflow and remove the need for other tools like [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) for publishing to [PyPI](https://pypi.org) which alone takes ~30 seconds ([example](https://github.com/pypa/hatch/actions/runs/3212030490/jobs/5250603213)) to build and use.

The most prevalent feature is Hatch's [environment management](https://hatch.pypa.io/1.6/environment/) which is used by projects like [MkDocs](https://github.com/mkdocs/mkdocs/blob/b2083d07f5d07ddfd82c1534bfef7203b77b4307/pyproject.toml#L108), organizations like [Project Jupyter](https://github.com/jupyterlab/hatch-jupyter-builder/blob/ac96e3c80f3352d88acb3863a6227ec704931728/pyproject.toml#L46), and companies like [Datadog](https://github.com/DataDog/integrations-core/pulls?q=is%3Apr+in%3Atitle+Use+Hatch+to+manage+environments) and [Instagram](https://github.com/Instagram/Fixit/blob/658bd250af0bd3fdac6ee858bf554829ec11bcc3/pyproject.toml#L68). It can also be used as a general purpose task runner, not just for Python projects.

Here is a non-exhaustive listing of users: https://hatch.pypa.io/dev/users/

### URL for tool's homepage

https://hatch.pypa.io/latest/

### Provide a basic test case to validate the tool's functionality.

```bash
hatch --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
python -m pip install hatch==1.6.0
```

### Tool installation time in runtime

~10-40 seconds

### Are you willing to submit a PR?

Yes, but I would need guidance

**Comment by ofek** [comment]
> > Are you willing to submit a PR?

> Yes, but I would need guidance

Actually, I think I did it!

- https://github.com/actions/runner-images/pull/6371
- https://github.com/actions/runner-images/pull/6372
- https://github.com/actions/runner-images/pull/6373

This was very easy to contribute, great job 😄

**Comment by igorboskovic3** [comment]
Hi @ofek , we will take a look and get back to you, thank you.

**Comment by igorboskovic3** [comment]
Hi @ofek we decide not to add Hatch to images, considering installation time, thank you.

**Comment by mikhailkoliada** [comment]
it can be installed from pip in 7 seconds

**Comment by ofek** [comment]
Not on macOS nor Windows
