### ISSUE TITLE
[all OSs] The VCPKG_ROOT variable will be removed from runner images

### ISSUE THREAD

**Issue by ddobranic** [actions/runner-images#6376]
### Breaking changes

The VCPKG_ROOT variable will be removed from runner images.

### Target date

October, 31. The propagation will take 2-3 days.

### The motivation for the changes

In accordance with the reaction of the VCPKG developers and community to the recent changes regarding the setting of the VCPKG_ROOT variable, it was decided to abandon such breaking changes so that users can independently control the contents of this environment variable.

The history of changes and reasons for cancellation can be found here: [#6146](https://github.com/actions/runner-images/discussions/6146), [#6192](https://github.com/actions/runner-images/pull/6192), [#6195](https://github.com/actions/runner-images/pull/6195), [#6196](https://github.com/actions/runner-images/pull/6196).

### Possible impact

Users who have already started using the VCPKG_ROOT variable in accordance with the latest changes may encounter some difficulties.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Users who have already started using the VCPKG_ROOT variable in accordance with the latest changes should revert to using the VCPKG_INSTALLATION_ROOT variable to avoid errors.

**Comment by mikhailkoliada** [comment]
Removal date shifted one week.

**Comment by monamimani** [comment]
Now that VCPKG_ROOT  is not defined anymore, 

For people that use the installation that comes with the image how do you set VCPKG_ROOT  to  VCPKG_INSTALLATION_ROOT  in a cross-platform way without have a step for each platform that set just 1 variable.

**Comment by mikhailkoliada** [comment]
Deployed
