### ISSUE TITLE
Github Action macOS-12 runner Xcode build failing with no log

### ISSUE THREAD

**Issue by isimpson** [actions/runner-images#6378]
### Description

In the last couple of days we are seeing Xcode build failures on our GitHub action for our iOS app.
This is blocking our PRing so we would like to get it fixed asap.

Using our GitHub actions runners on macOS-12 we haven't had a problem up until last week (around 6th October) which coincided with when you updated the runner to use Xcode to 14.0.1.
The version is not an issue as our app compiles fine locally with that Xcode version.

The output is not very helpful in the log it just shows:
```
[06:02:49]: $ set -o pipefail && xcodebuild -workspace "*******.xcworkspace" -scheme "******" -configuration "Debug" -sdk "iphonesimulator" -destination "generic/platform=iOS" clean build | tee '/Users/runner/Library/Logs/fastlane/xcbuild/2022-10-06/3483/xcodebuild.log' | xcpretty --color --simple
6175
[06:03:03]: ▸ Clean Succeeded
6176
[06:03:21]: ▸ ** BUILD FAILED **
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20220929.2
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20220929.2/images/macos/macos-12-Readme.md

### Is it regression?

yes, before 6th October the image was working

### Expected behavior

Build continues as normal and doesn't fail without warning.

### Actual behavior

Build fails with no log.

### Repro steps

Build iOS app with macos-12 image.
Build passes locally but fails with no error on runner:
`[06:03:21]: ▸ ** BUILD FAILED **`

**Comment by igorboskovic3** [comment]
Hi @isimpson we will take a look.

**Comment by al-cheb** [comment]
@isimpson, could you please provide steps to reproduce the issue?

**Comment by eseiler** [comment]
Might be related to https://github.com/actions/runner-images/issues/6350?
Does explicitly setting another/the old xcode version work?

**Comment by isimpson** [comment]
@eseiler yes it looks related to #6350 and downgrading did fix the issue, but we would like to use Xcode 14 :) 
I am also surprised that macos-latest is still using macos-11 and Xcode 13.2.1.

**Comment by al-cheb** [comment]
@isimpson, could you please provide steps and a repo to reproduce the issue?

**Comment by al-cheb** [comment]
Feel free to reopen the thread if you have any concerns.
