### ISSUE TITLE
"ubuntu-latest" and "macos-latest" don't use correct version.

### ISSUE THREAD

**Issue by Kichura** [actions/runner-images#6380]
### Description

When using "ubuntu-latest" and/or "macos-latest", they are normally supposed to be using their latest counter-parts of their operating systems, However what they actually do is reuse older versions of their operating systems instead.

Windows on the other hand is not affected as it is already using the correct version as expected.

### Platforms affected

- [x] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

*(Any GitHub Actions + Azure DevOps agents are affected)*

### Is it regression?

No.

### Expected behavior

Using "ubuntu-latest" will use ubuntu 22.04 lts meanwhile using "macos-latest" will use macos-12.

### Actual behavior

Using "ubuntu-latest" will use ubuntu 20.04 lts meanwhile using "macos-latest" will use macos-11 instead.

### Repro steps

1. Make any github actions you like,
2. Ensure the operating system is either on "ubuntu-latest" or "macos-latest",
3. Send out the commit and check the operating system context.

**Comment by erik-bershel** [comment]
@Kichura 
Hi! We are already working on this, but it is a rather complicated and long process, given that it should bring more benefit than loss to all of our users.

**Comment by erik-bershel** [comment]
@Kichura
Hi again! Take a look here, please. #6384 
First half of your request is already publicly in progress.

**Comment by Kichura** [comment]
Excellent, is there an related issue with ubuntu 22.04 lts as a relationship?

**Comment by erik-bershel** [comment]
@Kichura I'll send you a link when we start the public part of a process with Ubuntu. But we are working on that too.

**Comment by erik-bershel** [comment]
@Kichura so, next part published. #6399

**Comment by Kichura** [comment]
Alright, Thank you for the redirections. :)
