### ISSUE TITLE
macOS-latest workflows will use macOS-12

### ISSUE THREAD

**Issue by ddobranic** [actions/runner-images#6384]
### Breaking changes

macOS-12 is ready to be the default version for the "macos-latest" label in GitHub Actions and Azure DevOps.

### Target date

This change will be rolled out over a period of several weeks beginning on October, 3. We plan to complete the migration by March, 1st, 2023.

### The motivation for the changes

GitHub Actions and Azure DevOps have supported macOS-12 in public beta since April 2022, and starting from [June 2022 macOS-12 is generally available for all customers](https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/). We have monitored customer feedback to improve the macOS-12 image stability and now we are ready to set it as the latest.

### Possible impact

The macOS-12 image has a different set of software than macOS-11. The most significant changes are listed in the table below:

|Tool name|macOS-11|macOS-12|Notes|
|-|:-:|-|-|
|Virtualbox<br>Vagrant<br>Support for Parallels Desktop | - | 6.* <br>2.* <br>18.* | At the request of users, virtualization tools that were previously unavailable in macOS 11 had been added |
|Ruby toolcache | 2.4.* <br>2.5.* <br>2.6.* <br>2.7.* default <br>3.0.* <br>3.1.* | 2.7.* <br>3.0.* default <br>3.1.* | EOL Ruby versions had been removed |
|Ruby Gems | xcode-install,<br>cocoapods,<br>nomad-cli,<br>xcpretty,<br>bundler,<br>fastlane,<br>jazzy | xcode-install,<br>cocoapods,<br>xcpretty,<br>bundler,<br>fastlane,<br>jazzy | nomad-cli has been [removed](https://github.com/actions/runner-images/pull/4667) as the project is no longer maintained. |
|CLang | 13.0 (default) | 14.0 (default) | Please, pay attention to [changes](https://github.com/actions/runner-images/issues/5835) for default compiler |
|GCC / GFortran | 9.* <br>10.* <br>11.* | 11.* | Old versions had been removed |
|Xamarin.iOS | 13.20 - 15.8 | 15.0 - 16.0 | Old versions and versions incompatible with the pre-installed Xcodes had been removed |
|Xamarin.Mac | 6.20 - 8.8 | 7.14 - 8.12 | Old versions and versions incompatible with the pre-installed Xcodes had been removed |
|Xamarin.Android | 11.0 – 12.2 | 11.3 – 13.0 | Old versions and versions incompatible with the pre-installed Xcodes had been removed |
|Xcode | 13.2.1 (default)13.113.012.5.112.411.7 | 14.1 (beta)14.0.1 (default)14.013.2.113.113.012.5.112.411.7 | Only OS-compatible versions left + the latest 11 version |

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

If you see any issues with your workflows during this transition period:
- File an issue in this repository
- Switch back to macOS 11 by specifying the “macOS-11" label. We will continue to support macOS 11.

**Comment by arichorn** [comment]
I heard the news. Is there any new methods for these? These just got deprecated and it led me to this GitHub page. I will need to fix this as soon as possible if the new methods are found.
![42523143-E8E7-40EC-B122-6D6758BC33FA](https://user-images.githubusercontent.com/78001398/195637360-955ad414-ad37-4e1d-8f02-2867772bf324.jpeg)

**Comment by wojsmol** [comment]
@arichorn Please see this [blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by ddobranic** [comment]
Thank you @wojsmol

**Comment by arichorn** [comment]
Alright but I already went to this site earlier today, it is a little complicated to understand GitHub’s new commands

**Comment by mattjohnsonpint** [comment]
@arichorn - It would seem they forgot to include the name of the offending action into the error message, so it can be quite cryptic.  Re-run a job that shows the warning and check the box for debug logging, then you can see in the debug output which actions need to be updated.

**Comment by arichorn** [comment]
> @arichorn - It would seem they forgot to include the name of the offending action into the warning message, so it can be quite cryptic. Re-run a job that shows the warning and check the box for debug logging, then you can see in the debug output which actions need to be updated.
> 
> (Also - those are unrelated to this particular issue.)

Oh alright thanks, and sorry for putting it in here

**Comment by arichorn** [comment]
Hey I’m back! I have successfully migrated the runner to run MacOS 12 actions, I readed the thing above and resolved it! Ty y’all

**Comment by Xanonymous-GitHub** [comment]
I just found even I use `macos-latest` it still runs on v11 instead of v12 in this https://github.com/NEO-TAT/tat_flutter/actions/runs/3260016715/jobs/5353264229.

But if I changed it to `macos-12`, is use 12.

Don't know what's happened ...

**Comment by ddobranic** [comment]
@Xanonymous-GitHub hello, yes migration is in progress and it is planned to be complete by December 1st.

**Comment by Xanonymous-GitHub** [comment]
Got it, thanks :)

**Comment by charmipatalia** [comment]
I am using Azure Devops with fastlane to upload the iOS app in testFlight. If I use macOS-12 then build is failing. Any idea?
![Screen Shot 2022-10-25 at 9 48 06 am](https://user-images.githubusercontent.com/105029373/197647781-81f6d24a-9c6e-48e9-a323-1ed0b92aea8f.png)

**Comment by nima-ap** [comment]
> I am using Azure Devops with fastlane to upload the iOS app in testFlight. If I use macOS-12 then build is failing. Any idea? ![Screen Shot 2022-10-25 at 9 48 06 am](https://user-images.githubusercontent.com/105029373/197647781-81f6d24a-9c6e-48e9-a323-1ed0b92aea8f.png)

Try disabling xcpretty by setting `useXcpretty: false` under your `inputs` to the Xcode task and I believe you'll get to see a ton more logs that will hopefully help you figure out why it's failing.

**Comment by charmipatalia** [comment]
Hello @nima-ap , Thanks for your guide. Now I am able to see more logs of failure and trying to fix the issue.

**Comment by matskiv** [comment]
According to [macos-12 Readme](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) the Helm tool is not included, but it was included in macos-11. It is not listed in the "Possible impact" table in this issue.

**Comment by jeandiego** [comment]
I have experienced some issues after migrating the macOS-11 VM to 12 to run the command `install bundle`. Our project depends some gems and native Ruby installed on VM doesn't appears to work well. Even if I try to use a custom manager as `rbenv` or `rvm` to install ruby, I'm not able to install correctly since permissions. The fact is, the only way I found to run `install bundle` was using with `sudo`, which is not recommended. Someone passing through the same issue?


The error:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/json-2.3.0/ext/json/ext/generator
/usr/local/opt/ruby@3.0/bin/ruby -I /usr/local/lib/ruby/site_ruby/3.0.0
extconf.rb
creating Makefile

current directory:
/Users/runner/work/1/s/vendor/bundle/ruby/3.0.0/gems/json-2.3.0/ext/json/ext/generator
make DESTDIR\= sitearchdir\=./.gem.20221121-3140-yt7pht
sitelibdir\=./.gem.20221121-3140-yt7pht
compiling generator.c
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone'
[-Wincompatible-sysroot]
linking shared-object json/ext/generator.bundle
clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone'
[-Wincompatible-sysroot]
ld: warning: -undefined dynamic_lookup is deprecated on iOS
ld: warning: building for iOS, but linking in dylib file
(/usr/local/Cellar/ruby@3.0/3.0.4_1/lib/libruby.3.0.dylib) built for macOS
ld: building for iOS, but linking in object file built for iOS Simulator, file
'generator.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [generator.bundle] Error 1

make failed, exit code 2

...
##[error]Bash exited with code '5'.
```

Gemfile
```
source "https://rubygems.org"

gem "fastlane", '2.210.1'
gem "cocoapods", '1.11.3'
gem 'json', '2.5.1'
gem 'ffi', '1.15.5'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

**Comment by btfranklin** [comment]
We're now past the December 1 projected end date for this, but it looks like macos-latest is still resolving to macos-11 on my builds. Is there a new projected date for completion of this rollout?

**Comment by mikhailkoliada** [comment]
@btfranklin Hey! Yeah, we stretched migration phase to make it more flawless for all the customers, I've updated the original post.

**Comment by AntonOfTheWoods** [comment]
@mikhailkoliada , can you elaborate on how having random users impacted by a change or not is more flawless?

**Comment by btfranklin** [comment]
It seems crazy that people using an inherently-dynamic tag like "macos-latest" would require **six months** of time for a change. If people are so dependent upon a specific version, shouldn't their configurations specify the version they need? I thought the whole point of having dynamic labels like "-latest" was to express that you wanted to build on the latest-and-greatest and didn't have specific version dependencies? This feels like it's dragging on for a long time.

**Comment by richb-hanover** [comment]
> Why have "-latest" at all if it's not kept up to date in a timely manner?

I agree. This seems more like a several MONTH rollout. Does this mean we will endure several months of warnings that `macos-latest workflows will use macos-12 soon`? (That's not "soon". I was relying on previous guidance that said that 1 Dec 2022 was the cutoff. Now you've moved the goalposts.)

I apologize for being grumpy, but unnecessary warnings make me unhappy. Why? I have 40 occurrences of `...-latest` in my small project. I'm not aware of a facility in GHA that would allow me to specify a variable that contains `macos-12` and use it globally. So I'm stuck either living with the warnings or globally editing that string a load of times...

**Comment by realityworks** [comment]
Hey guys,

I understand that you have time pressures, and it's great to see the amazing work you are doing.

However, for the least six months, we have not been able to do a build using the runner.

We need to support Swift 5.7, and Xcode 14. However, it took six months for this runner to even support the latest Xcode/macOS.

Mac OS do YEARLY updates to their tooling. Having this run 6 months behind really is detrimental to delivery.

I could understand 1 month, but 6 month delays... While there has been a BETA out for even longer. Sounds like the Mac team needs to grow a few team members.

Thanks for the great work again, and hopefully we won't have to wait 6 months + for an update to the Xcode/macOS runners.

**Comment by mikhailkoliada** [comment]
Finally migrated: https://github.com/actions/runner-images/pull/6901!

**Comment by realityworks** [comment]
Thanks guys!

**Comment by karbonnanroid** [comment]
g

**Comment by karbonnanroid** [comment]
h
