### ISSUE TITLE
`tar` available but not listed for runner image docs

### ISSUE THREAD

**Issue by noslav** [actions/runner-images#6387]
### Description

https://github.com/actions/runner-images/blob/ubuntu20/20221002.2/images/linux/Ubuntu2004-Readme.md 
 does not contain any info for `tar`

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

NA

### Is it regression?

No

### Expected behavior

NA

### Actual behavior

NA

### Repro steps

NA

**Comment by mikhailkoliada** [comment]
Thanks, we probably should document it, indeed

**Comment by mikhailkoliada** [comment]
Changes are deployed now
