### ISSUE TITLE
Update/Add HAXM to macOS 11 and macOS 12 agents

### ISSUE THREAD

**Issue by mrk-han** [actions/runner-images#6388]
### Tool name

MacOS Runner Images

### Tool license

None

### Add or update?

- [X] Add
- [ ] Update

### Desired version

N/A

### Brief description of tool

https://github.com/actions/runner-images/blob/main/images/macos/macos-10.15-Readme.md HAXM 

https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md No HAXM

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md No HAXM

### Provide a basic test case to validate the tool's functionality.

```bash
- name: Emulator HAXM check
        uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          api-level: 33
          arch: x86_64
          target: google_apis
          profile: Nexus One
          disable-animations: false
          script: emulator -accel-check
```
```


### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Not sure it can be easily done: https://github.com/intel/haxm/wiki/Installation-Instructions-on-macOS
```

**Comment by igorboskovic3** [comment]
Hi @mrk-han, thank you for your interest, we are aware of this and we are already discussed HAXM, as you can see [here](https://github.com/actions/runner-images/issues/183#issuecomment-610723516). You can check this [thread](https://github.com/intel/haxm/issues/403) also for additional information.
