### ISSUE TITLE
[error]Unable to locate executable file

### ISSUE THREAD

**Issue by bhosalemahesh899** [actions/runner-images#6390]
### Description

I am using ubuntu-latest agent to run pipeline on azure DevOps. Getting following error for Python Script task.

##[error]Unable to locate executable file: '...' Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
![image](https://user-images.githubusercontent.com/15128309/195285102-c9f50a0c-c124-4db3-a540-4a30da943e03.png)
![image](https://user-images.githubusercontent.com/15128309/195285319-e48dbf50-0964-4ff7-9afb-56f2b3a957ab.png)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not able to find "Initialize job" -> "Runner Image" -> "Version".

### Is it regression?

no

### Expected behavior

Python script should run successfully

### Actual behavior

Getting an error ##[error]Unable to locate executable file: '...' Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

### Repro steps

1. Add task python script.  agent is ubuntu latest
2. Add inline script
3. Run pipeline

**Comment by al-cheb** [comment]
Hey @bhosalemahesh899.
I can't reproduce the issue.

pipeline:
![image](https://user-images.githubusercontent.com/47745270/195287427-0b0144b7-a041-45fa-829c-900166a7fc6c.png)

output:
![image](https://user-images.githubusercontent.com/47745270/195287314-2909ee6d-e09e-4a5c-aba0-4b11a7be85c9.png)

**Comment by al-cheb** [comment]
Feel free to open the thread if you have any concerns.
