### ISSUE TITLE
Add Swift 5.7 to Ubuntu 22.04 image

### ISSUE THREAD

**Issue by buttaface** [actions/runner-images#6396]
### Tool name

Swift

### Tool license

Apache

### Add or update?

- [X] Add
- [ ] Update

### Desired version

5.7

### Approximate size

1.5 GB

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by buttaface** [comment]
#5490 noted that prebuilt Swift toolchains for 22.04 were not available at that time, but [with the release of Swift 5.7 last month, support for 22.04 was added](https://www.swift.org/download/#releases).

**Comment by igorboskovic3** [comment]
Hi @buttaface we will taka a look and get back to you, thank you

**Comment by mikhailkoliada** [comment]
Deployed now
