### ISSUE TITLE
Package qtbase5-dev:i386 can't be installed

### ISSUE THREAD

**Issue by SNMetamorph** [actions/runner-images#6407]
### Description

This package can't be installed using apt, but it was working well on `ubuntu-18.04` environment.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 Image: ubuntu-20.04
 Version: 20221002.2

### Is it regression?

On environment `ubuntu-18.04`

### Expected behavior

When trying to install package it should work without any errors.

### Actual behavior

When trying to install package it throws error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtbase5-dev:i386 : Depends: libqt5concurrent5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5core5a:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5dbus5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5gui5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5network5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5printsupport5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5sql5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5test5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5widgets5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Depends: libqt5xml5:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
                    Recommends: libqt5opengl5-dev:i386 (= 5.12.8+dfsg-0ubuntu2.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### Repro steps

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install qtbase5-dev:i386
```

**Comment by al-cheb** [comment]
Hey @SNMetamorph.
You could use ubuntu-22.04.

**Comment by SNMetamorph** [comment]
> Hey @SNMetamorph. You could use ubuntu-22.04.
> 
> ![image](https://user-images.githubusercontent.com/47745270/195878217-9e3734d4-f416-400c-9e30-9d0f4ec166b4.png)

Yes, I can use it. But why it doesn't work on `ubuntu-20.04`? But also it works on WSL2 with Ubuntu 20.04

**Comment by al-cheb** [comment]
It works on Ubuntu 20.04:

```
- run: |
    sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
- run: |
    sudo dpkg --add-architecture i386
    sudo apt-get update
    sudo apt-get install qtbase5-dev:i386
```

![image](https://user-images.githubusercontent.com/47745270/196007438-17985031-597a-4ee9-aadc-44db9c4f6d4d.png)

**Comment by SNMetamorph** [comment]
@al-cheb so I just should use command `sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7` and it will work as it should?
