### ISSUE TITLE
[WinError 5] Access is denied when doing a shutil.copytree

### ISSUE THREAD

**Issue by Namburger** [actions/runner-images#6409]
### Description

Not sure if this is the right place for it, and my usage is a little convoluted :D

Anyhow, I'm trying to run a [bash script](https://github.com/Namburger/coralmicro/actions/runs/3252938515/workflow#L88) in the windows ci. The bash script setup toolchains and call a python script to package some artifacts. 
The issue is that I'm now getting a `[WinError 5] Access is denied` on a call to `shutil.copytree`:
https://github.com/Namburger/coralmicro/actions/runs/3252938515/jobs/5339704593#step:5:9933

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/Namburger/coralmicro/actions/runs/3252938515/jobs/5339704593#step:5:9933

### Is it regression?

no

### Expected behavior

It should build

### Actual behavior

it failed

### Repro steps

Run the CI on my repo.

**Comment by al-cheb** [comment]
Close as external bug - https://github.com/python/cpython/issues/82814
