### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by ohhmm** [actions/runner-images#6410]
### Tool name

boost

### Tool license

boost

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.80.0

### Brief description of tool

Its a library for native C++ development
https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.zip

### URL for tool's homepage

https://www.boost.org/

### Provide a basic test case to validate the tool's functionality.

```bash
This action downloads and builds boost prerequisite automatically https://github.com/ohhmm/openmind/actions/runs/3253134249/jobs/5340103606

If boost is installed with `bootstrap && b2 -a install` then this action use preinstalled boost 

Feel free to use it to test.
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, with notable action time taken.
```

### Tool installation time in runtime

~15m

### Are you willing to submit a PR?

maybe

**Comment by al-cheb** [comment]
Hey, @ohhmm.

```
The motivation for the changes
We are going to deprecate Boost due to lack of free space on images, maintenance concerns and low popularity.
```

Close as https://github.com/actions/runner-images/issues/2667

**Comment by ohhmm** [comment]
@al-cheb, FYI, boost is the most popular C++ library.
Anyway, 0.5 Gb is how much the boost installation require.
Also, NTFS-compression may be applied or NAS junction with COW FS.
