### ISSUE TITLE
Update/Add pack cli

### ISSUE THREAD

**Issue by Chthirupathi** [actions/runner-images#6415]
### Tool name

pack cli

### Tool license

pack CLI (version 0.27.0)

### Add or update?

- [X] Add
- [X] Update

### Desired version

pack CLI (version 0.27.0)

### Brief description of tool

Pack is a tool maintained by the Cloud Native Buildpacks project to support the use of buildpacks.

It enables the following functionality:

1. build an application using buildpacks.
2. Rebase application images created using buildpacks.
3. Creation of various used within the ecosystem.

### URL for tool's homepage

https://buildpacks.io/docs/tools/pack/

### Provide a basic test case to validate the tool's functionality.

```bash
Run sample pipeline with buildpacks.io task, if it is running without showing an error pack then it is working fine.
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

### Tool installation time in runtime

5 minutes

**Comment by al-cheb** [comment]
Hey @Chthirupathi.

We decided not to add pack-cli to images, considering installation time. Please use code snipet below it takes less 1 minute to install in runtime.

Windows:
`choco install pack --version=0.27.0`

Ubuntu:
```
sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
sudo apt-get update
sudo apt-get install pack-cli
```
