### ISSUE TITLE
Update/Add Python 3.9.15

### ISSUE THREAD

**Issue by uthark** [actions/runner-images#6421]
### Tool name

Python

### Tool license

https://docs.python.org/3.9/license.html

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.9.15

### URL for tool's homepage

https://www.python.org/downloads/release/python-3915/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
The new Ubuntu images have been deployed with Python 3.9.15.
