### ISSUE TITLE
CI tests pass on ubuntu image version 20221012.1 but not on 20221002.2

### ISSUE THREAD

**Issue by gaiksaya** [actions/runner-images#6422]
### Description

Hi,

We have some groovy (jenkins) [tests](https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/groovy-tests.yml) that uses `ubuntu-latest` as the CI runner. 
The tests were passing locally but randomly failing and on deep diving it was observed that they were only passing (for ubuntu latest) on below runner image
```
  Image: ubuntu-20.04
  Version: 20221012.1
```
Check the run here: https://github.com/opensearch-project/opensearch-build/actions/runs/3269402983/jobs/5376865336
However, the above version is not even tagged or released. Also seeing that related PR was closed https://github.com/actions/runner-images/pull/6394

The tests fail when the runner uses below image:
```
  Image: ubuntu-20.04
  Version: 20221002.2
```
Check the run here: https://github.com/gaiksaya/opensearch-build/actions/runs/3269402773/jobs/5376865157

Wanted to know what the issue might be?
Also is there a way to specify the runner image version as a work around?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Version: 20221002.2

 https://github.com/gaiksaya/opensearch-build/actions/runs/3269402773/jobs/5376865157

### Is it regression?

https://github.com/opensearch-project/opensearch-build/actions/runs/3269402983/jobs/5376865336

### Expected behavior

Should pass on all runners

### Actual behavior

Passing for `20221012.1` runner and failing on `20221002.2`
All we have specified is `ubuntu-latest`

### Repro steps

Run the workflow and see the above pattern.

**Comment by al-cheb** [comment]
Hey @gaiksaya.
We will take a look at it.

**Comment by akunzai** [comment]
Hi,

I'm facing the same issue running `phpstan` tests on the `ubuntu-latest` runner.

- [passing](https://github.com/akunzai/MageBridgeCore/actions/runs/3268350507/jobs/5374653206) on runner image `20221002.1`
- [failing](https://github.com/akunzai/MageBridgeCore/actions/runs/3268364514/jobs/5378099799) on runner image `20221002.2`

**Comment by akunzai** [comment]
@al-cheb - it [passing](https://github.com/akunzai/MageBridgeCore/actions/runs/3268364514/jobs/5424706702) on `ubuntu-20.04` runner with image version `20221018.2`
