### ISSUE TITLE
Ubuntu 20.04 - 20221012 release

### ISSUE THREAD

**Issue by AnnaMChoi-CD** [actions/runner-images#6423]
### Description

Some of the github actions I have in my repository that with run-on ubuntu-latest started to pick up the newer runner version: 20221012.
and it started to fail the bash command step which has no problem when it uses runner version of 20221002.

Below is the log from the "setup job" step:
Current runner version: '2.298.2'
Operating System
  Ubuntu
  [2](https://github.com/woolworthslimited/wwnz-ai-feature-library/actions/runs/3269980735/jobs/5378097294#step:1:2)0.0[4](https://github.com/woolworthslimited/wwnz-ai-feature-library/actions/runs/3269980735/jobs/5378097294#step:1:4).[5](https://github.com/woolworthslimited/wwnz-ai-feature-library/actions/runs/3269980735/jobs/5378097294#step:1:5)
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20221012.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20221012.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F2022[10](https://github.com/woolworthslimited/wwnz-ai-feature-library/actions/runs/3269980735/jobs/5378097294#step:1:11)12.1

Both "Included Software" and "Image Release" links don't work.

Looks like this PR was never merged but the branch was deleted? https://github.com/actions/runner-images/pull/6394

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
Version: 20221002.2

### Is it regression?

yes

### Expected behavior

I expect the "Included Software" and "Image Release" links to be working so I can see what was actually included in the new runner version release. 

### Actual behavior

Github action - setup job is picking up the Ubuntu 20.04 - 20221002.2 however I can't find the release docs

### Repro steps

1. Trigger any github action with the runs-on configuration with ubuntu-latest, see if the runner version picks up Ubuntu 20.04 - 20221002.2.
2. Try access the "Included Software" and "Image Release" links from the setup job step.

**Comment by xvjixiang** [comment]
Same for us, we have some python scripts what run smoothly with version 20221002 but failed with version 20221012

**Comment by al-cheb** [comment]
Hey @AnnaMChoi-CD.
We will take a look at it.

**Comment by peternorthphorest** [comment]
This also hit our workflows and resulted in a terraform version mismatch between 20221002.2 and 20221012.1 (terraform versions 1.3.1 and 1.3.2 respectively).

**Comment by eivinhb** [comment]
We also see issues with `20221012.1`. Exact same git commit was ok on `20221002.2` just 12h ago. 

We have strange issues with maven-jib-plugin in  java build:

```
Error:  Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.0:build (default-cli) on project dpost-engine: loader constraint violation: when resolving method 'org.apache.commons.compress.compressors.CompressorInputStream org.apache.commons.compress.compressors.CompressorStreamFactory.createCompressorInputStream(java.io.InputStream)' the class loader org.codehaus.plexus.classworlds.realm.ClassRealm @4438b862 of the current class, com/google/cloud/tools/jib/cache/CacheStorageWriter, and the class loader org.codehaus.plexus.classworlds.realm.ClassRealm @5b12012e for the method's defining class, org/apache/commons/compress/compressors/CompressorStreamFactory, have different Class objects for the type org/apache/commons/compress/compressors/CompressorInputStream used in the signature (com.google.cloud.tools.jib.cache.CacheStorageWriter is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4438b862, parent loader 'bootstrap'; org.apache.commons.compress.compressors.CompressorStreamFactory is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @5b12012e, parent loader 'bootstrap') -> [Help 1]
```

**Comment by Benj13** [comment]
Having some issues with the new image as well, different version of Azure CLI it seems between `20221002.2` and `20221012.1`, and we can't really "fix" the code that calls the CLI as we don't know which version of the runner image we'll get.

Interesting part also is that it seems that this version doesn't officially exists https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20221012.1

**Comment by al-cheb** [comment]
The Ubuntu 20.04 - 20221012 release was cancelled, the https://github.com/actions/runner-images/pull/6433 new image is on track.
