### ISSUE TITLE
Ubuntu 20.04 / Rust install fails with bindgen 0.61 issues

### ISSUE THREAD

**Issue by mhever** [actions/runner-images#6424]
### Description

Ubuntu 20.04 image fails at Rust installation with issues at bindgen 0.61:

==> azure-arm:   Downloaded bindgen v0.61.0
==> azure-arm: warning: no Cargo.lock file published in bindgen v0.61.0
==> azure-arm: error: there is nothing to install in `bindgen v0.61.0`, because it has no binaries
==> azure-arm: `cargo install` is only for installing programs, and can't be used with libraries.
==> azure-arm: To use a library crate, add it as a dependency in a Cargo project instead.

Last time we had a successful build it contained bindgen v0.60.1

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest dev

### Is it regression?

-

### Expected behavior

Installing bindgen successfully.

### Actual behavior

==> azure-arm:   Downloaded bindgen v0.61.0
==> azure-arm: warning: no Cargo.lock file published in bindgen v0.61.0
==> azure-arm: error: there is nothing to install in `bindgen v0.61.0`, because it has no binaries
==> azure-arm: `cargo install` is only for installing programs, and can't be used with libraries.
==> azure-arm: To use a library crate, add it as a dependency in a Cargo project instead.

### Repro steps

build the image with rust, buildgen v0.61.0

**Comment by al-cheb** [comment]
Fixed in https://github.com/actions/runner-images/pull/6417.
