### ISSUE TITLE
macOS-12 (version 20221010.1) - can't find Xcode Error

### ISSUE THREAD

**Issue by scottgrowdnd** [actions/runner-images#6425]
### Description

We have an established Xamarion IOs pipeline running on vm image: macOS-12 (version 20221010.1)  which failed today with a new error:
[BuildLog.txt](https://github.com/actions/runner-images/files/9814229/BuildLog.txt)

**Could not find a valid Xcode app bundle at 'Applications/Xcode_14.0.1.app'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK).** 

[BuildLog.txt](https://github.com/actions/runner-images/files/9814234/BuildLog.txt)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221010.1

### Is it regression?

yes, worked as of image build 20220929.2

### Expected behavior

The build would find the Xcode app bundle

### Actual behavior

receive error: :Could not find a valid Xcode app bundle at 'Applications/Xcode_14.0.1.app'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). 

### Repro steps

Run a pipeline for a Xamarin IOS deploy.

**Comment by al-cheb** [comment]
Hey @scottgrowdnd.
Could you check this https://github.com/actions/runner-images/issues/6362#issuecomment-1281602028 comment?

**Comment by scottgrowdnd** [comment]
@al-cheb thank you!  We had that line code, but were missing a "/" which was omitted when we recently updated the XCode version.
