### ISSUE TITLE
Activating Windows Feature 'NET-Framework-Features' fails on Windows 2022

### ISSUE THREAD

**Issue by manitua** [actions/runner-images#6431]
### Description

Noticed today that building Windows 2022 image on `main` branch (commit: 1bbdd25a22dd003e3b720c77de25bb44ece8bc0e) is failing when trying to activate the `NET-Framework-Features`.

Log:
```
    vhd: Activating Windows Feature 'NET-Framework-Features'...
==> vhd: Install-WindowsFeature : The request to add or remove features on the specified server failed.
==> vhd: Installation of one or more roles, role services, or features failed. Error: 0x800f0950
==> vhd: At C:\Windows\Temp\script-634fff5a-37f1-8382-8f7c-bfbad1c37709.ps1:16 char:19
==> vhd: +         $result = Install-WindowsFeature @Arguments
==> vhd: +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidOperation: (@{Vhd=; Credent...Name=localhost}:PSObject) [Install-WindowsFeature],
==> vhd:     Exception
==> vhd:     + FullyQualifiedErrorId : DISMAPI_Error__Failed_To_Enable_Updates,Microsoft.Windows.ServerManager.Commands.AddWind
==> vhd:    owsFeatureCommand
==> vhd: Failed to activate Windows Feature 'NET-Framework-Features'
==> vhd: At C:\Windows\Temp\script-634fff5a-37f1-8382-8f7c-bfbad1c37709.ps1:24 char:9
==> vhd: +         throw "Failed to activate Windows Feature '$($feature.name)'"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Failed to activ...ework-Features':String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Failed to activate Windows Feature 'NET-Framework-Features'
```

This is my first build of Windows 2022 image for this week. Last week it was working without issues - last build done, last week, was on Friday, 2022-10-14, on `main` branch  (commit: ac65b549ac1094005080fe0c0104376308940d1e).

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

We run `packer build` on custom VM.
main branch - commit: 1bbdd25a22dd003e3b720c77de25bb44ece8bc0e

### Is it regression?

yes

### Expected behavior

Activating Windows Feature `NET-Framework-Features` should succeed. 

### Actual behavior

Activating Windows Feature `NET-Framework-Features` fails.

### Repro steps

Run Windows 2022 build.

**Comment by al-cheb** [comment]
Hello @manitua.
Windows Server 2022(20348.1131.221014) Azure image is broken. As a workaround you can rollback image version to `"image_version": "20348.1129.221007"` - https://github.com/al-cheb/virtual-environments/commit/408d5a88f94396fd3d28ed53aa2326a1248c25cd

```
Publisher               : MicrosoftWindowsServer
Offer                   : WindowsServer
Sku                     : 2022-datacenter
Version                 : latest
ExactVersion            : 20348.1131.221014
```

**Comment by manitua** [comment]
Hi @al-cheb,

Sorry for late reply - I have applied rollback workaround yesterday, it built runner image flawlessly :). Thank you!
I hope Microsoft will fix this in next Azure datacenter version of WindowsServer 2022.

**Comment by peterjlay** [comment]
This is still in issue with current build. Setting "image_version" to "20348.1129.221007" didn't work for me.

**Comment by peterjlay** [comment]
I can confirm this is fixed now with latest commit

**Comment by conradj3** [comment]
Hey Y'all, some individuals may use our their own **packer**_.json_ files that closely mimic the main branch but offer customizations such as private networking, shared image gallery, etc...

Make sure you don't miss this in the **Packer** **_builders_** section for Windows 22.

```hcl
        "image_version": "20348.1129.221007",
```


**Example a custom Packer Json Builders Section**
```hcl
 "builders": [{
        "name": "vhd",
        "azure_tags": {
           ...
        },
        "managed_image_name": "{{user `capture_name_prefix`}}",
        "managed_image_resource_group_name": "{{user `resource_group`}}",
        "type": "azure-arm",
        "client_id": "{{user `client_id`}}",
        "client_secret": "{{user `client_secret`}}",
        "subscription_id": "{{user `subscription_id`}}",
        "object_id": "{{user `object_id`}}",
        "tenant_id": "{{user `tenant_id`}}",
        "os_disk_size_gb": "256",
        "location": "{{user `location`}}",
        "vm_size": "{{user `vm_size`}}",
        "shared_image_gallery_destination": {
           ...
        },
        "shared_image_gallery_timeout": "8h",
        "temp_resource_group_name": "{{user `temp_resource_group_name`}}",
        "virtual_network_name": "{{user `virtual_network_name`}}",
        "virtual_network_resource_group_name": "{{user `virtual_network_resource_group_name`}}",
        "virtual_network_subnet_name": "{{user `virtual_network_subnet_name`}}",
        "private_virtual_network_with_public_ip": "{{user `private_virtual_network_with_public_ip`}}",
        "allowed_inbound_ip_addresses": "{{user `allowed_inbound_ip_addresses`}}",
        "os_type": "Windows",
        "image_publisher": "MicrosoftWindowsServer",
        "image_offer": "WindowsServer",
        "image_sku": "2022-Datacenter",
        "image_version": "20348.1129.221007",
        "communicator": "winrm",
        "winrm_use_ssl": "true",
        "winrm_username": "REDACTED"
    }],

**Comment by al-cheb** [comment]
@manitua, @conradj3 , @fady-azmy-msft - the new image version has been published. I have reverted image_version in this https://github.com/actions/runner-images/pull/6545 PR.
