### ISSUE TITLE
Update/Add Pack CLI

### ISSUE THREAD

**Issue by Chthirupathi** [actions/runner-images#6435]
### Tool name

pack CLI

### Tool license

pack CLI (version 0.27.0)

### Add or update?

- [X] Add
- [X] Update

### Desired version

pack CLI (version 0.27.0)

### Brief description of tool

Pack is a tool maintained by the Cloud Native Buildpacks project to support the use of buildpacks.

It enables the following functionality:

1. build an application using buildpacks.
2. Rebaseapplication images created using buildpacks.
3. Creation of various components used within the ecosystem.

### URL for tool's homepage

https://buildpacks.io/docs/tools/pack/#pack-cli

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

10 Min

**Comment by al-cheb** [comment]
Close as https://github.com/actions/runner-images/issues/6415
