### ISSUE TITLE
Update GitHub CLI version in runners before next scheduled update considering this case an exception

### ISSUE THREAD

**Issue by vedantmgoyal2009** [actions/runner-images#6446]
### Description

GitHub CLI had a regression issue recently, due to which PRs were not created in non-interactive mode. The issue was fixed in v2.18.1 - https://github.com/cli/cli/releases/tag/v2.18.1.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

`win22/20221019.1` - https://github.com/actions/runner-images/releases/tag/win22%2F20221019.1

### Is it regression?

Yes, win22/20221012.4  https://github.com/actions/runner-images/releases/tag/win22%2F20221012.4

### Expected behavior

PR creation using GitHub CLI fails.

### Actual behavior

PR should be created.

### Repro steps

* Refer to https://github.com/cli/cli/issues/6467

**Comment by vedantmgoyal2009** [comment]
Latest runner image has GitHub CLI v2.18.0, the release in which this bug was introduced.

**Comment by al-cheb** [comment]
Hey @vedantmgoyal2009.
We will update GitHub CLI next week.

**Comment by vedantmgoyal2009** [comment]
Can't it be updated earlier? Many workflows are failing due to this.

**Comment by al-cheb** [comment]
> Can't it be updated earlier? Many workflows are failing due to this.

Weekends are the deployment freeze, we will try to start on Monday.

**Comment by vedantmgoyal2009** [comment]
It's Moday, please deploy. I can't see the pre-release.

**Comment by vedantmgoyal2009** [comment]
There are half of the workflow runs running on 20221024 update and half of them on 20221019 update. 

Why you guys don't consider the impact caused due to a bug, and prioritize the things according to that.

**Comment by mikhailkoliada** [comment]
Our deployment schedule takes 3-4 days, to catch all possible bugs, please keep the ticket open, we will close it ourselves once all updates are rolled out.

**Comment by al-cheb** [comment]
The new images with GitHub CLI v2.18.1 have been deployed.

**Comment by vedantmgoyal2009** [comment]
Thanks a lot 🙏🏻
