### ISSUE TITLE
Add [Tizen Studio]

### ISSUE THREAD

**Issue by yassinox1234** [actions/runner-images#6448]
### Tool name

Tizen Studio

### Tool license

https://docs.tizen.org/application/tizen-studio/setup/install-sdk/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

4.6

### URL for tool's homepage

https://developer.tizen.org/development/tizen-studio/download

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
Hey @yassinox1234.
We are not going to add Tizen Studio due to lack of free space on images and maintenance concerns.
