### ISSUE TITLE
Update g++

### ISSUE THREAD

**Issue by poconn** [actions/runner-images#6451]
### Tool name

GNU g++

### Tool license

GPL-2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

12 (to match installed gcc version)

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
We are installing the default build-essentials package which is now pulling only gnu toolchains versioned as 11, not 12
