### ISSUE TITLE
Update/Add Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [actions/runner-images#6472]
### Tool name

Microsoft Windows Package Manager

### Tool license

MIT (https://github.com/microsoft/winget-cli/blob/master/LICENSE)

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whatever is latest

### Brief description of tool

The Windows Package Manager is an open-source tool that is capable to be used by both the home user and the enterprise user. The tool enables users to get the right software installed (or uninstalled) on their machine to be productive.

### URL for tool's homepage

https://github.com/microsoft/winget-cli

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Invoke-WebRequest -Uri 'https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx' -OutFile 'VCLibs.appx'
Invoke-WebRequest -Uri 'https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -OutFile 'winget.msixbundle'
Invoke-WebRequest -Uri 'https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/9c0fe2ce7f8e410eb4a8f417de74517e_License1.xml' -OutFile 'license.xml'
Import-Module -Name Appx -UseWindowsPowerShell
Add-AppxProvisionedPackage -Online -PackagePath .\winget.msixbundle -DependencyPackagePath .\VCLibs.appx -LicensePath .\license.xml
Install-Module NtObjectManager -Force # Install NtObjectManager module
$installationPath = (Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation # Create reparse point
Set-ExecutionAlias -Path 'C:\Windows\System32\winget.exe' -PackageName 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe' -EntryPoint 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget' -Target "$installationPath\AppInstallerCLI.exe" -AppType Desktop -Version 3
explorer.exe 'shell:appsFolder\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget'
```

### Tool installation time in runtime

3-5 minutes (approx.)

### Are you willing to submit a PR?

Yes

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/runner-images/issues/910

https://github.com/microsoft/winget-cli#installing-the-client

> The client requires Windows 10 1809 (build 17763) or later at this time. Windows Server 2019 is not supported as the Microsoft Store is not available nor are updated dependencies. It may be possible to install on Windows Server 2022, this should be considered experimental (not supported), and requires dependencies to be manually installed as well.

**Comment by vedantmgoyal2009** [comment]
@al-cheb you're a contributor, how can you close the issue?

Also, as the note specifies that it is possible to (experimentally) install on Windows Server 2022, may be that can be added?

**Comment by vedantmgoyal2009** [comment]
Well, I've added my comments on the original issue.

**Comment by al-cheb** [comment]
> @al-cheb you're a contributor, how can you close the issue? (just curious to know about it 😅)
> 
> Well, as the note specifies that it is possible to (experimentally) install on Windows Server 2022, maybe that can be added?
> 
> Also, I found a clean installation method, without any extra installations and modifications:
> 
> ```powershell
> Invoke-WebRequest -Uri 'https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx' -OutFile 'VCLibs.appx' # automatically downloads latest version
> Invoke-WebRequest -Uri 'https://github.com/microsoft/winget-cli/releases/download/latest/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -OutFile 'winget.msixbundle'
> $ReleaseInfo = Invoke-RestMethod 'https://api.github.com/repos/microsoft/winget-cli/releases/latest'
> Invoke-WebRequest -Uri $ReleaseInfo.assets.Where({ $_.name.EndsWith('License1.xml') }).browser_download_url -OutFile 'license.xml' # because the prefix of the file changes with every release
> 
> Add-AppxProvisionedPackage -Online -PackagePath winget.msixbundle -LicensePath license.xml -DependencyPackagePath VCLibs.appx
> ```

Windows Server 2022, this should be considered experimental **(not supported)** - https://github.com/microsoft/winget-cli#installing-the-client
