### ISSUE TITLE
Add Python 3.12.0a1 (3.12-dev) support

### ISSUE THREAD

**Issue by parafoxia** [actions/runner-images#6473]
### Tool name

Python

### Tool license

PSF-2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.12.0a1

### Brief description of tool

3.12.0a1 was released on 24 October just after the release of 3.11.0. This should be released to allow for the inclusion of 3.12-dev Python versions within workflows.

### URL for tool's homepage

https://docs.python.org/3.12/whatsnew/3.12.html

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

This issue concerns the actions/setup-python action (with regard to the python-versions repo specifically).

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

Probably the same as other Python versions.

### Are you willing to submit a PR?

I wouldn't know how, but would be open to learn what I'd need to do.

**Comment by erik-bershel** [comment]
@parafoxia 
Hi! We'll take a look.

**Comment by erik-bershel** [comment]
@parafoxia 
We will add these changes in our images when this minor branch becomes stable but not preview or alfa. Until then, only installation in runtime will be available.

**Comment by parafoxia** [comment]
@erik-bershel

I'm a bit confused -- is Python 3.12 support only plans upon the release of final? This would be for the python-versions action btw, not preinstallation of the OS images. Apologies if I wasn't clear on that.

**Comment by erik-bershel** [comment]
@parafoxia it is okay. Feel free to ask anything.
About our case. We will add Python 3.12 directly to the runner images only after it becomes an [active official release](https://www.python.org/downloads/) according to the [software support policy](https://github.com/actions/runner-images#software-and-image-support) or in case if it becomes very popular. Until then, you can install in runtime the version, which one is in work right now according to that issue, by using [setup-python](https://github.com/actions/setup-python) action, or choose another path that suits you.
If you started this task in order for the actions team to add the latest version to the python-version, then generally this is exactly what will happen.

**Comment by parafoxia** [comment]
Okay awesome, thanks for the clarification! This sounds great -- I use the setup-python action generally to test compatibility with different versions, so yeah this issue was mainly for that. I look forward to the release!

**Comment by hugovk** [comment]
Here's the tracking issue for `3.12-dev` in `actions/setup-python`:

* https://github.com/actions/setup-python/issues/514

**Comment by kxrob** [comment]
Was also (miss-)guided here from https://github.com/actions/python-versions  :

> Please open an issue in [actions/virtual-environments](https://github.com/actions/virtual-environments) if any versions are missing.

( The link auto-translates to https://github.com/actions/runner-images )

That Readme link should perhaps be changed to https://github.com/actions/setup-python/issues

**Comment by al-cheb** [comment]
https://github.com/actions/setup-python/issues/514#issuecomment-1308580602
Python 3.12.0-alpha.1 is now available!
