### ISSUE TITLE
[all OSs] Nodejs 12.x will be removed from the images on November, 14

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#6482]
### Breaking changes

Nodejs 12.x will be removed from all the images alongside with its docker containers on Ubuntu runners.

### Target date

Rollout of the change will start on November, 14 and will take 3-4 days.

### The motivation for the changes

As per the [software and image support](https://github.com/actions/runner-images#software-and-image-support) policy only the 3 latest LTS versions are supported. The v18.x branch has become LTS on 2022/10/25.

### Possible impact

If your builds depend on the version v12.x they will take longer as this branch will not be pre-cached in the images anymore.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Nothing is required, if you are using the [Node Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) task (for Azure DevOps) and the [setup-node](https://github.com/actions/setup-node) action (for GitHub Actions) both will still download a version you specify if it is available in the [versions-manifest.json](https://github.com/actions/node-versions/blob/main/versions-manifest.json) file.

**Comment by hazem6767** [comment]
I need to send it to the wallet

**Comment by MikeMcC399** [comment]
If Node.js 12 is removed from the images will this stop actions relying on Node.js 12 from working or will they still have access to Node.js 12?

See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing which says:

`runs.using`

Required The runtime used to execute the code specified in [main](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsmain).

Use `node12` for Node.js v12.
Use `node16` for Node.js v16.

**Comment by mikhailkoliada** [comment]
@MikeMcC399 no, both tasks still will download a version you specify if it is listed in the [versions-manifest.json](https://github.com/actions/node-versions/blob/main/versions-manifest.json) file as stated in the mitigation section.

**Comment by MikeMcC399** [comment]
@mikhailkoliada 
> no, both tasks still will download a version you specify if it is listed in the [versions-manifest.json](https://github.com/actions/node-versions/blob/main/versions-manifest.json) file as stated in the mitigation section.

Thanks for the confirmation! I wasn't sure, since `runs.using` wasn't explicitly mentioned in "Mitigation ways" in the original post.

**Comment by mikhailkoliada** [comment]
Deployed
