### ISSUE TITLE
getting error while install system ds as fatal error compiling

### ISSUE THREAD

**Issue by chandrashekarkandepu** [actions/runner-images#6485]
### Description

<img width="1440" alt="Screen Shot 2022-10-27 at 7 25 39 PM" src="https://user-images.githubusercontent.com/34734568/198423548-8f1c7cb4-4d75-4db9-88d1-dc8a9be61c2d.png">

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

<img width="1440" alt="Screen Shot 2022-10-27 at 7 25 39 PM" src="https://user-images.githubusercontent.com/34734568/198423571-11d2d004-6ecd-4428-a319-c0cd25597170.png">

### Is it regression?

no this is the first time installation

### Expected behavior

Build success

### Actual behavior

when i try to run mvn clean package -P distribution this command this is showing fatal error

### Repro steps

just run with the java 1.8

**Comment by al-cheb** [comment]
Hey @chandrashekarkandepu.
We don't support non hosted github agents.
