### ISSUE TITLE
Cannot use actions to connect to apt-get (Repeat of #675)

### ISSUE THREAD

**Issue by luke-hill** [actions/runner-images#6486]
### Description

Running `Run sudo apt-get install libcurl4-openssl-dev` in github actions fails with an error

This looks like a clone of #675

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not sure what this is asking? I cannot find the link flow. Where is "Set up job"

### Is it regression?

I believe so from #675

### Expected behavior

The sudo command to install packages

### Actual behavior

```
Suggested packages:
  libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 322 kB of archives.
After this operation, 1543 kB of additional disk space will be used.
Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.13
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.13
  404  Not Found [IP: 52.[25](https://github.com/Globacap/web-automation/actions/runs/3342414147/jobs/5537865982#step:2:26)2.75.106 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.13_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

### Repro steps

As described

**Comment by al-cheb** [comment]
Hey @luke-hill.

Please note: https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners

> Note: Always run sudo apt-get update before installing a package. In case the apt index is stale, this command fetches and re-indexes any available packages, which helps prevent package installation failures.

Should be:
```
 - run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
```

**Comment by luke-hill** [comment]
Is there a reason this has passed ~ 300 times in the past 2+ months without this then?

**Comment by al-cheb** [comment]
> Is there a reason this has passed ~ 300 times in the past 2+ months without this then? To help my knowledge for the future e.t.c.

https://github.com/actions/runner-images/issues/592#issuecomment-602448135

**Comment by luke-hill** [comment]
So ubuntu updated this lib-ssl package, which hasn't happened for a while. And as such the old cache one is invalidated and it cannot find the existing one on the server without updating refs first.

TIL - Many thanks @al-cheb 🥇

**Comment by jrochkind** [comment]
I am running `sudo apt-get -y update` but am still getting connection errors here; I think others are too at the moment. 

Very slow connections to upstream apt repo; timeouts; or 404s. 

I think there is actually something that is wrong with the upstream server, that intermittently goes wrong with it. Not sure if we should file a separate ticket.

**Comment by manitgupta** [comment]
This error occurs even after adding `sudo apt-get update` in the command:

Failed workflow: https://github.com/cloudspannerecosystem/harbourbridge/actions/runs/3908957093/jobs/6679673034

Upated Workflow file: https://github.com/cloudspannerecosystem/harbourbridge/actions/runs/3908957093/workflow#L130
