### ISSUE TITLE
Provide pre-built, or make it possible to build locally, runner images for local testing

### ISSUE THREAD

**Issue by nagisa** [actions/runner-images#6487]
### Description

I have Github Actions run that runs some tests. These tests are segfaulting reliably in a Github Actions run, but not in an environment which was a best-effort replication of the GHA environment (I went ahead and grabbed a win2k22 evaluation image, pointed qemu at it and tried running tests on there...)

This makes me suspect that there is something very specific about how the VM image is setup in GHA and I will not be able to reproduce the issue without getting the VM image itself to use.

Now, an issue is that building VM images based on the instructions provided in this repository requires Azure – probably with billing enabled – and I have access to neither. So in practice obtaining a runner image is infeasible as is, at least not using the instructions provided.

Is there a reason why building images locally isn’t a supported mode of operation? What would it take to make it possible?

Is there a reason why GitHub is unable to provide images themselves? What would it take to make _that_ possible?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

  Image: windows-2022
  Version: 20221024.1

### Is it regression?

No.

### Expected behavior

It should be easier to reproduce the results of CI locally.

### Actual behavior

Right now it is very difficult and requires cloud resources as a prerequisite.

### Repro steps

Attempt to follow [these instructions](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md) without any access to Azure.

**Comment by al-cheb** [comment]
Hey @nagisa.

1. Is there a reason why building images locally isn’t a supported mode of operation? What would it take to make it possible?
We don't have any test environments expect Azure to build  images and the second concern is that it would take a huge amount of time to maintenance and support it. - https://github.com/actions/runner-images/issues/931

2. Is there a reason why GitHub is unable to provide images themselves? What would it take to make that possible?
https://github.com/actions/runner-images/discussions/3919
