### ISSUE TITLE
This version of Xamarin.iOS requires the iOS 16.0 SDK (shipped with Xcode 14.0)

### ISSUE THREAD

**Issue by Nisim761** [actions/runner-images#6493]
### Description

MTOUCH : error MT0180: This version of Xamarin.iOS requires the iOS 16.0 SDK (shipped with Xcode 14.0). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115

### Is it regression?

I do not know

### Expected behavior

The app will be built.

### Actual behavior

Getting the error in the description.

### Repro steps

I am try to build Xamarin app for iOS. Running on Circle-CI with XCode 13.2.1.

As this is a virtual machine, I do not have GUI. Is there a command line or a parameter I can pass to the "msbuild" command, to bypass this error?

**Comment by igorboskovic3** [comment]
Hi @Nisim761,thank you for reporting this one, we will take a look.

**Comment by mikhailkoliada** [comment]
@Nisim761 Hello!

> I am try to build Xamarin app for iOS. Running on Circle-CI with XCode 13.2.1.

Not sure I am following, the error message requires you to have xcode-14 which is a part of macos-12, plus circle ci and actions are quite different entities. 

I am going to close that issue as non-relevant one. Please let us know if we are wrong.
