### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by michaelsaxbury** [actions/runner-images#6495]
### Tool name

velero

### Tool license

open

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Velero (formerly Heptio Ark) gives you tools to back up and restore your Kubernetes cluster resources and persistent volumes. You can run Velero with a cloud provider or on-premises. Velero lets you:

Take backups of your cluster and restore in case of loss.
Migrate cluster resources to other clusters.
Replicate your production cluster to development and testing clusters.
Velero consists of:

A server that runs on your cluster
A command-line client that runs locally

### URL for tool's homepage

https://velero.io/docs/v1.9/index.html

### Provide a basic test case to validate the tool's functionality.

```bash
velero version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
https://velero.io/docs/v1.9/basic-install/

Option 2: GitHub release
Download the latest release’s tarball for your client platform.

Extract the tarball:

tar -xvf <RELEASE-TARBALL-NAME>.tar.gz
Move the extracted velero binary to somewhere in your $PATH (/usr/local/bin for most users).

Option 3: Windows - Chocolatey
On Windows, you can use Chocolatey to install the velero client:

choco install velero
```

### Tool installation time in runtime

few minutes

**Comment by al-cheb** [comment]
Hey @michaelsaxbury .
Considering can be installed in runtime, we wouldn't like to bake it into the image due to maintenance concerns

**Comment by michaelsaxbury** [comment]
I downloaded the latest package using powershell core in an Azure CLI task in my azure devops pipeline. It extracts successfully, but I cannot call velero to perform any actions?

$url = 'https://github.com/vmware-tanzu/velero/releases/latest'
$request = [System.Net.WebRequest]::Create($url)
$response = $request.GetResponse()
$realTagUrl = $response.ResponseUri.OriginalString
$version = $realTagUrl.split('/')[-1].Trim('v')
$version
$realTagUrl

$fileName = "velero-$($realTagUrl.split('/')[-1])-linux-arm64.tar.gz"
$realDownloadUrl = $realTagUrl.Replace('tag', 'download') + '/' + $fileName
$realDownloadUrl
"=================="
Invoke-WebRequest -Uri $realDownloadUrl -OutFile "$(System.ArtifactsDirectory)/$($fileName)"

Write-Host "`r`nDownloaded file"
ls

Write-Host "`r`nExtract the tar"
tar -xvf $fileName

Write-Host "`r`nExtracted contents"
ls

#Write-Host "`r`nVelero path:"
#$extractedFolderName = $fileName -replace '.tar.gz', ''
#"$(System.ArtifactsDirectory)/$($extractedFolderName)/velero"

#Write-Host "`r`nCD to velero path"
#cd $(System.ArtifactsDirectory)/$extractedFolderName
#ls

Write-Host "`r`nVelero run"
**#ALL of these fail** 
.\velero version
velero version
& velero version
$(System.ArtifactsDirectory)/$extractedFolderName/velero version
$(System.ArtifactsDirectory)/velero-v1.9.2-linux-arm64/velero version


Program 'velero' failed to run: An error occurred trying to start process '/home/vsts/work/r1/a/velero-v1.9.2-linux-arm64/velero' with working directory '/home/vsts/work/r1/a/velero-v1.9.2-linux-arm64'. Exec format errorAt /home/vsts/work/_temp/azureclitaskscript1667250930999_inlinescript.ps1:35 char:1

**Comment by al-cheb** [comment]
bash script:
```
latest="https://api.github.com/repos/vmware-tanzu/velero/releases/latest"
url=$(curl -sL $latest | jq -r '.assets[].browser_download_url | select(endswith("linux-amd64.tar.gz"))')
wget $url -O velero-linux-amd64.tar.gz
tar -zxvf velero-linux-amd64.tar.gz
sudo mv */velero /usr/local/bin/
```

venero help output:
![image](https://user-images.githubusercontent.com/47745270/199198452-8febb944-c853-4044-8cb5-d5edc1880618.png)
