### ISSUE TITLE
Homebrew installed libraries not being loaded properly

### ISSUE THREAD

**Issue by gotson** [actions/runner-images#6497]
### Description

Hi,

tbh i am not sure what's the problem here, but i will try to explain the best i can. I feel like something is wrong with the Linux environment, but i can't pinpoint what exactly.

My Java project is using native libraries, the CI used to work fine on both macOS and ubuntu 20.04. The [last run](https://github.com/gotson/NightMonkeys/actions/runs/2931046772) was 2 months ago.

Here is how it's setup:
- The libraries are installed on both Linux and Mac [using homebrew](https://github.com/gotson/NightMonkeys/blob/ecbbfc037b5df52e64a9fa1c60768f20f6d717b0/.github/workflows/ci.yml#L34-L34).
- The libraries are then made available to Java (via Gradle), [using the environment variable](https://github.com/gotson/NightMonkeys/blob/ecbbfc037b5df52e64a9fa1c60768f20f6d717b0/.github/workflows/ci.yml#L43-L43) `LD_LIBRARY_PATH` for Linux, set to `/home/linuxbrew/.linuxbrew/lib`.

Yesterday, after doing some changes, i noticed it was not working anymore, but only for Linux. I figured out that was because of the recent change for HomeBrew, so i added the Setup homebrew action. However, it was still not working.

After some more troubleshooting, i found that:
- [it works](https://github.com/gotson/NightMonkeys/actions/runs/3367192600/jobs/5584443893) on `ubuntu-22.04`, but fails on `ubuntu-18.04` and `ubuntu-latest`
- [it works](https://github.com/gotson/NightMonkeys/actions/runs/3367193558/jobs/5584445829) on all ubuntu versions if i only test with `libwebp`, but fails with `libjpxl`

I was inclined to think that the problem was with the homebrew package (libjxl version changed from 6.1.1 to 7.0.1 since it worked 2 months ago), but the fact that it works on Ubuntu 22.04 and not on other versions make me think there could be a problem with the runner environment.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-18.04
Version: 20221018.2

Image: ubuntu-20.04
Version: 20221024.1

### Is it regression?

Image: ubuntu-20.04   Version: 20220821.1 https://github.com/gotson/NightMonkeys/actions/runs/2931046772/jobs/4678006883

### Expected behavior

The Gradle`build` should succeed, meaning the native libraries installed with homebrew are loaded correctly.

### Actual behavior

The Gradle `build` fails, tests are failing because native libraries located in `/home/linuxbrew/.linuxbrew/lib` are not found.

### Repro steps

I can't provide repro steps apart from running my project

**Comment by igorboskovic3** [comment]
Hi @gotson, we will take a look and get back to you.

**Comment by mikhailkoliada** [comment]
We do not really manage homebrew anyhow now other than installing it into the image and the action itself just adds brew to the [path]https://github.com/Homebrew/actions/blob/master/setup-homebrew/main.sh#L34)
