### ISSUE TITLE
Packer build fails to provision Windows 2022 VM correctly in Azure Devops 

### ISSUE THREAD

**Issue by rmurphyaxa** [actions/runner-images#6498]
### Description

Hi,
We have been building packer generated windows self hosted agents with a hosted agent (vers 2.211.1) in Azure DevOps and uploaded these to an Azure shared image gallery.

The packer build uses the windows 2022 packer build (https://github.com/actions/runner-images/blob/main/images/win/windows2022.json) which was patched to point the target location to a Azure shared_image_gallery rather than an Azure storage_account. 
'''
git format-patch main
'''
Updated section;
'''
            "shared_image_gallery_destination": {
                "subscription": "{{user `subscription_id`}}",
                "resource_group": "{{user `resource_group`}}",
                "gallery_name": "{{user `gallery_name`}}",
                "image_name": "{{user `image_name`}}",
                "image_version": "{{user `image_version`}}",
                "replication_regions": ["northeurope","westeurope"]
            },
'''
When the pipeline runs, the provisioning of the VM appears to succeed however when it attempts to upload to the shared_image_gallery_destination, the following message is received. 
'''
    vhd: Provisioning with powershell script: /tmp/powershell-provisioner67359974

    vhd: IMAGE_STATE_COMPLETE

    vhd: IMAGE_STATE_UNDEPLOYABLE

    vhd: IMAGE_STATE_UNDEPLOYABLE

    vhd: IMAGE_STATE_UNDEPLOYABLE

    vhd: IMAGE_STATE_UNDEPLOYABLE
'''

I retested by removing all the provisioning steps except for the final upload steps. The VM builds and the image is created/uploaded successfully so it appears there is an issue in the provisioning steps. I tested this with a Gen-2 version of the VM image with similar results.

'''
        {
            "type": "powershell",
            "skip_clean": true,
            "scripts": [
                "{{ template_dir }}/scripts/Installers/Finalize-VM.ps1"
            ]
        },
        {
            "type": "windows-restart",
            "restart_timeout": "10m"
        },
        {
            "type": "powershell",
            "inline": [
                "if( Test-Path $Env:SystemRoot\\System32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\System32\\Sysprep\\unattend.xml -Force}",
                "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /mode:vm /quiet /quit",
                "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
            ]
        }
'''

Could someone indicate what steps need to be taken to get the VM to provision correctly?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az86-53'
Current agent version: '2.211.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20221024.1'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.201.1)
Downloading task: AzureCLI (2.208.0)
Downloading task: PackerBuild (1.208.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

not available

### Expected behavior

Provisioning steps succeed and finally, image is created and uploads to shared image gallery

### Actual behavior

Provisioning steps appear to succeed but fails to create image and can't upload to shared image gallery.

### Repro steps

AzDO steps;
1. git clone https://github.com/actions/virtual-environments.git
2. Apply patch 'git apply  --reject --whitespace=fix $(Build.SourcesDirectory)/self-hosted-agents/patches/${{ image_type }}.json-patch'
3. Set image variables 
            $ImageType = "${{ image_type }}"
            $TemplateDirectoryName = if ($ImageType.StartsWith("ubuntu")) { "linux" } else { "win" }
            $OsType = if ($ImageType.StartsWith("ubuntu")) { "Linux" } else { "Windows" }
            $TemplateDirectoryPath = Join-Path (Join-Path "virtual-environments" "images") $TemplateDirectoryName | Resolve-Path
            $TemplatePath = Join-Path $TemplateDirectoryPath "windows2022.json"
            $ImageReadmeNameConcat = "${{ image_type }}-README.md"
            $ImageReadmeName = $ImageReadmeNameConcat.Substring(0,1).ToUpper()+$ImageReadmeNameConcat.Substring(1)
            $InstallPassword = [System.GUID]::NewGuid().ToString().ToUpper()
            $SubscriptionId = az account show --query "id" -o tsv 
            Write-Host "##vso[task.setvariable variable=TemplateDirectoryPath]$TemplateDirectoryPath"
            Write-Host "##vso[task.setvariable variable=TemplatePath]$TemplatePath"
            Write-Host "##vso[task.setvariable variable=OsType]$OsType"
            Write-Host "##vso[task.setvariable variable=ImageType]$ImageType"
            Write-Host "##vso[task.setvariable variable=ImageReadmeName]$ImageReadmeName"
            Write-Host "##vso[task.setvariable variable=InstallPassword]$InstallPassword"
            Write-Host "##vso[task.setvariable variable=client_id]$env:servicePrincipalId"
            Write-Host "##vso[task.setvariable variable=client_secret;issecret=true]$env:servicePrincipalKey"
            Write-Host "##vso[task.setvariable variable=subscription_id]$SubscriptionId"
            Write-Host "##vso[task.setvariable variable=tenant_id]$env:tenantId"
4. Run packer build
      - task: PackerBuild@1
        inputs:
          templateType: 'custom'
          customTemplateLocation: $(TemplatePath)
          customTemplateParameters: '{"client_id":"$(client_id)","client_secret":"$(client_secret)","tenant_id":"$(tenant_id)","subscription_id":"$(subscription_id)","resource_group":"$(resource_group)","build_resource_group_name":"$(build_resource_group_name)","image_name":"$(image_name)","image_version":"$(image_version)","gallery_name":"$(gallery_name)","install_password":"$(InstallPassword)","location":"$(location)","github_feed_token":"$(github_feed_token)"}'
          connectedServiceName: 'AXA IE Prod (Owner Role)'

**Comment by igorboskovic3** [comment]
Hi @rmurphyaxa, we will take a look.

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/runner-images/discussions/6251
