### ISSUE TITLE
Swift package manager stuck on package resolution

### ISSUE THREAD

**Issue by jfk056** [actions/runner-images#6503]
### Description

We have start using the new version of Xcode 14.0.1/14.1 on macOS 12 agent back in the September but recently we are seeing some strange behaviour around swift package resolution process when we add new package to the project and the process will get stuck on resolution until we hit timeout on the pipeline. We have tried multiple things to debug this kind of behaviour but so far this lead to nowhere. 

Project is mixed with private Github repositories and public repositories. We have even tried to test it by removing some of our internal packages but this didn't had any effect on the process. The issue started to appear about 18 days ago. We have tried to run it without the fastlane and use xcodebuild via script directly and it still didn't had any effect. 

Could it be that behind the scenes some process might get stuck because it awaits for some keychain action?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20221027.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20221027.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20221027.1

Image: macos-12
Version: 20221010.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20221010.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20221010.1

### Is it regression?

Yes

### Expected behavior

The resolution process wouldn't hold the pipeline until it times out.

### Actual behavior

Described above

### Repro steps

Don't have exact steps for reproducing this issue.

**Comment by bogdan-damian-bgd** [comment]
Hi @jfk056, we will take a look and get back to you.

**Comment by bogdan-damian-bgd** [comment]
Hi @jfk056, could you provide us with minimal repro steps?

**Comment by mikhailkoliada** [comment]
I am going to close. If you have new info feel free to reach us again!
