### ISSUE TITLE
[go-versions] Get Go version action should be in sync with Go releases

### ISSUE THREAD

**Issue by maraino** [actions/runner-images#6504]
### Description

Go versions, especially security releases, are generally released minutes before 10 am Pacific Time. But the cronjob in [go-versions](https://github.com/actions/go-versions/blob/8b01adb6c0565ba2e44413df1bea0b29e04ccd49/.github/workflows/get-go-versions.yml#L1-L4) that I think it checks for new Go versions runs at `0 3,15 * * *`. 

Right now, on daylight saving, the release versions happen at 5 pm UTC (17). And if I am not mistaken, on the standard time, PST, the release will happen at 6 pm UTC (18).

The current cronjob won't pick new releases until 3 am, between 9 and 10 hours later than an actual release.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/go-versions/actions/runs/3370470118

### Is it regression?

No

### Expected behavior

Get Go version action should be in sync with Go releases.

### Actual behavior

Get Go version action runs between 9 and 10 hours late.

### Repro steps

N/A

**Comment by bogdan-damian-bgd** [comment]
Hey @maraino, thanks for reporting this one, we'll take a look and get back to you.

**Comment by Talalgmel** [comment]
I

**Comment by Talalgmel** [comment]
---------- Forwarded message ---------
From: Talal Gmel ***@***.***>
Date: Fri, 11 Nov 2022, 3:09 pm
Subject: Re: [actions/runner-images] [macOS] remove node12 and sync nvm18
(PR #6553)
To: actions/runner-images <
***@***.***>


S

**Comment by dmitry-shibanov** [comment]
Hello @maraino. The pull requests need manual approve from the team that is why I think changing schedule won't improve delivery of new versions because the creation of new pull request won't be in our working hours. 

For now I'm going to close the issue.
