### ISSUE TITLE
Update/Add lcov

### ISSUE THREAD

**Issue by alandefreitas** [actions/runner-images#6508]
### Tool name

lcov

### Tool license

GPL-2.0 license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

LCOV is an extension of GCOV, a GNU tool which provides information about what parts of a program are actually executed (i.e. "covered") while running a particular test case. 

After writing tests with your test suite you can generate a coverage report using lcov and upload that coverage report to Codecov as a part of your CI workflow.

### URL for tool's homepage

https://wiki.documentfoundation.org/Development/Lcov

### Provide a basic test case to validate the tool's functionality.

```bash
lcov --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt install -y lcov
```

### Tool installation time in runtime

5 secs

### Are you willing to submit a PR?

Yes if I'm capable of

**Comment by mikhailkoliada** [comment]
Hello!

Given the runtime installation time (3-5s) we would like not to preinstall it into the image
