### ISSUE TITLE
Update/Add GCC 12

### ISSUE THREAD

**Issue by alandefreitas** [actions/runner-images#6509]
### Tool name

GCC 12

### Tool license

GPL-2.0 and 2 other licenses found

### Add or update?

- [X] Add
- [X] Update

### Desired version

GCC 12

### Brief description of tool

The GNU Compiler Collection includes front ends for [C](https://gcc.gnu.org/c99status.html), [C++](https://gcc.gnu.org/projects/cxx-status.html), Objective-C, [Fortran](https://gcc.gnu.org/fortran/), Ada, Go, and D, as well as libraries for these languages (libstdc++,...). GCC was originally written as the compiler for the [GNU operating system](http://www.gnu.org/gnu/thegnuproject.html). The GNU system was developed to be 100% free software, free in the sense that it [respects the user's freedom](http://www.gnu.org/philosophy/free-sw.html).

### URL for tool's homepage

https://gcc.gnu.org/

### Provide a basic test case to validate the tool's functionality.

```bash
gcc --version
g++ --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt install -y gcc-12 g++-12
```

### Tool installation time in runtime

25 seconds

### Are you willing to submit a PR?

Yes if I'm capable of

**Comment by mikhailkoliada** [comment]
Thanks, we will add it

**Comment by EwoutH** [comment]
With #6511 merged, does that mean GCC 12 is fully added?

**Comment by EwoutH** [comment]
That should happen within a week or so right?

**Comment by mikhailkoliada** [comment]
@EwoutH yes
