### ISSUE TITLE
Ubuntu 22.04 SKUs have changed - "22_04-lts" is not longer valid

### ISSUE THREAD

**Issue by andrewvr99** [actions/runner-images#6510]
### Description

File images\linux\ubuntu2204.pkr.hcl refers to an out of date SKU. For the selected image_offer of "0001-com-ubuntu-server-jammy", the only valid SKUs are pro-22_04-lts and pro-22_04-lts-gen2, as can be seen from the output of this command:

Get-AzVMImageSku -Location 'westus' -PublisherName  'canonical' -Offer '0001-com-ubuntu-pro-jammy' | Select Skus

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current image version: '20221024.1'

https://dev.azure.com/CCBA-BI/Azure%20Integration%20Services/_build/results?buildId=9299&view=logs&j=e050bae0-d3ce-5baf-0955-f0db6008a7bd&t=e616c8dc-5598-40c0-9c45-d990462d5409&l=8

### Is it regression?

no

### Expected behavior

The Packer initialization should successfully find the source image name

### Actual behavior

==> azure-arm.build_vhd: Getting source image id for the deployment ...
==> azure-arm.build_vhd:  -> SourceImageName: '/subscriptions/3edc06c0-bb0d-4d61-a610-951165f1fa93/providers/Microsoft.Compute/locations/westeurope/publishers/canonical/ArtifactTypes/vmimage/offers/0001-com-ubuntu-server-jammy/skus/22_04-lts/versions/latest'
==> azure-arm.build_vhd: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ImageManagementOperationError",
        "message": "An internal error occurred in an image related operation."
      }
    ]
  }
}"}]

### Repro steps

I am running this in a private DevOps pipeline, (based on the work by YannickRe), that uses the images and tooling installation from the runner-images GIT repo

**Comment by al-cheb** [comment]
Hey @andrewvr99. 
We don't see any issues with nightly Ubuntu22 builds.
```
PS > az vm image list --location 'westus' --publisher Canonical --offer '0001-com-ubuntu-server-jammy' --sku '22_04-lts' --query '[].sku' --all --output tsv | Sort-Object -Unique
22_04-lts
22_04-lts-arm64
22_04-lts-gen2
```
