### ISSUE TITLE
ubuntu-latest in readme wrong

### ISSUE THREAD

**Issue by to-s** [actions/runner-images#6513]
### Breaking changes

22.04 is becoming the new _ubuntu-lastest_. Source: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221027.1 // https://github.com/actions/runner-images/issues/6399

### Target date

Now

### The motivation for the changes

We already running into issue caused by using the _ubuntu-latest_ label.

### Possible impact

Apt is not able to install packages (e.g. gcc-7) which were available in 20.04.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Already provided with https://github.com/actions/runner-images/pull/6512 but was unmerged closed by @mikhailkoliada

**Comment by mikhailkoliada** [comment]
The migration is not yet done. we update readmes automatically.
