### ISSUE TITLE
Powershell Install-Package ran into error "Unable to resolve package reference '' in ubuntu pool agent

### ISSUE THREAD

**Issue by JiayuanL** [actions/runner-images#6514]
### Description

I have been using azure pipeline with vmImage: 'ubuntu-latest', and run "install-package" powershell, the exact same powershell working in my local ubuntu, but ran into error "Unable to resolve package reference '' in ubuntu pool agent. I checked the ubuntu version and powershell version, both are same, can you help what could be the issue and how should I resolve it?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

NA

### Is it regression?

no

### Expected behavior

powershell install-package could be run

### Actual behavior

"Unable to resolve package reference ''

### Repro steps

Described in description

**Comment by al-cheb** [comment]
Hey @JiayuanL
I can' t reproduce the issue:

```
steps:
- powershell: 'Install-Package Posh-SSH -Force -Confirm:$false'
  displayName: 'Install package'
```
![image](https://user-images.githubusercontent.com/47745270/199922654-fc379dd4-6d08-4053-a0b0-7b4dbd2837c7.png)

Could you provide package name?

**Comment by JiayuanL** [comment]
Thanks @al-cheb  for your reply, the powershell I am using is as below:
	$Pkg = Install-Package $File.Basename -Source $File.Directory -Destination $Target -Force -Confirm:$false
And the error I hit is:
![image](https://user-images.githubusercontent.com/49004334/200039471-c80d54d1-3f0a-4968-a9fb-67881cbe1b88.png)

**Comment by al-cheb** [comment]
@JiayuanL, please attach a pkg archive that we can test it locally.
