### ISSUE TITLE
Add super-linter docker image

### ISSUE THREAD

**Issue by felipem1210** [actions/runner-images#6521]
### Tool name

Super-linter

### Tool license

MIT license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

slim-latest

### Approximate size

1.37GB

### Brief description of tool

The super-linter is a tool created by Github, it would be nice to have the docker image already included in the image of github runners, so we don't have to wait 1 minute of download of this docker image.

### URL for tool's homepage

https://github.com/github/super-linter

### Provide a basic test case to validate the tool's functionality.

```bash
I don't think is necessary is just to have the docker image downloaded
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

1 minute

**Comment by al-cheb** [comment]
Hey @felipem1210.
Due to the container image size we decided not to add it on images.
