### ISSUE TITLE
Android emulator dosent startup on non 27 SDK level

### ISSUE THREAD

**Issue by ShootingKing-AM** [actions/runner-images#6527]
### Description

Android emulator dosent startup on non-27 emulator image level

Used the snippet here - https://github.com/actions/runner-images/issues/6152#issuecomment-1243718140

Test Run - https://github.com/ShootingKing-AM/aw-android/actions/runs/3416481978

Full Test Code - https://github.com/ShootingKing-AM/aw-android/actions/runs/3416481978/workflow

Can github actions be used for android Instrumentation (e2e) Tests/Screenshot Tests ?, wish to have atleast emulator-24, 31(play store min), 33/32(current latest) level tests in CI. Is there a list of working (android) emulator images somewhere ?

Thankyou.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Test Run - https://github.com/ShootingKing-AM/aw-android/actions/runs/3416481978

Full Test Code - https://github.com/ShootingKing-AM/aw-android/actions/runs/3416481978/workflow

### Is it regression?

idk

### Expected behavior

Succesfully startup the emulators atleast.

### Actual behavior

Indefinite wait...

### Repro steps

Use the Full test code above or use the snippet linked above with the emulator versions aforementioned

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/runner-images/issues/6369
