### ISSUE TITLE
Update Visual Studio 2022 to 17.4

### ISSUE THREAD

**Issue by azchohfi** [actions/runner-images#6531]
### Tool name

Visual Studio 2022

### Tool license

https://visualstudio.microsoft.com/license-terms/vs2022-ga-proenterprise/

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.4

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by ldsenow** [comment]
really look forward to it! What is the ETA BTW?

**Comment by mikhailkoliada** [comment]
@ldsenow ending of the next week

**Comment by ssa3512** [comment]
This appears to have started rolling out and is breaking our builds as the .NET 6 SDK has been removed from the image. .NET 6 is LTS - aren't the last two LTS and latest major supposed to be supported?

**Comment by cybernescens** [comment]
We have also got failed builds popping up now; tracking it down it's because it can't find Microsoft.Build.Framework 15.x versions... I've been trying to figure out why our builds are failing and I'm wondering if this is why.

**Comment by wasabii** [comment]
Yeah. Same as others. Bunch of other stuff got removed/etc. Ended up adding a line to install it by hand.

**Comment by MaceWindu** [comment]
@mikhailkoliada was it reverted? I was able to get updated runner images on Wed and Thu, but for last two days azure gives me only older versions.

**Comment by DavoudEshtehari** [comment]
> @ldsenow ending of the next week

I don't see a new version for Win2022 image. I hope it wasn't a serious issue. Can you provide the new ETA, please?

**Comment by Sergio0694** [comment]
Yup, just tried again and I'm still seeing VS 17.3.2. Plus this week is thanksgiving, so I guess maybe end of next one? 😅

**Comment by JasonWei512** [comment]
Is it GA? My .NET 7 now builds on GitHub Action.

**Comment by Sergio0694** [comment]
Just tried again and I'm also seeing VS 17.4 and the .NET 7 SDK in all my Ci runs! 🎉

**Comment by mikhailkoliada** [comment]
Should be deployed.
