### ISSUE TITLE
Add Windows ARM64 support

### ISSUE THREAD

**Issue by taozuhong** [actions/runner-images#6532]
### Tool name

Windows-ARM64

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/runner-images/issues/6532

**Comment by Colengms** [comment]
@al-cheb Did you intend to duplicate this issue to itself?

**Comment by taozuhong** [comment]
> Duplicate #6532

Not yet.
