### ISSUE TITLE
Update/Add .Net 7 SDK (Released today)

### ISSUE THREAD

**Issue by ilya-scale** [actions/runner-images#6539]
### Tool name

.Net SDK

### Tool license

None

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7

### Brief description of tool

.Net 7 SDK just came out and it would be nice to have it by default in the runner images and not to pull it

### URL for tool's homepage

https://devblogs.microsoft.com/dotnet/announcing-dotnet-7/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

**Comment by mattjohnsonpint** [comment]
Per the [Software and Image Support Policy](https://github.com/actions/runner-images/blob/main/README.md#software-and-image-support):

| Tool name | Installation strategy |
|-----------|-----------------------|
| .NET Core | 2 latest LTS versions and 1 latest version. For each feature version only latest patch is installed |

Presently, at least according to the image ReadMe files, we have:

| Image        | .NET SDK Versions Installed |
|--------------|-----------------------------|
| ubuntu-22.04 | 6.0.402 |
| ubuntu-20.04 | 3.1.120 3.1.202 3.1.302 3.1.424 5.0.104 5.0.214 5.0.303 5.0.408 6.0.402 |
| macos-12     | 3.1.101 3.1.201 3.1.302 3.1.424 5.0.102 5.0.202 5.0.302 5.0.408 6.0.402 |
| macos-11     | 3.1.101 3.1.201 3.1.302 3.1.424 5.0.102 5.0.202 5.0.302 5.0.408 6.0.402 |
| windows-2022 | 3.1.120 3.1.202 3.1.302 3.1.424 5.0.104 5.0.214 5.0.303 5.0.408 6.0.402 |
| windows-2019 | 3.1.120 3.1.202 3.1.302 3.1.424 5.0.104 5.0.214 5.0.303 5.0.408 5.0.413 |

Thus none of the images are following the stated policy.

What I would expect is that all non-deprecated images would have previously had exactly versions `3.1.424 6.0.402` and would be in process of updating to exactly versions `3.1.425 6.0.403 7.0.100`.

This appears to be an ongoing problem.  Can we please do something to resolve the underlying process?

Thanks.

**Comment by mikhailkoliada** [comment]
thanks, we will add 7 soon

**Comment by sommmen** [comment]
> thanks, we will add 7 soon

Can you ballpark when this will happen? next week, next month?

**Comment by mikhailkoliada** [comment]
@sommmen next week

**Comment by mattjohnsonpint** [comment]
Just to mention for those that need .NET 7 and can't wait, you can still install it manually via:

```yaml
- name: Install .NET 7 SDK
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 7.x.x
```

Having it pre-installed is still important, as it speeds up build times and reduces network traffic.

**Comment by msavara** [comment]
I don't know what i'm doing wrong but it doesn't work for me. 

![image](https://user-images.githubusercontent.com/34938369/202916496-4386924f-2aab-47ff-8b21-8e976cd741dc.png)
And result

![image](https://user-images.githubusercontent.com/34938369/202916510-596ff7cb-a4f2-4331-a3b3-b19d28778c5b.png)

**Comment by mattjohnsonpint** [comment]
@msavara - Add spaces to indent `dotnet-version`

YAML is whitespace sensitive.

**Comment by MertUssakliMSFT** [comment]
Is .NET 7 still not included? https://github.com/actions/runner-images/blob/main/images/win/toolsets/toolset-2022.json

The `Install .NET 7 SDK` task works, but we now don't have the updated `wasm-tools`, which we have trouble installing as part of the pipeline.

**Comment by ShreyasJejurkar** [comment]
When this is going to happen!? Any ETA!?

**Comment by mikhailkoliada** [comment]
Deployed
