### ISSUE TITLE
Macos runner intermittent performance issues

### ISSUE THREAD

**Issue by sidekick-eimantas** [actions/runner-images#6547]
### Description

Hi

Either the network or disk is shot on macos runners, intermittently. See screenshots.

Control (ubuntu-22.04):
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/111279287/201122171-be65f456-7893-42f1-aa30-3782a42399ea.png">
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/111279287/201122221-83b66792-73d4-49fc-8754-7993deab5e80.png">

Macos 12:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/111279287/201122291-de06c68b-2e1f-46af-a68b-4cb5c68e8c8f.png">
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/111279287/201122365-956f9663-096a-4c8b-bc3e-b821e70597c2.png">

Macos 11:
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/111279287/201122442-5f84a4bd-8edb-44da-8966-0b373d387e80.png">

Any help would be highly appreciated.
Thank you

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221027.1

### Is it regression?

Don't know

### Expected behavior

N/A

### Actual behavior

N/A

### Repro steps

N/A

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/runner-images/issues/6547
