### ISSUE TITLE
Docker build failed with exit code 243

### ISSUE THREAD

**Issue by patrickcavli** [actions/runner-images#6558]
### Description

Tried building an Angular App with v13.0.0 but exited while installing npm and related dependencies. Tried clearing the cache, rewriting the workflow with uninstalling the npm version., but still the error persists.

**Please check the below log**

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/runner/.npm/_cacache/content-v2/sha512/33/ac
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:116 "/home/runner/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-11-12T14_52_36_558Z-debug-0.log
Error: Process completed with exit code 
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

The repo and organization are private.

### Is it regression?

No, we can't 

### Expected behavior

Expected to run the build successfully. Previous build log's have been automatically deleted by github org.

### Actual behavior

Build failed, while installing npm and building angular.

### Repro steps

Please try running the specific action for a sample angular repo.
```
 sudo npm cache clean --force 
 sudo npm install -g npm
 sudo npm install -g @angular/cli
 npm install --legacy-peer-deps
 ng build --aot --output-hashing=all --configuration=development
 docker build -t ${{secrets.CONT_NAME}}:${{steps.Release.outputs.version}} .
```

**Comment by al-cheb** [comment]
Hey @patrickcavli.

You should remove sudo:
```
- run: |
           npm cache clean --force
           npm install -g npm
           npm install -g @angular/cli
           npm install --legacy-peer-deps
           #ng build --aot --output-hashing=all --configuration=development
```
![image](https://user-images.githubusercontent.com/47745270/201481800-624d65a6-66db-477a-8c2d-8ead4def8d35.png)
