### ISSUE TITLE
Startup script is not running when gcp instance comes up

### ISSUE THREAD

**Issue by devmittalciv16** [actions/runner-images#6565]
### Description

I'm creating a custom image using a base image of windows-2019. I'm using the `images/win/windows2019.json` script to run the installations on a GCP instance. Once the image is created and I create a vm with it, The startup script isn't running.
Although with the base image, it's working fine.
Through trial and error, I found out that After I remove Finalize-VM.ps1 step and following step
`        {
            "type": "powershell",
            "inline": [
                "if( Test-Path $Env:SystemRoot\\System32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\System32\\Sysprep\\unattend.xml -Force}",
                "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
                "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
            ]
        }` in the packer script json, the startup script is running, but it then runs into some issue related to HKLM keys.
I understand that this script is written for azure platform and not gcp. But can you please help me understanding what changes do I need to make it work on gcp?

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Build is passing.

### Is it regression?

Not sure as your script is provided for azure platform.

### Expected behavior

The startup script should run.

### Actual behavior

The startup script is not running. Although In the instance created I can see it in custom-metadata section but it's not running.
Here is a screenshot of gcp logs.
![Uploading Screenshot 2022-11-14 at 3.25.26 PM.png…]()

### Repro steps

Use Google cloud to build an image using windows-2019 base image.
Create an instance with startup script.
The startup script won't run automatically.

**Comment by mikhailkoliada** [comment]
We support only azure as a primary building platform, other cloud providers are out of our scope.
