### ISSUE TITLE
Ubuntu 22.04 image breaking existing workflow 

### ISSUE THREAD

**Issue by znorcross211** [actions/runner-images#6569]
### Description

Upon running 
```
  docker run \
    --volumes-from=$HOST_CONTAINER_ID \
    --workdir $GITHUB_WORKSPACE \
    aquasec/trivy:0.22.0 --light --exit-code 0 --severity CRITICAL,HIGH --no-progress $FULL_IMAGE_NAME
```
with ubuntu `Image: ubuntu-22.04`

we are getting 
```
  BusyBox v1.32.1 () multi-call binary.
  
  Usage: basename FILE [SUFFIX]
  
  Strip directory path and .SUFFIX from FILE
```

If we roll back the ubuntu version to `Ubuntu 20.04` the action runs with no issue. 
Hoping to find the root cause of this, if it's an ubuntu issue or the `trivy` package.

Here's a before and after of anchoring our ubuntu version to 20.04 instead of ubuntu-latest

Before:
https://github.com/WW-Digital/cmx-search-metadata-service/actions/runs/3462362051/jobs/5785677832
After:
https://github.com/WW-Digital/cmx-search-metadata-service/actions/runs/3462953802/jobs/5782527104

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20221027.1

### Is it regression?

Ubuntu 20.04

### Expected behavior

Expected the action step to pass on the new ubuntu image 

### Actual behavior

Build action fails when running command 

### Repro steps

1. Attempt to run `aquasec/trivy:0.22.0 --light --exit-code 0 --severity CRITICAL,HIGH --no-progress $FULL_IMAGE_NAME`
on an image

**Comment by erik-bershel** [comment]
Hello @znorcross211,
The issue does not recur with the specified steps. Please provide more details or I will be forced to close the issue.
Logs with simple repro: [logs_45.zip](https://github.com/actions/runner-images/files/10006522/logs_45.zip)

**Comment by znorcross211** [comment]
@erik-bershel  seems like I was incorrect. It was due to `HOST_CONTAINER_ID=$(basename $(cat /proc/self/cgroup | grep name))` will need to update how we are doing this thanks for taking a look

**Comment by erik-bershel** [comment]
@znorcross211 so I'll close this issue. Feel free to contact us if you have another concerns.
