### ISSUE TITLE
Running UI Tests Involving the Health App

### ISSUE THREAD

**Issue by PSchmiedmayer** [actions/runner-images#6571]
### Description

The Health App on the iOS simulator instance running in a GitHub Action Runner environment does not display any content in the "Browse" section, making it impossible to test adding external HealthKit data such as EEG data in a UI test.

<p float="left">
  <img src="https://user-images.githubusercontent.com/28656495/201814712-8a0d4023-bb62-4919-9ae1-cc09d530fd94.jpg" width="320" />
</p>

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20221027.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20221027.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20221027.1

### Is it regression?

No

### Expected behavior

You can reproduce the expected behavior on our local macOS-based machine:
1. Download and install [Xcode 14.1](https://developer.apple.com/xcode/resources/)
2. [Reset the Simulator to get a completely clean instance](https://help.apple.com/simulator/mac/11.0/index.html?localePath=en.lproj#/devb4e6888f0)
3. [Run the UI Tests](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/05-running_tests.html) in this Repo by opening `TestApp.xcodeproj`.
4. The unit tests open the Health App and add Health Data using UI tests. You can observe the behavior in the iOS Simulator and see the Results in the Health App

### Actual behavior

The actual behavior can be observed in the https://github.com/CardinalKit/HealthKitTest/ repo.
- The GitHub Action Runners run the same UI tests using the GitHub Action found in `.github/workflows`: `build_and_test.yml`.
- The tests fail as the HealthKit's "Browse" tab does not include any content, e.g.,: https://github.com/CardinalKit/HealthKitTest/actions/runs/3466876834.
- The GitHub Action demonstrates this behavior as the UI tests create a screenshot on save and saves it in a `.xcresult` package.
- You can download the results bundle as an artifact created by the UI test and observe its behavior in Xcode by opening the `TestApp.xcresult`. 
- The screenshot at the bottom of the README from the GitHub Action run in the https://github.com/CardinalKit/HealthKitTest/ repo demonstrates the behavior.

### Repro steps

You can find a repository to reproduce the behavior including steps to follow at https://github.com/CardinalKit/HealthKitTest/.

**Comment by erik-bershel** [comment]
Hey @PSchmiedmayer! We'll take a look.

**Comment by PSchmiedmayer** [comment]
@erik-bershel Thanks a lot! Let me know if you need any help or additional context! 👍

**Comment by igorboskovic3** [comment]
Hi @PSchmiedmayer, does view uses UIWebview or WKWebView or other View?

**Comment by PSchmiedmayer** [comment]
Thanks for taking a look at the issue @erik-bershel, @mikhailkoliada, and @igorboskovic3!

@igorboskovic3: I would not suspect that the Health App uses a UIWebview or WKWebView to display the "Browse" section of the app. But as the Health App is a core system app developed by Apple I don't have any insights there and Apple engineers might be in a better situation to answer that question.
I am not sure what you mean with "other View"?

**Comment by igorboskovic3** [comment]
@PSchmiedmayer I thought generally on anything else that im not aware of. We will try to reproduce your issue, thank you

**Comment by dsame** [comment]
@PSchmiedmayer 

I do confirm the repro step "Run the UI Tests in this Repo by opening TestApp.xcodeproj" produces the successful test session. But if i try run the unit tests with the `xcodebuild` cli like the pipeline does it fails with the logs:

```
note: Building targets in dependency order
Testing started
Test suite 'UITests' started on 'Clone 1 of iPhone 14 Pro Max - UITests-Runner (67957)'
Test case 'UITests.testAddDataToHealthApp()' failed on 'Clone 1 of iPhone 14 Pro Max - UITests-Runner (67957)' (10.523 seconds)
2022-11-25 18:54:02.122 xcodebuild[67767:5825727] [MT] IDETestOperationsObserverDebug: 52.471 elapsed -- Testing started completed.
2022-11-25 18:54:02.122 xcodebuild[67767:5825727] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2022-11-25 18:54:02.122 xcodebuild[67767:5825727] [MT] IDETestOperationsObserverDebug: 52.471 sec, +52.471 sec -- end

Test session results, code coverage, and logs:
	/Users/dsa/AndroidStudioProjects/HealthKitTest/TestAppUITests.xcresult

Failing tests:
	UITests.testAddDataToHealthApp()
	UITests.testAddDataToHealthApp()

** TEST FAILED **
```

From this i suggest the problem is not the action environment but with the building command. Namely i assume the lack of the capabilities and entitlements necessary to access the HealthKit data.

Particularly i do not see any mentions of `com.apple.developer.healthkit` in the build log nor i do not see it mentioned in the source code. 

I am not sure about the setup for UI Tests of HealthKit and can only guess the XCode picks up the capabilities from some external provision files given with the auto-signing options but before we proceed with the investigation can you please confirm you can run the test with xcodebuild cli and provide us the repo and exact command options.

What about the empty browse screen i assume thee screen shout is done during the delay before the data appears - due to pure performance of macos build hosts it can be pretty big.

**Comment by igorboskovic3** [comment]
Hi @PSchmiedmayer, please pay attention the issue is inactive for several day days and it should be closed soon.

**Comment by PSchmiedmayer** [comment]
Hi @dsame & @igorboskovic3,

Thanks for further investigating the issue and taking a closer look!
Sorry for the late response, I have been out of the office during the Thanksgiving break and an now catching up with all the work that piled up.


Happy to help you with the issues you descried!

A bit more context: The test app that is included in the repo does not need to have access to the HealthKit data and does not need the HealthKit entitlement. The UI test that you can see at https://github.com/CardinalKit/HealthKitTest/blob/main/UITests/UITests.swift does never interact with the included iOS application. It immediately returns to the Home Screen (https://github.com/CardinalKit/HealthKitTest/blob/main/UITests/UITests.swift#L34) and then only interacts with the Health App. The project is a stripped-down version of the actual project that we have problems with (https://github.com/StanfordBDHG/CardinalKit) to make it easier for you to reproduce the error.

You can reproduce the builds and tests passing locally using the following xcodebuild CLI command, which is the same one that the GitHub Action at https://github.com/StanfordBDHG/.github/blob/main/.github/workflows/build-and-test-xcodebuild.yml uses with the inputs substituted with concrete values.
```
xcodebuild test \
  -project TestApp.xcodeproj \
  -scheme TestApp \
  -destination 'name=iPhone 14 Pro Max' \
  -enableCodeCoverage YES \
  -resultBundlePath TestApp.xcresult \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO
``` 
You might need to remove the `TestApp.xcresult` file before the test execution if you ran the tests before.

I have demonstrated that the overall xodebuild command works with an even more reduced UI test that only launches our application and the Health Application on the simulator without interacting with the empty browse tab in the Apple Health App (that is the problem described above). You can find the run on a separate branch here: https://github.com/CardinalKit/HealthKitTest/tree/onlyLaunchApp and the successful GitHub Action run here: https://github.com/CardinalKit/HealthKitTest/actions/runs/3595497238/jobs/6055057980.

You can also reproduce that the test is indeed failing in the Apple Health App and is not a problem in the xcodebuild command when you inspect the `.xcresult` bundle that is the output of the build command as described in the issue above. E.g., you can download the `.xcresult` bundle here: https://github.com/CardinalKit/HealthKitTest/actions/runs/3466994428, open the `.xcresult` bundle locally, and then inspect the screenshot that is automatically made at the end of the UI test showing the empty browse section. You can also do the same thing in the simplified run above that stops after navigating to the browse tab in the Apple Health App.

**Comment by igorboskovic3** [comment]
Hi @PSchmiedmayer after investigation and trying to found workaround, we conclude that this is performance issue, since this action/test performing well on self-hosted runner,
![image](https://user-images.githubusercontent.com/68074361/206672111-9dd92428-a61e-4d89-97ba-48531c01ace8.png)
 sorry for inconvenience.

**Comment by PSchmiedmayer** [comment]
@igorboskovic3 Thank you for taking a closer look at this! We will further investigate this on our side and see if we can work with even longer timeouts to address the performance issues on the GitHub Action runners 👍
