### ISSUE TITLE
Windows2019 pwsh 7.3 and Az.Network module not working

### ISSUE THREAD

**Issue by TheGitHubBro** [actions/runner-images#6574]
### Description

Looks like runners were updated yesterday and included an update to pwsh 7.3. Currently pwsh 7.3 and Az.Network don't play nicely together and it is causing issues on our pipelines. 

Is there any workaround or path forward? Can pwsh be rolled back to a previous version known to work with all the latest Az modules? 

Thanks in advance. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20221027.1

### Is it regression?

no

### Expected behavior

Expect pwsh and Az module to be compatible with each other. 

### Actual behavior

Az.Network and pwsh 7.3 have compatibility issues, error shown below: 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/43452124/202002084-af966b2e-b650-4c21-bf16-4fede5d61990.png">

### Repro steps

1. From a pipeline or any machine, use pwsh 7.3
2. Attempt to run any cmdlets in the Az.Network  module
3. Should see the error above

**Comment by mikhailkoliada** [comment]
Please use Azure Powershell task to specify the versions of Az Module and pwsh https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops
