### ISSUE TITLE
Problem with Install-Haskell.ps1

### ISSUE THREAD

**Issue by simbo1984** [actions/runner-images#6575]
### Description

When the script used to install Haskell runs, ghc 9.0.2 is installed correctly :

> ==> vhd: Provisioning with powershell script: C:\a\2\image-generation\images\win/scripts/Installers/Install-Haskell.ps1
    vhd: Installing ghc 9.0.2...
    vhd: Running [#1]: choco install ghc -y --version 9.0.2 -m
    vhd: Chocolatey v1.2.0
    vhd: Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
    vhd: Installing the following packages:
    vhd: ghc
    vhd: By installing, you accept licenses for the packages.
    vhd:
    vhd: cabal v3.8.1.0 [Approved]
    vhd: cabal package files install completed. Performing other installation steps.
    vhd: Downloading cabal 64 bit
    vhd:   from 'https://downloads.haskell.org/cabal/cabal-install-3.8.1.0/cabal-install-3.8.1.0-x86_64-windows.zip'
    vhd:
    vhd: Download of cabal-install-3.8.1.0-x86_64-windows.zip (14.71 MB) completed.
    vhd: Hashes match.
    vhd: Extracting C:\Users\packer\AppData\Local\Temp\chocolatey\cabal\3.8.1.0\cabal-install-3.8.1.0-x86_64-windows.zip to C:\ProgramData\chocolatey\lib\cabal.3.8.1.0\tools\cabal-3.8.1.0...
    vhd: C:\ProgramData\chocolatey\lib\cabal.3.8.1.0\tools\cabal-3.8.1.0
    vhd: Standalone msys2 detected. Using default paths.
    vhd: Could not read cabal configuration key 'install-method'.
    vhd: Updated cabal configuration.
    vhd: PATH environment variable does not have C:\Users\packer\AppData\Roaming\cabal\bin in it. Adding...
    vhd: Standalone msys2 detected. Using default paths.
    vhd: Adding C:\ProgramData\chocolatey\bin\mingw64-pkg.bat and pointing it to powershell command C:\ProgramData\chocolatey\lib\cabal.3.8.1.0\tools\mingw64-pkg.ps1
    vhd: Environment Vars (like PATH) have changed. Close/reopen your shell to
    vhd:  see the changes (or in powershell/cmd.exe just type `refreshenv`).
    vhd:  ShimGen has successfully created a shim for cabal.exe
    vhd:  The install of cabal was successful.
    vhd:   Software installed to 'C:\ProgramData\chocolatey\lib\cabal.3.8.1.0\tools\cabal-3.8.1.0'

When the script installs ghc 9.2.5:

>  vhd: Installing ghc 9.2.5...
    vhd: Running [#1]: choco install ghc -y --version 9.2.5 -m
    vhd: Chocolatey v1.2.0
    vhd: Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
    vhd: Installing the following packages:
    vhd: ghc
    vhd: By installing, you accept licenses for the packages.
    vhd:
    vhd: ghc v9.2.5 [Approved]
    vhd: ghc package files install completed. Performing other installation steps.
    vhd: ERROR: Cannot bind argument to parameter 'Path' because it is null.
    vhd: The install of ghc was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.2.5\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.
    vhd:
    vhd: Chocolatey installed 0/1 packages. 1 packages failed.
    vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vhd:
    vhd: Failures
    vhd:  - ghc (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.2.5\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.

Same when the script install ghc 9.4.3:

>  vhd: Installing ghc 9.4.3...
    vhd: Running [#1]: choco install ghc -y --version 9.4.3 -m
    vhd: Chocolatey v1.2.0
    vhd: Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
    vhd: Installing the following packages:
    vhd: ghc
    vhd: By installing, you accept licenses for the packages.
    vhd:
    vhd: ghc v9.4.3 - Possibly broken
    vhd: ghc package files install completed. Performing other installation steps.
    vhd: ERROR: Cannot bind argument to parameter 'Path' because it is null.
    vhd: The install of ghc was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.

Seems to be something related to the use of multiple versions by choco but I'm not sure...

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20221111.1

### Is it regression?

Yes, last one working for us was 20221002.2

### Expected behavior

When Haskell.Tests.ps1 is runned, no tests are failing.

### Actual behavior

When Haskell.Tests.ps1 is runned, 2 tests are failing because when Haskell is installed, only 1 version is succeeding (9.0.2). Other two versions (9.2.5 and 9.4.3) return this error :

**ERROR: Cannot bind argument to parameter 'Path' because it is null.**

_Also, 9.4.3 is possibly broken and is waiting for maintainer to take corrective action [(see here)](https://community.chocolatey.org/packages/ghc/9.4.3)_

### Repro steps

Build with Packer 1.8.3

**Comment by trhumphries** [comment]
We're seeing the same issue.

**Comment by rajeevoncloud9** [comment]
we are seeing the same issue

**Comment by erik-bershel** [comment]
Hey @simbo1984!
We'll take a look.

**Comment by trhumphries** [comment]
I think the best fix would be to change
$ODataQuery = '$filter=(Title eq ''ghc'') and (IsPrerelease eq false)&$orderby=Version desc'

to
$ODataQuery = '$filter=(Title eq ''ghc'') and (IsApproved eq true)&$orderby=Version desc'

**Comment by mikhailkoliada** [comment]
Must be fixed. Please sync your main.

**Comment by bjamone** [comment]
Hello,

We are still receiving this error, is there anything that we can do? Thanks

**Comment by erik-bershel** [comment]
@bjamone please update your fork and try again. If error will happen again send error-logs.

**Comment by bjamone** [comment]
Hello Erik, unfortunately we are using azure devops, I'm not sure what I should do. 

We have Invoke-RestMethod "https://api.github.com/repos/actions/virtual-environments/releases" and git clone https://github.com/actions/virtual-environments.git

**Comment by erik-bershel** [comment]
> Hello Erik, unfortunately we are using azure devops, I'm not sure what I should do.
> 
> We use git clone https://github.com/actions/virtual-environments.git

Please take a look at [guide](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md). You use old version as I can figure out from your link.

**Comment by bjamone** [comment]
Hello Erik,

Those old urls are pointing to the same pages, I changed them in our pipeline to be sure, will try again

**Comment by bjamone** [comment]
Hello Erik,

I used the new urls, made the changes, but unfortunately get the same error message:


    vhd: The install of ghc was NOT successful.

    vhd: Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.

    vhd:  See log for details.

    vhd:
    vhd: Chocolatey installed 0/1 packages. 1 packages failed.

    vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

    vhd:

    vhd: Failures

    vhd:  - ghc (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
