### ISSUE TITLE
Need Newer Windows Server 2022 Build - Windows App SDK 1.1/1.2 fails to install

### ISSUE THREAD

**Issue by michael-hawker** [actions/runner-images#6585]
### Description

The latest 1.1 & 1.2 builds of the Windows App SDK can't be installed on the current Windows Server 2022 VMs. This was reported here on their repo: https://github.com/microsoft/WindowsAppSDK/issues/2829

This is supposed resolved in the OS now in October, but the GitHub VMs haven't been updated. This blocks us from upgrading this package and running our tests, see: https://github.com/microsoft/WindowsAppSDK/issues/2706#issuecomment-1317818782

I imagine this also blocks MAUI folks as well as it uses the Windows App SDK?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current runner version: '2.299.1'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter

See: https://github.com/CommunityToolkit/Labs-Windows/actions/runs/3474985456/jobs/5808745741#step:18:376

### Is it regression?

Yes? (But related to other dependency)

### Expected behavior

Able to install Windows App SDK 1.2 on Windows Server 2022 VM and run Unit Tests.

### Actual behavior

Get deployment error when trying to run .NET unit tests.

### Repro steps

See: https://github.com/CommunityToolkit/Labs-Windows/actions/runs/3474985456/jobs/5808745741#step:18:376

**Comment by erik-bershel** [comment]
Hello @michael-hawker 
Which kind of update do you expecting? New OS's images deploy almost every week, so for regular Windows Updates it will not take a long time. If you are talking about changing the edition of the operating system, then I am afraid that we will not be able to provide this type of update. Please clarify this point.

**Comment by michael-hawker** [comment]
@erik-bershel I just need the latest version of the OS with the patch applied that fixes the linked Windows App SDK issue: https://github.com/microsoft/WindowsAppSDK/issues/2829 - FYI @sachintaMSFT

According to [this comment](https://github.com/microsoft/WindowsAppSDK/issues/2829#issuecomment-1292423709): 

> I was able to resolve the issue on Server 2022 by installing KB5018485

So that may be a solution as well?

**Comment by erik-bershel** [comment]
@michael-hawker it looks like that particular update will be distributed with next Windows images, yes. Deployment on this week was abandoned because of breaking changes connected with latest PowerShell release. But we will deploy fresh build on the very next week. Nothing special shouldn't be done from our side. So it is just "awaiting deployment" issue.
I'll keep an eye on it until next image will be developed to the prod.

**Comment by michael-hawker** [comment]
Thanks for the info @erik-bershel, is there a feed or something I can subscribe to in order to get the noticed of each VM release and patch notes?

Once deployed, I'll try re-running our pipeline and report back after the US holiday next week.

**Comment by erik-bershel** [comment]
@michael-hawker mmm, I'll ping you when it's ready. It is the simplest way.

**Comment by mikhailkoliada** [comment]
Updated

**Comment by michael-hawker** [comment]
Thanks @mikhailkoliada, I haven't got a clean build on my branch yet due to other reasons, but I'm pretty sure this is all working for us now as one of our jobs was clean.
