### ISSUE TITLE
KeyVault violates policy

### ISSUE THREAD

**Issue by Riisko** [actions/runner-images#6593]
### Description

Hi,
I can't create a Windows image because the temp KV Packer is trying to create violates policy. 
Here is the error:
`Build 'vhd' errored after 18 seconds 987 milliseconds: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplateDeployment" Message="The template deployment failed because of policy violation. Please see details for more information." Details=[{"additionalInfo":[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.KeyVault/vaults","operator":"Equals","path":"type","result":"True","targetValue":"Microsoft.KeyVault/vaults"},{"expression":"Microsoft.KeyVault/vaults/networkAcls.ipRules[*].value","expressionKind":"Field","operator":"In","path":"properties.networkAcls.ipRules[*].value","result":"False","targetValue":["xxx.xxx.xxx.xxx/32","yyy.yyy.yyy.yyy/32","zzz.zzz.zzz.zzz/32"]}]},"policyAssignmentDisplayName":"Organization Key Vault Portal - Firewall Setting Deny","policyAssignmentId":"/providers/Microsoft.Management/managementGroups/Org-landingzones/providers/Microsoft.Authorization/policyAssignments/<id>","policyAssignmentName":"<policyName>","policyAssignmentParameters":{"allowedAddressRanges":["xxx.xxx.xxx.xxx/32","yyy.yyy.yyy.yyy/32","zzz.zzz.zzz.zzz/32"]},"policyAssignmentScope":"/providers/Microsoft.Management/managementGroups/Org-landingzones","policyDefinitionDisplayName":"Organization Key Vault Portal - Firewall Setting Deny","policyDefinitionEffect":"Deny","policyDefinitionId":"/providers/Microsoft.Management/managementGroups/<id>/providers/Microsoft.Authorization/policyDefinitions/<id>","policyDefinitionName":"4<policyName>"},"type":"PolicyViolation"}],"code":"RequestDisallowedByPolicy","message":"Resource 'pkrkv0rdhd9bnqw' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Organization Key Vault Portal - Firewall Setting Deny\",\"id\":\"/providers/Microsoft.Management/managementGroups/Org-landingzones/providers/Microsoft.Authorization/policyAssignments/<policyName>\"},\"policyDefinition\":{\"name\":\"Organization Key Vault Portal - Firewall Setting Deny\",\"id\":\"/providers/Microsoft.Management/managementGroups/<id>/providers/Microsoft.Authorization/policyDefinitions/<id>\"}}]'.","target":"pkrkv0rdhd9bnqw"}]`

I would like to use my existing KV or let me configure the KV so it complies with the policy.

I have [tried the solution here](https://github.com/hashicorp/packer/pull/8704) but I get an error unknown configuration key "build_key_vault_name".

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest

### Is it regression?

no

### Expected behavior

Use existing KeyVault

### Actual behavior

Temporary KeyVault does not comply with Azure policy.

### Repro steps

Have a policy that:
1) Only allows KV to be accessible from a VNET
2) Only allows a set list of IPs

**Comment by erik-bershel** [comment]
Hey @Riisko.
Please provider more info about your issue. Repro steps and errors or logs.
And please confirm, if I understand correctly, that you want us to change the virtual machine generation process on our part so that users get more options for managing KV.

**Comment by mikhailkoliada** [comment]
Hi @Riisko. We do not use pre-created KV (and do not have plans to, at the moment), but you are free to modify repo-provided packer templates whatever you see fit and what azure-arm packer module supports.
