### ISSUE TITLE
Update [SwiftLint] to `0.50.0`

### ISSUE THREAD

**Issue by lukepistrol** [actions/runner-images#6599]
### Tool name

SwiftLint

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

0.50.0

### URL for tool's homepage

https://github.com/realm/SwiftLint

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Will be deployed this week

**Comment by mikhailkoliada** [comment]
Deployed
