### ISSUE TITLE
Error with identifierUris property

### ISSUE THREAD

**Issue by spowser** [actions/runner-images#6614]
### Description

Running into this error
```
GenerateResourcesAndImage : Values of identifierUris property must use a verified domain of the organization or its subdomain: 'http://011505AF-982E-482B-8547-1A80E56CFA0D'
At line:1 char:1
+ GenerateResourcesAndImage -SubscriptionId "123456 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,GenerateResourcesAndImage
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Navigate to the cloned repo
```
Import-Module ".\helpers\GenerateResourcesAndImage.ps1"

GenerateResourcesAndImage -SubscriptionId "<redacted>" -ResourceGroupName "Win2022AgentRG" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2022 -AzureLocation "South Central US"
```

### Is it regression?

No

### Expected behavior

Image creation runs without error

### Actual behavior

Error is thrown at the beginning of the script

### Repro steps
1. Install all the required tools
2. Run az login with subscription owner credentials
3. Check that Get-AzContext returns the correct default subscription
4. Run the commands in the instructions

**Comment by mikhailkoliada** [comment]
Looks like it is your tenant settings issues, but we will double check

**Comment by Alexey-Ayupov** [comment]
Hello @spowser, I cannot reproduce the issue, the authentication process was smooth as usual. Please bear in mind that I have tested the function with the next Powershell and module versions:
PSVersion                      7.2.7
Az.Accounts                  2.10.3 
Az.Resources                 6.4.1
Please kindly check your credentials one more time. If you have any questions, feel free to reach out.
