### ISSUE TITLE
Windows Driver Kit (WDK) fails installation, 10.0.22621.382

### ISSUE THREAD

**Issue by jH-** [actions/runner-images#6615]
### Description

Attempting a Windows2022 image creation currently fails due to WDK installation failure.
Refer to error code from the log below.

```
==> vhd: Provisioning with powershell script: C:\a\1\s\virtual-environments\images\win/scripts/Installers/Install-WDK.ps1
    vhd: Downloading wdksetup.exe...
    vhd: Downloading package from: https://go.microsoft.com/fwlink/?linkid=2196230 to path C:\Users\packer\AppData\Local\Temp\wdksetup.exe .
    vhd: Package downloaded successfully in 0.86 seconds
    vhd: Starting Install wdksetup.exe...
    vhd: Installation successful in 627.18 seconds
    vhd: Starting Install WDK.vsix...
    vhd: Unsuccessful exit code returned by the installation process: -532462766.
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20221027.1

### Is it regression?

Yes. (20221012.4)

### Expected behavior

Successfull installation of tools, continuation of image creation process.

### Actual behavior

WDK installation failure halts the script, and subsequently I'm forced to abort the image creation.

### Repro steps

Image creation via an Azure Devops pipeline.
```
GenerateResourcesAndImage -SubscriptionId ${{ variables.SubscriptionId }} `
              -ResourceGroupName $(ResourceGroupName) `
              -StorageAccountName $(StorageAccountName) `
              -ImageGenerationRepositoryRoot "$(Build.SourcesDirectory)/virtual-environments" `
              -ImageType Windows2022 `
              -AzureLocation "Norway East"
```

**Comment by mikhailkoliada** [comment]
it is general downloading issue, we have been observing it too (even though the file is downloaded it might be incomplete), please try again. If you have questions feel free to ask :)
