### ISSUE TITLE
ANT_HOME not set in windows images, but does get set in linux.

### ISSUE THREAD

**Issue by qwelyt** [actions/runner-images#6623]
### Description

https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers/Install-JavaTools.ps1
This script for windows does not set `ANT_HOME`, but a look at the Linux equivalent over at https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/java-tools.sh#L137 shows that the environment variable gets set (gradles variables get set at well on Linux but not Windows).

I would expect Windows to have the variables set as well. The lack of the variables set means that my current windows build for at project fails.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/qwelyt/opencv/actions/runs/3530511990/jobs/5922582505#step:5:699

### Is it regression?

Don't know.

### Expected behavior

That ANT_HOME gets set.

### Actual behavior

ANT_HOME is not set in windows runners, but are set in Linux runners.

### Repro steps

Use a windows runner and echo `ANT_HOME`. It does not exist.

**Comment by igorboskovic3** [comment]
Hi @qwelyt thank you, we will take a look.

**Comment by igorboskovic3** [comment]
Hi @qwelyt , it seems that we have ANT_HOME on both images.

![image](https://user-images.githubusercontent.com/68074361/203737318-475010cf-ccfd-430d-8196-4a08fc097eeb.png)

![image](https://user-images.githubusercontent.com/68074361/203739142-fda13731-abba-4f4e-9f7d-53ab6ee69c03.png)


![image](https://user-images.githubusercontent.com/68074361/203737424-7ff6d32c-0336-4514-827c-d16f19bff74b.png)

Feel free to reach us if you have more questions.
