### ISSUE TITLE
PublishCodeCoverage task fails on windows-2022 - 20221120.1

### ISSUE THREAD

**Issue by RicardoLans** [actions/runner-images#6628]
### Description

Our UnitTest PR build in Azure DevOps is failing since today 12.11, last succesfull was 10.21.

Steps to reproduce:
- task: DotNetCoreCLI@2 to (dotnet) build a .net6 unit test project
- task: DotNetCoreCLI@2 to (dotnet) test a .net6 unit test project -> with arguments /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/
- task: PublishCodeCoverageResults@1 to publish coverage results

Last task is currently (windows-2022 image 20221120.1) failing with message:
[error]No code coverage results were found to publish.

Last succesfull run (windows-2022 image 20221027.1) executed the following command succesfully:
"C:\Program Files\dotnet\dotnet.exe" D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.200.0\netcoreapp2.0\ReportGenerator.dll -reports:D:\a\1\s/**/coverage.cobertura.xml -targetdir:D:\a\_temp\cchtml -reporttypes:HtmlInline_AzurePipelines

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

failing -> windows-2022 - 20221120.1
succesfull -> windows-2022 - 20221027.1

### Is it regression?

Yes - windows-2022 image 20221027.1 was working perfectly

### Expected behavior

Expected behavior is pretty straightforward, task should not fail.

### Actual behavior

task is failing

### Repro steps

yml build:
- task: DotNetCoreCLI@2 to (dotnet) build a .net6 unit test project
- task: DotNetCoreCLI@2 to (dotnet) test a .net6 unit test project -> with arguments /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/
- task: PublishCodeCoverageResults@1 to publish coverage results

**Comment by erik-bershel** [comment]
Clone https://github.com/actions/runner-images/issues/6624

**Comment by RicardoLans** [comment]
Hi @erik-bershel 

That was fast :) 
I tried to find a similar issue but couldnt find the duplicate you linked.
Probably cause i filtered on label "OS: Windows"

Thanks for being aware of the clone that existed already.
