### ISSUE TITLE
Building docker image fails with "addgroup: gid '123' in use" error

### ISSUE THREAD

**Issue by morgoth** [actions/runner-images#6631]
### Description

When using the command:
`docker-compose build --build-arg uid=$(id -u) --build-arg gid=$(id -g)`
it fails with:
`addgroup: gid '123' in use`

Underneath it invokes:
```
ARG ruby_version

FROM ruby:$ruby_version-alpine3.16 AS builder

ARG uid
ARG gid

RUN apk add --no-cache --update \
      build-base \
      curl \
      git \
      less \
      libcurl \
      linux-headers \
      postgresql-client \
      postgresql-dev \
      tzdata \
      wget \
      zsh \
      nodejs \
      yarn \
      gcompat \
      npm

RUN ( ( getent passwd $uid && deluser $(getent passwd $uid | cut -d: -f1)) || true) && \
    ( ( getent group $gid && delgroup $(getent group $gid | cut -d: -f1)) || true) && \
    addgroup -g $gid -S app && \
    adduser -u $uid -S -G app -h /home/app -D app
```

It is passing fine on ubuntu 20.04.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20221119.2

### Is it regression?

ubuntu 20.04

### Expected behavior

docker image builds without error

### Actual behavior

Fails:
```
delgroup: 'ntp' still has 'ntp' as their primary group!
addgroup: gid '123' in use
The command '/bin/sh -c ( ( getent passwd $uid && deluser $(getent passwd $uid | cut -d: -f1)) || true) &&     ( ( getent group $gid && delgroup $(getent group $gid | cut -d: -f1)) || true) &&     addgroup -g $gid -S app &&     adduser -u $uid -S -G app -h /home/app -D app' returned a non-zero code: 1
```

### Repro steps

provided in description

**Comment by igorboskovic3** [comment]
Hi @morgoth , thanks, we will investigate.

**Comment by igorboskovic3** [comment]
Can you provide minimal repro steps?

**Comment by morgoth** [comment]
@igorboskovic3 It will be rather hard for me to create minimal script, as there are a lot of layers -> alpine, docker, docker-compose, etc.

**Comment by mikhailkoliada** [comment]
Hello @morgoth!

We do not really control what happens in docker containers, and your error is caused by the Dockerfile itself, not the runner image it is running on.

**Comment by sebastianpiskorski** [comment]
@mikhailkoliada But you can control the default group (and by so the `gid`) of default user on your `runs-on: ubuntu-latest` setup and why did you use `gid=123` for default group for default user instead of `1000`. Such config is very probable to be conflicting.

**Comment by 7PH** [comment]
Agree with @sebastianpiskorski.

I discovered this change because of a pipeline unexpectedly failed on one of my projects.

It's quite common to wanting to create a user within an image matching the host - meaning that lots of dockerfile setups will not work when using `ubuntu-latest` because the NTP user already exists on some images with uid `123` (namely `alpine`)

Is there any plans to reconsider this change?

**Comment by ptomulik** [comment]
My workaround (ubuntu/alpine) - does not delete existing users/groups within container, but rather reuses them:

```Dockerfile

# ...

ARG MY_USER='foo'
ARG MY_GROUP='foo'
ARG MY_UID=6789
ARG MY_GID=6789
ARG MY_HOME=/home/${MY_USER}

ENV MY_USER=$MY_USER \
    MY_GROUP=$MY_GROUP \
    MY_UID=$MY_UID \
    MY_GID=$MY_GID \
    MY_HOME=$MY_HOME \

RUN getent group "$MY_GID" > /dev/null && export MY_GROUP=$(getent group "$MY_GID" | cut -d: -f1); \
    getent passwd "$MY_UID" > /dev/null && export MY_USER=$(getent passwd "$MY_UID" | cut -d: -f1 ); \
    if [ -f /etc/alpine-release ]; then \
      ( getent group "$MY_GID" > /dev/null || addgroup -g "$MY_GID" "$MY_GROUP" ) && \
      ( getent passwd "$MY_UID" > /dev/null || adduser -h "$MY_HOME" -G "$MY_GROUP" -u "$MY_UID" -D "$MY_USER" ); \
    else \
      ( getent group "$MY_GID" > /dev/null || groupadd -g $MY_GID $MY_GROUP ) && \
      ( getent passwd "$MY_UID" > /dev/null || useradd -m -d $MY_HOME -g $MY_GID --uid $MY_UID $MY_USER ); \
    fi;

# ...
```
