### ISSUE TITLE
Ubuntu .NET 6.0 build fails with image 20221119.2 

### ISSUE THREAD

**Issue by IgorPietraszko** [actions/runner-images#6635]
### Description

We have an Azure build pipeline that has been working flawlessly for quite a while. About a week ago builds on some agents started failing and now they all are. Even builds on release branches that succeeded before are failing now. Failure error is:

`/usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1118,5): error NETSDK1151: The referenced project '../***.DbInstaller.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151 [/home/vsts/work/1/s/application/***.PublicPortal.csproj]`

Now this is not a recent change - we had this setup in place for quite a while. One suggestion is to add the following line in the project:

`<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>`

which fixes the builds but breaks our tests somewhere else.

Now I think this change might have something to do with a changed image and MSBuild version being used.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221119.2 

### Is it regression?

20221027.1

### Expected behavior

I would expect the build to succeed regardless of the condition highlighted with the new image.

### Actual behavior

Build is failing with error NETSDK1151

### Repro steps

Run our private repo build on any branch, including locked release branches using the latest image.

**Comment by igorboskovic3** [comment]
Hi @IgorPietraszko in your log you can see that is .NET 7 is used not . NET 6. 

Can you try to fix a version like [this](https://github.com/actions/runner-images/issues/6624#issuecomment-1327247540)

**Comment by IgorPietraszko** [comment]
Just noticed that.  Thanks.  Did implement global.json as suggested.  Build now succeeds but now our tests are failing, all having to do with PostgreSQL targeting unit tests.  Similar to when we implemented

`<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>`

Has anything changed around PostgreSQL in this image?

**Comment by mikhailkoliada** [comment]
@IgorPietraszko, the pgsql has been updated to 14.6as per https://github.com/actions/runner-images/commit/7d118628a44b22720df3c464500c43fc47cfda78. Please open a separate issue if you found anything relevant. Not to mess topics.

Thanks!

**Comment by IgorPietraszko** [comment]
I know this issue has been closed but I wanted to know how and when will I know to remove the work-around suggested by @igorboskovic3 above?
