### ISSUE TITLE
Configure Anti Virus step failing

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#6649]
### Description

Running the generateresourcesandimage.ps1 script to generate the image. the configure anti-virus script is failing with the following error :

![image](https://user-images.githubusercontent.com/90816346/204395173-3014dd31-0729-40eb-8414-ec93f5184a3c.png)

i retried and it still fails with the same error.

i think the task names should be passed into the get-scheduledtask command let, but the current one does not, not sure if this is is the cause of the problem.

Please guide on this.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows2022

### Is it regression?

no

### Expected behavior

expect it to move forward

### Actual behavior

failing it with the error described as above.

### Repro steps

run the generateresourcesandimage.ps1 script

**Comment by mikhailkoliada** [comment]
Hello!

We do not observe this problem in our nightly builds:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/88318005/204469367-fff20b79-baee-4743-9f23-a4c8943d0b35.png">

**Comment by vamshisiram** [comment]
@mikhailkoliada 

I am using centralus as the region. 

Do you recommend running these at the night rather than in the mrng?

**Comment by mikhailkoliada** [comment]
@vamshisiram I am nor sure it is region/az dependent. looks like some network failure and rerun must help you

**Comment by vamshisiram** [comment]
I already did rerun from the same attempt, it did not work. I mean from the same session in powershell.

I will try again in a new session.

Thanks @mikhailkoliada

**Comment by vamshisiram** [comment]
Did in a new session and fails with same error.

We have defender for cloud enabled in azure subscription, that might be playing a role here. @mikhailkoliada
