### ISSUE TITLE
Update MinGW

### ISSUE THREAD

**Issue by walbourn** [actions/runner-images#6653]
### Tool name

MinGW-64

### Tool license

GNU

### Add or update?

- [ ] Add
- [X] Update

### Desired version

12.2

### Brief description of tool

The existing toolset installed on the images is MinGW GNUC 11.2. 12.2 was released in August 2022 and includes a number of improvements.

### URL for tool's homepage

https://www.mingw-w64.org/downloads/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by ddobranic** [comment]
hello @walbourn! we will reconsider and get back to you, thank you.

**Comment by walbourn** [comment]
You could leave MinGW 11.2 on the windows-2019 images use 12.2 on the windows-2022 images to support both scenarios.

**Comment by Biswa96** [comment]
FYI, mingw and mingw-w64 are two different projects. Please try to mention the project name precisely always.

**Comment by mikhailkoliada** [comment]
just postponed it until the new year due to number of changes made, I'll take a look in few days.

**Comment by mikhailkoliada** [comment]
Hello! After careful version changes comparison we would not like to update mingw now yet, as too many actions and tasks rely on it, so it is good idea to postpone it for the time being.

**Comment by quyykk** [comment]
@mikhailkoliada Can MinGW be updated soon?

**Comment by Biswa96** [comment]
Alternatively, msys2 or cygwin can be used for latest mingw-w64 toolchain.
