### ISSUE TITLE
Add Tuist

### ISSUE THREAD

**Issue by ZoltanKapi** [actions/runner-images#6654]
### Tool name

Tuist

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest available

### Brief description of tool

Tuist is a command line tool that helps you generate, maintain and interact with Xcode projects.

It's open source and written in Swift.

### URL for tool's homepage

https://tuist.io

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
curl -Ls https://install.tuist.io | bash
```

**Comment by mikhailkoliada** [comment]
Hello @ZoltanKapi1! Due to installation time (only 3s) and maintenance concerns, we would like not to add the tool to the image.
