### ISSUE TITLE
Update IEDriverServer.exe

### ISSUE THREAD

**Issue by titusfortner** [actions/runner-images#6656]
### Tool name

IEDriverServer.exe

### Tool license

Apache License, Version 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

4.6.0+

### Brief description of tool

IEDriverServer.exe v4+ has been moved from google storage to Selenium's Github repo.

Now that Internet Explorer is no longer directly supported, the latest version of IE Driver is needed in order to use it with Microsoft Edge in IE Mode — https://titusfortner.com/2022/09/28/edge-ie-mode.html

I'm not sure how hard it is to to add the registry settings describe in that article (`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\`), but that would also be helpful.

You can essentially do the same thing for IE Driver that you're doing here - https://github.com/actions/runner-images/blob/1b3870ab40017b65d7e9708bbb6d28dd0871ec2d/images/win/scripts/Installers/Install-Selenium.ps1

Also, even for Windows 64 bit, the 32 bit IE Driver should be used - http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html

I do not know PS, but let me know if I can help.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Would take me a while to figure out PS

**Comment by ddobranic** [comment]
Hello @titusfortner! We will take a look, thank you.

**Comment by mikhailkoliada** [comment]
Updated
