### ISSUE TITLE
7z version unexpectedly changed?

### ISSUE THREAD

**Issue by swsnr** [actions/runner-images#6672]
### Description

From version 20221120.1 to 20221127.1 the version of 7z on Windows 2022 unexpectedly changed, from 22.01 to 17.04.

In a [build with windows-2022 version 20221120.1](https://github.com/swsnr/mdcat/actions/runs/3572460462/jobs/6005372595#step:10:19) from two days ago my 7z invocation succeeded, and used 7z version 22.01 according to its output:

```
+ 7z a mdcat-0.30.1-x86_64-pc-windows-msvc.zip ./target/x86_64-pc-windows-msvc/release/mdcat.exe ./README.md ./CHANGELOG.md ./LICENSE.txt 'D:\a\mdcat\mdcat\target\x86_64-pc-windows-msvc\release\build\mdcat-c02a67b7bf391c07\out/completions' ./mdcat.1.adoc

7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive:
1 folder, 13 files, 6632612 bytes (6478 KiB)

Creating archive: mdcat-0.30.1-x86_64-pc-windows-msvc.zip

Add new data to archive: 1 folder, 13 files, 6632612 bytes (6478 KiB)


Files read from disk: 13
Archive size: 2870024 bytes (2803 KiB)
Everything is Ok
```

In a [build with windows-2022 version 20221127.1](https://github.com/swsnr/mdcat/actions/runs/3592903041/jobs/6049807472#step:10:39) from today the identical and unchanged workflow suddenly failed in the same 7z invocation, and the output indicates the 7z is now version 17.04:

```
+ 7z a mdcat-0.30.2-x86_64-pc-windows-msvc.zip ./target/x86_64-pc-windows-msvc/release/mdcat.exe ./README.md ./CHANGELOG.md ./LICENSE.txt 'D:\a\mdcat\mdcat\target\x86_64-pc-windows-msvc\release\build\mdcat-9629c8ccb03e0e0d\out/completions' ./mdcat.1.adoc



7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
ERROR:
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (50654),ASM,AES-NI)
stat error for ./D:\a\mdcat\mdcat\target\x86_64-pc-windows-msvc\release\build\mdcat-9629c8ccb03e0e0d\out (No such file or directory)
```

I'm not sure whether this caused the build failure, but it's the first thing that I noticed, and in any case it doesn't seem to be correct wrt to the documented 7z version.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20221127.1

### Is it regression?

20221120.1 still worked, see https://github.com/swsnr/mdcat/actions/runs/3572460462/jobs/6005372595

### Expected behavior

I expected 7z version 22.01 as documented in README.

### Actual behavior

The build failed in a 7z step, and the output indicated that it's using 7z 17.04.

### Repro steps

I think a pipeline with 7z --version would be sufficient to demonstrate this issue.

**Comment by ddobranic** [comment]
Hello @swsnr, you can see [here](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#tools) that the version of 7z is 22.01

**Comment by swsnr** [comment]
@ddobranic Yes, I know, but that's not what I see in my pipeline.  7z reports its version with 17.04 in the failed build.

**Comment by swsnr** [comment]
@ddobranic Yes, I know, but that's not what I see in my pipeline.  7z reports its version with 17.04 in the failed build.

**Comment by swsnr** [comment]
Mmh, interesting. My log has a different version.

I'm running 7z from a bash script, though. Could this make a difference? Perhaps there are two 7z versions,and bash has a different `$PATH` 🤔

**Comment by ddobranic** [comment]
There is a difference in this step in [successful](https://github.com/swsnr/mdcat/actions/runs/3572460462/jobs/6005372595#step:5:1) and [failed](https://github.com/swsnr/mdcat/actions/runs/3592903041/jobs/6049807472#step:5:1) build examples.

**Comment by swsnr** [comment]
Oh dear, indeed setup-ruby messes up `$PATH`, see https://github.com/ruby/setup-ruby/issues/293

I'm very sorry for the noise; I'd never have thought that this innocent change might cause such troubles.

Thanks for helping me debugging this 🙏🏿 ❤️
