### ISSUE TITLE
Erlang and rebar3 is not included in 22.04 image

### ISSUE THREAD

**Issue by dgud** [actions/runner-images#6673]
### Description

Erlang and rebar was included in 20.04* and now with the switch of the default image to be 22.04 our actions are failing:
https://github.com/erlang/otp/actions/runs/3592910179/jobs/6049191930#step:4:14

From 20.04 readme:
* Erlang 25.0.4 (Eshell 13.0.4)
* Erlang rebar3 3.20.0

They are not included in 22.04

Can erlang and rebar be added to 22.04 image as well?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failure: https://github.com/erlang/otp/actions/runs/3592910179/jobs/6049191930#step:4:14

Image: https://github.com/actions/runner-images/blob/ubuntu22/20221127.1/images/linux/Ubuntu2204-Readme.md

### Is it regression?

Worked: https://github.com/erlang/otp/actions/runs/3584187011/jobs/6030538216

### Expected behavior

That erlang and rebar is included in the 22.04 image.

### Actual behavior

rebar3 is not found.

### Repro steps

Check that `rebar3 --version `works.

**Comment by ddobranic** [comment]
hello @dgud, we will take a look. thank you!

**Comment by mikhailkoliada** [comment]
@dgud It looks like erlang esl can't still be installed from the official repo fir Jammy. So, if your builds require you to have erlang, you will still have to downgrade to `ubuntu-22.04`

**Comment by dgud** [comment]
@mikhailkoliada Thanks for looking into this. 
Oh did you use the packages from erlang-solutions on 20.04?
We (erlang.org) are only providing the source tar-balls, the erlang-solutions packages are out of our control.

**Comment by mikhailkoliada** [comment]
@dgud yeah, we are using esl binaries and do not compile anything from source code at all :)
