### ISSUE TITLE
Add Ivy

### ISSUE THREAD

**Issue by JamieMagee** [actions/runner-images#6675]
### Tool name

Ivy

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.5.1

### Approximate size

3MB

### Brief description of tool

Apache Ivy is a transitive package manager. It is a sub-project of the Apache Ant project, with which Ivy works to resolve project dependencies.

### URL for tool's homepage

https://ant.apache.org/ivy/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
Hello! Given the size and installation time, we would not like to add the package to the images.

**Comment by JamieMagee** [comment]
@mikhailkoliada would you reconsider given Apache Ivy is the package manager for Apache Ant, and Apache Antis already installed in the images?

https://github.com/actions/runner-images/blob/8959c489f2a78eef664a8d15e6d3d6ac2bd061c8/images/linux/scripts/installers/java-tools.sh#L135-L137

https://github.com/actions/runner-images/blob/8959c489f2a78eef664a8d15e6d3d6ac2bd061c8/images/win/scripts/Installers/Install-JavaTools.ps1#L135
