### ISSUE TITLE
ubuntu-latest: jobs fail with error code 143

### ISSUE THREAD

**Issue by nicktrav** [actions/runner-images#6680]
### Description

We recently started seeing a high rate of failure in runs of a job that run `go race` on Linux runners (`ubuntu-latest`). We see the following in the logs, but lack the context to say why the process receives the SIGTERM:

```console
2022-12-01T17:39:21.3663768Z make: *** [Makefile:22: test] Terminated
2022-12-01T17:39:21.5137635Z ##[error]Process completed with exit code 143.
2022-12-01T17:39:21.5192954Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2022-12-01T17:39:21.7086950Z Cleaning up orphan processes
```

This seems to be less of an issue with the codebase itself (the same set of tests pass under stress on dedicated Linux workstations and cloud VMs), and more with the action runner VMs. That said, the failure rate seems to have markedly increased after a recent change to the codebase.

We're speculating that we are hitting some kind of resource limit due to the recent code change, though it's hard to say definitively.

More context in https://github.com/cockroachdb/pebble/issues/2159.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Image: ubuntu-22.04
  Version: 20221119.2
````

### Is it regression?

No - we've seen the same job passing with the same image.

### Expected behavior

The job should complete without error.

### Actual behavior

Job fails with exit code 143.

### Repro steps

Run the `linux-race` job in the Pebble repo (e.g. via PR, etc.). NOTE: we've since [temporarily disabled that job](https://github.com/cockroachdb/pebble/blob/a08baf44335e463d3bca831ab993f7716294a912/.github/workflows/ci.yaml#L48-L50) until we resolve this particular issue.

We used https://github.com/cockroachdb/pebble/pull/2158 to bisect down to the code change that increased the failure rate, though it's not clear _why_ it's failing with error code 143.

**Comment by mikhailkoliada** [comment]
@nicktrav Hello! My initial suspect is that you hit runner's limitation and we can not do anything here as you need to either reduce the resources usage or switch to [large runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners).

Could you post a link to the failed build please? (not mandatory the link is world-readable, as we do not need the content of the job, but the link itself)

**Comment by mikhailkoliada** [comment]
@nicktrav nevermind, I found what I was looking for.

**Comment by nicktrav** [comment]
> hit runner's limitation and we can not do anything here as you need to either reduce the resources usage or switch to large runners

Is there any way to tell if we're hitting the limitation? Are there graphs / metrics some place we can look?

**Comment by mikhailkoliada** [comment]
@nicktrav unfortunately we do not publish any data like this, but I found out that the runner has fallen due to high CPU usage rate, to my sadness we can not do anything on our side as I said above. The only alternatives are self-hosted runners or large runners.

If you have questions, feel free to reach us out again!

**Comment by svenjacobs** [comment]
We're facing the same problem since a few days. Builds are cancelled at various stages and runtimes. Did the behaviour change for Ubuntu 22.04 standard runners, which are now the [default](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/) since December 1, 2022? We never had these kind of problems with Ubuntu 20.04.

**Comment by mikhailkoliada** [comment]
@svenjacobs hi! No, runners are same

**Comment by JakubMosakowski** [comment]
The same problem started to occur in our repo. Is there any way to check if the runner hit its limitation?

Our builds ends with:
```
2022-12-06T15:40:04.3131651Z AAPT2 aapt2-7.3.0-8691043-linux Daemon #0: shutdown
2022-12-06T15:40:04.3150422Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2022-12-06T15:40:04.4473398Z ##[error]The operation was canceled.
```

at random stages of the build.

**Comment by nicktrav** [comment]
> unfortunately we do not publish any data like this, but I found out that the runner has fallen due to high CPU usage rate

Thanks for digging into it @mikhailkoliada.

If I might provide some feedback for the product, it would be nice to be able to tell _why_ a runner is failing in these situations. The `The runner has received a shutdown signal` message is very vague, and required us opening an issue here to confirm that we're seeing high CPU on the runner.

**Comment by thehowl** [comment]
@mikhailkoliada It's ~~very~~ a bit disappointing that the runner limitations are only mentioned here -- left for users to find only after extensive googling trying to find the root cause of a cryptic error message.

Could your team at the very least mention this fact on the official actions documentation? (Though it would obviously be better to have a proper error message, together with documentation on what these limits we're hitting are...)

**Comment by janosh** [comment]
Would be great to get a more informative error message than

> Error: The operation was canceled.

I had to rerun with debug logging enabled which produced the slightly more helpful

> Error: Process completed with exit code 143.

to find this thread. Please issue something like

1. Operation canceled due to excessive mem use: 8.5. GB out of 8GB (106%)

1. Operation canceled due to high CPU use: 115%

**Comment by montchr** [comment]
After searching for an explanation and troubleshooting the mysterious build cancellations for days, I finally saw the error code 413 message for the first time just now, leading me to this issue.

I really don't think this should have been closed without any evidence of an intention to make the underlying cause clearer.

**Comment by PGMacDesign2** [comment]
This is still an issue for us and we have no fix for this other than to schedule an elaborate retry loop to retry certain builds. 
Is this still being actively worked on? Or are there any workarounds / solutions that may solve this issue?

**Comment by joeflack4** [comment]
@mikhailkoliada @nicktrav How are you able to ascertain whether it is a CPU issue? I can't find the cause of my failure, and I think many others are having the same problem.

Do you or anyone else know where to find if/where GitHub has published CPU limitations?
It was very hard to find this article which shows [memory and disk limitations](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners). It mentions what kind of CPU is being used by the runner, but nothing about a limit.

**Comment by KarthikAyikkathil100** [comment]
Is there any update on this ?

**Comment by shojaeix** [comment]
This happened in my pipeline that was applying Terraform plan to AWS. The pipeline took 6 minutes and terminated with error 143. 

Then I restarted it, it took 12 minutes and finished successfully! very weird

**Comment by vitornesello** [comment]
I am also experiencing the same problem. A pipeline with the same code running with no issues yesterday started to fail today with signal 143.

**Comment by rogerfar** [comment]
This is happening more and more sporadically for our builds. For months they have been working great, and now it's almost a 50% shot to get the error.

**Comment by PGMacDesign2** [comment]
Just a heads up that we had success by updating the `runs-on` line within the yaml file to append `-large` to it so as to give it more space to run. Seems to be working most of the time for us. 

```
name: Your Workflow Name

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      some_id:
        description: 'some id'

jobs:
  run_your_action_here:
    runs-on: ubuntu-latest-large //THIS LINE HERE
    outputs:
  .
  .
  .
```

Along this path:

```
.github/workflows/your_workflow_name.yml
```

**Comment by mostafaznv** [comment]
I experienced the same issue today, and creating a swap file partition did the trick.

https://github.com/actions/runner-images/discussions/7188#discussioncomment-6750749

**Comment by danra** [comment]
In my case, this mysterious error was simply due to running out of memory on the machine/runner.
