### ISSUE TITLE
Unresolved external symbol in the C++ standard library

### ISSUE THREAD

**Issue by frankfliu** [actions/runner-images#6684]
### Description

Our build pipelines started failing yesterday for windows-latest VM images.

There is no changes related JNI build. And local build passed without issue. I tried build on previous passed commits also failed. The failed pipeline can be found: https://github.com/deepjavalibrary/djl/actions/runs/3599024682/jobs/6062298770

The issue looks similar to: #6091

I tried the workaround to remove windows components, but still failing.
I tried with Windows 2019, and it works fine.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/deepjavalibrary/djl/actions/runs/3599024682/jobs/6062298770

### Is it regression?

Latest success build: https://github.com/deepjavalibrary/djl/actions/runs/3580465043/jobs/6022615917

### Expected behavior

Build should pass

### Actual behavior

Build failed:

```
     Creating library D:/a/djl/djl/engines/pytorch/pytorch-native/build/Release/djl_torch.lib and object D:/a/djl/djl/engines/pytorch/pytorch-native/build/Release/djl_torch.exp
ai_djl_pytorch_jni_PyTorchLibrary_system.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
ai_djl_pytorch_jni_PyTorchLibrary_torch_random_sampling.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
ai_djl_pytorch_jni_PyTorchLibrary_system.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
ai_djl_pytorch_jni_PyTorchLibrary_nn_functional.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
ai_djl_pytorch_jni_PyTorchLibrary_torch_random_sampling.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
D:\a\djl\djl\engines\pytorch\pytorch-native\build\Release\djl_torch.dll : fatal error LNK1120: 2 unresolved externals [D:\a\djl\djl\engines\pytorch\pytorch-native\build\djl_torch.vcxproj]
```

### Repro steps

Build our pipeline

**Comment by erik-bershel** [comment]
Hello @frankfliu, looks like issue connected with last VS updates according to that stackoverflow [thread](https://stackoverflow.com/questions/74366357/updating-to-visual-studio-17-4-0-yields-linker-errors-related-to-tls). We'll take a look.

**Comment by mikhailkoliada** [comment]
As it is pytorch issue we can not do anything on our side here, we all have to wait for the fix. If you have concerns please feel free to reach us again!
