### ISSUE TITLE
LoadError: libffi.so.7: cannot open shared object file for Action on 22.04

### ISSUE THREAD

**Issue by daibhin** [actions/runner-images#6691]
### Description

The `ubuntu-latest` runner was recently upgraded to `22.04` from `20.04` which has caused my Rails tests to fail

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: ubuntu-22.04
Version: 20221127.1
```

### Is it regression?

Yes

### Expected behavior

Tests pass as normally as when `runs-on: ubuntu-20.04`

### Actual behavior

Fails with
```
LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/runner/work/unflow-server/unflow-server/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so
```

### Repro steps

1. Setup a Rails app that includes the ffi gem with version `1.15.5`
2. Run a GitHub action that runs a rake command

**Comment by erik-bershel** [comment]
@daibhin please provide minimal workflow with all the dependencies to reproduce the issue and/or link to affected run.

**Comment by erik-bershel** [comment]
Almost sure it will be connected to https://github.com/orgs/community/discussions/24949
And big thread about the same symptoms: https://github.com/ffi/ffi/issues/881
But we cannot be sure without additional info.

**Comment by erik-bershel** [comment]
Hi again @daibhin 
Please provide additional information or I will be forced to close the application.

**Comment by pglombardo** [comment]
I [just hit the same](https://github.com/pglombardo/PasswordPusher/actions/runs/3663621161/jobs/6193515626#step:9:76) but it's not the fault of runner-images.  The FFI issue (cached/broken c lib link) fixed it for me.  Thanks.

**Comment by Alexey-Ayupov** [comment]
Hello @daibhin, could you please try to use another version of Ruby as @pglombardo advises? We will close the issue for now. Feel free to reach out if you have any concerns.
