### ISSUE TITLE
Ubuntu-22.04 breaks our build.

### ISSUE THREAD

**Issue by gdborton** [actions/runner-images#6696]
### Description

We've got a playwright test config that starts our dev server on port 9999 with the command `pnpm dev &` then invokes playwright.

We're seeing in the latest ubuntu image that our dev server is unavailable. I don't have any additional info really, it's difficult to  say whether our server is running or if maybe the port isn't open?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Image: ubuntu-22.04
  Version: 20221127.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20221127.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221127.1
```

### Is it regression?

yes, 20.04 worked

### Expected behavior

See the description.

### Actual behavior

See the description.

### Repro steps

I didn't narrow this down to exact repro steps, but did describe what we're doing in the description.

I'm sort of assuming at the moment the issue is either w/ the `pnpm dev &` using `&` or port `9999` not being available. I don't see any relevant logs in our output though.

**Comment by mikhailkoliada** [comment]
Please provide minimal repro-steps

**Comment by mikhailkoliada** [comment]
@gdborton please feel free to reach us out once you have the steps we could help you with! For now I am going to close the ticket.
