### ISSUE TITLE
ubuntu-latest breaks the build

### ISSUE THREAD

**Issue by jerryphe88** [actions/runner-images#6699]
### Description

We use ubuntu-latest to run githib test. However the below error shown:

python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by python)
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.[35](https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590#step:5:36)' not found (required by /__t/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /__t/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /__t/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /__t/Python/3.9.15/x64/lib/libpython3.9.so.1.0)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.299.[1](https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590#step:1:1)'
Operating System
  Ubuntu
  [2](https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590#step:1:2)2.0[4](https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590#step:1:4).1
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 2022112[7](https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590#step:1:8).1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20221127.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221127.1
Runner Image Provisioner
  2.0.[9](https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590#step:1:10)1.1

### Is it regression?

NO

### Expected behavior

githib action should succeed

### Actual behavior

githib action failed

### Repro steps

ubuntu-latest is linked to   Image: ubuntu-22.04. Version: 20221127.1 However this is a new version on Dec 04 available, but not used

https://github.com/darkbluefactore/factore-worker/actions/runs/3623304127/jobs/6110351590

**Comment by mikhailkoliada** [comment]
Hello! This is expected. ubnutu-22.04 is shipped with glibc-2.35. Your  binary is built with the older glibc symbols, so you either must downgrade your runner to 20.04 or rebuild the binary. Nothing we can help with.
