### ISSUE TITLE
NX Build System

### ISSUE THREAD

**Issue by tomjrob** [actions/runner-images#6708]
### Tool name

NX

### Tool license

MIT Licence

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whichever is the latest

### Brief description of tool

NX is a tool used for monorepo build system management. In particular for resolving cross project dependencies and build order.

It comes with a flexible way of exposing common project commands (e.g. build, test, deploy, lint) so that for instance you can run `nx affected --target:deploy`, and it will compute the affected projects based on file changes, then calculate the downstream steps needed to run a full deployment of the affected projects and in addition any of their dependents that rely on them. Critically each project maintains their own.

See here for more information:
[NX Homepage](https://nx.dev/)
[Introduction to NX](https://nx.dev/getting-started/intro)

### URL for tool's homepage

https://nx.dev/

### Provide a basic test case to validate the tool's functionality.

```bash
if nx --version returns version number result then passed
else failed
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes. The tool can be installed globally using npm:
npm i nx@latest --global
```

### Tool installation time in runtime

4 seconds

### Are you willing to submit a PR?

yes

**Comment by erik-bershel** [comment]
@tomjrob 
Due to installation time (only 4s) and maintenance concerns, we would like not to add the tool to the image.
