### ISSUE TITLE
FYI, the error message showing up in AzDO builds is misspelled (unless the underlying name *is* changing to ubntu):

### ISSUE THREAD

**Issue by kiajfaty** [actions/runner-images#6717]
FYI, the error message showing up in AzDO builds is misspelled (unless the underlying name *is* changing to ubntu):
```
##[warning]ubuntu-latest pipelines will use ubntu-22.04 soon. For more details, see https://github.com/actions/runner-images/issues/6399
```

_Originally posted by @mechie in https://github.com/actions/runner-images/issues/6399#issuecomment-1341328226_

**Comment by mikhailkoliada** [comment]
oh, typo! fixed.
