### ISSUE TITLE
Unable to build Ubuntu 20.04, Error while loading libgtk.

### ISSUE THREAD

**Issue by SPALLADI** [actions/runner-images#6723]
### Description

Hi,

I am using packer to build the image for Ubuntu 20.04. The packer build is failing as below.
 
  chromium-browser: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
    azure-arm:    at "chromium-browser --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Browsers.Tests.ps1:39

    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Browsers.Tests.ps1:39

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 20.04

### Is it regression?

no

### Expected behavior

Build should be successful.

### Actual behavior

I am using packer to build the image for Ubuntu 20.04. The packer build is failing as below.
 
  chromium-browser: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
    azure-arm:    at "chromium-browser --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Browsers.Tests.ps1:39

    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/Browsers.Tests.ps1:39

### Repro steps

we are using Azure devops pipeline to build the packer
      - task: PackerBuild@1
        inputs:
          templateType: 'custom'
          customTemplateLocation: $(TemplatePath)
          customTemplateParameters: '{"client_id":"$(client_id)","client_secret":"$(client_secret)","tenant_id":"$(tenant_id)","subscription_id":"$(subscription_id)","resource_group":"$(resource_group)","build_resource_group_name":"$(build_resource_group_name)","image_name":"$(image_name)","image_version":"$(image_version)","gallery_name":"$(gallery_name)","install_password":"$(InstallPassword)","github_feed_token":"$(github_feed_token)"}'
          connectedServiceName: "SC"

**Comment by erik-bershel** [comment]
That one looks strange. The error indicates that the installation process used a version of the library for a different architecture (amd64 <-> i386). It happens when you installing 32-bit application on 64-bit or ARM system.

**Comment by spowser** [comment]
I can also confirm this issue.  I tried with ubuntu22/20221204.2 and ubuntu22/20221119.2

**Comment by naikrovek** [comment]
I'm seeing the exact same thing, but it is complaining about the lack of `libpng12.so.0` which is very old.  I think something may be broken in Chromium.

**Comment by randomcascade** [comment]
Yeah, have the same issue with libpng12.so.0. I've also noticed that the filesystem seems to think that the revision of Chromium installed via the google-chrome.sh script is from 2011. I suspect the script is downloading the wrong revision somehow, but I'm not familiar with how it *should* work.

**Comment by randomcascade** [comment]
[google-chrome.sh](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/google-chrome.sh) has some kind of bug we're winding up with an old revision of Chromium namely 90850. The question is why and what would the correct way to parse it be? When you print out the versions variable the revision numbers grow then suddenly drop to 90850 which is the one that gets installed.

**Comment by mikhailkoliada** [comment]
Have not taken a look yet, but looks like chromium revision returns too old chrome version https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/google-chrome.sh#L20

**Comment by szechyjs** [comment]
Seeing the same thing with 22.04
```
    amazon-ebs.build_ami: Running tests from '/imagegeneration/tests/Browsers.Tests.ps1'
    amazon-ebs.build_ami: Describing Chrome
    amazon-ebs.build_ami:   [+] Chrome 198ms (103ms|95ms)
    amazon-ebs.build_ami:   [+] Chrome Driver 15ms (13ms|1ms)
    amazon-ebs.build_ami:   [+] Chrome and Chrome Driver major versions are the same 76ms (75ms|2ms)
    amazon-ebs.build_ami: Tests completed in 689ms
    amazon-ebs.build_ami: Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 5
    amazon-ebs.build_ami: Pester v5.3.3
    amazon-ebs.build_ami:
    amazon-ebs.build_ami: Starting discovery in 1 files.
    amazon-ebs.build_ami: Discovery found 8 tests in 180ms.
    amazon-ebs.build_ami: Filter 'FullName' set to ('Chromium').
    amazon-ebs.build_ami: Filters selected 1 tests to run.
    amazon-ebs.build_ami: Running tests.
    amazon-ebs.build_ami:
    amazon-ebs.build_ami: Running tests from '/imagegeneration/tests/Browsers.Tests.ps1'
    amazon-ebs.build_ami: Describing Chromium
    amazon-ebs.build_ami:   [-] Chromium 184ms (88ms|96ms)
    amazon-ebs.build_ami:    Command 'chromium-browser --version' has finished with exit code
    amazon-ebs.build_ami:        chromium-browser: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
    amazon-ebs.build_ami:    at "chromium-browser --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Browsers.Tests.ps1:39
    amazon-ebs.build_ami:    at <ScriptBlock>, /imagegeneration/tests/Browsers.Tests.ps1:39
    amazon-ebs.build_ami: Tests completed in 630ms
    amazon-ebs.build_ami: Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 7
```

**Comment by CoryManson** [comment]
It appears the current chrome version `108.0.5359.98` & previous version `108.0.5359.94` are both using the same problematic 4 digit chromium base position `1016` which is resulting in fetching the old chromium version `90850`

**Comment by mikhailkoliada** [comment]
should be fixed
