### ISSUE TITLE
Update/Add gfortran-12

### ISSUE THREAD

**Issue by schmitts** [actions/runner-images#6724]
### Tool name

gfortran-12

### Tool license

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

12

### Brief description of tool

Cf. https://github.com/actions/runner/issues/2305

@AlexanderRichert-NOAA writes:

> All but one of the preinstalled GNU C compiler packages in the ubuntu 22 image (as of 20221127.1) have corresponding gfortran packages; gcc version 12 does not. For consistency it would be useful to include it.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
@schmitts we'll add it soon.

**Comment by mikhailkoliada** [comment]
Will be deployed next week

**Comment by mikhailkoliada** [comment]
Deployed
