### ISSUE TITLE
Function GenerateResourcesAndImage fails at packer build due to temp vm password policy

### ISSUE THREAD

**Issue by LeventeNagy-CD** [actions/runner-images#6735]
### Description

during GenerateResourcesAndImage , once packer build starts, the porvisioning fails after connecting the new temp vm via WinRM.
Windows2022 images seem to come with password a policy "Password must meet complexity requirements" on "Enabled".
This means the password is checked not to contain the username. 
GenerateResourcesAndImage.ps1 file line 129 sets the  $InstallPassword starting with the username followed by a guid generated.

      **$InstallPassword = $env:UserName + [System.GUID]::NewGuid().ToString().ToUpper()**

      **==> vhd: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements.**

This has caused our run to fail when the install user is getting created, see below.

```
==> vhd: Waiting for WinRM to become available...
    vhd: WinRM connected.
==> vhd: Connected to WinRM!
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\INSTAL~1\AppData\Local\Temp\2\powershell-provisioner2536938826
    vhd:
    vhd:
    vhd:     Directory: C:\
    vhd:
    vhd:
    vhd: Mode                 LastWriteTime         Length Name
    vhd: ----                 -------------         ------ ----
    vhd: d-----         12/8/2022   3:44 PM                image
==> vhd: Uploading C:\runner-images\images\win/scripts/ImageHelpers => C:\Program Files\WindowsPowerShell\Modules\
==> vhd: Uploading C:\runner-images\images\win/scripts/SoftwareReport => C:\image
==> vhd: Uploading C:\runner-images\images\win/post-generation => C:/
==> vhd: Uploading C:\runner-images\images\win/scripts/Tests => C:\image
==> vhd: Uploading C:\runner-images\images\win/toolsets/toolset-2022.json => C:\image\toolset.json
==> vhd: Provisioning with windows-shell...
==> vhd: Provisioning with shell script: C:\Users\INSTAL~1\AppData\Local\Temp\2\windows-shell-provisioner3318342576
    vhd:
    vhd: C:\Users\packer>net user installer <sensitive> /add /passwordchg:no /passwordreq:yes /active:yes /Y
    vhd:
    vhd: C:\Users\packer>net localgroup Administrators installer /add
    vhd:
    vhd: C:\Users\packer>winrm set winrm/config/service/auth @{Basic="true"}
    vhd: Auth
    vhd:     Basic = true
    vhd:     Kerberos = true
    vhd:     Negotiate = true
    vhd:     Certificate = false
    vhd:     CredSSP = false
    vhd:     CbtHardeningLevel = Relaxed
    vhd:
**==> vhd: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements.**
==> vhd:
==> vhd: More help is available by typing NET HELPMSG 2245.
==> vhd:
==> vhd: There is no such global user or group: installer.
==> vhd:
==> vhd: More help is available by typing NET HELPMSG 3783.
==> vhd:
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\INSTAL~1\AppData\Local\Temp\2\powershell-provisioner1168962454
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

# Microsoft Windows Server 2022 Datacenter
- OS Version: 10.0.20348 Build 1249
- Image Version: 20221127.1

### Is it regression?

no

### Expected behavior

The password should be a random strong password not containing the username.

### Actual behavior

installer user fails to be created due not meeting windows server 2022 default password policy.
The same would happen in almost any non-test environment where new VMs provisioned will have this policy enabled. 

### Repro steps

spin up an azure vm
follow instructions https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md. 

Command used:
C:\runner-images> GenerateResourcesAndImage -SubscriptionId "sub_id_removed" -ResourceGroupName "rg-pv-temp006" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2022 -AzureLocation "UK South"

**Comment by Alexey-Ayupov** [comment]
Hello, we will check it out and get back to you.

**Comment by Alexey-Ayupov** [comment]
We have checked and could not reproduce the issue. Let me explain how "$InstallPassword" variable works. 
The "$env:UserName" is basically the user in your build VM (AzureVM or localhost), it is not related to the user "installer" used in the Packer. 
However, if you also use the user name "installer" on your build VM, we consider changing it. 
Feel free to reach us again if you have any concerns.
