### ISSUE TITLE
ubuntu:20.04 v2.299.1 has not any dev tools installed

### ISSUE THREAD

**Issue by ezYakaEagle442** [actions/runner-images#6737]
### Description

I created a Self-Hosted Runner based on ubuntu:20.04 v2.299.1 Runner image.
The Runner starts & runs fine but none of the [pre-installed softwares](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software) are installed on this image.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[https://github.com/ezYakaEagle442/install-kubectl-from-pod/blob/main/Dockerfile](https://github.com/ezYakaEagle442/install-kubectl-from-pod/blob/main/Dockerfile)

FROM ubuntu:20.04
ENV RUNNER_VERSION=2.299.1

### Is it regression?

I guess so

### Expected behavior

All [pre-installed softwares](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software) should be available on the self-hosted runner

### Actual behavior

The Runner starts & runs fine but the dev tools are not installed as expected.

Also Fine-grained personal access tokens does not work, only Classical PAT works

### Repro steps

Follow the steps on my [repo]([https://github.com/ezYakaEagle442/install-kubectl-from-pod).

Run locally the image and then connect to a terminal : 
```sh
docker run --env GHA_RUNNER_PAT=$GHA_RUNNER_PAT -e OWNER=$OWNER -e REPO=$REPO -e NAME=$NAME -it pinpindock/self-hosted-runnner:latest  --
az version
java --version
mvn --version
kubectl version
jq --version
helm version
git --version
```
none of the above CLI commands works except jq

**Comment by mikhailkoliada** [comment]
Hello, we do not provide docker environments, so your results are expected.

**Comment by ezYakaEagle442** [comment]
@mikhailkoliada thank you for your reply, may i ask you to share the scripts to install the tools to get the ones listed at [https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#installed-software](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#installed-software) ?

I see scripts at : 
- [https://github.com/actions/runner-images/tree/main/images/linux/scripts/installers](https://github.com/actions/runner-images/tree/main/images/linux/scripts/installers)
- [https://github.com/actions/runner-images/blob/main/images/linux/ubuntu2004.json](https://github.com/actions/runner-images/blob/main/images/linux/ubuntu2004.json)
- [https://github.com/actions/runner-images/blob/main/images/linux/toolsets/toolset-2004.json](https://github.com/actions/runner-images/blob/main/images/linux/toolsets/toolset-2004.json)

But where is the main to trigger all those scripts , is it : 

- [https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/image-generation.yml](https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/image-generation.yml) ?
