### ISSUE TITLE
Add `yj`, a universal TOML/YAML/JSON/HCL convertor in CLI with a self-contained Go-based executale

### ISSUE THREAD

**Issue by achimnol** [actions/runner-images#6750]
### Tool name

yj

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

5.1.0

### Approximate size

4.5 MB

### Brief description of tool

An excerpt from the project README:

> Convert between YAML, TOML, JSON, and HCL.
> Preserves map order.
> 
> Format versions:
> - YAML: v1.2 (gopkg.in/yaml.v3)
> - TOML: v1.0.0 (github.com/BurntSushi/toml)
> - JSON: RFC 7159 (encoding/json)
> - HCL: v1 (github.com/hashicorp/hcl)

TOML is becoming more widely used in the Python community, as Python 3.11 now includes the standard `tomllib` module.

However, when writing shell scripts based on TOML files, it is still required to rely on regular expressions and unreliable string matching.  There are a few attempts to write TOML versions of `jq` or `yq`, such as [`tombl`](https://github.com/snyball/tombl) but they are still in a very early stage of development to use in production CI pipelines.

It is too cumbersome to directly invoke Python from a shell script to run `tomllib` like:
```console
$ python3.11 -c 'import tomllib,re; print(m.group(1) if (m := re.search(r"^CPython==(.*)$", tomllib.load(open("pants.toml","rb"))["python"]["interpreter_constraints"][0])) else "null")'
3.10.8
```
and there are also scenarios to read TOML values before the Python runtime becomes available in CI pipelines.

So, another approach is to just reuse the well-established `jq` and `yq` (which are already included in the runner base image!) by converting TOML to JSON or YAML, and `yj` does this job perfectly.

My usecase:
```console
$ cat pants.toml | yj -t | jq -r '.python.interpreter_constraints[0] | match("^CPython==(.*)$").captures[0].string'
3.10.8
```

### URL for tool's homepage

https://github.com/sclevine/yj

### Provide a basic test case to validate the tool's functionality.

```bash
#! /bin/bash
[ $(echo -e '[python]\ninterpreter_constraints = ["CPython==3.10.8"]' | yj -t | jq -r '.python.interpreter_constraints[0] | match("^CPython==(.*)$").captures[0].string') = "3.10.8" ] && echo 'pass' || echo 'fail'
[ $(echo -e '[python]\ninterpreter_constraints = ["CPython==3.10.8"]' | yj -ty | yq -r '.python.interpreter_constraints[0] | match("^CPython==(.*)$").captures[0].string') = "3.10.8" ] && echo 'pass' || echo 'fail'

# both should print "pass"
# if you change the right-hand value "3.10.8" to others, it should print "fail"
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
wget -O /usr/local/bin/yj https://github.com/sclevine/yj/releases/download/v5.1.0/yj-linux-amd64
chmod +x /usr/local/bin/yj
```
Since it is a Go-based single-binary executable, just downloading it from the release archive with proper platform and architecture names and setting `chmod +x` is sufficient to install it.

### Tool installation time in runtime

Less than 10 seconds

### Are you willing to submit a PR?

Not yet

**Comment by mikhailkoliada** [comment]
Hello! Given the tool size and installation time we would not like to add it to the images, please install in pipeline's  runtime.

**Comment by achimnol** [comment]
> Hello! Given the tool size and installation time we would not like to add it to the images, please install in pipeline's runtime.

Hm... I don't understand your reason about the tool size.
If the size is the main criteria for accepting a new tool, the same should apply to others such as `jq` (which is only about 1~2 MB).  The main motivation to include in the base runner image is to avoid copy-and-pasting the same installation codes to every workflow and make them universally available.
