### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by cpanato** [actions/runner-images#6752]
### Tool name

hashicorp vault

### Tool license

Mozilla Public License, version 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.12.2

### Brief description of tool

Secure, store and tightly control access to tokens, passwords, certificates, encryption keys for protecting secrets and other sensitive data using a UI, CLI, or HTTP API.

### URL for tool's homepage

https://developer.hashicorp.com/vault/downloads

### Provide a basic test case to validate the tool's functionality.

```bash
to use for CI tests when configuring a vault instance for e2e tests
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
 echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
 sudo apt update && sudo apt install vault
```

### Are you willing to submit a PR?

yes

**Comment by igorboskovic3** [comment]
Hi @cpanato we will take a look and get back to you.

**Comment by mikhailkoliada** [comment]
Hello. There is an action already that lets you managing vault data in your pipeline: [hashicorp/vault-action](https://github.com/hashicorp/vault-action). We would not like to pre-install the tool itself.

**Comment by cpanato** [comment]
that action does not install the tool rather uses the api to fetch secrets
