### ISSUE TITLE
Network issues in GitHub Runners

### ISSUE THREAD

**Issue by karampreetkaur0** [actions/runner-images#6764]
### Description

We are facing frequent intermittent network issues in our GitHub builds using the shared GitHub runners.

```
chmod +x /home/runner/work/csa/csa/bin/kind
mkdir -p /home/runner/work/csa/csa/bin
wget -q -O /home/runner/work/csa/csa/bin/kapp https://github.com/vmware-tanzu/carvel-kapp/releases/download/v0.37.0/kapp-linux-amd64
make: *** [IaC/Makefile.setup:52: /home/runner/work/csa/csa/bin/kapp] Error 8
Error: Process completed with exit code 2.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 Version: 20221204.2
Link: https://github.com/nwtoht-ca/csa/actions/runs/3686957825/jobs/6240275288
https://github.com/nwtoht-ca/csa/actions/runs/3686274762/jobs/6239017488
https://github.com/nwtoht-ca/csa/actions/runs/3686957825/jobs/6240275288

### Is it regression?

No

### Expected behavior

It should work without getting error and download the packages.

### Actual behavior

wget errors out with Error 8

### Repro steps

Its an intermittent issue.

**Comment by igorboskovic3** [comment]
Hi @karampreetkaur0 we will take a look.

**Comment by igorboskovic3** [comment]
Hi @karampreetkaur0 in my repro test all is going well as you can see here
![image](https://user-images.githubusercontent.com/68074361/207606060-eef41d31-6d46-4eaa-8c06-ccad7671e944.png)
Can you try to add `--waitretry=10` as a workaround if network hiccups occurs, which sometimes could be an issue.
Feel free to reach us if you have additional question.
