### ISSUE TITLE
Errors in Bazel header includes and Clang symbol after 20.04 -> 22.04

### ISSUE THREAD

**Issue by echeran** [actions/runner-images#6765]
### Description

ICU's CI checks have been passing without problems for a long time, on Ubuntu 20.04. The last successful such run was a week ago:
https://github.com/unicode-org/icu/actions/runs/3617159333

Some time in the last week, our project was (apparently) migrated over to Ubuntu 22.04, and subsequent PRs have had tests failing. Ex:
https://github.com/unicode-org/icu/actions/runs/3688629611

If we pin the failing jobs back to using Ubuntu 20.04, they pass again:
https://github.com/unicode-org/icu/actions/runs/3691279527

@markusicu @gnrunge

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20221204.2
https://github.com/unicode-org/icu/pull/2251/checks

Image version: 20221212.1
https://github.com/unicode-org/icu/actions/runs/3688629611

### Is it regression?

20221125.1 https://github.com/unicode-org/icu/actions/runs/3617159333

### Expected behavior

All of the CI checks should pass, including:
* [clang-release-build-and-test](https://github.com/unicode-org/icu/actions/runs/3688629611/jobs/6247470545)
* [run-with-stubdata](https://github.com/unicode-org/icu/actions/runs/3688629611/jobs/6247471664)
* [unicode-update-tools](https://github.com/unicode-org/icu/actions/runs/3688629611/jobs/6247472588)

### Actual behavior

* `clang-release-build-and-test` appears to cause the dependency checker script (which observes compiled symbols) to fail
* run-with-stubdata` has a segfault
* unicode-update-tools runs a Bazel build that claims header files are not declared on a build target

### Repro steps

1. If you previously ran the ICU CI checks on Ubuntu 20.04, they passed
2. If you run ICU CI checks on Ubuntu 22.04, these tests fail (and their failure is not 100% predictable)

**Comment by igorboskovic3** [comment]
Hi @echeran we will take a look, can you provide minimal repro steps?

**Comment by mikhailkoliada** [comment]
Hello! @echeran we can not guarantee that your code will work on ubuntu-22.04 at all due to version differences. From the log you provided we have not found faulty places we could fix on our side, that's why I am going to close the issue. Feel free to reach us out again if you have questions left.
