### ISSUE TITLE
Update [OpenSSL] - Microsoft Hosted Windows hosted agents

### ISSUE THREAD

**Issue by rajakumarbabu** [actions/runner-images#6768]
### Tool name

Openssl

### Tool license

OpenSource

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Latest

### Brief description of tool

We are using Microsoft hosted agent to generate self signed certificate from Azure DevOps pipeline using openssl command. Noticed that agents are using openssl version 1.1.1.0

![image](https://user-images.githubusercontent.com/57990039/207576554-2615a4fd-51f5-496c-b5a8-03fd2d5b85b7.png)

Based on [OpenSSL Security Advisory [15 March 2022]](https://www.openssl.org/news/secadv/20220315.txt) recommendation, need to upgrade openssl from 1.1.1 to 1.1.1n.

![image](https://user-images.githubusercontent.com/57990039/207576683-b47e26df-5ffe-4d92-a0de-d732d49c1c07.png)

Can you please perform openssl upgrade

### URL for tool's homepage

https://www.openssl.org/news/secadv/20220315.txt

### Provide a basic test case to validate the tool's functionality.

```bash
openssl version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by igorboskovic3** [comment]
Thank you @rajakumarbabu we will take a look.

**Comment by mikhailkoliada** [comment]
You can track progress here now: https://github.com/actions/runner-images/issues/6830
