### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by michasHL** [actions/runner-images#6774]
### Tool name

PowerShell 7.3.x

### Tool license

MIT license https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.3.1 or above

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
wget https://github.com/PowerShell/PowerShell/releases/download/v7.3.1/powershell_7.3.1-1.deb_amd64.deb
sudo dpkg -i powershell_7.3.1-1.deb_amd64.deb
sudo apt-get install -f
rm -rf powershell_7.3.1-1.deb_amd64.deb
```

### Tool installation time in runtime

<10 seconds

### Are you willing to submit a PR?

Sure

**Comment by igorboskovic3** [comment]
Thank you @michasHL, we will check it and get back to you.

**Comment by mikhailkoliada** [comment]
Hello! We would not like to add non-lts version of pwsh as it has lots of breaking changes.
