### ISSUE TITLE
Validation build unit tests failure since agent ver 44.0.0 (20221027.1)

### ISSUE THREAD

**Issue by wenjzha** [actions/runner-images#6782]
### Breaking changes

 suffering unit tests failures related to the recent agent image ver update in 1es pool. Here is the setting for the agent under the pool:
Agent name: 'ScheduleAndExecution-Builders-CUS-Pool 1'
Agent machine name: '57050056c000000'
Current agent version: '2.213.2'
Operating System:
Microsoft Windows Server 2022
10.0.20348
Datacenter:
Runner Image
Image: windows-2022
Version: 20221120.1
Included Software: https://github.com/actions/runner-images/blob/win22/20221120.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221120.1
1ES Hosted Pool:
SKU: Standard_D8as_v4
Image: ScheduleAndExecution-Builders-CUS-Image
Image Version: 44.0.0
Interactive Mode: False
Request Id: 2693cf00-1cd8-405e-931a-7b4dbc162e16
Pool Name: ScheduleAndExecution-Builders-CUS-Pool
Network Isolation Policy: None
Current image version: '20221120.1'
Agent running as: 'cloudtest'
                                                                                                                                                                                  
Everything works fine with image version 43.0.0 (20221027.1), but start from 44.0.0, our validation build unittests start failing with package assembly issue, here I what I got for the error messages:

"System.IO.FileLoadException with message "Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

We already have the Microsoft.Extensions.Logging.Abstractions ver6.0.0.1 under the related .csproj, package.config and app.config, I even try to reinstall that again with nuget package management under vs2022, still got the same error, In addition, I try to update to higher ver such as 7.0.0.0(the latest one), got similar error:

"System.IO.FileLoadException with message "Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

Anyone can help with this?

### Target date

12/05/22

### The motivation for the changes

using the latest image to prevent any potential security issues such as s360 violation.

### Possible impact

cannot use the validation build unit tests 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

none

**Comment by igorboskovic3** [comment]
Hi @wenjzha , please provide minimal repro steps, thanks.

**Comment by mikhailkoliada** [comment]
@wenjzha I am going to close the issue, feel free to reach us out when you have all the steps so we could help you! :)
