### ISSUE TITLE
Packer deprecated, when will the replacement be ?

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#6783]
### Description

I get a warning that packer is deprecated for vms and recommended path is to use managed disk.

when is this going to be upgraded to use managed disk?

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I get a warning that packer is deprecated for vms and recommended path is to use managed disk.

when is this going to be upgraded to use managed disk?

### Is it regression?

No

### Expected behavior

I get a warning that packer is deprecated for vms and recommended path is to use managed disk.

when is this going to be upgraded to use managed disk?

### Actual behavior

I get a warning that packer is deprecated for vms and recommended path is to use managed disk.

when is this going to be upgraded to use managed disk?

### Repro steps

I get a warning that packer is deprecated for vms and recommended path is to use managed disk.

when is this going to be upgraded to use managed disk?

**Comment by igorboskovic3** [comment]
Hi @vamshisiram can you be more specific , which packer and which image and what is the context? Thanks
