### ISSUE TITLE
Update conda / Add conda-libmamba-solver

### ISSUE THREAD

**Issue by jfrost-mo** [actions/runner-images#6785]
### Tool name

conda-libmamba-solver

### Tool license

BSD 3-Clause License

### Add or update?

- [X] Add
- [X] Update

### Desired version

22.12.0 or newer

### Approximate size

~2 MB

### Brief description of tool

The conda package manager [recently stabilised their work on a much improved solver](https://www.anaconda.com/blog/conda-is-fast-now), which can be accessed by installing the conda-libmamba-solver conda package, and setting a configuration option.

Based on [some testing](https://github.com/jfrost-mo/example-python-project/blob/github-actions-test/.github/workflows/test.yml) the time to create an environment can go from 10m30s down to 0m52s, with lower memory usage while it is working. This is less dev time wasted waiting, and less Actions minutes used too.

~~While installing is fine on a local install that will be reused, on GitHub actions the runner is freshly created each time, and so the slow installation step has to be repeated. Given this is what conda-libmamba-solver fixes, it somewhat defeats the purpose.~~ - It actually installs a lot quicker than I expected.

This does require conda itself to be up to date (version 22.11 or greater). Updating conda takes 15 seconds, and installing conda-libmamba-solver requires an additional 7 seconds.

### URL for tool's homepage

https://conda.github.io/conda-libmamba-solver/

### Provide a basic test case to validate the tool's functionality.

```bash
# Workaround for mamba-org/mamba#488
rm /usr/share/miniconda/pkgs/cache/*.json

# Install package using libmamba solver. (-q so the spinner doesn't mess up the logs.)
conda install numpy -q --solver=libmamba
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
#! /bin/bash

# Update conda
conda update -q conda

# Installing libmamba solver
conda install -q -n base conda-libmamba-solver

# Making it actually used. (Very quick, could be left to during
# workflow run, especially as it is a potentially breaking change due
# to it giving different solutions to the classic solver sometimes.)
conda config --set solver libmamba

# Workaround for mamba-org/mamba#488
rm /usr/share/miniconda/pkgs/cache/*.json
```

### Tool installation time in runtime

0m21s

### Are you willing to submit a PR?

Yes

**Comment by igorboskovic3** [comment]
Hi @jfrost-mo , we will take a look.

**Comment by jfrost-mo** [comment]
I want to say that the steps for supporting the other platforms should be exactly the same, but I don't have the experience with them to say that confidently. (The workaround probably needs to be different for Windows.)

**Comment by mikhailkoliada** [comment]
Hello! Given the installation time we would not like to add package to the image, it still can be installed in runtime.
