### ISSUE TITLE
Add bsdmainutils 

### ISSUE THREAD

**Issue by dbaileyut** [actions/runner-images#6789]
### Tool name

bsdmainutils

### Tool license

BSD?

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

652KB

### Brief description of tool

collection of more utilities from FreeBSD
This package contains lots of small programs many people expect to find when they use a BSD-style Unix system.
 
It provides banner (as printerbanner), calendar, col, colcrt, colrm, column, from (as bsd-from), hexdump (or hd), look, lorder, ncal (or cal), ul, and write (as bsd-write).

Specifically, I'm looking for ncal but the whole package was installed in previous Ubuntu releases

### URL for tool's homepage

https://packages.ubuntu.com/jammy/bsdmainutils

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Maybe

**Comment by mikhailkoliada** [comment]
Hello! Due to size of the binary and installation time we would not like to preinstall the package.
