### ISSUE TITLE
Windows 2019 Agent / build fails on the lasts step- sysprep. The image is undeployable 

### ISSUE THREAD

**Issue by jamelia1303** [actions/runner-images#6790]
### Description

Agent Build process fails on the last step -sysptep
Full log 
[logs.txt](https://github.com/actions/runner-images/files/10246741/logs.txt)

==> vhd: Machine successfully restarted, moving on
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Windows\SERVIC~1\NETWOR~1\AppData\Local\Temp\powershell-provisioner2297736075
    vhd: IMAGE_STATE_COMPLETE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE
    vhd: IMAGE_STATE_UNDEPLOYABLE

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [x] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: 10.0.17763.3650

### Is it regression?

no

### Expected behavior

Successfully sysprep image  

### Actual behavior

sysprep fails

### Repro steps

Run build creation

**Comment by mikhailkoliada** [comment]
Dup of https://github.com/actions/runner-images/discussions/6251
