### ISSUE TITLE
unable to download mysqlcli tools

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#6791]
### Description

when generating the image, it continuously fails at this step

![image](https://user-images.githubusercontent.com/90816346/208182246-3a1e0424-c5e3-47dd-a9ad-99e657774253.png)

![image](https://user-images.githubusercontent.com/90816346/208182916-68cf61f2-64ff-48cd-b6e6-861673ce459a.png)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://user-images.githubusercontent.com/90816346/208182277-00d282e5-efe8-40f5-b27a-34c85b29ef31.png)

![image](https://user-images.githubusercontent.com/90816346/208182934-8ba62f3c-a878-4758-8904-eb1a2112caea.png)

### Is it regression?

No

### Expected behavior

download mysqlcli and move forward

### Actual behavior

![image](https://user-images.githubusercontent.com/90816346/208182303-e001ed77-1243-4062-a753-194cdd276945.png)

### Repro steps

run it and it is failing.

after investigation from my side, it appears the link shown in the error is invalid, when i go to it in a browser it says cannot find.

so, the actual script from the repo has the URL as "https://dev.mysql.com/get/Downloads, where are the correct path is "https://dev.mysql.com/Downloads", wihtout the word get, unless this is some magic for the script.

**Comment by mikhailkoliada** [comment]
Please sync your main branch, we changed the installation method.
