### ISSUE TITLE
actions should fail if an invalid Runner name is specified.

### ISSUE THREAD

**Issue by Yaminyam** [actions/runner-images#6793]
### Description

If an invalid runner name is given as the runs-on argument, actions will stay loading forever.
I think actions should fail if you specify an invalid runner name.

ex)
https://github.com/Yaminyam/backend.ai/actions/runs/3716784740/jobs/6303496952

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

.

### Is it regression?

.

### Expected behavior

actions fail the action.

### Actual behavior

It's stuck in an infinite loading state.

### Repro steps

Invalid runner name given to the runs-on argument.

**Comment by mikhailkoliada** [comment]
Hello! Please file an issue to https://github.com/actions/runner, we are maintaining runner, images, not runner itself.
