### ISSUE TITLE
Allow multiple versions of runners to be used for larger runners.

### ISSUE THREAD

**Issue by Yaminyam** [actions/runner-images#6794]
### Tool name

larger runner

### Tool license

.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

beta

### Brief description of tool

https://github.blog/changelog/2022-10-20-github-actions-larger-hosted-runners-are-now-automatically-created-for-customers/
Only the latest version of each image can be used in the preset larger runner currently provided as a beta version.
As the version of ubuntu-latest runner has been changed from 20.04 to 22.04 this time, it is thought that the demand from users of the 20.04 version will increase.
I think it would be nice to provide a runner with a default setting of larger for older version runners such as `ubuntu-20.04-8-cores`.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello! We do not provide multiple versions at the moment and have no plans to provide them in the near future.
