### ISSUE TITLE
MacOS 11 Test Runners are sometimes very slow to allocate localhost ephemeral ports

### ISSUE THREAD

**Issue by philipaconrad** [actions/runner-images#6798]
### Description

MacOS test runners sometimes randomly fail to allocate local ephemeral ports (binding on localhost, port 0) in a reasonable amount of time. (<10 seconds)

### Background
The [Open Policy Agent](https://github.com/open-policy-agent/opa) project has had MacOS test runner flakeouts for the last year or longer, which we've traced down to Github's MacOS runners not allocating ephemeral ports on localhost within a reasonable timeout window.

We reduced the frequency of test failures by setting our test timeouts dramatically higher, but even that has not completely eliminated the issue.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

## Runner Image Version
```
  Image: macos-11
  Version: 20221204.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-11/20221204.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20221204.1
```

## Failed Build Links

Below is all of the failed builds I could find in the last 50+ pages of our Actions tab. There are more failures before that, but we lack logs for those, so I couldn't filter out the relevant MacOS-specific failures any further back than mid-September of this year.

- 2022-09-19 :: https://github.com/open-policy-agent/opa/actions/runs/3086002394/jobs/4989931846
- 2022-09-27 :: https://github.com/open-policy-agent/opa/actions/runs/3133718529/jobs/5087429623
- 2022-09-27 :: https://github.com/open-policy-agent/opa/actions/runs/3133907251
- 2022-09-29 :: https://github.com/open-policy-agent/opa/actions/runs/3150959161
- 2022-10-04 :: https://github.com/open-policy-agent/opa/actions/runs/3182161802
- 2022-10-07 :: https://github.com/open-policy-agent/opa/actions/runs/3205078959
- 2022-10-13 :: https://github.com/open-policy-agent/opa/actions/runs/3245707491/jobs/5323603860
- 2022-10-23 :: https://github.com/open-policy-agent/opa/actions/runs/3309741550
- 2022-10-26 :: https://github.com/open-policy-agent/opa/actions/runs/3328080921/jobs/5503679140
- 2022-10-26 :: https://github.com/open-policy-agent/opa/actions/runs/3328436743
- 2022-10-27 :: https://github.com/open-policy-agent/opa/actions/runs/3337314169
- 2022-11-04 :: https://github.com/open-policy-agent/opa/actions/runs/3398356922/jobs/5651340769
- 2022-11-14 :: https://github.com/open-policy-agent/opa/actions/runs/3465052451/jobs/5787351393
- 2022-11-16 :: https://github.com/open-policy-agent/opa/actions/runs/3478249417/jobs/5815415364
- 2022-11-29 :: https://github.com/open-policy-agent/opa/actions/runs/3573433258/jobs/6007520286
- 2022-12-06 :: https://github.com/open-policy-agent/opa/actions/runs/3631372190/jobs/6125953106
- 2022-12-08 :: https://github.com/open-policy-agent/opa/actions/runs/3648206847/jobs/6161384209
- 2022-12-15 :: https://github.com/open-policy-agent/opa/actions/runs/3704859616/jobs/6278041885#step:6:2280
- 2022-12-16 :: https://github.com/open-policy-agent/opa/actions/runs/3711650114/jobs/6292324267
- 2022-12-16 :: https://github.com/open-policy-agent/opa/actions/runs/3717877980/jobs/6305663651

### Is it regression?

Unknown, but likely not a new regression.

### Expected behavior

MacOS test runners provide ephemeral/dynamic localhost ports to our Golang tests in <10 seconds.

### Actual behavior

MacOS test runners occasionally fail to provide a port within a *10 second* time frame, causing our tests to crash.

### Repro steps

The failures are intermittent, and seem to be almost completely random. The failures may be tied to faulty hardware, as referenced in #3885.

I will periodically add new failures to the list above if that would be helpful.

**Comment by mikhailkoliada** [comment]
Hello!

We are aware of this problem and we are working in order to make macOS agents better, but for now we are having some hardware limitations and nothing can be done from the images side :(. Feel free to reach us again if you have questions left.

**Comment by philipaconrad** [comment]
@mikhailkoliada Is there any place that would be more appropriate to forward the failed jobs list to?
