### ISSUE TITLE
unable to resolve dependency for postgressql

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#6802]
### Description

as suggested i downloaded new code from main branch last night and kicked off a build, mysql issue resolved but failed on postgresql.

![Capture](https://user-images.githubusercontent.com/90816346/208256405-bfae7291-648c-4cf9-ade3-977e496667fa.PNG)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![Capture](https://user-images.githubusercontent.com/90816346/208256393-351d8b10-38f0-4444-bf39-9ef11eade891.PNG)

### Is it regression?

No

### Expected behavior

install postgresql. but failed

### Actual behavior

failure of postgresql

![Capture](https://user-images.githubusercontent.com/90816346/208256432-c45c8a14-555d-4268-9839-cc847862662b.PNG)

### Repro steps

run the latest code from last night and it will fail.

**Comment by LeventeNagy-CD** [comment]
I had the same. Debugging it I saw more packages were updated on Dec 16 to Chocolatey.

id         : http://community.chocolatey.org/api/v2/Packages(Id='postgresql',Version='14.4.1')
title      : title
summary    : summary
updated    : 2022-12-13T17:00:01Z
author     : author
link       : {link, link}
category   : category
content    : content
properties : properties

id         : http://community.chocolatey.org/api/v2/Packages(Id='postgresql',Version='14.5.1')
title      : title
summary    : summary
updated    : 2022-12-16T15:45:01Z
author     : author
link       : {link, link}
category   : category
content    : content
properties : properties

id         : http://community.chocolatey.org/api/v2/Packages(Id='postgresql',Version='14.6.1')
title      : title
summary    : summary
updated    : 2022-12-16T20:30:00Z
author     : author
link       : {link, link}
category   : category
content    : content
properties : properties 

I tried choco installation of 14.6.1 on a clean host and it failed with the same dependency error. 
Then i tried the same choco install with 14.5.1 and that worked. 

So i temporarily hardcoded that in line 11 of Install-ProgresSQL.ps1 and that allowed image generation to go past this. 

$latestChocoPackage = "14.5.1" #Get-LatestChocoPackageVersion -TargetVersion $toolsetVersion -PackageName "postgresql"             ++++dependency error with 14.6.1

**Comment by igorboskovic3** [comment]
Hi @vamshisiram thank you, we will take a look and get back to you.

**Comment by raherrebrugh** [comment]
Issue also applies to Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
Hi @vamshisiram, please check my PR, it will be merged after proper testing however, you can already use the alternative installation of the PostgreSQL from it.

**Comment by mikhailkoliada** [comment]
Should be fixed now.

**Comment by vamshisiram** [comment]
@Alexey-Ayupov  @mikhailkoliada Thanks, it fixed my issue with postgresl, but now i am having the same issue as in #6251 :-( , i tagged you guys in that issue thread to see if you can shed some light into it, as this has been going for over three months now and many folks are having this issue.
