### ISSUE TITLE
Update LLVM to version 15

### ISSUE THREAD

**Issue by WopsS** [actions/runner-images#6803]
### Tool name

LLVM

### Tool license

Apache-2.0 with LLVM-exception license

### Add or update?

- [ ] Add
- [X] Update

### Desired version

15.0.6 or newest

### Approximate size

~277 MB

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by igorboskovic3** [comment]
Hi @WopsS and thank you, we will take a look.

**Comment by WopsS** [comment]
Hello @igorboskovic3, no problem! :)
Does the comment in https://github.com/actions/runner-images/pull/5286 still applies or can I submit a PR for this?

**Comment by mikhailkoliada** [comment]
Done

**Comment by WopsS** [comment]
Great! Thanks :D
