### ISSUE TITLE
macOS 12 runners: AppleScript unable to target "Notifications & Focus" in System Preferences

### ISSUE THREAD

**Issue by cmorten** [actions/runner-images#6804]
### Description

I am running an AppleScript to disable do not disturb on macOS agents for CI tests.

Recently on macOS 12 agents the script has started failing because the command to click the "Notifications & Focus" button in System Preferences is incorrectly clicking the "Security & Privacy" button.

Timeline:

- Working as expected with version [20221018.2](https://github.com/guidepup/setup/actions/runs/3366047605/jobs/5582140127)
- First issue observed with version [20221027.1](https://github.com/guidepup/setup/actions/runs/3413410356/jobs/5680082861)
- Issue resolved with version [20221121.1](https://github.com/guidepup/setup/actions/runs/3588493202/jobs/6039949253)
- Still working as expected with version [20221127.5](https://github.com/guidepup/setup/actions/runs/3610309167/jobs/6084032121)
- Issue observed again with version [20221204.1](https://github.com/guidepup/setup/actions/runs/3724456811/jobs/6316620939)

Linked builds all take screen-recordings and store as GitHub Actions artifacts for debugging. See below for an example recording:

https://user-images.githubusercontent.com/11313985/208294986-fcd225db-f3dd-43d6-b0ee-784f77d2b5c0.mov

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Most recently failing with version [20221204.1](https://github.com/guidepup/setup/actions/runs/3724456811/jobs/6316620939).

### Is it regression?

Last working with version [20221127.5](https://github.com/guidepup/setup/actions/runs/3610309167/jobs/6084032121).

### Expected behavior

On macOS 12, delivering an AppleScript command to click the "Notifications & Focus" button in System Preferences should open the "Notifications & Focus" window.

### Actual behavior

On macOS 12, delivering an AppleScript command to click the "Notifications & Focus" button in System Preferences is incorrectly opening the "Security & Privacy" window.

### Repro steps

Execute AppleScript to click the "Notification & Focus" button in System Preferences on a macOS 12 agent.

Sample AppleScript:

```applescript
tell application "System Events"
  tell application "System Preferences" to activate

  click UI Element "Notifications
& Focus" of scroll area 1 of window "System Preferences" of application process "System Preferences"
end tell

-- Observe that locally this opens the "Notifications & Focus" window.
-- On the macOS agent it opens "Security & Privacy".
-- This is a simple example for illustration and may be prone to timeout / race conditions, impacted code has timeouts and retries in place.
```

For ease can run using <https://github.com/guidepup/setup-action>, however this performs more than just the above script.

**Comment by mikhailkoliada** [comment]
Hello! We do not really control osascript on image side, changes happen after macOS update (to osascript too) and it is completely out of our hands.

**Comment by cmorten** [comment]
@mikhailkoliada I can appreciate that - guess hands are tied when it’s the OS at fault! Thanks for taking a look.

Does make it somewhat tricky to enable do not disturb mode on macOS 12 😅. Looks like there might be another option using Shortcuts.app.

REF:
- https://github.com/sindresorhus/do-not-disturb/issues/9
- https://github.com/sindresorhus/do-not-disturb/issues/12

Would enabling do no disturb mode by default ever be considered as a feature request? (I’m guessing there are likely folks relying on default notification behaviour so they can test notification flows of their apps?)
