### ISSUE TITLE
first VSIX then on retry WDK failed with -532462766.

### ISSUE THREAD

**Issue by LeventeNagy-CD** [actions/runner-images#6805]
### Description

1. I tried to run a GenerateResourcesAndImage  script and it failed Install-Vsix.ps1 with the below.
```
==> vhd: Provisioning with powershell script: C:\runner-images\images\win/scripts/Installers/Install-Vsix.ps1
    vhd: Downloading package from: https://visualstudioclient.gallerycdn.vsassets.io/extensions/visualstudioclient/microsoftvisualstudio2022installerprojects/2.0.0/1641503017035/InstallerProjects.vsix to path C:\Users\packer\AppData\Local\Temp\InstallerProjects.vsix .
    vhd: Package downloaded successfully in 0.11 seconds
    vhd: Starting Install InstallerProjects.vsix...
    vhd: Unsuccessful exit code returned by the installation process: -532462766.
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? r
```

2. So i retried the entire GenerateResourcesAndImage into a whole new resource-group, everything new & clean.
This time it failed with the same error but not at Vsix but one step before at WDK
```
==> vhd: Provisioning with powershell script: C:\runner-images\images\win/scripts/Installers/Install-WDK.ps1
    vhd: Downloading wdksetup.exe...
    vhd: Downloading package from: https://go.microsoft.com/fwlink/?linkid=2196230 to path C:\Users\packer\AppData\Local\Temp\wdksetup.exe .
    vhd: Package downloaded successfully in 0.53 seconds
    vhd: Starting Install wdksetup.exe...
    vhd: Installation successful in 204.74 seconds
    vhd: Starting Install WDK.vsix...
    vhd: Unsuccessful exit code returned by the installation process: -532462766.
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows2022-readme.md

# Microsoft Windows Server 2022 Datacenter
- OS Version: 10.0.20348 Build 1249
- Image Version: 20221204.3

windows2022.json:
        "image_version": "dev",
        "image_os": "win22"

### Is it regression?

no

### Expected behavior

Vsixs and WDK installs, VHD generates. 

### Actual behavior

Similar failure seen first  at Vsix then at WDK installation

### Repro steps

checkout current code, try GenerateResourceAndImage for windows 2022

**Comment by mikhailkoliada** [comment]
Hello! It is a network issue. Nothing can be done.

**Comment by LeventeNagy-CD** [comment]
> Hello! It is a network issue. Nothing can be done.

Hey Mikhail
Sorry to be a pain but how do you mean nothing can be done?  Should I just stop using this and look for something else?

Network issue where and between what? -532462766 suggests some build/compile issue, can you please elaborate on what sort of network issue should I think of?

**Comment by mikhailkoliada** [comment]
> > Hello! It is a network issue. Nothing can be done.
> 
> Hey Mikhail Sorry to be a pain but how do you mean nothing can be done? Should I just stop using this and look for something else?
> 
> Network issue where and between what? -532462766 suggests some build/compile issue, can you please elaborate on what sort of network issue should I think of?

I mean it is vsix extension site issue and sometimes it happens, retry must help you
