### ISSUE TITLE
Update conda

### ISSUE THREAD

**Issue by jfrost-mo** [actions/runner-images#6806]
### Tool name

conda

### Tool license

3-Clause BSD License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

v22.11.1 (or latests if another stable release is made)

### Brief description of tool

Conda has [recently added some significant speedups](https://www.anaconda.com/blog/conda-is-fast-now) which can be combined with a dependency installed at runtime to get an order of magnitude faster package installation. (See #6785 for a few numbers.)

As conda is already installed on the runners, and as it is best practice to update it before using it to minimising the chances of it failing to install a package, it makes sense to run the latest stable version. The current runners use 4.12 (from March 2022), which is fairly old. Inline with the [preinstallation policy](https://github.com/actions/runner-images#preinstallation-policy) of Latest Technology it makes sense to update it.

### URL for tool's homepage

https://docs.conda.io/en/latest/

### Provide a basic test case to validate the tool's functionality.

```bash
conda --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Update conda
conda update -q conda
```

### Tool installation time in runtime

~20 seconds.

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
Hello! We are installing the latest available release from https://repo.anaconda.com/miniconda/ i.e running the `Miniconda3-latest-Linux-x86_64.sh` script, which downloads the latest release. So it will be updated as soon as miniconda's developers make their new latest release, we do not install non-release changes in this specific case.
