### ISSUE TITLE
Update Docker with the option "default-cgroupns-mode": "host" 

### ISSUE THREAD

**Issue by BorderCloud** [actions/runner-images#6809]
### Tool name

Docker compose

### Tool license

...

### Add or update?

- [ ] Add
- [X] Update

### Desired version

last

### Brief description of tool

I use systemctl in my scripts with docker containers in the runner ubuntu-last.
But now, my scripts failed because the new API 1.41 of Docker added the option cgroupns with by default, the value "private" or empty. I have to put the value "host" with my scripts.
The command "docker run" gives "--cgroupns=hosts" to configure this option correctly but it's not again possible via docker compose and there is only one solution: insert "default-cgroupns-mode": "host" in the /etc/docker/daemon.json

I tried to change the file /etc/docker/daemon.json with "sudo" via the file yml but I have the message "Permission denied". I don't know how stop correctly the service Docker in the runner.

Can you insert the option "default-cgroupns-mode": "host" in the /etc/docker/daemon.json in the runner? 
or how to modify myself the file /etc/docker/daemon.json  in my file yml ?

Thanks

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by igorboskovic3** [comment]
Hi @BorderCloud we will take a look.

**Comment by igorboskovic3** [comment]
hi @BorderCloud can you provide minimal repro steps?

**Comment by igorboskovic3** [comment]
@BorderCloud is this helpful?
```
name: test
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
        
      - name: host
        run: |
        
         echo $'{\n    "default-cgroupns-mode":host\n}' | sudo tee /etc/docker/daemon.json
         cat /etc/docker/daemon.json
         docker --version
```

**Comment by igorboskovic3** [comment]
@BorderCloud yes, just add `sudo service docker restart`, I will close this, if you have any additional questions feel free to reach us, thanks
