### ISSUE TITLE
Microsoft.NETCore.App.Host nuget restore regression between image 20221027.1 and 20221214.4 for x86 builds

### ISSUE THREAD

**Issue by Scottj1s** [actions/runner-images#6810]
### Description

With image 20221214.4, a nuget restore on a .NET Core 3.1 project building for x86 is failing because the AppHost runtime identifier is being incorrectly set to win-x64.

With image 20221027.1, the nuget restore did not require downloading the Microsoft.NETCore.App.Host package, presumably because it was included in the image.  However, with the 20221214.4 update, the Microsoft.NETCore.App.Host package is required.  For x64 builds, the on-demand download works fine.  But for x86 builds, the x64 package is erroneously downloaded, causing a downstream break when apphost.exe cannot be found.

A workaround is to add a "Use .NET Core 3.1" pipeline task to ensure that the package is downloaded already.

See attached build log excerpts for comparison:
[nuget_restore_20221027.1.txt](https://github.com/actions/runner-images/files/10262276/nuget_restore_20221027.1.txt)
[nuget_restore_20221214.4.txt](https://github.com/actions/runner-images/files/10262277/nuget_restore_20221214.4.txt)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

The affected pipeline is internal to Microsoft, but access can be granted on request.

### Is it regression?

Yes, see above

### Expected behavior

The correct runtime identifier (architecture) should be used when downloading the Microsoft.NETCore.App.Host package on demand. For example, an x86 build should download Microsoft.NETCore.App.Host.win-x86, and not Microsoft.NETCore.App.Host.win-x64.

### Actual behavior

The Microsoft.NETCore.App.Host.win-x64 package is being downloaded for an x86 build.

### Repro steps

1. Create a pipeline with a csproj targeting .NET Core 3.1
2. Run the pipeline targeting x86

**Comment by igorboskovic3** [comment]
Hi @Scottj1s we will take a look.

**Comment by bogdan-damian-bgd** [comment]
Hey @Scottj1s, apart from minor changes to VS, the .NET Core SDK 6.0 is the one that was added in the newer image (when comparing the mentioned [20221027.1](https://github.com/actions/runner-images/blob/8bdf5c36087ae1104905787ce0413d2eb355c1ab/images/win/Windows2019-Readme.md) and [20221214.4](https://github.com/actions/runner-images/blob/504c3071979510647b1f780aa7d69ff359e7788a/images/win/Windows2019-Readme.md)) while in the older image the 5.0 was the default. This seems to be the reason it no longer fetches the local nuget content included in the image and why the workaround you mentioned works. I assume that nuget download with the appropriate RID may also be affected by the corresponding project configs like in .csproj

**Comment by bogdan-damian-bgd** [comment]
Hi, I am going to close. Feel free to reach us again if you have any concerns.
