### ISSUE TITLE
.Net 7.0 fails with message "Unable to locate the .NET SDK."

### ISSUE THREAD

**Issue by ariel-lenis** [actions/runner-images#6835]
### Description

I'm working in a product that compiles .NET 7.0 C# projects, Managed C++ projects and Native C++ projects

We are using Microsoft Hosted Agents to compile the code, sometimes the build fails with the next message:

`A compatible .NET SDK was not found.

Requested SDK version: 7.0.101
global.json file: D:\a\1\s\MIP\global.json

Installed SDKs:
No .NET SDKs were found.

Install the [7.0.101] .NET SDK or update [D:\a\1\s\MIP\global.json] to match an installed SDK.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
`

`##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(83,3): Error : Unable to locate the .NET SDK. Check that it is installed, your PATH is configured for the correct architecture, and that the version specified in global.json (if any) matches the installed version.`

There is a pattern with the machine name:

**It always fails if the Agent machine name starts with "WIN"**
Agent machine name: 'WIN-QQ0A24GFN4G'
Agent machine name: 'WIN-QP82KKJAC6U'
Agent machine name: 'WIN-CP7VKK4U71G'

**It always completes successfully if the Agent machine name starts with "fv-"**

Agent machine name: 'fv-az172-278'
Agent machine name: 'fv-az346-513'
Agent machine name: 'fv-az175-381'
Agent machine name: 'fv-az342-127'
Agent machine name: 'fv-az347-831'
Agent machine name: 'fv-az172-278'
Agent machine name: 'fv-az130-841'

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

**It always fails if the Agent machine name starts with "WIN"**
Agent machine name: 'WIN-QQ0A24GFN4G'
Agent machine name: 'WIN-QP82KKJAC6U'
Agent machine name: 'WIN-CP7VKK4U71G'

**It always completes successfully if the Agent machine name starts with "fv-"**

Agent machine name: 'fv-az172-278'
Agent machine name: 'fv-az346-513'
Agent machine name: 'fv-az175-381'
Agent machine name: 'fv-az342-127'
Agent machine name: 'fv-az347-831'
Agent machine name: 'fv-az172-278'
Agent machine name: 'fv-az130-841'

### Is it regression?

Not sure about this field

### Expected behavior

It must always build in all Agents

### Actual behavior

**It always fails if the Agent machine name starts with "WIN"**

### Repro steps

It is a private project, I can't put all the details but basically the MSBUILD is not able to detect the installed .Net version if the Agent machine name starts with "WIN"*

**Comment by erik-bershel** [comment]
Hey @ariel-lenis, we'll take a look. But send please a links on failed runs of your Azure pipeline.

**Comment by mikhailkoliada** [comment]
As there is no repro steps, I am going to close the issue, feel free to reach us again once you have something we could help you with.
