### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by baldcorp** [actions/runner-images#6843]
### Tool name

azprn

### Tool license

none

### Add or update?

- [ ] Add
- [ ] Update

### Desired version

1.2

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hi @baldcorp, please fill ticket with all required information or I will have to close it.
