### ISSUE TITLE
[windows-2022] WSL fails to install Ubuntu image in GitHub Actions and Azure DevOps Pipelines

### ISSUE THREAD

**Issue by danieljurek** [actions/runner-images#6844]
### Description

Running a pipeline which attempts to install and run a WSL distro on `windows-2022` is seeing failures. 

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Azure DevOps Pipelines: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2061298&view=logs&j=62f96420-69e0-55c5-87e4-47c3c06a1c78&t=e9d05e54-e4c3-4068-b939-70402bb7e376&l=11

GitHub Actions: https://github.com/danieljurek/actions-testbed-public/actions/runs/3789275973/jobs/6442878070

### Is it regression?

It might be. We've seen success with image version `20221204.3` and earlier and now we are consistently experiencing failure.

### Expected behavior

Run a pipeline which attempts to install a WSL image like `Ubuntu-20.04` on `windows-2022` 

## Azure DevOps Pipelines

Result of running `wsl --install -d Ubuntu-20.04` 

```
Installing: Ubuntu 20.04 LTS


An error occurred during installation. Distribution Name: 'Ubuntu 20.04 LTS' Error Code: 0x8000ffff
```

In [previous runs of pipelines with roughly similar WSL code](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2061298&view=logs&j=62f96420-69e0-55c5-87e4-47c3c06a1c78&t=569ea126-27b5-5a23-71c4-ce1c427a6ea6) using the Microsoft hosted agent pool (image version `20221204.3`), the install succeeds and we can move to the next step. 

We've seen failures in images with later versions like [`20221215.2`](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2069013&view=logs&j=eab3bf07-e4a8-5feb-e258-dcdff3614a8b&t=834e81d0-1f5e-4907-824f-293c55e85984&l=8). 

## GitHub Actions

Result of running `wsl --install -d Ubuntu-20.04`
```
wsl --install -d Ubuntu-20.04
Installing: Ubuntu 20.04 LTS


An error occurred during installation. Distribution Name: 'Ubuntu 20.04 LTS' Error Code: 0x[80](https://github.com/danieljurek/actions-testbed-public/actions/runs/3789275973/jobs/6442878070#step:2:81)00ffff

```

## Azure DevOps Pipelines

```yaml
jobs:
  - job: TryWsl
    pool:
      name: Azure Pipelines
      vmImage: windows-2022

    steps:
      - pwsh: |
          Write-Host "wsl --status" 
          wsl --status 

          Write-Host "wsl --list --online" 
          wsl --list --online

          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04"
          wsl --install -d Ubuntu-20.04

          Write-Host "wsl --list --all --verbose | out-string"
          $wsl = wsl --list --all --verbose | out-string
          write-host $wsl

          $checkCount = 0
          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            $checkCount++
            if ($checkCount -gt 30) { 
              Write-Host "Failed to detect start in time"
              exit 1
            }
            start-sleep -seconds 1
            Write-Host "wsl --list --all --verbose | out-string"
            $wsl = wsl --list --all --verbose | out-string
            write-host $wsl

            Write-Host "wsl --status"
            wsl --status
          }
          write-host "Ubuntu installed."
        displayName: Install WSL


```

## GitHub Actions

```yaml
name: wsl

on:
  pull_request: 
    branches: [main]
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  run-wsl:
    runs-on: windows-2022
    steps:
      - name: Run WSL 
        shell: pwsh
        run: |
          Write-Host "wsl --status" 
          wsl --status 
          Write-Host "wsl --list --online" 
          wsl --list --online
          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04"
          wsl --install -d Ubuntu-20.04
          Write-Host "wsl --list --all --verbose | out-string"
          $wsl = wsl --list --all --verbose | out-string
          write-host $wsl
          while ($wsl -notmatch 'Ubuntu-20.04.*running') {
            start-sleep -seconds 1
            Write-Host "wsl --list --all --verbose | out-string"
            $wsl = wsl --list --all --verbose | out-string
            write-host $wsl
            Write-Host "wsl --status"
            wsl --status
          }
          write-host "Ubuntu installed."
```

**Comment by austinkinross** [comment]
+1, we're hitting similar problems that are blocking us, albeit with 1ES images

**Comment by erik-bershel** [comment]
Hi @danieljurek! We'll take a look on it.

**Comment by Alexey-Ayupov** [comment]
Hello @danieljurek, recently Microsoft moved WSL to the Microsoft store to make more close to end-users, and since that, we cannot update it using the windows update feature. And for installing it we are using the inbox version as well.
As a workaround, you can update WSL in your run using `wsl --update --web-download ` and check the updated WSL with the `wsl --version` command. You should get something like that:
```
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.20348.1366
```
Example run: 
```
name: test WSL

on:
  workflow_dispatch
  
jobs:
  wsl_run:
    runs-on: windows-latest
    
  - shell: pwsh
        run: |
            $wslupd = wsl --update --web-download | Out-String
            $wslupd
            if ($wslupd) {
              wsl --version
              wsl --set-default-version 1
              wsl --install --distribution Ubuntu-20.04 --web-download --no-launch
            }  
```
https://github.com/baldcorp/publictest/actions/runs/3799926258/jobs/6462906221

**Comment by danieljurek** [comment]
@Alexey-Ayupov -- Thanks for the advice! This does unblock us for now. Where would we find documentation for these kinds of changes so that we're not opening up bugs in the future?

**Comment by erik-bershel** [comment]
Hi @danieljurek,
We are glad we can help you. To track WSL development you can use this [GitHub repo](https://github.com/microsoft/WSL). Some useful links are located at the end of the [readme](https://github.com/microsoft/WSL#readme) file. Please feel free to contact us if you have another questions.
