### ISSUE TITLE
AVX2 instruction support for MacOS systems

### ISSUE THREAD

**Issue by napetrov** [actions/runner-images#6845]
### Description

MacOS systems reports that they don't have AVX2 instruction available. 
I understand that those systems are executed via VMware and many things going on, but from MacOS and Apple HW perspective there is no currently supported apple x86 hardware without AVX2 support.  All AVX systems lost both HW/SW for years ago.  

To be consistent with Apple ecosystem it would be nice to have AVX2 support to be enable for mac VMs   

CPU features:
=== CPU FEATURES ===
    VendorId                : GenuineIntel
    num_virtual_cores       : 3
    num_physical_cores      : 3
    num_threads_per_core    : 1
    num_cpus                : 1
    cache_line_size         : 64
    cache_L1_size           : 32768
    cache_L2_size           : 262144
    cache_L3_size           : 12582912
    OS_x64                  : True
    OS_AVX                  : True
    OS_AVX512               : False
    MMX                     : True
    x64                     : True
    ABM                     : False
    RDRAND                  : True
    BMI1                    : False
    BMI2                    : False
    ADX                     : False
    PREFETCHWT1             : False
    MPX                     : False
    SSE                     : True
    SSE2                    : True
    SSE3                    : True
    SSSE3                   : True
    SSE4.1                  : True
    SSE4.2                  : True
    SSE4.a                  : False
    AES                     : True
    SHA                     : False
    AVX                     : True
    XOP                     : False
    FMA3                    : False
    FMA4                    : False
    **AVX2                    : False**
    AVX512f                 : False
    AVX512pf                : False
    AVX512er                : False
    AVX512cd                : False
    AVX512vl                : False
    AVX512bw                : False
    AVX512dq                : False
    AVX512ifma              : False
    AVX512vbmi              : Fals

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

    System Software Overview:

      System Version: macOS 12.6.2 (21G320)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Mac-1672177612509.local
      User Name: runner (runner)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 21 minutes

    Hardware Overview:

      Model Name: Mac
      Model Identifier: VMware7,1
      Processor Name: Unknown
      Processor Speed: 3.33 GHz
      Number of Processors: 1
      Total Number of Cores: 3
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Memory: 14 GB
      System Firmware Version: VMW71.00V.13989454.B64.1906190538
      OS Loader Version: 540.120.3~22
      Apple ROM Info: [MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]Welcome to the Virtual Machine
      SMC Version (system): 2.8f0
      Serial Number (system): VM8Mb/79Cglq
      Hardware UUID: 4203018E-580F-C1B5-9525-B745CECA79EB
      Provisioning UDID: 4203018E-580F-C1B5-9525-B745CECA79EB

### Is it regression?

don't know

### Expected behavior

AVX2 support avaialbe within VM

### Actual behavior

AVX2 support is not avaialbe within VM

### Repro steps

# CPU info
echo "CPU features:"
if [ -x "$(command -v lscpu)" ]; then
    lscpu
elif [ "$(pip list | grep cpufeature)" != "" ]; then
    python -c "import cpufeature; cpufeature.print_features()"
else
    echo "Unable to get CPU features via lscpu or python/cpufeature"
fi
echo
if [ -x "$(command -v system_profiler)" ]; then
    echo "MacOS detailed features:"
    system_profiler SPSoftwareDataType SPHardwareDataType
fi

**Comment by erik-bershel** [comment]
Hi @napetrov!
It is the same as https://github.com/actions/runner-images/issues/5609 but for macOS. I forced to close that issue because nothing has changed from previous one. We will inform community when it happen.
