### ISSUE TITLE
Kotlin tests fail because of a deprecation warning

### ISSUE THREAD

**Issue by simbo1984** [actions/runner-images#6853]
### Description

One of the Kotlin tests (kotlinc-js -version) fails because the exit code isn't 0 (the deprecation warning oddly returns an error).

Here's the log : 
```
    vhd: Describing Kotlin
    vhd:   [+] kapt is available 2.91s (2.72s|193ms)
    vhd:   [+] kotlin is available 237ms (236ms|1ms)
    vhd:   [+] kotlinc is available 2.22s (2.22s|1ms)
    vhd:   [+] kotlin-dce-js is available 1.63s (1.63s|1ms)
    vhd:   [-] kotlinc-js is available 1.78s (1.77s|2ms)
    vhd:    Command 'kotlinc-js -version' has finished with exit code
    vhd:        info: kotlinc-js 1.8.0 (JRE 1.8.0_352-b08)
    vhd:        error: ==========
    vhd:        This project currently uses the Kotlin/JS Legacy compiler backend, which has been deprecated and will be removed in a future release.
    vhd:
    vhd:        Please migrate your project to the new IR-based compiler (https://kotl.in/jsir).
    vhd:        Because your build tool will not support the new Kotlin/JS compiler, you will also need to migrate to Gradle.
    vhd:
    vhd:        You can continue to use the deprecated legacy compiler in the current version of the toolchain by providing the compiler option -Xuse-deprecated-legacy-compiler.
    vhd:        ==========
    vhd:    at "$toolName -version" | Should -ReturnZeroExitCode, C:\image\Tests\Tools.Tests.ps1:189
    vhd:    at <ScriptBlock>, C:\image\Tests\Tools.Tests.ps1:189
    vhd:   [+] kotlinc-jvm is available 2.24s (2.24s|1ms)
    vhd: Tests completed in 14.5s
    vhd: Tests Passed: 5, Failed: 1, Skipped: 0 NotRun: 36 
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Win19: 20221214.4
Win22: 20221215.2

### Is it regression?

yes, last ones working for us were 20221119 (Win19) and 20221120 (Win22)

### Expected behavior

Kotlin tests should not fail because of a "deprecation" warning.

### Actual behavior

1x Kotlin test fails because of a "deprecation" warning.

### Repro steps

Just building the image using Packer v1.8.3...

**Comment by mikhailkoliada** [comment]
Hello. Fix with the main branch please.

**Comment by simbo1984** [comment]
Thanks @mikhailkoliada!
