### ISSUE TITLE
msys installation for `x64-mingw-ucrt` used by Ruby 3.1+ appears to be missing

### ISSUE THREAD

**Issue by andyundso** [actions/runner-images#6855]
### Description

I did a lot of observations in this issue, so I'm sorry if some of those are wrong. I'm not that deep into C toolchains and Windows programming.

We use Azure DevOps to test a Rails application against Windows. Naturally, to compile Gems with C code, it needs the msys system to do so. We use the windows-2019 environment.

With Ruby 3.1, the C runtime [has been changed](https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html) from MSVCRT to UCRT. I tried upgrading the mentioned application today and while everything on my Windows dev machine worked, I saw a couple of strange issues on Azure DevOps:

First, I ran into a segmentation fault with the Puma gem when starting the Rails tests. While I don't think those segmentation faults are relevant for the issue, I still past it for people that might find this issue via Google.

```
D:/a/1/s/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/puma_http11.so: [BUG] Segmentation fault
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]

-- Control frame information -----------------------------------------------
c:0027 p:-283377866910 s:0130 e:000129 TOP    [FINISH]
c:0026 p:---- s:0127 e:000126 CFUNC  :require
c:0025 p:0047 s:0122 e:000121 TOP    D:/a/1/s/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma.rb:13 [FINISH]
c:0024 p:---- s:0119 e:000118 CFUNC  :require
c:0023 p:0032 s:0114 e:000113 BLOCK  C:/hostedtoolcache/windows/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:60 [FINISH]
c:0022 p:---- s:0109 e:000108 CFUNC  :each
c:0021 p:0042 s:0105 e:000104 BLOCK  C:/hostedtoolcache/windows/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:55 [FINISH]
c:0020 p:---- s:0098 e:000097 CFUNC  :each
c:0019 p:0026 s:0094 e:000093 METHOD C:/hostedtoolcache/windows/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:44
c:0018 p:0013 s:0089 e:000088 METHOD C:/hostedtoolcache/windows/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/lib/bundler.rb:186
c:0017 p:0084 s:0084 e:000083 TOP    D:/a/1/s/config/application.rb:21 [FINISH]
c:0016 p:---- s:0081 e:000080 CFUNC  :require_relative
c:0015 p:0005 s:0076 e:000075 TOP    D:/a/1/s/Rakefile:4 [FINISH]
c:0014 p:---- s:0073 e:000072 CFUNC  :load
```

Upgrading the gem didn't help, so I thought something was wrong with windows-2019, so I switched to windows-2022 for comparison. There, the installation of the gems didn't work:

```
current directory:
D:/a/1/s/vendor/bundle/ruby/3.1.0/gems/websocket-driver-0.7.5/ext/websocket-driver
make DESTDIR\= sitearchdir\=./.gem.20221230-5632-xe03bj
sitelibdir\=./.gem.20221230-5632-xe03bj
generating websocket_mask-x64-mingw-ucrt.def
mingw32-make: *** No rule to make target
'/C/hostedtoolcache/windows/Ruby/3.1.3/x64/include/ruby-3.1.0/ruby.h', needed by
'websocket_mask.o'.  Stop.

make failed, exit code 2
```

`ridk version` gives information about versions and tools used by Ruby on Windows to compile native extension. I noted an interesting difference: My local environment puts out this:

```
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.3
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.3-1
  git_commit: a09714d
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev6, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.2130]
```

While the Azure DevOps environment puts out this:

```
---
ruby:
  path: C:/hostedtoolcache/windows/Ruby/3.1.3/x64
  version: 3.1.3
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev6, Built by MSYS2 project) 12.2.0
ruby_installer:
  package_version: 3.1.3-1
  git_commit: a09714d
msys2:
  path: c:\msys64
cc: gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
sh: GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.20348.1366]
```

Note that Azure DevOps appears to use a different `gcc` compared to my environment. Interesting, searching for `gcc` on my dev machine does not bring up any results.

```
PS C:\Users\Andy Pfister> where.exe gcc
INFO: Could not find files for the given pattern(s)
```

So, from this point, I assumed `ridk` tries to find the `gcc` inside the `msys` system, but for some reason, it is unable to do and falls back to the `gcc.exe` found in `PATH`, which gives those compilation errors, as it's not the correct version.

On my local machine, I have a directory `C:\Ruby31-x64\msys64\ucrt64\bin` containing a `gcc.exe`, which seem to be the expected version.

```
PS C:\Users\Andy Pfister> C:\Ruby31-x64\msys64\ucrt64\bin\gcc.exe -v
Using built-in specs.
COLLECT_GCC=C:\Ruby31-x64\msys64\ucrt64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/Ruby31-x64/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-12.2.0/configure --prefix=/ucrt64 --with-local-prefix=/ucrt64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/ucrt64/include --libexecdir=/ucrt64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/ucrt64 --with-mpfr=/ucrt64 --with-mpc=/ucrt64 --with-isl=/ucrt64 --with-pkgversion='Rev6, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Rev6, Built by MSYS2 project)
```

Azure DevOps has the msys toolchain installed at `C:\msys64`, so I expected a `gcc.exe` at `C:\msys2\ucrt64\bin\gcc.exe`. I have the following script in my `azure-pipelines.yml`.

```
Get-ChildItem C:\msys64\ucrt64
Get-ChildItem C:\msys64\ucrt64\bin
Remove-Item -Force C:\Strawberry\c\bin\gcc.exe
ruby -v
```

Resulting in the following output:

```
    Directory: C:\msys64\ucrt64


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        12/11/2022   2:06 PM                bin                                                                  
d-----        12/11/2022   2:06 PM                etc                                                                  
d-----        12/11/2022   2:06 PM                include                                                              
d-----        12/11/2022   2:06 PM                lib                                                                  
d-----        12/11/2022   2:06 PM                share                                                                
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
```

So, the missing output form the second `Get-ChildItem` indicates that the `bin` directory is empty.

To come to a conclusion, I added `ridk install 3` to my pipeline definition before running `bundle install`, which seemed to fix the issue as it installed a couple of packages. Now the `bin` directory also contains something:

```
    Directory: C:\msys64\ucrt64\bin


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
-a----         8/13/2022  12:34 PM        2328170 addr2line.exe                                                        
-a----         8/13/2022  12:34 PM        2356523 ar.exe                                                               
-a----         8/13/2022  12:34 PM        2973553 as.exe                                                               
-a----         1/12/2022  10:39 PM          27017 autopoint                                                            
-a----        12/27/2022   5:25 AM        2355225 c++.exe                                                              
-a----         8/13/2022  12:34 PM        2310250 c++filt.exe
```

Pipeline now works against both Windows 2019 and Windows 2022. So, would it be possible to provide a complete `ucrt64` directory for Ruby 3.1+?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20221214.4

### Is it regression?

no

### Expected behavior

Installing gems which need compilation of C code passes on Ruby 3.1+ without running `ridk install 3` prior.

### Actual behavior

See initial issue description.

### Repro steps

See initial issue description.

**Comment by erik-bershel** [comment]
Hi @andyundso, we'll think about it. Sounds good but may hit another users. So we'll return with answer after additional tests and investigation.

**Comment by mikhailkoliada** [comment]
@andyundso hello! We do not pre-install any toolchain for msys2 other than updating core packages (that's why your `ucrt64` dir is empty).

After, say, performing the ` C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-ucrt-x86_64-gcc"` call, all the basic toolchain is in place, generally we have no plans to pre-install anything. That's why it is up to you to choose what to install and what not.

If you have questions, feel free to reach us again, otherwise I am closing the issue now as there is nothing for us to do.

**Comment by andyundso** [comment]
Hi @mikhailkoliada 

thanks for the reply! just to note: the `mingw64` system seems to be populated, so apparently you do pre-install one toolchain.

```
    Directory: C:\msys64\mingw64\bin


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----       12/10/2022   9:13 AM            104 2to3                                                                  
-a----       12/10/2022   9:13 AM            104 2to3-3.10                                                             
-a----        2/23/2022  12:53 AM          90720 acountry.exe                                                          
-a----        8/13/2022  12:33 PM        2344717 addr2line.exe    
```
