### ISSUE TITLE
update gh CLI to latest version

### ISSUE THREAD

**Issue by Kiryuumaru** [actions/runner-images#6856]
### Description

I am using gh CLI `--previous-tag` which is not available in the current ubuntu-latest.
Please update it to latest version

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/cli/cli/releases/tag/v2.21.1

### Is it regression?

No

### Expected behavior

Successfully applied `--previous-tag`

### Actual behavior

`unknown flag: --previous-tag`

### Repro steps

Running the following command fails to get open pull request of a head branch fails:
`gh release create build.2 ./output/* --generate-notes --target dev --previous-tag build.1`

**Comment by bogdan-damian-bgd** [comment]
Hi @Kiryuumaru , it seems that `--previous-tag` is not available in the actual CLI version within the `gh release create` command options (see the [gh cli manual for the command](https://cli.github.com/manual/gh_release_create))

**Comment by Kiryuumaru** [comment]
My bad, I did not check it, I was referring to this merge https://github.com/cli/cli/issues/5963 and it seems that it is not released yet.

**Comment by wojsmol** [comment]
Hi @Kiryuumaru 
Looking at code tests in https://github.com/cli/cli/pull/6107 witch is actual implementation of https://github.com/cli/cli/issues/5963 correct parameter name is `--notes-start-tag` .

**Comment by Kiryuumaru** [comment]
Hi, I tried it and it all worked now. Thank you for your response.
