### ISSUE TITLE
Upgrade maven to 3.8.7

### ISSUE THREAD

**Issue by slaterx** [actions/runner-images#6858]
### Description

Seems maven 3.8.6 is no longer available after Apache Maven 3.8.7 was released: https://lists.apache.org/thread/vrzw0kwzmqwo7xxs01xk5ksb0kyt5hmk

![image](https://user-images.githubusercontent.com/15024405/210189632-69f43b4f-14fa-4e1a-98de-f1f9f6e6860f.png)

Without updating, we're unable to generate new ubuntu runner images using the provided packer scripts:

![image](https://user-images.githubusercontent.com/15024405/210189661-427653ff-6beb-41fd-94dc-343f7c334828.png)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not relevant, but: 

Runner Version: actions-runner-linux-x64-2.299.1

### Is it regression?

no

### Expected behavior

Packer scripts execute correctly and we can generate new ubuntu images.

### Actual behavior

Packer fails around 50% of installed tools on ubuntu.

### Repro steps

Download Runner Images repository.

```
Set-Location c:\
git clone https://github.com/actions/runner-images.git
```

Import [GenerateResourcesAndImage](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1) script from /helpers folder, and run GenerateResourcesAndImage function via Powershell.

```
Set-Location C:\runner-images

Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId {YourSubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu1804 -AzureLocation "East US"
```

**Comment by mikhailkoliada** [comment]
We will update the spec

**Comment by chrisdecker1201** [comment]
See: #6861

**Comment by mikhailkoliada** [comment]
Shall be fixed, thanks @chrisdecker1201 for submission
