### ISSUE TITLE
homebrew gcc/gfortran binaries broken on macOS runner images

### ISSUE THREAD

**Issue by jfowkes** [actions/runner-images#6866]
### Description

A while back GCC changed the way RPATH is handled on macOS as described [here](https://gcc.gnu.org/pipermail/gcc-patches/2021-November/584775.html). When we use homebrew gfortran/gcc with the latest macOS runner images to compile binaries we're seeing the following error when they are run:
```
dyld[8848]: Library not loaded: '@rpath/libgcc_s.1.1.dylib'
Referenced from: '/usr/local/Cellar/gcc@11/11.3.0/lib/gcc/11/libgcc_s.1.dylib'
Reason: tried: '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
```
so it looks like this change got backported to GCC 11.3 and somehow broke the runner-image homebrew install. I'm not seeing this on my local macOS homebrew gcc@11 install so I assume it is an issue with the runner images - note that meson are experiencing [a very similar issue](https://github.com/mesonbuild/meson/issues/10711) when installing gfortran binaries.

This started happening when the GitHub Actions macos-12 runners got updated from version [20221204.1](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20221204.1) to version [20221215.1](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20221215.1) although the same issue also appeared on the latest macos-11 runners (as they also got the newer GCC version).

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20221215.1
Failed build: https://github.com/jfowkes/pycutest/actions/runs/3748660589/jobs/6366253778

### Is it regression?

yes

### Expected behavior

Image version: 20221204.1
Successful build: https://github.com/jfowkes/pycutest/actions/runs/3730312024/jobs/6327217906

### Actual behavior

```
dyld[8848]: Library not loaded: '@rpath/libgcc_s.1.1.dylib'
Referenced from: '/usr/local/Cellar/gcc@11/11.3.0/lib/gcc/11/libgcc_s.1.dylib'
Reason: tried: '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
```

### Repro steps

Attempting to run a binary compiled with gcc/gfortran on the latest macOS runner images.

**Comment by mikhailkoliada** [comment]
Hello!

I was unable to reproduce anything

<img width="805" alt="image" src="https://user-images.githubusercontent.com/88318005/210393617-f56b4d30-59f6-49b5-9fe2-42240afba297.png">

**Comment by jfowkes** [comment]
Hello, are you able to reproduce with the yaml? Or is it to do with the gfortran symlinks I'm creating there?
https://github.com/jfowkes/pycutest/blob/master/.github/workflows/test_mac.yml

**Comment by mikhailkoliada** [comment]
Hmm, I see you manage the symlinks manually, it should never be done, i think it is the main root of your problem and you should really use `brew link`. It is not the image bug and nothing we can help you with, but if you have questions, feel free to reach us again.

**Comment by jfowkes** [comment]
Thank you for your help, it was indeed an issue with the symlinks.
