### ISSUE TITLE
Add Docker Compose "Cloud Integrations"

### ISSUE THREAD

**Issue by tkrotoff** [actions/runner-images#6876]
### Tool name

Docker Compose "Cloud Integrations"

### Tool license

Apache License v2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

53.8 MB

### Brief description of tool

Docker Compose "Cloud Integrations" is also called Compose CLI

> Makes it easy to run Docker containers and Docker Compose applications in the cloud using either:
>
> - Amazon Elastic Container Service
> - Microsoft Azure Container Instances
> - Kubernetes (Work in progress)
>
> ...using the Docker commands you already know.

When installing the official Docker distribution (called Docker Desktop) from docker.com, Compose CLI is included on all platforms (Windows, macOS, Linux).

Even the .deb package for Ubuntu on docker.com (https://docs.docker.com/desktop/install/ubuntu/) includes Compose CLI.

I spent quite some time figuring out that the `docker context` command line included in the GitHub Actions Ubuntu image is not the same as the one from docker.com

On Windows (https://github.com/actions/runner-images/blob/9ee93111224473826a8168cc6b2951f11fdba197/images/win/Windows2022-Readme.md) I don't know if Compose CLI is present (I didn't try GitHub Actions with Windows)

### URL for tool's homepage

https://github.com/docker/compose-cli

### Provide a basic test case to validate the tool's functionality.

"docker context create --help" should display:

```
Create a new context

Create docker engine context:
$ docker context create CONTEXT [flags]


Create Azure Container Instances context:
$ docker context create aci CONTEXT [flags]
(see docker context create aci --help)


Create Amazon ECS context:
$ docker context create ecs CONTEXT [flags]
(see docker context create ecs --help)

...
```

Currently it displays on Ubuntu:

```
Usage:  docker context create [OPTIONS] CONTEXT

Create a context

Docker endpoint config:

NAME                DESCRIPTION
from                Copy named context's Docker endpoint configuration
host                Docker endpoint on which to connect
ca                  Trust certs signed only by this CA
cert                Path to TLS certificate file
key                 Path to TLS key file
skip-tls-verify     Skip TLS certificate validation

Kubernetes endpoint config:

NAME                 DESCRIPTION
from                 Copy named context's Kubernetes endpoint configuration
config-file          Path to a Kubernetes config file
context-override     Overrides the context set in the kubernetes config file
namespace-override   Overrides the namespace set in the kubernetes config file

...
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

Yes

```bash
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
```

### Tool installation time in runtime

1s

**Comment by igorboskovic3** [comment]
Hi @tkrotoff, we will take a look and get back to you.

**Comment by mikhailkoliada** [comment]
Hello! Given it is just a shell script which could be installed in runtime, we would not like to add it to the image, please install in runtime.
