### ISSUE TITLE
Intuitively the UAP Test Seem Reversed

### ISSUE THREAD

**Issue by frek818** [actions/runner-images#6879]
### Description

I'm doing a build of the Window 2019 image and I am getting following error during the RunAll-Test phase. Note, that the 'Describing Window 10 SDK' step was skipped and the 'Describing Windows 11 SDK' step failed. I would think that WIndows 2019 would *not* skip the Windows 10 test but instead it would skip the Windows 11 test since Window 2019 is a lowever version with Windows 2022 and vice-versa

```
    w2019_template: Describing Windows 10 SDK
    w2019_template:   [!] Verifies 17763 SDK is installed 8ms (0ms|8ms)
    w2019_template:
    w2019_template: Describing Windows 11 SDK
    w2019_template:   [-] Verifies 22621 SDK is installed 14ms (10ms|4ms)
    w2019_template:    Expected path 'C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.22621.0\UAP.props' to exist, but it did not exist.
    w2019_template:    at "${env:ProgramFiles(x86)}\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.22621.0\UAP.props" | Should -Exist, C:\image\Tests\VisualStudio.Tests.ps1:35
    w2019_template:    at <ScriptBlock>, C:\image\Tests\VisualStudio.Tests.ps1:35
```

Should the -Skip predicate in these lines of code be reversed?

https://github.com/actions/runner-images/blob/9ee93111224473826a8168cc6b2951f11fdba197/images/win/scripts/Tests/VisualStudio.Tests.ps1#L27-L37

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Internal build. Link is not available.

### Is it regression?

Not sure

### Expected behavior

I expect the Window 10 SDK test to execute on Windows 2019 and the Window 11 SDK test to NOT execute.

### Actual behavior

The Windows 11 SDK test executes and the Window 10 SDK test is skipped.

### Repro steps

Run a build of the Windows 2019 pipeline.

**Comment by igorboskovic3** [comment]
Hi @frek818 , we will take a look.

**Comment by frek818** [comment]
The test case sort of tall the story that Windows SDK 10 is not required on  Windows 2019 but I looked at the Install-VS.ps1 script and apparently it install both Windows SDK 10 and 11 but the test only checks for Windows 11 (in the context of Windows 2019).

In addition, the test that fails for me doesn't fail in CI for the official images.

https://github.com/actions/runner-images/blob/9ee93111224473826a8168cc6b2951f11fdba197/images/win/scripts/Installers/Install-VS.ps1#L39-L61

**Comment by mikhailkoliada** [comment]
Hello! We do not observe anything like that in our daily builds https://github.visualstudio.com/runner-images/_build/results?buildId=130404&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24
