### ISSUE TITLE
Cannot find service fabric reg key windows 2019

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#6880]
### Description

fails at tools.tests.ps1 script, cannot find service fabric reg key

![image](https://user-images.githubusercontent.com/90816346/210916525-4d39e8d5-5327-435c-a8f8-bf0c578c59a8.png)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://user-images.githubusercontent.com/90816346/210916571-fb6d3f90-9bee-4c75-9cf4-141d988031cf.png)

### Is it regression?

No

### Expected behavior

proceed to build image

### Actual behavior

fails at image undeployable, so not installing configure-antivirus.ps1 script per discussion from https://github.com/actions/runner-images/discussions/6251

but fails with the above message.

fails at tools.tests.ps1 script, cannot find service fabric reg key

### Repro steps

1. remove configure-antivirus.ps1 from the windows2019 json file.
2. run the build.
3. will fail with above.

**Comment by igorboskovic3** [comment]
Hi @vamshisiram , we will take a look.

**Comment by angaar96** [comment]
Can confirm, having the same problem on builds of Windows 2019 as well as 2022.

**Comment by vamshisiram** [comment]
I know the PR is not merged/approved yet, but i tried making those changes from the PR to the repo i cloned to my PC and it still fails, with the message below : 

![image](https://user-images.githubusercontent.com/90816346/211086794-6f107617-5fa4-4c32-aeb1-8e39a31b487c.png)

hoping that the PR once reviewed and merged will help clear this issue. 

Tagging @igorboskovic3 @Alexey-Ayupov  for visibility into this new error i saw with the code from the PR above.

**Comment by mikhailkoliada** [comment]
Should be all set now, please sync your main again.

**Comment by vamshisiram** [comment]
windows 2022 failed as well with same message... 
![image](https://user-images.githubusercontent.com/90816346/211113837-1f7199b4-7219-4634-b438-302103bde9cc.png)


i will sync the main again and try, hoping some other changes were made to the repo other than what was in the PR by @Alexey-Ayupov . Because manually making those changes did not work.

**Comment by vamshisiram** [comment]
> Can confirm, having the same problem on builds of Windows 2019 as well as 2022.

@angaar96 If you run into the above issue with setting execution policy like me, i fixed it by modifying the "Install-ServiceFabricSDK.ps1" script lines 14 and 15 to the following:

![image](https://user-images.githubusercontent.com/90816346/211166226-59e91af4-d540-47a7-b566-00cccf04d06e.png)

I wanted to share this with you, as you were having the same issue as me.
