### ISSUE TITLE
docker builds fail on ubuntu 20.04 agents, but succeed on 18.04 agents.

### ISSUE THREAD

**Issue by BrianMouncer** [actions/runner-images#6887]
### Description

We build a 20.04 ubunto docker image on our current system, and it works file when we use Ubuntu 18.04 hosted agents.
I am trying to move our build system to use the new 20.04 hosted agent images, in preparation for 18.04 images going away in April.

I have yet to root cause the reason for the failure, but I am starting to think it is something to do with the agent image, as I have gutted our docker file so it is not doing anything other than making a copy of the base 20.04 ubuntu image and creating some empty folders in it (I've commented out installing our SDK and commandline tools), and it still fails using the new agents.

looking at the list of installed tools, I see that the 20.04 agent has an older version of the Docker Client and Server, and the 18.04 agent has a newer version.  Is there a reason for this, and could that be the reason for the failures only when using the 20.04 agent images?

20.04 agents:
-    Docker-Moby Client 20.10.**21**+azure-2
-    Docker-Moby Server 20.10.**21**+azure-2

18.04 agents:
 -   Docker-Moby Client 20.10.**22**+azure-1
 -   Docker-Moby Server 20.10.**22**+azure-1

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

all ubuntu 20.04 agents.

### Is it regression?

ubuntu 18.04 works, 20.04 does not

### Expected behavior

any docker file I can build on 18.04 build agents should also build on 20.04 builds agents.

### Actual behavior

18.04 build agents work, but 20.04 builds agents fail to compile very basic 20.04 docker file.

### Repro steps

compile this docker file on both 18.04 and 20.04 build agents.

```

# --- BUILD image
FROM mcr.microsoft.com/mirror/docker/library/ubuntu:20.04 as build
ARG SPX_Version=latest

RUN apt-get update && \
    apt-get install --yes \
        apt-transport-https \
        unzip \
        wget

# code removed that that created some working folders and installs Speech SDK and CLI.
# and docker file still fails on 20.04 build agents...

# --- OUTPUT image
FROM mcr.microsoft.com/mirror/docker/library/ubuntu:20.04 as output
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends libglib2.0 &&\
    apt-get install -y --no-install-recommends libglib2.0-cil &&\
    apt-get install -y --no-install-recommends libglib2.0-cil-dev &&\
    apt-get install -y --no-install-recommends \
        python3 python3-pip python3-dev \
        libgirepository1.0 libasound2 \
        libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly python3-gst-1.0 \
        apt-transport-https \
        unzip \
        wget

RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install --yes dotnet-runtime-6.0 azure-cli

```

**Comment by BrianMouncer** [comment]
Before you ask, this is the error returned while building the docker image.
It is failing on a normal APT install, and I don't really understand how/why checking the ado build agent host from 18.04 to 20.04 would cause an APT install inside the 20.04 docker image to fail like this???


```

Setting up libglib2.0-cil (2.12.40-3) ...

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
   --- End of inner exception stack trace ---
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x0000f] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.IO.File.Exists (System.String path) [0x00058] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at Mono.Tools.Driver.LoadConfig (System.Boolean quiet) [0x00031] in <c1f3f44c980c4c748aff61945c8f618f>:0 
  at Mono.Tools.Driver.Main (System.String[] args) [0x00347] in <c1f3f44c980c4c748aff61945c8f618f>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
   --- End of inner exception stack trace ---


```

**Comment by ddobranic** [comment]
Hello @BrianMouncer, we will investigate. thank you!

**Comment by ddobranic** [comment]
@BrianMouncer we will release new Ubuntu 20.04 image this week with updated Docker-Moby packages(same version as on Ubuntu 18.04)

**Comment by ddobranic** [comment]
@BrianMouncer looks like it was some temporary failure, please check again.

**Comment by ddobranic** [comment]
@BrianMouncer I will close the issue. If you have any other questions or concerns please feel free to reopen.
