### ISSUE TITLE
There is an error during WDK.vsix installation (windows 2022)

### ISSUE THREAD

**Issue by brgsstm** [actions/runner-images#6899]
### Description

windows2022 build failing consistently

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I'm not running the CI pipeline published in this repo as I have to make modifications to use managed disk and private IPs (to meet Azure Policy requirements).  Commit details below.

Date: Mon Jan 9 20:10:45 2023 +0100; Commit: e6fcf60b8e6c0f80a065327eaefe836881c28b68

### Is it regression?

no

### Expected behavior

Successful build

### Actual behavior

    vhd: Starting Install WDK.vsix...
    vhd: There is an error during WDK.vsix installation
    vhd: Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
    vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:302 char:24
    vhd: + ...  $process = Start-Process -FilePath "${installPath}\Microsoft Visual  ...
    vhd: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vhd:     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    vhd:     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
    vhd:
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

### Repro steps

Build windows2022

**Comment by ddobranic** [comment]
Hello, @brgsstm we will take a look. thank you!

**Comment by fajterini** [comment]
Have same issue stating yesterday.

**Comment by markatky46** [comment]
Also having same issue

**Comment by PapaDers** [comment]
> I am also seeing this error. It is intermittent for me. I had two builds fail at this step in a row; then, two got past it. If I get past this part which seems 50/50, I hit the Az test error listed in the other bug report. Happy to provide any information that might help.
> 
> ```powershell
>     vhd: Running tests from 'C:\image\Tests\Wix.Tests.ps1'
>     vhd: Describing Wix
>     vhd:   [+] Wix Toolset version from registry 690ms (491ms|199ms)
>     vhd: Tests completed in 4.48s
>     vhd: Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
> ==> vhd: Provisioning with powershell script: C:\a\1\s\images\win/scripts/Installers/Install-WDK.ps1
>     vhd: Downloading wdksetup.exe...
>     vhd: Downloading package from: https://go.microsoft.com/fwlink/?linkid=2196230 to path C:\Users\packer\AppData\Local\Temp\wdksetup.exe .
>     vhd: Package downloaded successfully in 0.56 seconds
>     vhd: Starting Install wdksetup.exe...
>     vhd: Installation successful in 159.13 seconds
>     vhd: Starting Install WDK.vsix...
>     vhd: Unsuccessful exit code returned by the installation process: -532462766.
> ==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
> ```

This issue affects more than the WDK.vsix phase. I am also getting errors past this step on the Install-Vsix.ps1 script.

```
    vhd: Starting Install wdksetup.exe...
    vhd: Installation successful in 92.82 seconds
    vhd: Starting Install WDK.vsix...
    vhd: WDK.vsix installed successfully
    vhd: Pester v5.4.0
    vhd:
    vhd: Starting discovery in 1 files.
    vhd: Discovery found 2 tests in 848ms.
    vhd: Running tests.
    vhd:
    vhd: Running tests from 'C:\image\Tests\WDK.Tests.ps1'
    vhd: Describing WDK
    vhd:   [+] WDK exists 1.29s (1.05s|233ms)
    vhd:   [+] Windows Driver Kit VSIX extension 106ms (104ms|1ms)
    vhd: Tests completed in 4.93s
    vhd: Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 0
==> vhd: Provisioning with powershell script: C:\a\2\s\images\win/scripts/Installers/Install-Vsix.ps1
    vhd: Downloading package from: https://visualstudioclient.gallerycdn.vsassets.io/extensions/visualstudioclient/microsoftvisualstudio2022installerprojects/2.0.0/1641503017035/InstallerProjects.vsix to path C:\Users\packer\AppData\Local\Temp\InstallerProjects.vsix .
    vhd: Package downloaded successfully in 0.13 seconds
    vhd: Starting Install InstallerProjects.vsix...
    vhd: InstallerProjects.vsix installed successfully
    vhd: Downloading package from: https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2022extension/1.0.0.22/1668223914320/Votive2022.vsix to path C:\Users\packer\AppData\Local\Temp\Votive2022.vsix .
    vhd: Package downloaded successfully in 0.06 seconds
    vhd: Starting Install Votive2022.vsix...
    vhd: Votive2022.vsix installed successfully
    vhd: Downloading package from: https://download.microsoft.com/download/b/b/5/bb57be7e-ae72-4fc0-b528-d0ec224997bd/Microsoft.DataTools.ReportingServices.vsix to path C:\Users\packer\AppData\Local\Temp\Microsoft.DataTools.ReportingServices.vsix .
    vhd: Package downloaded successfully in 2.34 seconds
    vhd: Starting Install Microsoft.DataTools.ReportingServices.vsix...
    vhd: Microsoft.DataTools.ReportingServices.vsix installed successfully
    vhd: Package downloaded successfully in 4.94 seconds
    vhd: Starting Install Microsoft.DataTools.AnalysisServices.vsix...
    vhd: Unsuccessful exit code returned by the installation process: -532462766.
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
```

**Comment by AmnaO** [comment]
I'm getting the same error. its also happens about 50% of time. got the same error when we looked it up all we got was Unknown software exception (0xe0434352).

**Comment by PapaDers** [comment]
I merged this change into my repository and am running a build to test. Thank you! 💯

I'll update this thread if this issue is still open when my build finishes.

**Comment by PapaDers** [comment]
Just an update. This fix worked flawlessly for me! Thank you, @Alexey-Ayupov!

**Comment by mikhailkoliada** [comment]
we will test that change more and improve if needed. Close for now. Thanks for the patience!
