### ISSUE TITLE
Python Version Not Listed In Image Update 20230109.1

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/runner-images#6903]
### Description

Previous Ubuntu releases include the versions of Python they ship with in the release notes.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230109.1

### Is it regression?

20221220.1

### Expected behavior

I expected the release notes to indicate the pre-installed versions of Python.

### Actual behavior

The text "Python" does not appear in the release notes.

### Repro steps

1. Go to https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230109.1 or https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230109.1.
2. Attempt to determine the available versions of Python.

**Comment by bogdan-damian-bgd** [comment]
Hey @Kurt-von-Laven, thanks for reporting, we'll take a look soon.

**Comment by mikhailkoliada** [comment]
Release page only contains a diff, not a full list, so python should not be listed as it had no changes.
