### ISSUE TITLE
The license for Visual Studio has expired.

### ISSUE THREAD

**Issue by mxschmitt** [actions/runner-images#6904]
### Description

Can’t compile using VS, it says the license has expired. Happened before but got fixed again, now it’s happening since 2-3h.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

 Version: 20221204.3

### Is it regression?

Yes

### Expected behavior

Works

### Actual behavior

 Microsoft Visual Studio 2022 Version 17.4.2
Copyright (C) Microsoft Corp. All rights reserved.

The license for Visual Studio has expired.

The evaluation period for this product has ended.

### Repro steps

Build something with `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com`

**Comment by mikhailkoliada** [comment]
Thanks for the report! We will fix it soon

**Comment by mikhailkoliada** [comment]
Hello! The plan is to rollout a fix the next Monday (16.01.23)

**Comment by yury-s** [comment]
@mikhailkoliada To my understanding this is a critical issue as it basically means no windows build for the next 4 days for us because of the problem with larger runners. Can you expedite roll out of the fix? One of the reason we switched from self-hosted runners to the larger runners for our builds was to minimize build process disruptions.

**Comment by mikhailkoliada** [comment]
@yury-s Hello! @mxschmitt contacted me, i kicked a yearly build off, but update will take few hours.

**Comment by mikhailkoliada** [comment]
@mxschmitt @yury-s runners for win22 have been updated, let us know if it fixes your issue.

**Comment by mxschmitt** [comment]
Works again, thanks!
