### ISSUE TITLE
Connection timing out to azure repositary

### ISSUE THREAD

**Issue by mohamed-shahid-afrid** [actions/runner-images#6909]
### Description

When downloading few of the dependencies from Azure, getting the below error.
Err:1 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libhiredis0.14 amd64 0.14.0-6
  Could not connect to azure.archive.ubuntu.com:80 (20.106.104.242), connection timed out

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.299.1
 https://github.com/mohamed-shahid-afrid/ODIM/actions/runs/3908839713/jobs/6679837385

### Is it regression?

https://github.com/mohamed-shahid-afrid/ODIM/actions/runs/3901619852

### Expected behavior

the job to sucess while downloading all the dependencies 

### Actual behavior

not able to connect to azzure repositories

### Repro steps

just re-run the failed jobs

**Comment by nulano** [comment]
Also mentioned in https://github.com/actions/runner-images/issues/6486#issuecomment-1334201417 and https://github.com/actions/runner-images/issues/6677#issuecomment-1381371350

**Comment by mikhailkoliada** [comment]
Hello! We handed over that to azure support, but we do not control the mirror, network hiccups happen and nothing we can do about it :(

**Comment by frenck** [comment]
@mikhailkoliada I have to disagree a bit on that, and I, therefore, think this issue was closed prematurely. 

GitHub could provide mitigation in routing, deploy runnings that default to a working mirror, and similar solutions like that.

I think it is too easy to say: Not our problem.

(Especially considering GitHub & Azure both owned by the same parent company).

@ Home Assistant this is causing serious problems with the intense flow of PRs we are currently receiving.

../Frenck

**Comment by frenck** [comment]
@ddobranic as per above, I think removing the triage label isn't appropriate.

**Comment by frenck** [comment]
@mikhailkoliada @ddobranic Please advise. Do you want me to open an new issue, that focusses on a solution/report from a GitHub perspective?

**Comment by salman01zp** [comment]
we are facing same issue.

**Comment by agdavydov81** [comment]
A few hours ago I had two jobs with the same problem.
Now one job is working fine with no effort on my part.
But the second job (with cross compilation) still can't fetch the required packages.
Looks like the only thing I can do is wait.

**Comment by levrik** [comment]
@mikhailkoliada Actually I'm seeing the same issue from inside a `docker build` with the official `archive.ubuntu.com`.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/9491603/212317494-6e155f06-c95e-41ea-8539-197a3063cc29.png">

I wonder what's the difference between the `azure.archive.` and this one.

**Comment by agdavydov81** [comment]
My jobs started working!
Hooray!

**Comment by strasdat** [comment]
I can confirm that github enterprise customers and corresponding github.com runners are affected as well. 

My assumption is that it is not runner specific (rate-limited by github) but rather a pure upstream problem at the azure org of microsoft.

I have seen two different type of causes in our particular instances:

 - Manually calling: "sudo apt-get -qq update"
 - Running the the ccache action "- uses: hendrikmuhs/ccache-action@v1"

(If you are a github employee, check out my support ticket #1964791 for more context.)

**Comment by osievert-gpfw** [comment]
@mikhailkoliada here is suggestion for how github could more easily help customers with these kinds of problems: without deploying a new image, github could release a fixup action that would make it easier for all affected customers to add to their jobs temporarily. That could be done much faster than deploying a new image, and would make it easier for all customers to "get by" until the azure problem is resolved. Much easier for us to add a new step to our jobs temporarily than for every one of github's affected customers to remember how to modify the sources.list file.
