### ISSUE TITLE
Broken packages with newest Ubuntu 20.04 image

### ISSUE THREAD

**Issue by tiborbuzasi** [actions/runner-images#6911]
### Description

With the newest (20230109.1) image version of Ubuntu 20.04 our GitHub Action process breaks on setting up the PHP environment (with nanasess/setup-php@v3.0.6). We also tried using newer versions (3.0.10 and 3.3.2) of nanasess/setup-php, but we always got the same result.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20230109.1

See build log at "Actual behaviour" section.

### Is it regression?

20221212.2

### Expected behavior

Packages are installed without a problem.

### Actual behavior

Setup of PHP environment fails because of broken packages. See log:
[3_Setup PHP environment.txt](https://github.com/actions/runner-images/files/10409815/3_Setup.PHP.environment.txt)

### Repro steps

1. Use this file as your workflow definition .yml file (Sorry, I had to rename it as upload of .yml is not allowed)
[php.txt](https://github.com/actions/runner-images/files/10409776/php.txt)
2. Run workflow and see step "Setup PHP environment" fail.

**Comment by ddobranic** [comment]
Hello, @tiborbuzasi! We will investigate, thank you

**Comment by ddobranic** [comment]
@tiborbuzasi fix for php 7.4 is [committed](https://github.com/nanasess/setup-php/commit/6065757f0154a2c6ed4db3d3b92ba9dfd0843f61) yesterday in nanasess/setup-php repository

**Comment by tiborbuzasi** [comment]
Thanks for the notice!

Unfortunately, we get the same result with the fix:
[3_Setup PHP environment.txt](https://github.com/actions/runner-images/files/10446688/3_Setup.PHP.environment.txt)

Is there a way to use the previous release of the ubuntu-20.04 image?

**Comment by ddobranic** [comment]
> Is there a way to use the previous release of the ubuntu-20.04 image?

Unfortunately, no

> Unfortunately, we get the same result with the fix

New image release is on the way for this week.

**Comment by ddobranic** [comment]
Hello @tiborbuzasi, I can confirm that everything is fine now on our latest image  
[php-7.4-setup.txt](https://github.com/actions/runner-images/files/10464146/php-7.4-setup.txt)

Please feel free to reopen issue if you have any other question or concerns.
