### ISSUE TITLE
`make` is missing in the ubuntu 22.04 images

### ISSUE THREAD

**Issue by FrederikNS** [actions/runner-images#6912]
### Description

The ubuntu-20.04 images included `make` out of the box. The new ubuntu-22.04 images do not.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

v2.299.1-ubuntu-22.04-acbce4b

### Is it regression?

v2.299.1-ubuntu-20.04-acbce4b

### Expected behavior

I expected make to be present and work, like this:

```
$ make
make: *** No targets specified and no makefile found.  Stop.
```

### Actual behavior

`make` isn't present:
```
$ make
/bin/bash: line 1: make: command not found
```

### Repro steps

1. Execute `make` in the runner.

**Comment by mikhailkoliada** [comment]
Hello!

<img width="776" alt="image" src="https://user-images.githubusercontent.com/88318005/212296023-4cf12ae3-5c2d-4a73-9683-63addb147cb8.png">

It is definitely in place, please check your $PATH settings :)
