### ISSUE TITLE
Safari browser WebGL / WebGL 2.0 on macos-latest

### ISSUE THREAD

**Issue by GrigoriyKalita** [actions/runner-images#6924]
### Description

WebGL / WebGL 2.0 does not work for the Safari browser on the macos-lates (macOS 12) for some reason. 

I tried it out on deprecated macOS runner (macos-10.15) it works perfectly fine.

By default it also working on the real Safari browser (desktop one) (version 16.1).

It seems like unexpected behaviour or it was turned off on purpose.

(we used it for testing purposes)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.300.2'

### Is it regression?

macos-10.15

### Expected behavior

WebGL and WebGL 2.0 are turned on / available by default

### Actual behavior

WebGL and WebGL 2.0 classes exist, but not available for usage

### Repro steps

1. Create instance of the Safari browser (we do it via selenium).
2. Execute following function in the browser:

function detectWebGL()
{
    // Check for the WebGL rendering context
    if ( !! window.WebGLRenderingContext) {
        var canvas = document.createElement("canvas"),
            names = ["webgl", "experimental-webgl", "moz-webgl", "webkit-3d"],
            context = false;
        for (var i in names) {
            try {
                context = canvas.getContext(names[i]);
                if (context && typeof context.getParameter === "function") {
                    // WebGL is enabled.
                    return 1;
                }
            } catch (e) {}
        }
        // WebGL is supported, but disabled.
        return 0;
    }
    // WebGL not supported.
    return -1;
};

3. Check output of detectWebGL function. For macOS 12 (macOS-latest) it is "0", for the macos-10.15 it is "1". 
That's correlate with actual e2e tests, our app do not work with macOS-latest and works fine with macos-10.15.

**Comment by erik-bershel** [comment]
Hi @GrigoriyKalita, we'll take a look soon.

**Comment by mikhailkoliada** [comment]
HI @GrigoriyKalita,

I Have just checked safari developer extensions on macos-12 vms, everything seems to be in order and webgl-2.0 is enabled.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/88318005/212803820-09bc0220-d53a-4e6e-9487-4735287f39cc.png">

We do not modify Develop menu anyhow but enabling the `Allow Remote Automation` option there via plist

**Comment by GrigoriyKalita** [comment]
@mikhailkoliada thanks for checking it up!

That's really strange... could you please copy and paste this script into the browser console?

```
function detectWebGL()
{
// Check for the WebGL rendering context
if ( !! window.WebGLRenderingContext) {
var canvas = document.createElement("canvas"),
names = ["webgl", "experimental-webgl", "moz-webgl", "webkit-3d"],
context = false;
for (var i in names) {
try {
context = canvas.getContext(names[i]);
if (context && typeof context.getParameter === "function") {
// WebGL is enabled.
return 1;
}
} catch (e) {}
}
// WebGL is supported, but disabled.
return 0;
}
// WebGL not supported.
return -1;
};
detectWebGL()

```

Just to be sure that it will not return 0, then

**Comment by vpolikarpov-akvelon** [comment]
Hi, @GrigoriyKalita.

We have investigated this issue and came to a conclusion that it's impossible to use WebGL API on macOS runners due to hardware limitations. Both Firefox and Safari utilize system-native Apple Software Renderer that doesn't work in runners environment.

You can still run your code in Chrome (or any Chromium-based browser) because it has custom built-in renderer. You can also utilize other operation systems.

Sorry for the inconvenience.

**Comment by firashamila33** [comment]
so this means that for example Maobox implementations cannot be tested on Github Macos runners ?

is the solution to just have self hosted runners ? as you wont support this in the future ?

**Comment by vpolikarpov-akvelon** [comment]
Hi @firashamila33. Both versions of WebGL work on MacOS runners in Google Chrome and Chromium based browsers.
