### ISSUE TITLE
ubuntu-latest: Failing to run NET6 app due to missing Microsoft.NETCore.App

### ISSUE THREAD

**Issue by gregory-paidis-sonarsource** [actions/runner-images#6925]
### Description

After the [latest](https://github.com/actions/runner-images/commit/c82cd6704bacd9429d4e037d6554e74375842f51) update in ubuntu-latest we started having issues in our Azure pipeline while running a NET6 app with the error:

```
/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5):
 error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.
```

Executing `dotnet --list-sdks` inside the VM shows:
```
6.0.404 [/usr/share/dotnet/sdk]
7.0.101 [/usr/share/dotnet/sdk]
```

Executing `dotnet --info` inside the VM shows:

```
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/039e26df-14cb-44e1-bd8d-5aa83db5ddf9.sh
.NET SDK (reflecting any global.json):
 Version:   6.0.404
 Commit:    be4f3ec411

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.404/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.404 [/usr/share/dotnet/sdk]
  7.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /home/vsts/work/1/s/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

This seems oddly similar to [this ticket](https://github.com/actions/runner-images/issues/5792) that a teammate of mine made some time ago.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: ubuntu-22.04
Version: 20230109.1
```

### Is it regression?

Yes, it worked before commit c82cd6704bacd9429d4e037d6554e74375842f51

### Expected behavior

Run the App without a runtime error.

### Actual behavior

Having an error:

```
/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5):
 error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.
```

### Repro steps

Could not reproduce this locally.

Changing the image to [ubuntu-18.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-Readme.md) seems to solve the issue on the pipeline, at least.

**Comment by erik-bershel** [comment]
Hey @gregory-paidis-sonarsource!
I'm not sure it is the same situation but according to my little investigation the same method will work for you here. You can use [setup-dotnet](https://github.com/actions/setup-dotnet) task or wait untill new image rollout.
More info about reasons you may find [here](https://github.com/dotnet/sdk/issues/28947).

**Comment by gregory-paidis-sonarsource** [comment]
yeah, @erik-bershel , I installed the latest `.NET 7 Sdk` to latest and got the same issue on Windows as well.
I cannot reproduce it, but if I find a way to, I will open an issue to the .NET repo.

Just leaving this here, to let you know I do not think it is platform(`ubuntu`)-specific.

**Comment by erik-bershel** [comment]
@gregory-paidis-sonarsource yes, it is not a really platform specific. It is more about compability of .Net platforms. As it was mentioned in issue sometimes it happens when you installing both of .Net 7 and 6 on the same machine. We'll see how next build would help you. And in case we got new compability bug, not the same I described, we'll think about another possibility to help you with broaken build. It works right now with old Ubuntu image because of process of retirement - no updates, no preinstalled comability issues.

**Comment by erik-bershel** [comment]
Hey @gregory-paidis-sonarsource!
New Ubuntu images shiped. May I ask you to try it again?

**Comment by erik-bershel** [comment]
Hi @gregory-paidis-sonarsource, any updates? How it works right now for you?

**Comment by gregory-paidis-sonarsource** [comment]
hey @erik-bershel , it works. Could you share, at a high level, what changed?

Thanks again for the fix!

**Comment by erik-bershel** [comment]
@gregory-paidis-sonarsource glad to see it. Main change that supposed been fix issue and did it is .NET Core SDK: 7.0.101 -> 7.0.102
