### ISSUE TITLE
androidtests failed windows 2022 and windows 2019 fails with image state undeployable.

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#6929]
### Description
**the build fails with the following error for windows 2022 and windows 2019, both.**

 but it did not match.
    vhd:     at "$installedPackages" | Should -Match "ndk;$ndkPackage", C:\image\Tests\Android.Tests.ps1:97
    vhd:     at <ScriptBlock>, C:\image\Tests\Android.Tests.ps1:97
    vhd: Tests completed in 19.21s
    vhd: Tests Passed: 34, Failed: 1, Skipped: 0 NotRun: 0
    vhd:
    vhd: Containers            : {[-] C:\image\Tests\Android.Tests.ps1}
    vhd: Result                : Failed
    vhd: FailedCount           : 1
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 34
    vhd: SkippedCount          : 0
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 35
    vhd: Duration              : 00:00:19.2144482
    vhd: Executed              : True
    vhd: ExecutedAt            : 1/17/2023 9:58:33 PM
    vhd: Version               : 5.4.0
    vhd: PSVersion             : 5.1.20348.1366
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:04.1323996
    vhd: UserDuration          : 00:00:11.7841906
    vhd: FrameworkDuration     : 00:00:03.2978580
    vhd: Failed                : {[-] NDK 25 is installed}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: Skipped               : {}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

**The images for windows 2022 and 2019 both fail with the following error** 

 but it did not match.
    vhd:     at "$installedPackages" | Should -Match "ndk;$ndkPackage", C:\image\Tests\Android.Tests.ps1:97
    vhd:     at <ScriptBlock>, C:\image\Tests\Android.Tests.ps1:97
    vhd: Tests completed in 19.21s
    vhd: Tests Passed: 34, Failed: 1, Skipped: 0 NotRun: 0
    vhd:
    vhd: Containers            : {[-] C:\image\Tests\Android.Tests.ps1}
    vhd: Result                : Failed
    vhd: FailedCount           : 1
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 34
    vhd: SkippedCount          : 0
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 35
    vhd: Duration              : 00:00:19.2144482
    vhd: Executed              : True
    vhd: ExecutedAt            : 1/17/2023 9:58:33 PM
    vhd: Version               : 5.4.0
    vhd: PSVersion             : 5.1.20348.1366
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:04.1323996
    vhd: UserDuration          : 00:00:11.7841906
    vhd: FrameworkDuration     : 00:00:03.2978580
    vhd: Failed                : {[-] NDK 25 is installed}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: Skipped               : {}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed

### Is it regression?

no

### Expected behavior

build to move forward, but fails with andorid tests.

retrying did not pass, fails with defender error on a retry.

### Actual behavior

 but it did not match.
    vhd:     at "$installedPackages" | Should -Match "ndk;$ndkPackage", C:\image\Tests\Android.Tests.ps1:97
    vhd:     at <ScriptBlock>, C:\image\Tests\Android.Tests.ps1:97
    vhd: Tests completed in 19.21s
    vhd: Tests Passed: 34, Failed: 1, Skipped: 0 NotRun: 0
    vhd:
    vhd: Containers            : {[-] C:\image\Tests\Android.Tests.ps1}
    vhd: Result                : Failed
    vhd: FailedCount           : 1
    vhd: FailedBlocksCount     : 0
    vhd: FailedContainersCount : 0
    vhd: PassedCount           : 34
    vhd: SkippedCount          : 0
    vhd: NotRunCount           : 0
    vhd: TotalCount            : 35
    vhd: Duration              : 00:00:19.2144482
    vhd: Executed              : True
    vhd: ExecutedAt            : 1/17/2023 9:58:33 PM
    vhd: Version               : 5.4.0
    vhd: PSVersion             : 5.1.20348.1366
    vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    vhd: Plugins               :
    vhd: PluginConfiguration   :
    vhd: PluginData            :
    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:04.1323996
    vhd: UserDuration          : 00:00:11.7841906
    vhd: FrameworkDuration     : 00:00:03.2978580
    vhd: Failed                : {[-] NDK 25 is installed}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: Skipped               : {}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed

### Repro steps

run the build as is and it will fail with the above.,

**Comment by vamshisiram** [comment]
it failed for 2022, 2019 is still going on, will know in about six horus, if it does not show the undeployable message again. i will update this thread.

**Comment by vamshisiram** [comment]
and i am now getting image state undeployable message with windows 2019.

**Comment by vamshisiram** [comment]
@Alexey-Ayupov @mikhailkoliada @igorboskovic3 

can you please look into these two issues and let me know what the next steps would be to resolve?

I have been trying for the past five weeks to get the builds going, but has been unsuccessful for windows, we are in a dead zone and cannot move forward, please help. do not convert this into a discussion please.

**Comment by erik-bershel** [comment]
Hey @vamshisiram
Please, update body of the issue in "description" and "image version and build link parts" for better understanding what was done by you.
For right now I can say only that Android NDK 25 was installed normally last few times. Screenshot from our last image generation for example:
<img width="999" alt="Screenshot 2023-01-18 at 09 48 35" src="https://user-images.githubusercontent.com/110455084/213126651-14376447-0a08-4836-aad5-7a5299c05607.png">

**Comment by erik-bershel** [comment]
@vamshisiram but it is not an issue for our repo. 

Image generation process is not currently experiencing problems with Android NDK 25 package both for Windows 2019 and Windows 2022. Just the same moment we are in process of shipping new Windows 2019 image as you can see here: https://github.com/actions/runner-images/pull/6932. And last one Windows 2022 image was generated about one hour before:
<img width="849" alt="Screenshot 2023-01-18 at 16 22 32" src="https://user-images.githubusercontent.com/110455084/213211875-e545b8a0-96e3-45ff-855b-bd041a1eb479.png">


Please update your fork (as I see you have outdated version in your repo) and read again [guide](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md)

I forced to close that issue because it is not reproducable and not connected with any bugs in source code. But you may continue ping us here if you have more questions about particular topic. And feel free to open issues in case you have another concerns.

**Comment by vamshisiram** [comment]
@erik-bershel  @Alexey-Ayupov  @mikhailkoliada 

I grabbed the latest commit by alexey and it still fails with image state undeployable.... no errors nothing.... please help.

![image](https://user-images.githubusercontent.com/90816346/213337673-91ce3bf6-3f5c-4522-a8f0-2535d8e8f8d1.png)

**Comment by erik-bershel** [comment]
Hey @vamshisiram!
Please provide full log from azure about an operation. It is advisable to remove personal data from the log. I'll take a look on it a bit later. And if you can then run please pipeline again just to be sure it's not a new transistent issue.
