### ISSUE TITLE
Add dotnet workload maui

### ISSUE THREAD

**Issue by pknupper** [actions/runner-images#6936]
### Tool name

dotnet workload maui

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

We are going to be build .NET MAUI applications. Our build step to install all required workloads takes several minutes:

```
dotnet nuget locals all --clear 
dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
```

In order to avoid this repetitive steps we would like to have these workloads pre-installed on windows agent.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
dotnet nuget locals all --clear 
dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
```

### Tool installation time in runtime

8min+ on windows agents

**Comment by erik-bershel** [comment]
In continuation of this discussion: https://github.com/actions/runner-images/issues/5720
@timheuer could you please assist again?

Currently Windows 2022 image with .NET 7 SDK has that list of preinstalled workloads:
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.52/7.0.100         VS 17.4.33205.214  
maui-maccatalyst           7.0.52/7.0.100         VS 17.4.33205.214  
maccatalyst                16.1.1477/7.0.100      VS 17.4.33205.214  
maui-ios                   7.0.52/7.0.100         VS 17.4.305.214  
ios                        16.1.1477/7.0.100      VS 17.4.205.214  
maui-android               7.0.52/7.0.100         VS 17.4.33205.214  
android                    33.0.4/7.0.100         VS 17.4.33205.214  
wasm-tools                 7.0.1/7.0.100          VS 17.4.33205.214
```
But what do you think about .NET 6 SDK workloads both for Windows 2019 and Windows 2022?

cc @mikhailkoliada

**Comment by mikhailkoliada** [comment]
As far As I understand maui has a number of components, but given that we do not see high demand of them, we would not like to pre-install them for the time being, but it may change in the future, please continue installing all the needed components in runtime

**Comment by thomasbach-dk** [comment]
> Thanks on your reply. I was checking again and tried to build my MAUI project on Windows-2022 image without installing MAUI workload manually. Unfortunately restoring the project is failing with following error message:
> 
> ```
> Determining projects to restore...
> C:\hostedtoolcache\windows\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-tizen [D:\a\1\s\XXX\xxx.csproj::TargetFramework=net7.0]
> C:\hostedtoolcache\windows\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [D:\a\1\s\XXX\xxx.csproj::TargetFramework=net7.0]
> ```
> 
> That´s a snippet of my pipeline without the manual installation step:
> 
> ```
> - stage: Build
>   jobs:
>   - job: BuildAndroid
>     displayName: Build Android App
>     pool:
>       vmImage: 'windows-2022'
>       demands:
>       - MSBuild
>       
>     steps:
>     - task: UseDotNet@2
>       displayName: .NET Version
>       inputs:
>         packageType: 'sdk'
>         version: '$(DotNetVersion)'
>     
>     - task: Bash@3
>       displayName: Restore nuget
>       inputs:
>         targetType: 'inline'
>         script: |
>           cd xxx
>           dotnet restore $(Project)
>   
>     - task: Bash@3
>       displayName: Build Android App
>       inputs:
>         targetType: 'inline'
>         script: |
>           cd xxx
>           dotnet publish $(Project) -f net7.0-android -c $(BuildConfiguration)
> ```
> 
> Parts of my .csproj:
> 
> ```
> <PropertyGroup>
> 		<TargetFrameworks>net7.0;net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
> 		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
> 		
> 		
>     <OutputType Condition="'$(TargetFramework)' != 'net7.0'">Exe</OutputType>
> 		<RootNamespace>xxx</RootNamespace>
> 		<UseMaui>true</UseMaui>
> 		<SingleProject>true</SingleProject>
> 		<ImplicitUsings>enable</ImplicitUsings>
> 
> 		
> 		<ApplicationTitle>xxx</ApplicationTitle>
> 
> 		
> 		<ApplicationId>xxx</ApplicationId>
> 		<ApplicationIdGuid>xxx</ApplicationIdGuid>
> 
> 		
> 		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
> 		<ApplicationVersion>1</ApplicationVersion>
> 
> 		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
> 		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
> 		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
> 		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
> 		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
> 		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
> 	</PropertyGroup>
> ```

I guess it’s because you are supporting Tizen. I’m currently restoring a .NET MAUI project supporting iOS and Android on windows-latest without installing MAUI and without any issues.

**Comment by Miniontoby** [comment]
> As far As I understand maui has a number of components, but given that we do not see high demand of them, we would not like to pre-install them for the time being, but it may change in the future, please continue installing all the needed components in runtime

Hey,
Running `dotnet workload install maui` takes 1 minute on mac, which I would love to save as much as I can as macOS is billed 10 times more than windows or linux.

On Windows the same command takes 2 minute-ish...

I dunno how I would do with runner caches, so uhhh yeah it would be nice if there could come a dedicated image instead
