### ISSUE TITLE
How to re-install docker after uninstalling it

### ISSUE THREAD

**Issue by ashraf-vazeer** [actions/runner-images#6945]
### Description

as part of our requirement, we need to first uninstall docker and perform some actions.
Later we need to again install docker pkgs to build docker images.

We have successfully uninstalled the docker by the following commands.:

sudo service docker stop
sudo apt-get remove -y --allow-change-held-packages containerd.io docker-ce docker-ce-cli docker-ce-rootless-extras

But later we are trying to install docker again by the following commands, it is not working.
sudo apt-get install -y docker-ce docker-ce-cli docker-ce-rootless-extras

Can you please help us to re-install docker pkgs again?

Thanks

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.300.2'

### Is it regression?

no

### Expected behavior

Docker pkgs should be re-installed successfully

### Actual behavior

Not able to re-install docker pkgs after uninstalling them

### Repro steps

1. Uninstall docker pkgs by the following commands.:

sudo service docker stop
sudo apt-get remove -y --allow-change-held-packages containerd.io docker-ce docker-ce-cli docker-ce-rootless-extras

2.  Later try installing docker again by the following commands.
sudo apt-get install -y docker-ce docker-ce-cli docker-ce-rootless-extras

The above commands not working

**Comment by erik-bershel** [comment]
Hey @ashraf-vazeer!
Please read officiall installation guide here: https://docs.docker.com/engine/install/ubuntu/
It wouldn't work so simple with Docker.
And you may use as an example our Docker moby installer [script](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/docker-moby.sh) and [another one](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/docker-compose.sh) for Docker compose.

**Comment by ashraf-vazeer** [comment]
Thanks a lot @erik-bershel will try out and get back to you.
This is really helpful.

**Comment by erik-bershel** [comment]
Hey @ashraf-vazeer! 
I'll close that issue because it isn't really connected with any current bugs in repo. Feel free to contact us in case you have other concerns.
