### ISSUE TITLE
Update Az PowerShell to 9.3.0

### ISSUE THREAD

**Issue by GeorgeMansoMSFT** [actions/runner-images#6947]
### Tool name

Az PowerShell 9.3.0

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

9.3.0

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by GeorgeMansoMSFT** [comment]
Currently, Az 9.2.0 has an issue where spaces are removed when using Set-AzPolicyDefinition and other PolicyDefinition cmdlets. This was fixed in Az 9.3.0. Up until yesterday, my customer was able to use the win-2019 runner as it still had 9.0.1, but now that has been updated to 9.2.0 so they are unable to continue using any pipelines for policy creation.

**Comment by mikhailkoliada** [comment]
Will be deployed next week

**Comment by lukargit** [comment]
Has this been deployed? We are trying to understand if we can remove the pinned PS Azure module version from our pipelines at this point.

**Comment by mikhailkoliada** [comment]
It should be available for everyone!
