### ISSUE TITLE
White spaces being trimmed from resource tags when tasks run on windows-latest runners

### ISSUE THREAD

**Issue by lukargit** [actions/runner-images#6948]
### Description

We have powershell tasks that run on the `windows-latest` runners, and since Az powershell modules were updated to 9.2 as documented in [this commit](https://github.com/actions/runner-images/commit/a22d921c177b4ff25548bd51282a72a0ffce9bed#diff-a1f67f5c4a583bf90c239743379ad9473fbf1fa9d11c5cb7739c8012404dcc7aL536-R541) some of our scripts are behaving unexpectedly. 

We have calls using `Set-AzResource` that are setting tags on VM's and tags that include white spaces are having them trimmed. Example of this happening with a date stamp tag:

When attempting to set a tag with the value `1/19/2023 5:07:03 PM`, the actual tag being set on the VM has a value that equals `1/19/20235:07:03PM`.

This is only happening since Az powershell was updated on these runners, and the work around we found is to set our preferred module version to `9.0.1` in our pipelines.

Can this be fixed on the runners so we can use the latest module versions?  I found [this issue](https://github.com/Azure-Player/azure.datafactory.tools/issues/276) that appears to be related as it references the same `Az.Resources` module having a similar issue after a recent update.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Image: windows-2022
Version: 20230109.1
```

### Is it regression?

No

### Expected behavior

Tags are set with the value that is passed in the `-Tags` param for `Set-AzResource`.

### Actual behavior

Tag values are having white spaces trimmed.

### Repro steps

On windows-latest runners, run this:

```
$date = ([DateTime]::UtcNow).tostring()
$tags += @{date=$date}
set-azresource -ResourceGroupName <resource_group> -ResourceType "Microsoft.Compute/VirtualMachines" -Name <vm_name> -tag $tags
```

**Comment by erik-bershel** [comment]
Hi @lukargit!
I will close that issue because it is a clone for https://github.com/actions/runner-images/issues/6947
