### ISSUE TITLE
Add [Meteor.js]

### ISSUE THREAD

**Issue by hridayeshgupta-iticks** [actions/runner-images#6951]
### Tool name

Meteor.js

### Tool license

The MIT License (MIT)

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.2.4

### Brief description of tool

Meteor.js is an open source platform for seamlessly building and deploying Web, Mobile, and Desktop applications in Javascript or TypeScript.

### URL for tool's homepage

https://www.meteor.com/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
npm install -g meteor
```

### Tool installation time in runtime

few mins

### Are you willing to submit a PR?

No

**Comment by erik-bershel** [comment]
Hello @hridayeshgupta-iticks ! 
Due to maintenance concerns, we would like not to add the tool to the image.

**Comment by hridayeshgupta-iticks** [comment]
> Hello @hridayeshgupta-iticks ! Due to maintenance concerns, we would like not to add the tool to the image.

Thanks for the revert. Do you recommend any steps to add support and maintain the same at our end?

**Comment by erik-bershel** [comment]
@hridayeshgupta-iticks I will take a little investigation in a free time later. Right now I see only that package is prepared for an older one ennvironment then we have by default.
<img width="556" alt="Screenshot 2023-01-20 at 12 48 17" src="https://user-images.githubusercontent.com/110455084/213688307-9200f956-3a14-4cbf-9455-be05f1758167.png">

**Comment by hridayeshgupta-iticks** [comment]
Thanks @erik-bershel any guidance will be helpful.
Yes, Meteor lags a bit in supporting nodejs. though its actively managed but they take time to release support for new versions, and always behind one stable version.

**Comment by erik-bershel** [comment]
Hay again @hridayeshgupta-iticks! 
Simplest and fastest option to install it is to use [meteorengineer/setup-meteor@v1](https://github.com/meteorengineer/setup-meteor) action. It will take about 20 seconds in runtime.

**Comment by hridayeshgupta-iticks** [comment]
Great thanks a lot @erik-bershel
