### ISSUE TITLE
Android API33 (Xamarin) looks to be missing with VS 16.11.23 update

### ISSUE THREAD

**Issue by t-anderson** [actions/runner-images#6955]
### Description

After Jan 11, 2023 we are seeing build errors for our Xamarin project, saying it could not find android.jar for API level 33.

##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(520,2): Error XA5207: Could not find android.jar for API level 33. This means the Android SDK platform for API level 33 is not installed. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-33\android.jar missing.)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: windows-2019
Version: 20230117.1
Included Software: https://github.com/actions/runner-images/blob/win19/20230117.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win19%2F20230117.1

### Is it regression?

Version: 20221214.4

### Expected behavior

See description

### Actual behavior

See description

### Repro steps

See description

**Comment by erik-bershel** [comment]
Hello @t-anderson!
After little check I found that we have only 33-EXT4 platform SDK . Check here:
<img width="1061" alt="Screenshot 2023-01-20 at 18 08 26" src="https://user-images.githubusercontent.com/110455084/213761477-6c08a812-94d9-4b36-8790-bd74932b062f.png">

Just to be sure I used [setup-android](https://github.com/android-actions/setup-android) action and got same result:
<img width="1068" alt="Screenshot 2023-01-20 at 18 47 01" src="https://user-images.githubusercontent.com/110455084/213771002-a3102e74-4562-4632-bb1d-c2d5e38a85c7.png">

I recommend you to check your project for an opportunity to use that SDK. Or you may open an issue for VS Studio developers. It happens from time to time with VS. For example: https://github.com/dotnet/maui/issues/10222

**Comment by t-anderson** [comment]
Opened and issue on VS Developer Community. https://developercommunity.visualstudio.com/t/Android-API33-Xamarin-looks-to-be-miss/10258905

**Comment by tklempay** [comment]
> 

I know this is closed but why was the extension included in the name?  I think its possible that is what's throwing things off for the build.  Notice that EVERY other version of the Android Platform SDK is a simple numeric.  In the AndroidManifest.xml, one does not reference the minor version number, rather just the main version number for the target SDK version.

In the most recent version of Visual Studio for Windows 2022, the Android SDK only offers us developers 33.0.2.  We don't even have access to 33-EXT4

![image](https://user-images.githubusercontent.com/44921765/213781834-88cc8638-95e4-448c-a804-903c2d198f75.png)

**Comment by mattjohnsonpint** [comment]
The following can be used to work around the problem:

```yaml
    - name: Install Android 33
      if: runner.os == 'Windows'
      shell: cmd
      run: '%ANDROID_HOME%\cmdline-tools\latest\bin\sdkmanager "platforms;android-33"'
```

It is only needed on `windows-2019`, not on `windows-2022` or `windows-latest`.

**Comment by erik-bershel** [comment]
@mattjohnsonpint would be available with the new Windows images very soon. Deployment in progress.
