### ISSUE TITLE
MacOS 12 image no longer has LLVM 14 at the queried location

### ISSUE THREAD

**Issue by JessyDL** [actions/runner-images#6956]
### Description

A runner script that was working fine up until today can no longer find LLVM 14 at the queried location (using `$(brew --prefix llvm@14)` ) as can be seen from this log: https://github.com/JessyDL/paradigm/actions/runs/3969538376/jobs/6804199113

Previous runs did find a clang at that location. It's interesting that brew is still reporting an LLVM 14 install at that location.

As extra, I re-ran a run that completed fine yesterday and it also broke. Did something change in the image recently?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

failed build: https://github.com/JessyDL/paradigm/actions/runs/3959573491/jobs/6804335634
same run yesterday: https://github.com/JessyDL/paradigm/actions/runs/3959573491/jobs/6782565113

That's the same job, with attempt 1 passing yesterday, but attempt 2 failing today. Only change to this would be the environment.

### Is it regression?

https://github.com/JessyDL/paradigm/actions/runs/3959573491/jobs/6782565113

### Expected behavior

The linked run worked fine yesterday, cmake should find a clang binary at the given location.

### Actual behavior

Clang cannot be found by cmake at the queried location.

### Repro steps

Pass `$(brew --prefix llvm@14)`/bin/clang to cmake, cmake can't find it althougn reporting the correct path.

**Comment by JessyDL** [comment]
Yeah, I just noticed there are new docs available for the new image. The linked environment information in the readme for macos-12 still points to LLVM 14 being present though: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
Might want to update that (if it doesn't happen automatically)

**Comment by erik-bershel** [comment]
@JessyDL it will happen soon in the end of CD process (speaking about merge). You just hitting that link in the moment of rollout when it works wrong, yes. It might be tricky and misleading.
