### ISSUE TITLE
`runs-on: ubuntu-20.04` is acting like `runs-on: ubuntu-latest`

### ISSUE THREAD

**Issue by jrajahalme** [actions/runner-images#6958]
### Description

Workflow with `runs-on: ubuntu-20.04` actually runs on Ubuntu 22.04, breaking the build. Seen first time on Friday, Jan 20, 2023. Example workflow run with this issue: https://github.com/cilium/proxy/actions/runs/3974895557/jobs/6814430446

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20230118.2

### Is it regression?

yes

### Expected behavior

Expecting the job to run on Ubuntu-20.04 like this: https://github.com/cilium/proxy/actions/runs/3974899935/jobs/6814436941

Set up job:
```
Current runner version: '2.300.2'
Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20230118.1
```

### Actual behavior

Job runs on 22.04, like here: https://github.com/cilium/proxy/actions/runs/3974895557/jobs/6814430446
Set up job:
```
Current runner version: '2.300.2'
Runner name: 'ubuntu-latest-4cores-16gb_43653747bb6f'
Runner group name: 'Default Public Runners'
Machine name: 'runner'
Operating System
  Ubuntu
  22.04.1
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230118.2
```

### Repro steps

Push changes to the above workflow and observe the random selection of Ubuntu version.

**Comment by jrajahalme** [comment]
Another example:

Fail, runs on Ubuntu 22.04: https://github.com/cilium/proxy/actions/runs/3975062654/jobs/6814683817
Re-run works, runs on Ubuntu 20.04: https://github.com/cilium/proxy/actions/runs/3975062654/jobs/6814691636

**Comment by Alexey-Ayupov** [comment]
Hello @jrajahalme, If you noticed, all your failed attempts were running on "'**ubuntu-latest-4cores-16gb**_xxxxxxx" runners. This is well known [GitHub Larger Ranners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners), if you didn't buy it, we will investigate why you have access to LRs, and come back to you later.

**Comment by jrajahalme** [comment]
Thanks for the info @Alexey-Ayupov! Assume our org has access to the larger runners, but why the workflow randomly pick up Ubuntu 20.04 or the larger runner with Ubuntu 22.04 when it says `runs-on: ubuntu-20.04`?

**Comment by jrajahalme** [comment]
We have one other workflow in `cilium/cilium` with `runs-on: ubuntu-latest-4cores-16gb`, none on `cilium/proxy`, but somehow this work at `cilium/proxy` randomly runs on that instead of the specified `ubuntu-20.04`. We also have workflows at `cilium/cilium` specifying `ubuntu-20.04` that get assigned to run on a Larger Runner, e.g. here: https://github.com/cilium/cilium/actions/runs/3982890953/jobs/6827750408

**Comment by jrajahalme** [comment]
Apparently this was due to a mishap on our org setup w.r.t. large runners, closing.

**Comment by maxim-lobanov** [comment]
Hello @jrajahalme , just to follow up it and explain root cause:
As i can see your org has two Larger Runners:
- `ubuntu-latest-4cores-16gb` (Labels: `ubuntu-latest-4cores-16gb`, `ubuntu-22.04`)
- `ubuntu-latest-4cores-16gb-20.04` (Labels: `ubuntu-latest-4cores-16gb-20.04`, `ubuntu-20.04` )

Looks like you have manually added `ubuntu-22.04` and `ubuntu-20.04` labels to your runners and they conflict with pre-defined labels for Standard Runners. We recommend you removing `ubuntu-22.04` and `ubuntu-20.04` and use full runner names in your YAML or assign new label that will be different from pre-defined standard runners labels.
