### ISSUE TITLE
Add gcc-12 (macOS)

### ISSUE THREAD

**Issue by mathomp4** [actions/runner-images#6969]
### Tool name

GCC 12

### Tool license

GPL-2.0 and 2 other licenses found

### Add or update?

- [X] Add
- [ ] Update

### Desired version

12

### Brief description of tool

The GNU Compiler Collection includes front ends for [C](https://gcc.gnu.org/c99status.html), [C++](https://gcc.gnu.org/projects/cxx-status.html), Objective-C, [Fortran](https://gcc.gnu.org/fortran/), Ada, Go, and D, as well as libraries for these languages (libstdc++,...). GCC was originally written as the compiler for the [GNU operating system](http://www.gnu.org/gnu/thegnuproject.html). The GNU system was developed to be 100% free software, free in the sense that it [respects the user's freedom](http://www.gnu.org/philosophy/free-sw.html).

### URL for tool's homepage

https://gcc.gnu.org/

### Provide a basic test case to validate the tool's functionality.

```bash
gcc --version
g++ --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install gcc-12
```

**Comment by mathomp4** [comment]
Note: I'm mainly asking for `gcc-12` along side `gcc-11` on the macos-latest image.

**Comment by Alexey-Ayupov** [comment]
Hi @mathomp4, we will take a look at it.

**Comment by sergei-pyshnoi** [comment]
Hi @mathomp4, gcc 12 will be deployed in next week.

**Comment by mathomp4** [comment]
> Hi @mathomp4, gcc 12 will be deployed in next week.

Thanks!

**Comment by mikhailkoliada** [comment]
Should be done
