### ISSUE TITLE
Fastlane screenshots timeouts after 60 mins - unable to automate screenshots in Azure DevOps

### ISSUE THREAD

**Issue by pirocso** [actions/runner-images#6982]
### Description

Hello,

We are trying to create an Azure DevOps pipeline to automate our screenshots using Fastlane Screenshots. However, while the UI Test target does launch, the pipeline timeouts and no screenshots are taken. On local systems, this executes and finishes well within 60 minutes.

We did separate the screenshots automation per device and per language to ensure each device and language combination has its own VM and thus its own 60 minutes limit, yet this still times out.

We looked at issue [https://github.com/actions/runner-images/issues/1436](https://github.com/actions/runner-images/issues/1436) but that does not seem to be the issue. We believe something is prompted on the VM blocking the execution the pipeline, thus timing out but we cannot connect remotely to it to see what could cause it.

Thanks
<img width="855" alt="Screenshot 2023-01-25 at 3 27 40 PM" src="https://user-images.githubusercontent.com/4984337/214683544-8b2eee5f-db97-4256-b8de-10ee9b54307e.png">
<img width="1143" alt="Screenshot 2023-01-25 at 3 27 56 PM" src="https://user-images.githubusercontent.com/4984337/214683552-6230678b-4fbc-451d-ab57-81b7214c53f4.png">

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version 20221215.1

### Is it regression?

No

### Expected behavior

Fastlane screenshots should launch correctly, capture screenshots and finish within 60 minutes

### Actual behavior

Pipeline times out after 60 minutes

### Repro steps

Create an Azure Dev Ops pipeline to build an Xcode project on a macOS 12 image
Ensure your Xcode project contains a UI Test Target that generates screenshots using Fastlane Screenshots
Ensure your Azure Dev Ops pipeline launches only that UI Test Target
Launch the pipeline

**Comment by Alexey-Ayupov** [comment]
Hello @pirocso, could you please provide minimal repro steps?

**Comment by pirocso** [comment]
> Hello @pirocso, could you please provide minimal repro steps?

Done

**Comment by mikhailkoliada** [comment]
@pirocso please provide a minimal pipeline files/project files which we could run in order to detect the problem.

**Comment by mikhailkoliada** [comment]
Hello! As there are no currently actable snippets we could work on I am going to close the issue. Feel free to reach us again if there are new info you would like to provide please feel free to reach us again.

**Comment by pirocso** [comment]
Hi - we are looking into providing the info requested - please stand by
