### ISSUE TITLE
Add virtual audio device for windows runners 

### ISSUE THREAD

**Issue by zackees** [actions/runner-images#6983]
### Description

Windows is missing a sound driver and a Runtime exception is thrown. I've noticed that this happens with any other utilities that tries to use Windows sound.

Adding this to the runner adds a virtual sound card and allows the runner to processes python `winsound` and other sound libraries:

```
name: Win_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.10.4]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install pytest
    - name: Print device
      run: Get-CimInstance Win32_SoundDevice | fl *
    - name: Install Scream
      shell: powershell
      run: |
        Start-Service audio*
        Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
        Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
        $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
        $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
        $store.Open("ReadWrite")
        $store.Add($cert)
        $store.Close()
        cd C:\Scream\Install\driver
        C:\Scream\Install\helpers\devcon install Scream.inf *Scream
    - name: Print Audio Device
      run: Get-CimInstance Win32_SoundDevice | fl *
    - name: Run Test
      run: |
        pytest tests
```

See also: https://github.com/actions/runner/issues/2393

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/zackees/playaudio/blob/main/.github/workflows/push_win.yml
"windows-latest"

Failing build:
https://github.com/zackees/playaudio/actions/runs/4010669207/jobs/6887434178

### Is it regression?

No

### Expected behavior

Windows sound should work

### Actual behavior

Right now python package winsound fails because of missing sound card.

For example, code like this fails:

```python
import winsound
winsound.PlaySound("bell.mp3", winsound.SND_FILENAME)
```

Will fail with:

```
RuntimeError: Failed to play sound
```

### Repro steps

Fork https://github.com/zackees/playaudio/commit/e5216d696cf7870be7ddb62150c83ce74751894e and watch your runner fail

**Comment by Alexey-Ayupov** [comment]
Hello @zackees, We do not pre-install any virtual hardware since it can affect end-users.
However, you can add virtual hardware during runtime.
Generally, we have no plans to pre-install anything like this. 
If you have any questions, feel free to reach us.

**Comment by zackees** [comment]
Cool, well I hope that other people having the same problem finds this solution above.

**Comment by onyedikachi-david** [comment]
> Cool, well I hope that other people having the same problem finds this solution above.

Thanks for this.
