### ISSUE TITLE
Java Runtime class file recognition

### ISSUE THREAD

**Issue by Technomann** [actions/runner-images#6989]
### Description

Image generation is not working with the latest **Windows2022** image.

The following error occurs when creating an image with the latest stable version of Windows2022 
(commit: 8105753c2c3ac7f1bdec48caaebd35d8d264a6ab):

==> vhd: Error: A JNI error has occurred, please check your installation and try again
==> vhd: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
==> vhd:        at java.lang.ClassLoader.defineClass1(Native Method)
==> vhd:        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
==> vhd:        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
==> vhd:        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
==> vhd:        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
==> vhd:        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
==> vhd:        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
==> vhd:        at java.security.AccessController.doPrivileged(Native Method)
==> vhd:        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
==> vhd:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
==> vhd:        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
==> vhd:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
==> vhd:        at java.lang.Class.getDeclaredMethods0(Native Method)
==> vhd:        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
==> vhd:        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
==> vhd:        at java.lang.Class.getMethod0(Class.java:3018)
==> vhd:        at java.lang.Class.getMethod(Class.java:1784)
==> vhd:        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
==> vhd:        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
==> vhd: Install-AndroidSDKPackages : Cannot bind argument to parameter 'AndroidPackages' because it is null.
==> vhd: At C:\Windows\Temp\script-63d23ccf-fbc9-8a77-b415-2a34bde5f8ff.ps1:90 char:34
==> vhd: +                 -AndroidPackages $platformList
==> vhd: +                                  ~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidData: (:) [Install-AndroidSDKPackages], ParentContainsErrorRecordException
==> vhd:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Install-AndroidSDKPackages
==> vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
UserTrackingId==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?

I used packer 1.8.5 and the image should be created in Azure, but the build runs on local Windows 11 PC.

I tried it multiple times, same error at each build.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Build is not public.

### Is it regression?

The following commit was just fine: 9b06b852013a0b207a0f73fc2b9aea75c29287f5

### Expected behavior

Should create the image in Azure.

### Actual behavior

Java Runtime cannot recognize class file with version 55.0 and this leads to failure.

### Repro steps

1. Checkout latest Windows2022 release commit: 8105753c2c3ac7f1bdec48caaebd35d8d264a6ab
2. Use packer 1.8.5 (add it to the path)
3. Use the given description and run the `GenerateResourceAndImage` function with additional authentication via service principal. Location: North Europe, ImageType: Windows2022

**Comment by Alexey-Ayupov** [comment]
Hello @Technomann, this issue was fixed by this PR https://github.com/actions/runner-images/pull/6963

Please update your repository and try again.

We will close this issue as a duplicate. If you have any questions feel free to reach us.
