### ISSUE TITLE
Drop `GRAALVM_11_ROOT` in favor of `setup-graalvm` Action

### ISSUE THREAD

**Issue by fniephaus** [actions/runner-images#6996]
### Tool name

GraalVM Community Edition

### Tool license

GPL 2 with Classpath Exception

### Add, update, or remove?

- [ ] Add
- [ ] Update
- [X] Remove

### Rationale

We are retiring JDK11 support in GraalVM (see https://github.com/oracle/graal/issues/5063), so users of `$GRAALVM_11_ROOT`, the GraalVM JDK preinstalled on GHA runners, will no longer be able to receive updates and access to new features of GraalVM. Instead, I think it'd make sense to recommend [`setup-graalvm`](https://github.com/marketplace/actions/github-action-for-graalvm) to users as this action also takes care of prerequisites required to use Native Image, GraalVM language runtimes, and other GraalVM components.

Please feel free to get in touch if you have any questions.

### URL for tool's homepage

https://www.graalvm.org/

### Are you willing to submit a PR?

no

**Comment by Alexey-Ayupov** [comment]
Hello @fniephaus, we will take a look at it.

**Comment by mikhailkoliada** [comment]
@fniephaus Hello!

Do I understand correctly that with the action, customers will be able to specify JDK 11 as well?
Apart from that, what's the eta on jdk11 deprication? So we could prepare an announcement.

**Comment by fniephaus** [comment]
Hi @mikhailkoliada,

> Do I understand correctly that with the action, customers will be able to specify JDK 11 as well?

Yes, you can, for example, use this:

```yml
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

> Apart from that, what's the eta on jdk11 deprication? So we could prepare an announcement.

JDK11 will be dropped in the next GraalVM release (see https://github.com/oracle/graal/issues/5063), which will be `23.0.0` and which is scheduled for April 18, 2023 (see [GraalVM Release Calendar](https://www.graalvm.org/release-notes/release-calendar/)).

I hope this helps!

**Comment by mikhailkoliada** [comment]
@fniephaus Hey! Sorry for long delay on our end. I have prepared the announcement here: https://github.com/actions/runner-images/issues/7338 it will be tracked and removed accordingly! Thank you for heads up, feel free to reach us out again if you have questions left!
