### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by mhsh90** [actions/runner-images#6998]
### Tool name

Upnto

### Tool license

No

### Add or update?

- [ ] Add
- [ ] Update

### Desired version

Upto

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
The issue was not created properly and will be closed.
