### ISSUE TITLE
[all OSs] Default Nodejs version will be set to 18 on February, 13

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#7002]
### Breaking changes

We are going to set Nodejs 18 as the default version across all VM images.

### Target date

Image deployment is starting on February 13 and will take 3-4 days.

### The motivation for the changes

Node.js 18 has moved to Active LTS status and is ready for general use. We would like to provide images with the latest stable updates as default ones.

### Possible impact

If your builds depend on the default Nodejs 16 they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

The recommended way is to pin your workflow to the desired nodejs version using:

https://github.com/actions/setup-node action for GH
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops for AzDO

**Comment by aeisenberg** [comment]
I think the description of this issue is incorrect. Are you setting the default node version to 18 on February 13?

**Comment by mikhailkoliada** [comment]
Right, fixed, thanks!

**Comment by jaden-zerbe-kr** [comment]
Will this enable the creation of GitHub javascript actions using node18? https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-action

**Comment by mikhailkoliada** [comment]
> Will this enable the creation of GitHub javascript actions using node18? https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-action

@jaden-zerbe-kr no, it is just a change of default for setup-node and some other tasks

**Comment by jaden-zerbe-kr** [comment]
> > Will this enable the creation of GitHub javascript actions using node18? https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-action
> 
> @jaden-zerbe-kr no, it is just a change of default for setup-node and some other tasks

Is this an appropriate repository to make such a feature request? If not, are you aware of the appropriate repository or an existing request for this to be supported?

**Comment by glenpogz36** [comment]
Is there any way I could still run these with node16??

If yes, how can I specify my azure pipeline to run node 16

It seems my agent pool is now running version 18 causing my pipeline run build to break
![image](https://user-images.githubusercontent.com/43967399/219292455-92018a6f-ca92-43f3-96a5-64767781fc05.png)

**Comment by glenpogz36** [comment]
at NormalModule._initBuildHash (D:\a\1\s\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\a\1\s\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\a\1\s\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\a\1\s\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\a\1\s\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\a\1\s\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
D:\a\1\s\node_modules\react-scripts\scripts\build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\a\1\s\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\a\1\s\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\a\1\s\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\a\1\s\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\a\1\s\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\a\1\s\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0

**Comment by guitoux1** [comment]
Same issue here, I need to use Node 1, no 18. 
My npm task in set inside a .csproj as a  BeforeBuild task, and in my devops yml task it's just a VSBuild task, so I don"t have anu control on the NPM version used.

**Comment by TomasHubelbauer** [comment]
@guitoux1 I think you should be able to use https://github.com/actions/setup-node. That is how you can control the global NPM version.

**Comment by prabhaskumra** [comment]
> Is there any way I could still run these with node16??
> 
> 
> 
> If yes, how can I specify my azure pipeline to run node 16
> 
> 
> 
> It seems my agent pool is now running version 18 causing my pipeline run build to break
> 
> ![image](https://user-images.githubusercontent.com/43967399/219292455-92018a6f-ca92-43f3-96a5-64767781fc05.png)
> 
> 

You can add a task to set a specific version of nodejs. The following is how I did it, I needed version 16.13.1. 

`- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.13.1'`

**Comment by vibhuti1** [comment]
> Is there any way I could still run these with node16??
> 
> If yes, how can I specify my azure pipeline to run node 16
> 
> It seems my agent pool is now running version 18 causing my pipeline run build to break ![image](https://user-images.githubusercontent.com/43967399/219292455-92018a6f-ca92-43f3-96a5-64767781fc05.png)

You can add a "Node.js tool installer" task in your job before the "npm install" task and specify the Node version you want to use. 
It will download and use the node version for the subsequent tasks.
![image](https://user-images.githubusercontent.com/37140454/219511247-de8f23bc-f49c-4ef1-9d57-48f4313a807f.png)

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by HanMan858** [comment]
This is causing the below error for everyone in the Azure pipeline
Error: error:0308010C:digital envelope routines::unsupported

As a solution we are downgrading version to 16 using node tool installer.

I hope this issue will be fixed in the upcoming patches.

**Comment by whiteKhoukha** [comment]
I am having the same issue as @HanMan858  and this caused my release pipeline to fail. 
As a solution I am setting the node version to 16 explicitly.

**Comment by yoanmLf** [comment]
Hello 👋 

Not sure it's fully related to that, but since couple of days, I'm seeing an error on projects using https://github.com/yoanm/github-action-deps-versions-checker when the `pre` action is executed:
```
The engine "node" is incompatible with this module. Expected version "16". Got "18.14.1"
```

[Documentation says](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre) that "The runtime specified with the using syntax will execute this file" but despite the fact that it's what it's configured, it doesn't seem to be the case anymore.

Is it related to that change ? If so, what can I do to make my GHAction working again ?

_N.B. : [I tried to move](https://github.com/yoanm/github-action-deps-versions-checker/actions/runs/4225070093/jobs/7336884428#step:6:1) the entire action to node 18, but that version seems not allowed (yet ?)_

**Comment by ilight** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1093002/220350442-733441d1-71e1-4682-b981-349d34fbe38d.png">

No success yet. We are using fastlane for Android build and we definitely need to use node16. Any suggestions on what I might be doing wrong here?

**Comment by GurliGebis** [comment]
I'm seeing issues on Azure Pipelines sometimes the last few days, where the NodeTool task installs another version like it should, but the next npm command uses v18 instead of the installer version.
Must be a bug, since rerunning the failed job often works fine.

**Comment by ilight** [comment]
> I'm seeing issues on Azure Pipelines sometimes the last few days, where the NodeTool task installs another version like it should, but the next npm command uses v18 instead of the installer version. Must be a bug, since rerunning the failed job often works fine.

Precisely. We too have NodeTool task that installs 16.19.0 but still uses node v18

**Comment by GurliGebis** [comment]
> > I'm seeing issues on Azure Pipelines sometimes the last few days, where the NodeTool task installs another version like it should, but the next npm command uses v18 instead of the installer version. Must be a bug, since rerunning the failed job often works fine.
> 
> Precisely. We too have NodeTool task that installs 16.19.0 but still uses node v18

I have created an issue #7168

**Comment by whiteKhoukha** [comment]
Can someone tell me where does gh annouce these changes? Especially when they can break the pipelines?

**Comment by mikhailkoliada** [comment]
@whiteKhoukha they are announced in this repository (by means of announcements like this one)

**Comment by 2sem** [comment]
```
- name: Specify Node version
         uses: actions/setup-node@v3
         with:
           node-version: 16
```

**Comment by WillBeebe** [comment]
> > Will this enable the creation of GitHub javascript actions using node18? https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-action
> 
> @jaden-zerbe-kr no, it is just a change of default for setup-node and some other tasks

I'm running into the same issue. I'd LOVE to upgrade to `node18` but I can't... sort-of.

Here's a failing build:
https://github.com/massdriver-cloud/actions/actions/runs/4256067294/jobs/7404476512

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')
```

```
name: 'Setup Massdriver CLI'
description: 'Sets up the Massdriver CLI'
author: 'Massdriver, Inc.'
inputs:
...omitted for clarity...
runs:
  using: 'node18'
  main: '../dist/index.js'
```

Now... I've heard that if you use `setup-node` like this in a GH action

```
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
      - uses: ./setup
        with:
          tag: ${{ matrix.version }}
      - run: node --version
  ```  

That it doesn't matter what you set as `using`, it will use a local copy first if it's available. I assume it would check the version, but I'm going to try an experiment.

**Comment by WillBeebe** [comment]
> > > Will this enable the creation of GitHub javascript actions using node18? https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-action
> > 
> > 
> > @jaden-zerbe-kr no, it is just a change of default for setup-node and some other tasks
> 
> I'm running into the same issue. I'd LOVE to upgrade to `node18` but I can't... sort-of.
> 
> Here's a failing build: https://github.com/massdriver-cloud/actions/actions/runs/4256067294/jobs/7404476512
> 
> ```
> Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')
> ```
> 
>  ```
> name: 'Setup Massdriver CLI'
> description: 'Sets up the Massdriver CLI'
> author: 'Massdriver, Inc.'
> inputs:
> ...omitted for clarity...
> runs:
>   using: 'node18'
>   main: '../dist/index.js'
> ```
> 
> Now... I've heard that if you use `setup-node` like this in a GH action
> 
> ```
>       - name: Set Node.js 18.x
>         uses: actions/setup-node@v3.6.0
>         with:
>           node-version: 18.x
>       - uses: ./setup
>         with:
>           tag: ${{ matrix.version }}
>       - run: node --version
> ```
> 
> That it doesn't matter what you set as `using`, it will use a local copy first if it's available. I assume it would check the version, but I'm going to try an experiment.

Lol dope, I think this works!

- set `using` to `node16` 
- use `setup-node` _before_ your action
- set whatever version of node you want 
- you only yolo once 🤙 🚀  

![Screenshot 2023-02-23 at 10 41 42 PM](https://user-images.githubusercontent.com/651833/221110111-256aa2fb-ddfc-4ba0-af45-7d1f2e52cf87.png)

**Comment by grzegorzjudas** [comment]
@mikhailkoliada node v18 is not LTS (since 2022-10-25, so almost 5 months now). When can we expect support for `using: node18` in custom JavaScript actions?

**Comment by Momotoculteur** [comment]
Hi, 
any news regarding to use node18 ?

**Comment by kekel87** [comment]
Hello, I can't figure out if this is supported now or not?

**Comment by vpolikarpov-akvelon** [comment]
Hey @kekel87. Could you elaborate your question?
