### ISSUE TITLE
MacOS actions get terminated with no log and no clear reason

### ISSUE THREAD

**Issue by oranagra** [actions/runner-images#7004]
### Description

Our MacOS tests often get terminated half way.
the summary page says `Received request to deprovision: The request was cancelled by the remote provider.`
and the job doesn't show any logs.
here's an example https://github.com/redis/redis/actions/runs/3977182258/jobs/6818115116
When it happens, the job logs are empty and no way to know what it was doing at the time and why it was terminated.
however, if i'm connecting a browser to the action before it terminates then i can see some logs until the point it hangs.

it was suggested to me that it could be a disk space issue like in #2840, and there is a chance that i have a test that has some timing issue and gets into a loop that fills the disk indefinitely, but so far i can't find any such thing (at normal times it only consumes a couple of gigabytes).

other possibilities i looked into is getting killed due to memory exhaustion, but i couldn't find any evidence for that either, and all my attempts to catch such a thing or blindly resolve it by toning down the more demanding tests, nothing seems to make a difference.

what i'm missing is two things:
1. a clear message that says what was the reason for the deprovision.
2. a way to postmortem inspect the run (see which processes consuming memory, or sizes of files), so that i can identify the culprit. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20230117.3
https://github.com/redis/redis/actions/runs/3977182258/jobs/6818115116

### Is it regression?

no

### Expected behavior

action to run to completion, or when it fails have some way to know why.

### Actual behavior

all i see is a `Received request to deprovision: The request was cancelled by the remote provider` message and empty logs

### Repro steps

i don't know how to easily reproduce it.
what i do is clone the `redis` repo, and trigger the test-macos-latest CI from the daily.yml

**Comment by erik-bershel** [comment]
Hey @oranagra!
I pushed to close that one because it's the same as https://github.com/actions/runner-images/issues/3517

In an addition I may say that the last signal from runner we got the same time with test step start. So it looks like job hitted all available resources and hanged.

**Comment by oranagra** [comment]
@erik-bershel even if that's right, and it's the same issue i think you have two serious issues that are not yet addressed.
1. there's nowhere in the termination message that says that the problem was disk space or memory.
2. without some way for a postmortem inspection, i have no way to find the culprit process or file.

i've spent several days and [hundreds of runs](https://github.com/oranagra/redis/actions/workflows/ci.yml) trying smoke it out.. sometimes it passes (and disk space is low), sometimes it fails, and i get no info.

**Comment by DaAwesomeP** [comment]
Example failed run on `ubuntu-latest` here: https://github.com/OpenLightingProject/ola/actions/runs/4371140416

Again, no logs or other way to troubleshoot. This is during a build of a large C++ project with `make`.

**Comment by DaAwesomeP** [comment]
**This is so far reproducible 100% of the time for us.** Associated pull: #1836
