### ISSUE TITLE
Document CPU architecture of each runner

### ISSUE THREAD

**Issue by TWiStErRob** [actions/runner-images#7031]
### Tool name

CPU architecture

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

whatever is available

### Brief description of tool

The CPU architecture. This is not really tool, but a core part of the system that is not listed in the documentation, the only reason I **guess** it's x86_64 is because of these env vars:

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#java
Mac could be M1 or M2 ARM64 too.

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
could be 32-bit x86 too.

Please list the CPU architecture of the runners for each runner.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by bogdan-damian-bgd** [comment]
Hi @TWiStErRob, a brief hardware overview for GH-hosted runners can be found [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). Thanks for the suggestion, we'll keep it in mind, but we won't be adding it to other documents for now.

If you have any questions feel free to reach us.

**Comment by TWiStErRob** [comment]
Not even a link to that page?

**Comment by TWiStErRob** [comment]
Hehe, sorry, I mean would you add a link to that page from the MD files to connect the software and hardware in some way.
