### ISSUE TITLE
Win22 - Resize-Partition : Size Not Supported

### ISSUE THREAD

**Issue by saoullabit** [actions/runner-images#7032]
### Description

Hi there, 
we face the following error : 
```
==> vhd: Resize-Partition : Size Not Supported
==> vhd:
==> vhd: Extended information:
==> vhd: The partition is already the requested size.
==> vhd:
==> vhd: Activity ID: {c2943d6d-e278-4b8d-80e1-a5d007270866}
==> vhd: At C:\Windows\Temp\script-63da2fea-9bba-5542-8267-d4b4262e995d.ps1:75 char:1
==> vhd: + Resize-Partition -DriveLetter $driveLetter -Size $size.SizeMax
==> vhd: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/.../MSFT_Partition) [Resize-Partition], CimExce
==> vhd:    ption
==> vhd:     + FullyQualifiedErrorId : StorageWMI 4097,Resize-Partition
==> vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```
After many (4) retries, we still face the issue at the same step.
Kind regards,
Marc.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

runner-images-win22-20230123.1

### Is it regression?

Yes, win22/20230109.1 (https://github.com/actions/runner-images/releases/tag/win22%2F20230109.1)

### Expected behavior

The resize step is working 

### Actual behavior

The Image is not build.

### Repro steps

Generate the image following the documentation.

**Comment by mikhailkoliada** [comment]
Hello! Could you post the full packer log?

**Comment by saoullabit** [comment]
Hi, please find the log : 
[full_Packer_Log.txt](https://github.com/actions/runner-images/files/10571056/full_Packer_Log.txt)
Regards,
Marc.

**Comment by mikhailkoliada** [comment]
@saoullabit what size and the region are you using? Does region of your choice support the size you choose?

**Comment by saoullabit** [comment]
@mikhailkoliada Size is 256G and it is made in region WEST EUROPE (supports resizing ... shall ...  may .... should ;-)  )

**Comment by mikhailkoliada** [comment]
@saoullabit not all regions support all the same sizes, the problem you observe is not connected with the image but with the region of your choice, please make sure your region supports your sku :) I am going to close the ticket for now but feel free to reach us again if you have questions left or you think we can help you with something else

**Comment by saoullabit** [comment]
@mikhailkoliada we already made some images (around 12) in the same region and this is was not an issue until THIS release.
Closing the case asking me for a SKU verification looks like you did not dig this case.
