### ISSUE TITLE
Update Android NDK to latest 25c

### ISSUE THREAD

**Issue by buttaface** [actions/runner-images#7040]
### Tool name

Android NDK

### Tool license

Apache

### Add or update?

- [ ] Add
- [X] Update

### Desired version

25c

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @buttaface!
Latest Android 25 NDK will be shipped with next image any way. It should happen on the very next week. Thank you for participation!

**Comment by mikhailkoliada** [comment]
updated
