### ISSUE TITLE
Update Moby CLI

### ISSUE THREAD

**Issue by JamieMagee** [actions/runner-images#7042]
### Tool name

moby-cli

### Tool license

Apache 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

23.0.0

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by JamieMagee** [comment]
Moby v23 was released yesterday[^1] and is already available in the Microsoft apt registry[^2]. This should be covered by a rebuild:

https://github.com/actions/runner-images/blob/751fe08d9840d2273fb1986980c5f18f3a920e64/images/linux/scripts/installers/docker-moby.sh#L13-L20

[^1]: https://github.com/moby/moby/releases/tag/v23.0.0
[^2]: http://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/moby-cli/

**Comment by erik-bershel** [comment]
@JamieMagee nice to see that you found how it works here. You are right - next moby-cli would be shipped with next Ubuntu images. It should happen on the very next week.

**Comment by mikhailkoliada** [comment]
updated

**Comment by JamieMagee** [comment]
@mikhailkoliada The installed version is still `20.10.22+azure-1`, according to [the software list][1]. I was mistaken, and v23 is still [in testing][2].

[1]: https://github.com/actions/runner-images/blob/bc6c8131b57bc748143a152c5cccf1376c3bdaf1/images/linux/Ubuntu2204-Readme.md
[2]: https://packages.microsoft.com/ubuntu/22.04/prod/dists/testing/main/binary-amd64/Packages
