### ISSUE TITLE
Deploying Ubuntu 22.04 with Tags fails

### ISSUE THREAD

**Issue by JoshuaVanDaalen** [actions/runner-images#7046]
### Description

Within the PowerShell script _(GenerateResourcesAndImage.ps1)_, the if statement for tags uses some ConverTo-Json and ConverFrom-Json, this will fail when choosing the packer file with extension pkr.hcl

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

​

### Is it regression?

​

### Expected behavior

Expected not to fail

### Actual behavior

It fails

### Repro steps

```powershell

$params = @{
    SubscriptionId                = $SubscriptionId
    ResourceGroupName             = $StorageAccountResourceGroupName
    ImageGenerationRepositoryRoot = "$pwd"
    ImageType                     = 'Ubuntu2204'
    AzureLocation                 = 'Australia Southeast'
    AzureClientId                 = $Credential.UserName
    AzureClientSecret             = $Credential.GetNetworkCredential().Password
    AzureTenantId                 = 'a47bd588-f2c9-4146-b0b2-d39f56758e0e'
    RestrictToAgentIpAddress      = $true
    AllowBlobPublicAccess         = $False
    EnableHttpsTrafficOnly        = $true
    SecondsToWaitForServicePrincipalSetup = 30
    OnError = "ask"
    Tags                          = @{
        Department  = 'P&E Infrastructure & Cloud'
        Environment = 'Non-Production-Shared'
        Platform    = 'Networking'
        Project     = 'BAU'
    }
}


.\GenerateResourcesAndImage.ps1 @params
```

**Comment by JoshuaVanDaalen** [comment]
See PR: [7047](https://github.com/actions/runner-images/pull/7047)

**Comment by ddobranic** [comment]
Hello @JoshuaVanDaalen, thank you for your contribution. We will take a look.

**Comment by erik-bershel** [comment]
Hi @JoshuaVanDaalen!
Thank you for your contribution again. I'll work on it near time. But I should close that issue due to it's a duplicate for https://github.com/actions/runner-images/issues/6946. We'll continue discussion in the #6946 issue and PR as well.
