### ISSUE TITLE
ValidateMajorVersionRegex fails for PowerShell modules

### ISSUE THREAD

**Issue by hbuckle** [actions/runner-images#7050]
### Description

We install some additional PowerShell modules on top of the base image, one of which installs SqlServer PowerShell module version 21.1.18221.

This causes the software report script to error with

```
==> azure-arm: Multiple versions from list '21.1.18221, 21.1.18256' return the same result from regex '^\d+': 21
==> azure-arm: At C:\image\SoftwareReport\software-report-base\SoftwareReport.Nodes.psm1:249 char:17
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230129.2

### Is it regression?

N/A

### Expected behavior

PowerShell modules can be installed side by side, so this should not fail the check

### Actual behavior

Software report script fails

### Repro steps

Install-Module -Name SqlServer -RequiredVersion 21.1.18221

**Comment by ddobranic** [comment]
Hello @hbuckle, we appreciate your interest to the project. And we should also warn you that all private changes to base images are done at your own risk and we may not always be able to help with some of these changes. Feel free to update software report generator to reflect your changes.
