### ISSUE TITLE
Update Maven to 3.9.0

### ISSUE THREAD

**Issue by Riggs333** [actions/runner-images#7055]
### Tool name

Maven

### Tool license

Apache 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.9.0

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ddobranic** [comment]
Hello, @Riggs333 we will update it in next image release. Thank you!

**Comment by Mohamed-E** [comment]
Hello, with this latest rollout of updating Maven from 3.8 to 3.9 an incompatibility has been identified with Maven 3.9 and The use of JFROG CLI to build/publish packages to an Artifactory instance. 

The following error started occurring in many of our pipelines
`ERROR org.apache.maven.cli.MavenCli - Internal error: java.lang.NullPointerException -> [Help 1]`

After much debugging and testing different version compatibilities with the different versions from all the components at play. We identified that the only resolution was to add an action for our workflows that would set the Maven version back to 3.8.

This is just informative of the impact this may have on others depending on similar workflows/tools.

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by mikhailkoliada** [comment]
@Mohamed-E you can use setup-maven-actions for gh actions: https://github.com/marketplace/actions/setup-maven-action. For Azure DevOps you will still have to download maven, with, say wget, and unpack/unzip it manually.

**Comment by Mohamed-E** [comment]
@mikhailkoliada - Correct yes, we identified that as our resolution while support is added for Maven 3.9. This is more for awareness.
