### ISSUE TITLE
Xamarin.iOS & Xamarin.Mac are outdated - Don't support XCode 14.1 & Missing bug fixes.

### ISSUE THREAD

**Issue by projectgoav** [actions/runner-images#7058]
### Description

The currently installed versions of Xamarin iOS & Xamarin.Mac are old and outdated. 

Xamarin.Mac 9.0.0 was released 22nd Novemeber 2022. This is not currently available and is required to build against Xcode 14.1 (or later). Currently only 8.12 is available

Xamarin.iOS 16.1 was also released 22nd November. This is not currently available and is required to correctly build against XCode 14.1 with native libraries present. Currently only 16.0 is available. 

When are we likely to see these Xamarin versions present on the build images. I would have thought they should have been updated by now. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Details of currently installed packages taken from here: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xamarin-bundles

### Is it regression?

Yes - Xamarin packages should remain up-to-date.

### Expected behavior

Xamarin.iOS & Xamarin.Mac are updated with XCode is updated as they largely need to stay in sync.

### Actual behavior

Xamarin.iOS & Xamarin.Mac are months old and don't support the latest version of XCode available on the runner.

### Repro steps

See above.

**Comment by projectgoav** [comment]
For more details:

Xamarin.Mac 9.0.0 is required to build with XCode 14.1 or later because of [this issue](https://github.com/xamarin/xamarin-macios/issues/16616)

Xamarin.iOS 16.1 is required to build with XCode 14.1 or later because of [this issue](https://github.com/xamarin/xamarin-macios/pull/16770)

**Comment by ddobranic** [comment]
Hello, @projectgoav! Updated images should be released this week.

**Comment by mikhailkoliada** [comment]
deployed

**Comment by projectgoav** [comment]
How long until the build machines pick this up? I've attempted to build this morning and the macos-12 agent is using image version `'20230205.1'` which I don't believe has these changes present.

**Comment by projectgoav** [comment]
Our Xamarin.Mac builds are still failing due to the XCode 14.1 & Xamarin tool version mismatch. Can you advise when this will be fully deployed to all agents?
