### ISSUE TITLE
ghcup broken

### ISSUE THREAD

**Issue by hasufell** [actions/runner-images#7061]
### Description

Failure reports:

* https://github.com/input-output-hk/ouroboros-network/actions/runs/4117108345/jobs/7108005081
* https://github.com/haskell/cabal/actions/runs/4118707642/jobs/7112381525#step:3:135

Error is:

```
ghcup: /usr/local/.ghcup/cache/ghcup-0.0.7.yaml: setModificationTime:setFileTimes: permission denied (Operation not permitted)
```

----

GHCup needs the cache and other directories writable. This is ensured in

https://github.com/actions/runner-images/blob/8361bb299ba9290b70b6ed8bf337456714c6516d/images/linux/scripts/installers/haskell.sh#L45

However, for some reason this seems to not be enough. 

This PR might have triggered the bug, because before, ghcup would (incorrectly) use `~/.ghcup`:

https://github.com/actions/runner-images/pull/6770

@mikhailkoliada @angerman @Mikolaj 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner version 2.301.1

Runner image version 20230206.1

### Is it regression?

Yes

### Expected behavior

ghcup can write to `/usr/local/.ghcup`

### Actual behavior

ghcup can't write to `/usr/local/.ghcup`

### Repro steps

Run `ghcup install ghc 9.4.4` in a standard ubuntu image.

**Comment by ddobranic** [comment]
@hasufell, thank you for reporting this issue. we already have ghc 9.4.4 installed on the image and image build logs doesn't contain any write permission errors. do you think we should revert [#6770](https://github.com/actions/runner-images/pull/6770)?

**Comment by hasufell** [comment]
I think we need to investigate why there are permission errors and fix it.

I also noticed newer pipeline runs don't use 20230206.1 image anymore but 20230129.2. Has someone reverted already?

**Comment by ddobranic** [comment]
20230206.1 is being released currently

**Comment by hasufell** [comment]
Some things to investigate:

1. do the tests run as superuser and change the permissions implicitly? Why did the tests not catch this?
2. there should be a permission test
3. is it possible that some later scripts change the permissions of `/usr/local` recursively?

**Comment by Mikolaj** [comment]
I think I confirmed that adding sudo chmod -R 777 /usr/local/.ghcup/cache to a CI script doesn't help: https://github.com/haskell/cabal/actions/runs/4123024121/jobs/7120538104

**Comment by Mikolaj** [comment]
^^^ is from this PR: https://github.com/haskell/cabal/pull/8739

**Comment by hasufell** [comment]
https://lists.gnu.org/archive/html/bug-coreutils/2015-12/msg00042.html

This sheds more light on the issue.

Using `utimensat` with a time other than `now` requires more than write permissions!

So we also need to run `chown`.

**Comment by hasufell** [comment]
https://github.com/haskell/cabal/actions/runs/4123791787/jobs/7122272909#step:3:19 shows that `ghcup-0.0.7.yaml` is indeed owned by root. My suspicion is that the test suite is doing this.

**Comment by mikhailkoliada** [comment]
@hasufell we are going to deploy an image with updated ghcup, if your recent changes will not work, we can fix ownership from the runner side, lets stay in touch for that, feel free to ping me directly (you know the ways ;))
