### ISSUE TITLE
Update/Add chart-releaser

### ISSUE THREAD

**Issue by wheelerlaw** [actions/runner-images#7064]
### Tool name

chart-releaser

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v1.5.0

### Approximate size

~25 MB

### Brief description of tool

Helpful tool that abstracts away some of the plumbing for creating a Helm repository in a GitHub repository using GitHub Pages. 

### URL for tool's homepage

https://github.com/helm/chart-releaser

### Provide a basic test case to validate the tool's functionality.

```bash
cr version (??)
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
curl -L "https://github.com/helm/chart-releaser/releases/download/v${CR_VERSION}/chart-releaser_${CR_VERSION}_linux_amd64.tar.gz" | sudo tar xvz --directory /usr/bin cr
```

### Tool installation time in runtime

Probably 1-10 seconds

### Are you willing to submit a PR?

Yes

**Comment by ddobranic** [comment]
@wheelerlaw thank you very much for your proposal to install chart-releaser on Ubuntu images. Since it takes only a few seconds to install, as you mentioned, we would not like to have it preinstalled right now, but we will reconsider it in the future.
