### ISSUE TITLE
Update/Add nix package manager

### ISSUE THREAD

**Issue by koozz** [actions/runner-images#7066]
### Tool name

nix

### Tool license

LGPL-2.1

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.13.2 (current latest)

### Brief description of tool

The Nix package manager seamlessly allows multiple versions of libraries to be used concurrently or even different versions per shell.

Packages are download into the nix-store on disk on demand and symlinked into the new shell. This will not alter the global environment and can be extremely valuable in building reproducible builds.

> Nix provides developers with a complete and consistent development environment. Stop worrying how to install dependencies for your project.
> 
> -- [NixOS site](https://nixos.org/explore.html)

Using a nix-shell to build software or writing scripts with the nix-shell shebang will make it work for everyone who has Nix installed. Other ways of leveraging Nix would be to be able to instantly build projects containing a `flake.nix` file.

Another option would be to support a NixOS runner image, but that would need all the tools already installed on the ubuntu-latest and other images.

### URL for tool's homepage

https://nixos.org

### Provide a basic test case to validate the tool's functionality.

```bash
nix-shell -p cowsay --run "cowsay Nix works fine!"
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
sh <(curl -L https://nixos.org/nix/install) --daemon
```

### Tool installation time in runtime

In the order of minutes, have not timed a clean install (yet).

### Are you willing to submit a PR?

Sure, though I would need to work my way around PowerShell I see, not my favorite shell scripting.

**Comment by ddobranic** [comment]
@koozz, thank you very much for proposal to include this interesting tool. at this point we would not like to preinstall it on our images since we already have a few, but we will reconsider in the future.

**Comment by dzmitry-lahoda** [comment]
just checking, 1.5 year passed. any reconsiderations?

previous asks

https://github.com/actions/runner-images/issues/1579

https://github.com/actions/runner-images/issues/376
