### ISSUE TITLE
Windows postgresql install fails

### ISSUE THREAD

**Issue by gpclassictech** [actions/runner-images#7072]
### Description

Since the below change I've been unable to create a new Windows 2022 image, where the image generation just stalls and doesn't complete when trying to install PostgreSQL. 

https://github.com/actions/runner-images/pull/6824

Looks like it's trying to pull version 14.7.x but that version isn't available from the source in the script, whereas 14.6 is available.

Install-PostgreSQL.ps1 

It finds the latest versions from here - 
https://git.postgresql.org/gitweb/?p=postgresql.git;a=tags 

Then tries to grab that version from here - https://get.enterprisedb.com/postgresql/postgresql-$toolsetVersion.$TargetMinorVersions-$increment-windows-x64.exe

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

8361bb2
https://github.com/actions/runner-images/commit/8361bb299ba9290b70b6ed8bf337456714c6516d

### Is it regression?

No

### Expected behavior

PostgreSQL to install successfully and the build to complete

### Actual behavior

Installation of PostgreSQL fails and the image generation stalls without completing

### Repro steps

Run the latest build and attempt to generate a Windows 2022 image using GenerateResourcesAndImage.ps1

You can test Install-PostgreSQL.ps1 alone by editing line 10 to - 
`$toolsetVersion = "14"`

Then running lines 10-45 which will return the below error -

` You cannot call a method on a null-valued expression.`
`At line:35 char:1`
`+ $InstallerName = $InstallerUrl.Split('/')[-1]`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException`
`    + FullyQualifiedErrorId : InvokeMethodOnNull`
 

If you change line 24 to be the below, the installation is successful as it installs version 14.6 (which is available from get.enterprisedb.com as of 09/02/2023)
`$TargetMinorVersions = ($MinorVersions | Sort-Object)[-2]`

**Comment by mikhailkoliada** [comment]
Hello! Sync your main please, it was fixed.
