### ISSUE TITLE
Server 2022 image for ScaleSet - or working documentation and scripts

### ISSUE THREAD

**Issue by KlausLinzner** [actions/runner-images#7074]
### Description

We're running into resource limitations in the microsoft hosted agents in azure devops and according to documentation at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted we wanted to switch to a VM ScaleSet in Azure.

Unfortunately - this is easier said than done. About 8 months after initially creating the discussion in https://github.com/actions/runner-images/discussions/5843 ...
* we've spent days and weeks trying to get this to work
* through our Microsoft EA we got several days of support and microsoft tried to set this up 
  * https://github.com/tomasszabo/devops-custom-managed-image
* and after that an external consulting company spent a lot of time (and money) to set this up.

So far, we're still far from having a working system that can be regularly updated from the repo at https://github.com/actions/runner-images/tree/main/images.CI/linux-and-win/azure-pipelines and have automatic pipelines that regularly update and redeploy it.

The problem pretty much comes down to the following items:
* The pipeline yamls need to be updated (a lot) to get anything to work once
* Once pipelines are updated, it's hard to integrate ongoing changes
* The pipelines rely running on VMs with specific capabilities. While MS Hosted agents fullfill software requirements, they lack the network pairing to created storages,... (only after you've successfully created an image once, it would be possible to use this image to build other images)
* which is were the required changes come in again to make it work that prevents from updating

Could you please either
* provide working documentation and guidance to make use of the source scripts OR
* simply provide the images altogether (similar to the VS image) so they can be used out of the box?

Currently, this is not only a major problem for us, but costs Microsoft revenue as well: Instead of upgrading from microsoft hosted agents to ScaleSets we're force to downgrading from microsoft hosted agents to on-prem virtual machine.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Windows-2022, Windows-2019, Ubuntu22.04

### Is it regression?

no

### Expected behavior

* provide working documentation and guidance to make use of the source scripts OR
* provide the images altogether (similar to the VS image) so they can be used out of the box

### Actual behavior

A set of scripts that can be used after extensive changes that prevents continous integration from upstream repositories

### Repro steps

Follow the steps in a new devops environments without any prerequisites at 
* https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops and 
* https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md

to see if you can get a working Windows 2022 environemnts.

**Comment by erik-de-bont** [comment]
@KlausLinzner  Maybe this can help https://github.com/erik-de-bont/azuredevops-buildagents

**Comment by KlausLinzner** [comment]
Thanks @erik-de-bont  - appreciate any support on that topic.

But you're facing similar issues as we did: The next steps to "if the hardware does not meet your needs just switch to a scaleset" should not be followed by
* friendly comments from other devs that face the same problem that guide you to 
* setting up linux build agents in the hope that they manage to complete within the microsoft enforced time limit
* make a fork of https://github.com/YannickRe/azuredevops-buildagents/ (which is referenced in discussion #5843 ) 
* adjust it to ones needs
* achieve varying degrees of sustainability - depending on the adjustments that needed to be made.

Switching to the scaleset should not take hundreds of developers world wide thousands of commits/hours to make it work.

In a perfect world, ready to use pipelines can be added directly from microsoft source, the only thing needed being a library group in devops where environment configuration (subscription, resource group,...) is added.

If that's the case I'm all in - but with the current proposal I fail every security audit and am better off building on-prem again.

**Comment by ddobranic** [comment]
@KlausLinzner did suggested repo from @erik-de-bont help?

**Comment by mikhailkoliada** [comment]
@KlausLinzner Hello!

Right now we do not provide support  other than for the use cases currently described in the docs (i.e. you can build your own flavour of the image using the specs from the repo and an Azure subscription). We also currently do not consider providing an alternative image as we do not see high demand for those from customers.
