### ISSUE TITLE
builds in container stop working after docker(moby) update to 23

### ISSUE THREAD

**Issue by since81** [actions/runner-images#7075]
### Description

builds in container stop working after docker(moby) update to 23

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: windows-2019
Version: 20230205.1
Included Software: https://github.com/actions/runner-images/blob/win19/20230205.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win19%2F20230205.1

### Is it regression?

yes, 20230129.2

### Expected behavior

I can run build tasks in container.

  - pwsh: |
      Write-Host "Set-TimeZone: W. Europe Standard Time"
      Set-TimeZone -Name "W. Europe Standard Time"
    displayName: Set-TimeZone

before 20230205.1:
Set-TimeZone: W. Europe Standard Time
Finishing: Set-TimeZone

### Actual behavior

after 20230205.1:
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "[http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.42/exec/e0225545d4d51ce61060595242da749fe73363381164db3211c4c31d9d20ba02/json"](http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.42/exec/e0225545d4d51ce61060595242da749fe73363381164db3211c4c31d9d20ba02/json%22): open //./pipe/docker_engine: The system cannot find the file specified.
##[error]Exit code 1 returned from process: file name 'C:\Windows\system32\docker.EXE', arguments 'exec -i   c7398eb16c791a8d75731730e0346cf181ac284177607008aad952a4285ea6e3 C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.
Finishing: Set-TimeZone

### Repro steps

- create pipeline
resources:
  containers:
    - container: test
      image: clouds365.azurecr.io/test:latest
stages:
  - stage: build
    displayName: building
    jobs:
      - job:
        pool:
          vmImage: windows-2019
        container: test
        steps:
          - pwsh: |
              Write-Host "Set-TimeZone: W. Europe Standard Time"
              Set-TimeZone -Name "W. Europe Standard Time"
            displayName: Set-TimeZone

- run
- output
Set-TimeZone: W. Europe Standard Time
Finishing: Set-TimeZone

**Comment by since81** [comment]
How can I use old version of image in builds?

**Comment by since81** [comment]
This issue is related to issue I created in September.
https://github.com/actions/runner-images/issues/6333

That time it was an update from docker to moby project, but Microsoft used alpha release build from master branch, which is 23.x, now.

Fix was update to stable 20.x version.

Now we reach  have same issue when 23.x released and installed.

Please fix it, this is blocking my builds.

**Comment by since81** [comment]
image  example
clouds365.azurecr.io/test:latest
which is stop working

**Comment by since81** [comment]
@ddobranic do you have any updates on this issue?

**Comment by since81** [comment]
Hi @ddobranic, @mikhailkoliada, @sergei-pyshnoi, @Alexey-Ayupov,

do you have any updates on this issue?

**Comment by ddobranic** [comment]
hi @since81 we are working on it. i will let you know as soon as possible. thank you for your patience.

**Comment by ddobranic** [comment]
@since81 I have tested on our latest image (20230213.1) and it is working:

![Screen Shot 2023-02-14 at 15 55 16](https://user-images.githubusercontent.com/101048884/218774720-7a53ef91-e01f-460c-97e5-7e5233c2b918.png)

Could you please try again?

**Comment by since81** [comment]
Hi @ddobranic,

thank you for your response.
Let me check when agent will be updated in my org.

Did you tried with image I provided?
clouds365.azurecr.io/test:latest

**Comment by ddobranic** [comment]
hi @since81 , yes i have tried your image but don't have access for it. image that was used for test is: 
mcr.microsoft.com/windows/servercore:1809
Looks like the problem was in the version of the Docker(Moby) which was [fixed](https://github.com/moby/moby/releases/tag/v23.0.1) recently in v23.0.1

**Comment by since81** [comment]
Hi @ddobranic,

can you please try with my container image on a new agent image version (in my org it is not available yet)
clouds365.azurecr.io/test:latest
I have enabled anonymous access.

With image 'mcr.microsoft.com/windows/servercore:1809' it was working, but with mine it is not.
Probably it is somehow related to size or layers or storage.

**Comment by since81** [comment]
Hi @ddobranic ,

image update did not help I still has this error
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "[http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.42/exec/d7012db24ab659fdcb1e24c144be9330cc92b99e52f4a0ad7b9acaafe4ea122d/json"](http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.42/exec/d7012db24ab659fdcb1e24c144be9330cc92b99e52f4a0ad7b9acaafe4ea122d/json%22): open //./pipe/docker_engine: The system cannot find the file specified.
##[error]Exit code 1 returned from process: file name 'C:\Windows\system32\docker.EXE', arguments 'exec -i   096c371bffccb2758ae5450a35181cd76affbeafcdf7ae53883905beba10816c C:\__a\externals\node\bin\node.exe C:\__w\_temp\containerHandlerInvoker.js'.
Finishing: Set-TimeZone

**Comment by since81** [comment]
When I am building new container, process exiting with error
unexpected EOF
##[error]The process 'C:\Windows\system32\docker.exe' failed with exit code 1

**Comment by since81** [comment]
Hi @ddobranic ,

can you please try with my container image on a new agent image version
clouds365.azurecr.io/test:latest

latest image does not work for me.

also I can run image locally with same version of docker, butit does not work on ms hosted agents.

**Comment by since81** [comment]
Hi @ddobranic, @mikhailkoliada, @sergei-pyshnoi, @Alexey-Ayupov,
do you have any update in this issue?

**Comment by ddobranic** [comment]
Hi @since81 , thank you for providing access to new image version. i tested this morning, and you are right, it is failing.
though, i think it is the problem with the image itself(image download took 11m48s).

**Comment by since81** [comment]
Yes, it is big, but it is normal for windows images.
Also it is working locally with version 23.x, and was working in azure hosted agent with version 20.x, till upgrade to 23.x.

**Comment by ddobranic** [comment]
> With image 'mcr.microsoft.com/windows/servercore:1809' it was working, but with mine it is not.
> Probably it is somehow related to size or layers or storage.

i would agree. based on [documentation](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources), we provide at least 14 GB of free space, but looks like it is not enough in this case.

**Comment by since81** [comment]
Issue fixed in moby release 23.0.2
