### ISSUE TITLE
Windows Server 2019 failing on Postgres installation

### ISSUE THREAD

**Issue by greha** [actions/runner-images#7076]
### Description

Windows Server 2019 image build fails during the postgres step.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/win19%2F20230129.2

### Is it regression?

No

### Expected behavior

Image build completes successfully,

### Actual behavior

Image build fails

> ==> vhd: Provisioning with powershell script: C:\agent\_work\28\s\virtual-environments\images\win/scripts/Installers/Install-PostgreSQL.ps1
    vhd: postgres
    vhd: root
==> vhd: You cannot call a method on a null-valued expression.
==> vhd: At C:\Windows\Temp\script-63e4a117-8784-e33d-4f41-52ff54842123.ps1:43 char:1
==> vhd: + $InstallerName = $InstallerUrl.Split('/')[-1]
==> vhd: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
==> vhd:     + FullyQualifiedErrorId : InvokeMethodOnNull
==> vhd:
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...

### Repro steps

Checked out the release from here https://github.com/actions/runner-images/releases/tag/win19%2F20230129.2
and run the build.

**Comment by mikhailkoliada** [comment]
Hello! Sync your main please, it has the fix.
