### ISSUE TITLE
Add libapache2-mod-php in Ubuntu 22.04 image

### ISSUE THREAD

**Issue by arvindpdmn** [actions/runner-images#7077]
### Tool name

libapache2-mod-php

### Tool license

Apache

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Compatible with default PHP installed in the image

### Brief description of tool

Ubuntu 22.04 image has Apache 2.4.52 installed and PHP 8.1.2 installed. However, Apache is unable to execute PHP scripts because `libapache2-mod-php` module is not installed. When I attempt to install this, lots of other packages are installed including PHP. This doesn't make sense since PHP is already installed. This installation takes about 2 minutes. 

The following commands were used:
```
  sudo add-apt-repository ppa:ondrej/php
  sudo apt-get update
  sudo apt install php libapache2-mod-php8.1
```

This leads to:
```
The following additional packages will be installed:
  libapache2-mod-php8.2 php8.1-bcmath php8.1-bz2 php8.1-cgi php8.1-cli
  php8.1-common php8.1-curl php8.1-dba php8.1-dev php8.1-enchant php8.1-fpm
  php8.1-gd php8.1-gmp php8.1-imap php8.1-interbase php8.1-intl php8.1-ldap
  php8.1-mbstring php8.1-mysql php8.1-odbc php8.1-opcache php8.1-pgsql
  php8.1-phpdbg php8.1-pspell php8.1-readline php8.1-snmp php8.1-soap
  php8.1-sqlite3 php8.1-sybase php8.1-tidy php8.1-xml php8.1-zip php8.2
  php8.2-cli php8.2-common php8.2-opcache php8.2-readline
Suggested packages:
  dh-php
Recommended packages:
  pkg-php-tools
The following NEW packages will be installed:
  libapache2-mod-php8.1 libapache2-mod-php8.2 php php8.2 php8.2-cli
  php8.2-common php8.2-opcache php8.2-readline
The following packages will be upgraded:
  php8.1-bcmath php8.1-bz2 php8.1-cgi php8.1-cli php8.1-common php8.1-curl
  php8.1-dba php8.1-dev php8.1-enchant php8.1-fpm php8.1-gd php8.1-gmp
  php8.1-imap php8.1-interbase php8.1-intl php8.1-ldap php8.1-mbstring
  php8.1-mysql php8.1-odbc php8.1-opcache php8.1-pgsql php8.1-phpdbg
  php8.1-pspell php8.1-readline php8.1-snmp php8.1-soap php8.1-sqlite3
  php8.1-sybase php8.1-tidy php8.1-xml php8.1-zip
31 upgraded, 8 newly installed, 0 to remove and 50 not upgraded.
Need to get 17.0 MB of archives.
After this operation, 26.3 MB of additional disk space will be used.
```

### URL for tool's homepage

https://packages.ubuntu.com/hu/jammy/ppc64el/libapache2-mod-php8.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ddobranic** [comment]
hello, @arvindpdmn! we have [removed](https://github.com/actions/runner-images/issues/6331) third party repo for PHP on Ubuntu 22.04, and recommend using [setup-php](https://github.com/shivammathur/setup-php) action for any customers who want to use any other (non-installed) versions of PHP or want to get latest PHP faster.

**Comment by arvindpdmn** [comment]
@ddobranic Thanks. I also found that using `sudo add-apt-repository ppa:ondrej/apache2` is better than `sudo add-apt-repository ppa:ondrej/php` if I just want to install the php apache module.

**Comment by farrukhahmed4220** [comment]
Any possibility of compiling it from the source?

**Comment by bmax911** [comment]
sudo add-apt-repository ppa:ondrej/apache2 I ran this, but Package 'libapache2-mod-php8.1' has no installation candidate. Anyone tried it before?

**Comment by roach-v** [comment]
> sudo add-apt-repository ppa:ondrej/apache2 I ran this, but Package 'libapache2-mod-php8.1' has no installation candidate. Anyone tried it before?

having the same issue. you find any solution?
