### ISSUE TITLE
limits.h not found on windows images

### ISSUE THREAD

**Issue by rhpvorderman** [actions/runner-images#7082]
### Description

A compilation on the runner fails: erasure_code\ec_base.c(30): fatal error C1083: Cannot open include file: 'limits.h': No such file or directory

I first thought this problem was related to windows-latest switching to windows-2022, but the problem occurs on both windows-2019 and windows-2022. This happened somewhere in the last 4 months (unfortunately I cannot be more specific) https://github.com/pycompression/python-isal/actions.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

   Image: windows-2022
  Version: 20230206.1

https://github.com/pycompression/python-isal/actions/runs/4062500426/jobs/7160603632

  Image: windows-2019
  Version: 20230205.1

https://github.com/pycompression/python-isal/actions/runs/4141544039/jobs/7161243674

### Is it regression?

yes, https://github.com/pycompression/python-isal/actions/runs/3279027306/jobs/5398088607 unfortunately the logs have expired

### Expected behavior

Limits.h is a C standard library file. Every C compiler should be able to find this without issue. It is described in the MSVC 2022 manual: https://learn.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170

### Actual behavior

Cannot find limits.h, a standard library file. This should never happen when compiling a C program.

### Repro steps

I use the matrix here to compile the ISA-L project:
https://github.com/pycompression/python-isal/blob/develop/.github/workflows/ci.yml#L55

**Comment by ddobranic** [comment]
hello @rhpvorderman, we will investigate.

**Comment by ddobranic** [comment]
@rhpvorderman i have tested using minimal c program using limits.h and did not encounter any issues.
maybe if you can provide minimal repro steps, i could try to help. or maybe you can try to reproduce it on that same minimal project which uses limits.h

**Comment by rhpvorderman** [comment]
Thanks. I will have a look again to see if I can narrow down the issue

**Comment by rhpvorderman** [comment]
I have found the issue. Turns out the Python package testing program `tox` had a complete rewrite. It did not pass the `INCLUDE` environment variable anymore. As a result the necessary includes could not be found during testing. I fixed it in the tox configuration. 

I am so sorry for bothering with you with this, the images are completely fine. Thank you for your time!
