### ISSUE TITLE
Feature Request: Trigger actions when the image in "runs-on" is changed.

### ISSUE THREAD

**Issue by nolanl** [actions/runner-images#7084]
### Description

In particular, when the "-latest" pointer changes to a newer version of the base OS.

It would also be cool to be able to trigger on more general updates (security, etc) updates to the base OS. It might also be useful to be able to trigger on installed tools changing.

I currently workaround the lack of this by scheduling a run once a month, but this is both wasteful and has some latency where the -latest has changed, but my scheduled action hasn't yet run.

The underlying motivation is that I want to have some confidence that when an action fails after a checkin, it is because of that checkin, not because the base OS changed in an incompatible way.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/nolanl/rp/actions/runs/4142153938

### Is it regression?

no

### Expected behavior

To have the ability to trigger actions when the underlying runner image changes.

### Actual behavior

AFAICT, there is no way to trigger actions when the underlying runner image changes.

### Repro steps

Search the docs for a trigger that runs when the underlying runner image changes. Fail to find anything better than the scheduled trigger workaround.

**Comment by mikhailkoliada** [comment]
Hello! Please report to https://github.com/actions/runner, this repository maintains image specs, but not the design approach
