### ISSUE TITLE
Add GPU Passthrough (Metal) for GitHub-hosted macOS runners

### ISSUE THREAD

**Issue by Gustl22** [actions/runner-images#7085]
### Tool name

Metal

### Tool license

Proprietary

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3

### Brief description of tool

Some tools such as Flutter 3.7 need GPU (Metal) support in order to execute the UI tests.
CC: @Steve-Glass 

Related:
#1779
https://github.com/actions/runner-images/issues/1779#issuecomment-707071183
#2014
Nested virtualization: #183

Flutter removes OpenGL support: https://github.com/flutter/flutter/issues/108304
According issue: https://github.com/flutter/flutter/issues/118469#issuecomment-1424390035
Apple Silicon / M1 support: https://github.com/github/roadmap/issues/528

### URL for tool's homepage

https://developer.apple.com/metal/

### Provide a basic test case to validate the tool's functionality.

```bash
name: test
jobs:
  macos:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - uses: bluefireteam/melos-action@main
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: ./packages/audioplayers/example/macos/Podfile.lock

      - name: Run Flutter integration tests
        working-directory: ./packages/audioplayers/example
        run: |
          flutter test -d macos integration_test/app_test.dart
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No this is a hardware or software restriction.
```

### Are you willing to submit a PR?

I don't think I can solve this

**Comment by ddobranic** [comment]
hello @Gustl22, thank you for your request. did you try to install the tool in runtime? how long will it take?

**Comment by Gustl22** [comment]
@ddobranic Yes I already linked that comment in the issue description, but it has been a while since then. There's always some way. The question is more the concrete _why it's not technically possible_ and if it's worth the effort 😅  
I created this due to https://github.com/actions/runner-images/issues/183#issuecomment-1412213172
Best regards :)

**Comment by mikhailkoliada** [comment]
Hello! It is currently impossible due to runners' design, there is no any ETA on feature like this.

**Comment by Gustl22** [comment]
@mikhailkoliada thank you! What do you mean by "impossible". As far as I'm aware the GPU on Apple Silicon chips is integrated. So it would only be a software limitation then. Would be helpful understanding, **why** something is not possible, instead of stating, that it is not possible. It's also ok, if GH does not make any profit from it (maybe).

**Comment by Gustl22** [comment]
@nebuk89 Do you also consider adding metal support in #2187. Seems that other providers also manage to give access to the Metal GPU. Apple has discontinued support for OpenGL, thus developers need an alternative to test their apps:
https://github.com/flutter/flutter/issues/120154#issuecomment-1500945622

**Comment by spyoungtech** [comment]
> Hello! It is currently impossible due to runners' design, there is no any ETA on feature like this.

@mikhailkoliada would you mind elaborating on this?

It may be helpful to know that [VMware](https://blogs.vmware.com/teamfusion/2023/07/vmware-fusion-2023-tech-preview.html) (since Sonoma) and [Parallels](https://kb.parallels.com/124095) (since Big Sur) now both support hardware acceleration via Metal, too.

**Comment by ptc-emaggio** [comment]
it would seem that metal support is now available in the Virtualization.framework https://developer.apple.com/videos/play/wwdc2022/10002/?time=644
