### ISSUE TITLE
larger-runners for ubuntu-latest missing GL implementation

### ISSUE THREAD

**Issue by runspired** [actions/runner-images#7088]
### Description

We are attempting to move our test suite from ubuntu-latest (stock) to a larger-runner with 16 cores (ubuntu-latest-16-cores). Our test suite runs fine on the former and cannot launch Chrome to run the tests on the latter.

I believe the issue is that no GL implementation is available. I've tried desktop/els/angle/gles GL configurations for chrome and all seem to hit issues with something not being present or working correctly.

chrome crashes on start. Have attempted a fair number of permutations of launcher flags trying to find one that can work on 16-core to no avail.

Out of the gate we receive this error:

```
 [0211/021348.733791:ERROR:socket_posix.cc(147)] bind() failed: Address already in use (98)
[0211/021348.778229:ERROR:devtools_http_handler.cc(309)] Cannot start http server for devtools.
[0211/021349.195513:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0211/021350.475686:WARNING:sandbox_linux.cc(385)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Some googling suggested that the dev tools error was due to our use of a stable remote-debugging-port, so I removed those two flags from our launcher. That proved to not be enough:

```
[Chrome] error
     Error: Browser exited unexpectedly
Stderr: 
 [0211/022847.893989:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0211/022848.471866:WARNING:sandbox_linux.cc(385)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Note the warnings here are not usually seen in our usage of `ubuntu-latest`.

Various debugging since led me to notice that there is no valid configuration for `--use-gl` on this image. The various options that would typically be passed each throws its own error.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.301.1'
Runner name: 'ubuntu-latest-16-cores_8563d6395ff9'
Runner group name: 'Larger Ubuntu Runners'
Machine name: 'runner'
Operating System
  Ubuntu
  [2](https://github.com/soxhub/auditboard-frontend/actions/runs/4149618746/jobs/7178697575#step:1:2)2.04.1
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 202[3](https://github.com/soxhub/auditboard-frontend/actions/runs/4149618746/jobs/7178697575#step:1:3)0122.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230122.1/images/linux/Ubuntu220[4](https://github.com/soxhub/auditboard-frontend/actions/runs/4149618746/jobs/7178697575#step:1:4)-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230[12](https://github.com/soxhub/auditboard-frontend/actions/runs/4149618746/jobs/7178697575#step:1:13)2.1
  ```

### Is it regression?

Image: ubuntu-22.04   Version: 20230206.1 https://github.com/soxhub/auditboard-frontend/actions/runs/4149193103/jobs/7177943990

### Expected behavior

ubuntu-latest and ubuntu-latest-16-cores to have the same overall image configuration such that chrome/chromedriver is launchable by testem with the same flags for both.

### Actual behavior

chrome crashes on start. Have attempted a fair number of permutations of launcher flags trying to find one that can work on 16-core to no avail.

I believe the issue is that no GL implementation is available. I've tried desktop/els/angle/gles GL configurations for chrome and all seem to hit issues with something not being present or working correctly.

### Repro steps

Example failed job (private repo) https://github.com/soxhub/auditboard-frontend/actions/runs/4149618746/jobs/7178697575

Repro: create a job on this image, attempt to launch chrome via testem.

I've tried various combinations of a number of flags:

```
  '--headless',
  '--incognito',
  // '--no-sandbox',
  '--disable-dev-shm-usage',
  // '--use-gl=angle',
  // '--disable-gpu',
  '--disable-software-rasterizer',
  '--mute-audio',
  // '--remote-debugging-port=9222',
  // '--remote-debugging-address=0.0.0.0',
  '--window-size=1440,900',
```

The configuration we usually use on `ubuntu-latest` is 

```
  '--headless',
  '--incognito',
  '--no-sandbox',
  '--disable-dev-shm-usage',
  '--disable-software-rasterizer',
  '--mute-audio',
  '--remote-debugging-port=9222',
  '--remote-debugging-address=0.0.0.0',
  '--window-size=1440,900',
```

**Comment by erik-bershel** [comment]
Hi @runspired, please provide short repro steps (simple workflow example or public repo) to investigate incident. And answer please couple more questions just to be sure that I did understood you correctly:
1) What was with same Chrome and ChromeDriver pair for Ubuntu20.04 standard runner runs? You said that "the warnings here are not usually seen in our usage of `ubuntu-latest`". But does it happened previously or not?
2) Is only the last specified larger runner affected by this error? Or were tests previously only done on standard runners?

**Comment by rajrku** [comment]
This seems to be an images issue on Larger runners. @samvantran - can you help with triaging this?

**Comment by runspired** [comment]
I can try to build a reproduction but it moved from being consistent to being intermittent, the frequency is increasing though. Feels very much like the hardware or images aren't in a consistent state. 

I'd be happy to help debug but I'm traveling today. @Wagenet could help from our end if needed.

**Comment by runspired** [comment]
I'm not sure what this was, but it went away after a time... we never did get to the root of it, it just started working.
