### ISSUE TITLE
iOS tests start failing after macos-12 runner image update to version 20230205.1

### ISSUE THREAD

**Issue by TomaszLizer** [actions/runner-images#7090]
### Description

After runner update to version 20230205.1 our unit tests suite started to fail - tests do not start running.
On same code tests ran successfully in runner image version: 20230125.4
Error returned by xcode:
```
Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. 
(Underlying Error: Test crashed with signal abrt before starting test execution. 
If you believe this error represents a bug, please attach the result bundle at /Users/runner/Logs/Test/Test-ContainerUnitTest-2023.02.10_17-35-39-+0000.xcresult)
```
Xcode version used: 14.1

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230205.1

### Is it regression?

20230125.4

### Expected behavior

Tests starts and run

### Actual behavior

Tests crashes on start or never launches

### Repro steps

No particular steps to reproduce.
Project we are running on github agent is quite large and complex.
Recently it started failing and it seems that failures started occurring after runner image was changed to never version (eg it now fails on commit on which it was passing 3 days ago with previous agent version).

**Comment by mikhailkoliada** [comment]
@TomaszLizer Hello! Please provide a minimal repo with repro-steps.

**Comment by TomaszLizer** [comment]
@mikhailkoliada Will try to provide example project with such issue, unfortunately cannot provide our particular project.
Btw, is there a way, to run Github Actions on runner with particular image version? This will help us validate if that is for sure root cause of our issues.

**Comment by erik-bershel** [comment]
@TomaszLizer only one runner image version is available at a time.

**Comment by mikhailkoliada** [comment]
Hello! I am going to close the issue for now, please file the new one or let us know here once repro steps are ready, we can not proceed otherwise :(

**Comment by TomaszLizer** [comment]
@mikhailkoliada @erik-bershel 
We have finally resolved that with prelaunching simulator on CI (using fastlane).
I would suspect this may be related to performance of CI agents as we weren't able to reproduce it locally on or smaller projects.

**Comment by TomaszLizer** [comment]
@asos-michaelwaterfall Exactly as you wrote I have added `prelaunch_simulator` as part of fastlane scan command.
My exact diff was adding that line: `prelaunch_simulator: true,` to fastlane scan invocation.
I am however not using `Scanfile` but using custom lane with scan invoked there.
