### ISSUE TITLE
Update/Add MacOS Venura 13.1

### ISSUE THREAD

**Issue by billnbell** [actions/runner-images#7096]
### Tool name

MacOS runner

### Tool license

13.1

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.1

### Brief description of tool

Please support MacOS 13.1 Ventura. Too replace macos-12-Readme.md

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
macOS 13!
```

**Comment by mikhailkoliada** [comment]
Duplicate of https://github.com/actions/runner-images/issues/6426
