### ISSUE TITLE
Still seeing "macOS-latest pipelines will use macOS-12 soon" message

### ISSUE THREAD

**Issue by ferdnyc** [actions/runner-images#7097]
### Description

Even though the `macos-12` migration is reportedly finished (#6384), and all of my macOS CI jobs did indeed run on macOS-12, my `macos-latest` pipeline run mere minutes ago still shows an annotation warning of the upcoming migration.

If the intention is just to inform people of the updated images, perhaps the message should be changed to something like:

> macOS-latest pipelines now run on macOS-12. For a list of software preinstalled in the new image, see https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: macos-12
  Version: 20230205.1

Build: https://github.com/BiglySoftware/BiglyBT/actions/runs/4160050654

### Is it regression?

No

### Expected behavior

No warning about migrations that have already happened

### Actual behavior

This annotation:

> macOS-latest pipelines will use macOS-12 soon. For more details, see https://github.com/actions/runner-images/issues/6384

Which is pretty confusing when the pipelines _are_ using macOS-12 already. 

### Repro steps

I assume, 
1. Create any CI pipeline
2. Run it on `macOS-latest`
3. See announcement of upcoming already-finished migration
 
I'm not aware of anything special in that run, to cause this.

**Comment by erik-bershel** [comment]
Hey @ferdnyc! I'll take a look soon at the current annotations config.

**Comment by mikhailkoliada** [comment]
Should be fixed!
