### ISSUE TITLE
Image version value is not set in the windows2022.json in the commit which is marked as latest

### ISSUE THREAD

**Issue by Technomann** [actions/runner-images#7102]
### Description

The commit which is marked latest has the "image_version" value set to "dev" in file windows2022.json. Because of this, when using VMs that were created from the generated VHD image, Azure Devops' "Initialize job" displays the image version as "dev".

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

-

### Expected behavior

-

### Actual behavior

-

### Repro steps

-

**Comment by mikhailkoliada** [comment]
Hello! The ImageVersion is a runner's property https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers /Update-ImageData.ps1. It is not changed via packer itself so it always will be with the `dev` version. If you want to have a custom, you must change the packer setting.

**Comment by erik-bershel** [comment]
Hey @Technomann, it is not a bug. A current state of the repository's main branch is not the same as the latest published runner image for any of the operating systems. In a time gap between any two deployments changes happening with our repo and with external repos too. Thus, it will not be fair enough to set the value of this label in the same way as the current latest release. For you brunch- or fork-based builds you may use any technically appropriate label value. To read more about azure-arm builder variables for packer: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#builder-variables
