### ISSUE TITLE
Ubuntu 22.04 (20230206): apt full-upgrade is broken

### ISSUE THREAD

**Issue by RoadRunnr** [actions/runner-images#7110]
### Description

Haveing a step in action with `apt update && apt full-upgrade -f` cause the action to fail with

```
Unpacking odbcinst1debian2:amd64 (2.3.11) ...
318
dpkg: error processing archive /tmp/apt-dpkg-install-9UxB5k/43-odbcinst1debian2_2.3.11_amd64.deb (--unpack):
319
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libodbcinst.so.2.0.0', which is also in package libodbcinst2:amd64 2.3.9-5
```

It is likely that this a problem in the  https://packages.microsoft.com/ubuntu/22.04/prod APT repository. However, the official GitHub image should not contain stuff that is broken by default.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20230206.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230206.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230206.1

**Failed Build**: https://github.com/RoadRunnr/playground/actions/runs/4181686447/jobs/7243882659#step:3:325

### Is it regression?

Yes, last build was in private repo

### Expected behavior

`apt full-upgrade` should not fail.

### Actual behavior

`apt full-upgrade` fails

### Repro steps

in an action:
1. use Ubuntu 22.04 as image
2. add a step  that does `apt update && apt full-upgrade -f`
3. watch it fail

**Comment by mikhailkoliada** [comment]
Hello!

It has been reported to Microsoft's linux repository, which is primary responsible for these packages: https://github.com/microsoft/linux-package-repositories/issues/39
