### ISSUE TITLE
Google Chrome tests failing on Ubuntu 22.04

### ISSUE THREAD

**Issue by markatky46** [actions/runner-images#7115]
### Description

Error has started since our last build 3 weeks ago. The test to describe Chrome fails with the following error. This is executed during the step: linux/scripts/installers/google-chrome.sh

   azure-arm.build_vhd: Running tests from '/imagegeneration/tests/Browsers.Tests.ps1'
    azure-arm.build_vhd: Describing Chromium
    azure-arm.build_vhd:   [-] Chromium 113ms (82ms|31ms)
    azure-arm.build_vhd:    Command 'chromium-browser --version' has finished with exit code
    azure-arm.build_vhd:        chromium-browser: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
    azure-arm.build_vhd:    at "chromium-browser --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Browsers.Tests.ps1:39
    azure-arm.build_vhd:    at <ScriptBlock>, /imagegeneration/tests/Browsers.Tests.ps1:39
    azure-arm.build_vhd: Tests completed in 559ms
    azure-arm.build_vhd: Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 7

Attempted 4 builds today all failing with same error. Latest main branch pulled each build.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: 20230206.1

No public link to build.

### Is it regression?

no

### Expected behavior

Describing Chromium passes successfully and build moves onto scripts/installers/google-cloud-sdk.sh

### Actual behavior

Build fails at Describing Chromium with: 
Command 'chromium-browser --version' has finished with exit code
chromium-browser: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

### Repro steps

Run a build and call linux/scripts/installers/google-chrome.sh via azure-arm build.

**Comment by erik-bershel** [comment]
Hey @markatky46!
Already in progress here: https://github.com/actions/runner-images/pull/7113

**Comment by markatky46** [comment]
Thanks for the swift response @erik-bershel, sorry i missed the other fix.

**Comment by mikhailkoliada** [comment]
Should be fixed.
