### ISSUE TITLE
Get 

### ISSUE THREAD

**Issue by fsaryazdi** [actions/runner-images#7120]
### Description

The Get-PowerShellModules function in images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1 throws an exception for Multiple versions of one of powershell modules (I am guessing that's AWSpowershell module, based on the version numbers that I see). 
Here's the [function ](https://github.com/actions/runner-images/blob/releases/win19/20230214/images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1#:~:text=%7D-,function%20Get%2DPowerShellModules%20%7B,%7D,-function%20Get%2DCachedDockerImages) which uses "[ToolVersionsListNode](https://github.com/actions/runner-images/blob/releases/win19/20230214/helpers/software-report-base/SoftwareReport.Nodes.psm1#:~:text=class%20ToolVersionsListNode)" class.
In that class, there is [method ](https://github.com/actions/runner-images/blob/releases/win19/20230214/helpers/software-report-base/SoftwareReport.Nodes.psm1#:~:text=%5Bvoid%5D-,ValidateMajorVersionRegex,-()%20%7B)that throws this exception and that causes my pipeline to fail and abort. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2022.12.05-284241

### Is it regression?

yes - It was working before adding those helper function for software-report-base

### Expected behavior

To provide a list of versions for powershell modules, rather than throwing an exception

### Actual behavior

The new helper file "software-report-base/SoftwareReport.Nodes.psm1" throws an exception from the following Class:
class ToolVersionsListNode: BaseToolNode {
    [ValidateNotNullOrEmpty()]
    [String[]] $Versions

    [Regex] $MajorVersionRegex

    [ValidateSet("List", "Inline")]
    [String] $ListType

    ToolVersionsListNode([String] $ToolName, [String[]] $Versions, [String] $MajorVersionRegex, [String] $ListType): base($ToolName) {
        $this.Versions = $Versions
        $this.MajorVersionRegex = [Regex]::new($MajorVersionRegex)
        $this.ListType = $ListType
        $this.ValidateMajorVersionRegex()
    }

    [String] ToMarkdown([Int32] $Level) {
        if ($this.ListType -eq "Inline") {
            return "- $($this.ToolName): $($this.Versions -join ', ')"
        }

        $sb = [System.Text.StringBuilder]::new()
        $sb.AppendLine()
        $sb.AppendLine("$("#" * $Level) $($this.ToolName)")
        $this.Versions | ForEach-Object {
            $sb.AppendLine("- $_")
        }

        return $sb.ToString().TrimEnd()
    }

    [String] GetValue() {
        return $this.Versions -join ', '
    }

    [String] ExtractMajorVersion([String] $Version) {
        $match = $this.MajorVersionRegex.Match($Version)
        if (($match.Success -ne $true) -or [String]::IsNullOrEmpty($match.Groups[0].Value)) {
            throw "Version '$Version' doesn't match regex '$($this.PrimaryVersionRegex)'"
        }

        return $match.Groups[0].Value
    }

    [PSCustomObject] ToJsonObject() {
        return [PSCustomObject]@{
            NodeType = $this.GetType().Name
            ToolName = $this.ToolName
            Versions = $this.Versions
            MajorVersionRegex = $this.MajorVersionRegex.ToString()
            ListType = $this.ListType
        }
    }

    static [ToolVersionsListNode] FromJsonObject([Object] $JsonObj) {
        return [ToolVersionsListNode]::new($JsonObj.ToolName, $JsonObj.Versions, $JsonObj.MajorVersionRegex, $JsonObj.ListType)
    }

    hidden [void] ValidateMajorVersionRegex() {
        $this.Versions | Group-Object { $this.ExtractMajorVersion($_) } | ForEach-Object {
            if ($_.Count -gt 1) {
                throw "Multiple versions from list '$($this.GetValue())' return the same result from regex '$($this.MajorVersionRegex)': $($_.Name)"
            }
        }
    }
}
That causes my pipeline to stop and abort.

### Repro steps

Run a Window2019 AMI build process on Azure Devops.

**Comment by erik-bershel** [comment]
Hey @fsaryazdi 
Are you use default code from repo or you have some changes made by yourself?

**Comment by erik-bershel** [comment]
@fsaryazdi 
I checked - we do not experience the same problems when building. Updating the repository to the current state will solve the issue. If the set of tools of your assembly differs from ours, then you need to make appropriate changes to the software reporter module. Or disable it if it is not urgently needed.
