### ISSUE TITLE
Chrome test failing with odd error

### ISSUE THREAD

**Issue by naikrovek** [actions/runner-images#7122]
### Description

I adapt these build templates for my own use, as well as for building on AWS instead of Azure.  (Thank you for your needless security rules, $employer.)

After about 20 minutes Chromium is installed and tested; this test fails with this error: 

```
amazon-ebs:    Command 'chromium-browser --version' has finished with exit code
amazon-ebs:        chromium-browser: error while loading shared libraries: libnss3.so.1d: cannot open shared object file: No such file or directory
```

note that that file extension is 1d, which seems very odd to me.  

Nothing I'm doing in my customizations are anywhere near chromium, so I'm wondering if there is something upstream somewhere causing this.

Also, most references to this file (with the extension I find odd) are from 2017 or so.  Maybe an older version of Chromium is being installed by mistake?  I recall a bug like this happening here a month or two ago.

Also, while you're reading, I just want to say "Thank you" for keeping these templates open, so that folks like myself can use them.  This is very much appreciated.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I'm building an image, not using one.

### Is it regression?

unknown

### Expected behavior

Chromium would be installed correctly and would test successfully.

### Actual behavior

Chromium is missing a dependency or is not installed correctly, causing a failing test.

### Repro steps

I do not believe that anything I'm doing is causing this.

Simply build the image as-is and Chromium should fail.  I really hope this isn't just me...

**Comment by erik-bershel** [comment]
Hi @naikrovek how old is your branch? Take a look here: https://github.com/actions/runner-images/pull/7113. Looks like you catch the same issue with Google Chrome installer but from other side.

**Comment by mikhailkoliada** [comment]
@naikrovek this error has been fixed by what @erik-bershel has mentioned, please sync your fork and try again :)
