### ISSUE TITLE
libxml2 not found on latest macos-12

### ISSUE THREAD

**Issue by jcamiel** [actions/runner-images#7128]
### Description

 A simple Rust sample using libxml is not building anymore on latest `macos-12`.

The sample build is KO with:

```
  Image: macos-12
  Version: 20230214.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230214.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230214.2 
```

The sample build is OK with
```
  Image: macos-12
  Version: 20230205.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230205.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230205.1
```

A reproductible sample is available at <https://github.com/jcamiel/testxml2.git> with a build action. The build is failing for latest `macos-12`.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: macos-12
  Version: 20230214.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230214.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230214.2 

### Is it regression?

Yes, OK with 20230205.1, KO with 20230214.2

### Expected behavior

The sample should build without error message.

### Actual behavior

The sample fails to build with the following error message:

```
thread 'main' panicked at 'Could not find libxml2.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libxml-0.3.1/build.rs:38:5
```

### Repro steps

1. Run the build action of <https://github.com/jcamiel/testxml2.git>

**Comment by jcamiel** [comment]
Maybe related to https://github.com/actions/runner-images/pull/7125

**Comment by Blacksmoke16** [comment]
Confirmed #7125 fixes things. Was getting a similar error but for `libssl`. Manually installing `pkg-config` via brew allowed my program to correctly resolve that lib.

**Comment by erik-bershel** [comment]
Hey @jcamiel and @Blacksmoke16. We working on that issue already. Should be fixed in the next release. Before it you may avoid that error with manual install of dependencies or pkg-config package in runtime with any of available methods.

**Comment by sblondon** [comment]
> Was getting a similar error but for `libssl`.

For a job failure with ssl missing : https://github.com/python/cpython/actions/runs/4201522041/jobs/7289697590

The Runner Image Version is 20230214.2.
The working job executed few day before : https://github.com/python/cpython/actions/runs/4179085476/jobs/7238623120 (Runner Image Version is 20230205.1).

**Comment by mikhailkoliada** [comment]
Deployed :)
