### ISSUE TITLE
Run Stuck at "Complete job"

### ISSUE THREAD

**Issue by aqeelat** [actions/runner-images#7144]
### Description

I have a run that has finished but is still showing up as running.

This doesn't happen very often (it only happened 3 or 4 times to me over the past 6 months)

This issue was resolved while I was writing this ticket, but it would still like to have it documented.

![image](https://user-images.githubusercontent.com/5212744/219940550-9742b224-c29b-4c50-b414-92c632064c82.png)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

version: 2.301.1
I don't have a public example 

### Is it regression?

No

### Expected behavior

It should report its status.

### Actual behavior

Stuck.

### Repro steps

Run build.
Wait.

**Comment by mikhailkoliada** [comment]
Please report to the https://github.com/actions/runner repo, this repo only maintains image specs only.
