### ISSUE TITLE
Update yarn to 3.4.1

### ISSUE THREAD

**Issue by lusarz** [actions/runner-images#7145]
### Tool name

Yarn

### Tool license

https://github.com/yarnpkg/berry/blob/master/LICENSE.md

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.4.1

### Brief description of tool

https://yarnpkg.com/getting-started/migration
https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

I'm not yet sure

**Comment by mikhailkoliada** [comment]
Hello, as we are following the stable-only (LTS) release strategy for nodejs itself, we are installing the rock stable yarn as well. Currently there are no plans to switch to more recent version (at least for now).

**Comment by SchulteMarkus** [comment]
Yarn 1 is not LTS, it's just old. There is no Yarn LTS policy. 

> Once done, the 1.x branch will officially enter maintenance mode - meaning that it won't receive further releases from me except when absolutely required to patch vulnerabilities.
https://dev.to/arcanis/introducing-yarn-2-4eh1

Not only was Yarn 2 released ~three years ago (should be rock stable), even [Yarn 3 is out there](https://dev.to/arcanis/yarn-3-0-performances-esbuild-better-patches-e07), aging ~two years  (should be rock stable, too).

You should upgrade to latest Yarn, 3.6 for time being.

**Comment by HUMBERP** [comment]
May you have seen that on https://github.com/yarnpkg/yarn they are telling the v1 is frozen and features and bugfixes are now on https://github.com/yarnpkg/berry ...
![image](https://github.com/actions/runner-images/assets/41609186/ccf9a2f3-29d3-442e-8630-3d42d6a95517)
