### ISSUE TITLE
Jobs fail with error code 143

### ISSUE THREAD

**Issue by Mehdi-Bendriss** [actions/runner-images#7146]
### Description

For a job where I allocate LXD containers for an integration test. The job consistently fails as soon as I get to the 3rd allocated unit, with an error `143`.

Following [this](https://github.com/actions/runner-images/issues/6680) similar thread, It seems it has to do with the resources of the runner. 

Something worth mentioning is that I disable the swappiness of the runner due to the requirements of the software running `sysctl -w vm.swappiness = 0`.

It doesn't seem like there is a straightforward way to investigate it from my side. Would it be possible, in the case of this specific job, to know exactly what the culprit is?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: ubuntu-22.04
Version: 20230206.1
```

[Failed Job](https://github.com/canonical/opensearch-operator/actions/runs/4197264691/jobs/7279356482#step:4:123)
[Indefinitely hanging job](https://github.com/canonical/opensearch-operator/actions/runs/4226369064/jobs/7339737059)

### Is it regression?

No - it's been failing consistently when provisioning a 3th LXD container. Occasionally the job will run forever (up to ~6h or so)

### Expected behavior

Build / integration tests should pass 

### Actual behavior

Error 143 when trying to allocate a new (3rd) LXD container on the runner.
In some other case, it will indefinitely hand (for hours)

### Repro steps

Run the `Integration tests for HA (lxd)` job in the [branch of the repo](https://github.com/canonical/opensearch-operator/tree/horizontal-scale-down), i.e via a PR -- the pipeline yaml can be found [here](https://github.com/canonical/opensearch-operator/blob/horizontal-scale-down/.github/workflows/ci.yaml#L66-L86)

**Comment by mikhailkoliada** [comment]
Hello, please provide minimal repro-steps and yaml snippets to reproduce the issue :)

**Comment by Mehdi-Bendriss** [comment]
@mikhailkoliada updated, thanks :)

**Comment by erik-bershel** [comment]
Hey @Mehdi-Bendriss! May I ask you to run the same pipeline again once? I need it to get new logs for investigation.

**Comment by mikhailkoliada** [comment]
@Mehdi-Bendriss please feel free to reach us again if the problem persists with a link of a workflow run, we will gladly help you. I am going to close it for now due to inactivity.

**Comment by tillbrodbeck-oviva** [comment]
Hi can you please update here, what was the reason for the error 143? Thanks a lot in advance

**Comment by higaski** [comment]
Same issue, have had a reuseable workflow which compiled a rather small C++ example in parallel. Copy/pasting the workflow and no longer building in parallel fixed whatever it was...

My best guess at the moment is that the free tier runners are now on 1GB of RAM due to the current memory prices... 😆

**Comment by braboobssiere** [comment]
i tried to transfer >=3 gb file with ftp and it always failed :( even with swapfile set to 8gb

it used to be able to do ~10gb file

**Comment by diego-escribano** [comment]
Did people get any resolution on this? we are having the same issue. 1/5 pipelines executions now failed because of this.

**Comment by WitchAurora** [comment]
> Did people get any resolution on this? we are having the same issue. 1/5 pipelines executions now failed because of this.

Yes https://github.com/erraggy/oastools/commit/cf95c456714ac81fe68dd176844d31620e75a381
