### ISSUE TITLE
Is libssl required for sqlpackage in Ubuntu 22.04?

### ISSUE THREAD

**Issue by zedzedzed** [actions/runner-images#7147]
### Description

Apologies if this is not the correct issue type.

As per issue titlte, I'm wondering if libssl is required for sqlpackage on Ubuntu 22.04? Here is the code reference:

https://github.com/actions/runner-images/blob/09baf89e70d403d052bc9089b6fddc4ba31e053c/images/linux/scripts/installers/sqlpackage.sh#L11-L15

The comment mentions it as a dependency however, I'm not able to find references to libssl at https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15. I've also downloaded onto an 22.04 installation and checked it with ldd but libssl doesn't appear either:

```
michael@dev:~/sqlpackage$ ./sqlpackage /Version
16.1.8089.0
michael@dev:~/sqlpackage$ ldd ./sqlpackage
	linux-vdso.so.1 (0x00007ffeb0fc6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9b5e890000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9b5e88b000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9b5e661000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9b5e57a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9b5e55a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9b5e330000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9b5e8c3000)
```

It was brought across from the `powershellcore.sh` installer as per https://github.com/actions/runner-images/commit/536cfa24b0714ec26c8b46129913efa22562fd8e

If it is a valid dependency for sqlpackage, can it not use the latest libssl3 as provided in 22.04?

If not a valid dependency, I would suggest to remove the code block to keep it clean and accurate for sqlpackage.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/a

### Is it regression?

No

### Expected behavior

Sqlpackage to continue to operate with accurate dependencies.

### Actual behavior

N/a

### Repro steps

None

**Comment by bogdan-damian-bgd** [comment]
@zedzedzed thanks, we'll take a look on it.

**Comment by mikhailkoliada** [comment]
Looks like the dependency is no longer needed, so we removed it, thanks!
