### ISSUE TITLE
Azure CLI version 2.45.0 fails on pipeline agents

### ISSUE THREAD

**Issue by laurynasr** [actions/runner-images#7151]
### Description

All images were recently updated with Azure CLI version 2.45.0, which has a dependency on a broken package and fails on any command
```
##[error]D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
```

![image](https://user-images.githubusercontent.com/18733763/220109536-1205143c-91fb-4fe0-964f-0a77c7f13ec6.png)

Related issues:
https://github.com/Azure/azure-cli/issues/25406
https://github.com/Azure/azure-cli/issues/25505
https://github.com/paramiko/paramiko/issues/2038

I did not explicitly test the `ubuntu-18.04`, `ubuntu-20.04` or `windows-2019` images but Az CLI was updated on them as well.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230214.1
Included Software: https://github.com/actions/runner-images/blob/win22/20230214.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230214.1

Image: ubuntu-22.04
Version: 20230217.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230217.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230217.1

### Is it regression?

Yes.
Previous working image: https://github.com/actions/runner-images/releases/tag/win22%2F20230206.1

### Expected behavior

Successful `az cli` commands should not report any messages to stderr

### Actual behavior

`az cli` commands report an error to stderr

```
##[error]D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
```

### Repro steps

Run any pipeline that is using `AzureCLI@2` task on Azure hosted agent

**Comment by kwacks** [comment]
We've have this same problem, since last Thursday. We even opened a support ticket with Microsoft and none of them could figure out what was going on.
It's still happening, we've had to resort to manually deploying builds.
Following for updates.

**Comment by Robar666** [comment]
Same here, we currently can't deploy via Azure DevOps.

**Comment by mikhailkoliada** [comment]
Hello! Please report this issue to the  https://github.com/microsoft/azure-pipelines-tasks repo. The task should not generate an error exit code on a deprecation warning, moreover, I see the warning has been around for a while, so at least it should be worked-around somehow I believe.

**Comment by laurynasr** [comment]
The actual problem is with Azure CLI and was already reported in https://github.com/Azure/azure-cli/issues/25406. The task only fails when `failOnStandardError` is set to `true` -- which is working by design. What's not by design is that `az cli` writes unrelated warnings to stderr, and that only started happening since version 2.45.0 -- which was included in the latest release of agent images. I filed the issue against this repository because the issue can be fixed very easily by reverting the images back to using Azure CLI 2.44.1 -- see https://github.com/actions/runner-images/pull/7132

**Comment by mikhailkoliada** [comment]
Lets preserve it open then, as far as I understand the fix is going to be out rather soon, downgrading here is only viable with the usual release cycle, which is the end of the next week I guess. I will double check with Microsoft on their plans.

**Comment by tullydwyer** [comment]
Please roll Azure CLI back to`2.44.1`, **all** pipelines in Azure DevOps that use the Azure CLI in the MS hosted `windows-2022` image are broken (lots) with no simple workaround.

The next update for Azure CLI may not be till early March?: https://github.com/Azure/azure-cli/issues/25406#issuecomment-1433251900

Are we able to specify a previous version of the of the `windows-2022` agent?

**Comment by RamakantDataGuy** [comment]
We are on the same boat. All our pipelines with task AZCLI@2 are broken

**Comment by RamakantDataGuy** [comment]
If it helps anyone using azcli@2 task :
Just before your AZ Cli task install the version that works for you using bash.
I have just tried and it works. I am rolling back to my previous working az cli version 2.44.1

task: Bash@3
inputs:
targetType: 'inline'
script: |
# Write your commands here

pip install azure-cli==2.44.1
displayName: "Install AZ CLI 2.44.1"

**Comment by mikhailkoliada** [comment]
We will update az-cli as soon as Microsoft will release a fix, otherwise we are completely depending on upstream. We will not be able to provide downgraded az-cli version. For now I am going to close the issue as there is no more we could help with at the moment.
