### ISSUE TITLE
Connect-AzContainerRegistry doesn't work on Windows, does in Ubuntu

### ISSUE THREAD

**Issue by xaviervv** [actions/runner-images#7152]
### Description

I was doing some major refactoring for work in our templates, and to speed up the process decided to host a few agents on my local vms at home. 

Until now I was using microsoft hosted agents (ubuntu-latest). Nothing changed, besides that my local build agent was a windows one. 

I then switched the working scripts over to windows-latest as a test, and I had the same issue as I do on my local vm agents.

My scripts kept failing at Connect-AzContainerRegistry with error: 
##[error]The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Error response from daemon: Get "[https://crsymetahybrid.azurecr.io/v2/"](https://crsymetahybrid.azurecr.io/v2/%22): unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
##[error]PowerShell exited with code '1'.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-latest: 
Agent name: 'Hosted Agent'
Microsoft Windows Server 2022 - windows-2022 - 20230214.1
Current agent version: '2.217.2'
Current image version: '20230214.1'

### Is it regression?

not sure

### Expected behavior

No errors, being able to login with a login success message as I do for ubuntu hosted.

### Actual behavior

Getting logged into acr and a Login success message

### Repro steps

Create a pipeline with an AzurePowershell@5 task that calls: Connect-AzContainerRegistry -Name <insert-cr-name-without-microsoft-postfix-for-url>

**Comment by xaviervv** [comment]
Remark: 

I did log in on the self-hosted vm
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Clear-AzContext -Scope Process
Connect-AzAccount -ServicePrincipal -Tenant <id> -Credential <System.Management.Automation.PSCredential

The provided credential was the app id (used by the devops/arm service connection) and a newly generated secret for testing purposes

I could connect to Azure. 
Upon executing 'Connect-AzContainerRegistry -Name <name> ' I was able to login and pull an image. 

Yet the pipeline kept failing due to the error as mentioned above: Get "[https://crsymetahybrid.azurecr.io/v2/"](https://crsymetahybrid.azurecr.io/v2/%22): unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.

**Comment by bogdan-damian-bgd** [comment]
Hi @xaviervv, could you please provide some more clear repro steps like a simple workflow and logs?

**Comment by sergei-pyshnoi** [comment]
Hello @xaviervv. Sorry for the late response. We have tested and come to the conclusion that problem in  `AzurePowershell@5` task. In pipeline where we used the "az" module directly in `PowerShell@2` task, connection to container registry was successful. Unfortunately, problem with `AzurePowershell@5` is out of scope of our responsibility, but you can create issue in [azure-pipelines-tasks repo](https://github.com/microsoft/azure-pipelines-tasks) . For now I close the issue, but if you have question, you can freely ask it in this tread.
