### ISSUE TITLE
ubuntu 20.04 unixodbc-dev package is broken

### ISSUE THREAD

**Issue by sei-eschwartz** [actions/runner-images#7155]
### Description

The ubuntu 20.04 image contains a custom package for `unixodbc-dev` 2.3.11 which is not distributed with stock Ubuntu.  Stock Ubuntu 20.04 only contains 2.3.6-0.1build1.  The version in the runner image is borked:

```
+ gcc -E /usr/include/sqltypes.h
/usr/include/sqltypes.h:56:10: fatal error: unixodbc.h: No such file or directory
   56 | #include "unixodbc.h"
      |          ^~~~~~~~~~~~
```

[Log](https://dev.azure.com/seipharos/pharos/_build/results?buildId=1419&view=logs&j=4ece0760-d5f8-52a7-a3af-a3541f4c3f53&t=fa2f8c11-70c8-5e2f-c3de-82e43840daa8&l=525)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Runner Image
Image: ubuntu-20.04
Version: 20230217.1
```

https://dev.azure.com/seipharos/pharos/_build/results?buildId=1419&view=logs&j=4ece0760-d5f8-52a7-a3af-a3541f4c3f53&t=fa2f8c11-70c8-5e2f-c3de-82e43840daa8&l=525

### Is it regression?

Unsure

### Expected behavior

The `unixodbc-dev` package should not include non-existent files.

`gcc -E /usr/include/sqltypes.hpp` should not fail.

### Actual behavior

`sqltypes.hpp` in the `unixodbc-dev` package includes the non-existent file `unixodbc.h`

`gcc -E /usr/include/sqltypes.hpp` fails because of the missing file.

### Repro steps

1. Run `gcc -E /usr/include/sqltypes.hpp`

**Comment by mikhailkoliada** [comment]
Hello!
<img width="797" alt="image" src="https://user-images.githubusercontent.com/88318005/220158570-02796491-e7c9-494f-8f69-cd10de999d3e.png">

Microsoft repo comes with higher priority. If you need older version, you need. to patch your pipeline to give the stock repo higher priority. We are unable to change this on our side, lots of important software come from that repository.

**Comment by sei-eschwartz** [comment]
To be clear, the version is not the problem. The package in the Microsoft repository appears to be broken because it is missing a required file. Is this not the proper place to file a bug about that?

I have already worked around this in my project.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mikhailkoliada** [comment]
@sei-eschwartz oh, I found the report. Other than workaround, please follow https://github.com/microsoft/linux-package-repositories/issues/36, and we will too :)
