### ISSUE TITLE
[Reopening the issue #7158] : After the latest node upgrade on azure devops , lerna with an older version 3.22.1 fails to work. Its considering the latest version 6.5.1

### ISSUE THREAD

**Issue by geetikaharlalka22** [actions/runner-images#7165]
### Description

After the latest upgrade , the build pipelines are breaking with an older node version 10.16.3 and lerna 3.22.1 . The global packages have the latest version and refuse to get uninstalled and run on the specific version . This is causing the build pipeline to break as our code is incompatible with the new versions .

Request to provide a way to get this working to unblock us

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://user-images.githubusercontent.com/56873325/220364574-4cc686f7-eaf0-47b6-b746-08bec6dfa887.png)

The Image where this does work

![image](https://user-images.githubusercontent.com/56873325/220364674-bcea86e4-bb76-45e0-a7d6-0dc419b5390a.png)

We have tried to use the setup-node to specify the version we need
![image](https://user-images.githubusercontent.com/56873325/220364880-c00f1d70-964e-4bd2-b3f0-183849a2f6d1.png)

### Is it regression?

yes

### Expected behavior

If we try to use the node 10.16.3 and **lerna** 3.22.1 version it should install and allow the system to use the specified version rather than imposing the latest version

### Actual behavior

It always uses **lerna** 6.5.1 even if you try to uninstall and install the version you require i.e 3.22.1. 

It is able to pick the node version supplied i.e '10.16.3'  but with **lerna** its not picking the version supplied i.e 3.22.1. Request you to help here 

Request you to please not close the issue 

### Repro steps

Have a task to install node 10.16.3
Then add a task to install the lerna version 3.22.1 in monorepo directory
add another powershell task and try to execute the script 'lerna bootstrap --hoist" . It throws the below error
![image](https://user-images.githubusercontent.com/56873325/220364379-d64818a8-c60e-408f-8993-27e789c2e08c.png)

Find the dependencies that we installing 
![image](https://user-images.githubusercontent.com/56873325/220367437-b3c93ff5-eefe-48f8-bed0-60c9dc4f08dc.png)

**Comment by sergei-pyshnoi** [comment]
Hello @geetikaharlalka22, we will take a look.

**Comment by geetikaharlalka22** [comment]
Hello @sergei-pyshnoi  we have managed to get our build pipeline working . The issue here was the Lerna 6.5.1 expects a new syntax i.e **npx** lerna bootstrap --hoist . Which was throwing off the pipeline . On adding that it is now able to pick up the version specified in package.json and build our packages . Hence closing the issue .
