### ISSUE TITLE
Vulnerabilities reported on GitHub Actions Runner file path.

### ISSUE THREAD

**Issue by bab01025** [actions/runner-images#7167]
### Description

Attached the vulnerability report for assistance and recommendation for this and going forward.

[VulnerabilitiesReport-GitHubActionsRunner.xlsx](https://github.com/actions/runner-images/files/10795350/VulnerabilitiesReport-GitHubActionsRunner.xlsx)

Remediation per attached document is as below, if so please assistance on the steps and process on updating Node.js.
The vulnerability can be remediated by updating Node.js to 12.22.11 or higher."
The vulnerability can be remediated by updating Node.js to 12.22.9 or higher."
The vulnerability can be remediated by updating Node.js to 16.17.1 or higher."
The vulnerability can be remediated by updating Node.js to 16.18.1 or higher."

Updating to the above, on checking the node version by executing "node -v" command got the below result.
"-bash: node: command not found"

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://user-images.githubusercontent.com/80772553/220398358-0b5f07e8-e71d-41c7-9504-1afebfd58c72.png)

### Is it regression?

no

### Expected behavior

vulnerability remediation version

### Actual behavior

vulnerability reported under actions-runner file path

### Repro steps

![image](https://user-images.githubusercontent.com/80772553/220398784-e451a74a-e820-4a11-afa0-e5a111f9f722.png)

Followed the instruction as per the above attached screen shot. But vulnerability reported on the extracted path.

**Comment by mikhailkoliada** [comment]
Hello! Please report to https://github.com/actions/runner, this repository only contains specs for GitHub / Microsoft hosted runners
