### ISSUE TITLE
PlatformImageNotFound : The platform image xxxxxxx is not available

### ISSUE THREAD

**Issue by icornett** [actions/runner-images#7170]
### Description

It appears that the CI scripts that are provided with this repo are failing due to the inability to find the platform image to start with.   The script runs fine locally.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '2.217.2'

### Is it regression?

unknown

### Expected behavior

VHD/Managed Image should build when script is invoked and find the base OS image specified

### Actual behavior

```
==> azure-arm.build_vhd: Running builder ...
==> azure-arm.build_vhd: Getting tokens using client secret
==> azure-arm.build_vhd: Getting tokens using client secret
    azure-arm.build_vhd: Creating Azure Resource Manager (ARM) client ...
==> azure-arm.build_vhd: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options
==> azure-arm.build_vhd: Getting source image id for the deployment ...
==> azure-arm.build_vhd: Creating resource group ...
==> azure-arm.build_vhd: Validating deployment template ...
==> azure-arm.build_vhd: Deploying deployment template ...
==> azure-arm.build_vhd: ERROR: -> DeploymentFailed : At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
==> azure-arm.build_vhd: ERROR:   -> Conflict
==> azure-arm.build_vhd: ERROR:   -> ResourceDeploymentFailure : The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.
==> azure-arm.build_vhd: ERROR:     -> PlatformImageNotFound : The platform image 'canonical:0001-com-ubuntu-server-jammy:22_04-lts:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile
```

### Repro steps

1. Fork repo
2. git pull upstream main && git push origin main
3. Run Ubuntu2204.yml or Win2019.yml CI scripts
4. Error occurrs

**Comment by mikhailkoliada** [comment]
Hello! The CI scripts you mentioned are not intended for external usage without any prior preparations. If you need to create a custom image please follow this guide: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md
