### ISSUE TITLE
Wron nodejs interpreter in ubuntu-22.04

### ISSUE THREAD

**Issue by arobenko** [actions/runner-images#7171]
### Description

I have a WebAssembly code tested with nodejs in ubuntu-22.04 system in github actions. After some cosmetic and unrelated updates the same unittests started failing. Short investigation showed that the used nodejs interpreter is taken from "/usr/local/bin", while I expect it to be taken from the  "/usr/bin" and provided by the ubuntu repositories (installed with sudo apt install).

If the /usr/local/bin/node is expected to be there and not a sign of a security breach, then it shouldn't take priority over the official system one. Otherwise its environment interferes.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/commschamp/commsdsl/actions/runs/4214812766/jobs/7315518038#step:9:950

### Is it regression?

yes, https://github.com/commschamp/commsdsl/actions/runs/4178844540

### Expected behavior

The following cmake code is expected to find "/usr/bin/node", instead of "/usr/local/bin/node".
```
find_program (NODE_EXECUTABLE NAMES node nodejs REQUIRED)
message (STATUS "Found node: ${NODE_EXECUTABLE}")
```

### Actual behavior

`NODE_EXECUTABLE` is set to "/usr/local/bin/node".

I had to pass `-DCMAKE_IGNORE_PATH=/usr/local/bin` to cmake to workaround the issue.

### Repro steps

1. Install nodejs as part of the build preparation
```
    - name: Install Packages
      run: sudo apt install nodejs
```
2. In cmake configuration try to find "node" executable
```
find_program (NODE_EXECUTABLE NAMES node nodejs REQUIRED)
message (STATUS "Found node: ${NODE_EXECUTABLE}")
```

**Comment by mikhailkoliada** [comment]
Hello! On runners `/usr/local/bin` comes first in `$PATH` and this is expected outcome as lots of software is being installed outside official apt repositories, if you want to use something what conflicts with the existing installation you should either cleanup the `/usr/local/bin` directory, or change the path priority.
