### ISSUE TITLE
Node 18.14.0 and 18.14.1 contain a breaking change

### ISSUE THREAD

**Issue by mikeharder** [actions/runner-images#7174]
### Description

Node 18.14.0 and 18.14.1 include npm 9.3.1, and npm 9.3.1 contains a breaking change (https://github.com/nodejs/node/issues/46542) that seems to be impacting many users.

Node 18.14.2 with npm 9.5.0 was released today and fixes the breaking change.

I think the best course of action would have been to pin Node to 18.13.0 until the breaking change was fixed.

However, since agent images with Node 18.14.0 and 18.14.1 have already been released, I think the next best action would be to upgrade to Node 18.14.2 as soon as possible.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
Version: 20230217.1

Build Link: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2206943&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f&l=30

### Is it regression?

Yes, from 20230122.1 which included Node 18.13.0

### Expected behavior

No breaking changes when using Node version `18.x`

### Actual behavior

Node version `18.x` can map to `18.14.0` or `18.14.1` which can break existing builds

### Repro steps

Run a pipeline that is impacted by https://github.com/nodejs/node/issues/46542

**Comment by mikhailkoliada** [comment]
Hello, minor versions are being updated automatically and will be included in the next release.

**Comment by mikhailkoliada** [comment]
deployed
