### ISSUE TITLE
Spyder will not load

### ISSUE THREAD

**Issue by ebiofuel** [actions/runner-images#7179]
### Description

On a clean install of Windows 11 and Anaconda Navigator, I am unable to start Spyder. The cmd prompt is stuck on 'Active code page: 1252' and 'Exit code: 3221225477'. 

### Expected behavior

Launch Spyder

### Actual behavior

Spyder does not launch and throws an exit code.

"Exit code: 3221225477"

### Repro steps

Open Anaconda Navigator

Launch Spyder

**Comment by bogdan-damian-bgd** [comment]
Hello! You seem to have chosen the wrong repo for your question ([About](https://github.com/actions/runner-images#about) - runner-images repo).
Feel free to contact us again if you have any further questions.
