### ISSUE TITLE
Checkout suddenly much slower on windows environment

### ISSUE THREAD

**Issue by yeu-degroot** [actions/runner-images#7180]
### Description

Since a few days, the duration of the `actions/checkout@v3` steps on `windows-2019` have dramatically increased.
This behavior is seen on all my repos (all private). Below a table showing an example of before/after.

| Checkout step | Feb 17th | Feb 21st |
| -- | -- | -- |
| 1 | `13s` | `1m35s` |
| 2 | `8s` | `47s` |

The result is a huge increase in build (and billable) time.

![image](https://user-images.githubusercontent.com/52652923/220855259-79a6e246-acd8-40b8-a9f3-7865cda67e34.png)

![image](https://user-images.githubusercontent.com/52652923/220855227-566903a4-42ad-4de9-8414-402171c4dcfe.png)

The [github status](https://www.githubstatus.com/history) page does show some issues around this time frame, but these were all solved:

![image](https://user-images.githubusercontent.com/52652923/220855851-9c8dac29-19c5-43ca-9835-06b043285087.png)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.301.1'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
```

Private repo

### Is it regression?

Yes, sorry private repos

### Expected behavior

The build times should be fairly constant. 

### Actual behavior

Build times explode. Burning down our build minutes too fast.

### Repro steps

Compare build times on any windows environment from before Feb 18th with today.

**Comment by mikhailkoliada** [comment]
Hello! Please report to the https://github.com/actions/checkout repo as they maintain the setup task primarily and can tell what happens on windows better.
