### ISSUE TITLE
Ubuntu 22.04 Azure pipeline extension failed to execute.

### ISSUE THREAD

**Issue by robertreems** [actions/runner-images#7187]
### Description

Hi there,

My customer hosts self hosted agents using a VMSS for our Azure DevOps environment. Since 22 feb building the image fails. 
The agents fail to come online and from the VMSS we see the following error:
`Azure Pipelines Extension failed with message: The Extension failed to execute: Pipeline script execution failed with exit code 100. 2023-02-23 07:34:50 version 14 2023-02-23 07:34:50 Url is https://dev.azure.com/experimentapg1/ 2023-02-23 07:34:50 Pool is SHA-ubuntu2204-imgTest 2023-02-23 07:34:50 RunArgs is --once 2023-02-23 07:34:50 Directory is /agent 2023-02-23 07:34:50 Creating AzDevOps account 2023-02-23 07:34:53 Giving AzDevOps user access to the '/home' directory 2023-02-23 07:34:53 Zipfile is /agent/vsts-agent-linux-x64-2.217.2.tar.gz 2023-02-23 07:34:53 Unzipping agent 2023-02-23 07:34:56 2023-02-23 07:34:56 Installing dependencies ++ id -u + user_id=0 + '[' 0 -ne 0 ']' + '[' -e /etc/os-release ']' + echo '--------OS Information--------' + cat /etc/os-release + echo ------------------------------ + '[' -e /etc/debian_version ']' + echo 'The current OS is Debian based' + echo '--------Debian Version--------' + cat /etc/debian_version + echo ------------------------------ + command -v apt + '[' 0 -eq 0 ']' + apt update WARNING: apt does not have a stable CLI interface. Use with caution in scripts. + apt install -y liblttng-ust0 libkrb5-3 zlib1g debsums WARNING: apt does not have a stable CLI interface. Use with caution in scripts. E: Unable to locate package liblttng-ust0 + '[' 100 -ne 0 ']' + echo ''\''apt'\'' failed with exit code '\''0'\''' + print_errormessage + echo 'Can'\''t install dotnet core dependencies.' + print_repositories_and_deps_warning + echo 'Please make sure that required repositories are connected for relevant package installer.' + echo 'For issues with dependencies installation (like '\''dependency was not found in repository'\'' or '\''problem retrieving the repository index file'\'') - you can reach out to distribution owner for futher support.' + echo 'You can manually install all required dependencies based on following documentation' + echo https://docs.microsoft.com/dotnet/core/install/linux + exit 1 2023-02-23 07:35:07 Dependencies installation failed 2023-02-23 07:35:07 Configuring build agent 2023-02-23 07:35:07 Configuring agent 2023-02-23 07:35:11 ___ ______ _ _ _ / _ \ | ___ (_) | (_) / /_\ \_____ _ _ __ ___ | |_/ /_ _ __ ___| |_ _ __ ___ ___ | _ |_ / | | | '__/ _ \ | __/| | '_ \ / _ \ | | '_ \ / _ \/ __| | | | |/ /| |_| | | | __/ | | | | |_) | __/ | | | | | __/\__ \ \_| |_/___|\__,_|_| \___| \_| |_| .__/ \___|_|_|_| |_|\___||___/ | | agent v2.217.2 |_| (commit ef0b5a5) >> End User License Agreements: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories. A copy of the Team Explorer Everywhere license agreement can be found at: /agent/license.html >> Connect: No usable version of libssl was found /agent/config.sh: line 86: 2868 Aborted (core dumped) ./bin/Agent.Listener configure "$@" 2023-02-23 07:35:11 Build agent configuration failed`

Could this be related to https://github.com/actions/runner-images/pull/7166 ?

Thanks for your assistance in advance. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not applicable since the agent didn't check in to Azure DevOps as mentioned above. 

### Is it regression?

2.217.2

### Expected behavior

The build agents successfully registers itself within Azure DevOps

### Actual behavior

The build agent doesn't register itself within Azure DevOps.

### Repro steps

step 1. Build a new image from the repo
Step 2. Use newly build as Azure DevOps agent.

**Comment by mikhailkoliada** [comment]
Hello! The issue you mentioned is not connected with the current image. Please report it to https://github.com/microsoft/azure-pipelines-agent as they are responsible for the agent itself and could provide better help for their product.
