### ISSUE TITLE
Add `splitdiff`

### ISSUE THREAD

**Issue by tharatau** [actions/runner-images#7189]
### Tool name

splitdiff

### Tool license

Not sure

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Not sure

### Brief description of tool

separate out incremental patches

### URL for tool's homepage

https://linux.die.net/man/1/splitdiff

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by tharatau** [comment]
The package is installed on my local machine (Ubuntu 22.04) but not on the Github image. It seems to be included in my local 22.04 which I installed recently.

**Comment by bogdan-damian-bgd** [comment]
Hi @tharatau, thank you for the installation suggestion, but since it only takes about ten seconds to install in runtime we would not like it to be pre-installed now, but we will reconsider it in the future.

**Comment by tharatau** [comment]
> since it only takes about ten seconds to install in runtime

How were you able to install `splitdiff` on the runner image? I was unable to do so which is why I opened this issue.

**Comment by mikhailkoliada** [comment]
splitdiff is a part of the patchutils which you can install in runtime

**Comment by tharatau** [comment]
@mikhailkoliada thanks!
