### ISSUE TITLE
Update Fastlane 2.212.1 (Because previous versions locks apple account)

### ISSUE THREAD

**Issue by einar-notland** [actions/runner-images#7194]
### Tool name

Fastlane

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.212.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by einar-notland** [comment]
See details about issue that caused Apple account locking here:

https://github.com/fastlane/fastlane/pull/21073

**Comment by Alexey-Ayupov** [comment]
Hello @einar-notland, this fix will be applied in next week's release.

**Comment by einar-notland** [comment]
> Hello @einar-notland, this fix will be applied in next week's release.

Seems like its only 2.212.0 thats included in this weeks release. You should really consider changing that to 2.212.1, its really anoying for us using fastlane to upload apps that we currently cannot use GitHub Actions to do it.
