### ISSUE TITLE
Update VS2022 to 17.5

### ISSUE THREAD

**Issue by jcelerier** [actions/runner-images#7201]
### Tool name

Visual Studio

### Tool license

Proprietary

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.5

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by mikhailkoliada** [comment]
It will be in the next release

**Comment by Life4gal** [comment]
It's really nice to see this, especially after I found that the latest Window image pre-installed the Visual Studio [17.4](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022) while Visual Studio needs at least [17.5](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170#prerequisites) to use the `std` module. 😆 😆 😆

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by sylveon** [comment]
Has this been deployed to Azure Pipelines too? I'm trying to use a feature that was added in 17.5 (std::format_string support), but I'm getting a compile error as if it is building on on 17.4
