### ISSUE TITLE
use interval value in retry function

### ISSUE THREAD

**Issue by RUBenGAMArrarodRiguEZ-ToMtOm** [actions/runner-images#7208]
### Description

The retry function in https://github.com/actions/runner-images/blob/macOS-12/20230219.1/images/linux/scripts/helpers/install.sh#L35 uses a hardcoded value. There is a message above that line (L35) that uses the value of the variable `interval`.

I would expect that the `interval` variable is also used in the logic.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu22/20230227.2

### Is it regression?

no

### Expected behavior

The logic uses the `interval` variable. The variable can be found for example here https://github.com/actions/runner-images/blob/macOS-12/20230219.1/images/linux/scripts/helpers/install.sh#L35

### Actual behavior

A hardcoded value is always used.

### Repro steps

To reproduce this behaviour it requires to have a download task that uses the `download_with_retries` function in `runner-images/images/linux/scripts/helpers/install.sh` and fails at least once.

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
fixed in https://github.com/actions/runner-images/pull/7207

**Comment by ddobranic** [comment]
Thank you, @RUBenGAMArrarodRiguEZ-ToMtOm . We will check and get back to you.

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
I see some changes merged here https://github.com/actions/runner-images/pull/7213

Why not using quotes for the variable like here https://github.com/actions/runner-images/pull/7207?

Even though currently the variable is declared some lines above, when the code is refactored one cannot be sure that `interval` will not contain spaces or symbols breaking the call to sleep

**Comment by mikhailkoliada** [comment]
Merged
