### ISSUE TITLE
apt upstream broken in ubuntu-latest (`22.04.2` version `20230219.1`)

### ISSUE THREAD

**Issue by ryankurte** [actions/runner-images#7210]
### Description

it looks like something has gone wrong with the upstream packaging / repo signing (not _technically_ the image, but, impacting the image). this appears to be intermittent, and has occured in march in the past https://github.com/actions/runner-images/issues/2919, so perhaps one of the repository mirrors is out of sync / hasn't picked up updated keys?

calling `apt update` or equivalent results in:
```
Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
...
Get:23 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [13.3 kB]
Reading package lists...
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy Release' is no longer signed.
```

this may be a recurrence of https://github.com/actions/runner-images/issues/5656

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230219.1

### Is it regression?

yes (this is an upstream package repo issue, the same image worked yesterday)

### Expected behavior

`apt update` should work

### Actual behavior

`apt update` fails with `E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy Release' is no longer signed.`

### Repro steps

create an action using `ubuntu-latest` with a step invoking `apt`

**Comment by ddobranic** [comment]
@ryankurte thank you, we will take a look.

**Comment by mikhailkoliada** [comment]
looks like it has been healed on the repo side (+ network)

<img width="753" alt="image" src="https://user-images.githubusercontent.com/88318005/222244577-e44f7aae-0621-4ec6-b9f3-db9ffcc63946.png">

**Comment by terrynguyen255** [comment]
I got this again, today, on Github Action with `runs-on: ubuntu-latest`  @ddobranic 
Could you have a look?

**Comment by alxmcs** [comment]
Faced the same problem as  @terrynguyen255 - Github Action and `ubuntu:latest`.
```
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```
I believe yesterday everything was fine 🤷‍♂️

**Comment by amalsgit** [comment]
Started facing the same issue on CI runs today

```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```

**Comment by driesvints** [comment]
Hi @mikhailkoliada. Sorry to ping you here directly but could I draw your attention to this issue? This is also happening for us on our build and judging from the activity above this seems like a widespread issue atm.
