### ISSUE TITLE
dotnet sdk 7.0.200 breaking change in latest runner

### ISSUE THREAD

**Issue by nt-evander** [actions/runner-images#7215]
### Description

A breaking change from the dotnet sdk has been released as a runner image causing azure pipeline builds to fail when using --output on a solution build

https://github.com/dotnet/sdk/issues/30625 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

 20230226.1

### Is it regression?

20230219.1

### Expected behavior

build a solution file with a specific --output location succeeds

### Actual behavior

build a solution file with a specific --output location errors

### Repro steps

build a solution file with a specific --output location and run via pipelines

as not all are updated to the latest image this fails inconsistently

**Comment by ddobranic** [comment]
Hello @nt-evander, could you please provide minimum repro steps?

**Comment by mikhailkoliada** [comment]
It will be a part of the next image release

**Comment by nt-evander** [comment]
I've made a solution with some dotnet new commands and included the yaml for the pipeline to confirm

[Build-Validation-Testing.zip](https://github.com/actions/runner-images/files/10861800/Build-Validation-Testing.zip)

**Comment by gautelo** [comment]
Is the new image already being rolled out, cause my builds are already failing due to this. I can't see an update to the image documentation though, so I don't know what to expect. It looks like it's being rolled out presently, cause the builds are failing sometimes - depending on whether version 7.0.200 or 7.0.103 is on that particular box.

Docs are saying windows-2022 has these versions installed: .NET Core SDK: 3.1.120, 3.1.202, 3.1.302, 3.1.426, 6.0.114, 6.0.203, 6.0.309, 6.0.406, 7.0.103. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

Honestly.. removing a cli option in a patch.. smh.

**Comment by ddobranic** [comment]
Hello, @gautelo! New image will be rolled out next week. Thank you!

**Comment by gautelo** [comment]
Very strange that it's already broken then @ddobranic. I wonder why that is. Perhaps the agents aren't cleaned appropriately after somebody else installs it explicitly? If so, that seems like a bit of an issue as well. Or how would you explain why the Microsoft hosted Azure Pipeline agent pool has that version of dotnet on it without me installing it explicitly?

**Comment by aknosis** [comment]
This is occurring in `GitHub Actions - Standard Runners` as well.

**Comment by DamienDennehy** [comment]
Can confirm also hit by this on GitHub Actions - Standard windows-latest runner.

Runner Info:
![image](https://user-images.githubusercontent.com/3924814/222709424-c1aac621-2d1a-40f0-a185-64bd44035164.png)

Pack Step:
![image](https://user-images.githubusercontent.com/3924814/222709585-0ec97aaf-cdaf-4ee7-8424-6f441e5d84b1.png)

**Comment by Dreamescaper** [comment]
They have released version 7.0.201 with a fix for this issue. 
Is it possible to update images with this version?

**Comment by aknosis** [comment]
For my specific build needs, I was able to just build with the Windows 2019 runner. 🤷‍♂️

**Comment by jozefizso** [comment]
I had to force the 7.0.201:

```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '7.0.201'
```

**Comment by ddobranic** [comment]
@Dreamescaper updated image will be released this week.

**Comment by mikhailkoliada** [comment]
Deployed
