### ISSUE TITLE
Maven 3.9.0 broke some build due to breaking changes.

### ISSUE THREAD

**Issue by mrizzi** [actions/runner-images#7216]
### Description

As reported in [Release Notes – Maven 3.9.0 - Potentially Breaking Core Changes](https://maven.apache.org/docs/3.9.0/release-notes.html#potentially-breaking-core-changes):
`Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. `

It caused a failure just like `A required class was missing while executing org.jboss.forge.furnace:furnace-maven-plugin:2.29.1.Final:addon-install: org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory` in  https://github.com/windup/windup/actions/runs/4302723286/jobs/7501572355#step:5:10015

Would it be possible to downgrade to Maven 3.8.7?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version `20230227.2`
Failed build link https://github.com/windup/windup/actions/runs/4302723286/jobs/7501572355#step:5:10015

### Is it regression?

yes, latest working image `20230217.1`, latest successful build https://github.com/windup/windup/actions/runs/4232267464/jobs/7351789096

### Expected behavior

The Maven build should work.

### Actual behavior

The Maven build doesn't run.

### Repro steps

Run a Maven build which involves executing a Maven plugin that depends on `plexus-utils` dependency with Maven `3.9.0`

**Comment by mrizzi** [comment]
As a workaround, before the failing Maven build, add the step
```
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.7
```

**Comment by ddobranic** [comment]
@mrizzi thank you for reporting and for the workaround. we hope that the issue will be solved in upstream repository soon.

**Comment by brvaland** [comment]
@ddobranic we are unable use unverified git action due company security policy. Is there workaround to downgrade maven version via script on the runner before execution time. 

Please advise ?

**Comment by ddobranic** [comment]
@brvaland you can see how we install maven [here](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/java-tools.sh#L139)
please use [this link](https://downloads.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.zip) for previous version

**Comment by isha12788** [comment]
It is affecting azure pipelines too, did anyone set the version to 3.8.7 in azure-pipelines.yml from default 3.9.0 (without adding the maven directory path from the source directory) 

Please advise how to resolve build in azure pipelines.

**Comment by isha-integration** [comment]
how to resolve for build in azure-pipelines.yml file? please advise. Getting this issue in build as pipelines is taking default to 3.9.0

**Comment by sbernard31** [comment]
Just to be sure, I understand correctly, does that means there is no official way to force the maven version in github action ?

**Comment by sbernard31** [comment]
> Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. 

If you face plugins which failed because of this  : 
1) You should try to update to a recent version of this plugin. As this should be fixed by plugin maintainer. 
2) If there is no fix, a workaround could to add yourself `plexus-utils` dependency to this plugin in your build. E.g. for `impsort-maven-plugin` : 
```xml
<plugin>
  <groupId>net.revelc.code</groupId>
  <artifactId>impsort-maven-plugin</artifactId>
  <!--  stuck to 1.6.x for java8 compatibility -->
  <version>1.6.2</version>
  <dependencies>
    <!-- Needed because of maven 3.9.0 backward compatibility issue,
         See : https://github.com/revelc/impsort-maven-plugin/issues/64 -->
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
      <version>3.5.1</version>
    </dependency>
  </dependencies>
</plugin>
```
3. you can try to force maven version in your github action like explain in previous comments :point_up:  BUT
 - it seems there is no official way to do that.
 - this will not make your build work locally with maven 3.9 and above.

**Comment by sbernard31** [comment]
(I created corresponding stackoverflow question, maybe this will help to give visibility to this issue : https://stackoverflow.com/questions/75652635/a-required-class-was-missing-while-executing-maven-plugin-with-github-action)
