### ISSUE TITLE
Bash is suddenly failing with error "Windows Subsystem for Linux has no installed distributions."

### ISSUE THREAD

**Issue by BMurri** [actions/runner-images#7218]
### Description

Without changing the pipeline, builds are suddenly failing shortly after cloning the sources when they "set the build number" (an action using bash which is installed on the machine and which we've been using for years)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20230219.1
Included Software: https://github.com/actions/runner-images/blob/win22/20230219.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230219.1
1ES Hosted Pool

https://malibu00.visualstudio.com/Emmons/_build/results?buildId=6794&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=1f5497c2-71da-4644-b6c1-936633e5030f&l=8

### Is it regression?

Operating System Microsoft Windows Server 2022 10.0.20348 Datacenter Runner Image Image: windows-2022 Version: 20230219.1 Included Software: https://github.com/actions/runner-images/blob/win22/20230219.1/images/win/Windows2022-Readme.md Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230219.1 1ES Hosted Pool https://malibu00.visualstudio.com/Emmons/_build/results?buildId=6788&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=59c1674d-ef16-4ddc-a930-cb05576ca9f6

### Expected behavior

No failures. The command we've used for years continues to work.

### Actual behavior

2023-03-01T22:40:05.9417100Z Task         : Bash
2023-03-01T22:40:05.9417424Z Description  : Run a Bash script on macOS, Linux, or Windows
2023-03-01T22:40:05.9418002Z Version      : 3.214.0
2023-03-01T22:40:05.9418466Z Author       : Microsoft Corporation
2023-03-01T22:40:05.9418925Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2023-03-01T22:40:05.9419459Z ==============================================================================
2023-03-01T22:40:06.5884135Z Generating script.
2023-03-01T22:40:06.6147409Z Script contents:
2023-03-01T22:40:06.6148644Z GIT_LFS_SKIP_SMUDGE=0 git lfs checkout
2023-03-01T22:40:06.6190649Z [command]C:\Windows\system32\bash.exe -c pwd
2023-03-01T22:40:07.9297716Z Windows Subsystem for Linux has no installed distributions.
2023-03-01T22:40:07.9299599Z 
2023-03-01T22:40:07.9301183Z Distributions can be installed by visiting the Microsoft Store:
2023-03-01T22:40:07.9302636Z 
2023-03-01T22:40:07.9303696Z https://aka.ms/wslstore
2023-03-01T22:40:07.9304394Z 
2023-03-01T22:40:07.9390622Z ##[error]The process 'C:\Windows\system32\bash.exe' failed with exit code 1

### Repro steps

1. Run build
2. See build fail within seconds of the build starting.

**Comment by yulin-li** [comment]
We are meeting same issue. Could you fix it ASAP?

**Comment by lehaleha** [comment]
Same issue. CI builds were successful on this:
```
Image: windows-2022
Image Version: 51.0.0
Current image version: '20230214.1'
```
Started to fail on:
```
Image: windows-2022
Image Version: 53.0.0
Current image version: '20230219.1'
```

**Comment by ddobranic** [comment]
Hello @BMurri, thank you for reporting. Could you please give us more details. Are you using `- task: Bash@3` or something else in your pipeline?

**Comment by ddobranic** [comment]
We have tested using simple pipeline with Bash@3 and it ran fine:
![Screen Shot 2023-03-02 at 09 37 00](https://user-images.githubusercontent.com/101048884/222469069-25e8b582-eb91-45da-b685-fe991b08384d.png)
What is different between our runs is that your pipeline uses 'C:\Windows\system32\bash.exe -c pwd', and you can see in the picture that ours uses '"C:\Program Files\Git\bin\bash.exe" -c pwd'

**Comment by BMurri** [comment]
[Bash@3 - Bash v3 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines&viewFallbackFrom=azure-devops) states: The Bash task will find the first Bash implementation on your system. Running `which bash` on Linux/macOS or `where bash` on Windows will give you an idea of which one it will select.

I don't see what knobs we can twist that control that. Here's what the pipeline says when it is starting up:

> Starting: Initialize job
> Agent name: 'tes-build 1'
> Agent machine name: '2ebc0871c000000'
> Current agent version: '2.217.2'
> Operating System
> Microsoft Windows Server 2022
> 10.0.20348
> Datacenter
> Runner Image
> Image: windows-2022
> Version: 20230219.1
> Included Software: https://github.com/actions/runner-images/blob/win22/20230219.1/images/win/Windows2022-Readme.md
> Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230219.1
> 1ES Hosted Pool
> SKU: Standard_D4s_v3
> Image: 1es-hosted-image-win22-southcentralus
> Image Version: 53.0.0
> Interactive Mode: False
> Request Id: 81e30b4b-4aca-4b12-9726-1082980a0d5c
> Pool Name: tes-build
> Network Isolation Policy: None
> Current image version: '20230219.1'
> Agent running as: 'cloudtest'
> Prepare build directory.
> Set build variables.
> Download all required tasks.
> Downloading task: nuget-security-analysis (0.2.157)
> Downloading task: Bash (3.214.0)
> Downloading task: VersionAssemblies (2.2.178)
> Downloading task: UseDotNet (2.207.2)
> Downloading task: CmdLine (2.212.0)
> Downloading task: DotNetCoreCLI (2.217.0)
> Downloading task: PoliCheck (2.196.0)
> Downloading task: CredScan (3.216.0)
> Downloading task: PublishSecurityAnalysisLogs (3.245.0)
> Downloading task: uploadScanResults (2.1.0)
> Downloading task: PostAnalysis (2.195.0)
> Downloading task: EsrpCodeSigning (2.0.2)
> Downloading task: ArchiveFiles (2.215.0)
> Downloading task: CopyFiles (2.211.0)
> Downloading task: PublishBuildArtifacts (1.211.0)
> Downloading task: ComponentGovernanceComponentDetection (0.2320301.1)
> Checking job knob settings.
>    Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
>    Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
>    Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
> Finished checking job knob settings.
> Plugin: 'Test Result Parser plugin' is running in background.
> Plugin: 'Test File Publisher plugin' is running in background.
> Start tracking orphan processes.
> Finishing: Initialize job

**Comment by lehaleha** [comment]
Btw, we are observing the failure with YAML-based build definition too.

**Comment by mikhailkoliada** [comment]
Could someone please provide a minimal yaml to reproduce the issue?

**Comment by DenisRumyantsev** [comment]
An agent from the 1ES-hosted pool is used. During the `Bash` task execution, before executing the bash script, the `Bash` task executes the `bash -c pwd` command, which fails with the error "WSL has no installed distributions". This error itself is not related to either the agent or the `Bash` task. It is some issue in wsl bash. As it was determined, wsl bash (`C:\Windows\system32\bash.exe`) is being run by the `Bash` task rather than git bash (`C:\Program Files\Git\bin\bash.exe`). Currently, there is no way to set the bash directory path right in the `Bash` task. If we will add a new `Bash` task input for this, it will be an enhancement for the `Bash` task, not a fix for this issue.

The `Bash` task uses wsl bash instead of git bash since `C:\Windows\system32\` is placed before `C:\Program Files\Git\bin\` in the `PATH` environment variable.

Since this issue is not reproduced constantly, it is possible that some services do not have enough time to start before invoking wsl bash.

**Comment by lehaleha** [comment]
OK, now I can't repro it with either small test yaml nor whole CI pipeline. I'm not sure what changed (if anything). In all successfull runs I've looked at `git` folder was before `System32`. 

I've added `Path` output to our CI pipeline and will update the thread if it will start failing again.

**Comment by ddobranic** [comment]
thank you, @lehaleha ! i will close this issue as duplicate for https://github.com/actions/runner-images/issues/7253
you can see more details about the issue there.

**Comment by felipec** [comment]
> i will close this issue as duplicate for #7253

I don't know if it's the same issue, I'm not using Bash@3, my issue might be specific to GNU `make` choosing `C:/Program Files/Git/bin/sh.exe` by default, although the underlying issue might be the same.

**Comment by BMurri** [comment]
I'm having trouble seeing the connection as well. This issue appears to be an issue of some unknown agent altering the order of directories in the PATH, while the other is a particular program (that's not referenced in this issue) always superimposing its own preference for a particular environment variable that isn't PATH.

These are really separate issues.

**Comment by BMurri** [comment]
> thank you, @lehaleha ! i will close this issue as duplicate for https://github.com/actions/runner-images/issues/7253
> you can see more details about the issue there.

These are really different issues. I completely don't understand what they have in common other than a tangential relationship with environment variables.

**Comment by felipec** [comment]
@BMurri GNU `make` doesn't superimpose its own preference, it's just that the relationship is way more complicated.

I think what is happening is that when the `SHELL` variable (not the same as the `$SHELL` environment variable) is set to something "weird" (from the UNIX perspective) such as `sh.exe` that is ignored and and then a suitable replacement is searched in `$PATH`, and somehow `C:\Windows\system32\bash.exe` ends up being picked.

Both issues could be entirely due to the ordering of `$PATH`, but they might not.

**Comment by marcus-crane** [comment]
I ran into this issue just now because I added the following step to a pipeline:

```
- if: runner.os == 'Windows'
  shell: bash
  run: |
    echo "C:\Windows\System32" >> $GITHUB_PATH
```

I only did that because I was trying to use Scoop which fails due to [Robocopy.exe](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy) not being found hence adding `C:\Windows\System32` to `$GITHUB_PATH` despite how unnecessary it seems.

Hopefully that gives other travellers a hint on how to undo the issue.
