### ISSUE TITLE
Dacpac publishing errors out in runner 20230226.1

### ISSUE THREAD

**Issue by ayepiz** [actions/runner-images#7219]
### Description

While doing a localdb dacpac publish the process fails with the following error:
*** An unexpected failure occurred: The type initializer for 'Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerImpl' threw an exception..

Is a cmd script that runs the following command:
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\SqlPackage.exe" /Action:Publish /SourceFile:"D:\a\1\a\MoxDB.dacpac" /TargetDatabaseName:MoxDBUT /TargetServerName:"(localdb)\apm"

We have a previous step that creates the localdb in the agent without problems:
sqllocaldb create "apm" -s
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\f639a3d9-e21d-4eda-a6e6-510885d280d4.cmd""
LocalDB instance "apm" created with version 15.0.4153.1.

LocalDB instance "apm" started.

These scripts have been running without problems for the last 3 and a half years, but yesterday they started failing. They always fail when we get the image version 20230226.1 but never fail if we get any previous version like 20230219.1

![image](https://user-images.githubusercontent.com/10385865/222332554-ffc37324-4fed-40ff-a51d-f02cedbd32d3.png)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230226.1

### Is it regression?

20230219.1

### Expected behavior

The dacpac publish should finish without errors

### Actual behavior

Dacpac file publishing is failing with the following error:
*** An unexpected failure occurred: The type initializer for 'Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerImpl' threw an exception..

### Repro steps

Perform a dacpac publish into a localdb created in the agent

**Comment by ddobranic** [comment]
@ayepiz thank you for reporting. we will take a look.

**Comment by ayepiz** [comment]
Thank you @ddobranic in the mean time, is there a way we can force a runner version?

**Comment by mikhailkoliada** [comment]
@ayepiz there is no way to change a version, but,  could your problem be connected with VS22 got updated to 17.5.33414.496?

**Comment by jonathbil** [comment]
We are experiencing the same error message, directly by publishing via sqlpackage.exe , it seems VS 2022 17.5 update DacFX to version 16.1 (SQL 2022) and that broke many things... I am downgrading to VS 17.4 for the moment.

**Comment by nf313743** [comment]
An alternative/workaround to using sqlpackage.exe is to use the dotnet tool:
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-download.md

**Comment by LoGA80** [comment]
It is due to the VS 17.5.1 update indeed: I have updated my VS on my developer machine and now I cannot build the database project anymore. The workaround to add the master.dacpac from a previous version seems to be working but it adds a lot of extra effort to modify all our build and release pipelines. I really hope there will be a fix soon.

**Comment by jonathbil** [comment]
@nf313743 I try it without success, did it work for you.

BTW it's report on developper community:

https://developercommunity.visualstudio.com/t/Visual-Studio-175-broke-SqlPackageexe/10289754#T-ND10298717

**Comment by ayepiz** [comment]
The workaround published in the developercommunity link that jonathbil posted worked for me, which is to install manually the sqlpackage tool:
dotnet tool install -g microsoft.sqlpackage

Is automatically added to the path so you only have to do sqlpackage and your commands

**Comment by nw-onediscovery** [comment]
> The workaround published in the developercommunity link that jonathbil posted worked for me, which is to install manually the sqlpackage tool: dotnet tool install -g microsoft.sqlpackage
> 
> Is automatically added to the path so you only have to do sqlpackage and your commands

This worked for me as well. 

SqlPackage.exe began failing after updating from VS 17.4 to 17.5, and resumed working when I rolled back. Unfortunately this broke something with the Azurite emulator, so I re-upgraded to 17.5.1 after its recent release, which re-broke sqlpackage. Had to install sqlpackage manually to get around the original issue.

**Comment by mikhailkoliada** [comment]
As the workaround given I believe there is nothing more for us to add here, feel free to reach us out if anybody has questions left

**Comment by isaacabraham** [comment]
Is this issue being tracked anywhere inside Visual Studio or DacPac etc.? I'm completely stuck now.

**Comment by nw-onediscovery** [comment]
> Is this issue being tracked anywhere inside Visual Studio or DacPac etc.? I'm completely stuck now.

[This is fixed in Visual Studio as of 17.5.3](https://developercommunity.visualstudio.com/t/Visual-Studio-175-broke-SqlPackageexe/10289754)
