### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by apudas90** [actions/runner-images#7225]
### Tool name

Apache Maven

### Tool license

Open Source

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.8.7

### Brief description of tool

Azure hosted agent is using maven version 3.9.0 by default.
We wat this to use version 3.8.7.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ddobranic** [comment]
Hello, @apudas90 ! Thank you for your request. Please take a look at [this](https://github.com/actions/runner-images/issues/7221#issuecomment-1452101628) post for solution.
