### ISSUE TITLE
Provisioning request delayed or failed to send 5 time(s). This is over the limit of 3 time(s).

### ISSUE THREAD

**Issue by hamenu** [actions/runner-images#7228]
### Description

After two big PRs to rename folders (one with 1000+ file changes that triggered 1 pipeline and the other with ~300 file changes that triggered 7 pipelines), we can no longer run _any_ build on _any_ branch on _any_ pipeline.

`ubuntu-20.04` and `windows-2022` time out with this error:

```
##[warning]There was a failure in sending the provision message: An unexpected failure occurred while attempting to contact the remote provider.
,##[warning]There was a failure in sending the provision message: An unexpected failure occurred while attempting to contact the remote provider.
,##[warning]There was a failure in sending the provision message: An unexpected failure occurred while attempting to contact the remote provider.
,##[warning]There was a failure in sending the provision message: An unexpected failure occurred while attempting to contact the remote provider.
,##[warning]There was a failure in sending the provision message: An unexpected failure occurred while attempting to contact the remote provider.
,##[error]Provisioning request delayed or failed to send 5 time(s). This is over the limit of 3 time(s).
Pool: [Azure Pipelines](https://dev.azure.com/REDACTED/REDACTED/_settings/agentqueues?poolId=&queueId=62)
Image: windows-2022
```

We have waited longer than 5min (more than 30min) just in case this is a rate limiting thing, but didn't fix the problem

https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#pipelines

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

It doesn't even get to the `Initialize job` step. It gets stuck here and the error appears when clicking on each of the jobs:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/123523199/222607220-9b15cf1f-0e8d-4653-a900-57ae0705f59d.png">

### Is it regression?

Don't know :shrug:

### Expected behavior

A new agent is assigned to the job and starts running

### Actual behavior

When looking at the agent pool, Azure Pipelines, it shows a spinner that an agent has picked up a job and is running, but when you go to the job (the pipeline itself), it's not running at all and eventually times out.

### Repro steps

Rename a folder a in big repo (maybe mono-repo), and run a couple of pipelines at the same time? 🤷

Not sure if those big PRs were just a coincidence or the real culprit.

**Comment by hamenu** [comment]
It was an Azure Pipelines outage and I can confirm our pipelines are back up and running.

https://status.dev.azure.com/_event/371776903

**Comment by GFoley83** [comment]
This issue can be closed as has nothing to do with Github actions.

Raised an issue here:
https://github.com/microsoft/azure-pipelines-agent/issues/4177

**Comment by ddobranic** [comment]
Thank you @GFoley83. Closing issue.

**Comment by senser-adi** [comment]
Hi
I now have this issue on github runners (not azure). 
Ubuntu-latest
I get:
```Received request to deprovision: The request was cancelled by the remote provider.```
