### ISSUE TITLE
Update/Add maven-3.8.4

### ISSUE THREAD

**Issue by IoanConstantinescu** [actions/runner-images#7230]
### Tool name

Preinstalled maven 

### Tool license

	Apache License 2.0

### Add or update?

- [x] Add
- [X] Update

### Desired version

3.8.4

### Brief description of tool

ubuntu-latest comes preinstalled with Maven but recently this has been update to the latest version  which is 3.9.0. This version can break existing builds and there is no alternative to roll back to 3.8.X other than installing it from binary as part of the  pipeline.

This process is really fragile as if the link breaks for whatever reason one must update all the pipelines which often involves a lot of effort, especially if you have a large number of  pipelines as we have.

My suggestion would be to have an imagine  that comes  both with the latest version but also with some of the older 3.8.X version e.g. >= 3.8.4 and then the user can decide which version to use in a  similar manner as one can chose between various python or java versions.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
steps:- script: 'wget  $(MAVEN_URI)' - task: ExtractFiles@1 inputs:    archiveFilePatterns: 'apache-maven-version-bin.zip'     destinationFolder: '$(build.sourcesdirectory)/maven' - task: Maven@3 inputs:   mavenPomFile: ''   mavenOptions: ''   javaHomeOption: ''   jdkVersionOption: ''   jdkArchitectureOption: ''   goals: ''  mavenVersionOption: 'Path'  mavenDirectory: '$(build.sourcesdirectory)/maven/Version’  mavenSetM2Home: true
```

**Comment by sergei-pyshnoi** [comment]
Hello @IoanConstantinescu . We have rollbacked maven to version 3.8.7 . Changes will be deployed next week.

**Comment by Mazik3370** [comment]
1

**Comment by neumannm** [comment]
> Hello @IoanConstantinescu . We have rollbacked maven to version 3.8.7 . Changes will be deployed next week.

I think I just found the reason why many of our builds fail since last week in this thread.

So does this mean, that until next week, if we want to have working builds again, we will need to add some additional step in our workflows that specify a mvn version < 3.9.0?

**Comment by sergei-pyshnoi** [comment]
> > Hello @IoanConstantinescu . We have rollbacked maven to version 3.8.7 . Changes will be deployed next week.
> 
> I think I just found the reason why many of our builds fail since last week in this thread.
> 
> So does this mean, that until next week, if we want to have working builds again, we will need to add some additional step in our workflows that specify a mvn version < 3.9.0?

Yes, you can use this as workaround before new version of image will be available.

**Comment by IoanConstantinescu** [comment]
@neumannm sorry for the delay. As @sergei-pyshnoi  mentioned you can use the workaround if you need a specific version of maven.

`- script: 'wget https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip'
- task: ExtractFiles@1
  displayName: Download Maven 3.8.4
  inputs:
    archiveFilePatterns: 'apache-maven-3.8.4-bin.zip'
    destinationFolder: '$(build.sourcesdirectory)/maven'`

Kind regards,
Ioan-Luchian

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by neumannm** [comment]
@IoanConstantinescu  thank you for the hint.

@mikhailkoliada I'm wondering, why is the changed maven version not mentioned in the changelog of the [Ubuntu 22.04](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230305.1) image? For the 20.04 image it is. But it appears to me that both images were affected and the change has been reverted in both, too. (?)
