### ISSUE TITLE
Xcode Build Error: There is no available Metal device on this system.

### ISSUE THREAD

**Issue by never-better** [actions/runner-images#7235]
### Description

My Project using Reality Composer For Reality Kit, so has a file which extension is `.rcproject`. Before create `.rcproject`, my xcodebuild is Success. 
Now I Got a Error Message
```
** BUILD FAILED **
error: Could not determine generated file paths for RC project code generation: The command `(cd /Users/runner/work/kukuku/kukuku/kukuku && /Applications/Xcode_14.2.app/Contents/Developer/usr/bin/rctool generate '--dry-run=true' '-o=/Users/runner/Library/Developer/Xcode/DerivedData/kukuku-dgfvacdfnuqvledwdyiiuqthsgzi/Build/Intermediates.noindex/kukuku.build/Debug-iphonesimulator/kukuku.build/DerivedSources/RCProjectGenerated/KUExperience' /Users/runner/work/kukuku/kukuku/kukuku/kukuku/Domain/Model/AR/KUExperience.rcproject '--swift-version=5.0')` exited with status 1. The command's standard error was:


Error: There is no available Metal device on this system.
 (in target 'kukuku' from project 'kukuku')
Error: Process completed with exit code 65.
```

This is my Image
```
  build:
    runs-on: macos-12
    strategy:
        matrix:
          include:
            - xcode: "14.2"
              ios: "16.2"
              simulator: "iPhone 14 Pro"
```

The simulator doesn't support Metal? I can't find reference about that error code.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [x] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

There is no reference about `.rcproject` and `RealityKit`. https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xamarin-bundles

### Is it regression?

Before create `.rcproject` file, xcodebuild successed.

### Expected behavior

xcodebuild success

### Actual behavior

xcodebuild is fail

### Repro steps

See Above.

**Comment by mikhailkoliada** [comment]
Hello! Does your project require GPU access?

**Comment by acidlynx** [comment]
Metal project requires GPU. For example https://support.circleci.com/hc/en-us/articles/360052160592-Tests-Fail-With-Error-There-is-no-available-Metal-device-on-this-system-

**Comment by never-better** [comment]
Hi @mikhailkoliada. Yes, my project use RealitKit, so it requires GPU.

**Comment by never-better** [comment]
Hi @acidlynx. Thank you for link! It seems like pay for using `Metal` resource class.

**Comment by mikhailkoliada** [comment]
@never-better unfortunately, we do not provide GPU exposure for macOS agents at the moment, there are efforts towards getting it done but with no exact eta. Given we can not do anything here right now I am going to close the issue but feel free to reach us again if you have questions left.
