### ISSUE TITLE
Windows Server runners runs slower than Linux and macOS

### ISSUE THREAD

**Issue by kuohuanhuan** [actions/runner-images#7237]
### Description

As titled.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Microsoft Windows Server 2022 10.0.20348 Datacenter

<https://github.com/kuohuanhuan/x-markdown-css/actions/runs/4334877921>

### Is it regression?

No

### Expected behavior

The timing should be close to Linux and macOS.

### Actual behavior

Both Linux and macOS only took 15~30s to complete, but Windows Server 2022 (`windows-latest`) took at least 1m.

### Repro steps

Workflow:  
<https://github.com/kuohuanhuan/x-markdown-css/actions/runs/4334877921/workflow>

**Comment by mikhailkoliada** [comment]
Hello! This repo is for image-specs and software installed in the images, we handed over your concerns to the appropriate  internalteam but going to close the issue as it is not directly connected with the scope of the repo.

**Comment by kuohuanhuan** [comment]
> Hello! This repo is for image-specs and software installed in the images, we handed over your concerns to the appropriate internalteam but going to close the issue as it is not directly connected with the scope of the repo.

Understood, thank you!
