### ISSUE TITLE
Update PowerShell to 7.3

### ISSUE THREAD

**Issue by krokofant** [actions/runner-images#7242]
### Tool name

PowerShell

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.3

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by krokofant** [comment]
Currently there is no way to utilize the newer features of PowerShell 7.3 like `$PSNativeCommandArgumentPassing`. The 7.3 version did cause an unexpected issue (https://github.com/actions/runner-images/issues/6586) before so the version was downgraded.

Can it be installed again in a safer way? It would be great to start a discussion around this because at some point the need to update will increase and there needs to be an upgrade path.

**Comment by sergei-pyshnoi** [comment]
Hello @krokofant . We do not plan to update PowerShell to version 7.3 for two reasons:
1. PowerShell 7.3 have changes that can broke existing pipelines.
2. During our policy we support only latest LTS version (for now it`s 7.2)

You can try installing a specific version of powershell in runtime if you need that.
