### ISSUE TITLE
Update/Add [CCache]

### ISSUE THREAD

**Issue by IGR2014** [actions/runner-images#7244]
### Tool name

CCache

### Tool license

GPL v3

### Add or update?

- [ ] Add
- [X] Update

### Desired version

4.7.4

### Provide a basic test case to validate the tool's functionality.

```bash
ccache --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
This tool can be downloaded during the build because pre-installed version (via Chocolatey, I guess) is out-of-date (v4.3) and does not support MSVC..

I use following pwsh code:


Set-Alias -Name ccache -Value ${{ env.CCACHE_EXE }} -Force
Invoke-WebRequest -TimeoutSec 60 -MaximumRetryCount 3 -OutFile "${{ env.CCACHE_DIR }}.zip" -URI "${{ env.CCACHE_DOWNLOAD_LINK }}"
7z e "${{ env.CCACHE_DIR }}.zip" ccache.exe -r
Remove-Item "${{ env.CCACHE_DIR }}.zip"
ccache --version
```
```


### Tool installation time in runtime

~ 5 sec.

### Are you willing to submit a PR?

_No response_

**Comment by ilia-shipitsin** [comment]
After some investigation we found out that ccache comes as a part of  mingw-11.2.0.07112021 package which is shipped on Windows-2022 only. ccache is not installed on purpose.

**Comment by mikhailkoliada** [comment]
Thanks @ilia-shipitsin!

@IGR2014 given all that and that installation time is ~5s, please continue installing in runtime, we would not like to preinstall the tool on the agents.
