### ISSUE TITLE
Need Xcode_10.1 for i386 compilation.

### ISSUE THREAD

**Issue by djearthquake** [actions/runner-images#7246]
### Description

Project needs i386 architecture. It's a bug when I can compile elsewhere.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Please add 'Xcode_10.1.xip' so we can compile i386. Thank you.

[_missing required architecture i386 in file /Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks//CoreServices.framework/CoreServices.tbd_](https://github.com/djearthquake/amxmodx/actions/runs/4349883777/jobs/7600039649#step:13:1601)

I can compile project locally with 10.1.

### Is it regression?

It worked prior to me contributing to this aspect of project over a year ago.

### Expected behavior

Compile error-free.

### Actual behavior

Can not compile.

### Repro steps

Pick any Xcode and try to compile 32-bit.

**Comment by sergei-pyshnoi** [comment]
Hello @djearthquake . Unfortunately we do not plan add Xcode 10.1 to images. During our policy we support only three latest major version of Xcode. As workaround, you can try install specific version in runtime.

**Comment by djearthquake** [comment]
Installing 10.1 to pick from instead of the failing 11.7 Xcode is not going to cause any issues it is going to fix them. There isn't anything to support. You have 6 not 3. You should know there is no other way to get i386 on the OSX. It isn't Linux where that is easily fixed at run-time. 

This is for mod of a  game that still sells on Steam.


https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md



13.2.1 (default) | 13C100 | /Applications/Xcode_13.2.1.app
-- | -- | --
13.1 | 13A1030d | /Applications/Xcode_13.1.app
13.0 | 13A233 | /Applications/Xcode_13.0.app
12.5.1 | 12E507 | /Applications/Xcode_12.5.1.app
12.4 | 12D4e | /Applications/Xcode_12.4.app
11.7 | 11E801a | /Applications/Xcode_11.7.app
