### ISSUE TITLE
Breaking rendering of view component using tag helper

### ISSUE THREAD

**Issue by vsiwach1** [actions/runner-images#7251]
### Description

This change is breaking the rendering of view component using tag-helper. like <vc:test-name></vc:test-name> was working previously but now not not working after this change. However if we change the invocation logic to @await Component.InvokeAsync("TestName"); it works as expected.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current agent version: '2.217.2'
Current image version: '20230226.1'

### Is it regression?

Windows latest (2022) before 26-Feb-2023 release

### Expected behavior

I should be able to call/render ViewComponent using taghelper

### Actual behavior

We are rendering ViewComponent in our project using tag helper like `<vc:name></vc:name>`. Invoke method didn't get hit and this view component wasn't rendered at all. In the Html generated we see the html tag as `<vc:name></vc:name>` instead of the actual html written in the "Default" view created for this ViewComponent.

### Repro steps

1. Create a dotnet 6 project
2. Create a ViewComponent
3. Render this newly created component on Html page using tag helper
4. Verify that the tag helper doesn't rendered as expected. You will not see the html written in the Default view of ViewComponent.

**Comment by sergei-pyshnoi** [comment]
Hello @vsiwach1. Can you please provide more detailed repro steps with minimal code and pipeline example?

**Comment by vsiwach1** [comment]
> Hello @vsiwach1. Can you please provide more detailed repro steps with minimal code and pipeline example?

Hi @sergei-pyshnoi, Please follow the steps below
1. Setup an azure CICD pipeline which uses "windows latest" image in the build.
2. Create a dotnet 6 project.
3. Create a ViewComponent say "TestViewComponent". Write some html code in the Default view of this ViewComponent like `<div>Hello from view component</div>`
4. Use this View Component on any cshtml page of the project (e.g. Layout page) using tag helper e.g. `<vc:test></vc:test>`
5. Now commit your code and run your CICD pipeline.
6. Navigate to the website where your code is deployed and verify that message "Hello from view component" is not displayed. If you inspect the element (key F12 on chrome) you will find the it has element `<vc:test></vc:test>` which is not expected. `<vc:test></vc:test>` must be rendered as `<div>Hello from view component</div>`

Note: If I use `@await Component.InvokeAsycn("Test") for rendering ViewComponent it works as expected. It is the tag helper way of implementation which is broken. It was working before 26-Feb-2023.
This bug is also reproducible on local with Visual Studio Professional 2022 with version "17.5.1".  For older version of VS it will not be reproducible on local.

Let me know if I any other information is required from my side.

**Comment by brucethomas** [comment]
Ran into this issue with our CI/CD pipelines in Azure DevOps yesterday. None of our view components tag helpers are rendering. Was able to reproduce locally by changing VS configuration from Debug to Release. Still haven't found a resolution.

Same symptons as reported. I am using VS Enterprise 17.5.1. Only seemed to appear with 17.5.1.

**Comment by sergei-pyshnoi** [comment]
@vsiwach1 . Unfortunately our team not able to reproduce this error in this way. We have such expertise in dotnet 6 and we can miss some point of complexity of your project. Can you provide minimal code example with ready pipeline? It can be small repository that we can clone and start debugging process.

**Comment by brucethomas** [comment]
@vsiwach1 From my research, this is an issue in the 7.0.2 SDK. You can read more about it here. Try using the "Use .NET Task" in your pipeline to have it use a prior version like 7.0.103.

https://github.com/dotnet/aspnetcore/issues/46740

**Comment by erik-bershel** [comment]
Hello @vsiwach1! I forced to close that issue due to fact that it is connected with bug outside of our repo and images. Please feel free to contact us if you have any questions or feel free to open new issues if you have another concerns.
