### ISSUE TITLE
Issues Running dotnet tools during Pipeline

### ISSUE THREAD

**Issue by v1ferrarij** [actions/runner-images#7258]
### Description

Hi,

I am using this repository to create images and deploying them to Virtual Machine Scale Sets.

I have noticed an issue with the dotnet tools, so the tools are installed successfully during Packer build, however, they fail to run during the Pipeline, after investigation, this appears it is because the install path (/etc/skel/.dotnet/tools) is not added to the user account which runs the Pipeline (AzDevOps) PATH environment variable.

If I log into the VM as a standard user, I can run the tools fine as they are in the PATH environment variable.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

image built from main.

### Is it regression?

Yes

### Expected behavior

the dotnet tools should run during the pipeline.

### Actual behavior

/usr/bin/bash /agent/_work/_temp/b0584144-ead1-4266-bc05-14e1b203288c.sh
/agent/_work/_temp/b0584144-ead1-4266-bc05-14e1b203288c.sh: line 1: nbgv: command not found
##[error]Bash exited with code '127'.

### Repro steps

1. Build Image via Packer.
2. Deploy to VMSS.
3. Create Self Hosted Agent in Azure DevOps.
4. Run Pipeline on Self Hosted Agent.
    - bash: | 
        nbgv --version

The fix is to add /etc/skel/.dotnet/tools to the PATH before execution of the dotnet tool, but this doesn't seem like a clean method.

**Comment by sergei-pyshnoi** [comment]
Hello @v1ferrarij . Unfortunately we were unable to reproduce this error. We used Bash@3 task for calling  `nbgv --version` and got `3.5.119+5d25f54fec` in the logs. For building images we use the config as in [runner-images repo](https://github.com/actions/runner-images/) , so it`s kind of strange conditional in your case.

**Comment by v1ferrarij** [comment]
Hello,
How did you test this though?

I literally built the entire repo with no changes, so something must not be right, as I say, if I log into the Virtual Machine myself as the admin user, the commands work, it is only when I use this machine as a Self Hosted Agent, it does not work, because it is running as a new user.

Can you test the same way please?

Build Image > Deploy to VMSS > Setup Self Hosted Agent in Azure DevOps > run commands.

**Comment by sergei-pyshnoi** [comment]
@v1ferrarij During the build we have automatic tests that checks installed tools. You can find full log of packer [here](https://github.visualstudio.com/runner-images/_build/results?buildId=131526&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a) and see that `nbgv` runs successfully. Also we checked those by creation pipeline in AzDevOps, command launched without errors. Maybe you should try to rebuild image and check logs.

**Comment by v1ferrarij** [comment]
Yeah the tests run fine because the user installing the software has the correct path (/etc/skel/.dotnet/tools) added to their PATH environment variable. 

The user (AzDevOps) does not have the path (/etc/skel/.dotnet/tools) added to its PATH environment variable, hence it fails.

**Comment by v1ferrarij** [comment]
> @v1ferrarij During the build we have automatic tests that checks installed tools. You can find full log of packer [here](https://github.visualstudio.com/runner-images/_build/results?buildId=131526&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a) and see that `nbgv` runs successfully. Also we checked those by creation pipeline in AzDevOps, command launched without errors. Maybe you should try to rebuild image and check logs.

Yeah the tests run fine because the user installing the software and running the tests has the correct path (/etc/skel/.dotnet/tools) added to their PATH environment variable.

The user (AzDevOps) does not have the path (/etc/skel/.dotnet/tools) added to its PATH environment variable, hence it fails.
