### ISSUE TITLE
Unable to post events on macOS

### ISSUE THREAD

**Issue by pentamassiv** [actions/runner-images#7269]
### Description

Currently it is not possible for an application to send keystrokes. SIP prevents any changes to the permissions (https://github.com/actions/runner-images/issues/650) so it would be great if you could grant `bash` the permissions to send keystrokes. It would allow us to run tests for the library `enigo` on macOS (https://github.com/enigo-rs/enigo/issues/141). The library allows sending keystrokes on Linux, Windows and macOS and it is used by virtual keyboards and applications such as RustDesk.

Please consider adding 
`
"'kTCCServicePostEvent','/bin/bash',1,2,0,1,NULL,NULL,NULL,'UNUSED',NULL,0,1583997993"`
 to the `TCC.db`. I guess it would be added to `images/macos/provision/configuration/configure-tccdb-macos.sh`.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

All versions

### Is it regression?

No

### Expected behavior

Be able to send events to test the library

### Actual behavior

The tests fail, because they lack the permissions to send keystrokes.

### Repro steps

- Clone my branch to add more tests to enigo: https://github.com/pentamassiv/enigo/tree/more_test_cases
- Run the `CI.yml` workflow.
- Have a look at the `nightly` workflows
  -> They pass for Linux & Windows but fail on macOS

**Comment by erik-bershel** [comment]
Hey @pentamassiv!
I'll check how it would affect couple things connected with images security and will turn back with changes or negative answer. In general it sounds reasonable for me.

**Comment by pentamassiv** [comment]
It looks like it is possible now. Thank you very much for your consideration and the quick fix :+1:
