### ISSUE TITLE
Add alpine:3.17

### ISSUE THREAD

**Issue by Kielek** [actions/runner-images#7270]
### Tool name

alpine:3.17

### Tool license

https://pkgs.alpinelinux.org/packages

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.17

### URL for tool's homepage

https://alpinelinux.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes (if needed)

**Comment by Kielek** [comment]
PR for 3.16: https://github.com/actions/runner-images/pull/6343

**Comment by erik-bershel** [comment]
Hi @Kielek, we'll add new Alpine Docker images soon.

**Comment by mikhailkoliada** [comment]
Deployed :)
