### ISSUE TITLE
Update/Add PHP 8.2.3

### ISSUE THREAD

**Issue by rdpqapi** [actions/runner-images#7275]
### Tool name

PHP

### Tool license

https://www.php.net/license/index.php

### Add or update?

- [ ] Add
- [x] Update

### Desired version

8.2.3

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by rdpqapi** [comment]
8.2.3 is available in WebServices/WebApp so it would make sense to have pipeline support 8.2.3

**Comment by erik-bershel** [comment]
Hey @rdpqapi! PHP 8.2 is not available for Ubuntu 22.04 via [APT](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=php&searchon=names). We won't use another sources at the moment due to maintenance concerns.
