### ISSUE TITLE
[All OSes] Go 1.17.x will be removed and 1.20.x set as default on April, 3

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#7276]
### Breaking changes

Go 1.17.x will be removed from all OSes and 1.20.x will be set as default.

### Target date

Image deployment is starting on April 3 and will take 3-4 days.

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.

### Possible impact

If your builds depend on Go 1.17.x they can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

To install any versions in runtime use:

https://github.com/actions/setup-go action for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by work-direxfranko** [comment]
Huboshellx.hsx

**Comment by mikhailkoliada** [comment]
All was set, will be deployed next week

**Comment by work-direxfranko** [comment]
One UI

**Comment by mikhailkoliada** [comment]
Deployed
