### ISSUE TITLE
Update Golang 1.20

### ISSUE THREAD

**Issue by stuartleeks** [actions/runner-images#7281]
### Tool name

Golang

### Tool license

BSD 3-Clause "New" or "Revised" License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.20.2

### Brief description of tool

Golang currently has 1.20.1 cached on the hosted runners, so the `actions/setup-go` action is picking 1.20.1 when using a `go.mod` file specifying `1.20`.

Go [1.20.2 was released around a week ago](https://github.com/golang/go/releases/tag/go1.20.2) which included various fixes (including security fixes). It would be good to have the cached version updated to 1.20.2 to pick up these fixes.

### URL for tool's homepage

https://github.com/golang/go

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

yes

**Comment by stuartleeks** [comment]
@erik-bershel - that's great. Thanks for the prompt response!

**Comment by Bigquin** [comment]
> ### Tool name
> Golang
> 
> ### Tool license
> BSD 3-Clause "New" or "Revised" License
> 
> ### Add or update?
> * [ ]  Add
> * [x]  Update
> 
> ### Desired version
> 1.20.2
> 
> ### Approximate size
> _No response_
> 
> ### Brief description of tool
> Golang currently has 1.20.1 cached on the hosted runners, so the `actions/setup-go` action is picking 1.20.1 when using a `go.mod` file specifying `1.20`.
> 
> Go [1.20.2 was released around a week ago](https://github.com/golang/go/releases/tag/go1.20.2) which included various fixes (including security fixes). It would be good to have the cached version updated to 1.20.2 to pick up these fixes.
> 
> ### URL for tool's homepage
> https://github.com/golang/go
> 
> ### Provide a basic test case to validate the tool's functionality.
> _No response_
> 
> ### Platforms where you need the tool
> * [ ]  Azure DevOps
> * [x]  GitHub Actions
> 
> ### Runner images where you need the tool
> * [ ]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [x]  Ubuntu 22.04
> * [ ]  macOS 11
> * [ ]  macOS 12
> * [ ]  Windows Server 2019
> * [ ]  Windows Server 2022
> 
> ### Can this tool be installed during the build?
> _No response_
> 
> ### Tool installation time in runtime
> _No response_
> 
> ### Are you willing to submit a PR?
> yes
https://github.com/actions/runner-images/issues/7281#issue-1623661041

**Comment by ilia-shipitsin** [comment]
Probably related: https://github.com/actions/runner-images/issues/7276

**Comment by erik-bershel** [comment]
@stuartleeks Ubuntu images with Go 1.20.2 deployed.
