### ISSUE TITLE
Microsoft Graph Connect-MgGraph failing on 20230314.1 image

### ISSUE THREAD

**Issue by ajbeaven** [actions/runner-images#7298]
### Description

I'm having issues with Microsoft.Graph on `2.0.0-preview5` running the following code on a particular Azure DevOps agent image:

```
Install-Module Microsoft.Graph -AllowPrerelease -AllowClobber -Force -RequiredVersion "2.0.0-preview5"

$clientSecret = ConvertTo-SecureString -String {CLIENTSECRET} -AsPlainText -Force
$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList {CLIENTID}, $clientSecret
Connect-MgGraph -TenantId {TENANTID} -ClientSecretCredential $credential
```
(note, the most recent pre-release version of Microsoft.Graph has [another bug](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1880) that doesn't play nice with client secret credentials, but that may not be relevant to this issue)

Here's the error message when `Connect-MgGraph` is called:
> ##[error]Method not found: 'Void Microsoft.Graph.TokenCredentialAuthProvider..ctor(Azure.Core.TokenCredential, System.Collections.Generic.IEnumerable`1<System.String>)'.

I'm running this script in a release pipeline on Azure DevOps. The only difference I can see between when it succeeds and when it fails is the environment it runs on. I'm running this pipeline on a standard "Hosted Windows 2019 with VS2019" Azure-hosted agent but have tried on "Windows 2019" and "Windows 2022" with the same results.

Here are the logs generated when initializing the release pipeline job in Azure DevOps:

[working.log](https://github.com/actions/runner-images/files/10996507/working.log)
[broken.log](https://github.com/actions/runner-images/files/10996508/broken.log)

I'll be honest and say I don't understand how a change to the image would cause this third-party package to fail, particularly given the release notes don't mention this tool being changed, but given this is the only difference between the environments that pass and fail, I can only assume it's something to do with the image. Apologies if this was misplaced, but I hope this will point me in the right direction.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230314.1

### Is it regression?

20230307.2

### Expected behavior

Connection succeeds with no error messages

### Actual behavior

Error message reported: Method not found: 'Void Microsoft.Graph.TokenCredentialAuthProvider..ctor(Azure.Core.TokenCredential, System.Collections.Generic.IEnumerable`1<System.String>)

### Repro steps

1. Run a release pipeline in Azure DevOps with the above code on an agent running the 20230314.1 image
2. Fails on call to Connect-MgGraph

**Comment by ajbeaven** [comment]
Hmm, this is looking less likely to be the image now... I've run another release and it worked, and the agent that ran that was using the 20230314.1 image. Remaining differences between the two that work and do not work on 20230314.1 are the agent machine names:
- fv-az348-458 (broken)
- WIN-9VA7BAR9GH8 (working)

Feel free to close if you agree this is unlikely to be a runner image issue :)

**Comment by erik-bershel** [comment]
Hi @ajbeaven! I'm not really sure we can do anything to help you with issue connected with preview version of any product. But I'm interested why it happened, so. After a small investigation I found that the Graph use external methods and libraries. You cannot use the Graph without .Net and PowerShell platforms for example. So issue might be connected with one of the updates of those tools. On other hand I have the same issue with the Graph but pretty old one honestly. You can read about it here: https://stackoverflow.com/questions/67290203/authprovider-with-microsoft-graph-api-ctor-not-found

**Comment by ajbeaven** [comment]
That's fair enough. I really appreciate your response and time spent looking into this, particularly given it's out of scope. I'll do some further investigation to see if I can find something and will report back here, but In the meantime I'll close this ticket.
