### ISSUE TITLE
ubuntu-22.04 runner image 20230313.1 fails due to regression issue in Azure CLI 2.46.0

### ISSUE THREAD

**Issue by codepic** [actions/runner-images#7299]
### Description

This simple command fails (both locally and in github actions) while it was working before for months:

```pwsh
az aks update --name *** --resource-group *** --attach-acr ***
```

Downgrading to `Azure CLI 2.45.0` works.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '[2](https://github.com/jamixdev/g6-infra-as-a-code/actions/runs/4446029380/jobs/7805993806#step:1:2).[3](https://github.com/jamixdev/g6-infra-as-a-code/actions/runs/4446029380/jobs/7805993806#step:1:3)03.0'
Operating System
  Ubuntu
  22.0[4](https://github.com/jamixdev/g6-infra-as-a-code/actions/runs/4446029380/jobs/7805993806#step:1:4).2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230313.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230313.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230313.1
Runner Image Provisioner
  2.0.12[7](https://github.com/jamixdev/g6-infra-as-a-code/actions/runs/4446029380/jobs/7805993806#step:1:8).1
```

### Is it regression?

20230305.1

### Expected behavior

The command should succeed

### Actual behavior

The command fails with:

```pwsh
Waiting for AAD role to propagate[###                                 ]  10.0000%
Waiting for AAD role to propagate[#######                             ]  20.0000%
Waiting for AAD role to propagate[##########                          ]  30.0000%
Waiting for AAD role to propagate[##############                      ]  40.0000%
Waiting for AAD role to propagate[##################                  ]  50.0000%
Waiting for AAD role to propagate[#####################               ]  60.0000%
Waiting for AAD role to propagate[#########################           ]  70.0000%
Waiting for AAD role to propagate[############################        ]  80.0000%
Waiting for AAD role to propagate[################################    ]  90.0000%ERROR: Could not create a role assignment for ACR. Are you an Owner on this subscription?
```

### Repro steps

1. deploy aks with container registry attached
2. run `az aks update --name *** --resource-group *** --attach-acr ***` on the previously deployed aks as the subscription owner

**Comment by codepic** [comment]
Possibly related https://github.com/Azure/azure-cli/issues/25854

**Comment by erik-bershel** [comment]
Hey @codepic! As you already found that issue connected with bug in Azure CLI 2.46.0. We won't downgrade it because of security and maintenance reasons. And as you already mentioned too you may use another version of AzCLI by installing it in runtime.
