### ISSUE TITLE
Update Azure CLI on ubuntu-latest agent on Microsoft Hosted Agent

### ISSUE THREAD

**Issue by sghonda** [actions/runner-images#7300]
### Tool name

Azure DevOps pipeline

### Tool license

Azure

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Azure CLI

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
AzurCLI 2.46.0 already available on Ubuntu 22.04 (ubuntu-latest) images. [Readme](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#:~:text=SAM%20CLI%201.76.0-,Azure%20CLI%202.46.0,-Azure%20CLI%20(azure)).
