### ISSUE TITLE
GHC 9.6.1 does not work with Cabal 3.6

### ISSUE THREAD

**Issue by andreasabel** [actions/runner-images#7305]
### Description

Virtual environments of 2023-03-13 ship GHC 9.6.1 with cabal 3.6.2.0, which do not work together.
Need to update cabal to at least 3.8.  Native cabal version for GHC 9.6.1 is 3.10.
(Previous environments shipped GHC 9.4.4 with cabal 3.6.2.0, which was fine.)

The combination of GHC 9.6 and cabal 3.6 fails for `custom-setup` packages like Agda:
https://github.com/agda/agda/actions/runs/4450907695/jobs/7816927352?pr=6544#step:4:22
```
[__1] rejecting: Agda:setup.Cabal-3.10.1.0/installed-3.10.1.0,
Agda:setup.Cabal-3.10.1.0, Agda:setup.Cabal-3.8.1.0 (constraint from maximum version of Cabal used by Setup.hs requires <3.8)
```
Note the "constraint from maximum version of Cabal used by Setup.hs":  It is a global constraint fixed by `cabal`:
https://github.com/haskell/cabal/blob/6870def8e1e21e04d737d8c176bd7efce8fcc366/cabal-install/src/Distribution/Client/ProjectPlanning.hs#L1257-L1258

I witnessed this in `ubuntu-22.04`, but _likely all other platforms that ship GHC 9.6 are affected as well_.

Evidence from workflow run:
- Image version: https://github.com/agda/agda/actions/runs/4450907695/jobs/7816927352?pr=6544#step:1:8
  ```
  Image: ubuntu-22.04
  Version: 20230313.1
  ```
- GHC and cabal versions: https://github.com/agda/agda/actions/runs/4450907695/jobs/7816927352?pr=6544#step:3:12
  ``` 
  GHC_VER   = 9.6.1
  CABAL_VER = 3.6.2.0
  ```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: https://github.com/agda/agda/actions/runs/4450907695/jobs/7816927352?pr=6544#step:1:8
  ```
  Image: ubuntu-22.04
  Version: 20230313.1
  ```

### Is it regression?

Yes, worked with 20230305.1, see https://github.com/agda/agda/actions/runs/4434218810/jobs/7779994899#step:1:9

### Expected behavior

Succeed setting up installation of Agda.

### Actual behavior

Fails setting up installation of Agda.

### Repro steps

All information about reproducibility is contained in the workflow run: https://github.com/agda/agda/actions/runs/4450907695/jobs/7816927352?pr=6544

The issue was originally discovered in this PR:
https://github.com/agda/agda/pull/6544#issuecomment-1474313196

**Comment by erik-bershel** [comment]
Hello @andreasabel! Thank you for the info. From that point of view it looks like we really should change a bit installation for cabal to use latest. We'll check and return with updates or answer later.

**Comment by andreasabel** [comment]
CC @hasufell

**Comment by mikhailkoliada** [comment]
Should be fixed
