### ISSUE TITLE
Edge Browser .deb how done?

### ISSUE THREAD

**Issue by Wassssup-people** [actions/runner-images#7306]
### Breaking changes

wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_102.0.1245.39-1_amd64.deb

sudo chmod +x microsoft-edge-stable_102.0.1245.39-1_amd64.deb

sudo apt-get install ./microsoft-edge-stable_102.0.1245.39-1_amd64.deb

Using Mint. 

### Target date

yr. 4032

### The motivation for the changes

It did not install when I tried but worked when I did this..
wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_102.0.1245.39-1_amd64.deb

sudo chmod +x microsoft-edge-stable_102.0.1245.39-1_amd64.deb

sudo apt-get install ./microsoft-edge-stable_102.0.1245.39-1_amd64.deb

Using Mint. 

### Possible impact

It launched and looking for Bing chat gpt4?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_102.0.1245.39-1_amd64.deb

sudo chmod +x microsoft-edge-stable_102.0.1245.39-1_amd64.deb

sudo apt-get install ./microsoft-edge-stable_102.0.1245.39-1_amd64.deb

Using Mint.

**Comment by erik-bershel** [comment]
Hey @Wassssup-people! Please make issue correct way from bug report template. Or please open a discussion if it is just general question.
About Egde browser. It is already installed on Ubuntu images. Please provide more clearly information about what you want to achieve. Or you may take a look at out script to understand how it works with installing Edge [here](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/microsoft-edge.sh).
