### ISSUE TITLE
Image ubuntu-20.04, version 20230313.1 seems to have broken dotnet

### ISSUE THREAD

**Issue by narasamdya** [actions/runner-images#7318]
### Description

Our Linux validation pipeline ran successfully with version 20230317.1 ([link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19548902&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5bdac805-9920-47d7-8129-8c843e736f8b)) and with version 20230305.1 ([link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19526515&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=4ccf6c28-97ae-4185-a8ff-a32d5183c4f3)), but failed with version 20230313.1 ([link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19559050&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=db53cd72-0ba2-4038-a504-895e799de269)).

It seems that with version 20230313.1 there is this upgrade to 6.0.15-1
```
Get:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-runtime-6.0 amd64 6.0.15-1 [23.1 MB]
Get:2 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 aspnetcore-runtime-6.0 amd64 6.0.15-1 [6612 kB]
```
and when that version is installed, the version match doesn't work correctly (may be a break in net6 release).

The repo itself only asks for net6, and so any version should work.

Also, from our pipeline, it looks like there is a downgrade from 20230317.1  to 20230313.1, and we are not sure about the reason. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Success
 - 20230317.1 ([link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19548902&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5bdac805-9920-47d7-8129-8c843e736f8b)) 
 - 20230305.1 ([link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19526515&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=4ccf6c28-97ae-4185-a8ff-a32d5183c4f3))
 

Failed:
- 20230313.1 ([link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19559050&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=db53cd72-0ba2-4038-a504-895e799de269)).

### Is it regression?

Yes. Latest good is 20230317.1

### Expected behavior

Pipeline validation succeeded

### Actual behavior

Pipeline validation failed

### Repro steps

Run the pipeline.

**Comment by ddobranic** [comment]
hello @narasamdya, thank you for reporting. image version 20230317.1 will be deployed this week.

**Comment by narasamdya** [comment]
Thank you for the prompt response. I'm interested in knowing 
- the reason for the image being downgraded from 20230317.1 to 20230313.1, and
- the issue with dotnet and the image 20230313.1 (any root cause of it?)

I did some test where I removed the dotnet installation from our init step so that we no longer have 
```
Get:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-runtime-6.0 amd64 6.0.15-1 [23.1 MB]
Get:2 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 aspnetcore-runtime-6.0 amd64 6.0.15-1 [6612 kB]
```
But the version match still didn't work correctly (build [link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19559327&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=0e85157e-8386-5a0d-deb6-f5b61bccf538))

**Comment by narasamdya** [comment]
Our latest builds were successful: [link](https://dev.azure.com/mseng/Domino/_build/results?buildId=19566718&view=results)

I see that the image has been updated to `20230320.1`. 

Thanks for the help.

PS: I'm still curious about the issue with dotnet and the image 20230313.1.

**Comment by mikhailkoliada** [comment]
Deployed
