### ISSUE TITLE
ubuntu-latest: Failing to run NET6 app due to missing Microsoft.NETCore.App

### ISSUE THREAD

**Issue by cristian-ambrosini-sonarsource** [actions/runner-images#7319]
## Description

After the [latest](https://github.com/actions/runner-images/commit/2c549825eaed806e2c85bbfcd5e50d99ebaa61c1) update in ubuntu-latest we started having issues in our Azure pipeline while running a NET6 app with the error:
```
/usr/share/dotnet/sdk/7.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5):
error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again. 
```

From a quick look, it might be the .NET Core SDK bump from `7.0.200` to `7.0.201` (see [commit](https://github.com/actions/runner-images/commit/1822632ce60ea5238445194474ed5e535322ecf2)). 

It's worth mentioning that we have already observed a couple of times very similar issues, see [here](https://github.com/actions/runner-images/issues/5792) and [here](https://github.com/actions/runner-images/issues/6925) for reference.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20230313.1

### Is it regression?

Yes. The previous version was working correctly.

### Expected behavior

Run the App without a runtime error.

### Actual behavior

Having an error:
```
/usr/share/dotnet/sdk/7.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5):
error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again. 
```

### Repro steps

Could not reproduce this locally.

Changing the image to [ubuntu-18.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-Readme.md) seems to solve the issue on the pipeline, at least.

**Comment by cristian-ambrosini-sonarsource** [comment]
Also from #6002 I can see that `18.04` will be fully unsupported by 2023/04/01. 
What does `unsupported` imply? This version is our only known workaround, so I wonder what will happen in 10 days if no fix is provided. Thank you

**Comment by ddobranic** [comment]
hello, @cristian-ambrosini-sonarsource! thank you for reporting. it is related to latest .NET Core SDK updates. new image will be rolled out this week containing version 7.0.202

**Comment by ddobranic** [comment]
Images have been deployed.
