### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by RodrigoTAlmeida** [actions/runner-images#7321]
### Tool name

Az 9.5.0  Azure/azure-powershell 

### Tool license

Don't know

### Add or update?

- [ ] Add
- [X] Update

### Desired version

9.5.0

### Brief description of tool

Following Support ticket 2302100050001269 and 2212220050001450, I was informed to raise an issue on this github to request that the new Az module version (https://github.com/Azure/azure-powershell/releases/tag/v9.5.0-March2023) that came out of the resolution of this ticket to be propagated to Microsoft-hosted agents. 

### URL for tool's homepage

https://github.com/Azure/azure-powershell/releases/tag/v9.5.0-March2023

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
From what I know, Az module comes installed in hosted agents images by default
```

**Comment by mikhailkoliada** [comment]
Hello! We would not like to add it pre-installed yet, please use [AzurePowerShellV5](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV5) task to fetch the version you need just in time.
