### ISSUE TITLE
Update/Add DTrace for windows

### ISSUE THREAD

**Issue by rbtcollins** [actions/runner-images#7325]
### Tool name

dtrace

### Tool license

open source

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Current version

### Approximate size

3MB

### Brief description of tool

DTrace for windows is useful for getting detailed information about system internals in a headless fashion, just what we need to debug the occasional mysterious difference between developer machines and runner VMs.

One wrinkle is that it requires elevated permissions to run on windows, and I'm not sure if runner scripts have those. 

### URL for tool's homepage

https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace

### Provide a basic test case to validate the tool's functionality.

```bash
dtrace -l
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

### Tool installation time in runtime

minutes

### Are you willing to submit a PR?

perhaps

**Comment by mikhailkoliada** [comment]
We will take a look

**Comment by rbtcollins** [comment]
https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace documents "Windows Server Build 18975" as being supported.

![image](https://user-images.githubusercontent.com/499678/228462717-5e2f477b-5b01-4a71-affb-e0a150ac6634.png)

**Comment by shamil-mubarakshin** [comment]
"Windows Server Build 18975" refers to Insider Build with same maintenance concerns.

**Comment by ilia-shipitsin** [comment]
@rbtcollins , maybe https://learn.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer can help in performance examination ?

honestly, I do not have much experience running it in scripted/headless mode, but I was really pleased with the way GUI works

**Comment by mikhailkoliada** [comment]
Hello! After more close investigation we decided not to add trace to the images due to limitation described above and maintenance chores.
