### ISSUE TITLE
Update [Azure Cosmos DB Emulator]

### ISSUE THREAD

**Issue by kaito-ms** [actions/runner-images#7327]
### Tool name

Azure CosmosDb Emulator

### Tool license

unknown

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.14.12

### URL for tool's homepage

https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator-release-notes

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by kaito-ms** [comment]
Link: [Azure CosmosDB emulator isn't running on localhost. · Issue #7039 · actions/runner-images](https://github.com/actions/runner-images/issues/7039)

**Comment by ddobranic** [comment]
hello, @kaito-ms! thank you for your request. we will update to new version.

**Comment by mikhailkoliada** [comment]
Deployed
