### ISSUE TITLE
Windows 2022 20230314.1 curl no longer uploads builds

### ISSUE THREAD

**Issue by janisozaur** [actions/runner-images#7329]
### Description

curl in updated image of windows-latest no longer uploads builds correctly.

Failing upload: https://github.com/OpenRCT2/OpenRCT2/actions/runs/4494171893/jobs/7906342484#step:10:28

Successful upload: https://github.com/OpenRCT2/OpenRCT2/actions/runs/4434792917/jobs/7781167528#step:10:22

Script which executes curl: https://github.com/OpenRCT2/OpenRCT2/blob/826fa4769cf4a1bef4f0743921247faab6c8bb35/scripts/upload-build#L36

There were no changes in our backend or other parts of infrastructure. I am still able to upload builds from local machine.

The receiving end of those uploads can be found here: https://github.com/Limetric/OpenRCT2.org/blob/1826c89f96b80a9b55edce4276a19bdb7a2d64ea/src/http/routes/altapi.js#L276-L277

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/blob/win22/20230314.1/images/win/Windows2022-Readme.md

### Is it regression?

win22/20230307.2

### Expected behavior

Curl uploads correctly

### Actual behavior

Curl fails to upload

### Repro steps

Try uploading openrct2 build to openrct2.org. To aid reproduction, I can provide some way for you to upload a build to our live backend.

**Comment by ilia-shipitsin** [comment]
Hello, @janisozaur !

you are uploading files to `https://openrct2.org` which is served by CloudFlare.
your successful download objects are near to 100mb.

might be hitting [upload limits](https://gridpane.com/kb/cloudflares-cdn-and-upload-limitations/)  here ?

**Comment by janisozaur** [comment]
No, the artifacts are around 33MB. Again - I can upload them without any issues from my local machine.

**Comment by sergei-pyshnoi** [comment]
Hello @janisozaur . Can you please tell which version of curl do you use on your local machine? You can just send output of `curl --version` command.

**Comment by janisozaur** [comment]
```
$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Comment by janisozaur** [comment]
I can confirm adding `--http1.1` made curl successfully upload in our case. I understand this is a workaround, so feel free to close as you see fit.

**Comment by sergei-pyshnoi** [comment]
@janisozaur . Thanks for your report. We close this issue for now, but if you have additional questions, feel free to ask.
