### ISSUE TITLE
Ubuntu 20.04 and 22.04 version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by nahimmedvent** [actions/runner-images#7333]
### Description

Azure Function using Ubuntu 20.04 and 22.04 display following error /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/site/wwwroot/.python_packages/lib/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so)

The solution is said to be downgrading to Ubuntu 18.04, but this image will be deprecated in less than 2 weeks from now. What are we to do then?

I have tried changing the image in the yml and testing ldd --version in all three images and get ldd (Debian GLIBC 2.28-10+deb10u2) 2.28 as a result. But only in 18.04 I do not get thrown that glibc error.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  vmImageName: 'ubuntu-20.04'
  vmImageName: 'ubuntu-18.04'

### Is it regression?

Ubuntu 18.04

### Expected behavior

Being able to run the Function App that has been running without this problem for the last year. Which uses Python 3.7 and pyodbc 4.0.35

### Actual behavior

Getting the error /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/site/wwwroot/.python_packages/lib/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so)

### Repro steps

1. Change the image on the yml to ubuntu 20.04 or 22.04
2. Use pip install --target="./.python_packages/lib/site-packages" -r requirements.txt in the yml
3. Try and run any function that uses pyodbc

**Comment by mikhailkoliada** [comment]
Hello! Answered your question here: https://github.com/actions/runner-images/issues/6002#issuecomment-1482344357
