### ISSUE TITLE
Action Runner Ubuntu 22.04 image regression

### ISSUE THREAD

**Issue by jnturton** [actions/runner-images#7340]
### Description

Hi

A few days ago we started seeing consistent failures of the CI runs we do for Apache Drill that we cannot link to any code change that we merged. The errors describe a missing Kerberos keytab file and are included in the logs section of this report. An example of a set of failed runs [is visible here](https://github.com/apache/drill/actions/runs/4374923172). We've been able to work around the issue by downgrading our Runner image from ubuntu-latest to ubunut-20.04. The unit tests in question also run fine on developers' local environments making the ubuntu-latest Runner the only place where we encounter the problem. We suspect that some change in the Ubuntu package configuration took effect in image version 20230305.1, specifically a change relating to Kerberos packages (krb5-user?).

Runner Image
  Image: ubuntu-22.04
  Version: 20230305.1

If this was an intentional change please let us know so we can try to add compensating Ubuntu package setup steps to our workflow. If it was unintentional, please look into whether it can be reversed in a new version of ubuntu-latest.

Thank you!
James

Reproduction Steps

Set runs-on: ubuntu-latest in .github/workflows/ci.yml and trigger the workflow opening a PR to apache/drill or pushing a commit to a test branch in apache/drill.

Fault Type

Permanent - Occurring repeatably

Blocking?

No

Last working date

06 March

Logs

```
Error: Errors:
20352
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20353
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20354
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20355
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20356
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20357
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20358
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20359
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
20360
Error: TestImpersonationMetadata.setup:72->BaseTestImpersonation.startMiniDfsCluster:84->BaseTestImpersonation.startMiniDfsCluster:112 » IO Running in secure mode, but config doesn't have a keytab
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/apache/drill/actions/runs/4374424200/jobs/7653832948

### Is it regression?

Builds succeed using the Ubuntu 20.04, https://github.com/apache/drill/actions/runs/4458926217/jobs/7831061065

### Expected behavior

The Ubuntu 22.04 behaves the same way that the Ubuntu 20.04 image does.

### Actual behavior

See the Description section.

### Repro steps

1. Change the Apache Drill CI runner image from Ubuntu 20.04 to Ubuntu 22.04.
2. Trigger a new workflow run.

**Comment by sergei-pyshnoi** [comment]
Hello @jnturton ! Ubuntu22 image version `20230305.1` is outdated, did you try run your workflow on `20230317.1` ?

**Comment by jnturton** [comment]
@sergei-pyshnoi thanks for your response. We haven't tried the new image version but we'll do so and I'll post feedback here .

**Comment by sergei-pyshnoi** [comment]
Hello @jnturton . Any updates? Did you try launch workflow with new version of image (for today its `20230326.2`) ?

**Comment by jnturton** [comment]
@sergei-pyshnoi thanks - we have tried using the new image version but the recent disappearance of the conjars.org Maven repository has now broken our CI for a completely different reason, so we still haven't obtained a clean run. But once we deal with the conjars problem I'll post an update here.

**Comment by sergei-pyshnoi** [comment]
Hello @jnturton . I am closing this issue for now during inactivity. When you get any updates with this issue please open new one with updated info. If you have additional questions, feel free to ask.

**Comment by jnturton** [comment]
@sergei-pyshnoi closing is correct, the new image does resolve the problem. Thanks for the help.

**Comment by jnturton** [comment]
@sergei-pyshnoi this issue has recently reappeared, and now in both the 22.04 and 20.04 image versions. I've reviewed the change logs for the recent runner image updates but I can't see any obvious culprit listed in them.

**Comment by jnturton** [comment]
@sergei-pyshnoi I now believe that the runner image updates have revealed an latent race condition in our unit tests. The root cause is surely in the Drill test code, and not due to anything that should be called a runner image regression.
