### ISSUE TITLE
Add dotnet workload ios

### ISSUE THREAD

**Issue by alexander-efremov** [actions/runner-images#7345]
### Tool name

dotnet workload ios

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

We are going to be build Xamarin IOS applications. Our build step to install all required workloads takes several minutes:

`dotnet workload install ios`

In order to avoid this repetitive steps we would like to have the workload pre-installed on MacOS agent.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
dotnet workload install ios
```

### Tool installation time in runtime

From 1 to 2 minutes.

**Comment by sergei-pyshnoi** [comment]
Hello @alexander-efremov . We will take a look.

**Comment by ivannggnnavi** [comment]
Not

**Comment by mikhailkoliada** [comment]
Hello! We would not like to add it mainly due to maintenance concerns, please continue installing in runtime
