### ISSUE TITLE
Update Az PowerShell module to 9.4.0 or later

### ISSUE THREAD

**Issue by sharpjs** [actions/runner-images#7351]
### Tool name

Az PowerShell module

### Tool license

Apache 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

9.4.0 or later, to get the fix for [this bug](https://github.com/Azure/azure-powershell/issues/20455) without needing an explicit install step

### Can this tool be installed during the build?

Yes

### Tool installation time in runtime

Minute or two

**Comment by sergei-pyshnoi** [comment]
Hello @sharpjs . We will take a look.

**Comment by mikhailkoliada** [comment]
Hello! Please still use the task, we have plans of adding a new az version right now as it may break lots of customers, but we will consider it for later usage.
