### ISSUE TITLE
[macos] Update Safari to v16.4

### ISSUE THREAD

**Issue by daxpedda** [actions/runner-images#7366]
The update was only just released yesterday (2023-03-28).

It's compatible with both macOS 11 and 12, as far as I can tell from the release notes: https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes.

This should be updated together with the Safari Webdriver.

**Comment by sergei-pyshnoi** [comment]
Hello @daxpedda . Thanks for your report. The latest Safari update will be available next week with new version of MacOS runner image.

**Comment by daxpedda** [comment]
Ah, I wasn't aware of that release cycle, thank you!

I guess we can leave this as a tracking issue? Otherwise feel free to close.

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by daxpedda** [comment]
Thanks!
