### ISSUE TITLE
[macos] Update Apache Maven to 3.9.1

### ISSUE THREAD

**Issue by attiasas** [actions/runner-images#7368]
### Tool name

Apache Maven

### Tool license

Apache License 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.9.1

### Brief description of tool

Can you update the latest version for Apache Maven to 3.9.1? for what I can see macos 11,12 already support 3.9.0

The update was released at 2022-12-11, release notes: 
https://maven.apache.org/docs/3.9.1/release-notes.html

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @attiasas . Thanks for your report. Apache 3.9.1 already for `macOS 11` image (you can check it in [Readme for MacOS 11](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md)).
For `macOS 12` it will be available next week with new version of runner image.

**Comment by attiasas** [comment]
thank you
