### ISSUE TITLE
Az PowerShell module path should not be /usr/share

### ISSUE THREAD

**Issue by icornett** [actions/runner-images#7370]
### Description

Azure PowerShell is installed as part of this image, but the path chosen makes it very difficult to import as it's not in the default `$env:PSModulePath`.  This results in needing to reinstall the modules when running in a VMSS in Azure DevOps as the path is inaccessible to the AzDevOps user even when using a fully qualified module path of `/usr/share/az_9.3.0/Az/9.3.0/Az.psm1`.  This results in extra unnecessary churn since the modules are already in the system.   Please use a path in the default `$env:PSModulePath` so that it can be easily referenced when using `AzureCLI@2` `pscore` tasks as it's the only way to obtain the service principal credential for passing to the `GenerateImageAndResources` script.

I understand that building these images in CI isn't exactly supported, but the larger problem exists in the Microsoft hosted agents from what I've seen as well for any `AzureCLI@2` `pscore` task.

recommended paths: `/usr/local/share/powershell/Modules, /opt/microsoft/powershell/7/Modules`

The issue occurs in `Install-AzureModules.ps1` on line 8

```powershell
# Get modules content from toolset
$modules = (Get-ToolsetContent).azureModules
$installPSModulePath = "/usr/share"
```

Pipeline code being executed:
```pwsh
try {
    Import-Module /usr/share/az_9.3.0/Az/9.3.0/Az.psm1 # also tried just Az
}
catch {
   Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
   Import-Module Az
 }
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

3.218.0

### Is it regression?

unknown

### Expected behavior

Az Powershell module should be importable from AzureCLI tasks

### Actual behavior

Module fails to be located, forcing it to reach out to PowerShellGallery.

### Repro steps

1. Use `ubuntu:latest` MS Hosted or Private agent from `runner-images` repo
2. Run a task on `AzureCLI@2` that's `pscore` with the script trying to import `Az` module
3. Module isn't found as it's not in the path

**Comment by sergei-pyshnoi** [comment]
Sorry, but I did`t get clearly. Are you using in your pipelines Windows or Ubuntu images?

**Comment by cumpstey** [comment]
I'm using Windows, and will be using MacOS in the future.

OP was using Ubuntu, but I don't.

**Comment by icornett** [comment]
There are instances when using the Azure CLI task is preferred over using the AzurePowerShell task.  For example when you need to access the service principal credentials, which can only be done with AzureCLI.  I may be barking up the wrong tree here, but it seems to me that this is more easily/quickly resolved with the addition of something like a symlink or changing to a default path than having the ADO team update the task.

**Comment by mikhailkoliada** [comment]
@cumpstey @icornett hey!

Apart from what @sergei-pyshnoi has mentioned, we can not install the modules different way because we may install lots of Az versions in parallel  and they and their dependencies conflict between each other
