### ISSUE TITLE
libpulse broken

### ISSUE THREAD

**Issue by LordOfDragons** [actions/runner-images#7373]
### Description

The image "ubuntu-latest" seems to be unable since some days to install libpulse-dev for nightly builds with this error:
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse0_15.99.1%2bdfsg1-1ubuntu2_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse-mainloop-glib0_15.99.1%2bdfsg1-1ubuntu2_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse-dev_15.99.1%2bdfsg1-1ubuntu2_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: ubuntu-22.04 , 20230326.2
Failed build: https://github.com/LordOfDragons/dragengine/actions/runs/4573411942/jobs/8073821518

### Is it regression?

https://github.com/LordOfDragons/dragengine/actions/runs/4549821319/jobs/8022263109

### Expected behavior

```sudo apt -y install libpulse-dev``` successfully installs package

### Actual behavior

```sudo apt -y install libpulse-dev``` fails to install package and fails build.

### Repro steps

1. Use workflow with image ```ubuntu-latest```
2. Add ```run: sudo apt -y install libpulse-dev``` step
3. Run workflow

**Comment by sergei-pyshnoi** [comment]
Hello @LordOfDragons . Thanks for your report. We have succeed nightly build for ubuntu images so this looks like a temporary error. Try to launch build later, if the problem continues to occur, we'll take a look.

**Comment by LordOfDragons** [comment]
The problem still persists: https://github.com/LordOfDragons/dragengine/actions/runs/4580988977/jobs/8090190152

**Comment by pwais** [comment]
found this thru search engine

oddly, an `apt-get update` before whatever was trying to install libpulse-dev fixed for me

**Comment by LordOfDragons** [comment]
Looks to be then a problem with 22.04 only since the linux build uses "ubuntu-20.04" and it does not fail. I guess the ubuntu 22.04 is incorrectly build? It should not be necessary to run apt-get update manually.

**Comment by krupkat** [comment]
I'm encountering the same issue, only with the 22.04 runner:
https://github.com/krupkat/xpano/actions/runs/4596260506/jobs/8117496572?pr=67
