### ISSUE TITLE
systemd version not documented?

### ISSUE THREAD

**Issue by dead-claudia** [actions/runner-images#7374]
### Description

It'd be helpful to know at a glance what systemd version is present, so I can know what all is supported without having to run a task. Filing it as a bug since systemd is clearly present and just not documented.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A - it's a docs bug

### Is it regression?

No

### Expected behavior

Docs list the systemd version.

### Actual behavior

No systemd version is listed.

### Repro steps

N/A

**Comment by sergei-pyshnoi** [comment]
Hello @dead-claudia . Thanks for your report, we will investigate this.

**Comment by mikhailkoliada** [comment]
It was added to the readme and will be a part of readme starting next week.
