### ISSUE TITLE
Update/Add Add Xcode 14.3

### ISSUE THREAD

**Issue by grzegorzkrukowski** [actions/runner-images#7375]
### Tool name

Xcode

### Tool license

Freeware

### Add or update?

- [X] Add
- [ ] Update

### Desired version

14.3

### Brief description of tool

Xcode 14.3 was released on 30.03, but it's still not available on the macOS 12 runners

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello! 14.3.x requires macOS-13 which is not provided for runners yet.

**Comment by grzegorzkrukowski** [comment]
Oh ok - any estimates on when macOS-13 will be available ?

**Comment by grzegorzkrukowski** [comment]
@mikhailkoliada Apparently there is a way to run Xcode on Monterey by modifying the Minimum system version in the Xcode 14.3 Info.plist seems to get it running - do you think it is possible to make it work on official runners?
