### ISSUE TITLE
Add powershell 7.x.x to the ubuntu images

### ISSUE THREAD

**Issue by sangrambal** [actions/runner-images#7376]
### Tool name

ubuntu latest

### Tool license

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

Please add  powershell core 7.x.x to the ubuntu latest images

### Platforms where you need the tool

- [x] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @sangrambal . Powershell version 7.2.10 is already installed for `ubuntu-20.04` and `ubuntu-latest`. For `ubuntu-18.04` its 7.2.9. Full list of installed software you can find in READMEs:

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md

I am closing issue for now but if you have additional questions feel free to ask.

**Comment by sangrambal** [comment]
Thanks for the info. Yes this is good for us. Thanks for the quick reply.
