### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by atedsimple** [actions/runner-images#7378]
### Tool name

kubelogin

### Tool license

opensource

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Go version: go1.19.6

### Brief description of tool

This is ruquired in order to connect to RBAC enabled AKS clusters

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by erik-bershel** [comment]
Clone of https://github.com/actions/runner-images/issues/7098
Please use runtime installation for that particular tool. We won't add it because of really small installation time and maintenance concerns.
