### ISSUE TITLE
Update Maven to 3.9.1

### ISSUE THREAD

**Issue by Riggs333** [actions/runner-images#7379]
### Tool name

Maven

### Tool license

Apache 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.9.1

### URL for tool's homepage

https://maven.apache.org/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @Riggs333!
We won't update Maven version to 3.9.x for Ubuntu images for the moment due to the reason it causing a lot of issues for other customers.
Take a look here please: https://github.com/actions/runner-images/issues/7216

**Comment by fwilhe** [comment]
Hi, I see why maven 3.9.x is not the default, but I'm wondering why there is no official way to configure using it. I know about a third party action like `stCarolas/setup-maven` to set it up, but should this not be possible for example via `actions/setup-java`?

**Comment by Phillipus** [comment]
Will there be an update to Maven 3.9.2 on Ubuntu? Or will it stay at 3.8.8?
