### ISSUE TITLE
Ubuntu 22.04 HCL format breaks tags for script GenerateResourcesAndImage.ps1

### ISSUE THREAD

**Issue by nnellans** [actions/runner-images#7381]
### Description

I'm trying to pass the tags parameter to the GenerateResourcesAndImage.ps1 script to build an Ubuntu 22.04 image.

Ubuntu 22.04's packer file is stored in .pkr.hcl format, where the older ones are still in .json format.

This breaks the part of the script that sets tags, because it's looking for .json file, like so:

```powershell
        if ($Tags) {
            $builderScriptPath_temp = $builderScriptPath.Replace(".json", "-temp.json")
            $packer_script = Get-Content -Path $builderScriptPath | ConvertFrom-Json
            $packer_script.builders | Add-Member -Name "azure_tags" -Value $Tags -MemberType NoteProperty
            $packer_script | ConvertTo-Json -Depth 3 | Out-File $builderScriptPath_temp
            $builderScriptPath = $builderScriptPath_temp
        }
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

n/a

### Expected behavior

Ability to pass tags to the script and use Ubuntu 22.04 in its HCL format.

### Actual behavior

Script fails with the following error:

```
GenerateResourcesAndImage : Conversion from JSON failed with error: Unexpected character encountered while parsing value: v. Path '', line 0, position 0.
At /home/owner/myagent/_work/_temp/azureclitaskscript1680366337515_inlinescript.ps1:9 char:1
+ GenerateResourcesAndImage `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,GenerateResourcesAndImage
##[error]GenerateResourcesAndImage : Conversion from JSON failed with error: Unexpected character encountered while parsing value: v. Path '', line 0, position 0.
```

### Repro steps

Run script to build Ubuntu 22.04 and use the `-tags` parameter on the script

**Comment by erik-bershel** [comment]
Clone of https://github.com/actions/runner-images/issues/6946.

Hey @nnellans! It's a known bug. We are in progress of resolving it.
