### ISSUE TITLE
The build tools for Visual Studio 2013 (Platform Toolset = 'v120') on windows-2019 & windows-2022

### ISSUE THREAD

**Issue by ramkumarchalla** [actions/runner-images#7390]
### Tool name

The build tools for Visual Studio 2013 (Platform Toolset = 'v120')

### Tool license

The build tools for Visual Studio 2013 (Platform Toolset = 'v120')

### Add or update?

- [X] Add
- [X] Update

### Desired version

The build tools for Visual Studio 2013 (Platform Toolset = 'v120')

### Brief description of tool

we are getting the following error while building the our sln. We need a image that can provide The build tools for Visual Studio 2013 (Platform Toolset = 'v120'), so that we can build our projects on azure pipelines.

The project "scim_install" is not selected for building in solution configuration "Release|Mixed Platforms".

##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): Error MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install Visual Studio 2013 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

Project "D:\a\1\s\xyz_device_service\emv_encoder.sln" (1) is building "D:\a\1\s\xyz_device_service\xyz_encoder\xyz_encoder.vcxproj.metaproj" (2) on node 1 (default targets).

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
yes
```

### Tool installation time in runtime

The build tools for Visual Studio 2013 (Platform Toolset = 'v120')

**Comment by erik-bershel** [comment]
Hello @ramkumarchalla!
The requested package can be installed using Choco in about 3 minutes. Example:
```
    - name: Choco
      run: choco install microsoft-build-tools-2013
```
Due to the ease of installation in runtime, and concerns with maintenance, we will not be adding it to our images.

**Comment by ramkumarchalla** [comment]
hi @erik-bershel , 

I see that - 2023-04-04 21:46:12,471 6840 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2023-04-04 21:46:12,471 6840 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\microsoft-build-tools-2013\.chocolateyPending".
2023-04-04 21:46:12,487 6840 [INFO ] -  **The install of microsoft-build-tools-2013 was successful.**

but the VSBuild is not finding the 

  **- task: VSBuild@1
    inputs:
      solution: 'xyz_device_service/xyz_encoder.sln'
      vsVersion: '12.0'
      platform: 'Mixed Platforms'
      configuration: 'Release'
      customVersion: '12.0'**

VSBuild

[View raw log](https://dev.azure.com/CardsOnTheSpot/76d1a18e-be9e-4274-a03f-308bf8ea2eb2/_apis/build/builds/190/logs/13)

Starting: VSBuild
==============================================================================
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.214.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -latest -format json
"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [16.0,17.0) -latest -format json
##[warning]Visual Studio version '12.0' not found. Falling back to version '16.0'.
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\a\1\s\scim_device_service\emv_encoder.sln" /nologo /nr:false /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=63f68231-73f4-422d-86af-af3322c85a09|SolutionDir=D:\a\1\s\scim_device_service|enableOrphanedProjectsLogs=true"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"  /p:platform="Mixed Platforms" /p:configuration="Release" /p:VisualStudioVersion="16.0" /p:_MSDeployUserAgent="VSTS_afb63df5-3df5-4bdb-a16a-c3e4d4275409_build_1_0"
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 4/4/2023 9:46:33 PM.
Project "D:\a\1\s\scim_device_service\emv_encoder.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Mixed Platforms".
ValidateProjects:
  The project "scim_install" is not selected for building in solution configuration "Release|Mixed Platforms".
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): Error MSB8020: The build tools for Visual Studio 2013 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install Visual Studio 2013 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

**Comment by erik-bershel** [comment]
@ramkumarchalla please take a look https://developercommunity.visualstudio.com/t/visual-studio-2019-error-msb8020/568655
