### ISSUE TITLE
Update/Add OpenSSL

### ISSUE THREAD

**Issue by iaoedsz2008** [actions/runner-images#7404]
### Tool name

OpenSSL

### Tool license

Apache-2.0 license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.1.1 for windows x86

### Brief description of tool

I am testing 32bit compatibility on Windows, I use find_package(OpenSSL) in cmake to find the openssl library, but I find the x64 architecture version, which causes problems with the link, can I install the x86 architecture version of openssl into the image?

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Tried to use choco, after successful installation, cmake still can't find the path
```

**Comment by iaoedsz2008** [comment]
is it possible to install the x86 architecture version of openssl into the default image?

**Comment by mikhailkoliada** [comment]
Hello! We generally have no plans to provide x86 software on the runners and try to remove some leftovers of it (like 32bit python on setup-python GitHub action).
