### ISSUE TITLE
Update Xcode to 14.3

### ISSUE THREAD

**Issue by fernandotcl** [actions/runner-images#7408]
### Tool name

Xcode

### Tool license

Xcode License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

14.3

### Brief description of tool

Xcode 14.3 was released on March 30th. It requires macOS 13 (Ventura), which AFAICT isn't supported yet in the Microsoft-hosted agents, so that would be a requirement.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @fernandotcl! Thank you for the request. You may track our progress of rolling out macOS 13 image here: https://github.com/actions/runner-images/issues/6426. And announces would be published of course.

**Comment by erik-bershel** [comment]
Ooops. Should be closed as a clone for: https://github.com/actions/runner-images/issues/7375
@fernandotcl please keep an eye on our announcements about macOS 13.
