### ISSUE TITLE
Ubuntu 20.04 - CSPM Scan

### ISSUE THREAD

**Issue by iandvt** [actions/runner-images#7410]
### Description

The VHD built via [GenerateResourcesAndImage.ps1](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1) has some underlying dependencies that should be updated to latest version. I'll try fixing these in a fork and contributing back.

## End Of Life Technology
<img width="1345" alt="Lastest Version" src="https://user-images.githubusercontent.com/25870869/230662648-504187fe-6aa3-4e30-9441-fb07fecdc7d4.png">

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Repro steps

N/A

**Comment by erik-bershel** [comment]
Hey @iandvt! 
Almost all of the packages in that list installed from official sources and generally because it was requested by other users. And we can do nothing about that. But we will appreciate any help, ideas and options. 
Generally I have only one question. It is about Apache 1.2.17 - looks strange for me, I almost sure we install Apache2. It should be checked.

**Comment by erik-bershel** [comment]
Gotcha!
```
{
   "name": "log4j",
   "SPDXID": "SPDXRef-Package-java-archive-log4j-7ce2f84f24d059a0",
   "versionInfo": "1.2.17",
   "downloadLocation": "NOASSERTION",
   "sourceInfo": "acquired package info from installed java archive: /usr/local/lib/android/sdk/patcher/v4/patcher.jar",
   "licenseConcluded": "NONE",
   "licenseDeclared": "NONE",
   "copyrightText": "NOASSERTION",
   "externalRefs": [
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:apache:log4j:1.2.17:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "PACKAGE-MANAGER",
     "referenceType": "purl",
     "referenceLocator": "pkg:maven/log4j/log4j@1.2.17"
    }
   ]
  }
  ```
  So, it's a part of the bundle for SDK Patch Applier v4 of Android SDK. You may request a fix from the development team for it. And we can do nothing about all other mentioned vulnerabilities due to the fact that all of those packages are somewhat obligatory to install.
