### ISSUE TITLE
Update/Add fish shell

### ISSUE THREAD

**Issue by andreiborisov** [actions/runner-images#7412]
### Tool name

fish shell

### Tool license

GNU GPL v2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.6.1

### Approximate size

8 MB

### Brief description of tool

[`fish`](https://github.com/fish-shell/fish-shell) is the most popular and widely used alternative (it uses C-like syntax) shell.

Preinstalling fish would offer more choices for writing shell scripts, including in `run` workflow steps.

### URL for tool's homepage

https://fishshell.com/

### Provide a basic test case to validate the tool's functionality.

```bash
fish --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update
sudo apt install fish

brew install fish
```

### Tool installation time in runtime

1 min

### Are you willing to submit a PR?

Yes

**Comment by Alexey-Ayupov** [comment]
Hello @andreiborisov, we do not install shells that are not supported by GitHub actions. The list of supported shells can be found [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell).
However, you are free to install the needed software during the pipeline run.

If you have any questions feel free to reach us again.

**Comment by andreiborisov** [comment]
@Alexey-Ayupov thank you for the quick reply.

Is there a way to submit a request for fish shell for GitHub Actions then?

**Comment by Alexey-Ayupov** [comment]
@andreiborisov, one of the options is to start the new discussion [here](https://github.com/orgs/community/discussions/categories/actions)
