### ISSUE TITLE
Update Visual Studio

### ISSUE THREAD

**Issue by EndangeredNayla** [actions/runner-images#7421]
### Tool name

Visual Studio

### Tool license

Priopetory

### Add or update?

- [ ] Add
- [X] Update

### Desired version

latest

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by EndangeredNayla** [comment]
Error i am receiving on my build is "Please update your build environment to the latest Visual Studio 2022!"

**Comment by Alexey-Ayupov** [comment]
Hello @EndangeredNayla, could you please be more specific about what runner caused this error? Overall we would like to get **minimal repro steps** from you to understand the error-appearing circumstances.

**Comment by Alexey-Ayupov** [comment]
We use the [script](https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers/Install-VS.ps1) which always takes the latest possible enterprise version of visual studio 2022. In case a new Visual Studio release appears during our weekly image release, we schedule it for the next weekly image release. 
Please try your pipeline on Friday this week. 

If you have any questions feel free to reach us out.
