### ISSUE TITLE
Error when running packer build windows2019.json

### ISSUE THREAD

**Issue by hiran-filho** [actions/runner-images#7427]
### Description

==> azure-arm: Waiting for WinRM to become available...
    azure-arm: WinRM connected.
==> azure-arm: Connected to WinRM!
==> azure-arm: Pausing after run of step 'StepConnectWinRM'. Press enter to continue. 
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner1006534545
    azure-arm:
    azure-arm:
    azure-arm:     Directory: C:\
    azure-arm:
    azure-arm:
    azure-arm: Mode                LastWriteTime         Length Name
    azure-arm: ----                -------------         ------ ----
    azure-arm: d-----        4/11/2023  10:56 PM                image
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Uploading /home/hiran/runner-images/images/win/scripts/ImageHelpers => C:\Program Files\WindowsPowerShell\Modules\
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Uploading /home/hiran/runner-images/images/win/scripts/SoftwareReport => C:\image
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Uploading /home/hiran/runner-images/images/win/../../helpers/software-report-base => C:\image/SoftwareReport/
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Uploading /home/hiran/runner-images/images/win/post-generation => C:/
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Uploading /home/hiran/runner-images/images/win/scripts/Tests => C:\image
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Uploading /home/hiran/runner-images/images/win/toolsets/toolset-2019.json => C:\image\toolset.json
    azure-arm: toolset-2019.json 17.57 KiB / 17.57 KiB [===================================================================================================================================================================================================================================================] 100.00% 1s
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Provisioning with windows-shell...
==> azure-arm: Provisioning with shell script: /tmp/windows-shell-provisioner978107406
    azure-arm:
    azure-arm: C:\Users\packer>net user installer  /add /passwordchg:no /passwordreq:yes /active:yes /Y
    azure-arm: The command completed successfully.
    azure-arm:
    azure-arm:
    azure-arm: C:\Users\packer>net localgroup Administrators installer /add
    azure-arm: The command completed successfully.
    azure-arm:
    azure-arm:
    azure-arm: C:\Users\packer>winrm set winrm/config/service/auth @{Basic="true"}
    azure-arm: Auth
    azure-arm:     Basic = true
    azure-arm:     Kerberos = true
    azure-arm:     Negotiate = true
    azure-arm:     Certificate = false
    azure-arm:     CredSSP = false
    azure-arm:     CbtHardeningLevel = Relaxed
    azure-arm:
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner2071264270
==> azure-arm: Pausing before the next provisioner . Press enter to continue. 
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner3655456271
==> azure-arm: (39,4):Task:
==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1:60 char:1
==> azure-arm: + $f.RegisterTaskDefinition($name, $t, 6, "installer", $password, $logo ...
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], COMException
==> azure-arm:     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
==> azure-arm:
==> azure-arm: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1:61 char:1
==> azure-arm: + $t = $f.GetTask("\$name")
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
==> azure-arm:     + FullyQualifiedErrorId : System.IO.FileNotFoundException
==> azure-arm:
==> azure-arm: Method invocation failed because [System.__ComObject] does not contain a method named 'Run'.
==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1:62 char:1
==> azure-arm: + $t.Run($null) | Out-Null
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : InvalidOperation: (Run:String) [], RuntimeException
==> azure-arm:     + FullyQualifiedErrorId : MethodNotFound
==> azure-arm:

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

can't make the picture

### Is it regression?

no

### Expected behavior

that an image was created and saved in AZURE so that a Vm Scale set could be created to use in AZURE DEVOPS

### Actual behavior

what is really happening is that there is some point in the script that is missing a file

### Repro steps

I change de build and variables parts for this:
{
    "variables": {
        "client_id": "{{env `ARM_CLIENT_ID`}}",
        "client_secret": "{{env `ARM_CLIENT_SECRET`}}",
        "client_cert_path": "{{env `ARM_CLIENT_CERT_PATH`}}",
        "subscription_id": "{{env `ARM_SUBSCRIPTION_ID`}}",
        "tenant_id": "{{env `ARM_TENANT_ID`}}",
        "object_id": "{{env `ARM_OBJECT_ID`}}",
        "resource_group": "{{env `ARM_RESOURCE_GROUP`}}",
        "storage_account": "{{env `ARM_STORAGE_ACCOUNT`}}",
        "build_resource_group_name": "{{env `BUILD_RESOURCE_GROUP_NAME`}}",
        "temp_resource_group_name": "{{env `TEMP_RESOURCE_GROUP_NAME`}}",
        "location": "{{env `ARM_RESOURCE_LOCATION`}}",
        "virtual_network_name": "{{env `VNET_NAME`}}",
        "virtual_network_resource_group_name": "{{env `VNET_RESOURCE_GROUP`}}",
        "virtual_network_subnet_name": "{{env `VNET_SUBNET`}}",
        "private_virtual_network_with_public_ip": "{{env `PRIVATE_VIRTUAL_NETWORK_WITH_PUBLIC_IP`}}",
        "allowed_inbound_ip_addresses": "{{env `AGENT_IP`}}",
        "vm_size": "Standard_D8s_v4",
        "image_folder": "C:\\image",
        "imagedata_file": "C:\\imagedata.json",
        "helper_script_folder": "C:\\Program Files\\WindowsPowerShell\\Modules\\",
        "agent_tools_directory": "C:\\hostedtoolcache\\windows",
        "install_user": "installer",
        "capture_name_prefix": "packer",
        "image_version": "dev",
        "image_os": "win19"
    },
    "sensitive-variables": [
        "client_secret"
    ],
    "builders": [
        {
            "type": "azure-arm",

            "client_id": "{{user `client_id`}}",
            "client_secret": "{{user `client_secret`}}",
            "subscription_id": "{{user `subscription_id`}}",
            "tenant_id": "{{user `tenant_id`}}",

            "managed_image_resource_group_name": "{{user `resource_group`}}",
            "managed_image_name": "EDPBR-IMG-WINSRV2019",

            "os_type": "Windows",
            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2019-Datacenter",

            "communicator": "winrm",
            "winrm_use_ssl": "true",
            "winrm_insecure": "true",
            "winrm_timeout": "10m",
            "winrm_username": "packer",
            "vm_size": "{{user `vm_size`}}",

            "build_resource_group_name": "{{user `resource_group`}}"
        }
    ],

and give this variables:

export ARM_RESOURCE_GROUP=RG-******-DEV
export ARM_TENANT_ID=********-***-***-****-************
export ARM_SUBSCRIPTION_ID=********-***-***-****-************
export ARM_CLIENT_SECRET=*************************
export ARM_CLIENT_ID=********-***-***-****-************

then execute:

packer build windows2019.json

**Comment by hiran-filho** [comment]
for more details:

2023/04/11 22:58:45 [INFO] (telemetry) ending powershell
2023/04/11 22:58:45 [INFO] (telemetry) Starting provisioner powershell
2023/04/11 22:58:45 ui: ask: [1;32m==> azure-arm: Pausing before the next provisioner . Press enter to continue.[0m
2023/04/11 22:58:47 ui: [1;32m==> azure-arm: Provisioning with Powershell...[0m
2023/04/11 22:58:47 packer-provisioner-powershell plugin: Found command: bcdedit.exe /set TESTSIGNING ON
2023/04/11 22:58:47 ui: [1;32m==> azure-arm: Provisioning with powershell script: /tmp/powershell-provisioner3655456271[0m
2023/04/11 22:58:47 packer-provisioner-powershell plugin: Opening /tmp/powershell-provisioner3655456271 for reading
2023/04/11 22:58:47 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-6435e510-7068-68fe-0c18-afcae1720f1a.ps1
2023/04/11 22:58:47 packer-provisioner-powershell plugin: [INFO] 74 bytes written for 'uploadData'
2023/04/11 22:58:47 [INFO] 74 bytes written for 'uploadData'
2023/04/11 22:58:47 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-6435e510-7068-68fe-0c18-afcae1720f1a.ps1'
2023/04/11 22:58:48 packer-provisioner-powershell plugin: Building elevated command wrapper for: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-6435e510-7068-68fe-0c18-afcae1720f1a.ps1; &'c:/Windows/Temp/script-6435e510-94b1-e9ee-851d-743e394bdd35.ps1'; exit $LastExitCode }"
2023/04/11 22:58:48 packer-provisioner-powershell plugin: Command [powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-6435e510-7068-68fe-0c18-afcae1720f1a.ps1; &'c:/Windows/Temp/script-6435e510-94b1-e9ee-851d-743e394bdd35.ps1'; exit $LastExitCode }" > %SYSTEMROOT%/Temp/packer-6435e628-8985-4d7f-5886-f3cd3a08d1c4.out 2>&1] converted to [powershell -executionpolicy bypass &#34;&amp; { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value &#39;SilentlyContinue&#39;};. c:/Windows/Temp/packer-ps-env-vars-6435e510-7068-68fe-0c18-afcae1720f1a.ps1; &amp;&#39;c:/Windows/Temp/script-6435e510-94b1-e9ee-851d-743e394bdd35.ps1&#39;; exit $LastExitCode }&#34; &gt; %SYSTEMROOT%/Temp/packer-6435e628-8985-4d7f-5886-f3cd3a08d1c4.out 2&gt;&amp;1] for use in XML string
2023/04/11 22:58:48 packer-provisioner-powershell plugin: Uploading elevated shell wrapper for command [powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-6435e510-7068-68fe-0c18-afcae1720f1a.ps1; &'c:/Windows/Temp/script-6435e510-94b1-e9ee-851d-743e394bdd35.ps1'; exit $LastExitCode }" > %SYSTEMROOT%/Temp/packer-6435e628-8985-4d7f-5886-f3cd3a08d1c4.out 2>&1] to [C:/Windows/Temp/packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1]
2023/04/11 22:58:48 packer-provisioner-powershell plugin: [INFO] 3496 bytes written for 'uploadData'
2023/04/11 22:58:48 [INFO] 3496 bytes written for 'uploadData'
2023/04/11 22:58:48 packer-builder-azure-arm plugin: Uploading file to 'C:/Windows/Temp/packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1'
2023/04/11 22:58:49 packer-provisioner-powershell plugin: [INFO] 32 bytes written for 'uploadData'
2023/04/11 22:58:49 [INFO] 32 bytes written for 'uploadData'
2023/04/11 22:58:49 packer-builder-azure-arm plugin: Uploading file to 'c:/Windows/Temp/script-6435e510-94b1-e9ee-851d-743e394bdd35.ps1'
2023/04/11 22:58:50 packer-builder-azure-arm plugin: [INFO] starting remote command: powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1"
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: (39,4):Task:[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1:60 char:1[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: + $f.RegisterTaskDefinition($name, $t, 6, "installer", $password, $logo ...[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], COMException[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1:61 char:1[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: + $t = $f.GetTask("\$name")[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:     + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:     + FullyQualifiedErrorId : System.IO.FileNotFoundException[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: Method invocation failed because [System.__ComObject] does not contain a method named 'Run'.[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: At C:\Windows\Temp\packer-elevated-shell-6435e628-0007-f61b-528d-9a179e29b7f9.ps1:62 char:1[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: + $t.Run($null) | Out-Null[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:     + CategoryInfo          : InvalidOperation: (Run:String) [], RuntimeException[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:     + FullyQualifiedErrorId : MethodNotFound[0m
2023/04/11 22:58:52 ui error: [1;31m==> azure-arm:[0m

**Comment by mikhailkoliada** [comment]
@hiran-filho Hello! Did you specify a proper password for a local windows user?

**Comment by hiran-filho** [comment]
@mikhailkoliada , Hello! I used this Microsoft documentation to make the changes, as there was no indication that it was necessary to have the password, as you can see above in the transcription of the changes I made to the JSON, I removed the password part.
About this password it can be blank?
How is it when the Scale Set creates the VM to run the Jobs, will this password be a problem?

https://learn.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer

**Comment by mikhailkoliada** [comment]
@hiran-filho your template clearly calls `packer-elevated-shell` which requires authentication, so either you should provide a way to authenticate or drop the elevated shell calls. 

I am going to close the ticket as there is nothing actable for us to do, but feel free to reach us out again if you have questions left.
