### ISSUE TITLE
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

### ISSUE THREAD

**Issue by balayml** [actions/runner-images#7437]
### Description

Getting error while build using gradle:

The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Operating System
 Ubuntu
 22.04.2
 LTS

Runner Image
  Image: ubuntu-22.04
  Version: 20230402.1

### Is it regression?

Ubuntu 20.04

### Expected behavior

build success without error The runner has received a shutdown signal.

### Actual behavior

getting The runner has received a shutdown signal.

### Repro steps

Getting error : `The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.`

For workflow `
    # Uses latest stable version of Ubuntu docker image available
    runs-on: ubuntu-latest

    steps:

      # Checkout source code from PR branch
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup JDK from adopt-open distribution
      # gradle cash is enabled and subsequent steps will utilise this
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Gradle action from GitHub marketplace is used for better maintainability
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      # Grants executable file permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew`

**Comment by Alexey-Ayupov** [comment]
Hello @balayml, we will take a look.

**Comment by balayml** [comment]
Thanks @Alexey-Ayupov .

**Comment by jamesnswithers** [comment]
I am seeing this same error on a private project as of 4 days ago for az devops with ubuntu-latest, trying to build an android application using gradle and java 11

**Comment by Alexey-Ayupov** [comment]
We are glad to hear that you have found a workaround. Unfortunately, we cannot manage the runners themselves, so if the CPU load is high the runner will shut down. 
We will close this issue if you have any questions feel free to reach us.

**Comment by jamesnswithers** [comment]
@Alexey-Ayupov I am unrelated to the reporter and so might my anecdotal issue be.
