### ISSUE TITLE
Visual Studio 16.11.24 on Windows 2019 giving license expired

### ISSUE THREAD

**Issue by markatky46** [actions/runner-images#7440]
### Description

We are receiving an error that the Visual Studio license has expired on our Windows 2019 agents. Our image is based on a build performed 13th March 2023. The visual studio version is 16.11.24.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: 20230314.1

https://github.com/actions/runner-images/blob/efd070e7b2cab786a6603503997304e32e14b1ef/images/win/Windows2019-Readme.md

### Is it regression?

No

### Expected behavior

Visual Studio builds complete without error

### Actual behavior

Microsoft Visual Studio 2019 Version 16.11.24.
Copyright (C) Microsoft Corp. All rights reserved.

The license for Visual Studio has expired.

ERR:The process 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com' failed with exit code 1
The evaluation period for this product has ended.Build C:\a\1\s\Data Warehouse General\Data Warehouse General.dtproj failed
ERR:Build failed

### Repro steps

Build something with C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com

<img width="671" alt="image" src="https://user-images.githubusercontent.com/103591278/231992077-2e9019f9-8874-423b-a908-65fdd27d8f7a.png">

**Comment by Alexey-Ayupov** [comment]
Hello @markatky46, this is normal behavior, every newly generated image has a Visual Studio license for one month, please use the latest image in order to solve your problem.

If you have any questions feel free to reach us.

**Comment by markatky46** [comment]
Ah ok, Thanks @Alexey-Ayupov I did not realise this and have never seen the issue before. Is this new?
