### ISSUE TITLE
Update/Add Powershell Module Az 9.6.0

### ISSUE THREAD

**Issue by peruzzof** [actions/runner-images#7441]
### Tool name

Powershell Module: Az 9.6.0

### Tool license

Apache License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

9.6.0

### Brief description of tool

The current version installed is 9.3.0, that has a know bug with Az.Automation 1.9.0 that was fixed 2 months ago.
Currently all my pipelines have a workaround to downgrade Az.Automation to 1.8.0 or update to 1.9.1, if we bump the version this issue will be fixed and I will be able to remove the workaround.

The discussion regarding the bug is here: https://github.com/Azure/azure-powershell/issues/20614

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes, I can

**Comment by mikhailkoliada** [comment]
Hello! given the stability of Az releases we would not like to update a default Az PowerShell version yet, please install the version via the `AzurePowerShell@5` AzDo task.
