### ISSUE TITLE
Invoke-Sqlcmd on windows-2022 throws an error; SqlColumnEncryptionAzureKeyVaultProvider method not found

### ISSUE THREAD

**Issue by cutecycle** [actions/runner-images#7446]
### Description

`SqlServer 22.0.59 / Windows PowerShell 5.1 / windows-2022 / Azure DevOps`

This occurs on Microsoft-hosted agents. 

It may have happened after this update: https://github.com/actions/runner-images/commit/0f4a3567b189f2f0f60582cf99bd5c62c9b8f4e1

When attempting to connect to a Synapse On Demand pool with password authentication, this occurs: 

with the following connection string characteristics:
`;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False`

```powershell
##[debug]Invoke-SqlCmd : Method not found: 'Void Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.SqlColumnEncryptionAzureKeyVaultProvider..ctor(Azure.Core.TokenCredential)'.
##[debug]At D:\a\1\s\deploy\Common.ps1:31 char:27
##[debug]+ ...   $result = Invoke-SqlCmd -ConnectionString $connectionString -query  ...
##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidResult: (:) [Invoke-Sqlcmd], MissingMethodException
##[debug]    + FullyQualifiedErrorId : ExecutionFailed,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at Invoke-AzSqlQuery, D:\a\1\s\file.ps1: line 31
##[debug]at <ScriptBlock>, D:\a\1\s\file2.ps1: line 59
##[debug]at <ScriptBlock>, D:\a\_temp\04a7747b-46d3-4ec0-8b74-6a37641f9b6b.ps1: line 38
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.MissingMethodException: Method not found: 'Void Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.SqlColumnEncryptionAzureKeyVaultProvider..ctor(Azure.Core.TokenCredential)'.
##[debug]   at Microsoft.SqlServer.Management.AlwaysEncrypted.Management.SqlAKVProviderWithDisposableCache..ctor(TokenCredential tokenCredential)
##[debug]   at Microsoft.SqlServer.Management.AlwaysEncrypted.Management.AlwaysEncryptedManagement.SetCustomProvidersWithDisposableCache(Boolean useGlobalCredential)
##[debug]   at Microsoft.SqlServer.Management.PowerShell.Shared.AzureKeyVaultUtilities.RegisterCustomKeyStoreProviders(String keyVaultAccessToken, String managedHsmAccessToken, SqlConnection conn)
##[debug]   at Microsoft.SqlServer.Management.PowerShell.GetScriptCommand.ProcessRecord()
##[error]Method not found: 'Void Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.SqlColumnEncryptionAzureKeyVaultProvider..ctor(Azure.Core.TokenCredential)'.
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link
https://github.com/actions/runner-images/commit/0f4a3567b189f2f0f60582cf99bd5c62c9b8f4e1

### Is it regression?

Yes
```
2023-04-06T16:21:28.8314157Z Image: windows-2022
2023-04-06T16:21:28.8314374Z Version: 20230402.1
2023-04-06T16:21:28.8314693Z Included Software: https://github.com/actions/runner-images/blob/win22/20230402.1/images/win/Windows2022-Readme.md
2023-04-06T16:21:28.8315281Z Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230402.1
```
### Expected behavior

Invoke-SqlCmd connects to the server and executes the command

### Actual behavior

##[debug]System.MissingMethodException: Method not found: 'Void Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.SqlColumnEncryptionAzureKeyVaultProvider..ctor(Azure.Core.TokenCredential)'.

### Repro steps

Connect to a Synapse On Demand pool with password authentication, with the following connection string characteristics:
`;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False`

**Comment by Matteo-T** [comment]
Hi @cutecycle,
 
Could you share a repro that does not involve a pipeline?

What usually matters in these scenarios are:
1) The list of modules loaded when the issue happens (e.g. the output of `Get-Module` before the last cmdlet is executed)
2) Their order of loading

When I have that, I can look into yet another patch to this.

Another useful data point would be to know if this is an issue in PS7 as well.

**Comment by Matteo-T** [comment]
@cutecycle - feel free to transfer this issue to https://github.com/microsoft/SQLServerPSModule/issues

**Comment by mikhailkoliada** [comment]
Closing here as the ticked was moved to the primary repo
