### ISSUE TITLE
vs2015_runtime version 14.34.31933 required, but does not exist

### ISSUE THREAD

**Issue by DominicDirkx** [actions/runner-images#7447]
### Description

Build of C++ code with clang using windows-2022 Azure vmImage requires vs2015_runtime package. Since the update of the Windows Server 2022, it requires vs2015_runtime version 14.34.31933, which does not exist here:
https://anaconda.org/conda-forge/vs2015_runtime/files
Using the previous windows-2022 Azure vmImage (issue first occured April 14; build from April 12 were unaffected), the requested version of vs2015_runtime was 14.34.31931, which is consistent with the latest version on conda-forge 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230407.1
Included Software: https://github.com/actions/runner-images/blob/win22/20230407.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230407.1

### Is it regression?

Yes ```2023-04-12T06:29:07.8425300Z Image: windows-2022 2023-04-12T06:29:07.8425422Z Version: 20230402.1 2023-04-12T06:29:07.8425632Z Included Software: https://github.com/actions/runner-images/blob/win22/20230402.1/images/win/Windows2022-Readme.md 2023-04-12T06:29:07.8425915Z Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230402.1```

### Expected behavior

The package `vs2015_runtime` should be installed, and the build should start.

### Actual behavior

```
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested vs2015_runtime >=14.34.31933 


```

### Repro steps

Run build from:
https://github.com/tudat-team/tudat-feedstock/blob/develop/recipe/meta.yaml. Main point:     
`- {{ compiler('clang') }}  # [win]` 
packages are downloaded fine with `- {{ compiler('clang') }}  # [win]` , but this does not lead to a succesfull build
with vmImage: windows-2022 as here:
https://github.com/tudat-team/tudat-feedstock/blob/develop/.azure-pipelines/azure-pipelines-win.yml

**Comment by sergei-pyshnoi** [comment]
Hello @DominicDirkx . We will take a look.

**Comment by Alexey-Ayupov** [comment]
Hello @DominicDirkx, it looks like this problem is gone with the new image version. At least I cannot reproduce it anymore.
Could you please confirm it, and we will close the issue.

**Comment by DominicDirkx** [comment]
Hi @Alexey-Ayupov, indeed the problem has resolved itself! In the meantime, we have modified our build settings to use MSVC on Windows, to circumvent this problem, as the error occured in a rather critical time for us (we use the software in one of our graduate courses for 50 students, which starts Monday, and needed a rebuild). In the future, would there be a better way for us to:
* Know when new images will be released, so we're certain that we don't need to do any critical releases in the 1-2 weeks after?
* If we do get an issue with a new image, any advice on how to best debug issues ourselves

Regardless, many thanks for taking the time to investigate this problem!

**Comment by Alexey-Ayupov** [comment]
@DominicDirkx, please see the answers to our questions below:
- Know when new images will be released, so we're certain that we don't need to do any critical releases in the 1-2 weeks after?
Normally, we make new image release every week. So every Friday you can expect a new version of the runners.
- If we do get an issue with a new image, any advice on how to best debug issues ourselves
First of all, you can check in our repository what was updated (closed pull requests), based on this information you can debug further however, sometimes it isn't obvious what exactly causes the issue.
