### ISSUE TITLE
Invoke-Sqlcmd: -Variable parameter string parsing changed in v20230407.1

### ISSUE THREAD

**Issue by AndreaCuneo** [actions/runner-images#7450]
### Description

Starting with [v20230407.1](https://github.com/actions/runner-images/blob/win19/20230407.1/images/win/Windows2019-Readme.md), the SqlServer Powershell module has been updated from v21 to v22. The module is used by `SqlAzureDacpacDeployment` task for executing SQL Scripts.

An issue has been opened on the Powershell Module project https://github.com/microsoft/SQLServerPSModule/issues/43 

We used -Variable in SqlAzureDacpacDeployment in Additional Parameters as
`Invoke-Sqlcmd ... -Variable "MyPath = D:\temp\drop\sql\"`

This stopped working in v20230407.1 and all pipelines are failing. 

The impact is that we use the original format in _hundreds_ of Azure DevOps Pipelines which means it takes _days_ of effort to change them all across all customers we manage.

Rollback to v21 until the issue is resolved, or upgrade to newer module if released very soon, would be much appreciated.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[v20230407.1](https://github.com/actions/runner-images/blob/win19/20230407.1/images/win/Windows2019-Readme.md)

### Is it regression?

yes, was working on v20230331.1

### Expected behavior

The -Variable to behave as end of March.

### Actual behavior

The Variable MyPath is not resolved correctly due to have a whitespace in front, which in turn cause the wrong Path resolution when the MyPath variable is used in `:r $(MyPath)"\0001_MigrateX.sql"`

### Repro steps

1. create a SQL script named `migrations.sql` with contents `:r $(MyPath)"\0001_MigrateX.sql"`
2. create a SQL script named `0001_MigrateX.sql"` which any content
3. create a Pipeline which Copy and Publish the above files as and Artifact and a followup stage that use SqlAzureDacpacDeployment to execute the first script
   - Sql Script: `$(System.DefaultWorkingDirectory)/drop/migration.sql`
   - Additional Invoke-Sqlcmd Arguments: `$(System.DefaultWorkingDirectory)\drop\`

**Comment by mikhailkoliada** [comment]
Hello! As the original authors are aware of the issue I am going to close that exact issue as we are always providing the latest version, it is possible to downgrade it in runtime and install the previous one straight in runtime if you need it.
