### ISSUE TITLE
http://azure.archive.ubuntu.com is throwing back 404 Not Found errors

### ISSUE THREAD

**Issue by RobPasMue** [actions/runner-images#7452]
### Description

For a couple of hours we are constantly getting these errors on GitHub runners when trying to install certain packages. See example here: https://github.com/pyansys/python-installer-qt-gui/actions/runs/4717996936/jobs/8367148080?pr=79#step:2:370

```
Get:55 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cups-bsd amd64 2.4.1op1-1ubuntu4.1 [37.0 kB]
Err:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9-common all 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.147.219.192 80]
Err:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9 amd64 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.147.219.192 80]
Err:19 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript amd64 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.147.219.192 80]
Err:20 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript-x amd64 9.55.0~dfsg1-0ubuntu5.1
  404  Not Found [IP: 52.147.219.192 80]
Fetched 161 MB in 4s (38.4 MB/s)
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.55.0%7edfsg1-0ubuntu5.1_all.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.55.0~dfsg1-0ubuntu5.1_all.deb)  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.55.0%7edfsg1-0ubuntu5.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript-x_9.55.0~dfsg1-0ubuntu5.1_amd64.deb)  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230409.1

PR: https://github.com/pyansys/python-installer-qt-gui/pull/79
GH Job: https://github.com/pyansys/python-installer-qt-gui/actions/runs/4717996936/jobs/8367148080

### Is it regression?

https://github.com/pyansys/python-installer-qt-gui/actions/runs/4700414779/jobs/8335081053

### Expected behavior

When doing ``sudo apt-get install libegl1`` we shouldn't be getting this error...

### Actual behavior

Artifacts not found in archive

### Repro steps

Follow the workflow steps.. Aparently if you just checkout an ``ubuntu-latest`` runner and run ``sudo apt-get install libegl1``, this should fail.

**Comment by sergei-pyshnoi** [comment]
Hello @RobPasMue . As I see you already add `apt update` to your workflow. Did it fixed error and can I close the issue?

**Comment by RobPasMue** [comment]
We added ``apt-get update`` indeed. But shouldn't the runners come with an updated version of the repositories? This is the first time something like this happens to us

**Comment by sergei-pyshnoi** [comment]
Runner images updates usually come once a week and package lists in repos are being updated quite more often than it so it's normal.
From [official documentation](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners) :  `Note: Always run sudo apt-get update before installing a package. In case the apt index is stale, this command fetches and re-indexes any available packages, which helps prevent package installation failures.`
I am closing this issue for now. If you have additional question, feel free to ask.
