### ISSUE TITLE
Update/Add [Xcode 14.3]

### ISSUE THREAD

**Issue by jamalalayq** [actions/runner-images#7464]
### Tool name

Xcode

### Tool license

Apple

### Add or update?

- [X] Add
- [ ] Update

### Desired version

14.3

### Approximate size

7 GB

### Brief description of tool

This version of Xcode need to macOS 13.3.1. to accept the installtion.

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by shahzadmajeed** [comment]
Hi, 
I also need Xcode 14.3. If we can add MacOS Ventura support that would be awesome. 
Thank you

**Comment by sergei-pyshnoi** [comment]
Hello @jamalalayq . Clone of https://github.com/actions/runner-images/issues/7375 . Please keep an eye on our announcements about macOS 13.
