### ISSUE TITLE
CMake updates after February are unable to find properly-installed zlib

### ISSUE THREAD

**Issue by squinky86** [actions/runner-images#7475]
### Description

After February, CMake has been unable to find zlib. This is a regression from the builds that occurred with ubuntu-latest (also using Jammy) prior to February.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/squinky86/STIGQter/actions/runs/4765396010/jobs/8471064959

CMake provided with the latest "ubuntu-latest" has a bug with finding zlib. The bug is documented here: https://gitlab.kitware.com/cmake/cmake/-/issues/20127

When updating ubuntu-latest to 22.04, my builds began to fail because they rely on libxlsxwriter which uses:
`find_package(ZLIB REQUIRED "1.0")`
in its CMakeLists.txt file. This results in a failed build:

```
-- The C compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/local/share/cmake-3.2[6](https://github.com/squinky86/STIGQter/actions/runs/4765396010/jobs/8471064959#step:7:7)/Modules/FindZLIB.cmake:[8](https://github.com/squinky86/STIGQter/actions/runs/4765396010/jobs/8471064959#step:7:9)8 (message):
  ZLIB does not provide any COMPONENTS.  Calling

    find_package(ZLIB COMPONENTS ...)

  will always fail.
Call Stack (most recent call first):
  CMakeLists.txt:222 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/local/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: 1.0) (found version "1.2.[11](https://github.com/squinky86/STIGQter/actions/runs/4765396010/jobs/8471064959#step:7:12)")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.26/Modules/FindZLIB.cmake:[20](https://github.com/squinky86/STIGQter/actions/runs/4765396010/jobs/8471064959#step:7:21)0 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:[22](https://github.com/squinky86/STIGQter/actions/runs/4765396010/jobs/8471064959#step:7:23)2 (find_package)


-- Configuring incomplete, errors occurred!
```

### Is it regression?

22.04, https://github.com/squinky86/STIGQter/actions/runs/4168371991

### Expected behavior

CMake should find zlib.

### Actual behavior

CMake finds ZLib and reports failure.

### Repro steps

Attempt to build a package with the CMake update that was pushed after February (note that it is now installed to /usr/local/share/cmake-3.26) which tries to link to a minimum zlib version using:
`find_package(ZLIB REQUIRED "1.0")`

**Comment by sergei-pyshnoi** [comment]
Hello @squinky86 . We will take a look.

**Comment by sergei-pyshnoi** [comment]
Hello! As the original authors are aware of the issue I am going to close that exact issue as we are always providing the latest version, it is possible to downgrade it in runtime and install the previous one straight in runtime if you need it.
