### ISSUE TITLE
Add gomplate

### ISSUE THREAD

**Issue by Thammachart** [actions/runner-images#7477]
### Tool name

gomplate

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v3.11.5

### Approximate size

10 - 52 MiB

### Brief description of tool

From [repo](https://github.com/hairyhenderson/gomplate):

`gomplate` is a template renderer which supports a growing list of datasources, such as: JSON (including EJSON - encrypted JSON), YAML, AWS EC2 metadata, [Hashicorp Consul](https://www.consul.io/) and [Hashicorp Vault](https://www.vaultproject.io/) secrets.

### URL for tool's homepage

https://docs.gomplate.ca/

### Provide a basic test case to validate the tool's functionality.

```bash
It is used to render templates into completed files, given the data sources and/or environments, straight from cli.

For example, render templates of K8s Deployment YAML manifest to have proper container image name and tag.
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
There are various ways to install the latest version of this tool without the need of building from scratch.

For Linux-based:
$ npm install --location=global gomplate

For macOS-based:
$ brew install gomplate

For more information: https://docs.gomplate.ca/installing/
```

### Tool installation time in runtime

binary installation should takes less than 30s, given good connection

### Are you willing to submit a PR?

yes

**Comment by erik-bershel** [comment]
Hey @Thammachart! We would not like to install the tool due to small installation time and maintenance concerns. Please, install it in runtime by adding additional step in your pipeline. I am closing this issue, but if you have additional questions feel free to ask.
