### ISSUE TITLE
Update/Add Xcode 14.3

### ISSUE THREAD

**Issue by kanstantsin-bucha** [actions/runner-images#7479]
### Tool name

Xcode

### Tool license

default

### Add or update?

- [X] Add
- [ ] Update

### Desired version

14.3

### Brief description of tool

The Xcode 14.3 have been released. It has updates in XCTests frameworks that fixes issues with testing async functions. (Deadlocks). It introduces a new way of waiting for expectations:
```
await fulfillment(of: [exp], timeout: 5)
```
Instead of:
```
wait(for: [exp], timeout: 5)
```

### URL for tool's homepage

default

### Provide a basic test case to validate the tool's functionality.

```bash
This test should compile.

import XCTest
class Tests: XCTestCase {
 func test_async_waiting() async {
    let exp = expectation(description: "Wait")
    exp.fulfill()
    await fulfillment(of: [exp], timeout: 5)
 }
}
```
```


### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

### Tool installation time in runtime

~30 min

### Are you willing to submit a PR?

I  have no idea how to do it =)

**Comment by Alexey-Ayupov** [comment]
Hello @kanstantsin-bucha. Clone of https://github.com/actions/runner-images/issues/7375 . Please keep an eye on our announcements about macOS 13.
