### ISSUE TITLE
Builds running on ubuntu-latest are consistently failing

### ISSUE THREAD

**Issue by mike-soak** [actions/runner-images#7480]
### Description

Actions that were previously completing are erroring during the second build step when running apt update …
```
E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230417.1

### Is it regression?

https://github.com/Games-Workshop/warhammer-40000-wordpress/actions/runs/4766216317

### Expected behavior

GitHub Action is expected to complete.

### Actual behavior

GitHub Action exits while fetching a runner.

### Repro steps

Initiate a GitHub Action running on ubuntu-latest.

**Comment by ilia-shipitsin** [comment]
Helllo, @mike-soak 

I'm able to run "sudo apt update", please have a look: https://github.com/ilia-shipitsin/gh7480/actions/runs/4787995309/jobs/8513988073


also, Ubuntu runner comes without `stretch/updates` repo (that's why build fails, it fails on "grep")

looks, there's something changed on [debian side](https://serverfault.com/questions/1074688/security-debian-org-does-not-have-a-release-file-on-with-debian-docker-images)

**Comment by mike-soak** [comment]
Hi @ilia-shipitsin 

Thanks for confirming there’s an issue. Surely this must be affecting many other builds using ubntu-latest?
Here’s a portion of my build log highlighting the difference between a working build and an affected build …

Working
```
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [59.1 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [3177 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [782 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Fetched 8135 kB in 1s (5661 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
25 packages can be upgraded. Run 'apt list --upgradable' to see them.
Removing intermediate container 4512698ca91e
 ---> 42e0ef134d61
Step 3/13 : RUN apt -yq install rsync openssh-client
 ---> Running in f5b7eba86cec
```

Failed
```
Ign:1 http://deb.debian.org/debian stretch InRelease
Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
Ign:3 http://deb.debian.org/debian stretch-updates InRelease
Err:4 http://security.debian.org/debian-security stretch/updates Release
  404  Not Found [IP: 151.101.2.132 80]
Err:5 http://deb.debian.org/debian stretch Release
  404  Not Found
Err:6 http://deb.debian.org/debian stretch-updates Release
  404  Not Found
Reading package lists...
E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
E: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
E: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
The command '/bin/sh -c apt update' returned a non-zero code: 100
```

Is this something GitHub is likely to attempt to resolve? Seems like it’s something they would be responsible for.
Please excuse my ignorance. This is the only issue I’ve raised to date on GitHub!

**Comment by mike-soak** [comment]
@ilia-shipitsin I think in my case the issue is with `AEnterprise/rsync-deploy`. It appears this repository has open issues relating to this exact build error. One user has forked the package and made the necessary change.
