### ISSUE TITLE
`rustup update stable` fails on `windows-2022`

### ISSUE THREAD

**Issue by acfoltzer** [actions/runner-images#7491]
### Description

On a `windows-2022` runner, `rustup update stable` attempts to self-update `rustup`, which fails due to permissions issues. This can be worked around by using specifying `rustup update --no-self-update stable`, but the `rustup` configured on this image should disallow self-updates as is already the case on other platforms.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Image: windows-2022
  Version: 20230417.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20230417.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230417.1
```
Failed build example: https://github.com/fastly/Viceroy/actions/runs/4803052207/jobs/8547545298

### Is it regression?

Sort of; previous builds succeeded but a new version of `rustup` is now available which triggers the self-update attempt

### Expected behavior

`rustup update stable` should update the Rust toolchain to the latest stable version.

### Actual behavior

The toolchain gets updated, but then an automatic self-update attempt follows which fails:

```
  stable-x86_64-pc-windows-msvc updated - rustc 1.69.0 (84c898d65 2023-04-16) (from rustc 1.68.2 (9eb3afe9e 2023-03-27))

info: checking for self-updates
info: downloading self-update
D:\a\_temp\3fd06ecf-b61a-45bf-bd0a-f3a4aa6937e7.sh: line 1: /c/Users/runneradmin/.cargo/bin/rustup: Device or resource busy
```

### Repro steps

Run an action on `windows-2022` and attempt to run `rustup update stable`

**Comment by ilia-shipitsin** [comment]
@acfoltzer , I'll have a look

**Comment by ilia-shipitsin** [comment]
@acfoltzer , it looks weird

```
    - name: Install Rust
      run: |
        rustup update stable
        sleep 60
        rustup default stable
      shell: bash
```

seems, there's some external locking (maybe windows defender ?) which locks files.
as a workaround, small delay between steps help

hope, we'll find better solution ...

**Comment by acfoltzer** [comment]
@ilia-shipitsin fascinating! I didn't emphasize the following `rustup default stable` in my report given that the `--no-self-update` flag on the first command solved the issue.

**Comment by ilia-shipitsin** [comment]
@acfoltzer , I'm not very familiar with rust, is current workaround good enough ? or there's still some bug hiding ?

**Comment by acfoltzer** [comment]
@ilia-shipitsin it is good enough for my purposes, but this is not a commonly-used flag for `rustup`, and I expect others will run into similar issues.

On Linux there is a `rustup` config file at `$HOME/.rustup/settings.toml`. It contains a key `auto_self_update = "enable"` by default; if we could change that to `auto_self_update = "disable"` in the image I suspect the workaround would no longer be necessary.

According to [these docs](https://rust-lang.github.io/rustup/configuration.html) the settings file should be at `%USERPROFILE%/.rustup/settings.toml`

**Comment by ilia-shipitsin** [comment]
mmm, do you want to open a PR ? ))

**Comment by ilia-shipitsin** [comment]
I've just realised that images are shipped without user (user is created later), so it is not possible to populate `$HOME/.rustup/settings.toml` during image generation.

we'll discuss it and maybe we'll address rustup tuning during later phases

**Comment by acfoltzer** [comment]
I would be happy to contribute, but I do not have Windows knowhow or a means to reproduce locally.

> or maybe it might be configured system wide ?

It looks like `RUSTUP_HOME` is overwritten here during the install process: https://github.com/actions/runner-images/blob/f4bbf91a0801f0f6d4ca07879837ab142bb3c944/images/win/scripts/Installers/Install-Rust.ps1#L7

So the settings file might be found at `C:\Users\Default\.rustup\settings.toml`?

**Comment by ilia-shipitsin** [comment]
@acfoltzer , I'm a bit confused. `RUSTUP_HOME` is indeed set during image generation, but it is not set during CI job.
so, I guess rustup has no way to find that file.

should it be considered as a bug ?

**Comment by acfoltzer** [comment]
@ilia-shipitsin possibly; again I do not know much about Windows but `rustup` will look for the settings file in `%USERPROFILE%/.rustup/settings.toml`. If `%USERPROFILE%` expands to `C:\Users\Default` it might work, but maybe that's not the environment where images run?

**Comment by ilia-shipitsin** [comment]
@acfoltzer , fyi

runner is created from scratch with no user. however 'c:\users\default' is used as a skeleton for creating users.
so, mentioned "settings.toml" is copied to user profile during user creatiion.

seems, we can add "no self update" to that file during image generation.
however, I'm not skilled in rust to justify whether it makes sense..

**Comment by acfoltzer** [comment]
@ilia-shipitsin it definitely makes sense, and is the behavior of the other OS runners. Having an initial version of `rustup` fixed when the image is created is just fine, it doesn't prevent people from changing `rustc` compiler versions or anything

**Comment by ilia-shipitsin** [comment]
@acfoltzer , so far, I investigated on standalone machine, rustup does not block itself.

either we miss something or github actions machinery locks files.
we are trying to investigate that, if we won't be lucky, we'll modify settings.toml to prevent auto self update (however, currently I do not see clear reason for such disabling)

**Comment by acfoltzer** [comment]
Great news, thank you for helping out in unfamiliar territory @ilia-shipitsin 🙏🏻
