### ISSUE TITLE
Error while building docker IOT Edge modules on ubuntu 20.04 agent - Latest agent version

### ISSUE THREAD

**Issue by dharanidhar-m** [actions/runner-images#7503]
### Description

Whenever docker build getting the following error

"/home/vsts/.local/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.0.0) or chardet (3.0.4)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn(
ERROR: ('Could not connect to Docker daemon. Please make sure Docker daemon is running and accessible', DockerException("Error while fetching server API version: request() got an unexpected keyword argument 'chunked'"))"

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: '20230426.1'

### Is it regression?

No

### Expected behavior

Docker build should happen

### Actual behavior

Failing with error

### Repro steps

Build a dockerized application

**Comment by ilia-shipitsin** [comment]
Hello, @dharanidhar-m 

can you please describe repro steps ?

(if those pipelines are somewhere in public repo, link would be just fine)

**Comment by dharanidhar-m** [comment]
1. Create a Pipeline
2. Develop IOT Edge C# Custom Module
3. Use "task: AzureIoTEdge@2" for building the edge module

**Comment by ilia-shipitsin** [comment]
Dear @dharanidhar-m , I confirm that mentioned task [fails](https://github.com/ilia-shipitsin/iot-edge-sample-c) (I tried both 20.04 and 22.04) with sample project using documentation provided

those tasks are supported in dedicated [repo](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureIoTEdgeV2/task.json), I suggest you to follow up there. 

looks, there is [similar issue](https://github.com/microsoft/azure-pipelines-tasks/issues/18209) already
