### ISSUE TITLE
Add macOS 14 (Sonoma) Runner Image

### ISSUE THREAD

**Issue by Steve-Glass** [actions/runner-images#7508]
### Tool name

macOS 14 

### Tool license

TBD

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Beta

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Steve-Glass** [comment]
This issue a placeholder and will be updated after [WWDC 2023](https://developer.apple.com/wwdc23/).

**Comment by ilia-shipitsin** [comment]
dummy reply to make our automation happy, please ignore ....

**Comment by fumoboy007** [comment]
Hi, is there an existing issue tracking the graduation of macOS 13 to GA (a.k.a. `macos-latest`)?

**Comment by mrackwitz** [comment]
With the release candidate available for Sonoma, what's the timeline to be made available as a GitHub Actions runner?

**Comment by mikhailkoliada** [comment]
Hello, no earlier than the official release comes out, we do not provide betas/rcs

**Comment by paulofierro** [comment]
Hi folks, it's been 2 weeks since Sonoma dropped. Any news on this front?

**Comment by ecnepsnai** [comment]
3 weeks since Sonoma was released. Could we please get an update or at least a confirmation that this is being worked on?

**Comment by Amnell** [comment]
Will this be a repetition of #6426 where it took more than 6 months from public release from Apple until an image was available at GitHub?

**Comment by paulofierro** [comment]
Quoting @Steve-Glass [from 7 months ago](https://github.com/actions/runner-images/issues/6426#issuecomment-1479974889) when discussing why it took 6 months to get a macOS 13 runner and how things will improve:
> Our team is not aware of any hardware compatibility requirements that would prevent us from prioritizing and providing the macOS 14 runner image in a timely manner.

Granted, it's "only" been a month, but we're now looking at alternatives. It's frustrating that this seems to happen with **every** new version of macOS. Its not like they're a surprise.

**Comment by BenjaminBhuyanYoung** [comment]
Is there any timeline for macOS 14/Sonoma?

**Comment by RyosukeCla** [comment]
Is there any progress for macOS 14/Sonoma?

**Comment by Andrewangeta** [comment]
Any timeline on when macOS Sonoma will be supported? Kinda getting long in the tooth here.

**Comment by dvosscricut** [comment]
me too, I can't even run Xcode 14.2 on Sonoma, I'm stuck at Xcode 15! Would be really helpful if GitHub action runners could match!

**Comment by mrackwitz** [comment]
@dvosscricut Xcode 15.0.1 is available on the latest macOS 13 runners. (You don't need Sonoma anymore to run Xcode 15, at least ever since the RC)

**Comment by Andrewangeta** [comment]
Just gonna migrate to XCode cloud for my iOS stuff.

**Comment by pafdad** [comment]
Hello

Please could we get a response on this thread? Would be great to have some communication from GitHub on this matter please.

Thank you in advance.

**Comment by fumoboy007** [comment]
@Steve-Glass @mikhailkoliada Please say _something_ for the sake of GitHub’s reputation. I get that there may be challenges or that this issue may not even be a high priority. However, complete silence is _worse_ than the delay.

Just a few sentences should suffice. For example:
> Very sorry for the delay. Our team is currently stretched thin working on X, Y, and Z issues, which management has deemed to be a higher priority. We aim to get around to this issue sometime next month.

**Comment by Steve-Glass** [comment]
👋 Our team has already started preparations for the macOS 14 public beta. We expect the runner image to be made available in January 2024.

**Comment by gereons** [comment]
Very disappointed to see that many months of delay is what is considered [top priority](https://github.com/actions/runner-images/issues/6426#issuecomment-1479974889).

**Comment by andrewdavidmackenzie** [comment]
It seems you can set the target os as macos-14 and the workflow and job will "run", but it will suspect forever waiting for a runner to execute it?

"Requested labels: macos-14
Job defined at: andrewdavidmackenzie/flow/.github/workflows/build_and_test.yml@refs/heads/master
Waiting for a runner to pick up this job..."

**Comment by brian-kayfitz** [comment]
Any updates on this?  

My team might have to stop using GitHub Actions soon because of the inability to use the latest iOS SDK.  There were some breaking changes that Apple made to EventKit that we were forced to make our app compile in the latest version of Xcode, but consequently, we can no longer use GitHub Actions to compile release builds.

If it's any consolation, this is the required API:
https://developer.apple.com/documentation/eventkit/ekeventstore/4162272-requestfullaccesstoevents

**Comment by dungi** [comment]
> Any updates on this?  
> 
> 
> 
> My team might have to stop using GitHub Actions...
> 
> 

The latest Xcode is also running on macOS 13. no need to wait for 14.

**Comment by brian-kayfitz** [comment]
> > Any updates on this?
> > My team might have to stop using GitHub Actions...
> 
> The latest Xcode is also running on macOS 13. no need to wait for 14.

That's great, thanks @dungi  I tried using `macos-13-large` to compile the app and still got the same swift error.
`Swift Compiler Error (Xcode): Value of type 'EKEventStore' has no member 'requestFullAccessToEvents'`

Is macos-13-large also not using the most recent version of the iOS SDK?

**Comment by dungi** [comment]
> 
> 
> Is macos-13-large also not using the most recent version of the iOS SDK?
> 
> 

Did you tried setting the newest xcode version and Selecting the newest sdks in your project file?

- name: Set Xcode Version
  run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

**Comment by chriswooden** [comment]
> 👋 Our team has already started preparations for the macOS 14 public beta. We expect the runner image to be made available in January 2024.

Any update on this eta? We're seeing increased test time and intermittent timeouts with Xcode 15.1 on macOS 13, so forced to roll back to Xcode 14. Understand macOS 14 resolves these Xcode 15 issues? Frustrating we still can't make use of iOS 17 apis in January 😞

**Comment by shagedorn** [comment]
@chriswooden we've finally seen a return to predictable and reasonable unit test runtimes with the adoption of Xcode 15.1, **but** we also needed to make sure our tests run on an iOS 17.2 runtime simulator. It's only been a few days, but we've had very stable (and fairly fast) results since then. Our test setup uses the `macos-13-xlarge` aka M1 runners.

That said, we are also (still) wondering when macOS 14 nodes arrive, given they will sooner or later become a requirement for the latest Xcode versions. But for the time being, we have no hard dependency on it.

**Comment by jacobsapps** [comment]
Hey @chriswooden, long time no speak! Hope all is well 

Surprised by how low-priortiy this issue is being treated considering mac runners costs 10x as much as others. Is everyone just rolling self-hosted?

**Comment by chriswooden** [comment]
@shagedorn Thanks for the tip, we hadn't tried this previously but can confirm it improves things.

Hey @jacobsapps 👋 We did consider self-hosting - seemed like a decent justification to get the company to buy us some Mac Pros... still waiting to hear back on that suggestion though... 😄

**Comment by iosdevben** [comment]
I've come across a bug with the iOS Simulator ignoring the language I set in the xctestplan, which is apparently resolved when run on macOS Sonoma.

Very keen to see GitHub release the macOS 14 xlarge runner.

**Comment by mariusfanu-metrobank** [comment]
On 12 September 2023 Apple announced the following [here](https://developer.apple.com/news/?id=khzvxn8a) :

> Starting in April 2024, apps submitted to the App Store must be built with Xcode 15 and the iOS 17 SDK, tvOS 17 SDK, or watchOS 10 SDK (or later).

Currently there is no production ready way to run Xcode 15 as macOS 13 runner image is still in beta/preview and macOS 14 is still work in progress.

Given that we are only a few months away from hitting the hard requirement from Apple,  it would be great to have some visibility on what are your expected timelines when these will be provided.

On Azure DevOps Pipelines when updating from macOS 12 to macOS 13 while still using Xcode 14.2 the build time increased **~4x times** and testing increased **~7x times**


@Steve-Glass do you have any timelines or additional information? This would be very helpful for us to at least plan for

The only information that I've found [here](https://github.com/github/roadmap/issues/814) is a timeline of **January - March**, but it would be great if we can get a more accurate date. 
That is very close to Apple's April deadline, and also looking at history I can see this date has shifted many times in the past, from **Q3 2023** to now **Q1 2024**, which is worrying

**Comment by dungi** [comment]
Or just `run: sudo xcode-select -s /Applications/Xcode_15.2.app`

**Comment by shagedorn** [comment]
@mariusfanu-metrobank have you tried [this](https://github.com/actions/runner-images/issues/7508#issuecomment-1880780025)? This works very well for us since Xcode 15.1 has been made available.

**Comment by mariusfanu-metrobank** [comment]
HI @shagedorn do you mean to use the `macos-13-xlarge` agents? Unfortunately I don't think these are available on Azure DevOps

Also our project would have different issues if moving to ARM based Macs, for example snapshots test will fail due to tiny differences in how images are generated etc.

**Comment by shagedorn** [comment]
@mariusfanu-metrobank my focus in that comment was meant to be on adopting Xcode 15.1 (which is now available) **and** making sure to use it with iOS 17.2 runtime simulators. We have a script to create a new simulator for each CI job to not take any chances:

```bash
echo "Removing all simulators"
xcrun simctl delete all

echo "Creating new test simulator"
xcrun simctl create MyTestSimulator com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-2

echo "Listing all simulators for confirmation"
xcrun simctl list
```
_(this is executed via fastlane which pins down the Xcode/xcrun version to Xcode 15.1)_

We have not tried this on Intel runners so I don't know if this helps in the same way, but for Apple Silicon runners, this combination has resolved all the CI issues (especially with regard to unit test duration) we've been seeing since Xcode 15.0 came out.

**Comment by mariusfanu-metrobank** [comment]
Good to know, thanks @shagedorn

**Comment by vlad-buhaescu-qoob** [comment]
Also looking into this as we updated our machines to Sonoma.

**Comment by remyjette** [comment]
> We have not tried this on Intel runners so I don't know if this helps in the same way, but for Apple Silicon runners, this combination has resolved all the CI issues 

Sadly this didn't help for me using the `macos-13` (intel) agent in Azure DevOps, but thank you for posting it

**Comment by mariusfanu-metrobank** [comment]
Seems like macOS 14 will be added soon according to #9179

**Comment by iosdevben** [comment]
Removing and recreating the simulators fixed the issues for me.

**Comment by mikhailkoliada** [comment]
As of https://github.com/actions/runner-images/issues/9254 and https://github.com/actions/runner-images/issues/9255 OS14 is now available!

**Comment by svaldetero** [comment]
@mikhailkoliada Do we have an item to follow or a way to know about Azure Devops availability? It is checked in the issue description but I get `##[warning]An image label with the label macOS-14 does not exist.`

**Comment by mariusfanu-metrobank** [comment]
+1

**Comment by filipw** [comment]
The issue says:

> Platforms where you need the tool
>
>  [x] Azure DevOps
>  [x] GitHub Actions

This was closed as completed, but the [announcement](https://github.com/actions/runner-images/issues/9254) only mentions GitHub Actions, and not ADO

> Platforms affected
>
>  [ ] Azure DevOps
>  [x] GitHub Actions

I think it should be reopened until Azure DevOps support is added.

**Comment by billnbell2** [comment]
When is beta going to be released for Mac OS 14 on M1/M2 chips? I see the roadmap but no dates? Are we getting closer to a date?

https://ch1n2.wordpress.com/2022/09/19/how-to-deploy-an-ssis-project-via-azure-devops/

**Comment by 3a4oT** [comment]
> The issue says:
> 
> > Platforms where you need the tool
> > [x] Azure DevOps
> > [x] GitHub Actions
> 
> This was closed as completed, but the [announcement](https://github.com/actions/runner-images/issues/9254) only mentions GitHub Actions, and not ADO
> 
> > Platforms affected
> > [ ] Azure DevOps
> > [x] GitHub Actions
> 
> I think it should be reopened until Azure DevOps support is added.

Agree! Can we please get an update for Azure DevOps?

**Comment by muellnes** [comment]
Included with #8971

**Comment by jtromo** [comment]
@muellnes  https://github.com/actions/runner-images/issues/8971 is adding ARM64 runners and this ticket is for a general macOS 14 image so it seems appropriate to keep this open.

**Comment by jtromo** [comment]
Note that Apple will start requiring Xcode 15 or later April 19 which requires macOS 14 so this is going to be a deal breaker for any iOS developers using Azure DevOps.

> ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

**Comment by mariusfanu-metrobank** [comment]
@jtromo Xcode 15.0 until Xcode 15.2 can still run on macOS 13, so this should not be a blocker. Xcode 15.3 will require macOS 14 

See below from release notes from specific Xcode version:

> Xcode 15 requires a Mac running macOS Ventura 13.5 or later.
> Xcode 15.2 requires a Mac running macOS Ventura 13.5 or later.
> Xcode 15.3 beta 3 requires a Mac running macOS Sonoma 14 or later.

**Comment by jtromo** [comment]
Thanks. Looks like manually selecting Xcode 15.2 on macOS-13 works.

**Comment by 3a4oT** [comment]
Hey all, #9459 was merged, but it doesn't include the Azure Pipelines runners update. Who can help us and at least provide an ETA?

**Comment by nbevans** [comment]
> Thanks. Looks like manually selecting Xcode 15.2 on macOS-13 works.

How? macos-latest on ADO doesn't have Xcode 15 at all for me. Doing a `ls` in the `/Applications` directory only shows Xcode 13 and 14 versions.

**Comment by nbevans** [comment]
Right well this is like _really_ messed up. Apparently using `macos-latest` on ADO is broken and doesn't actually use `macos-13`. If I manually choose `macos-13` instead of `macos-latest`, I get Xcode 15:

<img width="389" alt="image" src="https://github.com/actions/runner-images/assets/542188/a86a8510-7b32-4663-88f4-4d9c9379192f">

**Comment by Baza207** [comment]
So it seems like macOS 14 non-arm runners released the other with no notice or information. Are we going to get any info on if we'll see the same roadmap as GitHub on DevOps or just continued radio silence and random unannounced updates?

https://github.com/actions/runner-images/releases/tag/macos-14/20240422.1

**Comment by muzimuzhi** [comment]
@Baza207 I think the linked release [macos-14/20240422.1](https://github.com/actions/runner-images/releases/tag/macos-14/20240422.1) is specifically for macOS 14 larger runner, as can be seen from its assets.

Non-arm macOS 14 larger runners are documented in
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners
and more or less announced with
https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

**Comment by Baza207** [comment]
@muzimuzhi Oh interesting point, thanks for the links. 🙇‍♂️

I did try it in our Azure DevOps pipeline quickly on Friday and it found an agent and ran on Xcode 15.3 (our tests failed, but the agent was there running macOS 14), which previously we weren't able to do with large or xLarge agents. I just used the `macos-14` agent name as well, not `macos-14-large`. Could have been a fluke, but we'll see when I'm able to test a bit more. 🤷‍♂️

**Comment by Baza207** [comment]
@muzimuzhi Found the DevOps link. The ones you listed I think are the ones references in #9255 when they (incorrectly) closed all these issues.

Here's the link for DevOps users: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

**Comment by Siedlerchr** [comment]
Here is also the announcements from Azure Devops itself, unfortunately still no arm runners. Just the x86_64 with sonomo https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline-released
