### ISSUE TITLE
npm server in GitHub Action stage responding with HTTP status 403

### ISSUE THREAD

**Issue by aseggemu-yoc** [actions/runner-images#7512]
### Description

**Error**
Failed to load resource: the server responded with a HTTP status of 403 (Forbidden)

**Context**
The issue is happening on a private repo when we updated from Ubuntu 18.04 to 20.04 it failed. We tried updating from Ubuntu 18.04 to 22.04 and latest. But we are getting HTTP status of 403 (Forbidden). This is causing our tests to fail.

We have already create a support ticket https://support.github.com/ticket/personal/0/2124288 for more information on the build links.
Note: It is a private repo and we are using GitHub team plan.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.303.0

### Is it regression?

2.303.0

### Expected behavior

The npm server is  responding with a HTTP status of 403 (Forbidden)

### Actual behavior

The npm server should  respond with a HTTP status of 200

### Repro steps

1. Update GitHub Actions workfile ubuntu image from 18.04 to 22.04 `runs-on: ubuntu-22.04`
2. step - `uses: actions/checkout@v2`
3. step - `Use Node.js 16.13.1`
4. step - `actions/setup-node@v2`
5. step - `with:
                  node-version: '16.13.1'`
6. step - `npm run server`
7. npm starts running server on localhost:8081 
8. Detach the server using `.unref();`
```
.unref();

process.exit(0);
```
9. The npm server on port 8081 responds with HTTP status 403  (Forbidden)

**Comment by erik-bershel** [comment]
@aseggemu-yoc please provide actual repro steps. There are no reason to share private project to do it as I see.

**Comment by aseggemu-yoc** [comment]
> @aseggemu-yoc please provide actual repro steps. There are no reason to share private project to do it as I see.

I updated the reproduction steps. More details are in the build link of the github support.

**Comment by ilia-shipitsin** [comment]
@aseggemu-yoc , can you please try  adding `sudo systemctl stop mono-xsp4` before test invocation ?

**Comment by aseggemu-yoc** [comment]
@ilia-shipitsin I tried it
```
  sudo systemctl stop mono-xsp4
  shell: /usr/bin/bash -e {0}
```

but it did not solve the issue. I added extra reproduction step if it helps as we use `.unref();` to detach the server.

**Comment by dmitry-shibanov** [comment]
Hello @aseggemu-yoc. Sorry for the late response. I have some questions regarding to the issue:
 - Do you use any kind virtualisation ?
 - Does the issue reproduce only for port 8081 or others too ? 
 - Does the issue reproduce for other Nodejs versions ?
 
 I tried to reproduce the issue I created a simple server. Through the `child_process` I run server as a child process and `unref()` it. I could access it and get information from it in the parent process and the next step. Could you please correct me If I have a misunderstanding in my set up ? If this looks right, could you please provide a public repository?

**Comment by aseggemu-yoc** [comment]
> Hello @aseggemu-yoc. Sorry for the late response. I have some questions regarding to the issue:
> 
> * Do you use any kind virtualisation ?

We use docker compose for the virtualisation of the server comprising of php and nginx docker images as test server which listens to port 9000

> * Does the issue reproduce only for port 8081 or others too ?

The issue is also on port 3000 where we have a server running for [ngrok](https://www.npmjs.com/package/ngrok)

> * Does the issue reproduce for other Nodejs versions ?

No, we did not try other versions as we have projects on Node.JS version: 16.13.1. We would like to use only the version 16.13.1.
 
> I tried to reproduce the issue I created a simple server. Through the `child_process` I run server as a child process and `unref()` it. I could access it and get information from it in the parent process and the next step. Could you please correct me If I have a misunderstanding in my set up ? If this looks right, could you please provide a public repository?

You are using it correct. We cannot provide a public repository. As mentioned our repo is a private repository.

**Comment by mikhailkoliada** [comment]
@aseggemu-yoc could you please provide a minimal public repo (not mandatory consisting a code you use privately) so we could make sure we can reproduce your issue. Currently, if I understand correctly @dmitry-shibanov could not reproduce your issue.

**Comment by aseggemu-yoc** [comment]
> @aseggemu-yoc could you please provide a minimal public repo (not mandatory consisting a code you use privately) so we could make sure we can reproduce your issue. Currently, if I understand correctly @dmitry-shibanov could not reproduce your issue.

I'm unable to create a minimal public repo as most of the code is private. It creates a lot burden on me to create new GitHub actions, new repo. I appreciate the GitHub internal team to coordinate and look into the private repo where the issue is happening.

**Comment by aseggemu-yoc** [comment]
The GitHub support staff was given access to the private repo. More details in the support ticket.
I'm closing this as the issue is not solved and I lost trust in GitHub actions.
