### ISSUE TITLE
macOS 13 Runner Missing App Center CLI

### ISSUE THREAD

**Issue by eseay** [actions/runner-images#7514]
### Description

After upgrading to the macOS 13 runners, we're unable to upload our builds to App Center using the CLI. An audit of the [macOS 13 README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) indicates that it is not pre-installed.

When building, we receive the following error:

```
/Users/runner/work/_temp/2f167934-85a2-4ed2-b379-837fc7c1a9e8.sh: line 6: appcenter: command not found
Error: Process completed with exit code 127.
```

This tool exists pre-installed on [macOS 12 runners](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md?plain=1#L92).

If this is something we need to install on our own now, I guess that's fine; I'd just like to understand whether the exclusion of the tool was intentional or if I should wait for it to get added instead of implementing a workaround.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macOS-13 - 20230419.1

### Is it regression?

It appears so to me, but I need to understand the intent of the engineering team.

### Expected behavior

I expected the pre-installed software on the macOS 13 runner to be a superset of that which was installed on macOS 12.

### Actual behavior

macOS 13 runners cannot invoke the App Center CLI out of the box.

### Repro steps

- Run a job against the macOS 13 runner
- Try to invoke the `appcenter` command

**Comment by ilia-shipitsin** [comment]
the intent is indeed to ship macOS-13 identically to 12.
I'm not sure whether App Center CLI is available for macos-13, if it is, it will be added (someday)

**Comment by erik-bershel** [comment]
Hey @eseay! 
At the moment we won't add App Center CLI to macOS 13 images due to maintenance concerns mainly. 
So available options are to use macOS 11/12 runners or to install App Center CLI in runtime on macOS 13 runner.

**Comment by eseay** [comment]
@erik-bershel Thanks for the clarification. Installing was no big deal - just wanted to make sure it was the right solution.
