### ISSUE TITLE
Add Microsoft.Health.Fhir.Liquid.Converter.Tool in the tools

### ISSUE THREAD

**Issue by tahirjaved1** [actions/runner-images#7517]
### Tool name

Microsoft.Health.Fhir.Liquid.Converter.Tool 

### Tool license

MIT License

### Add or update?

- [x] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

FHIR Converter is an open source project that enables conversion of health data from legacy formats to FHIR.

### URL for tool's homepage

https://github.com/microsoft/FHIR-Converter

### Provide a basic test case to validate the tool's functionality.

```bash
Microsoft.Health.Fhir.Liquid.Converter.Tool.exe push <container-registry>
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

few seconds

### Are you willing to submit a PR?

yes

**Comment by Alexey-Ayupov** [comment]
Hello @tahirjaved1,  We would not like to install the tool due to small installation time and maintenance concerns. Please, install it in runtime by adding an additional step in your pipeline. I am closing this issue, but if you have any other questions feel free to ask.
