### ISSUE TITLE
Ubuntu 22.04 image fails at git.sh installation script

### ISSUE THREAD

**Issue by Vinayak014** [actions/runner-images#7518]
### Description

Building a linux image using AzureDevOps Packer build task results in an error at git.sh script installation. It fails at the ssh-keyscan step without any proper error message since 28th April . The message we see is below:

"Provisioning step had errors: Running the cleanup provisioner, if present"

We overrode the git.sh file to add some logging as below and we don't see any detailed logs
ssh-keyscan -vvv -t rsa,ecdsa,ed25519 github.com >> /etc/ssh/ssh_known_hosts

logs:

debug2: fd 3 setting O_NONBLOCK
debug3: conalloc: oname github.com kt 2
debug2: fd 4 setting O_NONBLOCK
debug3: conalloc: oname github.com kt 4
debug2: fd 5 setting O_NONBLOCK
debug3: conalloc: oname github.com kt 8
Provisioning step had errors: Running the cleanup provisioner, if present

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu22/20230426

### Is it regression?

ubuntu22/20230317

### Expected behavior

Packer build task should execute successfully

### Actual behavior

Packer build task fails on git.sh installation script

### Repro steps

1. Azure DevOps
2. Pipeline with Packer build task

**Comment by mortenlerudjordet** [comment]
We are also seeing the same problem, have run the pipeline multiple times to verify it's failing in the same place.

**Comment by Alexey-Ayupov** [comment]
Hello @mortenlerudjordet , @Vinayak014 , we do not observe this issue in our Azure pipelines https://github.visualstudio.com/runner-images/_build/results?buildId=131952&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24.
Please check your configs one more time, and make sure you are using the updated master branch.
We are going to close this issue. If you have any questions feel free to reach us.

**Comment by Vinayak014** [comment]
I fixed my problem by reverting this commit - bea98d07491839b4ab1963e6a0341e8cab07ae16 which is related to install.sh.

**Comment by mortenlerudjordet** [comment]
Can confirm that after allowing outbound on 22 for github.com and ssh.dev.azure.com for the packer build VM the pipeline no longer fails on ssh-keyscan part.

**Comment by rdvansloten** [comment]
Also ran into this issue. Checking if opening port 22 fixes this issue. If it does, consider adding more verbosity. Right now, the pipeline just dies after downloading. It downloads, does not throw any warning or error, then continues onto the VM breakdown.
