### ISSUE TITLE
"Canceled by the server"

### ISSUE THREAD

**Issue by nowadashi** [actions/runner-images#7525]
### Description

I'm running the code in Github Actions, with the Windows-latest image and also Windows-2019, but it keeps getting the "Canceled by the server" error. I DON'T HAVE TO RULE THE CODE, MY CODE HAS TO RUN AT LEAST 5 HOURS, BUT IN 10 MINUTES IT IS OFF AND ERROR, SOLVE THIS

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I deleted it but I have screenshots:
![Screenshot_20230503-185055](https://user-images.githubusercontent.com/132260359/235908107-e6f1155e-a1b0-4a65-b358-b1a9b351056e.jpg)

### Is it regression?

0

### Expected behavior

0

### Actual behavior

0

### Repro steps

0

**Comment by nowadashi** [comment]
> Hello @nowadashi, could you please provide a link to the failed run? It could be because of the high CPU load on the runner, we would like to check this. Moreover, without repro steps, we cannot do much, so please provide minimal repro steps too.

My yml file is as follows, I'm just trying to test Linux in Windows, but it turns off all of a sudden:

name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: steps 1
      shell: powershell
      run: |
           wsl --install
           wsl --update
           choco install wsl-ubuntu-2004
           ubuntu.exe
           wsl

**Comment by nowadashi** [comment]
> Hello @nowadashi, could you please provide a link to the failed run? It could be because of the high CPU load on the runner, we would like to check this. Moreover, without repro steps, we cannot do much, so please provide minimal repro steps too.

The second time I got it was when I ran a dockerfile windows server on images windows-2019, it suddenly shut down

**Comment by Alexey-Ayupov** [comment]
The provided code throws an error, however completely another.

If you want to try WSL, please use windows-2022 runner and the next code snippet
```
       shell: pwsh
        run: |
           $wslupd = wsl --update --web-download | Out-String
            $wslupd
            if ($wslupd) {
              wsl --version
              wsl --set-default-version 1
              wsl --install --distribution Ubuntu-20.04 --web-download
            }
```
The windows-2019 runner is too old and WSL there cannot be updated with the command "wsl --update", so please avoid using it.
As for your second time also please try to use the latest windows runner.

I will close this issue so far. If you have other questions feel free to reach us again.
