### ISSUE TITLE
CMake missing from windows-2022 version 20230502.2

### ISSUE THREAD

**Issue by langmm** [actions/runner-images#7533]
### Description

After my job updated to using the  20230502.2 version of the windows-2022 images (previously 20230425.1), it appears that cmake is not longer available. I assume this is a bug as cmake is listed as included in the [tools list](https://github.com/actions/runner-images/blob/win22/20230502.2/images/win/Windows2022-Readme.md) for this version, but maybe this was intentional and just not documented?

[Failing Job with version 20230502.2 without cmake](https://github.com/astro-friedel/yggcpp/actions/runs/4884739588/jobs/8717881346)
[Previous Job with version 20230425.1 with cmake
](https://github.com/astro-friedel/yggcpp/actions/runs/4878170055/jobs/8703564189)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230502.2 https://github.com/astro-friedel/yggcpp/actions/runs/4884739588/jobs/8717881346

### Is it regression?

20230425.1 https://github.com/astro-friedel/yggcpp/actions/runs/4878170055/jobs/8703564189

### Expected behavior

cmake is available

### Actual behavior

cmake is not available

### Repro steps

Run cmake from a job step (powershell)

**Comment by mikhailkoliada** [comment]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/88318005/236390724-672c61ae-9af6-451c-97bd-d8c6a5697328.png">

Hello! It looks like you mismosify your PATH variable somehow, make is in place
