### ISSUE TITLE
GenerateResourcesandImage failing with parsing JSON file for Linux and windows builds

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#7534]
### Description

Running the generate script with tags for linux and windows build fails with the following error :

Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character 'ÿ' looking for beginning of value
At line 1, column 1 (offset 1):
    1: �
      ^

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character 'ÿ' looking for beginning of value
At line 1, column 1 (offset 1):
    1: �
      ^

### Is it regression?

NO

### Expected behavior

Build to proceed

### Actual behavior

Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character 'ÿ' looking for beginning of value
At line 1, column 1 (offset 1):
    1: �
      ^

### Repro steps

run the generate script with -tags parameter

**Comment by vamshisiram** [comment]
@vpolikarpov-akvelon  can you pls help with this? It appears you resolved it in https://github.com/actions/runner-images/issues/6946 but it is back again :-(

**Comment by vpolikarpov-akvelon** [comment]
Hi @vamshisiram. Could you provide the whole command you are trying to run so we can test it?

**Comment by vamshisiram** [comment]
Here is the command

GenerateResourcesAndImage -SubscriptionId {MySubscriptionId} -ResourceGroupName "myTestResourceGroup" -ImageGenerationRepositoryRoot "C:\runner-images-main" ImageType Ubuntu2004 -AzureLocation "centralus" -tags @{id="126759764897437896gjfy87";environment="prod"}

Repeat for windows os, just change the images type.

Result is same for both Linux and windows.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vpolikarpov-akvelon** [comment]
Hey @vamshisiram. The issue should be fixed now. Could you please sync your local main branch and try again?

**Comment by vamshisiram** [comment]
Thanks, I will give it a try.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
