### ISSUE TITLE
macOS Images Should Add xcodes

### ISSUE THREAD

**Issue by jshier** [actions/runner-images#7535]
### Tool name

xcodes

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Approximate size

5.3 MB

### Brief description of tool

The Fastlane tool has deprecated the previous `xcode-install`-based action with one using the `xcodes` tool, so the base macOS images should include the `xcodes` CLI tool (`brew install --formula xcodes`) to enable the non-deprecated functionality without users having to manually install it in every build job.

### URL for tool's homepage

https://github.com/XcodesOrg/xcodes

### Provide a basic test case to validate the tool's functionality.

```bash
xcodes list
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
Hello @jshier, we are aware of the deprecated Xcode-install however, we are still using it. In general, we do not plan to add new software to the images, but plans can be changed.
If you have any other questions feel free to reach us again.
