### ISSUE TITLE
Az PowerShell module path

### ISSUE THREAD

**Issue by StijnDevogel** [actions/runner-images#7540]
### Description

Based on previous closed PR #7370 

Powershell module `az 9.3.0` is installed as part of the default image, but the specified [install path](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/Install-AzureModules.ps1#L8) `/usr/share/` is not part of `$env:PSModulePath`.

This leads to installing the module again under `Directory: /usr/local/share/powershell/Modules` by the users themselves as an additional step in their workflows

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.304.0

### Is it regression?

unknown

### Expected behavior

The cmdlets that come with the az powershell module should be loaded into the pwsh shell and not be installed again by the user that creates the workflow. As the powershel module is part of the image toolset:

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#powershell-modules
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#powershell-modules

### Actual behavior

az 9.3.0 is installed under `/usr/share` and because of the install path, the cmdlets are not loaded within the shell as the path is not part of` $env:PSModulePath`

The issue/bug can be fixed by adding the install path to `$env:PSModulePath` -> `$env:PSModulePath += ':/usr/share'` within the pwsh shell.

### Repro steps

1. login to azure with login/azure with enable-AzPSSession: true 
2. have a run step within the pwsh shell and run `Get-AzContext`. This will throw an error that the cmdlet could not be found

**Comment by sergei-pyshnoi** [comment]
Hello @StijnDevogel . Thank you for report. I am closing this issue as clone of https://github.com/actions/runner-images/issues/7370 . You can use suggested solution in runtime .

**Comment by StijnDevogel** [comment]
@sergei-pyshnoi I do not agree that you define it as a clone.
The previous issue mentioned the Azure DevOps running platform. 
So it's an issue that exist on both platforms. my solution is a quick fix, but it doesn't solve the overal problem itself.
I needed to look into the code to find where the az modules where installed. I don't think a lot of people do this. especially if the readme mentions this as an available toolset for powershell

Fixing the issue would be adding a step in packer template to start pwsh and add the `/usr/share` path to the $env:PSModulePath.
Or explain the rationale why the azure modules are installed in the image under `/usr/share` instead of one of the default paths for linux, namely `/root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules`

**Comment by sergei-pyshnoi** [comment]
Azure DevOps and Github Action uses the same images.  We can not install the modules different way because we may install lots of Az versions in parallel and they and their dependencies conflict between each other. You can select version of AZ using [Azure PowerShell Action](https://github.com/marketplace/actions/azure-powershell-action) and if it cached version, It will be used without downloading.
