### ISSUE TITLE
Add qemu-kvm to Ubuntu runners

### ISSUE THREAD

**Issue by pchaigno** [actions/runner-images#7541]
### Tool name

qemu-kvm

### Tool license

GPL v2

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Whatever is latest on Ubuntu repositories

### Approximate size

Approximate download size on a 22.04 Ubuntu is 140MB.

### Brief description of tool

QEMU allows us to boot any kernel we want to test (including custom builds) in our GitHub Action runners thanks to nested virtualization.

Installation time is short, but the need to download the packages for every test run tends to increase flakiness due to short connectivity blips.

### URL for tool's homepage

https://www.qemu.org/

### Provide a basic test case to validate the tool's functionality.

```bash
qemu-system-x86_64 --help
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt-get install -y qemu-kvm
```

### Tool installation time in runtime

Approximately 30 seconds in our CI

### Are you willing to submit a PR?

Of course!

**Comment by rinquan861** [comment]
I want it too, it can run android adb, github never generates android images :(

**Comment by sergei-pyshnoi** [comment]
Hello @pchaigno . We will take a look.

**Comment by mikhailkoliada** [comment]
Hello, given that we do not load kvm modules during runners preparation and do not see high demand to do so we would not like to provide an emu package by default as well. Please continue installing in runtime.
