### ISSUE TITLE
macos-13 build fails: "mkdir: /usr/local/miniconda: Permission denied"

### ISSUE THREAD

**Issue by bhaller** [actions/runner-images#7543]
### Description

Hi.  My project's build failed on macos-13 (but worked on macos-12), as you can see here:

https://github.com/MesserLab/SLiM/actions/runs/4903142813/jobs/8755411853

I may well be doing something foolish.  The error message is:

mkdir: /usr/local/miniconda: Permission denied

I believe that comes from this, in the YAML config:

      - name: Fix OSX Cache Restore
        if: steps.cache.outputs.cache-hit == 'true' && startsWith(matrix.os, 'macos')
        run: |
          mkdir -p /usr/local/miniconda/envs
          sudo cp -r ~/osx-conda /usr/local/miniconda/envs/anaconda-client-env

This was added to the YAML file by @petrelharp, who knows what it does and may have insight here.  However, I wanted to start out by just asking you folks at GitHub: has write permission for that directory changed, and if so, is there a recommended alternative location?  Or do you have any idea why this operation would be failing?  Thanks!

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I can't find "Set up job" so I'm not sure how to find the runner image version; perhaps the instructions above need updating/clarification?

Link to the failed build:

https://github.com/MesserLab/SLiM/actions/runs/4903142813/jobs/8755411853

### Is it regression?

I don't know how to determine this, but it works for macos-12

### Expected behavior

Build succeeds, as it does on macos-12

### Actual behavior

Error: "mkdir: /usr/local/miniconda: Permission denied"

### Repro steps

Happens when building my project under GitHub Actions with my YAML script; not sure what else to say here.

**Comment by wojsmol** [comment]
@bhaller Set up job is first step of a run. For the failing run you posted above Image version is `20230426.3`.

**Comment by bhaller** [comment]
> @bhaller Set up job is first step of a run. For the failing run you posted above Image version is `20230426.3`.

I see, thank you.

**Comment by sergei-pyshnoi** [comment]
Hello @bhaller . We will take a look.

**Comment by sergei-pyshnoi** [comment]
@bhaller Did you try run `mkdir -p /usr/local/miniconda/envs` with sudo ?

**Comment by bhaller** [comment]
> @bhaller Did you try run `mkdir -p /usr/local/miniconda/envs` with sudo ?

I will try that today and report back, if that is what you folks recommend.  :->

**Comment by bhaller** [comment]
Hmm, well, with `sudo` the `mkdir` step succeeds, but it fails at a later point.  Here's the new run:

https://github.com/MesserLab/SLiM/actions/runs/4916659490/jobs/8780711991

And here's the new error:

`/Users/runner/.profile: line 22: conda: command not found`

This is puzzling, since the "cache conda and dependencies" step said:

```
Cache restored successfully
Cache restored from key: macOS-3.9-conda-v13-87630525833a2da8558b1733f729a2e3420203b00272c3ea34edd1224e4332c3-9eb7f216bfb731e612b73962aea43070e1b545554396de60ecd44e1ca8d77f3e
```

I don't understand this conda caching stuff; as I wrote before, @petrelharp added this to the YAML file.  If you folks have any idea what's going on, help would be greatly appreciated.  I'm not sure whose bug this is (yours or ours, or maybe some third party's!), but since it works on macos-11 and macos-12, I have no idea why it wouldn't work on macos-13.  Thanks!

**Comment by sergei-pyshnoi** [comment]
We do not install miniconda on macos-13 images for now, I think this can be main problem.
Full list of installed software can be found in [README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md)
Please remember macOS 13 is still in beta version.
I am closing this issue for now, but if you have additional questions feel free to ask.

**Comment by bhaller** [comment]
> We do not install miniconda on macos-13 images for now, I think this can be main problem.
> Full list of installed software can be found in [README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md)
> Please remember macOS 13 is still in beta version.
> I am closing this issue for now, but if you have additional questions feel free to ask.

Hi @sergei-pyshnoi, thanks.  Yes, that seems like the root problem, then.  Do you know whether miniconda is planned to be added for macos-13?  (I'd like to put in a vote for it, certainly!  :->)  And is there a schedule for releasing macos-13 (i.e., not beta)?  If it's going to be reasonably soon, and will contain miniconda, then I guess I'll just twiddle my thumbs a bit and ignore these CI failures in the interim.  :->
