### ISSUE TITLE
Ubuntu-20.04 cgroup issue since ubuntu20/20230426.1

### ISSUE THREAD

**Issue by artsiom-abakumov** [actions/runner-images#7573]
### Description

We are running kind cluster in github runners to test various deployments before going to the CSP kubernetes deployment.
After release of ubuntu-20.04 images 20230426.1, our pipelines started to fail due to kyverno pods not able to start (log below). Investigation showed that ubuntu-22.04 images is working fine. However we are linked to the ubuntu-20.04 due to org structure.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230426.1
Version: 20230507.1

### Is it regression?

https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230417.1

### Expected behavior

kyverno pods in kind cluster are up and running; hosted inside github actions pipeline using ubuntu-20.04 image

### Actual behavior

Getting following error in kyverno pods logs:
```
I0511 12:06:06.154131       1 maxprocs.go:12] setup/maxprocs "msg"="setup maxprocs..." 
E0511 12:06:06.154804       1 error.go:19] setup/maxprocs "msg"="failed to configure maxprocs" "error"="path \"/actions_job/aac3f1ad53ddd36ad0adea587d87e1a86f638526722bd448aea44bcfb50c0266\" is not a descendant of mount point root \"/actions_job/aac3f1ad53ddd36ad0adea587d87e1a86f638526722bd448aea44bcfb50c0266/kubelet\" and cannot be exposed from \"/sys/fs/cgroup/misc/kubelet\"" 
```

### Repro steps

.github/workflows/
```
jobs:
  test-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          kind create cluster
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno --namespace kyverno kyverno/kyverno --create-namespace --wait
```

**Comment by sergei-pyshnoi** [comment]
@artsiom-abakumov Can you please confirm that problem still exist on images with version [20230507.1](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230507.1) ? Also can you provide link to a failed build?

**Comment by artsiom-abakumov** [comment]
@sergei-pyshnoi 
Yes, its reproducible with the latest image version.
I've created public repo to show this:
https://github.com/artsiom-abakumov/artsiom-test/actions

**Comment by sergei-pyshnoi** [comment]
Hi @artsiom-abakumov . The main reason for the error is that ubuntu 20.04 uses `cgroup v1` . Apparently, kyverno requires `cgroup v2` (test directly on VM confirm it). Switching version of cgroup requires restarting OS, so it can`t be done in runtime during workflow.  Also we have no plans to change `cgroup` version for ubuntu 20.04 maintenance concerns.

**Comment by artsiom-abakumov** [comment]
@sergei-pyshnoi Thanks for the information. Last thing which worries me - do you have idea why it stopped working and was working before? We will think about switching to ubuntu22 but such insights could help us to avoid issue and blockers in future. From our side kyverno version was not changed from March and stopped working after [release](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230426.1) which seems have changed only minor versions of docker server and kernel...

**Comment by sergei-pyshnoi** [comment]
> @sergei-pyshnoi Thanks for the information. Last thing which worries me - do you have idea why it stopped working and was working before? We will think about switching to ubuntu22 but such insights could help us to avoid issue and blockers in future. From our side kyverno version was not changed from March and stopped working after [release](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230426.1) which seems have changed only minor versions of docker server and kernel...

We`ll try to investigate this. I  am closing this issue for now, but if you have additional questions feel free to ask.

**Comment by vpolikarpov-akvelon** [comment]
Hey @artsiom-abakumov. We released some tweaks recently. Could you check your workflow again?

**Comment by artsiom-abakumov** [comment]
> Hey @artsiom-abakumov. We released some tweaks recently. Could you check your workflow again?

Workflow job is passing now on ubuntu-20.04 runner! Thanks.
