### ISSUE TITLE
MacOS-11/12/13 images all fail to build lastest macos workload

### ISSUE THREAD

**Issue by gghart** [actions/runner-images#7577]
### Description

The recent update to the dotnet macos workload broke our pipeline on all of the available MacOS images.

We have a powershell script to pull in the macos workload:
```
Write-Host "Running: dotnet workload install macos"
Start-Process dotnet -ArgumentList "workload install macos" -NoNewWindow -Wait
```

Which previously imported
Microsoft.macOS.Sdk version 13.1.2054

I guess that got updated, and now it pulls down
Installing pack Microsoft.macOS.Sdk version 13.3.7054...

Now when we run the dotnet publish, we get this error.
ILLINK : warning MM0079: The recommended Xcode version for Microsoft.macOS 13.3.7054 is Xcode 14.3 or later. The current Xcode version (found in /Applications/Xcode_13.2.1.app/Contents/Developer) is 13.2.1. [/Users/runner/work/1/s/Mac-LogAnalyzerApp/Mac-LogAnalyzerApp.csproj]

Now this makes sense, because the MacOS images only have XCode 14.2 installed - 14.3 on MacOS-13, but the default is still 14.2, so that also fails out-of-the box

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

MacOS-12:
Current image version: '20230505.1'

MacOS-13:
Current image version: '20230509.4'

### Is it regression?

No

### Expected behavior

Images should be able to compile latest publicly released software libraries

### Actual behavior

Working pipeline fails once new macos workload was released

### Repro steps

```
dotnet workload install macos
dotnet publish
```

For any project using that workload

**Comment by sergei-pyshnoi** [comment]
Hello @gghart . We will take a look.

**Comment by mattjohnsonpint** [comment]
@gghart - this is because Microsoft added support for Xcode 14.3 to the latest workloads.  In doing so, they made Xcode 14.3 _required_.  Unfortunately, Xcode 14.3 only works on macOS 13.  Thus, they _should_ be working on the `macos-13` Github Actions runner image (currently in beta), but not anything lower.  

For the `macos-12` image, see my workaround at https://github.com/xamarin/xamarin-macios/issues/17561#issuecomment-1542559109

For `microsoft.net.sdk.macos`, I believe the latest Xcode 14.2 compatible workload version is `13.1.2054/7.0.100`.

**Comment by mikhailkoliada** [comment]
@gghart what @mattjohnsonpint suggested is right. If you need to specify an Xcode version other that the default one you can use the setup-code task https://github.com/maxim-lobanov/setup-xcode. If you have other questions feel free to reach us again and reopen the ticket! :)

**Comment by gghart** [comment]
Hi,

Thanks for clarifications - agreed, and if I force the XCode version it does build on MacOS-13 agent.

MacOS-13 is currently in public beta, right? Given this, doesn't it make sense to change the default XCode from 14.2 to 14.3 so going forward this will just "work" for people using the MacOS packages and not require people to Google how to change the default XCode?

Geoff
