### ISSUE TITLE
macOS-10.15 is still in the infrasturtur in some way / workflow hangs with: Waiting for a runner to pick up this job... 

### ISSUE THREAD

**Issue by berlin4apk** [actions/runner-images#7579]
### Description

https://github.com/actions/runner-images/pull/7078

failed workflow run: https://github.com/berlin4apk/ccache-action/actions/runs/4950864318/jobs/8855059719
 latest successful workflow run: https://github.com/berlin4apk/ccache-action/actions/runs/4808602758/jobs/8558802550

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

##[debug]Starting: Set up job
Current runner version: '2.303.0'
Operating System
  Mac OS X
  10.15.7
  19H2026
Runner Image
  Image: macos-10.15
  Version: 20221018.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-10.15/20221018.1/images/macos/macos-10.15-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-10.15%2F20221018.1
Runner Image Provisioner 2.0.159.1

### Is it regression?

https://github.com/berlin4apk/ccache-action/actions/runs/4808602758/jobs/8558802550

### Expected behavior

skipped the job with an error

### Actual behavior

hangs with:
Requested labels: macos-10.15
Job defined at: berlin4apk/ccache-action/.github/workflows/tests.yml@refs/heads/main
Waiting for a runner to pick up this job...

### Repro steps

run a job with Requested label: macos-10.15

**Comment by mikhailkoliada** [comment]
Hello! macOS-10.15 does not exist anymore as a hosted runner. What you see is the expected behaviour of the runner itself as it assumes that some self-hosted agent may come online later on using the same tags. If you have questions regarding this behaviour feel free to open an issue in the https://github.com/actions/runner repo. If you have more questions for us feel free to reach out again as well.
