### ISSUE TITLE
Unable to run `brew install android-platform-tools`

### ISSUE THREAD

**Issue by VincentMasselis** [actions/runner-images#7581]
### Description

Hey ! 👋

The current homebrew instance used into the latest macos runner contains a bug which block the installation of the formulae `android-platform-tools` from homebrew.

Homebrew already fixed the issue from his side here => https://github.com/orgs/Homebrew/discussions/4501 but the actual runner `macos-latest` doesn't use the fixed homebrew instance so my builds cannot succeed until the runner is updated.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/VincentMasselis/TPMS-advanced/actions/runs/4957595681/jobs/8869490137

### Is it regression?

https://github.com/VincentMasselis/TPMS-advanced/actions/runs/4917194908/jobs/8781980089

### Expected behavior

I except `brew install android-platform-tools` to succeed.

### Actual behavior

```
Downloading https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip
Error: SHA256 mismatch
Expected: ef3dd374ebd2dddf5d8ab6179feb8016462ad25473ccc44555a98fb37adc9d63
  Actual: 38e4abc642250e7090041e569d9de8d3f1dee2908fa30daf5ebe45a3089ec54b
    File: /Users/runner/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip
To retry an incomplete download, remove the file above.
Error: Process completed with exit code 1.
```

### Repro steps

* Create a runner which uses `macos-latest`
* Add a step which run bash scripts
* Add `brew install android-platform-tools` to the script

**Comment by mikhailkoliada** [comment]
Hello! it will be fixed only after new image rollout

**Comment by VincentMasselis** [comment]
For those who come here with the same issue, you have to put the instruction `brew update` before using `brew install` into your script to fix the error

**Comment by ilia-shipitsin** [comment]
@VincentMasselis , updated image should have been deployed, can you please check ?

**Comment by VincentMasselis** [comment]
I can confirm every works has expect now :) 

https://github.com/VincentMasselis/TPMS-advanced/actions/runs/5155470734/jobs/9285187505

Thanks a lot !
