### ISSUE TITLE
GenerateResourcesAndImage -RestrictToAgentIpAddress fails (regression)

### ISSUE THREAD

**Issue by geekzter** [actions/runner-images#7585]
### Description

Running `GenerateResourcesAndImage -RestrictToAgentIpAddress` ([full YAML](https://github.com/geekzter/azure-pipeline-agents/blob/master/pipelines/build-image-template.yml#L198)) fails with:
```
Error: Invalid number literal

  on <value for var.allowed_inbound_ip_addresses from arguments> line 1:
  (source code not available)

Failed to recognize the value of this number literal.
```

This looks like a quoting regression introduced in [this PR](https://github.com/actions/runner-images/commit/5777d37af1d4bb32f7dee1feb4669c278f39bb6c#). I tried to influence quoting with PSNativeCommandArgumentPassing, but that did not yield any difference.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

This is not image version dependent, but it does apply only to HCL packer templates

### Is it regression?

[this PR](https://github.com/actions/runner-images/commit/5777d37af1d4bb32f7dee1feb4669c278f39bb6c#)

### Expected behavior

For the image to build

### Actual behavior

```
Error: Invalid number literal

  on <value for var.allowed_inbound_ip_addresses from arguments> line 1:
  (source code not available)

Failed to recognize the value of this number literal.
```

### Repro steps

Run `GenerateResourcesAndImage -RestrictToAgentIpAddress`

**Comment by shamil-mubarakshin** [comment]
Hello @geekzter, we will have a look

**Comment by shamil-mubarakshin** [comment]
@geekzter, I have run some tests.
Issue is related to PowerShell embedded quote handling when used as arguments to external programs. Prior to pwsh 7.3, quotes needed to be escaped.
PSNativeCommandArgumentPassing did work for me, but since it is an experimental feature in pwsh 7.2, it needs to be in a separate step. While it might be a fix in this case, it might break something else:
```
- pwsh: |
    Enable-ExperimentalFeature -Name PSNativeCommandArgumentPassing
```
We are thinking of rolling back the changes and updating GenerateResourcesAndImage documentation with pwsh 7.3 cases.
Will get back with more info

**Comment by shamil-mubarakshin** [comment]
@geekzter, changes were reverted. Pipeline should run as it used to

**Comment by shamil-mubarakshin** [comment]
I will close this for now. Feel free to reach us in case of further issues

**Comment by geekzter** [comment]
Thanks @shamil-mubarakshin !
