### ISSUE TITLE
Error during provisioning for Ubuntu 22.04 on SoftwareReport.Generator.ps1

### ISSUE THREAD

**Issue by tarunfeb27** [actions/runner-images#7586]
### Description

I am trying to build the runner image for Ubuntu 22.04 and everything proceeds well for around ~1.5 hours until I get to the provisioning step where SoftwareReport.Generator.ps1 is executed. At this point, the packer build fails with the following error:

```
==> azure-arm.build_vhd: Provisioning with shell script: /agent/_work/1/s/runner-images/images/linux/scripts/base/apt-mock-remove.sh
==> azure-arm.build_vhd: Provisioning with shell script: /tmp/packer-shell1704030224
==> azure-arm.build_vhd:  ›   Warning: Our terms of service have changed:
==> azure-arm.build_vhd:  ›   https://dashboard.heroku.com/terms-of-service
==> azure-arm.build_vhd: Flag --short has been deprecated, and will be removed in the future.
==> azure-arm.build_vhd: info: This is the version for the rustup toolchain manager, not the rustc compiler.
==> azure-arm.build_vhd: info: The currently active `rustc` version is `rustc 1.69.0 (84c898d65 2023-04-16)`
==> azure-arm.build_vhd: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : You cannot call a method on a null-valued expression.
==> azure-arm.build_vhd: + CategoryInfo          : InvalidOperation: (:) [SoftwareReport.Generator.ps1], RuntimeException
==> azure-arm.build_vhd: + FullyQualifiedErrorId : InvokeMethodOnNull,SoftwareReport.Generator.ps1
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed
==> azure-arm.build_vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
```

No sure what is causing this , but last successful run I had was on 17th March ~ 13:00 CET.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I am building images an existing Azure DevOps pipeline which is using previously built images(SelfHosted) from same pipeline.

### Is it regression?

Not sure

### Expected behavior

Image build being successful

### Actual behavior

Build fails

### Repro steps

Clone the repo, run GenerateResourcesAndImage.ps1 with your env vars. 
```
Import-Module .\helpers\GenerateResourcesAndImage.ps1
GenerateResourcesAndImage -SubscriptionId $(SUBSCRIPTION_ID) -ResourceGroupName  ${{ parameters.imageAzureRmResourceGroupName }} -ImageGenerationRepositoryRoot "$pwd" -ImageType ${{ parameters.image_type }} -AzureLocation ${{ parameters.imageAzureRmLocation }} -AzureClientId $(CLIENT_ID) -AzureClientSecret $(CLIENT_SECRET) -AzureTenantId  $(TENANT_ID) -Force
```

**Comment by jpuckettgomeyra** [comment]
I'm having the same issue I believe it is because the SoftwareReport.Generator.ps1 script is referencing Python 2.7 which was removed in #7401.

**Comment by mikhailkoliada** [comment]
It is broken because of the docker cached images table, we will take a look

**Comment by Alexey-Ayupov** [comment]
Hello @tarunfeb27, we are working on it. Thank you.

**Comment by mikhailkoliada** [comment]
fixed

**Comment by mikhailkoliada** [comment]
please sync your main
