### ISSUE TITLE
Install swiftlint via homebrew

### ISSUE THREAD

**Issue by AllDmeat** [actions/runner-images#7588]
Runner images has `swiftlint` preinstalled already, but it's installed not via `homebrew`.
Why it was done this way is described here: https://github.com/actions/runner-images/pull/2296

Can we undo this change to support `swiftlint` installation via `homebrew`? Otherwise `brew bundle` fails to install `swiftlint` listed in `Brewfile` due to one already being preinstalled in a different way.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello! We do not have plans to migrate to home-brew from SwiftLint as it pulls unwanted dependencies time to time. if you want to change the installation method it can still be done in runtime.
