### ISSUE TITLE
`pipx` is missing on `macOS-13`

### ISSUE THREAD

**Issue by mayeut** [actions/runner-images#7590]
### Description

`pipx` is available on all images except for `macos-13`.
This tool is expected to always be available in some actions which fail to run on `macos-13`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: macos-13
  Version: 20230509.4
  Included Software: https://github.com/actions/runner-images/blob/macOS-13/20230509.4/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20230509.4
```
https://github.com/mayeut/nox/actions/runs/4972661637/jobs/8897999212

### Is it regression?

yes

### Expected behavior

`pipx` is available on `macos-13`

### Actual behavior

```
pipx: command not found
```

### Repro steps

pipx --version

**Comment by shamil-mubarakshin** [comment]
Hello @mayeut. 
Macos-13 is still in beta and Pipx is not a part the image yet. We will consider adding pipx.
For now, pipx can be installed in runtime using following step:
```
- name: Run a multi-line script
  run: |
    brew install pipx
    pipx ensurepath
```

**Comment by ilia-shipitsin** [comment]
@mayeut , pipx was added to image definition. hopefully in a week or two new image will be deployed

**Comment by ilia-shipitsin** [comment]
@mayeut , new image (with pipx in it) was deployed.
sorry for delay, we were sort of frozen by https://github.blog/2023-05-16-addressing-githubs-recent-availability-issues/

**Comment by emersonfoni** [comment]
@ilia-shipitsin was pipx intentionally left out of the `macos-13-xl` arm64 images?

I was hoping to get some arm64 wheels built, but my workflows failed. [setup-python](https://github.com/actions/setup-python) with Poetry caching requires Poetry to be installed. The [official documentation says to use pipx to install Poetry](https://github.com/actions/setup-python/blob/b64ffcaf5b410884ad320a9cfac8866006a109aa/docs/advanced-usage.md#caching-packages), but pipx is now missing. And the other methods to install Poetry require Python, which isn't installed by default. 

I've disabled caching for now, but it's unclear how this can work on these images.
