### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by nonesky666** [actions/runner-images#7605]
### Tool name

N

### Tool license

Mit

### Add or update?

- [X] Add
- [X] Update

### Desired version

Dev

### Brief description of tool

N.

### URL for tool's homepage

www.github.com/xstarint

### Provide a basic test case to validate the tool's functionality.

```bash
Run N Deploy
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by shamil-mubarakshin** [comment]
Hello @nonesky666.
Could you please provide more information about the tool?
