### ISSUE TITLE
API endpoint unavailable

### ISSUE THREAD

**Issue by Woblo1205** [actions/runner-images#7628]
### Description

In the table "Available Images" in the README.md file the column "Rollout Progress of Latest Image Release" contains links to [status20](https://actionvirtualenvironmentsstatus.azurewebsites.net/api/status?imageName=ubuntu20). However, this API endpoint seems to be offline. 

The response is: "Function host is not running."

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

not applicable

### Is it regression?

No

### Expected behavior

Return the latest image version e.g. 20230507.1

### Actual behavior

"Function host is not running."

### Repro steps

Step 1: go to https://actionvirtualenvironmentsstatus.azurewebsites.net/api/status?imageName=ubuntu20

**Comment by vpolikarpov-akvelon** [comment]
Hi, @Woblo1205. Thank you for reporting, we are working on this.

**Comment by mikhailkoliada** [comment]
Should be fixed in readme now
