### ISSUE TITLE
Missing pkg-config  on macos-13 image

### ISSUE THREAD

**Issue by dalcinl** [actions/runner-images#7632]
### Description

`pkg-config` command fails on the `macos-13` image with command not found.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230509.4
Build link: https://github.com/dalcinl/test-gh-actions/actions/runs/5070204041

### Is it regression?

Yes  (if compared to the other macOS images)

### Expected behavior

`pkg-config` should be available, executing `pkg-config --version` should succeed.

### Actual behavior

`pkg-config` is not available, executing `pkg-config --version` fails.

### Repro steps

```sh
pkg-config --version
```

**Comment by vpolikarpov-akvelon** [comment]
Hi, @dalcinl. MacOS 13 runners are in beta now and provide reduced set of tools out of the box. You can install pkg-config manually using `brew` utility.

**Comment by dalcinl** [comment]
In understand the macos-13 images are in beta, and of course I can `brew install` any missing bits. I submitted this issue just to raise awareness that the `pkg-config` tool (that many other packages/buildsystems may use for configure/build steps) is not present in macos-13, while it was present in the two previous macos images, as well as the linux images. If this omission is on purpose and not just an oversight, feel free to close this issue. IMHO, `pkg-config` is important enough to be included by default, and the fact that all previous macOS and Linux images had it support my claim.

**Comment by vpolikarpov-akvelon** [comment]
Thank you for your concern. We don't install all of the software on macOS 13 runners to ease debugging and testing while runners are in beta. Though we are working on adding tools there.

The complete lists of tools and utilities that is installed on runner of each type are located here: https://github.com/actions/runner-images/tree/main/images/macos/toolsets. Feel free to investigate and compare these lists.

I'm going to leave this issue opened until `pkg-config` is available on runner so you and others get notified when the tool is available.

**Comment by ilia-shipitsin** [comment]
approximately in 1-2 weeks new image will be deployed

**Comment by mikhailkoliada** [comment]
Closing now as we do not track public beta deployments weekly, png-config should be indeed available in 1-2 weeks as @ilia-shipitsin mentioned

**Comment by reedloden** [comment]
> Closing now as we do not track public beta deployments weekly, png-config should be indeed available in 1-2 weeks as @ilia-shipitsin mentioned

It's been over 2 weeks, and there hasn't been a new macOS-13 image released with this change yet. When is that expected? Thanks!
