### ISSUE TITLE
github action job failed when compile application for linux platform

### ISSUE THREAD

**Issue by Droid-MAX** [actions/runner-images#7637]
### Description

![image](https://github.com/actions/runner-images/assets/12762435/c8566bdc-561b-4a17-99f2-9dd4bc073381)

The OS image used by the failed compilation jobs is "ubuntu-latest"

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

        # a list of all the targets
        include:
          - TARGET: i686-unknown-linux-musl # test in an alpine container on a mac
            OS: ubuntu-latest
          - TARGET: x86_64-unknown-linux-gnu # tested in a debian container on a mac
            OS: ubuntu-latest
          - TARGET: x86_64-unknown-linux-musl # test in an alpine container on a mac
            OS: ubuntu-latest
          - TARGET: aarch64-unknown-linux-gnu # tested on aws t4g.nano
            OS: ubuntu-latest
          - TARGET: aarch64-unknown-linux-musl # tested on aws t4g.nano in alpine container
            OS: ubuntu-latest
          - TARGET: armv7-unknown-linux-gnueabihf # raspberry pi 2-3-4, not tested
            OS: ubuntu-latest
          - TARGET: armv7-unknown-linux-musleabihf # raspberry pi 2-3-4, not tested
            OS: ubuntu-latest
          - TARGET: arm-unknown-linux-gnueabihf # raspberry pi 0-1, not tested
            OS: ubuntu-latest
          - TARGET: arm-unknown-linux-musleabihf # raspberry pi 0-1, not tested
            OS: ubuntu-latest
          - TARGET: x86_64-apple-darwin # tested on a mac, is not properly signed so there are security warnings
            OS: macos-latest
          - TARGET: i686-pc-windows-msvc # tested on a windows machine
            OS: windows-latest
          - TARGET: x86_64-pc-windows-msvc # tested on a windows machine
            OS: windows-latest

### Is it regression?

no

### Expected behavior

The expectation should be that all compilations pass correctly

### Actual behavior

Only when using the ubuntu-latest system image, an error occurred when updating the software source, causing job failure

### Repro steps

Define an action, OS uses ubuntu-latest, to execute the update software source command

**Comment by ilia-shipitsin** [comment]
Hello, @Droid-MAX , please consider adding `apt-get update`

**Comment by Droid-MAX** [comment]
Why hasn't this happened for such a long time?

**Comment by ilia-shipitsin** [comment]
it is how ubuntu repo design works. nothing we can do on github side

**Comment by ilia-shipitsin** [comment]
there's good explanation how ubuntu packaging works https://askubuntu.com/questions/337198/is-sudo-apt-get-update-mandatory-before-every-package-installation

**Comment by Droid-MAX** [comment]
thx, issues solved.
