### ISSUE TITLE
create actions that target the new m1 runner

### ISSUE THREAD

**Issue by ashok-arora** [actions/runner-images#7638]
### Description

I tried to use the runs-on: tag with the macos-13 but it still provisions x86_64 machines and not arm64, the exact discussion is going on [here](https://github.com/deepmind/lab2d/issues/25?notification_referrer_id=NT_kwDOASl98rM2MjM0Mzg2MjE0OjE5NDk2NDM0#issuecomment-1557201897) and [here](https://github.com/deepmind/lab2d/pull/26?notification_referrer_id=NT_kwDOASl98rM2MzQzNDAxMDg5OjE5NDk2NDM0#issuecomment-1558948858). Can somebody look into it and suggest if I'm doing something wrong?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

NA

### Is it regression?

NA

### Expected behavior

`arm64` images should be accessible. 

### Actual behavior

only `x86` images available.

### Repro steps

NA

**Comment by mikhailkoliada** [comment]
Hello! Please follow https://github.com/actions/runner-images/issues/2187

**Comment by ashok-arora** [comment]
@mikhailkoliada I am aware that m1 ARM machines is in public beta, my question is how do I access them? #2187 does not help at all.

**Comment by ashok-arora** [comment]
@mikhailkoliada what's the reason for closing the issue?

**Comment by mikhailkoliada** [comment]
@ashok-arora we do not provide m1 machines yet. You can track the progress in the ticket mentioned above + https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by ashok-arora** [comment]
@mikhailkoliada its mentioned here: https://github.com/github/roadmap/issues/528 that m1 machines are in public beta.
