### ISSUE TITLE
Cannot download version libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb of libssl

### ISSUE THREAD

**Issue by lukerogers** [actions/runner-images#7654]
### Description

This is related to #7105. It looks like a new version (libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb) was released 5/30/2023 and the older version was removed.

This is a quick fix to https://github.com/actions/runner-images/blob/035dc70f77d4353de9fbacd66be4f0797d4d9f62/images/linux/scripts/installers/sqlpackage.sh and I can certainly create the PR if it would help.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I'm running my own

### Is it regression?

No

### Expected behavior

Expect the installation of sqlpackage.

### Actual behavior

Fails to download:

    azure-arm.build_vhd: Downloading 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' to '/tmp/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb'...
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 19 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 18 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 17 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 16 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 15 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 14 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 13 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 12 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 11 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 10 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 9 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 8 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 7 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 6 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 5 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 4 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 3 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 2 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 1 attempts left
    azure-arm.build_vhd: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 0 attempts left

### Repro steps

Run build for Ubuntu 22.04.

**Comment by sergei-pyshnoi** [comment]
Hello @lukerogers . Thanks for your report, we will take a look.

**Comment by mikhailkoliada** [comment]
Should be fixed in main, please sync your local copy.
