### ISSUE TITLE
Actions runner image scheduled maintenance (June 2 2023 through June 16 2023)

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#7660]
### Breaking changes

Customers may see differences in the software versions installed in their runners between runs of the same workflow or pipeline.

### Target date

Images will be up to date and consistent by June 16th 2023.

### The motivation for the changes

The GitHub Runner Images team is extending the rollout  of new image versions to provide a more predictable environment.

### Possible impact

During this period you may see different runner image versions reported in your workflow runs or pipeline jobs. Versions may differ between runs or multiple attempts of the same run.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

No steps should be taken.

**Comment by codeArtisanry** [comment]
Hey there, 
I guess I'm getting affected 
Here is the detailed version of details you can see
https://github.com/actions/runner-images/issues/7659

I tried every Ubuntu image (22,20,18,lts) every time I'm getting the same error even in self hosted runner
Could you please able to give me any other Images for the workout ??

Any help is much appreciated... 
Thanks

**Comment by mikhailkoliada** [comment]
It was decided to prolong the maintenance period up until June 16th to provide better experience in the future.

**Comment by renemadsen** [comment]
> It was decided to prolong the maintenance period up until June 16th to provide better experience in the future.

@mikhailkoliada when will we be seeing the new ubuntu 22.04 images in our action runs? Right now it's the former version. Just to know how long we have to wait?

What does this maintenance period do in exact terms of experience?

**Comment by modosc** [comment]
we started seeing job failures today. our jobs all use:
```
    runs-on: ubuntu-latest
```
we're seeing random failures with this message:
<img width="603" alt="image" src="https://github.com/actions/runner-images/assets/2231664/ec685c28-6e67-4694-90ac-e8f85c4b26c5">

is this related to the rollout?

**Comment by lp-disco** [comment]
+1 I am seeing similar issues using `ubuntu-20.04` despite some jobs using that same runner passing

**Comment by OPattinson** [comment]
In the latest 22.04 image version (20230611.1) that has been rolled out, we are now experiencing ModuleNotFound errors when trying to import certain packages in Python3.8, even though the logs show that package has been downloaded and installed via Pip (specifically, the package `dunamai-1.17.0`, using latest version of pip). 

The previous image version that we had running worked fine (20230517.1), so I'm assuming this is a result of the runner update?

**Comment by nikhaxuall** [comment]
^ I am seeing the same issue with ModuleNotFound errors in python3.8.  Jobs that ran fine yesterday on ubuntu-20.04:20230517.1 fail when rerun today on 20230611.1

**Comment by vpolikarpov-akvelon** [comment]
@OPattinson, @nikhaxuall, current update rollouts for Ubuntu 20.04 and Ubuntu 22.04 runners have been completed:
- https://github.com/actions/runner-images/pull/7702
- https://github.com/actions/runner-images/pull/7701

If you see any problems that may be caused by this update please create a separate issue and provide more details (logs, workflow run links, repro steps, etc).

**Comment by mariokoehler** [comment]
with the new ubuntu image we see problems running our Arquillian Junit tests. the maven surefire plugin indicates that it has run the tests, but the actual test is not really executed (debug logs normally written by the test show up nowhere, and files that should have been created by the tests are missing, thats why we are certain the test hasn't actually run). we hand random individual builds that still pulled the old image and they were fine, but whenever the new image gets pulled this behavior appears.

**Comment by mikhailkoliada** [comment]
It has ended, runners should receive a standard updates cycle!
