### ISSUE TITLE
MSVC tools + Bazelisk broken in 20230517.1

### ISSUE THREAD

**Issue by mkruskal-google** [actions/runner-images#7662]
### Description

We use [msvc-dev-cmd](https://github.com/ilammy/msvc-dev-cmd) to setup the MSVC build environment before running Bazel builds, and this has worked well on windows-2019 and windows-2022 runners for months.  Since the 20230517.1 update, we've been seeing the following error from our windows-22 jobs:
```
  The target you are compiling requires Visual C++ build tools. 
  Bazel couldn't find a valid Visual C++ build tools installation on your machine. 
   
  Visual C++ build tools seems to be installed at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC 
  But Bazel can't find the following tools: 
      VCVARSALL.BAT, cl.exe, link.exe, lib.exe, ml64.exe 
  for x64 target architecture 
   
  Please check your installation following https://docs.bazel.build/versions/main/windows.html#using 
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230517.1
Included Software: https://github.com/actions/runner-images/blob/win22/20230517.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230517.1

https://github.com/protocolbuffers/protobuf/actions/runs/5157364030/jobs/9289681151

### Is it regression?

yes, this was working on 20230508.3 (https://github.com/protocolbuffers/protobuf/actions/runs/5148680966/jobs/9270810559)

### Expected behavior

Bazel should be able to find the MS build tools

### Actual behavior

Bazel is failing to find build tools and can't compile C++ code

### Repro steps

Run a bazel build over C++ code in windows-2022

**Comment by shamil-mubarakshin** [comment]
Hi @mkruskal-google,
We will investigate the issue and get back

**Comment by Chronostasys** [comment]
I've probably encountered the same issue. In my case, a cargo build script fail with 
```
  CMake Error at CMakeLists.txt:6 (project):
    The CMAKE_C_COMPILER:

      C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/HostX64/x64/cl.exe

    is not a full path to an existing compiler tool.
```
ever since the runner image version changed to 20230517.1.

Latest success workflow: https://github.com/Pivot-Studio/pivot-lang/actions/runs/5116915861/jobs/9199519978

Failed workflow: https://github.com/Pivot-Studio/pivot-lang/actions/runs/5177967705/jobs/9328773378

**Comment by laramiel** [comment]
FWIW, bazel uses this file to resolve VC location:

https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_configure.bzl

In summary, it looks for:

1. Environment variables: `BAZEL_VC`, `BAZEL_VS`

2. vswhere.exe under `Program Files (x86)\Microsoft Visual Studio\Installer`
  
3. VsDevCmd.bat using VS_VERSION variable:
 * `VS%VS_VERSION%COMNTOOLS/VsDevCmd.bat`
 * `VS90COMNTOOLS` ... `VS160COMNTOOLS` variables

4. Registry keys:

 * `HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\SxS\\VC7`
 * `HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\SxS\\VS7`

5. Common paths:

 * `Program Files (x86)\Microsoft Visual Studio\\2019\\Preview\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2019\\BuildTools\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2019\\Community\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2019\\Professional\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2019\\Enterprise\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2017\\BuildTools\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2017\\Community\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2017\\Professional\\VC`
 * `Program Files (x86)\Microsoft Visual Studio\\2017\\Enterprise\\VC`
 * `Program Files (x86)\Microsoft Visual Studio 14.0\\VC`

**Comment by shamil-mubarakshin** [comment]
I have tested setting BAZEL_VC and BAZEL_VC_FULL_VERSION on runtime, but same errors appeared.
`C:\Program Files\Microsoft Visual Studio\2022\Enterprise` is a default VS 2022 installation location on runners.
Possible error reason is mentioned in https://github.com/bazelbuild/bazel/issues/18592 issue, where [this _is_vs_2017_or_2019 function](https://github.com/bazelbuild/bazel/blob/030d94cf4cb23c3e4581141774a1b3d8cf828a85/tools/cpp/windows_cc_configure.bzl#L257-L267) not functioning correctly for VS 17.6.

**Comment by shamil-mubarakshin** [comment]
@Chronostasys,
V143 VC tools `14.34.31933` are replaced by `14.35.32215` and `14.36.32532` so I am not really sure why your workflow is trying to use old version. Maybe it is set or somehow cached.
You can also try installing `14.34.31933` tools in runtime using step:
```
      - name: install workloads
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToAdd = @(
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM64",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ARM64.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM64",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.ATL.ARM64.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM.Spectre",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM64",
              "Microsoft.VisualStudio.Component.VC.14.34.17.4.MFC.ARM64.Spectre"
          )
          [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0)
          {
              Write-Host "components have been successfully added"
          }
          else
          {
              Write-Host "components were not installed"
              exit 1
          }
```

**Comment by mkruskal-google** [comment]
I created a simpler reproduction step in https://github.com/protocolbuffers/protobuf/pull/13010 (see Bazel test <runner machine>).  Here I've removed all of our complex infrastructure and caching, and just simply invoke a bazelisk command.   I couldn't get any combination of BAZEL_VC_FULL_VERSION or BAZEL_VC to work on windows-2022, and as you can see all other runners handle this just fine

**Comment by shamil-mubarakshin** [comment]
@mkruskal-google, thanks for your input.
Bazel has a problem with [this _is_vs_2017_or_2019 function](https://github.com/bazelbuild/bazel/blob/030d94cf4cb23c3e4581141774a1b3d8cf828a85/tools/cpp/windows_cc_configure.bzl#L257-L267) not functioning correctly for VS 17.6.
I will close the issue for now. Feel free to reopen it in case of any
