### ISSUE TITLE
[All OSs] .NET 3.1 will be removed from the images on July, 3

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#7667]
### Breaking changes

All the pre-cached .NET 3.1 versions will be removed from all operating systems.

### Target date

The rollout will start on July, 3 and will take 3-4 days to propagate the image to all the environments.

### The motivation for the changes

According to our [Software and image guidelines](https://github.com/actions/runner-images#software-and-image-support) tools and versions have to be removed 6 months after they are deprecated or have reached end-of-life. The .NET 3.1 [has reached EOL on 13 December 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

### Possible impact

If your project depends on a pre-installed .NET 3.1 it can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

To install any version in runtime you can use the following action\task:

https://github.com/actions/setup-dotnet for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops task for AzDO

**Comment by wsmelton** [comment]
> The .NET 3.1 [has reached EOL on 13 December 2023](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

Should read as:

> The .NET 3.1 [has reached EOL on 13 December 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

**Comment by erik-bershel** [comment]
All the images rolled out.
