### ISSUE TITLE
[Windows] Invoke-WebRequest: The Local Security Authority cannot be contacted

### ISSUE THREAD

**Issue by Cyberboss** [actions/runner-images#7669]
### Description

Recreating this issue so it doesn't get lost. The original issue is closed but still prevalent: https://github.com/actions/runner-images/issues/7007

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
  Image: windows-2022
  Version: 20230508.3
  Included Software: https://github.com/actions/runner-images/blob/win22/20230508.3/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230508.3
```

### Is it regression?

Unknown

### Expected behavior

TLS connections run successfully

### Actual behavior

TLS connections sometimes fail with the following error.

### Repro steps

Unknown, I've seen it happen when trying to download this specific file from a .NET 6.0 program: https://github.com/tgstation/tgstation-server/releases/download/tgstation-server-v4.8.1/ServerUpdatePackage.zip

**Comment by ilia-shipitsin** [comment]
@Cyberboss 

I ran couple of times in my fork

(original matrix)
https://github.com/ilia-shipitsin/tgstation-server/actions/runs/5187279899

(reduced matrix, only windows)
https://github.com/ilia-shipitsin/tgstation-server/actions/runs/5187797819


those builds use "windows-latest", however I do not see "The Local Security Authority cannot be contacted".
there are several failures, but them look "something on app level".


do you have any suggestion how to get repro ?

**Comment by Cyberboss** [comment]
I'll check if the issue is still occurring

**Comment by ilia-shipitsin** [comment]
also, I do not see any `Invoke-WebRequest` usage ....

![image](https://github.com/actions/runner-images/assets/125650415/cef0e3a7-869b-4e6e-a7a5-6d93d6897b52)

**Comment by ilia-shipitsin** [comment]
I've created simple workflow on `windows-latest` (URL is downloaded 50 times)

```
          (0..50) | % { 
              Invoke-WebRequest -Headers @{ Authorization = "Token $env:GITHUB_TOKEN" } -Uri 'https://github.com/tgstation/tgstation-server/releases/download/tgstation-server-v4.8.1/ServerUpdatePackage.zip' -OutFile ServerUpdatePackage.zip
              Get-Item 'ServerUpdatePackage.zip'
              Start-Sleep -Sec 10 
           }
```


all green

https://github.com/ilia-shipitsin/gh7669/actions/runs/5189002820/jobs/9353390883


maybe, some other change that trigger Local Security Authority ?

**Comment by Cyberboss** [comment]
The issue was copied from the original, it seems to affect all the machine's SSL traffic. In our case it was using a .NET `HttpClient`

This did not occur until sometime last month with no changes on our end. We shortly switched to use `windows-2019` which did not have the issue.

I have a test up to see if it will reoccur now. The tricky bit is we've since abstracted the majority of the GitHub API calls we make in the integration tests, so there aren't as many anymore. In fact, I think there's only one remaining.

@Giorgi and @weshaggard are also familiar with the issue. Perhaps they can comment.

**Comment by weshaggard** [comment]
For my case it seems to be an issue with using Invoke-WebRequest while downloading files from github on a windows machine. It didn't repro every time but it did enough to where I actually moved to pulling files from Azure blob storage instead of a github release and haven't had an issue sense.

**Comment by ilia-shipitsin** [comment]
I can imagine that SSL certificate storage could get corrupted under some heavy IO operations. Nothing else comes to mind.
No idea how to reproduce

**Comment by ilia-shipitsin** [comment]
> For my case it seems to be an issue with using Invoke-WebRequest while downloading files from github on a windows machine. It didn't repro every time but it did enough to where I actually moved to pulling files from Azure blob storage instead of a github release and haven't had an issue sense.

it was easy thing to try, I [downloaded](https://github.com/ilia-shipitsin/gh7669/actions/runs/5189002820/jobs/9353390883) zip 50 times, no failure.
however, it was the only job on vm, vm was not overloaded

**Comment by Giorgi** [comment]
I downgraded to 2019 and there are no issues.

**Comment by weshaggard** [comment]
Only update for me is that I tried to create a localized repro but never got it to fail. However, we definitely had lots of failures across our many builds which forced me to move to a new solution. The only thing I was able to narrow down is that it appears to be some issue with Windows 2022 agent and connecting to an https endpoint on github. I say that because I've not seen any issues connecting to an https endpoint for downloading from azure blob storage instead. 

If it is helpful here is a link to an example build log that was failing:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2782815&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=b942b2a6-feb0-56ec-1249-c44856571d9f

Here is a link to the change I made to move away from pulling from github to blob storage:
https://github.com/Azure/azure-sdk-for-net/commit/94bb08e3ff48faf86dc591f72e08a101b1004bb8

**Comment by Cyberboss** [comment]
I've recently switched back to 2022 due to the lack of repros

**Comment by ilia-shipitsin** [comment]
well, it would be really nice to fix Local Security Authority, however it is near to impossible without repro.
I'll have a look to azure-sdk builds next week

**Comment by Giorgi** [comment]
I reverted back to `windows-latest` and it worked this time. But it also used to fail intermittently so it's hard to tell from this single run.
