### ISSUE TITLE
Blaze build in Windows not working

### ISSUE THREAD

**Issue by s-perron** [actions/runner-images#7675]
### Description

The presubmit and continuous builds for spirv-tools are failing. In particular, the blaze build on windows is no longer able to find the C++ compiler. This started when the image version was updated to 20230517.1.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/s-perron/SPIRV-Tools/actions/runs/5189086426/jobs/9353588178?pr=14

20230517.1

### Is it regression?

Yes, 20230508.3 worked. https://github.com/KhronosGroup/SPIRV-Tools/actions/runs/5146670262/jobs/9266043569

### Expected behavior

We expect the compiler to be correctly identified, and the project to be compiled.

### Actual behavior

We see an error when trying to compile the first file:

```
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/users/runneradmin/.bazel/cache/uecedngd/external/com_google_googletest/BUILD.bazel:80:11: Compiling googlemock/src/gmock-cardinalities.cc failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command external\local_config_cc\vc_installation_error_x64.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 ... (remaining 24 arguments skipped)
```

### Repro steps

This fails the presubmit tests for all PRs in spirv-tools. You can reproduce by closing and reopening any existing PR.

I've been using:

https://github.com/s-perron/SPIRV-Tools/pull/14
https://github.com/KhronosGroup/SPIRV-Tools/pull/5254

**Comment by shamil-mubarakshin** [comment]
Hi @s-perron,

While investigating workflows, I came across following https://github.com/bazelbuild/bazel/issues/18592.
Your issue might be the case of inaccurate directory detection by bazel, since windows-2022 runners were updated with VS 17.6.
You can follow bazel issues for the resolution. Running workflows on windows 2019 is available as a workaround: `runs-on: windows-2019`.

**Comment by s-perron** [comment]
This is a duplicate of https://github.com/actions/runner-images/issues/7662.
