### ISSUE TITLE
 "GitHub Actions has encountered an internal error when running your job." when using reusable workflow

### ISSUE THREAD

**Issue by Cjkjvfnby** [actions/runner-images#7676]
### Description

I have a parent workflow that reuses other workflows, triggered by the push to a specific branch. 
https://github.com/freeorion/freeorion/blob/weekly-test-builds/.github/workflows/build-weekly.yml

There are 2 runs that fail with "GitHub Actions has encountered an internal error when running your job" for each child workflow.
GitHub status is green, retry does not change the situation.

Failing workflows runs are about a week apart:
- https://github.com/freeorion/freeorion/actions/runs/5189828460
- https://github.com/freeorion/freeorion/actions/runs/5148311572

A similar job was working before (because of force push the history is lost).
https://github.com/freeorion/freeorion/actions/workflows/build-weekly.yml

All three child workflows are part of another parent workflow, which is working well. But some steps are disabled when using them in other places: getting the secrets and uploading the binaries.

There is no run log now, but when it just started it was a couple of lines:
```
Requested labels: macos-11
Job defined at: freeorion/freeorion/.github/workflows/_build-macos.yml@refs/heads/weekly-test-builds
Reusable workflow chain:
freeorion/freeorion/.github/workflows/build-weekly.yml@refs/heads/weekly-test-builds (09820928d10afd94e7f55704f7624cd8a01f7f4f)
-> freeorion/freeorion/.github/workflows/_build-macos.yml@refs/heads/weekly-test-builds (09820928d10afd94e7f55704f7624cd8a01f7f4f)
Waiting for a runner to pick up this job...
Job is waiting for a hosted runner to come online.
Job is about to start running on the hosted runner: GitHub Actions 4 (hosted)
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/freeorion/freeorion/actions/runs/5189828460

### Is it regression?

Not sure, build that was working might had sligtly different code

### Expected behavior

I expect workflow to work or provide more specific error messages.

### Actual behavior

Workflow fails with "GitHub Actions has encountered an internal error when running your job" after a couple of seconds after start.

### Repro steps

- Fork the repo https://github.com/freeorion/freeorion
- Checkout `weekly-test-builds`
- Make a dummy commit to trigger build "git commit --allow-empty -m "Dummy"
- Push branch
- Check workflow "Weekly" (build-weekly.yml)

**Comment by mikhailkoliada** [comment]
Hello! Please report this issue to the actions/runner repository https://github.com/actions/runner
