### ISSUE TITLE
Ubuntu 22.04 - unable to authenticate on local Postgres

### ISSUE THREAD

**Issue by llRandom** [actions/runner-images#7678]
### Description

According to https://github.com/actions/runner-images/blob/ubuntu22/20230604.1/images/linux/Ubuntu2204-Readme.md this image includes Postgres server. There's an info about username but there's no password. I'm trying to run .net tests on this server in azure devops pipeline. I've tried several options:
1. Skip password & use the following connection string: `Server=localhost;Database=MyTestDb;Username=postgres;Include Error Detail=true;CommandTimeout=300`. The error is `No password has been provided but the backend requires one (in SASL/SCRAM-SHA-256-PLUS)`
2. Enable integrated security: `Server=localhost;Database=MyTestDb;Username=postgres;Integrated Security=True;Include Error Detail=true;CommandTimeout=300`. Same error: `No password has been provided but the backend requires one (in SASL/SCRAM-SHA-256-PLUS)`
3. Enable integrated security & skip username: `Server=localhost;Database=MyTestDb;Integrated Security=True;Include Error Detail=true;CommandTimeout=300`. Same error: `No password has been provided but the backend requires one (in SASL/SCRAM-SHA-256-PLUS)`
4. Tried basic passwords (`root` and `postgres`) with and without `Integrated Security`. The error is `28P01: password authentication failed for user "postgres"`

What is expected way to connect to Postgres? It would be helpful to add this info to readme page. And it's added for Windows images (password `root`)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20230604.1

### Is it regression?

No

### Expected behavior

Add information about the password or expected authentication method to wiki page

### Actual behavior

Auth info only includes username and it fails if password is not provided and integrated security is not working

### Repro steps

1. Start Postgres server (`sudo systemctl start postgresql.service`)
2. Run .net app that connects to local postgres using npgsql 7.0.1 package with `Server=localhost;Database=MyTestDb;Username=postgres;Integrated Security=True;Include Error Detail=true;CommandTimeout=300` connection string

**Comment by ilia-shipitsin** [comment]
we use the following to test postgres (it's not public, but there's no sensitive info)

`sudo -u postgres psql -c "CREATE DATABASE new_test_db"`

from what I can tell, postgres is set to use "ident" auth, i.e. if linux (system) user is "postgres", it is authenticated.
but I really wonder why nobody else complains :)

**Comment by llRandom** [comment]
Thanks! Maybe I'm doing something wrong or npgsql client doesn't support ident auth but it seems to work after executing `sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'root'"`, will use that as a workaround

**Comment by ilia-shipitsin** [comment]
glad to hear it is resolved.
I'm closing this issue, feel free to reopen if issue persist
