### ISSUE TITLE
Qemu-user-static install failed with 404 on ubuntu-22.02

### ISSUE THREAD

**Issue by timandy** [actions/runner-images#7682]
### Description

Qemu install failed with 404 on ubuntu-22.02

```
Run sudo apt-get -y install qemu-user-static
  sudo apt-get -y install qemu-user-static
  shell: /usr/bin/bash -e {0}
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  qemu-user-static
0 upgraded, 1 newly installed, 0 to remove and [2](https://github.com/timandy/routine/actions/runs/5209249159/jobs/9398865987#step:7:2)8 not upgraded.
Need to get 1[3](https://github.com/timandy/routine/actions/runs/5209249159/jobs/9398865987#step:7:3).0 MB of archives.
After this operation, 130 MB of additional disk space will be used.
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd6[4](https://github.com/timandy/routine/actions/runs/5209249159/jobs/9398865987#step:7:5) qemu-user-static amd[6](https://github.com/timandy/routine/actions/runs/5209249159/jobs/9398865987#step:7:7)4 1:6.2+dfsg-2ubuntu6.[8](https://github.com/timandy/routine/actions/runs/5209249159/jobs/9398865987#step:7:9)
  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_6.2%2bdfsg-2ubuntu6.8_amd64.deb  404  Not Found [IP: 40.81.[13](https://github.com/timandy/routine/actions/runs/5209249159/jobs/9398865987#step:7:14).82 80]
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/timandy/routine/actions/runs/5209093876/jobs/9398538244

### Is it regression?

https://github.com/timandy/routine/actions/runs/5152256809/jobs/9296930310

### Expected behavior

install qemu-user-static successful.

### Actual behavior

install failed with 404

### Repro steps

1. Use runner ubuntu-22.04
2.  run cmd `sudo apt-get -y install qemu-user-static`

**Comment by ilia-shipitsin** [comment]
hello, @timandy 

`apt-get install ... ` operates on package cache, which sometimes must be updated by running `apt-get update`

https://blog.packagecloud.io/you-need-apt-get-update-and-apt-get-upgrade/
