### ISSUE TITLE
Windows2022 - Install VS error - Component.Unreal.Android not found. Using Latest Image.

### ISSUE THREAD

**Issue by 2E0MHQ** [actions/runner-images#7684]
### Description

Have been stuck with the following error since 3/10. We use Packer build to create images for VMSS from the Windows2022.json template file. Our pipeline downloads the latest version of the image each run.

Image creation fails at the install Visual Studio step. Pester tests fails as shown in the following:

vhd: Running tests from 'C:\image\Tests\VisualStudio.Tests.ps1'
...
vhd: [-] Component.Unreal.Android 473ms (470ms|3ms)
vhd: Expected 'Component.Unreal.Android' to be found in collection @('android', 'Component.Android.Emulator.MDD', 'Component.Android.NDK.R23C', 'Component.Android.SDK.MAUI', 'Component.CPython39.x64', 'Component.Dotfuscator', 'Component.HAXM.Private', 'Component.Linux.CMake', 'Component.Linux.RemoteFileExplorer', 'Component.MDD.Android', ...255 more), but it was not found.
vhd: at $installedComponents | Should -Contain $ComponentName, C:\image\Tests\VisualStudio.Tests.ps1:22
vhd: at , C:\image\Tests\VisualStudio.Tests.ps1:22

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'vblue000C4D'
Agent machine name: 'vblue000C4D'
Current agent version: '3.220.2'
Current image version: '1.0.44'
Agent running as: 'AzDevOps'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DownloadPipelineArtifact (1.198.0)
Downloading task: ExtractFiles (1.213.0)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

Not known

### Expected behavior

Virtual Studio installation passes Pester tests successfully

### Actual behavior

vhd: Tests Passed: 120, Failed: 1, Skipped: 1 NotRun: 0

### Repro steps

Deployment through Azure DevOps self-hosted agent. Packer backend hosted in Azure.

**Comment by shamil-mubarakshin** [comment]
Hello @2E0MHQ,
Could you provide tools version information on building agent (powershell, packer), options which specified for `packer biuld` and packer logs?

**Comment by mikhailkoliada** [comment]
Hello! Given we do not observe the same error over recent builds I am going to close the issue. Feel free to reach us out again if you have questions left.
