### ISSUE TITLE
Docker Compose v2.18.0 needs to be patched to v2.18.1 to fix Image not Found Issues

### ISSUE THREAD

**Issue by evgenyslab** [actions/runner-images#7686]
### Description

GH Runner failing to find built images due to bug that is fixed by docker compose v2.18.1:

https://docs.docker.com/compose/release-notes/#2181

Using Ubuntu-latest will cause certain docker-compose file instructions to fail.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230604.1

### Is it regression?

yes, previous version using docker compose 2.17.3 was OK

### Expected behavior

Docker compose should find images it built

### Actual behavior

Docker compose doesn't find images it built, seems to be issues in docker compose v2 2.18.0
https://docs.docker.com/compose/release-notes/#2181

### Repro steps

1. Create GH action that uses Docker Compose build command with override service
2. Run action that calls an override service
3. GH Action will report `Error: No such image: `

**Comment by marcanft** [comment]
Hello!

Will you update the docker compose version soon? 
This bug affects our tests and deployments

Thank you!

**Comment by joshm91** [comment]
Yeah, this is breaking our Actions as well. @erik-bershel The broken Docker Compose version (2.18.0) is _already_ in the latest ubuntu-latest version.

**Comment by erik-bershel** [comment]
Currently the next Ubuntu releases are expected around June 15.

**Comment by evgenyslab** [comment]
Is there a possibility for hot-fix to be deployed sooner? Sadly this is blocking all of our Org's deployments.

**Comment by joshm91** [comment]
Yeah, that's a long time to wait for a fairly major breakage. Docker compose seems [quite popular](https://github.com/search?q=%22docker-compose+up%22+path%3A.github%2Fworkflows+language%3AYAML+lang%3AYAML&type=code&ref=advsearch) within Actions.

**Comment by dhansen-gw** [comment]
For what it's worth, this is blocking our org's deployments as well. As an aside, the same broken version is also included in Ubuntu 20.04

**Comment by gsong** [comment]
We rely on this for our CI and backups, so it's critical that this is fixed ASAP. We are also being billed for the broken workflows due to the broken runners.

**Comment by mikhailkoliada** [comment]
Hello! We are rolling the image version to the exact version without issue in question. The old runner image version will be available in 3-5h depending on your region

**Comment by samvantran** [comment]
Sorry for this causing issues. Ubuntu images should be back to `20230517.1` now - please let us know if you aren't seeing that. If your workflows are back to working as expected with the previous version of docker-compose, we can close this issue. Thank you everyone for reporting!
