### ISSUE TITLE
Latest Change in build agent for Image: ubuntu-latest and image: macos-latest started failing since last few hours since 5 AM IST

### ISSUE THREAD

**Issue by kanhaiya4197** [actions/runner-images#7692]
### Description

Latest Change in build agent for Image: ubuntu-latest and image: macos-latest started failing since last few hours since 5 AM IST

Generating script.
========================== Starting Command Output ===========================
/bin/bash /Users/runner/work/_temp/860d684b-534b-40b5-80c0-21fcb50588ee.sh
Path variable value is /usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.9.3/x64:/Users/runner/.pub-cache/bin:/Users/runner/work/1/s/apps/flutter/bin/cache/dart-sdk/bin:/Users/runner/work/1/s/apps/lib/main.dart
Downloading ios tools...                                            3.7s
Downloading ios-profile tools...                                 2,752ms
Downloading ios-release tools...                                 2,286ms
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.sc.mobile.scMobileAppAlpha for device (ios-release)...
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Adding input path to Thin Binary build phase.
Running pod install...                                            187.6s
Running Xcode build...                                          
Xcode build done.                                           428.0s
Failed to build iOS app
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/sentry_flutter-6.22.0/lib/src/widgets_binding_observer.dart:178:17: Error: A non-*** value must be returned since the return type 'String' doesn't allow ***.

Encountered error while building for device.

Android Build : 
Note: Recompile with -Xlint:deprecation for details.
Note: /home/vsts/.pub-cache/hosted/pub.dev/mixpanel_flutter-2.1.1/android/src/main/java/com/mixpanel/mixpanel_flutter/MixpanelFlutterHelper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
../../../../../.pub-cache/hosted/pub.dev/sentry_flutter-6.22.0/lib/src/widgets_binding_observer.dart:178:17: Error: A non-*** value must be returned since the return type 'String' doesn't allow ***.
  static String _lifecycleToString(AppLifecycleState state) {
                ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/home/vsts/work/1/s/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1214

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/vsts/work/1/s/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 1m 5s
Running Gradle task 'assembleRelease'...                           65.9s
Gradle task assembleRelease failed with exit code 1
Flutter build for Android completed

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-latest and 
image: macos-latest

### Is it regression?

no

### Expected behavior

no Build has been working successfully till 12 AM IST

### Actual behavior

Pipelines should work as expected

### Repro steps

Please test mobile build for android and IOS with SENTRY 6.22.0

**Comment by erik-bershel** [comment]
Hello @kanhaiya4197!

Nothing significant happened simultaneously with macOS and Ubuntu during this period. Additionally, it is worth considering that these operating system branches are largely independent in our infrastructure, which greatly reduces the likelihood of the same error occurring.

To better understand the situation, please provide the following information:
- The version of the agents on which the task was executed
- The version of the agents on which the task failed
- Complete reproduction steps, including the YAML file or snippet and a minimal project that reproduces the error
- If your project is public, please provide a link to it.

**Comment by erik-bershel** [comment]
Hey @kanhaiya4197!
I will be forced to close the issue due to lack of information. Please provide more info about problem.

**Comment by kanhaiya4197** [comment]
We had to upgrade SENTRY version to get it resolved
