### ISSUE TITLE
MSVC version not synced

### ISSUE THREAD

**Issue by gengjiawen** [actions/runner-images#7700]
### Description

trigger https://github.com/nodejs/node/pull/45427#issuecomment-1586733684. 
MSVC version is old 14.35. The version should be 14.36

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

  Image: windows-2022
  Version: 20230606.1

### Is it regression?

no

### Expected behavior

right MSVC version in Visual Studio

### Actual behavior

not latest version

### Repro steps

trigger https://github.com/nodejs/node/pull/45427

**Comment by gengjiawen** [comment]
fixed in https://github.com/actions/runner-images/pull/7694.

**Comment by vpolikarpov-akvelon** [comment]
Reopening issue because fix haven't deployed yet.

**Comment by vpolikarpov-akvelon** [comment]
Hey @gengjiawen. Update have been rolled out. Please try running your workflow.

**Comment by gengjiawen** [comment]
> Hey @gengjiawen. Update have been rolled out. Please try running your workflow.

thx, now build passed.

**Comment by gengjiawen** [comment]
@vpolikarpov-akvelon This re-appeared. Can you take a look. 

ctx: https://github.com/nodejs/node/pull/45427#issuecomment-1662307056

cc @targos

**Comment by vpolikarpov-akvelon** [comment]
Hey @gengjiawen. I don't see any new updates for MSVC build tools, the latest version is 14.36 still. There should be some other reason for your workflow to fail. Could you please check it once more and create a new issue if it looks like image regression indeed?
