### ISSUE TITLE
Update [Xcode Default on macOS 13 Runners to 14.3.1]

### ISSUE THREAD

**Issue by xavier2k6** [actions/runner-images#7713]
### Tool name

Xcode

### Tool license

Apple, Inc.

### Add or update?

- [ ] Add
- [X] Update

### Desired version

14.3.1

### Brief description of tool

Xcode IDE

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello! We change the default version once in 3-5 weeks after a new major version released, we have no plans to change it right now, please use the https://github.com/maxim-lobanov/setup-xcode if you want another version to be specified in the meantime
