### ISSUE TITLE
Update WiX to version 3.14 (latest development build)

### ISSUE THREAD

**Issue by svnscha** [actions/runner-images#7721]
### Tool name

WiX

### Tool license

Microsoft Reciprocal License (MS-RL)

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.14

### Brief description of tool

WiX handles MSI installation as you folks most likely know. WiX was recently updated to v 3.14 (latest development build). This version got ARM64 support. The Azure agents do cross-compile just fine but the missing WiX 3.14 is hindering at least myself to make an MSI package in Azure. 

Any chance you guys can update that?

### URL for tool's homepage

https://wixtoolset.org/docs/v3/releases/v3-14-0-6526/

### Provide a basic test case to validate the tool's functionality.

```bash
Pretty sure there are test cases already.
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

1 minute

### Are you willing to submit a PR?

most likely, but I have no idea how to build these agents to test my PR

**Comment by vpolikarpov-akvelon** [comment]
Hey @svnscha. Thank you for the request. We are investigating it.

**Comment by vpolikarpov-akvelon** [comment]
Hey @svnscha. According to the documentation development builds are not considered to be production-ready and may introduce unexpected bugs so we are not going to install it. The latest official release of WiX Toolset v3 is v3.11.2.

**Comment by svnscha** [comment]
Hi again, thank you for this quick response! That is fair enough and I will check installing it in this specific use case when the pipeline starts.
