### ISSUE TITLE
./images/linux/scripts/installers/git.sh failed at line 42

### ISSUE THREAD

**Issue by xfc** [actions/runner-images#7722]
### Description

git.sh failed at https://github.com/actions/runner-images/blob/500995c0adc5830fd3da8b3347b97806c568a6be/images/linux/scripts/installers/git.sh#L42
with error: 
" jq: error (at <stdin>:1): Cannot index string with string "prerelease"
  jq: error (at <stdin>:1): Cannot index string with string "tag_name"
".

The root cause is at this line: https://github.com/actions/runner-images/blob/500995c0adc5830fd3da8b3347b97806c568a6be/images/linux/scripts/helpers/install.sh#L75

A very simple way to reproduce this bug is to run this line (https://github.com/actions/runner-images/blob/500995c0adc5830fd3da8b3347b97806c568a6be/images/linux/scripts/helpers/install.sh#L75) manually : "curl -s https://api.github.com/repos/github/hub/releases?per_page=100" and the return is:
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/401025/releases?per_page=100",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}.

Two potential solutions:
1. replace "curl -s" with "curl -sL" at https://github.com/actions/runner-images/blob/500995c0adc5830fd3da8b3347b97806c568a6be/images/linux/scripts/helpers/install.sh#L75.
2. replace "github/hub" with "GrantBirki/hub" at https://github.com/actions/runner-images/blob/500995c0adc5830fd3da8b3347b97806c568a6be/images/linux/scripts/installers/git.sh#L42. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Any.

### Is it regression?

No.

### Expected behavior

./images/linux/scripts/installers/git.sh ran successfully.

### Actual behavior

./images/linux/scripts/installers/git.sh failed.

### Repro steps

A one-liner to reproduce the bug is provided in the description section.

**Comment by vpolikarpov-akvelon** [comment]
Hey @xfc. Could you elaborate a bit what you are trying to do?

**Comment by MonaMoravej** [comment]
I have seen the exact same issue, starting today, I am using the "releases/ubuntu22/20230611" tag to re-build a custom image (subset of toolset needed to be installed in our image and we do share the generated image in azure image gallery)

**Comment by ejike-nnodi** [comment]
Yes I noticed the same issue as well... I was actually just investigating it.

I can confirm that @mikhailkoliada solution works
adding "-sL" to curl command.

**Comment by mikhailkoliada** [comment]
Should be fixed now, please pull updates from main!
