### ISSUE TITLE
Add things to make customization easier 

### ISSUE THREAD

**Issue by naikrovek** [actions/runner-images#7729]
### Description

This is more of a feature request of the templates than a bug report on any functionality.

My enterprise hosts our own fleet of enterprise runners for GHES and GHEC and they are based on these templates.  Thank you very much for making these templates available, by the way.

Recently, for Ubuntu, a file called `basic.sh` was removed, and that caused a small problem for us.  We've since addressed our problem which was caused by the removal of that file, and in doing so I thought that it would be quite nice if there were a couple of empty scripts in this repo which served as "attachment" points for users to add customizations they wish to apply on top of what this template provides.  

Prior to the removal of `basic.sh`, my automation around these Ubuntu templates was a shell script which would `cat` a few commands to the end of `basic.sh` before invoking Packer.  It was a good place to add a few things that I needed to add because invocation of `basic.sh` was very early in the execution of the template.  Now it is gone and I need to modify the Packer template JSON itself programmatically to make sure that my customizations get executed.

If it is feasible to do so, can you please add an empty script to the beginning of the Ubuntu Packer templates, and another at the end, as a place for users to add customizations easily?  It won't add any build time to the repo as-is, because while the scripts will exist and will be called, they take no action and exit immediately.

This would be a "nice to have" or "quality of life" feature and nothing more.  I have already implemented my changes without these additions, but I felt it would be something that may be useful for others who also use your templates with a bit of customization.

Thank you.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

not applicable

### Is it regression?

no

### Expected behavior

I would like to see a couple of empty scripts called by the template to ease customization of these templates.

### Actual behavior

There are no ways to easily customize these packer templates without either manually maintaining the changes, or programmatically manipulating the template files before invoking Packer, and neither of those solutions are good.

### Repro steps

not applicable

**Comment by vpolikarpov-akvelon** [comment]
Hi @naikrovek. Thank you for your request, we will consider it definitely.

Btw, speaking of basic.sh, it wasn't removed but renamed [here](https://github.com/actions/runner-images/commit/e62bcae84b772d1d5346bb884faa80d64aa4cd91#diff-5dd28a78d7dccdb493ebb587f485facc1db67cb8dc0fc98a8ecd8a83fb6db349). For now you can continue doing what you used to with renamed script.

**Comment by mikhailkoliada** [comment]
Hello! We have no plans to change status quo, adding any number of arbitrary files to the downloaded repo and then modify the packer templates is a pretty straightforward way of acting, we believe no additional steps are required from our side.
