### ISSUE TITLE
git-ftp package installation fails

### ISSUE THREAD

**Issue by tomvo12** [actions/runner-images#7734]
### Description

Hi!

Currently, I cannot create images based on ubuntu20/20230611.1 release or ubuntu22/20230611.1 due to the following error:

    azure-arm.build_vhd: After this operation, 80.9 kB of additional disk space will be used.
    azure-arm.build_vhd: Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 git-ftp all 1.6.0+dfsg-1 [25.2 kB]
    azure-arm.build_vhd: Fetched 25.2 kB in 0s (780 kB/s)
    azure-arm.build_vhd: Selecting previously unselected package git-ftp.
    azure-arm.build_vhd: (Reading database ... 176619 files and directories currently installed.)
    azure-arm.build_vhd: Preparing to unpack .../git-ftp_1.6.0+dfsg-1_all.deb ...
    azure-arm.build_vhd: Unpacking git-ftp (1.6.0+dfsg-1) ...
    azure-arm.build_vhd: Setting up git-ftp (1.6.0+dfsg-1) ...
    azure-arm.build_vhd: Processing triggers for man-db (2.10.2-1) ...
    azure-arm.build_vhd: NEEDRESTART-VER: 3.5
    azure-arm.build_vhd: NEEDRESTART-KCUR: 5.15.0-1039-azure
    azure-arm.build_vhd: NEEDRESTART-KEXP: 5.15.0-1040-azure
    azure-arm.build_vhd: NEEDRESTART-KSTA: 3
    azure-arm.build_vhd: NEEDRESTART-SVC: chrony.service
    azure-arm.build_vhd: NEEDRESTART-SVC: dbus.service
    azure-arm.build_vhd: NEEDRESTART-SVC: irqbalance.service
    azure-arm.build_vhd: NEEDRESTART-SVC: multipathd.service
    azure-arm.build_vhd: NEEDRESTART-SVC: networkd-dispatcher.service
    azure-arm.build_vhd: NEEDRESTART-SVC: packagekit.service
    azure-arm.build_vhd: NEEDRESTART-SVC: polkit.service
    azure-arm.build_vhd: NEEDRESTART-SVC: rsyslog.service
    azure-arm.build_vhd: NEEDRESTART-SVC: ssh.service
    azure-arm.build_vhd: NEEDRESTART-SVC: systemd-journald.service
    azure-arm.build_vhd: NEEDRESTART-SVC: systemd-logind.service
    azure-arm.build_vhd: NEEDRESTART-SVC: systemd-manager
    azure-arm.build_vhd: NEEDRESTART-SVC: systemd-networkd.service
    azure-arm.build_vhd: NEEDRESTART-SVC: systemd-resolved.service
    azure-arm.build_vhd: NEEDRESTART-SVC: systemd-udevd.service
    azure-arm.build_vhd: NEEDRESTART-SVC: unattended-upgrades.service
    azure-arm.build_vhd: NEEDRESTART-SVC: user@1000.service
    azure-arm.build_vhd: NEEDRESTART-SVC: walinuxagent.service
    azure-arm.build_vhd: Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
    azure-arm.build_vhd: Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
    azure-arm.build_vhd: Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
    azure-arm.build_vhd: Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
    azure-arm.build_vhd: Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
    azure-arm.build_vhd: Hit:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
    azure-arm.build_vhd: Hit:7 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
    azure-arm.build_vhd: Hit:8 http://archive.ubuntu.com/ubuntu jammy InRelease
    azure-arm.build_vhd: Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
    azure-arm.build_vhd: Hit:10 https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease
    azure-arm.build_vhd: Reading package lists...
    azure-arm.build_vhd: PPA publishes dbgsym, you may need to include 'main/debug' component
    azure-arm.build_vhd: Repository: 'deb https://ppa.launchpadcontent.net/git-core/ppa/ubuntu/ jammy main'
    azure-arm.build_vhd: Description:
    azure-arm.build_vhd: The most current stable version of Git for Ubuntu.
    azure-arm.build_vhd:
    azure-arm.build_vhd: For release candidates, go to https://launchpad.net/~git-core/+archive/candidate .
    azure-arm.build_vhd: More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
    azure-arm.build_vhd: Removing repository.
    azure-arm.build_vhd: Disabling deb entry in /etc/apt/sources.list.d/git-core-ubuntu-ppa-jammy.list
    azure-arm.build_vhd: Removing disabled deb entry from /etc/apt/sources.list.d/git-core-ubuntu-ppa-jammy.list
    azure-arm.build_vhd: Removing disabled deb-src entry from /etc/apt/sources.list.d/git-core-ubuntu-ppa-jammy.list
==> azure-arm.build_vhd: jq: error (at <stdin>:1): Cannot index string with string "prerelease"
==> azure-arm.build_vhd: jq: error (at <stdin>:1): Cannot index string with string "tag_name"
==> azure-arm.build_vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_vhd: 

Anything we can do about that?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu20/20230611.1
ubuntu22/20230611.1

### Is it regression?

no

### Expected behavior

Image should be created finally

### Actual behavior

Image creation fails, retries did not help so far

### Repro steps

Start image creation based on the listed releases
[build-ubuntu22-prod-20230616_093417.log](https://github.com/actions/runner-images/files/11768920/build-ubuntu22-prod-20230616_093417.log)
[build-ubuntu22-prod-20230615_102917.log](https://github.com/actions/runner-images/files/11768923/build-ubuntu22-prod-20230615_102917.log)

**Comment by mikhailkoliada** [comment]
Hello! This is fixed in main, please build from main, we do not guarantee building from releases.

**Comment by tomvo12** [comment]
Ah, ok

Didn't expect a guarantee anyway, but usually a 5 days old release does work.

thx
