### ISSUE TITLE
Windows ASAN Build Regression in 20230612.1

### ISSUE THREAD

**Issue by nibanks** [actions/runner-images#7739]
### Description

Yesterday we started noticing our ASAN Windows builds in [microsoft/msquic](https://github.com/microsoft/msquic) start occassionally failing with the following errors:
```
error LNK2038: mismatch detected for 'annotate_string': value '0' doesn't match value '1'
```
A quick search of the internet seems to indicate some issues related to ASAN builds, but from long ago.

Today, the builds all are consistently failing, and I have determined that builds on `20230606.1` always pass, while `20230612.1` always fail. My guess is that the move from `Microsoft.VisualStudio.Component.VC.14.35.*` to `Microsoft.VisualStudio.Component.VC.14.36.*` is the cause here, and while the Runner might not be completely responsible for this, it has regressed our ability to build our product that ships both in Windows and externally.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

`20230612.1` - https://github.com/microsoft/msquic/actions/runs/5273495410/jobs/9536998292

### Is it regression?

Yes

### Expected behavior

The builds should succeed.

### Actual behavior

The builds for ASAN fail with `error LNK2038: mismatch detected for 'annotate_string': value '0' doesn't match value '1'`.

### Repro steps

Run the MsQuic BVT pipeline.

**Comment by ilia-shipitsin** [comment]
we'll have a look

**Comment by ilia-shipitsin** [comment]
I did a brief search, looks like lib<-->app flags mismatch

https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/sanitizers/error-container-overflow.md#error-container-overflow

```
When a standard type has annotations enabled, to avoid one-definition-rule (ODR) violations, each static library and object used to link the binary must also enable those annotations. Effectively, you must build those static libraries and objects with AddressSanitizer enabled. Mixing code with different annotation settings causes an error
```


I was able to reproduce that failure in my fork. I wonder why it was triggered with image change

**Comment by ilia-shipitsin** [comment]
looks like there's breaking change: https://developercommunity.visualstudio.com/t/__sanitizer_annotate_contiguous_containe/10119696

**Comment by erik-bershel** [comment]
Deployment with 14.35 here: https://github.com/actions/runner-images/pull/7798

**Comment by nibanks** [comment]
Thanks @ilia-shipitsin and @erik-bershel, so with this, it should fix things by adding back the old VC?

**Comment by ilia-shipitsin** [comment]
@nibanks the answer is "yes, if you switch to older VC"

**Comment by ilia-shipitsin** [comment]
@nibanks , hope you are doing well. did you have a chance to test ? can we close this issue ?

**Comment by nibanks** [comment]
How do we test on the new deployment?

**Comment by ilia-shipitsin** [comment]
well, it is something we do not know.
new image contains several MSVC versions.

how to tell msquic to pick certain version number - it depends on build system used in msquic

**Comment by ilia-shipitsin** [comment]
@nibanks, I'm going to close this issue.

**Comment by nibanks** [comment]
Ok. I will let you know if things don't work out.
