### ISSUE TITLE
Update to NSIS 3.08 "large strings" build

### ISSUE THREAD

**Issue by mpilgrem** [actions/runner-images#7740]
### Tool name

NSIS 3.08 "large strings" build

### Tool license

zlib/libpng

### Add or update?

- [ ] Add
- [X] Update

### Desired version

NSIS 3.08 "large strings" build

### Brief description of tool

See https://nsis.sourceforge.io/Special_Builds under the heading 'Large strings', the guidance there, and the link to the zip file with the relevant build.

The motivation for this request is reducing the risk of building installers that corrupt `PATH` environment variables that exceed the default 1024 characters. See https://nsis.sourceforge.io/Environmental_Variables:_append,_prepend,_and_remove_entries. 

Alternatively, there appears to be a plug in that could be installed to expand the functionality of the basic ("short strings") build: https://nsis.sourceforge.io/EnVar_plug-in.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by mpilgrem** [comment]
The original NSIS 3.08 tool request issue was: https://github.com/actions/runner-images/issues/4739.

**Comment by mpilgrem** [comment]
@ilia-shipitsin , I am afraid I am just a user. I am involved with a project called Stack that uses a NSIS compiler to create its Windows installer. In the GitHub Actions CI for that project, in a `shell: bash`, I am doing the following:

~~~
        # Updates NSIS 3.08 to a 'large strings' build of the same tool. See
        # https://nsis.sourceforge.io/Special_Builds.
        if [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          # wget is not available but the Stack-supplied MSYS2 will provide it
          stack exec -- wget -O nsis-3.08-strlen_8192.zip https://downloads.sourceforge.net/nsis/NSIS%203/3.08/nsis-3.08-strlen_8192.zip
          7z x -aoa -o"/c/Program Files (x86)/NSIS" nsis-3.08-strlen_8192.zip
          # Clean up
          rm nsis-3.08-strlen_8192.zip
          # Report the version on the PATH ...
          makensis -VERSION && echo
          # Should include defined symbol NSIS_MAX_STRLEN=8192
          makensis -HDRINFO
        fi
~~~

I am using a MSYS2-supplied `wget` because I could not get the (Windows?) `curl` to work.

The `.zip` file includes executables that overwrite the executables in the standard (1024 character limit) build. I agree that is an odd way to package things.

**Comment by ilia-shipitsin** [comment]
it is not default installer and we need to be sure that we won't  introduce any side effect for all github actions customers.

**Comment by mpilgrem** [comment]
It is a puzzle. As described, the only difference between the builds is that symbol `NSIS_MAX_STRLEN` is set differently. The NSIS wiki is peppered with headline warnings that the basic build can corrupt users' environment variables (eg https://nsis.sourceforge.io/Path_Manipulation). So, why not just publish a version, as standard, that reduces that risk? Perhaps the NSIS objective of 'designed to be as small as possible' is considered to trump being 'safe to use'.

**Comment by ilia-shipitsin** [comment]
I trust NSIS developers that they have reasons not to add that to default build

**Comment by mpilgrem** [comment]
The 'large strings' advice on the NSIS wiki seems to have been there since the page was created in 2005. It starts "If you are working with large strings use this build ...". I suppose what may have changed is that in 2023, the percentage of people with user `PATH` environment variables longer than 1024 characters may be higher.

**Comment by mpilgrem** [comment]
Understood. There is an existing NSIS feature request from 2017: https://sourceforge.net/p/nsis/feature-requests/542/.

**Comment by mikhailkoliada** [comment]
Hello! Given it is easy enough to alter the build version right in pipeline runtime, we would not like to change it in the image, please continue installing in runtime
