### ISSUE TITLE
podman: broken network functionality for CNI plugins

### ISSUE THREAD

**Issue by jordimassaguerpla** [actions/runner-images#7753]
### Description

Since yesterday, I see this error 

```
plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"
```

I believe is a bug in the latest ubuntu update of podman https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

?

### Is it regression?

yes

### Expected behavior

2 days ago I had no error and network was working as expected with podman rootfull.

### Actual behavior

Network does not work see https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394

### Repro steps

podman network create -d bridge test-net
podman network ls

**Comment by ilia-shipitsin** [comment]
interesting.

do you think it makes sense to add the following to image testing ?

```
podman network create -d bridge test-net
podman network ls
```

**Comment by ilia-shipitsin** [comment]
btw, is it possible to downgrade podman using apt-get ? it would help to unblock users before podman fix is released

**Comment by jordimassaguerpla** [comment]
I  just realized that I was doing "sudo apt-get update && sudo apt-get -y install podman" . If I remove this line, the issue is not happening. I think by running apt-get I was installing the latest podman version, which is the broken one. I did not know the base image contained podman. Thus, by not running the apt-get command it works... but we do not have the latest updates from podman. However,  it will buy us some time, at least until it is fixed in Ubuntu.

**Comment by ilia-shipitsin** [comment]
it is similar to what we do during image generation. thus we could deploy buggy podman.

we [test](https://github.com/actions/runner-images/blob/main/images/linux/scripts/tests/Tools.Tests.ps1#L334-L344) podman, but just "podman -v"

**Comment by ilia-shipitsin** [comment]
I can imagine that `apt-get install podman=3.4.3` may work (3.4.3 is just an example, proper version ought to be specified)

**Comment by ilia-shipitsin** [comment]
@jordimassaguerpla , can you please help with podman ?

![image](https://github.com/actions/runner-images/assets/125650415/5bc1b4c9-f82f-4a97-a72a-771bc15b9a8d)


is it possible to make it return non zero ?

**Comment by pbrezina** [comment]
> I can imagine that `apt-get install podman=3.4.3` may work (3.4.3 is just an example, proper version ought to be specified)

`E: Version '3.4.3' for 'podman' was not found`

**Comment by ilia-shipitsin** [comment]
> > I can imagine that `apt-get install podman=3.4.3` may work (3.4.3 is just an example, proper version ought to be specified)
> 
> `E: Version '3.4.3' for 'podman' was not found`

yes, that was an example.

the exact command may be constructed from launchpad issue which describes known working version

```
 apt install podman=3.4.4+ds1-1ubuntu1 --allow-downgrades
```

**Comment by ilia-shipitsin** [comment]
@jordimassaguerpla , can you please review https://github.com/actions/runner-images/pull/7763/commits/43936f0dc3701b513fefd0cc5bd534792ef67b39 ?

**Comment by wzshiming** [comment]
I have the same problem https://github.com/kubernetes-sigs/kwok/actions/runs/5357275996/jobs/9720430111#step:14:67

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla , can you please review [43936f0](https://github.com/actions/runner-images/commit/43936f0dc3701b513fefd0cc5bd534792ef67b39) ?

Done. Sorry I could not do it last week.

**Comment by mikhailkoliada** [comment]
Workaround included into the image
