### ISSUE TITLE
Blazor project stopped to build after update to image version of windows-2022 20230612.1

### ISSUE THREAD

**Issue by DostojnyKocur** [actions/runner-images#7762]
### Description

We use Azure Pipeline to build out blazor project. Yesterday the project stopped to build. There was no code changes since last successful build (Jun 9). The only change I found was version of the image used by the build agent. Locally, the project builds without errors. We also test to build the project using older commit, but the result is the same.

The build have started to crash with the errors like:
 - Error RZ9991: The attribute names could not be inferred from bind attribute 'bind-value'. Bind attributes should be of the form 'bind' or 'bind-value' along with their corresponding optional parameters like 'bind-value:event', 'bind:format' etc.
 -  Error CS1660: Cannot convert lambda expression to type 'bool' because it is not a delegate type

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

2.0.238.1 Current image version: '20230612.1'

### Is it regression?

2.0.171.1 Current image version: '20230508.3'

### Expected behavior

The project builds without errors.

### Actual behavior

Build crashes with the errors like:
 - Error RZ9991: The attribute names could not be inferred from bind attribute 'bind-value'. Bind attributes should be of the form 'bind' or 'bind-value' along with their corresponding optional parameters like 'bind-value:event', 'bind:format' etc.
 -  Error CS1660: Cannot convert lambda expression to type 'bool' because it is not a delegate type
 

### Repro steps

Run azure pipeline with windows-2022 to build a blazor project.

**Comment by ilia-shipitsin** [comment]
@DostojnyKocur , can you help with repro steps ? small project maybe ? 

if your project is public, link would be fine.

**Comment by vpolikarpov-akvelon** [comment]
Hey, @DostojnyKocur.

It may be caused by Blazor regression that emerged in .NET Core SDK v7.0.302: https://github.com/dotnet/razor/issues/8718
New image release that includes fixed SDK is on the way already: https://github.com/actions/runner-images/pull/7761

**Comment by DostojnyKocur** [comment]
@ilia-shipitsin I'm afraid it isn't so easy. That's my client's repo. If the new image that @vpolikarpov-akvelon mentioned doesn't fix my build then I'll try to create sample project.

**Comment by DostojnyKocur** [comment]
Your workaround works like a charm. Many thanks.

**Comment by vpolikarpov-akvelon** [comment]
Hey @DostojnyKocur. Image update has been deployed. Could you check that your workflow works without the workaround now?

**Comment by DostojnyKocur** [comment]
Hi @vpolikarpov-akvelon. I just checked the pipeline and it works as expected. The new release fixed my issues. Thanks :)
