### ISSUE TITLE
Broken Python 3.7.17 in the runner image macos-13/20230611

### ISSUE THREAD

**Issue by pavoljuhas** [actions/runner-images#7764]
### Description

Recently the CI checks for the Python package [quantumlib/Cirq](https://github.com/quantumlib/Cirq) started failing when testing with Python 3.7 on the MacOS system.  Specifically the jobs fail on the import of a stock Python module bz2 with `ModuleNotFoundError: No module named '_bz2'` - [example](https://github.com/quantumlib/Cirq/actions/runs/5328915438/jobs/9654061191?pr=6122).

The same behavior persists after simplifying the CI job to a single `python -c 'import bz2'` command in 
https://github.com/pavoljuhas/Cirq/blob/43f0422f1a57953b61c9911afa336506a7792668/.github/workflows/ci.yml.
The job output is at https://github.com/quantumlib/Cirq/actions/runs/5338748062/jobs/9676533015?pr=6148

Can you please check if the Python 3.7.17 installation provided with the macos13/20230611 image is functional?

The macos-12 image seems to be affected as well; the CI failures appear to coincide with the upgrade of Python 3.7.16 --> 3.7.17.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230611.2

https://github.com/quantumlib/Cirq/actions/runs/5338748062/jobs/9676533015

### Is it regression?

Yes, the last passing build was https://github.com/quantumlib/Cirq/actions/runs/5306418353/jobs/9603991766

### Expected behavior

Python 3.7.17 can do `import bz2` as it is its builtin module.

### Actual behavior

Module import fails with the following traceback
```
python -c 'import bz2'
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/[3](https://github.com/quantumlib/Cirq/actions/runs/5306418353/jobs/9603991766#step:5:3).7.17/x6[4](https://github.com/quantumlib/Cirq/actions/runs/5306418353/jobs/9603991766#step:5:4)
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.7.17/x[6](https://github.com/quantumlib/Cirq/actions/runs/5306418353/jobs/9603991766#step:5:6)4/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.[7](https://github.com/quantumlib/Cirq/actions/runs/5306418353/jobs/9603991766#step:5:7).17/x64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.7.17/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.7.17/x64
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/bz2.py", line 1[9](https://github.com/quantumlib/Cirq/actions/runs/5306418353/jobs/9603991766#step:5:9), in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
Error: Process completed with exit code 1.
```

### Repro steps

Configure and trigger the CI job per
https://github.com/pavoljuhas/Cirq/blob/43f0422f1a57953b61c9911afa336506a7792668/.github/workflows/ci.yml

**Comment by ilia-shipitsin** [comment]
thank for the report. will have a look

**Comment by ilia-shipitsin** [comment]
@pavoljuhas , sorry for the issue.


we should wait for a fix from the upstream https://github.com/actions/setup-python/issues/682
