### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by RyanMulready** [actions/runner-images#7771]
### Description

When trying to run a workflow it fails with an error message `GitHub Actions has encountered an internal error when running your job.`. If you try to rerun the failed job it hangs indefinitely.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.305.0; It's a private repo

### Is it regression?

Yes

### Expected behavior

The job runs

### Actual behavior

The job doesn't run

### Repro steps

1. Run the job; watch it not work 😱

**Comment by ede-n** [comment]
We are experiencing the same issue as well, on self-hosted runners running on Kubernetes clusters.

**Comment by ilia-shipitsin** [comment]
can I ask you to open a ticket on https://support.github.com ?

here, in "runner-images" repo we handle issues with packages included to image, highly unlikely your issue is related to packages.

as for self-hosted agent, there may be an option to have a look at its log.

**Comment by mikhailkoliada** [comment]
Could you post a link to the failed build?

**Comment by mikhailkoliada** [comment]
There was a GitHub outage and multiple customers reported the same issues across different regions, the issue seems to be fixed now as we did our best to mitigate this. Feel free to reach us out again if you see something similar.
