### ISSUE TITLE
`libmemcached-dev` fails to install on `ubuntu-20.04` image version 20230619.1.0

### ISSUE THREAD

**Issue by mcheng-brilliant** [actions/runner-images#7774]
### Description

`libmemcached-dev` fails to install on `ubuntu-20.04` when it previously worked.

**Details:**

On the last successful workflow run, "Set up Job" has the following details:

```
Current runner version: '2.305.0'
Operating System
  Ubuntu
  20.04.6
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20230611.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230611.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230611.1
Runner Image Provisioner
  2.0.238.1
```

Note that the **Version is 20230611.1**.

On a later workflow run, the "Set up Job" output said:

```
Current runner version: '2.305.0'
Operating System
  Ubuntu
  20.04.6
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20230619.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230619.1.0/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230619.1.0
Runner Image Provisioner
  2.0.238.1
```

Note how the Version is now bumped up to 20230619.1.0.

Given that there are no differences between the dependency installation steps of these two workflow runs, I believe that the root cause was a change in latest Ubuntu 20.04 runner image.

Potentially other useful information is that these two jobs ran at around 3:14-3:40 AM PDT on 2023-06-22 which is close to the timing of when https://github.com/actions/runner-images/pull/7747 was merged.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/mcheng-brilliant/gha-dep-install-issue-repro/actions/runs/5350967616/jobs/9704227895?pr=1

### Is it regression?

yes

### Expected behavior

`libmemcached-dev` successfully installs.

### Actual behavior

`libmemcached-dev` fails to install with the following error:

```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libmemcached-dev : Depends: libhashkit-dev (= 1.0.18-4.2ubuntu2) but it is not going to be installed
                    Depends: libmemcached11 (= 1.0.18-4.2ubuntu2) but 1.1.3-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

### Repro steps

Unable to provide a public working example because our CI jobs are on private repositories, however, this is a link to a minimal reproduction example: https://github.com/mcheng-brilliant/gha-dep-install-issue-repro/blob/a22cedd48de11959f7f06cdd23fd80ba2a5bc2c9/.github/workflows/dep-install-repro.yml

To reproduce, create a GitHub Action workflow that:
1. `runs-on: ubuntu-20.04`
2. Has a step to run:
    ```
    sudo apt-get update
    sudo apt-get install -y libmemcached-dev
    ```
3. Trigger the workflow

Example:
```yml
name: Test Dependency Install

on: [push]

jobs:
  install_dependencies:
    runs-on: ubuntu-20.04
    steps:
      - name: install packages and dependencies
        run: |
          sudo apt-get update
          apt search libmemcached-dev
          sudo apt-get install -y libmemcached-dev
```

**Comment by ilia-shipitsin** [comment]
thank you for the detailed report

**Comment by ilia-shipitsin** [comment]
it is because of https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/php.sh#L14-L17

php-memcached installs its own libmemcached11 and that breaks libmemcached-dev installation

**Comment by ilia-shipitsin** [comment]
@mcheng-brilliant , I can suggest the following workaround (i.e. removing offending PPA and packages)

```
  dpkg -P libmemcached11 php8.2-memcached php8.1-memcached php8.0-memcached php7.4-memcached hhvm libhashkit2
  apt-add-repository --remove ppa:ondrej/php -y
  apt-get update
  apt install libmemcached-dev
```

I'm afraid we do not have good solution for Ubuntu 20, since php is very popular.

**Comment by mcheng-brilliant** [comment]
Thanks for getting back to me with the workaround. Luckily, we don't use PHP so this will work for us.

**Comment by mikhailkoliada** [comment]
I am going to close this for now as there is nothing more we are able to help with, it happens that package versions conflict between repos :/. Feel free to reach us again if you have more questions.

**Comment by lachesis** [comment]
Darn what a pain in the butt. We're only trying to use Python and never need PHP. It looks like a new PHP version was added to 20.04 after this post. The workaround that worked for me:

```
dpkg -P libmemcached11 php8.3-memcached php8.2-memcached php8.1-memcached php8.0-memcached php7.4-memcached hhvm libhashkit2
apt-add-repository --remove ppa:ondrej/php -y
apt-get update
apt install libmemcached-dev -y
```
