### ISSUE TITLE
sharp issues on macos runners

### ISSUE THREAD

**Issue by Stanzilla** [actions/runner-images#7779]
### Description

This recently broke, installing/rebuilding sharp via npm fails with it unable to find vips and glib

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20230618.1

### Is it regression?

Yes, Image: macos-12   Version: 20230612.1, https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5314011843

### Expected behavior

Build succeeds 

See https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5314011843

### Actual behavior

Build fails with 

node_modules/sharp install: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
node_modules/sharp install:   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
node_modules/sharp install:   LIBTOOL-STATIC Release/nothing.a
node_modules/sharp install: warning: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
node_modules/sharp install:   TOUCH Release/obj.target/libvips-cpp.stamp
node_modules/sharp install:   CXX(target) Release/obj.target/sharp-darwin-x64/src/common.o
node_modules/sharp install: ../src/common.cc:13:10: fatal error: 'vips/vips8' file not found
node_modules/sharp install: #include <vips/vips8>
node_modules/sharp install:          ^~~~~~~~~~~~
node_modules/sharp install: 1 error generated.

https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5360920526/jobs/9726429378

### Repro steps

- Have sharp in deps in package.json
- pnpm install
- pnpm install --config.platform=darwin --config.arch=x64 sharp && pnpm --config.platform=darwin --config.arch=arm64 rebuild sharp

**Comment by mikhailkoliada** [comment]
@Stanzilla Hello!

`brew install libvips glib` fixes the issue, otherwise I am afraid we are unable to help here, the issue must be reported to the upstream package developers

**Comment by Stanzilla** [comment]
> @Stanzilla Hello!
> 
> `brew install libvips glib` fixes the issue, otherwise I am afraid we are unable to help here, the issue must be reported to the upstream package developers

It did not for me, see https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5366164299/jobs/9735434003

**Comment by erik-bershel** [comment]
@Stanzilla hey!
It was upstream package issue but not a runner issue. Already resolved to the current moment as I see.
