### ISSUE TITLE
Elixir's Dialyzer fails following runner OS version update

### ISSUE THREAD

**Issue by RichDom2185** [actions/runner-images#7781]
### Description

Referring to the following two workflows, ran from the same commit:

* https://github.com/source-academy/backend/actions/runs/5334986654/jobs/9667558259
* https://github.com/source-academy/backend/actions/runs/5334986654/jobs/9741437806

The first workflow was ran on Ubuntu 20.04 version `20230611.1`, while the second was run on version `20230619.1.0`.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[`20230619.1.0`](https://github.com/source-academy/backend/actions/runs/5334986654/jobs/9741437806)

### Is it regression?

Yes, [`20230611.1`](https://github.com/source-academy/backend/actions/runs/5334986654/jobs/9667558259) works fine

### Expected behavior

Build passess

### Actual behavior

Build fails with the following error:

```
:dialyzer.run error: File not found: /home/runner/work/_temp/.setup-beam/otp/lib/dialyzer-5.0.5/ebin/erl_bif_types.beam
```

### Repro steps

1. Fork https://github.com/source-academy/backend
2. Run the CI workflow in the repository

**Edit 1:** Fixed typo and broken link

**Comment by erik-bershel** [comment]
Hello @RichDom2185! I'll take a look at the issue, thx for the repro.

**Comment by RichDom2185** [comment]
> Hi, @RichDom2185. I found [this discussion](https://github.com/erlef/setup-beam/issues/214) and I think it may be related to your problem. I would try cleaning cache as it suggested there. Please, let us know whether it helps or not.

Hi @vpolikarpov-akvelon, thanks for the suggestion! We tried clearing all our caches and it does indeed work now.

Apologies, this was something we missed during our internal checks. We had noted that the last commit of the action we used, [`erlef/setup-beam`](https://github.com/erlef/setup-beam), was actually committed before both workflow runs (but had overlooked the fact that the GitHub release for the new version itself was only published in-between), so we had eliminated the possibility that this error was due to the action early on, which should not have been the case.

Thank you once again! I will proceed to close this issue. Please feel free to reopen should you or your team discover anything else worth reopening 😄
