### ISSUE TITLE
.net build fails on windows-latest 20230620 but works on 20230612

### ISSUE THREAD

**Issue by ShadowXVII** [actions/runner-images#7782]
### Description

I've a project which has suddenly stopped building when deployed to a Azure DevOps Hosted Build Agent with version 20230620 of the image. 

The changes in this image are listed here: https://github.com/actions/runner-images/releases/tag/win22%2F20230620.1

```
2023-06-26T03:54:24.3217964Z (ResolveRuntimePackAssets target) -> 
2023-06-26T03:54:24.3219208Z   C:\hostedtoolcache\windows\dotnet\sdk\6.0.411\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(430,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'. [D:\a\1\s\proj\proj.csproj]
2023-06-26T03:54:24.3220136Z   C:\hostedtoolcache\windows\dotnet\sdk\6.0.411\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(430,5): error NETSDK1112: The runtime pack for Microsoft.WindowsDesktop.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'. [D:\a\1\s\proj\proj.csproj]
2023-06-26T03:54:24.3220371Z 
```

I had originally thought it was a bug with the .net SDK but it was just the older version was running on a different host. Multiple runs see a correlation between the Windows image version and failure/success.

https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1112

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Agent name: 'Hosted Agent'
Current agent version: '3.220.2'
Operating System: Microsoft Windows Server 2022 10.0.20348 Datacenter
Runner Image Image: windows-2022
Version: 20230508.3
Included Software: https://github.com/actions/runner-images/blob/win22/20230508.3/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230508.3

### Is it regression?

20230612

### Expected behavior

No error.

### Actual behavior

```
2023-06-26T03:54:24.3217964Z (ResolveRuntimePackAssets target) -> 
2023-06-26T03:54:24.3219208Z   C:\hostedtoolcache\windows\dotnet\sdk\6.0.411\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(430,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'. [D:\a\1\s\proj\proj.csproj]
2023-06-26T03:54:24.3220136Z   C:\hostedtoolcache\windows\dotnet\sdk\6.0.411\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(430,5): error NETSDK1112: The runtime pack for Microsoft.WindowsDesktop.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'. [D:\a\1\s\proj\proj.csproj]
2023-06-26T03:54:24.3220371Z 
```

### Repro steps

1. dotnet restore
2. msbuild

**Comment by ShadowXVII** [comment]
Okay, so it's actually both issues at play. 20230620.1.0 has .NET core SDK v6.0.411 which causes the build to fail.

I can get it to succeed if both the OS image is 20230612.1.0 and the .NET Core SDK version is v6.0.408. I'm unsure who's the cause here. I'll try create a demo project.

**Comment by ilia-shipitsin** [comment]
hello, @ShadowXVII ,

as a workaround you can install certain .net core by using the following task https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines

**Comment by ShadowXVII** [comment]
@ilia-shipitsin , That's what I did, however it still fails if runs on the newer image. I need to use the older image and have it forced to the older version. I'm playing around with a test project to see if I can discovery any more.

**Comment by ilia-shipitsin** [comment]
I'd suggest adding `/bl` switch to msbuild, it enables so called "binary log" named `msbuild.binlog`, which can be viewed by https://msbuildlog.com/

(I suspect that msbuild picks wrong SDK)

**Comment by ShadowXVII** [comment]
It seems to be using 6.0.408... It's only failing when using the 20230620 image...

20230620 Image
![image](https://github.com/actions/runner-images/assets/446329/6613e996-a941-4c34-90c8-440eab74ca62)

20230612 Image
![image](https://github.com/actions/runner-images/assets/446329/b50534cd-3636-40c0-a007-358682181e2c)

**Comment by ilia-shipitsin** [comment]
it might be breaking change in msbuild [behaviour](https://stackoverflow.com/questions/52182158/vs-15-8-2-broke-build-tools-missing-runtimeidentifier)

**Comment by ilia-shipitsin** [comment]
"obj" is not persissted (unless commited in repo). 
is `<RuntimeIdentifier>` specified in project ?

**Comment by ShadowXVII** [comment]
No, just 
		`<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>`

**Comment by ilia-shipitsin** [comment]
a naive guess would be to try `win-x64` (no idea what's wrong with `win10-x64`)

`The runtime pack for Microsoft.NETCore.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'`

**Comment by ShadowXVII** [comment]
Tried that, but no luck :(

**Comment by ilia-shipitsin** [comment]
I ran out of ideas. 

maybe we can find something if you provide minimal repro

**Comment by mikhailkoliada** [comment]
@ShadowXVII Hello! As we have not had repro we could work on to reproduce the problem, I am going to close the issue. Feel free to re-open and reach us out again if you have something new to add.

**Comment by ShadowXVII** [comment]
Hi @mikhailkoliada , @ilia-shipitsin , I've created a new repo here with a code sample: https://github.com/ShadowXVII/WapProjCompile

**Comment by ilia-shipitsin** [comment]
I was able to build locally, also I cannot build in ADO. Thank you for repro.

**Comment by ilia-shipitsin** [comment]
meanwhile, I added restore step suggested by dotnet, build became green 

https://github.com/ilia-shipitsin/WapProjCompile/commit/f032610c94c773b2fbc576cc789af76ac803e4ff

I'll try to figure out why (locally) it works without that restore step.

**Comment by ShadowXVII** [comment]
Oh right, I naively thought the DotNetCoreCli `restore` was the "equivalent" though I guess dotnet build doesn't work.

**Comment by ilia-shipitsin** [comment]
`dotnet restore` under the hood uses `msbuild restore`, it also sets properties (including `RuntimeIdentifier`), I suspect that something in ADO makes it set RuntimeIdentifier in different way

**Comment by ShadowXVII** [comment]
Ahk. That's interesting. I ran into the same problem originally with `dotnet build` vs. `vsbuild` also -- I think because of the WAP project. Not sure if there's similar subtle differences there.

**Comment by ilia-shipitsin** [comment]
I tend to think that `dotnet restore` is only supposed to restore SDK style project, WAP is not SDK style.
why it worked before, most probably image was shipped with proper [Microsoft.NETCore.App.Runtime](https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.win-x64) version, but I see only 6.0.408 for "working" image. Also, we do not install `Microsoft.NETCore.App.Runtime` explicitly , this package is marked `Internal implementation package`. 

I beleive that proper approach will be use "msbuild restore" and not depend on presence of that package.

**Comment by ilia-shipitsin** [comment]
@ShadowXVII , I'm going to close this issue

**Comment by ilia-shipitsin** [comment]
I'm closing this issue. Feel free to reopen if the problem still exists. Thank you.
