### ISSUE TITLE
Update/Add [Heads-up] Please be aware that we are desiring to add SSIS extension to Microsoft-2022 agent when the test is done

### ISSUE THREAD

**Issue by MSraye** [actions/runner-images#7796]
### Tool name

SSIS

### Tool license

VS license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

This is a heads-up that we are going to onboard SSIS to Microsoft-2022 agent when the test is done.

We'd like to know how long it'll take to onboard the extension.

### URL for tool's homepage

https://marketplace.visualstudio.com/items?itemName=SSIS.MicrosoftDataToolsIntegrationServices

### Provide a basic test case to validate the tool's functionality.

```bash
the same as SSIS for VS2019
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by MSraye** [comment]
Now the test is done. And I think we can start the train for installing SSIS extension to VS2022 for that image. Anyone can help us on this?

**Comment by ilia-shipitsin** [comment]
@MSraye , I'll try adding that extension

**Comment by ilia-shipitsin** [comment]
changes are merged. hopefully, next week new image will be delivered

**Comment by mikhailkoliada** [comment]
Deployed
