### ISSUE TITLE
Incorrect behavior of git log inside a runner

### ISSUE THREAD

**Issue by lord-alfred** [actions/runner-images#7807]
### Description

I have a workflow in which new files are added to the repository. To set the username and email for the commit - I get them from the first commit in the repository:
```shell
# Get name & email from 1st commit
git config --local user.email "$(git log --format='%ae' --reverse | head -1)"
git config --local user.name "$(git log --format='%an' --reverse | head -1)"
```

But as it turns out - it doesn't work correctly inside the runner. For some reason it always returns the **last** commit, not the **first**. I checked this script locally with the same calls - everything is fine, but not in runner.

Whether it was always like this, I don't know. Maybe it's some kind of regression.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

unknown

### Expected behavior

The command should return the **first** commit in the repository inside runner:

```shell
$ git log --reverse | head -5

commit 4171caaa79021c9f29138b6f5c0b8cf63e811357
Author: Lord Alfred <2259979+lord-alfred@users.noreply.github.com>
Date:   Thu Jul 29 13:21:39 2021 +0300

    Initial commit
```

### Actual behavior

The command returns the **last** commit (see action log below):
```shell
$ git log --reverse | head -5

commit 9eca7976532f6f15bcb4b26db27e9129393605ac
Author: Lord Alfred <2259979+lord-alfred@users.noreply.github.com>
Date:   Mon Jun 26 14:40:42 2023 +0300

    Add debug to update workflow [v2]
```

### Repro steps

- repo: https://github.com/lord-alfred/ipranges
- workflow: https://github.com/lord-alfred/ipranges/blob/main/.github/workflows/update.yml#L85-L113
- last runned action log: https://github.com/lord-alfred/ipranges/actions/runs/5380652775/jobs/9763677315

**Comment by vpolikarpov-akvelon** [comment]
Hey @lord-alfred. I think it may be related to [fetch depth](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches). By default checkout action fetches only the latest commit. Try setting fetch depth to zero:
```yaml
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

**Comment by erik-bershel** [comment]
Hey @lord-alfred!
It's related to how actions/checkout@v3 works but not the runners.
Example works fine:
```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run git
        run: git log --reverse | head -5
``` 
<img width="1060" alt="Screenshot 2023-06-29 at 10 27 20" src="https://github.com/actions/runner-images/assets/110455084/3e3061dd-fcfb-4b0c-8c75-786e5c4060e1">

**Comment by lord-alfred** [comment]
Thank you so much! `fetch-depth: 0` works as it is needed
