### ISSUE TITLE
Update/Add alpine:3.18

### ISSUE THREAD

**Issue by Kielek** [actions/runner-images#7809]
### Tool name

alpine:3.18

### Tool license

https://pkgs.alpinelinux.org/packages

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.18

### URL for tool's homepage

https://alpinelinux.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by erik-bershel** [comment]
Hello @Kielek!
I'll add it soon.

**Comment by erik-bershel** [comment]
Image rollout of Ubuntu images for the Standard Runners done.
