### ISSUE TITLE
Links in "Runner image" section of "Set up job" step are broken

### ISSUE THREAD

**Issue by allanlewis** [actions/runner-images#7814]
### Description

The "Runner image" section of the "Set up job" step contains two links, one to "included software" and another to "image release", both of which are broken. Here's the content of that section from a recent workflow run in one of my repos:

```
  Image: ubuntu-22.04
  Version: 20230625.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230625.1.0/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230625.1.0
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
20230625.1.0
```

### Is it regression?

Unclear

### Expected behavior

The links should work and point to the file listing the included software for a given build and the release notes, respectively.

### Actual behavior

The links are both broken.

### Repro steps

* Run any workflow.
* Check the "Runner image" section of the "Set up job" step.

**Comment by erik-bershel** [comment]
Hey @allanlewis!
It's known bug. Fix is in progress.

**Comment by shamil-mubarakshin** [comment]
Rollout has been completed. Fix should be available

**Comment by erik-bershel** [comment]
@allanlewis sure.
https://github.com/actions/runner-images/pull/7790
