### ISSUE TITLE
Access to the Screen Recording API

### ISSUE THREAD

**Issue by Aleksey28** [actions/runner-images#7818]
### Description

I try to run tests via TestCafe on `macos-latest` image. To open browsers TestCafe uses [testcafe-browser-tools](https://github.com/DevExpress/testcafe-browser-tools). But [testcafe-browser-tools](https://github.com/DevExpress/testcafe-browser-tools) needs access to the Screen Recording API.

Without this access pop-up with an access request appears and an error is thrown.

https://github.com/actions/runner-images/assets/32869530/c6104bfb-437f-4948-b481-6fda4d256c94

To resolve this issue I edit `$HOME/Library/Application Support/com.apple.TCC/TCC.db` and `/Library/Application Support/com.apple.TCC/TCC.db` with these commands:
```zsh
sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceScreenCapture','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'UNUSED',NULL,0,1687952810);"
```

But when I try to edit `/Library/Application Support/com.apple.TCC/TCC.db` I get an error:
```cli
Error: stepping, attempt to write a readonly database (8)
Error: Process completed with exit code 8.
```

@erik-bershel and I figured out that it happens only in macos-12 (macos-latest) and earlier versions. It works fine in macos-13. (https://github.com/actions/runner-images/discussions/7792)

Since `macos-13` is beta, please, add the possibility to change the `/Library/Application Support/com.apple.TCC/TCC.db` in the `macos-latest` or add this row:
```
'kTCCServiceScreenCapture','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'UNUSED',NULL,0,1687952810
```
to the `/Library/Application Support/com.apple.TCC/TCC.db` in the `macos-latest`.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: macos-12
  Version: 20230623.2

### Is it regression?

no

### Expected behavior

Permission for Screen Recording should be added for the app `com.devexpress.testcafe-browser-tools`

### Actual behavior

`com.devexpress.testcafe-browser-tools` doesn't have permission for Screen Recording

### Repro steps

Repo: https://github.com/Aleksey28/testcafe-macos-safari-tests/actions/runs/5412183948/jobs/9835943686
1. Clone repor
2. Run workflow `main`

**Comment by erik-bershel** [comment]
Hi again @Aleksey28!
Just in case, I will test the required changes again on the macOS 11/12 runners - macOS 13 works a little differently. We can then add the permission to the assembly.

**Comment by erik-bershel** [comment]
@Aleksey28 all the images deployed. Enjoy tests.

**Comment by Aleksey28** [comment]
Hi @erik-bershel,

Thank you for your work, I really appreciate what you do. I've tried the latest release. but it still requires access.

It works on `macos-13` after executing these commands:
```bash
sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceScreenCapture','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'UNUSED',NULL,0,1687952810);"
```

But when I try to execute a test on `macos-12` by executing only the command:
```bash
sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
```
it fails and says that there is no access to the Screen Recording API.

My repo with two workflows on different `macos-latest` and `macos-13`: https://github.com/Aleksey28/testcafe-macos-safari-tests.

I checked your changes. Perhaps, it is needed also to set this permission:
```bash
'kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810
```
to [userValuesArray](https://github.com/erik-bershel/runner-images/blob/18b3ecbf29a27a923664483c4bcf707d66d20fe4/images/macos/provision/configuration/configure-tccdb-macos.sh#L37C1-L37C16). Maybe it doesn't work because of one permission integrated into the image, but another one set from workflow. But it's weird.

**Comment by Aleksey28** [comment]
Hi again @erik-bershel,

Should I create a new issue?

**Comment by erik-bershel** [comment]
Hi @Aleksey28! Nope, I got your signal. Give me please couple days for checking.

**Comment by erik-bershel** [comment]
@Aleksey28 latest security update changed game rules again. I'll work on it on weekend - lets see what I can do.
