### ISSUE TITLE
[Ubuntu] Alpine 3.14 & 3.15 docker image will be removed on July, 24

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#7824]
### Breaking changes

We are going to remove alpine:3.14 and alpine:3.15 docker image from the list of pre-cached images on VM.

### Target date

Image deployment will start July, 24 and will take 3-4 days.

### The motivation for the changes

According to our [Software and images support policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) we support not more than 3 latest LTS versions of images.

### Possible impact

If your pipelines depend on any of these images they may become slower due to time needed to download images in runtime.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Nothing is required — if there is no local image docker will pull it automatically from the docker hub.

**Comment by mikhailkoliada** [comment]
rolled out

**Comment by hontongwanchana** [comment]
node-version: 1[6](https://github.com/adoptium/adoptium-support/actions/runs/5661843352/job/15340581346#step:2:6)
    always-auth: false
    check-latest: false
    token: ***
