### ISSUE TITLE
XCode 14.3 with macos-latest in Azure DevOps Pipeline Microsoft Hosted Agent

### ISSUE THREAD

**Issue by lomeshnparmar** [actions/runner-images#7825]
### Tool name

Azure DevOps Pipeline Microsoft Hosted MacOS Agent

### Tool license

MacOS Latest

### Add or update?

- [X] Add
- [x] Update

### Desired version

XCode 14.3

### Brief description of tool

We Require XCode 14.3 with macos-latest in microsoft hosted agent, as we're having dependency on MAUI iOS Application Code and getting error due to that. Current default XCode is 14.2 only and not able to upgrade even using command as well.
Requirement : XCode 14.3 with macos-latest 

**Error in MAUI iOS Build Pipeline : This version of Microsoft.iOS requires the iOS 16.4 SDK (shipped with Xcode 14.3).**

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @lomeshnparmar, macOS 13 agent with Xcode 14.3 on board is available. See doc [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#:~:text=macOS%2D13-,macOS%2D13,-Link). List of software [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md).
Migration of the "latest" label from macOS 12 to macOS 13 is not happening now, if that's what you're asking. We will notify the community separately about such changes.
