### ISSUE TITLE
Edge browser unexpected update at job start

### ISSUE THREAD

**Issue by klensy** [actions/runner-images#7827]
### Description

While investigating slow parts of Windows builder, found in etw log that Edge started unexpected update somewhere at job start:
`"C:\Program Files (x86)\Microsoft\EdgeUpdate\Install\{C91A863F-217D-4FB4-A288-E44F2C548C74}\EDGEMITMP_96F2C.tmp\setup.exe" --install-archive="C:\Program Files (x86)\Microsoft\EdgeUpdate\Install\{C91A863F-217D-4FB4-A288-E44F2C548C74}\MicrosoftEdge_X64_114.0.1823.58_114.0.1823.43.exe" --previous-version="114.0.1823.43" --msedge --verbose-logging --do-not-launch-msedge --system-level --channel=stable`, consuming resources.

I assume that Windows Server 2022, other platforms and newer version of images affected too, but didn't checked.

I see that autoupdate was disabled in macos runners: https://github.com/actions/runner-images/blob/9f98ea446189a947c8a13ac29ef7fb9003ba7821/images/macos/provision/core/edge.sh#L38-L39

Is linux images affected too?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230612.1
https://github.com/rust-lang/rust/actions/runs/5360795506/jobs/9726098048

### Is it regression?

no?

### Expected behavior

No auto Edge update at job start, as it updated with runner image new version release.

### Actual behavior

Running EdgeUpdate, downloading (and installing?) update at job start.

### Repro steps

1. Start windows 2019 image with outdated Edge version
2. Catch running process\services list, by using etw or any other monitoring app.

Catching running EdgeUpdate can be tricky, as i didn't consistently found it in next few runs, probably it completed too fast or didn't run by some other reason.

**Comment by erik-bershel** [comment]
Hey @klensy! We'll take a look.

**Comment by klensy** [comment]
Hi, so things from https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies can't be used?

**Comment by shamil-mubarakshin** [comment]
That's right. Registry changes are ignored with:
`Update policies are configured but will be ignored because this device isn't domain joined.`

**Comment by klensy** [comment]
Thanks. In which image versions should fix arrive?

**Comment by shamil-mubarakshin** [comment]
In `20230710.1`.
You can find more info in release notes for [Ubuntu20](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230710.1) and [Ubuntu22 ](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230710.1)

**Comment by klensy** [comment]
But this windows only change.

**Comment by shamil-mubarakshin** [comment]
Apologies for the mix up.
Rollout with fixed edge auto-update hasn't started yet. Image version will be known next week

**Comment by mikhailkoliada** [comment]
Should be rolled out now

**Comment by klensy** [comment]
> Should be rolled out now

Thanks! From which version this should be applied, 20230716.1.1?
