### ISSUE TITLE
"brew update" on MacOS 13 fails with an error: error: https://github.com/Homebrew/homebrew-cask did not send all necessary objects

### ISSUE THREAD

**Issue by lsh123** [actions/runner-images#7855]
### Description

MacOSX 13 builds fail (e.g. https://github.com/lsh123/xmlsec/actions/runs/5458349250):

```
Run brew update
error: Could not read ffac597fdb6ce8236b5e2da77ab6fbae3d9d9cb7
fatal: revision walk setup failed
error: https://github.com/Homebrew/homebrew-cask did not send all necessary objects

error: Could not read 623226b77a148708197a10c0d1eab3f8d6ca005b
fatal: revision walk setup failed
error: https://github.com/Homebrew/homebrew-core did not send all necessary objects

Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!
```

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/lsh123/xmlsec/actions/runs/5458349250

```
Current runner version: '2.305.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:ee0669bd1cc54295c223e0bb666b733df41de1c5)
Complete job name: check-osx
```

### Is it regression?

It worked on same version last week (https://github.com/lsh123/xmlsec/actions/runs/5384482840/jobs/9772463248)

### Expected behavior

Builds work

### Actual behavior

Builds fail (see details above)

### Repro steps

See https://github.com/lsh123/xmlsec/actions/runs/5458349250

**Comment by shamil-mubarakshin** [comment]
Hello @lsh123,
The seems to be an issue when cloning `homebrew-cask`. You can track in https://github.com/Homebrew/homebrew-cask/issues/150323, which also provides workaround options. E.g. adding following action allowed `brew update` to complete:
```
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
```

I will close the issue for now. Feel free to reopen in case of any
