### ISSUE TITLE
Update Docker Compose

### ISSUE THREAD

**Issue by clementai** [actions/runner-images#7857]
### Tool name

Docker Compose

### Tool license

Apache

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.19.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by clementai** [comment]
There is a bug on Docker Compose 2.19.0 that prevent to start containers attached to multiple networks, also the default for context has been removed. (https://github.com/docker/compose/issues/10668)
All that is supposed to be fixed in the next release https://github.com/docker/compose/releases/tag/v2.19.1

**Comment by shamil-mubarakshin** [comment]
Hello @clementai,
Windows release of Docker Compose 2.19.1 is in progress and should be available by the end of the week.
Ubuntu release of Docker Compose 2.19.1 is pending for package to become available and, unfortunately, there is no exact eta.

**Comment by clementai** [comment]
@shamil-mubarakshin Is it possible to revert to the last version that work then? v2.18.1

**Comment by shamil-mubarakshin** [comment]
@clementai, I was able to downgrade compose version to 2.18.1 on runtime and [run](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/5473841895/jobs/9967838365) simple `docker compose` project. Could you check if this helps in your case?
```
  - name: downgrade moby
    run: |
        sudo apt-get update
        sudo apt-get install -y --allow-downgrades moby-compose=2.18.1+azure-ubuntu20.04u2
        systemctl is-active --quiet docker.service || systemctl start docker.service
        systemctl is-enabled --quiet docker.service || systemctl enable docker.service
        sleep 10
        docker info
```

**Comment by clementai** [comment]
@shamil-mubarakshin Thanks it works

**Comment by shamil-mubarakshin** [comment]
Ubuntu image rollout with requested docker compose version is in progress and will take 3-4 days to complete

**Comment by clementai** [comment]
@shamil-mubarakshin Will it go directly to v2.20.0? https://github.com/docker/compose/releases/tag/v2.20.0
Looks like v2.19.1 was buggy too

**Comment by shamil-mubarakshin** [comment]
@clementai, New image will be with v2.19.1 of docker compose.
You can find more info about software changes in release notes for [Ubuntu20](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230710.1) and [Ubuntu22](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230710.1)

**Comment by clementai** [comment]
I'm closing but I will wait for the next version to remove your hotfix. Thanks!
