### ISSUE TITLE
Packer fmt . checks are not part of the CI/hooks

### ISSUE THREAD

**Issue by mbean-epc** [actions/runner-images#7872]
### Description

 `packer fmt .` is not part of the commit/CI process. As a result, format of HCL files are not consistent.

I created a PR that updates the HCLs for the Linux HCL files: https://github.com/actions/runner-images/pull/7871

Automation around this would be preferred. Ex: if running formatter results in changes to an HCL, automatically block merge of PR.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu*

### Is it regression?

No

### Expected behavior

HCL files are properly formatted and never merged in state that fails to meet best practices.

### Actual behavior

Some HCL files snuck in that are not following best practices.

### Repro steps

```
cd images/linux
packer fmt .
```

**Comment by shamil-mubarakshin** [comment]
Hello @mbean-epc,
Thank you for contributing, we will have a look
