### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by parijatn** [actions/runner-images#7881]
### Tool name

mono

### Tool license

6.12.0.188

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
Hello @parijatn, we check out the best way to add mono to macOS 13.

**Comment by Alexey-Ayupov** [comment]
@parijatn, we are already working on adding mono in this https://github.com/actions/runner-images/issues/7635 issue. The current one will be closed as a duplicate.
