### ISSUE TITLE
Update/Add ImgBurn

### ISSUE THREAD

**Issue by Minionguyjpro** [actions/runner-images#7888]
### Tool name

ImgBurn

### Tool license

AGPL-3.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.5.8.20210426

### Brief description of tool

ImgBurn is a lightweight CD / DVD / HD DVD / Blu-ray burning application that everyone should have in their toolkit!

It has several 'Modes', each one for performing a different task:

[Read](https://www.imgburn.com/index.php?act=screenshots#isoread) - Read a disc to an image file
[Build](https://www.imgburn.com/index.php?act=screenshots#isobuild) - Create an image file from files on your computer or network - or you can write the files directly to a disc
[Write](https://www.imgburn.com/index.php?act=screenshots#isowrite) - Write an image file to a disc
[Verify](https://www.imgburn.com/index.php?act=screenshots#isoverify) - Check a disc is 100% readable. Optionally, you can also have ImgBurn compare it against a given image file to ensure the actual data is correct
[Discovery](https://www.imgburn.com/index.php?act=screenshots#discovery) - Put your drive / media to the test! Used in combination with [DVDInfoPro](http://www.dvdinfopro.com/), you can check the quality of the burns your drive is producing

It also has a command line interface, which is handy for GitHub Actions in order to build a disk image including the program files.

### URL for tool's homepage

https://www.imgburn.com/

### Provide a basic test case to validate the tool's functionality.

```bash
name: Create disk image
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
 test:
  runs-on: windows-latest
  steps:
      - name: Create .ISO disk image
        run: '"%PROGRAMFILES(X86)\ImgBurn\ImgBurn.exe /MODE BUILD /BUILDINPUTMODE STANDARD /BUILDOUTPUTMODE IMAGEFILE /SRC "src\ISO\" /DEST "build\app.iso" /FILESYSTEM "ISO9660 + Joliet" /VOLUMELABEL_ISO9660 "App" /VOLUMELABEL_JOLIET "App" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE /NOIMAGEDETAILS'
        shell: cmd
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
name: Install ImgBurn
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
 install:
  runs-on: windows-latest
  steps:
   - name: Install ImgBurn
     run: choco install imgburn -y
```

### Tool installation time in runtime

I think 5-50 seconds

### Are you willing to submit a PR?

Yes, I can do so.

**Comment by Alexey-Ayupov** [comment]
Hello @Minionguyjpro!  We would not like to install the tool due to short installation time and maintenance concerns. Please, install it in runtime by adding an additional step in your pipeline. I am closing this issue, but if you have any other questions feel free to ask.
