### ISSUE TITLE
Upversion Azure CLI for bugfix

### ISSUE THREAD

**Issue by michelletaal-shell** [actions/runner-images#7890]
### Description

Azure CLI 2.49.0 introduced a bug around the az keyvault command https://github.com/Azure/azure-cli/issues/26552

This bugfix has been released in Azure CLI 2.50.0

Please update Azure CLI in all runner images to version 2.50.0 as many ADO pipelines word-wide are failing on this bug.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

See examples in https://github.com/Azure/azure-cli/issues/26552

### Is it regression?

No

### Expected behavior

Azure CLI is supposed to list secrets in the keyvault in combination with the --vault-name flag

### Actual behavior

Azure CLI is unable to find the domain when listing secrets in the keyvault when using the --vault-name flag

### Repro steps

1. Run "az keyvault list --vault-name $vault_name"

**Comment by Alexey-Ayupov** [comment]
Hello @michelletaal-shell, the latest version (2.50.0) will be available in our new version of the runner image.

**Comment by michelletaal-shell** [comment]
@Alexey-Ayupov When is the next release scheduled?

**Comment by Alexey-Ayupov** [comment]
@michelletaal-shell, by the end of this week.

**Comment by mikhailkoliada** [comment]
rolled out
