### ISSUE TITLE
brew install llvm@16 broken on macos-latest image

### ISSUE THREAD

**Issue by tcbrindle** [actions/runner-images#7894]
### Description

Previously the command `brew install llvm@16` would correctly install LLVM16 on the macos-latest image.

A  recent update has broken this, as now installation appears to cause a conflict with Python files found in /usr/local

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20230623.2

https://github.com/tcbrindle/flux/actions/runs/5454254313/jobs/10038123300

### Is it regression?

Yes. Last known successful: 20230612.1. Link: https://github.com/tcbrindle/flux/actions/runs/5336761356/jobs/9671902082

### Expected behavior

`brew install llvm@16` should install LLVM 16, as it did before

### Actual behavior

Installation fails. It appears that this is because it's installing Homebrew Python 3.11 as a dependency, which conflicts with Python files already in /usr/local:

```
==> Installing llvm dependency: python@3.11
==> Pouring python@3.11--3.11.4_1.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/2to3-3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3-3.11
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/idle3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3.11
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/pydoc3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3.11
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3-config
/usr/local/bin/python3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
/usr/local/bin/python3.11-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11-config
```

### Repro steps

```
brew update
brew install llvm@16
```

(Possibly `brew install python@3.11` would be enough to trigger the regression)

**Comment by Alexey-Ayupov** [comment]
Hello @tcbrindle, due to our installation script architecture, in the case of a newer version of python@3.11, the command `brew update` brokes the installation process. 
Please install llvm@16 without `brew update` command. The next version of python@3.11 will be available in the new version of the runner image.
I will close the issue. If you have other questions fill free to reach us.
