### ISSUE TITLE
Add ImageMagick to macOS-13

### ISSUE THREAD

**Issue by enoktate** [actions/runner-images#7899]
### Tool name

ImageMagick

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

7.1.1-12 (latest)

### URL for tool's homepage

https://github.com/ImageMagick/ImageMagick

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install imagemagick
```

**Comment by enoktate** [comment]
macOS-11 and macOS-12 images already has ImageMagick installed. ([related issue](https://github.com/actions/runner-images/issues/5371)) 
Realized it is not installed in macOS-13 image when an action failed.

**Comment by mikhailkoliada** [comment]
Hello! We would not like to pre-install imagemagick to the image anymore as it causes maintain concerns. Please install in runtime
