### ISSUE TITLE
Unable to build macOS packages on macOS 11

### ISSUE THREAD

**Issue by LucasXu0** [actions/runner-images#7900]
### Description

The Github action for macOS 11 always got stuck, but it will build successfully when I switch to macOS 12 or macOS 13.

Is there any suggestion to fix this problem?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Runner Image
  Image: macos-11
  Version: 20230623.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-11/20230623.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20230623.1
```

https://github.com/LucasXu0/AppFlowy/actions/runs/5519598038/jobs/10065072146

### Is it regression?

no

### Expected behavior

the packages should be built successfully.

### Actual behavior

the action always stuck on `Building macOS application...`

### Repro steps

1. push a new tag to the repo
2. it will trigger the release action automatically.

```
# lucas.xu @ MacBook-Pro-4 in ~/Desktop/appFlowy on git:main o [22:32:24]
$ git tag 0.2.6

# lucas.xu @ MacBook-Pro-4 in ~/Desktop/appFlowy on git:main o [22:32:28]
$ git push origin 0.2.6
```

**Comment by Alexey-Ayupov** [comment]
Hello @LucasXu0, we will take a look, however, if you can build on macOS 12, please do it. Any way macOS 11 will be deprecated after a certain period of time, so it is better to move your builds in advance.

**Comment by LucasXu0** [comment]
Got it. By the way, when will macOS 11 be deprecated?

**Comment by vpolikarpov-akvelon** [comment]
> When will macOS 11 be deprecated?

According to [the policy](https://github.com/actions/runner-images/tree/main#image-deprecation-policy) image deprecation process will start when new version (it's 13 currently) is out of beta. I can't provide any exact dates though. Deprecation will be announced in advance.

**Comment by LucasXu0** [comment]
We can't use macOS 12 now because our production still supports macOS 10.14. I tried to use macOS 12 to build the package, but it couldn't be installed on macOS 10.14.

**Comment by ilia-shipitsin** [comment]
@LucasXu0 , I forked your repo, I had to comment out some release steps (I haven't figured out yet what was wrong there). Surprisingly, I had successful build. I notice extremely high build time

your repo

![image](https://github.com/actions/runner-images/assets/125650415/e779d8e6-a644-4092-83c1-cb22b1fea885)


[fork ](https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5645764005/job/15292253438)

![image](https://github.com/actions/runner-images/assets/125650415/b9adece6-4e98-4fcf-ae25-052c4712c4b8)


any idea why original build could take 2 hours ? maybe side effect of caching ?

**Comment by LucasXu0** [comment]
@ilia-shipitsin. Normally, this job will succeed within 50 minutes. It took 2 hours because it failed already and got stuck in the Building phase until it timed out.

**Comment by ilia-shipitsin** [comment]
ok, I ran several times.

**Comment by ilia-shipitsin** [comment]
@LucasXu0 , I ran build dozen times, all are green.

https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5657429060/job/15326468954
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5658107154/job/15328681559
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5658615508/job/15330320747
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5659212484/job/15332275818
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5659802148/job/15334138629
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5661404560/job/15339229206
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5662027563/job/15341145905
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5666060243/job/15352035330
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5667249398/job/15355603556
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5670076566/job/15364179071
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5670907205/job/15366858893
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5678407990/job/15388561775
https://github.com/ilia-shipitsin/AppFlowy/actions/runs/5681051334/job/15396377698


what is failure rate in your observations ?

**Comment by LucasXu0** [comment]
Thanks for your try. It seems random. If the task failed once, it will likely fail again in subsequent attempts. Let me close this issue and re-open it if it happens again.
