### ISSUE TITLE
unable to download gmp from github building server(ubuntu 20.04)

### ISSUE THREAD

**Issue by lanewei120** [actions/runner-images#7901]
### Description

try building on ubuntu 20.04 in repo https://github.com/bambulab/BambuStudio
the downloading of GMP will always fail

```
CMake Error at dep_GMP-stamp/download-dep_GMP.cmake:170 (message):
  Each download failed!

    error: downloading 'https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2' failed
          status_code: 28
          status_string: "Timeout was reached"
          log:
          --- LOG BEGIN ---
            Trying 130.242.124.102:443...

  connect to 130.242.124.102 port 443 failed: Connection timed out

  Failed to connect to gmplib.org port 443 after 131501 ms: Couldn't connect
  to server

  Closing connection 0
          --- LOG END ---
```

but  this file https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2 can be downloaded successfully from browser

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
  Version: 20230702.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230702.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230702.1

build link:
https://github.com/bambulab/BambuStudio/actions/runs/5487881208/jobs/10030442148#step:7:16739

last successful build:
 Image: ubuntu-22.04
  Version: 20230517.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230517.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230517.1

https://github.com/bambulab/BambuStudio/actions/runs/5206485499/jobs/9393101873

### Is it regression?

yes,

### Expected behavior

can build successfully

### Actual behavior

build always failed due to downloading of GMP

### Repro steps

steps:
1. submit a pull request to https://github.com/bambulab/BambuStudio
2. check the result in actions

**Comment by Alexey-Ayupov** [comment]
Hello @lanewei120, we will take a look.

**Comment by zhaofengli** [comment]
It appears that the GMP project [has banned](https://www.theregister.com/2023/06/28/microsofts_github_gmp_project/) the GitHub Actions/Azure ranges.

**Comment by vpolikarpov-akvelon** [comment]
Hey @lanewei120. GMP is an open-source project and their servers can't handle huge volume of traffic that GitHub Actions service may generate. This is why they recently restricted GitHub runners to access their site directly. There is nothing we can do about it.

I recommend you to download gmp from some other location, e.g. https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz

**Comment by lanewei120** [comment]
> Hey @lanewei120. GMP is an open-source project and their servers can't handle huge volume of traffic that GitHub Actions service may generate. This is why they recently restricted GitHub runners to access their site directly. There is nothing we can do about it.
> 
> I recommend you to download gmp from some other location, e.g. https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz

ok, thanks for digging into it
I will switch to other place
