### ISSUE TITLE
v1.20.6 is missing from the manifest of go-versions

### ISSUE THREAD

**Issue by earl-warren** [actions/runner-images#7903]
### Description

All in the title

https://github.com/actions/go-versions/blob/main/versions-manifest.json only has v1.20.5

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

-

### Expected behavior

v1.20.6 is found

### Actual behavior

v1.20.5 is found

### Repro steps

setup-go >= v1.20 will get v1.20.5 instead of v1.20.6

**Comment by Alexey-Ayupov** [comment]
Hello @earl-warren, the new version was added to the manifest, [PR](https://github.com/actions/go-versions/pull/78).
