### ISSUE TITLE
link error when building openssl 1.1.1k on ubuntu 20.04

### ISSUE THREAD

**Issue by lanewei120** [actions/runner-images#7908]
### Description

when building openssl 1.1.1k on ubuntu 20.04
found following error:

```
2023-07-12T13:54:49.0202351Z /usr/bin/ld: /home/runner/work/BambuStudio/BambuStudio/deps/build/destdir/usr/local/lib/libcrypto.a(dso_dlfcn.o): in function `dlfcn_globallookup':
2023-07-12T13:54:49.0207845Z dso_dlfcn.c:(.text+0x17): undefined reference to `dlopen'
2023-07-12T13:54:49.0210897Z /usr/bin/ld: dso_dlfcn.c:(.text+0x2a): undefined reference to `dlsym'
2023-07-12T13:54:49.0211417Z /usr/bin/ld: dso_dlfcn.c:(.text+0x35): undefined reference to `dlclose'
2023-07-12T13:54:49.0214669Z /usr/bin/ld: /home/runner/work/BambuStudio/BambuStudio/deps/build/destdir/usr/local/lib/libcrypto.a(dso_dlfcn.o): in function `dlfcn_bind_func':
2023-07-12T13:54:49.0215264Z dso_dlfcn.c:(.text+0x1b7): undefined reference to `dlsym'
2023-07-12T13:54:49.0215979Z /usr/bin/ld: dso_dlfcn.c:(.text+0x282): undefined reference to `dlerror'
2023-07-12T13:54:49.0216694Z /usr/bin/ld: /home/runner/work/BambuStudio/BambuStudio/deps/build/destdir/usr/local/lib/libcrypto.a(dso_dlfcn.o): in function `dlfcn_load':
2023-07-12T13:54:49.0217439Z dso_dlfcn.c:(.text+0x2f5): undefined reference to `dlopen'
2023-07-12T13:54:49.0218051Z /usr/bin/ld: dso_dlfcn.c:(.text+0x369): undefined reference to `dlclose'
2023-07-12T13:54:49.0218735Z /usr/bin/ld: dso_dlfcn.c:(.text+0x3a5): undefined reference to `dlerror'
2023-07-12T13:54:49.0219386Z /usr/bin/ld: /home/runner/work/BambuStudio/BambuStudio/deps/build/destdir/usr/local/lib/libcrypto.a(dso_dlfcn.o): in function `dlfcn_pathbyaddr':
2023-07-12T13:54:49.0221202Z dso_dlfcn.c:(.text+0x466): undefined reference to `dladdr'
2023-07-12T13:54:49.0221691Z /usr/bin/ld: dso_dlfcn.c:(.text+0x4d7): undefined reference to `dlerror'
2023-07-12T13:54:49.0222566Z /usr/bin/ld: /home/runner/work/BambuStudio/BambuStudio/deps/build/destdir/usr/local/lib/libcrypto.a(dso_dlfcn.o): in function `dlfcn_unload':
2023-07-12T13:54:49.0223253Z dso_dlfcn.c:(.text+0x6b8): undefined reference to `dlclose'
2023-07-12T13:54:49.0223868Z collect2: error: ld returned 1 exit status
```

it can build successfully on an older version
and it can also build successfully on ubuntu-latest

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
Version: 20230702.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230702.1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230702.1

build link:
https://github.com/bambulab/BambuStudio/actions/runs/5532389251/jobs/10094405175  ([Linux AppImage Build](https://github.com/bambulab/BambuStudio/actions/runs/5532389251/jobs/10094405175#logs)

last successful build:
Image: ubuntu-22.04
Version: 20230517.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230517.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230517.1

https://github.com/bambulab/BambuStudio/actions/runs/5206485499/jobs/9393101873

### Is it regression?

yes

### Expected behavior

can build successfully

### Actual behavior

found link error

### Repro steps

1. download openssl package from https://github.com/openssl/openssl/archive/OpenSSL_1_1_1k.tar.gz
2. extract it under ubuntu 20.04
3. build it as static library use cmake
4. found link error

the cmake building file is included in Bambu Studio's compiling process, the file is like this:

```
include(ProcessorCount)
ProcessorCount(NPROC)

if(DEFINED OPENSSL_ARCH)
    set(_cross_arch ${OPENSSL_ARCH})
endif()

set(_conf_cmd "./config")
set(_cross_comp_prefix_line "")
set(_make_cmd make -j${NPROC})
set(_install_cmd make -j${NPROC} install_sw)
if (CMAKE_CROSSCOMPILING)
    set(_cross_comp_prefix_line "--cross-compile-prefix=${TOOLCHAIN_PREFIX}-"
    set(_cross_arch "linux-aarch64")
endif ()


ExternalProject_Add(dep_OpenSSL
    #EXCLUDE_FROM_ALL ON
    URL "https://github.com/openssl/openssl/archive/OpenSSL_1_1_1k.tar.gz"
    URL_HASH SHA256=b92f9d3d12043c02860e5e602e50a73ed21a69947bcc74d391f41148e9f6aa95
    DOWNLOAD_DIR ${DEP_DOWNLOAD_DIR}/OpenSSL
        CONFIGURE_COMMAND ${_conf_cmd} ${_cross_arch}
        "--openssldir=${DESTDIR}/usr/local"
        "--prefix=${DESTDIR}/usr/local"
        ${_cross_comp_prefix_line}
        no-shared
        no-asm
        no-ssl3-method
        no-dynamic-engine
    BUILD_IN_SOURCE ON
    BUILD_COMMAND ${_make_cmd}
    INSTALL_COMMAND ${_install_cmd}
)

ExternalProject_Add_Step(dep_OpenSSL install_cmake_files
    DEPENDEES install

    COMMAND ${CMAKE_COMMAND} -E copy_directory openssl "${DESTDIR}/usr/local/${CMAKE_INSTALL_LIBDIR}/cmake/openssl"
    WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
)

```

**Comment by Alexey-Ayupov** [comment]
Hello @lanewei120, we will check it.

**Comment by vpolikarpov-akvelon** [comment]
Hey @lanewei120. I found this thread: https://github.com/curl/curl/issues/6902. Looks like the same problem is discussed there. May it help?

**Comment by lanewei120** [comment]
> Hey @lanewei120. I found this thread: [curl/curl#6902](https://github.com/curl/curl/issues/6902). Looks like the same problem is discussed there. May it help?

@vpolikarpov-akvelon 
thanks for the above information

I just use the default building scripts included in the openssl package,
and there are two things need to take care:
1. it can built successfully when using ubuntu-latest
2. it can built successfully on previous ubuntu-20.04

is it possible anything changed on ubuntu-20.04 causing this issue?

**Comment by lanewei120** [comment]
> ### Image version and build link
> Image: ubuntu-20.04 Version: 20230702.1.0 Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230702.1/images/linux/Ubuntu2004-Readme.md Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230702.1
> 
> build link: https://github.com/bambulab/BambuStudio/actions/runs/5532389251/jobs/10094405175 ([Linux AppImage Build](https://github.com/bambulab/BambuStudio/actions/runs/5532389251/jobs/10094405175#logs)
> 
> last successful build: Image: ubuntu-22.04 Version: 20230517.1 Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230517.1/images/linux/Ubuntu2204-Readme.md Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230517.1
> 
> https://github.com/bambulab/BambuStudio/actions/runs/5206485499/jobs/9393101873
> 
> ### Is it regression?
> yes
here is the version information:

Image version and build link
Image: ubuntu-20.04
Version: 20230702.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230702.1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230702.1

build link:
https://github.com/bambulab/BambuStudio/actions/runs/5532389251/jobs/10094405175 ([Linux AppImage Build](https://github.com/bambulab/BambuStudio/actions/runs/5532389251/jobs/10094405175#logs)

last successful build:
Image: ubuntu-22.04
Version: 20230517.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230517.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230517.1

https://github.com/bambulab/BambuStudio/actions/runs/5206485499/jobs/9393101873

**Comment by vpolikarpov-akvelon** [comment]
Well, the links you have provided refer to (1) failed build on Ubuntu 20.04 and (2) successful build on Ubuntu 22.04. In the initial message you wrote that build have been passing on the older version of ubuntu-20.04 runner, but I didn't find such runs. Could you provide a link for successful build on Ubuntu 20.04?

**Comment by lanewei120** [comment]
> Well, the links you have provided refer to (1) failed build on Ubuntu 20.04 and (2) successful build on Ubuntu 22.04. In the initial message you wrote that build have been passing on the older version of ubuntu-20.04 runner, but I didn't find such runs. Could you provide a link for successful build on Ubuntu 20.04?

even on this patch https://github.com/bambulab/BambuStudio/actions/runs/4792578416,
I changed "ubuntu-latest" to "ubuntu 20.04", it still runs on ubuntu 22.04

so you are right, the previous successful builds are also use 22.04
and I can only find a successful build on 22.04 currently
for the logs of older build(for example https://github.com/bambulab/BambuStudio/actions/runs/4415909930/jobs/7739493771) are not there anymore

I will check whether I can do something to fix this issue on our side

thank you very much

**Comment by vpolikarpov-akvelon** [comment]
Thank you for your patience and collaboration. I'm closing this issue, feel free to file a new one if you other questions.
