### ISSUE TITLE
XDG_CONFIG_HOME being incorrectly set via post-generation scripts

### ISSUE THREAD

**Issue by jack1902** [actions/runner-images#7913]
### Description

I'm unsure at what point the `post-generation` scripts are supposed to be ran, so this might be entirely my own fault but i'm using this repo to create images to run my own Azure DevOps Agents so that i have more power behind the build agent for various tasks. This repo seemed like a great starting point to get a "like for like" experience from Microsoft hosted to self-hosted without encountering issues of things not existing.

Having ran the `GenerateResourcesAndImage` to create a VHD, an image was created from the VHD and this image backs the agents.

i'm unsure at what point i should be running this `post-generation` script so that the agent is able to execute properly. Looking at the Azure VM Scale Set approach, it results in a VMSS which spins instances up and the azure devops extension is enabled which results in the azure-devops agent being installed and configured to enable jobs within a relevant pool.

My issue is that the azure-devops extension creates a user `AzDevOps`, and the custom-script extension executes before the agent is installed.

Should i be running the instances with `AzDevOps` as the default user so that when the custom-script extension executes the correct values are populated into the `/etc/environment` settings? (since currently, i'm getting `admin` in `/etc/environment` and the jobs fail as they are running as `AzDevOps` and attempt to populate things in the wrong directories)

I see that `post-generation` was added in this PR to address different issues happening in the past https://github.com/actions/runner-images/pull/3030

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

built using the git tag `tags/ubuntu22/20230702.1`

### Is it regression?

no

### Expected behavior

Agent runs the jobs that worked on the microsoft-hosted pool, using config files as specified by the `XDG_CONFIG_HOME`

### Actual behavior

Job fails as it is attempting to write to the wrong directory (instance default user, not `AzDevOps`)

### Repro steps

1. Create a VHD using the provided packer scripts
2. Create an Image from this VHD
3. Create a Virtual Machine Scale Set with a user such as `admin`
4. Attach the VMSS to an Azure DevOps Pipeline pool
5. Add the `custom-script` extension to run the `post-generation` scripts (again, not sure this is the correct place for the post-generation)
6. Run jobs checking the values of `/etc/environment` and see that it has `admin` within it not `AzDevOps`

**Comment by Alexey-Ayupov** [comment]
Hello @jack1902, thank you for finding a solution for your issue and sharing it with the community. Since post-generation scripts are intended to be run manually, and we cannot predict all cases, we would not like to change anything here.
This issue will be closed. If you have any questions feel free to reach us.
