### ISSUE TITLE
Add Microsoft.Graph.Beta PowerShell Module

### ISSUE THREAD

**Issue by lsuarez5280** [actions/runner-images#7917]
### Tool name

Microsoft.Graph.Beta

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.0.0

### Brief description of tool

With the bifurcation of Graph beta pwsh cmdlets in the 2.0.0 libraries, which are heavily used in Graph automation, it would be helpful to install both packages on the runner image.

This is explained in detail in [the release breaking change documentation](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#profile-support).

### URL for tool's homepage

https://www.powershellgallery.com/packages/Microsoft.Graph.Beta/2.0.0

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

Add a toolset.json configuration entry, similar to [this](https://github.com/actions/runner-images/blob/48a11cfaddc00044ad4af1a9162d872f3d695b47/images/linux/toolsets/toolset-2204.json#L103), e.g.

```
{
    "powershellModules": [
        {"name": "MarkdownPS"},
        {"name": "Microsoft.Graph"},
        {"name": "Microsoft.Graph.Beta"},
        {"name": "Pester"},
        {"name": "PSScriptAnalyzer"}
    ]
}
```

**Comment by Alexey-Ayupov** [comment]
Hello, @lsuarez5280! We would not like to install the Beta versions of any modules due to potential security and performance risks. Please, try to install it runtime by adding an additional step in your pipeline. I am closing this issue, but if you have any other questions feel free to ask.

**Comment by lsuarez5280** [comment]
@Alexey-Ayupov the module is not in beta or pre release. It is a fully supported release. The only thing "beta" about it is the Graph URL it constructs and the API payloads returned.
