### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by androa** [actions/runner-images#7923]
### Tool name

Trivy

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

200MB

### Brief description of tool

Trivy https://github.com/aquasecurity/trivyis a comprehensive and versatile security scanner. Trivy has scanners that look for security issues, and targets where it can find those issues.

### URL for tool's homepage

https://github.com/aquasecurity/trivy

### Provide a basic test case to validate the tool's functionality.

```bash
trivy image python:3.4-alpine
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt-get install wget apt-transport-https gnupg lsb-release
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
sudo apt-get update
sudo apt-get install trivy
```

### Are you willing to submit a PR?

Sure

**Comment by androa** [comment]
It does exist as a docker image and a GitHub Action, but coming in at 200+MB it does add a significant time spent on all our builds.

**Comment by vpolikarpov-akvelon** [comment]
Hi @androa. Thank you for your suggestion, we will consider it. In the meantime you can run trivy in the docker container using `docker run aquasec/trivy`.

**Comment by vpolikarpov-akvelon** [comment]
@mikhailkoliada, could you review this? By the way, it takes 15 - 25 seconds to install trivy from apt repo during build.

**Comment by mikhailkoliada** [comment]
Hello! Given the installation time (23s) we would not like to pre-install the tool into the image, please continue installing in runtime
