### ISSUE TITLE
Unable to load the EventMachine C extension on macos-latest (macos-12)

### ISSUE THREAD

**Issue by adan-babbel** [actions/runner-images#7929]
### Description

Since this change
https://github.com/actions/runner-images/commit/315796c6ee1e81a5c7d46941c0c6786a6d7e06dc#diff-de83d5c5fa69158ec0c3eb7781d321cff841a277a7b393694b3cdbda34df0c9aR8

we have started observing an error in our test execution workflow
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

we were using macos-latest before and started observing this error since 14.07.23

now with macos-13 things are working fine.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20230709.1

Dont have any public link

### Is it regression?

Working fine on 20230611.2, https://github.com/lessonnine/ui-automation.test/actions/runs/5586208810/jobs/10209964277

### Expected behavior

Things were working perfectly fine on

image version: 20230623.2 (macos-latest/macos-12)
https://github.com/lessonnine/ui-automation.test/actions/runs/5574278769/jobs/10182686975

we are expecting the same behaviour now.

### Actual behavior

Currently its failing on macos-latest since the image version was changed

### Repro steps

we are installing eventmachine gem along with other dependencies

```
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
```

and then starting the appium test execution using command
```
rspec ./spec/
```

**Comment by vpolikarpov-akvelon** [comment]
Hey @adan-babbel. We will try to investigate it, but we need more information. Unfortunately, your repository is private so we can't analyze your runs. It may be very useful it you share logs of failed and successful runs.

Could you also check issues in [eventmachine repo](https://github.com/eventmachine/eventmachine/issues)? I suppose you may find some relevant information there.

**Comment by adan-babbel** [comment]
Hey @vpolikarpov-akvelon 
I have found an open thread on eventmachine, where the error is same
https://github.com/eventmachine/eventmachine/issues/960#issuecomment-1059459915
but nothing here is latest. 

I can try the solution mentioned in the thread but everything was working fine for us on macos-latest.

I have attached the logs here, please give it a look if you can find something.
[Failed logs on macos-latest:image-version-20230709.1.txt](https://github.com/actions/runner-images/files/12093738/Failed.logs.on.macos-latest.image-version-20230709.1.txt)
[Successful logs on macos-13:image-Version- 20230611.2.txt](https://github.com/actions/runner-images/files/12093739/Successful.logs.on.macos-13.image-Version-.20230611.2.txt)
[Successful logs on macos-latest:image-Version- 20230623.2.txt](https://github.com/actions/runner-images/files/12093740/Successful.logs.on.macos-latest.image-Version-.20230623.2.txt)

**Comment by kofkgoing** [comment]
working
<img width="866" alt="스크린샷 2023-07-19 오후 8 04 58" src="https://github.com/actions/runner-images/assets/85471652/b24951f3-ace6-4dbe-a309-305a9b9ca220">

not working - failed to generate dSYM
<img width="868" alt="스크린샷 2023-07-19 오후 8 05 07" src="https://github.com/actions/runner-images/assets/85471652/bcd24b22-7680-440b-9bb1-76f0ea1a54af">

**Comment by kofkgoing** [comment]
How can I specify 20230623.2??

**Comment by 2sem** [comment]
How can I specify 20230623.2??
```
jobs:
  deploy:
    runs-on: macos-latest
```

**Comment by vpolikarpov-akvelon** [comment]
Hey @adan-babbel. Looks like error related with Allure.

I noticed a pattern: build fails where homebrew installs Allure version `2.23.0` and succeeds when it's `2.22.*`. And looks like homebrew tends to install previous version of Allure on old runners and the latest one on new. This may explain why your builds fail now on macos-12 but not on macos-13 - the latter is in beta and updates rarely now.

Could you please try to install Allure in your workflow using this formula: https://github.com/Homebrew/homebrew-core/blob/24dad4c048efb08d4683ff4b2bfeef4f70cfc5f9/Formula/allure.rb

**Comment by 2sem** [comment]
it works with macos-13

**Comment by vpolikarpov-akvelon** [comment]
> it works with macos-13

As I already mentioned, it works on `macos-13` because it updates rarely now due to it's beta status so the latest version of macos-13 is `20230611.2` - it was built on June 6th. As it's quite old, it also pulls old version of Allure from Homebrew.

**Comment by vpolikarpov-akvelon** [comment]
Hey @adan-babbel. Did you try installing older version of Allure (https://github.com/actions/runner-images/issues/7929#issuecomment-1642352755)? Does it help in your case?

**Comment by adan-babbel** [comment]
Hi @vpolikarpov-akvelon 
thanks for your response. Apologies for delay, i was ooo.

I am unable to install allure using formula
https://raw.githubusercontent.com/Homebrew/homebrew-core/24dad4c048efb08d4683ff4b2bfeef4f70cfc5f9/Formula/allure.rb

Would be great if you help with the command which would help me to install specific version of allure using homebrew.

command `brew search allure` doesn't show other versions, would have been easier then to install a specific version of allure then.

**Comment by vpolikarpov-akvelon** [comment]
Hey @adan-babbel. You may use something like this to install a specific version of a homebrew formula:
```
PKG_NAME=allure
FORMULA_COMMIT=24dad4c048efb08d4683ff4b2bfeef4f70cfc5f9
FORMULA_URL="https://raw.githubusercontent.com/Homebrew/homebrew-core/${FORMULA_COMMIT}/Formula/${PKG_NAME}.rb"
curl -fsSL "$FORMULA_URL" > $(find $(brew --repository) -name "${PKG_NAME}.rb")
HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_FROM_API=1 brew install "${PKG_NAME}"
```

**Comment by vpolikarpov-akvelon** [comment]
Hey @adan-babbel, any news? Did you succeed downgrading Allure?

**Comment by vpolikarpov-akvelon** [comment]
Well, I'm closing this issue as it doesn't seem related with runner image update. Feel free to reach out if you have other questions.

**Comment by adan-babbel** [comment]
Hey @vpolikarpov-akvelon, sorry we could not prioritise this.. things are working fine for us with macos-13 and we couldn't dig deep. thanks for your support.
