### ISSUE TITLE
Ubuntu 22.04 VHD fails to build due to issue during install of ChromeDriver

### ISSUE THREAD

**Issue by PottsSG** [actions/runner-images#7933]
### Description

On or around July 18, 2023 the latest stable version of Chrome and ChromeDriver changed from major version 114 to major version 115.  As per an announcement on the [ChromeDriver page](https://chromedriver.chromium.org/), the Downloads page only has versions up to 114.

When building a VHD for Ubuntu 22.04 (and possibly other linux vhds), the image creation fails with an error 

````
azure-arm.build_vhd: Downloading chromedriver v<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/LATEST_RELEASE_115.0.5790</Details></Error>...
    azure-arm.build_vhd: Downloading 'https://chromedriver.storage.googleapis.com/<?xml' to 'version='1.0'/encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The'...
    azure-arm.build_vhd: Error — Either HTTP response code for 'https://chromedriver.storage.googleapis.com/<?xml' is wrong - '' or exit code is not 0 - '1'. Waiting 30 seconds before the next attempt, 19 attempts left
````

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [x] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [x] Windows Server 2022

### Image version and build link

Latest from the main branch.
````
Latest commit:
Date: Tue Jul 18 17:47:39 2023 +0200; Commit: 0f7d7a82caa1a89cac0b656cf840ada34caaa37e - [macos] download XCode installer with retries (#7898); Author: ilia-shipitsin <125650415+ilia-shipitsin@users.noreply.github.com>
````

### Is it regression?

No

### Expected behavior

When running `/helpers/GenerateResourcesAndImage.ps1` with `-ImageType ubuntu2204` the image generation process should complete successfully.  Part way through the log the ChromeDriver download succeeds:

````
    azure-arm.build_vhd: Downloading chromedriver v114.0.5735.90...
    azure-arm.build_vhd: Downloading 'https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip' to '/tmp/chromedriver_linux64.zip'...
    azure-arm.build_vhd: Download completed
    azure-arm.build_vhd: CHROMEWEBDRIVER=/usr/local/share/chrome_driver
    azure-arm.build_vhd: Downloading 'https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1134878%2Fchrome-linux.zip?alt=media' to '/tmp/1134878-chromium-linux.zip'...
    azure-arm.build_vhd: Download completed
````

### Actual behavior

Part way through the image generation, azure-arm.build_vhd logs an error and fails after 20 retries of installing the ChromeDriver
````
    azure-arm.build_vhd: Downloading chromedriver v<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/LATEST_RELEASE_115.0.5790</Details></Error>...
    azure-arm.build_vhd: Downloading 'https://chromedriver.storage.googleapis.com/<?xml' to 'version='1.0'/encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The'...
    azure-arm.build_vhd: Error — Either HTTP response code for 'https://chromedriver.storage.googleapis.com/<?xml' is wrong - '' or exit code is not 0 - '1'. Waiting 30 seconds before the next attempt, 19 attempts left
````

### Repro steps

- Run the following steps in a Powershell terminal, or equivalently try to create a VHD image:
````
git clone https://github.com/actions/runner-images.git
Import-Module .\helpers\GenerateResourcesAndImage.ps1
GenerateResourcesAndImage -SubscriptionId {sub-guid} -ResourceGroupName {rg-name} -ImageGenerationRepositoryRoot "$pwd" -ImageType ubuntu2204 -AzureLocation {location}
````
### Alternate repro steps
- In an Ubuntu 20.04 shell, manually run `/images/linux/scripts/installers/google-chrome.sh`
- The same error is shown
`````
Downloading chromedriver v<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/LATEST_RELEASE_</Details></Error>...
````

**Comment by vpolikarpov-akvelon** [comment]
Hi @PottsSG. Thank you for reporting this. We are aware and working on a solution.

**Comment by sjesse** [comment]
I'm sure you are aware but also seeing this on Win2022 and Ubuntu2004

**Comment by rickardk-se** [comment]
Same issue here.

**Comment by Igor-Pchelko** [comment]
I have experience the same issue, it can't find latest chromeDriver on the https://chromedriver.storage.googleapis.com/

And I found release notes on `chrome-for-testing`:
https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries

Looks like they changed the release process and script needs new way to get driver, e.g. https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints

**Comment by mikhailkoliada** [comment]
Should be fixed now
