### ISSUE TITLE
Apple certificates installation issue in mac runners

### ISSUE THREAD

**Issue by nikhilkd1999** [actions/runner-images#7947]
### Description

I am currently setting up the build process of my project on GitHub Actions with a macOS runner (macos-12 / macos-13). As part of the process, I need to install the "Developer ID Application" and "Developer ID Installer" certificates on the runner for codesign purpose.

While doing this I came across [Link to the article 1](https://twocanoes.com/trusting-certificates-in-system-keychain-without-prompting/).

To automate the certificate management, I followed the steps mentioned in this article: [Link to the article 2](https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions). The article provides a solution for trusting certificates in the system keychain without prompting.

However, I encountered an issue while trying to set the custom keychain as the default one in the runner. The following error message is displayed:

```
Will not set default: UID=0 does not own directory /Users/runner
security: SecKeychainSetDefault: Write permissions error.
Error: Process completed with exit code 1.
```

![image](https://github.com/actions/runner-images/assets/66085432/1c8b8543-cbbb-4b73-9f5a-c05d4b4ef5c0)

This error prevents me from proceeding with the workflow, and I'm unable to set the custom keychain as the default one on the runner.

I'm open to any guidance or alternative approaches to successfully install and trust the certificates in the keychain on the macOS runner. 

Thank you!

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://github.com/actions/runner-images/assets/66085432/0a187955-c158-4b5d-931e-173d74d23144)

### Is it regression?

No

### Expected behavior

The certificate addition/installation should be seamless.

### Actual behavior

Not able to add the certificate to keychain.

### Repro steps

https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions

**Comment by nikhilkd1999** [comment]
Hello, @vpolikarpov-akvelon . I appreciate your acknowledgment, and I'm eagerly looking forward to any assistance or solution you can provide. Thank you!

**Comment by erik-bershel** [comment]
Hello @nikhilkd1999! 
I have a question right away – why is `sudo` used in your example? It's not necessary for adding to your keychain; in the provided article, the operation is also performed with regular privileges: 
```
 - name: Codesign executable
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
          security create-keychain -p <your-password> build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p <your-password> build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k <your-password> build.keychain
          /usr/bin/codesign --force -s <identity-id> ./path/to/you/app -v
```
It looks like a root of your issue.

**Comment by nikhilkd1999** [comment]
Hey @erik-bershel,

If I run it without sudo this is what I get :

`Will not set default: file /Users/runner/Library/Keychains/build1.keychain-db is owned by UID=0, but we have UID=501
security: SecKeychainSetDefault: Write permissions error.
Error: Process completed with exit code 1.`

![image](https://github.com/actions/runner-images/assets/66085432/8b5f343b-4a30-421c-bc6f-32a68539b0bb)

**Comment by erik-bershel** [comment]
Sad to see it, @nikhilkd1999 
I'll try to reproduce the issue so. Will be there with the additional info a bit later.

**Comment by ilia-shipitsin** [comment]
@nikhilkd1999 , can you try steps from https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development ?

**Comment by erik-bershel** [comment]
Hi @nikhilkd1999!
I'm going to close this issue due to lack of activity. If you still have questions, then feel free to ask them here. In case of other problems, please open new issues.
