### ISSUE TITLE
Add [v141_xp toolset for vs2022]

### ISSUE THREAD

**Issue by Streamlet** [actions/runner-images#7959]
### Tool name

v141_xp toolset

### Tool license

with Visual Studio

### Add or update?

- [X] Add
- [ ] Update

### Desired version

with Visual Studio

### Brief description of tool

"%ProgramFiles(x86)%\\Microsoft Visual Studio\\Installer\\setup.exe" modify --quiet --productId  Microsoft.VisualStudio.Product.Enterprise --channelId VisualStudio.17.Release --add Microsoft.VisualStudio.Component.WinXP

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

### Tool installation time in runtime

10min

### Are you willing to submit a PR?

Yes

**Comment by sergei-pyshnoi** [comment]
Hello @Streamlet . Due maintenance concerns, we wouldn't add this package to image. Please install it in runtime. I am closing this issue, but if you have additional questions feel free to ask.

**Comment by Streamlet** [comment]
Why? It takes no extra cost to maintain the image with this package.

**Comment by sergei-pyshnoi** [comment]
> Why? It takes no extra cost to maintain the image with this package.

Adding this tool to base image will increase VMs size, build and deploy time.
