### ISSUE TITLE
Add [PyYAML] for python

### ISSUE THREAD

**Issue by Streamlet** [actions/runner-images#7962]
### Tool name

PyYAML

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever

### Brief description of tool

pip install PyYAML

Ubuntu image has installed it already. But Windows and macOS images are not.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

### Tool installation time in runtime

<10s

### Are you willing to submit a PR?

I have the willing but don't know where to add pip packages

**Comment by sergei-pyshnoi** [comment]
Hello @Streamlet . During small installation time, we wouldn't  add this package to image. Please install it in runtime. I am closing this issue, but if you have additional questions feel free to ask.

**Comment by Streamlet** [comment]
But why the package is installed on Windows and macOS images, but not on Linux image?
