### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by MichaelDally** [actions/runner-images#7965]
### Tool name

Chrome/Edge

### Tool license

N/a

### Add or update?

- [ ] Add
- [X] Update

### Desired version

115

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
I was able to install this myself using:


- script: |
    choco upgrade googlechrome -y
  displayName: 'Upgrade Google Chrome'

In the Yaml build pipeline
```

### Tool installation time in runtime

approx 2 minutes

**Comment by sergei-pyshnoi** [comment]
Hello @MichaelDally . Updated Windows images with newer version of Edge/Chrome will be deployed during this week.

**Comment by mikhailkoliada** [comment]
Deployed
