### ISSUE TITLE
No space left on device - Minimized/Slim images request

### ISSUE THREAD

**Issue by Martin-Molinero** [actions/runner-images#7969]
### Description

The default images contain many pre installed tools, at least >13GB that I know off, which seems to be getting bigger with time. When running using a `container` it's very probable all this overhead is not desired/used and actually causes space issues.
It would be nice if there were a minimized version/tag of the runner images which do not contain this space overhead.
The need for this can also be confirmed by the amount of workarounds around.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

N/A

### Expected behavior

Images with no pre installed tools

### Actual behavior

Images with > 13 GB of preinstalled tools

### Repro steps

```
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
```

The job will fail trying to pull the container image, see https://github.com/QuantConnect/Lean/actions/runs/5645968966/job/15292876421

**Comment by mikhailkoliada** [comment]
@Martin-Molinero Hello! We are only providing 14 GB of space as per documentation: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources for container job there is no way to clean up hosted runner space for the container. We are investigating possibility of providing slim images but there is no ETA on this.

For the time being you could switch using Larger Runners as described here: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners

**Comment by mikhailkoliada** [comment]
If you have more questions feel free to reach us out again

**Comment by HinTak** [comment]
> [@Martin-Molinero](https://github.com/Martin-Molinero) Hello! We are only providing 14 GB of space as per documentation: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources for container job there is no way to clean up hosted runner space for the container. We are investigating possibility of providing slim images but there is no ETA on this.
> 
> For the time being you could switch using Larger Runners as described here: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners

I am having problem with this (again) - I am using the ubuntu image purely to run a fedora container  to build rpms, and does not need anything on the base image  except what is needed to run docker. Is it possible to provide that, or fedora images natively?
