### ISSUE TITLE
Functional tests constantly failing after Ubuntu 22.04 image bump.

### ISSUE THREAD

**Issue by gurevichdmitry** [actions/runner-images#7970]
### Description

Since the Ubuntu 22.04 image was upgraded to version `20230716`, our functional tests have been consistently failing.

<img width="1706" alt="Screenshot 2023-07-24 at 19 21 36" src="https://github.com/actions/runner-images/assets/99176494/78e14a09-d308-47eb-8b16-5fb97c7998ed">

The CI process worked flawlessly with the image version 20230710 ([run example](https://github.com/elastic/cloudbeat/actions/runs/5587652618/job/15133194848)).
<img width="1697" alt="Screenshot 2023-07-24 at 19 19 50" src="https://github.com/actions/runner-images/assets/99176494/1002660c-9141-40af-96b2-d72bfad40e20">

We already encountered the same situation with the image update a month ago (previous upgrade started on 02-06-2023). We've used ubuntu-20.04. But the issue solved by moving to the image ubuntu-22.04.

In general, our test workflow begins with the creation of a Kubernetes cluster using the `kind` tool. Once the cluster is ready, we deploy an instance of `Elasticsearch` using `Helm` charts. The deployment of `Elasticsearch` serves as the foundation for our functional tests.

The next step involves deploying Cloudbeat, our product, onto the cluster. Subsequently, we initiate functional tests to validate its functionality. The primary objective of these tests is to verify that the findings generated by Cloudbeat are correctly stored in Elasticsearch.

However, recently, after updating the runner image, we encountered a critical issue. The logs indicate that the Elasticsearch shards are invalid and failing to be created. As a result, all Elasticsearch indexes have become invalid, leading to a "red" status for the Elasticsearch cluster.

More information can be found in the following issue https://github.com/elastic/cloudbeat/issues/1153

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20230716

[CI run example](https://github.com/elastic/cloudbeat/actions/runs/5610575211/job/15281071861?pr=1146)

### Is it regression?

20230710

### Expected behavior

Functional tests are running sucessfully.

### Actual behavior

Functional tests are continuously failing.

### Repro steps

1. Fork [Cloudbeat repo](https://github.com/elastic/cloudbeat/)
2. Disable GitHub workflows:  After forking the repository, disable all GitHub workflows for the forked repository. 
4. Update k8s-ci.yml: In your forked repository, navigate to the .github/workflows directory and open the k8s-ci.yml file. Uncomment the configuration by removing any comments or lines starting with #. Make sure the configuration is correctly set up to trigger the K8s-CI workflow.
5. Create a pull request: Once you are ready, create a pull request (PR) from your forked repository to your fork main branch. This will trigger the Kubernetes CI workflow for your pull request.
6. Investigate k8s run

**Comment by sergei-pyshnoi** [comment]
Hello @gurevichdmitry , we will take a look

**Comment by vpolikarpov-akvelon** [comment]
Hey @gurevichdmitry. Could you try re-running some old successful pipeline on the new runner image? For example, the one [you linked](https://github.com/elastic/cloudbeat/actions/runs/5587652618/job/15133194848). This may help identifying potential cause of the problem.

**Comment by gurevichdmitry** [comment]
Hey @vpolikarpov-akvelon. After re-running the [successful pipeline](https://github.com/elastic/cloudbeat/actions/runs/5587652618/job/15350766758) you mentioned, all tests are now failing. I noticed that the runner image has been updated to version `20230724.1.0`.

**Comment by gurevichdmitry** [comment]
@sergei-pyshnoi, @vpolikarpov-akvelon, we have successfully resolved our issue. It turned out that the new images had less workspace due to various installed tools, as mentioned in [this issue](https://github.com/actions/runner-images/issues/7969). To tackle this problem, we [added](https://github.com/elastic/cloudbeat/pull/1156/files) a new GitHub [action](https://github.com/marketplace/actions/free-disk-space-ubuntu) for workspace cleanup. This action has proven to be effective in resolving our problems, as it now provides sufficient workspace for Elasticsearch. As a result, Elasticsearch can create nodes and shards without any hindrance. You can find an example of a [successful run](https://github.com/elastic/cloudbeat/actions/runs/5667426093/job/15356335916?pr=1139) with the latest changes and the latest image` 2023.07.24.1`.

**Comment by sergei-pyshnoi** [comment]
@gurevichdmitry Glad to hear that. Regarding this I am closing issue,  but if you have additional question feel free to ask.
