### ISSUE TITLE
Add Xcode 15 beta 5

### ISSUE THREAD

**Issue by ForeverQ** [actions/runner-images#7986]
### Tool name

Xcode 15 beta 5

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 15 beta 5

### Approximate size

Around 13 GB with iOS 17 beta and watchOS 10 beta

### Brief description of tool

Xcode IDE

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No.
```

**Comment by ForeverQ** [comment]
Hi, I opened this issue to request an update for the latest version of Xcode beta (currently beta 5) since the system are still on beta 0.

<img width="443" alt="image" src="https://github.com/actions/runner-images/assets/4921232/d2f64cca-3d2c-4ecb-a775-f09e2f7bb1de">

**Comment by ilia-shipitsin** [comment]
XCode-15 beta 3,4,5 has known [bug](https://discuss.circleci.com/t/xcode-15-beta-4-released/48645) with `xcodebuild`

we use xcodebuild to accept license, our build generation fails on those XCode versions.

hopefully, next image will be released with beta 2 (not affected by that bug, but still require some work from our side)

**Comment by ilia-shipitsin** [comment]
@ForeverQ , we deployed new image today (macos-13.5 + xcode-15.0 Beta2), please try

**Comment by gildor7** [comment]
Please to update to beta 5. The beta 2 is subject to a known bug "cfstring constant not pointer aligned on iOS 17" that prevents completing the build:
https://developer.apple.com/forums/thread/731090

**Comment by ilia-shipitsin** [comment]
unfortunately, Beta 3,4,5 are affected by `objc[13795]: Class DTXDecompressionException is implemented in both /System/Library/PrivateFrameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices (0x1ee1048e0) and /Applications/Xcode-15.app/Contents/SharedFrameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices (0x1042bf630). One of the two will be used. Which one is undefined.` mentioned there: https://discuss.circleci.com/t/xcode-15-beta-4-released/48645

**Comment by gildor7** [comment]
Can you confirm that it has been released?

**Comment by ilia-shipitsin** [comment]
it hasn't been released yet (however, an image is prepared and tested).
release timeframe is next week.

**Comment by davdroman** [comment]
> unfortunately, Beta 3,4,5 are affected by `objc[13795]: Class DTXDecompressionException is implemented in both /System/Library/PrivateFrameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices (0x1ee1048e0) and /Applications/Xcode-15.app/Contents/SharedFrameworks/DTXConnectionServices.framework/Versions/A/DTXConnectionServices (0x1042bf630). One of the two will be used. Which one is undefined.` mentioned there: [discuss.circleci.com/t/xcode-15-beta-4-released/48645](https://discuss.circleci.com/t/xcode-15-beta-4-released/48645)

That same post says:

> So far, it seems this does not cause any negative impact other than excessive noise in build outputs, so can be safely ignored.

So you're basically holding up the entire iOS and macOS developer community over a few extra lines of logs. That is not okay.

**Comment by sgade** [comment]
Beta 6 is out, would it be possible to release that instead?

**Comment by ilia-shipitsin** [comment]
> Beta 6 is out, would it be possible to release that instead?

deploy is planned on next week.
most probably it will be Beta 6

**Comment by ilia-shipitsin** [comment]
image definition updated: https://github.com/actions/runner-images/commit/9f81916bc7fdc7170be68a746d7ec1860d5baccb

**Comment by adambuckland** [comment]
Is the deploy for the beta 6 image still anticipated for this week? 😄

**Comment by ilia-shipitsin** [comment]
Beta 6 was just deployed

**Comment by adambuckland** [comment]
Superb, thank you!
