### ISSUE TITLE
Update/Add Windows Server Hybrid Benefit License for Azure

### ISSUE THREAD

**Issue by shapleya** [actions/runner-images#7991]
### Tool name

Windows Server Hybrid Benefit License for Azure

### Tool license

n/a

### Add or update?

- [X] Add
- [ ] Update

### Desired version

n/a

### Approximate size

n/a

### Brief description of tool

Windows Server Hybrid Benefit License for Azure is a built in supported flag for saving money when building VM's in Azure.

It is supported as part of the standard ARM Builder template as "[license_type](https://developer.hashicorp.com/packer/plugins/builders/azure/arm#license_type)"

It would be nice if the option to have this is added into this repo so people using it can benefit from Hybrid Benefit licensing.

### Provide a basic test case to validate the tool's functionality.

```bash
license_type (string) - Specify a license type for the build VM to enable Azure Hybrid Benefit. If not set, Pay-As-You-Go license model (default) will be used. Valid values are:

For Windows:

Windows_Server
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
no installation is required, this is simply a packer template modification
```

### Tool installation time in runtime

0

### Are you willing to submit a PR?

yes

**Comment by sergei-pyshnoi** [comment]
Hello @shapleya. Thanks for your report. We do not have plan to add and support additional parameters to packer templates. Users can add and modify templates by themselves for specific needs. I am closing this issue, but if you have  additional questions feel free to ask.
