### ISSUE TITLE
Android Install Error on ubuntu 2204 images

### ISSUE THREAD

**Issue by samjarrett** [actions/runner-images#8000]
### Description

In the last couple of days, building ubuntu2204 images has started failing with error message:

```
==> build_vhd: Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
==> build_vhd: 	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We build this image ourselves based on runner version `ubuntu22/20230724.1` on both Azure and AWS (AWS has slight modifications of the provided packer template) and both began erroring sometime around July 30.

### Is it regression?

This exact version (`ubuntu22/20230724.1`) previously built without issues

### Expected behavior

The android setup script to pass successfully.

### Actual behavior

Above error

### Repro steps

Run the ubuntu2204 packer script using up-to-date ubuntu on either AWS or Azure's current images

**Comment by samjarrett** [comment]
This seems similar to previous issues #7015, #6989 and #6985.

**Comment by ilia-shipitsin** [comment]
I confirm similar failure in our [nightly builds](https://dev.azure.com/github/runner-images/_dashboards/dashboard/813e1008-b464-4637-ac5a-0279fa13d115)

**Comment by mnr3395** [comment]
We are also facing the issue in ubuntu20.04 OS version. 

```
==> amazon-ebs.shared-services: Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
==> amazon-ebs.shared-services: 	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by vpolikarpov-akvelon** [comment]
Hey @samjarrett, @mnr3395. The issue should be fixed now. Please sync you code with main branch before retrying.

**Comment by jeanhipages** [comment]
@vpolikarpov-akvelon have also been experiencing this issue for the last 2 days.  I tried again right now and got the same error.

<img width="1378" alt="image" src="https://github.com/actions/runner-images/assets/75591707/f9cc4b26-b131-4660-939c-d391c01ad254">

**Comment by samjarrett** [comment]
@vpolikarpov-akvelon working for me now, thank you so much!

**Comment by vpolikarpov-akvelon** [comment]
Hey @jeanhipages. Could you please ensure that you build image using the latest commit from the main branch?

**Comment by vpolikarpov-akvelon** [comment]
@samjarrett, thank you for your feedback. Feel free to reach out again when you have other questions.

**Comment by jeanhipages** [comment]
> Hey @jeanhipages. Could you please ensure that you build image using the latest commit from the main branch?

@vpolikarpov-akvelon we're using github agents not pulling code and building locally.  i've tried ubuntu-latest and ubuntu-22.04 but neither work.  I'm not sure how else to make sure I get an agent with the pinned cmdline-tools version?

**Comment by vpolikarpov-akvelon** [comment]
@jeanhipages, this thread is about image generation problems that have been already resolved. As your issue is different please start a new thread and provide some steps how to reproduce it. We'll be glad to help you if it's in our hands.
