### ISSUE TITLE
Unable to install MySQLCli

### ISSUE THREAD

**Issue by mnieto** [actions/runner-images#8004]
### Description

Executing Install-MysqlCli.ps1, line 
```
    $MysqlVersion = (Invoke-RestMethod -Uri "https://dev.mysql.com/downloads/mysql/${MysqlVersionMajorMinor}.html" |
        Select-String -Pattern "${MysqlVersionMajorMinor}\.\d+").Matches.Value
```

is returning most of the times (a few times is getting the correct response) something like this:

```
             This site https://dev.mysql.com/downloads/mysql/8.0.html  is experiencing technical difficulty. We are
aware of the issue and are working as quick as possible to correct the issue.
```

See full output in the attached file for reference: [mysqlcli_error.txt](https://github.com/actions/runner-images/files/12215042/mysqlcli_error.txt)

That makes the Select-String cmdlet to fail. I managed to solve the problem adding a custom header `Accept=text/html`

```
    $MysqlVersion = (Invoke-RestMethod -Uri "https://dev.mysql.com/downloads/mysql/${MysqlVersionMajorMinor}.html" -Headers @{"Accept"="text/html"} |
        Select-String -Pattern "${MysqlVersionMajorMinor}\.\d+").Matches.Value
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

win22/20230724.1

### Is it regression?

No

### Expected behavior

MySQLCli is installed

### Actual behavior

Getting powershell error during this Install-MySQLCli.ps1 script

```
==> azure-arm: At C:\Windows\Temp\script-64c789b3-6529-7f0a-8e5d-0ab63b6da3b7.ps1:18 char:22
==> azure-arm: + ... lVersion = (Invoke-RestMethod -Uri "https://dev.mysql.com/downloads/m ...
==> azure-arm: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
==> azure-arm:    eption
==> azure-arm:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...

```

### Repro steps

build the image or just executing a couple of times the command 
`Invoke-RestMethod -Uri "https://dev.mysql.com/downloads/mysql/8.0.html"`
from the powershell console

**Comment by ilia-shipitsin** [comment]
thank for the report, we'll have a look

**Comment by mikhailkoliada** [comment]
Should be fixed
