### ISSUE TITLE
Update Maven to 3.9.3 on runners (including Ubuntu)

### ISSUE THREAD

**Issue by tuxji** [actions/runner-images#8015]
### Tool name

Apache Maven

### Tool license

Apache License 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.9.3 or later

### Brief description of tool

As of version 4.0.0, the Eclipse Tycho plugin for Maven requires Maven 3.9.0 or later:

`Error:  Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.1:build-qualifier (default-build-qualifier) on project com.ge.research.jena: The plugin org.eclipse.tycho:tycho-packaging-plugin:4.0.1 requires Maven version 3.9.0 -> [Help 1]`

I know that Maven 3.9.0 [broke](https://github.com/actions/runner-images/issues/7216) some users' CI builds due to removing an outdated and vulnerable `plexus-utils` dependency from the plugin classpath.  I know that GitHub developers [closed](https://github.com/actions/runner-images/issues/7379) a request to update Maven to 3.9.1 for the same reason.  The fix for affected plugin maintainers is to explicitly declare a dependency on `plexus-utils`. The workaround for affected plugin users is to add this dependency to the affected plugin's dependencies until the issue is fixed by the affected plugin maintainer.

Maven was frozen at 3.8.8 in March.  Now it is August, and this Maven 3.8.8 version is blocking some users' CI builds from updating Eclipse Tycho.  Please consider updating Maven to 3.9.3 since affected plugin maintainers and users have had 5 months to fix their `plexus-utils` dependencies and updating Maven will help some users who need Maven 3.9.0 or later.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ilia-shipitsin** [comment]
@tuxji , while we evaluate the impact of update, can you help with justification whether such an update can (or cannot) be done by user himself ?

we are afraid to introduce some breaking change for the majority of users

**Comment by ilia-shipitsin** [comment]
@tuxji you said `The workaround for affected plugin users is to add this dependency to the affected plugin's dependencies until the issue is fixed by the affected plugin maintainer.`

do you know is there any ETA for a fix from plugin maintainer ?

**Comment by tuxji** [comment]
> @tuxji , while we evaluate the impact of update, can you help with justification whether such an update can (or cannot) be done by user himself ?
> 
> we are afraid to introduce some breaking change for the majority of users

I am aware of two ways users can update Maven by themselves.  Neither way is ideal.

1. Call an unverified GitHub action (https://github.com/marketplace/actions/setup-maven) in their GitHub workflow file.  There is currently no verified action (such as setup-java) which will update Maven in a workflow.
2. Install the Apache Maven Wrapper script (https://github.com/apache/maven-wrapper) in their project, configure the desired Maven version, and modify their GitHub workflow to call the wrapper script instead of the `mvn` command.

**Comment by tuxji** [comment]
> @tuxji you said `The workaround for affected plugin users is to add this dependency to the affected plugin's dependencies until the issue is fixed by the affected plugin maintainer.`
> 
> do you know is there any ETA for a fix from plugin maintainer ?

I do not know how many plugins broke in March, how many plugins have been fixed by their maintainers since then, and how many plugins still remain broken 5 months later.  This is the risk that needs to be evaluated by GitHub developers.

**Comment by ilia-shipitsin** [comment]
we tried to update maven two times and every times we drown in feedback "please get it back".
I'm afraid that 3rd time will be like that.

can we stay with possibly non ideal, but working way updating maven directly in workflow ?

**Comment by ilia-shipitsin** [comment]
another idea is to use containers (maybe you already considered that).

https://github.com/ilia-shipitsin/php-matrix/blob/main/.github/workflows/blank.yml#L7-L12

i.e. you can specify any docker image to run on (supported only for linux runners).
there may be docker images with any maven version.

**Comment by tuxji** [comment]
No, I had not known about this third way to update Maven in one's workflow.  Using a Maven container broke my workflow's docker/build-push-action step, but the error message suggested calling docker/setup-buildx-action.  I added that step to my workflow and the next job ran successfully, so using a Maven container can indeed be a solution for some workflows.

I will close my request since the third way was good enough for me.  For the benefit of other users who also want to try the third way, here it is:

```yaml
jobs:
  integration:
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 17 ]
        maven-version: [ 3.9 ]
        os: [ ubuntu-22.04 ]

    runs-on: ${{ matrix.os }}
    container:
      image: maven:${{ matrix.maven-version }}
```

**Comment by ilia-shipitsin** [comment]
@tuxji , if we want to keep it for other users, shall we convert it to discussion ?

**Comment by tuxji** [comment]
Yes, you may convert this issue to a discussion.
