### ISSUE TITLE
New macos-13 release breaks InstallAppleCertificate@V2 task

### ISSUE THREAD

**Issue by Cheesebaron** [actions/runner-images#8017]
### Description

MacOS agents are often used for building iOS Apps, for this you would typically use the Task InstallAppleCertificate@V2, which in the latest version of the macos-13 agents stopped working.

Looking at the list of things that were updated, LibreSSL was replaced with OpenSSL. https://github.com/actions/runner-images/releases/tag/macos-13%2F20230731.2

There is an open issue in with the InstallAppleCertificate Task, which explicitly says that it breaks when OpenSSL is installed: https://github.com/microsoft/azure-pipelines-tasks/issues/18560

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent name: 'Azure Pipelines 3'
Agent machine name: 'Mac-1690898999289'
Current agent version: '3.224.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20230731.2'

### Is it regression?

Yes

### Expected behavior

InstallAppleCertificate task works

### Actual behavior

The Task breaks with:

```
/usr/local/bin/openssl pkcs12 -in /Users/runner/work/_temp/mykey.p12 -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -sha1 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
Error outputting keys and certificates
00077E5CF87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
##[debug]success of first tool:false
Could not read certificate from <stdin>
```

### Repro steps

Add the InstallAppleCertificate@V2 task and install a Apple certificate

**Comment by ilia-shipitsin** [comment]
thank for the report. I'll have a look

**Comment by gildor7** [comment]
This issue is very impactful, all ios builds with Azure DevOps are blocked.

**Comment by Cheesebaron** [comment]
@ilia-shipitsin I cannot share a distribution certificate with you. But usage would be:

```
    - task: InstallAppleCertificate@2
      displayName: 'Install Apple Distribution Certificate'
      inputs:
        certSecureFile: '$(distributionCertName)'
        certPwd: '$(distributionCertKey)'
```

**Comment by gildor7** [comment]
It could be useful: the InstallAppleCertificate Task attempts to use openssl from the path at /usr/local/bin instead of the system openssl binary at /usr/bin

**Comment by TheMakerOleguch** [comment]
Will attach pieces of reports from Appcenter CI
<img width="866" alt="image" src="https://github.com/actions/runner-images/assets/16706446/60f4d133-186f-4055-8b28-14a466740c43">
![image](https://github.com/actions/runner-images/assets/16706446/cc79781a-9553-4a12-8572-0baac99771ca)

**Comment by ilia-shipitsin** [comment]
yes, I think the issue is on `InstallAppleCertificate`, I plan to find a way how to tell it to use proper openssl command line

**Comment by gildor7** [comment]
In the last version, the openssl has changed:
https://github.com/actions/runner-images/pull/8013/files#diff-49d5008075920b3466eff9e2bb3f4a933cca7733524c0153fd761cf9b6fc4fd4R56

**Comment by ilia-shipitsin** [comment]
we do not install neither OpenSSL, nor LibreSSL. I bet it came as a dependency of some other Homebrew package.

I do not have a certificate to play with, but I was able to put libressl before any other implementation in the following way

```
          brew install libressl
          export PATH="/usr/local/opt/libressl/bin:$PATH"
          echo 'export PATH="/usr/local/opt/libressl/bin:$PATH"' >> /Users/runner/.bash_profile

```

can you try it as a workaround?

**Comment by Cheesebaron** [comment]
I guess resolution of OpenSSL happens here: https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/aea571fa9b87ad655280a86530c88b1e9b12790b/common-npm-packages/ios-signing-common/ios-signing-common.ts#L525

**Comment by Cheesebaron** [comment]
> we do not install neither OpenSSL, nor LibreSSL. I bet it came as a dependency of some other Homebrew package.
> 
> I do not have a certificate to play with, but I was able to put libressl before any other implementation in the following way
> 
> ```
>           brew install libressl
>           export PATH="/usr/local/opt/libressl/bin:$PATH"
>           echo 'export PATH="/usr/local/opt/libressl/bin:$PATH"' >> /Users/runner/.bash_profile
> ```
> 
> can you try it as a workaround?

Giving it a spin now

**Comment by ilia-shipitsin** [comment]
> The command most likely needs the `-legacy` or `-provider legacy` to allow it to work: https://stackoverflow.com/questions/72598983/curl-openssl-error-error0308010cdigital-envelope-routinesunsupported

looks like a proper way. however, it will require us few days to test and deploy

**Comment by lxr-mwhite** [comment]
Would it be possible to somehow use the macOS-13 image release that was available before the latest 20230131?

**Comment by codynedved** [comment]
Can we please roll back to previous image so we can continue to build while you figure out if -legacy command will work.

**Comment by jci-cfoxr** [comment]
How does this stuff get released?   This operation would happen on pretty much every iOS build.   Please revert this latest set of changes.

**Comment by denisyakimov07** [comment]
MacOS-12 still works fine; I'm very hopeful they're not going to update it.

**Comment by svaldetero** [comment]
> MacOS-12 still works fine; I'm very hopeful they won't update it.

Except if you are using the latest SDKs it requires Xcode 14.3 which isn't on macos-12. I'd have to pin an older version of dotnet to allow Xcode 14.2 so I could use macos-12. Which puts you in a bad position if there were bug fixes in the later version of dotnet that you were using.

**Comment by wscld** [comment]
looks like adding -legacy to the "OpenSSL arguments for PKCS12" fixes the issue here
`opensslPkcsArgs: '-legacy'`

**Comment by jdbenito** [comment]
@samvantran what are the chances that this image will be deployed out soon?

**Comment by Cheesebaron** [comment]
While waiting for the new image to get deployed. Instead of the InstallAppleCertificate and InstallProvisioningProfile tasks you could do something like I do here: https://gist.github.com/Cheesebaron/a2e8f9c1c62ad3e38fae4b668fc30eed

**Comment by jdbenito** [comment]
Excellent. I'll give this one a whirl. Thanks @Cheesebaron!

**Comment by johnterickson** [comment]
While we work on the image, some teams have had success with this mitigation:
run `brew unlink openssl` after `brew install openssl@3`

**Comment by johnterickson** [comment]
A fix is rolling out over the next few hours: https://github.com/actions/runner-images/pull/8019

**Comment by jdbenito** [comment]
Just as soon as I applied @Cheesebaron's fix, the fix got rolled out and was working in other branches and projects. 🤦🏻‍♂️

This day was a total write off!

**Comment by ilia-shipitsin** [comment]
@Cheesebaron , the following caught my attention `Algorithm (RC2-40-CBC : 0)`

can you provide more details on certificate ? is it RC2-40-CBC ?

those algorithms were indeed disabled in modern OpenSSL-3.X by default (and must be enabled by using "legacy" provider), however, justification on enabling legacy algs by default is not clear.

**Comment by Cheesebaron** [comment]
@ilia-shipitsin this is what I get with:

`openssl pkcs12 -in mykey.p12 -noout -info`:

```
MAC verified OK
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
```

These are issued by Apple FYI.

**Comment by ilia-shipitsin** [comment]
Interesting. Looks like a good justification for enabling "legacy" on Homebrew side

**Comment by Cheesebaron** [comment]
Alternatively there needs to be a step in the process that attempts to convert the cert or some docs about how to convert the certificate to a format that is supported.

**Comment by ilia-shipitsin** [comment]
well, it should have been addressed better.

maybe, some helpful error message on `InstallAppleCertificate@V2` side, like "your certificate is not secure, please do so and so"

**Comment by mikhailkoliada** [comment]
Hello all! 

We apologise for inconvenience caused. Even though the issue is fixed, we would like to remind that macOS-13 is still in the public beta state, therefore, we urge everybody not to use it for the production development yet. We are working on improving the image's stability and will make an additional announcement once macOS 13 is generally available.

Thank you for your patience and understanding!

**Comment by Cheesebaron** [comment]
To be quite frank you probably wouldn't have found out unless we used it for production purposes already. AppCenter thinks that these are fine to use for production purposes as well.

Also keep in mind that some people are forced to use the images because of which versions of Xcode available on macos-12 agents.

**Comment by TedaLIEz** [comment]
Hi, we found the same issue on `macos-15` image, currently we workaround by adding `-legacy` to openssl command. But we hope this gets a fix.

**Comment by Komdosh** [comment]
> Hi, we found the same issue on `macos-15` image, currently we workaround by adding `-legacy` to openssl command. But we hope this gets a fix.

+1

**Comment by brentpi** [comment]
@Komdosh @TedaLIEz 

legacy didnt work for me - I had to convert my certificate exported from Keychain Access using this guide: https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3

Seems to work after that.
