### ISSUE TITLE
Update GHA CI to allow providing runner versions

### ISSUE THREAD

**Issue by disa6302** [actions/runner-images#8027]
### Tool name

Github actions CI

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

N/A

### Brief description of tool

Github actions should provide a way to also specify runner version along with OS. Off late I have been seeing quite a lot of instability across runner versions and users of the CI are left wondering why the build is failing and is required to wait till it is fixed/addressed by the team. Allowing users to set the runner version will help them in reverting to the operational runner version and unblock their CI till the appropriate fixes go in. 

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by szaichenko26** [comment]
I completely agree, our CI just overworked after yesterday's update. Right on release day.

**Comment by reesscot** [comment]
+1, we need the ability to pin a specific runner because the latest version of MacOS running is causing issues.

**Comment by ilia-shipitsin** [comment]
@disa6302 , please provide more details. currently it looks too general.

**Comment by disa6302** [comment]
@ilia-shipitsin , 

Is there a specific detail you are looking for?
To be precise, my request indicates adding a new field in the yaml script, something like `runner-version` to allow users to specific the version. I am looking for something like:

```
  mac-os-build-gcc:
    runs-on: 
        os: macos-13
        runner-version: 3.7.1    
```

The version I am talking about is the one that shows up in the Setup step of the build:

```
Current runner version: '**2.307.1**'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7[2](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/actions/runs/5741154558/job/15560609881?pr=388#step:1:2)51135ab7dc9ce3241c5835cc595a9)
Download action repository 'aws-actions/configure-aws-credentials@v1-node1[6](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/actions/runs/5741154558/job/15560609881?pr=388#step:1:7)' (SHA:023daa7fe5f7f8[17](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/actions/runs/5741154558/job/15560609881?pr=388#step:1:21)faa31fc0fc4a8d0fb6[22](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/actions/runs/5741154558/job/15560609881?pr=388#step:1:26)4ed0)
Complete job name: mac-os-build-gcc
```

**Comment by mikhailkoliada** [comment]
Hello! We currently do not have plans to implement something like that in the near future, regarding macOS 13 we would like to remind everyone that the image is still in public beta, it means it may pose problems time to time.

**Comment by disa6302** [comment]
@mikhailkoliada ,

The builds are unreliable not only in MacOS 13 but other mac versions as well (I have another open ticket item in this repo that is being looked into). Had there been a runner version that could be specified, it would have unblocked me. But now I am blocked on that build running to make it to release. 

Hence the idea. Its alright if its not in the plans right now, but I would appreciate if this is tracked seriously for future because this will be pretty powerful in working around the instability of the runners through updates.
