### ISSUE TITLE
macOS-13 runner runs Fastlane v 2.211.0 despite it's doc says v 2.214.0

### ISSUE THREAD

**Issue by kanstantsin-bucha** [actions/runner-images#8031]
### Description

Yesterday we switched to the macOS-13 image to support upcoming iOS and Xcode versions in the near future.
I read the docs here https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md and found out the Fastlane is supposed to have version 2.214.0
```
* Tools
    *Fastlane 2.214.0
```
When I ran the macos-13 image, I got the Fastlane version 2.211 by default.
```
#######################################################################
# fastlane 2.214.0 is available. You are on 2.211.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
```

That leads to the issues with sending the build to the TestFlight described there:
https://github.com/actions/runner-images/issues/7194

Is there Fastlane version 2.214.0 in the image, and how can I switch to it until the issue will be resolved?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

The link to the failed build https://github.com/umg/oscil8-ios-client/actions/runs/5739611113/job/15560638330

```
Current runner version: '2.307.1'
Operating System
  macOS
  13.5
  22G74
Runner Image
  Image: macos-13
  Version: 20230801.2
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20230801.2/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230801.2
Runner Image Provisioner
  2.0.264.1
```

### Is it regression?

unknown

### Expected behavior

I expected the Fastlane to be 2.214.0

### Actual behavior

the Fastlane is 2.211.0 by default

### Repro steps

The script runs the default Fastlane action: upload_to_testflight
The script fails with the error: [16:16:16]: The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'.
This error is a known issue that was fixed in 2.214.0.

**Comment by ilia-shipitsin** [comment]
thank you for the report. I'll have a look

**Comment by ilia-shipitsin** [comment]
@kanstantsin-bucha , I have playground repo , I added "fastlane --version": https://github.com/ilia-shipitsin/macos13/blob/main/.github/workflows/blank.yml#L31

it shown "2.214.0": https://github.com/ilia-shipitsin/macos13/actions/runs/5749475196/job/15584381607#step:3:272

it is suprizing to see 

```
#######################################################################
# fastlane 2.214.0 is available. You are on 2.211.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
```

can you provide repro steps ? I cannot access your repo, it is private one.

**Comment by kanstantsin-bucha** [comment]
Right, I forked your test repo and try to reproduce the setup we have in the repo that fails the build.
We use `bundle exec fastlane lane` and gem file
I copied the content into the repo and have another failure 
https://github.com/kanstantsin-bucha/macos13/actions/runs/5750383404/job/15587050426

**Comment by ilia-shipitsin** [comment]
in your case it complains on `Could not find gem 'rest-client' in locally installed gems`

it is commented in Gemfile:

https://github.com/kanstantsin-bucha/macos13/blob/main/Gemfile#L4C19-L4C19

**Comment by kanstantsin-bucha** [comment]
@ilia-shipitsin  I found out the we have a gem.lock file with the previous version of the Fastline locked in the repo. Sorry to trouble you
