### ISSUE TITLE
EdgeDriver 115.0.1901.188 fails on Linux

### ISSUE THREAD

**Issue by tkoukkari** [actions/runner-images#8046]
### Description

WebDriverException: Message: unknown error: unrecognized Microsoft Edge version: HeadlessChrome/115.0.5790.110

Works fine with previous version of EdgeDriver 115.0.1901.183 and below.

Also reported in EdgrDriver repo:
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102

Might be best to downgrade the driver on linux until fix is available.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest

### Is it regression?

Yes, worked fine with previous edgedriver version

### Expected behavior

Running automated test with selenium webdriver / Edge on linux should be possible.

### Actual behavior

Browser fails to open. Works fine with previous version of EdgeDriver. 

Note: No issues on other platforms (Mac/Windows).

### Repro steps

Use Webdriver to open Edge on Linux.

**Comment by erik-bershel** [comment]
Hi @tkoukkari! Thank you for reporting this issue. We'll think about what's best to do about it.

**Comment by erik-bershel** [comment]
Hey @tkoukkari,
Unfortunately, Microsoft only provides the latest stable minor version for each major version of the driver. Thus, if we want to downgrade the driver version, we would need to revert to version 114, which would lead to incompatibility with the browser that currently holds version 115. Lowering the browser version isn't the most optimal solution either, as many users would lose the ability to test their products for compatibility with the latest browser version. Considering the above, the decision was made to wait for a bug fix from Microsoft.

**Comment by tkoukkari** [comment]
Ok, thanks for looking into this. Let's hope the next version of EdgeDriver fixes the issue.

**Comment by mikhailkoliada** [comment]
Hello! It looks like workaround is given in the upstream ticket https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1710724173 going to close this specific issue as there is nothing actable for us for the time being, as soon as Microsoft releases a fixed version of the driver it will be a part of the next image update automatically, let us know if there are any more concerns.

**Comment by Prajakta365** [comment]
facing same issue for edge driver version 117.0.2045.35
`ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: unrecognized Microsoft Edge version: HeadlessChrome/117.0.5938.88
ERROR webdriver: unknown error: unknown error: unrecognized Microsoft Edge version: HeadlessChrome/117.0.5938.88`
