### ISSUE TITLE
Update JDK to 18/19

### ISSUE THREAD

**Issue by MarcBuch** [actions/runner-images#8057]
### Tool name

JDK

### Tool license

GNU General Public License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

18, 19

### Brief description of tool

Java 17 is the latest version pre-installed on the runner-images. Please add support for 18 and 19.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello @MarcBuch! As of our pre-installed software [policy](https://github.slack.com/archives/C0G0H3KDK/p1690979287253309), we are pre-installing only all LTS versions, neither 18 nor 18 is the LTS one and can can not be considered for addition.
