### ISSUE TITLE
Add Go version 1.21

### ISSUE THREAD

**Issue by ptman** [actions/runner-images#8059]
### Tool name

Go

### Tool license

https://github.com/golang/go/blob/master/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.21

### Approximate size

140 MB

### Brief description of tool

Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.

### URL for tool's homepage

https://go.dev/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by erik-bershel** [comment]
Hi @ptman! We'll add it ASAP

**Comment by mikhailkoliada** [comment]
Should be available via the setup-go action now

**Comment by barbabbott** [comment]
Thank you
