### ISSUE TITLE
Azure Pipeline Visual Studio Build Fails: Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.7.0.0' of the compiler, which is newer than the currently running version '4.6.0.0'

### ISSUE THREAD

**Issue by schamal2205** [actions/runner-images#8067]
### Description

Since Yesterday our Builds on "Windows Server 2022" Pipelines are failing with the following error message: 
`##[error]CSC(0,0): Error CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.7.0.0' of the compiler, which is newer than the currently running version '4.6.0.0'.`

Yesterday was also the publish of .NET 7.0.10 with SDK 7.0.400 as well as Visual Studio 17.7 which are both missing on the pipeline Agents. 

Is there a timeline for updating the Agents to the newest Versions?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

mage: windows-2022
Version: 20230730.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20230730.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230730.1

### Is it regression?

no

### Expected behavior

Build should not fail. 
On local machines with VS 17.7 and .net 7.0.10 with SDK 7.0.400 build succeeded with no error

### Actual behavior

Build fails because of compiler Version mismatch.

### Repro steps

Create a ASP.NET MCV Web Application with .NET.Razor and run a VS Build in Azure Pipelines

**Comment by erik-bershel** [comment]
Hi @schamal2205!
As per our SLA, updates to existing packages typically occur no later than six business days after a release and/or a previous update. Thus, a new image should be expected around next Thursday, provided that there are no serious problems with it that affect the user experience.

**Comment by erik-bershel** [comment]
@schamal2205 you can try to use Azure Pipelines Task to update .NET SDK until we update the image itself.
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-installer-v1?view=azure-pipelines
But as I see from the thread it might be helpless depending on your project: https://stackoverflow.com/questions/76740942/how-to-fix-the-analyzer-assembly-references-version-4-7-0-0-of-the-compiler

**Comment by schamal2205** [comment]
We now have a workaround to get our build working again. 
The workaround is to set the SDK version to 7.0.306 rather than 7.0.400 (or 7.x for latest), which was released on Wednesday. 
So switch from 
```
- Task: UseDotNet@2
  displayName: 'Use .NET Core sdk 7.x'
  Inputs:
    packageType: 'sdk'
    version: '7.x'
    includePreviewVersions: false
``` 
to 
```
- Task: UseDotNet@2
  displayName: 'Use .NET Core sdk 7.x'
  Inputs:
    packageType: 'sdk'
    version: '7.0.306'
    includePreviewVersions: false
```
got our build working again.

I will report as soon as the 7.x version is working again.

**Comment by erik-bershel** [comment]
@schamal2205 that the point. Latest installed version is 7.0.306. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#net-core-tools
Issue you described here connected with the project config.

**Comment by robertmclaws** [comment]
Any progress on this?

**Comment by mikhailkoliada** [comment]
Should be deployed
