### ISSUE TITLE
Update to VS 17.7 

### ISSUE THREAD

**Issue by LBally** [actions/runner-images#8072]
### Tool name

Visual Studio 2022

### Tool license

Proprietary

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.7

### URL for tool's homepage

https://github.com/xamarin/xamarin-android

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by LBally** [comment]
17.7 includes a critical fix for an android 14 time zone issue.
![image](https://github.com/actions/runner-images/assets/52003288/0e6a87ac-8688-40ce-a840-bd9ca6fd8ea5)

**Comment by erik-bershel** [comment]
Hi @LBally!
We already got request to update VS. #8067 
So I'll close this issue as a duplicate. But thank you for paying attention and reporting critical fix. I may add that new image supposed to be deployed somewhere about next Wednesday or Thursday.

**Comment by LBally** [comment]
I didn't see the other issue, sorry for the duplicate.
And thanks for letting me know a time frame, I appreciate the quick reply.
