### ISSUE TITLE
Build for Ubuntu fails for kubectl

### ISSUE THREAD

**Issue by mariusfilipowski** [actions/runner-images#8094]
### Description

The build fails for the new version of kubectl on Ubuntu. We use it in our self hosted runners.

```
[-] kubectl 255ms (247ms|8ms)
    githubactions-runner.amazon-ebs.githubrunner:    Expected regular expression 'Client Version: version.Info' for 'kubectl version' command to match 'Client Version: v1.28.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 The connection to the server localhost:8080 was refused - did you specify the right host or port?
    githubactions-runner.amazon-ebs.githubrunner:    ', but it did not match.
    githubactions-runner.amazon-ebs.githubrunner:    at "kubectl version" | Should -MatchCommandOutput "Client Version: version.Info", /imagegeneration/tests/Tools.Tests.ps1:287
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Private image build.

### Is it regression?

Private image build.

### Expected behavior

The version output of kubectl has changed. It needs to be adjusted and also the Software report.
Example of new output of `kubectl version`
```
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```  

### Actual behavior

It fails.

Expected regular expression 'Client Version: version.Info' for 'kubectl version' command to match 'Client Version: v1.28.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 The connection to the server localhost:8080 was refused - did you specify the right host or port?
    githubactions-runner.amazon-ebs.githubrunner:    ', but it did not match.
    githubactions-runner.amazon-ebs.githubrunner:    at "kubectl version" | Should -MatchCommandOutput "Client Version: version.Info", /imagegeneration/tests/Tools.Tests.ps1:287

### Repro steps

Just start the build.

**Comment by mikhailkoliada** [comment]
Should be fixed, please sync your main branch.
