### ISSUE TITLE
Add Actionlint

### ISSUE THREAD

**Issue by mariusfilipowski** [actions/runner-images#8097]
### Tool name

actionllint

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

5MB

### Brief description of tool

Linting of GitHub Actions.

### URL for tool's homepage

https://github.com/rhysd/actionlint

### Provide a basic test case to validate the tool's functionality.

```bash
actionlint --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Can be downloaded from GitHub Release page: https://github.com/rhysd/actionlint/releases


source "${HELPER_SCRIPTS}/install.sh"

tmp_actionlint="/tmp/actionlint"
mkdir -p "${tmp_actionlint}"

downloadUrl=$(get_github_package_download_url "rhysd/actionlint" "contains(\"_linux_amd64\")")
download_with_retries "${downloadUrl}" "${tmp_actionlint}"
tar xzf "${tmp_actionlint}"/actionlint_*_linux_amd64.tar.gz -C "${tmp_actionlint}"
mv "${tmp_actionlint}"/actionlint /usr/local/bin

chmod +x /usr/local/bin/actionlint
```
```


### Tool installation time in runtime

_No response_

### Are you willing to submit a PR?

_No response_

**Comment by shamil-mubarakshin** [comment]
Hello @mariusfilipowski, we will take a look
