### ISSUE TITLE
macOS 12 (20230812) Image Update breaks qemu HVF

### ISSUE THREAD

**Issue by tamird** [actions/runner-images#8113]
### Description

We use QEMU with HVF in https://github.com/aya-rs/aya.

Our [last successful run](https://github.com/aya-rs/aya/actions/runs/5892372835/job/15981487929) took place this morning and ran on https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230803.1.

The [first failing run](https://github.com/aya-rs/aya/actions/runs/5892485804/job/15981870216) took place 11 minutes later and ran on https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230812.3.

The two runs are testing the same code; the latter is the merge commit of the PR tested in the former.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

See above.

### Is it regression?

Yes.

### Expected behavior

QEMU with `-accel hvf` works.

### Actual behavior

```
qemu-system-x86_64: -accel hvf: Unknown Error
```

### Repro steps

I don't have a concise repro; https://github.com/aya-rs/aya's CI reproduces reliably.

**Comment by shamil-mubarakshin** [comment]
Hello @tamird, thanks for reporting.
At first glance there is `qemu` updated to `8.0.4` which might cause issues. We will investigate
