### ISSUE TITLE
Update LLVM to latest (v16)

### ISSUE THREAD

**Issue by Tractorou24** [actions/runner-images#8125]
### Tool name

LLVM

### Tool license

Apache License v2.0 with LLVM Exceptions

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16.0.6 (latest release)

### Approximate size

2.5GB (should not be bigger than previous 15.x versions)

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
I think it's already done at build time, yes.
```

### Are you willing to submit a PR?

Sure!

**Comment by Alexey-Ayupov** [comment]
Hi @Tractorou24, we will check the possibility.

**Comment by mikhailkoliada** [comment]
Added, will be deployed next week

**Comment by pdimov** [comment]
This is necessary because the 20230820.1.0 image has an updated Visual Studio 2022 whose STL requires Clang 16.

**Comment by Tractorou24** [comment]
Yes, thank you for the fix!

**Comment by Sainan** [comment]
\> deploys faulty setup
\> fixes issue
\> "will be deployed next week"

love me some billion dollar companies with inefficient internal processes that apparently don't allow mistakes to be undone, nor fixed, so you just have stuff in a broken state until the cogs are done spinning.

**Comment by pdimov** [comment]
Any progress with that deployment? clang-cl jobs continue to fail for this reason.

**Comment by Sainan** [comment]
Just add a `run: choco upgrade llvm` step to your Windows workers, I guess.

**Comment by mikhailkoliada** [comment]
Added to the image!
