### ISSUE TITLE
Building Ubuntu 22.04 tests fail

### ISSUE THREAD

**Issue by sander110419** [actions/runner-images#8128]
### Description

When building the Ubuntu 22.04 image (20230814 Image Update), the image seems to install fine, but it fails on testing:

    azure-arm.build_vhd: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'  
    azure-arm.build_vhd: Describing Kubernetes tools  
    azure-arm.build_vhd:   [+] kind 77ms (51ms|25ms)  
    azure-arm.build_vhd:   [-] kubectl 64ms (62ms|2ms)  
    azure-arm.build_vhd:    Expected regular expression 'Client Version: version.Info' for 'kubectl version' command to match Client Version: v1.28.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 The connection to the server localhost:8080 was refused - did you specify the right host or port?  
    azure-arm.build_vhd:    ', but it did not match.  
    azure-arm.build_vhd:    at "kubectl version" | Should -MatchCommandOutput "Client Version: version.Info",  
    /imagegeneration/tests/Tools.Tests.ps1:287  
    azure-arm.build_vhd:    at <ScriptBlock>, /imagegeneration/tests/Tools.Tests.ps1:287  
    azure-arm.build_vhd:   [+] helm 39ms (38ms|1ms)  
    azure-arm.build_vhd:   [+] minikube 73ms (72ms|1ms)  
    azure-arm.build_vhd:   [+] kustomize 14ms (12ms|2ms)  
    azure-arm.build_vhd: Tests completed in 961ms  
    azure-arm.build_vhd: Tests Passed: 4, Failed: 1, Skipped: 0 NotRun: 93  
    azure-arm.build_vhd:  
    azure-arm.build_vhd: Containers            : {[-] /imagegeneration/tests/Tools.Tests.ps1}  
    azure-arm.build_vhd: Result                : Failed  
    azure-arm.build_vhd: FailedCount           : 1  
    azure-arm.build_vhd: FailedBlocksCount     : 0  
    azure-arm.build_vhd: FailedContainersCount : 0  
    azure-arm.build_vhd: PassedCount           : 4  
    azure-arm.build_vhd: SkippedCount          : 0  
    azure-arm.build_vhd: NotRunCount           : 93  
    azure-arm.build_vhd: TotalCount            : 98  
    azure-arm.build_vhd: Duration              : 00:00:00.9610966  
    azure-arm.build_vhd: Executed              : True  
    azure-arm.build_vhd: ExecutedAt            : 08/21/2023 23:45:20  
    azure-arm.build_vhd: Version               : 5.5.0  
    azure-arm.build_vhd: PSVersion             : 7.2.13  
    azure-arm.build_vhd: PSBoundParameters     : {[Configuration, PesterConfiguration]}  
    azure-arm.build_vhd: Plugins               :   
    azure-arm.build_vhd: PluginConfiguration   :   

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent version 3.224.1
Image version 20230814.1.0

### Is it regression?

yes, it worked on ubuntu22/20230806.1

### Expected behavior

Testing is completed succesfully

### Actual behavior

Testing fails for kubectl version

### Repro steps

[2023-08-21T230233.2145065Z_LOG.txt](https://github.com/actions/runner-images/files/12405793/2023-08-21T230233.2145065Z_LOG.txt)

See log in attachment

**Comment by Alexey-Ayupov** [comment]
Hi @sander110419, we did some changes in tests - https://github.com/actions/runner-images/pull/8112. Please update your fork and try again. Our night build was good.

**Comment by sander110419** [comment]
Running it now, I'll update whether it's confirmed working

**Comment by sander110419** [comment]
Ah that is not the latest branch, fudge. I'll retry once more

**Comment by sander110419** [comment]
Confirmed fixed!
