### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by AshwaqAzan** [actions/runner-images#8138]
### Tool name

Xcode 

### Tool license

I don't have 

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Xcode version 14.3.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello! Xcode 14.3.1 is available on macOS-13 [runner](https://github.com/actions/runner-images/blob/1ac680fb5f997ed582886ce443a57d0f581ef9a3/images/macos/macos-13-Readme.md)

**Comment by ilia-shipitsin** [comment]
14.3.1 can only be installed on macos-13.
unfortunately, no 11 or 12
