### ISSUE TITLE
Update/Add nmake

### ISSUE THREAD

**Issue by illeatmyhat** [actions/runner-images#8142]
### Tool name

nmake

### Tool license

you literally own it

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

This tool is used by CMake to compile C/C++ code using MSVC.
My org does not allow GitHub Actions from unverified creators, so I attempted to manually install winget and the VS2022 build tools manually but couldn't get it to work.

### URL for tool's homepage

https://winget.run/pkg/Microsoft/VisualStudio.2022.BuildTools

### Provide a basic test case to validate the tool's functionality.

```bash
nmake /?
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
winget install -e --id Microsoft.VisualStudio.2022.BuildTools
```

### Are you willing to submit a PR?

if it's easy

**Comment by Alexey-Ayupov** [comment]
Hello @illeatmyhat, Given the small installation time (1-2 min.) we would not like to pre-install the tool into the image also because of maintenance concerns. 
Please install it in runtime using the following snippet.

```
- name: install VS component
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --channelId VisualStudio.16.Release --productId Microsoft.VisualStudio.Product.Enterprise -q --includeRecommended --add "Microsoft.VisualStudio.2022.BuildTools"
```
