### ISSUE TITLE
Process substitution not working in macOS 13.5 runner

### ISSUE THREAD

**Issue by mywristbands** [actions/runner-images#8146]
## Context

I have a GitHub Actions workflow that deploys an iOS app to App Store Connect. One of the steps involves importing a certificate to the Keychain. My code to perform this importing step has been the same since I originally set up the workflow almost a year ago. Here is the code:

```
security import <(echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode) \
                -f pkcs12 \
                -k build.keychain \
                -P $SIGNING_CERTIFICATE_PASSWORD \
                -T /usr/bin/codesign
```

However, as of Thursday, August 10, 2023, this code now leads to the following errors:
```
security: SecKeychainItemImport: One or more parameters passed to a function were not valid.
bad decrypt
140704704464640:error:02012020:system library:fflush:Broken pipe:crypto/bio/bss_file.c:316:fflush()
140704704464640:error:20074002:BIO routines:file_ctrl:system lib:crypto/bio/bss_file.c:318:
```

Note that this code works just fine for me on my local Mac also running macOS 13.4.1

## The culprit
For some reason Process Substitution (using `<(command-goes-here)` to direct the output of a command to a temporary file) is no longer working correctly for me in GitHub Actions, or at least not working anymore in my particular case. I reached out to GitHub support, and they were also able to replicate the issue.

From viewing my workflow logs, it appears an update to the runner image was involved in this issue.

Here's the run image info for my last succeeding workflow run:
```
2023-07-28T02:35:55.1924780Z Current runner version: '2.306.0'

2023-07-28T02:35:55.1955640Z ##[group]Operating System

2023-07-28T02:35:55.1956690Z macOS

2023-07-28T02:35:55.1957130Z 13.4

2023-07-28T02:35:55.1957740Z 22F66

2023-07-28T02:35:55.1958190Z ##[endgroup]

2023-07-28T02:35:55.1958730Z ##[group]Runner Image

2023-07-28T02:35:55.1959660Z Image: macos-13

2023-07-28T02:35:55.1960380Z Version: 20230611.2

2023-07-28T02:35:55.1961150Z Included Software: https://github.com/actions/runner-images/blob/macos-13/20230611.2/images/macos/macos-13-Readme.md

2023-07-28T02:35:55.1962130Z Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230611.2
```

Here's the run image info for my first failing workflow run:
```
2023-08-11T03:21:36.6299760Z Current runner version: '2.307.1'

2023-08-11T03:21:36.6342250Z ##[group]Operating System

2023-08-11T03:21:36.6343470Z macOS

2023-08-11T03:21:36.6344220Z 13.5

2023-08-11T03:21:36.6344560Z 22G74

2023-08-11T03:21:36.6345240Z ##[endgroup]

2023-08-11T03:21:36.6345720Z ##[group]Runner Image

2023-08-11T03:21:36.6351510Z Image: macos-13

2023-08-11T03:21:36.6352010Z Version: 20230801.2

2023-08-11T03:21:36.6352820Z Included Software: https://github.com/actions/runner-images/blob/macos-13/20230801.2/images/macos/macos-13-Readme.md

2023-08-11T03:21:36.6353620Z Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230801.2
```

## Temporary workaround
I found that one way to get around this issue is to instead (1) save the command output to a regular file, then (2) pass this filename into the import command, and then (3) delete the file afterwards. So here's my new code:
```
echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode > signingCertificate.p12
security import signingCertificate.p12 \
                -f pkcs12 \
                -k build.keychain \
                -P $SIGNING_CERTIFICATE_PASSWORD \
                -T /usr/bin/codesign
rm signingCertificate.p12
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

**Image**: macos-13
**Version**: 20230801.2
**Included Software**: https://github.com/actions/runner-images/blob/macos-13/20230801.2/images/macos/macos-13-Readme.md
**Image Release**: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230801.2

My repository is not public so I cannot provide a link to the failed build.

### Is it regression?

Yes, the latest image version where the issue didn't occur was version 20230611.2

### Expected behavior

I expected Process Substitution to work in my `security import` command I provided earlier in the Issue description.

### Actual behavior

When I run the `security import` command and provide the signing certificate file via Process Substitution, it results in errors like `bad decrypt` and `broken pipe`. See the Issue description above for a full example.

### Repro steps

Here is the whole script involved in setting up the keychain and importing the certificate (the error occurs after the `security import` step):
```
#!/bin/bash

set -euo pipefail

security create-keychain -p "" build.keychain
security list-keychains -s build.keychain
security default-keychain -s build.keychain
security unlock-keychain -p "" build.keychain
security set-keychain-settings
security import <(echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode) \
                -f pkcs12 \
                -k build.keychain \
                -P $SIGNING_CERTIFICATE_PASSWORD \
                -T /usr/bin/codesign
security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
```

And here is the step in my GitHub Actions workflow that actually runs the script:
```
    - name: Import signing certificate
      env:
        SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
        SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      run: |
        exec .github/scripts/import-certificate.sh
```

**Comment by ilia-shipitsin** [comment]
`security` here's is an Apple command line tool. It just cames with macos. runner images recently upgraded to 13.5.1, locally you run 13.4.1, can it be the reason ?

**Comment by mywristbands** [comment]
@ilia-shipitsin Thanks for your response. I just upgraded my local Mac to 13.5.1, and Process Substitution in the context of my script is still working just fine. So it seems to be an issue with the GitHub Actions macOS 13.5 runner specifically.

**Comment by ilia-shipitsin** [comment]
it is surprizing. I've double checked `security` is system utility, and it does not depend on any 3rd party (I suspected that we install something via brew and it may bring some library)

```
Mac-1693222773318:~ runner$ which security
/usr/bin/security
Mac-1693222773318:~ runner$ otool -L `which security`
/usr/bin/security:
        /System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60420.140.26)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1979.0.0)
        /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation (compatibility version 1.0.0, current version 55260.100.9)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1979.0.0)
        /System/Library/Frameworks/Network.framework/Versions/A/Network (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
        /System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking (compatibility version 1.0.0, current version 46.0.0)
Mac-1693222773318:~ runner$
```


no of those library we install, all are shipped by Apple.

well, to move forward we need some repro. may I ask to generate some p12 similar to your ?
we'll play with that file

in theory we can generate our own p12, but I'm afraid it won't be identical to your

**Comment by mywristbands** [comment]
Appreciate you looking into this, but unfortunately I don't think I can provide you with our own company's certificates, as these are confidential.

But if you would like to generate your own certificate for debugging purposes, I'd recommend checking out the tutorial I based my deployment on: [Deploy an iOS App to TestFlight or the App Store Using GitHub Actions](https://betterprogramming.pub/deploy-an-ios-app-to-testflight-or-the-app-store-using-github-actions-c4d7082b1430).

**Comment by ilia-shipitsin** [comment]
my colleague @mikhailkoliada has tested on Mac locally. unfortunately, issue is reproduced even without github runner. not much we can do here. feel free to report to Apple.

**Comment by SteinRobert** [comment]
Just for anyone who stumbles across this issue - I also git the error message `SecKeychainItemImport: One or more parameters passed to a function were not valid.`.

However in my case it only happened on PRs that were opened by Github's Dependabot. It didn't have access to the secrets that were used in that particular workflow. Since I do not need signed binaries in that case I just skipped the signing when the `actor` is dependabot:
```yaml
- name: Codesign App
      if: ${{ github.actor != 'dependabot[bot]' }}
```
