### ISSUE TITLE
az cli x86 is not installed anymore

### ISSUE THREAD

**Issue by omar-oropeza** [actions/runner-images#8150]
### Description

our pipelines were working just fine until Monday morning (2023-08-21), I realized the python version referencing now is x64, this avoid that a custom tool unable to find az cli, as a workaround we had to install az cli x86.

C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\**Program Files**\Microsoft SDKs\Azure\CLI2\python.exe'

after installing az cli x86 it worked again

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Azure DevOps - Windows-latest

### Is it regression?

no

### Expected behavior

az cli x86 should be installed on the agent as before

### Actual behavior

Python location 'C:\**Program Files**\Microsoft SDKs\Azure\CLI2\python.exe'

### Repro steps

add an AzureCLI task and validate the az cli version currently is using python x64 path

**Comment by mikhailkoliada** [comment]
Hello! We are aware of it, azure-cli version has been switched to its x86_64 alternative here: https://github.com/actions/runner-images/pull/8096 as it is now recommended by Microsoft, unfortunately it is not possible installing 2 different az-cli distributions same time, so you indeed should continue installing it in runtime if you need one, or switch to the modern version. Sorry for inconvenience caused, I am going to close the ticket now, if you have more questions feel free to reach us out again.
