### ISSUE TITLE
Suddenly `pigz` is no longer available in Ubuntu-20.04

### ISSUE THREAD

**Issue by Luc45** [actions/runner-images#8161]
### Description

My worksflows suddently started failing 2 days ago because `pigz` could not be found anymore. This tool has been available in the ubuntu-20.04 image, but seems to have been removed without notice. Is the removal expected? If so, why? Is it possible to re-add it?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

It's not a public repo

### Is it regression?

It's not a public repo

### Expected behavior

pigz should be installed in the image

### Actual behavior

pigz is not installed in the image

### Repro steps

Try to execute pigz in Ubuntu 20.04, it should be available.

**Comment by Alexey-Ayupov** [comment]
Hello @Luc45, we will take a look, however temporarily you can switch to `gzip`.

**Comment by Alexey-Ayupov** [comment]
The "pigz" was never in our software list, however, it was installed as a recommended package along with docker. Recently we have changed the `docker` installation source and stopped installing "pigz".
If you would like to use it you can install it in runtime, using a snippet like this

```
- name: check issue
        id: test_out
        shell: bash
        run: |
          apt-get -yq update
          apt-get install -y pigz
```

If you have any questions, feel free to reach us.

**Comment by Luc45** [comment]
Thanks, that makes sense now. I'll adapt my workflows.

**Comment by jeffwidman** [comment]
I opened:
* https://github.com/actions/runner-images/issues/8205

to try to get this installed by default as in our workflows the step to install pigz adds 2 mins which seems excessively long given it's only a 259kb install...
