### ISSUE TITLE
workflow now doesn't work with ubuntu-latest

### ISSUE THREAD

**Issue by bananaturtlesandwich** [actions/runner-images#8171]
### Description

running the same action on the same commit now results in a failure with `Syntax error: word unexpected (expecting ")")`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

before: https://github.com/bananaturtlesandwich/UE4-Modding-Guide/actions/runs/2920374181
after: https://github.com/bananaturtlesandwich/UE4-Modding-Guide/actions/runs/5989705501/job/16246175470

### Is it regression?

https://github.com/bananaturtlesandwich/UE4-Modding-Guide/actions/runs/2920374181 - not sure what the image version was 

### Expected behavior

a successful build like before

### Actual behavior

a failure with `Syntax error: word unexpected (expecting ")")`

### Repro steps

re-run this workflow https://github.com/bananaturtlesandwich/UE4-Modding-Guide/actions/runs/5989705501/job/16246175470

**Comment by mikhailkoliada** [comment]
Hello! Please convey the concerns to the original author of the action you use, we support the runner images but do not guarantee 3rd party actions will work after updates as we do not track the development progress of independent authors and the problem is seeming to be in the action code itself.
