### ISSUE TITLE
LLVM 14 is not installed om macos-12

### ISSUE THREAD

**Issue by laytan** [actions/runner-images#8172]
### Description

According to the readme at [images/macos/macos-12-Readme.md](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) LLVM 14 should be installed on macos-12 runners, it is not though.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-12

### Is it regression?

IDK

### Expected behavior

Either the readme should not say it is installed, or the runner should have it installed.

### Actual behavior

Not installed.

### Repro steps

Try using llvm 14 in a macos-12 runner. For example `brew list | grep llvm`

**Comment by mikhailkoliada** [comment]
Hello! The docs are correct, llvm 14 does not come with brew but with xcode installed in the image and is also pinned to the clang version from Xcode 

<img width="967" alt="image" src="https://github.com/actions/runner-images/assets/88318005/0e49bc15-e4e7-4912-8ef2-9b5c64742f6e">
