### ISSUE TITLE
Latest 20230821.1.0 is not 100% rolled out, builds still on 20230814.1.0

### ISSUE THREAD

**Issue by renemadsen** [actions/runner-images#8177]
### Description

At last update of images, we also experienced the samme issue.

![image](https://github.com/actions/runner-images/assets/76994/8813fbef-5b91-46a8-9d38-97c98fe38b8c)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/microting/eform-angular-frontend/actions/runs/5995685573/job/16259163514

### Is it regression?

don't know

### Expected behavior

To use latest version, when it says it's 100% deployed and not an older version,
See https://github.com/microting/eform-angular-frontend/actions/runs/5995685573/job/16259163431 for correct behavior.

### Actual behavior

It's using an older version.

### Repro steps

Setup any repository to runs-on: ubuntu-latest

**Comment by vpolikarpov-akvelon** [comment]
Hey @renemadsen. I don't see any Ubuntu 22.04 pools that run image of version `20230814.1.0`. Could you please retry your workflows? If problem persists please share log of your runs as your projects are private and we can't access them.

Also please note that:
- Larger runners weren't updated yet (the latest version is `20230806.1` now);
- If you host runners on your own then you are in charge of updating them;
- If runners are hosted by your organization then reach out for the tech team of your organization.

**Comment by renemadsen** [comment]
@vpolikarpov-akvelon 
Thanks for the information.
Is there some place with information about upgrade cycle for large-runners, so we could follow, what version the included software has?

Issue has been resolved.

**Comment by vpolikarpov-akvelon** [comment]
I'm glad to hear your issue has been resolved.

As of larger runners, there is no any status page that would display currently deployed versions, unfortunately. The only way to check current version is to start a job.
