### ISSUE TITLE
Unable to grant accessibility permissions to Apple Notes

### ISSUE THREAD

**Issue by TomasHubelbauer** [actions/runner-images#8214]
### Description

Hi, I am using AppleScript to control Apple Notes. On the macOS runner, the AppleScript doesn't work which I figure is because of the accessibility permission grant not being there for Apple Notes. I looked for ways to grant it in the workflow file programmatically.

I tried this:
```
sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.Notes',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e66696e64657200000003',NULL,1592919552);"
```

This succeeds but my Apple Script times out.

Then I tried this:
```
sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, auth_value, auth_reason, auth_version, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 2, 0, 0, 'com.apple.Notes')"
```

Same thing, succeeds but Apple Script times out.

I do try to run `osascript -e 'tell application "Notes" to activate'` which makes no difference.
I suspect the grant is not given yet.

I looked at similar threads like this one:
- https://github.com/actions/runner-images/issues/553#issuecomment-648109166
- https://github.com/actions/runner-images/issues/3286

The first one's command is for older macOS version that is on the image now and no longer works due to a change in the TCC DB structure. My scripts above reflect the new structure.

How can I make it possible to script Apple Notes via AppleScript on the macOS runner? How do I debug stuff on it to be able to tell what is happening?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-latest

### Is it regression?

No idea

### Expected behavior

The permission is granted and the AppleScript works and controls Apple Notes.

### Actual behavior

The grant is seemingly added to the TCC DB but the Apple Script times out.

### Repro steps

1. `sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" -cmd ".headers ON" "select * from access where service = 'kTCCServiceAppleEvents'"` to check the structure
2. `sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, auth_value, auth_reason, auth_version, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 2, 0, 0, 'com.apple.Notes')"` to grant the permission
3. `osascript -e 'tell application "Notes" to activate'` and `osascript -e 'tell application "Notes" to name of every note in every folder'`

**Comment by vpolikarpov-akvelon** [comment]
Hey @TomasHubelbauer. Thank you for reporting, we will take a look.

**Comment by sergei-pyshnoi** [comment]
Hello @TomasHubelbauer . I made some changes in sql query and it works using provided repro steps. Can you try it?
` sudo sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.Notes',X'fade0c000000002c0000000100000006000000020000000f636f6d2e6170706c652e4e6f7465730000000003',NULL,1592919552);"`

**Comment by TomasHubelbauer** [comment]
You can see the failing run here:
https://github.com/TomasHubelbauer/apple-notes-database/actions/runs/6048441753/job/16413788595

The command itself ran fine, but the AppleScript timed out. Have I missed a step?

**Comment by sergei-pyshnoi** [comment]
> You can see the failing run here: https://github.com/TomasHubelbauer/apple-notes-database/actions/runs/6048441753/job/16413788595
> 
> The command itself ran fine, but the AppleScript timed out. Have I missed a step?

Here is workflow with successful run
https://github.com/sergei-pyshnoi/workflow_test/actions/runs/6074554201/job/16478847170

**Comment by sergei-pyshnoi** [comment]
```
jobs:
  build:
    runs-on: macos-13
    steps:

      - name: check-directory
        run: |
          sudo sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.Notes',X'fade0c000000002c0000000100000006000000020000000f636f6d2e6170706c652e4e6f7465730000000003',NULL,1592919552);"
          osascript -e 'tell application "Notes" to activate'
          osascript -e 'tell application "Notes" to name of every note in every folder'
```

**Comment by TomasHubelbauer** [comment]
@sergei-pyshnoi I am using your snippet verbatim (literally copy-pasted it to my workflow file) and I am unable to reproduce your success:
https://github.com/TomasHubelbauer/apple-notes-database/actions/runs/6075355558/job/16481368183

But I realized it is probably because you are using the beta `macos-13` runner image while I am using `macos-latest`. Is this only possible in the beta image? Is there a way to make it work for macOS 12?

**Comment by sergei-pyshnoi** [comment]
Hello @TomasHubelbauer . Sorry for the late response . Unfortunately provided workaround will work only with macos-13. Please those for your pipeline. Regarding exits from beta, please follow the announcements. I am closing this issue for now, but if you have additional feel free to ask.
