### ISSUE TITLE
Xamarin.Android version 13.2.1.2 

### ISSUE THREAD

**Issue by LBally** [actions/runner-images#8215]
### Tool name

Xamarin Bundle

### Tool license

The MIT License (MIT)

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.2.1.2

### URL for tool's homepage

https://github.com/xamarin/xamarin-android

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by vpolikarpov-akvelon** [comment]
@LBally, thank you for your request, we will take a look.

**Comment by LBally** [comment]
This will let us build apps against Android 14 with the new fix with our existing pipelines

**Comment by mikhailkoliada** [comment]
Updated, will be deployed next week

**Comment by mikhailkoliada** [comment]
It should be available in the image now.
