### ISSUE TITLE
Update PowerShell Module Az

### ISSUE THREAD

**Issue by Ellestad1995** [actions/runner-images#8224]
### Tool name

PowerShell Module Az

### Tool license

MICROSOFT SOFTWARE LICENSE TERMS

### Add or update?

- [ ] Add
- [X] Update

### Desired version

10.2.0

### Brief description of tool

Include latest PowerShell Module Az. 
Version included in image is 9.3.0 and latest version available is 10.2.0 since late july.

### URL for tool's homepage

https://github.com/Azure/azure-powershell/releases/tag/v10.2.0-August2023

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
// Update /images/win/toolsets/toolset-2022.json  (https://github.com/actions/runner-images/blob/main/images/win/toolsets/toolset-2022.json)
```

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
Hello! given the stability of Az releases we would not like to update a default Az PowerShell version yet, please install the version via the AzurePowerShell@5 AzDo task.
