### ISSUE TITLE
Error: Undefined -var variable

### ISSUE THREAD

**Issue by abdul561** [actions/runner-images#8235]
### Description

Currently use Azure devops to build the image weekly. Use to work fine until recently. I have this error of : Error: Undefined -var variable for the following 2 variables: 
storage_account and resource_group.

```
Error: Undefined -var variable

A "resource_group" variable was passed in the command line but was not found in
known variables. To declare variable "resource_group", place this block in one
of your .pkr files, such as variables.pkr.hcl

Error: Undefined -var variable

A "storage_account" variable was passed in the command line but was not found in
known variables. To declare variable "storage_account", place this block in one
of your .pkr files, such as variables.pkr.hcl

```
Have they been removed from the ubuntu2204 packer file?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '3.225.0

### Is it regression?

no

### Expected behavior

Should be taking in my resource group and storage account fine and build the image

### Actual behavior

error of due to using variables not stated in the packer file

### Repro steps

when adding in variables for the task "packer build" , add resource group and storage account

**Comment by sergei-pyshnoi** [comment]
Hello @abdul561 . We have updated packer templates due unmanaged VHDs deprecation. More detailed information you can see in [this PR](https://github.com/actions/runner-images/pull/8167). You need update build configuration according to new documentation (also included to PR). Before it, as workaround you can pin commit before new changes in your pipeline. I am closing issue for now. But if you have  any question feel free to ask.

**Comment by abdul561** [comment]
> Hello @abdul561 . We have updated packer templates due unmanaged VHDs deprecation. More detailed information you can see in [this PR](https://github.com/actions/runner-images/pull/8167). You need update build configuration according to new documentation (also included to PR). Before it, as workaround you can pin commit before new changes in your pipeline. I am closing issue for now. But if you have any question feel free to ask.

No worries thanks for the explanation , will just have to update it to fit the new config
