### ISSUE TITLE
[All OSes] Go 1.18.x will be removed on September, 18

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#8237]
### Breaking changes

Go 1.18.x will be removed from all OSes.

### Target date

Image deployment is starting on September 18 and will take 3-4 days.

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.

### Possible impact

If your builds depend on Go 1.18.x they execution time of the pipeline will become longer (as the go archive will be downloaded in runtime).

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

To install any versions in runtime use:

https://github.com/actions/setup-go action for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by sashabu** [comment]
Could you please clarify whether Go 1.**18**.x (per the title) or 1.**17**.x (per the body) will be removed?

**Comment by mikhailkoliada** [comment]
Fixed a typo :) 1.18 is meant to be removed

**Comment by sashabu** [comment]
> Fixed a typo :) 1.18 is meant to be removed

Thanks!

> ### Breaking changes
> Go 1.17.x will be removed from all OSes.

Still one left.

**Comment by mikhailkoliada** [comment]
Removed
