### ISSUE TITLE
Update/Add [PowerShell]

### ISSUE THREAD

**Issue by kilasuit** [actions/runner-images#8242]
### Tool name

PowerShell

### Tool license

MIT

### Add or update?

- [X] Add
- [X] Update

### Desired version

Stable & Preview

### Approximate size

Depends on if 1/both are accepted

### Brief description of tool

PowerShell is already available pinned to the latest LTS release with this [script on windows](https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers/Install-PowershellCore.ps1) (which should be renamed to LTS), this [script on linux](https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/powershellcore.sh) & this [script on MacOs](https://github.com/actions/runner-images/blob/main/images/macos/provision/core/powershell.sh)

However we have also Stable, Preview and Daily releases that are available, not just the LTS.

I am proposing that as PowerShell is soon to move to the next LTS (7.4.0) that we extend the current `shell: pwsh` tasks to allow for a version flag of `shell: pwsh-stable` `shell: pwsh-lts` & `shell: pwsh-preview` as well. Then once 7.4.0 is released (the next LTS) then we could optionally remove the option for `shell:pwsh-stable` & `shell:pwsh-lts` as they would be the one and the same until we get closer to the 7.5.0 release timeframe.

This is a "is this feasible" request as I know there has been discussions around the lack of having more recent versions of PowerShell in the images for those needing to build and test & would help in reducing some need for customised images if this were to be accepted as feasible based on the above

### URL for tool's homepage

https://github.com/powershell/powershell

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes it can be by using the various install methods already
```

### Are you willing to submit a PR?

potentially

**Comment by sergei-pyshnoi** [comment]
Hello @kilasuit . Thanks for your report. The main reason of installing only LTS version of PowerShell it is attempting to avoid breaking changes that  can impact GH Action/Azure Pipeline users. So in the near future we do not have plan to add additional versions of PS to images. About additional options for `shell` argument, you should create request in [actions/runner](https://github.com/actions/runner) repo, because it is not image related feature. I am closing issue for now, but if you have additional questions feel free to ask.
