### ISSUE TITLE
Update Azure Cli

### ISSUE THREAD

**Issue by OranguTech** [actions/runner-images#8244]
### Tool name

Azure CLI

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

At least version 2.52.0

### Brief description of tool

New version fixes https://github.com/Azure/azure-cli/issues/27109

### URL for tool's homepage

https://github.com/Azure/azure-cli

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @OranguTech . Thanks for your report. Latest version of Azure CLI will be available during next week.

**Comment by mikhailkoliada** [comment]
Deployed.
