### ISSUE TITLE
Chrome is missing from windows-latest registry (Software\Clients\StartMenuInternet)

### ISSUE THREAD

**Issue by roniemartinez** [actions/runner-images#8246]
### Description

I was asked to redirect the bug report from https://github.com/actions/runner/issues/2829

Google Chrome is missing from `Software\Clients\StartMenuInternet` for `windows-latest`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/roniemartinez/browsers/pull/95

### Is it regression?

Not sure when this regression was released but previous windows-latest was passing weeks ago

### Expected behavior

Chrome should be in registry: `Software\Clients\StartMenuInternet`

### Actual behavior

Chrome is missing from registry

### Repro steps

Tests should pass: https://github.com/roniemartinez/browsers/pull/95

**Comment by sergei-pyshnoi** [comment]
Hello @roniemartinez. We will take a look.

**Comment by sergei-pyshnoi** [comment]
Closing as duplicate https://github.com/actions/runner-images/issues/8114
