### ISSUE TITLE
Update/Add Helix Core CLI

### ISSUE THREAD

**Issue by Zageron** [actions/runner-images#8251]
### Tool name

Helix Core CLI (P4)

### Tool license

P4/P4API

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

22.4MB

### Brief description of tool

Perforce cli tool for interacting with a perforce server.

I searched for history on this tool, it surprises me that it isn't included in the images by default. My assumption is that the P4/P4API license is unacceptable? I made this issue regardless so there can be a record of acceptance/rejection.

Here's the incomplete p4 specific portion of the license regarding distribution:

```
P4/P4API License
    -----------------------
    Copyright (c) 1995-2023, Perforce Software, Inc.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

        Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

        Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
```

There is a full license which includes the license pieces of all distributed software used by perforce.
It can be acquired by `p4 help legal`.

### URL for tool's homepage

https://www.perforce.com/products/helix-core-apps/command-line-client

### Provide a basic test case to validate the tool's functionality.

```bash
p4 -V
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
https://www.perforce.com/manuals/v15.1/p4guide/chapter.install.html
```

**Comment by sergei-pyshnoi** [comment]
Hello @Zageron .  With small installation time (1-2 min) would not like to pre-install the tool into the image also because of maintenance concerns. Please install provided tool in runtime. I am closing this issue for now, but if have any additional questions feel free to ask.
