### ISSUE TITLE
Install-MongoDB.ps1 is failing with a (403) Forbidden error

### ISSUE THREAD

**Issue by mnieto** [actions/runner-images#8252]
### Description

Install-MongoDB.ps1 is failing with below error:
```
azure-arm: Downloading package from: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.21-signed.msi to path C:\Users\packer\AppData\Local\Temp\mongodb-windows-x86_64-5.0.21-signed.msi .
    azure-arm: There is an error encounterd after 0.22 seconds during package downloading:
    azure-arm:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
    azure-arm: System.Management.Automation.MethodInvocationException: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden." ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
    azure-arm:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
    azure-arm:    at CallSite.Target(Closure , CallSite , Object , String , Object )
```

Searching in the Install-MongoDB.ps1, it is parsing the https://www.mongodb.com/docs/upcoming/release-notes/5.0 page
and getting the latest release, at this moment it's 5.0.21 and the script generates this url
`https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.21-signed.msi`
But the 5.0.21 is a RC release and the correct url is 
`https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.21-rc0-signed.msi`

you can verify the correct link from the [Mongo download page](https://www.mongodb.com/try/download/community-kubernetes-operator)
![image](https://github.com/actions/runner-images/assets/7962206/3e6e9267-8518-4fb5-aaa8-9152eefe792b)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

win22/20230903.2

### Is it regression?

No

### Expected behavior

Install last MongoDB version

### Actual behavior

Generating error and stopping the build process
```
azure-arm: Downloading package from: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.21-signed.msi to path C:\Users\packer\AppData\Local\Temp\mongodb-windows-x86_64-5.0.21-signed.msi .
    azure-arm: There is an error encounterd after 0.22 seconds during package downloading:
    azure-arm:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
    azure-arm: System.Management.Automation.MethodInvocationException: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden." ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
    azure-arm:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
    azure-arm:    at CallSite.Target(Closure , CallSite , Object , String , Object )
```

### Repro steps

run the [GenerateResourcesAndImage](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1) script

**Comment by mikhailkoliada** [comment]
Should be fixed, please sync your fork.

**Comment by tomasszabo** [comment]
Hello @mikhailkoliada, this fix didn't helped. Generated URL is:

`https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.22-signed.msi`

but 5.0.22 is also RC, therefore correct link is:

`https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.22-rc0-signed.msi`

Please reopen. Thank you!

**Comment by sergei-pyshnoi** [comment]
Hello @tomasszabo . We created [PR](https://github.com/actions/runner-images/pull/8589) with fix. We will merge it as soon as tests pass.

**Comment by sergei-pyshnoi** [comment]
Merged. Please rebase your fork
