### ISSUE TITLE
Update LLVM and Clang to version 15

### ISSUE THREAD

**Issue by chandlerc** [actions/runner-images#8253]
### Tool name

LLVM and Clang

### Tool license

Apache 2.0 with LLVM exception

### Add or update?

- [ ] Add
- [X] Update

### Desired version

version 15 (whichever point release is available

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt install clang-15
```

**Comment by chandlerc** [comment]
Just to note -- #6803 did this for Windows and macOS, so getting Ubuntu would allow folks to set a baseline at Clang and LLVM v15 or newer.

**Comment by sergei-pyshnoi** [comment]
Hello @chandlerc . Thanks for your report. We will merge PR with clang-15 as soon as tests pass https://github.com/actions/runner-images/pull/8255.

**Comment by chandlerc** [comment]
That somewhat seems like libc++-15 isn't installed?

**Comment by mikhailkoliada** [comment]
Deployed
