### ISSUE TITLE
Update/Add lld

### ISSUE THREAD

**Issue by quyykk** [actions/runner-images#8260]
### Tool name

lld

### Tool license

Apache 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest on Ubuntu repos

### Brief description of tool

LLD is much faster than the default GNU linker.

### URL for tool's homepage

https://lld.llvm.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt-get install lld
```

**Comment by shamil-mubarakshin** [comment]
Hello @quyykk, we will have a look

**Comment by shamil-mubarakshin** [comment]
@quyykk, due to short installation time on build and maintenance concerns, we would not like to include the tool in the image.
I will close the issue. Feel free to reach out in case of further concerns
