### ISSUE TITLE
Clang 12 will be removed from Ubuntu 22.04 image on September 25

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#8263]
### Breaking changes

Clang 12 will be removed from the Ubuntu 22.04 image.

### Target date

Image deployment is starting on September 25 and will take 3-4 days.

### The motivation for the changes

As per our [software support policy](https://github.com/actions/runner-images#software-and-image-support), we are supporting only 3 latest versions of clang.

### Possible impact

If your projects depend on clang 12 they might be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

The package can still be installed at runtime by running the `sudo apt-get install cling-12` command.

**Comment by mikhailkoliada** [comment]
Removed

**Comment by echoix** [comment]
> `sudo apt-get install cling-12`

I think you meant 
`sudo apt-get install clang-12`
Is it possible?
