### ISSUE TITLE
Update/Add gradlew

### ISSUE THREAD

**Issue by ajaysuwalka** [actions/runner-images#8267]
### Tool name

gradlew

### Tool license

Open

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Gradlew is a popular build tool and since you have maven it makes sense to add gradlew too

### URL for tool's homepage

https://docs.gradle.org/current/userguide/gradle_wrapper.html

### Provide a basic test case to validate the tool's functionality.

```bash
Gradlew is a popular build tool
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes but takes long time

```

### Tool installation time in runtime

2m 23s
<img width="1421" alt="image" src="https://github.com/actions/runner-images/assets/5610570/d682536d-185b-41c0-8eab-854f78e36999">

### Are you willing to submit a PR?

Yes

**Comment by shamil-mubarakshin** [comment]
Hello @ajaysuwalka, we will have a look

**Comment by shamil-mubarakshin** [comment]
@ajaysuwalka, according to docs, `gradlew` is project specific and should be run for each project. We would not like to add it to the image.
To enhance build time you can consider adding [actions/cache](https://github.com/marketplace/actions/cache) and/or [gradle/gradle-build-action](https://github.com/marketplace/actions/gradle-build-action). which can use caching as well.

**Comment by ajaysuwalka** [comment]
Sorry I didn't get your point, You have a lot of popular tools by default in your image and that was the motivation behind raising this ticket. I will appreciate if you consider this adding

**Comment by shamil-mubarakshin** [comment]
I have the [impression](https://docs.gradle.org/current/userguide/gradle_wrapper.html#:~:text=Executing%20the%20wrapper%20task%20generates%20the%20necessary%20Wrapper%20files%20in%20the%20project%20directory), that using `gradle wrapper` in project directory is the correct way of using the wrapper. Result can be cached or checked to repository for further use afterwards.
