### ISSUE TITLE
"DevToolsActivePort file doesn't exist" with ChromeDriver 116

### ISSUE THREAD

**Issue by solverat** [actions/runner-images#8268]
### Description

Running acceptance tests with chromium 116 fails:

>   (unknown error: DevToolsActivePort file doesn't exist)

ChromeDriver 116.0.5845.96

However, it worked perfectly with Chromedriver 115.

There was a similar issue some years ago: https://github.com/actions/runner-images/issues/506

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Version: 20230903.1.0

Failed Build: https://github.com/dachcom-digital/pimcore-formbuilder/actions/runs/6151632528/job/16692099977

### Is it regression?

https://github.com/dachcom-digital/pimcore-toolbox/actions/runs/5923872316/job/16060318949

### Expected behavior

Chromedriver 116 works as expected

### Actual behavior

Chromdriver 116 fails with "DevToolsActivePort file doesn't exist" 

### Repro steps

```yaml
-   name: Setup Chromium
    run: |
        nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &
```

**Comment by solverat** [comment]
Hey @shamil-mubarakshin, thanks for your feedback. I've restarted my tests with your suggestions without any success. 
Even changing the parameters as suggested on the chromedriver issue list have not made a difference.

in my despair, i've changed my command from

```yaml
chromedriver --url-base=/wd/hub &
```

to

```yaml
chromedriver --url-base=/wd/hub &
sudo Xvfb -ac :99 > /dev/null 2>&1 &
```

and.... now it works. 🤷‍♂

However, I have no idea why I need to this, but maybe this is useful for someone out there.

**Comment by shamil-mubarakshin** [comment]
@solverat, glad you have found the solution.
I will close this issue for now. Feel free to reach out in case of concerns

**Comment by StephenT-McMurray** [comment]
Hi. I am also running into this issue, it seems. Can this ticket be reopened?

**Comment by solverat** [comment]
I just had some similar thing and this time I fixed it for real. :) I was on the wrong path all the time.  Selenium changed the chrome option node from `chromeOptions` to  `goog:chromeOptions`. Therefor, my options haven't been resolved anymore.

```diff
capabilities:
-    chromeOptions
+    'goog:chromeOptions':
        args: ['--no-sandbox', '--disable-extensions', '--headless', '--disable-gpu', '--disable-dev-shm-usage', '--window-size=1280,1024']
```

**Comment by ziadoz** [comment]
Just in case it helps someone else. I've hit this issue upgrading a GitHub Actions workflow that runs Laravel Dusk tests from Ubuntu 22.04 to 24.04. Adding these Chrome flags seems to have fixed it: `--no-sandbox` and `--disable-dev-shm-usage`.
