### ISSUE TITLE
Add Swift to Windows images

### ISSUE THREAD

**Issue by fumoboy007** [actions/runner-images#8281]
### Tool name

Swift

### Tool license

Apache

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Any

### Brief description of tool

From the homepage:
> Swift is a general-purpose programming language that’s approachable for newcomers and powerful for experts. It is fast, modern, safe, and a joy to write.

### URL for tool's homepage

https://www.swift.org

### Provide a basic test case to validate the tool's functionality.

Something similar to the Ubuntu image’s [tests](https://github.com/actions/runner-images/blob/5ffd15d845c7466f1eedda2b3e9a69c055b85d15/images/linux/scripts/tests/Common.Tests.ps1#L32-L44) I would assume:
```powershell
Describe "Swift" {
    It "swift" {
        "swift --version" | Should -ReturnZeroExitCode
    }

    It "swiftc" {
        "swiftc --version" | Should -ReturnZeroExitCode
    }

    It "libsourcekitd" {
        "/usr/local/lib/libsourcekitdInProc.so" | Should -Exist
    }
}
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

Something similar to the Ubuntu image’s [install script](https://github.com/actions/runner-images/blob/5ffd15d845c7466f1eedda2b3e9a69c055b85d15/images/linux/scripts/installers/swift.sh) I would assume:

```bash
#!/bin/bash -e
################################################################################
##  File:  swift.sh
##  Desc:  Installs Swift
################################################################################

# Source the helpers for use with the script
source $HELPER_SCRIPTS/install.sh

# Install
image_label="$(lsb_release -rs)"
swift_version=$(curl -fsSL "https://api.github.com/repos/apple/swift/releases/latest" | jq -r '.tag_name | match("[0-9.]+").string')

swift_tar_name="swift-$swift_version-RELEASE-ubuntu$image_label.tar.gz"
swift_tar_url="https://swift.org/builds/swift-$swift_version-release/ubuntu${image_label//./}/swift-$swift_version-RELEASE/$swift_tar_name"
download_with_retries $swift_tar_url "/tmp" "$swift_tar_name"

tar xzf /tmp/$swift_tar_name

SWIFT_INSTALL_ROOT="/usr/share/swift"
SWIFT_BIN_ROOT="$SWIFT_INSTALL_ROOT/usr/bin"
SWIFT_LIB_ROOT="$SWIFT_INSTALL_ROOT/usr/lib"

mv swift-$swift_version-RELEASE-ubuntu$image_label $SWIFT_INSTALL_ROOT
mkdir -p /usr/local/lib

ln -s "$SWIFT_BIN_ROOT/swift" /usr/local/bin/swift
ln -s "$SWIFT_BIN_ROOT/swiftc" /usr/local/bin/swiftc
ln -s "$SWIFT_LIB_ROOT/libsourcekitdInProc.so" /usr/local/lib/libsourcekitdInProc.so

echo "SWIFT_PATH=$SWIFT_BIN_ROOT" | tee -a /etc/environment

invoke_tests "Common" "Swift"
```

### Are you willing to submit a PR?

I don’t think I’m the right person. I’ve never used Swift on Windows. I just want to make sure my Swift package’s tests pass on Windows.

**Comment by shamil-mubarakshin** [comment]
Hello @fumoboy007. There were some concerns about adding swift to windows images in the past. Let us check if those still stand and get back

**Comment by shamil-mubarakshin** [comment]
@fumoboy007, we would not like to include the tool in the image due to maintenance concerns. I am closing this issue for now, feel free to reach out in case of further concerns

**Comment by fumoboy007** [comment]
@shamil-mubarakshin For posterity’s sake, can you elaborate on the maintenance concerns?

**Comment by fumoboy007** [comment]
> @shamil-mubarakshin For posterity’s sake, can you elaborate on the maintenance concerns?

@shamil-mubarakshin ^

**Comment by fumoboy007** [comment]
@compnerd Would you happen to know if there are extra maintenance issues with Swift on Windows? Not sure what kind of maintenance issues @shamil-mubarakshin is referring to that aren’t also relevant to the [existing](https://github.com/actions/runner-images/blame/c5c9a7cd7b2cfd20d740f7667fdaca8a412f2b52/images/ubuntu/scripts/build/install-swift.sh) support for Swift in the Ubuntu runner images.

**Comment by compnerd** [comment]
I'm unaware of the issues, the only one that was ever mentioned was size.
