### ISSUE TITLE
Add Xcode 14.0.1 to macOS 13

### ISSUE THREAD

**Issue by ychin** [actions/runner-images#8299]
### Tool name

Xcode

### Tool license

Apple

### Add or update?

- [X] Add
- [ ] Update

### Desired version

14.0.1

### Approximate size

12 GB

### Brief description of tool

Xcode 14.0.1 was the last version of Xcode that targets the macOS 12 SDK. (https://developer.apple.com/support/xcode/)

The macOS 12 SDK supports building macOS apps down to macOS 10.9 Mavericks, whereas the newer macOS 13 SDK only allows deployment target down to 10.13 High Sierra, a big jump of 4 versions / years of OSes. I have an open source app that still has some people using these older macOS versions (10.9 - 10.12) and I have been building a separate version using Xcode 14.0.1.

Seems like the macOS 13 runner image (https://github.com/actions/runner-images/blob/releases/macos-13/20230903/images/macos/macos-13-Readme.md) only has down to Xcode 14.2 now. Given GitHub's policy of deprecating older OS images I am afraid that I would lose access to the older version of Xcode since it's only available on the macOS 12 image now.

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

**Comment by shamil-mubarakshin** [comment]
Hello @ychin,
We would not like to add 14.0.1 Xcode to macos13 image.
You can continue using macos12 since there are no plans on deprecating the image in near future.
