### ISSUE TITLE
XCode 14.3 and Xamarin 16.4.0.15 on macos-12 images

### ISSUE THREAD

**Issue by IainS1986** [actions/runner-images#8320]
### Tool name

XCode and Xamarin.iOS

### Tool license

Apple, inc

### Add or update?

- [ ] Add
- [X] Update

### Desired version

XCode 14.3, Xamarin.iOS 16.4.0.15

### Brief description of tool

There's a breaking issue with Xamarin.iOS apps running on iOS 17 if they haven't linked away the references to deprecated NewsStand APIs.

Details can be seen here...
https://github.com/xamarin/xamarin-macios/issues/18964

A fix has been published in Xamarin.iOS 16.4.0.15 - which I think also requires Xcode 14.3

Are there plans to update the macos-12 image with this update?

Current the macos-12 image appears to have Xcode 14.2 installed and Xamarin.iOS 16.0.0.72

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello! Xcode 14.3 requires macOS 13+ to be used, but at the time we do not have plans to provide Xamarin bundles in macOS13, that is why we are unable to assist here, if you want the fix to be available you should switch to macos13.
I'm going to close the issue for now, if you have more questions, feel free to reach us out again in this ticket.

**Comment by IainS1986** [comment]
Does macos-13 image have Xamarin support? It wasn't listed in the installed tools/libraries

**Comment by beeradmoore** [comment]
@IainS1986 , you should be able to create a custom build step and install Xamarin bundles with [boots](https://github.com/jonathanpeppers/boots).
