### ISSUE TITLE
Update JDK to 21 LTS

### ISSUE THREAD

**Issue by 4brunu** [actions/runner-images#8336]
### Tool name

JDK

### Tool license

GNU General Public License, version 2, with the Classpath Exception

### Add or update?

- [ ] Add
- [X] Update

### Desired version

21 LTS

### Brief description of tool

Please add JDK 21 LTS

### URL for tool's homepage

https://jdk.java.net/21/

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @4brunu!
Thank you for the request. We'll work on it.

**Comment by erik-bershel** [comment]
@4brunu JDK 21 is not yet available in [Adoptium](https://adoptium.net/en-GB/temurin/releases/) repo.
We will add it as soon as it becomes available.
