### ISSUE TITLE
Intermediate docker images generated in previous build steps within the same run weren't retained when running on Microsoft-hosted agent

### ISSUE THREAD

**Issue by LiangZugeng** [actions/runner-images#8350]
### Description

We have an Azure DevOps yaml pipeline running on a self-hosted agent, it works fine. When we switch to use the Microsoft-hosted agent, we got an issue retrieving the intermediate unit test docker image generated in the previous build stage. The issue was found within the same pipeline run. It's not caused by Microsoft-hosted agent not retaining any data between runs.

Dockerfile
```
# Phase 1: Build the source code
FROM nginx:latest AS build
WORKDIR /src
RUN echo "Build completed" > build.txt

# Phase 2: Run unit tests
FROM build as testrunner
WORKDIR /testresults
RUN echo "Placeholder" > placeholder.txt
RUN echo "Unit test completed" > testresults.txt
LABEL unittestlayer=true

# Phase 3: Publish the binary
FROM build as publish
WORKDIR /publish
COPY --from=build /src/build.txt .
RUN echo "Binary publish completed" > publish.txt

# Phase 4: Build the final docker image
FROM nginx:latest AS base
WORKDIR /app
COPY --from=publish /publish .
COPY --from=testrunner /testresults/placeholder.txt .
```

azure-pipelines.yml
```
trigger:
  - main

pool:
  vmImage: "ubuntu-22.04"

steps:
  - task: DockerCompose@0
    displayName: "Build and Test"
    inputs:
      dockerComposeFile: "**/docker-compose.yml"
      dockerComposeFileArgs: |
        TAG=$(Build.BuildNumber)
      projectName: "demo"
      action: "Build services"

  - script: |
      docker images -a
      export unittestlayerid=$(docker images --filter "label=unittestlayer=true" -q)
      docker create --name unittestcontainer $unittestlayerid
      docker cp unittestcontainer:/testresults/ $(Build.ArtifactStagingDirectory)/testresults/
      docker stop unittestcontainer
      docker rm unittestcontainer
    displayName: "Retrieve Test and Coverage Results"
    continueOnError: false
```

The script in the pipeline failed to get the unit test image, `docker images --filter "label=unittestlayer=true" -q` returned empty result. There is also no intermediate docker images in the output of `docker images -a` command.

What does Microsoft-hosted agent do differently to cause the issue and how can the intermediate docker image be retrieved in latter build steps within the same build pipeline?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We prepared the minimal example code to replicate the issue and uploaded it to a public Azure DevOps project:

https://dev.azure.com/liangzugeng/_git/DockerBuildPipelineRepro

The previous failed pipeline run contains the build output:

https://dev.azure.com/liangzugeng/DockerBuildPipelineRepro/_build/results?buildId=59&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

### Is it regression?

no

### Expected behavior

The intermediate docker images can be retrieved in latter build steps within the same run

### Actual behavior

The intermediate docker image generated in the previous build stage cannot be retrieved in the latter build steps.

### Repro steps

1. Clone the sample code repo provided in this issue.
2. Create a project in Azure DevOps and upload all files in the cloned repo to the new project repo
3. Create a pipeline in the new project and accept all default settings
4. Run the created pipeline
5. See the error message in the `Retrieve Test and Coverage Results` build step

As `docker images --filter "label=unittestlayer=true" -q` cannot find the intermediate image, the `unittestlayerid` is empty which cause an error executing `docker create --name unittestcontainer $unittestlayerid`

**Comment by erik-bershel** [comment]
Hey @LiangZugeng! 
This problem is not related to the images per se. The problem is related to the organisation of multistage build of the Docker image. I can suggest converting this issue into a discussion - maybe one of the users will share an example of best practice or recommend a convenient crutch. Or to ask the same question in the azure-pipelines-tasks [repository](https://github.com/microsoft/azure-pipelines-tasks).
For my part, I can recommend splitting the build into two parts.

**Comment by erik-bershel** [comment]
In addition, I can say that out of interest I tried to reproduce the situation in the action environment and locally - the described behaviour is repeated.

**Comment by LiangZugeng** [comment]
@erik-bershel thanks for the reply, I would like to point out the issue doesn't exist in a self-hosted agent, we've been using the same method to build docker images for two years without issues until we switched to Microsoft-hosted agent.

One solution I'd come up with is exactly splitting the build into two or more Dockerfile files, the first Dockerfile is to build the source code, then another one to build the unit test image, and then a third one to build the final image, with both having appropriate tags. I will do some testing to validate the idea though.

Still I just want to know why the issue occurred, we used the exact same DockerCompose@0 task to build the image on both self-hosted and Microsoft-hosted agents, I can't imagine the task does an automatic intermediate image removal before it's finished on only Microsoft-hosted agent, so there must be something different in the two environments.

**Comment by erik-bershel** [comment]
> Still I just want to know why the issue occurred, we used the exact same DockerCompose@0 task to build the image on both self-hosted and Microsoft-hosted agents, I can't imagine the task does an automatic intermediate image removal before it's finished on only Microsoft-hosted agent, so there must be something different in the two environments.

This question can be best answered by the maintainers of the task. In fact, there could be many hypothetical reasons for this behaviour, but they all lie more likely on the side of the self-hosted runner, taking into account the fact that the locally installed composer repeats the specified behaviour. There may be a difference in versions of Docker or Composer and, as a result, in behaviour, perhaps there are some nuances of how the task works - the field is too large to guess right away.

**Comment by erik-bershel** [comment]
I would start by checking what composer your runners are using. I suspect that the reason lies there, but I could be wrong.

**Comment by LiangZugeng** [comment]
@erik-bershel Thanks for pointing me towards the right direction.

Yes, the issue was caused by different behaviors of different docker-compose versions, after further investigation, the docker-compose version running on our self-hosted agent is `1.27.4, build 40524192`, the one Microsoft-hosted agent installed is `1.29.2, build 5becea4c`, the docker engines on both machines are in version of `24.0.6`.

The difference I found is with 1.27.4, docker-compose didn't use buildkit, but with 1.29.2, it used buildkit, that's the only difference I observed. I also tried to download 1.29.2 on our self-hosted agent server, and the issue can be reproduced with the newer version.

I submitted a new issue in docker repo docker/for-mac#6988, hopefully someone from there can be of help.

As a workaround, I changed my build script and replaced DockerCompose@0 task with a script like below. This generates multiple tagged images for each build stage, and the script in the following build step can retrieve the intermediate images without any issue.

```
trigger:
  - main

pool:
  vmImage: "ubuntu-22.04"

steps:
  - script: |
      docker build -t dockerissue.repro:build --target build .
      docker build -t dockerissue.repro:testrunner --target testrunner .
      docker build -t dockerissue.repro:$(Build.BuildNumber) .
    displayName: "Build services"
    continueOnError: false

  - script: |
      docker images -a
      export unittestlayerid=$(docker images --filter "label=unittestlayer=true" -q)
      docker create --name unittestcontainer $unittestlayerid
      docker cp unittestcontainer:/testresults/ $(Build.ArtifactStagingDirectory)/testresults/
      docker stop unittestcontainer
      docker rm unittestcontainer
    displayName: "Retrieve Test and Coverage Results"
    continueOnError: false

```

**Comment by LiangZugeng** [comment]
@nicks replied on the issue, https://github.com/docker/for-mac/issues/6988, he confirmed that BuildKit only exports the final image and removes all intermediate images, so we revised our pipeline and used the workaround provided above to solve the problem. Now everything works fine.
