### ISSUE TITLE
Update JDK to 17 LTS

### ISSUE THREAD

**Issue by Eclion** [actions/runner-images#8358]
### Tool name

JDK

### Tool license

GNU General Public License, version 2, with the Classpath Exception

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17 LTS

### Brief description of tool

Please update JDK from 11 to 17 LTS.

I requested for Ubuntu 22, but I guess all images could benefit from this request.

### Provide a basic test case to validate the tool's functionality.

```bash
java --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

sure!

**Comment by Eclion** [comment]
This issue relates to #8336 where @4brunu requested the update to JDK 21.

as mentioned by @erik-bershel, JDK 21 is not available in [Adoptium](@4brunu JDK 21 is not yet available in [Adoptium](https://adoptium.net/en-GB/temurin/releases/) yet but JDK 17 is!

**Comment by erik-bershel** [comment]
Hey @Eclion! Java 17 is available on Ubuntu images. Please, use Java related actions or environment variables.
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java

**Comment by Eclion** [comment]
Hello @erik-bershel !
I am really sorry, I didn't realise the versions were installed, and I just have to update my JAVA_HOME env variable to the corresponding JAVA_HOME_{version}_X64 env var.
Thank you very much for your explanation!
