### ISSUE TITLE
Update NodeJS to 18.18.X

### ISSUE THREAD

**Issue by lvivski** [actions/runner-images#8368]
### Tool name

NodeJS

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

18.18.0

### Brief description of tool

Node.js® is an open-source, cross-platform JavaScript runtime environment.

### URL for tool's homepage

https://nodejs.org/en

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
NodeJS@18.17.X has a regression https://github.com/nodejs/node/issues/49330 that forced us to use v18.16.1. Since it's not pre-installed it has to be downloaded every time and creates unnecessary load on the NodeJS CDN, that sometimes fails. The issue has been fixed in NodeJS@18.18.0.
```

### Are you willing to submit a PR?

No

**Comment by mikhailkoliada** [comment]
Hello! It will be available in the images by the end if next week.

**Comment by codybak4** [comment]
Command‘deploy’: accepted not a bot @mikhailkoliada

**Comment by mikhailkoliada** [comment]
Deployed now

**Comment by lvivski** [comment]
Thank you!

**Comment by techieshark** [comment]
Just adding a link here, in case others were trying to figure out how a github actions runner update could cause their builds to fail after switching from 18.17 to 18.18, see this issue with NPM / Node - https://github.com/nodejs/node/issues/49737#issuecomment-1730808336
