### ISSUE TITLE
[All OS] Android NDK r23 will be removed from images on November 13

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#8383]
### Breaking changes

Android NDK r23 will be removed from all the images.

### Target date

Images deployment starts November 13, and will take 3-4 days.

### The motivation for the changes

According to our software support [policy](https://github.com/actions/runner-images#support-policy) we are installing 1 latest non-LTS and 2 latest LTS versions.

### Possible impact

if your workflows or pipelines depend on NDK r23 they might be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Nothing is required.

**Comment by cortinico** [comment]
> According to our software support [policy](https://github.com/actions/runner-images#support-policy) we are installing 1 latest non-LTS and 2 latest LTS versions.

Hey @mikhailkoliada 
Can you clarify this statement? As according to the NDK release history (https://developer.android.com/ndk/downloads/revision_history), NDK 23 and 25 should be the 2 latest LTS version, and NDK 24 should be the 1 latest non-LTS version.

**Comment by mikhailkoliada** [comment]
@cortinico hey

23 - LTS
24 - latest non-LTS
25 - LTS
26 - LTS but not mentioned in history, only at the main download page

**Comment by cortinico** [comment]
Great thanks for the clarification @mikhailkoliada

**Comment by WorexSDK** [comment]
Slll.yty

**Comment by twofingerrightclick** [comment]
Is this an expected side affect of the upgrade turnover? 
`error NETSDK1147: To build this project, the following workloads must be installed: maui-android [D:\a\1\s\Foo.App.Maui\Foo.App.Maui.csproj::TargetFramework=net7.0-android]
`
With: 
Agent machine name: 'fv-az490-897'
Current agent version: '3.230.0'
Operating System
Runner Image
Image: windows-2022
Version: 20231115.2.0

**Comment by mikhailkoliada** [comment]
Rolled out
