### ISSUE TITLE
Add Node 20

### ISSUE THREAD

**Issue by mikeharder** [actions/runner-images#8386]
### Tool name

Node

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

20

### Brief description of tool

Please add Node 20 to the set of cached Node versions, alongside 14, 16, and 18.  We need to test on Node 20, and we can download the version during our build using the `NodeTool` task, but the download sometimes fails or is really slow.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ilia-shipitsin** [comment]
@mikeharder , did you consider using cache ? so, you can install it once and use cached version

**Comment by mikeharder** [comment]
Why not add Node Current?  The images include .NET Core Latest which seems equivalent.

**Comment by mikhailkoliada** [comment]
@mikeharder support policy us a result of customer demand, it does not mean we are supporting only latest or only LTS, we try to satisfy most customers demand and every single change must be discussed. CC @samvantran @Steve-Glass @lkfortuna

**Comment by ilia-shipitsin** [comment]
I see the following options

1) modifying policy / adding a tool
2) using cache 
3) using nodejs containers, GHA notation
```
      runs-on: ubuntu-latest
      container:
        image: somenodejsimage:sometag
```
