### ISSUE TITLE
Task "UseDotNet@2" does not use pre-installed versions

### ISSUE THREAD

**Issue by mikeharder** [actions/runner-images#8387]
### Description

My understanding is task `UseDotNet@2` is supposed to prefer using a pre-installed version of .NET if it matches the requested version, and only download .NET when necessary.  However, the task appears to ignore the pre-installed versions, and always downloads .NET, even if the version exactly matches what is pre-installed.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
Version: 20230917.1.0

### Is it regression?

unknown

### Expected behavior

Task to use `dotnet` binaries pre-installed in image.

### Actual behavior

Task always downloads and installs binaries.

### Repro steps

This yml:

```yml
steps:
  - script: dotnet --info

  - task: UseDotNet@2
    inputs:
      version: 6.x

  - task: UseDotNet@2
    inputs:
      version: 7.x
```

Outputs this:

```
$ dotnet --info
.NET SDKs installed:
  6.0.414 [/usr/share/dotnet/sdk]
  7.0.111 [/usr/share/dotnet/sdk]
  7.0.203 [/usr/share/dotnet/sdk]
  7.0.308 [/usr/share/dotnet/sdk]
  7.0.401 [/usr/share/dotnet/sdk]

Tool to install: .NET Core sdk version 6.x.
Found version 6.0.414 in channel 6.0 for user specified version spec: 6.x
get-os-distro: Error: Distribution specific OS name and version could not be detected: UName = Linux
Version 6.0.414 was not found in cache.

Tool to install: .NET Core sdk version 7.x.
Found version 7.0.401 in channel 7.0 for user specified version spec: 7.x
get-os-distro: Error: Distribution specific OS name and version could not be detected: UName = Linux
Version 7.0.401 was not found in cache.
```

Command `dotnet --info` confirms the requested versions are installed, but the task is not installing them.

Related: https://github.com/microsoft/azure-pipelines-tasks/issues/19019

**Comment by ilia-shipitsin** [comment]
thanks, we'll have a look.
however, if you state that task is not doing what is expected to do, it looks like it is a responsibility of that task.

**Comment by ilia-shipitsin** [comment]
let's close the issue. feel free to reopen if after investigation it will appear on imagen side

**Comment by mikeharder** [comment]
@ilia-shipitsin: I think there is an implicit contract between the task and the .NET SDKs pre-installed in the image, that is currently broken.  I do not know which side has broken the contract, but it would be great if someone could figure this out.

**Comment by ilia-shipitsin** [comment]
yes, but on the imagegen side we do not know how to investigate WHY that task cannot use pre-installed versions.
