### ISSUE TITLE
Convert managed image to VHD step fails when copying VHD blob

### ISSUE THREAD

**Issue by Kyronn94** [actions/runner-images#8392]
### Description

The 'az storage blob copy start' command in the 'convert-to-vhd.ps1' script fails with:
'ERROR: the following arguments are required: --destination-blob/-b, --destination-container/-c'

This occurs when the value of $sourceDiskUri contains special characters such as '&' which are common in SAS URLs.

This might be a regression caused by this commit:
https://github.com/actions/runner-images/commit/276efb2a890cfff16ded7c4e4b366b48202dcbeb

Wrapping $sourceDiskUri in triple double quotes seems to fix this:
$sourceDiskUri = """{0}""" -f $sourceDiskUri

This was remove as part of the above commit.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Latest - 20230924.1.0

### Is it regression?

Yes - 20230910.1.0

### Expected behavior

convert-to-vhd.ps1 script completes without errors and VHD blob is correctly created.

### Actual behavior

convert-to-vhd.ps1 script fails if there are special characters in the $sourceDiskUri variable.

### Repro steps

1. Run windows2022.yml pipeline from runner-images repository

**Comment by Alexey-Ayupov** [comment]
Hello @Kyronn94. We do not recommend using pipelines and scripts from the [images.CI](https://github.com/actions/runner-images/tree/main/images.CI) directory. They are configured for our environment. However, I can try to explain what was the reason for removing quotes from the variable.

As you can see we pass the `$sourceDiskUri` variable as a parameter to the next Az CLI command. 
In PowerShell v5 it was mandatory to put `$sourceDiskUri` variable in double quotes. But in PowerShell v7 it is vice versa, the `$sourceDiskUri` variable should not have any quotes.

It looks like by default you are using PowerShell v5, if it is not a strict condition, I would suggest you switch to the PowerShell v7. It should help.
