### ISSUE TITLE
MinGW misconfiguration results in run-time library mismatch

### ISSUE THREAD

**Issue by TheMostDiligent** [actions/runner-images#8399]
### Description

This [discussion thread](https://github.com/actions/runner-images/discussions/8372) revealed that MinGW installation is not properly configured.
In particular, applications built with MinGW require that c++ run-time library `libstdc++-6.dll` is loaded by the application.
MinGW packages have these libraries in the bin folder.
In the runner image, MinGW DLLs are located in `C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin`, but this directory is not in the `PATH`. However, other packages install mingw, so `libstdc++-6.dll` can be found at another locations:

```
where.exe libstdc++-6.dll:
C:\Program Files\Git\mingw64\bin\libstdc++-6.dll
C:\Strawberry\c\bin\libstdc++-6.dll
C:\Strawberry\perl\bin\libstdc++-6.dll
```

So applications built with MinGW used to pick up `libstdc++-6.dll`  installed by git. This worked fine until MinGW in the most recent image was updated to use UCRT, which made `libstdc++-6.dll` from MinGW installation incompatible with other DLLs from other packages that use `msvcrt.dll`. As a result, any application built with MinGW will fail to start in the latest runner image.

The following workaround that tweaks the path before launching the application fixes the problem:

```
PATH="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH"
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230918.1.0

### Is it regression?

Yes, 20230910.1.0

### Expected behavior

`libstdc++-6.dll` from MinGW installation is found in the PATH

### Actual behavior

`libstdc++-6.dll` from `C:\Program Files\Git\mingw64\bin` is found

### Repro steps

Any application built with MinGW on the latest runner image will fail to start because of the run-time library mismatch.

**Comment by ilia-shipitsin** [comment]
yes, windows linker indeed loads libraries from PATH. it is a feature.
also, we install strawberry perl, it requires to be added to PATH

well, I do not think we can do anything here. deinstall strawberry perl ? do not add it to PATH ?

I wonder if it is possible to use RPATH or RUNPATH equialent during linking on MinGW in order to pick particular library

**Comment by vpolikarpov-akvelon** [comment]
Hey @TheMostDiligent. Thank you for your investigation.

We are installing MinGW using chocolatey. I examined installation script in the package and found that it sets PATH for User (that is different during build), but not for Machine, so directory is absent of PATH for runner user. I will prepare a solution for that and let you know. Till than please modify PATH yourself.

**Comment by TheMostDiligent** [comment]
Another thing I noticed is that in MinGW package, `gcc.exe` and all `DLLs` are all located in the `bin` folder.
In the runner image, however, the gcc is found in `C:/ProgramData/chocolatey/bin/`, but DLLs are not there.

This might be a tricky issue as if the MinGW installation directory goes first in the path, other apps (e.g. git) may fail to run because now they will pick up incompatible `libstdc++-6.dll`

**Comment by ChrisThrasher** [comment]
http://disq.us/p/2uv00vh

MinGW 13 as provided by Chocolatey may actually switch back to the same Libc implementation that version 11 uses if I'm understanding this comment correctly. Is it feasible to skip MinGW 12 to avoid this problem entirely pending the official release of that Chocolatey package in the near future? I'm sure many users would appreciate the additional features that MinGW 13 provides anyways.

**Comment by TheMostDiligent** [comment]
Another strange thing: I am trying to add MinGW installation directory to PATH:
```
echo "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin" >> $GITHUB_PATH
```

It does prepend most other paths [as the documentation describes](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path), except for three:

```
PATH: /mingw64/bin:/usr/bin:/c/Users/runneradmin/bin:/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:...
```

It appears like `/mingw64/bin` is forced to always be first in the PATH. I assume this is by design?

**Comment by vpolikarpov-akvelon** [comment]
@TheMostDiligent, taking into account all strange things about chocolatey package you mentioned above I' going to try to get rid of it and install MinGW manually. It would provide us more control and better understanding of what and how we install.

**Comment by TheMostDiligent** [comment]
@vpolikarpov-akvelon I think that adding mingw64 installation directory to `PATH` may be the least intrusive way. Some projects may rely on a specific location of mingw64 binaries.

**Comment by mikhailkoliada** [comment]
Deployed now, closing

**Comment by TheMostDiligent** [comment]
So what is the solution that you implemented?

**Comment by SuraRengoku** [comment]
> http://disq.us/p/2uv00vh
> 
> MinGW 13 as provided by Chocolatey may actually switch back to the same Libc implementation that version 11 uses if I'm understanding this comment correctly. Is it feasible to skip MinGW 12 to avoid this problem entirely pending the official release of that Chocolatey package in the near future? I'm sure many users would appreciate the additional features that MinGW 13 provides anyways.

I installed MinGW 13.2.0 the problem still exists. seems like they did not fix it
