### ISSUE TITLE
Fastlane not using the version present on cloud macos image

### ISSUE THREAD

**Issue by salvatoreboemia** [actions/runner-images#8400]
### Description

Using the github actions and fastlane, I noticed that I get an update warning

`fastlane 2.216.0 is available. You are on 2.214.0`

But shouldn't it automatically use the latest version present on the runner-image?

Is there anything to change or modify in the gem file or anything?

Thank you

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos 12 xl

### Is it regression?

no

### Expected behavior

use the version present in the cloud

### Actual behavior

using the old version

### Repro steps

No step

**Comment by erik-bershel** [comment]
Hey @salvatoreboemia! Issue might be related to the image inconsistency for macOS-12 XL. May I ask you to share log or screenshoot with the image version?

**Comment by erik-bershel** [comment]
@salvatoreboemia FYI:
> But shouldn't it automatically use the latest version present on the runner-image?

Yes, but. If you do not have a `fastlane` version pinned in your project, the one installed in the image will be picked up. And here several factors come into play. There can be two versions of an image in production at the same time. The previous release and the current release that is in progress. If you look at the composition of the images, you will notice that the current release contains just the latest `fastlane`. But it’s not a fact that you came across exactly such an agent - there are still many agents that have not been updated to the latest version. Previous agent contain exactly the `2.214.0` version, so I guess you took this image.

> Is there anything to change or modify in the gem file or anything?
You may use this [guide](https://docs.fastlane.tools/actions/update_fastlane/).

**Comment by salvatoreboemia** [comment]
> Hey @salvatoreboemia! Issue might be related to the image inconsistency for macOS-12 XL. May I ask you to share log or screenshoot with the image version?

<img width="960" alt="Screenshot 2023-09-28 at 14 13 14" src="https://github.com/actions/runner-images/assets/20614870/f578955c-942d-4f6c-a77f-a5c95fd64afe">


> @salvatoreboemia FYI:
> 
> > But shouldn't it automatically use the latest version present on the runner-image?
> 
> Yes, but. If you do not have a `fastlane` version pinned in your project, the one installed in the image will be picked up. And here several factors come into play. There can be two versions of an image in production at the same time. The previous release and the current release that is in progress. If you look at the composition of the images, you will notice that the current release contains just the latest `fastlane`. But it’s not a fact that you came across exactly such an agent - there are still many agents that have not been updated to the latest version. Previous agent contain exactly the `2.214.0` version, so I guess you took this image.
> 
> > Is there anything to change or modify in the gem file or anything?
> 
> You may use this [guide](https://docs.fastlane.tools/actions/update_fastlane/).

Ok I got it

I have a fastlane file

Basically I need to add only this one row to avoid to use an old version

Like this oen

```
before_all do
  update_fastlane
end
```

right?


For exemple now I change with macos 13 xl, and is using the latest version

<img width="165" alt="Screenshot 2023-09-28 at 14 05 12" src="https://github.com/actions/runner-images/assets/20614870/8b604659-512a-4b6e-bcae-5bce835a252c">
 
Thanks

**Comment by erik-bershel** [comment]
@salvatoreboemia indeed correct - I'm glad it worked out for you.
Judging by the screenshot, the situation is exactly the one I mentioned - the agent has not yet received the latest updates. When this happens, your pipeline will save a few seconds on updating. Considering that this is a normal situation for an image during the delivery process, I am forced to close this issue. If you have any questions regarding the topic under discussion, you can contact me right here. In case of other concerns, please feel free to open a new issue.
