### ISSUE TITLE
Add more simulators in Xcode 15.0

### ISSUE THREAD

**Issue by amseddi** [actions/runner-images#8402]
### Tool name

Xcode 15.0

### Tool license

NA

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16.4 Simulators

### Brief description of tool

Add more simulators for Xcode 15.0 or at least iOS 16.4

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ilia-shipitsin** [comment]
I created small repro

```
          brew install xcodesorg/made/xcodes
          xcodes runtimes --include-betas
```

https://github.com/ilia-shipitsin/xcodes15-runtimes/actions/runs/6337845954/job/17213741033


iOS 16.4 is already there

**Comment by ilia-shipitsin** [comment]
![image](https://github.com/actions/runner-images/assets/125650415/acc63308-e4a1-4dad-9814-50b305c55bb4)

**Comment by amseddi** [comment]
I am referring to this:
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#installed-simulators

As you can see, only iOS 17.0 simulator is available in Xcode 15.0

**Comment by amseddi** [comment]
> I created small repro
> 
> ```
>           brew install xcodesorg/made/xcodes
>           xcodes runtimes --include-betas
> ```
> 
> https://github.com/ilia-shipitsin/xcodes15-runtimes/actions/runs/6337845954/job/17213741033
> 
> iOS 16.4 is already there

In this build you are using Xcode 14.3.1 as it is the default and it has iOS 17.0 and 16.4 simulators
(https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode)

**Comment by amseddi** [comment]
FYI This would help speeding some build times as there is a known issue with iOS 17 simulators performance 

https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Known-Issues
> Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776) (FB12237092)

**Comment by amseddi** [comment]
FYI This would help speeding some build times as there is a known issue with iOS 17 simulators performance

https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Known-Issues

Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776) (FB12237092)

**Comment by ilia-shipitsin** [comment]
we investigate simulators

https://github.com/actions/runner-images/issues/8023
https://github.com/actions/runner-images/issues/7971


thanks for the tip, performance of simulators is currently poor

**Comment by ilia-shipitsin** [comment]
> ntains iOS 17.0 and 16.4 simulator

simulators are system wide as far as I know.

I'll check with xcode-select a little bit later

**Comment by amseddi** [comment]
Not necessarily 
I forked your sample repo and selected Xcode 15.0 (https://github.com/amseddi/xcodes15-runtimes)

And this is the result:
https://github.com/amseddi/xcodes15-runtimes/actions/runs/6338503994/job/17215753615
<img width="323" alt="image" src="https://github.com/actions/runner-images/assets/1511694/4d6cd23b-0b55-4347-88c5-f1b952b1bbf9">

**Comment by ilia-shipitsin** [comment]
interesting. let me check it

**Comment by ilia-shipitsin** [comment]
I tried to install on clean vm.

I installed XCode-14.3.1, XCode-15.0.0, I did "xcode-select" and then "xcodebuild  -downloadAllPlatforms".

even running "xcode-select" did not change anything. I see iOS-16.4 is available for XCode-14.3.1 and iOS-17.0 for XCode-15.0.0

what is your local experience ? what do you see running "xcodes runtimes" ?
if you have it working locally and you can tell us how to install simulators, we can try

**Comment by ilia-shipitsin** [comment]
for example

```
Mac-mini:~ runner$ sudo xcode-select -s /Applications/Xcode-15.0.0.app/
Mac-mini:~ runner$ xcodebuild  -downloadPlatform 'iOS 16.4'
Could not find platform: iOS 16.4
Mac-mini:~ runner$
```

**Comment by ilia-shipitsin** [comment]
also, I do not see an evidence that XCode 15 supports "iOS 16.4" officially

https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes

![image](https://github.com/actions/runner-images/assets/125650415/271663c5-8165-46a4-b23d-dcff09e813de)

please elaborate with "iOS 16.4" support on XCode 15. if you have it working on your local Mac, please share details how did you install it

**Comment by amseddi** [comment]
I usually add it using the Xcode user interface.

- Go to`Settings > Platforms`
<img width="942" alt="Screenshot 2023-09-29 at 09 40 14" src="https://github.com/actions/runner-images/assets/1511694/a5093413-e5ef-462c-bf25-9da8a635ac11">

- Click on `+ > iOS Simulators` and then select and download iOS 16.4
<img width="942" alt="Screenshot 2023-09-29 at 09 40 29" src="https://github.com/actions/runner-images/assets/1511694/da69ef40-b3ee-4c7c-999c-6df12cd36870">

The Apple documentation explains how to do it from the command line but you need to download the dmg first
https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes

**Comment by amseddi** [comment]
And reading the doc [xcodes](https://github.com/XcodesOrg/xcodes/tree/1.4.1#install-runtimes-) can install runtimes too
```sh
xcodes runtimes install "iOS 16.4"
```

**Comment by ilia-shipitsin** [comment]
![image](https://github.com/actions/runner-images/assets/125650415/f4a7e179-9c59-48fa-b711-3c6c71fa17e8)

**Comment by ilia-shipitsin** [comment]
@amseddi , I suggest you to try installing it within your pipeline (yes, it takes time). as for installing - it looks like it can be installed that way.  why I'm asking to try - I'm not sure whether it will work.

if that works and you confirm that, we can install it

**Comment by amseddi** [comment]
I could add it successfully to my workflow
<img width="484" alt="image" src="https://github.com/actions/runner-images/assets/1511694/7b3f8378-5898-4bfd-8e1c-ed946dd1b518">
And I am seeing better tests execution times than with the 17.0 simulator.

**Comment by amseddi** [comment]
We could add it to the workflow cache but IMO it is better to add it to the runner so everyone can profit from this.

**Comment by ilia-shipitsin** [comment]
no, I do not mean cache as long-term approach, it's just for testing. Since you confirm it works for you, thanks, we'll discuss internally adding runtimes.

**Comment by amseddi** [comment]
I found this action that could does runtime install + cache: https://github.com/muukii/actions-xcode-install-simulator

**Comment by AlexCookeTrader** [comment]
I'm also having the same issue where build times are identical across 14.2 and 15, yet test runs on iOS17 simulators have taken us over our 1 hour limit for individual jobs. Hoping for an update with iOS 6.4 support soon.

**Comment by ilia-shipitsin** [comment]
action https://github.com/muukii/actions-xcode-install-simulator is good indeed. 
maybe, we can leave images small and required runtimes can be installed (and cached) by that action

**Comment by amseddi** [comment]
Maybe you could have a rule of adding the previous runtime with each new version of Xcode 🤔

**Comment by joshuapoq** [comment]
If this may take a while could we look to get the Xcode 15.1 beta added to the runners?
> Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776)

**Comment by eseay** [comment]
Bumping this issue. My specific use case is:
- We are compiling our apps/packages with Xcode 15.x
- Need to execute unit tests against iOS 16.4 (at least - ideally also iOS 15)
- Installing these simulators at runtime is a non-starter because of the performance and time cost.

**Comment by AlexCookeTrader** [comment]
Bumping this issue as it is currently blocking our team. Hoping that the simulator performance issues are being addressed.

**Comment by amseddi** [comment]
@ilia-shipitsin Do you have any news on this issue?

**Comment by ilia-shipitsin** [comment]
> @ilia-shipitsin Do you have any news on this issue?

please speak to @mikhailkoliada 
I cannot make a decision unfortunately

**Comment by einar-notland** [comment]
This might be of help. We currently use this step in our CI workflow to run tests on 16.4 simulator. The step creates a simulator called "iPhone 13" so we can reference it in our fastlane scan.

```
- name: Link to 16.4 Simulators
        run: |
          echo "Creating Runtimes folder if needed..."
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          echo "Creating symlink of the iOS 16.4 runtime..."
          sudo ln -s /Applications/Xcode_14.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 16.4.simruntime
          xcrun simctl create "iPhone 13" "com.apple.CoreSimulator.SimDeviceType.iPhone-13" "com.apple.CoreSimulator.SimRuntime.iOS-16-4"
```

**Comment by AlexCookeTrader** [comment]
> This might be of help. We currently use this step in our CI workflow to run tests on 16.4 simulator. The step creates a simulator called "iPhone 13" so we can reference it under devices in our [fastlane scan](https://docs.fastlane.tools/actions/scan/).
> 
> ```
> - name: Link to 16.4 Simulators
>         run: |
>           echo "Creating Runtimes folder if needed..."
>           sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
>           echo "Creating symlink of the iOS 16.4 runtime..."
>           sudo ln -s /Applications/Xcode_14.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 16.4.simruntime
>           xcrun simctl create "iPhone 13" "com.apple.CoreSimulator.SimDeviceType.iPhone-13" "com.apple.CoreSimulator.SimRuntime.iOS-16-4"
> ```

I'm seeing some good results with this! However it would seem the coverage results are not being generated or saved in the usual spot using this method. Going to keep digging for now unless anyone has encountered and resolved this issue.

**Comment by mikhailkoliada** [comment]
Hello and sorry for long delay! We do not plan providing additional simulators (other than the ones which come in stock with the release) as a part of the macOS runners, because we can not guarantee it will work well (or if it will work at all), please use additional 3rd party tools to install the versions you need in runtime.
