### ISSUE TITLE
Ubuntu 22/04 version 20230924.1.0 does not generate androidx.databinding.DataBindingComponent

### ISSUE THREAD

**Issue by stspenke** [actions/runner-images#8409]
### Description

Since the update to version 20230924.1.0 the build actions for my project fail because the androidx.databinding.DataBindingComponent class is not generated. That is the only error I see, I can't find the reason for this class not being generated anymore.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

version 20230924.1.0

### Is it regression?

Yes, it worked fine with version 20230917.1.0

### Expected behavior

I expect my project to build successfully as it did with the previous version of the runner. 

### Actual behavior

Since the update to version 20230924.1.0 the build actions for my project fail because the androidx.databinding.DataBindingComponent class is not generated. That is the only error I see, I can't find the reason for this class not being generated anymore.

### Repro steps

Execute any build of my project

**Comment by ilia-shipitsin** [comment]
@stspenke , do you a link to some failed build ?

**Comment by stspenke** [comment]
@ilia-shipitsin certainly: https://github.com/FDMediagroep/fd-android/actions/runs/6339219131

**Comment by ilia-shipitsin** [comment]
is it private ?

![image](https://github.com/actions/runner-images/assets/125650415/b6fb4c9f-1400-4f60-8ec1-a2db63e67fc1)

**Comment by stspenke** [comment]
Yes, it is.
I'm afraid I can't give access to our project.

**Comment by ilia-shipitsin** [comment]
well, we need some repro steps to try.

**Comment by ilia-shipitsin** [comment]
sorry, we do not have repro steps to investigate. I'm closing the issue.
feel free to reopen once repro is known
