### ISSUE TITLE
Add kwok/kwokctl

### ISSUE THREAD

**Issue by wzshiming** [actions/runner-images#8424]
### Tool name

kwok/kwokctl

### Tool license

Apache-2.0 license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

100M

### Brief description of tool

Kubernetes WithOut Kubelet - Simulates thousands of Nodes and Clusters.

### URL for tool's homepage

https://kwok.sigs.k8s.io/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Tool installation time in runtime

1 minute

### Are you willing to submit a PR?

Yes

**Comment by Alexey-Ayupov** [comment]
Hello @wzshiming, we will take a look.

**Comment by Alexey-Ayupov** [comment]
Hello! Given the big application size and low demand we would not like to pre-install the tool into the image also because of maintenance concerns, please continue installing in runtime.
