### ISSUE TITLE
Update to PowerShell 7.3

### ISSUE THREAD

**Issue by ld0614** [actions/runner-images#8436]
### Tool name

PowerShell 7.3

### Tool license

First Party Software

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Latest Stable Version

### Brief description of tool

I understand and appreciate the rationale for only supporting the LTS versions of PowerShell, unfortunately other teams within Microsoft such as the Bicep Language team (https://github.com/PSBicep/PSBicep) are requiring the use of the latest stable version and not the latest LTS edition. 

While there is a workaround DevOps task suggested, this is not first party and has a very low number of installs making it a high risk deployment to a number of my customers. 

Having the latest stable version of PowerShell installed would mitigate these issues and would provide a local-like environment, reducing the changes of confusion between a local developer workstation operating on latest stable and the hosts on LTS.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
Hello, @ld0614. Due to a lot of customers currently using PowerShell v7.2, we would like to not upgrade to the 7.3 version cause it potentially can break a lot. However, you can still update its runtime.
If you have other questions feel free to reach us.
