### ISSUE TITLE
[macOS] Apple Silicon (M1) powered macOS runners are now available in public beta!

### ISSUE THREAD

**Issue by Steve-Glass** [actions/runner-images#8439]
### Breaking changes

To try the new Apple silicon macOS larger runner, update the `runs-on:` key in your GitHub Actions YAML workflow YAML file to target `macos-latest-xlarge` or `macos-13-xlarge`. The 12-core macOS larger runner is moving from xlarge to large, and is still available by updating the `runs-on:` key to `macos-latest-large`, `macos-12-large`, or `macos-13-large`. There is no sign-up required for the beta and the runner is immediately available to all developers, teams, and enterprises.

- [Blog Post](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/)
- [Documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners)
- [Pricing](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates)

### Target date

N/A

### The motivation for the changes

N/A

### Possible impact

N/A

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [x] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

N/A

**Comment by jpomykala** [comment]
Yes! 🙌

**Comment by oscarsj** [comment]
Thanks for the hard work, this will be incredible useful for Code Scanning pipelines! ❤️ 
One question @Steve-Glass, what's the status of SIP ([System Integrity Protection](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)) on these runners, is it enabled or disabled? 

Thanks all the team again for making this happen so timely!

**Comment by hamaney** [comment]
> Thank you for providing Apple Silicon macOS runners! 🙌

Thank you for paying 10x factor 👍

**Comment by letmaik** [comment]
Will M1 runners be available for free for public projects? I just tried to use it and got:

> The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

**Comment by fkorotkov** [comment]
Why the VM has access to only 6 out of 8 M1 cores? Genuinely curious because a lot of [Tart](https://tart.run/) users use it for managing VMs for self-hosted GitHub Actions Runners. So far there were no reports from people running VMs that fully utilize cores and memory of M1/M2 chips. I wonder if you found some macOS/Actions limitation in your extensive private beta testing?

**Comment by joeyparrish** [comment]
It seems M1 is currently tied to the "large" or "XL" runners for a fee.  Will there be small M1 runners available for free for public projects?

**Comment by DelevoXDG** [comment]
Seems like the Android SDK is missing in the new runner: https://github.com/actions/runner-images/blob/375e9a1c270ec81a3ffd5b429dcdee9508b46124/images/macos/macos-13-arm64-Readme.md

**Comment by ychin** [comment]
> It seems M1 is currently tied to the "large" or "XL" runners for a fee. Will there be small M1 runners available for free for public projects?

Same question here. I have been holding off in adding an Apple Silicon CI pipeline for my project because I knew GitHub had this in their roadmap and wanted to wait for it as I prefer just managing one single CI system. If there is no plan in foreseeable future that would allow open source projects to use Apple Silicon in free-tier CI that would be really useful to know as it would save us time and we can decide appropriately.

**Comment by shepmaster** [comment]
> Seems like the Android NDK is missing in the new runner

There are a number of packages available in the x86_64 runner that are not in the Apple Silicon runner (the one I noticed missing was `aws`). Would it be possible to get a hint on if these packages absence is transient or permanent? If it's permanent, we can change our CI config appropriately; if it's transient we can wait for them to be fully matched.

Thank you!

**Comment by jorgegarciarey** [comment]
When will be theses macOS runners available from Azure DevOps? @Steve-Glass

**Comment by xanather** [comment]
Is is possible to use enterprise entitlement minutes on these runners...? Seems like it's specific to larger runners only.

**Comment by theofficialgman** [comment]
Great, now lets get most requested [ARM Linux runners](https://github.com/actions/runner-images/issues/5631) on the roadmap!

**Comment by martinbonnin** [comment]
Hi 👋  the images seem to be missing at least:

* Android SDK
* Chrome Browser

See also [previous comment](https://github.com/actions/runner-images/issues/8439#issuecomment-1743638467)

Are there any plans to add those?

**Comment by 05nelsonm** [comment]
Anyone using this for Kotlin Multiplatform will be sorely disappointed. It still builds for `x86_64` and skips all simulator/arm tests.

**Comment by mikhailkoliada** [comment]
@martinbonnin re chrome and android sdk it is still pending, no guarantee we will add it but we investigating, re AWS, no, there is no plan to add it anymore please install in runtime

**Comment by alexander-efremov** [comment]
Hey team,
We found that the action **apple-actions/download-provisioning-profiles@v1** very often fails with error exactly on `macos-13-xlarge` images:

```
Error: {
	"errors": [{
		"status": "401",
		"code": "NOT_AUTHORIZED",
		"title": "Authentication credentials are missing or invalid.",
		"detail": "Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens"
	}]
}
```
And it works perfectly on the macos-13-xl images.

**Comment by FrankSolleveld** [comment]
> When will be theses macOS runners available from Azure DevOps? @Steve-Glass

Would love to know this as well since our build times are 45 minutes when it could easily be less with M1 machines.

**Comment by prattcmp** [comment]
What about Linux arm64?

**Comment by nschonni** [comment]
@prattcmp that's tracked on https://github.com/actions/runner-images/issues/5631, and not related to this thread

**Comment by prattcmp** [comment]
> @prattcmp that's tracked on https://github.com/actions/runner-images/issues/5631, and not related to this thread

But its locked as off topic?

**Comment by wayson** [comment]
Do you know why we can't use the xlarge runnners in Azure Devops?

**Comment by cqc-alec** [comment]
Maybe this is as good a place to ask as any, and related to the Linux-arm64 question above: has anyone managed to get docker working on the new macos-13-xlarge images? If so would they mind sharing how they did it?

**Comment by Steve-Glass** [comment]
👋 I am closing this issue as it is just an announcement of M1 runner availablity. If you have any questions or need any additional software installed, please submit a software request. TIA! 

> Will M1 runners be available for free for public projects? I just tried to use it and got:
> >  The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

This will happen but the date is TBD. GitHub is responsible for the provisioning of all Mac hardware in Azure data centers. Our team is ramping up capacity in preparation for[ GA in Jan-Mar 2024 timeframe](https://github.com/github/roadmap/issues/819). Once we reach the GA milestone, we will start working on additional plans to support open source, along with new macOS runners.  

> What about Linux arm64?

This is something our team is preparing for. Please keep an eye out for a public roadmap item in the next few months! 

> has anyone managed to get docker working on the new macos-13-xlarge images? If so would they mind sharing how they did it?

https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#limitations-for-macos-larger-runners

**Comment by James-Mart** [comment]
Would be great if you could add docker to the new runners as well.

**Comment by kgantchev** [comment]
Hi all... you can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's.

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Comment by yurijmikhalevich** [comment]
@joeyparrish, GitHub Actions added support for `macos-14`, which is Apple Silicon and available for free to the public repositories.

https://github.com/github/roadmap/issues/926
https://github.com/actions/runner-images?tab=readme-ov-file#available-images

**Comment by joeyparrish** [comment]
Thanks!  I have already started using it.
