### ISSUE TITLE
Checksum verification failed for pypy3.9-v7.3.13-win64.zip during packer build of Windows 2022 image

### ISSUE THREAD

**Issue by bvaughan527** [actions/runner-images#8440]
### Description

When the Windows Server 2022 packer build executes the below steps, the checksum of the file fails with error included in this description.

**Packer build executes:**
azure-arm.image: Found PyPy 'pypy3.9-v7.3.13-win64.zip' package
    azure-arm.image: Downloading package from: https://downloads.python.org/pypy/pypy3.9-v7.3.13-win64.zip to path C:\Users\packer\AppData\Local\Temp\pypy3.9-v7.3.13-win64.zip .
    azure-arm.image: Package downloaded successfully in 0.11 seconds

**Checksum verification failure:**
==> azure-arm.image:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
==> azure-arm.image: Checksum verification failed. Expected hash: 55ab1c7ba3c3bf04d3acba15eeee3e2e6a185e7a6cb80dd4c0ee2d804a78b4a3; Actual
==> azure-arm.image: hash: 09EA41154AD1DCD3E8378609A73196A6C108B17AA05EF3CBB240610744102803.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:658 char:9
==> azure-arm.image: +         throw "Checksum verification failed. Expected hash: $Distribu ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Checksum verifi...40610744102803.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Checksum verification failed. Expected hash: 55ab1c7ba3c3bf04d3acba15eeee3e2e6a185e7a6cb
==> azure-arm.image:    80dd4c0ee2d804a78b4a3; Actual hash: 09EA41154AD1DCD3E8378609A73196A6C108B17AA05EF3CBB240610744102803.
==> azure-arm.image:

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

This occurs when building the latest Windows Server 2022 runner image: 
OS Version: 10.0.20348 Build 1970
Image Version: 20230924.1.0

### Is it regression?

No. Appears that a newer version than 3.9.17 [PyPy 7.3.12] is being installed.

### Expected behavior

File checksum should pass.

### Actual behavior

File checksum is failing and as a result, the Packer build fails.

### Repro steps

Attempt to build the Windows Server 2022 image following the instructions in the runner-images repo documentation here: https://github.com/actions/runner-images/blob/releases/win22/20230924/docs/create-image-and-azure-resources.md

Review build logs when packer build fails and generates the error provided in the issue description.

**Comment by Alexey-Ayupov** [comment]
Hello, @bvaughan527. This issue was fixed by this PR - https://github.com/actions/runner-images/pull/8429.
Please update your fork and try one more time.

**Comment by bvaughan527** [comment]
Thank you Alexey, I will give it another try and advise of results.

**Comment by erik-bershel** [comment]
Hi @bvaughan527!
Happy to see that my PR helped you. Since the issue resolved I'm going to close it. Please feel free to open new one in case of other concerns.
