### ISSUE TITLE
Install-AzureDevOpsCli.ps1 script fails when building Windows Server 2022 runner image

### ISSUE THREAD

**Issue by bvaughan527** [actions/runner-images#8457]
### Description

The Install-AzureDevOpsCli.ps1 script fails when building Windows Server 2022 runner image and results in the build process failing with the below error:

2023-10-03T18:42:17.0472425Z [1;31m==> azure-arm.image: ERROR: (1312, 'CredRead', 'A specified logon session does not exist. It may already have been terminated')[0m
2023-10-03T18:42:17.9033617Z [1;31m==> azure-arm.image: ERROR: (1312, 'CredRead', 'A specified logon session does not exist. It may already have been terminated')[0m

As a result, no image is built.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image Version: 20230924.1.0

### Is it regression?

Yes: 20230903.2

### Expected behavior

The Install-AzureDevOpsCli.ps1 script should complete successfully with an exit code of 0.

### Actual behavior

The Install-AzureDevOpsCli.ps1 script throws an error and results in the below error:

Some builds didn't complete successfully and had errors:
2023-10-03T20:33:40.7770130Z --> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

### Repro steps

1. Follow the instructions in the document at this link: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md.
2. Attempt to build a Windows Server 2022 image and get the failure messages provided in this issue log.

**Comment by vpolikarpov-akvelon** [comment]
Hey @bvaughan527. These error messages seem to pop up during the az-devops warmup process, and they're actually pretty normal. However, it would be super helpful if you could share more details from your build log. Could you provide the entire build journal and let us know the exact command you used? That way, we can pinpoint the issue more accurately and provide you with a better solution. Thanks!

**Comment by bvaughan527** [comment]
Hi @vpolikarpov-akvelon, please find attached the full build log from our Azure pipeline that builds the Windows 2022 image.
[dev.azure.com_nbadev_build_builds_277533_logs_27.txt](https://github.com/actions/runner-images/files/12803443/dev.azure.com_nbadev_build_builds_277533_logs_27.txt)

**Comment by vpolikarpov-akvelon** [comment]
Well, according to the log it failed installing Windows update KB5001148. We have caught that too and temporarily excluded KB5001148 from installation (#8456). Please update your main branch and retry image build.

**Comment by bvaughan527** [comment]
> Well, according to the log it failed installing Windows update KB5001148. We have caught that too and temporarily excluded KB5001148 from installation (#8456). Please update your main branch and retry image build.

Thank you @vpolikarpov-akvelon , that did the trick and I was able to build the Windows Server 2022 image.
