### ISSUE TITLE
Windows 2019-22 image build failure  on update KB5001148

### ISSUE THREAD

**Issue by fajterini** [actions/runner-images#8459]
### Description

Hi, I am trying to build windows image but starting from yesterday i see it always failed on this update step (tested three times).

I see you have same issue in your build pipelines, is there any workaround to fix this ?

    azure-arm.image: Validating windows updates installation and skip Microsoft Defender Antivirus
    azure-arm.image: Windows updates failed to install: KB5001148
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...

https://support.microsoft.com/en-us/topic/kb5001148-visual-studio-client-detector-utility-for-administrator-updates-ad593454-547c-43c3-b5a3-6f201ae63f03

Looks like new windows update issue ?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

N/A

### Expected behavior

Image build succesfull.

### Actual behavior

Image build failed 

### Repro steps

Try to build runner image with pipeline.

**Comment by mikhailkoliada** [comment]
Hey, it is fixed by https://github.com/actions/runner-images/commit/038cb56f853d3e81ed9d4746d7bb7c5a35ca071b, please sync your main :)

**Comment by fajterini** [comment]
Thanks Mikhail, Just started build now ;)

It would be nice if there was easy way to exclude some updates is this cases with parameter file or configuration,
so there would be no need to directly edit windows update install script. But big thanks for quick fix.
