### ISSUE TITLE
Ubuntu 22/04 version 20230924.1.0 does not generate androidx.databinding.DataBindingComponent (part 2)

### ISSUE THREAD

**Issue by stspenke** [actions/runner-images#8468]
### Description

Last week I submitted issue https://github.com/actions/runner-images/issues/8409.
Because I could not give access to my project that ticket was closed.
I can not re-open it, but I did create a repo with the exact same problem. I can give access to this new repository to whomever picks up this issue.
Please let me know whom I should give access.

Description copied from previous ticket:
Since the update to version 20230924.1.0 the build actions for my project fail because the androidx.databinding.DataBindingComponent class is not generated. That is the only error I see, I can't find the reason for this class not being generated anymore.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/FDMediagroep/android-failing-build-20231004/actions/runs/6406656111

### Is it regression?

Yes, it worked fine with version 20230917.1.0

### Expected behavior

I expect my project to build successfully as it did with the previous version of the runner.

### Actual behavior

Since the update to version 20230924.1.0 the build actions for my project fail because the androidx.databinding.DataBindingComponent class is not generated. That is the only error I see, I can't find the reason for this class not being generated anymore.

### Repro steps

Execute the build action of my project

**Comment by Alexey-Ayupov** [comment]
Hello @stspenke. We will try to find a person who can take a look. For now, you could give access to me.

**Comment by stspenke** [comment]
Thanks a lot. 
Without any code change, my build started to fail with the new runner.
It is quite possible that the fix needs to be made in my project, e.g. that my code contains some deprecated functionality, which the new runner no longer supports, but I can't find out what it is.

**Comment by stspenke** [comment]
Hello @sergei-pyshnoi,
Do you already have any progress or findings for this issue?

**Comment by sergei-pyshnoi** [comment]
> Hello @sergei-pyshnoi, Do you already have any progress or findings for this issue?
Hi @stspenke . Thank you for your patience, We still on debug process and doesn`t find nothing useful. Also look like it is project specific problem because we didn`t receive similar reports. I will let you know as soon as we get any results.

**Comment by stspenke** [comment]
It has been a week since I last heard from you...
Do you have any news?

**Comment by sergei-pyshnoi** [comment]
@stspenke Glad to hear that problem is gone. I am not sure what exactly fix the issue, but I am sure it is related android sdks changes in [last image update](https://github.com/actions/runner-images/commit/f0e56b58e4e2af325ce3e5ff2d4e9c9b2617b23e). I closing this issue as fixed. Feel free to ask if you have additional questions.

**Comment by stspenke** [comment]
@sergei-pyshnoi I am very sad to see that after being on holiday for 3 weeks our builds are now again failing with the same problem... Can this ticket be reopened? 
It seems that after every update to the pipelines there is a chance that the builds of our project start failing again, or are magically working again.

**Comment by stspenke** [comment]
And since yesterday the build is succesful again...
