### ISSUE TITLE
Update/Add [Xcode 15.1 beta 1]

### ISSUE THREAD

**Issue by allenhumphreys** [actions/runner-images#8471]
### Tool name

Xcode

### Tool license

Commercial

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 15.1 beta 1

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

No

**Comment by Alexey-Ayupov** [comment]
Hello, @allenhumphreys. Work in progress, we are testing it. https://github.com/actions/runner-images/pull/8466

**Comment by allenhumphreys** [comment]
Thanks @Alexey-Ayupov , this version is supposed to fix the very long simulator boot times which would be very valuable.

**Comment by alminveh** [comment]
@Alexey-Ayupov  any update on this one, when can we expect the PR to be completed?

**Comment by mikhailkoliada** [comment]
Hello! we figured that Xcode 15.1 has number of unresolved bugs and it was decided until apple releases a full 15.1 release, so we are planning ti skip all the betas and rcs this time for better experience. I am planning to close this issue, but we will keep an eye on apple releases. Sorry for inconvenience caused.

**Comment by allenhumphreys** [comment]
@mikhailkoliada this is a terrible experience. Every other CI provider that supports macOS always makes Xcode betas available. I am utterly disappointed by how poor GitHub is supporting macOS.

**Comment by allenhumphreys** [comment]
Bitrise.io made Xcode 15.1 beta 1 available the day after it was released https://stacks.bitrise.io/changelogs/osx-xcode-15.1.x-edge/

**Comment by samsymons** [comment]
Xcode 15.1 has now been released: https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes

**Comment by mikhailkoliada** [comment]
Good to know, it will be a part of the images next year I guess, after holidays :)
