### ISSUE TITLE
helm 3.13.0 has a bug that makes it unable to access charts via oci, please downgrade helm

### ISSUE THREAD

**Issue by Loki-Afro** [actions/runner-images#8475]
### Description

see issue here https://github.com/helm/helm/issues/12449

helm 3.13.0 is affected
helm 3.12.3 still works

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

ubuntu-latest

### Expected behavior

working helm version

### Actual behavior

helm unable to pull charts from github oci packages

### Repro steps

```
zarathustra@esel ~/code/dof_app_deploy (git)-[bc-5488-pwi] % podman run -it alpine/helm:3.12.3 pull oci://ghcr.io/raffis/charts/mongodb-query-exporter --version 3.0.1
Pulled: ghcr.io/raffis/charts/mongodb-query-exporter:3.0.1
Digest: sha256:1f31985fccbbf66faffba89f498c23aef3d10059d7ad89821452b643f4c33eee
zarathustra@esel ~/code/dof_app_deploy (git)-[bc-5488-pwi] % podman run -it alpine/helm:3.13.0 pull oci://ghcr.io/raffis/charts/mongodb-query-exporter --version 3.0.1
Resolved "alpine/helm" as an alias (/home/zarathustra/.cache/containers/short-name-aliases.conf)
Trying to pull docker.io/alpine/helm:3.13.0...
Getting image source signatures
Copying blob 8f55ccf48d2f done   | 
Copying blob 96526aa774ef done   | 
Copying blob 0bbba39cff7e done   | 
Copying config 9511a681ca done   | 
Writing manifest to image destination
Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Araffis%2Fcharts%2Fmongodb-query-exporter%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden
```

**Comment by Alexey-Ayupov** [comment]
Hello, @Loki-Afro. We cannot downgrade the `helm` in our images since it forces us to pin specific version (we are always trying to install the latest version), however, you can do it runtime with the following snippet:

```
    steps:
      - name: downgrade helm
        shell: bash
        run: |
          sudo rm /usr/local/bin/helm
          sudo  curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > /tmp/helm.sh
          sudo chmod +x /tmp/helm.sh
          sudo /tmp/helm.sh --version v3.12.3
          helm version
```          
After upstream releases a new version of `helm` you will get it with the new image version.

**Comment by Alexey-Ayupov** [comment]
Hello, @Loki-Afro. Since the workaround was provided and we are waiting for the new version of helm from the upstream, this issue will be closed.
If you have other questions feel free to reach us.

**Comment by V-A-Kaiser** [comment]
@Alexey-Ayupov A new version of Helm has been released that resolves this issue: https://github.com/helm/helm/issues/12423
https://github.com/helm/helm/releases/tag/v3.13.1

**Comment by lucacome** [comment]
How often are new images released? I'm running into this too...

**Comment by R-Studio** [comment]
Who updates the [Chocolatey package](https://community.chocolatey.org/packages/kubernetes-helm)? It is still v3.13.0
