### ISSUE TITLE
[macOS] Apple Silicon runners does not have `swiftlint` preinstalled

### ISSUE THREAD

**Issue by jozefizso** [actions/runner-images#8477]
### Description

We are trying the Apple Silicon GHA runners and while the standard runners have the `Swiftlint` tool preinstalled the new runners does not include it.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.309.0'
Operating System
  macOS
  13.6
  22G120
Runner Image
  Image: macos-13
  Version: 20230924.3
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20230924.3/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230924.3
```

### Is it regression?

macos-13

### Expected behavior

The `Swiftlint` tool should be preinstalled on both `macos-13` and `macos-13-xlarge` runners.

### Actual behavior

The `Swiftlint` tool is missing in `macos-13-xlarge` runner.

### Repro steps

1. Use `macos-13-xlarge`
2. Run `swiftlint` tool

**Comment by Alexey-Ayupov** [comment]
Hello, @jozefizso. We have no plans to install `swiftlint` on macOS 13 arm64 runners. Please install it runtime. 
I will close this issue. If you have other questions feel free to reach us.
