### ISSUE TITLE
aws cli missing in the m1 runners

### ISSUE THREAD

**Issue by Mark-Simulacrum** [actions/runner-images#8498]
There are a number of packages available in the x86_64 runner that are not in the Apple Silicon runner (the one I noticed missing was `aws`). Although it is [documented which packages are available](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md), would it be possible to get a hint on if these packages absence is transient or permanent? If it's permanent, we can change our CI config appropriately; if it's transient we can wait for them to be fully matched.

_Originally posted by @shepmaster in https://github.com/actions/runner-images/issues/8439#issuecomment-1744051925_

**Comment by vpolikarpov-akvelon** [comment]
We aim to keep our images as lean and maintenance-friendly as possible, which is why we didn't include the AWS CLI tool in that specific image. It only takes a couple of seconds to install so you can easily include it when you need it. If you prefer to have it preinstalled, you can always set up custom self-hosted runners.

If you have any questions or need assistance with adding the AWS CLI tool to your workflow, feel free to ask

**Comment by jozefizso** [comment]
@vpolikarpov-akvelon why all the other runners have the `aws-cli` preinstalled?

Why should we pay for 30s for installing `aws-cli` in each workflow run in a premium priced runner when it is for free in all the others?

**Comment by vpolikarpov-akvelon** [comment]
Hey @jozefizso. There are historical reasons for it. We already had AWS CLI installed on runners in the past, but we had no plans to install it on new runners. So it's not about paidness but about novelty.

Anyway, we decided recently to add AWS CLI to M1-based runner images: https://github.com/actions/runner-images/pull/8774. It will be included to the closest release.

**Comment by jozefizso** [comment]
> Hey @jozefizso. There are historical reasons for it. We already had AWS CLI installed on runners in the past, but we had no plans to install it on new runners. So it's not about paidness but about novelty.
> 
> Anyway, we decided recently to add AWS CLI to M1-based runner images: #8774. It will be included to the closest release.

Thanks, we really appreciate the AWS will be preinstalled.
