### ISSUE TITLE
Add Android SDK to `macos-13-xlarge`

### ISSUE THREAD

**Issue by martinbonnin** [actions/runner-images#8515]
### Tool name

Android SDK

### Tool license

Android SDK license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Same as https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#android

### Brief description of tool

Can the Android SDK be installed in the M1 macOS images (`macos-13-xlarge`) ?
 
[The MacOS 13 page](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#android) says it should be supported but it is not (see this [workflow run](https://github.com/apollographql/apollo-kotlin/actions/runs/6480096895/job/17594924884))

### URL for tool's homepage

https://developer.android.com/studio

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes. I can provide steps if needed but given that the Android SDK is already installed in other machines, it's probably easier to reuse this
```

**Comment by ilia-shipitsin** [comment]
there's hardware limitation https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#limitations-for-macos-larger-runners

```
Due to a limitation of Apple's Virtualization Framework, which our hypervisor uses, nested-virtualization is not supported by arm64 runners.
```

I'm afraid, android sdk without simulators is not very useful

**Comment by ilia-shipitsin** [comment]
as far as I understand, it will be "build only" mode, which already available on MacOS intel runners. am I missing something ?

**Comment by martinbonnin** [comment]
I'd like to use the M1 runners for:

* hopefully faster compile time
* run macosArm64 tests at the same time

We could shard our CI to build/run different architectures on different images but it'd be very convenient to do everything from the same M1 image.

**Comment by ilia-shipitsin** [comment]
@martinbonnin , we've changed our mind. we'll add android SDK.

small question. android SDK takes a lot of space on HDD. will it be enough to include only 32 ?

**Comment by martinbonnin** [comment]
[Latest version is 34](https://developer.android.com/tools/releases/platforms#14) so I would recommend adding this one and the previous one (33) at a minimum. 

That gives developers 1 year to upgrade their apps to the latest version which sounds acceptable if HDD space is scarce? 

Adding only the latest SDK would be problematic as all the builds would start failing whenever there is a version bump.

**Comment by ilia-shipitsin** [comment]
@martinbonnin , I added SDK. let's wait for new image rollout

**Comment by ilia-shipitsin** [comment]
deployed. 
I'm closing issue. Feel free to re-open if we missed something

**Comment by fibelatti** [comment]
@ilia-shipitsin some of our workflows are still failing due to missing environment variables when running on `macos-13-xlarge` and the [README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md) still doesn't list any Android installed software. I'm a bit confused about what was rolled out and deployed, could you clarify?

```
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/runner/work/Unfold-Android/Unfold-Android/local.properties'.
```

**Comment by fibelatti** [comment]
@ilia-shipitsin some of our workflows are still failing due to missing environment variables when running on `macos-13-xlarge` and the [README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md) still doesn't list any Android installed software. I'm a bit confused about what was rolled out and deployed, could you clarify?

```
> SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '<path>'.
```

**Comment by ilia-shipitsin** [comment]
thank you for pointing that.

https://github.com/actions/runner-images/blob/main/images/macos/software-report/SoftwareReport.Generator.ps1#L283

we do not need that condition anymore

**Comment by martinbonnin** [comment]
Can we reopen this issue? We having the same `SDK location not found` issue as @fibelatti above ([sample run](https://github.com/apollographql/apollo-kotlin/actions/runs/6878059147/job/18706881295?pr=5370)).
