### ISSUE TITLE
Add Chrome to `macos-13-xlarge`

### ISSUE THREAD

**Issue by martinbonnin** [actions/runner-images#8516]
### Tool name

Chrome

### Tool license

Chrome License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Same as https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#browsers

### Brief description of tool

Can Chrome be installed in the M1 macOS images (`macos-13-xlarge`) ?
 
[The MacOS 13 page](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#android) says it should be supported but it is not (see this [workflow run](https://github.com/apollographql/apollo-kotlin/actions/runs/6467087435/job/17556441607))

```
Execution failed for task ':browser-tests:allTests'.
> Failed to execute all tests:
  :browser-tests:jsBrowserTest: java.lang.IllegalStateException: Errors occurred during launch of browser for testing.
  - ChromeHeadless
  Please make sure that you have installed browsers.
  Or change it via
  browser {
      testTask {
          useKarma {
              useFirefox()
              useChrome()
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
960 actionable tasks: 526 executed, 434 from cache
              useSafari()
          }
      }
  }
```

### URL for tool's homepage

https://www.google.com/chrome/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes. I can provide steps if needed but given that Chrome is already installed in other images, it's probably easier to reuse this
```

**Comment by vpolikarpov-akvelon** [comment]
Hey there. Thank you for you request, we will consider installing Chrome.

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by joffrey-bion** [comment]
I'm facing the same error with `macos-latest` now. Isn't Chrome supported there? The page seems to list it.
