### ISSUE TITLE
Update Android NDK to r26b

### ISSUE THREAD

**Issue by Javernaut** [actions/runner-images#8517]
### Tool name

Android NDK

### Tool license

Same as before

### Add or update?

- [ ] Add
- [X] Update

### Desired version

r26b aka 26.1.10909125

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by vpolikarpov-akvelon** [comment]
Hey @Javernaut. Thank you for your request, we will take a look.

**Comment by mikhailkoliada** [comment]
Duplicate of https://github.com/actions/runner-images/issues/8327
