### ISSUE TITLE
Update/Add Java 21

### ISSUE THREAD

**Issue by mvh77** [actions/runner-images#8523]
### Tool name

Java 21

### Tool license

Same as other Java versions

### Add or update?

- [ ] Add
- [X] Update

### Desired version

21 latest

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mvh77** [comment]
And also add support in Maven@3 task jdkVersionOption

**Comment by vpolikarpov-akvelon** [comment]
Hey there. Thank you for your request, we will take a look.

**Comment by vpolikarpov-akvelon** [comment]
Installers for Eclipse Temurin 21 haven't been published yet. Let's wait a bit. I hope it won't take long.

Btw, release progress is tracked here: https://github.com/adoptium/temurin/issues/8

**Comment by Komdosh** [comment]
> Installers for Eclipse Temurin 21 haven't been published yet. Let's wait a bit. I hope it won't take long.
> 
> Btw, release progress is tracked here: [adoptium/temurin#8](https://github.com/adoptium/temurin/issues/8)

it's available now
https://adoptium.net/temurin/releases/

**Comment by mvh77** [comment]
Any progress on this?

**Comment by vpolikarpov-akvelon** [comment]
Hey @mvh77. Java 21 has been rolled out to all runners except Mac OS 11 and Mac OS 12. Feel free to use it in your workflow. This issue will be closed as soon as rollout is complete for all operation systems.

**Comment by mvh77** [comment]
Ok thanks! Does the Maven@3 task support it too? It's not yet documented [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/maven-v3?view=azure-pipelines).

**Comment by vpolikarpov-akvelon** [comment]
> Does the Maven@3 task support it too?

The task is maintained by another team [here](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/MavenV3). I can't guarantee Java 21 is supported, but probably it is, so I would recommend you to just give it a try.

**Comment by mikhailkoliada** [comment]
Deployed
