### ISSUE TITLE
Update/Add Xcode 15.0.1 RC

### ISSUE THREAD

**Issue by dayton-bobbitt** [actions/runner-images#8530]
### Tool name

Xcode

### Tool license

Commercial

### Add or update?

- [X] Add
- [ ] Update

### Desired version

15.0.1 RC

### Brief description of tool

Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776) (FB12237092)

### URL for tool's homepage

https://developer.apple.com/documentation/xcode-release-notes/xcode-15_0_1-release-notes

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

No

**Comment by vpolikarpov-akvelon** [comment]
Hey @dayton-bobbitt. Thank you for your request. We will take a look.

**Comment by nbevans** [comment]
Should also add Xamarin to macos-13 agent whilst you're doing XCode15, see: https://github.com/actions/runner-images/issues/8045#issuecomment-1758906216

**Comment by pronebird** [comment]
Please expedite.

**Comment by ilia-shipitsin** [comment]
we keep an eye on 15.0.1 RC.

on Friday we caught a regression on simulators shipped with 15.0.1 (tracked internally), today is resolved (we are still investigating)

**Comment by harry171023** [comment]
Is there any ETA on deployment?

**Comment by TomaszLizer** [comment]
@vpolikarpov-akvelon @ilia-shipitsin 
Any expected timeframe of deployment for Xcode 15.0.1 addition? :)

**Comment by vpolikarpov-akvelon** [comment]
Hey @TomaszLizer. Update for Mac OS arm64 is rolling now, once https://github.com/actions/runner-images/pull/8586 is closed the Xcode 15.0.1 is in place.
Update for Mac OS x64 will we somewhat later.

**Comment by dayton-bobbitt** [comment]
Thanks @vpolikarpov-akvelon! Is the macOS 13 arm image available in Azure? If so, what is the image name? I've only been able to get "macOS-13" to work which I believe is x86.

**Comment by vpolikarpov-akvelon** [comment]
@dayton-bobbitt, there was an [announce in GitHub blog](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) a couple of weeks ago and as far as I know it's for GitHub Actions only. As for x64 version, I can't provide any exact estimation, sorry.

**Comment by Baza207** [comment]
Do we know when #8586 will be fully available? As we're having major upload issues which we're hoping will be solved by Xcode 15.0.1. Our pipeline is failing to let Fastlane upload using the Azure DevOps Xcode task, related to this https://github.com/fastlane/fastlane/issues/21535 Fastlane issue.

We've been in touch with Apple as well but they haven't got a solution for us. 😞

**Comment by vpolikarpov-akvelon** [comment]
Mac OS 13 x64 update is on the way: https://github.com/actions/runner-images/pull/8601

**Comment by hr147** [comment]
> Mac OS 13 x64 update is on the way: #8601

@vpolikarpov-akvelon when this PR will be merged?

**Comment by vpolikarpov-akvelon** [comment]
> @vpolikarpov-akvelon when this PR will be merged?

Pull request represents update that is being rolled currently. As soon as rollout is complete PR will be merged. We are working on it, but I can't provide any estimations, sorry.

**Comment by ivannggnnavi** [comment]
> ### Tool name
> 
> Xcode
> 
> ### Tool license
> 
> Commercial
> 
> ### Add or update?
> 
> - [X] Add
> - [ ] Update
> 
> ### Desired version
> 
> 15.0.1 RC
> 
> ### Approximate size
> 
> _No response_
> 
> ### Brief description of tool
> 
> Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776) (FB12237092)
> 
> ### URL for tool's homepage
> 
> https://developer.apple.com/documentation/xcode-release-notes/xcode-15_0_1-release-notes
> 
> ### Provide a basic test case to validate the tool's functionality.
> 
> _No response_
> 
> ### Platforms where you need the tool
> 
> - [X] Azure DevOps
> - [X] GitHub Actions
> 
> ### Runner images where you need the tool
> 
> - [ ] Ubuntu 20.04
> - [ ] Ubuntu 22.04
> - [ ] macOS 11
> - [ ] macOS 12
> - [X] macOS 13
> - [ ] Windows Server 2019
> - [ ] Windows Server 2022
> 
> ### Can this tool be installed during the build?
> 
> _No response_
> 
> ### Tool installation time in runtime
> 
> _No response_
> 
> ### Are you willing to submit a PR?
> 
> No
