### ISSUE TITLE
"This version of ChromeDriver only supports Chrome version 118" on Windows images

### ISSUE THREAD

**Issue by StephenT-McMurray** [actions/runner-images#8540]
### Description

A couple of days ago, I updated one of my .NET projects' NuGet reference to Selenium.WebDriver.ChromeDriver to use the latest version, 118.0.5993.7000. Since this point, my GH Actions runs -- on Windows specifically -- have been failing with the error message "This version of ChromeDriver only supports Chrome version 118."

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Windows Server 2019 image version: 20231002.2.0
Windows Server 2022 image version: 20231002.1.0

### Is it regression?

No

### Expected behavior

My tests should run, using ChromeDriver v118.x and either Chrome v118.x or Chrome v117.x.

### Actual behavior

Each of my tests fails to start, with the error message "This version of ChromeDriver only supports Chrome version 118".

Note: This does not seem to occur on the non-Windows runner images.

### Repro steps

1. Create a C# .NET 6 project that uses Selenium. Make sure to reference Selenium.WebDriver.ChromeDriver version 118.0.5993.7000.
2. Set up a fairly standard .NET Core Test workflow on GitHub Actions, using a matrix of OSes and OS versions that includes `windows-2019` and `windows-2022`, along with other, non-Windows OSes such as `ubuntu-22.04` and `macos-11`. (Note that my workflow is set up to run manually, with the environment (Live/Staging) as a required user input. Not sure if this matters or not.)
3. Try to run your new GitHub Actions workflow.

**Comment by vpolikarpov-akvelon** [comment]
Hey @StephenT-McMurray. Currently both Windows 2019 and Windows 2022 runners have Chrome Driver 117 installed. It will be updated by the closest rollout. Unfortunately, I can't give you any specific date. Sorry for that.

You can find versions of all software components that we install on runners here: [Windows 2019](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#browsers-and-drivers), [Windows 2022](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#browsers-and-drivers)

**Comment by StephenT-McMurray** [comment]
I see. So until then, the solution is to downgrade the NuGet package to 117.x?

**Comment by vpolikarpov-akvelon** [comment]
> I see. So until then, the solution is to downgrade the NuGet package to 117.x?

I think it's the best workaround. Another option is to install updated Chrome and Chrome Driver in a runtime, if you really need it immediately.

**Comment by StephenT-McMurray** [comment]
> > I see. So until then, the solution is to downgrade the NuGet package to 117.x?
> 
> I think it's the best workaround. Another option is to install updated Chrome and Chrome Driver in a runtime, if you really need it immediately.

OK, thanks.
