### ISSUE TITLE
macOS 13 runner needs Xcode UI testing capabilities

### ISSUE THREAD

**Issue by mpiwosal** [actions/runner-images#8546]
### Description

I'm seeing a regression on the latest Image version, similar to previous: https://github.com/actions/runner-images/issues/7621
The job fails with timeout "The test runner failed to initialize for UI testing".
I moved from macOS 12 to macOS 13 runner and started seeing this.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231002.1

### Is it regression?

yes

### Expected behavior

xcode ui unit tests should work

### Actual behavior

they don't work

### Repro steps

Run xcode ui tests on a project, see that they fail.

**Comment by vpolikarpov-akvelon** [comment]
Hey @mpiwosal. Thank you for reporting. Could you please share a link to failing workflow or provide more specific repro steps so we can investigate it?

**Comment by mpiwosal** [comment]
@vpolikarpov-akvelon no public link I'm afraid. 
however I added automationmodetool bash script to the pipeline and the output of that was 

```
Automation Mode is disabled.
This device DOES NOT REQUIRE user authentication to enable Automation Mode.
```

which suggest that it's not the same issue. 
This started happening for me when I migrated from macOS 12 to macOS 13 runner (on Azure)

**Comment by vpolikarpov-akvelon** [comment]
Well, it's hard to say, but it may relate to #7971. I may recommend you trying to pin simulator version (e.g. `iPhone 14,OS=16.4`).
Also upcoming rollout of Xcode 15.0.1 RC1 may fix you issue.

If not, we would really appreciate if you share more information (logs, screenshots etc.).

**Comment by asif-marakkar** [comment]
I'm also seeing issue on macos-13 runner in Azure pipeline.
The job fails with error "UITests-Runner (14751) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying Error: Test crashed with signal kill before starting test execution.))".
Recently, I moved from macOS 12 to macOS 13 runner and started seeing this.
Operating System: macOS 13.6 - 22G120
Runner Image: macos-13 Version: 20231002.1
Xcode 15 and iOS 17.0

**Comment by asif-marakkar** [comment]
> Well, it's hard to say, but it may relate to #7971. I may recommend you trying to pin simulator version (e.g. `iPhone 14,OS=16.4`). Also upcoming rollout of Xcode 15.0.1 RC1 may fix you issue.
> 
> If not, we would really appreciate if you share more information (logs, screenshots etc.).

I'm also seeing issue on macos-13 runner in Azure pipeline.
The job fails with error "UITests-Runner (14751) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying Error: Test crashed with signal kill before starting test execution.))".
Recently, I moved from macOS 12 to macOS 13 runner and started seeing this.
Operating System: macOS 13.6 - 22G120
Runner Image: macos-13 Version: 20231002.1
Xcode 15 and iOS 17.0

**Comment by mikhailkoliada** [comment]
We have delivered Xcode 15.1, please test it and let us know if it helps to solve the issue, if not, feel free to reach us again and we will help you!
