### ISSUE TITLE
Update/Add GCC 13

### ISSUE THREAD

**Issue by McFlyboy** [actions/runner-images#8555]
### Tool name

GCC 13

### Tool license

Same as other GCC versions

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13 latest

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @McFlyboy. We will take a look.

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by dwkimm01** [comment]
Is this broken?  Builds started failing and I don't see gcc-13/g++-13 in /usr/bin (which is where I do see gcc-9/10/11/12).

**Comment by DouisLavid** [comment]
It indeed seems to be broken, a simple build job that used to work for me on ubuntu-latest (so 22.04) with cmake now fails and yield the following logs :
CMake Error at /usr/local/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  g++-13.

Call Stack (most recent call first):
  CMakeLists.txt:12 (enable_language)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by ermig1979** [comment]
I tried to run in **runs-on** (on ubuntu-latest): 

    sudo apt-get update && sudo apt-get -y install g++-13

but threre is trying to install clang-13

**Comment by erik-bershel** [comment]
Hey there!

Please take a look here: https://github.com/actions/runner-images/issues/9679, https://github.com/actions/runner-images/issues/9866
GCC-13 was removed from `ubuntu-22.04` image. You may use `ubuntu-24.04` or install tool in runtime from PPA.

cc @dwkimm01 @DouisLavid @ermig1979

**Comment by dwkimm01** [comment]
> Hey there!
> 
> Please take a look here: #9679, #9866 GCC-13 was removed from `ubuntu-22.04` image. You may use `ubuntu-24.04` or install tool in runtime from PPA.
> 
> cc @dwkimm01 @DouisLavid @ermig1979

Thanks Erik, should ubuntu-24.04 be "latest" then?

**Comment by erik-bershel** [comment]
Hey @dwkimm01!
> Thanks Erik, should ubuntu-24.04 be "latest" then?

Not now. Later somewhen. It's in `beta` now. Firstly it should be moved to `General Available` status.
