### ISSUE TITLE
Update/Add Xamarin.iOS

### ISSUE THREAD

**Issue by ramtechjoe** [actions/runner-images#8557]
### Tool name

Xamarin.iOS

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

16.4.0.18

### Brief description of tool

Add Xamarin.iOS 16.4.0.18 with XCode 15 support to mac-os-13 to support Xamarin builds targeting XCode 15

https://github.com/xamarin/xamarin-macios/releases

### URL for tool's homepage

https://github.com/xamarin/xamarin-macios/releases

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

**Comment by mikhailkoliada** [comment]
Hello! Given that Xamarin announced its [deprecation](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) on May 1, 20204 we would not like to preinstall it. Please install in runtime from homebrew as `brew install --cask xamarin-ios`

**Comment by Saccomani** [comment]
> Hello! Given that Xamarin announced its [deprecation](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) on May 1, 20204 we would not like to preinstall it. Please install in runtime from homebrew as `brew install --cask xamarin-ios`

Installing with home brew I will be able to build for iOS 17 target ?

**Comment by ramtechjoe** [comment]
@Saccomani 
You need to make sure to point to xcode 15+ (can be 15.0 ... 15.2), and install  xamarin.iOS

```
- script: |
    sudo xcode-select -s /Applications/Xcode_15.0.app
  displayName: Selects a specific version of Xcode
```

```
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Install Xamarin.iOS
      
      brew install --cask xamarin-ios
```
