### ISSUE TITLE
Could not iniitialize a new repository

### ISSUE THREAD

**Issue by tester0077** [actions/runner-images#8558]
### Description

Trying to initialize a bare repo issues the warning, even though the action succeeds
TortoiseGit 2.15.0.0
git 2.3.12
running Windows 11

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

TortoiseGit 2.15.0.0
git 2.3.12
running Windows 11

### Is it regression?

don't know don't recal it happening earlier, but have no time frame

### Expected behavior

should not issue warning if the action succeeded

### Actual behavior

issues the warning  for repository path //mynas/git/buildtest.git

### Repro steps

create a directory on a directory on my OpenMediaVault NAS . from a SMB share on Win11
Cd to directory
right-click in directory
select "Create repository here ..." select  "Make it bare" and click OK
The bare directory structure is created and ignoring the warning lets one proceed without further errors or issues.

**Comment by sergei-pyshnoi** [comment]
Hell @tester0077 . Look like you come to wrong repo. [runner-images](https://github.com/actions/runner-images) repository contains the source code used to create the VM images for [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) used for Actions, as well as for [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) used for Azure Pipelines. Based on the description of your problem, it looks like this is about native use of Windows 11 + Git + OpenMediaVault from your station. Did I understand you correct? Or you trying to create repo from pipeline?

**Comment by sergei-pyshnoi** [comment]
I am closing this issue for now as "not runner-images" related. But if have additional questions feel free to mention me in this tread.
