### ISSUE TITLE
Add Terragrunt 

### ISSUE THREAD

**Issue by runnerImages** [actions/runner-images#8583]
### Tool name

Terragrunt

### Tool license

MIT License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Terragrunt is a thin wrapper for [Terraform](https://www.terraform.io/) that provides extra tools for keeping your Terraform configurations [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), working with multiple Terraform modules, and managing remote state.

### URL for tool's homepage

https://github.com/gruntwork-io/terragrunt

### Provide a basic test case to validate the tool's functionality.

```bash
terragrunt --version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
#!/bin/bash -e
################################################################################
##  File:  terragrunt.sh
##  Desc:  Installs custom software
################################################################################

source $HELPER_SCRIPTS/install.sh

# Install Terragrunt
echo 'Terragrunt installation'
json=$(curl -s "https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest")
downloadUrl=$(echo $json | jq -r ".assets | .[] | select(.name==\"terragrunt_linux_amd64\").browser_download_url")
download_with_retries $downloadUrl "/tmp"
sudo mv /tmp/terragrunt_linux_amd64 /usr/local/bin/terragrunt
chmod +x /usr/local/bin/terragrunt

# Test installation
echo 'Test Terragrunt'
terragrunt --version
```

### Tool installation time in runtime

Less than 1 minute

### Are you willing to submit a PR?

Ye

**Comment by runnerImages** [comment]
I'd like to add the Terragrunt to Image build because due to organizational procedures I cannot install it in pipeline which will use terragrunt.
I was trying to add it on my own, however I'm having some issues with it: https://github.com/actions/runner-images/discussions/8570

**Comment by sergei-pyshnoi** [comment]
Hello @runnerImages . Unfortunately we do not have plans to add `Terragrunt ` to runner images due maintain concern and small installation time. About building own image, I will answer in discussion.
