### ISSUE TITLE
Update/Add Winget

### ISSUE THREAD

**Issue by MrHinsh** [actions/runner-images#8584]
### Tool name

Winget

### Tool license

n/a/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

he winget command line tool enables users to discover, install, upgrade, remove and configure applications on Windows 10 and Windows 11 computers. This tool is the client interface to the Windows Package Manager service.

Install winget
Windows Package Manager winget command-line tool is available on Windows 11 and modern versions of Windows 10 as a part of the App Installer.

You can [get App Installer from the Microsoft Store](https://www.microsoft.com/p/app-installer/9nblggh4nns1#activetab=pivot:overviewtab). If it's already installed, make sure it is updated with the latest version.

### URL for tool's homepage

https://learn.microsoft.com/en-us/windows/package-manager/winget/

### Provide a basic test case to validate the tool's functionality.

```bash
Winget search "nkdAgility.AzureDevOpsMigrationTools"
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
$progressPreference = 'silentlyContinue'
Write-Information "Downloading WinGet and its dependencies..."
Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx -OutFile Microsoft.UI.Xaml.2.7.x64.appx
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.UI.Xaml.2.7.x64.appx
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
```

### Tool installation time in runtime

abou 15s

### Are you willing to submit a PR?

yes

**Comment by sergei-pyshnoi** [comment]
Hello @MrHinsh . Unfortunately we cannot install `winget` due it incapability with Windows Server.  More information you can find in [official repo](https://github.com/microsoft/winget-cli#installing-the-client).

**Comment by carlescufi** [comment]
`winget` is actually part of the latest [Windows Server 2025](https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md) image, although this does not seem to be documented.
