### ISSUE TITLE
Install-MongoDB.ps1 is failing with a (403) Forbidden error

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#8600]
### Description

Install-MongoDB.ps1 is failing with a (403) Forbidden error

Pipeline for generating windows images failed with below error
==========================================

  azure-arm.image: Disable auto root update mechanism
==> azure-arm.image: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/win/scripts/Installers/Install-MongoDB.ps1
    azure-arm.image: Downloading mongodb-windows-x86_64-5.0.22-signed.msi...
    azure-arm.image: Downloading package from: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.22-signed.msi to path 
C:\Users\packer\AppData\Local\Temp\mongodb-windows-x86_64-5.0.22-signed.msi .
    azure-arm.image: There is an error encounterd after 0.3 seconds during package downloading:
    azure-arm.image:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 19
    azure-arm.image: Downloading package from: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.22-signed.msi to path 
C:\Users\packer\AppData\Local\Temp\mongodb-windows-x86_64-5.0.22-signed.msi .
    azure-arm.image: There is an error encounterd after 0.2 seconds during package downloading:
    azure-arm.image:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
    azure-arm.image: Waiting 30 seconds before retrying. Retries left: 18

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

win22/20231016.1.0

### Is it regression?

NA

### Expected behavior

Install last MongoDB version

### Actual behavior

==> azure-arm.image: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/win/scripts/Installers/Install-MongoDB.ps1
    azure-arm.image: Downloading mongodb-windows-x86_64-5.0.22-signed.msi...
    azure-arm.image: Downloading package from: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.22-signed.msi to path 
C:\Users\packer\AppData\Local\Temp\mongodb-windows-x86_64-5.0.22-signed.msi .
    azure-arm.image: There is an error encounterd after 0.3 seconds during package downloading:
    azure-arm.image:  Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."

### Repro steps

Running pipeline again.

**Comment by sergei-pyshnoi** [comment]
closing as duplicate https://github.com/actions/runner-images/issues/8252
