### ISSUE TITLE
Unable to Set Screen Resolution in GitHub Actions Workflow

### ISSUE THREAD

**Issue by mohit-sculptsoft** [actions/runner-images#8606]
### Description

I'm currently working on creating a GitHub Actions workflow for application testing. I'm using macos-latest as the GitHub workflow runner, but I'm encountering an issue with setting the screen resolution in the workflow.

![Screenshot from 2023-10-19 18-40-30](https://github.com/actions/runner-images/assets/131239259/4910d3f9-40ca-4f2a-9d58-28b48654d213)
![Screenshot from 2023-10-19 18-41-25](https://github.com/actions/runner-images/assets/131239259/9a7c87f7-d1fa-4daf-bb3a-b910a87cf6c6)

I need to change the screen resolution from the current setting to 2560x1440, but I'm unable to achieve this. The standard way of changing screen resolution doesn't seem to work in this environment. Is there a way to set the screen resolution for the macOS-latest GitHub Actions runner, or are there alternative approaches to achieve this goal?

I'd appreciate any guidance or insights from the community on how to resolve this issue. Thank you!

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

github runner version - macos-latest (macos 12)

### Is it regression?

NA

### Expected behavior

resolution changed.

### Actual behavior

resolution is not getting changed.

### Repro steps

NA

**Comment by sergei-pyshnoi** [comment]
Hello @mohit-sculptsoft . Can you please provide link to one of failed runs? Is it ok if repo is private, we just need to identify run for collecting some additional info.

**Comment by sergei-pyshnoi** [comment]
Can you please also provide screenshot before and after resolution sets? (you can do it using `screencapture` command and uploading it to artifacts)

**Comment by ivannggnnavi** [comment]
The

**Comment by mohit-sculptsoft** [comment]
before resolution sets,
![before_resolution](https://github.com/actions/runner-images/assets/131239259/9b9f6ba9-06bf-4757-bed4-62969cc8d2b6)

after resolution sets,
![after_resolution](https://github.com/actions/runner-images/assets/131239259/02f13a16-93db-43df-b7e9-d6dde5d37497)

latest workflow run >> https://github.com/mohit-sculptsoft/github-azure-ss/actions/runs/6636528718

**Comment by sergei-pyshnoi** [comment]
Hello @mohit-sculptsoft . Sorry for the late response. After investigation we found that `"/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440` command applies resolution correctly but in require some time before new display will initialize . You can put `sleep 2` before `system_profiler SPDisplaysDataType` to see new applied resolution. I am closing this issue for now but if you have additional question, feel free to reach me out in this tread.
