### ISSUE TITLE
Add AWS CLI for macos-13-xlarge image

### ISSUE THREAD

**Issue by daltonclaybrook** [actions/runner-images#8613]
### Tool name

AWS CLI

### Tool license

Copyright 2012-2020 Amazon.com, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.13.22

### Brief description of tool

The macos-13-Readme.md indicates that the AWS CLI is installed on the macOS runners, but it appears to be skipped for the arm64/Ventura runner. The CLI should be installed on all macOS runners for consistency.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @daltonclaybrook . We will take a look

**Comment by jozefizso** [comment]
Missing aws-cli makes the `macos-13-xlarge` runners incompatible with other runners.

This is a regression when upgrading from `macos-13` to `macos-13-xlarge`.

**Comment by ilia-shipitsin** [comment]
this looks related: https://github.com/actions/runner-images/pull/8683

**Comment by mikhailkoliada** [comment]
Deployed
