### ISSUE TITLE
'This environment is externally managed' python error

### ISSUE THREAD

**Issue by TheMostDiligent** [actions/runner-images#8615]
### Description

In MacOS-12 runner version 20231017.6, CMake configuration steps in our CI builds started to fail with the following error:

```
-- The ASM compiler identification is AppleClang
-- Found assembler: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Symbol prefix: 
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Notice:  A new release of pip is available: 23.2.1 -> 23.3
Notice:  To update, run: python3.12 -m pip install --upgrade pip
CMake Error at DiligentTools/RenderStateNotation/CMakeLists.txt:32 (message):
  /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m pip
  install libclang failed with 1
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Failing runner](https://github.com/DiligentGraphics/DiligentFX/actions/runs/6582821091/job/17885109069):
```
Current runner version: '2.310.2'
Operating System
  macOS
  12.6.9
  21G726
Runner Image
  Image: macos-12
  Version: 20231017.6
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231017.6/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231017.6
Runner Image Provisioner
  2.0.312.1
```

[OK runner](https://github.com/DiligentGraphics/DiligentFX/actions/runs/6582821091/job/17885159165):
```
Current runner version: '2.310.2'
Operating System
  macOS
  12.7
  21G816
Runner Image
  Image: macos-12
  Version: 20230921.4
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230921.4/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230921.4
Runner Image Provisioner
  2.0.310.1
```

### Is it regression?

Yes, 20231017.6. Worked OK in 20230921.4

### Expected behavior

CMake configuration completes successfully, as it used to.

### Actual behavior

CMake configuration fails.

### Repro steps

For us the build fails on this commit: https://github.com/DiligentGraphics/DiligentFX/commit/d544c7c256031c17d3b89e18ec2ce81901e8308f

**Comment by sergei-pyshnoi** [comment]
Hello @TheMostDiligent , We will take a look

**Comment by TheMostDiligent** [comment]
After some digging I figured that this happens because python was updated to version 12 and it changed how packages are installed.
In particular, `--break-system-packages` command line option is required to use the old behavior.
Here are the links to relevant discussions:

[How do I solve "error: externally-managed-environment" every time I use pip 3?](https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3)
[pip install -r requirements.txt is failing: "This environment is externally managed"](https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana)

I don't think there is anything that can be done on the runner side, so I am closing this issue.
I changed the title so that anyone having the same issue can find it.

**Comment by AbdelmajidBen** [comment]
Homebrew wants you to create a virtual env so that pip-installed modules don’t break something in your system. Same is true if working with python installed by apt-get in Ubuntu for same reason.

**Comment by janbrasna** [comment]
Question is whether the marker file should be present at all in this context, see:
- https://github.com/actions/runner-images/issues/10781#issuecomment-2454865613

**Comment by MichaIng** [comment]
The issue currently appears on `macos-latest`. While for end user distros and end user single app containers (which are usually not supposed to be changed anyway by users), I agree that the marker file has some use and should be left in place, in a temporary development environment like a GitHub Actions runners, it IMO does not make any sense.

It is removed on Ubuntu 24.04 runner, so I guess it makes sense to remove it from the macOS image(s) as well.

**Comment by janbrasna** [comment]
@MichaIng Bad news is it's coming back:
- https://github.com/actions/runner-images/issues/10897

**Comment by MichaIng** [comment]
I just wanted to suggest to apply the same workaround for the macOS images ... sadly the "The motivation for the changes" does not reflect the motivation for having this nonsense on a GitHub Actions runner image, which is meant to exist temporarily for a particular test or build only, but just explains the change at Python side, at best containing a motivation for why Python implemented the option.

And I want to point out that that Python itself does NOT prevent pip from installing packages, but it is the distributions to add the marker file into their Python stdlib packages, to make use of that option. For end user distros this makes sense, since indeed Python packages installed via pip usually override those installed via distro package manager. GitHub runners however come with their own Python instance, NOT installed via this package manager but even located at a totally different place, where any motivation for distros to implement the marker does not apply. It stands IMO a fact that this is a burden for GitHub Action users, over-complicating things by requiring a v(irtual)env in a temporary runner image, or applying the workaround by themselves, for no reason.

**Comment by agray-ctm** [comment]
My agents are running DinD (sysbox)

./pip refers to:
```
#!/bin/bash
set -e

# Wrap "pip install" with --break-system-packages
if [ "$1" = "install" ]; then
  shift;
  pip.orig install "$@" --break-system-packages;
else
  pip.orig "$@";
fi
```
And in the Dockerfile
```
# This is a consequence of upgrading Ubuntu 22.04 -> 24.04
# Given the agents are tossed away each run, this is a reasonable tradeoff
RUN mv $(which pip3) /usr/bin/pip.orig
COPY --chmod=755 ./pip /usr/bin/pip3
COPY --chmod=755 ./pip /usr/bin/pip
RUN dos2unix /usr/bin/pip3 /usr/bin/pip
```

If you're not using DinD, just do the pip replacement manually.
