### ISSUE TITLE
Bug Report - Intermittent Screen Resolution Change Issue in GitHub Actions Workflow

### ISSUE THREAD

**Issue by mohit-sculptsoft** [actions/runner-images#8620]
### Description

I'm encountering an intermittent issue with screen resolution changes in a GitHub Actions workflow running on macOS-latest. The problem seems to be related to VMWare Tools and Paravirtual devices, as indicated by the error message: "Device PreExisted [00000001000002c6] Apple Paravirtual device"

![Screenshot from 2023-10-20 19-05-11](https://github.com/actions/runner-images/assets/131239259/b9b3e7ba-5df2-4201-9e1d-6f3fef21c70f)
![Screenshot from 2023-10-20 19-04-50](https://github.com/actions/runner-images/assets/131239259/021e0da5-23f9-4cff-bd57-c6a1747b3211)

GitHub Actions runner: macOS-latest
failed run: https://github.com/mohit-sculptsoft/github-azure-ss/actions/runs/6588410554/job/17900601440

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failed Run Link : https://github.com/mohit-sculptsoft/github-azure-ss/actions/runs/6588410554/job/17900601440

### Is it regression?

No

### Expected behavior

I expect to be able to change the screen resolution as part of my GitHub Actions workflow.

### Actual behavior

The screen resolution change does not work consistently. It sometimes succeeds, but at other times, I receive the error message related to VMWare Tools.

### Repro steps

Here are the steps to reproduce the issue:

1. Run the GitHub Actions workflow on macOS-latest.
2. Attempt to change the screen resolution using VMWare Tools.

**Comment by sergei-pyshnoi** [comment]
Look like new error for same repro in your previos report. So I close this as duplicate https://github.com/actions/runner-images/issues/8606
