### ISSUE TITLE
macOS-13 Image failing Xcode@5 task with message "Cannot test target [target] on Any iOS Device: Tests must be run on a concrete device"

### ISSUE THREAD

**Issue by tobiaslewinzon** [actions/runner-images#8621]
### The issue:
The following Azure Pipeline YML setup has been working until the last couple of days
```
pool:
  vmImage: 'macos-13'

- script: |
    sudo xcode-select -s /Applications/Xcode_15.0.app

- task: Xcode@5
  displayName: 'Running tests'
  inputs:
    actions: 'test'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: '[path].xcworkspace'
    scheme: '[scheme]'
    xcodeVersion: 'default'
    useXcpretty: true
    publishJUnitResults: true
    args: '-destination "platform=iOS Simulator,name=iPad (10th generation)"'
```
After the last releases on this repo around macOS 13, the Pipeline began consistently failing with this error

```
/usr/bin/xcodebuild -version
Xcode 15.0.1
Build version 15A507
/usr/bin/xcodebuild -sdk iphonesimulator17.0 -configuration Debug -workspace /Users/runner/work/1/s/[path].xcworkspace -scheme [scheme] -destination platform=iOS,name=iPad Pro (11-inch) (4th generation) test CODE_SIGNING_ALLOWED=NO | /usr/local/lib/ruby/gems/3.0.0/bin/xcpretty -r junit --no-color
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:D448B773-5393-4AD6-9011-3FB11C925D52, OS:17.0.1, name:iPad (10th generation) }
{ platform:iOS Simulator, id:3EE3BD40-239B-4309-91D9-C7F9AF6D210A, OS:17.0.1, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:75DF3EB8-680D-44A1-9FEC-197484B6082F, OS:17.0.1, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:6B725DBB-7585-48A2-B801-4BB699152CA0, OS:17.0.1, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:627D8C99-7959-44F6-83B8-EE362203A6EC, OS:17.0.1, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:838DD7EC-B8E9-43D5-A866-75BA36207564, OS:17.0.1, name:iPhone 14 }
{ platform:iOS Simulator, id:A00966E0-8965-4F3D-BFB1-3901FE575C82, OS:17.0.1, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:635E82CF-FEFA-4AFC-AD12-875FFF2D96C4, OS:17.0.1, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:E55715D8-881F-49ED-B25A-7C45E9E6CD9F, OS:17.0.1, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:3F7809C3-1016-4776-83CA-BEBEB15608F0, OS:17.0.1, name:iPhone 15 }
{ platform:iOS Simulator, id:DAF8DFCF-3099-4694-8BDE-9D9778460859, OS:17.0.1, name:iPhone 15 Plus }
{ platform:iOS Simulator, id:2FC57890-5AF7-4C05-97E3-5E34D7D30A0B, OS:17.0.1, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:00FDB8D1-678D-43F2-BC5F-7F4184D36D0B, OS:17.0.1, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:633F0356-04B4-414D-897F-DB71ECBA6D65, OS:17.0.1, name:iPhone SE (3rd generation) }
2023-10-20 13:10:03.950 xcodebuild[1251:6401] Writing error result bundle to /var/folders/q4/3s60g5510ydbd3qc3p4xflm80000gn/T/ResultBundle_2023-20-10_13-10-0003.xcresult
xcodebuild: error: Failed to build workspace [app] with scheme [scheme].: Cannot test target [target] on Any iOS Device: Tests must be run on a concrete device
##[error]Error: /usr/bin/xcodebuild failed with return code: 70
```
### What we tried:
- We tried the new macOS images using `macos-latest-xlarge` or `macos-13-xlarge`
- We updated the task setup to use the latest Xcode 15.0.1 and dumped the script that selected Xcode:
```
xcodeVersion: 'specifyPath'
xcodeDeveloperDir: '/Applications/Xcode_15.0.1.app'
```
- Carefully revised the combination of settings listed in https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xcode?view=azure-devops 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Listed under  `"Initialize job" -> "Runner Image"`
```
Runner Image
Image: macos-13
Version: 20231018.14
Included Software: https://github.com/actions/runner-images/blob/macos-13/20231018.14/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20231018.14
```

### Is it regression?

Image: macos-13 Version: 20231002.1

### Expected behavior

Tests to run the selected device.

### Actual behavior

Xcode unit tests fail with error "Failed to build workspace [app] with scheme [scheme].: Cannot test target [target] on Any iOS Device: Tests must be run on a concrete device"

### Repro steps

Running tests

**Comment by sergei-pyshnoi** [comment]
Hello @tobiaslewinzon , we will take a look.

**Comment by Seelan010111** [comment]
Also experiencing the same issue in my pipeline

**Comment by davidaberg** [comment]
We're facing the same issue. Our pipeline setup is using:
platform=iOS Simulator,name=iPhone 15
Xcode 15.0
macOS-13

**Comment by ilia-shipitsin** [comment]
@tobiaslewinzon , @davidaberg , @Seelan010111 , do you have a small project that you can share ?

I've performed few tests, with GHA yet. I was not able to repro yet. If I do "xcode-select ... 15.0", it is followed with "xcodebuild -version" displayed 15.0, not 15.0.1

I'll check with ADO, but I'm afraid my tests without real project will miss something

**Comment by davidaberg** [comment]
We are getting intermittent results. One of our branches running the same setup just passed. I will report if we see the same failure again.

**Comment by davidaberg** [comment]
```bash
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:D448B773-5393-4AD6-9011-3FB11C925D52, OS:17.0, name:iPad (10th generation) }
{ platform:iOS Simulator, id:3EE3BD40-239B-4309-91D9-C7F9AF6D210A, OS:17.0, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:75DF3EB8-680D-44A1-9FEC-197484B6082F, OS:17.0, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:6B725DBB-7585-48A2-B801-4BB699152CA0, OS:17.0, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:627D8C99-7959-44F6-83B8-EE362203A6EC, OS:17.0, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:838DD7EC-B8E9-43D5-A866-75BA36207564, OS:17.0, name:iPhone 14 }
{ platform:iOS Simulator, id:A00966E0-8965-4F3D-BFB1-3901FE575C82, OS:17.0, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:635E82CF-FEFA-4AFC-AD12-875FFF2D96C4, OS:17.0, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:E55715D8-881F-49ED-B25A-7C45E9E6CD9F, OS:17.0, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:3F7809C3-1016-4776-83CA-BEBEB15608F0, OS:17.0, name:iPhone 15 }
{ platform:iOS Simulator, id:DAF8DFCF-3099-4694-8BDE-9D9778460859, OS:17.0, name:iPhone 15 Plus }
{ platform:iOS Simulator, id:2FC57890-5AF7-4C05-97E3-5E34D7D30A0B, OS:17.0, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:00FDB8D1-678D-43F2-BC5F-7F4184D36D0B, OS:17.0, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:633F0356-04B4-414D-897F-DB71ECBA6D65, OS:17.0, name:iPhone SE (3rd generation) }
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:D448B773-5393-4AD6-9011-3FB11C925D52, OS:17.0, name:iPad (10th generation) }
{ platform:iOS Simulator, id:3EE3BD40-239B-4309-91D9-C7F9AF6D210A, OS:17.0, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:75DF3EB8-680D-44A1-9FEC-197484B6082F, OS:17.0, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:6B725DBB-7585-48A2-B801-4BB699152CA0, OS:17.0, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:627D8C99-7959-44F6-83B8-EE362203A6EC, OS:17.0, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:838DD7EC-B8E9-43D5-A866-75BA36207564, OS:17.0, name:iPhone 14 }
{ platform:iOS Simulator, id:A00966E0-8965-4F3D-BFB1-3901FE575C82, OS:17.0, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:635E82CF-FEFA-4AFC-AD12-875FFF2D96C4, OS:17.0, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:E55715D8-881F-49ED-B25A-7C45E9E6CD9F, OS:17.0, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:3F7809C3-1016-4776-83CA-BEBEB15608F0, OS:17.0, name:iPhone 15 }
{ platform:iOS Simulator, id:DAF8DFCF-3099-4694-8BDE-9D9778460859, OS:17.0, name:iPhone 15 Plus }
{ platform:iOS Simulator, id:2FC57890-5AF7-4C05-97E3-5E34D7D30A0B, OS:17.0, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:00FDB8D1-678D-43F2-BC5F-7F4184D36D0B, OS:17.0, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:633F0356-04B4-414D-897F-DB71ECBA6D65, OS:17.0, name:iPhone SE (3rd generation) }
2023-10-23 13:25:53.290 xcodebuild[4838:27097] Writing error result bundle to /var/folders/q4/3s60g5510ydbd3qc3p4xflm80000gn/T/ResultBundle_2023-23-10_13-25-0053.xcresult
xcodebuild: error: Failed to build project Example with scheme Example.: Cannot test target “Example UI Test” on “Any iOS Device”: Tests must be run on a concrete device
Error: Process completed with exit code 70.
```
@tobiaslewinzon

**Comment by ilia-shipitsin** [comment]
guys, I'm afraid I have to ask you for small project to repro this issue.

so far, I created a VM from our image, I created "hello world" iOS project and launched test. ok, it failed and we'll investigate/escalate it

however, failure is quite different from yours

![image](https://github.com/actions/runner-images/assets/125650415/149b51d3-d072-4110-b4f6-4467a157eeec)

**Comment by ilia-shipitsin** [comment]
so far, running tests on "hello world" project fails ~80%, sometimes tests pass

![image](https://github.com/actions/runner-images/assets/125650415/45bde878-3cb9-4908-aae6-ddef91efc76e)

**Comment by tobiaslewinzon** [comment]
@ilia-shipitsin Thanks. What setup are you using? Any args to setup SDK, iOS device, etc?  Also, the issue we are experiencing is on unit tests, not UI tests. Maybe mirroring that will prompt the same error.

Sorry for the late reply, I will try to run tests on a dummy project on our Pipeline later today and send it over. However, I don't think it will make a difference because our error prompts before even the tests suite runs. It just complains about the lack of a specified device, which we have been specifying and was working fine until October 19th.

**Comment by ilia-shipitsin** [comment]
@tobiaslewinzon , @davidaberg , @Seelan010111 , can I ask you to add "brew install virtualbox" and "brew install qemu" to your workflow ?

accidently, I used vm for another investigation and I installed virtualbox and qemu on it.
yesterday I got all tests failed, today I got all tests passed.

we do not add "virtualbox" and "qemu" to macos-13 image. I wonder whether one of them is required for simulators.

**Comment by ilia-shipitsin** [comment]
> @ilia-shipitsin Thanks. What setup are you using? Any args to setup SDK, iOS device, etc? Also, the issue we are experiencing is on unit tests, not UI tests. Maybe mirroring that will prompt the same error.
> 
> Sorry for the late reply, I will try to run tests on a dummy project on our Pipeline later today and send it over. However, I don't think it will make a difference because our error prompts before even the tests suite runs. It just complains about the lack of a specified device, which we have been specifying and was working fine until October 19th.

it would be nice to play with the same project.
I created "swift" iOS project in XCode, I launch tests using "xcodebuild test -scheme ilia -destination "platform=iOS Simulator,name=iPad (10th generation)"

**Comment by jcesarmobile** [comment]
We are having a similar intermittent failure, looks like some macos-13 machines don't have simulators installed.

We just run `pod spec lint our.podspec --allow-warnings` and two days ago started failing with this error message

> Encountered an unknown error (Could not find a `ios` simulator (valid values: tvos, watchos). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Yesterday it was still intermittent, but today it looks permanent or none of our restarts is picking an image with simulators.

**Comment by lingzlu** [comment]
Has anyone found a mitigation to the issue? Our build pipeline is encountering the same problem started yesterday. All xcodebuild test step failed because the specified destination was not honored, resulting in the error message: 'Tests must be run on a concrete device.

**Comment by ilia-shipitsin** [comment]
we had long running deploy which has finished just today. before today your builds may be run either on "old" or "new" images.
starting from today it should be all new.

please try.

**Comment by johnmalatras** [comment]
I am facing a different but similar error after updating my workflow to use `macos13`:
```
Testing failed:
	No Accounts: Add a new account in Accounts settings.
	No profiles for 'com.substack.SubstackUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.substack.SubstackUITests.xctrunner'.
	No Accounts: Add a new account in Accounts settings.
	Provisioning profile "iOS Team Provisioning Profile: com.substack.Substack" doesn't include the currently selected device "Mac-1698336258996.local" (identifier 0000FE00-A4034866B7C2B1E0).
	No Accounts: Add a new account in Accounts settings.
	Provisioning profile "iOS Team Provisioning Profile: com.substack.Substack.NotificationServiceExtension" doesn't include the currently selected device "Mac-1698336258996.local" (identifier 0000FE00-A4034866B7C2B1E0).
	No Accounts: Add a new account in Accounts settings.
	Provisioning profile "iOS Team Provisioning Profile: com.substack.Substack.ShareExtension" doesn't include the currently selected device "Mac-1698336258996.local" (identifier 0000FE00-A4034866B7C2B1E0).
	Testing cancelled because the build failed.
```

In particular `Provisioning profile ... doesn't include the currently selected device "Mac-1698336258996.local"` is the similar error

**Comment by johnmalatras** [comment]
Update: if I use `macos13` instead, I get the same error that you all are reporting:
```
xcodebuild: error: Failed to build project Substack with scheme Substack.: Cannot test target “SubstackTests” on “Any iOS Device”: Tests must be run on a concrete device
Cannot test target “SubstackUITests” on “Any iOS Device”: Tests must be run on a concrete device
Cannot test target “NotificationServiceTests” on “Any iOS Device”: Tests must be run on a concrete device
```

**Comment by lingzlu** [comment]
> The issue seems to be related to the Xcode pipeline task. I replaced the task with a command line script and executed a similar command as generated by the Xcode task. This resolved the issue for me.
> 
> > xcodebuild test -sdk iphonesimulator -configuration Debug -workspace App.xcworkspace -scheme TestScheme
> > -destination "platform=iOS Simulator,name=iPhone 14"

The issue actually isn't related to the Xcode task. Coincidentally, the issue was resolved for me because, when I ran it with the command line, I forgot to explicitly set the Xcode version. By default, it picked up Xcode 14.3.1. The issue reoccurred after I set the Xcode version to 15.0. However, when I tried 15.0.1, the issue went away. So, it seems like the issue is related to Xcode 15.0.

**Comment by ilia-shipitsin** [comment]
> The issue seems to be related to the Xcode pipeline task. I replaced the task with a command line script and executed a similar command as generated by the Xcode task. This resolved the issue for me.
> 
> > xcodebuild test -sdk iphonesimulator -configuration Debug -workspace App.xcworkspace -scheme TestScheme
> > -destination "platform=iOS Simulator,name=iPhone 14"

if so, it should be reported to to them.

**Comment by ilia-shipitsin** [comment]
> I am facing a different but similar error after updating my workflow to use `macos13-xlarge`:
> 
> ```
> Testing failed:
> 	No Accounts: Add a new account in Accounts settings.
> 	No profiles for 'com.substack.SubstackUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.substack.SubstackUITests.xctrunner'.
> 	No Accounts: Add a new account in Accounts settings.
> 	Provisioning profile "iOS Team Provisioning Profile: com.substack.Substack" doesn't include the currently selected device "Mac-1698336258996.local" (identifier 0000FE00-A4034866B7C2B1E0).
> 	No Accounts: Add a new account in Accounts settings.
> 	Provisioning profile "iOS Team Provisioning Profile: com.substack.Substack.NotificationServiceExtension" doesn't include the currently selected device "Mac-1698336258996.local" (identifier 0000FE00-A4034866B7C2B1E0).
> 	No Accounts: Add a new account in Accounts settings.
> 	Provisioning profile "iOS Team Provisioning Profile: com.substack.Substack.ShareExtension" doesn't include the currently selected device "Mac-1698336258996.local" (identifier 0000FE00-A4034866B7C2B1E0).
> 	Testing cancelled because the build failed.
> ```
> 
> In particular `Provisioning profile ... doesn't include the currently selected device "Mac-1698336258996.local"` is the similar error

I think we do will benefit from mixing all possible issues into one thread.
please open a dedicated issue for better observability

**Comment by ilia-shipitsin** [comment]
> > The issue seems to be related to the Xcode pipeline task. I replaced the task with a command line script and executed a similar command as generated by the Xcode task. This resolved the issue for me.
> > > xcodebuild test -sdk iphonesimulator -configuration Debug -workspace App.xcworkspace -scheme TestScheme
> > > -destination "platform=iOS Simulator,name=iPhone 14"
> 
> The issue actually isn't related to the Xcode task. Coincidentally, the issue was resolved for me because, when I ran it with the command line, I forgot to explicitly set the Xcode version. By default, it picked up Xcode 14.3.1. The issue reoccurred after I set the Xcode version to 15.0. However, when I tried 15.0.1, the issue went away. So, it seems like there's a compatibility issue with the new image and Xcode 15.0.

we've removed 15.0.0 from new image.
it is currently a symlink to 15.0.1

if that resolved an issue, can we close it ?

**Comment by jcesarmobile** [comment]
For us Xcode 15.0 still doesn't work, using 15.0.1 fixed the issue

Failing task
https://github.com/ionic-team/capacitor/actions/runs/6660057593/job/18112918645
> ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: tvos, watchos). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Fixed with 15.0.1: https://github.com/ionic-team/capacitor/actions/runs/6664838833/job/18113266701

**Comment by lingzlu** [comment]
> > > The issue seems to be related to the Xcode pipeline task. I replaced the task with a command line script and executed a similar command as generated by the Xcode task. This resolved the issue for me.
> > > > xcodebuild test -sdk iphonesimulator -configuration Debug -workspace App.xcworkspace -scheme TestScheme
> > > > -destination "platform=iOS Simulator,name=iPhone 14"
> > 
> > 
> > The issue actually isn't related to the Xcode task. Coincidentally, the issue was resolved for me because, when I ran it with the command line, I forgot to explicitly set the Xcode version. By default, it picked up Xcode 14.3.1. The issue reoccurred after I set the Xcode version to 15.0. However, when I tried 15.0.1, the issue went away. So, it seems like there's a compatibility issue with the new image and Xcode 15.0.
> 
> we've removed 15.0.0 from new image. it is currently a symlink to 15.0.1
> 
> if that resolved an issue, can we close it ?

ah, if Xcode 15.0 was removed from the new image, that does explain the problem. 
I'm not the one who opened the issue. Since 15.0.1 mitigates the issue, I think it's fine to close. 🙂

**Comment by jay-canty-dept** [comment]
I fixed my tests with:

**Comment by tobiaslewinzon** [comment]
Thanks everyone. Tests run smoothly now with the following setup for Xcode 15.0.1:
```
xcodeVersion: 'specifyPath'
xcodeDeveloperDir: '/Applications/Xcode_15.0.1.app'
args: '-destination "platform=iOS Simulator,name=iPad (10th generation)"'
```
Closing the ussue.
