### ISSUE TITLE
Update VirtualBox in macos-12 runners

### ISSUE THREAD

**Issue by dereknola** [actions/runner-images#8625]
### Tool name

Virtualbox

### Tool license

VirtualBox: GPL2 (https://www.virtualbox.org/wiki/Licensing_FAQ)

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.0.10,a,158379

### Brief description of tool

Please update the brew installed version of VirtualBox. It is currently on `virtualbox 6.1.38,153438` which was published over a year ago. 

When VirtualBox 7.0.0 was released, Internal Networking was broken for MacOS, and as such, the version was pinned in https://github.com/actions/runner-images/pull/6391. However, support was added back in 7.0.2 (see https://www.virtualbox.org/wiki/Changelog-7.0 )

![image](https://github.com/actions/runner-images/assets/11727736/ce10218f-deed-433f-a7ce-aab220a75665)

Additional fixes have been introduced in the year since, it is now safe to use the newest versions of Virtualbox.

### URL for tool's homepage

https://www.virtualbox.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No, you cannot use `brew install` during CI run as there are limitations around KEXT permissions.

Attempting to call `brew install --cast virtualbox` sees the following error:

An error occurred durning 'sudo /sbin/kextunload -m org.virtualbox.kext.VBoxDrv', there should be a message above. (rc=71)
Failed to unload one or more KEXTs, please reboot the machine to complete the uninstall.
```
```


### Tool installation time in runtime

_No response_

### Are you willing to submit a PR?

Yes

**Comment by dereknola** [comment]
I am happy to open a PR to fix this, however it appears that MacOS changes are currently not accepted as stated in the https://github.com/actions/runner-images/blob/main/CONTRIBUTING.md#macos guide. Let me know if this limitation is not applicable for this fix.

**Comment by ilia-shipitsin** [comment]
hello, we'll have a look

**Comment by vpolikarpov-akvelon** [comment]
Hey @dereknola. Unfortunately, updating VirtualBox to version 7 still breaks many pipelines. Here is an example: https://github.com/actions/runner-images/issues/8730. We will have to revert this update. Sorry for that.

**Comment by dereknola** [comment]
Unfortunate
