### ISSUE TITLE
Update/Add Python 3.12

### ISSUE THREAD

**Issue by remyjette** [actions/runner-images#8626]
### Tool name

Python 3

### Tool license

https://github.com/python/cpython/blob/main/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.12

### Brief description of tool

Python 3.12 was added in the Ubuntu 20231005.3.0 image but 20231016.1.0 (via #8510) removes it, going back to 3.11.x.

Creating an issue to track so we can understand the reason for the revert and when we can expect 3.12 to be pre-installed in the images again.

### URL for tool's homepage

https://www.python.org/

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

**Comment by ilia-shipitsin** [comment]
we'll have a look, thanks

**Comment by mikhailkoliada** [comment]
we got python 3.12 added back and it should be released by the end of next week (current images are deployed without that exact commit)
