### ISSUE TITLE
Unit tests pass when ran locally or on a cloud server but not from within GitHub action

### ISSUE THREAD

**Issue by sdd** [actions/runner-images#8648]
### Description

I maintain a Rust library, https://github.com/sdd/kiddo.

The library has an opt-in feature, `simd`, disabled by default. Enabling this feature turns on conditional compilation for some code paths that use SIMD intrinsics.

Running the test suite without the `simd` feature enabled works fine on GitHub Actions (see example here: https://github.com/sdd/kiddo/actions/runs/6626247812/job/17998782025)

Running the test suite with the `simd` feature enabled works fine on my local Linux desktop (a Ryzen 5900x), as well as on an EC2 linux host that runs on an Intel Xeon that has AVX2, but fails on the GitHub Actions runner. (see https://github.com/sdd/kiddo/actions/runs/6626251084/job/17998791562?pr=97)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231016.1.0

https://github.com/sdd/kiddo/actions/runs/6626251084/job/17998791562?pr=97

### Is it regression?

No

### Expected behavior

Test suite passes

### Actual behavior

Test suite fails on `immutable::float::query::nearest_one::tests::can_query_nearest_one_item` and `immutable::float::query::nearest_one::tests::can_query_nearest_one_item_large_scale`

### Repro steps

Running the tests:

```bash
git clone git@github.com:sdd/kiddo.git
cd kiddo
export RUSTFLAGS='-C target-feature=+avx2'
cargo test --workspace --all-features --release -- --show-output
```

All tests pass everywhere I've tried to run them, except GitHub actions, where two of the tests fail when the `simd` feature is enabled, enabling compilation of the codepath that runs SIMD intrinsics on x86/x86_64 architectures with the AVX2 CPU feature present

**Comment by ilia-shipitsin** [comment]
as I can see, according to `cat /proc/cpuinfo` there's avx2 support

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E[5](https://github.com/ilia-shipitsin/avx2/actions/runs/6628213838/job/18004801821#step:3:6)-2[6](https://github.com/ilia-shipitsin/avx2/actions/runs/6628213838/job/18004801821#step:3:7)[7](https://github.com/ilia-shipitsin/avx2/actions/runs/6628213838/job/18004801821#step:3:8)3 v4 @ 2.30GHz
stepping	: 1
microcode	: 0xffffffff
cpu MHz		: 2294.6[8](https://github.com/ilia-shipitsin/avx2/actions/runs/6628213838/job/18004801821#step:3:9)6
cache size	: 51200 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit mmio_stale_data
bogomips	: 458[9](https://github.com/ilia-shipitsin/avx2/actions/runs/6628213838/job/18004801821#step:3:10).37
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```


can we run some simple AVX2 related test to see that cpu is working as expected ? currently it looks like "something on rust side"

**Comment by sdd** [comment]
My mistake. I was setting the RUSTFLAGS env var on the wrong pipeline step. I have things working on GH actions perfectly well now. Thanks for your time!
