### ISSUE TITLE
Remove MSVC 14.35 in vs2022 which is out of support

### ISSUE THREAD

**Issue by toothache** [actions/runner-images#8654]
### Description

Remove MSVC 14.35 in vs2022 which is out of support.
![image](https://github.com/actions/runner-images/assets/2187096/668b6e5f-352e-48ab-81e5-44d2a541fb19)

The existence of MSVC 14.35 also conflicts with the default one and causes issues to load the correct compiler version using cmake:
#8259

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

win22/20231016.1

### Is it regression?

No

### Expected behavior

Remove the out of support 14.35 components.

### Actual behavior

MSVC 14.35 is installed.

https://github.com/actions/runner-images/blob/32c795e64ca31dded26ab79c86bd9e3a6d542d74/images/win/Windows2022-Readme.md?plain=1#L390-L407

### Repro steps

https://github.com/actions/runner-images/blob/32c795e64ca31dded26ab79c86bd9e3a6d542d74/images/win/Windows2022-Readme.md?plain=1#L390-L407

**Comment by ilia-shipitsin** [comment]
currently deployed image contains the following workloads

![image](https://github.com/actions/runner-images/assets/125650415/17f43ac8-0a49-4cee-ae30-35cc4d72e10e)


as far as we include latest version, you can pick it.
indeed, there are some "out of support" workloads, it is good to remove them, but I think there always may be several versions of the same workloads, people usually ask us to provide them.

if there would have been two versions, neither of which is outdated, will it make cmake tooling happy ? I'm not sure

**Comment by toothache** [comment]
> if there would have been two versions, neither of which is outdated, will it make cmake tooling happy ? I'm not sure

Yes. But that's another issue. See my comments in #8259 and [issue](https://developercommunity.visualstudio.com/t/MicrosoftVCToolsVersionv143defaulttx/10041951), VS team should fix the unexpected behavior.

**Comment by ilia-shipitsin** [comment]
we'll try to improve our algo and exclude "out of date" (if that's possible). however, usually you can expect several workloads at a time due to demand from customers.

**Comment by toothache** [comment]
> we'll try to improve our algo and exclude "out of date" (if that's possible). however, usually you can expect several workloads at a time due to demand from customers.

Understood. Btw, vs installer has an optiom to auto remove out of support compoments.
https://developercommunity.visualstudio.com/t/Easily-remove-all-out-of-support-compone/10111534

**Comment by ilia-shipitsin** [comment]
> > we'll try to improve our algo and exclude "out of date" (if that's possible). however, usually you can expect several workloads at a time due to demand from customers.
> 
> Understood. Btw, vs installer has an optiom to auto remove out of support compoments. https://developercommunity.visualstudio.com/t/Easily-remove-all-out-of-support-compone/10111534

is that possible to run it in "dry run" mode ? in order to detect if there's anything outdated

**Comment by MehdiChinoune** [comment]
Sorry to ask, It maybe off-topic. Is there a way to make CMake use the latest version `14.37`. It uses `14.35` by default. `cmake -T version 14.37` fails.

**Comment by toothache** [comment]
> Sorry to ask, It maybe off-topic. Is there a way to make CMake use the latest version `14.37`. It uses `14.35` by default. `cmake -T version 14.37` fails.

CMake thinks 14.37 is the default. It will ignore the version string passed from the command line if they are the same. However, MSVC (vcvarsall.bat) thinks 14.35 is the default. That's why you can't get cmake using the latest version.

My current work around is removing `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.*`

You can also see my comments in https://github.com/actions/runner-images/issues/8259#issuecomment-1777259871

**Comment by toothache** [comment]
> is that possible to run it in "dry run" mode ? in order to detect if there's anything outdated

I haven't seen such option as far as i know. But you may export all installed components before and after running `-removeoos` and then make a diff?

**Comment by MehdiChinoune** [comment]
> CMake thinks 14.37 is the default. It will ignore the version string passed from the command line if they are the same. However, MSVC (vcvarsall.bat) thinks 14.35 is the default. That's why you can't get cmake using the latest version.

I am confused, What do you mean?
CMake is not ignoring version string, It fails to configure the project.

**Comment by toothache** [comment]
> > CMake thinks 14.37 is the default. It will ignore the version string passed from the command line if they are the same. However, MSVC (vcvarsall.bat) thinks 14.35 is the default. That's why you can't get cmake using the latest version.
> 
> I am confused, What do you mean? CMake is not ignoring version string, It fails to configure the project.

You missed the equal sign. The correct syntax is like this, [link](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html#visual-studio-toolset-selection):
```
cmake .. -T version=14.37
```

However, even if you successfully specify the version string in the command line, it's very likely that CMake won't be able to configure the latest toolset version. I explained the reason in the last reply. 

However

**Comment by MehdiChinoune** [comment]
> You missed the equal sign. The correct syntax is like this, [link](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html#visual-studio-toolset-selection):
> ```
> cmake .. -T version=14.37
> ```

Actually I missed it only here, in my workflow I used it correctly.

**Comment by vpolikarpov-akvelon** [comment]
@toothache, an [update](https://github.com/actions/runner-images/pull/8686) has been deployed. Could you check your workflow now please?
