### ISSUE TITLE
New apple silicon runners don't work

### ISSUE THREAD

**Issue by epicfaace** [actions/runner-images#8661]
### Description

The new apple silicon runners don't work. See this for a reproduction: https://github.com/epicfaace/dockertest/pull/7 and https://github.com/epicfaace/dockertest/actions/runs/6647145143/job/18062024643?pr=7

<img width="1096" alt="image" src="https://github.com/actions/runner-images/assets/1689183/b9f661c0-644d-4a8a-a9af-bcd014c8afb6">

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-latest-xlarge

### Is it regression?

Yes

### Expected behavior

It should work

### Actual behavior

It doesn't work

### Repro steps

Run this action in this PR https://github.com/epicfaace/dockertest/pull/7

**Comment by mikhailkoliada** [comment]
Hey!

Well, your workflow has number of mistakes which makes it incompatible with arm64 runner, though the job with your yaml is picked up 

<img width="1086" alt="image" src="https://github.com/actions/runner-images/assets/88318005/2a1bf02d-051a-4af3-a63a-4500d2225103">

It is outside of the scope of the  hosted images (at least it looks like for now), please report your issue to the [actions/runner](https://github.com/actions/runner) as I think it is a better place to start in this specific case, they can always reach us if they think they need our assistance or we can help them with additional investigation.
