### ISSUE TITLE
Permissions on /dev/kvm set in composite action are reset since latest update

### ISSUE THREAD

**Issue by DaanDeMeyer** [actions/runner-images#8670]
### Description

I have an action that changes the permissions of /dev/vhost-vsock: https://github.com/systemd/mkosi/blob/4b225181a9d47f9a3c10b793ec70a2e1138fd4db/action.yaml#L17.

Up until now, this worked fine and users of my action would see the changed permission. Since the latest update this week, our CI has started failing because the permission is now being reset to the original default of 666. (e.g. https://github.com/systemd/mkosi/actions/runs/6654068019/job/18081436758#step:9:6)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Green job with previous image version: https://github.com/systemd/mkosi/actions/runs/6643480344/job/18050698993#step:1:9
Red job with new image version: https://github.com/systemd/mkosi/actions/runs/6654068019/job/18081436758#step:1:9

### Is it regression?

yes it's a regression, latest working image version: 20231016.1.0

### Expected behavior

Changes made to permissions of /dev/vhost-vsock in composite action are retained.

### Actual behavior

Changes made to permissions of /dev/vhost-vsock in composite action are lost.

### Repro steps

1. Modify permissions of /dev/vhost-vsock to 666 in composite action
2. Check permissions of /dev/vhost-vsock in another action using the composite action

**Comment by ilia-shipitsin** [comment]
thanks, we'll have a look

**Comment by ilia-shipitsin** [comment]
"/dev" permissions are managed by udev which is systemd subsystem.
I see that you install some packages which update systemd as well

https://github.com/systemd/mkosi/actions/runs/6654068019/job/18081436758#step:3:180

can it be the cause of permission change ?

**Comment by DaanDeMeyer** [comment]
This was indeed caused by a systemd update (which someone was the cause of the image update I guess). I found a workaround so closing the issue
