### ISSUE TITLE
Add Linux arm64 images

### ISSUE THREAD

**Issue by inf17101** [actions/runner-images#8677]
### Tool name

Linux arm64

### Tool license

arm64 architecture

### Add or update?

- [X] Add
- [ ] Update

### Desired version

arm64

### Brief description of tool

Could you please enable GitHub actions to support building Linux ARM64 binaries using ARM64 machines? 

Currently, as a workaround, we are using cross builds for our projects which is slower compared to original arm64 builds.

Thus, it would be very useful for a lot of projects to have Linux arm64 support in GH actions.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by ilia-shipitsin** [comment]
sure, there's already a ticket for tracking that

https://github.com/actions/runner-images/issues/5631

**Comment by inf17101** [comment]
> sure, there's already a ticket for tracking that
> 
> #5631

Thanks for your reply. Is there a timeline defined when the arm64 are going public and available?
