### ISSUE TITLE
Ubuntu image build fails.

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#8681]
### Description

Ubuntu build fails.... (issue is intermittent)

Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0%2b9_amd64.deb  400  Bad Request [IP: 151.101.39.42 443]

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231025.1.0

### Is it regression?

NA

### Expected behavior

Build gets completed.

### Actual behavior

build fails with error

    azure-arm.build_image:   temurin-17-jdk
    azure-arm.build_image: 0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded.
    azure-arm.build_image: Need to get 166 MB of archives.
    azure-arm.build_image: After this operation, 331 MB of additional disk space will be used.
    azure-arm.build_image: Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0+9
    azure-arm.build_image:   400  Bad Request [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0%2b9_amd64.deb  400  Bad Request [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-17-jdk-amd64/release: No such file or directory

### Repro steps

rerun build stage

**Comment by erik-bershel** [comment]
Hey @jaswant-dnv!
Issue with Adoptium's delivery here. https://github.com/adoptium/installer/issues/766
Lets wait them to fix it.

**Comment by jaswant-dnv** [comment]
Just to update.

==> azure-arm.build_image: Provisioning with shell script: /agent/_work/1/s/runner-images/images/linux/scripts/installers/sqlpackage.sh
    azure-arm.build_image: Downloading 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' to '/tmp/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb'...
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 19 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 18 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 17 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 16 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 15 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 14 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 13 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 12 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 11 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 10 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 9 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 8 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 7 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 6 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 5 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 4 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 3 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 2 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 1 attempts left
    azure-arm.build_image: Error — Either HTTP response code for 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 0 attempts left
    azure-arm.build_image: Could not download http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_image:

**Comment by ilia-shipitsin** [comment]
maybe it worth to switch to github releases https://github.com/actions/runner-images/discussions/8675#discussioncomment-7406834

**Comment by erik-bershel** [comment]
Seems resolved by Adoptium team.

**Comment by jaswant-dnv** [comment]
I don't find this working yet

    azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-17-jdk-amd64/release: No such file or directory
    azure-arm.build_image: Java 17 Toolcache Version Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk//usr/lib/jvm/temurin-17-jdk-amd64/bin/java:
    azure-arm.build_image: Setting up JAVA_HOME_17_X64 variable to /usr/lib/jvm/temurin-17-jdk-amd64
    azure-arm.build_image: JAVA_HOME_17_X64=/usr/lib/jvm/temurin-17-jdk-amd64
    azure-arm.build_image: Reading package lists...
    azure-arm.build_image: Building dependency tree...
    azure-arm.build_image: Reading state information...
    azure-arm.build_image: The following packages were automatically installed and are no longer required:
    azure-arm.build_image:   liblldb-13 liblldb-15
    azure-arm.build_image: Use 'sudo apt autoremove' to remove them.
    azure-arm.build_image: The following NEW packages will be installed:
    azure-arm.build_image:   temurin-21-jdk
    azure-arm.build_image: 0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded.
    azure-arm.build_image: Need to get 177 MB of archives.
    azure-arm.build_image: After this operation, 360 MB of additional disk space will be used.
    azure-arm.build_image: Get:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12 [177 MB]
    azure-arm.build_image: Ign:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12
    azure-arm.build_image: Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12
    azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-21-jdk-amd64/release: No such file or directory
    azure-arm.build_image: Java 21 Toolcache Version Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk//usr/lib

**Comment by DevOpsAzurance** [comment]
> I don't find this working yet
> 
> ```
> azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
> ```
> 
> ==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb Error reading from server. Remote end closed connection [IP: 151.101.39.42 443] ==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? ==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-17-jdk-amd64/release: No such file or directory azure-arm.build_image: Java 17 Toolcache Version Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk//usr/lib/jvm/temurin-17-jdk-amd64/bin/java: azure-arm.build_image: Setting up JAVA_HOME_17_X64 variable to /usr/lib/jvm/temurin-17-jdk-amd64 azure-arm.build_image: JAVA_HOME_17_X64=/usr/lib/jvm/temurin-17-jdk-amd64 azure-arm.build_image: Reading package lists... azure-arm.build_image: Building dependency tree... azure-arm.build_image: Reading state information... azure-arm.build_image: The following packages were automatically installed and are no longer required: azure-arm.build_image: liblldb-13 liblldb-15 azure-arm.build_image: Use 'sudo apt autoremove' to remove them. azure-arm.build_image: The following NEW packages will be installed: azure-arm.build_image: temurin-21-jdk azure-arm.build_image: 0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded. azure-arm.build_image: Need to get 177 MB of archives. azure-arm.build_image: After this operation, 360 MB of additional disk space will be used. azure-arm.build_image: Get:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12 [177 MB] azure-arm.build_image: Ign:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12 azure-arm.build_image: Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12 azure-arm.build_image: Error reading from server. Remote end closed connection [IP: 151.101.39.42 443] ==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb Error reading from server. Remote end closed connection [IP: 151.101.39.42 443] ==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? ==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-21-jdk-amd64/release: No such file or directory azure-arm.build_image: Java 21 Toolcache Version Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk//usr/lib

Having this issue as well.   I am reaching out to my Cloud and SOC teams, as they handle Defender and Sentinel separately.  I am having a few other issues that may be related to those, including:

"IMAGE_STATE_UNDEPLOYABLE" on the Windows build
and the above for the Ubuntu 22.04 build.  Works perfectly fine in my personal VS subscription, but once I migrate it to deploy to our main organization subscription...all hell breaks loose:

![image](https://github.com/actions/runner-images/assets/7709919/d3ff8d55-4f2c-4424-b7d8-c0dcaf299f96)
