### ISSUE TITLE
Builds unexpectedly failing from Friday

### ISSUE THREAD

**Issue by zeroDivider** [actions/runner-images#8685]
### Description

Hi,

I had some actions setup and I got issues from friday - nothing was changed in `build.gradle` or `.yml` files. Everything is working when building in Android Studio and in console on my Mac with same commands from actions.

It is an android app, built on every pushed commit and on every pushed tag using actions. It was working last time on thursday.

My actions had:
```
jobs:
  Build:
    name: Release
    runs-on: ubuntu-latest
    ...
```

After I got an issue, I have tried fixing runner as:
```
jobs:
  Build:
    name: Release
    runs-on: ubuntu-20.04
    ...
```

A few steps passed and it crashes on:
```
      - name: Build DEV apk
        run: ./gradlew assembleMyAppPackageDebug
```

More info on build related setup of my app:
`build.gradle` app module:
```
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
```
I have tried with `JavaVersion.VERSION_11` - not working
`build.gradle` project:
```
classpath 'com.android.tools.build:gradle:7.3.1'
```
(inform me if you need more info, I am not sure what else I should include)
Thank you :)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: ubuntu-20.04
  Version: 20231025.1.0
--------
Runner Image
  Image: ubuntu-22.04
  Version: 20231025.1.0

### Is it regression?

Image: ubuntu-22.04   Version: 20231016.1.0

### Expected behavior

Build should pass sucessfully.

### Actual behavior

Build failed with some unexpected errors including build generated files

### Repro steps

no steps

**Comment by erik-bershel** [comment]
Hey @zeroDivider!
There really isn't enough information here to draw any conclusions. Please provide as much information as possible. Error logs, link to the failed launch, repro steps (as short as possible). I don't see anything among the updates between these versions of runners that could affect you, and our tests are also going well.

**Comment by zeroDivider** [comment]
Hi, here are logs:
```
/home/runner/work/myaoov1-client-android/myappv1-client-android/app/src/main/java/com/myapp/user/ui/fragment/auth/PhoneNumberFragment.java:171: error: cannot find symbol

                safeNavigate(requireView(), PhoneNumberFragmentDirections.backToLogin());
> Task :app:compileButlerGmsDebugJavaWithJavac
                                                                         ^
  symbol:   method backToLogin()
  location: class PhoneNumberFragmentDirections
```
Thanks for your patient, I think we may be in different time zones.

**I am afraid I cannot send link to build since it is private repository and I cannot make it public, text me if we can do something related to this small issue**

It seems it has a problem generating navigation directions. Problem is that it was working until few days ago, I did not do anything about build or library versions. It is also working when building in Android Studio and in command line with same commands listed in my `.yml` files for GitHub Actions. (you can find it in initial issue description)

I put this in app module `build.gradle`:
```
apply plugin: "androidx.navigation.safeargs"
```
and this is in project `build.gradle`
```
classpath 'com.android.tools.build:gradle:7.3.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10"
classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.5.2'
```
I am using java 8 for compilation and I have also tried upgrading to 11 and 17 - no changes, still failing.

**Comment by erik-bershel** [comment]
It's still really hard to say what is the real reason of this issue without repro steps or example project. It might be dependency issue in case you used inherited methods. I'm pretty sure you know that the error itself says that `method backToLogin()` wasn't recognised by compiler. I may only guess without full information here.

As I said, there were no changes between these two images that could affect your environment. Let's think about the hypothetical possibility that some of the libraries that we cannot yet calculate (without repro) were damaged. In this case, the next image should fix the situation (deployment is already in progress, should take about three days).

I'll be there for you if you found an opportunity to spoil more light on the issue. Might be helpful if you didn't saw it yet: https://stackoverflow.com/questions/25706216/what-does-a-cannot-find-symbol-or-cannot-resolve-symbol-error-mean

**Comment by zeroDivider** [comment]
Okay. What do you need me to share?
```
name: "Everyday Development Build"

on:
  pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Clean
      run: ./gradlew clean

    - name: Build Butler Dev Environment (Google)
      run: ./gradlew app:assembleMyAppVariantDebug

    - name: Release to Firebase App Distribution (Google)
      run: FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} ./gradlew appDistributionUploadMyAppVariantDebug
```

I know what is the error, but the fact is that your _unchanged environment_ run same commands that I use last 6 month is now having an error in build. Every time before building, I do clean. So, there is no way your runner was saving something and suddenly it got removed.

This is navigation graph:
```
<fragment
        android:id="@+id/phoneNumberFragment"
        android:name="com.myapp.ui.fragment.auth.PhoneNumberFragment"
        android:label="PhoneNumberFragment"
        tools:layout="@layout/fragment_phone_number">
        ...
        <action
            android:id="@+id/back_to_login"
            app:destination="@id/signInFragment"
            app:launchSingleTop="true"
            app:popUpTo="@id/phoneNumberFragment"
            app:popUpToInclusive="true" />
    </fragment>
```
and `androidx.navigation.safeargs` based on that generates file with direction that we use in app later. This is the output:
```
public class PhoneNumberFragmentDirections {
  private PhoneNumberFragmentDirections() {
  }

  @NonNull
  public static NavDirections backToLogin() {
    return new ActionOnlyNavDirections(R.id.back_to_login);
  }
}
```
Directory is: `app/build/generated/source/navigation-args/myAppVariant/debug/my/app/package/auth/PhoneNumberFragmentDirections.java`
The file is not here after build is done and it says `error: cannot find symbol` since it is not there.

Just like you, I did not touch my local environment and everything works just fine, after I click `Run 'app'` green button and also in case I use command line - just like listed in my `.yml` file:
`./gradlew app:assembleMyAppVariantDebug`

I am successfully building and installing my app for days, on my computer and on computers of my co-workers.
Last time I merged and built successfully my latest commit and when problem started I tried pushing tag that is triggering my action, it did not work - no matter nothing changed:
<img width="953" alt="image" src="https://github.com/actions/runner-images/assets/17478088/ba6c58da-71e7-4852-afbd-29f498a1f9b7">

GithubActions are not useful to me anymore, as simple as that. If I don't do a thing and it is failing, no point in using it anymore. I am not sure that you believe me when I say a thing did not change except UI - no build files, no graphs.

And the problem is not that that one method is unavailable. It seems no directions are generated. The only thing that changed is something on runner or in library (but I did not change library version)

**Comment by erik-bershel** [comment]
@zeroDivider 
Hey, in no way did I question your words about changes in the project. This is a very common situation when the cause of a build crash is an update of the tools involved in the process, or the dependencies that the project pulls up. This is the difficulty of your particular case. There were no visible changes to the base image that would even theoretically affect your build. In this case, we would have already come to a solution, but this is not it.

I am as interested in solving the problem as you are, but unfortunately this is not always a quick and easy process. At the moment, I believe that we have at least some basis from which we can build on in further investigation. I'll be back with clarifications later.

**Comment by dromer** [comment]
Just found this out myself. Had updated some docs and then my midi tests fail somehow: https://github.com/Wasted-Audio/hvcc/actions/runs/6716331081/job/18252650852#step:6:22

Reverting to `ubuntu-20.04` "fixed it" for me, but it's really hard for me to trace what could've gone wrong in this case.

My tests rely on retrieving stdout and comparing it to a known file and the test-result seems to be it's comparing an empty list. However other tests that work similarly do succeed, so really no clue :shrug:

**Comment by erik-bershel** [comment]
Hey @dromer! Do you believe that the missing file in this case was caused by the reasons you indicated? I suppose that the current problem (this issue) and yours should not be related, but I would be glad to be wrong.

**Comment by dromer** [comment]
@erik-bershel what do you mean missing file? I believe a file is created, but stdout is empty somehow.

I honestly don't know to which report this info should go (this was the first I spotted, then later saw more). The fact that other tests that work similarly (run binary; redirect stdout to file; compare with original) are successful just adds to the confusion.

Should I make a separate report then?

**Comment by erik-bershel** [comment]
@dromer oh, no. I was asking about @zeroDivider issue with android app. Your issue seems not related to the current. It would be better to open new item.

**Comment by zeroDivider** [comment]
Hi, @erik-bershel 

Whatever you did, it worked! <3 It is okay now, my pipelines work like they did just last week.
(It also worked for short period yesterday, cca 18 hours ago, but shortly after that, it started failing again - now okay, as I mentioned)

Thank you for your support!

**Comment by erik-bershel** [comment]
@zeroDivider I'm glad your builds is okay now. And I’ll add again - it’s really important for us to help users, unfortunately this doesn’t always happen as quickly and as easily as we would like.
A clarification regarding your case - we have not found the real reason for what happened. Looks like a transitive error when building one of the participating libraries (on the image side, not your project itself). Accordingly, hypothetically, this could appear again.

**Comment by zeroDivider** [comment]
> hypothetically, this could appear again.

Yep, it did appear again

**Comment by erik-bershel** [comment]
@zeroDivider may I ask you to send build-link. No matter private or public. I'll check available information.

**Comment by erik-bershel** [comment]
Hey @zeroDivider! 
We will try to reproduce the error. Couple questions just to be on the same page:
- Is it the same mistake now?
- In case if it successfully builds in local environment please provide versions of installed software (gradle, android sdk, jdk).
If we have any suggestions (or questions), we will come back with additional information.

**Comment by zeroDivider** [comment]
Hi, thanks for your reply.
Yes, of course :)

- it is same error
- installed software versions: **gradle** - `gradle-7.4-all`, **android sdk** - `33` (both compile and target), **jdk** - `JavaVersion.VERSION_1_8`

Have a nice day :)

**Comment by erik-bershel** [comment]
@zeroDivider while we thinking could you be so kind to try run your wf with different Java setups?
example:
```yml
- uses: actions/setup-java@v3
  with:
    distribution: 'zulu'
    java-version: '17'
```
Supported distributions (NOTE: in images you may find Temurin 11.0.21+9 by default): https://github.com/actions/setup-java#supported-distributions

**Comment by zeroDivider** [comment]
Hey,

I am not using actions for Java setup. I also have tried with java 11, but it was working just the same as with 8. And for Java 17, my app is not compatible with it.

**Comment by erik-bershel** [comment]
@zeroDivider hmm. I'm not gradle-buld senior user, but it seems like you have to setup Java if you want to build on Java 8, because on image default version is 11. Yes, sure, you may do it on your own (not using actions) since Java 8 is being installed. And it might be distribution related issue too. It's the reason why I ask you to check your build on other versions of JDKs.

**Comment by zeroDivider** [comment]
It is setup in gradle file and I have tried last time setting it up to 11.. did not work. At some point it started working, no one knew why.

**Comment by erik-bershel** [comment]
@zeroDivider 
Without access to the code, we cannot continue diagnostics on our part. Need a minimal project with a similar problem or a public fork of your project if possible.
Or we can try building with JDKs from other distributors on your side.
I would also like to ask you to check the peak amount of memory that is consumed during the build process in your local environment - I noticed that at a certain point in time the free RAM on the runner runs out. This could be one of the possible reasons if gradle run out of memory.

**Comment by zeroDivider** [comment]
How much RAM is there on your runner? It is highly demanding build, I think. Android studio is requiring `8 GB RAM or more` and it does very well in case there is 16GB+.

I'll try crating similar project when I get time and also do some research/upgrades around my app. For now I think I will disable my actions. It works just fine from Android Studio and from command line running same scripts. Somehow almost magically, it starts happening around runners update lately and I cannot help it, obviously.

**Comment by erik-bershel** [comment]
Hi @zeroDivider!

Yes, sure, whatever is more convenient for you. Please, text me back when you have new information - I will be happy to join the investigation. Unfortunately, at the moment we can only guess what exactly happened from our side - we do not have access to private projects. Couple cents:
- In the case of a blind search, I would start by checking different Java distributions - maybe it'll help catch a more informative error-message about why it fails generating navigation directions. 
- You can also dig into the optimisation of the build when using Gradle - since such processes are quite resource-intensive, free runners cannot always provide the required amount of resources. Perhaps they were not enough to assemble a component that was to be used later. A fair question would be why the environment did not throw an error in this case. You may read more information about such cases here: https://github.com/actions/runner-images/discussions/7188

So, please, feel free to ping me here about this issue and also feel free to open new items in case of other concerns.

**Comment by erik-bershel** [comment]
Hi @zeroDivider!
`Time was ~8 min and now it is ~4.` Is it about build time in local environment or about time building in Actions before getting failure? Hope it's first option.
I'm still trying to find someone with a similar problem to yours. If I'm lucky, I'll be happy to share the information I find.
