### ISSUE TITLE
Format windows temporary/build disk using ReFS

### ISSUE THREAD

**Issue by MatthewSteeples** [actions/runner-images#8698]
### Tool name

DevDrive / ReFS

### Tool license

Windows

### Add or update?

- [X] Add
- [ ] Update

### Desired version

N/A

### Approximate size

N/A

### Brief description of tool

Not technically a request for a new tool, but a change in configuration of the build agents.

ReFS (Resilient FileSystem) (which backs [DevDrive](https://devblogs.microsoft.com/visualstudio/devdrive/)) can reduce the amount of time required to build a project with very little input required on the developer's behalf.

It may cause breaking changes if anyone relies on [specific functionality of NTFS](https://learn.microsoft.com/en-us/windows-server/storage/refs/refs-overview#the-following-features-are-unavailable-on-refs-at-this-time) as part of their build process. 

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
I'm not familiar with how the build agents are deployed, but it's possible that the Temp drive is not part of the "image". If that's the case then 1 of the following steps would need to be performed before the build agent picks up a task:

1) Quick format the D drive to replace the NTFS filesystem with ReFS
2) Copy a .vhdx file pre-formatted with ReFS onto the D drive and use that as the build drive
```

### Tool installation time in runtime

< 10 seconds

### Are you willing to submit a PR?

I would love to but I don't think it's part of the "image"

**Comment by erik-bershel** [comment]
Hello @MatthewSteeples! 
The idea as a whole is interesting and has already been investigated before. Unfortunately, implementation is not practical at the moment - the predicted negative impact is too large. Perhaps we will return to this issue when we release the next version of Windows.

**Comment by fowl2** [comment]
Now that [CoW is automatically enabled for ReFS/DevDrive](https://devblogs.microsoft.com/engineering-at-microsoft/copy-on-write-performance-and-debugging/), I think enabling it in the hosted images would have an even greater impact. So much building involves copying files.
