### ISSUE TITLE
Major Refactoring of GitHub Actions Runner Images Repository

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#8706]
### Breaking changes

We are currently undergoing a major refactoring of our repository. This notice is relevant to anyone who builds their own VM images from this repo. If you do not build images, these changes do not impact you.

### Target date

The refactoring process has already started, and you can review the ongoing work in our open pull requests ([Windows](https://github.com/actions/runner-images/pull/8616), [Ubuntu](https://github.com/actions/runner-images/pull/8627), [macOS](https://github.com/actions/runner-images/pull/8741)). The merging of these changes into the main branch is scheduled to start on November 15th. Please note that the entire process, including all changes and adjustments, is expected to take a couple of months.

### The motivation for the changes

The current structure of the repository has grown organically over time and has become difficult to manage and navigate. The refactoring will include changes to the directory structure, script renaming, and code refactoring to improve the organization and readability of the code, making it easier for contributors to find and modify the scripts they need.

### Possible impact

Scripts that rely on specific file paths may need to be updated to reflect the new directory structure. We will strive to minimize the impact of these changes and communicate known issues in advance. We appreciate your patience during this process.

### Platforms affected

This refactoring work is focused on the repository structure and won't directly affect the runners themselves. Therefore, there is no specific platform impact to note in this context.

### Runner images affected

- [x] Ubuntu 20.04
- [x] Ubuntu 22.04
- [x] macOS 11
- [x] macOS 12
- [x] macOS 13
- [x] Windows Server 2019
- [x] Windows Server 2022

### Mitigation 

We recommend reviewing your workflows and scripts that interact with our repository and preparing to update any hard-coded file paths or script names. We will provide a detailed mapping of the old and new directory structures and script names to assist with this process in separate pull requests, attached to the announcement.

We appreciate your understanding and cooperation during this refactoring process. Our goal is to make our repository more manageable and user-friendly, and we believe these changes will greatly assist in achieving that goal.

**Comment by elldritch** [comment]
FYI, this change has broken the documentation links at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#preinstalled-software.

**Comment by mikhailkoliada** [comment]
@elldritch nice catch, we will pass it to the respective team.

**Comment by renemadsen** [comment]
Links in the https://github.com/actions/runner-images/blob/main/README.md are pointing to https://gh-runnerimagesdeploymentstatus.azurewebsites.net/api/status?imageName=ubuntu22&redirect=1 which in turn redirects to https://github.com/actions/runner-images/blob/releases/ubuntu22/20231115/images/linux/Ubuntu2204-Readme.md
and doing the refectoring is not correct.

**Comment by BartDecker** [comment]
Something is going awry with the newly updated image.

Ubuntu-latest -> 20231115.8.0 -> errors related to the below.
Ubuntu-Latest -> 20231030.2.0 -> workflow ok

note: we have multiple git projects having the same workflows targeting different environments, running in a nightly deploy schedule, which are all failing at the moment after the version was updated. No code changes were made, no yamls adjusted. The only thing changed is the runner image version so I think it's related to something that changed in the image.

This is a job that also imports an az.resourcegraph module because the jobs needs it. 

 | Failed to process the requested module(s). This module requires
     | Az.Accounts version 2.9.1. An earlier version of Az.Accounts is imported
     | in the current PowerShell session. Please open a new session before
     | importing this module. This error could indicate that multiple
     | incompatible versions of the Azure PowerShell cmdlets are installed on
     | your system. Please see https://aka.ms/azps-version-error for
     | troubleshooting information.

**Comment by Alexey-Ayupov** [comment]
Hello @renemadsen, we have fixed it.

**Comment by markatky46** [comment]
To all involved in this, just wanted to say a massive well done. Well documented, well communicated major change.

**Comment by m-soltani** [comment]
Yes, Big thanks for this reorganization. It helped also our team, a lot.

**Comment by mikhailkoliada** [comment]
I believe everything planned has been done! Thanks for the feedback.
