### ISSUE TITLE
'pip install aqtinstall' to target directory broken by macOS CI image update

### ISSUE THREAD

**Issue by Steveice10** [actions/runner-images#8709]
### Description

As part of our macOS build we use pip to install `aqtinstall`, which allows us to download official Qt builds to compile against. We do this pretty early on with barely any changes to the runner environment from start.

When our job runs on `macos-13` version `20231018.14` this install succeeds. When it runs on `macos-13` version `20231025.2`, it fails with a compile error for `inflate64`, `pybcj`, and `pyppmd`.

Passing job: https://github.com/citra-emu/citra/actions/runs/6726923198/job/18283974803
 - pip succeeds but the job is cancelled by other job failing

Failing job: https://github.com/citra-emu/citra/actions/runs/6726923198/job/18283975021
 - pip fails with a compile error

Notably, when using the old image pip only needs to build wheels for a smaller set of packages, which excludes the failing packages: `Building wheels for collected packages: patch, bs4` vs `Building wheels for collected packages: patch, bs4, inflate64, pybcj, pyppmd`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: `macos-13` version `20231025.2`.

Build: https://github.com/citra-emu/citra/actions/runs/6726923198/job/18283975021

### Is it regression?

Yes; worked on version `20231018.14`.

### Expected behavior

I expect the `pip install` command to succeed.

### Actual behavior

The `pip install` command fails due to strange compile errors building wheels for three packages.

### Repro steps

1. Set up a `macos-13` runner.
2. Install `aqtinstall` to a target directory: `mkdir temp && pip install --target=temp aqtinstall`.

**Comment by erik-bershel** [comment]
Hello @Steveice10! We'll take a look on your issue. Some of our team-members will be there soon with an update for you.

**Comment by Steveice10** [comment]
The dependencies of the tool in question have been updated with Python 3.12.0 support and seem to be working now, so I'll go ahead and close this.
