### ISSUE TITLE
Checksum verification failed for kotlin-compiler-1.9.20 during packer build for Win2022

### ISSUE THREAD

**Issue by carentsen** [actions/runner-images#8732]
### Description

Checksum validation fails for kotlin-compiler package during packer build for Win2022 for both release 20231024.1 and 20231029.1
 (latest). It seems somewhat related to https://github.com/actions/runner-images/issues/8440 in terms of validation of checksum, except the checksum in this case seems so be related to the kotlin package and not actual sum, more details below. 

This is built in an Azure DevOps CICD pipeline using the packer scripts as described in [Runner-image in CICD](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#automated-image-generation).

**Packer build executes**
```
==> image: Provisioning with powershell script: C:\a\1\Build.PackerScripts\runner-images-win22-20231029.1\images\win/scripts/Installers/Install-Kotlin.ps1
    image: Downloading package from: https://github.com/JetBrains/kotlin/releases/download/v1.9.20/kotlin-compiler-1.9.20.zip to path C:\Users\packer\AppData\Local\Temp\kotlin-compiler.zip .
    image: Package downloaded successfully in 0.8 seconds
==> image: Checksum verification failed. Expected hash: kotlincompiler1920zip; Actual hash:
==> image: 15A8A2825B74CCF6C44E04E97672DB802D2DF75CE2FBB63EF0539BF3AE5006F0.
==> image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:673 char:9
==> image: +         throw "Checksum verification failed. Expected hash: $Distribu ...
==> image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> image:     + CategoryInfo          : OperationStopped: (Checksum verifi...539BF3AE5006F0.:String) [], RuntimeException
==> image:     + FullyQualifiedErrorId : Checksum verification failed. Expected hash: kotlincompiler1920zip; Actual hash: 15A8A28
==> image:    25B74CCF6C44E04E97672DB802D2DF75CE2FBB63EF0539BF3AE5006F0.
==> image:
==> image: Provisioning step had errors: Running the cleanup provisioner, if present...
```

Notice expected hash: **Expected hash: kotlincompiler1920zip**.

I have not attempted earlier releases of the win2022 config. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

[20231029.1 (latest)](https://github.com/actions/runner-images/releases/tag/win22%2F20231029.1) and [20231024.1](https://github.com/actions/runner-images/releases/tag/win22%2F20231024.1)

### Is it regression?

Not sure. Have not attempted since 2022.

### Expected behavior

Checksum should pass. Expected checksum should be a checksum and not *kotlincompiler1920zip*

### Actual behavior

Checksum validation fails, and as a result the packer build fails.

### Repro steps

Attempt to build Windows Server 2022 following the [instructions for CICD](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#automated-image-generation).

**Comment by erik-bershel** [comment]
Hi @carentsen! It was fixed here: https://github.com/actions/runner-images/pull/8704.

Please do not use tags/branches other than the `main`. Only it has an up-to-date status.

**Comment by erik-bershel** [comment]
@carentsen 
I think I may post a link to the pull request when it's ready so you can start your build as soon as it's merged. Please write if you do not need this.

**Comment by carentsen** [comment]
@erik-bershel Thank you so much for the quick response! I missed the PR, sorry. 
I am, however, slightly puzzled by your `main` branch comment, as I looked to the releases, and took latest stable, does that not come from master?

And yes, please keep me posted, thank you.

**Comment by erik-bershel** [comment]
@carentsen yeah, that is tricky point. Release tags are not reproducible - almost always there are some fixes in `main`, and the difference between `main` and `release/tag` brunches almost always leads to build failures.

**Comment by drazkiewicz** [comment]
I did run both Windows and Linux pipelines on Saturday - the error is still there.
