### ISSUE TITLE
iOS App built with Xcode 15.0.1 on ADO macos-13 runner image(20231025.2) cannot be submitted for TestFlight testing

### ISSUE THREAD

**Issue by guojiubo** [actions/runner-images#8734]
### Description

Yesterday, our ADO macos-13 runner images have been upgraded to version 20231025.2. But when we tried to submit our app for TestFlight testing this afternoon, we got the following error:

> **This build is using a beta version of Xcode and can’t be submitted. Make sure you’re using the latest version of Xcode or the latest seed release found on the releases tab in [News and Updates](https://developer.apple.com/news/releases/)**

**It seems that the App Store thinks the app was built with a beta version of Xcode.**

Previously, the runner image (20231018.14) had both Xcode 15.0 and 15.0.1 installed, and we were using Xcode 15.0 and everything was fine. However, yesterday, ADO upgraded the runner images to version 20231025.2 and removed Xcode 15.0, so we are now using Xcode 15.0.1 and have encountered the issue.

<img width="682" alt="image" src="https://github.com/actions/runner-images/assets/1475090/b572ed1b-8aa7-4fbd-97a7-d0d1c0baabf5">

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: macos-13
Version: 20231025.2

### Is it regression?

Not sure, because we just switched to Xcode 15.0.1

### Expected behavior

The app can be submitted for TestFlight review.

### Actual behavior

The app cannot be submitted for TestFlight review.

### Repro steps

1. Build an app with Xcode 15.0.1
2. Upload it to TestFlight and submit for TestFlight review

**Comment by erik-bershel** [comment]
Hey @guojiubo! Thank you for pointing out this issue. It seems that there is a bug in XCode 15.0.1: 
- https://developer.apple.com/forums/thread/740871
- https://developer.apple.com/forums/thread/740853
We'll think what we may do about it. Please wait for updates from us.

**Comment by ilia-shipitsin** [comment]
@guojiubo , can you please have a look at "Initialize job", what image version is displayed there ?

![image](https://github.com/actions/runner-images/assets/125650415/60d35084-2f7a-46d0-be88-492462246e9d)

in early images 15.0.1 was a beta, but 20231025.2 is supposed to be shipped with 15.0.1 release.
I think accidently your build may reach oldish image, I'd be surprised if it is actually 20231025.2

**Comment by erik-bershel** [comment]
Hey @guojiubo! 
Can you try again? Apple support says the problem has been resolved [here](https://developer.apple.com/forums/thread/740871).

**Comment by guojiubo** [comment]
Hi @erik-bershel, yes, the problem has been resolved. Thank you!
