### ISSUE TITLE
Safari extension project created using Xcode 15.0.1 fails to build

### ISSUE THREAD

**Issue by infinitepower18** [actions/runner-images#8736]
### Description

I have recently built my Safari extension project using Xcode 15.0.1, however the build is failing with this message being spammed in the logs:

```
2023-11-03 16:58:02.722 xcodebuild[2343:11929] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x6000013[18](https://github.com/infinitepower18/CloneInVSCode-Safari/actions/runs/6748099483/job/18345724692#step:5:19)3c0>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com/ with this warning message and any useful information you can provide.
```

It however builds without any issue on my local machine.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20231025.2
https://github.com/infinitepower18/CloneInVSCode-Safari/actions/runs/6748099483/job/18345724692

### Is it regression?

Project builds without issue when the extension project was previously created using Xcode 13. https://github.com/infinitepower18/CloneInVSCode-Safari/actions/runs/6739075160/job/18319896063

### Expected behavior

The build should have succeeded.

### Actual behavior

The build fails with this error spammed many times:

```
2023-11-03 16:58:02.722 xcodebuild[2343:11929] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x6000013[18](https://github.com/infinitepower18/CloneInVSCode-Safari/actions/runs/6748099483/job/18345724692#step:5:19)3c0>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com/ with this warning message and any useful information you can provide.
```

### Repro steps

1. Create a new Safari extension project using Xcode 15.0.1 using `--macos-only` and `--copy-resources` flags: https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari/
2. Commit the project to GitHub
3. Create the workflow: https://github.com/infinitepower18/CloneInVSCode-Safari/blob/main/.github/workflows/xcode.yml

**Comment by ilia-shipitsin** [comment]
there's similar report https://developer.apple.com/forums/thread/737923
that makes me beleive that "it is something on XCode side", which should be reported to Apple

**Comment by sergei-pyshnoi** [comment]
Hello @infinitepower18 . After some investigation, we found that is possible reason is in incorrect configuration signing certificates  . After removing pipe `xcpretty && exit ${PIPESTATUS[0]}` in `xcodebuild` command can additional logs that contain error with:

```
/Users/runner/CloneInVSCode-Safari/Clone in VS Code.xcodeproj: error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "3W9UA5X43W" with a private key was found. (in target 'Clone in VS Code Extension' from project 'Clone in VS Code')
/Users/runner/CloneInVSCode-Safari/Clone in VS Code.xcodeproj: error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "3W9UA5X43W" with a private key was found. (in target 'Clone in VS Code' from project 'Clone in VS Code')
** ANALYZE FAILED **
```

**Comment by infinitepower18** [comment]
Removing the development team solved the issue. Thanks.
