### ISSUE TITLE
Windows Image build fails with error

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#8737]
### Description

Windows Image build fails with error. Looks like Typo 

    azure-arm.image: [=======================================] 100% Unzipping... share/vim/vimfiles/s
    azure-arm.image:
==> azure-arm.image: Warning: Failed to find package 'patcher;v4'
    azure-arm.image: [=======================================] 100% Unzipping... android-ndk-r23c/sha

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image 20231029.1.0

### Is it regression?

NA

### Expected behavior

Image is build

### Actual behavior

    azure-arm.image: [=======================================] 100% Unzipping... share/vim/vimfiles/s
    azure-arm.image:
==> azure-arm.image: Warning: Failed to find package 'patcher;v4'
    azure-arm.image: [=======================================] 100% Unzipping... android-ndk-r23c/sha

### Repro steps

Rerun pipeline.

**Comment by shamil-mubarakshin** [comment]
Hello @jaswant-dnv.
We are working on the issue

**Comment by mikhailkoliada** [comment]
Should be fixed now, do not forget to pull the latest changes from main :)
