### ISSUE TITLE
ghc on macOS 11

### ISSUE THREAD

**Issue by quark17** [actions/runner-images#8738]
### Description

The GitHub Actions CI for the `b-lang-org/bsc` repo was passing two days ago and then we merged a PR that only updated a README, and the CI triggered by that is failing, even when re-run.  So it seems that something has changed in the environment.  We do install some software using homebrew and ghcup, so those could be the source of the issue, but in this case I think it may be a change in the VM.

The repo has jobs on two Ubuntu VMs and three macOS VMs; the Ubuntu VMs are fine and the macOS 13 VM is fine.  But the macOS 11 VM fails ([see here](https://github.com/B-Lang-org/bsc/actions/runs/6757594575/job/18369693049)).  (The macOS 12 VM appears to be fine, but is killed because of the macOS 11 failure.)

The source of the failure is when we attempt to install GHC version 9.4.7 using ghcup.  We do this for all five VMs, but only on macOS 11 does it have a problem.  In the job "Install dependencies", there is this warning:
```
The upgrade will not be in effect, unless you remove /usr/local/bin/ghc
or make sure /Users/runner/.ghcup/bin comes before /usr/local/bin in PATH.
```
And later, in the stage `Build`, the version of GHC is reported, and it is reported as 9.6.2, which is the default GHC for the macOS 11 VM.  So, indeed, the ghcup-installed GHC is not first on the path.  And that's why the CI fails: in the job "Test Haskell Language Server", a mismatch is detected between the GHC version that was used to build and the GHC version of the HLS.

I tried to be helpful by debugging the issue myself, but I'm not understanding how the code in this repo works.  I see, for example, that macOS 11 and 12 VMs have GHC 9.6.2, but macOS 13 has GHC 9.8.1 -- but I can't see any place in this repo where those are separately specified.  In this repo, there is the file [`images/macos/provision/core/haskell.sh`](https://github.com/actions/runner-images/blob/main/images/macos/provision/core/haskell.sh), but it seems to be same across all the versions.  I don't know why macOS 11 would have GHC installed in `/usr/local/bin/` while macOS 12 and 13 do not.  It's also possible that macOS 12 and 13 do have it, but they put `/Users/runner/.ghcup/bin` earlier in the PATH.  However, I don't see where that would happen.  The only place is, again, in the `haskell.sh` provision script:
```
export PATH="$HOME/.ghcup/bin:$PATH"
echo 'export PATH="$PATH:$HOME/.ghcup/bin"' >> "$HOME/.bashrc"
```
Although it's interesting that the first line puts it first in the path but the second line puts it last.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Link to the failing job in our public repo: https://github.com/B-Lang-org/bsc/actions/runs/6757594575/job/18369693049

As reported there:
```
Current runner version: '2.311.0'
```

However, if I go to the last time the job passed, I see that it is also using that runner version:
https://github.com/B-Lang-org/bsc/actions/runs/6738428521/job/18317983989

### Is it regression?

Yes

### Expected behavior

I expect that the following command:
```
ghcup install ghc 9.4.7
```
Should not report a warning about the path.  And, when finished, running `ghc --version` should report 9.4.7.

### Actual behavior

Currently, the ghcup install command has this at the end:
```
[ Warn  ] [
[ ...   ] The upgrade will not be in effect, unless you remove /usr/local/bin/ghc
[ ...   ] or make sure /Users/runner/.ghcup/bin comes before /usr/local/bin in PATH.
```
What I've shown here is the text copied from GitHub's report, but I expect that the first line should have more text!  So that also seems like an odd bug.  (Looking at ghcup's source code, I expect the line to say `ghc is shadowed by /usr/local/bin/ghc`.)

### Repro steps

It's probably as simple as running `ghcup install ghc 9.4.7` in the macOS 11 VM.

**Comment by quark17** [comment]
I created a new repo with a very simple example: https://github.com/quark17/runner-ghcup-test

It has a workflow job that just does this (on two Ubuntu and three macOS VMs):
```
ghcup install ghc 9.4.7
ghcup set ghc 9.4.7
ghc --version
```
You can see that for macOS 11, we have this result, showing that ghcup is not first in the path:
```
[ Info  ] GHC 9.4.7 successfully set as default version
The Glorious Glasgow Haskell Compilation System, version 9.6.2
```
But for the other four systems, we have the expected result:
```
[ Info  ] GHC 9.4.7 successfully set as default version
The Glorious Glasgow Haskell Compilation System, version 9.4.7
```

**Comment by quark17** [comment]
I added `which -a ghc` to the job, and the output confirms that the macOS 11 runner has GHC in `/usr/local/bin/` but none of the other systems do.

**Comment by shamil-mubarakshin** [comment]
Hi @quark17, thanks for reporting.
We will take a look

**Comment by shamil-mubarakshin** [comment]
@quark17, the issue seems to reside in `brew` being deprecated on macos-11. Packages are built from source, so `yq` package installs `pandoc`, `ghc`, `cabal-install` by dependency and creates links in `/usr/local/bin/`. Could you try a workaround in your workflow for `build-macOS` job:
```
- name: Unlink brew ghc/cabal
  if: ${{ matrix.os=='macos-11' }}
  run: |
    brew unlink ghc cabal-install
```

**Comment by quark17** [comment]
Thanks.  However, I don't believe that `ghc` is installed in `brew`, so I don't think that workaround would help?

It's the tool `ghcup` that is used to install versions of `ghc`.  And the existence of `ghc` in `/usr/local/bin/` wouldn't be problem, except that the `haskell.sh` provision script puts `$HOME/.ghcup/bin` later in the path than `/usr/local/bin`.

It seems like the options are: (1) Remove `ghc` from `/usr/local/bin`; (2) change the Haskell provision script to put `$HOME/.ghcup/bin` earlier in the path (in the bashrc file); or (3) a workaround in the user's workflow to change the path.  If the first two can't be done, then I can implement the third locally using something like this:
```
- name: Put ghcup early in PATH
  run: |
    echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
```
Or else add this to each action that needs it:
```
  run: |
    export PATH=$HOME/.ghcup/bin:$PATH
```
I have confirmed that this works by pushing a new commit to the example repo, and observing the [results](https://github.com/quark17/runner-ghcup-test/actions/runs/6796116876/job/18475531652).  The "install dependencies" step is still first and shows the wrong ghc, but then a step after that updates the path, and a third "check GHC" step then shows that the right GHC is found first.

Is there a reason why the Haskell provision script puts ghcup later in the path?  My vote would be to change that script.  But I'm ok to implement the path-change workaround locally, if needed.

**Comment by quark17** [comment]
Oh, sorry, I see what you mean.  The `yq` package in `brew` has installed `ghc`.  Ah, let me try the unlink then.  However, I still wonder if the change to the provision script wouldn't be best.

**Comment by quark17** [comment]
Unlinking also works.  I used this command, between calls to brew to install packages and calls to ghcup to install ghc:
```
(brew list ghc > /dev/null 2>&1) && brew unlink ghc
(brew list cabal-install > /dev/null 2>&1) && brew unlink cabal-install
```
It displays the `brew unlink` output when the package exists and displays nothing otherwise.  If by chance our call to `brew` installs ghc on other VMs, it would unlink in that case, too.

**Comment by mikhailkoliada** [comment]
Should be deployed next week

**Comment by mikhailkoliada** [comment]
fix deployed
