### ISSUE TITLE
Update/Add PowerShell Core

### ISSUE THREAD

**Issue by tig** [actions/runner-images#8754]
### Tool name

PowerShell Core

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.3.9

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

yes

**Comment by tig** [comment]
Reason:

PowerShell 7.2.6, which is in the current runners was built with .NET 6.x.

PowerShell 7.3, was built with .NET 7.x.

Any PowerShell Module that requires .NET 7 will fail with a super unhelpful error:

```
Import-Module: D:\a\_temp\bc1451cf-be26-4c21-a8ab-69d5323c81e0.ps1:7
Line |
   7 |  Import-Module Microsoft.PowerShell.ConsoleGuiTools -Verbose -Force
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral,
     | PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Error: Process completed with exit code 1.
```

I found a workaround that forces `shell: pwsh` to use a separtely installed version of 7.3.9:


```yml
- name: HACK - Install Latest PowerShell (so we get v7.3+ that uses .net 7)
  shell: pwsh
  run: |
        dotnet tool install --global PowerShell
        $prependText = "C:\Users\runneradmin\.dotnet\tools"
        $filePath = $env:GITHUB_PATH
        $content = Get-Content -Path $filePath
        $newContent = $prependText + "`r`n" + $content
        $newContent | Set-Content -Path $filePath -Encoding utf8
```

Related to this, I think it should be easier to force `shell: pwsh` to use a specific pwsh installation; it seems to always use `C:\Program Files\PowerShell\7\pwsh.EXE`. I tried `shell: C:\Users\runneradmin\.dotnet\tools\pwsh` and got an error.

**Comment by shamil-mubarakshin** [comment]
Hello @tig, PowerShell 7.3 comes with breaking changes, impacting many GitHub and Azure DevOps users. There are no update plans in the neare feature. I'm closing the issue for now
