### ISSUE TITLE
[Windows] C drive is siginificant slower than D drive which causes issue with workflow runtime being significantly increased in general

### ISSUE THREAD

**Issue by jetersen** [actions/runner-images#8755]
### Description

This seems to affect all Windows based hosted runners.
In general tool installation, download speeds and compression and decompression on anything that is on the C drive as in any IO is significantly slower compared to D drive.

Somewhat based on research in #3577 and https://github.com/actions/setup-dotnet/issues/260

Seems like actions/setup-go seems to have made a workaround for https://github.com/actions/setup-go/pull/393

There is a suggestion to make similar workarounds in the actions/setup-dotnet https://github.com/actions/setup-dotnet/issues/260#issuecomment-1794326743

Hopefully we can find a solution that is more generic for all 😅 
Maybe we can simply make the C drive similar to the D drive? That way there is no difference.
I assume this is most likely a small change in the packer script?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/jetersen/dotnet.restore.slow.github.action/actions/runs/6736383956/job/18311632176
https://github.com/jetersen/dotnet.restore.slow.github.action/actions/runs/6736262624

### Is it regression?

Yes/No it has been a constant regression

### Expected behavior

Windows actions should be similar or only a few seconds slower not like 30 seconds more.

### Actual behavior

Depending on IO everything is significantly slower sometimes a whole minute slower or longer depending on how much IO.

### Repro steps

https://github.com/jetersen/dotnet.restore.slow.github.action

**Comment by shamil-mubarakshin** [comment]
Hello @jetersen,
We will have a look

**Comment by Piedone** [comment]
As far as I understand, this would need a change of `$GITHUB_WORKSPACE` at its core. Then, `actions/checkout` would be able to use the D drive too.

**Comment by jetersen** [comment]
I don't like the solution to just move everything to the D drive 😅
It means changes throughout many actions and something all actions developers have to be aware of.

I would hope the solution was to make C drive have the same iOPS, throughput and disk technology (Premium SSD, Standard SSD, Standard HDD in azure terms)

**Comment by shamil-mubarakshin** [comment]
@jetersen, unfortunately, there is no simple fix to put C drive's performance on par with D drive.
There are certain limitations that we don't expect to be solved in the near future.
I will close the issue for now. Feel free to reach out to us in case of further concerns.

**Comment by PureKrome** [comment]
@shamil-mubarakshin 👋🏻 G'Day. I'm not sure I quite understand the solution here?

So changing the "C" drive's hardware isn't going to happen right now / short-term, etc. Fine. .. but surely there's still some possibility of doing some of the actions, running on the "D" drive, right?

or even making some approved actions that work on "D" allowing people to "opt-in" to this (for backwards compat)?

**Comment by mgood7123** [comment]
aren't we using the D drive by default anyway ?

`Working directory is 'D:\a\<repo>\<repo>'`
```yaml
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{needs.should_run.outputs.output1}}
          submodules: recursive
```
