### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by harsh29113** [actions/runner-images#8768]
### Tool name

Azure Databricks cli

### Tool license

no

### Add or update?

- [X] Add
- [X] Update

### Desired version

latest

### Brief description of tool

unable to run Azure databricks command 

unable to run databricks.exe

### URL for tool's homepage

not sure

### Provide a basic test case to validate the tool's functionality.

```bash
C:\hostedtoolcache\windows\Python\3.9.10\x64\Scripts\databricks.exe
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
not sure

C:\hostedtoolcache\windows\Python\3.9.10\x64\Scripts\databricks.exe
```

### Tool installation time in runtime

C:\hostedtoolcache\windows\Python\3.9.10\x64\Scripts\databricks.exe

### Are you willing to submit a PR?

C:\hostedtoolcache\windows\Python\3.9.10\x64\Scripts\databricks.exe

**Comment by shamil-mubarakshin** [comment]
Hello @harsh29113,
Due to maintenance concerns and short installation time, we would not like to bake the tool into the image.
Please install in runtime using: `curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh`
