### ISSUE TITLE
Finalize-VM.ps1 fails if any of the services being stopped do not exist

### ISSUE THREAD

**Issue by achechen** [actions/runner-images#8770]
### Description

there is a list of services to be disabled in the Finalize-VM.ps1 script:

```
# Disabled services
$servicesToDisable = @(
    'wuauserv'
    'DiagTrack'
    'dmwappushservice'
    'PcaSvc'
    'SysMain'
    'gupdate'
    'gupdatem'
    'StorSvc'
)

$servicesToDisable | ForEach-Object {
    Stop-Service -Name $_
    Set-Service -Name $_ -StartupType Disabled -ErrorAction Ignore
} | Out-Null
```

This works fine if you have all these services installed but we do some customizations and some of the services do not exist.
The `Set-Service` command has` -ErrorAction Ignore` but the `Stop-Service` command does not, therefore fails if a service does not exist.

Please add `-ErrorAction Ignore` to the `Stop-Service` command too.

This bug was introduced with #8605 

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest version of the main branch

### Is it regression?

yes, worked before #8605 

### Expected behavior

stop-service command should not fail if a service from the list does not exist

### Actual behavior

stop-service command fails if a service from the list does not exist

### Repro steps

see above explanations

**Comment by shamil-mubarakshin** [comment]
Hello @achechen,
Thanks for bringing this to our attention. We will have a look and fix

**Comment by shamil-mubarakshin** [comment]
@achechen, non-existent service handling has been adjusted. Please sync with main.
I will close the issue. Feel free to reach out in case of further concerns
