### ISSUE TITLE
Resolution changes when ci runs on self-hosted windows 10 runner

### ISSUE THREAD

**Issue by jiyeexxi** [actions/runner-images#8777]
### Description

The resolution of the window notebook is as follows.
![image](https://github.com/actions/runner-images/assets/76234655/451fafbf-af8f-4a59-81a1-d9a3d45cf473)

The actual resolution changes as soon as ci is turned, and the ui test fails.
Doesn't happen in previous runner versions
I couldn't find that version because it was a long time ago. Probably 2.307.1

(Should I write it like this? It's my first time, so I have a lot of shortcomings)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

actions-runner-osx-x64-2.311.0

### Is it regression?

2.307.1

### Expected behavior

Runner resolution equal to window os resolution

### Actual behavior

Smaller resolution when running on Runner

### Repro steps

1. Install runner in window 10 notebook
2. Run UI test using Pytest, selenium in runner
3. Verify that the resolution runs the same as window 10 notebook

**Comment by shamil-mubarakshin** [comment]
Hello @jiyeexxi.
This repository contains code for images used by [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) and [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent).
I would suggest asking in https://github.com/actions/runner for self-hosted runner issues
