### ISSUE TITLE
CMake being forced to use not the latest Windows SDK

### ISSUE THREAD

**Issue by MarkCallow** [actions/runner-images#8781]
### Description

My jobs running on windows_latest are always built with Windows SDK 10.0.20348.0. According to the documentation for CMake, 3.27 (which the image currently runs) should choose the latest version available. The image has the following SDK versions and 20348 is by no means the latest:

```
d----          10/29/2023 10:09 PM                10.0.10240.0
d----          10/29/2023 10:24 PM                10.0.17763.0
d----          10/29/2023 10:08 PM                10.0.19041.0
d----          10/29/2023 10:06 PM                10.0.20348.0
d----          10/29/2023 10:05 PM                10.0.22000.0
d----          10/29/2023 10:31 PM                 10.0.22621.0
```

When I run locally the latest is used.

I've tried to override the choice by setting the environment variable `WindowsSDKVersion` but it did not change the behaviour. It seems to me that the image is somehow forcing CMake to select 20348.

Why I care is that I am attempting an arm64 cross-compile of an app that links against glu32.lib and some of the arm64 SDKs, including 20348 do not have this library. It's in all the x64 SDKs. The latest 22621 has it.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version 2.311.0

https://github.com/KhronosGroup/KTX-Software/actions/runs/6834591051/job/18587498118

### Is it regression?

Unknown

### Expected behavior

I expected CMake to choose the latest SDK, 22621.

### Actual behavior

CMake is not choosing the latest SDK.

### Repro steps

Make a project that uses CMake and builds with Visual Studio 2022. Include in the CMakeLists a print out of the variables `CMAKE_SYSTEM_VERSION` and `CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION`. Observe the values printed..

**Comment by vpolikarpov-akvelon** [comment]
Hey @MarkCallow. The main difference between CI and your local environments is OS version. Runner `windows-latest` is based on Windows Server 2022 `10.0.20348`, while you local Windows 11 system is probably updated to `10.0.22621`. This is why an older version is selected, I assume. Did you try switching the policy to the old behavior and setting `CMAKE_SYSTEM_VERSION` manually?

**Comment by MarkCallow** [comment]
> Hey @MarkCallow. The main difference between CI and your local environment is OS version. Runner `windows-latest` is based on Windows Server 2022 `10.0.20348`, while you local Windows 11 system is probably updated to `10.0.22621`. This is why an older version is selected, I assume. 

But 10.0.22621 is installed on the runner. I don't understand why running on Windows Server 2022 should dictate which SDK CMake picks.

> Did you try switching the policy to the old behavior and setting `CMAKE_SYSTEM_VERSION` manually?

No. After `WindowsSDKVersion` did not work under the new behaviour I gave up and disabled that part of my build until I have a better understanding of what is going on.

**Comment by vpolikarpov-akvelon** [comment]
> I don't understand why running on Windows Server 2022 should dictate which SDK CMake picks.

I've investigated source code of CMake and seems like OS version affects SDK selection indeed: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.27.7/Source/cmGlobalVisualStudio14Generator.cxx#L526

But the code I referenced above runs only when `CMP0149` is switched to `OLD` so I would assume that something is wrong with policy activation. Unfortunately, I don't know much about it. Could you please ensure that the policy is really enables and set to `NEW`?

**Comment by vpolikarpov-akvelon** [comment]
Hey @MarkCallow. Do you have any updates? Did you succeed verifying policy state?

**Comment by MarkCallow** [comment]
Sorry for the delay replying. I've been off for a few days.

With the help of Brad King at Kitware I have determined that I had the policy setting in the wrong place. It needs to be before the first `project` command in CMakeLists.txt. After moving it, I can control which SDK is used via the `WindowsSDKVersion` environment variable. I can now build the component that needs the library missing from 10.0.20348.

As you point out, CMake is choosing to match the selected SDK to the system. There is clearly no issue with the runner image so I will close this.
