### ISSUE TITLE
Update/Add PSResourceGet module (PowerShellGet replacement)

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [actions/runner-images#8785]
### Tool name

PSResourceGet PowerShell module (PowerShellGet replacement)

### Tool license

MIT License

### Add or update?

- [X] Add
- [X] Update

### Desired version

1.0.1 (current latest)

### Approximate size

5 MB

### Brief description of tool

PSResourceGet is the successor to PowerShellGet (PowerShell's built-in package manager). PSResourceGet was [released to general availability](https://devblogs.microsoft.com/powershell/psresourceget-is-generally-available/) early last month - this module is expected to be the new package manager for PowerShell (both 7.x+ and Windows PowerShell 5.1) in the future.

The older PowerShellGet module had significant supportability challenges, so a decision was made to release PSResourceGet under a new name and with a fundamentally different command structure. The two modules are being handled separately, with a planned update to PowerShellGet serving as a compatibility shim during the transition period. More details are available [here](https://devblogs.microsoft.com/powershell/powershellget-in-powershell-7-4-updates/).

### URL for tool's homepage

https://github.com/PowerShell/PSResourceGet

### Provide a basic test case to validate the tool's functionality.

```bash
# Does the module exist in $env:PSModulePath?
Get-Module Microsoft.PowerShell.PSResourceGet -ListAvailable

# Can we probe PSGallery for a well-known package? (assumes internet access/line-of-sight to powershellgallery.com from test environment)
Find-PSResource -Name Az -Type Module
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Install PSResourceGet module from PSGallery
# Assumes PowerShellGet v2.x and PackageManagement modules are already present
Install-Module Microsoft.PowerShell.PSResourceGet
```

### Tool installation time in runtime

Variable depending on the number of packages installed, downstream NuGet feed config, etc.

### Are you willing to submit a PR?

Yes

**Comment by Alexey-Ayupov** [comment]
Hello @hmmwhatsthisdo. We do not have plans to add `Microsoft.PowerShell.PSResourceGet` to the runner images due to maintenance concerns and small installation time. This module can be added after `PowerShellGet` module deprecation.

**Comment by wsmelton** [comment]
If the Powershell version gets updated to the latest LTS release (v4) you will get PSResourceGet automatically. It is pre-packaged with v4 of PowerShell.

ref: #8847
