### ISSUE TITLE
environment error with mingw and ctest

### ISSUE THREAD

**Issue by jeremy-rifkin** [actions/runner-images#8803]
### Description

I have stumbled across a very strange environment error causing an integration test for my C++ library to crash unexpectedly. This is an error I only encountered when upgrading to the windows-2022 runner, it did not happen on the windows-2019 runner and this is an issue I've never run into on my local windows machine.

My setup is something along the following lines
```cmake
        add_executable(integration tests/integration/integration.cpp tests/integration/a.cpp tests/integration/x/a.cpp)
        # ...
        add_test(
            NAME integration
            WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/tests
            COMMAND
            python3 run-tests.py $<TARGET_FILE:integration> ${CMAKE_BUILD_TYPE} ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_STANDARD}
        )
```
```py
    # ... eventually
    p = subprocess.Popen(
        [integration_binary],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env
    )
    output, err = p.communicate()
```

I run this all through `make test` which runs ctest which runs the python script etc.

On the github the test case fails and a diagnostic from the python script indicates the integration executable exited with an access violation exit code.

Example run and repro below.

You should see `p.retruncode = 3221225477` near the end.

The integration binary behaved normally when ran manually or in gdb, it also behaved normally when launched with subprocess in a python shell. I eventually found the environment difference between the python shell and python script under ctest to be `C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\runneradmin\\bin;` pre-pended to the start of the path. I'm not sure which of the three paths there are to blame but one of them was causing the wrong dlls to be loaded (my code was built with mingw from `C:/mingw64` and `(get-command g++).Path` is `C:\mingw64\bin\g++.exe`).

![image](https://github.com/actions/runner-images/assets/51220084/4c3cd083-7983-4efd-bfbb-f8d9cb49b9fb)

I am filing this issue here because however those folders are appended to the path does not seem to be like it can possibly be correct behavior.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20231029.1.0

https://github.com/jeremy-rifkin/libassert/actions/runs/6869853495/job/18683510917

### Is it regression?

Regression from windows-2019

### Expected behavior

The integration test should not crash

### Actual behavior

The integration test crashed

### Repro steps

```ps1
# run in powershell
git clone https://github.com/jeremy-rifkin/libassert.git
cd libassert
mkdir build
cd build
git checkout b57c78ba5ab783661fdf0a9a20b74150e4e923d4
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DASSERT_BUILD_TESTING=On "-GUnix Makefiles"
make -j
$env:CTEST_OUTPUT_ON_FAILURE=1
make test
```

**Comment by Alexey-Ayupov** [comment]
Hello @jeremy-rifkin, we will take a look.

**Comment by jeremy-rifkin** [comment]
Thanks! :)

**Comment by sergei-pyshnoi** [comment]
Hello @jeremy-rifkin . Unfortunately it is expected condition when multiply mingw  executors appears in PATH env. That versions can incompatible because its comes in bundles with other tools that installed in runner-images. We do not have plans for removing them from PATH and modify installation scripts where it appear because it can affect other workflows. If you have errors with capability , you can modify PATH in runtime (I see you already done this in your workaround) or use absolute path to mingw. I am closing issue for now, but if you have additional questions, feel free to ask.

**Comment by jeremy-rifkin** [comment]
Hi @sergei-pyshnoi, where do things go wrong with the environment, is ctest coming from a different mingw / msys install?

I'm not doing anything fancy here, I'm just running `cmake` and then `make test`. That should always work. But somehow things are going wrong such that the program fails with really strange and hard to track down errors because the wrong runtime is being loaded.

There's nothing I'm doing on my end that would cause weirdness with multiple mingws my msys installs, it should be using whatever is first in the path. There is no world where the current behavior can make sense to me and this comes as a massive detriment to the user. If I'm understanding the problem here correctly I will not be the only user affected. Please consider reopening this issue.

**Comment by TheVice** [comment]
@jeremy-rifkin whole environment using path to directory with dll from one of previous version of the MinGW.
Please read issue #6103, probably that your case too.

**Comment by WardBrian** [comment]
Just wanted to add another report to the pile that the state of the mingw environment on these runners broke something and cost me a day of chasing it down, see https://github.com/google/googletest/issues/4811 (I mistakenly blamed googletest/ctest, but it was the runner's fault)
