### ISSUE TITLE
[azure-cli] better default configuration to reduce chances of accidental data leaks

### ISSUE THREAD

**Issue by jessehouwing** [actions/runner-images#8816]
### Description

The Azure cli has a tendency to be quite chatty and this can expose secrets stored in Azure in the logs of CI tools that run it.

See:

 * https://www.paloaltonetworks.com/blog/prisma-cloud/secrets-leakage-user-error-azure-cli/
 * https://github.com/Azure/azure-cli-extensions/pull/6793/

There are a number of sensible configuration settings that can be applied to greatly reduced the chance of this happening:

```
core.only_show_errors=true
core.error_recommendation=off
core.collect_telemetry=false
logging.enable_log_file=false
```

These can either be set using `az config` or registered as environment variables. The latter being more secure as the AzureCLI@2 task in Azure pipelines ignores the global config by default.

This way command output isn't echo'id to the log by default and also not written to disk where it can easily be intercepted.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/a

### Is it regression?

no

### Expected behavior

Azure-cli is configured with sane CI/CD defaults.

There is an extension to Azure cli called `init` which provides sane automation defaults.

### Actual behavior

Azure-cli is configured in standard interactive mode.

### Repro steps

https://www.paloaltonetworks.com/blog/prisma-cloud/secrets-leakage-user-error-azure-cli/

**Comment by Alexey-Ayupov** [comment]
Hello, @jessehouwing. Thank you for your suggestion, but we prefer to use default settings since they are common for everyone. If you would like to change some behavior of Azure-cli you can try to do it in runtime.
