### ISSUE TITLE
Add `find`

### ISSUE THREAD

**Issue by elldritch** [actions/runner-images#8817]
### Tool name

find

### Tool license

GPLv3+

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

`find` is a common shell utility in package `findutils` which is considered an `essential` package by Debian and Ubuntu. Ideally, the images would add explicit dependencies on all `essential` packages. For example, see #986.

I think this package is already being installed implicitly of other existing packages, but because it's not explicitly installed, it's not listed [in the generated documentation](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md) as installed, which caused my team to waste a few cycles figuring out what exactly is installed in the runner images.

### URL for tool's homepage

https://www.gnu.org/software/findutils/manual/html_mono/find.html

### Provide a basic test case to validate the tool's functionality.

```bash
find --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt-get install findutils
```

### Tool installation time in runtime

Very fast

### Are you willing to submit a PR?

Yes, if time permits

**Comment by Alexey-Ayupov** [comment]
Hello @elldritch, we will take a look.
