### ISSUE TITLE
Update/Add xcbeautify & xcodes to the macOS runner image

### ISSUE THREAD

**Issue by Steve-Glass** [actions/runner-images#8827]
### Tool name

xcbeatufy & xcodes

### Tool license

MIT

### Add or update?

- [x] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

- xcbeautify: an OSS tool that replaces the deprecated xcpretty tool, used for formatting verbose Xcode build logs into a format that’s readable from CI/CD tooling
  - the deprecated xcpretty tool is included in all macOS Actions runner images and [no longer maintained](https://github.com/xcpretty/xcpretty/issues/360#issuecomment-538140426), and may have a variety of security issues or bugs due to lack of maintenance

- xcodes: another OSS tool that replaces the deprecated xcode-install tool, used for fetching info about, downloading and installing different versions of Xcode and iOS simulator runtimes (read: iOS versions)
  - the deprecated xcode-install is included in all macOS Actions runner images and [no longer maintained](https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md), and may have a variety of security issues or bugs due to lack of maintenance

### URL for tool's homepage

https://github.com/tuist/xcbeautify 

### Platforms where you need the tool

- [x] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

It can, but would be very beneficial to the iOS community to include these in the image.

**Comment by Alexey-Ayupov** [comment]
Hello @Steve-Glass. We will add tools to the image.

**Comment by jshier** [comment]
Is there an updated timeline for the deployment of this tool? It doesn't seem available yet.

**Comment by mikhailkoliada** [comment]
Deployed
