### ISSUE TITLE
Win2022 image: New "Java SDK 11.0 or above is required" errors when building .csproj targeting Android v12.0

### ISSUE THREAD

**Issue by dd-eg** [actions/runner-images#8828]
### Description

We have multiple .csproj files that target Android 12.0 and our Azure DevOps build pipeline uses the Windows Server 2022 agent pool to build them. After today's image update, our builds began to fail with errors like this:

```
2023-11-16T20:46:54.6444765Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0. [{path to our .csproj file]
2023-11-16T20:46:54.6448075Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Download the latest JDK at: https://aka.ms/msopenjdk [{path to our .csproj file]
2023-11-16T20:46:54.6452207Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11 [{path to our .csproj file]
```

I have found a workaround -- I added the following [JavaToolInstaller](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/java-tool-installer-v0?view=azure-pipelines) step to my pipeline:
```
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20231115.2.0

### Is it regression?

20231029.1.0

### Expected behavior

The project should build successfully, as it did on image version 20231029.1.0.

### Actual behavior

The project now fails to build.

### Repro steps

My build pipeline is complex so I can't immediately provide a working example, but below is a trimmed-down example of the kind of project file I'm trying to build using the 'windows-2022' image.

```
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Example.Android</RootNamespace>
    <AssemblyName>Example.Android</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <AndroidResgenFile>Resources\Resource.Designer.cs</AndroidResgenFile>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
    <TargetFrameworkVersion>v12.0</TargetFrameworkVersion>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Mono.Android" />
    <Reference Include="mscorlib" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
</Project>
```

**Comment by mikhailkoliada** [comment]
@dd-eg hey! This is expected behaviour as one should not really rely on the image default and pick the java version they need using the `JavaToolInstaller@0` task. That psaid, please continue using the task :)

**Comment by dd-eg** [comment]
Thanks for the quick response, much appreciated. Now that I'm reviewing the installed software, I see that the default Java version is 8, so the error makes sense.

Any thoughts as to why our builds were working on the prior image version? We changed the project's target Java framework to v12 about 8 months ago, so I'm surprised we didn't hit the issue earlier.

**Comment by mikhailkoliada** [comment]
I guess because VS on windows-2022 got updated recently

**Comment by lhughey** [comment]
This is new behavior that is breaking builds. What is the source of the change? I've been building to Android 13 for a while, and the server hasn't had issue. Did the default JDK version get rolled back on the server or did was there a Java change that previously allowed Android 13 to be built with version 8, but now requires Java version 11?

I am aware of what the fix is and understand that servers upgrade SDK versions over time, but this appears that the server downgraded the installed SDK version.
