### ISSUE TITLE
Same action, multiple different image versions 20231115.7.0 and Version: 20231030.2.0

### ISSUE THREAD

**Issue by renemadsen** [actions/runner-images#8829]
### Description

Tests are running on different versions of the Runner image, which is not expected. It needs to run on the older image until rollout is 100%. This mixed versions situation is breaking our entire CI/CD pipeline!

See https://github.com/microting/eform-angular-frontend/actions/runs/6901192700/job/18775648266

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

None failing build:
![image](https://github.com/actions/runner-images/assets/76994/3f06abde-41be-40b2-85f0-3b7802e0889b)

Failing build:
![image](https://github.com/actions/runner-images/assets/76994/ab7cdecb-f199-4b97-80de-0bbe8031b4de)

### Is it regression?

Don't know

### Expected behavior

Not mix versions until image is 100% rolled out.

Since we use chrome for the testing in this repository, the version is critical for making the tests pass. If we upgrade our dependencies to match version 119 of chrome, all the tests running on the older image with chrome 118 fails and vice versa.

### Actual behavior

Same test run is using different versions of the Runner image.

### Repro steps

Create any repository which relies on a specific version of Chrome.

**Comment by Alexey-Ayupov** [comment]
Hello @renemadsen. Unfortunately, it is impossible to pin the image version for certain customers by design. Also, we have our protocol to distribute the new image across all available pools. We are very sorry that you experiencing such an issue, and as a possible solution, you can switch to the [GitHub large runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners). Their image version update happening within one day.

**Comment by renemadsen** [comment]
> Hello @renemadsen. Unfortunately, it is impossible to pin the image version for certain customers by design. 
I don't need for us a customer, just that you consider to make it possible in general for all users of github. It could be solved with ubuntu-latest for bleadig edge following your rollout. Where ubuntu-22.04 only switching image version, when the rollout is 100% done.

> Also, we have our protocol to distribute the new image across all available pools. 
What do you mean by the above?

> We are very sorry that you experiencing such an issue, and as a possible solution, you can switch to the [GitHub large runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners). Their image version update happening within one day.
It still have the same issue, just narrowed down to one day. 

I don't understand why it's this way of rollig version instead of switching the version when rollout is 100% done?
What is the technically reason for doing it this way?

**Comment by renemadsen** [comment]
@Alexey-Ayupov actually what we need is not large runners, but some sort of stable runners. We would gladly pay for a stable CI env, where we are sure that a given runner image version is consistent across all our builds until they all switch over and not this mixed versioning as it is right now.
