### ISSUE TITLE
windows-2022 image update started breaking our builds

### ISSUE THREAD

**Issue by steve-torchia** [actions/runner-images#8836]
### Description

Yesterday, mid-day, our image windows-2022 image seems to have been changed to include .net 8.0 support but it BROKE our build which was depending on the previous image.  We started getting a bunch of nuget warnings as errors.

Is there any way for us to get back to that previous image? This was a pretty big braking change on us which is affecting our engineering groups across the company.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2022

### Is it regression?

yes

### Expected behavior

We expect the windows-2022 to not cause our builds to fail due to newly surfaced WarningsAsErrors.   At the very least we need the ability to (temporarily) get back to a previously-working image

### Actual behavior

MS build is failing our builds with Warnings as errors for nuget packages

### Repro steps

run msbuild and see the build fail with warningsaserrors

**Comment by Alexey-Ayupov** [comment]
Hello @steve-torchia. In the new image version, the .net 8 is the default version of SDK. If you need to use an older version please include the `UseDotNet` task in your pipeline.
Example:
```
  - task: UseDotNet@2
    inputs:
      version: 7.x
```

**Comment by steve-torchia** [comment]
Hi @Alexey-Ayupov, thanks for the response.   

I tried your suggestion above but have not been able to find: MSBuild version: 17.7.2.37605, which is the version I was using prior to the new image 

Is there any way I can force my way back to using that MS Build version?   

Thanks,
Steve

**Comment by mikhailkoliada** [comment]
@steve-torchia could you show how you invoke msbuild?

**Comment by steve-torchia** [comment]
We use Invoke-Build (https://github.com/nightroman/Invoke-Build) which uses Resolve-MSBuild to get the location of msbuild.exe, whose path we then use directly from the command line to invoke msbuild.

**Prior** to the new image

    $MSBuildLocation = Resolve-MSBuild -MinimumVersion 17.0   #<< This says to go find the latest 17.x version of MSBuild
    Set-Alias MSBuild $MSBuildLocation`
    Write-Build White "Using InvokeBuild version: $InvokeBuildVersion"
    Write-Build White "Using MSBuild version: ", (MSBuild /version /nologo)
    Write-Build White "MSBuild located at: $MSBuildLocation"

would yield:

>Using InvokeBuild version: 5.9.11
Using MSBuild version:  **17.7.2.37605**
MSBuild located at: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe

Using the **new** image yields:

>Using InvokeBuild version: 5.9.11
Using MSBuild version:  **17.8.3.51904**
MSBuild located at: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe

"Forcing" the pipeline image to go back to an older version via this:
  task: UseDotNet@2
    inputs:
      version: 7.x
Yields:

>Using InvokeBuild version: 5.9.11
Using MSBuild version:  **17.8.3.51904**
MSBuild located at: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe

which tells me that either the UseDotNet@2 task didn't work to force the older image (though the logs say it did) or that isn't the image that originally had msbuild version: 17.7.2.37605 installed

**Comment by steve-torchia** [comment]
here is the log from 

task: UseDotNet@2
inputs:
version: 7.x

>Starting: UseDotNet
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.230.2
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 7.x.
Found version 7.0.404 in channel 7.0 for user specified version spec: 7.x
Version 7.0.404 was not found in cache.
Getting URL to download .NET Core sdk version: 7.0.404.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.230.2\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/4f4fc500-65a8-42ca-a70c-c7f8827e7bd0/b6bbe369a0f4c16382811399bdb4a435/dotnet-sdk-7.0.404-win-x64.zip
Extracting downloaded package D:\a\_temp\a3dc11e7-3707-495a-b29b-a1534794b031.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\a3dc11e7-3707-495a-b29b-a1534794b031', 'D:\a\_temp\9968')"
Successfully installed .NET Core sdk version 7.0.404.
Creating global tool path and pre-pending to PATH.
Finishing: UseDotNet

**Comment by steve-torchia** [comment]
@mikhailkoliada @Alexey-Ayupov  Apologies if this is not the right forum for this but I don't consider this issue closed.  This was a pretty major breaking change for my company that heavily relies on the build pipeline which broke due to this image update.  

We are getting Nuget warnings as errors now as well as new compiler errors that are causing our build to break.  I acknowledge that we need to address the Nuget and Complier errors, but we have to be able to address them on our own cadence.  We cannot fix them now just to get the build running again.  Those are changes that require a wider range of testing.

**Comment by asd-oak** [comment]
FWIW, [NuGet auditing](https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages#disabling-security-auditing) has to be opted-out of with the latest image. I found that writeup from this issue: https://github.com/dotnet/project-system/issues/9246 

@steve-torchia I dug in after seeing your comment on the other thread; we had some builds that might have been affected (turned out OK; they didn't have warnings treated as errors) and some other builds that _were_ affected by other changes to MSBuild as part of the .net8 release cycle. Whether it helps or not--good luck.

**Comment by steve-torchia** [comment]
I don't see how this auditing could have been on by default.  This is a **breaking** change for anyone using automated builds

**Comment by gioce90** [comment]
Me and my company are having the exactly same issue.

**Comment by immoderate** [comment]
Our company has also been experiencing this mysterious Azure build failure since the image was updated last week, what exactly is the solution? Updating to DotNet v7 or v6 with the `UseDotNet@2` task did not resolve the problem.
```
  - task: UseDotNet@2
    inputs:
      version: 7.x
```

**Comment by gioce90** [comment]
Hi @immoderate in my company we resovled in the same way, but stay stick with the .NET6 version.
