### ISSUE TITLE
pip install ray on macos-latest intermittently fails

### ISSUE THREAD

**Issue by amitschang** [actions/runner-images#8839]
### Description

I have a test with a dependency on the python "ray" package, and it runs on ubuntu-latest and macos-latest. During the pip install phase, macos fails intermittently - required one or several times clicking on "rerun jobs". Eventually it will succeed as the ray package is in fact available. The same test on ubuntu does not exhibit the same behavior. 

The test runs under tox, and emits an error like this. 

```
Run tox -e test
test: install_deps> python -I -m pip install -r requirements/prd.txt
ERROR: Could not find a version that satisfies the requirement ray==2.8.0 (from versions: none)
ERROR: No matching distribution found for ray==2.8.0
test: exit 1 (2.19 seconds) /Users/runner/work/dplutils/dplutils> python -I -m pip install -r requirements/prd.txt pid=1563
  test: FAIL code 1 (2.89 seconds)
  evaluation failed :( (3.00 seconds)

Error: Process completed with exit code 1.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/ssec-jhu/dplutils/actions/runs/6906914589/job/18793284248

### Is it regression?

Unknown

### Expected behavior

I expect it to work more often, e.g. rarely fail

### Actual behavior

In some cases it must be restarted 7 or 8 times or so, eventually it will succeed. Rarely does it seem to succeed on the first try.

### Repro steps

Run a test with a python package requirement on "ray"

```
pip install ray
```

**Comment by vpolikarpov-akvelon** [comment]
Hi @amitschang, thanks for reaching out and bringing this to our attention.

The module's official support for Python 3.11 is currently experimental, as mentioned in [the documentation](https://docs.ray.io/en/latest/ray-overview/installation.html). Considering the experimental status, it's expected that installations may fail at times. However, we'll look into the inconsistency aspect to understand why it may succeed or fail in certain cases.

In the meantime, you might want to check the [discussion forum](https://github.com/ray-project/ray) or the [GitHub repo](https://github.com/ray-project/ray) for any ongoing discussions or solutions related to Python 3.11 compatibility.

**Comment by amitschang** [comment]
Thanks @vpolikarpov-akvelon! I am aware that ray is experimental for py3.11, I should have also included evidence that the same behavior does indeed exist for py3.10, which is supported. I added the py310 cases and it does exhibit the same behavior: https://github.com/ssec-jhu/dplutils/actions/runs/6932129008/job/18855699561?pr=25 took 8 times to succeed, for example.

The error appears to happen before it even gets to the install phase. I think it is unrelated to the py environment or the even the contents of the package (though could it be related to the size? ray is large, and I've come across another issue related to large packages, though may not be related to this one https://github.com/actions/runner-images/issues/1354). Could it be some network throttling or the like? Unfortunately the error itself doesn't reveal much.

I appreciate your looking into this :smiley:

**Comment by vpolikarpov-akvelon** [comment]
Hey @amitschang, thank you for the explanation and additional workflow for me to investigate.

I found that the problem is related to the use of the `-l` flag in your workflow step's shell command (`bash -l {0}`). When using the login shell (this is what `-l` stands for), it reads profile scripts and overrides the configurations set by the `setup-python` action. Consequently, Python 3.12 is being used instead of the version you specified. You can see it [here](https://github.com/ssec-jhu/dplutils/actions/runs/6932129008/job/18855699561?pr=25#step:4:16).

To resolve this, please remove the `-l` flag from your shell command. This should prevent bash from resetting the environment variables and PATH modifications made by the `setup-python` action. After making this change, the installation of the module should proceed as expected.

**Comment by amitschang** [comment]
@vpolikarpov-akvelon, I completely missed that, thanks! It does look like a recent macos build both py310 and 311 worked first time without issue. Given this, I'm still a bit confused as to why it worked at all - could it be that workloads happened to eventually get scheduled on systems which did not have a system-level 3.12 installed, but only 3.11 (I see a previous successful build that has line `Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (23.2.1)`, so this could be the case)?

I think my issue is solved in any case, many thanks!
