### ISSUE TITLE
Update ChromeDriver

### ISSUE THREAD

**Issue by MZole** [actions/runner-images#8841]
### Tool name

ChromeDriver

### Tool license

-

### Add or update?

- [ ] Add
- [X] Update

### Desired version

119.0.6045.105

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by vpolikarpov-akvelon** [comment]
Hey @MZole. Ubuntu 22.04 image update is rolling out yet. You can track it here: https://github.com/actions/runner-images/pull/8819. Pull request will be closed as soon as rollout is complete.

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by MZole** [comment]
Thank you for your answers and quick action :)
