### ISSUE TITLE
macos Linking Swift: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by tagatac** [actions/runner-images#8843]
### Description

As part of [my github workflow](https://github.com/tagatac/bagoup/blob/bff4f89f6aba75578d3a6149c16f90ea58657147/.github/workflows/makefile.yaml#L27), I am trying to [compile a swift executable and link it with an objective C binary](https://github.com/tagatac/bagoup/blob/bff4f89f6aba75578d3a6149c16f90ea58657147/cmd/typedstream-decode/Makefile).

It works locally on both amd64 and x86-64 architectures, but on macos-latest and macos-13 runners, it [fails](https://github.com/tagatac/bagoup/actions/runs/6865077084/job/18668240142#step:6:301) with
```
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftXPC'
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftIOKit'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swift_StringProcessing'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_main)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_main)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_main)
  "__swift_FORCE_LOAD_$_swiftIOKit", referenced from:
      __swift_FORCE_LOAD_$_swiftIOKit_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftIOKit_$_main)
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_main)
  "__swift_FORCE_LOAD_$_swiftXPC", referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftXPC_$_main)
  "_swift_getObjCClassFromMetadata", referenced from:
      _$sSo6DecodeCABycfC in main.o
  "_swift_getObjCClassMetadata", referenced from:
      _$sSo6DecodeCMa in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [typedstream-decode] Error 1
make: *** [typedstream-decode] Error 2
Error: Process completed with exit code 2.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`Current runner version: '2.311.0'`
https://github.com/tagatac/bagoup/actions/runs/6865077084/job/18668240142#step:6:301

### Is it regression?

no

### Expected behavior

The swift standard library is found and the linking succeeds.

### Actual behavior

```
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_main)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_main)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_main)
  "__swift_FORCE_LOAD_$_swiftIOKit", referenced from:
      __swift_FORCE_LOAD_$_swiftIOKit_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftIOKit_$_main)
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_main)
  "__swift_FORCE_LOAD_$_swiftXPC", referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_main in main.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftXPC_$_main)
  "_swift_getObjCClassFromMetadata", referenced from:
      _$sSo6DecodeCABycfC in main.o
  "_swift_getObjCClassMetadata", referenced from:
      _$sSo6DecodeCMa in main.o
```

### Repro steps

1. Fork the "missing-libs" branch of tagatac/bagoup: https://github.com/tagatac/bagoup/tree/missing-libs
2. Commit and push an empty commit to that branch.
3. The Makefile CI workflow should run.
4. See the error pasted above in the results of the workflow run.

**Comment by tagatac** [comment]
I was able to work around this by linking with `swiftc` instead of `clang`. I'm not sure if it's supposed to work, but I able to link with `clang` on a MacBook.

**Comment by vpolikarpov-akvelon** [comment]
Hey @tagatac. Thank you for letting us know. We will take a look.

**Comment by ilia-shipitsin** [comment]
@tagatac , looks related https://stackoverflow.com/questions/50096025/it-gives-errors-when-using-swift-static-library-with-objective-c-project/56187043#56187043

(I cam to stackoverflow from https://github.com/facebookarchive/react-native-fbsdk/issues/755 )

can you please try "Create Bridging Header" described there ?

**Comment by tagatac** [comment]
Does `decode.h` fill the role of a bridging header? Anyway, my first attempt did actually use a bridging header separate from `decode.h` and still failed the workflow (while working locally):
https://github.com/tagatac/bagoup/actions/runs/6934326270/job/18862186928

I removed it when I found that it did not affect the compilation or linking locally.

This was the SO that prompted me to try linking with swiftc: https://stackoverflow.com/a/24154763/5403337

**Comment by ilia-shipitsin** [comment]
well, it is hard to guess why it works locally.
if you can help us with steps, we can try to reproduce the same.

**Comment by tagatac** [comment]
Sure!
The steps are
1. `git clone git@github.com:tagatac/bagoup.git`
2. `cd bagoup`
3. `git checkout missing-libs`
4. `make`

If you get an executable named `typedstream-decode` in the folder where you ran the `make` command, it succeeded.

**Comment by ilia-shipitsin** [comment]
I meant steps you took preparing your Mac.
if we know those steps, we can prepare runners in the similar way

**Comment by tagatac** [comment]
There were no special steps on either the arm machine or the intel machine. They are both running MacOS 14, however.

**Comment by ilia-shipitsin** [comment]
well, I think we can postone that to MacOS 14 release.
as we could not figure out required steps to prepare MacOS 13 in desired way, we cannot step forward (I spent few hours yesterday investigating, only found mentioned SO article, which does not help)

I suggest to stay with workaround (i.e. using swiftc instead of clang) either until MacOS 14 image is ready or some details will be known how to prepare MacOS 13

**Comment by tagatac** [comment]
Sounds good! Thanks for taking a look!
