### ISSUE TITLE
Add Alpine

### ISSUE THREAD

**Issue by rgherta** [actions/runner-images#8856]
### Tool name

alpine

### Tool license

MIT License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Improved security, smaller footprint

### URL for tool's homepage

https://www.alpinelinux.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

maybe

**Comment by mikhailkoliada** [comment]
Hello! Currently we have no plans of adding any new platforms/distros, if there are any plans in the future you can track the https://github.com/github/roadmap/issues repository.
