### ISSUE TITLE
windows-latest 20231115.2.0 failed to build the same YAML at DotNetCLI build stage

### ISSUE THREAD

**Issue by xchen218** [actions/runner-images#8864]
### Description

Nuget restore stage finished successfully:
      - task: DotNetCoreCLI@2
        displayName: RestoreNuget
        inputs:
          command: 'restore'
          projects: | 
          (our projects)
          restoreArguments: '--interactive'
          feedsToUse: 'select'
          vstsFeed: '(Guid)'
          includeNuGetOrg: false

Dotnet build stage failed:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: |
          (same projects as above)

with error: ##[error]C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): Error : Unable to load the service index for source <internal source json>.

The YAML file has not been changed for long and we observed that the successful runs were all in version '20231029.1.0' while all '20231115.2.0' runs failed with the error above.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: `windows-2022 (windows-latest)`
Version: `20231115.2.0`
Included Software: https://github.com/actions/runner-images/blob/win22/20231115.2/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231115.2

### Is it regression?

`20231029.1.0` works fine on the same YAML

### Expected behavior

`20231115.2.0` is expected to build the same YAML without having nuget errors

### Actual behavior

`20231115.2.0` build errored out with error: ##[error]C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): Error : Unable to load the service index for source <internal source json>.

### Repro steps

M365Common can serve as a repro feed

**Comment by vpolikarpov-akvelon** [comment]
Hey @xchen218, thank you for reporting, we will investigate this. Please keep in mind that recent Windows 2022 image update includes new version of .NET Core (8) and Visual Studio (17.8), which may affect you workflow. 

Do you have problem with private feed or public one? I found some similar issues in VS Community, e.g.: https://developercommunity.visualstudio.com/t/10521931. I suppose it's not a runner-specific issue, but something more global.

**Comment by xchen218** [comment]
Thank you for your response @vpolikarpov-akvelon . Our engineers have validated the local build and cannot repro the issue with the exact same YAML and upon the same feed. So I don't think it is related to the feed.

**Comment by vpolikarpov-akvelon** [comment]
> Our engineers have validated the local build and cannot repro the issue with the exact same YAML and upon the same feed. So I don't think it is related to the feed.

I didn't mean that it's caused by the feed, I meant that there might be a bug in new version of .NET Core that breaks possibility to work with private feeds. Did your engineers validated build using the latest version of both .NET Core (8) and Visual Studio (17.8)? Could you please ask them to do so if they didn't?

**Comment by mikhailkoliada** [comment]
Similar has been reported to https://github.com/microsoft/azure-pipelines-tasks/issues/19187, lets track it there as it does not look like image bug.

**Comment by craigchandler** [comment]
could it be nuget is 6.7 while dotnet is v8?
