### ISSUE TITLE
dotnet custom tool task picks wrong framework version

### ISSUE THREAD

**Issue by bexxx** [actions/runner-images#8868]
### Description

We are using a dotnet tool as part of our build pipeline to create swagger files out of the compiled code.
The simplified list of steps are:
UseDotnet task with .net8 as target
Restore nugets
Restore dotnet tools from nuget
build projects
run dotnet tool.

All build steps seem to use .net8 fine, but the DotNetCoreCLI seems to not honor net8 from path correctly.

Details (shortened):

What else should I look for to provide as information?

Same task with build works perfect, writing binary files to .../net8/... directories.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current image version: '20231115.8.0'

https://dev.azure.com/project-argos/Sorento/_build/results?buildId=745471&view=logs&j=9dd51b93-2435-51c6-9534-da9ac09c666e&t=e7d3c925-197a-4661-8bb7-39aaebc64659

### Is it regression?

no

### Expected behavior

Build would use dotnet tool from correct framework

### Actual behavior

Error from logs:
Starting: Generate 2022-12-01 swagger file
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.221.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/opt/hostedtoolcache/dotnet/dotnet swagger tofile --serializeasv2 --output ./service/AzureOpenAI.Api/Swagger/Reference/2022-12-01/azureopenai.json ./service/AzureOpenAI.Api/bin/Release/net8.0/linux-x64/AzureOpenAI.Api.dll 2022-12-01
You must install or update .NET to run this application.

App: /home/vsts/work/1/s/.\packages/swashbuckle.aspnetcore.cli/6.5.0/tools/net7.0/any/dotnet-swagger.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: /opt/hostedtoolcache/dotnet/

The following frameworks were found:
  8.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=linux-x64&os=ubuntu.20.04
##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 150
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [ '' ]
Finishing: Generate 2022-12-01 swagger file

### Repro steps

- task: UseDotNet@2
  displayName: 'Install .NET Core sdk v8.x'
  inputs:
    packageType: sdk
    version: 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore nuget packages'
  inputs:
    command: custom
    custom: restore
    projects: |
      **/*.csproj
    arguments: >-
      --configfile:nuget.config
      --runtime $(BuildRuntime)

- task: DotNetCoreCLI@2
  displayName: 'Locally restore dotnet tools'
  inputs:
    command: custom
    custom: tool
    arguments: >-
        restore
  condition: succeeded()

- task: DotNetCoreCLI@2
  displayName: 'Generate 2022-12-01 swagger file'
  inputs:
    command: custom
    custom: swagger
    arguments: >-
        tofile --serializeasv2 --output ./service/AzureOpenAI.Api/Swagger/Reference/2022-12-01/azureopenai.json ./service/AzureOpenAI.Api/bin/Release/net8.0/linux-x64/AzureOpenAI.Api.dll 2022-12-01
  condition: succeeded()

**Comment by vpolikarpov-akvelon** [comment]
Hey @bexxx. Thank you for your report, we will try to investigate this. Please keep in mind that recent Ubuntu 20.04 image update includes new version of .NET Core (8.0.100), which may affect you workflow. Also there might be issues with either `DotNetCoreCLI@2` or `UseDotNet@2` Azure task related to the update of .NET Core.

Unfortunately, your project is private and we can't access it. Could you please provide pipeline logs in more convenient format (e.g. attach a file)?

Also could you please elaborate whether you have this pipeline working recently or you are trying to create a new one and it doesn't work from the very beginning? If it was working recently, could you please attach logs of successful run as well so we can examine it?

**Comment by bexxx** [comment]
This is the raw log of this build:
[57.txt](https://github.com/actions/runner-images/files/13439388/57.txt)

Our global.json which is checked in too:
[global.json](https://github.com/actions/runner-images/files/13439407/global.json)

It works for .net7 builds. This is the first time we try to get it work with our code using .net8. All other builds and packaging with .net 8 works, just not the dotnet tool step.

If this turns out to be a task issue, could you please point me to the place where those can be reported?

**Comment by ilia-shipitsin** [comment]
@bexxx , please run `dotnet --list-sdks` before and after `UseDotNet@2` (before all of them and after all of them).

**Comment by bexxx** [comment]
Full logs with info und list-sdks: 
[79.txt](https://github.com/actions/runner-images/files/13441776/79.txt)

**Comment by mikhailkoliada** [comment]
This should be reported to dotnet developers, it is not the image bug because UseDotnet downloads dotnet distros to the /opt/hostedtoolcache/dotnet/ and this is not the directory where we install dotnet (we install system dotnet to /usr/share because not everybody using the task). Going to close this ticket, feel free to reach us out again if questions left.

**Comment by bexxx** [comment]
Just for reference if someone with same problem find this.

I can confirm this works for me using an Azure DevOps build pipeline now.
I've added
variables:
DOTNET_ROLL_FORWARD: LatestMajor

to the build and it started to work.
