### ISSUE TITLE
Bug in Helm 3.13.1 included in Ubuntu images

### ISSUE THREAD

**Issue by PottsSG** [actions/runner-images#8876]
### Description

Under Packaging, the current Helm version is 3.13.1.  Helm 3.13.0 and 3.13.1 contain a bug preventing authentication to Azure Container Registry to push or pull charts.  Helm should be bumped to 3.13.2 or rolled back to the last working version 3.12.3 to make the image usable for build agents that deploy to AKS and Kubernetes.

Helm changelog https://github.com/helm/helm/releases
Note in 3.13.2 "Revert "fix(main): fix basic auth for helm pull or push" https://github.com/helm/helm/commit/e785e6c50c622ed5019fd4020a13509c87a3022d (Matt Farina)"

Bug report (3.13.1) https://github.com/helm/helm/issues/12533

Reproduced in an Azure Devops pipeline using self-hosted agents built from runner-images Ubuntu 22.04 November 20, 2023.  May also be an issue in Windows Server and macOS.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Date: Mon Nov 20 13:56:28 2023 +0000; Commit: 3275edff484bffe7c50915d76ec904c453f1515a - Windows Server 2019 (20231115) Image Update (#8825); Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>Managed image name: ubuntu-2204-20231120T040009
Warning: Bundled plugins used

### Is it regression?

Yes, we rolled back to build agents we built in September from Date: Thu Sep 7 11:49:34 2023 +0000; Commit: 08f6a0590445016b813efe25048da76ad3e4c0b1 - Updating readme file for ubuntu20 version 20230903.1.0 (#8230); Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>Managed image name: ubuntu-2204-20230907T090332 Warning: Bundled plugins used

### Expected behavior

The Helm CLI bundled with the runner images can pull charts from Azure Container Registry

### Actual behavior

The error is logged
helm pull oci://XXXXXXX.azurecr.io/XXXXX/XXXXX/XXXXX --version XXXXX --registry-config $DOCKER_CONFIG_PATH
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /agent/_work/_temp/03552853-eb7f-4fb6-bc08-641a19e749f8.sh
Error: unexpected status from HEAD request to ***/v2/XXXXXXX/XXXXXX/XXXXXX/manifests/XXXXX: 401 Unauthorized

### Repro steps

Set up a build pipeline that has a step to pull a Helm chart from Azure Container Registry, authenticated through a previous Docker Login step to the same Azure Container Registry
Run the pipeline

**Comment by vpolikarpov-akvelon** [comment]
Hey @PottsSG, Thank you for you report. We install helm using [get-helm-3](https://github.com/helm/helm/blob/main/scripts/get-helm-3) script. It fetches the latest version number from get.helm.sh site and receives `3.13.1` currently. There is an [open issue](https://github.com/helm/helm/issues/12559) regarding this problem in helm's repo.

There is nothing wrong with runner images and updated Helm will be installed as soon as information on get.helm.sh site is fixed. If it won't happen soon, then we will consider overriding version number in our scripts.

**Comment by PottsSG** [comment]
Thank you for confirming the change is external and linking to it, that resolves this for me.

**Comment by mikhailkoliada** [comment]
Closing for now as there swim no people complaining about this specific issue + nothing actable for us to do from the runner-images side (as we are always installing the latest version and the latest is broken currently, I'll keep an eye on upstream bug though so your efforts of reporting it do not go nowhere)

**Comment by IanMoroney** [comment]
@vpolikarpov-akvelon  , helm version 3.14.0 is now out, and the get-helm-3 script now does pull down 3.14.0.
How can we get this into a new set of image versions?

**Comment by PottsSG** [comment]
@IanMoroney Since the script pulls the latest, as of now, just running image generation again will include Helm 3.14.0 in the tools.

**Comment by IanMoroney** [comment]
Yep that's fine, I guess it's more for the published version for the Azure devops hosted agents
