### ISSUE TITLE
Pool provider is sometimes slow

### ISSUE THREAD

**Issue by Cheesebaron** [actions/runner-images#8879]
### Description

I wrote in the developer community here: https://developercommunity.visualstudio.com/t/macos-13-Pool-provider-seems-slow/10522135#T-ND10523938 Tong Wu told me to log a bug here.

We are often seeing this message in Azure Pipelines that pool provider is slow and often builds are stuck waiting for macOS-13 agents for upwards of 40 minutes. This is even though in our concurrent builds of 25 there are 20+ agents idling.

![B08d8b538869245e8a404ad91fe1f8e82638361869593652200_20231121-190918-image](https://github.com/actions/runner-images/assets/249719/aa4c9839-12e8-4967-a092-3fca0c7e9306)

![B52abe0c320e042a99e0721ab087a9e27638361869902303844_20231121-190949-image](https://github.com/actions/runner-images/assets/249719/34c9052c-c398-4fe1-ac51-8e463d45dcff)

<img width="1526" alt="B2ac2e44e8f194b4dbbe1f878190db146638361871388561460_20231121-191218-image" src="https://github.com/actions/runner-images/assets/249719/f292ccd6-549d-4f03-9c21-4faabf3f4eda">

You can find some of the affected builds here:
https://trackman.visualstudio.com/Golf/_build/results?buildId=395103&view=results
https://trackman.visualstudio.com/Golf/_build/results?buildId=395072&view=results

It doesn't happen every time, but it happens several times on different pipelines during the day.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent name: 'Azure Pipelines 2'
Agent machine name: 'Mac-1700593125567'
Current agent version: '3.227.2'
Operating System
macOS
13.6
22G120
Runner Image
Image: macos-13
Version: 20231025.2
Included Software: https://github.com/actions/runner-images/blob/macos-13/20231025.2/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20231025.2
Runner Image Provisioner
2.0.312.1
Current image version: '20231025.2'

### Is it regression?

yes

### Expected behavior

Not having to wait upwards of 40 minutes for agent to become available

### Actual behavior

Pool provider is slow and there is a long wait for agents

### Repro steps

Just queue a macOS-13 vmpool build and observe

**Comment by vpolikarpov-akvelon** [comment]
Hey @Cheesebaron. Thank you for reaching out, but there is nothing to do on the side of the runner images generation team. Please contact [GitHub Support](https://support.github.com/).

**Comment by Cheesebaron** [comment]
Nice to be sent from place to place to get support

**Comment by unrateddi** [comment]
@Cheesebaron we are facing the same issue here and changed to macos-13-arm64 which seems to work fine. So, maybe you could try that, if that image works for your needs, until they resolve the issue.

**Comment by Cheesebaron** [comment]
> @Cheesebaron we are facing the same issue here and changed to macos-13-arm64 which seems to work fine. So, maybe you could try that, if that image works for your needs, until they resolve the issue.

![image](https://github.com/actions/runner-images/assets/249719/6ae888e2-164e-40ef-a84a-0babb046c726)

These don't seem to be available in Azure DevOps pipelines

**Comment by unrateddi** [comment]
@Cheesebaron that's weird. I have successfully run Azure Pipelines with that image. I even tried to run it now in case something changed.

![Screenshot_20231125_113321](https://github.com/actions/runner-images/assets/13433165/eb302a90-5d02-4ed5-943b-84e284de0833)

![Screenshot_20231125_113631_edit_135028888371510](https://github.com/actions/runner-images/assets/13433165/cc85a398-06d6-4321-95a2-8b2843235c35)

**Comment by Cheesebaron** [comment]
Maybe your organization has access to a preview of some sorts?

**Comment by unrateddi** [comment]
@Cheesebaron hmm maybe, unfortunately I can't know it for sure.

**Comment by mmrazik** [comment]
Please note that the only supported images on Azure DevOps are the following: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software


![Image](https://github.com/actions/runner-images/assets/4578040/67178ebb-3cd1-41b9-b537-56c488d6886a)



Anything else is strongly discouraged as it can stop working for you without prior notice.

**Comment by qwertylolman** [comment]
> Please note that the only supported images on Azure DevOps are the following: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
> 
> When it comes to MacOS 13 the only vm image available for Azure DevOps is `macOS-13` (in beta).

yeah, it's quite confusing that arm64 is not listed anywhere, but presented in the repository xD
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md

but, seems like this image doesn't have the issue. i've switched our flutter project, it's building faster and without delays. xamarin net7 projects, from time to time, are having some strange freezes during the dotnet build step, we are currently investigating this as for now.

**Comment by Nathan-Molby** [comment]
https://github.com/actions/runner-images/issues/8971

**Comment by IainS1986** [comment]
> Anything else is strongly discouraged and it may stop working for you without prior notice.

`macos-13` stops working without prior notice (hence the ticket).

Is there anyone looking into this or can tell us if its an issue thats being worked on, 'macos-13 is beta' is not really an excuse that can last much longer...

**Comment by haavamoa** [comment]
Our release pipeline stopped working today due to `macOS-13` providers not responding. This is blocking our planned .NET MAUI app release next week.

**Comment by cho-trackman** [comment]
This is painful:
![image](https://github.com/actions/runner-images/assets/48789991/6ad22ca0-ad1d-4d5c-b9f0-5ded7c0f3b6e)
![image](https://github.com/actions/runner-images/assets/48789991/9354db38-c069-4233-894b-017564d485d8)

**Comment by adminM365x34654676** [comment]
Same issue.....

**Comment by Cheesebaron** [comment]
I've provided the feedback to the product team when I was at MVP Summit, they are aware of these issues.

**Comment by akrol95** [comment]
We are affected by the same problem. I hope it will be solved soon.

**Comment by olokobayusuf** [comment]
Chiming in to say that this issue also affects us.

**Comment by jvanoeveren** [comment]
I'll also chime in and say that we are required to use macos-13 to build for iOS, due to the warning Apple is giving out in their review process that we need to be building for iOS SDK 17 by April 29 (shown below). This is because MacOS 12 uses XCode 14.2 by default, whereas MacOS 13 uses Xcode 15 which is the version we need. Sometimes I can get this VM pool to pick up right away, but most times it just hangs for a long time. 

`ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.`

**Comment by CAG-panda-srv-acct** [comment]
This issues seems to be occurring again:

```yml
Pool provider seems slow, we notified pool provider at 12/08/2025 13:14:15, still agent has not started processing it. Pool provider delay(in mins): 25.3546225733333
```

**Comment by mario-galvan-dev** [comment]
I am seeing it too

**Comment by erik-bershel** [comment]
Unfortunately, this is a relatively normal situation - we experience certain difficulties with free capacity during peak loads.

We are aware of each such case and are working to redistribute capacity if automatic services fail, but it will not be possible to completely get rid of the problem in the near future.

**Comment by twurm** [comment]
We are seeing long delays with Azure Maanged Pools and ubuntu in East US.  The service was supposed to save us time, instead our jobs wait 25 - 45 minutes to start.  I understand macOS agents maybe limited, but why amd64 based Ubuntu?

<img width="1353" height="225" alt="Image" src="https://github.com/user-attachments/assets/87ff4c6d-a71d-4484-bfde-168e232a7255" />

**Comment by Cheesebaron** [comment]
@twurm sadly this is not the right tree to bark at. You have much better chances escalating through the Azure Portal or if you have an account manager ping them.

A lot of the issues in Azure DevOps stem from flat ray payment of parallel agents and the big cheeses not wanting to do anything about that. Allowing more agents to be provisioned and available is probably not something they want either.

Their answer will likely be:
- Move to GitHub
- Run your own hosted agents

That is at least what we keep getting told.

Now with macOS-26 and arm64 macOS agents, which have been available on GitHub for a while, these might not make it anytime soon to Azure DevOps, again, because of $$$ and how you pay flat rate for parrallel agents in AzDo.
