### ISSUE TITLE
Standard linux nodes sometimes support nested virt, sometimes not

### ISSUE THREAD

**Issue by gtardif** [actions/runner-images#8882]
### Description

we tried to run Docker Desktop on linux nodes, it works well on large linux runners, but we on standard nodes ("ubuntu-lates"), it works "sometimes" but sometimes fails, depending on the node we get, because of nested virt support.

But since we get random nodes, we can't rely on it for our Desktop action.
This is sad because 1) large runners cost more (quite a lot), but maybe even worse: 2) it requires access to non-standard nodes, users might not have access to these nodes.

It would be really cool if we had a way to specify that we need an ubuntu-latest, but the AMD one with nested virt support (even if slightly more expensive, but part of the standard nodes, that would be great)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04  Version: 20231030.2.0
https://github.com/docker/desktop-action/actions/runs/6863985359/job/18664812419?pr=16

### Is it regression?

I don't know, we had not this action running on linux before trying it recently

### Expected behavior

have reproducible access to linux nodes with nested virt, using specs available in standard nodes

### Actual behavior

Sometimes we have a node "Intel Xeon" that does not support it, like [here](https://github.com/docker/desktop-action/actions/runs/6863985359/job/18664812419?pr=16#step:3:67).
Sometimes we get an "AMD" with nested virt support and Docker Desktop starts nicely, like [here](https://github.com/docker/desktop-action/actions/runs/6863985359/job/18664812942?pr=16#step:3:55). (apparently a single proc, cpu_core: 2 so we don't need a huge machine)

### Repro steps

Try launching "ubuntu-latest" nodes and check  /proc/cpuinfo flags for nested virt support (`egrep '(vmx|svm)' /proc/cpuinfo`). some execution will have nested virt support, some not

**Comment by mikhailkoliada** [comment]
@gtardif Hello! Unfortunately nested virtualisation is not yet supported on the standard runners (while it fully does on the larger ones indeed), the fact that you hit a vm with nested virt on is rather an exception than a rule and I would not recommend relying on this and continue using larger runners if there is a need of nested virt for you. Eventually we are planing to make nested available for the standard runners too as we are working in this direction, just not yet, you can follow our announcements not to miss anything, if you have questions feel free to reach us out again.

**Comment by gtardif** [comment]
> Eventually we are planing to make nested available for the standard runners too as we are working in this direction, just not yet

Thanks, good to know this, that's the direction I was hoping :) 
We'll continue with the large runners for now, thanks
