### ISSUE TITLE
Xamarin Android and iOS for ARM64

### ISSUE THREAD

**Issue by TryLastOne** [actions/runner-images#8888]
### Tool name

Xamarin Android and iOS for ARM64

### Tool license

Free

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by vpolikarpov-akvelon** [comment]
Hey @TryLastOne. It's unlikely that we will install Xamarin on new images as its support will end soon (on May 1, 2024). Anyway, thank you for your request, we will consider it.

**Comment by TryLastOne** [comment]
yes, I knew Xamarin will be expired soon, but there are a lot of Xamarin App still there and upgrade new third-party libraries built for ARM64 as in my case. Anyway, thank you for your listening my request.

**Comment by munkii** [comment]
@vpolikarpov-akvelon fair enough support for Xamarain is currently due to expire in May 2024. However it was announced by MS [here](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-rc-2/) at the same time as the .NET 8.0 SDK RC2 that 

> Xamarin developers can now use [Xcode 15 to target the latest versions (e.g iOS 17, iPadOS 17)](https://github.com/xamarin/xamarin-macios/releases/tag/xamarin-ios-16.4.0.18), and target [Android API 34](https://learn.microsoft.com/xamarin/android/release-notes/13/13.2) in order to be compliant with store policies

If we are going to do that then we need to be able to do it in our Release Pipelines. That means we need to be able to target XCode 15 and use Xamarin on a Mac OS 13 image.

**Comment by qwertylolman** [comment]
even if you migrate your app to net7, you still need to use macos-13 agent which is in beta and really unstable for the last few months (evening time, pipeline fails with a timeout)

**Comment by qwertylolman** [comment]
even if you migrate your app to net7, you still need to use macos-13 agent which is in beta and really unstable for the last few months (~15:00-19:00UTC time, pipeline fails with a timeout)

**Comment by mikhailkoliada** [comment]
Given that tamarin is EOL we do not have plans to add this to the images due to maintenance concerns, for amd64 xamarin could be installed via brew and arm64 installation strategy is unclear.
