### ISSUE TITLE
Update [NSIS]

### ISSUE THREAD

**Issue by xavier2k6** [actions/runner-images#8890]
### Tool name

NSIS (Nullsoft Scriptable Install System)

### Tool license

https://nsis.sourceforge.io/License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.09

### Brief description of tool

NSIS (Nullsoft Scriptable Install System) is a professional open source system to create Windows installers

### URL for tool's homepage

https://nsis.sourceforge.io/Main_Page

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by ilia-shipitsin** [comment]
thank you for bringing this up, we'll update

**Comment by xavier2k6** [comment]
@ilia-shipitsin FYI: `Windows2019-Readme.md` & `Windows2022-Readme.md` (tools section) will need to be updated too to reflect version bump, unsure if this is done by `bot` or needs to be done manually at image creation time.

**Comment by ilia-shipitsin** [comment]
that will happen after new image deployment.
also, deployment takes few days and some agent may run older version until deploy is finished.

image used for particular build can be found under "Set up job"

![image](https://github.com/actions/runner-images/assets/125650415/2deede0e-d9e4-41a1-84fd-d0ac86dd393a)

**Comment by mikhailkoliada** [comment]
Deployed
