### ISSUE TITLE
Set pwsh `PSNativeCommandUseErrorActionPreference`

### ISSUE THREAD

**Issue by vaind** [actions/runner-images#8900]
### Description

There have been multiple issues asking to change the behavior of `pwsh` to respect executables exit codes. Since pwsh v7.3, there's a new setting to do exactly what other shells do: `PSNativeCommandUseErrorActionPreference`. This has become mainstream in pwsh v7.4: https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.4#psnativecommanderroractionpreference

One of the issues that this has come up before: 
* https://github.com/actions/runner-images/issues/6668

Depends on updating pwsh: https://github.com/actions/runner-images/issues/8847

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/getsentry/sentry-unity/actions/runs/6999733486/job/19047630987

### Is it regression?

no

### Expected behavior

(Native) executable errors should propagate and fail the step, the same way they would on other shells.

Docs already indicate they should: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

### Actual behavior

Errors let the step script continue as if nothing has happened, leading to an incorrect CI execution.

This partially works if there's a single command, because that one will get its exit code propagated

### Repro steps

create a multiline run step, the first shell command failing, the second one passing (zero exit code)

**Comment by ilia-shipitsin** [comment]
shouldn't it be done on Windows (or Powershell) level ?
we do not enforce any non default Powershell setting.

**Comment by vaind** [comment]
> shouldn't it be done on Windows (or Powershell) level ?

technically, it's a breaking change in a wide world, that's why it's a new opt-in setting.

> we do not enforce any non default Powershell setting.

That's not entirely correct, see docs:
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
> Fail-fast behavior when possible. For pwsh and powershell built-in shell, we will prepend $ErrorActionPreference = 'stop' to script contents.

**Comment by sergei-pyshnoi** [comment]
Hello @vaind . Unfortunately we cannot enable this feature because current installed PowerShell version (7.2.16) doesn`t support those.
```
Enable-ExperimentalFeature PSNativeCommandErrorActionPreference
Enable-ExperimentalFeature: No experimental feature was found that matched the name 'PSNativeCommandErrorActionPreference'.

```
But, as you say,  this setting will default to enabled on Powershell 7.4 . I am closing this issue for now, but if you have additional questions, feel free to ask.

**Comment by oblivioncth** [comment]
It seems that the setting ended up being defaulted to "false", not "true", so this issue is still valid (at least as of pwsh 7.4.5).

IMO it makes sense to force PSNativeCommandUseErrorActionPreference to not only unify behavior with unix shells, but also to match the clear fail-fast behavior intention that is mentioned in the docs linked by @vaind:

> Fail-fast behavior when possible. For pwsh and powershell built-in shell, we will prepend `$ErrorActionPreference` = 'stop' to script contents.

Which could now of course read:

> Fail-fast behavior when possible. For pwsh and powershell built-in shell, we will prepend `$ErrorActionPreference = 'stop'` and `$PSNativeCommandUseErrorActionPreference = $true` to script contents.

This behavior seems intuitive in the context of CI/CD, especially since again, bash and sh already function this way when used through GitHub Actions as shown in the above documentation.

**Comment by muzimuzhi** [comment]
> It seems that the setting ended up being defaulted to "false", not "true", so this issue is still valid (at least as of pwsh 7.4.5).

+1

It's Oct, 2025 and now GitHub-hosted Windows runners include at least PowerShell v7.4.11.
https://github.com/actions/runner-images/blob/610c1c15eebf2100d81cc1e0743141a78625cc2f/images/windows/Windows2019-Readme.md?plain=1#L502
