### ISSUE TITLE
MacOs 12 inconsistance Agent version

### ISSUE THREAD

**Issue by florentm35** [actions/runner-images#8902]
### Description

Hello, I have a problem with macOs-12 en java 21 with the Azure develops public pools.
Sometime I have a different runner with one where java 21 not working.

Exemple in 2 jobs of the same pipeline
![image](https://github.com/actions/runner-images/assets/31475579/7dc29c70-2d61-455e-bc53-b35539a4441a)

![image](https://github.com/actions/runner-images/assets/31475579/3835a2e0-58bb-4fe4-9276-808d50e6517d)

![image](https://github.com/actions/runner-images/assets/31475579/f98e529f-c162-46ef-9e0a-6680814b7a06)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

When it work :
```
Agent name: 'Azure Pipelines 4'
Agent machine name: 'Mac-1701083996688'
Current agent version: '3.230.0'
Operating System
Runner Image
Image: macos-12
Version: 20231115.2
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231115.2/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231115.2
```

When it's not work :

```
Agent name: 'Azure Pipelines 7'
Agent machine name: 'Mac-1701083304032'
Current agent version: '3.227.2'
Operating System
Runner Image
Image: macos-12
Version: 20230921.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230921.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230921.1
```

The second version does not have java 21 available (and the documentation not working)

### Is it regression?

No

### Expected behavior

Use the same runner image all the time

### Actual behavior

Random macOs runner version

### Repro steps

It's random, some time i have the good version some time not

**Comment by sergei-pyshnoi** [comment]
Closing as duplicate https://github.com/actions/runner-images/issues/8642
