### ISSUE TITLE
Rollout in macos-12 is stuck since a week

### ISSUE THREAD

**Issue by gionn** [actions/runner-images#8909]
### Description

<img width="842" alt="Screenshot 2023-11-28 at 10 00 12" src="https://github.com/actions/runner-images/assets/71768/1b378edb-e8b9-4f2d-b19a-a46e48cbb190">

Multiple people are reporting at https://github.com/actions/runner-images/issues/8730

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

.

### Is it regression?

.

### Expected behavior

.

### Actual behavior

.

### Repro steps

.

**Comment by sergei-pyshnoi** [comment]
Closing as duplicate https://github.com/actions/runner-images/issues/8642
