### ISSUE TITLE
Not able to use cifs for mapping

### ISSUE THREAD

**Issue by niegowic** [actions/runner-images#8911]
### Description

We were using option to mount azure files share -> sudo mount -t cifs $(URL) /mnt/airflow -o username=$(USER),password=$(KEY),serverino,nosharesock,actimeo=30

WIth ubuntu-latest image which currently points to ubuntu-22.04 we got error -> when we change back to ubuntu-20.04 this command works fine

Problem on Ubuntu 22.04:

mount error: cifs filesystem not supported by the system
mount error(19): No such device
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

Expected result:
Mapping is done correctly without error. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

**Failing on this image:**

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az243-979'
Current agent version: '3.230.0'
Operating System
Ubuntu
22.04.3
LTS
Runner Image
Image: ubuntu-22.04
Version: 20231115.7.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231115.7/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231115.7

**It was not failing on this:**
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az416-640'
Current agent version: '3.227.2'
Operating System
Ubuntu
22.04.3
LTS
Runner Image
Image: ubuntu-22.04
Version: 20231030.2.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231030.2/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231030.2

### Is it regression?

Yes 

### Expected behavior

File share is successfully mapped no error during mapping

### Actual behavior

Getting error:
mount error: cifs filesystem not supported by the system
mount error(19): No such device
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

### Repro steps

Use in pipline definiton
pool:
  vmImage: ubuntu-latest

And try to mapp Azure file share with cifs - it will show error

After updating to 
pool:
  vmImage: ubuntu-20.04 

It works fine it was also workign fine on 22.04 recent version broke this

**Comment by sergei-pyshnoi** [comment]
Hello @niegowic . We will take a look.

**Comment by ColinPowersRES** [comment]
If it helps any, I had this issue a few weeks ago (November 18th). I was able to fix it using the workaround listed here: https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/2042092

However, the issue has come back again today, so perhaps something has changed.

**Comment by dano0b** [comment]
Just in case someone didn't see the linked workaround:
```
WORKAROUND: cifs.ko is provided in the linux-modules-extra-azure (as noted in comment #7); a 'sudo apt install linux-modules-extra-azure' will add it in.
```

**Comment by niegowic** [comment]
No restart needed ?

**Comment by jamesiri** [comment]
Ran into this issue last week and fixed it by installing the `linux-modules-extra-azure` package but started getting the same error yesterday.

**Comment by mikhailkoliada** [comment]
should be fixed in newly deployed fixed
