### ISSUE TITLE
Alpine runner-image with `ubuntu-latest` runs as root user

### ISSUE THREAD

**Issue by jmillan** [actions/runner-images#8915]
### Description

We are running an executable that fails if it's being run as `root` user (if `geteuid() returns 0`). The test is being run in the following runner-images:

* ubuntu-latest
* ubuntu-latest (alpine)

In the case of Alpine it's failing as `geteuid()` returns 0, meaning that the running user is `root`. 

I consider this inconsistency a bug as in the rest of linux runner-images commands are not run as `root`, and `sudo` must be explicitly used in case one wants to run something as root.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/mesonbuild/wrapdb/actions/runs/7017645697/job/19091354600

### Is it regression?

Unknown. This is the first time we are running this test with Alpine

### Expected behavior

For consistency, actions should NOT be run as `root` unless explicitly stated via `sudo`.

### Actual behavior

Actions as being run as `root`.

### Repro steps

Run the provided action, which fails if `geteuid() == 0`

**Comment by mikhailkoliada** [comment]
Hey! How are you invoking docker commands?

**Comment by ibc** [comment]
> Hey! How are you invoking docker commands?

This is wrapdb CI actions which, as you can see, don't do anything special to make hosts run with a user different than root. So while using Ubuntu host makes the test run with user != root, that doesn't happen in the Alpine (container) host:

https://github.com/mesonbuild/wrapdb/blob/master/.github/workflows/sanity_checks.yml

**Comment by jmillan** [comment]
> Hey! How are you invoking docker commands?

No, the workflow file is [this simple](https://github.com/mesonbuild/wrapdb/actions/runs/7017645697/workflow#L27) and the `sanity_checks.py` is calling just calls `meson` commands.

Let me reiterate that the **same** action in ubuntu-latest works OK, but ubuntu-latest + alpine does run with root and hence fails.

**Comment by ibc** [comment]
Also reported in wrapdb project in case there is something they should do to avoid the Alpine container to run as root:

https://github.com/mesonbuild/wrapdb/issues/1316

**Comment by mikhailkoliada** [comment]
@ibc @jmillan I am afraid we are unable to help here as the `runner` linux user of the hosted runner is a member of the `docker` group and it means it will run all the docker containers with the root privileges it actually happens to any container, not only to alpine, following snippet will also return you root user


```name: Continous integration

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: test
        run: |
          docker run -t -d --name ubuntu ubuntu:20.04
          docker ps
          sleep 10
          docker exec ubuntu id
```

**Comment by ibc** [comment]
> the `runner` linux user of the hosted runner is a member of the `docker` group and it means it will run all the docker containers with the root privileges

So indeed libuv tests are not checking whether current user is "root" or not. They are checking `geteuid` which is the "effective user id". If the user running the command is different than root but it the command was granted with root privileges then the libuv test will fail. This is like the `passwd` command which writes in `/etc/passwd` despite a normal user cannot write in that file, but the command can do it since it runs with EUID (effective user id) = root.

Is this the same here?

And assuming it's the same, what's the typical approach here? Should the CI not only run the container but also make the container run some steps to create a new non privileged user and then run the intended command with it?

**Comment by jmillan** [comment]
@mikhailkoliada,

How comes `ubuntu-lastest` and `ubuntu-lastest + Alpine` behave differently? I'm missing that part.

**Comment by ibc** [comment]
> How comes `ubuntu-latest` and `ubuntu-lastest + Alpine` behave differently? I'm missing that part.

Only Alpine runs in a container: https://github.com/mesonbuild/wrapdb/blob/master/.github/workflows/sanity_checks.yml#L29

What @mikhailkoliada meant is that it doesn't matter whether the container runs Alpine or Ubuntu, the problem happens when running any linux container.

**Comment by mikhailkoliada** [comment]
@ibc linux has the `$EUID` variable which is available inside the docker container as well, but as far as I remember it will default to 0 uid as well, the best thing to do here is indeed create a local docker user with deterministic gid/uid and run the tests using that user, we are unlikely to offer any specific help here as it is default docker behaviour and it is not gh-specific. If you have more questions feel free to reach us again in the future. Happy new year!
