### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by dvdtok** [actions/runner-images#8920]
### Tool name

Subversion

### Tool license

Subversion

### Add or update?

- [X] Add
- [X] Update

### Desired version

Subversion

### Approximate size

Subversion

### Brief description of tool

Subversion

### URL for tool's homepage

Subversion

### Provide a basic test case to validate the tool's functionality.

```bash
Subversion
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Subversion
```

### Tool installation time in runtime

Subversion

### Are you willing to submit a PR?

Subversion

**Comment by sergei-pyshnoi** [comment]
Hello @dvdtok . Subversion (SVN) 1.14.2 is already installed to Windows image. Full list of installed software you can see here https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
