### ISSUE TITLE
Add PHP 8.3

### ISSUE THREAD

**Issue by mcetkovsky** [actions/runner-images#8922]
### Tool name

PHP

### Tool license

BSD

### Add or update?

- [X] Add
- [ ] Update

### Desired version

8.3

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @mcetkovsky . We will take a look

**Comment by mikhailkoliada** [comment]
Deployed
