### ISSUE TITLE
Running windows-latest fails suddenly

### ISSUE THREAD

**Issue by darrell-d** [actions/runner-images#8931]
### Description

I have an action setup that last ran successfully on May 22nd. The action builds a go application for mac, linux and windows.

On running the command `go build -v ./...` now in November, it fails with the following error:

```
C:\hostedtoolcache\windows\go\1.18.10\x64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2433905030\000016.o: in function `_cgo_preinit_init':
\\_\_\runtime\cgo/gcc_libinit_windows.c:30: undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2433905030\000016.o: in function `x_cgo_sys_thread_create':
\\_\_\runtime\cgo/gcc_libinit_windows.c:60: undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2433905030\000016.o: in function `x_cgo_notify_runtime_init_done':
\\_\_\runtime\cgo/gcc_libinit_windows.c:101: undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2433905030\000017.o: in function `x_cgo_thread_start':
\\_\_\runtime\cgo/gcc_util.c:18: undefined reference to `__imp___iob_func'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2433905030\000018.o: in function `_cgo_sys_thread_start':
\\_\_\runtime\cgo/gcc_windows_amd64.c:31: undefined reference to `__imp___iob_func'
collect2.exe: error: ld returned 1 exit status
```

I've gone back to the commit that last successfully ran the action, branched off of that and fixed a typo in the README, commit and push to trigger the action and it fails with that error.

I've also tried building from source on a Windows 10 machine and a freshly installed Windows 11 machine and they both ran the `go build -v ./...` command with the code without an issue

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20231126.1.0

### Is it regression?

https://github.com/Pennsieve/pennsieve-agent/actions/runs/5051727417/job/13676056228

### Expected behavior

The build should successfully complete

### Actual behavior

Build fails with GCC errors

### Repro steps

1. Push to repo
2. Action runs
3. Action fails

**Comment by sergei-pyshnoi** [comment]
Hello @darrell-d . We will take a look.

**Comment by mikhailkoliada** [comment]
Hey! I am closing this issue as stale, as it seems we are unable to reproduce the problem and have not heard any new information. If you have more information / repro steps / new submissions feel free to reach us again and we will help you.
