### ISSUE TITLE
macos-12: build fails sporadically

### ISSUE THREAD

**Issue by antmak** [actions/runner-images#8932]
### Description

I'm building original qemu project with runs-on`macos-12` at Intel (fork: https://github.com/antmak/qemu/commits/build_test)

I have found that sometimes this builds successfully on
```
  Image: macos-12
  Version: 20230921.1
```
( https://github.com/antmak/qemu/actions/runs/7055665481/job/19206594318 )

But it fails on 
```
  Image: macos-12
  Version: 20231115.2
```
(https://github.com/antmak/qemu/actions/runs/7055766788/job/19206720658 )
with error
```
[184/2373] Generating ui/dbus-display gdbus-codegen with a custom command
FAILED: ui/dbus-display1.h ui/dbus-display1.c 
/usr/local/Cellar/glib/2.78.1/bin/gdbus-codegen ui/dbus-display1.xml --glib-min-required 2.64 --output-directory /Users/runner/work/qemu/qemu/build/ui --interface-prefix org.qemu. --c-namespace QemuDBus --generate-c-code dbus-display1
Traceback (most recent call last):
  File "/usr/local/Cellar/glib/2.78.1/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/local/Cellar/glib/2.78.1/share/glib-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/usr/local/Cellar/glib/2.78.1/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/local/Cellar/glib/2.78.1/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
```

I suppose the cause is in runner image since you updated python environment from 3.11 to 3.12.

Also it could be affected by `gdbus-codegen` from GLIB (2.78.1 vs. 2.78.0)

For workaround and test purpose could you help me, how to specify runner-image version to 20230921.1 in my workflow?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12, Version: 20231115.2, https://github.com/antmak/qemu/actions/runs/7055766788/job/19206720658 

### Is it regression?

yes

### Expected behavior

like on Version: 20230921.1 , https://github.com/antmak/qemu/actions/runs/7055665481/job/19206594318

### Actual behavior

fails on 20231115.2, 20231029.1

### Repro steps

affected Workflow is in https://github.com/antmak/qemu/commits/build_test

**Comment by sergei-pyshnoi** [comment]
Hello @antmak, MacOS image in rollout process. During next week problem should be gone.

**Comment by sergei-pyshnoi** [comment]
Unfortunately, after further investigation, I found that rollout in your case doesn't help and in that case you should use [setup-python](https://github.com/actions/setup-python) action . Your behavior is expected so I am closing this issue. If you have additional questions feel free to ask.
