### ISSUE TITLE
Update/Add [go]: bump default version to the latest stable minor release - go1.21.x

### ISSUE THREAD

**Issue by bschaatsbergen** [actions/runner-images#8933]
### Tool name

go

### Tool license

BSD

### Add or update?

- [ ] Add
- [X] Update

### Desired version

default version set to: 1.21.x

### Brief description of tool

Set the default version for Go to: 1.21.x

### URL for tool's homepage

https://go.dev/doc/devel/release#go1.21.minor

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
Please do not depend on the image default, moreover do not depend on brew's implementation of go installed. If you need to select a specific version of Golang you should use the `actions/setup-go` task.
