### ISSUE TITLE
ReuseResourceGroup flag doesn't work in GenerateResourcesAndImage

### ISSUE THREAD

**Issue by Stepness** [actions/runner-images#8936]
### Description

When using the `ReuseResourceGroup` flag the `GenerateResourcesAndImage` script returns
` ==> azure-arm: A resource group with that name already exists. Please use build_resource_group_name to use an existing resource group.`

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

N/A

### Expected behavior

When using the flag `ReuseResourceGroup` the build should start

### Actual behavior

When using the flag `ReuseResourceGroup` the command fail returning the error ` ==> azure-arm: A resource group with that name already exists. Please use build_resource_group_name to use an existing resource group.`

### Repro steps

1. Create a service principal for Azure
2. Crete a Resource Group in Azure
3. Give Contributor permission to the service principal in this Resource group
4. Run the `GenerateResourcesAndImage` script and pass `-ReuseResourceGroup`

**Comment by sergei-pyshnoi** [comment]
Hello @Stepness . We will take a look.
