### ISSUE TITLE
error C3611: 'System::Numerics::INumberBase::System::IUtf8SpanFormattable.TryFormat': a sealed function cannot have a pure-specifier

### ISSUE THREAD

**Issue by NaveenVNaik** [actions/runner-images#8944]
### Description

I am getting this error while building the c++/cli project in Azure Pipeline. 

**Error I am getting:** error C3611: 'System::Numerics::INumberBase::System::IUtf8SpanFormattable.TryFormat': a sealed function cannot have a pure-specifier

**Task**: VSBuild@1
**UseDotNet@2 (version):** 8.0.x
**vmImage:** 'windows-2022'

I have gone through the existing defect https://github.com/dotnet/runtime/issues/94998. Here the solution states that we have to use v14.38 or higher and so VS2022 17.8 or later. As I am using Microsoft hosted agent machine (windows-2022), all the required tools are installed, but still it is failing to build the project.

Could someone please help me to resolve this issue.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

**vmImage:** 'windows-2022'

### Is it regression?

No

### Expected behavior

Project should build without any errors.

### Actual behavior

Build is failing with error C3611: 'System::Numerics::INumberBase::System::IUtf8SpanFormattable.TryFormat': a sealed function cannot have a pure-specifier

### Repro steps

In Azure pipeline, use windows-2022 image and .NET 8.0.x to build the c++/cli project.

Few task details:

pool:
  vmImage: 'windows-2022'
  
    - task: UseDotNet@2
      displayName: Use .NET8 SDK
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: VSBuild@1
      displayName: 'Build to get all Test Binaries'
      inputs:
        solution: '$(solution)'
        vsVersion: 'latest'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '-p:OutputPath=$(System.DefaultWorkingDirectory)\bin\$(buildPlatform)\$(buildConfiguration)'
        clean: true
        maximumCpuCount: true

**Comment by ilia-shipitsin** [comment]
Hello @NaveenVNaik , do you have repro steps, maybe some minimal project publicly available ?

**Comment by NaveenVNaik** [comment]
Hi @ilia-shipitsin , I cannot share the code as it is in my companies private repo.

**Comment by ilia-shipitsin** [comment]
Hello, @NaveenVNaik

In the [issue](https://github.com/dotnet/runtime/issues/94998) mentioned by you is said that VC toolset 14.38 is required.
That toolset is [included](https://github.com/actions/runner-images/blob/main/images/windows/toolsets/toolset-2022.json#L279C1-L286C78) into current windows images.

As there're several toolsets included, VSbuild@1 task may pick either of them. For more diagnostic, please add '-bl' flag to `msbuildArgs', it will produce binary log (file `msbuild.binlog`). 

Can you please collect `msbuild.binlog` via following task

```
- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)\msbuild.binlog'
    ArtifactName: 'msbuild.binlog'
    publishLocation: 'pipeline'
```

**Comment by NaveenVNaik** [comment]
Hello @ilia-shipitsin, 

The issue is resolved.  We have to set the MSVC toolset version to 14.38 in C++/CLI project properties.
[ Configuration Properties -> Advanced -> MSVC Toolset version -> 14.38 ]

![image](https://github.com/actions/runner-images/assets/13975566/4c6ec8d7-0dc6-403a-8a9f-77cb384779d6)


Issue is no issue with windows current image.

Thank you for looking into it. !
