### ISSUE TITLE
.net 7 x86 runtime appears to be missing in latest runner

### ISSUE THREAD

**Issue by mungojam** [actions/runner-images#8950]
### Description

When running tests for x86 targeting .net 7 we are now getting this, despite the fact that the runner image says it contains .net 7. I believe this only impacts x86, not x64. We will move to .net 8 shortly, but Rider hasn't released support for it (only in release candidate).

> You must install or update .NET to run this application.
> App: D:\a\REDACTED\net7.0-windows\testhost.x86.exe
> Architecture: x86
> Framework: 'Microsoft.NETCore.App', version '7.0.0' (x86)
> .NET location: C:\Program Files (x86)\dotnet\
> The following frameworks were found:
>   6.0.25 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>   8.0.0 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
> Learn more:
> https://aka.ms/dotnet/app-launch-failed
> To install missing framework, download:
> https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x86&rid=win-x86&os=win10
> . Please check the diagnostic logs for more information.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/win22%2F20231126.1
https://github.com/actions/runner-images/blob/win22/20231126.1/images/windows/Windows2022-Readme.md

### Is it regression?

yes (logs have been archived now unfortunately, but it was 3 weeks ago)

### Expected behavior

Builds for in-support .net versions should still work for x86 and x64

### Actual behavior

Build failing as it can't find x86 .net 7

### Repro steps

Too much internal build code to post here unfortunately, but create an app targeting .net 7 x86 and try to run tests

**Comment by mikhailkoliada** [comment]
Hello, we never install x86 dotnet to the images, it is expected, if you want to override this behaviour it is better to use the `actions/setup-dotnet` task. I bet it was available as a part of previous VS installation, which is now got upgraded to the dotnet 8. I.e. it was a part of VS itself and not the .net disto (latest dotnet always comes as a part of VS).
