### ISSUE TITLE
Ubuntu-latest default runner failing to install plantuml

### ISSUE THREAD

**Issue by nikosmoum** [actions/runner-images#8953]
### Description

Ubuntu runner cannot install plantuml, due to missing transient dependency: openjdk-11-jre-headless amd64 11.0.20.1+1-0ubuntu1~22.04

The openjdk-11-jre-headless package is being installed as a transient dependency of plantuml. I can see `openjdk-11-jre-headless amd64 11.0.20.1+1-0ubuntu1~22.04` is missing from http://azure.archive.ubuntu.com/ubuntu/dists/jammy-updates/main/binary-amd64/Packages.xz but a newer version `openjdk-11-jre-headless amd64 11.0.21+9-0ubuntu1~22.04` is available.

But for some reason the runner is trying to install the old/missing `11.0.20.1+1-0ubuntu1~22.04` version and failing.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Here is the failing build: https://github.com/candlepin/candlepin.github.io/actions/runs/7100702074/job/19328164385

### Is it regression?

Yes. Here is the last successful build: https://github.com/candlepin/candlepin.github.io/actions/runs/6616697673/job/17971485195

### Expected behavior

The installation of the plantuml package should be successful on the runner.

### Actual behavior

The following error is thrown: 
```
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/o/openjdk-lts/openjdk-11-jre-headless_11.0.20.1%2b1-0ubuntu1%7e22.04_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Repro steps

1. Create a workflow using the default runner  (`runs-on: ubuntu-latest`)
2. In one of the steps of the workflow, try to install plantuml (`sudo apt-get install -y plantuml`)

**Comment by wojsmol** [comment]
Hi @nikosmoum 
Please add `sudo apt update` in https://github.com/candlepin/candlepin.github.io/blob/3ee9c0c70c3f6c87ccf987f16427237e4dfaf69f/.github/workflows/deploy.yml#L25 this will fix this issue.

**Comment by mikhailkoliada** [comment]
Hey! @wojsmol is indeed right, apt-get update or alternatives is indeed required as you start any new runner job. After you perform it the problem is gone. Feel free to reach us out again if you have questions left.
