### ISSUE TITLE
macOS-13-arm64 Image Not Being Found

### ISSUE THREAD

**Issue by Nathan-Molby** [actions/runner-images#8955]
### Description

When using a pipeline with the macOS-13-arm64 runner, we are getting the error

##[warning]An image label with the label unsupported-vmimage does not exist.
##[error]The remote provider was unable to process the request.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macOS-13-arm64

### Is it regression?

Yes

### Expected behavior

macOS-13-arm64 is a valid image

### Actual behavior

macOS-13-arm64 is an unsupported vmimage

### Repro steps

1. Create a pipeline using the macOS-13-arm64 runner
2. Attempt to run it
3. Notice error

**Comment by Nathan-Molby** [comment]
Sounds good, I understand. It is somewhat confusing that the runner-images repo contains this image and Microsoft links to this repository for the software that it supports, but I will revert our repo to use `macos-13`

**Comment by mmrazik** [comment]
Fair feedback. I'll pass that down to make the docs less confusing.

**Comment by Nathan-Molby** [comment]
https://github.com/actions/runner-images/issues/8971
