### ISSUE TITLE
Cannot write in $RUNNER_TEMP

### ISSUE THREAD

**Issue by mmorier** [actions/runner-images#8970]
### Description

I used Github Actions on macos runners for buillding and siging iOS applications.
I follow this [documentation](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development#add-a-step-to-your-workflow) and it works perfectly on runners `macos-latest`. If I set `macos-13` because I need Xcode 15, I have the following error :

```sh
  shell: /bin/bash -e {0}
  env:
    CERTIFICATE_BASE64: ***  
    P12_PASSWORD: ***
    KEYCHAIN_PASSWORD: ***
    MD_APPLE_SDK_ROOT: /Applications/Xcode_15.0.1.app
base64: invalid argument --output
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
security: Error reading infile /Users/runner/work/_temp/certificate.p12: No such file or directory
```

If I run the same script on `macos-latest` runner, everything is OK and I have the following log : 

```sh
   shell: /bin/bash -e {0}
  env:
    CERTIFICATE_BASE64: ***
    P12_PASSWORD: ***
    KEYCHAIN_PASSWORD: ***
1 identity imported.
```

If I display `$CERTIFICATE_PATH` (`CERTIFICATE_PATH=$RUNNER_TEMP/certificate.p12`), it displays the same path (`/Users/runner/work/_temp/certificate.p12) for both runners but it seems macos-13 runner has not the same rights to allow `base64` command writing in it.

So I am totally blocked to build a new signed IPA because I need Xcode 15 and it fails because no certificate can be installed in the keychain for signing the IPA.

I tried to create file with the command `touch $CERTIFICATE_PATH` and I have no issue with this command but after base64 cannot did its job :
```sh
 base64: invalid argument --output
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
security: SecKeychainItemImport: One or more parameters passed to a function were not valid.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-13
Version: 20231025.2

### Is it regression?

yes, it works on   Image: macos-12   Version: 20231029.1

### Expected behavior

```sh
   shell: /bin/bash -e {0}
  env:
    CERTIFICATE_BASE64: ***
    P12_PASSWORD: ***
    KEYCHAIN_PASSWORD: ***
1 identity imported.
```

### Actual behavior

```sh
  shell: /bin/bash -e {0}
  env:
    CERTIFICATE_BASE64: ***  
    P12_PASSWORD: ***
    KEYCHAIN_PASSWORD: ***
    MD_APPLE_SDK_ROOT: /Applications/Xcode_15.0.1.app
base64: invalid argument --output
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
security: Error reading infile /Users/runner/work/_temp/certificate.p12: No such file or directory
```

### Repro steps

1. follow https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development#add-a-step-to-your-workflow
2. execute the step `Install the Apple certificate and provisioning profile` on macos-13 runner, checked everything works on macos-12 runner

**Comment by mikhailkoliada** [comment]
Hello! Please report the issue to the https://github.com/actions/runner repo, `$RUNNER_TEMP` is a directory created by the runner itself, i.e. it is not the hosted image directory as it is located in the `/home/runner/work/` and we have no control over it from our side.
