### ISSUE TITLE
Add k6

### ISSUE THREAD

**Issue by bartul** [actions/runner-images#8973]
### Tool name

k6

### Tool license

GNU Affero General Public License v3.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v0.48.0 (Latest)

### Approximate size

40M

### Brief description of tool

**k6** is a modern load-testing tool, built on [our years of experience](https://k6.io/about) in the performance and testing industries.
It's built to be powerful, extensible, and full-featured. The key design goal is to provide **the best developer experience**.

Its core features are:

- **Configurable load generation.** Even lower-end machines can simulate lots of traffic.
- **Tests as code.** Reuse scripts, modularize logic, version control, and integrate tests with your CI.
- **A full-featured API.** The scripting API is packed with features that help you simulate real application traffic.
- **An embedded JavaScript engine.** The performance of Go, the scripting familiarity of JavaScript.
- **Multiple Protocol support**. HTTP, WebSockets, gRPC, and more.
- **Large extension ecosystem.** You can extend k6 to support your needs. And many people have already shared their extensions with the community!
- **Flexible metrics storage and visualization**. Summary statistics or granular metrics, exported to the service of your choice.

### URL for tool's homepage

https://k6.io/

### Provide a basic test case to validate the tool's functionality.

```bash
// execute in terminal - k6 run <this file>
import http from 'k6/http';

export default function () {
  http.get('http://test.k6.io');
}
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
https://k6.io/docs/get-started/installation/
```

### Tool installation time in runtime

~20s

### Are you willing to submit a PR?

Yes

**Comment by ilia-shipitsin** [comment]
Hey there!

We've decided not to include k6 in the images to help reduce maintenance. We're trying to strike a balance between convenience and keeping things streamlined and k6 isn't a super common tool for everyone.

Also, for Ubuntu you can use [containers](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container)  to directly use prebuilt k6 image https://hub.docker.com/r/grafana/k6

If you have any more questions or suggestions, feel free to share.
