### ISSUE TITLE
ADO pipeline failes while building windows image build for agent

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#8988]
### Description

ADO pipeline failes while building windows image build for agent

==> azure-arm.image: Multiple download urls found in SeleniumHQ/selenium version "4.16.0" matching pattern "*/selenium-server-*.jar":
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.0.jar
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.1.jar
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:682 char:9
==> azure-arm.image: +         throw "Multiple download urls found in ${Repository} version  ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Multiple downlo...rver-4.16.1.jar:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Multiple download urls found in SeleniumHQ/selenium version "4.16.0" matching pattern "*
==> azure-arm.image:    /selenium-server-*.jar":
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.0.jar
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.1.jar
==> azure-arm.image:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image 20231205.1.0

### Is it regression?

NA

### Expected behavior

Pipeline complete with building image for windows agent.

### Actual behavior

==> azure-arm.image: Multiple download urls found in SeleniumHQ/selenium version "4.16.0" matching pattern "*/selenium-server-*.jar":
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.0.jar
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.1.jar
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:682 char:9
==> azure-arm.image: +         throw "Multiple download urls found in ${Repository} version  ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Multiple downlo...rver-4.16.1.jar:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Multiple download urls found in SeleniumHQ/selenium version "4.16.0" matching pattern "*
==> azure-arm.image:    /selenium-server-*.jar":
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.0.jar
==> azure-arm.image: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.1.jar
==> azure-arm.image:

### Repro steps

Rerun pipeline.

**Comment by erik-bershel** [comment]
Hey @jaswant-dnv!
It will be fixed after merge of https://github.com/actions/runner-images/pull/8981

**Comment by mikhailkoliada** [comment]
https://github.com/actions/runner-images/pull/8981 is merged, please sync your main branch.
