### ISSUE TITLE
The practice of bundling external plugins into Packer will be removed in an upcoming version

### ISSUE THREAD

**Issue by abdul561** [actions/runner-images#8989]
### Description

This template relies on the use of plugins bundled into the Packer binary.

My packer version has went up to 1.10 if i now try to run my pipeline to build the image it does not work since the error the practice of bundling external plugins has now been removed. Is there any way we could maybe add an external plugins folder we can reference to? My fix right now was to go on the version where it does not get removed but interested in thoughts?

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Its not image version bug more packer version

### Is it regression?

No

### Expected behavior

For it to use azure plugins normally

### Actual behavior

Because it does not bundle the plugins i get this error: 
<img width="374" alt="image" src="https://github.com/actions/runner-images/assets/74545992/3f347428-b1f0-4610-8909-dafa4a8bc416">

### Repro steps

1. Use packer version 1.10
2. Run normally

**Comment by erik-bershel** [comment]
Hey @abdul561!
Thank you for reporting such a relevant and major issue. We are working on it right now. Will update state as soon as possible.

**Comment by acollard** [comment]
Ran into the same issue. 

As a workaround, you can add a build task to install the missing Azure Packer plugin using this command:
`packer plugins install github.com/hashicorp/azure`

**Comment by abdul561** [comment]
> Ran into the same issue.
> 
> As a workaround, you can add a build task before the Packer task to install the missing Azure plugin using this command: `packer plugins install github.com/hashicorp/azure`

Thanks Andrew

**Comment by Triodes** [comment]
I believe the solution here would be to add a block to the template:
```hcl
packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 2"
    }
  }
}
```
after which you can install the plugins required for the template with `packer init <path-to-template-file.pkr.hcl>`

This one is specifically for templates relying on the azure plugin of course, but the idea is the same for all templates.
Link to relevant docs: https://developer.hashicorp.com/packer/docs/commands/init

**Comment by JaimePoloTeck** [comment]
I am having the same issue even when the image version 1.10.0 is supposed to have the azure-arm provider installed

<img width="932" alt="image" src="https://github.com/actions/runner-images/assets/98366998/5411a087-fd33-4849-9e58-f02634ee416c">

**Comment by mikhailkoliada** [comment]
Should be fixed now.
