### ISSUE TITLE
ADO pipeline failes while building windows image build for agent

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#8996]
### Description

Validating packer template...
##[debug]Agent running environment resource - Disk: available:26594.00MB out of 85160.00MB, Memory: used 16MB out of 15981MB, CPU: usage 3.45
##[debug]Agent running environment resource - Disk: available:26594.00MB out of 85160.00MB, Memory: used 16MB out of 15981MB, CPU: usage 3.36
Error: Failed to initialize build "image"

The builder azure-arm is unknown by Packer, and is likely part of a plugin that
is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.

https://developer.hashicorp.com/packer/integrations?filter=azure

Packer template validation failed.
At /agent/_work/1/s/runner-images/helpers/GenerateResourcesAndImage.ps1:247 char:9
+         throw "Packer template validation failed."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Packer template validation failed.:String) [], RuntimeException
+ FullyQualifiedErrorId : Packer template validation failed.
##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed

Tried installing azure plugins
packer plugins install github.com/hashicorp/azure
But NO Luck.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image 20231205.1.0

### Is it regression?

NA

### Expected behavior

Agent image pipelinegets completed.

### Actual behavior

Validating packer template...
##[debug]Agent running environment resource - Disk: available:26594.00MB out of 85160.00MB, Memory: used 16MB out of 15981MB, CPU: usage 3.45
##[debug]Agent running environment resource - Disk: available:26594.00MB out of 85160.00MB, Memory: used 16MB out of 15981MB, CPU: usage 3.36
Error: Failed to initialize build "image"

The builder azure-arm is unknown by Packer, and is likely part of a plugin that
is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.

https://developer.hashicorp.com/packer/integrations?filter=azure

Packer template validation failed.
At /agent/_work/1/s/runner-images/helpers/GenerateResourcesAndImage.ps1:247 char:9
+         throw "Packer template validation failed."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Packer template validation failed.:String) [], RuntimeException
+ FullyQualifiedErrorId : Packer template validation failed.
##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed

### Repro steps

rerun pipeline

**Comment by erik-bershel** [comment]
Hey @jaswant-dnv!

It's a known issue related to Packer 1.10 release. Please track progress of resolving here: https://github.com/actions/runner-images/issues/8989
I'm going to close this issue as a duplicate, but feel free to ask any questions about it here or to open new items in case of other concerns.
