### ISSUE TITLE
Update/Add Xcode 15.1 to macOS 13

### ISSUE THREAD

**Issue by luquanlang** [actions/runner-images#8997]
### Tool name

Xcode 15.1

### Tool license

NA

### Add or update?

- [X] Add
- [X] Update

### Desired version

15.1

### Approximate size

2.92 GB

### Brief description of tool

Xcode 15.1 has been released. It contains a number of fixes that could improve the performance issues that many of us are having when running CI actions on GitHub.

<img width="920" alt="Captura de pantalla 2023-12-12 a les 8 15 44" src="https://github.com/actions/runner-images/assets/45352151/9120b174-0e89-48b9-a6d0-00b11c0d3562">
 that contains a number of fixes, chief of which is the improved iOS 17.0 simulator performance.

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

No, because of its size

**Comment by hr147** [comment]
We are also waiting for the Xcode 15.1

**Comment by erik-bershel** [comment]
Hi @luquanlang and @hr147! 
A new version of the Xcode will be added in the next release of macOS-13.

**Comment by luquanlang** [comment]
Awesome! @erik-bershel Do you have an estimated date of when that might be? 🥹

**Comment by erik-bershel** [comment]
Unfortunately, I can’t give an exact or approximate release dates right now, but we understand the importance of this kind of update and will make every effort to release it as soon as possible.

**Comment by mmalesevic** [comment]
@erik-bershel thats great news! Waiting for it patiently...

**Comment by iletai** [comment]
With iOS Development Require macos-14. For example, SwiftUI iOS 17+ seems to still wait this. There will be many limitations to upgrading to Xcode 15 and iOS 17+ with build and deploy in macos14.

https://developer.apple.com/news/?id=khzvxn8a
> Starting in April 2024, apps submitted to the App Store must be built with Xcode 15 and the iOS 17 SDK, tvOS 17 SDK, or watchOS 10 SDK (or later).

**Comment by Jalroka** [comment]
If I have it right xcode 15 requires macOS 14.  I'm suprised to see that macOS 13 is still preview.  The only work around for this I can find is this.  Can we get an update on when macOS 14 and xcode 15 even in preview will become available.  https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/osx-agent?view=azure-devops

**Comment by mluisbrown** [comment]
> If I have it right xcode 15 requires macOS 14. 
It doesn't. I've been running Xcode 15 for weeks on macOS 13 and only updated to macOS 14 a couple of days ago.
The only compatibility issue that exists is that on macOS 14 you can no longer run Xcode 14.

**Comment by robinphillips** [comment]
Looking forward to 15.1 being added. There are problems with UITests in Xcode 15.0.1 and the new lifecycle method `viewIsAppearing` requires building in Xcode 15 or later.

**Comment by mikhailkoliada** [comment]
It will be deployed somewhere in the start-mid January (after holidays)

**Comment by robinphillips** [comment]
> It will be deployed somewhere in the start-mid January (after holidays)

Thanks for letting us know. It's helpful to have a timeframe on this.

**Comment by honkmaster** [comment]
@MikhailKoliada I appreciate the update on the timeframe for Xcode 15.1 in GitHub actions.

It's worth noting that Xcode 15.1 was officially released on December 5th, and a release in mid-January would imply a delay of 4-6 weeks. From my perspective, such a lengthy delay for a(n essential) bugfix release can be considered **critical**. Of course, holiday season is indeed approaching, and it's well-understood that resources can be limited during this time. However, GitHub actions play a critical role in numerous projects, and the community greatly relies on them.

**In the interest of the community, is there a plan to minimize such extended delays for future updates?**

**Comment by pafdad** [comment]
I completely agree with @honkmaster

CircleCI has already gotten Xcode 15.1, and not only that, but 15.2.0 beta as well https://circleci.com/docs/testing-ios/

Over the years I have used a variety of CI systems and I have to say, unfortunately, GitHub is the slowest in updating to latest Xcode versions for Flutter/iOS project which is proving to be a big problem.

**Comment by mluisbrown** [comment]
I would also suggest that we get a runner image for Xcode 15.1 that uses macOS 14. Whilst Xcode 15 runs just fine on macOS 13, there is some evidence [from similar performance issues on Circle CI](https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/49205/110) that the performance issue is only really solved running Xcode 15.1 on macOS 14.

**Comment by khsora34** [comment]
I can already see and select Xcode 15.1 with the `xcodes` command in the `macos-13-xl` image. Testing it now!

**Comment by luquanlang** [comment]
This request was completed. An updated image of macOS 13 that includes Xcode 15.1 was released
https://github.com/actions/runner-images/releases/tag/macos-13%2F20231218.2

**Comment by alecazam** [comment]
On macos-latest, but still seeing SwiftUI code failing due to use of Xcode 14.2 on GItHub actinos.  Is there an easy way to get 15.1?
