### ISSUE TITLE
Please update binutils package for Ubuntu 2204

### ISSUE THREAD

**Issue by chrisbra** [actions/runner-images#9016]
### Description

Due to a recent security update in Ubuntu 22.04, the installed binutils package is slightly out of date (see changelog here: https://changelogs.ubuntu.com/changelogs/pool/main/b/binutils/binutils_2.38-4ubuntu2.4/changelog), which causes the CI in the Vim project to fail https://github.com/vim/vim/actions/runs/7193408595/job/19591800767

If I read the docs correctly, this also affect the latest tag 20231211 https://github.com/actions/runner-images/blob/releases/ubuntu22/20231211/images/ubuntu/Ubuntu2204-Readme.md (search for binutils)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/vim/vim/actions/runs/7193408595/job/19591800767

### Is it regression?

yes

### Expected behavior

be able to add architecture i386

### Actual behavior

fails:
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 binutils : Conflicts: binutils:i386 but 2.38-4ubuntu2.4 is to be installed
 binutils:i386 : Conflicts: binutils but 2.38-4ubuntu2.3 is to be installed
 binutils-common : Breaks: binutils-common:i386 (!= 2.38-4ubuntu2.3) but 2.38-4ubuntu2.4 is to be installed
 binutils-common:i386 : Breaks: binutils-common (!= 2.38-4ubuntu2.4) but 2.38-4ubuntu2.3 is to be installed
 libbinutils : Breaks: libbinutils:i386 (!= 2.38-4ubuntu2.3) but 2.38-4ubuntu2.4 is to be installed
 libbinutils:i386 : Breaks: libbinutils (!= 2.38-4ubuntu2.4) but 2.38-4ubuntu2.3 is to be installed
 libctf0 : Breaks: libctf0:i386 (!= 2.38-4ubuntu2.3) but 2.38-4ubuntu2.4 is to be installed
 libctf0:i386 : Breaks: libctf0 (!= 2.38-4ubuntu2.4) but 2.38-4ubuntu2.3 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Error: Process completed with exit code 100.
```

### Repro steps

Install i386 architecture, see .e.g here: https://github.com/vim/vim/blob/a02fe3480f8ea9e99b9d7398923aed225ca655cd/.github/workflows/ci.yml#L90-L123

**Comment by mikhailkoliada** [comment]
Deployed
