### ISSUE TITLE
ADO pipeline fails while building windows image 2022

### ISSUE THREAD

**Issue by jain-ranjith** [actions/runner-images#9017]
### Description

The Pipeline fails after this..

```
==> azure-arm.image: Provisioning with powershell script: /home/vsts/work/1/s/images/windows/templates/../scripts/build/Install-Miniconda.ps1
==> azure-arm.image: Unable to find checksum for Miniconda3-latest-Windows-x86_64.exe in https://repo.anaconda.com/miniconda/
==> azure-arm.image: At C:\Windows\Temp\script-65799a8a-810a-b2f0-e66c-01572b2f487f.ps1:21 char:5
==> azure-arm.image: +     throw "Unable to find checksum for $installerName in https://repo/ ...
==> azure-arm.image: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Unable to find ....com/miniconda/:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Unable to find checksum for Miniconda3-latest-Windows-x86_64.exe in https://repo.anacond/
==> azure-arm.image:    a.com/miniconda/
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.image: 
==> azure-arm.image: Deleting Virtual Machine deployment and its attatched resources...
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20231211.1.0

### Is it regression?

No

### Expected behavior

Pipeline complete with building image for windows agent.

### Actual behavior

==> azure-arm.image: Provisioning with powershell script: /home/vsts/work/1/s/images/windows/templates/../scripts/build/Install-Miniconda.ps1
==> azure-arm.image: Unable to find checksum for Miniconda3-latest-Windows-x86_64.exe in https://repo.anaconda.com/miniconda/
==> azure-arm.image: At C:\Windows\Temp\script-65799a8a-810a-b2f0-e66c-01572b2f487f.ps1:21 char:5
==> azure-arm.image: +     throw "Unable to find checksum for $installerName in https://repo/ ...
==> azure-arm.image: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Unable to find ....com/miniconda/:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Unable to find checksum for Miniconda3-latest-Windows-x86_64.exe in https://repo.anacond/
==> azure-arm.image:    a.com/miniconda/
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.image: 
==> azure-arm.image: Deleting Virtual Machine deployment and its attatched resources...

### Repro steps

run the pipeline

**Comment by mikhailkoliada** [comment]
fixed, do not forget to sync with the repo.
