### ISSUE TITLE
Ubuntu image update breaks cypress parallel testing

### ISSUE THREAD

**Issue by pmerwin** [actions/runner-images#9018]
### Description

When the ubuntu runner is being updated, our tests fail because some of the machines get an older version of the image than the others in the matrix, in this case that mismatches the browser version, which breaks our cypress runner ( it will only run when all machines in the matrix have the same browser version)

so when we specify the 22.04 runner,  or latest, the matrix machines are getting 2 different versions:

jobs:
  e2e:
    runs-on: ubuntu-22.04
    
    spins up either version:

20231211.1.0
20231205.1.0

is there a way we can specify the version in our workflow to remedy this?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

sorry we do not

### Is it regression?

no

### Expected behavior

We would like to be able to lock an image version to avoid matrix runner's mismatches.

### Actual behavior

Mismatched versions:

cypress error in the actions:

`In order to run in parallel mode each machine must send identical environment parameters such as:

 - specs
 - osName
 - osVersion
 - browserName
 - browserVersion (major)

This machine sent the following parameters:

{
  "osName": "linux",
  "osVersion": "Ubuntu - ",
  "browserName": "Chrome",
  "browserVersion": "120.0.6099.71.... (Expected: 1[19](https://github.com/adept-at/lib-cypress-canary/actions/runs/7197639056/job/19605228872#step:8:20))",`

### Repro steps

Run any wf specifying ubuntu-22-04 or latest for the runner, have a matrix of 8 machines, they will not all get the same image version.  :(

**Comment by mikhailkoliada** [comment]
Hey! We are in the process of deploying a new ubuntu versions, you can observe it here: https://github.com/actions/runner-images/pull/8993 and here https://github.com/actions/runner-images/pull/8992 as soon as these are merged it should be fine for you.

**Comment by pmerwin** [comment]
> Hey! We are in the process of deploying a new ubuntu versions, you can observe it here: #8993 and here #8992 as soon as these are merged it should be fine for you.

Yes, I understand, but we are going on our 3rd day of test failures, if we could lock the version that would mitigate that. :).  This has happened now each time the runner image is updated.  We appreciate any help to address this.

**Comment by pmerwin** [comment]
In the future, can we have a feature to specify the image version to help us mitigate this?
