### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by CripTz00** [actions/runner-images#9024]
### Tool name

Npm

### Tool license

MIT

### Add or update?

- [X] Add
- [X] Update

### Desired version

Latest

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hello!
All images already contain NPM. If you want to upgrade to the version of the package manager you need, you can do it like this: `npm install npm@latest -g` - it shouldn't take much time. If you meant something else, then please ping me here with more information.
