### ISSUE TITLE
Java Native Interface (JNI) fails on loading native libraries

### ISSUE THREAD

**Issue by MaciejG604** [actions/runner-images#9026]
### Description

On the version `20231204.4` of `macos-13` the runners fail when a GraalVM native image application tries to load native libraries using JNI.

The same behaviour was present when using the new runner `macOS-12/20241115.2`. While everything was fine on `macOS-12/20231029.1`.

What could be the issue? What's the difference between these versions that could have caused this?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231204.4

https://github.com/VirtusLab/scala-cli/actions/runs/7197273928/job/19604787698?pr=2630#step:5:777

### Is it regression?

20231025.2

### Expected behavior

The library should be loaded with no problems.

### Actual behavior

The native library can't be loaded with exception:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /Users/runner/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/virtuslab/scala-cli/libsodiumjni/0.0.3/libsodiumjni-0.0.3-x86_64-apple-darwin.dylib
```

### Repro steps

The reproduction can be seen on the CI jobs that happen to run on `macos-12` `20231204.4` and not `20231025.2`, but I cannot find the root cause to minimize it.
E.g. Two attempts here:
OK https://github.com/VirtusLab/scala-cli/actions/runs/7197273928/job/19633628265?pr=2630#logs
NOK https://github.com/VirtusLab/scala-cli/actions/runs/7197273928/job/19604787698?pr=2630#logs

**Comment by mikhailkoliada** [comment]
Hello, please provide a minimal repro steps so we could reproduce the issue and scope it properly

**Comment by erik-bershel** [comment]
Hey @MaciejG604!
How is your investigation going? Is it possible for you to provide simpler repro-steps than those presented?

**Comment by erik-bershel** [comment]
Hey @MaciejG604!

As I see you have already switched to a newer version of the `libsodium jni` and it seems as a fix for you. Please ping me if I'm wrong.
