### ISSUE TITLE
Failed to fetch xserver-xorg-dev: 404  Not Found

### ISSUE THREAD

**Issue by cfnptr** [actions/runner-images#9039]
### Description

Hello!

My action is trying to install xorg-dev library on Ubuntu 22.04 Jammy and it fails with this error:

```
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/x/xorg-server/xserver-xorg-dev_21.1.4-2ubuntu1.7%7e22.04.2_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
```

Nothing has changed in the action script, it just stopped working.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/cfnptr/garden/actions/runs/7234721336/job/19711376705

### Is it regression?

Yes, last successful run: https://github.com/cfnptr/garden/actions/runs/7153808761/job/19480671496

### Expected behavior

A xorg-dev package is installing as before.

### Actual behavior

Package is not found (404) in the mirror file.

### Repro steps

Re-run job

**Comment by shamil-mubarakshin** [comment]
Hello @cfnptr.
We will take a look

**Comment by shamil-mubarakshin** [comment]
@cfnptr, Could you add `sudo apt-get update` to your workflow and re-run?
Invoking update command is recommended when working with apt on ubuntu runners.

**Comment by cfnptr** [comment]
Yeah, now it works. Thank you!
