### ISSUE TITLE
[macOS] screen recordings are green

### ISSUE THREAD

**Issue by cmorten** [actions/runner-images#9047]
### Description

Recently have observed (what appears to be) an increase in screen recordings showing as green on macos-12 runners where screen recordings taken using the `screencapture` CLI.

This appears similar to the issue described in https://apple.stackexchange.com/questions/87613/quicktime-records-a-green-screen

Example output recording: https://guidepup.github.io/aria-at-tests/data/attachments/2776d48372a34b12.qt

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/guidepup/aria-at-tests/actions/runs/7258634208/job/19774873344

```
Current runner version: '2.311.0'
Operating System
  macOS
  12.6.9
  21G726
Runner Image
  Image: macos-12
  Version: 20231029.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231029.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231029.1
Runner Image Provisioner
  2.0.321.1
```

### Is it regression?

Yes

### Expected behavior

Screen recordings should not be green.

### Actual behavior

Screen recordings are green.

### Repro steps

1. Run macos-12 job.
2. Run command similar to `/usr/sbin/screencapture -v -C -k -T0 -g recording.mov`.
3. Observe recording is green.

**Comment by shamil-mubarakshin** [comment]
Hello @cmorten,
We will take a look

**Comment by jlp-craigmorten** [comment]
By way of example / visual aid, here is an example https://github.com/guidepup/setup/actions/runs/7527748171 where have attached the recordings generated for MacOS 11, 12, and 13. MacOS 12 is almost always green.

https://github.com/actions/runner-images/assets/124147726/b229e4f9-58ba-4b1e-badd-31c857bc0da4

https://github.com/actions/runner-images/assets/124147726/d2cb9434-c934-42a5-b86b-b4425712b51c

https://github.com/actions/runner-images/assets/124147726/b6b0eeff-f7fe-4133-ba72-0790ef1426f5

**Comment by Vyazovoy** [comment]
Could #9529 be related to this?

**Comment by jlp-craigmorten** [comment]
> Could #9529 be related to this?

May be similar, but in the linked issue it is MacOS 13 and 14 having problems whereas in this issue it is MacOS 12 having problems.

**Comment by prasanjitsahoo** [comment]
HI @jlp-craigmorten , It's just a faulty macOS 12 and there is nothing we can do about it. Please consider to switch to MacOS 13 or MacOS 14 as you wish. Thanks
