### ISSUE TITLE
Update MSBuild on Ubuntu

### ISSUE THREAD

**Issue by stevewithey** [actions/runner-images#9051]
### Tool name

MSBuild

### Tool license

NA

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.7.0 or newer

### Provide a basic test case to validate the tool's functionality.

```bash
When doing a Nuget Restore task in Azure Devops with .NET 8 repo. Currently you see this warning:
Version 8.0.100 of the .NET SDK requires at least version 17.7.0 of MSBuild. The current available version of MSBuild is 16.10.1.31701

This error should go away if it can be upgraded.
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hey!

`dotnet msbuild` and `msbuild` are the two different implementation `msbuild` comes from mono. The version you need is already installed in the image 

<img width="1152" alt="image" src="https://github.com/actions/runner-images/assets/88318005/b0fbb46d-fbd8-4cd3-82d6-669013a3c7a8">
