### ISSUE TITLE
Include file KHR/khrplatform.h' file not found

### ISSUE THREAD

**Issue by tobbi** [actions/runner-images#9061]
### Description

When building SuperTux with glbinding, we keep getting this error message since the latest build:
```
/usr/local/include/glbinding/gl/types.h:10:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231216.1

https://github.com/SuperTux/supertux/actions/runs/7297439106/job/19886676323

### Is it regression?

yes 20231127.1 https://github.com/SuperTux/supertux/actions/runs/7208676326/job/19638135965

### Expected behavior

SuperTux glbinding build succeeds.

### Actual behavior

SuperTux glbinding build fails with the following error message:

```
/usr/local/include/glbinding/gl/types.h:10:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
```

### Repro steps

See https://github.com/SuperTux/supertux/blob/master/.github/workflows/macos.yml

**Comment by tobbi** [comment]
https://github.com/SuperTux/supertux/issues/2704

**Comment by shamil-mubarakshin** [comment]
Hello @tobbi,
We will take a look

**Comment by shamil-mubarakshin** [comment]
@tobbi, `glbinding` version installed by brew has been [recently](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+glbind+is%3Aclosed) updated to `3.3.0`. I tried adding following to the workflow as a workaround and project build succeeded:
```
brew install glbinding@2
brew link glbinding@2
```
With the above, issue doesn't seem to be image related so I am closing it for now. Feel free to reach out in case of further concerns
