### ISSUE TITLE
Add support for cloud_environment_name for azure-arm builder

### ISSUE THREAD

**Issue by GitYukari** [actions/runner-images#9062]
### Description

All Packer templates currently accept the following parameters to authenticate to the Azure Resource Manager:

```
source "azure-arm" "image" {
  client_cert_path                       = "${var.client_cert_path}"
  client_id                              = "${var.client_id}"
  client_secret                          = "${var.client_secret}"
  object_id                              = "${var.object_id}"
  tenant_id                              = "${var.tenant_id}"
}
```

While this provides flexibility in specifying the authentication method and tenant, it does not provide any flexibility for other Azure clouds. If this parameter is not included, running this template in any Azure cloud besides the Public cloud will fail authentication to Azure.

The ARM builder for Packer specifies the `cloud_environment_name` parameter. It states the value is "one of Public, China, or USGovernment. Defaults to Public. Long forms such as USGovernmentCloud and AzureUSGovernmentCloud are also supported."

Since it is currently omitted, it is defaulting to Public. It would add more flexibility to add `cloud_environment_name` as an optional user-provided variable (like object_id or private_virtual_network_with_public_ip) to allow this template to be used in any cloud supported by Packer.

Also, as a side bonus, I strongly recommend adding `use_azure_cli_auth` as an optional parameter (bool). This will increase the security of any runner because it will not be necessary to specify the secret to the pipeline, and instead it will just use the Azure CLI service connection 

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

- https://github.com/actions/runner-images/blob/main/images/windows/templates/windows-2022.pkr.hcl
- https://github.com/actions/runner-images/blob/main/images/windows/templates/windows-2019.pkr.hcl
- https://github.com/actions/runner-images/blob/main/images/ubuntu/templates/ubuntu-22.04.pkr.hcl
- https://github.com/actions/runner-images/blob/main/images/ubuntu/templates/ubuntu-20.04.pkr.hcl
- https://github.com/actions/runner-images/blob/main/images/ubuntu/templates/ubuntu-minimal.pkr.hcl

### Is it regression?

No

### Expected behavior

If the user provides `cloud_environment_name` as an input parameter to the template, the template should accept the value when authenticating to Azure using the provided service principal.

### Actual behavior

Packer fails to authenticate to the cloud (defaults to "Public" ARM endpoints)

### Repro steps

1. Attempt to deploy template to Azure Public > Success
2. Attempt to deploy same template to US Government > Fail
3. Add `cloud_environment_name = "USGovernment"` to `source "azure-arm" "build_image"` > Success
4. (Ideally, just make it a variable so it defaults to Public if not otherwise specified):
    - cloud_environment_name = "${var.cloud_environment_name}"

**Comment by mikhailkoliada** [comment]
Hello! Given that the packer parameter defaults to `Public` and it is like 99% of use cases, we would not like to add more parameters to the template, please modify your template as you see fit.
