### ISSUE TITLE
Add Apple Silicon runners to Azure DevOps

### ISSUE THREAD

**Issue by Maxwell175** [actions/runner-images#9068]
### Tool name

Apple Silicon

### Add or update?

- [X] Add
- [ ] Update

### Desired version

macOS 13

### Brief description of tool

Now that Apple Silicon is a mainstay in the Apple ecosystem, it is really becoming pressing to be able to compile on arm64. GitHub has had Apple Silicon runners for a while now.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Duplicate of https://github.com/actions/runner-images/issues/8971

**Comment by Maxwell175** [comment]
Apologies for the dup. I was unable to find the original because it was closed for some reason.
