### ISSUE TITLE
PostgreSQL is missing on macOS 13

### ISSUE THREAD

**Issue by ikalnytskyi** [actions/runner-images#9083]
### Description

PostgreSQL is preinstalled on all other images, even on macOS 12. However, it's missing on macOS 13. It'd be nice to have it there too in order to make sure we can run it regardless of the macOS version.

It seems PostgreSQL can be easily installed on macOS 13 using Homebrew.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

no

### Expected behavior

PostgreSQL is preinstalled.

### Actual behavior

PostgreSQL is not preinstalled.

### Repro steps

n/a

**Comment by erik-bershel** [comment]
Hey @ikalnytskyi!
There are no plans to add databases to the macOS 13 images at this point. As you said it might be easily install via Homebrew during runtime for now.
I'm going to close this issue as a clone of https://github.com/actions/runner-images/issues/9029.

**Comment by ikalnytskyi** [comment]
Thank you for your reply, @erik-bershel. Can you suggest the best way to check for macOS 13 executors please? As I understand it, `runner.os` just points to the generic operating system name and does not contain a version number. I'm positive I can get one using `sw_vers -productVersion` on macOS, but maybe there's a better way.

**Comment by erik-bershel** [comment]
@ikalnytskyi 
As I remember we are using the same command to check version in bash/zsh and also some a bit more complicated constructions for PowerShell ([example](https://github.com/actions/runner-images/blob/main/images/macos/scripts/docs-gen/SoftwareReport.Common.psm1#L151C4-L151C4)).
