### ISSUE TITLE
Update/Add 7zip

### ISSUE THREAD

**Issue by PilotMob3** [actions/runner-images#9117]
### Tool name

7zip

### Tool license

GNU LGPL

### Add or update?

- [ ] Add
- [X] Update

### Desired version

23.01

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

Maybe

**Comment by mikhailkoliada** [comment]
Hey! 7zip 23.01 is available as a part of the windows-2019 and windows-2022 runners, as of ubuntu/macOS runners there is a p7zip implementation installed from the stock apt / homebrew available which is quite different, but we have no plans to install exactly 7zip binary there. If you have questions left feel free to reach us out again.
