### ISSUE TITLE
PowerShell Az Module is missing

### ISSUE THREAD

**Issue by flcdrg** [actions/runner-images#9122]
### Description

Docs indicate that the Az module should be installed, but running `Get-InstalledModule` or `Get-Module -ListAvailable` doesn't list any Az modules.

This may be correct for Windows images as there is a comment under https://github.com/actions/runner-images/blob/win22/20231217.2/images/windows/Windows2022-Readme.md#powershell-modules "All other versions are saved but not installed.", but this comment does not appear in the Ubuntu notes https://github.com/actions/runner-images/blob/ubuntu22/20231217.2/images/ubuntu/Ubuntu2204-Readme.md#powershell-modules so one would expect that Az is installed there.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
  Version: 20231217.2.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231217.2/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231217.2

Image: windows-2022
  Version: 20231217.2.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20231217.2/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231217.2

### Is it regression?

Probably

### Expected behavior

Az module should be pre-installed and available to use.

### Actual behavior

Az module doesn't appear to be installed

### Repro steps

See job output from https://github.com/flcdrg/runner-info/actions/runs/7437652506, specifically https://github.com/flcdrg/runner-info/actions/runs/7437652506/job/20235522862

**Comment by mikhailkoliada** [comment]
Hey! all az-specific modules are indeed installed but by the `C:\\Modules` path, which is not a [art pf the PSModulePath directory, so it will not be by default available in the standard `Get-*` commands and you have to operate on them in semi-manual mode.

**Comment by flcdrg** [comment]
@mikhailkoliada what about the ubuntu image?

**Comment by mikhailkoliada** [comment]
@flcdrg it resides in `/usr/share` there, the reason why is simple, adding them to `$PSModulePath` leads to unwanted conflicts which we want to avoid

**Comment by flcdrg** [comment]
@mikhailkoliada ok. Given they are not usable by default, it seems like it should be mentioned in the notes for the Ubuntu releases (in a similar way that it is done for Windows) to avoid confusion.
