### ISSUE TITLE
Update/Add Xcode 15.2

### ISSUE THREAD

**Issue by erikng** [actions/runner-images#9139]
### Tool name

Xcode 15.2

### Tool license

NA

### Add or update?

- [X] Add
- [X] Update

### Desired version

15.2 (15C500b)

### Approximate size

3GB

### Brief description of tool

Xcode 15.2 has been released. It contains a number of fixes that could improve the performance issues that many of us are having when running CI actions on GitHub.

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
should be fixed, sync your main.

**Comment by erikng** [comment]
Assuming you closed this originally because of the other 15.2 build currently being deployed. They are definitely different builds unfortunately, to the point where I would say to stop the rollout of the beta one.

**Comment by Alexey-Ayupov** [comment]
Hello @erikng, xcode 15.2 will be added shortly

**Comment by kstoletniy** [comment]
I've updated the xcode-version to '15.2-beta', however the xcodebuild -version is pointing to Xcode 14.3.1.
In my case this cause that builds failure because of a different swift-tool-version that i use in my project.

**Comment by grzegorzkrukowski** [comment]
It seems that Xcode 15.2 is officially available for regular macOS13 machines, but it's still randomly failing for us on `macos-13-xlarge` machines - it works most of the time, but randomly it is not seeing the latest Xcode version.
Sometimes it uses `20240107.1` without new version and sometimes `20240114.1` with Xcode 15.2.

**Comment by mikhailkoliada** [comment]
available now

**Comment by hughesjs** [comment]
@mikhailkoliada - Is this available? I've tried `macos-latest`, `macos-14`, and `macos-13` and none of them seem to have xcode 15. 

Is there some additional step I need to take in my workflow?

**Comment by Eilon** [comment]
If you're using `macos-latest` as the image, that's on macOS 12.x, which does _not_ have Xcode 15.2. You'll need to pick a macOS image that actually has Xcode 15.2 on it.

Check out which macOS image name maps to which macOS version here: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
And check which Xcode is available on each macOS version here: https://github.com/actions/runner-images/blob/releases/macos-13/20240114/images/macos/macos-13-Readme.md#installed-sdks
