### ISSUE TITLE
Install VisualStudio signature thumbprint do not match

### ISSUE THREAD

**Issue by liwu2024** [actions/runner-images#9140]
### Description

Install-VisualStudio.ps1 failed with Signature thumbprint does not match expected.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest

### Is it regression?

no

### Expected behavior

Signature Thumbprint should match

### Actual behavior

The signature of Install-VisualStudio.ps1 was hardcode on the toolset-2019.json and toolset-2022.json, it doesn't match the new vs_enterprise.exe from https://aka.ms/vs/16/release/vs_Enterprise.exe

### Repro steps

na

**Comment by xxsumsxx** [comment]
x2

**Comment by achechen** [comment]
Current version is 17, not 16. The signature in the toolset config files is for version 17.

**Comment by Alexey-Ayupov** [comment]
Hello @liwu2024, we aware of the issue and will fix it shortly.

**Comment by pmatthews05** [comment]
@sergei-pyshnoi I have a question regarding this, I've been pulling the last tag release (win19/20231217.2) of the code to build my own images in and I too encountered this issue. 

Does that mean, by pulling the given release, each time I build the image, I do not actually build the exact same image? Surely a point of a release is to be able to pull it down and build exactly the same image?

**Comment by frittsy** [comment]
@pmatthews05 the pending documentation change in #8946 might clear this up for you.

You'll find that some tooling is pinned to a specific version, while others will grab the latest minor/patch version available. So it expected that some tooling will change with each build.

**Comment by mikhailkoliada** [comment]
fixed, please sync your main branch
