### ISSUE TITLE
Encoding of secret values broken on Windows Server 2022

### ISSUE THREAD

**Issue by eberthold** [actions/runner-images#9141]
### Description

We encountered a bug in the processing of some special characters of secret values in our pipeline when using a Windows Server 2022 Image.

The secrets are stored in an azure key vault and downloaded during the pipeline run with the AzureKeyVault@2 task.
When signing our Android app on two of four environments the signing fails with different behaviors, because of different special symbols in the secret value, which is the keystore password.

Behavior 1:
The password contains a quote symbol like `xxx%xxx"xxx`. In this case the AndroidSigning@3 task does the following:
It fails on signing the aab file and exposes the password with double quotes. The error message of the signing task is "Missing input APK" supposedly because the command line parameter parsing was terminated early because of the wrongly encoded double quotes.

`apksigner.bat sign --ks D:\a\_temp\redacted.keystore --ks-pass "pass:xxx%xxx""xxx" --ks-key-alias .....`
Note the difference in the password mentioned above and the console output.

Behavior 2:
The password contains a cirumflex and looks like this `xxxxxx#^xxx`. In this case the signing fails with a wrong password message but does not expose the passwort and shows *** instead as expected. I attempted to expose this password with a echo command and it works but the circumflex is ommited in the output `xxxxxx#xxx`. The two working pipelines do not print any portion of the passwords with an echo but print *** instead, which is the normal behavior.

When using the exact same pipeline with a ubuntu-22.04 or macOS-latest image works as expected.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20231217.2.0

### Is it regression?

unknown

### Expected behavior

Secrets with symbols like " and ^ are processed properly.

### Actual behavior

The secrets break the pipeline and even expose the secrets in certain scenarios.

### Repro steps

- Store secret values in azure keyvault
- Build an android app
- Try to sign the app with passwords containing the mentioned special characters
- Try to print the passwords with echo

**Comment by Alexey-Ayupov** [comment]
Hello @eberthold, we will check the image behavior, however the problem itself can be on the `AndroidSigning@3` task side or even action engine.

**Comment by eberthold** [comment]
Hi, what lead me to the conclusion that it is not a bug of the `AndroidSinging@3` task is that even an added `- script: echo $({{ secret }})` misbehaves when those special characters are present.

When they aren't present the password gets displayed - but with slightly different encoding problems, whereas `***` is printed for passwords which do not contain those chars.

If it's not in the image itself I would rather point to the `AzureKeyVault@2` tasks which would have a bug in the importing routine.

**Comment by erik-bershel** [comment]
Hey @eberthold! We are not operating secrets or related to operating secrets components on images side. It might be an issue for AzDO agent itself or one of the underlying tasks too. If one of those had issues with images components they could contact us, but the same time we cannot investigate what's going on from our side.
You may report it also [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent) and [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks). I believe that one of those teams could help you solve this issue.
