### ISSUE TITLE
Install-DACFx.ps1 fails due to wrong file signature

### ISSUE THREAD

**Issue by achechen** [actions/runner-images#9142]
### Description

Looks like the file at https://aka.ms/dacfx-msi has been updated and now has a different signature than the one hard coded in the script.
Downloaded file's signature:
![image](https://github.com/actions/runner-images/assets/10340542/8935425a-07b4-4dc0-9297-aff0bd33e704)

Signature from the script:
![image](https://github.com/actions/runner-images/assets/10340542/e6853ab4-b86b-4102-b19b-1744de9b733f)

Are you sure it is a good idea to use signatures this way? I notice you are having a lot of issues with signatures lately.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest version

### Is it regression?

no

### Expected behavior

file signature check should not fail

### Actual behavior

file signature check fails

### Repro steps

see above

**Comment by sergei-pyshnoi** [comment]
Hello @achechen. Thanks for your report, PR with fix is ready. Will merge it as soon as possible.

**Comment by mikhailkoliada** [comment]
fixed, please sync your main branch
