### ISSUE TITLE
 ubuntu22/20240107.1 produces bad error for `sudo path/to/nonexistent`

### ISSUE THREAD

**Issue by jrose-signal** [actions/runner-images#9146]
### Description

One of our private CI bots has a step

```
    - name: Install NDK
      run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
```

that runs on `ubuntu-latest`. Within the last week, jobs have started failing with

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

In checking the jobs that succeeded vs the jobs that failed, the ones that failed are on 20240107.1.0, while the ones that passed were still using the December tag. I eventually realized this is related to the Android tools pruning, but the error message did not make that clear at all.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240107.1.0

### Is it regression?

Unknown

### Expected behavior

A reasonable error message from passwordless sudo, as documented at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#administrative-privileges

### Actual behavior

`sudo: a password is required`

### Repro steps

Run a nonexistent command with `sudo`, no default shell specified, on ubuntu22/20240107.1.

**Comment by jrose-signal** [comment]
I'm not sure why this is *only* affecting the NDK install. `sudo apt-get update` is still working on other bots.

**Comment by jrose-signal** [comment]
…Presumably this is related to https://github.com/actions/runner-images/issues/8952, with the path I included no longer existing. But I don't understand why the error message would come back about entering a password rather than specifying that it can't find the command in question.

**Comment by mikepenz** [comment]
We are seeing the same problem. With a very similar step:

```
echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "build-tools;32.0.0" --sdk_root=${ANDROID_SDK_ROOT}
```

It worked still with `Version: 20231217.2.0` but is now broken with the latest version `20240107.1` of the Ubuntu GitHub actions runner.

**Comment by jrose-signal** [comment]
(by the way, we fixed our `sdkmanager` invocation to `${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager`, which should work across several versions)

**Comment by Alexey-Ayupov** [comment]
Hello @jrose-signal, according to the PR #9094, the obsolete package [sdk tools](https://developer.android.com/tools/releases/sdk-tools) no longer available.
The proper sdkmanager, indeed, located in `${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager` or full path `/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager`.

Do you still have an issue with the password prompt?

**Comment by mikepenz** [comment]
@Alexey-Ayupov I believe we are seeing the same issue with the latest version however we already use the full path. The exact same code was working in the prior version:

```
Run echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "build-tools;34.0.0" --sdk_root=${ANDROID_SDK_ROOT}
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

In case you believe it is a different problem, I am more than happy to create a separate issue for it. Thank you.
