### ISSUE TITLE
Refer #9118. Issue was closed but not fixed.

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#9152]
### Description

Refer #9118. Issue was closed but not fixed.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022

### Image version and build link

Image 20240108.1.0

### Is it regression?

NA

### Expected behavior

Build image for agent

### Actual behavior

==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:

### Repro steps

rerun pipeline.

**Comment by Alexey-Ayupov** [comment]
Hello @jaswant-dnv, we are also using Azure DevOps and ubuntu as a runner - https://github.visualstudio.com/runner-images/_build/results?buildId=134524&view=results. We do not face this issue, please check your repository/pipeline one more time.

**Comment by erik-bershel** [comment]
Hey @jaswant-dnv! Just to be sure. Don't use release labels or branches when building - we are not support it due to repository structure. Build from the `main` branch only, please. It seems that you build using stale version of code.

**Comment by mikhailkoliada** [comment]
Hello! As @erik-bershel and @Alexey-Ayupov mentioned please always build your images from `main` and please make sure that you run `git pull` before running any packer builds, ll the builds are fixed by now.
