### ISSUE TITLE
choco install visualstudio2022buildtools fails

### ISSUE THREAD

**Issue by MattGalton** [actions/runner-images#9154]
### Description

Hello,

I am trying to install some packages from visualstudio2022buildtools and have recently started getting some errors. This was not an issue around a week ago. I was hoping to ask if anyone has come across the same issue and knows a fix.

I am trying to run

```
 choco install visualstudio2022community -y 
--params "
    --remove Microsoft.VisualStudio.Product.BuildTools
    --add Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64
    --add Microsoft.VisualStudio.Component.VC.CMake.Project
    --add Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL
    --add Microsoft.VisualStudio.Component.Windows10SDK.20348
"
```

Installation continues as normal up to this first warning

```
Visual Studio Installer has been installed.
WARNING: The Visual Studio Installer got updated to version 3.8.2112.61926, which is still lower than the requirement of version 3.8.2122.37638 or later.
WARNING: The Visual Studio Installer engine got updated to version 3.8.2112.61926, which is still lower than the requirement of version 3.8.2122.37638 or later.
Downloading visualstudio2022community 
  from 'https://download.visualstudio.microsoft.com/download/pr/63b5064f-af60-4cbe-96cd-a9dd9d41ee3d/51d8dc03605a4fa11d445795cb1cc7ea1a518b0b0ce466cdaa805fc6029d7058/vs_Community.exe'
```

Then, I get the following error

```
Download of vs_Community.exe (3.77 MB) completed.
Hashes match.
Installing visualstudio2022community..


WARNING: Errors/warnings from the Visual Studio Installer log file C:\Users\runneradmin\AppData\Local\Temp\chocolatey\dd_installer_20240111163844.log:
WARNING: [1230:000e][2024-01-11T16:39:42] Warning: No previous catalog found at 'C:\ProgramData\Microsoft\VisualStudio\Packages\_Instances\583afe9f\catalog.previous.json'
WARNING: [1230:000e][2024-01-11T16:39:42] Warning: Didn't find any channel feed.
WARNING: [1230:0004][2024-01-11T16:39:44] Warning: https://download.visualstudio.microsoft.com/download/pr/78eb9d79-decd-4704-adc0-78dba2473667/5e3ba6f516d2b77f164b31dc8ec57be10ca1420f9ec2889fb4bba8be9f28c8f7/vs_Setup.exe
WARNING: [1230:0004][2024-01-11T16:39:44] Error 0x80131500: Failed to load the details page
WARNING: [1230:0004][2024-01-11T16:39:44] Warning: Shutting down the application with exit code 1
WARNING: [1230:0001][2024-01-11T16:39:45] Warning: Didn't find any channel feed.
WARNING: [1230:0001][2024-01-11T16:39:45] Warning: Didn't find any channel feed.
ERROR: The installation of visualstudio2022community failed (installer exit code: 1).
The install of visualstudio2022community was NOT successful.

Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2022community\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 4/5 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Installed:
 - chocolatey-dotnetfx.extension v1.0.1
 - chocolatey-visualstudio.extension v1.11.1
 - dotnetfx v4.8.0.20220524
 - visualstudio-installer v2.0.3

Failures
 - visualstudio2022community (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2022community\tools\ChocolateyInstall.ps1'.
```

This does not happen for me locally, and I get the same error when attempting to install choco package `visualstudio2022buildtools`, too.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Runner Image
  Image: windows-2022
  Version: 20240108.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240108.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240108.1
```

### Is it regression?

Yes. 20231217.2.0

### Expected behavior

choco installs visualstudio2022community, visualstudio2022buildtools and friends successfully

### Actual behavior

choco does not install visualstudio2022community or visualstudio2022buildtools successfully

### Repro steps

Try to install package `visualstudio2022buildtools` using choco:

```
steps:
      - name: Install Dependencies
        env:
          VS_INSTALLER_VERSION: '117.8.2.0'
          VS_INSTALLER_PARAMS: >-
            --remove Microsoft.VisualStudio.Product.BuildTools
            --add Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64
            --add Microsoft.VisualStudio.Component.VC.CMake.Project
            --add Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL
            --add Microsoft.VisualStudio.Component.Windows10SDK.20348
        run: |
          choco install visualstudio2022buildtools --version ${{env.VS_INSTALLER_VERSION}} --params "${{env.VS_INSTALLER_PARAMS}}" -y
```

I have tried using the latest `VS_INSTALLER_VERSION` to no avail.

**Comment by mikhailkoliada** [comment]
Hello! This error is connected with choco and its packages itself, while this repository contains the issues about runner-images usage, please report your concerns directly to choco package maintainer at https://github.com/jberezanski/ChocolateyPackages

**Comment by MattGalton** [comment]
Thanks for the quick feedback. I had assumed it was a gh runner issue since I managed to install locally fine. I will get in touch with the choco package gang directly. Cheers!

**Comment by MattGalton** [comment]
Your link was super helpful @mikhailkoliada, thanks!

In case anyone else stumbles across this and has the same issue:

# Workaround

- `choco install visualstudio2022buildtools` and friends is not completely independent of the environment that you install it in.
- VS 2022 Enterprise begin installed on the `windows-2022` image is borking the installation of the choco package (See https://github.com/jberezanski/ChocolateyPackages/issues/97#issuecomment-798688284). 
- Do a `choco upgrade visualstudio2022enterprise` before trying your install.
