### ISSUE TITLE
apt-get errors

### ISSUE THREAD

**Issue by gerritlansing** [actions/runner-images#9157]
### Description

apt-get errors out when trying to install packages on latest version of 'ubuntu-22.04' image. Worked in prior versions.

```
> sudo apt-get update
Reading package lists...
E: Method https has died unexpectedly!
E: Sub-process https received signal 9.
E: Method http has died unexpectedly!
E: Sub-process http received signal 9.
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240107.1.0

### Is it regression?

20231217.2.0

### Expected behavior

apt-get runs successfully

### Actual behavior

apt-get fails with fatal errors

### Repro steps

1. Add a pipeline step with:
```
- pwsh: |
     sudo apt-get update
```
2. Run pipeline

**Comment by sergei-pyshnoi** [comment]
Hello @gerritlansing . Unfortunately we cannot reproduce your error. Is problem still persist? Can you provide link to failed runs if yes?

**Comment by gerritlansing** [comment]
Hi @sergei-pyshnoi, yes, I just ran the pipeline again and the same failure still occurs. Unfortunately the pipeline is in a private repo. I could do a Zoom and share my screen with you if desired.

**Comment by sergei-pyshnoi** [comment]
@gerritlansing  It will be better if you provide more detailed reprosteps (it can be public repo with pipeline example or code snippet). Possible problem can be in steps before `sudo apt-get update` execution. Here is my action workflow that finished without errors (on azure devops same result) https://github.com/sergei-pyshnoi/workflow-test/actions/runs/7526097747/job/20496702708

**Comment by gerritlansing** [comment]
@sergei-pyshnoi Apologies, our error. We had a security tool blocking the connection and not reporting it.
