### ISSUE TITLE
Vagrant was deleted from macos-13 image

### ISSUE THREAD

**Issue by pedrofurtado** [actions/runner-images#9158]
### Description

Vagrant was deleted from macos-13 image. Is it possible to add to it?

It is present in macos-12 image.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image macos-13

### Is it regression?

yes

### Expected behavior

To have vagrant in macos13 image

### Actual behavior

There is no vagrant installed

### Repro steps

Run a CI with macos-13 and run "vagrant --version"

**Comment by pedrofurtado** [comment]
The PR that deleted vagrant: https://github.com/actions/runner-images/pull/8375

**Comment by mikhailkoliada** [comment]
Hello! Vagrant does not run properly on our modern macOS virtualisation so we are unable to restore it and do not plan doing it in the foreseeable future, unfortunately.
