### ISSUE TITLE
Install updated MSBuild version

### ISSUE THREAD

**Issue by SnapADrag0n** [actions/runner-images#9160]
### Description

On the latest stable macOS agent (macos-12), installed MSBuild version is [16.10](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#language-and-runtime) while .NET 6 builds need atleast MSBuild version [17.0](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle) to build. Build for Xamarin iOS app based on .NET 6 fails due to this.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240105.3

### Is it regression?

No

### Expected behavior

Latest MSBuild version should be available which can build .NET6+ applications.

### Actual behavior

Old MSBuild version is present, so .NET6 application build is failing.

### Repro steps

1. Create a Xamarin mobile app based on .NET 6
2. Setup YAML pipeline with Microsoft hosted agent "macos-latest"
3. Run the pipeline

**Comment by mikhailkoliada** [comment]
`msbuild` is a mono's implementation of msbuild, if you want to run a dotnet's implementation of msbuild you should run `dotnet msbuild` (it is the 17.x branch)
