### ISSUE TITLE
Update Ubuntu 22.04 to Node.JS >=20.8.1

### ISSUE THREAD

**Issue by martincaisley** [actions/runner-images#9163]
### Tool name

Node.JS

### Tool license

MIT License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

>=20.8.1

### Brief description of tool

The semantic release plugin (https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0) has recently dropped support for Node.JS version 18. Meaning the latest version of semantic release is incompatible with this version of ubuntu.

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello, please use the `UseNode@1` task to set up your node environment and not the on-host default node, it has the version you need. 
<img width="830" alt="image" src="https://github.com/actions/runner-images/assets/88318005/eb944594-426b-4260-bccc-1fee6f4c2f2e">

**Comment by martincaisley** [comment]
That worked. Thanks for the reply 👍
