### ISSUE TITLE
macos-13 image has the wrong xcodebuild version

### ISSUE THREAD

**Issue by kstoletniy** [actions/runner-images#9164]
### Description

A few weeks ago, the workflow utilizing the macOS-13 runner unexpectedly began to fail. Prior to this, the workflow was functioning correctly, and no modifications were made to the workflow file. The failure stemmed from the fact that the Swift tool version was outdated compared to the one utilized in my project's packages. In my local project, I employ Xcode 15.2, so I specified '15.2-beta' in the workflow.

After an extensive investigation into the potential cause of the issue, I discovered that xcodebuild was pointing to version 14.3.1, leading to the problems encountered.

Three weeks ago, everything was functioning smoothly, and both the Xcode version and xcodebuild matched seamlessly. It appears that an issue was introduced recently, causing the discrepancy.

I urgently request assistance in resolving this matter as it is impeding all of my workflows.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240106.8
Included Software: https://github.com/actions/runner-images/blob/macos-13/20240106.8/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240[10](https://github.com/drivecaramel/caramel-ios/actions/runs/7504457311/job/20431533689#step:1:11)6.8

### Is it regression?

N/A

### Expected behavior

The xcode version and xcodebuild version should match always. i.e.

<img width="1057" alt="Screenshot 2024-01-15 at 10 31 58" src="https://github.com/actions/runner-images/assets/79856619/07223b11-2b65-449a-9973-1680778f5776">

### Actual behavior

The xcode version and xcodebuild version are not matching versions.
<img width="1057" alt="Screenshot 2024-01-15 at 10 26 32" src="https://github.com/actions/runner-images/assets/79856619/f2b87d7d-89a2-44b1-bb92-e1fc78783e8d">

### Repro steps

Start building a Swift project using xcode 15 or higher with the last image macos-13

**Comment by mikhailkoliada** [comment]
I am unable to reproduce the issue

<img width="1062" alt="image" src="https://github.com/actions/runner-images/assets/88318005/ed7d4451-725e-43f5-8d98-242ab72f01e6">

Please report to the https://github.com/maxim-lobanov/setup-xcode directly,  technically this bug is impossible from the images side because xcodebuild versions are managed natively by the `Xcode-select calls`
