### ISSUE TITLE
mac-os 13 runner need intermediates certificates update

### ISSUE THREAD

**Issue by clementmorissard** [actions/runner-images#9167]
### Description

I'm using fastlane to build my apps with github actions 

I think the macos-13 runner need an update for the intermediates apple certificates because i didnt change anything and my builds started to fail 3 months ago, around the expire day of the WWDRCAG7 certificate

I have this error:
`Error: Revoke certificate: Your account already has an Apple Development signing certificate for this machine, but its private key is not installed in your keychain. Xcode can create a new one after revoking your existing certificate.`

I saw people solved it locally before with installing the new WWDR certificates (AppleWWDRCAG8) but i cant find a way to fixed it, i tried this but it didnt worked:

`- name: install intermediates certificates
        run: wget https://www.apple.com/certificateauthority/AppleWWDRCAG8.cer && sudo
          security add-trusted-cert -d -r unspecified -k`

The previous certificates expired in november:
[Worldwide Developer Relations - G7 (Expiring 11/17/2023 20:40:52 UTC)](https://www.apple.com/certificateauthority/AppleWWDRCAG7.cer)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

runner: macos-13
https://github.com/Rythme-Tech/rythme-ios/actions/runs/7530996744

### Is it regression?

no

### Expected behavior

Should not fail to build testflight build

### Actual behavior

It failed with this error:

Revoke certificate: Your account already has an Apple Development signing certificate for this machine, but its private key is not installed in your keychain. Xcode can create a new one after revoking your existing certificate.

### Repro steps

.

**Comment by mikhailkoliada** [comment]
Hey! We do not install WWDRCAG7 in runner, only WWDRCAG3 which expires somewhere in 2030, where is this cert coming from in your builds, might be we missed something?

**Comment by clementmorissard** [comment]
Oh okay so the issue might be on fastlane side then i'll try to search more 
i'm not downloading manually the certificates i just give the credentials to fastlane

`- name: Setup Env
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FIREBASE_AUTH_KEY: ${{ secrets.FIREBASE_AUTH_KEY }}
          APPSTORE_PRIVATE_KEY_64: ${{ secrets.APPSTORE_PRIVATE_KEY_64 }}
        run: |
          echo $APPSTORE_PRIVATE_KEY_64 | base64 --decode > AuthKey.p8
          echo $FIREBASE_AUTH_KEY > Firebase.json
          echo FASTLANE_PASSWORD=$FASTLANE_PASSWORD >> $GITHUB_ENV
          echo FASTLANE_USER=$FASTLANE_USER >> $GITHUB_ENV`

**Comment by mikhailkoliada** [comment]
@clementmorissard fastlane fetches G1-G6 and not G7, we only install G3, what's landing into your keychain on fastlane execution?

**Comment by clementmorissard** [comment]
Found the issue. It's not on the runner issues fault.
Fastlane is recreating a new certificate everytime i build for appstore, and when i reach the certificates limit, i get the error saying i need to revoke certificate :/
I'll try to see if i can change the way i use fastlane then
thanks !
