### ISSUE TITLE
Ubuntu 22.04 Bug related to Docker Compose 2.24 breaking builds

### ISSUE THREAD

**Issue by rodolfovilaca** [actions/runner-images#9172]
### Description

Not sure if this is a proper bug to file here but there's a known [regression bug](https://github.com/docker/compose/issues/11343) with docker compose `2.24` That breaks builds when having multiple extensions. This is currently breaking our pipelines that have more complex compose builds extensions. Most likely this is also breaking for other people.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Ubuntu 22.04](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240114.1) that has Docker Compose version 2.24

### Is it regression?

yes

### Expected behavior

To not break when building from building compose files that have extensions.

### Actual behavior

Breaking with:

```
Circular reference:
  service-a in docker-compose.yaml
  extends service-b  in docker-compose.shared.yaml
  extends service-c  in docker-compose.shared.yaml
  extends service-d  in docker-compose.yaml
  extends service-a  in docker-compose.shared.yaml
Error: Process completed with exit code 15.
```

### Repro steps

Have a docker compose build with extension files.

**Comment by pdonorio** [comment]
This is affecting also `20.04` 
https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240114.1

Question: is there a way to install/switch/use an older version of compose inside the workflow as a workaround?

**Comment by sergei-pyshnoi** [comment]
Hello @rodolfovilaca . Thanks for your report. We currently working on solution.

**Comment by JCenatus** [comment]
> This is affecting also `20.04` https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240114.1
> 
> Question: is there a way to install/switch/use an older version of compose inside the workflow as a workaround?

You can create a job like that :

      - name: Downgrade Compose plugin (Docker) version
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

**Comment by kasperg** [comment]
[The `202401014` releases are not/no longer listed](https://github.com/actions/runner-images/releases). Have they been pulled back?

**Comment by mikhailkoliada** [comment]
Should be fixed now with the image version from Jan 16th, thanks for the early report of the problem!

**Comment by julienfalque** [comment]
I think upstream issue has been fixed in latest Docker Compose releases. Is it possible to unpin the installed version? v2.23.3 does not support `!override` flag
