### ISSUE TITLE
Windows 2022 and Ubuntu 22.04 build failing due to IMAGE_STATE_UNDEPLOYABLE and Java 17 Temurin fetch failure respectively

### ISSUE THREAD

**Issue by DevOpsAzurance** [actions/runner-images#9176]
### Description

![image](https://github.com/actions/runner-images/assets/7709919/5b7f83fb-981c-4891-97f4-9c3a66f340eb)

When running against a VS Subscription, it works fine, but when run against a productionized subscription in my organization, I get the above failures.  We have Defender and Sentinel running, so wondering if they are causing conflict on these servers.  Since these are temporary resources, inquiring with my security teams, if that could be disable for these servers only.  I run them via Pipelines in ADO.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images

Using the image built in VS subscription to run my self-hosted runner.

### Is it regression?

Not applicable

### Expected behavior

Windows build runs in 6-7 hrs
Linux build runs in 2-3 hrs

### Actual behavior

Windows build fails, or is cancelled, looping with IMAGE_STATE_UNDEPLOYABLE

and

Linux build fails, with failed Temurin 17 test failure, due to not being able to fetch the package from adoptium.

### Repro steps

This is ADO pipeline driven, kicking off the Packer build from the hcl config in the runner-images repo.

Using a prexisting Resource group and keyvault as part of the build and outputting to a compute gallery.

**Comment by sergei-pyshnoi** [comment]
Hello @DevOpsAzurance . Unfortunately нhere's not much we can suggest here.  You can visit [this discussion](https://github.com/actions/runner-images/discussions/6251) to refer `image state undeployed` . About fetching temurin repo, time to time we expect the same issue (not often), but retries helping with this. I am closing this issue, but if you have additional question - feel free to ask.

**Comment by andreasschild** [comment]
Hi. I triggered the image creation by calling the [GenerateResourcesAndImage PS file](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1) and had the same issue. I solved it by adding a tag to disable the MS Defender for Cloud Extension. Please talk to your security team when doing this change.


```ps1
.\virtual-environments\helpers\GenerateResourcesAndImage.ps1
Import-Module .\virtual-environments\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage `
    -SubscriptionId "<subid>"  `
    -ResourceGroupName "<rgroupname>"  `
    -ImageGenerationRepositoryRoot "$($PSScriptRoot)\<runner-images>"  `
    -ImageType Windows2022  `
    -AzureLocation "<location>"  `
    -AzureClientId "<clientid>" `
    -AzureClientSecret "<clientsecret>" `
    -AzureTenantId "<tenantid>" `
    -RestrictToAgentIpAddress $False `
    **-Tags @{"ExcludeMdeAutoProvisioning" = "True"}**
```
