### ISSUE TITLE
Ubuntu 20.04 - System.Tests.ps1 fails on Azure DevOps

### ISSUE THREAD

**Issue by bmv0161** [actions/runner-images#9182]
### Description

Recently, Our Ubuntu 20.04 image generation is failing the at the test "Image has more than 31GB free space". 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/tree/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu

### Is it regression?

Yes, likely introduced here: https://github.com/actions/runner-images/pull/9109

### Expected behavior

Successful image generation.

### Actual behavior

Pipeline errors out due to [System.Test.ps1](https://github.com/actions/runner-images/blob/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu/scripts/tests/System.Tests.ps1). Based on [this PR](https://github.com/actions/runner-images/pull/9153), we would expect this test to be skipped. We are running the image generation on a self-hosted Azure Devops agent, using an older version of the Ubuntu 20.04 image. 

We have validated that $env:AGENT_NAME is set prior to the packer build step on the Agent, however the test continues to fail.

    azure-arm.build_image: Running tests from '/imagegeneration/tests/System.Tests.ps1'
    azure-arm.build_image: Describing Disk free space
    azure-arm.build_image:   [-] Image has more than 31GB free space 34ms (33ms|2ms)
    azure-arm.build_image:    Expected the actual value to be greater than or equal to 33285996544, but got 31900524544.
    azure-arm.build_image:    at $freeSpace | Should -BeGreaterOrEqual 31GB, /imagegeneration/tests/System.Tests.ps1:6
    azure-arm.build_image:    at <ScriptBlock>, /imagegeneration/tests/System.Tests.ps1:6

### Repro steps

Packer build ./ubuntu-20.04.pkr.hcl

**Comment by mikhailkoliada** [comment]
Hey! This test is written to catch exactly what written in the title - that the resulting vm has more than 31gb of free space, if you do not need / want to check the free space you may disable or remove the test as it is unlikely needed for private needs. If you have questions feel free to reach us out again.

**Comment by bmv0161** [comment]
@mikhailkoliada As stated in this PR, https://github.com/actions/runner-images/pull/9153, the test should be skipped as we are running the image generation on an Azure DevOps Agent. However, the test is not being skipped as expected. 

Would it be recommended to pass a different value for [vm_size:Standard_D4s_v4](https://github.com/actions/runner-images/blob/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu/templates/ubuntu-20.04.pkr.hcl#L143C16-L143C16) to allow for more free space?

**Comment by bmv0161** [comment]
@mikhailkoliada Can we have a feature request to parameterize this value in the template? [os_disk_size_gb: 86](https://github.com/actions/runner-images/blob/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu/templates/ubuntu-20.04.pkr.hcl#L158C25-L158C25)

**Comment by mikhailkoliada** [comment]
@bmv0161 not really,  you run the _buld_ script in azure DevOps environment, but the machine that packer creates once the script is launched does not know anything about the place you run the script from (azure DevOps in your case) packer create a brand new machine from the Azure's marketplace
