### ISSUE TITLE
Repository readme deployment status images are broken

### ISSUE THREAD

**Issue by ErisApps** [actions/runner-images#9184]
### Description

The README's badges for the "Rollout Progress of Latest Image Release" all seem to be broken as they report the status unknown. This seems to be caused by the underlying API no longer reporting the machine counts for each image version.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not applicable

### Is it regression?

Not applicable

### Expected behavior

The badges work and show the rollout progress for the latest version.

### Actual behavior

The badges don't work and report the status "unknown".

### Repro steps

Not applicable

**Comment by sergei-pyshnoi** [comment]
Hello @ErisApps . Thanks for report, we will take a look

**Comment by sergei-pyshnoi** [comment]
We know about this problem. We will remove (or replace) badges with upcoming PR.

**Comment by jeroen** [comment]
Is there some way to see the currently deployed date/version of the images? (that used to be in the badge).

**Comment by HenrikSommer-Energinet** [comment]
@sergei-pyshnoi any eta on that PR?
or place where I can check i manual?

**Comment by erikng** [comment]
Why close the issue before it's resolved? This really makes it difficult to understand the rollout status.
