### ISSUE TITLE
Missing role out status.

### ISSUE THREAD

**Issue by HenrikSommer-Energinet** [actions/runner-images#9190]
### Description

You have started rollout of [20240116](https://github.com/actions/runner-images/releases/tag/win22%2F20240116.1)
But the rollout status is unknow here: https://github.com/actions/runner-images/tree/main?tab=readme-ov-file#available-images

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240116.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20240116.1/images/windows/Windows2022-Readme.md

### Is it regression?

.

### Expected behavior

I can see status of roll out.

### Actual behavior

Status is unknow

### Repro steps

1. Click on the link: https://github.com/actions/runner-images/tree/main?tab=readme-ov-file#available-images

**Comment by sergei-pyshnoi** [comment]
duplicate https://github.com/actions/runner-images/issues/9184
