### ISSUE TITLE
Ubuntu 20.04 - feature request - parameterize os_disk_size_gb

### ISSUE THREAD

**Issue by bmv0161** [actions/runner-images#9193]
### Description

Recently, Our Ubuntu 20.04 image generation is failing the at the test "Image has more than 31GB free space". We have had success resolving the issue by increasing the value for [os_disk_size_gb](https://github.com/actions/runner-images/blob/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu/templates/ubuntu-20.04.pkr.hcl#L158C25-L158C25). 

We would like a feature request to be able to pass a different value for os_disk_size_gb to the template through a Packer variable.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/tree/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu

### Is it regression?

Yes, likely introduced here: https://github.com/actions/runner-images/pull/9109

### Expected behavior

Successful image generation.

### Actual behavior

Pipeline errors out due to [System.Test.ps1](https://github.com/actions/runner-images/blob/f046bcaec35305f006ce3cb6fdebb161d0ea5577/images/ubuntu/scripts/tests/System.Tests.ps1). Based on [this PR](https://github.com/actions/runner-images/pull/9153), we would expect this test to be skipped. We are running the image generation on a self-hosted Azure Devops agent, using an older version of the Ubuntu 20.04 image. 

We have validated that $env:AGENT_NAME is set on the DevOps agent prior to the packer build step on the Agent, however this is not passed to the Packer build VM.

    azure-arm.build_image: Running tests from '/imagegeneration/tests/System.Tests.ps1'
    azure-arm.build_image: Describing Disk free space
    azure-arm.build_image:   [-] Image has more than 31GB free space 34ms (33ms|2ms)
    azure-arm.build_image:    Expected the actual value to be greater than or equal to 33285996544, but got 31900524544.
    azure-arm.build_image:    at $freeSpace | Should -BeGreaterOrEqual 31GB, /imagegeneration/tests/System.Tests.ps1:6
    azure-arm.build_image:    at <ScriptBlock>, /imagegeneration/tests/System.Tests.ps1:6

### Repro steps

Packer build ./ubuntu-20.04.pkr.hcl

**Comment by sergei-pyshnoi** [comment]
Hello @bmv0161 . For now we do not have plans for adding additional parameters to packer template. You can disable `Disk free space` test or increase disk size (as you already did) . I am closing this issue for now but if you have additional questions feel free to ask.

**Comment by jappenzesr** [comment]
We also need to change this value as we are using a more modern SKU  (D2d_v5)  with smaller (ephemeral) disk. We are working around substituting the value suing sed. Making it a parameter would be useful.
