### ISSUE TITLE
Signatures don't match for VS Installation causing script to fail | windows 2022

### ISSUE THREAD

**Issue by m-soltani** [actions/runner-images#9197]
### Description

The installation script for Visual Studio, located at `windows\scripts\build\Install-VisualStudio.ps1`, is designed for Windows 2022. This script anticipates a specific signature that doesn't align with the one provided by `toolset-2022.json` located at `windows\toolsets\toolset-2022.json`. This mismatch in signatures causes the script to fail.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

[20240108](https://github.com/actions/runner-images/releases/tag/win22%2F20240108.1)

### Is it regression?

Not Sure

### Expected behavior

Signatures match.

### Actual behavior

Signatures mismatch between installation script and toolset provided input parameter causes the script to fail

### Repro steps

1. Try to generate a windows 2022 new image based off the main branch

**Comment by sergei-pyshnoi** [comment]
Hello @m-soltani . Unfortunately we cannot reproduce your issue. We have update VS signature recently (this week). Please make sure that you use latest commit from `main` branch.

**Comment by m-soltani** [comment]
thanks for the reminder. In fact using latest commit from the `main` branch did solve the problem

**Comment by ihari277** [comment]
Just now, the signatures got updated. Please try now; it will work. @m-soltani

**Comment by m-soltani** [comment]
Yes, no issues so far.
