### ISSUE TITLE
Unable to start emulator on macos-12 image in azure devops

### ISSUE THREAD

**Issue by rkolipaka-98** [actions/runner-images#9199]
### Description

Hi, we are running espresso tests on macos-12 VM, and we see that the emulator screen is blank at times.
We have followed the steps mentioned in this issue https://github.com/actions/runner-images/issues/6369

That issue mostly talks about using API 27 but we want atleast API 30 and we did try installing intel haxm driver that also did not resolve the issue.

This is our yml file task.

```
    - bash: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-31;google_apis;x86_64'
      displayName: 'Download and install emulator image'
    - bash: |
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n android_emulator -k 'system-images;android-31;google_apis;x86_64' -d 17 --force --device "pixel_6"
        echo "Emulator created successfully"
        nohup $ANDROID_HOME/emulator/emulator -memory 4096 -avd android_emulator -skin 1080x2400 -no-snapshot -netdelay none -netspeed full -no-audio -no-boot-anim -accel auto -gpu auto -qemu -lcd-density 420 > /dev/null 2>&1 &
        
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done'
        $ANDROID_HOME/platform-tools/adb devices
        $ANDROID_HOME/platform-tools/adb shell input keyevent 82
        $ANDROID_HOME/platform-tools/adb shell settings put global window_animation_scale 0
        $ANDROID_HOME/platform-tools/adb shell settings put global transition_animation_scale 0
        $ANDROID_HOME/platform-tools/adb shell settings put global animator_duration_scale 0
      displayName: 'Create and start emulator'
```

This is the screenshot from the VM

![VM_After_Build](https://github.com/actions/runner-images/assets/111806534/0bf47c46-06fb-46fc-a983-4238c6e31c74)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-12
Version: 20240105.3

### Is it regression?

Yes

### Expected behavior

Emulator should start

### Actual behavior

Emulator screen is blank

### Repro steps

It is intermittent but was able to repro it with the configuration we had for starting the emulator.

**Comment by rkolipaka-98** [comment]
Hi @shamil-mubarakshin, here are the links,

Test's failed due to emulator being blank - https://office.visualstudio.com/ISS/_build/results?buildId=25522365&view=results

Test's started but emulator screen is grayed - https://office.visualstudio.com/ISS/_build/results?buildId=25580106&view=logs&j=2aae03dc-ec11-5a59-196b-bc84a737f091

**Comment by rkolipaka-98** [comment]
Hi @shamil-mubarakshin, any updates on this. Appreciate your help. Thank you.

**Comment by shamil-mubarakshin** [comment]
@rkolipaka-98, apart from some emulator startups being slow due to hardware restrictions and performance which we can't do much about, I found using `$ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png` command for screen capture yielding results more consistent, rather than `screencapture` on macos-12. E.g. [runs](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/7710334774) using Actions (same applies for Azure DevOps).

```
- bash: |
    echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-31;google_apis;x86_64'
    echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n android_emulator -k 'system-images;android-31;google_apis;x86_64' --force --device "pixel_6"
    echo "Emulator created successfully"
    nohup $ANDROID_HOME/emulator/emulator -memory 2048 -avd android_emulator -skin 1080x1920 -no-snapshot -netdelay none -netspeed full -no-audio -no-boot-anim -accel auto -gpu guest -qemu -lcd-density 420 > /dev/null 2>&1 &
    $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done'
    $ANDROID_HOME/platform-tools/adb devices

    sleep 60
    screencapture emulator.jpg
    $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png
  timeoutInMinutes: 15
  displayName: Create Android emulator
```

**Comment by shamil-mubarakshin** [comment]
@rkolipaka-98, Hope the alternative for screen capture fits your needs. There are certain limitations when it comes to nested virtualization, which is also comes as a warning when using android emulators. Let us know in case of further concerns
