### ISSUE TITLE
macos-13-xlarge is randomly picking different images (one containing Xcode 15.2 and one without it)

### ISSUE THREAD

**Issue by grzegorzkrukowski** [actions/runner-images#9200]
### Description

We are using `runs-on: macos-13-xlarge` and we expect to have Xcode 15.2 there (the [Xcode 15.2 PR](https://github.com/actions/runner-images/pull/9169) is merged and deployed).

Unfortunately, the runner images are picked randomly between runs:
```
Image: macos-13-arm64
  Version: 20240114.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-13/20240114.1/images/macos/macos-13-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20240114.1
```

and 

```
Image: macos-13-arm64
  Version: 20240107.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-13/20240107.1/images/macos/macos-13-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20240[10]
```

The expected one is `20240114.1` which contains a required Xcode version 15.2, but it often happens we get the older one `20240107.1` which is making our CI failing.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240107.1
Version: 20240114.1

### Is it regression?

yes

### Expected behavior

Run action always on 20240114.1

### Actual behavior

It randomly runs on 20240107.1 and 20240114.1

### Repro steps

Make a workflow to run on macos-13-arm64 and run it several times. See how it randomly runs on different image versions

**Comment by erik-bershel** [comment]
Hey @grzegorzkrukowski!
macOS-13-arm64 is not fully deployed yet. So it's kinda expected behaviour. See [PR](https://github.com/actions/runner-images/pull/9170) and the [release](https://github.com/actions/runner-images/releases/tag/macos-13-arm64%2F20240114.1). Also you can just keep an eye on this issue https://github.com/actions/runner-images/issues/9139. We'll let here know users when all the images deployed.
