### ISSUE TITLE
Add visionOS simulator to Intel-based runners

### ISSUE THREAD

**Issue by vfilyakov** [actions/runner-images#9209]
### Tool name

visionOS simulator

### Tool license

?

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.0

### Brief description of tool

Now that GitHub Action runners come with Xcode 15.2 and visionOS SDK, we could start using GitHub Actions for full visionOS builds. However, when runner is on Intel silicon, the visionOS simulator is not installed and this prevents us from using Xcode for builds limiting what we can build for visionOS on GitHub Action (no tests or apps).

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
There is an existing workaround:
https://github.com/actions/runner-images/issues/8144#issuecomment-1902072070

However it requires downloading of visionOS simulator on each CI run, which adds unnecessary time to CI build time (~6mins in my tests).
```

### Tool installation time in runtime

6 minutes

**Comment by shamil-mubarakshin** [comment]
Hey @vfilyakov, according to [Apple Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_2-release-notes#Notes), Intel runners are not supposed to be used for visionOS development. This should be the reason why `xcodebuild -downloadAllPlatforms` command doesn't install runtimes by default.
Please continue installing in runtime. You could also consider using [arm64 runners](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md#installed-simulators) instead

**Comment by saagarjha** [comment]
Apple does this for Xcode Cloud, which does not run on Apple silicon hardware. Can you consider using the steps I outlined to prepare the image in a similar way?
