### ISSUE TITLE
Github Action unable to pick up runner for macos-13-arm64

### ISSUE THREAD

**Issue by StephenHodgson** [actions/runner-images#9216]
### Description

I needed to setup a new workflow for my org to begin building apple silicon dedicated software, but a macos-13-arm64 runner would never pick up the job. The job would time out instead.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-13-arm64

### Is it regression?

yes?

### Expected behavior

macos-13-arm64 to pick up job

### Actual behavior

Job times out

### Repro steps

Create a new workflow

use runs-on: macos-13-arm64

**Comment by Vyazovoy** [comment]
Hi, @StephenHodgson! Looks like you are using an incorrect runner name (`macos-13-arm64`). According to [this doc](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners) you would need to use `macos-13-xlarge`

**Comment by StephenHodgson** [comment]
I do not want to use xl, only base model

**Comment by StephenHodgson** [comment]
Docs are not source truth.

If the xl runners are working, it would beg to argue that the base runner is broken.

**Comment by shamil-mubarakshin** [comment]
Hello @StephenHodgson, arm64 runners are available using `macos-13-xlarge`. @Vyazovoy has already provided some documentation links. You can also find additional information in https://github.com/actions/runner-images/issues/8439 announcement, which contains some Q&A

**Comment by felixbrucker** [comment]
I stumbled upon this issue trying to use macos-13-arm64 as well.

I "fixed" it by using `macos-14`, as that seems to always use arm64 for me (and also hinted at in this [blog post](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) which suggests macos-14 does not have any intel runners), as seen in the actions "setup job" log:
> Runner Image
>  Image: macos-14-arm64

When using `macos-14-arm64` specifically it doesn't work and just sits there as you reported for macos-13-arm64 as well.
