### ISSUE TITLE
Update/Add Github Action runner for macos-13-arm64

### ISSUE THREAD

**Issue by StephenHodgson** [actions/runner-images#9217]
### Tool name

macos-13-arm64

### Tool license

FOSS

### Add or update?

- [X] Add
- [ ] Update

### Desired version

apple arm64 support

### Brief description of tool

macos-13-arm64 runner that is NOT large runner.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hello, there is `macOS-13-xlarge` at the moment as described [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners) there are currently no plans to introduce any new runners right now, please follow announcements in this repository to stay on top of things.
