### ISSUE TITLE
Add Android emulator on Ubuntu2204

### ISSUE THREAD

**Issue by yschimke** [actions/runner-images#9219]
### Tool name

Android emulator on Ubuntu2204

### Tool license

Android SDK license

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Same as macos-latest

### Brief description of tool

https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md includes the android emulator (33.1.24)

But https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by yschimke** [comment]
Hit this switching from macos-latest to ubuntu-latest in order to use the new KVM support.

https://issuetracker.google.com/issues/321876773

Example PR - https://github.com/android/wear-os-samples/pull/989/files

Without this, each build must install the emulator in order to use the new Android emulator launcher in gradle managed devices.

**Comment by shamil-mubarakshin** [comment]
Hey @yschimke, we will take a look

**Comment by shamil-mubarakshin** [comment]
@yschimke,
It has been decided not to bake emulator android component into the image at this time due to maintenance concerns and relatively short runtime installation time.
Component can be installed on runtime:
```
SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
echo "y" | ${SDKMANAGER} "tools"
```

**Comment by shamil-mubarakshin** [comment]
No plans as of yet

**Comment by NavDevganMistplay** [comment]
I am running macos-latest VM for running android emulators. I only have to install JDK 17 and appium version to run my script on emulators. For switching to ubuntu, do we have an ticket open or steps to follow to setup emulator environment so my selenium java can be run on ubuntu as well ? Thanks in advance.

**Comment by NavDevganMistplay** [comment]
I am running macos-latest with no issues to start my selenium java appium scripts on the emulators. I am trying to switch to ubuntu VM but being faced with issues like appium driver not being triggered. What changes do i have to do to my .yml script to get my script get running on ubuntu emulator as well.Thanks

**Comment by karlhorky** [comment]
Hm, @mikhailkoliada mentioned that Android emulator support will be going away for M1 runners:

> Hello! Apple M1 (which is a base for both OS13 & OS14 arm64 runners) does not support nested virtualisation, that is why android emulator is not supposed to function here, it is expected and nothing could/should be done here.

Source: https://github.com/actions/runner-images/issues/9472#issuecomment-1984324388

And since `macos-14` (and probably future macOS versions) will only run on M1 (see below), that means that Android emulators will no longer be supported (even to install) on macOS runners?

> Workflows executed on this image will run exclusively on the 3 vCPU M1 runner

Source: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/#:~:text=Workflows%20executed%20on%20this%20image%20will%20run%20exclusively%20on%20the%203%20vCPU%20M1%20runner
