### ISSUE TITLE
Ubuntu 22.04 Packer Build Failing related to IP Issue

### ISSUE THREAD

**Issue by impsoftjoel** [actions/runner-images#9221]
### Description

Packer Build of the ubuntu 22.04 from the latest main branch is reporting various errors:

Both failures are reporting  errors related to an IP address:
(1st run example)
    azure-arm.build_image:   403  Forbidden [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb  403  Forbidden [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

(2nd run example)
    azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-11/temurin-11-jdk_11.0.21.0.0%2b9_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]

First Error:
##[debug]Agent running environment resource - Disk:C:\ Windows available:18828.00MB out of 30153.00MB, Memory: used 29MB out of 65534MB, CPU: usage 0.45
    azure-arm.build_image: Ign:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-11-jdk amd64 11.0.21.0.0+9
    azure-arm.build_image: Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-11-jdk amd64 11.0.21.0.0+9
    azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-11/temurin-11-jdk_11.0.21.0.0%2b9_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-11-jdk-amd64/release: No such file or directory
    azure-arm.build_image: Java 11 Toolcache Version Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk//usr/lib/jvm/temurin-11-jdk-amd64/bin/java:
    azure-arm.build_image: Setting up JAVA_HOME variable to /usr/lib/jvm/temurin-11-jdk-amd64
    azure-arm.build_image: JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
    azure-arm.build_image: Setting up default symlink
==> azure-arm.build_image: update-java-alternatives: directory does not exist: /usr/lib/jvm/temurin-11-jdk-amd64
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...

![image](https://github.com/actions/runner-images/assets/143825561/bd3093e9-1e2c-45de-bd70-90576f237a94)

Second Error:
   azure-arm.build_image: After this operation, 360 MB of additional disk space will be used.
    azure-arm.build_image: Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12
    azure-arm.build_image:   403  Forbidden [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb  403  Forbidden [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
...
    azure-arm.build_image:    Command '"/usr/lib/jvm/temurin-21-jdk-amd64/bin/java" -version' has finished with exit code
    azure-arm.build_image:        /usr/bin/bash: line 1: /usr/lib/jvm/temurin-21-jdk-amd64/bin/java: No such file or directory
    azure-arm.build_image:    at "`"$javaPath`" -version" | Should -ReturnZeroExitCode, /imagegeneration/tests/Java.Tests.ps1:43
    azure-arm.build_image:    at <ScriptBlock>, /imagegeneration/tests/Java.Tests.ps1:43
    azure-arm.build_image: Tests completed in 3.36s
    azure-arm.build_image: Tests Passed: 9, Failed: 1, Skipped: 0 NotRun: 0
    azure-arm.build_image:
    azure-arm.build_image: Containers            : {[-] /imagegeneration/tests/Java.Tests.ps1}
    azure-arm.build_image: Result                : Failed
    azure-arm.build_image: FailedCount           : 1
    azure-arm.build_image: FailedBlocksCount     : 0
    azure-arm.build_image: FailedContainersCount : 0
    azure-arm.build_image: PassedCount           : 9
    azure-arm.build_image: SkippedCount          : 0
    azure-arm.build_image: NotRunCount           : 0
    azure-arm.build_image: TotalCount            : 10
    azure-arm.build_image: Duration              : 00:00:03.3641660
    azure-arm.build_image: Executed              : True
    azure-arm.build_image: ExecutedAt            : 01/23/2024 21:07:50
    azure-arm.build_image: Version               : 5.5.0
    azure-arm.build_image: PSVersion             : 7.2.18
    azure-arm.build_image: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    azure-arm.build_image: Plugins               : 
    azure-arm.build_image: PluginConfiguration   : 
    azure-arm.build_image: PluginData            : 
    azure-arm.build_image: Configuration         : PesterConfiguration
    azure-arm.build_image: DiscoveryDuration     : 00:00:00.1823695
    azure-arm.build_image: UserDuration          : 00:00:02.7451801
    azure-arm.build_image: FrameworkDuration     : 00:00:00.4366164
    azure-arm.build_image: Failed                : {[-] Java 21}
    azure-arm.build_image: FailedBlocks          : {}
    azure-arm.build_image: FailedContainers      : {}
    azure-arm.build_image: Passed                : {[+] Java 11 is default, [+] java, [+] javac, [+] mvn…}
    azure-arm.build_image: Skipped               : {}
    azure-arm.build_image: NotRun                : {}
    azure-arm.build_image: Tests                 : {[+] Java 11 is default, [+] java, [+] javac, [+] mvn…}
    azure-arm.build_image: CodeCoverage          : 
    azure-arm.build_image:
==> azure-arm.build_image: Exception: Test run has failed
![image](https://github.com/actions/runner-images/assets/143825561/0cd9af46-ec82-4033-9345-b23b73d8e87c)

![image](https://github.com/actions/runner-images/assets/143825561/9bfe19f6-efcf-4b3e-bc59-636270a81ea1)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu 22.04 

### Is it regression?

No

### Expected behavior

Packer builds and deploys a managed image to my defined resource group in azure

### Actual behavior

The packer build is failing 

### Repro steps

Attempt to packer build ubuntu 22.04 on actions/runner-images@main

**Comment by vamshisiram** [comment]
I am getting similar error with ubuntu 20.04. https://github.com/actions/runner-images/issues/9220

but with ubuntu 20.04, i tired four times and each time i have a different error, the latest error is forbidden IP error.

**Comment by shamil-mubarakshin** [comment]
There is an issue upstream https://github.com/adoptium/adoptium-support/issues/923. The issue itself is intermittent, e.g. our [nightly builds](https://dev.azure.com/github/runner-images/_build?definitionId=103&_a=summary) passed successfully, but we don't have control over adoptium packages availability.

**Comment by mikhailkoliada** [comment]
Hey! It is reported as https://github.com/adoptium/installer/issues/782 we can not do anything about it, but retries should help

**Comment by vamshisiram** [comment]
@shamil-mubarakshin  @mikhailkoliada I saw the adoptium issue link, but that one exclusively talks about adoptium, but in my first three attempts, i did not see the forbidden IP error and it was not even adoptium. Can you please advise?

![image](https://github.com/actions/runner-images/assets/90816346/81288612-897f-4d60-9f8f-e5e763e2e6e9)

![image](https://github.com/actions/runner-images/assets/90816346/25712b07-c447-4206-94f4-c8aaf6e402b0)

![image](https://github.com/actions/runner-images/assets/90816346/0dbb89e4-556c-411e-9d4b-44fc7fe7ad41)

None of these show adoptium error, so how are these related?
