### ISSUE TITLE
Add Android SDK Platform-Tools on Ubuntu2204

### ISSUE THREAD

**Issue by s1204IT** [actions/runner-images#9227]
### Tool name

Android SDK Platform-Tools

### Tool license

Apache License, Version 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

34.0.5

### Approximate size

16M

### Brief description of tool

![](https://github.com/actions/runner-images/assets/52069677/4fb8ad3f-ba5f-4c9c-808d-9993163a51cf)

This behavior occurs in repositories that are building with Gradle using the latest AGP.

I hope you will respond in the same way as #9219.

### URL for tool's homepage

https://developer.android.com/tools/releases/platform-tools#downloads

### Provide a basic test case to validate the tool's functionality.

Building an Android app with Gradle

Gradle: 8.5
AGP: 8.2.1

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

Yes. But, we would like it to in included with runner-image.

### Tool installation time in runtime

2s

### Are you willing to submit a PR?

Sorry, but I don't have the skills to fix it.

**Comment by shamil-mubarakshin** [comment]
@s1204IT,
It has been decided not to bake emulator android component into the image at this time due to maintenance concerns and relatively short runtime installation time.
Component can be installed on runtime:
```
SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
echo "y" | ${SDKMANAGER} "platform-tools"
```
