### ISSUE TITLE
"Signature thumbprint do not match expected" when runninng Install-AzureCosmosDbEmulator.ps1 in powershell provisioner for Windows 2022 build

### ISSUE THREAD

**Issue by DevOpsAzurance** [actions/runner-images#9231]
### Description

Install script seems to download an msi:

Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\mhwezmz5.msi

that may not be matching the required thumbprint.

Reopening as the issue was previously closed, but I don't think is it resolved.  Had no ability to reopen the case:

                    Please sync the main branch, you are using the obsolete main tip.
                    
                    I am running the following, as the build clones the branch at runtime:
                    
                           . git config --global http.sslVerify false
                            $gitOutput = . git clone --branch $Branch "$agentPackerBuildUrl" "$agentPackerBuildPath\"
                    with $Branch currently set to "main" and $agentPackerBuildUrl set to "https://github.com/actions/runner-images.git".

and 

                    I am also seeing that the change on the 18th was for the Visual Studio item int he toolset-2022.json file:
                    
                    "visualStudio": {
                    "version" : "2022",
                    "subversion" : "17",
                    "edition" : "Enterprise",
                    "channel": "release",
                    "signature": "C2048FB509F1C37A8C3E9EC6648118458AA01780",

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Using earlier runner-image from this same source:

Current agent version: '3.232.1'
Current image version: 'dev'

### Is it regression?

192a94d

### Expected behavior

Builds without error

### Actual behavior

Build fails with installhelper step that seems to validate the thumbprint

### Repro steps

Run packer build using the latest main branch version.

**Comment by shamil-mubarakshin** [comment]
Hey @DevOpsAzurance,
We cannot reproduce the issue. The thumbprint of CosmosDB Emulator has already been updated and Windows 2022 build from the `main` branch of this repository is [successful](https://dev.azure.com/github/runner-images/_build/results?buildId=134633&view=results). Please sync your main branch
