### ISSUE TITLE
Update/Add [Curl]

### ISSUE THREAD

**Issue by benj-fletch** [actions/runner-images#9238]
### Tool name

curl / libcurl

### Tool license

Curl license: https://curl.se/docs/copyright.html

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.88.1

### Brief description of tool

Curl is a core tool for the runners and is used to install a number of the other packages for the images used in GitHub

### URL for tool's homepage
https://curl.se/

### Provide a basic test case to validate the tool's functionality.

Same as the one currently used:
```
Describe "curl" {
    It "curl" {
        "curl --version" | Should -ReturnZeroExitCode
    }
}
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
Hello! Unfortunately we can not update curl as canonical only [provides](https://packages.ubuntu.com/search?keywords=curl) 7.81.x in 22.04 and we do not derive from the upstream repo for the core packages mainly.
