### ISSUE TITLE
Add Haskell tools to macos-13

### ISSUE THREAD

**Issue by andreasabel** [actions/runner-images#9242]
### Tool name

GHCup, possibly also GHC and Cabal

### Tool license

Same as on macos-12 and all other images

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest, i.e., same version that the other images have (should be uniform for the sake of upgrading from an older image to a newer one).

### Brief description of tool

I am surprised to see GHCup, GHC and Cabal not present in macOS-13 when they are supplied in all other images.  E.g. here in macOS-12: https://github.com/actions/runner-images/blob/6308849b2531330934dc881cfa920a7fc53b0929/images/macos/macos-12-Readme.md?plain=1#L106-L112
(first and last two lines in the list).

I don't know if this is a conscious decision to drop Haskell, or just an omission or a bug.

Not sure I used the correct form to report this issue.  

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hello @andreasabel!
Due to certain technical constraints and maintenance difficulties, we have decided to streamline latest macOS images and remove some programs from them that can be installed quickly and easily at runtime or are infrequently used. The Haskell developer tools package is also included in this list. Unfortunately, at the moment, we have no plans to reintroduce any of the removed packages, but we will certainly notify the community if plans change.

**Comment by andreasabel** [comment]
Thanks @erik-bershel , for the swift reply.
I totally respect your decision.

It would be good if such decisions would be recorded somewhere in this repo where one could find them.  I was looking around here before opening the issue, but could not find any changelogs or some other documents that would list such decisions (and maybe explain them).

Basically, I should expect Haskell to also disappear from the other images in the future and be prepared to install it myself, is that right?  (I am asking in my role as the maintainer of the setup action for haskell, `haskell-actions/setup`).

**Comment by erik-bershel** [comment]
> It would be good if such decisions would be recorded somewhere in this repo where one could find them. I was looking around here before opening the issue, but could not find any changelogs or some other documents that would list such decisions (and maybe explain them).

Each image is accompanied by documentation. You can view the content at any time. We also inform users about changes in existing images in advance; for this, there are announcement mechanisms as well as prereleases. 

> Basically, I should expect Haskell to also disappear from the other images in the future and be prepared to install it myself, is that right? (I am asking in my role as the maintainer of the setup action for haskell, haskell-actions/setup).

Unfortunately, I cannot predict in advance what will be contained in images that are not even in beta yet. This is always a very difficult question for which there is no ready answer.

**Comment by pbrisbin** [comment]
:wave: this seems to be the link that everyone finds first when they encounter a lack of `stack` on a new macOS runner, so I wanted to drop the snippet you need to get `stack` back here:

```yaml
      - if: ${{ runner.os == 'macOS' }}
        run: curl -sSL https://get.haskellstack.org/ | sh
```

This assumes you are running `macOS-latest`. If you are running some other versions, e.g. in a matrix, you can use the matrix in your conditional instead,

```yaml
      - if: ${{ matrix.os == 'macOS-14' }}
        run: curl -sSL https://get.haskellstack.org/ | sh
```

Lastly, if you're a [freckle/stack-action](https://github.com/freckle/stack-action) user, as of v5.3 it will install stack for you if necessary.

**Comment by andreasabel** [comment]
[haskell-actions/setup](https://github.com/haskell-actions/setup) still works out the box on `macos-13/14`, yet GHC 9.0 and below does not work on the `macos-14` (ARM) image (because of LLVM troubles).
