### ISSUE TITLE
2024 GitHub Actions macOS runner image roadmap

### ISSUE THREAD

**Issue by Steve-Glass** [actions/runner-images#9255]
### Breaking changes

Updates to the macOS runner image release cycle were [published today](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/), along with the macOS 14 announcement. In addition, the roadmap for calendar year 2024 has been presented below. This announcement will be updated with links to public roadmap objectives as they become publicly available.

![Image](https://github.com/actions/runner-images/assets/84886334/ac6ef1f1-8e18-4af1-a97f-d38cf82885df)

### Target date

N/A

### The motivation for the changes

N/A

### Possible impact

N/A

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] macOS 11
- [x] macOS 12
- [x] macOS 13
- [x] macOS 13 Arm64
- [x] macOS 14
- [x] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

N/A

**Comment by dpogue** [comment]
One question that doesn't seem to be addressed anywhere (and I realize this was just published today and doesn't have all the details): When macOS-14 becomes latest, does that mean all macOS runners will move to M1 instances, or will macOS-14 be available on Intel-based runners?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
`macos-14` runner reports a broken link to the included software because the tag was not pushed: https://github.com/actions/runner-images/blob/macOS-14/20240116.1/images/macos/macos-14-arm64-Readme.md
Also wondering if this image will be available for `x86-64` will it also be available on free accounts.

**Comment by mariusfanu-metrobank** [comment]
@dpogue according to the [announcement](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) macOS-14 agents will run exclusively on M1 vCPUs

> The macOS 14 runner image is now available for GitHub hosted runners. Workflows executed on this image will run exclusively on the 3 vCPU M1 runner announced earlier today.

**Comment by mariusfanu-metrobank** [comment]
@Steve-Glass is there any timeline for macOS-14 to be deployed on Azure DevOps?

**Comment by bvaughan527** [comment]
> @Steve-Glass is there any timeline for macOS-14 to be deployed on Azure DevOps?

I have the same question. It would be great to have the macos-14 build agent available in Azure DevOps.

**Comment by 3a4oT** [comment]
+1 regarding  `Azure DevOps`. It's a blocker for our team

**Comment by Maleware** [comment]
Are their any plans to add docker?

**Comment by Reisclef** [comment]
Is there any roadmap for supporting xcode 15 as the default on the macOS-13 image? I appreciate this may not be the correct place to ask, but was just curious as Apple is requiring xcode 15 for app store apps as of 29th April, and I wanted to see if we will need to manually set the version in our xcode v5 task.

**Comment by hugovk** [comment]
Good timing! 

Xcode 15 is the default in the runner image currently being rolled out:

https://github.com/actions/runner-images/blob/macos-13/20240204.1/images/macos/macos-13-Readme.md#xcode

**Comment by Reisclef** [comment]
Wow! That was fast! ;)

Excellent news, thanks very much. :)

**Comment by lsaudon** [comment]
XCode 15 will never be put on macOS 12/latest?
Do we have to specify macOS 13 for a few months?

**Comment by mariusfanu-metrobank** [comment]
@lsaudon Xcode 15 requires a Mac running macOS Ventura 13.5 or later.

**Comment by lsaudon** [comment]
> @lsaudon Xcode 15 requires a Mac running macOS Ventura 13.5 or later.

macOS 13 will never go latest to fix this problem?

**Comment by Galkon** [comment]
> One question that doesn't seem to be addressed anywhere (and I realize this was just published today and doesn't have all the details): When macOS-14 becomes latest, does that mean all macOS runners will move to M1 instances, or will macOS-14 be available on Intel-based runners?

Curious about this as well. Currently they are M1 only, which is better than nothing! But would love intel macOS 14 runners to be holistic 😄

**Comment by gamer191** [comment]
This seems to be the only announcement about MacOS-11 being removed. If that is going ahead in June, shouldn't it be mentioned in the annoucement section at the top of https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
