### ISSUE TITLE
Add Python 3.9 to macos-14

### ISSUE THREAD

**Issue by hugovk** [actions/runner-images#9258]
### Tool name

Python

### Tool license

PSF License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.9.13

### Brief description of tool

Python 3.9.1 was the first to support Apple Silicon: https://www.python.org/downloads/release/python-391/

Python 3.10-3.13 are already available for macos-14, but 3.9 is missing from `actions/setup-python@v5`:

```
  Version ~3.9.0-0 was not found in the local cache
  Error: The version '3.9' with architecture 'arm64' was not found for macOS 14.2.1.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

### URL for tool's homepage

https://www.python.org

### Provide a basic test case to validate the tool's functionality.

```bash
name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [macos-latest, macos-14]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: python --version --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by erik-bershel** [comment]
Hey @hugovk!
It's an action behaviour but not an image. You can report it here: https://github.com/actions/setup-python
Also I noticed that I can provide more info about it. It was stated that this action wouldn't support this arch/version pair. Check here: https://github.com/actions/setup-python/issues/696.
