### ISSUE TITLE
Add miniconda to macOS 13 and 14 images (again)

### ISSUE THREAD

**Issue by jezdez** [actions/runner-images#9262]
### Tool name

miniconda

### Tool license

3-clause BSD License

UPDATE (as reported by @zooba): Miniconda is covered by a licensing agreement between Microsoft and Anaconda Inc:

- https://devblogs.microsoft.com/python/anaconda-licensing/
- https://www.anaconda.com/partners/azure

### Add or update?

- [X] Add
- [ ] Update

### Desired version

23.11.0

### Brief description of tool

Miniconda was part of the macOS images in the past, until macOS 12, but has not been part of the macos 13 and 14 images.

It _is_ currently part of the Ubuntu and Windows images.

Miniconda is used by a huge number of people in all industries, from Open Source maintainers (e.g. [bioconda](https://bioconda.github.io), [conda-forge](https://conda-forge.org)) to Enterprise customers, particularly in the scientific and AI communities (~40 million users according to Microsoft partner Anaconda Inc). [Conda is free](https://www.anaconda.com/blog/is-conda-free#summarize) to use.

In https://github.com/actions/runner-images/issues/8422#issuecomment-1754613250 @vpolikarpov-akvelon replied:

>We've decided not to include Miniconda in the mac OS 13 image to help reduce maintenance. We're trying to strike a balance between convenience and keeping things streamlined and Miniconda isn't a super common tool for everyone.

> If you'd like to have Miniconda preinstalled, you can use custom self-hosted runners. They're a great way to tailor your environment to your specific needs.

I'm responding here in a new issue since I haven't gotten a reply to my comment in the original issue. Running custom self-hosted runners is not going to solve this problem, since conda is a self-service package manager and GitHub user would not run a self-hosted runner to make use of it. You wouldn't make the same argument for tools like homebrew or pipx.

I'm looking to get feedback from GitHub on how we can add miniconda to the macOS 13 and 14 images again. What are the constraints currently that block adding it back, and how can we overcome them?

### URL for tool's homepage

https://docs.conda.io/projects/miniconda/en/latest/

### Provide a basic test case to validate the tool's functionality.

```bash
conda --version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
See the installation of miniconda in the Windows and Ubuntu images, as well as the macOS builds prior to macOS 13.
```

### Tool installation time in runtime

30 seconds

### Are you willing to submit a PR?

Yes

**Comment by erik-bershel** [comment]
Hello @jezdez!

Due to certain technical constraints and maintenance difficulties, we have decided to streamline latest macOS images and remove some programs from them that can be installed quickly and easily at runtime or are infrequently used. The Miniconda package manager tool is also included in this list. Unfortunately, at the moment, we have no plans to reintroduce any of the removed packages, but we will certainly notify the community if plans change.

I would like to note that installing a Miniconda in runtime using the official instructions presented on the [site](https://docs.conda.io/projects/miniconda/en/latest/index.html#quick-command-line-install) takes less than a minute (about 20 sec to be honest) and does not require special skills or extreme complexity of the workflow code.

**Comment by zooba** [comment]
Is this kind of thing supported and regularly tested in actions?

```
After installing, initialize your newly-installed Miniconda. The following commands initialize for bash and zsh shells:

~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh
```

I know there have been issues in the past where updating shell settings doesn't apply properly to subsequent steps, which is one of the main reasons we've had to have stuff preconfigured.

**Comment by ndevenish** [comment]
Probably want to update your documentation that still tells you that it's built in https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

**Comment by ndevenish** [comment]
The Azure pipelines documentation (which links here as the image source) still states that conda is built-in: https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

**Comment by guyer** [comment]
The explanation offered here is specious if you're not also going to drop it from the ubuntu and windows images, particularly given @ndevenish's point that the documentation still tells you `$CONDA` is defined for macOS. To make this all the more confusing, the `macos-latest` image just jumped from `macos-12` to `macos-14` between [October 1st](https://dev.azure.com/guyer/FiPy/_build/results?buildId=1376&view=logs&j=6e9fd3b2-3876-5f92-ebcc-0273b412dd37&t=4ad2ecc3-2e7d-4366-99ba-8836d6c1c57e&l=10) and [October 2nd](https://dev.azure.com/guyer/FiPy/_build/results?buildId=1381&view=logs&j=025cffda-e780-5709-3db1-5f3116e45a49&t=830c5d1b-92e3-4d0c-b8ad-51a0bb0cdf79&l=10).

**Comment by ndevenish** [comment]
> To make this all the more confusing, the `macos-latest` image just jumped from `macos-12` to `macos-14` between [October 1st](https://dev.azure.com/guyer/FiPy/_build/results?buildId=1376&view=logs&j=6e9fd3b2-3876-5f92-ebcc-0273b412dd37&t=4ad2ecc3-2e7d-4366-99ba-8836d6c1c57e&l=10) and [October 2nd](https://dev.azure.com/guyer/FiPy/_build/results?buildId=1381&view=logs&j=025cffda-e780-5709-3db1-5f3116e45a49&t=830c5d1b-92e3-4d0c-b8ad-51a0bb0cdf79&l=10).

Ah! I had wondered what caused our CI to break all of a sudden. I thought it might have been an image change, but couldn't find any notices about it and thought "Wait, 14 was last year, maybe something else happened".
