### ISSUE TITLE
vs_Enterprise.exe signature thumbprint do not match expected

### ISSUE THREAD

**Issue by JSeb084** [actions/runner-images#9263]
### Description

Current signature in "\images\windows\toolsets\toolset-2022.json" is C2048FB509F1C37A8C3E9EC6648118458AA01780

New signature is: F9A7CF9FBE13BAC767F4781061332DA6E8B4E0EE

```
==> azure-arm.image: Machine successfully restarted, moving on
==> azure-arm.image: Provisioning with Powershell...
==> azure-arm.image: Provisioning with powershell script: C:/a/1/s/dv.adobuilderserver.fromgithub/images/windows/templates/../scripts/build/Install-VisualStudio.ps1
    azure-arm.image: Downloading Bootstrapper ...
    azure-arm.image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.image: Package downloaded in 0.3 seconds
    azure-arm.image: Signature thumbprint do not match expected.
    azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.image: +         throw "Signature thumbprint do not match expected."
    azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
    azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0 3010]
==> azure-arm.image: Step "StepProvision" failed
==> azure-arm.image: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? Added TLS 1.2 in session.
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

main [https://github.com/actions/runner-images/commit/301ded2638a8854400b8e941f9c42505b1024bca](https://github.com/actions/runner-images/commit/301ded2638a8854400b8e941f9c42505b1024bca)

### Is it regression?

N/A

### Expected behavior

Signature match

### Actual behavior

Errors with the above message

### Repro steps

Load function "Test-FileSignature" from \images\windows\scripts\helpers\InstallHelpers.ps1

Download "vs_Enterprise.exe" from https://aka.ms/vs/17/release/vs_Enterprise.exe

Run > Test-FileSignature -path "vs_Enterprise.exe" -ExpectedThumbprint "C2048FB509F1C37A8C3E9EC6648118458AA01780"

Get error "Signature thumbprint do not match expected."

Run >  Test-FileSignature -path "vs_Enterprise.exe" -ExpectedThumbprint "F9A7CF9FBE13BAC767F4781061332DA6E8B4E0EE"

Signature for vs_Enterprise.exe is valid

**Comment by erik-bershel** [comment]
Hey @JSeb084!
Will be fixed here: https://github.com/actions/runner-images/pull/9261.
