### ISSUE TITLE
Unable to create runner image for windows 2022

### ISSUE THREAD

**Issue by rajravat** [actions/runner-images#9264]
### Description

I've been following the instructions from here: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#manual-image-generation

to create a runner image for windows 2022, however i keep getting an exception raised shortly into the process with the message of "Signature thumbprint do not match expected". I am successfully able to create a Windows 2019 runner image with no issue though. Is anyone able to help?

![Screenshot 2024-01-31 103834](https://github.com/actions/runner-images/assets/25839791/35865387-7074-45bc-bf28-6ee26a214635)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I presume it is using the latest build Windows 2022 build: 20240128.1.0

### Is it regression?

No

### Expected behavior

Able to create a runner image

### Actual behavior

Throws an exception trying to create the runner image

### Repro steps

https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#manual-image-generation

Follow the instructions here and choose Windows 2022 when asked for which image type, using UK South as the location (not sure this matters?)

**Comment by erik-bershel** [comment]
Hey @rajravat!
Use only the main branch to build machines. We do not support other branches. Closing as a clone: https://github.com/actions/runner-images/issues/9263
