### ISSUE TITLE
choco install sql-server-2022 runs to completion on Standard Runners, requires reboot on Larger Runners

### ISSUE THREAD

**Issue by Piedone** [actions/runner-images#9277]
### Description

My expectation would be that Standard and Larger Runners work the same, except for the hardware resources. This is not the case with [our action](https://github.com/Lombiq/GitHub-Actions/tree/ebc7033ff5882d5b77899c6cc0e6d688cefb37fe/.github/actions/setup-sql-server) that installs SQL Server 2022.

Its [PowerShell script](https://github.com/Lombiq/GitHub-Actions/blob/ebc7033ff5882d5b77899c6cc0e6d688cefb37fe/.github/actions/setup-sql-server/Initialize-SqlServer.ps1#L7) runs this under Windows:

```
choco install sql-server-2022  --no-progress
```

This runs to completion using `windows-2022`, see e.g. [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7757215962/job/21156207106). Running on an 8-core Windows 2022 Larger Runner (i.e. the same image but a Larger Runner) necessitates a restart, see [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7755813572/job/21152505961#step:8:49).

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20240128.1.0 (same in both cases)

https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7755813572/job/21152505961#step:8:49

### Is it regression?

We last used Larger Runners for this about a year ago, when it worked, but can't point you to any specific build.

### Expected behavior

The script execution yields the exact same results under Standard and Larger Runners.

### Actual behavior

The behavior is different.

### Repro steps

1. Create a Larger Runner (8-core, not sure if this makes any difference) using the `windows-2022` image.
2. Run `choco install sql-server-2022  --no-progress` on it.
3. Experience the above-mentioned reboot required message.

**Comment by mikhailkoliada** [comment]
Hello! The error emitted by the choice itself, not by listed runner, please file an issue agains the choco package maintainer, we can not help here, unfortunately.

**Comment by Piedone** [comment]
But isn't it due to some difference between Standard and Large Runners?
