### ISSUE TITLE
Pipeline Failure on Ubuntu 22.04 Agent Update: NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by author4all** [actions/runner-images#9278]
### Description

We've encountered an issue where our Spring MVC (with Maven) CI pipeline fails when running Maven@3 `verify` goal due to `org.springframework.beans.factory.NoSuchBeanDefinitionException`, without any modifications to our codebase. This error emerged following an update to the Azure DevOps hosted agent's runner image for Ubuntu 22.04, pinpointing the update as the cause.

Issue Overview:

- **Error**: `org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [bean name] available at [used location]`.
- **Observation**: The pipeline succeeds on Ubuntu 20.04's latest image but fails on Ubuntu 22.04 following an image update.

Agent Version and Image Details:

- **Successful Execution**: Agent Version **3.232.3**, Ubuntu 22.04 Image Version **20240122.3.0**.
- **Failed Execution**: Agent Version **3.232.3**, Ubuntu 22.04 Image Version **20240126.1.0**.

The failure seems linked to the updated **20240126.1.0** image for Ubuntu 22.04, suggesting a potential incompatibility or missing dependencies affecting our project. We request an investigation into the changes made in this image version to identify and rectify the root cause.

We appreciate your support in ensuring the stability of our CI/CD processes. Thank you.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240126.1.0

### Is it regression?

no

### Expected behavior

No failure.

### Actual behavior

Failing with exception.

### Repro steps

1. Run Maven@3 task with `verify`

**Comment by OKiMaureen** [comment]
A customer also sent in a ticket experiencing issues with the latest runner version `ubuntu-22.04 Version: 20240126.1.0` when running maven commands. They said the following:

> In some of our projects maven unit tests are just stopped working.
> The code stayed the same, no changes were made in between. The only difference what we are seeing is, that the successful run was on the image Image: ubuntu-22.04  Version: 20240122.3.0 and the failing ones are on   Image: ubuntu-22.04 Version: 20240126.1.0.

Sample error:

```
2024-02-02T08:14:52.8864715Z java.lang.NullPointerException: Cannot invoke "org.springframework.security.core.context.SecurityContextHolderStrategy.clearContext()" because "org.springframework.security.core.context.SecurityContextHolder.strategy" is null
```

Could the team kindly take a look as soon as possible because this is blocking since they can't pin runners to previous versions? Thanks.

**Comment by fatihhguvenn** [comment]
My spring boot application hangs before SpringSecurity initialization with Ubuntu 22.04 (20240126), it was working fine until Ubuntu 22.04 (20240116). I can't understand what's going on everything looks the same. Even the jar files are identical. But latest builts won't start! I changed runner to 20.04, it works for now.

**Comment by mikhailkoliada** [comment]
Hello, please provide a minimal repro-steps so we could reproduce the issue

**Comment by fatihhguvenn** [comment]
I can't reproduce the issue on a public repo. it's a jar file problem. jar file that built by gradle is corrupted somehow.

this command below **fails**
`java -jar app.jar`

after extracting app.jar file contents into disk and then directly running java class as below **works fine**
`java org.springframework.boot.loader.launch.JarLauncher`

any java expert has any idea?

**Comment by MaksimZhukov** [comment]
Hello everyone!
@author4all, thank you for reporting the issue! 
Unfortunately, we could not reproduce the issue from our side. For further investigation, it would be helpful if you could provide us with a link to the public repository or create a simple test project where the issue occurs. 
As a workaround please use `ubuntu-20.04` image

**Comment by mikhailkoliada** [comment]
ado version has been updated

**Comment by angaaruriakhil** [comment]
Hi, was this issue actually related to azcopy? We are performing ubuntu 22.04 builds right now and are concerned that this will be an issue for our customers who use Maven.

**Comment by mikhailkoliada** [comment]
@angaaruriakhil oh, ignore me, I closed the wrong ticket :/

**Comment by mikhailkoliada** [comment]
Could someone please test it on a new version of the image?

**Comment by akbast** [comment]
@mikhailkoliada We have tested this with the newest image and it works. Can you say what is changed to solve this issue?

**Comment by mikhailkoliada** [comment]
@akbast little to no idea, I mean, it has probably been caused by some deep dependency we do not track explicitly in the readme files, but track of this dependency does not look prominent now as we have no full minimal repro steps and are not aware in which direction to dig. I'd consider it a luck given that it got self-healed but if it is going to repeat itself we will have to have some repro to start looking under the hood, I guess it can be closed for now.

**Comment by fatihhguvenn** [comment]
> Could someone please test it on a new version of the image?

I tested too, the issue is gone. my jar running without any problems. thanks for the fix
