### ISSUE TITLE
macOS12 : 12.7.3 (21H1015) - Android Emulator is not found - adb: no devices/emulators found

### ISSUE THREAD

**Issue by anchitkoul** [actions/runner-images#9279]
### Description

Since the recent update in the macOS12 version to 12.7.3, our Android Test pipeline are failing due to inability to find emulator

Failing builds: https://msasg.visualstudio.com/Bing_Ads/_build/results?buildId=43178778&view=results

`
Fri Feb 2 00:34:43 UTC 2024 (DEBUG) Emulator starting 270
adb: no devices/emulators found`

`Fri Feb 2 00:35:13 UTC 2024 (DEBUG) Emulator starting 240
adb: no devices/emulators found`

`Fri Feb 2 00:35:44 UTC 2024 (DEBUG) Emulator starting 210
adb: no devices/emulators found`

`Fri Feb 2 00:36:14 UTC 2024 (DEBUG) Emulator starting 180
adb: no devices/emulators found`

`Fri Feb 2 00:36:44 UTC 2024 (DEBUG) Emulator starting 150
adb: no devices/emulators found`

`Fri Feb 2 00:37:14 UTC 2024 (DEBUG) Emulator starting 120
adb: no devices/emulators found`

`Fri Feb 2 00:37:44 UTC 2024 (DEBUG) Emulator starting 90
adb: no devices/emulators found`

`Fri Feb 2 00:38:14 UTC 2024 (DEBUG) Emulator starting 60
adb: no devices/emulators found`

`Fri Feb 2 00:38:45 UTC 2024 (DEBUG) Emulator starting 30
adb: no devices/emulators found
(DEBUG) Start cleaning current processes
`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '3.232.3'
Operating System
macOS
12.7.3
21H1015
Runner Image
Image: macos-12
Version: 20240127.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20240127.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240127.1
Runner Image Provisioner
2.0.341.1+ea3907f30f87ddf37e44fa45b753abddb03811b4
Current image version: '20240127.1'
Agent running as: 'runner'

### Is it regression?

macOS 12.7.2 21G1974, https://msasg.visualstudio.com/Bing_Ads/_build/results?buildId=42249299&view=results

### Expected behavior

Emulator should start

: example ADO build : https://msasg.visualstudio.com/Bing_Ads/_build/results?buildId=42244266&view=logs&j=cac0b18b-0cc8-5043-3805-66f8c8408803&t=aa86683d-edf6-5f61-4d71-4c7f2e8a6d5e&l=30713

### Actual behavior

Fri Feb 2 00:38:45 UTC 2024 (DEBUG) Emulator starting 30
adb: no devices/emulators found

### Repro steps

Failing ADO build : https://msasg.visualstudio.com/Bing_Ads/_build/results?buildId=43178778&view=logs&j=63a13f03-ea48-5d1e-b10f-995ff4ca2c01&t=d971d4db-5e70-52b1-7720-c3f8e3b6489c&l=4630

**Comment by anchitkoul** [comment]
@erik-bershel

**Comment by rohanp-91** [comment]
@shamil-mubarakshin - 

Below is the script that we are running to launch emulator:

`for (( i=0; i<$numEmulators; i++ )); do
    # create and start emulator with specific SDK
    emulator_name='emulator'$i
    echo -e $(date) "$debugTag Create AVD $emulator_name "
    if [[ "`uname -m`" == "arm64" ]]; then
      avdmanager create avd -n $emulator_name -k "system-images;android-30;google_apis;arm64-v8a" -d pixel_6 --force
    else
      avdmanager create avd -n $emulator_name -k "system-images;android-30;google_apis;x86" -d pixel_6 --force
    fi
    echo -e $(date) "$debugTag Check hardware acceleration "
    emulator -accel-check
    echo -e $(date) "$debugTag Boot AVD $emulator_name "
    # wait for AVD boot finished
    if [[ "`uname -m`" == "arm64" ]]; then
      emulator -avd $emulator_name -cores 2 -memory 5120 -accel on -noaudio -no-snapshot -no-boot-anim &
    else
      emulator -avd $emulator_name -cores 2 -memory 5120 -accel on -gpu swiftshader_indirect -noaudio -no-snapshot -no-boot-anim &
    fi
    echo -e $(date) "$debugTag Wait for AVD boot finished "

    threshold=600
    until false
    do
      sleep 30
      adb shell 'if [[ -z $(getprop sys.boot_completed) ]]; then exit 1; fi;'
      result=$?

      if [ $result -eq 0 ]; then
        echo -e $(date) "$debugTag Emulator started $result"
        echo ""
        break
      fi

      if [ $threshold -le 0 ]; then
        exit 1
      fi
      echo -e $(date) "$debugTag Emulator starting $threshold"
      ((threshold-=30))
    done

    echo -e $(date) "$debugTag Emulator started"
    echo ""
  done
  sleep 30`

I just copied some of the outputs from our logs:

```
Fri Feb 2 12:00:03 UTC 2024 (DEBUG) Boot AVD emulator0 
INFO    | Android emulator version 33.1.24.0 (build_id 11237101) (CL:N/A)
INFO    | Found systemPath /Users/runner/Library/Android/sdk/system-images/android-30/google_apis/x86/
Fri Feb 2 12:00:03 UTC 2024 (DEBUG) Wait for AVD boot finished 
WARNING | Please update the emulator to one that supports the feature(s): Vulkan
WARNING | Running on a system with less than 6 logical cores. Setting number of virtual cores to 1
WARNING | FeatureControl is requesting a non existing feature.
adb: no devices/emulators found
Fri Feb 2 12:00:33 UTC 2024 (DEBUG) Emulator starting 600
adb: no devices/emulators found
Fri Feb 2 12:01:03 UTC 2024 (DEBUG) Emulator starting 570
adb: no devices/emulators found
Fri Feb 2 12:01:33 UTC 2024 (DEBUG) Emulator starting 540
adb: no devices/emulators found
```


It seems like for some agents, it cannot find Android emulator. We have around 20 retries in the overall run, but it fails for all 20 times. It's not consistent, but it's happening more frequently over the past 2 weeks. It's not very clear to us as to how, across  agents with same configuration, some are able to find the emulator whereas for others it's failing consistently.

**Comment by shamil-mubarakshin** [comment]
@anchitkoul, @rohanp-91, I couldn't run code from your snippet as it gave me `avd not found` errors and entries such as `adb: no devices/emulators found` you reported. I modified the script with full paths to android components and it completed successfully:
```
    echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-30;google_apis;x86'
    for (( i=0; i<1; i++ )); do
        # create and start emulator with specific SDK
        emulator_name='emulator'$i
        echo -e $(date) "$debugTag Create AVD $emulator_name "
        if [[ "`uname -m`" == "arm64" ]]; then
            $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n $emulator_name -k "system-images;android-30;google_apis;arm64-v8a" -d pixel_6 --force
        else
            $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n $emulator_name -k "system-images;android-30;google_apis;x86" -d pixel_6 --force
        fi
        echo -e $(date) "$debugTag Check hardware acceleration "
        $ANDROID_HOME/emulator/emulator -accel-check
        echo -e $(date) "$debugTag Boot AVD $emulator_name "
        # wait for AVD boot finished
        if [[ "`uname -m`" == "arm64" ]]; then
            $ANDROID_HOME/emulator/emulator -avd $emulator_name -cores 2 -memory 2048 -accel on -noaudio -no-snapshot -no-boot-anim &
        else
            $ANDROID_HOME/emulator/emulator -avd $emulator_name -cores 2 -memory 5120 -accel on -gpu swiftshader_indirect -noaudio -no-snapshot -no-boot-anim &
        fi

        echo -e $(date) "$debugTag Wait for AVD boot finished "
        threshold=600
        until false
        do
          sleep 30
          $ANDROID_HOME/platform-tools/adb shell 'if [[ -z $(getprop sys.boot_completed) ]]; then exit 1; fi;'
          result=$?

          if [ $result -eq 0 ]; then
            echo -e $(date) "$debugTag Emulator started $result"
            echo ""
            break
          fi

          if [ $threshold -le 0 ]; then
            exit 1
          fi
          echo -e $(date) "$debugTag Emulator starting $threshold"
          ((threshold-=30))
        done

        echo -e $(date) "$debugTag Emulator started"
        echo ""
        sleep 60
    done
    sleep 30
```
And this is how logs looked like:
```
WARNING | Failed to process .ini file /Users/runner/.android/emu-update-last-check.ini for reading.
adb: device offline
Wed Feb 7 15:05:04 UTC 2024  Emulator starting 600
adb: device offline
Wed Feb 7 15:05:34 UTC 2024  Emulator starting 570
adb: device offline
Wed Feb 7 15:06:05 UTC 2024  Emulator starting 540
WARNING | /etc/localtime does not point to zoneinfo-compatible timezone name
Wed Feb 7 15:06:35 UTC 2024  Emulator starting 510
Wed Feb 7 15:07:05 UTC 2024  Emulator starting 480
Wed Feb 7 15:07:36 UTC 2024  Emulator starting 450
Wed Feb 7 15:08:06 UTC 2024  Emulator starting 420
Wed Feb 7 15:08:37 UTC 2024  Emulator starting 390
Wed Feb 7 15:09:07 UTC 2024  Emulator starting 360
Wed Feb 7 15:09:38 UTC 2024  Emulator starting 330
Wed Feb 7 15:10:08 UTC 2024  Emulator starting 300
E0207 15:10:34.486693 bed9000 FrameBuffer.cpp:3765] Failed to find ColorBuffer:5
E0207 15:10:34.486703 bed9000 FrameBuffer.cpp:3765] Failed to find ColorBuffer:8
Wed Feb 7 15:10:38 UTC 2024  Emulator started 0
Wed Feb 7 15:10:38 UTC 2024  Emulator started
INFO    | Boot completed in 378962 ms
INFO    | Increasing screen off timeout, logcat buffer size to 2M.
```

I will close this issue as it doesn't look like problems with the image. Feel free to reach out in case of further concerns
