### ISSUE TITLE
MacOS arm has no vcpkg pre-installed

### ISSUE THREAD

**Issue by TrueBrain** [actions/runner-images#9286]
### Description

All runner images have vcpkg preinstalled, including the non-arm runners of MacOS. But the arm ones do not. And I can't really find anything if that was a deliberately choice, or just an oversight.

So from my perspective, this is a bug. Upgrading a macos-latest to macos-14 causes build failures on my side, as vcpkg is missing. But if we install vcpkg manually it works just fine.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Image: macos-14-arm64
  Version: 20240116.1
```

### Is it regression?

Against `macos-latest`, yes. Otherwise, no.

### Expected behavior

Have vcpkg installed on all images; not all except 2.

### Actual behavior

No vcpkg installed on arm images

### Repro steps

Create a workflow that uses CMake with vcpkg.
Run CMake with any other image: works fine.
Run CMake with arm images:

```
     Could not find toolchain file:
    /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
```

Did not test, but given `vcpkg` is not listed [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md), it is reasonable to think you also can't use `vcpkg` from a bash step.

**Comment by MaksimZhukov** [comment]
Hello @TrueBrain!
This is an expected behaviour. It has been decided not to bake vcpkg into the image due to maintenance concerns and relatively short installation time. Please continue installing in runtime.

**Comment by talregev** [comment]
+1 for add vcpkg to macos arm64.
