### ISSUE TITLE
Image build failed for self hosted agents

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#9289]
### Description

**Ubuntu image build failed**
azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0%2b7_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-17-jdk-amd64/release: No such file or directory

**Windows Image build failed**
==> azure-arm.image: Join-Path : Cannot bind argument to parameter 'Path' because it is null.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:224 char:30
==> azure-arm.image: +     $toolsetPath = Join-Path $env:IMAGE_FOLDER "toolset.json"
==> azure-arm.image: +                              ~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidData: (:) [Join-Path], ParentContainsErrorRecordException
==> azure-arm.image:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
==> azure-arm.image:    mand
==> azure-arm.image:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

**Ubuntu**
Image 20240201.1.0

**Windows**
Image 20240128.1.0

### Is it regression?

NA

### Expected behavior

Image build pipeline complete successfully.

### Actual behavior

**Ubuntu image build failed**
azure-arm.build_image:   Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0%2b7_amd64.deb  Error reading from server. Remote end closed connection [IP: 151.101.39.42 443]
==> azure-arm.build_image: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> azure-arm.build_image: cat: /usr/lib/jvm/temurin-17-jdk-amd64/release: No such file or directory

**Windows Image build failed**
==> azure-arm.image: Join-Path : Cannot bind argument to parameter 'Path' because it is null.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:224 char:30
==> azure-arm.image: +     $toolsetPath = Join-Path $env:IMAGE_FOLDER "toolset.json"
==> azure-arm.image: +                              ~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidData: (:) [Join-Path], ParentContainsErrorRecordException
==> azure-arm.image:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
==> azure-arm.image:    mand
==> azure-arm.image:

### Repro steps

Rerun pipelines...

**Comment by mikhailkoliada** [comment]
Hey! It is a video known problem we can not fix, please report it here: https://github.com/adoptium/adoptium-support/issues/923 usually rerun of the pipeline helps.
