### ISSUE TITLE
`glibtoolize` not present on macos-14 runner

### ISSUE THREAD

**Issue by nazar-pc** [actions/runner-images#9290]
### Description

My understanding is that `glibtoolize` should be present on macOS runners, but something is different about `macos-14` runner comparing to `macos-12`

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner image is 20240116.1

I've got the following [CI failure](https://github.com/nazar-pc/space-acres/actions/runs/7781125803/job/21214972867?pr=116) after upgrading from macos-12 to macos-14:
```
  autoreconf: running: glibtoolize --copy --force
  Can't exec "glibtoolize": No such file or directory at /opt/homebrew/Cellar/autoconf/2.72/share/autoconf/Autom4te/FileUtils.pm line 318.
  autoreconf: error: glibtoolize failed with exit status: 2
```

### Is it regression?

Unknown

### Expected behavior

`glibtoolize` should be present on `macos-14`

### Actual behavior

`glibtoolize` is missing on `macos-14`

### Repro steps

-

**Comment by mikhailkoliada** [comment]
Hello! No, it is not present by default, I'd say on macOS-12 it is installed as a dependency of some package (I have not checked which one), and we have no plans to install auto tools dependencies directly until absolutely needed. You can install one if you need in runtime `brew install lib tool` takes 3s of execution.
