### ISSUE TITLE
`macos-latest-large` gets resolved to macOS 13 instead of macOS 12

### ISSUE THREAD

**Issue by Vyazovoy** [actions/runner-images#9301]
### Description

When I use `runs-on: macos-latest-large` it gets resolved to a runner with macOS 13 (13.6.3), but according to [this docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners) it supposed to be macOS 12.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240114.1

### Is it regression?

With all the image renames it is hard to say

### Expected behavior

`macos-latest-large` gets resolved to macOS 12 (per documentation)

### Actual behavior

`macos-latest-large` gets resolved to macOS 13

### Repro steps

* use `runs-on: macos-latest-large`
* see the "Set up job" -> "Operating System"

**Comment by mikhailkoliada** [comment]
Hey! do you have a workflow run url? (no matter public or not?)

**Comment by Vyazovoy** [comment]
> Hey! do you have a workflow run url? (no matter public or not?)

Hi, @mikhailkoliada! Sure, here is [a link](https://github.com/sqsp/ios-ci-cd-tools/actions/runs/7758368155/job/21159977465)

**Comment by MaksimZhukov** [comment]
Hello @Vyazovoy!
Unfortunately, we do not have access to the repository you provided.

**Comment by mikhailkoliada** [comment]
`macos-latest-large` indeed points at `macos-13`.

cc @Steve-Glass for updates on documentation.

**Comment by mikhailkoliada** [comment]
Documentation update has been merged as I see, thanks! Nice catch!

**Comment by Vyazovoy** [comment]
@mikhailkoliada, I see the [corrected docs on site](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners) but it would be good to update [README](https://github.com/actions/runner-images#available-images) of this repo as well.
