### ISSUE TITLE
Passwordless sudo not working on ubuntu-latest

### ISSUE THREAD

**Issue by siddvenk** [actions/runner-images#9303]
### Description

We have recently encountered issues with passwordless sudo on the `ubuntu-latest` runner image. 

We leverage sudo on ubuntu-latest in quite a few of our workflows, but we are only experiencing this issue in a single workflow.

Our workflow did not change between the previous successful runs, and the recent failed runs. The only changes I see are to the image and version used by the runner.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Latest Successful Run:
- https://github.com/deepjavalibrary/djl/actions/runs/7457259653
- Image: ubuntu-22.04
- Version: 20231217.2.0

Sample Failed Run:
- https://github.com/deepjavalibrary/djl/actions/runs/7470948230/job/20330430308
- Image: ubuntu-22.04
- Version: 20240107.1.0

### Is it regression?

yes

### Expected behavior

Passwordless sudo should work.

### Actual behavior

Passwordless sudo does not work (though we have other workflows where it does work using the same ubuntu-latest runner image)

### Repro steps

This is the workflow that we are seeing the issue in https://github.com/deepjavalibrary/djl/blob/master/.github/workflows/native_jni_s3_pytorch_android.yml#L29.

To reproduce, I think one could create a new workflow that runs the steps through the "Install NDK" step (nothing prior to that relies on the repo or custom resources/permissions)

**Comment by mikhailkoliada** [comment]
@siddvenk hey, does the path you try to call with sudo really exist?

**Comment by siddvenk** [comment]
That may be the issue, did the location of the Android SDK manager change between the runner versions I linked above?

It seems like it may have based on what I can parse from https://github.com/actions/runner-images/issues/8952. 

I will test that and report back.

**Comment by mikhailkoliada** [comment]
It might be a combination of non-existing path + sudo bug described [here](https://github.com/actions/runner-images/issues/9146#issuecomment-1887150134)

**Comment by siddvenk** [comment]
Yes, that was exactly the issue. Thanks for the quick response!
