### ISSUE TITLE
PATH env var duplicated in /etc/environment

### ISSUE THREAD

**Issue by mhever** [actions/runner-images#9307]
### Description

the line
```add_etc_environment_variable "PATH" "${ENVPATH}"```
in file images/ubuntu/scripts/build/configure-system.sh duplicates the PATH in the /etc/environment file, once with quotes, once without. Possibly the add_etc_environment_variable should be the replace variant.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

for example ubuntu22/20240201 or any recent ubuntu stable release

### Is it regression?

-

### Expected behavior

Only one PATH entry in /etc/environment, without quotes

### Actual behavior

/etc/environment for example contains two PATH entries
PATH="/snap/bin:$HOME/.local/bin:/opt/pipx_bin:$HOME/.cargo/bin:$HOME/.config/composer/vendor/bin:/usr/local/.ghcup/bin:$HOME/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
PATH=/snap/bin:$HOME/.local/bin:/opt/pipx_bin:$HOME/.cargo/bin:$HOME/.config/composer/vendor/bin:/usr/local/.ghcup/bin:$HOME/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

### Repro steps

build an ubuntu-20 or ubuntu-22 image

**Comment by MaksimZhukov** [comment]
Hello @mhever! 
Thank you for reporting this! 
We will investigate it

**Comment by mikhailkoliada** [comment]
Deployed to production!
