### ISSUE TITLE
Ubuntu22 libssl version changed

### ISSUE THREAD

**Issue by mhever** [actions/runner-images#9309]
### Description

https://github.com/actions/runner-images/blob/5d5f63b19a6bfedd8ef26f5cbbafe342790a7c51/images/ubuntu/scripts/build/install-sqlpackage.sh#L13C44-L13C136
the ubuntu22 libssl package version is changed now:
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Any ubuntu22 stable release

### Is it regression?

no

### Expected behavior

Download the current version

### Actual behavior

Tries to download a non-existant version

### Repro steps

Build any ubuntu22 recent release

**Comment by mhever** [comment]
Seems to be a duplicate of https://github.com/actions/runner-images/pull/9306

**Comment by mikhailkoliada** [comment]
Fixed, please sync your main.
