### ISSUE TITLE
Failing Windows Action after image upgraded to 20240128.1.0 for Windows Server 2022

### ISSUE THREAD

**Issue by pratik-fractl** [actions/runner-images#9315]
### Description

Hi,

We have a repository called [Fractl](https://github.com/fractl-io/fractl) where we have bunch of actions
like test-clj which runs on ubuntu-latest and windows-latest.

The problem now is, the same Action which was running without any change on codebases, is working
for ubuntu-latest but, failing for windows-latest. We do, have some community based Marketplace
actions for support of Clojure and Leiningen, but, upon our debugging we tested that, bumping the versions
of the community actions, Java action/version wasn't the culprit.

The issue can be seen [here](https://github.com/fractl-io/fractl/actions/runs/7796190195/job/21260395352?pr=1221).

We had Windows image version of 20240122.1.0 up-to which the Action was running successfully:
https://github.com/fractl-io/fractl/actions/runs/7690993525/job/20955621629#step:1:9

But, after the image version upgrade, it started failing:
https://github.com/fractl-io/fractl/actions/runs/7739791345/job/21147818105#step:1:9

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Previous successful link:
https://github.com/fractl-io/fractl/actions/runs/7690993525/job/20955621629#step:1:9

Failing link:
https://github.com/fractl-io/fractl/actions/runs/7739791345/job/21147818105#step:1:9

### Is it regression?

yes, image version: 20240122.1.0

### Expected behavior

Passing Action, as there isn't any breaking change happening on the Action for it.

### Actual behavior

We are now receiving, java.lang.ClassNotFoundException for previously successfully running jars. The jars haven't gone through breaking changes.

### Repro steps

Step 1: From the action, re-trigger the run.
Step 2: It fails for Windows.

**Comment by MaksimZhukov** [comment]
Hello @pratik-fractl!
Thank you for the reporting this!
We will investigate the issue and contact you as soon as we have any updates

**Comment by MaksimZhukov** [comment]
The issue was caused by updating the PowerShell version. Please find details in the [related announcement](https://github.com/actions/runner-images/issues/9115). 
To mitigate the issue, please downgrade PowerShell version:
```yml
      - name: Downgrade PowerShell
        shell: cmd
        run: |
          set "extractPath=C:\Program Files\PowerShell\7"
          curl -sLO https://github.com/PowerShell/PowerShell/releases/download/v7.2.17/PowerShell-7.2.17-win-x64.zip
          RMDIR "%extractPath%" /S /Q
          7z x PowerShell-7.2.17-win-x64.zip -o"%extractPath%"
          pwsh --version
```
or use `cmd` as default shell:
```yml
defaults:
  run:
    shell: cmd
```

**Comment by pratik-fractl** [comment]
Thank you. 🙏
