### ISSUE TITLE
Precompiled PYPY Python binary in Ubuntu 22 breaking: ImportError: libffi.so.7: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by loginvarun** [actions/runner-images#9318]
### Description

 /opt/hostedtoolcache/Python/3.9.18/x64/bin/python -m pip install --upgrade pip pipenv

errored out:
`  ImportError: libffi.so.7: cannot open shared object file: No such file or director`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Description:	Ubuntu 22.04.3 LTS

### Is it regression?

--

### Expected behavior

 /opt/hostedtoolcache/Python/3.9.18/x64/bin/python -m pip install --upgrade pip pipenv

above command should complete successfully.

### Actual behavior

` /opt/hostedtoolcache/Python/3.9.18/x64/bin/python -m pip install --upgrade pip pipenv` errored out:

`   from _ctypes import Union, Structure, Array
      ImportError: libffi.so.7: cannot open shared object file: No such file or directory
      [end of output] `

### Repro steps

Run the below command in machine with Ubuntu 22 OS:
` /opt/hostedtoolcache/Python/3.9.18/x64/bin/python -m pip install --upgrade pip pipenv`

**Comment by MaksimZhukov** [comment]
Hello @loginvarun!
The command works as expected ([link to the test workflow run](https://github.com/MaksimZhukov/test-repo/actions/runs/7831308684/job/21367329344)). Please check your workflow for mistakes.
