### ISSUE TITLE
Update/Add PHP 8.3

### ISSUE THREAD

**Issue by michaelLoeffelmann** [actions/runner-images#9323]
### Tool name

PHP

### Tool license

BSD

### Add or update?

- [X] Add
- [ ] Update

### Desired version

8.3

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by PatrickMessierGoC** [comment]
@michaelLoeffelmann The ubuntu 20.04 runner image currently has PHP 7.4.33, 8.0.30, 8.1.27, 8.2.15 and 8.3.3 installed althouth only PHP 7.4 is officially available through Ubuntu package archive. Is this a change in direction/strategy from Azure? What's the rational and what should we expect from upcoming Ubuntu 24.04 runner image? Thanks for sharing your thoughts.
