### ISSUE TITLE
[All OSes] Go 1.19.x will be removed and 1.21.x set as default on February, 26

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9326]
### Breaking changes

Go 1.19.x will be removed from all OSes and 1.21.x will be set as default.

### Target date

Image deployment is starting on February 26 and will take 3-4 days.

### The motivation for the changes

As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.

### Possible impact

If your builds depend on Go 1.19.x they can be broken.

### Platforms affected

- [x] Azure DevOps
- [x] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [x] macOS 11
- [X] macOS 12
- [x] macOS 13
- [x] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

https://github.com/actions/setup-go action for GH actions
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops task for AzDO

**Comment by Eianaftyio** [comment]
.diff
