### ISSUE TITLE
[All OSes] Ruby versions <= 2.7.x will be removed on February, 26

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9327]
### Breaking changes

Toolcache Ruby versions <= 2.7.x will be removed from the images on February, 26.

### Target date

Image deployment is starting on February 26 and will take 3-4 days.

### The motivation for the changes

All versions <= 2.7.x were EOLed more than a year [ago](https://endoflife.date/ruby). We would like to remove long-term unsupported versions.

### Possible impact

if your workflows / pipeline depennd on Ruby versions <= 2.7.x they might become broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Nothing is required.

**Comment by Vyazovoy** [comment]
As a "Mitigation ways" I would recommend to just use [setup-ruby](https://github.com/ruby/setup-ruby) action if someone needs super old Ruby version.
