### ISSUE TITLE
Update to Android NDK r26c

### ISSUE THREAD

**Issue by Javernaut** [actions/runner-images#9342]
### Tool name

Android NDK

### Tool license

Same as before

### Add or update?

- [ ] Add
- [X] Update

### Desired version

r26c aka 26.2.11394342

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
Hello @Javernaut , The new NDK version will be released in the next image version.
