### ISSUE TITLE
android emulator issue in windows 2019 and 2022 runner

### ISSUE THREAD

**Issue by Kiranksk** [actions/runner-images#9343]
### Description

1. we are using below script to start the emulator.   
2. _**List AVDs**_ not giving any results.
3. Error: ﻿no is not a valid reply ERROR coming   when it prompts "Do you wish to create a custom hardware profile?"

$SDK = "${env:ANDROID_HOME}\cmdline-tools\latest\bin\sdkmanager"
$AVD = "${env:ANDROID_HOME}\cmdline-tools\latest\bin\avdmanager"
$EMU = "${env:ANDROID_HOME}\emulator\emulator"
$ADB = "${env:ANDROID_HOME}\platform-tools\adb"
$NAME_EMU = "android_emulator"
$IMG_EMU = "system-images;android-33;google_apis;x86_64"
& $SDK --install $IMG_EMU
echo no | & $AVD create avd -n $NAME_EMU -k $IMG_EMU --force
Write-Host "List AVDs:"
**& $EMU -list-avds**       
Start-Process $EMU -ArgumentList "-avd $NAME_EMU -no-snapshot -no-window -no-audio -no-boot-anim" -NoNewWindow -PassThru
& $ADB wait-for-device
& $ADB shell { while($null -eq $(getprop sys.boot_completed)) { Start-Sleep -Seconds 1 }; input keyevent 82 }
& $ADB devices
& $ADB exec-out screencap -p > emulator.png

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image Provisioner
2.0.341.1
Current image version: '20240211.1.0'

### Is it regression?

yes

### Expected behavior

not sure

### Actual behavior

- _**List AVDs**_ not giving any results.
- Error: ﻿no is not a valid reply ERROR coming   when it prompts "Do you wish to create a custom hardware profile?"

### Repro steps

run it with below script

$SDK = "${env:ANDROID_HOME}\cmdline-tools\latest\bin\sdkmanager"
$AVD = "${env:ANDROID_HOME}\cmdline-tools\latest\bin\avdmanager"
$EMU = "${env:ANDROID_HOME}\emulator\emulator"
$ADB = "${env:ANDROID_HOME}\platform-tools\adb"
$NAME_EMU = "android_emulator"
$IMG_EMU = "system-images;android-33;google_apis;x86_64"
& $SDK --install $IMG_EMU
echo no | & $AVD create avd -n $NAME_EMU -k $IMG_EMU --force
Write-Host "List AVDs:"
**& $EMU -list-avds**       
Start-Process $EMU -ArgumentList "-avd $NAME_EMU -no-snapshot -no-window -no-audio -no-boot-anim" -NoNewWindow -PassThru
& $ADB wait-for-device
& $ADB shell { while($null -eq $(getprop sys.boot_completed)) { Start-Sleep -Seconds 1 }; input keyevent 82 }
& $ADB devices
& $ADB exec-out screencap -p > emulator.png

**Comment by Alexey-Ayupov** [comment]
Hello @Kiranksk, we will take a look.

**Comment by Alexey-Ayupov** [comment]
Hi @Kiranksk. Have you tried to run you PowerShell task with the `pwsh: true` parameter?

```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
```

It gives me this result:
![image](https://github.com/actions/runner-images/assets/116575425/6157e0f8-a90d-4ad1-91fd-0ede3007d106)

**Comment by Kiranksk** [comment]
Thanks for the finding @Alexey-Ayupov


 It moved further

**Comment by Alexey-Ayupov** [comment]
@Kiranksk , I will close this issue since we have found a workaround.
If you have any other questions feel free to reach us.
