### ISSUE TITLE
macOS runners: Connection refused by host '127.0.0.1' port '8086'

### ISSUE THREAD

**Issue by mrcalvin** [actions/runner-images#9346]
### Description

The Tcl network I/O command socket cannot connect to 127.0.0.1 on port 8086. Connection refused by host '127.0.0.1' port '8086'. This happens on all macOS runners, except for one (see below).

The port is unused (via `sudo lsof -PiTCP -sTCP:LISTEN`), before the test suite runs:

`COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME launchd 1 root 7u IPv6 0x2512f6607ec87ef5 0t0 TCP *:22 (LISTEN) launchd 1 root 8u IPv4 0x2512f660808df655 0t0 TCP *:22 (LISTEN) launchd 1 root 11u IPv6 0x2512f6607ec87ef5 0t0 TCP *:22 (LISTEN) launchd 1 root 12u IPv4 0x2512f660808df655 0t0 TCP *:22 (LISTEN) launchd 1 root 14u IPv6 0x2512f6607ec885f5 0t0 TCP *:5900 (LISTEN) launchd 1 root 16u IPv4 0x2512f660808e00fd 0t0 TCP *:5900 (LISTEN) launchd 1 root 18u IPv6 0x2512f6607ec885f5 0t0 TCP *:5900 (LISTEN) launchd 1 root 19u IPv4 0x2512f660808e00fd 0t0 TCP *:5900 (LISTEN) kdc 130 root 5u IPv6 0x2512f6607ec88cf5 0t0 TCP *:88 (LISTEN) kdc 130 root 7u IPv4 0x2512f660808dd655 0t0 TCP *:88 (LISTEN)`

It tried making localhost available by setting:

`sudo networksetup -setdnsservers Ethernet 9.9.9.9`

See https://github.com/actions/runner-images/issues/6383;  no effect.

Also, I switched from using `localhost` to loopback IPv4 `127.0.0.1`; no effect

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.313.0 in https://github.com/nm-wu/nsf/actions/runs/7894266756/job/21544574117

### Is it regression?

https://github.com/nm-wu/nsf/actions/runs/6175609365/job/16762837091

### Expected behavior

```
run: SimpleRequest r0 -url http://127.0.0.1:8086/logo-100.jpg
running test 1 times
xocomm/test.001: Trying to load image logo-100.jpg ...  ok

```
See https://github.com/nm-wu/nsf/actions/runs/7894266756/job/21544573512 ... it works on this one job, for the same runner and image version ? The last jobs executing successfully date back five months ago, logs are not available anymore: https://github.com/nm-wu/nsf/actions/runs/6175609365/job/16762837091, sigh.

### Actual behavior

The test fails:

```
run: SimpleRequest r0 -url http://127.0.0.1:8086/logo-100.jpg
!!!::req1 (2): Connection refused by host '127.0.0.1' port '8086'
 error flushing "sock7f88ebaebd90": socket is not connected!!!
xocomm/test.001:	incorrect result for 'Trying to load image logo-100.jpg ... ', expected:
```

### Repro steps

See the build steps in the [workflow script](https://github.com/nm-wu/nsf/blob/14a7986b5ce0fab858adda0af69e524c52a32296/.github/workflows/build.yml#L140).

**Comment by Alexey-Ayupov** [comment]
Hello @mrcalvin, we will take a look.

**Comment by mrcalvin** [comment]
@shamil-mubarakshin this is a cure, thank you! Could you share some background info about this?

**Comment by shamil-mubarakshin** [comment]
@mrcalvin, it might be related to https://github.com/actions/runner-images/issues/8649 and lookup issues. It is being looked at, but unfortunately, we don't have ETA on a long term fix as of yet.
Happy workaround helps! I will close the issue for now, feel free to reach out in case of further concerns.
