### ISSUE TITLE
Docker runc, BuildKit, and Moby CVE not fixed in Ubuntu runner image

### ISSUE THREAD

**Issue by gfallerBCAG** [actions/runner-images#9349]
### Description

For Docker there are multiple vulnerabilities in runc, BuildKit, and Moby. Docker fixed this and released new versions of runc, Buildkit and Moby. The current version of Ubuntu  20.04/22.04 does not use the latest (fixed) version of these components.

Currently used: 
Docker-Buildx 0.12.1
Docker Client 24.0.7
Docker Server 24.0.7

Should be:
Docker-Buildx > 0.12.4
Docker Client > 24.0.8
Docker Server > 24.0.8

https://www.docker.com/blog/docker-security-advisory-multiple-vulnerabilities-in-runc-buildkit-and-moby/

Regards

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240212.2.0
20240212.1.0

### Is it regression?

no

### Expected behavior

update to 
Docker-Buildx > 0.12.4
Docker Client > 24.0.8
Docker Server > 24.0.8

### Actual behavior

Docker-Buildx 0.12.1
Docker Client 24.0.7
Docker Server 24.0.7

### Repro steps

run image

**Comment by Alexey-Ayupov** [comment]
Thank you @gfallerBCAG, we will take a look.

**Comment by gfallerBCAG** [comment]
Hey @Alexey-Ayupov  this issue is not fixed, yet. 
The version needs to be > 24.0.8 
https://github.com/moby/moby/releases/tag/v24.0.9
Im not aware of the other dependencies in this image but it seems not all vulnerabilities are fixed in this version 24.0.9
the recommendation is to go to 25.0.2 or 25.0.3

**Comment by mikhailkoliada** [comment]
deployed now
