### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by nateaskoffdbp** [actions/runner-images#9357]
### Tool name

AWSPowerShell Module

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

AWS.Tools.* Modules

### Brief description of tool

The windows-latest github runner image comes pre-installed with the 'AWSPowerShell' module by default. This module contains over 12,000 commands, and has been deprecated by Amazon for some time now in favor of the newer 'AWS.Tools.*' modules, which are broken down by AWS service and thus, much faster to load and use.

As one example, when issuing the 'Get-ECRLoginCommand' cmdlet, it takes nearly _**four minutes**_ to load the AWSPowerShell module, whereas it takes only a few seconds when using the AWS.Tools.ECR module. Unfortunately, before this can occur one needs to uninstall the AWSPowerShell module, and install the correct module, which still slows things down.

### URL for tool's homepage

https://aws.amazon.com/powershell/

### Provide a basic test case to validate the tool's functionality.

```bash
# Test module import and command
Import-Module AWSPowerShell
Get-ECRLoginCommand <parameters>

# Test modular tools import and command
Import-Module AWS.Tools.ECR
Get-ECRLoginCommand <parameters>
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
This update would easily be accomplished by removing AWSPowerShell from the image build and instead using:

`Get-Module -Name AWS.Tools.* | For-EachObject { Install-Module -Name $_.Name -Scope AllUsers -Confirm:$false -Force -AllowClobber`
```

### Tool installation time in runtime

A few minutes, as there are quite a few modules and more being made / updated every day.

### Are you willing to submit a PR?

I will review the builds and consider doing so

**Comment by mikhailkoliada** [comment]
Hello! We would not like pre-install tools modules due to maintenance concerns, was recommends installing AWSPowerShell over tools.* if one still needs the full set of commands rather than installing the whole collection of Tools subset, it might be reconsider though if AWS finally decides to drop the whole AWSPowerShell forcibly which is outside any foreseeable time frame it seems.
