### ISSUE TITLE
Update CMake

### ISSUE THREAD

**Issue by Ravbug** [actions/runner-images#9358]
### Tool name

CMake

### Tool license

BSD-3

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.28.3 or higher (Fixes some visionOS issues)

### URL for tool's homepage

http://cmake.org/download

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Alexey-Ayupov** [comment]
Hello @Ravbug, CMake will be updated in the next releases. Our nightly builds already have the latest version.

**Comment by Ravbug** [comment]
Is there any ETA on when this will release to stable?

**Comment by mikhailkoliada** [comment]
this has been deployed
