### ISSUE TITLE
Update/Add [Strawberry Perl]

### ISSUE THREAD

**Issue by xavier2k6** [actions/runner-images#9360]
### Tool name

Strawberry Perl

### Tool license

https://github.com/StrawberryPerl/Perl-Dist-Strawberry?tab=License-1-ov-file

### Add or update?

- [ ] Add
- [X] Update

### Desired version

5.38.2.2

### Brief description of tool

Strawberry Perl is a perl environment for MS Windows containing all you need to run and develop perl applications. It is designed to be as close as possible to perl environment on UNIX systems.

### URL for tool's homepage

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by mikhailkoliada** [comment]
Hey! Given that stbwperl's bundled mingw implementation tends to break lots of customers we would not like to update mingw as a whole.
