### ISSUE TITLE
Large macOS runners are pointing to unpaid versions of macOS runners

### ISSUE THREAD

**Issue by akhilamoyila9** [actions/runner-images#9364]
### Description

We have adjusted our workflows to utilize large macOS 12 runners by specifying the label "macos-12-large". However, it appears that the workflow is still utilizing the unpaid version macOS 12 [OS Version: macOS 12.7.2 (21G1974)], leading to a **"The machine is in the 'gurumeditation' state"** error again. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/magma/magma/actions/runs/7890640681/job/21533252478

### Is it regression?

https://github.com/magma/magma/actions/runs/7019943006/job/19126552806

### Expected behavior

It should utilize the macOS-12 large runner 

### Actual behavior

![image](https://github.com/actions/runner-images/assets/136717650/f19176b8-6d23-4e68-a7cc-448bd58196e4)

### Repro steps

Workflow file : https://github.com/magma/magma/blob/master/.github/workflows/sudo-python-tests.yml

**Comment by sergei-pyshnoi** [comment]
Hello @akhilamoyila9 . You problem not connected with large or standard runners (we checked your run and it was running on `macos-12-large` agent). However  `The machine is in the 'gurumeditation' state` error comes from low nested performance on new runners. More information you can find in similar [issue here ](https://github.com/actions/runner-images/issues/8730) .

**Comment by akhilamoyila9** [comment]
Hi @sergei-pyshnoi As suggested by @erik-bershel , if we utilize larger runners, they should support nested virtualization, as mentioned in https://github.com/actions/runner-images/issues/8730#issuecomment-1824248825."

**Comment by erik-bershel** [comment]
Hey @akhilamoyila9! As I said in mentioned comment:
> We recommend using larger **linux** runners for workflows that require nested virtualization.

Linux but not macOS. Currently we are not support directly nested on macOS due to platform related limitations.
