### ISSUE TITLE
Update on LCM for Xcode15

### ISSUE THREAD

**Issue by superjamel** [actions/runner-images#9366]
### Tool name

Azure DevOps

### Tool license

none

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Xcode 15

### Brief description of tool

When is the support added for runner images when building with Xcode 15, using the latest image for Azure DevOps pipeline. 
Is there any specific LCM when we can expect macOS 14 [beta] to be GA for production ready deployments?

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @superjamel . Unfortunately we cannot provide estimates about MacOS 14 for ADO. You can find more information about current images and recent updates for ADO in [this documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software).
