### ISSUE TITLE
Add sbt to macOS 13, 14

### ISSUE THREAD

**Issue by armanbilge** [actions/runner-images#9369]
### Tool name

sbt

### Tool license

Apache-2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

sbt is a build tool commonly used for Scala projects. It is already available in the macOS 11 and 12 images, but is missing from 13 and 14 for some reason.

### URL for tool's homepage

https://www.scala-sbt.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by sergei-pyshnoi** [comment]
Hello @armanbilge . We do not have plans for adding `sbt` package to MacOS 13, 14 images for now. You cant install it in runtime using `brew install sbt`  (approximate installation time  ~8-9 sec).

**Comment by robstoll** [comment]
out of curiosity what is the reason? too big ?

**Comment by mkurz** [comment]
> out of curiosity what is the reason? too big ? What were the bad experiences in macOS 11 and 12 ?

See https://github.com/actions/runner-images/issues/9837#issuecomment-2107335260

**Comment by eed3si9n** [comment]
I've created sbt/setup-sbt to workaround this - https://eed3si9n.com/setup-sbt/.
