### ISSUE TITLE
PKI module fails to import (Windows Server 2022 version 20240204.1.0)

### ISSUE THREAD

**Issue by sfoslund** [actions/runner-images#9381]
### Description

My teammate recently filed https://github.com/actions/runner-images/issues/9331, which was closed as not reproducible, but we are continuing to see this issue in a different pipeline with an updated version of this image. We were able to fix the original pipeline by downgrading to an older image version that was based on an older/working version of this image. However, for this new failing pipeline, we are unable to downgrade and this issue is now blocking. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Experiencing issue in version: 20240204.1.0

Unable to provide build links as our product is not public.

### Is it regression?

Yes

### Expected behavior

We expect PowerShell to be able to import necessary modules as usual.

### Actual behavior

PKI module is inexplicably unable to be loaded.

### Repro steps

Run `Import-PfxCertificate`

**Comment by sergei-pyshnoi** [comment]
Hello @sfoslund . We tried to import module and invoke `Import-PfxCertificate` in pipeline using example from [previous issue](https://github.com/actions/runner-images/issues/9331#issuecomment-1941619366) and got no errors. We used upcoming image version `20240218.2` . Rollout will finished by the end of this week (possible that you already receive new image version in your pipeline) .

**Comment by mikhailkoliada** [comment]
@jlperkins hey! Are you using 1es hosted pools or the standard azure pipelines ones?

**Comment by mikhailkoliada** [comment]
After more precise look we decided to close this issue as non-images one and the reasoning is:

1. in your snippet you are using `pwsh` as a shell, while PKI module is a native powershell 5 module, it is not mandatory but may cause additional troubles of not being compatible between v7 (pwsh) and v5 (classic powershell) (though they are supposed to be interchangeable in this specific case, I would be cautious when calling it from within node)
2. The ```The module to process 'Microsoft.CertificateServices.PIClient.mdlets',listed in field 'NestedModules' of module manifest 'C: \WINDOWS \system32 \windowsPowerShell\v1.0\Modules\P
KI\PKIpsd1' was not processed because no valid module was found in any module directory.``` error does mean that the shell you spin from within nodes is _not_ aware of any environmental variables it should have, namely it looks like it does not know anything about the `$PSModulePath` which contains the paths of the modules powershell gonna scan on the module import invocation, if you perform `Import-Module -Name PKI -Verbose` you will see that it tries to reach the `PKI.psd1` file exactly on the path from your error
3. Why is it happening in your code... I am not a nodes guru but as of child process documentation and exec functionality, the `exec` invocation spawns a new shell inside the nodes process whereas this shell is not aware / doesn't inherit any environment variables (and, possibly other settings) from its parent, it looks like you need to experiment with the different `child_process` modes like SpawnProcess, etc.

**Comment by jalkire** [comment]
In case anyone else comes across this problem, our issue stemmed from a change in PowerShell 7.4.1, which was included in the image update. A workaround is to set the `PSModulePath` env variable when running commands with `pwsh -command <command>` (which node was using under the hood), for example:
`pwsh -c { $env:PSModulePath = [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine') ; Import-Module PKI }`
