### ISSUE TITLE
NDK 26.1.10909125 not available on some runner images

### ISSUE THREAD

**Issue by jamilbk** [actions/runner-images#9387]
### Description

We're getting flaky "NDK is not installed" failures over at https://github.com/firezone/firezone. We use NDK 26.1.10909125.

Started happening yesterday after an Ubuntu-22.04 runner update.

Example passing:

https://github.com/firezone/firezone/actions/runs/7983048215

Example failing:

https://github.com/firezone/firezone/actions/runs/7983050727

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.313.0

### Is it regression?

Seems so, but it's intermittent.

### Expected behavior

Expect NDK 26.1.10909125 to be installed.

### Actual behavior

Seems to be missing. [Tried overriding ANDROID_NDK_HOME and ANDROID_NDK with the path explicitly](https://github.com/firezone/firezone/actions/runs/7992402004/job/21825820184), which still failed.

### Repro steps

Hard to reproduce, because the issue is intermittent.

**Comment by sergei-pyshnoi** [comment]
Hello @jamilbk . NDK 26.1.10909125 was removed with new image version. You can find image diff [in releases](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240218.1) .
