### ISSUE TITLE
Julia and R are removed from macos-14-arm64?

### ISSUE THREAD

**Issue by eitsupi** [actions/runner-images#9394]
### Description

It seems that these language runtimes were suddenly removed, but since there was no information about updates, I wasn't sure if this was intentional.
#9377
https://github.com/actions/runner-images/commit/c30352657a48f6fe8bf88c47ed89902113988192#diff-5c04a529d3c8adf7a5f23afe544071dad1853e281c9c7b44cd8d626b6c57444dL19-L24

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/commit/c30352657a48f6fe8bf88c47ed89902113988192#diff-5c04a529d3c8adf7a5f23afe544071dad1853e281c9c7b44cd8d626b6c57444dL19-L24

### Is it regression?

No

### Expected behavior

These runtimes are included.

### Actual behavior

These runtimes are not included.

### Repro steps

NA

**Comment by sergei-pyshnoi** [comment]
Hello @eitsupi . Thanks for your report but we remove Julia and R from MacOS 14 due maintain concern. Please remember that MacOS 14 in beta now so possible changes  like can this can persist.

**Comment by eitsupi** [comment]
> Hello @eitsupi . Thanks for your report but we remove Julia and R from MacOS 14 due maintain concern. Please remember that MacOS 14 in beta now so possible changes like can this can persist.

@sergei-pyshnoi Thanks for the reply.
Does that mean Julia and R will likely be permanently removed from macos-14?
Also is it likely that Julia and R will be removed from other images in the future?

I think that this should be documented, as the removal of a previously usable tool without any announcement could cause confusion.

**Comment by IanButterworth** [comment]
Indeed. At least this should be documented as a difference, not just omitted from the list. 

Ideally though they should be installed. I am personally most interested in julia and can provide help maintaining Julia installation.
