### ISSUE TITLE
Latest windows 2022 image 20240218.2.0 has same flaw as latest Visual Studio 2022 17.9 version, dacpac deploys fail unable to resolve file references

### ISSUE THREAD

**Issue by HanoRossouw** [actions/runner-images#9396]
### Description

We noticed from today our sql builds and dacpac deploys started failing on the Azure Devops Hosted Agent build environments. The same pipeline on windows 2019 works correctly but on 2022 the SqlPackage process is unable to resolve file references and the deploys keep failing, we have inspected multiple commits and the issue seems to be unrelated to our code changes. We did notice from a build that worked earlier in the week the VM image has changed to the latest one.

Issue reported on Visual Studio and dacpac failure https://developercommunity.visualstudio.com/t/SQL72025-after-upgrading-to-Visual-Studi/10584742?sort=active&topics=Known+Issue+in%3A+Visual+Studio+2017+Version+15.5

Last working build was on windows-2022 build image version 20240211.1.0

Builds started to fail from version 20240218.2.0
![image](https://github.com/actions/runner-images/assets/161013196/d72c4ba6-2d8f-4f35-8d91-83289cc68d75)
![db deploy failure](https://github.com/actions/runner-images/assets/161013196/75a2063b-7d3d-4e44-8222-421535f68f5c)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image
Image: windows-2022
Version: 20240218.2.0
Included Software: https://github.com/actions/runner-images/blob/win22/20240218.2/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240218.2
Runner Image Provisioner
2.0.341.1
Current image version: '20240218.2.0'

### Is it regression?

no

### Expected behavior

I expect the build process and dacpac deploys through SqlPackage.exe to correctly resolve file reference dependencies.

### Actual behavior

Dacpac deploys are unable to resolve file reference dependencies and deploys fail

### Repro steps

Build any sql project in latest visual studio 17.9 version msbuild process that has file references to dacpac files. Then attempt to deploy the top level built dacpac using a SQL Server database deploy task to sql localdb.

We tested using a sql task like Deploy SQL Server database and also using powershell and invoking SqlPackage.exe to perform the deploy and both result in the same failure

**Comment by janelhunt** [comment]
I confirm also that our Azure DevOps Sql Server Database Builds with Microsoft Hosted Agent have started to fail since 
Windows Server 2022 Image version 20240218.2.0 was released.

Our database projects in Visual Studio 2022 built successfully until this new Image version was used by the Microsoft Hosted Agent.

The **MSBuild Version** on this new image **changed to 17.9.5.7688** from 17.8.5.5502 causing error SQL72025.
_##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets(542,5): Error SQL72025: No file was supplied for reference master.dacpac; deployment might fail. When package was created, the original referenced file was located MASTER.DACPAC.
2024-02-22T14:18:51.7473202Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets(542,5): Build error SQL72025: No file was supplied for reference master.dacpac; deployment might fail. When package was created, the original referenced file was located MASTER.DACPAC. [D:\a\1\s\DataWarehouse\DNADataWarehouse\DataWarehouseSQLDB\DataWarehouseSQLDB.sqlproj]
2024-02-22T14:18:52.1532640Z Done Building Project "D:\a\1\s\DataWarehouse\DNADataWarehouse\DataWarehouseSQLDB\DataWarehouseSQLDB.sqlproj" (default targets) -- FAILED._

This same SQL72025 error was reported in the Visual Studio Developer community concerning using Visual Studio 2022 version 17.9.
[](https://developercommunity.visualstudio.com/t/SQL72025-after-upgrading-to-Visual-Studi/10584742?sort=active&topics=Known+Issue+in%3A+Visual+Studio+2017+Version+15.5&viewtype=all)

**Comment by sergei-pyshnoi** [comment]
Hello @HanoRossouw . We will take a look.

**Comment by mikhailkoliada** [comment]
We are installing a singltone sqlpackage here `$env:ProgramFiles\Microsoft SQL Server\160\DAC\bin\sqlpackage.exe` has anybody tried using this as a workaround?

**Comment by HanoRossouw** [comment]
> We are installing a singltone sqlpackage here `$env:ProgramFiles\Microsoft SQL Server\160\DAC\bin\sqlpackage.exe` has anybody tried using this as a workaround?

Other than referenced packages, even master.dacpac reference is not resolving so singleton packages which just need to build something but make use of any of the built in system tables are also is unable to deploy. Our workaround for now is to build on our self hosted server which happens to be running an older version of Visual studio 2022 and latest SQL server 2019

**Comment by barnum1** [comment]
Hi.
Does anyone have an estimate for when this will be fixed?
The fact that Azure build pipeline fails, means that we cannot build any new versions of our product.
So this is critical for us.

**Comment by HanoRossouw** [comment]
> Hi. Does anyone have an estimate for when this will be fixed? The fact that Azure build pipeline fails, means that we cannot build any new versions of our product. So this is critical for us.

If your db project is in a different repo to your latest .Net code, you could use the windows 2019 image as workaround to build unless you are dependent on newer SQL Server 2019 syntax and functionality. Otherwise the only other temporary reliable workaround is to use a self hosted build server like we do which is running older version of Visual Studio 2022 than version 17.9.

**Comment by barnum1** [comment]
Thanks @HanoRossouw for your suggestions.
Unfortunately, the DB project is together with the rest of our .NET code.
And we did try our own build server with an older Visual Studio, but it failed (on .NET versions I believe).

Hope that Microsoft does all it can to fix this. It must affect many customers.
(Although DB-projects always seems to have been down-prioritized by Microsoft - just look for bug reports in VS Community.)

**Comment by HanoRossouw** [comment]
Ensure for the later .NET versions to install the latest .NET sdk versions you require on the build server for .NET 6, 7 or 8

run "dotnet --list-sdks" to check which .NET sdk versions are currently installed.

https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows

https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by barnum1** [comment]
Ok, I will give this advice to our guy working with this, but I suspect he has tried it already.
Thanks!

**Comment by HanoRossouw** [comment]
Some additional context to add, we did some further investigation into the generated dacpacs and compared a dacpac build on the latest image with one generated on our self hosted build server which is running a slightly older version of Visual Studio 2022 Professional.

![image](https://github.com/actions/runner-images/assets/161013196/c0c4120d-2594-459c-b104-daa765e33105)

Here we can see the reference paths we had inside the solution is retained on the right side which is the self hosted build compared to the left side which is the hosted agent's build.

The hosted agent build version has removed the file path references inside the model.xml file which is contained inside the dacpac. The second issue is normally the right side file we then take all the dacpacs and publish them into a folder inside a universal package for shipment, on the server we deploy, sqlpackage.exe does not expect the same reference path structure to perform the deploy its able to read them from the same directory. Now on the build server it expects all dacpacs and reference dacpacs to reside in the exact same folder in order to do the deployment. This was a workaround suggested to us by a microsoft engineer after we opened a support ticket. We still need to validate the workaround actually works but will post again if we can confirm having all dacpacs in the same directory then its able to resolve the file references.

**Comment by HanoRossouw** [comment]
After updating our pipeline to move all referenced dacpacs into the same folder as the top level dacpac then start the deploy, the files are able to resolve. So it can resolve the file references within the same path. So a workaround could be to remodel your pipelines so they first copy all related dacpacs into a common folder before you do any dacpac deployments within the pipelines. However to me i feel still that this is functionality which worked previously it retained the reference path structure and you could deploy in that way or by putting all dacpacs in the same folder like in the universal package.

**Comment by barnum1** [comment]
Thanks again @HanoRossouw for your advice.
We would like to avoid work-arounds though, so we really need Microsoft to fix this.

**Comment by barnum1** [comment]
From Developer Community (https://developercommunity.visualstudio.com/t/SQL72025-after-upgrading-to-Visual-Studi/10584742):
"A fix for this issue has been internally implemented and is being prepared for release. We’ll update you once it becomes available for download."

Good news. Does anyone know how long it usually takes before it is deployed? In this case to the Azure Build Pipeline.

**Comment by mikhailkoliada** [comment]
@barnum1 we deploy weekly, if VS developers claim (I read the recent comment there) that the fix will be available next week, then, in the worst case you can expect the fix to be available no later than March 22nd

**Comment by barnum1** [comment]
Thanks for an update. 
By "we" I guess you refer to the team working with Azure DevOps? As opposed to VS?
As long as VS is fixed, we can run it self-hosted I believe.

**Comment by mikhailkoliada** [comment]
VS 17.9 will be added to the images next week.

**Comment by bheemvennapureddy** [comment]
@mikhailkoliada  can you help us with the timeline for release ?

**Comment by bheemvennapureddy** [comment]
<img width="1312" alt="Screenshot 2024-03-19 at 9 44 07 PM" src="https://github.com/actions/runner-images/assets/144472943/10fdd50b-b119-4981-bc85-21ad23bf32a5">
<img width="993" alt="Screenshot 2024-03-19 at 9 44 16 PM" src="https://github.com/actions/runner-images/assets/144472943/2bad593b-d858-4b9f-880b-7ed514a49f60">

images for reference

**Comment by mikhailkoliada** [comment]
It has been completed, should be available to customers in the next couple of hours.

**Comment by bheemvennapureddy** [comment]
@mikhailkoliada we are still seeing the issue with the new images

**Comment by bheemvennapureddy** [comment]
@barnum1 did this latest image fix the issue for you ?

**Comment by barnum1** [comment]
We have only run this self-hosted with latest VS,
not in the Azure build pipeline. And it works self-hosted.

**Comment by giacomotaba** [comment]
Still getting the error, Image ver 20240317.1.1 with VS 17.9.34701.34

**Comment by HanoRossouw** [comment]
Yes issue is not resolved yet its still occuring on hosted agents.

Current image version: '20240317.1.0'

It still cannot resolve dacpacs to deploy from the same reference paths as they are in the solution when building. 

repo/databases  (here we have our referenced dacpacs)
repo/project/databases  (we deploy from here)

This way of deploying where it retained your reference paths worked perfectly before but since the change the model.xml object that is in the dacpac if you unzip it before the change it had the reference path in the model, after the change the reference path was removed. previously with the reference path present it could either deploy if you had the same folder structure as your referenced paths or if all the dacpacs were in the same folder. Now you are forced to always place everything in the same folder in order to deploy. To me this is not fixed something that worked previously is still no longer working.

**Comment by athompson211** [comment]
Also seeing this same problem with Microsoft hosted build agents in Azure DevOps.
