### ISSUE TITLE
Unable to generate an Ubuntu2204 Image

### ISSUE THREAD

**Issue by micro9000** [actions/runner-images#9400]
### Description

I follow the instruction on manual generation of the image
I used the following PS script and passed my Azure Subscription Id and Resource group

```
param(
    [string]$subscriptionId,
    [string]$resourceGroupName
)
$temporaryDirectory = "C:\AzureDevOpsRunnerImagesRepo"

# Delete the directory and its contents
Remove-Item -Path $temporaryDirectory -Recurse -Force

# Create a new directory
New-Item -ItemType Directory -Path $temporaryDirectory
Set-Location -Path $temporaryDirectory

# Clone the repository
git clone https://github.com/actions/runner-images.git

# Set the working directory
Set-Location runner-images

# Import the module
Import-Module .\helpers\GenerateResourcesAndImage.ps1

# Generate resources and image
GenerateResourcesAndImage -SubscriptionId $subscriptionId -ResourceGroupName $resourceGroupName -ImageType Ubuntu2204 -AzureLocation "East Asia"
```

After waiting for maybe 15mins, it asked me if I want to clean up the resources
Here are the last few logs
```

==> azure-arm.build_image: Provisioning with shell script: C:/AzureDevOpsRunnerImagesRepo/runner-images/images/ubuntu/templates/../scripts/build/install-swift.sh
==> azure-arm.build_image: Downloading package from https://swift.org/builds/swift-5.9.2-release/ubuntu2204/swift-5.9.2-RELEASE/swift-5.9.2-RELEASE-ubuntu22.04.tar.gz to /tmp/swift-5.9.2-RELEASE-ubuntu22.04.tar.gz...
==> azure-arm.build_image: Package downloaded in 5 seconds
==> azure-arm.build_image: Downloading package from https://swift.org/keys/all-keys.asc to /tmp/all-keys.asc...
==> azure-arm.build_image: Package downloaded in 1 seconds
==> azure-arm.build_image: gpg: directory '/root/.gnupg' created
==> azure-arm.build_image: gpg: keybox '/root/.gnupg/swift' created
==> azure-arm.build_image: gpg: no valid OpenPGP data found.
==> azure-arm.build_image: gpg: Total number processed: 0
==> azure-arm.build_image: Script exited with non-zero exit status: 2. Allowed exit codes are: [0]
==> azure-arm.build_image: Step "StepProvision" failed
==> azure-arm.build_image: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
```

I don't know how to fix this

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

It should continue the image generation?

### Actual behavior

It stop the generation

### Repro steps

Just run the PowerShell Script

`.\Initial-Image.ps1 -subscriptionId "<subscription-id>" -resourceGroupName "AzureDevOpsAgentImagesRG"`

**Comment by micro9000** [comment]
I temporary removed the install-swift.sh in ubuntu-22.04.pkr.hcl file so I can continue generating the image since I don't need that for now

**Comment by shamil-mubarakshin** [comment]
Hey @micro9000,
Error is gpg related and seems transient. I have run [ubuntu22 build](https://dev.azure.com/github/runner-images/_build/results?buildId=134874&view=results) and issue cannot be reproduced.
I will close the issue for now. Feel free to reach out in case of further concerns.

**Comment by code-on-git** [comment]
I'm also getting the same error message. I'm running this:
`GenerateResourcesAndImage -SubscriptionId 1234-abcd -ResourceGroupName rg01-image-linux -AzureLocation 'West Europe' -ImageType Ubuntu2204`

When I run the exact same command for Windows2022 it works, but not Ubuntu2204
