### ISSUE TITLE
Windows Server 2022 runner does not have IPv6 connectivity

### ISSUE THREAD

**Issue by jozefizso** [actions/runner-images#9401]
### Description

GitHub hosted cloud runners with Windows Server are not able to communicate with IPv6 hosts.

IPv6 was introduced on December 1995, 28 years ago. We should be able to use it in workflows.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current runner version: '2.313.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20240218.2.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240218.2/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240218.2

### Is it regression?

no

### Expected behavior

I can be able to connect to IPv6 hosts.

### Actual behavior

Cloud runners are able to connect to IPv6 hosts.

### Repro steps

Run this command on Windows Server runners:

```
curl -m 3 -6 https://ifconfig.co/
```

The `curl` will fail with error `curl: (6) Could not resolve host ifconfig.co`.

**Comment by mikhailkoliada** [comment]
Duplicte of https://github.com/actions/runner-images/issues/668

**Comment by jozefizso** [comment]
Hi @mikhailkoliada, I hope you are doing well.

> GitHub hosted cloud runners with Windows Server are not able to communicate with IPv6 hosts.
> IPv6 was introduced on December 1995, 28 years ago. We should be able to use it in workflows.

This issue was not answered.

**Comment by mikhailkoliada** [comment]
@jozefizso hey, we do not support ipv6 for both inbound or outbound ways, so it is expected

**Comment by jozefizso** [comment]
@mikhailkoliada This is not expected for a networking technology which is 28 years old in a world where servers are accessibleusing IPv6.

**Comment by jozefizso** [comment]
> IPv6 is the actual internet protocol, while IPv4 is a legacy protocol. Please, priorize this request.

https://github.com/orgs/community/discussions/10539#discussioncomment-2063601
