### ISSUE TITLE
Update Az PowerShell Module

### ISSUE THREAD

**Issue by SebastianClaesson** [actions/runner-images#9418]
### Tool name

Azure PowerShell Module

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

11.2.0

### URL for tool's homepage

https://github.com/Azure/az-ps-module-versions

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, Already written the code for installation during build.
```

### Tool installation time in runtime

5

### Are you willing to submit a PR?

Yes

**Comment by shamil-mubarakshin** [comment]
Hey @SebastianClaesson, thank you for your contribution!
Unfortunately, we currently do not have plans to update version of AZ module due to maintenance concerns and to avoid potential customer impact. We recommend using [AzurePowerShell@5](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) Azure DevOps task or [Azure powershell](https://github.com/Azure/powershell) action for GitHub Actions to install required versions in runtime.
Thank you for understanding and sorry for the inconvenience!

**Comment by nibanks** [comment]
Hello, my team opened #9705 which was just duplicated to this issues which seems to have been closed as Won't Fix. IMO, that's not acceptable.

> We recommend using [AzurePowerShell@5](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) Azure DevOps task or [Azure powershell](https://github.com/Azure/powershell) action for GitHub Actions to install required versions in runtime.

We are doing something similar [here](https://github.com/microsoft/netperf/actions/runs/8731856592/job/23957931774) but it adds at least 5 to 10 minutes for everyone of our CI runs (which is pretty significant).

```yaml
    - name: Install Latest Az PowerShell Module
      shell: pwsh
      run: |
        Install-Module -Name Az -Force -AllowClobber -Repository PSGallery
        Update-Module Az -Force
        Get-Module 'Az' | where {([string]($_.Version)).StartsWith('9.3.0')} | Remove-Module
        Get-Module -Name Az -ListAvailable
```

> do not have plans to update version of AZ module due to maintenance concerns and to avoid potential customer impact.

IMO, there needs to be an answer here that isn't 'we never update again'. Our automation creates a number of new VMs that we dynamically onboard as new self hosted runners, and that requires commands/versions in the latest version of Az PowerShell. This automation is being built to run the performance test automation of all Windows (networking to start, but more to follow) inbox and undocked/oss components, so scale and performance is of paramount concern for us.

So, I ask that you reopen this issue and reconsider how we can move forward. Thans you!

**Comment by riverar** [comment]
This module appears to be installed incorrectly. `Az` is not compatible with `AzureRM` and both appear to be installed on runners, resulting in a broken experience. (Will open a separate issue.)
