### ISSUE TITLE
Add latest Xamarin to MacOS-13

### ISSUE THREAD

**Issue by David-Sobin** [actions/runner-images#9423]
### Tool name

Xamarin.iOS 

### Tool license

Same as used in MacOS-12 for Xamarin

### Add or update?

- [X] Add
- [X] Update

### Desired version

Xamarin-ios 16.4.0.23

### Brief description of tool

I checked both 'add' button above as well as 'update' because the MacOS-13 Readme shows no Xamarin support at all, while MacOS-12 does have Xamarin.
In particular, we need MacOS-13 support for the latest Xamarin.iOS package so we can create  Xamarin iOS builds that target iOS 17, which will soon be a requirement to upload builds to the App Store.
While Microsoft will soon be dropping support for Xamarin, those of us who are in the process of migrating our apps to .NET iOS continue to need the latest supported version of Xamarin iOS, which is 16.4.0.23, on MacOS13 so we can continue to build on App Center.

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by shamil-mubarakshin** [comment]
Hey @David-Sobin,
Unfortunately, we currently don't have plans on baking this into the image due to maintenance concerns and upcoming EOL. You can find additional info and runtime installation options in https://github.com/actions/runner-images/issues/8045.

**Comment by benoit808** [comment]
> Hey @David-Sobin, Unfortunately, we currently don't have plans on baking this into the image due to maintenance concerns and upcoming EOL. You can find additional info and runtime installation options in #8045.

Unfortunately the solutions offered there with HomeBrew do not work for me because we need Xamarin.iOS SDK 17 since Apple will start rejecting app updates if not built against SDK 17 starting on April 29 but HomeBrew only has Xamarin.iOS SDK 16.4.
