### ISSUE TITLE
Update WiX Toolset

### ISSUE THREAD

**Issue by arixmkii** [actions/runner-images#9426]
### Tool name

WiX

### Tool license

Microsoft Reciprocal License (MS-RL)

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.14

### Brief description of tool

WiX handles MSI installation as you folks most likely know. WiX was recently released v 3.14 to mitigate DLL redirect vulnerability
* https://wixtoolset.org/news/2024/02/06/wix-v4.0.4-available/ 
* https://www.firegiant.com/blog/2024/2/6/wix-security-releases-available/

### URL for tool's homepage

https://wixtoolset.org/

### Provide a basic test case to validate the tool's functionality.

```bash

```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by dbenzhuser** [comment]
And here I was wondering why my builds that ran fine just yesterday are now failing ...

Anybody else getting these after the update to 3.14?

```
light.exe : error LGHT0204: ICEM10: The property 'ProductCode' is not allowed in a Merge Module

light.exe : error LGHT0217: Error executing ICE action 'ICE103'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor.
```

**Comment by mikhailkoliada** [comment]
Deployed!

**Comment by dbenzhuser** [comment]
Just in case anybody finds this: Seems to be a bug in VS's mergemodule.cub that got picked up in Wix 3.14 and just never got fixed. Merge modules can be built by suppressing ICE103 and ICEM10.

**Comment by chrpai** [comment]
I've found multiple issues with this change and reported it under https://github.com/actions/runner-images/issues/9543

**Comment by chrpai** [comment]
Yes, taking mergemod.cub from 3.11 and copying it to 3.14\bin works around this issue.  I also found an issue with the NetFx Extension which can be solved in a similar way. I don't know what other issues might lurk in 3.14 though.
