### ISSUE TITLE
Unable to create Azure Runbook of type PowerShell72 

### ISSUE THREAD

**Issue by cmicck** [actions/runner-images#9434]
### Description

Following command returns an error when run on ADO agent.
`Import-AzAutomationRunbook -ResourceGroupName $resourceGroupName -AutomationAccountName $automationaccount -Name $runbookName -Type PowerShell72 -Path $scriptFile -Force`

Getting following error : 
> Cannot validate argument on parameter 'Type'. The argument
> "PowerShell72" does not belong to the set
> "PowerShell,GraphicalPowerShell,PowerShellWorkflow,GraphicalPowerShellWorkflow,Graph,Python2,Python3" specified by the ValidateSet attribute.

This is supported in the newer Powershell modules, works when I run it locally with the newest module. [Link to doc from new module](https://learn.microsoft.com/en-us/powershell/module/az.automation/import-azautomationrunbook?view=azps-11.3.0)
Any ETA on update of modules on Microsoft-Hosted agents?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240225.1.0

### Is it regression?

No

### Expected behavior

Command **Import-AzAutomationRunbook** supports Type PowerShell72

### Actual behavior

     | Cannot validate argument on parameter 'Type'. The argument
     | "PowerShell72" does not belong to the set
     | "PowerShell,GraphicalPowerShell,PowerShellWorkflow,GraphicalPowerShellWorkflow,Graph,Python2,Python3" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

### Repro steps

Running the command **Import-AzAutomationRunbook** with **-Type PowerShell72**
ex: 
`Import-AzAutomationRunbook -ResourceGroupName $resourceGroupName -AutomationAccountName $automationaccount -Name $runbookName -Type PowerShell72 -Path $scriptFile -Force`

**Comment by erik-bershel** [comment]
Hey @cmicck!
Thank you for rising this. We'll think about updating Az.PowerShell modules. I'll be there here later with the additional information.

**Comment by mikhailkoliada** [comment]
Hello! There is a plan to upgrade az powershell later this spring, for the time being you can use the https://github.com/Azure/powershell action to specify the version of az you need to support your workflow

**Comment by cmicck** [comment]
> Hello! There is a plan to upgrade az powershell later this spring, for the time being you can use the https://github.com/Azure/powershell action to specify the version of az you need to support your workflow

We are currently on Azure Dev Ops, there an equivalent to this Github Action for ADO?
