### ISSUE TITLE
macOS runners sometimes fail to extract tar archive

### ISSUE THREAD

**Issue by NullHypothesis** [actions/runner-images#9435]
### Description

We have a macOS workflow that [downloads and extracts a tarball](https://github.com/TileDB-Inc/TileDB-Go/blob/pw/fix-test/.github/scripts/install_tiledb_macos.sh). The extraction only works sometimes. Other times, tar would fail with:
```
$ sudo tar -C /usr/local -xSf tiledb.tar.gz
./: Can't restore time
tar: Error exit delayed from previous errors.
```
GNU tar doesn't work either:
```
$ sudo gtar -C /usr/local -xSf tiledb.tar.gz
gtar: .: Cannot utime: Operation not permitted
gtar: .: Cannot change ownership to uid 501, gid 20: Operation not permitted
gtar: Exiting with failure status due to previous errors
```
Note that the tarball is fine. The runners downloaded it correctly and I can extract the tarball on my personal macOS.

I believe that the above is a continuation of https://github.com/actions/runner-images/issues/2619. In that issue, https://github.com/actions/runner-images/issues/2619#issuecomment-805058474 observed that the problem is caused by the underlying infrastructure. Note that the fixes proposed by https://github.com/actions/runner-images/issues/2619#issuecomment-1041125521 do **not** work for me – and don't seem to have worked for some of the original reporters either.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Here's a run that contains both a [successful](https://github.com/TileDB-Inc/TileDB-Go/actions/runs/8123276940/job/22203538510) and [failed](https://github.com/TileDB-Inc/TileDB-Go/actions/runs/8123276940/job/22203538361) job:
https://github.com/TileDB-Inc/TileDB-Go/actions/runs/8123276940

### Is it regression?

Possibly. We did not have these problems before mid-February.

### Expected behavior

The tar process on macOS runners should be able to extract the tarball without problems.

### Actual behavior

The tar process on macOS runners fails to extract the tarball.

### Repro steps

1. Fork [this repository](https://github.com/TileDB-Inc/TileDB-Go) and check out its `pw/fix-test` branch (for faster testing).
2. Run the workflow.
3. If the error does not surface on the first run, continue running the workflow until it fails.

**Comment by erik-bershel** [comment]
Hey @NullHypothesis!
Thank you for the information provided - we will check what is happening and come back a little later with additional comments. I may say that I checked the described issue using another example - the problem does indeed exist, but I am not yet sure of its causes for now.

**Comment by erik-bershel** [comment]
Hi again @NullHypothesis!
I'm not sure that your issue is related to #2619 exactly. It's more likely an access right issue which happens with `tar` from time time when you are not the owner of the directory. 

I tried this:
```yml
jobs:
  untar:
    runs-on: macos-12
    steps:
    - name: Download and untar
      shell: bash
      run: |
        set -e -x
        mkdir -m 0777 -p /tmp/test-folder
        curl \
            --location \
            --output /tmp/test-folder/tiledb.tar.gz \
            https://github.com/TileDB-Inc/TileDB/releases/download/2.20.1/tiledb-macos-x86_64-2.20.1-249c024.tar.gz
        shasum /tmp/test-folder/tiledb.tar.gz # Verify tarball integrity
        # Try both BSD and GNU tar, with the `-S` argument.
        sudo tar -C /tmp/test-folder -xSf /tmp/test-folder/tiledb.tar.gz || \
        sudo gtar -C /tmp/test-folder -xSf /tmp/test-folder/tiledb.tar.gz
```

None of 20 runs was failed. Could you try to use some intermediate folder with full access and ownership in order to avoid this behaviour of `tar`?

**Comment by NullHypothesis** [comment]
> None of 20 runs was failed. Could you try to use some intermediate folder with full access and ownership in order to avoid this behaviour of `tar`?

Thanks a lot for your help @erik-bershel! I believe you're right. Things are looking good after the first few runs. I think we can close this issue.

**Comment by erik-bershel** [comment]
>Sorry for responding prematurely. I'm not convinced that this is a permissions issue: My command is using sudo after all, and the same sequence of commands (including permissions) works on my macOS laptop. Besides, if this was a permissions issue only, it should happen consistently instead of sporadically, no?

It's not about `sudo` and user/system contexts - it's a well-known `tar` issue working with the file system permissions. And no, it happens sporadically.

**Comment by erik-bershel** [comment]
@NullHypothesis 
There is also another possible workaround for this issue, but I didn't checked it specifically with your case to be honest. You may try to use `tar` with the flag `--no-same-owner`. It should prevent `tar` from setting an owner.

**Comment by erik-bershel** [comment]
Hey @NullHypothesis!
Did you tried workarounds? Does it help?

**Comment by NullHypothesis** [comment]
> Hey @NullHypothesis! Did you tried workarounds? Does it help?

No, it didn't help. We noticed however that a cpack-based tarball can be extracted just fine.

> It's not about `sudo` and user/system contexts - it's a well-known `tar` issue working with the file system permissions. And no, it happens sporadically.

Do you happen to have a reference for that? While researching this issue, I stumbled upon all sorts of extraction problems but nothing quite like what we seem to be encountering.

**Comment by erik-bershel** [comment]
@NullHypothesis 
>Do you happen to have a reference for that? While researching this issue, I stumbled upon all sorts of extraction problems but nothing quite like what we seem to be encountering.

Sure thing! You can dive deeper into this here: https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233

> No, it didn't help. We noticed however that a cpack-based tarball can be extracted just fine.

Such a surprise for me, and not the best one to be honest. I'll try to reproduce it in clean action.

**Comment by erik-bershel** [comment]
@NullHypothesis 

I checked it again. I launched this workflow three times (30 different jobs / 150 different steps) - not a single crash. Please use a directory in which the `utime` utility has enough rights to change metadata, also you may try to find a combination of flags for `tar`/`gtar` that will allow to avoid calling the `utime` in the process - unfortunately I was not able to do this.

```yml
name: TAR - 9435

on:
  workflow_dispatch:

jobs:
  untar:
    strategy:
      matrix:
        os: [ macos-12, macos-12, macos-12, macos-12, macos-12, macos-12, macos-12, macos-12, macos-12, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download and untar FROM and IN folder
      shell: bash
      run: |
        set -x
        for attempt in {1..5}; do
          mkdir -m 0777 -p /tmp/test-folder
          curl \
              --location \
              --output /tmp/test-folder/tiledb.tar.gz \
              https://github.com/TileDB-Inc/TileDB/releases/download/2.20.1/tiledb-macos-x86_64-2.20.1-249c024.tar.gz
          shasum /tmp/test-folder/tiledb.tar.gz
          sudo tar -C /tmp/test-folder -xf /tmp/test-folder/tiledb.tar.gz || \
          sudo gtar -C /tmp/test-folder -xf /tmp/test-folder/tiledb.tar.gz
          rm -rf /tmp/test-folder
        done
    - name: Download and untar IN folder
      shell: bash
      run: |
        set -x
        for attempt in {1..5}; do
          mkdir -m 0777 -p /tmp/test-folder
          curl \
              --location \
              --output tiledb.tar.gz \
              https://github.com/TileDB-Inc/TileDB/releases/download/2.20.1/tiledb-macos-x86_64-2.20.1-249c024.tar.gz
          shasum tiledb.tar.gz
          sudo tar -C /tmp/test-folder -xf tiledb.tar.gz || \
          sudo gtar -C /tmp/test-folder -xf tiledb.tar.gz
          rm -rf /tmp/test-folder
        done
```
