### ISSUE TITLE
Unable to Run Android Emulator in MacOs 14 Github Runner based On M1

### ISSUE THREAD

**Issue by mg3994** [actions/runner-images#9436]
### Description

I am Unable to Start any Android Emulator in My M1 based Macos 14 Github Runner

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Emulator Required in Workflow](https://github.com/FilledStacks/testsweets-example)

### Is it regression?

no

### Expected behavior

A working Android Emulator , as i want to run some adb commands

### Actual behavior

Unable to Start Emulator

### Repro steps

* Uncomment the Emulator Part in Workflow
* [Repo Link](https://github.com/FilledStacks/testsweets-example)
* Uncomment and Run Workflow

**Comment by erik-bershel** [comment]
Hey @mg3994!
Unfortunately it's a platform related issue which we cannot solve on our side. It was firstly mentioned some time ago.
Take a look here, please: https://docs.veertu.com/anka/anka-virtualization-cli/nested-virtualization/#android-emulators
Closing as a clone of https://github.com/actions/runner-images/issues/9199 and https://github.com/actions/runner-images/issues/9194.
