### ISSUE TITLE
Add PHP on macos-14 runner

### ISSUE THREAD

**Issue by shivammathur** [actions/runner-images#9437]
### Tool name

PHP

### Tool license

PHP-3.01

### Add or update?

- [X] Add
- [ ] Update

### Desired version

8.3

### Brief description of tool

PHP is a popular general-purpose scripting language

### URL for tool's homepage

https://php.net/

### Provide a basic test case to validate the tool's functionality.

```bash
php -v
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install php
```

### Tool installation time in runtime

~2 min

### Are you willing to submit a PR?

No

**Comment by mikhailkoliada** [comment]
@shivammathur we have no plans to onboard php to macOS-14 yet now at least while it is in beta, later might be, but now we do not see the high demand and observe the need
