### ISSUE TITLE
Add PHP 8.2 & PHP 8.3 to Ubuntu 22.04

### ISSUE THREAD

**Issue by sylfabre** [actions/runner-images#9442]
### Tool name

PHP

### Tool license

PHP-3.01

### Add or update?

- [X] Add
- [ ] Update

### Desired version

8.2 and 8.3

### Brief description of tool

PHP is a popular general-purpose scripting language

### URL for tool's homepage

https://php.net/

### Provide a basic test case to validate the tool's functionality.

```bash
`php -v`
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

Yes

You already do it with Ubuntu 20.04

You already closed as not planned many issues about this request:
- https://github.com/actions/runner-images/issues/6743
- https://github.com/actions/runner-images/issues/9323
- https://github.com/actions/runner-images/issues/8068
- ...

The provided reason for closing these previous issues is that PHP is installed from the official Canonical repository which only provides PHP 8.1 for Ubuntu 22.04.

However:
- PHP 8.1 is now obsolete
- Canonical only provides PHP 7.4 for Ubuntu 20.04 while the Azure DevOps runner image using Ubuntu 20.04 currently has PHP 7.4, 8.0, 8.1, 8.2, and 8.3.

So it looks like you did accept more PHP versions for Ubuntu 20.04: we are kindly asking you to do the same for Ubuntu 22.04 😊

As developers, the current setup provided by Azure DevOps is blocking upgrading our pipelines from Ubuntu 20.04 to 22.04 because it lacks support for the latest versions of PHP!

**Comment by mikhailkoliada** [comment]
Hello! There was an [announcement](https://github.com/actions/runner-images/issues/6331) about that change, 22.04 supports more versions of php installed because it is using the famous third party repository but we no longer have plans to use it as it is considered generally unreliable and causing security concerns, if you need php versions other than Canonical provides you can still enable and fetch this repo in [runtime](https://launchpad.net/~ondrej/+archive/ubuntu/php)

**Comment by EPGDigital-MW** [comment]
It's a little bit disappointing to see these php versions disappear by default, the pipeline run times have now increased considerably as we are now having to add php each time. I'd love to know what the global impact this has had across everyone using other php versions than the ones now provided.
