### ISSUE TITLE
macos cmake fails to download from https source

### ISSUE THREAD

**Issue by acalcutt** [actions/runner-images#9447]
### Description

I am having an issue on the macos 12-13 runners in cmake where a [DOWNLOAD with TLS_VERIFY](https://github.com/maplibre/maplibre-native/blob/main/platform/node/cmake/module.cmake#L18)  is failing that was working fine last month. My guess is maybe it stopped working with https://github.com/actions/runner-images/pull/9379

The file being downloaded by cmake is
https://registry.npmjs.org/nan/-/nan-2.18.0.tgz , but I have also tried to make it download a mirror from https://registry.yarnpkg.com/nan/-/nan-2.18.0.tgz , but both fail with a "Failed to download Nan 2.18.0: "SSL connect error" which is returned by the cmake when the download fails.

The certs at those urls look ok to me so I'm not sure why the TLS_VERIFY would fail. If I set TLS_VERIFY to OFF then the download is able to complete without an issue.[](url)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Macos-13 - https://github.com/maplibre/maplibre-native/actions/runs/8144665118/job/22259246848?pr=1793
Macos-14-arm - https://github.com/maplibre/maplibre-native/actions/runs/8144665118/job/22259247093?pr=1793

### Is it regression?

yes, it worked in cmake 3.28.0 at  https://github.com/maplibre/maplibre-native/actions/runs/7613826847/job/20736578240

### Expected behavior

cmake should be be able to download from the valid npm url
https://registry.npmjs.org/nan/-/nan-2.18.0.tgz with TLS_VERIFY on

### Actual behavior

download fails when TLS_VERIFY is ON. the download does still work if TLS_VERIFY is OFF

### Repro steps

Use cmake to download a http file

**Comment by acalcutt** [comment]
Thanks for looking into it. I have been trying to make a simpler example at https://github.com/WifiDB/cmake-test/blob/main/CMakeLists.txt but I haven't quite gotten it to work (it keeps getting a write error and I'm not sure why) . I'll see if I can get that working.

Was cmake in these iamges built with OpenSSL support?

**Comment by MaksimZhukov** [comment]
Hello @acalcutt!
We install cmake via brew. 
Downgrading cmake version in runtime resolves the issue ([successful build](https://github.com/MaksimZhukov/maplibre-native/actions/runs/8241654485/job/22539315125), [workflow file](https://github.com/MaksimZhukov/maplibre-native/actions/runs/8241654485/workflow)). Please use the following code snippet as a workaround:
```yml
      - name: Downgrade cmake version
        run: |
          brew uninstall cmake
          mkdir ~/Downloads/CMake
          curl --silent --location --retry 3 "https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-macos-universal.dmg" --output ~/Downloads/CMake/cmake-Darwin-x86_64.dmg
          yes | PAGER=cat hdiutil attach -quiet -mountpoint /Volumes/cmake-Darwin-x86_64 ~/Downloads/CMake/cmake-Darwin-x86_64.dmg
          cp -R /Volumes/cmake-Darwin-x86_64/CMake.app /Applications/
          hdiutil detach /Volumes/cmake-Darwin-x86_64
          sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install=/usr/local/bin
```
 I am closing the issue, but please let us know if you have any questions or concerns.
