### ISSUE TITLE
Activating windows feature fails

### ISSUE THREAD

**Issue by robertreemsrivm** [actions/runner-images#9456]
### Description

I'm building a new pipeline for image generation.

Unfortunately I'm running into issues with Windows and receive an error. I've tried to use both Windows 2019 and 2022.

I'm building from the main branch.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

no, it is our first attempt

### Expected behavior

No error is produced and the script 'Install-WindowsFeatures.ps1' runs as expected.

### Actual behavior

I get the following error:

```
==> azure-arm.image: Provisioning with powershell script: /agent/_work/1/s/rivm-cpt/runner-images/images/windows/templates/../scripts/build/Install-WindowsFeatures.ps1
    azure-arm.image: Activating Windows Feature 'NET-Framework-Features'...
==> azure-arm.image: Install-WindowsFeature : The request to add or remove features on the specified server failed.
==> azure-arm.image: Installation of one or more roles, role services, or features failed. Error: 0x80072f8f
==> azure-arm.image: At C:\Windows\Temp\script-65e82cba-1f7e-bb8c-ac59-5ed8a4244424.ps1:21 char:19
==> azure-arm.image: +         $result = Install-WindowsFeature @arguments
==> azure-arm.image: +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidOperation: (@{Vhd=; Credent...Name=localhost}:PSObject) [Install-WindowsFeature],
==> azure-arm.image:     Exception
==> azure-arm.image:     + FullyQualifiedErrorId : DISMAPI_Error__Failed_To_Enable_Updates,Microsoft.Windows.ServerManager.Commands.AddWind
==> azure-arm.image:    owsFeatureCommand
==> azure-arm.image: Failed to activate Windows Feature 'NET-Framework-Features'
==> azure-arm.image: At C:\Windows\Temp\script-65e82cba-1f7e-bb8c-ac59-5ed8a4244424.ps1:29 char:9
==> azure-arm.image: +         throw "Failed to activate Windows Feature '$($feature.name)'"
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Failed to activ...ework-Features':String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Failed to activate Windows Feature 'NET-Framework-Features'

```

### Repro steps

I'm running packer using the following command:
packer build -on-error=abort -var install_password=$installPassword -var managed_image_resource_group_name=$ManagedImageResourceGroupName -var build_resource_group_name=$BuildResourceGroupName -var virtual_network_name=$VirtualNetworkName -var virtual_network_resource_group_name=$VirtualNetworkRG -var virtual_network_subnet_name=$VirtualNetworkSubnet -var image_version=$ImageReleaseVersion -var managed_image_name=$ManagedImageName -var vm_size=$VMSizeName -color=false $TemplatePath

The packer file https://github.com/actions/runner-images/blob/main/images/windows/templates/windows-2019.pkr.hcl is used without modification.

**Comment by erik-bershel** [comment]
Hey @robertreemsrivm!
It could be a transient issue. Night builds went fine: [windows-2022](https://dev.azure.com/github/runner-images/_build/results?buildId=134948&view=results), [windows-2019](https://dev.azure.com/github/runner-images/_build/results?buildId=134940&view=results). I'll check how it's going now here: [windows-2022](https://dev.azure.com/github/runner-images/_build/results?buildId=134952&view=results), [windows-2019](https://dev.azure.com/github/runner-images/_build/results?buildId=134953&view=results).

**Comment by erik-bershel** [comment]
Yes, the assembly passes the specified moment on both images. I recommend just trying again.
