### ISSUE TITLE
Update/Add Docker image "azure-sql-edge:latest"

### ISSUE THREAD

**Issue by emn-dev** [actions/runner-images#9463]
### Tool name

Docker image => mcr.microsoft.com/azure-sql-edge:latest

### Tool license

unknown

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Docker image of azure sql edge.

### URL for tool's homepage

https://hub.docker.com/_/microsoft-azure-sql-edge

### Provide a basic test case to validate the tool's functionality.

```bash
¯\_(ツ)_/¯
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
# FILE =  ./docker-compose.yml
# CMD = docker-compose up -d
version: "3.7"
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
      - mydatabase:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd

volumes:
  mydatabase:
```

### Tool installation time in runtime

30 to 60 seconds

### Are you willing to submit a PR?

sure :)

**Comment by erik-bershel** [comment]
Hey @emn-dev!
Due to maintenance concerns and the fact that the image is easily and quickly added in runtime, we would not want to add it to the image.

**Comment by emn-dev** [comment]
@erik-bershel thanks for the speedy reply! I totally understand your comment. However, just curious... when it comes to pre-installed databases (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#databases) there is no Sql Server/Express/etc. Why does PostgreSQL or MySQL get to be pre-installed?
