### ISSUE TITLE
Ubuntu 22 build fails because kotlin package doesn't published checksums

### ISSUE THREAD

**Issue by cengelenVW** [actions/runner-images#9466]
### Description

A new [release of kotlin](https://github.com/JetBrains/kotlin/releases/tag/v1.9.23) has been released. 
The packager picks up this version but wants to check the checksum also. 
This isn't possible because there aren't checksums published in the release body this release.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 20240304.1.1

### Is it regression?

no

### Expected behavior

building of image succeeds with previous kotlin version or with newest (but without checksum check)

### Actual behavior

build fails

### Repro steps

Start the packaging process of the mentioned ubuntu 22 image

**Comment by erik-bershel** [comment]
Hello @cengelenVW!
I'm working on this right now. I'll call you when the PR is ready.

**Comment by erik-bershel** [comment]
Hey @cengelenVW!
Both Ubuntu and Windows PR are in tests right now. You may start your builds after those will be merged.

**Comment by cengelenVW** [comment]
@erik-bershel
Great work! Thanks!

**Comment by mikhailkoliada** [comment]
The fix is now merged, please sync your main branch.
