### ISSUE TITLE
GitHub API Rate Limits during image creation

### ISSUE THREAD

**Issue by hendrik-schaffer** [actions/runner-images#9470]
### Description

Dear all,

When building the images for Windows and Ubuntu as described in the [repository](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md) we sometimes get build failures for HTTP requests agains the GitHub API as the rate limit has been exceeded.

The helper scripts for MacOS already contain a possibility to provide a GitHub PAT to prevent those API rate limits of unauthenticated users. E.g. see https://github.com/actions/runner-images/blob/61df9288f9be9f6aeaaaa4ad52a7332432913fc3/images/macos/scripts/helpers/utils.sh#L159C12-L159C19

Why is this functionality not included in the Ubuntu and Windows install helpers? Alternatively, how do you prevent running into the GitHub rate limit when building the image as outlined in this respository for Ubuntu or Windows?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

.

### Is it regression?

.

### Expected behavior

More stable behavior when building the images

### Actual behavior

Unstable in case of network issues and retries, the GitHub API rate limit for unauthenticated calls get exhausted quite fast. (only 60 requests per hour)

### Repro steps

Clone the repo and run the build-image.ps1 script.

**Comment by mikhailkoliada** [comment]
@hendrik-schaffer hello! for macOS it is an internal functionality we are using to build macOS across behind-nat hardware, for windows and ubuntu we do not need that functionality so customers are encouraged to implement one as they see fit for their own images, we have no plans to add this into main until absolutely needed.
