### ISSUE TITLE
Add Microsoft 365 Access Runtime

### ISSUE THREAD

**Issue by carlos-quintero** [actions/runner-images#9475]
### Tool name

Microsoft 365 Access Runtime

### Tool license

Free download redistributable

### Add or update?

- [X] Add
- [ ] Update

### Desired version

365 64-bit English

### Approximate size

The 365 Access Runtime download (OfficeSetup.exe) is 7 MB, but when installed it downloads more files. As a reference, the Access Runtime for Access 2016 was 323 MB.

### Brief description of tool

The Microsoft 365 Access Runtime includes this ODBC driver:

- "Microsoft Access Driver (*.mdb, *.accdb)"
 
and these OLEDB providers:

- "Microsoft.ACE.OLEDB.12.0"
- "Microsoft.ACE.OLEDB.16.0"

required to connect to modern .accdb files, because the old ODBC drivers and OLEDB providers shipped with the Windows OS only work with the old .mdb format.

These ODBC drivers / OLEDB providers are required to perform integration tests in builds for apps that use the .accdb file format.

### URL for tool's homepage

Download and install Microsoft 365 Access Runtime
https://support.microsoft.com/en-us/office/download-and-install-microsoft-365-access-runtime-185c5a32-8ba9-491e-ac76-91cbe3ea09c9

### Provide a basic test case to validate the tool's functionality.

The PowerShell command:

(New-Object system.data.oledb.oledbenumerator).GetElements() | select SOURCES_NAME

should include in the results:

Microsoft.ACE.OLEDB.12.0
Microsoft.ACE.OLEDB.16.0

### Platforms where you need the tool

- [x] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022

### Can this tool be installed during the build?

It requires admin rights and it takes several minutes

### Tool installation time in runtime

Several minutes

**Comment by MaksimZhukov** [comment]
Hello @carlos-quintero!
Unfortunately, we have no plans to add Microsoft 365 Access Runtime to the image due to the maintenance concerns.

**Comment by carlos-quintero** [comment]
Hi @MaksimZhukov 

Can you elaborate on the maintenance concerns? What makes it different to any other tool included in the image?
