### ISSUE TITLE
Windows agent image build fail

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#9479]
### Description

Windows agent image build fail

==> azure-arm.image: Invoke-PesterTests : Unable to find type [PesterConfiguration].
==> azure-arm.image: At C:\Windows\Temp\script-65ebc787-b155-b9ea-a7e2-ac35bf878797.ps1:55 char:1
==> azure-arm.image: + Invoke-PesterTests -TestFile "Docker" -TestName "Docker"
==> azure-arm.image: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidOperation: (PesterConfiguration:TypeName) [Invoke-PesterTests], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : TypeNotFound,Invoke-PesterTests
==> azure-arm.image:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image 20240304.2.0

### Is it regression?

NA

### Expected behavior

Image build completes

### Actual behavior

==> azure-arm.image: Invoke-PesterTests : Unable to find type [PesterConfiguration].
==> azure-arm.image: At C:\Windows\Temp\script-65ebc787-b155-b9ea-a7e2-ac35bf878797.ps1:55 char:1
==> azure-arm.image: + Invoke-PesterTests -TestFile "Docker" -TestName "Docker"
==> azure-arm.image: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidOperation: (PesterConfiguration:TypeName) [Invoke-PesterTests], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : TypeNotFound,Invoke-PesterTests
==> azure-arm.image:

### Repro steps

rerun pipeline

**Comment by MaksimZhukov** [comment]
Hello @jaswant-dnv!
As you can see, [Windows22 test builds](https://github.visualstudio.com/runner-images/_build?definitionId=97) on the `main` branch were successful. Please make sure you are using the correct configuration.

**Comment by stoopman** [comment]
I get the same error, but the build before this was successful, using the same configuration.
```
==> azure-arm.image: Invoke-PesterTests : Unable to find type [PesterConfiguration].
==> azure-arm.image: At C:\Windows\Temp\script-66f267ef-637c-6014-f328-f723c9e13a1d.ps1:55 char:1
==> azure-arm.image: + Invoke-PesterTests -TestFile "Docker" -TestName "Docker"
==> azure-arm.image: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidOperation: (PesterConfiguration:TypeName) [Invoke-PesterTests], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : TypeNotFound,Invoke-PesterTests
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
```
