### ISSUE TITLE
LINUX_VERSION_CODE does not match the kernel version on ubuntu 20.04

### ISSUE THREAD

**Issue by wwierzbicki-alpha** [actions/runner-images#9495]
### Description

On ubuntu-20.04 runner I get following results:
```
$ uname -r
5.15.0-1057-azure
$ grep "LINUX_VERSION_CODE" /usr/include/linux/version.h
#define LINUX_VERSION_CODE 328959
```

The `LINUX_VERSION_CODE` is not matching the kernel version.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.314.1'

Runner Image
  Image: ubuntu-20.04
  Version: 20240304.1.0

### Is it regression?

no

### Expected behavior

`LINUX_VERSION_CODE` matching the kernel version

### Actual behavior

`LINUX_VERSION_CODE` matching an older kernel version

### Repro steps

Run the following commands:
1. `uname -r`
2. `grep "LINUX_VERSION_CODE" /usr/include/linux/version.h`

**Comment by mikhailkoliada** [comment]
Hello! This is not a bug, this behaviour is expected, the file you are trying to reference does not come with a kernel version, it comes with the libc version (you can easily spot it by typing something like `sudo dpkg -S /usr/include/linux/version.h`). This file does not contain the version code for the currently running kernel, instead it contains the kernel version glib was built on, to reference a kernel version running you should still use the version.h file installed by the appropriate linux-header package version (the version of the package for the current kernel version is already the part of the runner).

**Comment by wwierzbicki-alpha** [comment]
@mikhailkoliada what about boost which includes `include <linux/version.h>` and then:
```
#  if LINUX_VERSION_CODE < KERNEL_VERSION(5,10,0)
#   error Linux kernel 5.10 or later is required to support io_uring
#  endif // LINUX_VERSION_CODE < KERNEL_VERSION(5,10,0)
```
it will not compile due to `LINUX_VERSION_CODE` from the header.

Is it expected to be unable to compile this code on Ubuntu 20.04 runner?

**Comment by mikhailkoliada** [comment]
@wwierzbicki-alpha the answer is, it depends, it just contains the version and nothing more, but I would not rely on that file if you are interested in currently-running kernel, but if your snippet is not ubuntu-specific the result can be unpredictable, some distros (say Gentoo) install linux headers into the /usr/inuclude/linux dir and then manage it via symlinks.

**Comment by wwierzbicki-alpha** [comment]
@mikhailkoliada boost is not Ubuntu specific. Here is the boost code that is causing compilation failure https://github.com/boostorg/asio/blob/3a7078a2002c670d98ee3044802a5086f3e49634/include/boost/asio/detail/config.hpp#L827

Do you mean that the boost library is not checking the kernel version properly?

**Comment by mikhailkoliada** [comment]
@wwierzbicki-alpha LINUX_VERSION_CODE is not unique macro, I mean there are multiple versions of the `version.h` header with this macro defined, the one you included comes with glibc and this exact `version.h` does not reflect running kernel version, from your reference I can not judge if it is right or wrong as I am lacking the context + not really a boost expert
