### ISSUE TITLE
Issues with Sysprep and Geneva Extension on Windows Images

### ISSUE THREAD

**Issue by oolaoluwa** [actions/runner-images#9499]
### Description

Hello,

We are the 1ES Resource Management team, we provide VMSS for internal CI/CD pipelines and part of that is creating S360 compliant versions of the Azure Pipelines images. Recently we have noticed two different types of failures in the image build that is preventing us from releasing new windows versions for customers. 

The first comes during provisioning.  We can see the Geneva Monitoring extension deployed to the machines, but in WAAppAgent logs we see it determines that no extensions are installed. 

The second issue comes during the image build where we get this error: 
2024-03-06 18:47:53, Error                 SYSPRP ActionPlatform::DeleteValue: Error from RegDeleteValueW for value senseGuid under key HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Advanced Threat Protection; dwRet = 0x5
As this key is only set when azure applies its MDE/Security extensions, this seems to indicate that a Geneva extension is already present on the image and causing a conflict​

As this is a relatively urgent matter as we will be spinning up many agents with an older image version missing security patches, we were hoping that we could get some help from your team to investigate. Has anything changed in the last month or so in how the Windows images are generated?

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Windows 2022 and 2019 version 20240304.2.1

### Is it regression?

yes. 20240128.1.1

### Expected behavior

Image created after sysprep and security enhancements.

### Actual behavior

Sysprep fails with registry key already set. Vms created using secure image fail in the geneva extension.

### Repro steps

Clearing Packages folder and creating new image from that leads to failures in the geneva extension

**Comment by mikhailkoliada** [comment]
These issues should not be filed to the public repo.

**Comment by oolaoluwa** [comment]
@mikhailkoliada Where should I file them
