### ISSUE TITLE
Packer failing on ubuntu22/20240304.1, but passing on ubuntu22/20240310.1

### ISSUE THREAD

**Issue by celloza** [actions/runner-images#9504]
### Description

I'm trying to build Azure DevOps Self-Hosted agents.

I'm using the build-image.ps1 file in images.CI/linux-and-win/. Everything works fine up until it gets to this bit in the log:

```
    azure-arm.build_image: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_image: Describing Mono
    azure-arm.build_image:   [+] mono 138ms (101ms|37ms)
    azure-arm.build_image:   [+] msbuild 103ms (100ms|2ms)
    azure-arm.build_image:   [+] nuget 574ms (572ms|2ms)
    azure-arm.build_image: Tests completed in 1.71s
    azure-arm.build_image: Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 94
==> azure-arm.build_image: Provisioning with shell script: /home/vsts/work/1/s/runner-images/images/ubuntu/templates/../scripts/build/install-kotlin.sh
==> azure-arm.build_image: Downloading package from https://github.com/JetBrains/kotlin/releases/download/v1.9.23/kotlin-compiler-1.9.23.zip to /tmp/kotlin-compiler-1.9.23.zip...
==> azure-arm.build_image: Package downloaded in 1 seconds
==> azure-arm.build_image: File name kotlin-compiler-.*\.zip not found in release body
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_image: 
==> azure-arm.build_image: Deleting Virtual Machine deployment and its attatched resources...

```

I'm guessing the issue is at "File name kotlin-compiler-.*\.zip not found in release body", since that is when my resources start being decommissioned.

I ran the exact same process with the new pre-release version, ubuntu22/20240310.1, which passes this bit successfully:

```
    azure-arm.build_image: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_image: Describing Mono
    azure-arm.build_image:   [+] mono 123ms (89ms|34ms)
    azure-arm.build_image:   [+] msbuild 97ms (95ms|2ms)
    azure-arm.build_image:   [+] nuget 522ms (520ms|2ms)
    azure-arm.build_image: Tests completed in 1.57s
    azure-arm.build_image: Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 94
==> azure-arm.build_image: Provisioning with shell script: /home/vsts/work/1/s/runner-images/images/ubuntu/templates/../scripts/build/install-kotlin.sh
==> azure-arm.build_image: Downloading package from https://github.com/JetBrains/kotlin/releases/download/v1.9.23/kotlin-compiler-1.9.23.zip to /tmp/kotlin-compiler-1.9.23.zip...
==> azure-arm.build_image: Package downloaded in 1 seconds
==> azure-arm.build_image: Downloading package from https://github.com/JetBrains/kotlin/releases/download/v1.9.23/kotlin-compiler-1.9.23.zip.sha256 to /tmp/kotlin-compiler-1.9.23.zip.sha256...
==> azure-arm.build_image: Package downloaded in 0 seconds
    azure-arm.build_image: Performing checksum verification
    azure-arm.build_image: Checksum verification passed
    azure-arm.build_image: Pester v5.5.0
    azure-arm.build_image:
    azure-arm.build_image: Starting discovery in 1 files.
    azure-arm.build_image: Discovery found 97 tests in 514ms.
    azure-arm.build_image: Filter 'FullName' set to ('Kotlin').
    azure-arm.build_image: Filters selected 5 tests to run.
    azure-arm.build_image: Running tests.
    azure-arm.build_image:
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

|Name|Value|
|---|---|
|published_at|03/05/2024 12:28:09|
|tag_name|ubuntu22/20240304.1|
|url|[https://api.github.com/repos/actions/runner-ima…](https://api.github.com/repos/actions/runner-ima%E2%80%A6)|
|name|Ubuntu 22.04 (20240304) Image Update|
|target_commitish|6eff71fa20678f3d24d285a8e5c1f1fa0500fddd|
|prerelease|False|

### Is it regression?

Don't know?

### Expected behavior

Image is successfully generated

### Actual behavior

Build fails on "File name kotlin-compiler-.*\.zip not found in release body"

### Repro steps

Just run build-image.ps1 for ubuntu22/20240304.1.

**Comment by mikhailkoliada** [comment]
Hello! We do not back port patches to gh releases / tags so if it does not build for you it might behave as expected, please always use main for the custom images build as described in the repo's FAQ: https://github.com/actions/runner-images?tab=readme-ov-file#faqs
