### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by pierre6666** [actions/runner-images#9506]
### Tool name

flutter sdk with fvm

### Tool license

https://github.com/flutter/flutter/blob/master/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.19.3

### Brief description of tool

Flutter is an open-source UI toolkit by Google for building natively compiled applications for mobile, web, and desktop from a single codebase, known for its fast development, expressive UI, and hot reload feature.

FVM (Flutter Version Management) is a tool that allows developers to easily manage multiple Flutter SDK versions on their machine, enabling seamless switching between versions for different projects, enhancing development flexibility and compatibility.

### URL for tool's homepage

https://flutter.dev

### Provide a basic test case to validate the tool's functionality.

```bash
can build an app from flutter code
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
#Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#Install fvm
brew tap leoafarias/fvm
brew install fvm
#install Flutter via fvm
fvm install 3.19.0
```

**Comment by MaksimZhukov** [comment]
Hello @pierre6666!
It was decided not to add these tools to the macOS images due to maintenance concerns and simplicity of installation in runtime. Please continue installing them in runtime
