### ISSUE TITLE
Update/Add OpenTofu

### ISSUE THREAD

**Issue by zchoate** [actions/runner-images#9507]
### Tool name

OpenTofu

### Tool license

MPL-2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.6.2 or latest stable

### Approximate size

21MB

### Brief description of tool

OpenTofu is the fork of Terraform that respects the original MPL-2.0 licensing after Terraform switched to a non-OSS license.

### URL for tool's homepage

https://opentofu.org/

### Provide a basic test case to validate the tool's functionality.

```bash
tofu --version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://get.opentofu.org/opentofu.gpg | sudo tee /etc/apt/keyrings/opentofu.gpg >/dev/null
curl -fsSL https://packages.opentofu.org/opentofu/tofu/gpgkey | sudo gpg --no-tty --batch --dearmor -o /etc/apt/keyrings/opentofu-repo.gpg >/dev/null
sudo chmod a+r /etc/apt/keyrings/opentofu.gpg
echo \
  "deb [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main
deb-src [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main" | \
  sudo tee /etc/apt/sources.list.d/opentofu.list > /dev/null
sudo apt-get update
sudo apt-get install -y tofu
```

### Tool installation time in runtime

<5min

### Are you willing to submit a PR?

Sure

**Comment by MaksimZhukov** [comment]
Hello @zchoate!
It was decided not to add this tool to the Ubuntu images due to maintenance concerns and relatively short installation time (~20s). Please continue installing it in runtime

**Comment by JasonWhall** [comment]
For those that discover this thread through searching:

- For the Azure pipelines users - I've published an extension to [install at runtime](https://marketplace.visualstudio.com/items?itemName=jasonwhalley.opentofu-installer-task)

- For GitHub Actions Users - There's a community maintained [GitHub action here](https://github.com/opentofu/setup-opentofu)
