### ISSUE TITLE
Could not symlink bin/2to3 macoslatest

### ISSUE THREAD

**Issue by leonaAtkins** [actions/runner-images#9508]
### Description

When trying to run terraform into on macos we're now getting the following error, for info this worked fine last week (March 08/03/2024) 
This is using `runs-on: macos-latest`
`- uses: Homebrew/actions/setup-homebrew@master`
` runs: brew install tfenv grep findutils` -- fails

error 
```
Error: Process completed with exit code 1.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/alphagov/govwifi-terraform/actions/runs/8263390839/job/22604698757

### Is it regression?

https://github.com/alphagov/govwifi-terraform/actions/runs/8207689743/job/22449523941

### Expected behavior

expected action to pass.

### Actual behavior

Fails with
```
The installation does not include `sbtn`.
Error: Process completed with exit code 1.
```
Edit on further investigation, there was another error 
```
Error: The `brew link` step did not complete
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
```
Which I think is the actual cause of my problems and seems to be a recurring issue

### Repro steps

This is using `runs-on: macos-latest`
`- uses: Homebrew/actions/setup-homebrew@master`
` runs: brew install tfenv grep findutils` -- fails
error 
```
The installation does not include `sbtn`.
Error: Process completed with exit code 1.
```

**Comment by MaksimZhukov** [comment]
Hello @leonaAtkins!
Both attached builds have the same image version (`20240218.1`). This means that nothing has changed from the image side. Also, your successful build has the same [error message](https://github.com/alphagov/govwifi-terraform/actions/runs/8207689743/job/22449523941#step:4:273).

**Comment by leonaAtkins** [comment]
@MaksimZhukov You are right, I hadn't noticed that, it was the last error reported when the build failed, so I incorrectly assumed this was the cause of the failure.  But you can see that one build passed, the other failed, on the installation step, so something is up with that step, difficult to pin down what it is then.

**Comment by leonaAtkins** [comment]
Might be similar to this bug (thought we don't use xz)
https://github.com/python/cpython/issues/116026
I'm not sure how to stop it updating dependencies, I tried to stop it performing updates, but that broke it further.

**Comment by leonaAtkins** [comment]
Switched to using Ubuntu Runner as needed to get deployment out in timely manor.
