### ISSUE TITLE
ubuntu-latest's `vm.mmap_rnd_bits` is too high to work with sanitizers

### ISSUE THREAD

**Issue by cmazakas** [actions/runner-images#9515]
### Description

The original issue is here: https://github.com/google/sanitizers/issues/1716

This doesn't just affect jobs using tsan, ubsan + asan are also seemingly affected and various CI jobs will hang. This can be replicated locally using ubuntu-23.10 with the latest kernel 6.5.0-25-generic.

The problem is that `vm.mmap_rnd_bits` is 32, not 28. Locally, I can fix all these issues by using:
```bash
sysctl vm.mmap_rnd_bits=28
```
but the filesystem is read-only for runners so there's nothing users can do.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 Image: ubuntu-22.04
 Version: 20240310.1.0

https://github.com/cmazakas/http_proto/actions/runs/8285130986/job/22672196607

### Is it regression?

Yes, https://github.com/cmazakas/http_proto/actions/runs/8239646755

### Expected behavior

Normally, c++ tests compiled `-fsanitize=address` don't indefinitely hang. There's some defect in the sanitizers that needs to be sorted out

### Actual behavior

asan jobs hang indefinitely

### Repro steps

Well, it can be a lot of work to pull down, build and test a C++ library so we'll get there when we get there.

All the runner-images need is just this `mmap_rnd_bits` value to be adjusted to its old value.

**Comment by mikhailkoliada** [comment]
Duplicate of https://github.com/actions/runner-images/issues/9491
