### ISSUE TITLE
Disk space test is running inside ADO pipeline

### ISSUE THREAD

**Issue by shanoor** [actions/runner-images#9517]
### Description

I have a pipeline that build a custom image from this repo and it fails on the [disk space test](https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/tests/System.Tests.ps1) because there is no `$env:AGENT_NAME` automatically created.

![image](https://github.com/actions/runner-images/assets/17402800/f8f7ac5a-2a6c-40e0-89ef-6b6bfc8f9509)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current image version: '20240304.1.0'

### Is it regression?

yes

### Expected behavior

The disk space test not running when the image generation is done through ADO

### Actual behavior

Image building succeeding

### Repro steps

- run the image generation inside an ADO pipeline

**Comment by mikhailkoliada** [comment]
Hello! This is expected, the machine where the build is running is not the machine you are running your pipeline from, therefore it has no `$env:AGENT_NAME` and this test is being run detecting your machine is being out of space, but given you are running a private build it is not mandatory for you to keep this test at all.
