### ISSUE TITLE
Job stuck for windows OS build - Windows2022

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#9518]
### Description

Job stuck for windows OS build

==> azure-arm.image: Waiting for machine to restart...
==> azure-arm.image: A system shutdown is in progress.(1115)
==> azure-arm.image: A system shutdown is in progress.(1115)
==> azure-arm.image: #< CLIXML
    azure-arm.image: pkrvmeqll1ltxae restarted.
==> azure-arm.image: <Objs Version="1.1.0.1" xmlns="[http://schemas.microsoft.com/powershell/2004/04"><Obj](http://schemas.microsoft.com/powershell/2004/04%22%3E%3CObj) S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm.image: Machine successfully restarted, moving on
==> azure-arm.image: Provisioning with Powershell...
==> azure-arm.image: Provisioning with powershell script: /tmp/powershell-provisioner574559651
    azure-arm.image: IMAGE_STATE_COMPLETE
    azure-arm.image: IMAGE_STATE_UNDEPLOYABLE

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20240310.1.0

### Is it regression?

NA

### Expected behavior

build image

### Actual behavior

Job stuck for windows OS build

==> azure-arm.image: Waiting for machine to restart...
==> azure-arm.image: A system shutdown is in progress.(1115)
==> azure-arm.image: A system shutdown is in progress.(1115)
==> azure-arm.image: #< CLIXML
    azure-arm.image: pkrvmeqll1ltxae restarted.
==> azure-arm.image: <Objs Version="1.1.0.1" xmlns="[http://schemas.microsoft.com/powershell/2004/04"><Obj](http://schemas.microsoft.com/powershell/2004/04%22%3E%3CObj) S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm.image: Machine successfully restarted, moving on
==> azure-arm.image: Provisioning with Powershell...
==> azure-arm.image: Provisioning with powershell script: /tmp/powershell-provisioner574559651
    azure-arm.image: IMAGE_STATE_COMPLETE
    azure-arm.image: IMAGE_STATE_UNDEPLOYABLE

### Repro steps

rerun pipeline

**Comment by jaswant-dnv** [comment]
Assumign defender for VM/servers is enabled and causing this.
But we can not disable defender and need work around.

**Comment by mikhailkoliada** [comment]
Hey! I guess you can find this discussion useful: https://github.com/actions/runner-images/discussions/6251 we can not help with any workaround as packer is blocked by in-tenant settings which can not be leveraged via the packer options.
