### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job

### ISSUE THREAD

**Issue by kasium** [actions/runner-images#9519]
### Description

If I schedule the [release job of sqlalchemy-hana](https://github.com/SAP/sqlalchemy-hana/actions/workflows/release.yml), it runs for 1min and stops w/o any log with `GitHub Actions has encountered an internal error when running your job`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

unknown, no log available 

### Is it regression?

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240304.1

### Expected behavior

should work

### Actual behavior

GitHub Actions has encountered an internal error when running your job.

### Repro steps

1. Trigger the release action of `sqlalchemy-hana`: https://github.com/SAP/sqlalchemy-hana/actions/runs/8301603439

**Comment by Alexey-Ayupov** [comment]
Hello @kasium, we will take a look.

**Comment by kasium** [comment]
Thanks, FYI, the issue did not occur again in the meantime

**Comment by Alexey-Ayupov** [comment]
Hello @kasium. Unfortunately I did not find any logs from your failed run, so cannot provide a root cause. It looks like was a glitch and now everything is ok.
If you have any other questions feel free to reach us.

**Comment by kasium** [comment]
Thanks a lot for the analysis!
