### ISSUE TITLE
Add: Runner - Fedora Images

### ISSUE THREAD

**Issue by Dylan-M** [actions/runner-images#9520]
### Tool name

Fedora Linux

### Tool license

https://docs.fedoraproject.org/en-US/legal/fedora-linux-license/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Rawhide, Latest 2 Branched Releases

### Brief description of request

Fedora has been [requested](#1443) many times.

Per #1443, "Since we see popularity of this request, we will keep it on mind and will be able to revisit this decision in future."

That popularity has not ceased, with at least six (counting this one) issues requesting it in some fashion.

There are many reasons why doing this via containers running on the Ubuntu image is not a valid enough solution. For example, there are just some things you cannot do with a container.

Reasons to add this:
1. It is the only missing "major" packaging scheme (RPM)
2. RedHat (.rpm) base, and Debian (.deb) are the 2 largest Linux environment bases.
    Yes, there are many other packaging schemes in the Linux world, but none of them
    with the adoption of RPM and DEB.
3. Testing of systemd service files (And with a minimal effort, also older sysv init scripts for those of us who have to support them)
4. More representative environment. If my customers are all using RPM based systems, testing on DEB based systems such as Ubuntu is not a representative environment.
5. In many instances Fedora can be a stand in for RHEL, CentOS Stream, SuSE Linux Enterprise, OpenSuSE, Rocky Linux, AlmaLinux, and a few others for most testing due to the shared RPM packaging base.
6. Sometimes it is just important to make your users happy, and with the popularity of this request; this _might_ be one of those times.
7. Potential community support that can offload some of the work of maintaining this from the GitHub team.
8. Self hosted runners are also not realistic for everyone.

Related issues:
#45
#898
#1443
#2307
simphony/simphony-remote/pull/558
RedHatInsights/compliance-backend/pull/1136
osalbahr/pmem-redirection/issues/1

### URL for tool's homepage

https://fedoraproject.org/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

**Comment by Alexey-Ayupov** [comment]
Hello @Dylan-M . Unfortunately the decision is the same, we are not planning to add  Fedora Linux as a new image.

If you have any questions feel free to reach us.

**Comment by stefan-it** [comment]
Guys, is there any progress on adding more Runner Images?

Fedora is declined, even no image for Debian is available (why the holy distribution fish, Debian was first...)

I guess self-hosting a runner is really the best option.

**Comment by GongT** [comment]
Ubuntu's official kernel and packages is too old 🥺
