### ISSUE TITLE
Update/Add Bun

### ISSUE THREAD

**Issue by TomasHubelbauer** [actions/runner-images#9521]
### Tool name

Bun

### Tool license

MIT https://bun.sh/docs/project/licensing

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

Hi, I'd like to request that Bun, the alternative JavaScript runtime to Node, be added to the runner images by default. It would eliminate the need to add an explicit installation step for it (https://bun.sh/guides/runtime/cicd) the same way we don't need to do this for Node if we're okay with the OOTB version.

### URL for tool's homepage

https://bun.sh/

### Provide a basic test case to validate the tool's functionality.

```bash
bun -v
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
https://bun.sh/install
```

### Are you willing to submit a PR?

Sure, if there's interest in adding this from the maintainers and there is a guide showing how to do it or an example to copy (like the way Node is currently being installed)

**Comment by Alexey-Ayupov** [comment]
It was decided not to add this tool to the Ubuntu images due to maintenance concerns and relatively short installation time. Please continue installing it in runtime.

If you have any questions feel free to reach us.

**Comment by Jarred-Sumner** [comment]
@Alexey-Ayupov is there anything we can do on Bun's end to make it easier to include Bun in the GitHub runner images?

**Comment by lobaorn-bitso** [comment]
Hey @Jarred-Sumner @erik-bershel @Alexey-Ayupov any news regarding this? Is it not to be reconsidered even now for Ubuntu 26 runners?
