### ISSUE TITLE
Memory Sanitizer build with same commit crashed in recent Ubuntu image

### ISSUE THREAD

**Issue by Chilledheart** [actions/runner-images#9525]
### Description

Previously the memory santizer bots run well in Github Actions such as [f31ac3b](https://github.com/Chilledheart/yass/actions/runs/8267819525) but it continues to fail after a special day.

![image](https://github.com/actions/runner-images/assets/54673341/c587c42c-ccfe-4fef-9406-2f63c3a9a17a)

After some triangle, it is found that it seems the issue isn't affect by the source code but Github Action image because when retried with the same commit [f31ac3b](https://github.com/Chilledheart/yass/actions/runs/8267819525), the new runner continues to fail such as  [new runner on f31ac3b](https://github.com/Chilledheart/yass/actions/runs/8320263119/job/22764718977) .

Memory Sanitizer builds are now failing to run both of debug and release builds.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240310.1.0

https://github.com/Chilledheart/yass/actions/runs/8320263119/job/22764718466
https://github.com/Chilledheart/yass/actions/runs/8299018778
https://github.com/Chilledheart/yass/actions/runs/8308892204

### Is it regression?

Yes 20240304.1.0 https://github.com/Chilledheart/yass/actions/runs/8267819525/job/22619190023

### Expected behavior

The binaries are able to run well and the test cases should be passed.

### Actual behavior

The debug builds failed and the release builds crashed once the built binaries started up.

### Repro steps

1. Build Unittests
2. Run Unittests

**Comment by Alexey-Ayupov** [comment]
Hello @Chilledheart we will take a look.

**Comment by Alexey-Ayupov** [comment]
@Chilledheart, after quick investigation we have found that your issue is related to #9491. 
We will close this issue as duplicate, if you have any other questions feel free to reach us.

**Comment by Chilledheart** [comment]
Thanks for the quick reply. I will subscribe the issue you mentioned.

**Comment by Chilledheart** [comment]
@Alexey-Ayupov As I mentioned in https://github.com/actions/runner-images/issues/9491#issuecomment-2003605933, I think you probably want to re-open this issue because the original issue only affects ASAN but for my case I am using the latest toolchain so ASAN is good but MSAN is not.

**Comment by Chilledheart** [comment]
<img width="327" alt="Screenshot 2024-03-18 at 18 56 45" src="https://github.com/actions/runner-images/assets/54673341/ded140e2-00af-4474-868c-eface53588d0">

ASAN is good but MSAN is not.
