### ISSUE TITLE
Non-spectre VS libraries are loaded for spectre-enabled project, which leads to binskim warnings 

### ISSUE THREAD

**Issue by sureshyerva87** [actions/runner-images#9533]
### Description

My C++ DLL project (on Windows) has dependency on some of VS libraries (such as krnel32.dll). I've added those dependencies to Additional Dependencies section of project properties. And the project is spectre-enabled. Binskim reports warnings for VS libraries (as below). This blocks warning-free use of BinSkim for binaries.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Visual Studio 2019
Platform Toolset v142
Windows C++ DLL project

### Is it regression?

No

### Expected behavior

When running the Guardian: BinSkim task to scan for vulnerabilities in compiled binaries, no warnings due to the CRT being used should be encountered.

### Actual behavior

At a minimum, libcmt.lib, libcpmt.lib, libvcruntime.lib, msvcrt.lib, and msvcprt.lib are impacted.

Binskim warnings for MD runtime library flag with Spectre-enabled
[MD_Spectre.txt](https://github.com/actions/runner-images/files/14644726/MD_Spectre.txt)

Binskim warnings for MT runtime library flag with Spectre-enabled
[MT_Spectre.txt](https://github.com/actions/runner-images/files/14644727/MT_Spectre.txt)

### Repro steps

1. Create a C++ Windows DLL project (in VS2019 or VS2022)
2. Add source files to use any of above .lib files (such as libcmt.lib, libcpmt.lib, libvcruntime.lib, msvcrt.lib, and msvcprt.lib)
3. Add the VS lib used in Project Properties-> Linker -> Additional Dependencies
4. Enable Spectre
5. Create project DLL
6. Run binskim scan

**Comment by Alexey-Ayupov** [comment]
Hello @sureshyerva87. I'm afraid we can't help you since we're installing Visual Studio and its components without any modifications. Could you please ask the [VS developer community](https://developercommunity.visualstudio.com/home) for help, I hope they will be able to help you.
If you have any other questions feel free to reach us.
