### ISSUE TITLE
Waiting for SSH to become available... Timeout

### ISSUE THREAD

**Issue by lzandman** [actions/runner-images#9535]
### Description

I've been trying all day to build my own runner images. However, following the [instructions ](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#manual-image-generation) to build a `MinimalUbuntu`, it keeps failing with a timeout while waiting for SSH to become available. I've also tried the other two Ubuntu images, but keep getting the same error.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I don't think this is applicable.

### Is it regression?

No

### Expected behavior

I expect Packer to be able to connect to the VM using SSH and complete the runner config.

### Actual behavior

Script timeout.

### Repro steps

https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#manual-image-generation

**Comment by holgerjs** [comment]
Maybe your network settings are preventing outbound ssh connections to public ip adresses? I've been facing a similar issue a while ago when I was running packer on an Azure VM where the NSG was blocking SSH connections to the internet.

**Comment by Alexey-Ayupov** [comment]
Hello @lzandman. I also believe that something in your environment is preventing SSH communication. Did you follow the instruction step by step without any deviation?

**Comment by lzandman** [comment]
I seems you guys are right. Something on my side is blocking the SSH connection. I just tried creating a runner image on my personal Macbook and that worked just fine. Will investigate tomorrow, but I think this issue can be closed. Thanks!
