### ISSUE TITLE
Update/Add pigz

### ISSUE THREAD

**Issue by camscale** [actions/runner-images#9539]
### Tool name

pigz

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Any / latest

### Brief description of tool

pigz is parallel gzip:

* https://zlib.net/pigz/
* https://github.com/madler/pigz

### URL for tool's homepage

https://zlib.net/pigz/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install pigz
```

### Are you willing to submit a PR?

Yes

**Comment by camscale** [comment]
pigz was added to Ubuntu runners in https://formulae.brew.sh/formula/pigz.

It would be nice to have this also on Mac runners so I don't need a conditional step in a workflow to install it. It makes sense that runners are common across platforms as much as possible.

**Comment by Alexey-Ayupov** [comment]
Hello @camscale, we will review the possibility to add this app.

**Comment by Alexey-Ayupov** [comment]
Hello @camscale. It was decided not to add this tool due to maintenance concerns and relatively short installation time. Please continue installing it in runtime.

If you have any questions feel free to reach us.

**Comment by camscale** [comment]
Does this mean it will be removed from the Ubuntu images at all? Should I be adding a step to install it on Ubuntu as well?

**Comment by jeffwidman** [comment]
FWIW, we (the :Dependabot: team, who originally requested `pigz` in #8205) have now switched to `zstd` as we found it provided better compression than `gzip` w/o losing the parallelism of `pigz`:
* https://github.com/dependabot/dependabot-core/pull/7950

So we no longer need `pigz` installed in the runner image.
