### ISSUE TITLE
Docs mention password in HCL2 file, but that's no longer the case.

### ISSUE THREAD

**Issue by lzandman** [actions/runner-images#9545]
### Description

The "[Debugging Failed Packer Builds](https://github.com/actions/runner-images/blob/main/docs/debugging-failed-builds.md)" article refers to a password that can be copied from the appropriate HCL2 file. However, I looked at the code and it seems the password is no longer present in the HCL2 file. Instead, it is [generated at runtime](https://github.com/actions/runner-images/blob/88b4de5d653020e38ff5f83876ce94324224ee30/helpers/GenerateResourcesAndImage.ps1#L210). Shouldn't the docs be updated to reflect this?

The doc location:
https://github.com/actions/runner-images/blob/88b4de5d653020e38ff5f83876ce94324224ee30/docs/debugging-failed-builds.md?plain=1#L24C54-L24C92

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not applicable.

### Is it regression?

No

### Expected behavior

Docs reflect the actual code.

### Actual behavior

Docs don't match the code.

### Repro steps

Not applicable.

**Comment by Alexey-Ayupov** [comment]
Hello @lzandman. Nice catch, we will think about how best to deal with this document.

**Comment by mikhailkoliada** [comment]
This doc is really out of date and does not make any sense to keep it around, I've made a PR to delete it.
