### ISSUE TITLE
Update jq to 1.7.1 on Ubuntu Runners

### ISSUE THREAD

**Issue by Arthri** [actions/runner-images#9550]
### Tool name

jq

### Tool license

CC3.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.7.1

### Brief description of tool

jq is query JSON documents

### URL for tool's homepage

https://github.com/jqlang/jq

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

Yes

### Tool installation time in runtime

A few seconds

**Comment by sergei-pyshnoi** [comment]
Hello @Arthri . For ubuntu images we install `jq` from official `apt` repo that contain only `1.6` version. We do not have plans for install it from another sources. I am closing this issue, but if you have additional questions feel free to ask.
