### ISSUE TITLE
Windows 2022 - Build - Unable to resolve dependency dotnet 3.5 and packer

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#9552]
### Description

azure-arm.image:  - wixtoolset - Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
    azure-arm.image: Running [#4]: choco install wixtoolset -y --force
    azure-arm.image: Chocolatey v2.2.2
    azure-arm.image: Installing the following packages:
    azure-arm.image: wixtoolset
    azure-arm.image: By installing, you accept licenses for the packages.
    azure-arm.image: Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
    azure-arm.image:
    azure-arm.image: Chocolatey installed 0/1 packages. 1 packages failed.
    azure-arm.image:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm.image:
    azure-arm.image: Failures
    azure-arm.image:  - wixtoolset - Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

azure-arm.image:  - wixtoolset - Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
    azure-arm.image: Running [#4]: choco install wixtoolset -y --force
    azure-arm.image: Chocolatey v2.2.2
    azure-arm.image: Installing the following packages:
    azure-arm.image: wixtoolset
    azure-arm.image: By installing, you accept licenses for the packages.
    azure-arm.image: Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
    azure-arm.image:
    azure-arm.image: Chocolatey installed 0/1 packages. 1 packages failed.
    azure-arm.image:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm.image:
    azure-arm.image: Failures
    azure-arm.image:  - wixtoolset - Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

### Is it regression?

No

### Expected behavior

Expect image to be generated.

### Actual behavior

azure-arm.image:  - wixtoolset - Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
    azure-arm.image: Running [#4]: choco install wixtoolset -y --force
    azure-arm.image: Chocolatey v2.2.2
    azure-arm.image: Installing the following packages:
    azure-arm.image: wixtoolset
    azure-arm.image: By installing, you accept licenses for the packages.
    azure-arm.image: Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.
    azure-arm.image:
    azure-arm.image: Chocolatey installed 0/1 packages. 1 packages failed.
    azure-arm.image:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm.image:
    azure-arm.image: Failures
    azure-arm.image:  - wixtoolset - Unable to resolve dependency 'dotnet3.5'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

### Repro steps

Run the image generation script and it would fail as noted above.

**Comment by vamshisiram** [comment]
HI All,

I downloaded code from two days ago and it failed similar error. Pls help this is stopping our builds for windows.

azure-arm.image: Running [#1]: choco install packer -y
    azure-arm.image: Chocolatey v2.2.2
    azure-arm.image: Installing the following packages:
    azure-arm.image: packer
    azure-arm.image: By installing, you accept licenses for the packages.
    azure-arm.image: packer not installed. The package was not found with the source(s) listed.
    azure-arm.image:  Source(s): 'https://community.chocolatey.org/api/v2/'
    azure-arm.image:  NOTE: When you specify explicit sources, it overrides default sources.
    azure-arm.image: If the package version is a prerelease and you didn't specify `--pre`,
    azure-arm.image:  the package may not be found.
    azure-arm.image: Please see https://docs.chocolatey.org/en-us/troubleshooting for more
    azure-arm.image:  assistance.
    azure-arm.image:
    azure-arm.image: Chocolatey installed 0/1 packages. 1 packages failed.
    azure-arm.image:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm.image:
    azure-arm.image: Failures
    azure-arm.image:  - packer - packer not installed. The package was not found with the source(s) listed.
    azure-arm.image:  Source(s): 'https://community.chocolatey.org/api/v2/'
    azure-arm.image:  NOTE: When you specify explicit sources, it overrides default sources.
    azure-arm.image: If the package version is a prerelease and you didn't specify `--pre`,
    azure-arm.image:  the package may not be found.
    azure-arm.image: Please see https://docs.chocolatey.org/en-us/troubleshooting for more
    azure-arm.image:  assistance.

**Comment by vamshisiram** [comment]
I even tried downloading code from five days ago https://github.com/actions/runner-images/tree/65efa8ca2d33fb499f6fa36f5dc16f43b4c2ee63 and i am now getting this error reported here but i am using windows 2022 : https://github.com/actions/runner-images/issues/9553

So, four attempts with last four commits and all fail with different errors. Hope that someone can help resolve one of these.

**Comment by sergei-pyshnoi** [comment]
Hello @vamshisiram . Looks like problem was on 'choco' side. That's why checkout previous commits didn`t helps. I tried to run manually on local machine `choco install wixtoolset` and installation finished successfully.  Please, checkout latest commit from `main` branch and try again. 

I am closing issue for now but if you have additional questions feel free to ask.

**Comment by vamshisiram** [comment]
Hi,

I tried four different Commits.

I see latest commit from 15 mins ago. Is that the one you want me to try now?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikhailkoliada** [comment]
hey, the error you see is not really connected with the state of the repo, but rather state of choco package manager itself, so while we always encourage using the latest commit from main, if this specific problem is there the commit won't change this situation

**Comment by vamshisiram** [comment]
Thanks for the clarification.

I first tried the latest commit from main and got the dotnet error.

I just downloaded the latest commit from main from you and trying that now. If it fails again I will let you know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vamshisiram** [comment]
@mikhailkoliada the latest from main branch still fails with same error. So, you are saying that the CDN for chocolatey is having issues and we just have to try again until it succeeds, is that the right way to put this? please let me know.
