### ISSUE TITLE
GenerateResourcesAndImage for Windows 2019 fails with C:\ProgramData\docker\cli-plugins already exists

### ISSUE THREAD

**Issue by clbarrett** [actions/runner-images#9553]
### Description

Getting the following error when running GenerateResourcesAndImage for Windows2019:
"New-Item : An item with the specified name C:\ProgramData\docker\cli-plugins already exists"

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Windows 2019

### Is it regression?

Not that I'm aware of

### Expected behavior

I expect the build to complete and create a viable Windows 2019 build agent image

### Actual behavior

Fails with the following error:

    azure-arm.image: Chocolatey installed 2/2 packages.
    azure-arm.image:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm.image: Package installed: docker-compose|2.26.0
    azure-arm.image: Install-Package Docker-Compose v2
==> azure-arm.image: New-Item : An item with the specified name C:\ProgramData\docker\cli-plugins already exists.
==> azure-arm.image: At C:\Windows\Temp\script-6600d936-3c53-a9b8-af17-02b9ef79c5ce.ps1:17 char:1
==> azure-arm.image: + New-Item -Path $cliPluginsDir -ItemType Directory
==> azure-arm.image: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : ResourceExists: (C:\ProgramData\docker\cli-plugins:String) [New-Item], IOException
==> azure-arm.image:     + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand
==> azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.image: Step "StepProvision" failed
==> azure-arm.image: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?

### Repro steps

cd <runner-image location>
az login

Import-Module .\helpers\GenerateResourcesAndImage.ps1
GenerateResourcesAndImage -SubscriptionId <MySubscriptionHere> -ResourceGroupName PackerBuildAgentWindowsRG -ImageType Windows2019 -ManagedImageName "BuildAgentWin19_IMG" -AzureLocation "westus2" -ImageGenerationRepositoryRoot <Runner-image location>

**Comment by sergei-pyshnoi** [comment]
Hello  @clbarrett . Thanks for your report. We working on it.

**Comment by mikhailkoliada** [comment]
Should be fixed, please pull your main branch updates.
