### ISSUE TITLE
windows : Packer could not be installed, version not found at chcolatey

### ISSUE THREAD

**Issue by vamshisiram** [actions/runner-images#9564]
### Description

build of windows fails with this consistently. 

i attempted with latest commit from main branch since last two days (five attempts) with no luck.

last commit i used it this one., the latest commit as of that time, https://github.com/actions/runner-images/tree/9ee0335bca637272ec439ed8b9a8b9108a7d39b2 per suggestion from @mikhailkoliada from previous issue https://github.com/actions/runner-images/issues/9552

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows 2022 or windows 2019

### Is it regression?

NO

### Expected behavior

build to succeed

### Actual behavior

fails with packer version not found, it appeart that packer version is incorrect or cdn issue, pls suggest resolution. I tried latest commit as suggested by @mikhailkoliada and it still fails.

azure-arm.image: Chocolatey installed 0/1 packages. 1 packages failed.
azure-arm.image: See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
azure-arm.image:
azure-arm.image: Failures
azure-arm.image: - packer - packer not installed. The package was not found with the source(s) listed.
azure-arm.image: Source(s): 'https://community.chocolatey.org/api/v2/'
azure-arm.image: NOTE: When you specify explicit sources, it overrides default sources.
azure-arm.image: If the package version is a prerelease and you didn't specify --pre,
azure-arm.image: the package may not be found.
azure-arm.image: Please see https://docs.chocolatey.org/en-us/troubleshooting for more
azure-arm.image: assistance.
azure-arm.image:
azure-arm.image: Did you know the proceeds of Pro (and some proceeds from other
azure-arm.image: licensed editions) go into bettering the community infrastructure?
azure-arm.image: Your support ensures an active community, keeps Chocolatey tip-top,
azure-arm.image: plus it nets you some awesome features!
azure-arm.image: https://chocolatey.org/compare
azure-arm.image: Could not install packer after 5 attempts

### Repro steps

CLone the latest commit at https://github.com/actions/runner-images/tree/9ee0335bca637272ec439ed8b9a8b9108a7d39b2

run generate image script

**Comment by sergei-pyshnoi** [comment]
Hello @vamshisiram . Looks like it is the same problem with `https://community.chocolatey.org/api/v2/` . We are looking on it.

**Comment by sergei-pyshnoi** [comment]
Our latest builds successful, so problem should be gone. Please try to build again.
