### ISSUE TITLE
macos-14 runner provides inconsistent macOS version

### ISSUE THREAD

**Issue by DanielKrofchick** [actions/runner-images#9568]
### Description

Requesting a `macos-14` runner randomly provides either a macOS 14.3.1 image (Version [20240219.1](https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240219.1)) or a macOS 14.2.1 image (Version 20240116.1, broken Image Release link https://github.com/actions/runner-images/releases/tag/macOS-14%2F20240116.1).

This wouldn't typically be an issue except our UI tests time out on 14.3.1 and pass on 14.2.1.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macOS 14.3.1: Version [20240219.1](https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240219.1)
macOS 14.2.1: Version 20240116.1, broken Image Release link https://github.com/actions/runner-images/releases/tag/macOS-14%2F20240116.1

### Is it regression?

Do Actions normally guarantee a stable OS version per runner?

### Expected behavior

I would expect a stable macOS version per runner. This would make it significantly easier to diagnose an OS specific issue.

### Actual behavior

macOS version provided is random.

### Repro steps

Run Action and see which version of the OS is provided.

**Comment by sergei-pyshnoi** [comment]
Hello @DanielKrofchick . Can you please provide jobs links with different image versions? It is ok if repo is private, its only for run identification.

**Comment by DanielKrofchick** [comment]
@sergei-pyshnoi sure,
macOS 14.3.1: https://github.com/carmigo/eblock-ios/actions/runs/8348979476/job/22852113225
macOS 14.2.1: https://github.com/carmigo/eblock-ios/actions/runs/8349945230/job/22855268413

**Comment by yksingh12** [comment]
I've also encountered an issue related to this. I've been using the 'macos-14' label, and starting from Friday, March 29th, it began defaulting to macOS 14.4, which has led to my builds failing. The command yarn install is not completing successfully, resulting in the error "/Users/runner/work/mobile-app/mobile-app/node_modules/sharp: Command failed". I can share the complete error log as well if that can help you debug it.

Everything was functioning correctly with the macOS 14.3.1 version.

**Comment by mikhailkoliada** [comment]
Runners should be consistent now.
