### ISSUE TITLE
Update Docker Compose

### ISSUE THREAD

**Issue by Tibo-lg** [actions/runner-images#9571]
### Tool name

docker compose

### Tool license

Apache

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.26.0 (>=2.24.7)

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by sergei-pyshnoi** [comment]
Hello @Tibo-lg . For now we do not have plans for updating docker-compose since its contain possible breaking changes.

**Comment by Tibo-lg** [comment]
Hello @sergei-pyshnoi. The reason I would like to update is because I'm seeing some DNS issues between containers (`Temporary failure in name resolution`) which happen on the runner but not locally. It looks rather similar to https://github.com/docker/compose/issues/11563 even though the version on the runner is different than the one mentioned in this issue so I'm not 100% sure. Do you know if there would be a way to manually update compose on the runner to check whether the issue gets solved? I tried to do so with `sudo apt install -y moby-compose` but was not able to restart the docker service afterwards.
