### ISSUE TITLE
cannot run sudo apt-get update in ubuntu 22.04.03

### ISSUE THREAD

**Issue by RussellFish** [actions/runner-images#9576]
### Description

when i run  sudo apt-get update  i get this long error message
russell@Russell-Fish:~$ sudo apt-get update
[sudo] password for russell:
Ign:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Err:2 http://archive.ubuntu.com/ubuntu jammy InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.91.81), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.82), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.83), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.48.79.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.55.83.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.48.79.30), connection timed out
Err:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.81), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.82), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.83), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to security.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to security.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to security.ubuntu.com:80 (192.48.79.30), connection timed out Could not connect to security.ubuntu.com:80 (192.55.83.30), connection timed out Could not connect to security.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to security.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to security.ubuntu.com:80 (192.48.79.30), connection timed out
Err:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable)
Err:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable)
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.91.81), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.82), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.83), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.48.79.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.55.83.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to archive.ubuntu.com:80 (192.48.79.30), connection timed out
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:502:7094::30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::19). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4002:1::101). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4002:1::102). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4002:1::103). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2620:2d:4000:1::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:502:1ca1::30). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:503:231d::2:30). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.81), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.82), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.83), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to security.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to security.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to security.ubuntu.com:80 (192.48.79.30), connection timed out Could not connect to security.ubuntu.com:80 (192.55.83.30), connection timed out Could not connect to security.ubuntu.com:80 (192.12.94.30), connection timed out Could not connect to security.ubuntu.com:80 (192.33.14.30), connection timed out Could not connect to security.ubuntu.com:80 (192.48.79.30), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

?

### Is it regression?

i think so

### Expected behavior

success

### Actual behavior

the long text above

### Repro steps
 sudo apt-get update

**Comment by sergei-pyshnoi** [comment]
Hello @RussellFish . Looks like problem in your environment. `apt` in image works correctly itself.
https://github.com/sergei-pyshnoi/workflow-test/actions/runs/8455109102/job/23161794246
I am closing issue as not runner-image related.
