### ISSUE TITLE
Update/Add Flutter

### ISSUE THREAD

**Issue by dan-at-confirm** [actions/runner-images#9587]
### Tool name

flutter

### Tool license

BSD 3-Clause "New" or "Revised" License

### Add or update?

- [x] Add
- [ ] Update

### Desired version

stable

### Brief description of tool

Flutter is a platform for building native iOS, Android, Desktop, and web apps.

It is an official Google project widely used in production

### Provide a basic test case to validate the tool's functionality.

```bash
...
- run: flutter pub get
- run: flutter build ios --release --no-codesign
- run: bundle update
- run: bundle exec fastlane development
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, there is an action for it.

https://github.com/subosito/flutter-action
```

### Tool installation time in runtime

1min 30sec

### Are you willing to submit a PR?

yes

**Comment by sergei-pyshnoi** [comment]
Hello @dan-at-confirm . We do not have plans to add flutter to runner-images due maintain concerns and small installation time. Please continue installing it in runtime.

**Comment by dan-at-confirm** [comment]
Ok. Appreciate you letting me know 🙏
