### ISSUE TITLE
Windows Server 2019 image (20240322) - installation fails - 'zstd' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by LubovKrasikova** [actions/runner-images#9588]
### Description

 Updating readme file for win19 version 20240322.1 is failing for Azure Devops Agents with the error:
```
    azure-arm.image: Describing Zstd
    azure-arm.image:   [-] zstd 859ms (619ms|240ms)
    azure-arm.image:    Command 'zstd -V' has finished with exit code 1 and output:
    azure-arm.image:        'zstd' is not recognized as an internal or external command,
    azure-arm.image:        operable program or batch file.
    azure-arm.image:    at "zstd -V" | Should -ReturnZeroExitCode, C:\image\tests\Tools.Tests.ps1:193
    azure-arm.image:    at <ScriptBlock>, C:\image\tests\Tools.Tests.ps1:193
```

`##[error]Error: The process 'C:\ProgramData\Chocolatey\bin\packer.exe' failed with exit code 1`

![image](https://github.com/actions/runner-images/assets/135702697/8c01e004-364d-4c04-96aa-60b8e725135e)

![image](https://github.com/actions/runner-images/assets/135702697/6a2f7e5e-cfec-49a4-9b84-ccde78419411)
 
![image](https://github.com/actions/runner-images/assets/135702697/5a1ad1a0-504f-4bbe-92fd-ea99a39e1bc7)

Previously this build was running successfully for other versions.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Pipelines -> runner-images -> Packer build

### Is it regression?

no

### Expected behavior

Packer build should be completed with a **success code 0**  and all tests are passed.: 
##[debug]Exit code 0 received from tool 'C:\ProgramData\Chocolatey\bin\packer.exe'

```
==> Builds finished. The artifacts of successful builds are:
##[debug]Exit code 0 received from tool 'C:\ProgramData\Chocolatey\bin\packer.exe'
##[debug]STDIO streams have closed for tool 'C:\ProgramData\Chocolatey\bin\packer.exe'
Finishing: Packer build
```

### Actual behavior

The build was finished with the **Exit code 1** and failed and test is failed for:
**Command 'zstd -V' has finished with exit code 1 and output:**
```
    azure-arm.image: Describing Zstd
    azure-arm.image:   [-] zstd 859ms (619ms|240ms)
    azure-arm.image:    Command 'zstd -V' has finished with exit code 1 and output:
    azure-arm.image:        'zstd' is not recognized as an internal or external command,
    azure-arm.image:        operable program or batch file.
    azure-arm.image:    at "zstd -V" | Should -ReturnZeroExitCode, C:\image\tests\Tools.Tests.ps1:193
    azure-arm.image:    at <ScriptBlock>, C:\image\tests\Tools.Tests.ps1:193
```

```
==> Some builds didn't complete successfully and had errors:
--> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
##[debug]Exit code 1 received from tool 'C:\ProgramData\Chocolatey\bin\packer.exe'
##[debug]STDIO streams have closed for tool 'C:\ProgramData\Chocolatey\bin\packer.exe'
##[debug]task result: Failed
##[error]Error: The process 'C:\ProgramData\Chocolatey\bin\packer.exe' failed with exit code 1
##[debug]Processed: ##vso[task.issue type=error;]Error: The process 'C:\ProgramData\Chocolatey\bin\packer.exe' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process 'C:\ProgramData\Chocolatey\bin\packer.exe' failed with exit code 1
Finishing: Packer build
```

### Repro steps

In Azure Devops create a new Pipeline to update image in Agents based on win-19 server: 

1. Select a source: GitHub
![image](https://github.com/actions/runner-images/assets/135702697/9c1515c6-4704-490e-8842-bcdcf90d4885)

2. Agent job: select agents pool which should be updated
3. Add task 'Packer init'
![image](https://github.com/actions/runner-images/assets/135702697/029fca6f-6454-4fc9-b825-23e76a3d5bc0)

4. Add task 'Packer build'
![image](https://github.com/actions/runner-images/assets/135702697/07dd8e8e-81e3-4f92-9b8a-5531f913df35)

5. Run the build (takes around 5 hours)

**Comment by sergei-pyshnoi** [comment]
Hello @LubovKrasikova . Unfortunately we cannot reproduce your error.
Here is `nightly` windows-2019 build  - https://dev.azure.com/github/runner-images/_build/results?buildId=135153&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a

Please, use latest commit from `main` branch for your image generation.  Current builds are not idempotent and if one tries to build a runner image using the specific tag it is not guaranteed that the build will succeed.

**Comment by JSeb084** [comment]
We encounter the same failure while using the windows2022 build:

`azure-arm.image: Found download url for facebook/zstd version 1.5.6: https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-v1.5.6-win64.zip
    azure-arm.image: Downloading package from https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-v1.5.6-win64.zip to C:\Users\packer\AppData\Local\Temp\zstd-v1.5.6-win64.zip...
    azure-arm.image: Package downloaded in 0.67 seconds
    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\zstd-v1.5.6-win64.zip' to 'C:\tools' directory
    azure-arm.image: Pester v5.5.0
    azure-arm.image:
    azure-arm.image: Starting discovery in 1 files.
    azure-arm.image: Discovery found 46 tests in 1.32s.
    azure-arm.image: Filter 'FullName' set to ('Zstd').
    azure-arm.image: Filters selected 1 tests to run.
    azure-arm.image: Running tests.
    azure-arm.image:
    azure-arm.image: Running tests from 'C:\image\tests\Tools.Tests.ps1'
    azure-arm.image: Describing Zstd
    azure-arm.image:   [-] zstd 799ms (576ms|223ms)
    azure-arm.image:    Command 'zstd -V' has finished with exit code 1 and output:
    azure-arm.image:        'zstd' is not recognized as an internal or external command,
    azure-arm.image:        operable program or batch file.
    azure-arm.image:    at "zstd -V" | Should -ReturnZeroExitCode, C:\image\tests\Tools.Tests.ps1:193
    azure-arm.image:    at <ScriptBlock>, C:\image\tests\Tools.Tests.ps1:193
    azure-arm.image: Tests completed in 4.99s
==> azure-arm.image: Test run has failed
`
