### ISSUE TITLE
Enhancement: Support for OCI?

### ISSUE THREAD

**Issue by tonic889** [actions/runner-images#9592]
### Description

For various reasons I am interested in building Azure Devops agents images from this project but deploying them to Oracle Cloud (OCI) rather than Azure.  Assuming I can figure out how to accomplish this in packer, would there be interest in a PR that would enhance this project to support deployment to OCI in addition to Azure?  

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I would assume that I can support all the existing images

### Is it regression?

No

### Expected behavior

The toolset would be enhanced to provide a new powershell function would accept the necessary parameters for deployment to OCI.

### Actual behavior

Currently toolset only supports deployment to Azure.

### Repro steps

N/A

**Comment by shamil-mubarakshin** [comment]
Hey @tonic889, thanks for reaching out.
Packer templates within this repository can used to build images for Azure, VMware, Veertu Anka. Each one of those comes with its own challenges and we continuously ensure their functionality.
There are no plans on supporting additional packer integrations. Source code and templates from this repository with some adjustment can be used to build images in other platforms
