### ISSUE TITLE
Update [NSIS]

### ISSUE THREAD

**Issue by xavier2k6** [actions/runner-images#9596]
### Tool name

NSIS (Nullsoft Scriptable Install System)

### Tool license

https://nsis.sourceforge.io/License

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.10

### Brief description of tool

NSIS (Nullsoft Scriptable Install System) is a professional open source system to create Windows installers

### URL for tool's homepage

https://nsis.sourceforge.io/Main_Page

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by shamil-mubarakshin** [comment]
Hey @xavier2k6, we will take a look

**Comment by shamil-mubarakshin** [comment]
@xavier2k6, tool [didn't pass](https://community.chocolatey.org/packages/nsis/3.10.0) choco checks, which we use to install NSIS. We would not like to include software at this time

**Comment by xavier2k6** [comment]
@shamil-mubarakshin Can you please re-open/re-evaluate as all checks on choco are now passing?!

**Comment by erik-bershel** [comment]
Hey @xavier2k6!
We'll work on it soon. Thank you for bringing it back to our attention.

**Comment by xavier2k6** [comment]
@erik-bershel Thanks!

**Comment by mikhailkoliada** [comment]
Deployed
