### ISSUE TITLE
Add `just` task runner

### ISSUE THREAD

**Issue by wiktor-k** [actions/runner-images#9597]
### Tool name

just

### Tool license

CC0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Just is a task runner similar to make but with less footguns. It's already quite popular (almost 17k stars) and is packaged in Debian testing as rust-just.

The only issue I see is just using CC0 license which is not on the "allow list". 😔

### URL for tool's homepage

https://github.com/casey/just

### Provide a basic test case to validate the tool's functionality.

```bash
just --help
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
cargo install just
```

### Are you willing to submit a PR?

Yes, if this gets "acked".

**Comment by shamil-mubarakshin** [comment]
Hello @wiktor-k! We would not like to install the tool due to small installation time and maintenance concerns.
