### ISSUE TITLE
pipx has been added, but is configured incorrectly

### ISSUE THREAD

**Issue by dalemyers** [actions/runner-images#9607]
### Description

In the latest macOS 13 arm64 image, pipx is now installed. However, it has been installed with the `PIPX_BIN_DIR` and `PIPX_HOME` variables set in a way which means the tool doesn't work. 

Here's what they are set to:

```
PIPX_BIN_DIR=/usr/local/opt/pipx_bin
PIPX_HOME=/usr/local/opt/pipx
```

By default, these should be:

```
PIPX_HOME="$HOME/Library/Application Support/pipx"
PIPX_BIN_DIR="$HOME/.local/bin"
```

With the ones that are set, we cannot use pipx as it tries to set up a virtual environment for itself and fails due to lack of access to that path. The workaround is to manually set the environment variables before using it. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Runner Image
Image: macos-13-arm64
Version: 20240219.3
Included Software: https://github.com/actions/runner-images/blob/macos-13-arm64/20240219.3/images/macos/macos-13-arm64-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13-arm64%2F20240219.3
```

### Is it regression?

20240219.3

### Expected behavior

See above

### Actual behavior

See above

### Repro steps

See above

**Comment by sergei-pyshnoi** [comment]
Hello @dalemyers . Thanks for your report. We are working on it.

**Comment by erik-bershel** [comment]
macOS arm64-based Images with the updated config delivered. :tada:
