### ISSUE TITLE
Azure CLI installer certificate thumbprint is outdated due to new release

### ISSUE THREAD

**Issue by BenedekFarkas** [actions/runner-images#9610]
### Description

Attempted to build a Windows 2022 image based on the [current latest `main` commit](2fd9adccce8acd226d394935c55b8a932b04d315), but it failed with the error below.

[Azure CLI 2.59.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.59.0) was released today, so the installer downloaded no longer matches what's expected in the build process.
It might be beneficial to introduce version pinning for this dependency and download the specific version from GitHub instead.

```
Provisioning with powershell script: images/windows/templates/../scripts/build/Install-AzureCli.ps1
    Install the latest Azure CLI release
    Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\ttejpecu.msi...
    Package downloaded in 2.58 seconds
Signature thumbprint do not match expected.
At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
+         throw "Signature thumbprint do not match expected."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    + FullyQualifiedErrorId : Signature thumbprint do not match expected.
```

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Functionally, it's like building the Windows 2022 image according to the 20240331.1.1 version, based on the 41ad29f9c97a8550b829f13607098a0ec8d565cd commit, whose build was successful in DevOps.

### Is it regression?

Yes: https://github.visualstudio.com/runner-images/_build/results?buildId=135183&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a

### Expected behavior

The installer's certificate thumbprint (`C2048FB509F1C37A8C3E9EC6648118458AA01780`) matches.

### Actual behavior

Building the image fails due to the actual certificate thumbprint (`F9A7CF9FBE13BAC767F4781061332DA6E8B4E0EE`) being different.

### Repro steps

Alternative repro is to download the installer from https://aka.ms/installazurecliwindowsx64 and running the following script:
```
Import-Module '<path-to-repository>\images\windows\scripts\helpers\InstallHelpers.ps1'
Test-FileSignature -Path '<path-to-installer>\azure-cli-2.59.0-x64.msi' -ExpectedThumbprint 'C2048FB509F1C37A8C3E9EC6648118458AA01780'
```

**Comment by erik-bershel** [comment]
Hey @BenedekFarkas!
Thank you for bringing this issue to our attention. Fix is in progress here: https://github.com/actions/runner-images/pull/9611.

**Comment by erik-bershel** [comment]
@BenedekFarkas should be fine now. 🥳

**Comment by BenedekFarkas** [comment]
Sounds good, I was about to submit a PR, but you beat me to it. :)

What do you think about

> It might be beneficial to introduce version pinning for this dependency and download the specific version from GitHub instead.

?

**Comment by erik-bershel** [comment]
> It might be beneficial to introduce version pinning for this dependency and download the specific version from GitHub instead.

We'll think about it. Might be beneficial, yes. But the same time not so crucial I may say.
