### ISSUE TITLE
macos-latest runner image is unable to find xcode-version - 15.2.0

### ISSUE THREAD

**Issue by SandeshKR** [actions/runner-images#9612]
### Description

macos-latest runner image is unable to find xcode-version - 15.2.0
![Screenshot 2024-04-02 at 9 45 25 AM](https://github.com/actions/runner-images/assets/4434963/cad052f5-fe27-4426-b4cb-1dbc9692e056)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner image: macos-latest

### Is it regression?

It is working fine in macos-13. macos-14 did not have an issue 4 days ago. 

### Expected behavior

macos-latest should have xcode 15.2.0

### Actual behavior

macos-latest is unable to find xcode 15.2.0

### Repro steps

runs-on: macos-latest
uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0

**Comment by mikhailkoliada** [comment]
macOS-latest is macOS 12 currently, if you need macOS 13 you should target macOS 13

**Comment by SandeshKR** [comment]
![Screenshot 2024-04-02 at 4 40 25 PM](https://github.com/actions/runner-images/assets/4434963/13081204-4423-4243-ac83-b17646820db6)
In the screenshot above, macos-latest points to macOS 14 Arm64.

Can you correct it to avoid confusion?

**Comment by mikhailkoliada** [comment]
True, I guess @Steve-Glass was a bit ahead of time, we'll take care of that

**Comment by Steve-Glass** [comment]
From the change log: https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

> Over the next 12 weeks, jobs using the macos-latest runner label will migrate from macOS 12 (Monterey) to macOS 14 (Sonoma). During migration, you can determine if your job has migrated by viewing the Runner Image information in the Set up job step of your logs. 

The migration happens behind the scene and there is nothing you need to do. If you need to use macOS 14 directly, please update your workflow file to `runs on: macos-14`.
