### ISSUE TITLE
Update/Add [tool name]Why is there no Windows 2012r2

### ISSUE THREAD

**Issue by ShopRobloxsieuuytin** [actions/runner-images#9615]
### Tool name

Window2012r2

### Tool license

Window2012

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Window2012r2

### Approximate size

4.6gb

### Brief description of tool

It is window2012r2 which can run things that window 2022 cannot

### URL for tool's homepage

Microsoft.com

### Provide a basic test case to validate the tool's functionality.

```bash
I tried running something on window 2022 and it doesn't work, please add window 2012r2 pls
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
No
```

### Tool installation time in runtime

0

### Are you willing to submit a PR?

0

**Comment by shamil-mubarakshin** [comment]
Hey @ShopRobloxsieuuytin, according to our [policy](https://github.com/actions/runner-images?tab=readme-ov-file#support-policy) we support 2 GA images. There are no plans on adding Windows 2012r2
