### ISSUE TITLE
Update docker compose

### ISSUE THREAD

**Issue by mfosterw** [actions/runner-images#9629]
### Tool name

Docker Compose

### Tool license

Apache 2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

\>=2.24

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mfosterw** [comment]
Nevermind, I just saw https://github.com/actions/runner-images/issues/9571, this can be closed as a duplicate, but how long do you plan to wait before accepting the change?

**Comment by shamil-mubarakshin** [comment]
Hello @mfosterw, closing as a duplicate of https://github.com/actions/runner-images/issues/9571. Unfortunately, there is no ETA as of now.
