### ISSUE TITLE
I believe you may need to add LIBRARY_PATH: "/opt/homebrew/lib" to the macos 14 image

### ISSUE THREAD

**Issue by LewisPringle** [actions/runner-images#9638]
### Description

I ran into a number of problems, like glibtoolize, and then not finding libidn2 during my builds. Its really SUCH A PITA to debug these problems since I cannot directly login and interact with the virtual machine BTW).

Anyhow - I believe I found the problem - which is that LIBRARY_PATH is empty, but brew install installs stuff to opt/homebrew/lib

Maybe you dont expect people to be using brew? Not sure. Anyhow - just a suggestion...

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/SophistSolutions/Stroika/blob/v3-Dev/.github/workflows/build-N-test.yml

BROKEN:
   https://github.com/SophistSolutions/Stroika/actions/runs/8558077781/job/23451846535

WITH MY WORKAROUND  MANUALLY SPECIFYING THIS ENV VAR:
   https://github.com/SophistSolutions/Stroika/actions/runs/8558121073/job/23451985744

### Is it regression?

wasn't a problem with macos14.2 so sort of...

### Expected behavior

LIBRARY_PATH: "/opt/homebrew/lib"

### Actual behavior

LIBRARY_PATH: ""

### Repro steps

echo $LIBRARY_PATH

**Comment by LewisPringle** [comment]
I think you maybe mistaken, or perhaps I've identified the wrong bug.

If your image provides a copy of 'brew' - and it does - that suggests brew is an OK way to install stuff. Brew is configured to install libraries in /opt/homebrew/lib (or so it appears to me). So the LIBRARY_PATH should be set to reflect that.

YES, its OK to NOT set that into LIBRARY_PATH, but then you should configure brew to install where you expect libraries installed.

Anyhow - I'm OK. Simple workaround. But I still suggest you reconsider/rethink.

**Comment by rohansingh** [comment]
This is particularly problematic because it "just worked" in previous version of the image, but library and include paths are now broken on newer versions.
