### ISSUE TITLE
GHA docs say `macos-latest` is `macos-14` (M1) but it is instead `macos-12` (Intel)

### ISSUE THREAD

**Issue by cclauss** [actions/runner-images#9640]
### Description

> The `macos-latest` label currently uses the macOS 14 runner image. 

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

# `macos-latest` and `macos-14`
macOS (`macos-latest`)
Current runner version: '2.315.0'
Operating System
  macOS
  12.7.4
  21H1123
Runner Image
  Image: macos-12

---
macOS (`macos-14`)
Current runner version: '2.315.0'
Operating System
  macOS
  14.4.1
  23E224
Runner Image
  Image: macos-14-arm64

### Is it regression?

No

### Expected behavior

It would be GREAT if M1 was the default but I sense that the default is still Intel.

### Actual behavior

Docs are incorrect.

### Repro steps

Run a GHA with `macos-latest` and look at `set up job`.

**Comment by mikhailkoliada** [comment]
@cclauss Hey! Please report to https://github.com/orgs/community/discussions (cc @Steve-Glass) as we do not maintain GitHub docs directly

**Comment by mikhailkoliada** [comment]
@cclauss actually no need to report, I clarified our docs a bit, https://github.com/actions/runner-images/pull/9642
