### ISSUE TITLE
Update/Add LocalDB to be SQL 2022

### ISSUE THREAD

**Issue by markalroberts** [actions/runner-images#9661]
### Tool name

SQL Server LocalDB

### Tool license

Free/Dev

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2022

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
https://stackoverflow.com/a/78038720/187030

- powershell: |
    Write-Host "================ Download SQL2022 installer==============="
    mkdir SQL2022
    $url = "https://go.microsoft.com/fwlink/?linkid=2215160"
    $outputFilePath = "$(System.DefaultWorkingDirectory)\SQL2022\SQL2022-SSEI-Expr.exe"
    Invoke-WebRequest -Uri $url -OutFile $outputFilePath
    tree $(System.DefaultWorkingDirectory) /F /A
    
    Write-Host "================Download and extract SqlLocalDB.MSI from installation media==============="
    & "$(System.DefaultWorkingDirectory)\SQL2022\SQL2022-SSEI-Expr.exe" /Action=Download /MediaType=LocalDB /Quiet /MEDIAPATH=$(System.DefaultWorkingDirectory)\SQL2022
    Start-Sleep -s 60.00 # Wait for the downlaoding to complete
    tree $(System.DefaultWorkingDirectory) /F /A
    
    Write-Host "================Run the SqlLocalDB.MSI installer non-interactively=============="
    msiexec.exe /qb /i $(System.DefaultWorkingDirectory)\SQL2022\en-US\SqlLocalDB.msi IAcceptSqlLocalDBLicenseTerms=YES
    Start-Sleep -s 60.00 # Wait for the installation to complete
    
    Write-Host "================Check SQLLocalDB verion and SQL Server installation path again==============="
    sqllocaldb versions
    sqllocaldb info
    tree "C:\Program Files\Microsoft SQL Server\" /F /A
  displayName: Install SQllocalDb for SQL Server 2022
```

### Tool installation time in runtime

20 seconds

### Are you willing to submit a PR?

Potentially yes, but not sure if the script above is the right approach - seems like it should be related to upgrading the VS 2022 local db runtime support?

**Comment by erik-bershel** [comment]
Hey @markalroberts!
Thank you for your interest for the project. Unfortunately, at the moment we are trying to make the images as light as possible and trying to avoid installing programs and packages that can be easily and quickly added at runtime. I'm forced to refuse to add this package due to maintenance concerns and runtime installation simplicity.

**Comment by markalroberts** [comment]
Thanks for the info... shame.... main reason we were against doing this as a custom install task was the extra ~20seconds it takes to download and install. Is there a way we can reuse/snapshot the customised version of a `vmImage` do you know, or will we just have to take this hit each time?

**Comment by erik-bershel** [comment]
> Is there a way we can reuse/snapshot the customised version of a vmImage do you know, or will we just have to take this hit each time?

Only self-hosted agents came to my mind.

**Comment by iernie** [comment]
@erik-bershel How exactly can you do this runtime? I'm having issues installing SQL 2022 in a github actions task.
