### ISSUE TITLE
`macos-latest` resolves to `macos-12` while it is documented to refer to `macos-14`

### ISSUE THREAD

**Issue by erikmd** [actions/runner-images#9663]
### Description

The `macos-latest` runner image resolves to `macos-12` (version 12.7.4) while it is documented to refer to `macos-14`.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240329.1

See also if need be: https://github.com/ocaml-sf/learn-ocaml/actions/runs/8621954279/job/23631973945?pr=597

### Is it regression?

N/A

### Expected behavior

According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories, we should get the Image: macos-14

### Actual behavior

We get the Image: macos-12

And the build fails with:

```
xcbeautify: A full installation of Xcode.app 15.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.
Xcode 15.0 cannot be installed on macOS 12.
You must upgrade your version of macOS.
Error: xcbeautify: An unsatisfied requirement failed this build.
```

### Repro steps

Push a commit in a repo's master branch with a following workflow such as:

```yaml
name: macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build learn-ocaml on macOS
    runs-on: macos-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: MWE
        run: |
          set -ex
          
          sw_vers
          system_profiler SPSoftwareDataType
          uname -a
          
          brew update
          
          # homebrew fails to upgrade python due to unlinking failure
          # (cf. https://github.com/actions/setup-python/issues/577 )
          rm -f /usr/local/bin/2to3
          rm -f /usr/local/bin/idle3
          rm -f /usr/local/bin/pydoc3
          rm -f /usr/local/bin/python3
          rm -f /usr/local/bin/python3-config
          rm -f /usr/local/bin/2to3-3.*
          rm -f /usr/local/bin/idle3.*
          rm -f /usr/local/bin/pydoc3.*
          rm -f /usr/local/bin/python3.*
          rm -f /usr/local/bin/python3.*-config
          rm -f /usr/local/lib/libtcl8.6.dylib
          rm -f /usr/local/lib/libtk8.6.dylib
          rm -f /usr/local/bin/go
          rm -f /usr/local/bin/gofmt
          rm -f /usr/local/bin/node
          rm -f /usr/local/bin/npm
          rm -f /usr/local/bin/npx
          rm -f -r /usr/local/include/node
          rm -f -r /usr/local/share/doc/node
          rm -f -r /usr/local/lib/node_modules
          rm -f /usr/local/lib/dtrace/node.d
          rm -f /usr/local/share/man/man1/node.1
          rm -f /usr/local/share/systemtap
          
          brew upgrade
```

**Comment by erik-bershel** [comment]
Hey @erikmd!
We are in process of migration. 
Closing as duplicate: https://github.com/actions/runner-images/issues/9640

**Comment by erikmd** [comment]
OK Thanks @erik-bershel ! and sorry for not spotting the duplicate myself…
