### ISSUE TITLE
Swift failing when generating Ubuntu2204 image

### ISSUE THREAD

**Issue by GavinToddlds** [actions/runner-images#9664]
### Description

When running the GenerateResourcesAndImages.ps1 it fails when running install-swift.sh
```
==> azure-arm.build_image: Downloading package from https://swift.org/builds/swift-5.10-release/ubuntu2204/swift-5.10-RELEASE/swift-5.10-RELEASE-ubuntu22.04.tar.gz to /tmp/swift-5.10-RELEASE-ubuntu22.04.tar.gz...
==> azure-arm.build_image: Package downloaded in 8 seconds
==> azure-arm.build_image: Downloading package from https://swift.org/keys/all-keys.asc to /tmp/all-keys.asc...
==> azure-arm.build_image: Package downloaded in 1 seconds
==> azure-arm.build_image: gpg: directory '/root/.gnupg' created
==> azure-arm.build_image: gpg: keybox '/root/.gnupg/swift' created
==> azure-arm.build_image: gpg: no valid OpenPGP data found.
==> azure-arm.build_image: gpg: Total number processed: 0
==> azure-arm.build_image: Script exited with non-zero exit status: 2. Allowed exit codes are: [0]
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

Yes, my last success was january release

### Expected behavior

Install swift and move to next tool

### Actual behavior

Erroring out on checking keys

### Repro steps

Run generateResouresandimage.ps1 with -ImageType "Ubuntu2204"

**Comment by erik-bershel** [comment]
Hey @GavinToddlds!
One of our nightly builds failed too. It should be transitive issue, but I'll wait for build to return green.

**Comment by spyder007** [comment]
FWIW, I have seen this issue pretty consistently since Monday at 1:00 pm EDT, I have tried a new build each day (using the latest code each time).

**Comment by GavinToddlds** [comment]
@erik-bershel Thanks for the update. I'm seeing the issue today as well.

**Comment by erik-bershel** [comment]
Just for the history and newcomers:
It seems to be not transitive. We are working on unlocking builds.

**Comment by erik-bershel** [comment]
Heads up!
PR merged - feel free to update your forks or clones to continue builds.
