### ISSUE TITLE
WiX 3.14.1 causes issues due to TEMP directory handling

### ISSUE THREAD

**Issue by JSdeJong** [actions/runner-images#9667]
### Description

Described in issue tracker: https://github.com/wixtoolset/issues/issues/8078

Remediation currently is to revert back to 3.14.0

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240322.1.0

### Is it regression?

No

### Expected behavior

Rollback WiX to 3.14.0 until the bug in WiX 3.14.1 is solved

### Actual behavior

WiX 3.14.1 is installed, which breaks Windows Installer builds due to bug in Wix 3.14.1.

See https://github.com/wixtoolset/issues/issues/8078

### Repro steps

Create a project that creates a Windows Installer file with a Custom Action
Build the project via Azure Pipelines on latest Windows 2019 or Windows 2022 build agent.
Run Windows Installer as user, it will return a SFXCA error in de Windows installer log file.

`SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)`

When building this project with a build agent that runs WiX 3.14.0, it will build a Windows Installer file that will not return this issue

**Comment by erik-bershel** [comment]
Hey @JSdeJong!
Thank you for bringing it to our attention. We'll think about what to do with this issue.

**Comment by erik-bershel** [comment]
Hi again @JSdeJong!
It was decided to wait for the new version of tool to be available. Previous version had (have?) other bugs and CVE: https://github.com/actions/runner-images/issues/9543
There is no particular point in replacing some breaking changes with others. I will leave this issue to better inform users until a new update occurs.

In the meantime there is a workaround you could use, it will take about couple minutes:
```powershell
choco install wixtoolset --version <desired_version> --allow-downgrade --force
```

**Comment by birarroshan** [comment]
Hello @erik-bershel  Is there any ETA for newer version in image? We are waiting on production release.

**Comment by JSdeJong** [comment]
It seems the fix for WiX is committed, but not released yet. So first have to wait for WiXToolset team to release a new version with the fix @birarroshan 

@erik-bershel Thanks for the _**very**_ quick reply! Currently we managed to downgrade WiX in our pipelines.

**Comment by erik-bershel** [comment]
I planing to close this item due to the fact that in general we cannot do anything on our part to resolve it without ruining the experience of other users. As I said, the release of a new image with the fixed `WIX` toolset will occur next week after the updates are published in the `Chocolatey` repository. Until then, we ask those who are affected by the `WIX` bug to use the workaround.

**Comment by birarroshan** [comment]
Hello @erik-bershel, I cannot see Wix release tag 3.14.2. May I know what is the next version?

**Comment by erik-bershel** [comment]
Hey @birarroshan! It isn't yet available in Choco. See there: https://community.chocolatey.org/packages/wixtoolset#versionhistory
We'll deploy it next week after the release in Chocolatey.

**Comment by thenextman** [comment]
> Hi again @JSdeJong! It was decided to wait for the new version of tool to be available. Previous version had (have?) other bugs and CVE: #9543 There is no particular point in replacing some breaking changes with others. I will leave this issue to better inform users until a new update occurs.
> 
> In the meantime there is a workaround you could use, it will take about couple minutes:
> 
> ```powershell
> choco install wixtoolset --version <desired_version> --allow-downgrade --force
> ```

Posting because I lost a bunch of time to this; but the above command won't work - I'm not sure why, but I suspect the WiX installer doesn't allow downgrades.

It's necessary to uninstall wixtoolset before installing the older version

`choco uninstall wixtoolset `

**Comment by tve-altx** [comment]
> We'll deploy it next week after the release in Chocolatey.
Do you have some information about release in Chocolatey?

**Comment by erik-bershel** [comment]
> Do you have some information about release in Chocolatey?

No, we do not have a separate communication channel with the Chocolatey support team.
