### ISSUE TITLE
[Ubuntu] ubuntu-toolchain-r/test repository will be removed from images on May 13

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9679]
### Breaking changes

The `ubuntu-toolchain-r/test` PPA will be removed from Ubuntu images.

### Target date

The images rollout process will start on May 13 and take 3-4 days.

### The motivation for the changes

We work towards reducing the number of third-party repositories used in the images generation process in order to provide better security and compatibility of Ubuntu runners.

### Possible impact

if your pipelines or workflows depend on the packages installed from this repository, they can become broken, this will also impact you, if your project is using GCC-13, as this version is currently not available in the LTS repositories of Ubuntu.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

The repository can still be added manually in runtime by calling to following commands:

```shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update -y
```

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by haampie** [comment]
This breaks all cached binaries compiled with any version of clang++ and g++-13.

**Comment by higaski** [comment]
The GCC-13 toolchain from `ppa:ubuntu-toolchain-r/test` is not compatible with sanitizers.

**Comment by higaski** [comment]
In times where people go like `npm install the entire fucking universe` inside their CI this decision seems questionable.

**Comment by hartwork** [comment]
This change broke things left and right, not cool: https://github.com/actions/runner-images/issues/9866#issuecomment-2119211496 .
