### ISSUE TITLE
Add macOS 11.3 SDK on MacOS 12 or 13

### ISSUE THREAD

**Issue by jeroen** [actions/runner-images#9682]
### Tool name

macOS SDK 11.3

### Tool license

not needed?

### Add or update?

- [X] Add
- [ ] Update

### Desired version

11 or 11.3	

### Brief description of tool

We use GHA for building binary packages for the R programming language. To maximize portability for end-uses we use macOS 11.3 SDK and set `MACOSX_DEPLOYMENT_TARGET=11.0`. I think many other FOSS projects that build releases on GHA do something similar.

Currently macos-11 runner is deprecated and will soon be removed. Would it be possible to install the 11 SDK on the macos-12 or macos-13 runners, such that we can use these to build release that can run on macos 11 and up?

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [x] macOS 12
- [x] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by MaksimZhukov** [comment]
Hello @jeroen!
It was decided not to add macOS 11.3 SDK to the macos-12 or macos-13 runners. According to our installation policy, we only install the macOS SDKs that come with Xcode.
