### ISSUE TITLE
Add Ubuntu 24.04 Noble Numbat

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9691]
### Tool name

ubuntu

### Tool license

OSS

### Add or update?

- [X] Add
- [ ] Update

### Desired version

24.04

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment]
The release is still planed on April 25th

**Comment by TomKeur** [comment]
Hopefully it will before august 9 :D 
Ubuntu 22.04 announce message: https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

**Comment by TomKeur** [comment]
> @TomKeur the announcement you pointed at is about GA, GA will be somewhere in August I think, but public beta is mid-May

Awesome, thanks for the heads up! 👍

**Comment by mungojam** [comment]
I'm interested to know if this will regress the .net 8 SDK version to 8.1xx, rather than the current 8.2xx given the changes in .net provision in Ubuntu 24.04

See the MS post [here](https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404) where I have [also commented](https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404/#comment-20737):

**Comment by vishalkhode1** [comment]
> The release is still planed on April 25th

Hi @mikhailkoliada
Any update on when release will be made ??

**Comment by mikhailkoliada** [comment]
@vishalkhode1 as stated in my previous [comment](https://github.com/actions/runner-images/issues/9691#issuecomment-2063926929) we plan to release it public beta mid May :)

**Comment by MikeMcC399** [comment]
@mikhailkoliada 

Is the [Ubuntu 24.04 LTS](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) runner supposed to be live already?
I can see it in the overview on [GitHub Actions Runner Images](https://github.com/actions/runner-images) with YAML Label `ubuntu-24.04`. 

If I try to use it I'm seeing it hang:

```text
Requested labels: ubuntu-24.04
Job defined at: xxxx
Waiting for a runner to pick up this job...
```

**Comment by mikhailkoliada** [comment]
@MikeMcC399 not yet, there will be a separate announcement once everything is available, we are just in the process of setting things up, that is why readme is there.

**Comment by MikeMcC399** [comment]
@mikhailkoliada 

Thanks for confirming the status! Looking forward to the announcement as soon as you're ready! 👍🏻

**Comment by mikhailkoliada** [comment]
Should be here now: https://github.com/actions/runner-images/issues/9848

**Comment by Anb111pip** [comment]
> ### _****_madny

**Comment by mungojam** [comment]
> ~I'm interested to know if this will regress the .net 8 SDK version to 8.1xx, rather than the current 8.2xx given the changes in .net provision in Ubuntu 24.04~
>  
> ~See the MS post [here](https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404) where I have [also commented](https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404/#comment-20737).~
> 
> Update: answered [very quickly](https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404/#comment-20738), so no worries. 

My fear came true, the new image only has .net 8.10x SDK so has broken some of our builds that depended on the later SDK versions

**Comment by richlander** [comment]
This appears to be the guidance. Does it not work?

![{7F86EDC7-8017-4508-911B-6F99DD1D916A}](https://github.com/user-attachments/assets/09e9744c-a706-4209-9e6a-abe31cfa43e4)

**Comment by mungojam** [comment]
It will work but will increase the time/cost of every one of our 100s of builds. It means that GitHub hosted runners are no longer the batteries included option.
