### ISSUE TITLE
[Ubuntu, Windows] Docker Compose v1 will be removed from images on July, 29

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9692]
### Breaking changes

Docker compose v1 will be removed from Ubuntu & Windows images.

### Target date

The images rollout process will start on July, 29 and take 3-4 days.

### The motivation for the changes

Docker compose v1 has been [deprecated](https://docs.docker.com/compose/migrate/) since July 2023 and customers are encouraged to migrate to v2, apart from that, as per our support [policy](https://github.com/actions/runner-images?tab=readme-ov-file#support-policy) it has been more that 6 months since the deprecation announcement so we would like to finally remove it. More information can also be found on the GitHub [blog](https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/).

### Possible impact

If your pipelines or workflows still depend on docker compose v1 they might be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [x] Windows Server 2019
- [x] Windows Server 2022

### Mitigation ways

The last release of the v1 branch is still [available](https://github.com/docker/compose/releases/tag/1.29.2) on GitHub and can be downloaded and installed manually in runtime for both Ubuntu and Windows.

**Comment by kekomenos** [comment]
#9717

**Comment by cPereira13** [comment]
e6:0F:53:71:CA:B8 WiFi pasword

**Comment by daveisfera** [comment]
I understand removing it from new images (like the Ubuntu 24.04 one that was just released), but why remove it from existing images?
That means that if I make a branch from an old tag to release a bug fix that I have to also worry about patching this as well?

**Comment by lukins-cz** [comment]
> Rozumím jeho odstranění z nových obrázků (jako je právě vydaný Ubuntu 24.04), ale proč to odstraňovat z existujících obrázků? To znamená, že když vytvořím větev ze staré značky, abych vydal opravu chyby, musím se také starat o opravu této chyby?

Hm toto je dobrá otázka. Nevím jak to mají vymyšlené, ale to co píšete je fakt

**Comment by Alexey-Ayupov** [comment]
The removal of Docker Compose v1 is postponed till 29 of July.

**Comment by ShaharM7** [comment]
@Alexey-Ayupov 
My workaround for that on **Azure DevOps Pipelines ** is to pass the path of the docker-compose plugin (of course before it needs to install it on the Agents - in my case, it is Redhat 8 machines): 

`      - task: DockerCompose@0
        displayName: 'Build Service Images'
        inputs:
          action: Build services
          dockerComposeFile: $(docker_compose_file_path)
          dockerComposePath: $(docker_compose_exe_path)
          detached: true
          dockerComposeFileArgs: |
            NPM_TOKEN=$(NPM_TOKEN)
            CI_BUILD_ID=$(Build.BuildId)
            AGENT_NAME=$(Agent.Name)
            IS_RUNNING_ON_NIGHT_INSTALLATION=$(is_running_on_night_installation)`

And the variable:  $(docker_compose_exe_path) is: 
`  - job: start_application_and_testing_for
    displayName: "Run E2E Tests For - "
    variables:
      - name: docker_compose_exe_path
        value: '/usr/libexec/docker/cli-plugins/docker-compose'`

**Comment by sandywangkpmg** [comment]
@Alexey-Ayupov  could you confirm if v2 executable will still be available at this path after the removal of v1? _/usr/libexec/docker/cli-plugins/docker-compose_

**Comment by Blackmaster88** [comment]
> ### Breaking changes
> Docker compose v1 will be removed from Ubuntu & Windows images.
> 
> ### Target date
> The images rollout process will start on July, 29 and take 3-4 days.
> 
> ### The motivation for the changes
> Docker compose v1 has been [deprecated](https://docs.docker.com/compose/migrate/) since July 2023 and customers are encouraged to migrate to v2, apart from that, as per our support [policy](https://github.com/actions/runner-images?tab=readme-ov-file#support-policy) it has been more that 6 months since the deprecation announcement so we would like to finally remove it. More information can also be found on the GitHub [blog](https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/).
> 
> ### Possible impact
> If your pipelines or workflows still depend on docker compose v1 they might be broken.
> 
> ### Platforms affected
> * [x]  Azure DevOps
> * [x]  GitHub Actions
> 
> ### Runner images affected
> * [x]  Ubuntu 20.04
> * [x]  Ubuntu 22.04
> * [ ]  macOS 11
> * [ ]  macOS 12
> * [ ]  macOS 13
> * [ ]  macOS 13 Arm64
> * [ ]  macOS 14
> * [ ]  macOS 14 Arm64
> * [x]  Windows Server 2019
> * [x]  Windows Server 2022
> 
> ### Mitigation ways
> The last release of the v1 branch is still [available](https://github.com/docker/compose/releases/tag/1.29.2) on GitHub and can be downloaded and installed manually in runtime for both Ubuntu and Windows.

**Comment by MMONSTER124** [comment]
{ "AccountIndex" : 2592906, "AccountIdHash" : "0fa4571185a72f98ae7fe6f3ba1dafe4c40c495e89e4f4ed951d3d14725e86f2", "TotalEquity" : 4287399285800000, "TotalDebt" : 3442722385200000, "Assets" : [ { "Index" : 2, "Equity" : 4053, "Debt" : 19 }, { "Index" : 148, "Equity" : 3127886, "Debt" : 2587484 } ], "Root" : "272cafea86240006f4e0d08502ff06d55e386202a48c38eab98304f43ec54266", "Proof" : [ "LhX8NdPxmmsN0UeMOLB0C9bcSrDaVslrk7+/wayVF44=", "GoLC22vcDMvA1kMBjNAX60BT4QmE7kmgKK++IAfFIvk=", "KAFtSjKxg5juRnfJE13Fm7nU1WUM0rYFiPO8+PBghbc=", "EvwIHunWHt/pfLTpcU0dlHofuGeZZHXgrUA8GUESYdo=", "HKKL1Tab0UrVpBD68iK1mbik9Pw/lfn5ioMghESnn8M=", "HxP4gI08JxaJibvZEL30xuX5aiqdUO22Gt6QsxegAQs=", "GYTtdi/ONE27BIqHf2aCH2rcndbSI9tPUfLkdABdz0w=", "BvdnXbWGt8VfTOibf3wshposQVz6nzfKhzU1WO3o6uQ=", "BxQZwRrGGrLMII4Gm5/SdVesithff9PwmIre94zcwnI=", "A9vNlxt4LbqDctidGqpm+/faP/FR6S/fUjc91RaaFKo=", "H8QC7vvqtQWg4yrYMEQ9uwTMBIDjwY0rTnqyrcMM4H4=", "G3Dg/V4C+sGqZiQXv55DhXlcQgJgOpijvoRu8CbqbgI=", "LqnwEFVP971Mt4PUmbBMAcyhX0AqmY3RH+z5GdPOJdA=", "KLdjD1hGTxKWhcvpd/KxULKf9TXE7fvyw5Hq/IIgasM=", "JU5QaEwXPf5YiSRpKLtwG1QcJmxOFAwh4wrbR4sFvDs=", "GrOjSzyOQdyX1Yg3c86JvkHx6bSh6z15fp5pepPeUyA=", "EHfdjjbtd9d7bjhyUpoJXWmvHQm9RYpvFSEHjtJHLJk=", "I8m1IIQRcCrjxEGYeLbGTBZhp5cj+uQyKrS129i6AIw=", "I7hMJCzWsvgx7J7zQdlRRX7KOZU25bVyaInGX064Bg8=", "BDNNc+3zW3jcOKeAn0MWNEAo/cxChrlFAc1YIK2rxqw=", "ICVwNzzOskoL3v3F35xvpMUFa9w3/I/Ew8DsMYwhVNI=", "KAnBcYNMwyAQ1ZMUqPHhH4Fi5bFPM45mMp0wYnW7bwA=", "EARemVtcpq9NGIcasaFYLZhAd2+rd9p2klWxizrY7ig=", "IWPO/Hp1trxgbsfkab8tD9JGyjRBUuXgKl0SUhW4qtY=", "Ka9Bm2US+/WINDk8MvytsX20bHmJZNoGWbwHD4VEUdc=", "DQaCV6xirXclfSEXLz5CThuLajuIKgG47BeV0u6jHHs=", "G3j3tGx68tGwEASTdGp53FVLiVKbv9e6NAYoXXX919M=", "FZccOkiNSW8NLDCniDlhv5iB8nemSPBCGmovBe5UdBc=" ] }

**Comment by adamdecaf** [comment]
Can breaking changes like this be announced better in the future? The changelog blog has tons of posts and that post doesn't have any labels about it being a breaking change. This issue just says "Announcement" but I didn't know we were supposed to follow this repository to be alerted on breaking changes.

Can't you see what programs orgs are using and notify them?

**Comment by molexx** [comment]
This has just broken our production deployments. Obviously we need those to be available so I've just spent my weekend time investigating and now testing because of this. Luckily we don't have an urgent hotfix to deploy right now.

Perhaps Actions users should be able to opt out of breaking changes?

**Comment by daveisfera** [comment]
> Can't you see what programs orgs are using and notify them?

Every single branch/tag that's using this is now broken, so the notification would be to basically every project that uses this in an action. So I think the better request is "can breaking changes like this not be done?"

Common practice is to remove support for older software when a new image is released, like what was done with the Ubuntu 24.04 release. Then the breaking changes are during upgrades and are expected instead of destroying the build process of so much existing software

**Comment by PhilippeFerreiraDeSousa** [comment]
1. I strongly disapprove of purposefully breaking everyone's CIs while only offering `latest` tags or treating all tags like `latest`.
2. Replace `docker-compose` by `docker compose`.

**Comment by ijunaidm** [comment]
Thank you , Closing this issue as the Docker compose V1 got removed from both Windows and Ubuntu/MacOS images.

**Comment by Nichebiche** [comment]
> ### Breaking changes
> Docker compose v1 will be removed from Ubuntu & Windows images.
> 
> ### Target date
> The images rollout process will start on July, 29 and take 3-4 days.
> 
> ### The motivation for the changes
> Docker compose v1 has been [deprecated](https://docs.docker.com/compose/migrate/) since July 2023 and customers are encouraged to migrate to v2, apart from that, as per our support [policy](https://github.com/actions/runner-images?tab=readme-ov-file#support-policy) it has been more that 6 months since the deprecation announcement so we would like to finally remove it. More information can also be found on the GitHub [blog](https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/).
> 
> ### Possible impact
> If your pipelines or workflows still depend on docker compose v1 they might be broken.
> 
> ### Platforms affected
> * [x]  Azure DevOps
> * [x]  GitHub Actions
> 
> ### Runner images affected
> * [x]  Ubuntu 20.04
> * [x]  Ubuntu 22.04
> * [ ]  macOS 11
> * [ ]  macOS 12
> * [ ]  macOS 13
> * [ ]  macOS 13 Arm64
> * [ ]  macOS 14
> * [ ]  macOS 14 Arm64
> * [x]  Windows Server 2019
> * [x]  Windows Server 2022
> 
> ### Mitigation ways
> The last release of the v1 branch is still [available](https://github.com/docker/compose/releases/tag/1.29.2) on GitHub and can be downloaded and installed manually in runtime for both Ubuntu and Windows.

Agree

**Comment by danieljamesscott** [comment]
Did docker-compose get put back in? We worked around this by installing docker-compose in our workflows, but the [recent docker upgrade](https://github.com/actions/runner-images/issues/13474) seems to have caused an issue with our workaround.

**Comment by erik-bershel** [comment]
Hey @danieljamesscott!

Nope.

**Comment by nichechristie** [comment]
lol. Nah haha lol 


Sent from Yahoo Mail for iPhone


On Friday, February 13, 2026, 6:43 AM, Erik Bershel ***@***.***> wrote:

erik-bershel left a comment (actions/runner-images#9692)
Hey @danieljamesscott!

Nope.
