### ISSUE TITLE
Install-WindowsUpdates.ps1 is failing to install April 2024 updates

### ISSUE THREAD

**Issue by frede192** [actions/runner-images#9694]
### Description

Windows April 2024 security update (KB5036909) fails to install.

![image](https://github.com/actions/runner-images/assets/167175084/bb4bf966-0a69-4658-bb7e-15f24ce22940)

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

latest version

### Is it regression?

Worked before patch April 9, 2024 

### Expected behavior

Updates should install successfully or at least image generation should complete

### Actual behavior

Updates do not install, image generation fails

### Repro steps

Trigger a build and wait

**Comment by MaksimZhukov** [comment]
Hello @frede192!
As you can see, [Windows22 test build](https://github.visualstudio.com/runner-images/_build/results?buildId=135299&view=results) on the `main` branch was successful yesterday. Please make sure you are using the `main` branch and correct configuration.

**Comment by frede192** [comment]
Hi @MaksimZhukov,

I just checked. We are using the main branch, and have followed these docs as part of setup:
https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#automated-image-generation

Our packer build command which results in a failed windows update looks as follows:
`
packer build -var "client_id=$ClientId" `
                -var "client_secret=$ClientSecret" `
                -var "install_password=$InstallPassword" `
                -var "location=$Location" `
                -var "subscription_id=$SubscriptionId" `
                -var "temp_resource_group_name=$TempResourceGroupName" `
                -var "tenant_id=$TenantId" `
                -var "virtual_network_name=$VirtualNetworkName" `
                -var "virtual_network_resource_group_name=$VirtualNetworkRG" `
                -var "virtual_network_subnet_name=$VirtualNetworkSubnet" `
                -var "managed_image_name=$ImageType-$ResourcesNamePrefix" `
                -var 'azure_tags={ "ExcludeMdeAutoProvisioning": "True" }' `
                -var "managed_image_resource_group_name=$ResourceGroup" `
                -color=false `
                $TemplatePath
`

**Comment by frede192** [comment]
Hi again @MaksimZhukov,

I tried to re-run the pipeline (without doing any changes) and today it works. 

So I do not know why 'Install-WindowsUpdates.ps1' failed yesterday when trying to install security update (KB5036909).

I will close this issue for now. If run into this problem again in the future, then we can revisit it then.

Thank you
