### ISSUE TITLE
[Windows-2022] Multiple VC Build Tools will be removed on May, 13

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9701]
### Breaking changes

We will commence the procedure of removing redundant `Microsoft.VisualStudio.Component.VC` components and leave only the latest available version of some oh them.

### Target date

The images rollout process will start on May, 13 and take 3-4 days.

### The motivation for the changes

Due to numerous reports regarding errors when using Visual Studio 2022 with multiple pre-installed versions of VC build tools, we are compelled to cease the distribution of alternative versions of the component. Detailed description of the problem can be found [here](https://developercommunity.visualstudio.com/t/MicrosoftVCToolsVersionv143defaulttx/10041951). The list of previously opened issues: #9670, #9404, #9086, #8891, #7867, #7832, #6107, #6091. Therefore, starting from May 6th, we will commence the procedure of removing redundant VC components and leave only the latest available version. We'll possibly reconsider this decision once the problem is resolved.

List of the VC components which are expected to be installed (if you notice that some useful base VC component is missing - indicate that in the comments, we will consider adding it):

| Package                                                                   | Version         |
| ------------------------------------------------------------------------- | --------------- |
| Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM                       | latest          |
| Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM64                     | latest          |
| Microsoft.VisualStudio.Component.VC.ASAN                                  | latest          |
| Microsoft.VisualStudio.Component.VC.ATL                                   | latest          |
| Microsoft.VisualStudio.Component.VC.ATL.ARM                               | latest          |
| Microsoft.VisualStudio.Component.VC.ATL.ARM.Spectre                       | latest          |
| Microsoft.VisualStudio.Component.VC.ATL.ARM64                             | latest          |
| Microsoft.VisualStudio.Component.VC.ATL.ARM64.Spectre                     | latest          |
| Microsoft.VisualStudio.Component.VC.ATL.Spectre                           | latest          |
| Microsoft.VisualStudio.Component.VC.ATLMFC                                | latest          |
| Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre                        | latest          |
| Microsoft.VisualStudio.Component.VC.CLI.Support                           | latest          |
| Microsoft.VisualStudio.Component.VC.CMake.Project                         | latest          |
| Microsoft.VisualStudio.Component.VC.CoreIde                               | latest          |
| Microsoft.VisualStudio.Component.VC.DiagnosticTools                       | latest          |
| Microsoft.VisualStudio.Component.VC.Llvm.Clang                            | latest          |
| Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset                     | latest          |
| Microsoft.VisualStudio.Component.VC.MFC.ARM                               | latest          |
| Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre                       | latest          |
| Microsoft.VisualStudio.Component.VC.MFC.ARM64                             | latest          |
| Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre                     | latest          |
| Microsoft.VisualStudio.Component.VC.Modules.x86.x64                       | latest          |
| Microsoft.VisualStudio.Component.VC.Redist.14.Latest                      | latest          |
| Microsoft.VisualStudio.Component.VC.Redist.MSM                            | latest          |
| Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre                  | latest          |
| Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre                | latest          |
| Microsoft.VisualStudio.Component.VC.Runtimes.ARM64EC.Spectre              | latest          |
| Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre              | latest          |
| Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest               | latest          |
| Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest              | latest          |

### Possible impact

Builds that require non-latest components missing from the list above will be broken.

### Platforms affected

- [x] Azure DevOps
- [x] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022

### Mitigation ways

Missing workloads can be installed manually in runtime. We recommend to uninstall unsupported workloads before installing new, it might be done using [this](https://github.com/actions/runner-images/issues/7832#issuecomment-1617585694) snippet.

```yml
    steps:
      - name: Delete components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                    "Microsoft.VisualStudio.Component.VC.ATL.ARM"
                    "Microsoft.VisualStudio.Component.VC.ATL.ARM.Spectre"
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      
      - name: Install components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                  "Microsoft.VisualStudio.Component.VC.14.39.17.9.ATL.ARM"
                  "Microsoft.VisualStudio.Component.VC.14.39.17.9.ATL.ARM.Spectre"
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

**Comment by malkia** [comment]
I saw only `Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM` and `Microsoft.VisualStudio.Component.VC.14.29.16.11.ARM64` - but not x64 and x86.

14.29 is Visual Studio 2019 (v142)

**Comment by erik-bershel** [comment]
Heads up.
Latest `windows-2022` image contains described list of VC tools. Please ping us if something went wrong.

**Comment by caesay** [comment]
This change is is "very not ideal" for me. Has broken all my fairly basic/standard Rust pipelines in a very non-obvious way (eg. builds succeed but now are producing invalid binaries). I assume that the new image is missing something which is critical for Rust. `Microsoft.VisualStudio.Component.VC.Tools.x86.x64` for sure? probably more.

**Comment by erik-bershel** [comment]
Hey @caesay!
Thank you for catching this bug. We'll add this component with the next `windows-2022` image release. If you see that something else is missing, be sure to mention it - we will definitely try to add it.

**Comment by Avasam** [comment]
Just a note that the `Mitigation ways` example script uses variable name `$componentsToRemove` for components to **add** in the second step.

**Comment by Avasam** [comment]
Why does vs_installer need to be run twice? And is there anyway to cache this installation across runs? Taking an extra ~8 minutes per job is really awful.

**Comment by Avasam** [comment]
https://github.com/mhammond/pywin32/pull/2582#discussion_r2062745965
> I tried to get info about the CI's VS and MSVC versions and this is what I got using `vswhere -latest` [mhammond/pywin32/actions/runs/14687605417/job/41218346703?pr=2582#step:6:6](https://github.com/mhammond/pywin32/actions/runs/14687605417/job/41218346703?pr=2582#step:6:6)
> 
> ```powershell
> $VS_PATH = vswhere.exe -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
> echo "VS_PATH=$VS_PATH" >> $env:GITHUB_ENV
> echo "MSVC_VERSION=$(((Get-Content "$VS_PATH\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt") -split '\.')[0..1] -join '.')" >> $env:GITHUB_ENV
> echo "VS_VERSION=$(((vswhere.exe -latest -property installationVersion) -split '\.')[0..1] -join '.')" >> $env:GITHUB_ENV
> ```
> 
> Results in:
> 
> ```
> VS_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
> MSVC_VERSION: 14.43
> VS_VERSION: 17.13
> ```
> 
> Which is completely different than the `14.29` and `16.11` needed here. That's why I hardcoded this component version number.
