### ISSUE TITLE
pipx home path could cause problems

### ISSUE THREAD

**Issue by dunkmann00** [actions/runner-images#9703]
### Description

Hello, the new version of `pipx` (1.5.0) has updated the default location for `pipx` managed virtual environments. The main reason for doing this was to [avoid issues](https://github.com/pypa/pipx/discussions/1247) on `macOS` and `Windows`.

It seems the custom locations `runner-images` uses for the `macOS arm64` runner and the `windows` runner have spaces in their paths. This results in this message being displayed in the log when using `pipx`:

> Found a space in the home path. We heavily discourage this, due to multiple
    incompatibilities. Please check our docs for more information on this, as
    well as some pointers on how to migrate to a different home path.

It might be worth changing the `PIPX_HOME` directory for these runners.

In case it is useful, [here](https://github.com/pypa/pipx/blob/44023628756588ca74c9a2256037e796cd02613a/src/pipx/paths.py#L12-L26) is the `pipx` code that sets the default locations for the different platforms.

Thanks!

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I saw this on a job I ran on both:
- GitHub Actions macos-14-arm64 20240405.1
- GitHub Actions windows-2022 20240414.1.0

### Is it regression?

No, an update to pipx.

### Expected behavior

No warning when using pipx.

### Actual behavior

The following warning message when running pipx:

> Found a space in the home path. We heavily discourage this, due to multiple
    incompatibilities. Please check our docs for more information on this, as
    well as some pointers on how to migrate to a different home path.

### Repro steps

Use pipx on windows or macos Arm64.

**Comment by MaksimZhukov** [comment]
Hello @dunkmann00!
Thank you for reporting the problem! 
We will investigate it and come back to you as soon as we have any updates

**Comment by dunkmann00** [comment]
I haven't tested this again, but it looks like only the macOS runner has been updated, not Windows?

**Comment by erik-bershel** [comment]
Hey @dunkmann00!
macOS images with those changes released. It was decided not to move `pipx` on WIndows images - there are possible side effects in moving tool from "Program Files". So we prefer to keep it on place while it works fine. Might be reconsidered when negative effect became massive.

**Comment by dunkmann00** [comment]
Okay, thanks for the info!
