### ISSUE TITLE
Use hkps instead of hkp for gpg?

### ISSUE THREAD

**Issue by mhever** [actions/runner-images#9708]
### Description

We're behind corporate firewall. Since https://github.com/actions/runner-images/pull/9677/files build doesn't work, hkp protocol is blocked. Could you switch to hkps? That one is using port 443 and works. I don't see any downside to that change.

images/ubuntu/scripts/build/install-swift.sh

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

HEAD

### Is it regression?

no

### Expected behavior

Build working, but right now hkp port is blocking us.

### Actual behavior

We get timeout on the gpg call.

### Repro steps

Building HEAD for ubuntu 20/22.

**Comment by MaksimZhukov** [comment]
Hello @mhever!
We follow the recommended approach: https://www.swift.org/install/linux/#Installation-via-Tarball 
Please adjust your corporate firewall.

**Comment by bbosveld** [comment]
For compatibility reasons wouldn't it be better to switch to hkp://keyserver.ubuntu.com:80?

**Comment by LokeshNagireddy** [comment]
> Hello @mhever! We follow the recommended approach: https://www.swift.org/install/linux/#Installation-via-Tarball Please adjust your corporate firewall.

Hi @MaksimZhukov , Can you please let me know what kind of adjustments should we do on our firewall?
after the firewall changes, does regular swift installation from runner image work? or do we need to add any additional steps/scripts to our build?

**Comment by nnellanspdl** [comment]
This is being blocked for me as well.  I've resorted to manually changing the `install-swift.sh` to hkps for now.
