### ISSUE TITLE
macOS ARM (macos-14) has rendering issues with lines and texture when using OpenGL

### ISSUE THREAD

**Issue by mwestphal** [actions/runner-images#9712]
### Description

I'm the co-creator of [F3D](https://github.com/f3d-app/f3d), a fast an minimalist cross platform 3D viewer.
We have been supporting macOS ARM using cross-compilation for a while but we recently switched to using macos-14 runner instead.

So far it has been behaving great we do have one issue that seems to be caused by the runner images themselves.

Indeed, we struggle to render certain specific part of our models, it very much looks like a driver bug in the OpenGL stack.
We do not reproduce on any actual macOS ARM, these issues are specific to macos-14 ARM images on github.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240415.6

### Is it regression?

No

### Expected behavior

Correct rendering like this:

![TestDXF](https://github.com/actions/runner-images/assets/3129530/ccb75876-6089-4176-a074-6ac9468e465a)

![TestConfigStemBuild](https://github.com/actions/runner-images/assets/3129530/726a09aa-7994-4709-99ef-918e95d21958)

![TestGridX](https://github.com/actions/runner-images/assets/3129530/89f63fc6-fe16-46b9-a5a0-6e891c79a050)

![TestGridZ](https://github.com/actions/runner-images/assets/3129530/424bb76f-9824-4a8f-8df3-8bf59de5921b)

### Actual behavior

|Test|Result|Diff|
|--|--|--|
|TestConfigStemBuild|![TestConfigStemBuild](https://github.com/f3d-app/f3d/assets/6069752/7c928813-5598-4464-8eec-804630149223)|![TestConfigStemBuild diff](https://github.com/f3d-app/f3d/assets/6069752/28861064-89f5-4148-b28b-d2c27d7b3a6e)|
|TestDXF|![TestDXF](https://github.com/f3d-app/f3d/assets/6069752/229744aa-3322-40ff-bc69-cd124f2aca81)|![TestDXF diff](https://github.com/f3d-app/f3d/assets/6069752/49733d2e-51fe-4968-8b71-9eeeaf47d4d2)|
|TestGridX|![TestGridX](https://github.com/f3d-app/f3d/assets/6069752/d057c664-e866-456b-a276-0927ed012544)|![TestGridX diff](https://github.com/f3d-app/f3d/assets/6069752/1aea42d5-0493-4d6b-8913-15885ce24677)|
|TestGridZ|![TestGridZ](https://github.com/f3d-app/f3d/assets/6069752/1a6e633e-5227-4a6b-b128-cb01e8fcc6d9)|![TestGridZ diff](https://github.com/f3d-app/f3d/assets/6069752/83d29ed0-2a3e-41a3-b600-10fd56312ddd)|

Are you can see, certain lines and texture are incorrectly rendered.

### Repro steps

Create a PR on F3D but in `.github/actions/generic-ci/action.yml:210`, remove the `-E` ctest argument to run all the tests instead of excluding the one that do not render correctly.

**Comment by Alexey-Ayupov** [comment]
Hello @mwestphal, we will take a look what we can do about it.

**Comment by mwestphal** [comment]
Thanks! Please let me know if I can help or test anything on my side.

**Comment by kintel** [comment]
We see a very similar issue with OpenSCAD:

Example of issue:
<img width="1033" alt="Screenshot 2024-04-25 at 19 36 48" src="https://github.com/actions/runner-images/assets/186094/711f0577-2c6d-49a7-98e8-d041181f464a">

**Comment by kintel** [comment]
I ran some tests in an UTM VM with a macOS-14 guest on a macOS-13 host, and I see similar issues, so this might be an upstream OpenGL issue. The GL version is the same as on the GitHub macos-14 runner:
```
OpenGL Version: 2.1 APPLE-21.0.19 (Apple Software Renderer)
```

**Comment by kintel** [comment]
I also managed to reproduce this in an UTM VM with macOS-13.6.6 on a macOS-13 host:
```
OpenGL Version: 2.1 APPLE-20.5.2 (Apple Software Renderer)
```

**Comment by kintel** [comment]
..and finally: Running the Apple Software Renderer directly on a macOS-13 M1 host also fails:
```
OpenGL Version: 2.1 APPLE-20.5.2 (Apple Software Renderer)
```

This last piece of info takes the VM out of the equation.

**Comment by mwestphal** [comment]
> ..and finally: Running the Apple Software Renderer directly on a macOS-13 M1 host also fails:
> 
> ```
> OpenGL Version: 2.1 APPLE-20.5.2 (Apple Software Renderer)
> ```
> 
> This last piece of info takes the VM out of the equation.

So that means this is not fixable because it is a bug in the software rendering stack on macos ?

**Comment by kintel** [comment]
> So that means this is not fixable because it is a bug in the software rendering stack on macos ?
There may still exist workarounds. I haven't experimented with GL context settings to see if the bug only manifests through certain pixel format configurations. I also haven't tried any newer (if they exist) renderers than `21.0.19`.

I can only reproduce this bug in relatively complex scenarios. We have more than 1500 tests, and only 41 of them fail, so there may be some specific GL usage which triggers this issue, and it might be possible to avoid that GL usage by rewriting code (or using slightly different code for testing on macOS).

If you manage to reproduce this with a minimal example, that could be interesting to look into more closely and/or find some paying Apple developer who can engage with Apple on the topic.

**Comment by sureshe456** [comment]
@mwestphal,  We conducted tests in a UTM VM using a macOS-14 guest on a macOS-13 host, and we observed similar issues. please submit the report to Apple.we are closing this issue from our end.Thanks.

**Comment by mwestphal** [comment]
I'm afraid I wont be submitting anything to apple as I would not know where to start nor do I care enough. Thanks for checking as you did though, at least we know where its coming from. Maybe someone will find some kind of work around.

**Comment by kintel** [comment]
I guess we wait until a paying Apple customer is hit by this and can engage with Apple. I had hoped GitHub could do that as this affects a bunch of GitHub customers. Luckily, GitHub Actions still has x86 runners, so it's not yet critical.

Once the x86 runners become decommissioned we'll have to either migrate off GitHub Actions or find another solution. The only workaround I can think about right now is to replace Apple's SW renderer with Mesa, but I haven't looked into what it would take to get that working. I'm afraid it will be pretty messy :(

**Comment by duburcqa** [comment]
Cross-referencing a thread about a similar issue with ‘panda3d’ [here](https://discourse.panda3d.org/t/offscreen-buffer-rendering-issues-on-macos-apple-silicon/30412/14).

**Comment by kintel** [comment]
Update: This issue is still present on macOS 15 (15.1.1 at the time of writing:
```
OpenGL Version: 2.1 APPLE-21.0.27 (Apple Software Renderer)
```

**Comment by mwestphal** [comment]
Detected in VTK gitlab CI too: https://gitlab.kitware.com/vtk/vtk/-/issues/19578

The CI of VTK is running a bare metal macOS arm, so the fact thats its coming from macOS OpenGL stack is fully confirmed.

**Comment by kintel** [comment]
I don't have any hopes that Apple will fix this, but had anyone explored alternatives? Mesa or openglonmetal are both on my list to try. We (OpenSCAD) still run all SW tests on x86, and all ARM tests on real HW, so it's not on fire yet for us, but once GitHub turns off their x86 Mac CI it will get critical..

**Comment by duburcqa** [comment]
Eventually GPU support for nested virtualisation will come before x86 Mac gets dumped, i.e. by providing Apple Silicon M3 runners. If my understanding is correct, fallback to software OpenGL will no longer be necessary, and therefore glitches will disappear by themselves.

**Comment by kintel** [comment]
@duburcqa That would be awesome. Crossing fingers!

**Comment by kintel** [comment]
This issue just became relevant again, since Homebrew dropped support for macOS 13, which is the only OS version still available on x86 runners. Does anyone know the status of running GitHub CI on M3+, or getting a macOS 14 Intel runner set up?

Edit: The new macos-15-intel runner fixes this issue (#13045)

**Comment by erik-bershel** [comment]
Hey @kintel! 👋 

Subscribe there: https://github.com/actions/runner-images/issues/13027

**Comment by mwestphal** [comment]
FYI we fixed this by building OSMesa in our CI instead of using Apple driver.

**Comment by mwestphal** [comment]
> > FYI we fixed this by building OSMesa in our CI instead of using Apple driver.
> 
> The issue was only on `macos-14` ?

we had issues on `macos-14`, `macos-15` and `macos-15-intel`.

**Comment by kintel** [comment]
This issue is becoming more urgent, as Homebrew is deprecating Intel support, and it's already infeasible to install homebrew packages on Intel nodes as it ends up building a large number of packages from source.

My understanding is that GitHub's arm64 runners are still stuck on M1, leaving us with only the broken Apple SW drivers.

**Comment by kintel** [comment]
> FYI we fixed this by building OSMesa in our CI instead of using Apple driver.

When you say "OSMesa" are you actually using the custom offscreen APIs in OSMesa to manage offscreen surfaces in your tests? i.e. as opposed to the OpenGL platform tools (EGL, NSOpenGL, WGL etc.) ?

**Comment by mwestphal** [comment]
> > FYI we fixed this by building OSMesa in our CI instead of using Apple driver.
> 
> When you say "OSMesa" are you actually using the custom offscreen APIs in OSMesa to manage offscreen surfaces in your tests? i.e. as opposed to the OpenGL platform tools (EGL, NSOpenGL, WGL etc.) ?

Yes, correct, we have a custom code to create a OSMesa render window instead of Cocoa or EGL.
