### ISSUE TITLE
Update pip to >=v22.0.3

### ISSUE THREAD

**Issue by Piedone** [actions/runner-images#9731]
### Tool name

pip

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

22.0.3 or greater

### Brief description of tool

Pip, the Python package manager, is installed with v22.0.2 under `ubuntu-latest`. This has [a bug](https://github.com/pypa/pip/issues/10851), fixed in pip v22.0.3 in January 2022, that can cause Read the Docs builds to fail, see [this other issue](https://github.com/readthedocs/readthedocs.org/issues/8864). Updating to v22.0.3 or later fixes this issue.

On `windows-latest` (and also under `macos-latest`), pip is on v24.0, so this is also about bringing Ubuntu in sync with Windows if it can be upgraded to v24. However, v22.0.3 would suffice too for this particular user-case; nevertheless, I recommend updating pip to v24, i.e. latest.

### URL for tool's homepage

https://pip.pypa.io/

### Provide a basic test case to validate the tool's functionality.

```bash
`pip -V` should show "pip 22.0.3".
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, with `python -m pip install pip==22.0.3`.
```

### Tool installation time in runtime

About a second on the 4-core default OSS runners.

### Are you willing to submit a PR?

I wouldn't venture into it; the change itself should be trivial but I'm not sure about the context.

**Comment by Alexey-Ayupov** [comment]
Hello @Piedone. We do not pin the `pip` version (please see installation [script](https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-python.sh)). Once the new version is available in the Ubuntu repository, the new version will be available in our Ubuntu images.

If you have any other questions feel free to reach us.
