### ISSUE TITLE
Cargo lo longer available on macOS-latest

### ISSUE THREAD

**Issue by francisdb** [actions/runner-images#9732]
### Description

Since somewhere the past 4 days rust no longer is available on the `macOS-latest` images. Looks like there was a switch from `macos-12` to `macos-14-arm64`

```
Runner Image
  Image: macos-14-arm64
  Version: 20240422.3
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3
```

![image](https://github.com/actions/runner-images/assets/161305/40c4774a-7590-4672-adda-bb2690501042)

https://github.com/francisdb/vpxtool/actions/runs/8805372288/job/24167793335

Previous build from 4 days ago

```
Runner Image
  Image: macos-12
  Version: 20240412.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20240412.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240412.2
```

https://github.com/francisdb/vpxtool/actions/runs/8753067182/job/24021993766

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [x] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240422.3

https://github.com/francisdb/vpxtool/actions/runs/8805372288/job/24167793335

### Is it regression?

yes

### Expected behavior

`cargo` still works as before

### Actual behavior

`cargo: command not found`

### Repro steps

See linked repo

**Comment by Alexey-Ayupov** [comment]
Hello @francisdb. Indeed we are currently in the process of `macos-14` to `macos-latest` migration, however the cargo should be there. We will check it.

**Comment by Alexey-Ayupov** [comment]
@francisdb, at least the `cargo --version` command works. Could you please specify `macos-14` label and try again? Make sure that image version is `20240422.3`
 
![image](https://github.com/actions/runner-images/assets/116575425/fc490e9a-9e80-4de9-b94a-25c1e00fc008)

**Comment by francisdb** [comment]
I'm getting ` Version: 20240415.6`

https://github.com/francisdb/vpin/actions/runs/8813246540/job/24190584925?pr=67

**Comment by Alexey-Ayupov** [comment]
Yes, that's  expected. We are in the middle of the updating images to the new version.

**Comment by francisdb** [comment]
According to https://github.com/actions/runner-images/discussions/3464 I can't pin a version so I can't try macos-14?

**Comment by Alexey-Ayupov** [comment]
I have forked your repository and run your workflow with `macOS-14` label. And it works - https://github.com/Alexey-Ayupov/vpin/actions/runs/8815461877/job/24197473679.

Could you please clean your cash and try again today evening or tomorrow? 

Planned end of the image version updating is today evening, so tomorrow all macOS 14 arm64 images should have version `20240422.3`

**Comment by francisdb** [comment]
Looks like this is fixed now, maybe related to the cache clear

**Comment by str4d** [comment]
I encountered the same issue. The cause is that `macos-latest` used to point to `macos-12` which is x86_64, but now points to `macos-14` which is ARM64. This breaks the Cargo cache because the platform arch is unexpectedly different.

I don't know what guarantees GitHub makes about the `*-latest` runner labels, but given that until now every `*-latest` runner was x86_64, this seems like a rather frustrating change for the ecosystem (though necessary).

**Comment by Fernthedev** [comment]
> I don't know what guarantees GitHub makes about the `*-latest` runner labels, but given that until now every `*-latest` runner was x86_64, this seems like a rather frustrating change for the ecosystem (though necessary).

I wholeheartedly agree with this. I suffered from this issue today and was frustrated to find my CI action failing without any notice or ideas as to why. I'd appreciate if there could be some warning during the migration period notifying users that their cache is currently broken and/or a fix for the cache issue.

Glad to see the issue has a fix though, thanks!
