### ISSUE TITLE
Build of Ubuntu 22.04 fails with latest packer version

### ISSUE THREAD

**Issue by matthiasbrix** [actions/runner-images#9742]
### Description

Hi,

The installer script for packer fetches the latest version of packer (1.10.3) which has recently introduced the file `LICENSE.txt` in the downloaded archive file. This is now causing the build of the ubuntu 22 image (20240422) to fail as the `unzip` operation in the script `install-packer.sh` is being prompted with whether replacing the file `LICENSE.txt` is desired. I suggest adding perhaps an overwrite flag to the `unzip` operation

```
==> azure-arm.build_image: Provisioning with shell script: runner-images-ubuntu22-20240422.1/images/ubuntu/templates/../scripts/build/install-packer.sh
==> azure-arm.build_image: Downloading package from https://releases.hashicorp.com/packer/1.10.3/packer_1.10.3_linux_amd64.zip to /tmp/packer_1.10.3_linux_amd64.zip...
==> azure-arm.build_image: Package downloaded in 0 seconds
==> azure-arm.build_image: replace /usr/local/bin/LICENSE.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
==> azure-arm.build_image: (EOF or read error, treating as "[N]one" ...)
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_image: 
==> azure-arm.build_image: Deleting Virtual Machine deployment and its attatched resources...
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu/22-20240422
No public available.

### Is it regression?

Yes

### Expected behavior

No prompt but a successful unzip.

### Actual behavior

Build fails

### Repro steps

Just try to build ubuntu 22 image (20240422)

**Comment by SebastianClaesson** [comment]
This also affects Ubuntu 20.04 build as both installs Packer.
Seems the Unzip command requires either (-o) over-write or refresh (-f) to overwrite the existing license file under /usr/local/bin/LICENSE.txt

**Comment by Alexey-Ayupov** [comment]
Hello @matthiasbrix. We aware of the problem and are working on it.

**Comment by mikhailkoliada** [comment]
Fixed, please sync your main!

**Comment by matthiasbrix** [comment]
@mikhailkoliada  - just need a new release with the fix :). Thanks.

**Comment by mikhailkoliada** [comment]
@matthiasbrix we do not [support](https://github.com/actions/runner-images?tab=readme-ov-file#faqs) building from releases, so if it fails no fixes will be provided, the one should always use main to build their own images.
