### ISSUE TITLE
Subversion is missing from recent macOS versions

### ISSUE THREAD

**Issue by sebbASF** [actions/runner-images#9746]
### Description

Subversion used to be provided in macOS versions up to 12, and is still provided for Windows and Ubuntu

AFAICT there has been no announcement of the omission

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3

### Is it regression?

Did not occur with macOS-12

### Expected behavior

Subversion should be provided with all macOS versions

### Actual behavior

Subversion is not present

### Repro steps

Subversion is not mentioned in the README files for macOS-13 and later

**Comment by Alexey-Ayupov** [comment]
Hello @sebbASF. It was not a bug, we just did not install `subversion` to the new macOS images due to maintenance concerns and relatively short installation time.
You can always install it in runtime using `brew install subversion` command. 

If you have any other questions feel free to reach us.
