### ISSUE TITLE
Add libtool on macos-14

### ISSUE THREAD

**Issue by hummeltech** [actions/runner-images#9753]
### Tool name

libtool

### Tool license

GNU General Public License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

GNU Libtool is a generic library support script that hides the complexity of using shared libraries behind a consistent, portable interface. 

### URL for tool's homepage

https://www.gnu.org/software/libtool/

### Provide a basic test case to validate the tool's functionality.

```bash
This seems to have been included in `macos-13`, but not in `macos-14`.
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
brew install libtool
```

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
Hey! We would not like pre installing lib tool due to its short installation time in runtime.

**Comment by hummeltech** [comment]
Hello, yes I indeed understand that, however the problem isn't really that it's not installed or cannot be installed at runtime. The problem is that all other `macos` images have it pre-installed, so there is going to be confusion when a user expects a tool to be installed when adding `macos-14` jobs to an existing workflow already using `macos-13` or `macos-12`. This is especially important as `macos-latest` has very recently stopped pointing to `macos-12` and now points to `macos-14`.

Here is a very basic workflow demonstrating this:
https://github.com/hummeltech/TempPackages/actions/runs/8883237239
