### ISSUE TITLE
brew openssl install on macOS 14 Arm64 is borked

### ISSUE THREAD

**Issue by benoit-pierre** [actions/runner-images#9755]
### Description

The pkg-config entry libraries search path is invalid:
```bash
# the include directory is correct:
▸ pkg-config --cflags libcrypto
-I/opt/homebrew/Cellar/openssl@3/3.3.0/include
# but the libraries search path is not:
▸ pkg-config --libs libcrypto
-L/opt/homebrew/Cellar/openssl@3/3.3.0 -lcrypto
#
▸ ls -l /opt/homebrew/Cellar/openssl@3/3.3.0
total 1752
-rw-r--r--   1 runner  admin     990 Apr  9 12:12 AUTHORS.md
-rw-r--r--   1 runner  admin  782003 Apr  9 12:12 CHANGES.md
-rw-r--r--   1 runner  admin    1256 Apr 22 18:13 INSTALL_RECEIPT.json
-rw-r--r--   1 runner  admin   10175 Apr  9 12:12 LICENSE.txt
-rw-r--r--   1 runner  admin   84478 Apr  9 12:12 NEWS.md
-rw-r--r--   1 runner  admin    8182 Apr  9 12:12 README.md
drwxr-xr-x   4 runner  admin     128 Apr 22 18:13 bin
drwxr-xr-x   3 runner  admin      96 Apr  9 12:12 include
drwxr-xr-x  12 runner  admin     384 Apr 22 18:13 lib
drwxr-xr-x   4 runner  admin     128 Apr  9 12:12 share
```

Reinstalling with `brew reinstall openssl@3` fix it.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.316.0'

### Is it regression?

No idea.

### Expected behavior

`pkg-config --libs openssl` return the correct flags.

### Actual behavior

`pkg-config --libs openssl` return an invalid libraries search path.

### Repro steps

Check the output for `pkg-config --libs openssl` (or `libcrypto`/`libssl`): `-L/opt/homebrew/Cellar/openssl@3/3.3.0` is returned instead of `-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib`.

**Comment by Chocobo1** [comment]
>Reinstalling with brew reinstall openssl@3 fix it.

Linking to upstream issue: https://github.com/Homebrew/homebrew-core/issues/169728
and upstream PR: https://github.com/Homebrew/homebrew-core/pull/169721

I suppose the macOS image just need to bundle the new openssl bottle/package.

**Comment by benoit-pierre** [comment]
Thank!

How come a `brew update` does not also fix the problem? They did not bump the formula?

**Comment by ReenigneArcher** [comment]
I believe I'm facing this as well.

Something interesting that I discovered is that even though the image is supposed to be arm64... `uname -m` returns `x86_64`

**Comment by mikhailkoliada** [comment]
Hey! Unfortunately we can not help fixing this issue, we do not manage `.pc` files shipped with openssl, it should be reported to Hebrew and the fix shipped there (well, it was, so I hope it is soon to be fixed)

**Comment by benoit-pierre** [comment]
I know you don't manage the pc files yourselves, but you do provide an image with a number of homebrew packages pre-installed. So are you going update the image with the fixed version?

**Comment by mikhailkoliada** [comment]
the rollout gonna happen after may 7th I believe, in the meantime `brew upgrade` should do the trick in runtime

**Comment by benoit-pierre** [comment]
OK, thanks.
