### ISSUE TITLE
Cannot set xcode as part of setup 

### ISSUE THREAD

**Issue by kj-brown** [actions/runner-images#9767]
### Description

Sorry if this is the wrong place, but discussion looks a little quiet..

I'm trying to set the xcode version to 15.3 using the `macos-14` image, but when I start fastlane I unfortunatelt am told I have Xcode 15.0.1:

```
[12:57:31]: Selected Xcode version doesn't match your requirement.
Expected: Xcode 15.3
Actual: Xcode 15.0.1
```

I've looked at https://github.com/maxim-lobanov/setup-xcode but our org doesn't support 3rd party actions. Is there a supported way to set this outside of downloading and installing xcodes?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

Able to set xcode version as part of runner

### Actual behavior

Stuck with lowest version xcode

### Repro steps

N/A

**Comment by maxim-lobanov** [comment]
You can use the following command to switch Xcode:
`sudo xcode-select -s /Applications/Xcode_15.3.app`
(Xcode paths are listed in https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode)

It is exactly what https://github.com/maxim-lobanov/setup-xcode does under hood. But action provides more convenient way to do it and avoid hardcoding path.

**Comment by kj-brown** [comment]
Thanks! Perfect :)
