### ISSUE TITLE
apt upstream broken in ubuntu-latest (22.04.4 version 20240422.1.0)

### ISSUE THREAD

**Issue by driesvints** [actions/runner-images#9768]
### Description

Basically exactly the same as https://github.com/actions/runner-images/issues/7210 which is happening for us on our private repo. Running `sudo apt-get update` will trigger it. I tried adding `sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list` to prevent it but it didn't help unfortunately.

```
      - name: Install ghostscript
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt install ghostscript
```

<img width="1383" alt="Screenshot 2024-04-30 at 15 55 10" src="https://github.com/actions/runner-images/assets/594614/97a48479-89f9-45fe-84f4-32c3eeb906e8">

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I don't understand where to find this sorry. Where can I find "Set up job"?

### Is it regression?

Yes, see link above to old closed issue

### Expected behavior

I'd expect to be able to run an `apt-get update` on GitHub Actions.

### Actual behavior

It's failing and giving an invalid signature error.

### Repro steps

Run `sudo apt-get update` in GitHub Actions on `ubuntu-latest`.

**Comment by mikhailkoliada** [comment]
Hey! your workflow indicates problems with the ondrej/php repo which is not a part of the ubuntu-latest runner, please report the problem to the repository owner

**Comment by driesvints** [comment]
Thanks @mikhailkoliada. Eventually we managed to solve this one by placing the apt-get update before the setup-php action. I have no idea why that solved things but glad it did.
