### ISSUE TITLE
Azure CLI installer certificate thumbprint is outdated due to new release

### ISSUE THREAD

**Issue by Ami-007** [actions/runner-images#9771]
### Description

Attempted to build a Windows 2019 image based on the current repo, but it failed with the error below.

==> azure-arm: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/scripts/build/Install-AzureCli.ps1
    azure-arm: Install the latest Azure CLI release
    azure-arm: Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\kbhjzvvz.msi...
    azure-arm: Package downloaded in 2.84 seconds
==> azure-arm: Signature thumbprint do not match expected.
==> azure-arm: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm: +         throw "Signature thumbprint do not match expected."
==> azure-arm: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Private build of Azure DevOps agent based on Windows Server 2019 from this repo

### Is it regression?

Yes

### Expected behavior

Thumbprint should match and build of new Windows 2019 runner image built successfully

### Actual behavior

Building the image fails due to:
==> azure-arm: Signature thumbprint do not match expected.
==> azure-arm: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm: +         throw "Signature thumbprint do not match expected."
==> azure-arm: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

### Repro steps

Build the Windows Server 2019 image using the code in runner images

**Comment by sergei-pyshnoi** [comment]
Hello @Ami-007 . Thanks for your report, we are working on it.

**Comment by mikhailkoliada** [comment]
should be fixed now in main!
