### ISSUE TITLE
MacOS 14 Runner Cant Resolve keyserver.ubuntu.com

### ISSUE THREAD

**Issue by steelhead31** [actions/runner-images#9777]
### Description

The MACOS 14 github action runner is unable to resolve keyserver.ubuntu.com for retrieving GPG keys.

Currently using this workaround to replace the keyserver name with its IP address which works

`sed -i '' 's/keyserver\.ubuntu\.com/185.125.188.27/g' `

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Link : https://github.com/adoptium/infrastructure/actions/runs/8922598468/job/24505071773

Current runner version: '2.316.0'
Operating System
  macOS
  14.4.1
  [2](https://github.com/adoptium/infrastructure/actions/runs/8922598468/job/24505071773#step:1:2)3E224
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@9bb56186c[3](https://github.com/adoptium/infrastructure/actions/runs/8922598468/job/24505071773#step:1:3)b09b4f86b1c65136769dd318[4](https://github.com/adoptium/infrastructure/actions/runs/8922598468/job/24505071773#step:1:4)69633' (SHA:9bb[5](https://github.com/adoptium/infrastructure/actions/runs/8922598468/job/24505071773#step:1:5)6186c3b09b4f8[6](https://github.com/adoptium/infrastructure/actions/runs/8922598468/job/24505071773#step:1:7)b1c65136769dd318469633)
Complete job name: macOS (macos-14)

### Is it regression?

No

### Expected behavior

The machine should be able to resolve the DNS name to its IP address

### Actual behavior

```
TASK [ant : GPG Signature verification] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 2, "stderr": "gpg: directory '/Users/runner/.gnupg' created\ngpg: keyserver receive failed: No route to host\n", "stderr_lines": ["gpg: directory '/Users/runner/.gnupg' created", "gpg: keyserver receive failed: No route to host"], "stdout": "", "stdout_lines": []}
```

### Repro steps

Import a gpg key from keyserver.ubuntu.com on a macos14 runner.

**Comment by shamil-mubarakshin** [comment]
Hey @steelhead31. System itself is resolving `keyserver.ubuntu.com` [correctly](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/8982461301/job/24670118651). There might be some name resolution issue when using gpg which I will check and get back

**Comment by steelhead31** [comment]
@shamil-mubarakshin  Thanks!

**Comment by steelhead31** [comment]
Thanks for the response, I'll check with some of our Mac developers, see if anyone else has seen this behaviour outside of the runner. The workaround works for now.

**Comment by steelhead31** [comment]
Ok, since it looks intermittent, I'll assume its server side @ Ubuntu, will keep an eye on this.
