### ISSUE TITLE
Update GitHub CLI to 2.49.0 in Ubuntu 22.04 (current ubuntu-latest)

### ISSUE THREAD

**Issue by matthewfeickert** [actions/runner-images#9784]
### Tool name

GitHub CLI

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

2.49.0

### URL for tool's homepage

https://github.com/cli/cli

### Provide a basic test case to validate the tool's functionality.

```bash
gh attestation verify --help
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
I think so, but this wouldn't be the recommended approach.
```

### Are you willing to submit a PR?

Yes, though it unclear from PRs like PR https://github.com/actions/runner-images/pull/9730 how to actually do this for the GitHub CLI.

**Comment by matthewfeickert** [comment]
In PR https://github.com/actions/runner-images/pull/9776, the `ubuntu-24.04` runner environment description was added, which includes

https://github.com/actions/runner-images/blob/7bb1d84f7071bfa9c350d7552d9631d9a69bfdb0/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L95

This is great, but for using `gh attestation verify` to validate a GitHub artifact attestation before publishing to an index or repository in a GitHub Actions workflow

```yaml
    - name: Verify wheel artifact attestation
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh attestation verify dist/package-*.whl --repo ${{ github.repository }}
```

this now requires users to switch to `ubuntu-24.04`. As `ubuntu-22.04` is the current `ubuntu-latest` runner, it would be useful to update

https://github.com/actions/runner-images/blob/7bb1d84f7071bfa9c350d7552d9631d9a69bfdb0/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L118

to `2.49.0` there as well.

**Comment by sssharif** [comment]
thank you for your request. GitHub CLI will be updated in next image deployment. We expect next image deployment will be on tuesday or wednesday next week.

**Comment by cclauss** [comment]
https://github.com/actions/runner-images/releases

**Comment by matthewfeickert** [comment]
> We expect next image deployment will be on tuesday or wednesday next week.

@sssharif Do you have an updated estimate on this?

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by matthewfeickert** [comment]
Thank you @mikhailkoliada!

For others, c.f. https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240514.2 for the full deployment notes.
