### ISSUE TITLE
macOS output of $(pkg-config --libs openssl ) incorrect

### ISSUE THREAD

**Issue by slewsys** [actions/runner-images#9789]
### Description

On GitHub runner for macos-latest, with openssl installed via brew (workflow here: [ed.yml](https://github.com/slewsys/ed/blob/main/.github/workflows/ed.yml)), `pkg-config` produces an incorrect library path for linking libssl.  Instead of:

```
-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib -lssl -clrypto
```

it produces:

```
-L/opt/homebrew/Cellar/openssl@3/3.3.0 -lssl -lcrypto
```

as seen here [link step](https://github.com/slewsys/ed/actions/runs/8952033136/job/24588993751#step:7:888).

The issue is not repeatable locally on M1/macOS 14.4.1 Homebrew 4.2.20-104-gdfbf269. 
In this particular case, explicitly setting LDFLAGS during configure is a workaround as seen here: [configure step](https://github.com/slewsys/ed/actions/runs/8952033136/job/24588993751#step:6:3).

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240422.3
[Build link](https://github.com/slewsys/ed/actions/runs/8952033136/job/24588993751)

### Is it regression?

Maybe? Was openssl recently removed from macOS runners?

### Expected behavior

After installing **openssl**:

```
brew install m4 autoconf automake libtool gettext openssl texinfo
brew unlink openssl@1.1 &&  brew link --force --overwrite openssl@3
```

then

```
pkg-config --libs openssl
```

should report:

> -L/opt/homebrew/Cellar/openssl@3/3.3.0/lib -lssl -lcrypto

### Actual behavior

> -L/opt/homebrew/Cellar/openssl@3/3.3.0 -lssl -lcrypto

i.e., the _lib_ subdirectory is missing.

### Repro steps

Run an action on macos-latest that installs openssl and attempts to link against the installed -lssl.

**Comment by erik-bershel** [comment]
Heads up!

It's a clone of the existing issue: https://github.com/actions/runner-images/issues/9759
You may use `brew upgrade` as a workaround. Will be fixed with the next image rollout.
