### ISSUE TITLE
macos-14 image changes version from `2.314.1` to `2.316.0` breaks the iOS simulator to use HEIF/HEVC codec encoder

### ISSUE THREAD

**Issue by dreampiggy** [actions/runner-images#9791]
### Description

We're testing the macOS System framework HEIF/HEVC encoder API

However, we found that the runner image version bump(not controlled by me) from `2.314.1` to `2.316.0` breaks the Apple System framework HEIF/HEVC encoder API's behavior.

+ 2.314.1: https://github.com/SDWebImage/SDWebImage/actions/runs/8433619909/job/23095041515
+ 2.316.0: https://github.com/SDWebImage/SDWebImage/actions/runs/8845702946/job/24290135387

The error log shows (from macOS system framework):

```
2024-04-26 08:59:58.966569+0000 xctest[6991:32863] [xctest] writeImageAtIndex:962: *** CMPhotoCompressionSessionAddImage: err = kCMPhotoError_UnsupportedOperation [-16994]    (codec: 'hvc1')
```

(note: The only changes in the git repo between these 2 action run is only comments, should not effect the result: https://github.com/SDWebImage/SDWebImage/commit/ea2e3d5debbe19f5f59284cf2c605c67dac3cdbd)

And, I can ensure that when running on physical MacBook Pro 15 M1 Pro, the API returns correctly (which may use the Apple M1 chip's media codec for HEVC decoding).

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Works: 2.314.1
Broken: 2.316.0

### Is it regression?

yes

### Expected behavior

The Apple's ImageIO API for HEIF/HEVC encoder should work as expected.

### Actual behavior

The Apple's ImageIO API for HEIF/HEVC encoder just report error

### Repro steps

1. Use Apple's System HEIF/HEVC encoder API to decode any HEIF image, like my demo:  https://github.com/SDWebImage/SDWebImage/blob/master/Tests/Tests/Images/TestImage.heic
2. Run on macos-14 runner in version `2.316.0`, see failure
3. Run on macos-14 runner in version `2.314.1`, see success

**Comment by dreampiggy** [comment]
Sorry for the misunderstanding. The broken is `HEVC encoding`, not `HEVC decoding`

**Comment by dreampiggy** [comment]
Similar: https://github.com/rlxone/Equinox/issues/66

Is the macos system bug ? What's the actual macOS version number between runner `2.314.1` and `2.316.0` ?

**Comment by dreampiggy** [comment]
I guess this maybe a macOS system bug which introduced during minor version bump (14.2.1 -> 14.4.1)

How can I use github action yaml to declare the exact macOS version I want to use ?😼

**Comment by dreampiggy** [comment]
For now, since I use GitHub action as free service. I quickly ignore HEIF encoding in the unit test :(

https://github.com/SDWebImage/SDWebImage/pull/3710

**Comment by erik-bershel** [comment]
Hey @dreampiggy!
Thank you for bringing it into our attention. We'll take a closer look. I may say that it seems as a macOS degradation itself, but should be checked for sure.

**Comment by prasanjitsahoo** [comment]
HI @dreampiggy, I tried reproducing the issue on macOS 14 in current runner version is '2.317.0' and CI pipeline got succeeded now. Please let us know if we are good to close this issue. 
<img width="1509" alt="Screenshot 2024-07-16 at 6 05 08 PM" src="https://github.com/user-attachments/assets/7f6f3222-7d86-4cbf-92d1-4651b9a14650">

**Comment by dreampiggy** [comment]
Sorry for the delay. I'll update the envionment and trigger a github action pipeline to check again now.

**Comment by dreampiggy** [comment]
Using `Xcode_15.4.app` and re-run:

Seems works on iPhone simulator now. (But brokwn on macOS HEVC encoding...I'm investigating)

**Comment by prasanjitsahoo** [comment]
Thank you for the update.
