### ISSUE TITLE
PHP issue on Ubuntu 22.04 packer build

### ISSUE THREAD

**Issue by LokeshNagireddy** [actions/runner-images#9795]
### Description

Hi Team,
We are getting below error in the latest build image 9e048184f96ae40344bbb302949ca0c725238ec5

2024-05-06T13:14:00.6749478Z ==> azure-arm.image: Provisioning with Powershell...
2024-05-06T13:14:00.6754945Z ==> azure-arm.image: Provisioning with powershell script: /tmp/powershell-provisioner4195621839
2024-05-06T13:14:35.2311924Z ==> azure-arm.image: **PHP version 8.3.6 (c:\tools\php\php.exe)**
2024-05-06T13:14:35.2316533Z ==> azure-arm.image: **Run the "diagnose" command to get more detailed diagnostics output.**
2024-05-06T13:14:42.9660744Z ==> azure-arm.image: **Found a space in the home path. We heavily discourage this, due to multiple**
incompatibilities. Please check our docs for more information on this, as
well as some pointers on how to migrate to a different home path.
 [31;1mbindgen : [31;1mThe term 'bindgen' is not recognized as a name of a cmdlet, function, script file, or executable program.[0m
 [31;1m[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.[0m
 [31;1m[31;1mAt C:\image\SoftwareReport\SoftwareReport.Common.psm1:53 char:5[0m
 [31;1m[31;1m+     bindgen --version | Get-StringPart -Part 1[0m
 [31;1m[31;1m+     ~~~~~~~[0m
 [31;1m[31;1m+ CategoryInfo          : ObjectNotFound: (bindgen:String) [], ParentContainsErrorRecordException[0m
 [31;1m[31;1m+ FullyQualifiedErrorId : CommandNotFoundException[0m

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240422.1.0

### Is it regression?

Yes

### Expected behavior

Clean execution of PHP

### Actual behavior

PHP version 8.3.6 (c:\tools\php\php.exe)
Found a space in the home path. We heavily discourage this, due to multiple
    incompatibilities. Please check our docs for more information on this, as
    well as some pointers on how to migrate to a different home path.
[31;1mbindgen : [31;1mThe term 'bindgen' is not recognized as a name of a cmdlet, function, script file, or executable program.[0m
[31;1m[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.[0m
[31;1m[31;1mAt C:\image\SoftwareReport\SoftwareReport.Common.psm1:53 char:5[0m
[31;1m[31;1m+     bindgen --version | Get-StringPart -Part 1[0m
[31;1m[31;1m+     ~~~~~~~[0m
[31;1m[31;1m+ CategoryInfo          : ObjectNotFound: (bindgen:String) [], ParentContainsErrorRecordException[0m
[31;1m[31;1m+ FullyQualifiedErrorId : CommandNotFoundException[0m

### Repro steps

Just run the image deployment: image reference from May 2nd commit.

**Comment by vidyasagarnimmagaddi** [comment]
hi ,we  will be performing the required task

**Comment by erik-bershel** [comment]
Hey @LokeshNagireddy!
It's not a PHP issue at all. According to the logs provided the issue itself related to the `bindgen`. It seems missed in your build. Please use `main` branch to build images.

**Comment by LokeshNagireddy** [comment]
im using main branch only.. Can you please reverify the below screen shot.

![image](https://github.com/actions/runner-images/assets/113025693/4ed85b80-7273-4fe4-b1d6-975744508bbc)

please let me know if i miss something
