### ISSUE TITLE
macos-latest image using an antique version of makefile

### ISSUE THREAD

**Issue by kdschlosser** [actions/runner-images#9797]
### Description

```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Darwin Mac-1715067091984.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:50 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_VMAPPLE arm64
```

### Is it regression?

??

### Expected behavior

to have an up to date version of makefile installed not one that was made for an operating system in 2012 and was written in 2006. 

### Actual behavior

getting strange behavior when running make

### Repro steps

create a a workflow using the macos-latest image and make a job that runs `make --version` and you will see that it's a really old version that has been included in the image.

**Comment by erik-bershel** [comment]
Hey @kdschlosser!

It is a default `make` which is a part of Xcode installation. You can update it via runtime using `brew` for example if you need newer version. Since different projects require different version of `make` we are not going to control its version manually.
