### ISSUE TITLE
Runner macos-14 lacks vcpkg command

### ISSUE THREAD

**Issue by JonatanAntoni** [actions/runner-images#9809]
### Description

The command `vcpkg` is not available on MacOS 14 runners while it is available by default for all other versions of MacOS, and for Windows, and Linux.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/ARM-software/cmsis-actions/actions/runs/8999157484/job/24720758818

### Is it regression?

https://github.com/ARM-software/cmsis-actions/actions/runs/8986533074

### Expected behavior

For Windows, Linux, and Mac (up to 13) runners there is a default vcpkg installation shipped in the images. The MacOS 14 image seems not to have it.

### Actual behavior

All default images are expected to have a similar toolset installed by default.

### Repro steps

Run `vcpkg` command on different versions of MacOS images.
See https://github.com/ARM-software/cmsis-actions/actions/runs/8986533074 vs https://github.com/ARM-software/cmsis-actions/actions/runs/8999157484/job/24720758818

**Comment by shamil-mubarakshin** [comment]
Hey @JonatanAntoni, we will consider adding the tool

**Comment by mikhailkoliada** [comment]
We would not like to pre-install vcpkg here due to low demand and maintenance concerns. Please install in runtime as it is easy to do.

**Comment by JonatanAntoni** [comment]
@mikhailkoliada, thanks for the reply. The "problem" here is the inconsistency across different versions and variants of runner images. In most of the OSes and versions its already installed but only in Mac 13 it is not.

**Comment by a4z** [comment]
low demand is not true, I was also looking for it

but most people will not tell you if they have to work around 
and the argument of inconsistency is very value, so please, @mikhailkoliada , reconsider your decision and re-open this feature

**Comment by theAeon** [comment]
Throwing another voice on the pile here-it also doesn't make sense to have it on the macOS intel runners but not the arm ones.

**Comment by petersteneteg** [comment]
@mikhailkoliada Run into this when updating the macOS image. Very annoying. Now I need to handle macOS-14 differently. Are you planning to remove it from the other images too? Should I just clone it my self everywhere? The list of software included should state that the omission is intentional, since it is installed on all the other ones.
