### ISSUE TITLE
xcrun error in MacOS14

### ISSUE THREAD

**Issue by hovancik** [actions/runner-images#9811]
### Description

Hi, I am not able to run `xcrun --show-sdk-version` with macOS 14. I've created simple repro here: https://github.com/hovancik/xcrun-issue-repo

```
Run xcrun --show-sdk-version
2024-05-08 12:07:16.873 xcodebuild[3969:24327] Writing error result bundle to /var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/ResultBundle_2024-08-05_12-07-0016.xcresult
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240422.3

https://github.com/hovancik/xcrun-issue-repo/actions/runs/9001515302/job/24727916139

### Is it regression?

Works on macOS13 https://github.com/hovancik/xcrun-issue-repo/actions/runs/9001515302/job/24727915857

### Expected behavior

`xcrun --show-sdk-version` works

### Actual behavior

`xcrun --show-sdk-version` errors

### Repro steps

try running `xcrun --show-sdk-version`

**Comment by shamil-mubarakshin** [comment]
Hey @hovancik, thanks for reporting, we will take a look

**Comment by Alexey-Ayupov** [comment]
Hello @hovancik, during the investigation we have found if change the xcode command line tools path to the default one we can retrieve the SDK version.
Could you please try the `sudo xcode-select -s /Library/Developer/CommandLineTools` before executing `xcrun` command?

**Comment by hovancik** [comment]
@Alexey-Ayupov that seems to work fine, and also seems to fix my real-world application where `xcrun` gets called in some package that I use: https://github.com/hovancik/stretchly/actions/runs/9019543005/job/24782648534?pr=1450
