### ISSUE TITLE
Receive error                                                                        Error booting VM: VmBoot(DeviceManager(VfioDmaMap(IommuDmaMap(Error(14)))))

### ISSUE THREAD

**Issue by sdake** [actions/runner-images#9821]
### Description

Starting a VM with 1 or 2 vfio devices results in the error `                                                                       Error booting VM: VmBoot(DeviceManager(VfioDmaMap(IommuDmaMap(Error(14)))))`. I have done some basic debug and not found the root cause. I reinstalled debian 12.5 while keeping all binaries the same, and this error occurs. I am not sure how to further debug the problem. Any insight would be valued.

```
./chdebug \
	--kernel "${kernel_img}" \
        --disk path="${disk_img}" \
        path="${config_img}" \
	--cpus boot=4 \
        --memory "size=256G,hugepages=on,hugepage_size=2M" \
	--api-socket "${api_sock}" \
	--serial tty \
	--console pty \
        --net fd=3,mac=${mac} 3<>$"${tapdevice}" \
	-v \
	--vsock cid=3,socket="${vsock}" \
	--log-file "${log}" \
        --cmdline "rd.module_blacklist=nouveau,nvidiafb console=tty0 root=/dev/vda1 rw" \
       --device path="/sys/bus/pci/devices/0000:61:00.0"
```

```
sdake@beast-06:/usr/local/bin$ sudo driverctl list-overrides
[sudo] password for sdake:
0000:01:00.0 vfio-pci
0000:24:00.0 vfio-pci
0000:41:00.0 vfio-pci
0000:61:00.0 vfio-pci
0000:a1:00.0 vfio-pci
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I built my own image using packer: https://github.com/artificialwisdomai/origin/blob/main/platform/golden/run-bookworm.sh

### Is it regression?

not sure

### Expected behavior

boot into VM.

### Actual behavior

VM fails to boot and reports an error.

I added some debug:
```
sdake@beast-06:/usr/local/bin$ bash wise-a40x2.sh
11: macvtap61@ens8f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether c2:67:4f:53:29:61 brd ff:ff:ff:ff:ff:ff
[2024-05-09T20:28:51Z ERROR virtiofsd] Error creating pid file '/var/run/artificial_wisdom/61/virtiofs.sock.pid': Resource temporarily unavailable (os error 11)
Region Start Address: 0x0                         
Region Length: 3221225472                                                 
Region Pointer Address: 0x7f58a8000000
Region Start Address: 0x100000000
Region Length: 271656681472
Region Pointer Address: 0x7f1968000000
Error booting VM: VmBoot(DeviceManager(VfioDmaMap(IommuDmaMap(Error(14)))))
```

### Repro steps

Run command in this log. If anyone has insight into further debug steps or a workaround, would appreciate it.

**Comment by sdake** [comment]
Turning off 2MB pages seems to rectify the problem, although after setting 2MB pages, page size is 4096kb. Any insights?

**Comment by sdake** [comment]
To recap, I had 2MB page count of 96000. I allocated a VM of 256GB with 2MB shared. The VM does not have enough 2MB pages to start properly, and prints the difficult to diagnose error.

**Comment by shamil-mubarakshin** [comment]
Hey @sdake, this repository contains code for windows/ubuntu/macos packer builds for Azure/VMware/Anka. Unfortunately, we will not be of much help in your case. 
I saw you are using [virtualbox-iso](https://developer.hashicorp.com/packer/integrations/hashicorp/virtualbox/latest/components/builder/iso) builder. https://github.com/hashicorp/packer-plugin-virtualbox might be a better place for such issues
