### ISSUE TITLE
GitHub Actions lost communication with the server

### ISSUE THREAD

**Issue by ramkia613** [actions/runner-images#9823]
### Description

Hi

The GitHub actions jobs on my pipeline have been failing recently. In the past, it worked, but now it always fails.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Two different workflows.
- https://github.com/dee-money/passenger-android/actions/runs/9027931195
- https://github.com/dee-money/passenger-android/actions/runs/9027598102

### Is it regression?

no

### Expected behavior

Job should pass

### Actual behavior

Job failed with below error

The hosted runner: GitHub Actions 8 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

### Repro steps

private repo

**Comment by erik-bershel** [comment]
Hey @ramkia613!
You exhausted runner resources in both cases. Please optimise your run configuration in order to save some CPU and RAM for the runner itself to continue work. We do not investigate resources related issues. For the troubleshooting I may say that your run hit CPU, RAM, and IOPS the same time so it's hard to say what exactly resulted in failure.

**Comment by signor-mike** [comment]
I downgraded Ubuntu from 22.04 LTS to 20.04 LTS and the workflow is no longer exhausting anything.

**Comment by BenSandeen314** [comment]
@erik-bershel But is there a way to view logs or anything, or do you just have to do a painful guess-and-check process to fix this?
