### ISSUE TITLE
macos-latest-large job fails with "spending limit needs to be increased" on free tier

### ISSUE THREAD

**Issue by stefantalpalaru** [actions/runner-images#9826]
### Description

When using the "macos-latest-large" runner image (but not with the "macos-latest" one) I get this error:

`The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.`

I am on a free tier and I already switched to yearly billing, in case monthly billing is buggy. No change.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/stefantalpalaru/transmission-og/actions/runs/9030763192?pr=25

### Is it regression?

Yes. Last successful build was more than a year ago: https://github.com/stefantalpalaru/transmission-og/actions/runs/5894799112

### Expected behavior

The AMD64 macOS job should run.

### Actual behavior

The AMD64 macOS job does not run.

### Repro steps

Try to use the "macos-latest-large" builder image on a free tier. See it fail to start.

**Comment by erik-bershel** [comment]
Hey @stefantalpalaru!

Unfortunately we cannot help you with this problem. Please contact Github support: https://support.github.com/contact/account
