### ISSUE TITLE
Failures related to macos-14 migration

### ISSUE THREAD

**Issue by cpackham** [actions/runner-images#9832]
### Description

Hello from crosstool-ng,

The switch of macos-latest from macos-12 to macos-14 triggered for us recently.

Problems so far
* missing makeinfo and libtool (we can fix the action to explicitly install these from brew).
* Odd compilation failures, I'm not sure about this one. Given that we're compiling a cross gcc with the system compiler (clang) there seems to be some issues with this possibly due to C++ changes
```
[ALL  ]    In file included from /Users/runner/work/crosstool-ng/crosstool-ng/.build/arc-multilib-elf/src/gcc/gcc/gcov.cc:39:
[ALL  ]    In file included from /Users/runner/work/crosstool-ng/crosstool-ng/.build/arc-multilib-elf/src/gcc/gcc/system.h:227:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/map:2529:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:526:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/boyer_moore_searcher.h:27:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:321:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__format/formatter_bool.h:20:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__format/formatter_integral.h:32:
[ALL  ]    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/locale:202:
[ERROR]    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:550:5: error: '__abi_tag__' attribute only applies to structs, variables, functions, and namespaces
[ALL  ]        _LIBCPP_INLINE_VISIBILITY
[ALL  ]        ^
[ALL  ]    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:891:37: note: expanded from macro '_LIBCPP_INLINE_VISIBILITY'
[ALL  ]    #  define _LIBCPP_INLINE_VISIBILITY _LIBCPP_HIDE_FROM_ABI
[ALL  ]                                        ^
[ALL  ]    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:870:26: note: expanded from macro '_LIBCPP_HIDE_FROM_ABI'
[ALL  ]              __attribute__((__abi_tag__(_LIBCPP_TOSTRING(_LIBCPP_ODR_SIGNATURE))))
[ALL  ]                             ^
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/crosstool-ng/crosstool-ng/actions/runs/9036989700

### Is it regression?

macos-12

### Expected behavior

Successful build

### Actual behavior

Failed build

### Repro steps

Run CI action in crosstool-ng

**Comment by erik-bershel** [comment]
Hey @cpackham!

At the moment, I see no exact reason why these error can be associated with problems in the image. Looks more like a build issue related to incompatibility with the standard libraries shipped with `macOS-14-arm64`. Is there any way for you to test the issue on macOS-13/macOS-14-large runners?

**Comment by erik-bershel** [comment]
Hey @cpackham 
Forced to close this issue due to inactivity. If you have new information, please ping me - I will be happy to help you. Also, do not hesitate to open new issues if you find any other problems or concerns.

**Comment by joseedil** [comment]
Probably related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111632
