### ISSUE TITLE
Update Go to 1.22.3

### ISSUE THREAD

**Issue by jansepke** [actions/runner-images#9835]
### Tool name

go

### Tool license

https://github.com/golang/go/blob/master/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.22.3

### Brief description of tool

Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.

Fixes [GO-2024-2824](https://pkg.go.dev/vuln/GO-2024-2824)

### URL for tool's homepage

https://go.dev/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @jansepke! It will be updated automatically when package available in the [source-repository](https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json). I've checked it for you and may say that the required update will be published with the next image rollout.
