### ISSUE TITLE
Add Xcode 15.4

### ISSUE THREAD

**Issue by bfreiband** [actions/runner-images#9840]
### Tool name

Xcode 15.4

### Tool license

Free

### Add or update?

- [X] Add
- [X] Update

### Desired version

15.4

### Approximate size

3.17 GB

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @bfreiband!

This will be update ASAP. In progress now.

**Comment by bfreiband** [comment]
Just out of curiosity, what's generally the turnaround we aim for with new xcode versions and iOS SDKs? Just asking since WWDC season is coming up, and there will likely be a rotating cast of new xcode beta versions for a little while

**Comment by erik-bershel** [comment]
@bfreiband all the macOS-14 based agents updated.
