### ISSUE TITLE
docker-compose not found in Ubuntu 24.04

### ISSUE THREAD

**Issue by daveisfera** [actions/runner-images#9864]
### Description

`Docker Compose v2 2.27.0` is listed as available on Ubuntu 24.04 but running `docker-compose` says that it's not found

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240510.1.0

https://github.com/awresports/awresports-server/actions/runs/9105296423/job/25030858761

### Is it regression?

Yes

### Expected behavior

`docker-compose` would work on Ubuntu 24.04 like it did on Ubuntu 22.04

### Actual behavior

`docker-compose` is not found

### Repro steps

1. Run a task that uses `docker-compose`
2. Observe that it errors out after not being found

**Comment by kojoru** [comment]
`docker-compose` is a command for running Compose V1, but this image has Compose V2. Please see [the migration guide](https://docs.docker.com/compose/migrate/). In simple cases it boils down to removing the dash, i. e. running `docker compose` instead of `docker-compose`.

Compose V1 [will also be removed from other images in July](https://github.com/actions/runner-images/issues/9692).

**Comment by erik-bershel** [comment]
Hey @daveisfera!

@kojoru sent an exceptionally correct answer already. We have plans to remove Docker Compose V1 at all, and for `beta` image it was decided to do it from the start. Please update your workflows to work with the current Docker Compose V2 or install old version in runtime.

**Comment by janbrasna** [comment]
@daveisfera You're probably just observing https://docs.docker.com/compose/migrate/#how-do-i-switch-to-compose-v2 Docker Desktop doing this shim for your convenience behind the scenes…

**Comment by daveisfera** [comment]
> Hey @daveisfera!
> 
> @kojoru sent an exceptionally correct answer already. We have plans to remove Docker Compose V1 at all, and for `beta` image it was decided to do it from the start. Please update your workflows to work with the current Docker Compose V2 or install old version in runtime.

Definitely agree with removing old/deprecated software as new images become available, but @erik-bershel can you explain why it was removed from old images? Is there an official lifecycle/support document about runner images and GitHub actions?
(I was just reminded of this concern because of the [sudden breaking change that's happening with the cache action](https://github.com/actions/cache/discussions/1510))

**Comment by erik-bershel** [comment]
Hey @daveisfera!

We do not provide LTS versions of images. All images (except deprecated) are constantly changing to ensure security, quality and provide more features. We are also forced to update the content to comply with both [support policy](https://github.com/actions/runner-images?tab=readme-ov-file#software-and-image-support) and user requests.

**Comment by daveisfera** [comment]
Thanks! The support policy is the info that I'm looking for.
I'm still not clear on why removing `docker-compose` from old/existing images was the right path forward, but I guess that's water under the bridge at this point.
