### ISSUE TITLE
Helm version incomplete regex

### ISSUE THREAD

**Issue by alxmats** [actions/runner-images#9865]
### Description

`Get-HelmVersion` docs generation helper extracts incomplete Helm version.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Subsequent report generation fails `packer build` operation.
```
==> azure-arm.build_image: ToolVersionNode 'Helm' has empty version
==> azure-arm.build_image: At /imagegeneration/SoftwareReport/software-report-base/SoftwareReport.Nodes.psm1:166 char:13
==> azure-arm.build_image: +             throw "ToolVersionNode '$($this.ToolName)' has empty vers …
==> azure-arm.build_image: +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.build_image: + CategoryInfo          : OperationStopped: (ToolVersionNode 'Helm' has empty version:String) [], RuntimeException
==> azure-arm.build_image: + FullyQualifiedErrorId : ToolVersionNode 'Helm' has empty version
```

### Is it regression?

no

### Expected behavior

> helm version
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}
> $(helm version) -match 'Version:"v(?<version>\d+\.\d+\.\d+)"'
True

### Actual behavior

> helm version
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}
> $(helm version) -match 'Version:"v(?<version>\d+\.\d+\.\d+)"'
False

### Repro steps

`packer build ubuntu-22.04.pkr.hcl`

**Comment by alxmats** [comment]
`'Version:"v(?<version>\d+\.\d+\.\d+(\-[0-9A-Za-z\-\.]+)?(\+[0-9A-Za-z\-\.]+)?)"'` includes all helm releases.

**Comment by erik-bershel** [comment]
Hey @alxmats!

I'll fix it today. Thank you for bringing it to our attention.

**Comment by mikhailkoliada** [comment]
Should be fixed, please update your main branch

**Comment by mackobi** [comment]
https://jira.itergo.com/browse/TOOLCHAIN-1145
