### ISSUE TITLE
Ubuntu 22.04, GNU C++ 13.1.0 removed from image 20240514.2.1

### ISSUE THREAD

**Issue by marcalff** [actions/runner-images#9866]
### Description

This is a regression, GCC 13.1.0 was removed.

See commit:

* https://github.com/actions/runner-images/commit/072fc82c54cd23b4a2e08c42a05d22f121ec5479

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: ubuntu-22.04
  Version: 20240514.2.0

### Is it regression?

Build succeeds with:

```
  Image: ubuntu-22.04
  Version: 20240422.1.0
```
### Expected behavior

GNU C++ 13.1.0 available

### Actual behavior

GNU C++ 13.1.0 was available before, and was removed.

### Repro steps

CI build break in opentelemetry-cpp

https://github.com/open-telemetry/opentelemetry-cpp/actions/runs/9108384703/job/25039040061?pr=2669#logs

```
CMake Error at /usr/local/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  /usr/bin/gcc-13.
```

**Comment by erik-bershel** [comment]
Hey @marcalff!

It's an expected behaviour. We removed external PPA with GCC-9 and GCC-13 from the image. See there: https://github.com/actions/runner-images/issues/9679
You have two options:
- to use `beta` image Ubuntu-24.04
- to install GCC 13 in runtime

It will take about three minutes:
```yml
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install gcc-13
```

**Comment by hartwork** [comment]
@actions I've been quite happy with most of GitHub Actions so far but **dropping GCC 13 from ubuntu-22.04 images is breaking API contracts, breaking existing CI across the board** — were you really not aware of the consequences? None of these runs were suppose to fail in the first place…

- https://github.com/Libvisual/libvisual/actions/runs/9122421421/job/25083192547
- https://github.com/hartwork/antijack/actions/runs/9122426949/job/25083206150
- https://github.com/cpptest/cpptest/actions/runs/9122348253/job/25083012085
- https://github.com/rpodgorny/unionfs-fuse/actions/runs/9108374360/job/25039401128

…and now I'm forced to deal with that change in time or every new push and pull request will be red — ouch!

Please think again next time you're breaking CI for everyone, thank you.

CC @rpodgorny @kaixiong @hannob
