### ISSUE TITLE
macOS 14.2 not found on ADO pipelines on macOS 13 or macOS 14

### ISSUE THREAD

**Issue by palencharj** [actions/runner-images#9872]
### Description

When trying to use macosx14.2 SDK in macOS 13 or 14 I am getting this error:

```error
2024-05-16 17:11:39.602 xcodebuild[2807:17514] Writing error result bundle to /var/folders/9y/90rvfg4s1c5_5fzgz8497x_h0000gn/T/ResultBundle_2024-16-05_17-11-0039.xcresult
xcodebuild: error: SDK "macosx14.2" cannot be located.
```

I think is a bug in the template. 

Here is the configuration for my pipeline yml:
```yml
trigger:
- Development/Framework

pool:
  vmImage: 'macos-14'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'macosx14.2'
    xcWorkspacePath: '**/*.xcodeproj'
    scheme: 'Accessibility SDK'
```

Thank you,

John E. Palechar

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'Mac-1715878782279'
Current agent version: '3.239.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20240514.3'
Agent running as: 'runner'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: Xcode (5.238.1)
Downloading task: CmdLine (2.237.1)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = /Users/runner/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: UseGitLongPaths = true Source: $(USE_GIT_LONG_PATHS) 
   Knob: UseLatestGitVersion = true Source: $(USE_LATEST_GIT_VERSION) 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC_LOG) 
   Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
   Knob: ProcessHandlerEnableNewLogic = true Source: $(AZP_75787_ENABLE_NEW_PH_LOGIC) 
   Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
   Knob: FailJobWhenAgentDies = true Source: $(FAIL_JOB_WHEN_AGENT_DIES) 
   Knob: CheckForTaskDeprecation = true Source: $(AZP_AGENT_CHECK_FOR_TASK_DEPRECATION) 
   Knob: MountWorkspace = true Source: $(AZP_AGENT_MOUNT_WORKSPACE) 
   Knob: LogTaskNameInUserAgent = true Source: $(AZP_AGENT_LOG_TASKNAME_IN_USERAGENT) 
   Knob: UseInteropToFindParentProcess = true Source: $(AZP_AGENT_USE_INTEROP_TO_FIND_PARENT_PROCESS) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

No

### Expected behavior

I expect that the Xcode build will work and the SDK will be there. 

### Actual behavior

I get this error: 
```
2024-05-16 17:11:39.602 xcodebuild[2807:17514] Writing error result bundle to /var/folders/9y/90rvfg4s1c5_5fzgz8497x_h0000gn/T/ResultBundle_2024-16-05_17-11-0039.xcresult
xcodebuild: error: SDK "macosx14.2" cannot be located.
##[error]Error: /usr/bin/xcodebuild failed with return code: 64
```

### Repro steps

1. make a sample mac app.
2. make a sample pipeline.
3. set the 
```
pool:
    vmImage: 'macos-14'
```
4. set the
```
    sdk: 'macosx14.2'
```

**Comment by erik-bershel** [comment]
Hey @palencharj!

Default `Xcode` version for mentioned OSs is `15.0.1`. `macosx14.2` SDK is available with `Xcode` `15.1` and later. Please, configure your workflow to use newer Xcode from the software list: [macOS-13](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md), [macOS-14-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md).

**Comment by erik-bershel** [comment]
You may use something like this:
```yml
- script: |
    sudo xcode-select -s /Applications/Xcode_15.1.app
```

**Comment by palencharj** [comment]
> You may use something like this:
> 
> ```yaml
> - script: |
>     sudo xcode-select -s /Applications/Xcode_15.1.app
> ```

Thank you so much! :) 👍
