### ISSUE TITLE
apt-get don't configure to run without sudo

### ISSUE THREAD

**Issue by nagayev** [actions/runner-images#9879]
### Description

I use conan for managing C++ dependencies.
If I run it on Ubuuntu 22.04 everyone works, but on Ubuntu 24.04 I see:
`
dpkg-query: no packages found matching libva-dev
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
ERROR: vaapi/system: Error in system_requirements() method, line 38
	apt.install(["libva-dev"], update=True, check=True)
	ConanException: Command 'apt-get update' failed
`
I suppose it's because apt-get doesn't configured to work without sudo.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: ubuntu-24.04
Version: 20240516.4.0
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240516.4
```

### Is it regression?

no

### Expected behavior

Works as on Ubuntu 22.04

### Actual behavior

Doesn't works

### Repro steps

Run `apt-get install libva-dev` from action

**Comment by Alexey-Ayupov** [comment]
Hello @nagayev, We do not configure `apt-get` to work without `sudo`. Both Ubuntu-22.04 and Ubuntu-24.04 fail during execution `apt-get update` without `sudo` command. Please see screenshot below.

Please continue to use `sudo` with the commands `apt-get update` and `apt-get install`.

If you have any other questions feel free to reach us.

![image](https://github.com/actions/runner-images/assets/116575425/a747a852-b310-4e69-a325-80fea5ee0da7)
