### ISSUE TITLE
Gstreamer packages not found although part of noble

### ISSUE THREAD

**Issue by otiv-emiel-vanseveren** [actions/runner-images#9885]
### Description

Ubuntu noble comes with gstreamer packages. These are available locally on Ubuntu 24.04, but are not found when running the github actions container.

E: Unable to locate package  gstreamer1.0-plugins-base
E: Couldn't find any package by glob ' gstreamer1.0-plugins-base'
E: Couldn't find any package by regex ' gstreamer1.0-plugins-base'
E: Unable to locate package  gstreamer1.0-plugins-bad
E: Couldn't find any package by glob ' gstreamer1.0-plugins-bad'
E: Couldn't find any package by regex ' gstreamer1.0-plugins-bad'
E: Unable to locate package  gstreamer1.0-libav
E: Couldn't find any package by glob ' gstreamer1.0-libav'
E: Couldn't find any package by regex ' gstreamer1.0-libav'

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

/

### Is it regression?

unknown

### Expected behavior

It to find the packages which are currently addressed as not found.

### Actual behavior

Packages are reported as not found

### Repro steps

Run sudo apt-get update && sudo apt-get -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \ gstreamer1.0-plugins-base libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good \ gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \ gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev

(some of these install, some don't)

**Comment by erik-bershel** [comment]
Hey @otiv-emiel-vanseveren!
There is an issue with you apt-get command syntax I suppose. This worked perfectly fine for me:
```yml
      - name: Run multiline
        run: |
          sudo apt-get update
          sudo apt-get -y install libgstreamer1.0-dev 
          sudo apt-get -y install libgstreamer-plugins-base1.0-dev
          sudo apt-get -y install gstreamer1.0-plugins-base
          sudo apt-get -y install gstreamer1.0-plugins-good
          sudo apt-get -y install gstreamer1.0-plugins-bad
          sudo apt-get -y install gstreamer1.0-plugins-ugly
          sudo apt-get -y install gstreamer1.0-libav 
          sudo apt-get -y install libgstrtspserver-1.0-dev 
          sudo apt-get -y install libges-1.0-dev
```

<img width="1083" alt="Screenshot 2024-05-17 at 19 11 15" src="https://github.com/actions/runner-images/assets/110455084/afd568f4-48d2-4dd7-82b8-623960429e5f">
