### ISSUE TITLE
Signature validation for AzureCosmosDbEmulator failing on 2022 build

### ISSUE THREAD

**Issue by DevOpsAzurance** [actions/runner-images#9887]
### Description

Packer build run fails with the following:

```
==> azure-arm.image: Provisioning with powershell script: C:/a/1/AgentPacker/images/windows/templates/../scripts/build/Install-AzureCosmosDbEmulator.ps1
    azure-arm.image: Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\kfrl41cd.msi...
    azure-arm.image: Package downloaded in 2.23 seconds
==> azure-arm.image: Signature status is not valid. Status: UnknownError
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:958 char:9
==> azure-arm.image: +         throw "Signature status is not valid. Status: $($signature.St ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature statu...s: UnknownError:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature status is not valid. Status: UnknownError
==> azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.image: Step "StepProvision" failed, aborting...
```

I am using the main branch for the build:

```
WARNING: Building using main branch
Cloning into 'C:\a\1\AgentPacker'...
main
WARNING:  Branch:  main
WARNING:  SHA:     4abf97ab13928c4731cb243a72225c55436832fc
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current agent version: '3.238.0'
Current image version: '1.0.2'

### Is it regression?

NA

### Expected behavior

Runs the thumbprint verification successfully. 

### Actual behavior

Fails to validate installer of CosmosDB.

### Repro steps

packer build run on the Windows 2022 template.

**Comment by erik-bershel** [comment]
Hey @DevOpsAzurance!

It's in progress here: https://github.com/actions/runner-images/pull/9875

**Comment by mikhailkoliada** [comment]
fixed, please sync your main.
