### ISSUE TITLE
Chocolatey installation fails due to thumbprint mismatch

### ISSUE THREAD

**Issue by jhennessey** [actions/runner-images#9890]
### Description

The chocolatey installation script (at https://chocolatey.org/install.ps1) was recently signed with a new certificate (appears to have occurred on 5/17/2024). Therefore, the thumbprint check now fails when attempting to install chocolatey.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Issue is not in any released image as it is a build issue

### Is it regression?

No

### Expected behavior

Chocolatey installs successfully when building the Windows images

### Actual behavior

Chocolatey fails to install when building the Windows images with the following message: `Signature thumbprint do not match expected.`

### Repro steps

Attempting to build any of the Windows images will error out when attempting to install chocolatey.

**Comment by erik-bershel** [comment]
Hey @jhennessey!

Thank you for your effort. Very good example of the first issue for our repo. Should wait for test run before merging PR.

**Comment by mikhailkoliada** [comment]
fixed now, please sync your main!
