### ISSUE TITLE
libyaml-dev is missing on ubuntu-24.04

### ISSUE THREAD

**Issue by eregon** [actions/runner-images#9895]
### Description

libyaml-dev is missing on ubuntu-24.04, but is present on all other ubuntu versions, since https://github.com/actions/runner-images/issues/6725.
The same reasons as in that issue still apply.
It's also causing for instance https://github.com/ruby/setup-ruby/actions/runs/9148517485/job/25151153737?pr=596 to fail.

Could you install it on ubuntu-24.04 and also check it's part of the package list for future ubuntu versions?

Related: https://github.com/ruby/setup-ruby/issues/595

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240516.4.0
https://github.com/ruby/setup-ruby/actions/runs/9148517485/job/25151153737?pr=596

### Is it regression?

Yes compared to Ubuntu 22.04

### Expected behavior

It's installed

### Actual behavior

It's not installed

### Repro steps

setup-ruby with ruby-version: truffleruby+graalvm on 24.04

**Comment by MaksimZhukov** [comment]
Hello @eregon!
Thank you for reporting this! We will add it to the ubuntu-24.04 runners
