### ISSUE TITLE
configure-apt.sh - is_ubuntu24 not found

### ISSUE THREAD

**Issue by JT-Dingo** [actions/runner-images#9902]
### Description

Non-terminating error found in configure-apt.sh since the introduction of Ubuntu 24 into the scripts. 

`2024/05/21 12:38:28 ui error: [1;31m==> amazon-ebs.build_image: /tmp/script_5264.sh: line 45: is_ubuntu24: command not found[0m`

From what I see, the os.sh helper script needs to be sourced into the script at the top so the `is_ubuntu24` function is brought in but that's not present.

The placement of configure-apt.sh and it's mock in the Packer template would also need to be updated in the Ubuntu templates to after the helper file provisioner. 

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Currently in Main branch of the runner-images repo. 

### Is it regression?

Yes, this issue was introduced with the introduction of Ubuntu 24. 

### Expected behavior

Configure-apt.sh should complete successfully. 

### Actual behavior

Configure-apt.sh fails with `is_ubuntu24` not found as the os.sh helper script isn't sourced in. 

### Repro steps

* Set up build of the new Runner Images main branch
* Configure-apt.sh fails during build, does not cause the build to terminate

**Comment by mikhailkoliada** [comment]
fixed, please sync your main
