### ISSUE TITLE
CI/CD Broken After Ubuntu Runner Image Upgrade

### ISSUE THREAD

**Issue by satishmscict** [actions/runner-images#9913]
### Description

CICD workflow is broken after the runner image of Ubuntu `22.04` was upgraded from `20240422.1` to `20240516.1`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
  Version: 20240516.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240516.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240516.1

### Is it regression?

Yes,  Image: ubuntu-22.04   Version: 20240422.1.0   Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240422.1/images/ubuntu/Ubuntu2204-Readme.md   Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240422.1

### Expected behavior

A unit test should be pass be passed without error.

### Actual behavior

Traceback (most recent call last):
  File "/usr/bin/extractReport.py", line 51, in <module>
    main()
  File "/usr/bin/extractReport.py", line 48, in main
    parseXML(path)
  File "/usr/bin/extractReport.py", line 37, in parseXML
    print(message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u[25](https://github.com/xxx/xxx/actions/runs/9186097332/job/25261188735#step:10:26)bc' in position 47: ordinal not in range(128)
./modules/authentication-auth0/build/test-results/testDebugUnitTest/TEST-com.xxx.authentication.auth0.Auth0WrapperTest.xml

### Repro steps

Actual code:
```
 override fun generateRsaKeyPair(): KeyPair = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_RSA).let { keyPairGenerator ->
        keyPairGenerator.initialize(KEY_SIZE_IN_BITS_FOR_RSA, SecureRandom())
        keyPairGenerator.genKeyPair()
    }
```

Unit test code. Android + Kotlin dsl + Strikt

 ```
@Test
    fun `Generate RSA key pair`() {
        val rsaKeyPair = with(CryptographyImpl()) {
            generateRsaKeyPair()
        }

        expectThat(rsaKeyPair.private.algorithm).isEqualTo("RSA")
        expectThat(rsaKeyPair.private.toString()).startsWith("SunRsaSign RSA private CRT key, 4096 bits")
    }
```

**Comment by sergei-pyshnoi** [comment]
Hello @satishmscict . It looks like the problem is an unsupported ascii character. In your case it is ▼. This behavior is independent of the version of runner-images. Unfortunately we can't do anything from our side.
