### ISSUE TITLE
Windows runners listen on port 80 by System (PID=4)

### ISSUE THREAD

**Issue by nyurik** [actions/runner-images#9915]
### Description

Running `netstat -ano` on both Windows 2019 and 2022 runners show many listening ports including 

```
Active Connections
  Proto  Local Address          Foreign Address        State           PID
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       4
```

PID is System.  This conflicts with nginx and apache configuration as specified in the docs page.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

  Image: windows-2022
  Version: 20240514.3.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240514.3/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240514.3

### Is it regression?

maybe

### Expected behavior

port 80 should not be used, or the default port of nginx and apache services should be set to some other port by default

### Actual behavior

port is used

### Repro steps

Run `netstat -ano`

**Comment by kishorekumar-anchala** [comment]
Hi @nyurik , 

kindly update your project confirmation  file with different port numbers and try to re-produce .

**Comment by ijunaidm** [comment]
@nyurik - Can you please update your project configuration file with different port number and try to re-build it.

**Comment by nyurik** [comment]
@ijunaidm I don't think I understand.  NGINX as installed right now on VM does not seem to be able to start "AS IS" - I had to modify the conf file as part of my new [action-setup-nginx](https://github.com/nyurik/action-setup-nginx). Port 80 seems to be used by Windows itself.

**Comment by ijunaidm** [comment]
@nyurik - Default port 80 is being used by Windows IIS service . Probably we can't able to change default ports for the services running on the image. 
Please update/change your port number in your configuration file.
