### ISSUE TITLE
MS Build Version on ubuntu 22.04

### ISSUE THREAD

**Issue by martinwurst1** [actions/runner-images#9927]
### Description

The MSBuild Version on the Ubuntu 22.04 agent is 16.10.1.31701, which cannot be used for .net8 projects. The agent needs the updated version (17.9.34511.75). 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

no public link available

### Is it regression?

no

### Expected behavior

The agent should contain the latest MsBuild version.

### Actual behavior

The agent contains an outdated MsBuild version.

### Repro steps

In a azure devops pipeline execute a nuget restore with the NuGetCommand@2 command. It fails with the error:
 "Version 8.0.300 of the .NET SDK requires at least version 17.8.3 of MSBuild. The current available version of MSBuild is 16.10.1.31701. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available."

**Comment by vidyasagarnimmagaddi** [comment]
hi @martinwurst1  , could you please try to run your pipeline with Visual Studio 2022 or latest at MSBuild task in the pipeline. The latest announcement says : "MSBuild 17.0 shipped with Visual Studio 2022 and .NET 6.0." 
[Reference](https://github.com/dotnet/msbuild/releases/tag/v17.0.0)

**Comment by ijunaidm** [comment]
@martinwurst1 - Can you please confirm once you run the pipeline with Visual studio 2022 or latest version at MS build task, if it is working for you or not.

**Comment by JohanKlijn** [comment]
@vidyasagarnimmagaddi : you are saying "could you please try to run your pipeline with Visual Studio 2022 or latest at MSBuild task in the pipeline.". How would you install this on a Microsoft hosted agent? Is there any task to install the latest MSBuild?

@ijunaidm : why is this task closed, because if I look at https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md MSBuild 16.10.1.31701 is still installed on the Ubuntu 22.04  image runner. Shouldn't version 17.x be installed? For example I am running a "Microsoft.NET.Sdk.Worker" project (background service based on the the [worker template](https://learn.microsoft.com/en-us/dotnet/core/extensions/workers).) on a Microsoft Hosted Agent and I get the error message "Version 8.0.302 of the .NET SDK requires at least version 17.8.3 of MSBuild."

**Comment by holajan** [comment]
I have the same problem. There is not MSBuild v. 17 needed for NET 8 in Ubuntu 22.04 or Ubuntu 24.04 image. Please reopen this issue and fix it.

**Comment by 1sourcelead** [comment]
Same issue here, why this PR is closed ?

**Comment by dostoievsky** [comment]
It seems that the version of the package itself has been halted also in registries. As the OP itself has questioned:

> hi @martinwurst1 , could you please try to run your pipeline with Visual Studio 2022 or latest at MSBuild task in the pipeline. The latest announcement says : "MSBuild 17.0 shipped with Visual Studio 2022 and .NET 6.0." [Reference](https://github.com/dotnet/msbuild/releases/tag/v17.0.0)

what it seems to be proposed a solution it is not quite like reality.

**Comment by holajan** [comment]
I now try building on Ubuntu image version: **20241117.1.0** where is **.NET Core SDK: 8.0.404** with **MSBuild version 17.11.9**.
I have .csproj with Sdk="Microsoft.NET.Sdk.Worker" and build passed without errors, so it looks like the issue has been fixed and the error message about the MSBuild version is no longer there.

**Comment by BalassaMarton** [comment]
> I now try building on Ubuntu image version: **20241117.1.0** where is **.NET Core SDK: 8.0.404** with **MSBuild version 17.11.9**. I have .csproj with Sdk="Microsoft.NET.Sdk.Worker" and build passed without errors, so it looks like the issue has been fixed and the error message about the MSBuild version is no longer there.

Did that work?
