### ISSUE TITLE
tree is missing on ubuntu-24.04

### ISSUE THREAD

**Issue by kachick** [actions/runner-images#9935]
### Description

tree command is missing on ubuntu-24.04, but it is present on ubuntu-22.04 and ubuntu-20.04.  
Is this an intentional change?

* tree is not listed in [Installed Software](https://github.com/actions/runner-images/blob/ed92ac6e3ff66f090ff7527f5e9c104993653d09/images/ubuntu/Ubuntu2404-Readme.md).
* I agree, "tree" is not a vital package.

related issue: https://github.com/actions/runner-images/issues/9848

## Workaround

Adding this step resolved my problem but added a few seconds to complete runs.

```yaml
      - name: Install tree command
        run: sudo apt-get install --no-install-recommends --assume-yes tree
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Image: ubuntu-24.04
  Version: 20240516.4.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20240516.4/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240516.4
```

---

* https://github.com/kachick/example-tree-ubuntu-24.04-runner-image/blob/30b9f514581467a58d0ac2afd9ff5d59c7c2d000/.github/workflows/tree.yml
* https://github.com/kachick/example-tree-ubuntu-24.04-runner-image/actions/runs/9249889143/job/25442442519

### Is it regression?

https://github.com/kachick/example-tree-ubuntu-24.04-runner-image/actions/runs/9249889143/job/25442442678

### Expected behavior

I can use tree command in ubuntu runner by default.

### Actual behavior

tree command is missing. I need to install it with apt-get.

### Repro steps

      - name: Inspect depednency
        run: |
          command -v tree
          tree --version
      - run: tree

**Comment by Alexey-Ayupov** [comment]
Hello @kachick, the `tree` is added. Will be deployed soon.

**Comment by kachick** [comment]
Thank you! 🙏
