### ISSUE TITLE
Ubuntu 24.04 actions killed after 4 minutes

### ISSUE THREAD

**Issue by daveisfera** [actions/runner-images#9960]
### Description

Yesterday, our actions that use Ubuntu 24.04 started being killed if they ran for more than 4 minutes. We reverted the build to use 22.04 and they completed, so it appears to be something specific to those runners

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.316.1'
Runner Image
  Image: ubuntu-24.04
  Version: 20240516.4.0
```

### Is it regression?

Yes, started yesterday and the successful builds have the same version info

### Expected behavior

Build run to completion and aren't cancelled after 4 minutes

### Actual behavior

All builds using Ubuntu 24.04 are cancelled after 4 minutes

### Repro steps

With 24.04 and it was killed after 4 minutes:
https://github.com/awresports/awresports-server/actions/runs/9292154743

With 22.04 and it finished:
https://github.com/awresports/awresports-server/actions/runs/9292165631

**Comment by marcalff** [comment]
Same report for repository opentelemetry-cpp.

* https://github.com/open-telemetry/opentelemetry-cpp

**Comment by Piedone** [comment]
Seems to be the duplicate of: https://github.com/actions/runner-images/issues/9959.

**Comment by daveisfera** [comment]
Agreed that it's a duplicate
