### ISSUE TITLE
vcpkg+boost libraries hash mismatch

### ISSUE THREAD

**Issue by SimenZhor** [actions/runner-images#9961]
### Description

Hi,

Boost developers recently had to change some tags on the release that is included in the vcpkg version shipped with the current Azure DevOps agents for Windows and Ubuntu (I have not tested other platforms). This change caused a mismatch between the expected hash and the downloaded dependency, causing builds to fail. The issue has already been addressed by vcpkg, but the runner agents need to update to a version after this fix was implemented.

Relevant vcpkg PR: https://github.com/microsoft/vcpkg/pull/38979
Relevant mail thread between boost devs: https://lists.boost.org/Archives/boost/2024/05/256902.php (https://lists.boost.org/Archives/boost/2024/05/256896.php)

Relevant output:
```
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
```

Full output for this specific package:
```
Installing 13/17 boost-core:x64-windows@1.85.0...
Building boost-core:x64-windows@1.85.0...
-- Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz -> boostorg-core-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
[DEBUG] Trying to hash C:\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.1268.part
[DEBUG] C:\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.1268.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: C:\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.1268.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997): 
[DEBUG] Time in subprocesses: 281346us
[DEBUG] Time in parsing JSON: 25us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1810us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.6 s (909017us)
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

-

### Expected behavior

vcpkg downloads and builds dependencies

### Actual behavior

vcpkg downloads dependencies but the has does not match what it expects, so the build stops.

### Repro steps

Use vcpkg and depend on any boost library.

**Comment by wbasheer** [comment]
I am also getting this error:

Installing 1/58 boost-core:x64-windows@1.85.0#1...
Building boost-core:x64-windows@1.85.0#1...
-- Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz -> boostorg-core-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\******\vcpkg-master\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\*********\vcpkg-master\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
[DEBUG] Trying to hash C:\Users\*******\vcpkg-master\downloads\boostorg-core-boost-1.85.0.tar.gz.26008.part
[DEBUG] C:\Users\********\vcpkg-master\downloads\boostorg-core-boost-1.85.0.tar.gz.26008.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: C:\Users\J58548\vcpkg-master\downloads\boostorg-core-boost-1.85.0.tar.gz.26008.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 7us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 6257us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 879 ms (789165us)

**Comment by ijunaidm** [comment]
We are looking into this issue, we will update on this issue after investigating the error you have faced.

**Comment by Alexey-Ayupov** [comment]
Hello @wbasheer, this is not the image related issue, please raise the issue to the https://github.com/microsoft/vcpkg/issues repo.

If you have any other questions feel free to reach us.

**Comment by SimenZhor** [comment]
Hi @Alexey-Ayupov, 
was the original problem that was reported by me fixed? I can't see any PRs related to using a newer vcpkg build in the list of completed PRs and no PR that has referred to this issue.

**Comment by SimenZhor** [comment]
I'm sorry if I didn't make myself clear, but the problem I'm reporting has already been fixed in vcpkg. This issue is related to the image, since the image is still including a broken version of vcpkg.

**Comment by wbasheer** [comment]
@Alexey-Ayupov , I didn't realize that this was not the vcpkg project page.  @SimenZhor , this issue has been reported on the vcpkg github page:
https://github.com/microsoft/vcpkg/issues/38974

**Comment by SimenZhor** [comment]
@wbasheer I know. I listed that issue in my first message.
@Alexey-Ayupov, @ijunaidm, I think this issue was incorrectly marked as "closed" for being unrelated to this repository. Please consider reopening it. The Azure pipeline images are still not working due to shipping with a broken version of vcpkg.

**Comment by SimenZhor** [comment]
According to the changelog PR #9989 will fix this issue:

<html><body>
<h3 dir="auto">Updated</h3>

Category | Tool name | Previous (20240526.1.0) | Current (20240603.1.1)
-- | -- | -- | --
Package Management | Vcpkg | (build from commit 01f602195) | (build from commit 67cc1677c)


</body>
</html>

Commit of previous version: 01f6021 (May 25, 2024)
Commit fixing hash issue: a8954b9 (May 29, 2024)
Commit of new version: 67cc167 (Jun 3, 2024)
