### ISSUE TITLE
Chocolatey Download signature Incorrect on Windows 2022 image

### ISSUE THREAD

**Issue by JWHolding** [actions/runner-images#9970]
### Description

The fix for chocolatey download has included in #9876 / #9891  was not included in the most recent windows 2022 release / tag. Any chance you could produce a new version?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Win22/20240514.3

### Is it regression?

No

### Expected behavior

Chocolatey installs successfully when building the Windows images

### Actual behavior

Chocolatey fails to install when building the Windows images with the following message: Signature thumbprint do not match expected.

### Repro steps

Attempting to build Windows 2022 image will error out when attempting to install chocolatey.

**Comment by kishorekumar-anchala** [comment]
Hi @JWHolding , 

Please provide us with repro steps for further investigation. It would be great if you could provide us with error logs.

**Comment by ymerej** [comment]
I get the same error.

```
"stderr_lines": ["Signature thumbprint do not match expected.", "At C:\\Program Files\\WindowsPowerShell\\Modules\\ImageHelpers\\InstallHelpers.ps1:972 char:9", "+
         throw \"Signature thumbprint do not match expected.\"", "+
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException", "    + FullyQualifiedErrorId : Signature thumbprint do not match expected.", " "]
```
         
The signature is on line 16 of Install-Chocolatey.ps1.

I don't know if this is relevant, but on the [Chocolatey security page](https://docs.chocolatey.org/en-us/information/security#chocolatey-binaries-and-the-chocolatey-package) it mentions the signature and that it is not valid after May 1st.

**Comment by kishorekumar-anchala** [comment]
Hi @ymerej , 

  we are unable to re-produce the error, we are requesting you , fork the latest main branch into your local and retry and kindly check the thumbprint value in the logs and script both are match ?

**Comment by JWHolding** [comment]
Hi @kishorekumar-anchala, the fix / PR that I mentioned has been merged into main, and I believe an new release was created for Server 2019 which consumes the fix.  But the issue also affected Server 2022 but no new release was created for it, and we depend on the release tags for version pining.

**Comment by Alexey-Ayupov** [comment]
Hello @JWHolding, it is better to build images from the main branch only, please read the faq section https://github.com/actions/runner-images?tab=readme-ov-file#faqs.

If you have any other questions feel free to reach us.

**Comment by ymerej** [comment]
> Hi @ymerej ,
> 
> we are unable to re-produce the error, we are requesting you , fork the latest main branch into your local and retry and kindly check the thumbprint value in the logs and script both are match ?

Using the `main` branch fixed my issue.  Thank you for the suggestions everyone!
