### ISSUE TITLE
Add Firefox and geckodriver to ARM versions of MacOS 13 and 14

### ISSUE THREAD

**Issue by whimboo** [actions/runner-images#9974]
### Description

Using the runner images for MacOS 13 and 14 for ARM64 doesn't include Firefox and geckodriver anymore, and requires users to manually install the applications. Out of curiosity was there a reason why it is no longer part of these runner images? Over on https://github.com/actions/runner-images/issues/349 both Firefox and geckodriver were added to all existing images at that time.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240526.2

### Is it regression?

MacOS 12/13 (non ARM)

### Expected behavior

Both Firefox and geckodriver should be available by default.

### Actual behavior

Firefox and geckodriver are no longer installed by default:

https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md#browsers
https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#browsers

### Repro steps

Just check the installed software to verify that both applications are missing.

**Comment by Alexey-Ayupov** [comment]
Hello @whimboo, we will take a look.

**Comment by whimboo** [comment]
What I actually missed to reference is that we currently face an issue with Firefox running on these ARM images. There is https://bugzilla.mozilla.org/show_bug.cgi?id=1893921 filed for investigation.

Due to some reason it takes quite some time for new content processes to launch, which we cannot reproduce locally on our own ARM based MacBooks. In case you know what might be special to your runners we would appreciate some feedback. Thanks.

**Comment by erik-bershel** [comment]
Hey @whimboo!

Those tools might be installed in runtime in less than a minute with the next code:

```yml
    steps:
      - name: Run multiline
        run: |
          brew install --cask firefox
          brew install geckodriver
```

We are working to make images smaller and easier to maintain and so trying not to add tools to the image that can be quickly installed on the fly. The decision regarding this browser and its driver may be reconsidered in the future.

**Comment by whimboo** [comment]
@erik-bershel thanks a lot! Quick follow-up question through... Shall I file a new issue regarding my comment https://github.com/actions/runner-images/issues/9974#issuecomment-2144831935 so that we can get this investigated? We would at least be interested which kind of machine configuration you have that might trigger a hang in some native MacOS code when Firefox creates new web content processes.

**Comment by erik-bershel** [comment]
@whimboo unfortunately we do not investigate resources related issues. Regarding configuration I may say that it's not a private info: runner is a virtual machine based on Veertu Anka with the following [set of resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories). If you provide more info regarding bottleneck we may investigate possibility to workaround it in our environment.
I suppose that the root cause may be placed in the issue with Apple's virtualisation framework limitations which is the reason of almost any of unexpected productivity issues.

**Comment by whimboo** [comment]
Thanks. We will investigate and will get back to you when we have more information.

**Comment by erik-bershel** [comment]
@whimboo sure. Feel free to open the issue with the new information. We'll try to help at least.

**Comment by juliandescottes** [comment]
@erik-bershel hi, I'm also investigating the issue on the Firefox side, is there any way we can get the images of the VMs used here? That would probably help our investigation. Thanks!

**Comment by erik-bershel** [comment]
Hey @juliandescottes I’m very sorry to upset you, but these particular images are not public. I keep an eye on the bug ticket from time to time - I saw that you have come quite a long way. If you see any steps that might help you, feel free to ping me.

**Comment by whimboo** [comment]
FYI one of our Mac platform engineers can actually reproduce in a VM. So he will investigate the problem. Lets hope that it is the same underlying issue.

**Comment by whimboo** [comment]
> FYI one of our Mac platform engineers can actually reproduce in a VM. So he will investigate the problem. Lets hope that it is the same underlying issue.

We were able to fix this problem completely on our side. With today's Nightly build of Firefox the 5s delay when creating a new content process is no longer present. That means that Firefox now also works correctly on the ARM runners.
