### ISSUE TITLE
Directory c++ is not existing in Command Line Tools of the latest MacOS version

### ISSUE THREAD

**Issue by SakuragiHnmch** [actions/runner-images#9976]
### Description

There supposed to be a directory `c++` which located in `/Library/Developer/CommandLineTools/usr/include`, but I cannot find it when running my actions.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I have tried to update the command line tools, but it did not work.

Here is one of the failed [link](https://github.com/SakuragiHnmch/Explosion/actions/runs/9352449047/job/25740630558) (In step: Install Xcode CommandLine Tool)

### Is it regression?

no

### Expected behavior

There supposed to be a directory `c++` which located in `/Library/Developer/CommandLineTools/usr/include`

### Actual behavior

 Directory `c++` is not existing in `/Library/Developer/CommandLineTools/usr/include`.

### Repro steps

When actions runs on `macos-latest`, we cannnot find directory `c++` in `/Library/Developer/CommandLineTools/usr/include`

**Comment by erik-bershel** [comment]
Hey @SakuragiHnmch!

> There supposed to be a directory c++ which located in /Library/Developer/CommandLineTools/usr/include

Not exactly. It's not a default behaviour anymore for `macOS-14` and you should handle it by your own. By default there is only `swift` directory, and you should create a link to the `c++` if you wish to continue to use it the old way.

You may find some `include/c++` in one of the SDKs folders:
`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` which is link to `14.latest` `SDK`
or
`/Library/Developer/CommandLineTools/SDKs/MacOSX${version}.sdk/usr/include` where $version = { 12, 13, 14 }

But I have no idea how appropriate for your project those `include/c++/v1` are.

**Comment by SakuragiHnmch** [comment]
Oh! I got it, thanks for yout reply.
