### ISSUE TITLE
Update GCC to 13.1 (MinGW) on windows runners

### ISSUE THREAD

**Issue by SylvainCorlay** [actions/runner-images#9981]
### Tool name

Mingw

### Tool license

GPL

### Add or update?

- [ ] Add
- [X] Update

### Desired version

13.1

### Brief description of tool

Please update GCC to Version 13 on the windows runner 🙏 

### Platforms where you need the tool

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by vidyasagarnimmagaddi** [comment]
Hey @SylvainCorlay Due maintenance concerns we are  not ready to upgrade mingw for windows images, because that could  cause huge impact for other users. I am closing this tread but we will continue track similar issues for possible changing in decision.Thanks
