### ISSUE TITLE
macos-{13,14} produce corrupt artefacts

### ISSUE THREAD

**Issue by panekj** [actions/runner-images#9995]
### Description

(I apologise for mixing terminology here and there, it's unfortunate how we ended up with such things, tl;dr: `arm64` == `aarch64` == `Apple Silicon` == `M3`/`M2`/`M1` ||| `x86` == `x86-64` == `Apple Intel`)

Project technology tl;dr: Rust, C, C++, Cocoa, OpenGL
Trying to upgrade from `macos-11` runner (since it will be removed soon) to `macos-latest` we noticed that artefacts produced are crashing instantly on Apple devices that are using Apple Silicon (arm64); Apple devices with Intel seem unaffected.
After hours of trying out various things, this is the state:
- Builds done on `macos-13` (Intel x86 64bit) and `macos-14` (Apple M1 arm64) produce a valid x86 and an invalid arm64 artefact. Resultant artefacts were tested on an M3 device with macOS 14.5
  - `macos-14`: (cross-)compiling from `aarch64-apple-darwin` host to `x86_64-apple-darwin` and `aarch64-apple-darwin` target, both artefacts are put together as "Universal" build (x86+arm64)
    - `x86-64`: (untested but shouldn't be relevant much due to result from `macos-13`)
    - `aarch64`: build doesn't work on M3
    - build run: https://github.com/lapce/lapce/actions/runs/9363759508
  - `macos-13`: (cross-)compiling from `x86_64-apple-darwin` host to `x86_64-apple-darwin` and `aarch64-apple-darwin` target
    - `x86-64`: works fine on Apple Intel (macOS 14.2)
    - `aarch64`: build doesn't work on Apple M3 (macOS 14.5) nor Apple M2 (macOS 14.2)
    - build run: https://github.com/lapce/lapce/actions/runs/9364976535
  - `macos-12` & `macos-11`: (cross-)compiling from `x86_64-apple-darwin` host to `x86_64-apple-darwin` and `aarch64-apple-darwin` target
    - produced build works on all targets
    - `macos-11`: https://github.com/lapce/lapce/actions/runs/9372643494/job/25804569889
    - `macos-12`: https://github.com/lapce/lapce/actions/runs/9372643494/job/25804569668
  - Local build with Apple M3 (macOS 14.5 ; Xcode 15.4) produces a valid working builds for `arm64` targets
    - uploaded manually to https://github.com/lapce/lapce/releases/download/nightly/Lapce.dmg
 
This was re-tested few times today by splitting builds, changing various configurations such as macOS version and `MACOSX_DEPLOYMENT_TARGET` which yielded no improvement.
Given that we are able to build it locally with recent macOS and recent Xcode version and it doesn't crash makes it somehow related to GitHub Actions (current) environment.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

<details>
<summary>macos-14</summary>

https://github.com/lapce/lapce/actions/runs/9363759508/job/25775246702

```
 Current runner version: '2.316.1'
Operating System
  macOS
  14.5
  23F79
Runner Image
  Image: macos-14-arm64
  Version: 20240526.2
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240526.2/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240526.2

```

</details>

<details>
<summary>macos-13</summary>

https://github.com/lapce/lapce/actions/runs/9342129138/job/25709758588

```
 Current runner version: '2.316.1'
Operating System
  macOS
  13.6.7
  22G720
Runner Image
  Image: macos-13
  Version: 20240526.1
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20240526.1/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240526.1
```

</details>

<details>
<summary>macos-12</summary>

https://github.com/lapce/lapce/actions/runs/9372643494/job/25804569668

```
 Current runner version: '2.316.1'
Operating System
  macOS
  12.7.5
  21H1222
Runner Image
  Image: macos-12
  Version: 20240527.4
  Included Software: https://github.com/actions/runner-images/blob/macos-12/20240527.4/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-12%2F20240527.4

```

</details>

<details>
<summary>macos-11</summary>

https://github.com/lapce/lapce/actions/runs/9372643494/job/25804569889

```
 Current runner version: '2.316.1'
Operating System
  macOS
  11.7.10
  20G1427
Runner Image
  Image: macos-11
  Version: 20240127.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-11/20240127.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20240127.1
```

</details>

### Is it regression?

Yes, but on macos-{13,14}

### Expected behavior

Compiled artefacts are not crashing

### Actual behavior

When trying to run builds from `macos-13` or `macos-14` on arm64 device
```
[1]    5059 illegal hardware instruction  /Applications/Lapce.app/Contents/MacOS/lapce -w
```

### Repro steps

Reproducing runtime failure:
1. Download https://github.com/lapce/lapce/releases/download/nightly/Lapce-macos.dmg and run on arm64 apple device

Reproducing miscompilation:
1. You can copy https://github.com/lapce/lapce/pull/3305 and uncomment `macos-13` in matrix ; I doubt we will be able to provide a smaller repro case

**Comment by erik-bershel** [comment]
Hey @panekj!
We'll try to figure out whats going on there.

**Comment by EmilDohne** [comment]
@panekj To add to this I had similar experiences with XCode 15.0.1 which would produce linker errors and ive since bumped up my XCode version to 15.1+

Heres the relevant bugfix excerpt in the XCode 15.1 release:

```
Fixed: Binaries using symbols with a weak definition crash at runtime on iOS 14/macOS 12 or older. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650) (FB13097713)
```

I would in general propose to raise it from 15.0.1 as in my experience 15.0.1 is unusable for cpp

**Comment by erik-bershel** [comment]
Hey @EmilDohne!

> I would in general propose to raise it from 15.0.1 as in my experience 15.0.1 is unusable for cpp

Will take a look on usage statistics, might worth updating really.

**Comment by erik-bershel** [comment]
Hey @panekj and @EmilDohne!

Yes, there is a certain point in updating `Xcode` by default to the latest version for `macOS-13` and to a similar one on `macOS-14`. The most used are the latest releases. We'll get into that soon after some additional testing.

**Comment by erik-bershel** [comment]
Hey there!
We are going to update default `Xcode` both for `macOS-13` and `macOS-14` based images soon. Keep an eye on the `Announcement`'s
