### ISSUE TITLE
Ubuntu 24.04 image self cancels the build if you install the wrong package

### ISSUE THREAD

**Issue by randombit** [actions/runner-images#9996]
### Description

Installing certain packages causes apt to try to restart services; when this happens, the build is cancelled.

This is not isolated; several people have (incorrectly) reported this in https://github.com/actions/runner-images/issues/9959 if you check the last 3-4 comments it's people hitting this issue, *not* the 4 minute timeout which was the original report.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`apt-get install valgrind`: https://github.com/randombit/botan/actions/runs/9374504770/job/25810702531?pr=4098

`apt-get install g++-multilib linux-libc-dev libc6-dev-i386`: https://github.com/randombit/botan/actions/runs/9374504770/job/25810703776?pr=4098

### Is it regression?

Works in 22.04

### Expected behavior

The build runs rather than self-cancelling

### Actual behavior

This appears in the log

```
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...

Running kernel seems to be up-to-date.

Restarting services...
 systemctl restart chrony.service containerd.service cron.service haveged.service hv-kvp-daemon.service multipathd.service packagekit.service php8.3-fpm.service polkit.service rsyslog.service runner-provisioner.service systemd-journald.service systemd-networkd.service systemd-resolved.service systemd-udevd.service udisks2.service walinuxagent.service
Error: The operation was canceled.
```

Then the job is cancelled.

### Repro steps

Perform somewhere in your CI scripts

```
apt-get update
apt-get install valgrind
```

Other packages also work, it just needs to be something that will pull in an update which then cause apt to try to restart services.

**Comment by randombit** [comment]
`export NEEDRESTART_MODE=l`

will cause apt to skip the automatic service restarts, allowing the build to continue

**Comment by sergei-pyshnoi** [comment]
duplicate https://github.com/actions/runner-images/issues/9937
